na calda di acciughe disciolte nell''olio con succo di limone.',4212);
INSERT INTO "ricette" VALUES (25827,'Tonno Ai Ferri','Pesce','Tonno',4,' -','4 Fette Tonno Fresco (fette Di 150 G Ognuna),
8 Pomodori Perini,
1 Spicchio Aglio,
2 Fettine Cipolla,
12 Foglie Basilico,
1/2 Bicchiere Olio D''oliva,
Sale','Tritare i pomodori spellati e privati dei semi con il basilico, l''aglio e la cipolla. Salare il trito e condirlo con l''olio. Cuocere alla griglia le fette di tonno, salarle leggermente, disporle sui piatti individuali e coprirle con il trito di pomodoro. Servire subito.',2375);
INSERT INTO "ricette" VALUES (25828,'Tonno Ai Ferri (2)','Pesce','Tonno',4,' -','4 Fette Tonno Fresco (fette Da 200 G),
8 Pomodori Perini,
1 Spicchio Aglio,
2 Fettine Cipolla,
12 Foglie Basilico,
1/2 Bicchiere Olio D''oliva,
Sale','Spellare i pomodori e tritarli con la cipolla, l''aglio e il basilico. Salare e unire l''olio. Cuocere le fette di tonno sulla griglia per 15 minuti rigirandole un paio di volte. Disporle su un piatto da portata, ricoprirle con la salsa e servire subito.',1927);
INSERT INTO "ricette" VALUES (25829,'Tonno Al Finocchio','Pesce','Tonno',4,' -','4 Fette Tonno,
1 Cucchiaio Semi Di Finocchio,
Sale,
Pepe,
Olio D''oliva','Ridurre in polvere i semi di finocchio, quindi aggiungere sale e pepe. Cospargere con il ricavato le fette di tonno da entrambi i lati. Mettere sul fuoco una padella con l''olio e cuocerle quando l''olio sarà molto caldo, rigirandole con delicatezza per evitare di romperle.',1806);
INSERT INTO "ricette" VALUES (25830,'Tonno Al Forno','Pesce','Tonno',4,' -','1 Confezione Melanzane Grigliate,
400 G Tonno A Fette Sottili,
Basilico,
Aglio,
30 G Formaggio Pecorino Grattugiato,
Capperi,
Peperoncino,
Yogurth,
Pomodori','Foderare il fondo di una teglia antiaderente unta di olio con le melanzane. Cospargere con basilico, pecorino, disporre le fette di tonno e coprirle con le melanzane. Cuocere in forno caldo per 20 minuti. Servire molto caldo con una salsa preparata frullando insieme capperi, aglio, basilico, peperoncino, yogurth e pomodori.',1326);
INSERT INTO "ricette" VALUES (25831,'Tonno Al Sedano','Pesce','Tonno Fresco',4,' -','900 G Tonno Fresco,
50 G Olive Nere,
4 Pomodori,
Alcune Foglie Basilico,
1 Costa Sedano,
2 Cucchiai Olio D''oliva,
1 Noce Burro,
Peperoncino,
Sale,
Pepe','Tagliate a pezzetti una costa di sedano. Scottate i pomodori, spellateli, eliminate i semi e tagliateli a cubetti. Fate scaldare in un tegame due cucchiai d''olio e una noce di burro, rosolatevi il tonno diviso a pezzi regolari. Aggiungete i pomodori, alcune foglie di basilico spezzettato, un po'' di peperoncino, il sedano. Salate e pepate. Coprite e cuocete mezz''ora a fuoco moderato. A pochi minuti dalla fine unite le olive nere. Vini di accompagnamento: Oltrepò Pavese Riesling Italico DOC, Pomino Bianco DOC, Melissa Bianco DOC.',3418);
INSERT INTO "ricette" VALUES (25832,'Tonno All''aceto','Pesce','Tonno Fresco',4,' -','4 Trance Tonno Fresco,
2 Cucchiai Aceto Di Vino Molto Forte,
1 Spicchio Aglio,
Prezzemolo Tritato,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','In un largo tegame basso scaldate tre cucchiai d''olio con uno spicchio d''aglio tagliato a filetti. Adagiatevi le trance di tonno, bagnatele con due cucchiai d''acqua, regolate sale e pepe, cospargete un po'' di prezzemolo tritato. Cuocete, a fuoco basso e coperto, per circa 20 minuti. All''ultimo minuto spruzzate con due cucchiai d''aceto molto forte, fate evaporare e servite. Vini di accompagnamento: Trentino Pinot Grigio Spumante DOC, Verdicchio Di Matelica Spumante DOC, Torbato Spumante IGT Di Sardegna.',3174);
INSERT INTO "ricette" VALUES (25833,'Tonno Alla Genovese','Pesce','Tonno',4,'Luogo: Liguria. Luogo: Genova.','4 Fette Tonno,
Funghi Secchi,
30 G Burro,
Olio D''oliva,
1 Spicchio Aglio,
Prezzemolo,
1 Cucchiaio Farina,
Vino Bianco,
1/2 Limone (succo),
Sale,
Pepe','Mettete in un tegame l''olio, 1 cucchiaio di farina, acciughe tritate, prezzemolo e uno spicchio d''aglio. Mescolare e aggiungere il tonno con del vino bianco, sale, pepe e funghi, che avrete prima messo a bagno in acqua tiepida e poi tagliati. Mettete a cuocere e prima che la cottura sia terminata aggiungete 30 g di burro e il succo di mezzo limone.',2322);
INSERT INTO "ricette" VALUES (25834,'Tonno Alla Genovese (2)','Pesce','Tonno',6,'Luogo: Liguria. Luogo: Genova.','600 G Tonno Fresco,
2 Acciughe,
30 G Funghi Secchi,
Olio D''oliva,
1 Pizzico Pepe,
1 Bicchiere Vino Bianco,
Cipolla,
Aglio,
Prezzemolo,
1 Pizzico Spezie,
1 Pizzico Sale,
Farina','Tagliare il tonno a trance alte 1 cm. In una teglia, preparare un soffritto con l''olio, aglio, cipolla, prezzemolo e i funghi ammollati in acqua tiepida e strizzati, il tutto tritato finemente. Stemperare nel soffritto le acciughe lavate e spinate, versare il vino e 1 cucchiaio di farina. Far insaporire per 6-7 minuti e unire il tonno, con 1 pizzico di pepe, di sale e di spezie. Coprire la teglia e lasciar cuocere, a fuoco moderato, per circa 1 ora.',2613);
INSERT INTO "ricette" VALUES (25835,'Tonno Alla Griglia','Pesce','Tonno',4,' -','1 Trancio Di Tonno Di 700 G,
1 Cipolla,
Aglio,
Prezzemolo,
2 Chiodi Di Garofano,
2 Limoni,
Pangrattato,
Olio D''oliva Extra-vergine,
Sale,
Pepe Verde','Accomodare il trancio di tonno suddviso in 4 parti in una terrina e coprirlo con un''emulsione di olio, succo di limone, erbe, aromi triturati, sale, pepe e lasciare il pesce in questa marinata per circa 2 ore, quindi passarlo nel pangrattato e cuocerlo alla griglia bagnandolo con la marinata.',2555);
INSERT INTO "ricette" VALUES (25836,'Tonno Alla Ligure','Pesce','Tonno',1,'Luogo: Liguria.','160 G Tonno Fresco,
10 G Funghi Secchi,
15 G Acciughe Salate,
Olio D''oliva Extra-vergine,
Prezzemolo,
Aglio,
1 Goccio Vino Bianco','Tritare bene il prezzemolo e l''aglio e farli soffriggere in un tegame con l''olio e i filetti d''acciughe. Far rinvenire i funghi in un po'' d''acqua, strizzarli, tritarli e unirli al soffritto. Spruzzare con il vino e disporvi il tonno. Cuocere per 10 minuti.',1147);
INSERT INTO "ricette" VALUES (25837,'Tonno Alla Livornese','Pesce','Tonno Fresco',4,'Luogo: Toscana. Luogo: Livorno. Luogo: Liguria.','4 Fette Spesse Tonno Fresco,
Farina,
4 Cucchiai Olio D''oliva,
1 Ciuffo Prezzemolo,
1/2 Cipolla,
1 Foglia Alloro,
1 Cucchiaio Capperi,
1 Pizzico Cannella,
1/2 Bicchiere Vino Bianco Secco,
Sale,
Pepe Appena Macinato','Passate le fette di tonno nella farina, quindi adagiatele in una casseruola dove avrete in precedenza fatto rosolare nell''olio la cipolla ed il prezzemolo tritati finemente. Fatele dorare da ambo i lati, aggiustate di sale e pepe secondo il vostro gusto ed irroratele con il vino bianco. Lasciate evaporare un poco, insaporite con i capperi, la foglia di alloro sbriciolata, un poco di cannella, incoperchiate e lasciate cuocere a fuoco medio per circa 20 minuti diluendo se necessario con un poco di acqua. Servite il tonno coperto con il suo fondo di cottura e con contorno di patate al prezzemolo o insalata fresca.',2953);
INSERT INTO "ricette" VALUES (25838,'Tonno Alla Livornese (2)','Pesce','Tonno',4,'Luogo: Toscana. Luogo: Livorno.','600 G Trance Di Tonno,
1/2 Bicchiere Vino Rosso,
1 Cipolla,
1 Spicchio Aglio,
1/2 Cucchiaio Farina,
Prezzemolo Tritato,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Affettare aglio e cipolla, metterli in un tegame con l''olio e un po'' di prezzemolo, far appassire per 2 minuti rigirando, quindi unire le trance di tonno, salarle e peparle e cuocerle per 5 minuti per parte. Bagnare con 2 cucchiai d''acqua calda, coprire, abbassare la fiamma e cuocere per altri 2 minuti. Togliere il coperchio. Unire il vino, diluire la farina con poca acqua e aggiungerla alle trance e cuocere finché si sarà addensato il tutto.',2183);
INSERT INTO "ricette" VALUES (25839,'Tonno Alla Menta','Pesce','Tonno',6,' -','1000 G Tonno (tranci Da 170 G Circa L''uno),
1 Limone,
1 Cucchiaio Prezzemolo Tritato,
1/2 Cucchiaio Menta,
1 Bicchierino Vodka,
Sale,
Pepe','Disponete in un piatto i tranci di tonno e irrorateli con una marinata di olio, prezzemolo tritato, menta, succo di limone, sale e pepe. Lasciateli immersi in questa salsa per 1 ora perché assorbano completamente i sapori, sgocciolateli e fateli arrostire su una graticola già calda, da entrambi i lati, bagnandoli con la loro marinata. Alla fine irrorateli con la Vodka e date fuoco al liquore. Serviteli decorando il piatto con spicchi di limone.',2405);
INSERT INTO "ricette" VALUES (25840,'Tonno Alla Mentuccia','Pesce','Tonno',4,' -','800 G Tonno Fresco Tagliato A Fette Di 3 Cm,
250 G Cipolle,
Farina,
5 Cucchiai Olio D''oliva,
1 Cucchiaino Zucchero,
1/2 Bicchiere Aceto Di Vino,
Mentuccia Fresca Tritata,
Sale,
Pepe','Spellare il tonno, tagliarlo a dadini, infarinarlo e friggerlo in olio bollente. Levarlo quando è dorato e metterlo da parte. Friggere le cipolle affettate nello stesso olio del tonno, salarle, peparle, farle imbiondire e poi aggiungere lo zucchero e l''aceto. Far restringere questo sugo a fuoco basso. Rimettere i dadini di tonno nella padella con le cipolle e far insaporire per 10 minuti. Servire il tonno cosparso di mentuccia.',2673);
INSERT INTO "ricette" VALUES (25841,'Tonno Alle Acciughe','Pesce','Tonno Fresco',4,' -','6 Filetti Tonno Fresco,
3 Cl Olio D''oliva,
Sale,
Pepe Nero Macinato Di Fresco,
Per La Salsa:,
60 G Acciughe Sott''olio,
10 Olive Nere Sminuzzate,
2 Spicchi Aglio Schiacciato,
6 Cl Vino Bianco Secco,
30 G Prezzemolo,
1 Cucchiaio Succo Di Limone,
10 Capperi,
Sale,
Pepe Nero','Fate marinare per un''ora i filetti di tonno in sale, pepe e olio. Passateli sulla griglia o cuoceteli al vapore. Nel frattempo preparate la salsa emulsionando nel mixer tutti gli ingredienti indicati. Versare un cucchiaio di salsa su ogni filetto appena cotto e servite subito, con un altro cucchiaio di salsa a fianco.',3407);
INSERT INTO "ricette" VALUES (25842,'Tonno Alle Verdure','Pesce','Tonno',4,' -','700 G Tonno (tranci Da 175 G L''uno),
150 G Peperoni,
150 G Melanzane,
150 G Zucchine,
15 G Capperi,
50 G Cipolla,
300 G Pomodori,
4 Cucchiai Olio D''oliva Extra-vergine,
1 Spicchio Aglio,
4 Foglie Basilico,
Sale,
Pepe','Fate appassire in 2 cucchiai di olio la cipolla e l''aglio tritati, aggiungete quindi tutte le altre verdure tagliate a pezzetti di uguali dimensioni e cuocetele a fuoco basso per 40 minuti bagnando se necessario con qualche cucchiaio di acqua bollente; salate e pepate. Fate insaporire i tranci in una padella antiaderente con 2 cucchiai di olio. Quindi trasferitele nel sugo di verdure, aggiungete i pomodori a filetti, i capperi e il basilico spezzettate. Proseguite la cottura per 10 minuti girando le fette di tonno con molta delicatezza per evitare di spezzarle.',2457);
INSERT INTO "ricette" VALUES (25843,'Tonno Aromatico','Pesce','Tonno',4,' -','4 Trance Tonno Fresco,
1 Cucchiaio Semi Di Finocchio,
1 Presa Sale,
1 Presa Pepe,
Abbondante Olio D''oliva','Macinare i semi di finocchio ed unirli ad una presa di sale e pepe. Cospargere le fette di tonno da entrambi i lati con gli aromi. Porre sul fuoco una larga padella con abbondante olio. Quando l''olio sarà molto caldo cuocervi il pesce, rigirandolo delicatamente per non romperlo.',2970);
INSERT INTO "ricette" VALUES (25844,'Tonno Con Ananas Grigliato E Tortino Di Bieta','Contorno','Tonno',4,' -','400 G Tonno,
200 G Ananas,
150 G Bieta,
4 Uova,
100 G Pangrattato,
50 G Formaggio Grana,
1 Cipolla,
Burro','Per il tortino lessare la bieta dopo averla pulita, metterla in padella con della cipolla fatta appassire. Aggiungere un rosso d''uovo ed il pangrattato e porre tutto all''interno di uno stampino precedentemente imburrato. Cuocere in forno per 10 minuti a 180 gradi. Scottare il tonno (tagliato spesso) con l''ananas in una padella antiaderente. Dopo la cottura intercalare l''ananas ed il tonno e porvi sopra il tortino di bieta.',2756);
INSERT INTO "ricette" VALUES (25845,'Tonno Con La Cipollina Fresca','Contorno','Tonno',4,' -','60 G Olio D''oliva,
Sale,
Pepe,
Aglio,
10 Cl Vino Bianco Secco,
Menta Fresca,
600 G Pomodorini Da Sugo,
1000 G Tonno Fresco (pezzi Da 1000 G),
300 G Cipollina Fresca','Il pezzo di tonno dovrebbe avere forma piuttosto regolare. Da ogni lato praticate piccole incisioni nella polpa, infilate dentro qualche pezzo di aglio, qualche granello di pepe e qualche fogliolina di menta. Mettete a cuocere il pezzo di tonno così preparato in tegame, dove avrete già scaldato l''olio; date qualche rigirata, spruzzate di sale. Quando vedete che il tonno prende colore, bagnatelo col vino, in due riprese; aspettate che il vino ''sfumi'', togliete il pezzo di tonno dal tegame, tenetelo in caldo. Intanto, al fondo di cottura unite la cipollina tritata, lasciate che diventi perlacea, appassendo; unite la polpa dei pomodori passati al setaccio, date qualche rigirata e qualche minuto ancora di cottura per legare, rimettete dentro il tonno, portate a cottura. A questo punto sgocciolate bene il pezzo di tonno, affettatelo nel piatto di servizio ben caldo, coprite con il sugo, e servite.',3108);
INSERT INTO "ricette" VALUES (25846,'Tonno Con Patate','Contorno','Tonno Sott''olio',4,' -','200 G Tonno Sott''olio,
4 Patate,
200 G Polpa Di Pomodoro,
1 Spicchio Aglio,
Prezzemolo Tritato,
Origano,
Poco Vino Bianco Secco,
4 Cucchiai Olio D''oliva,
Sale','Sbucciare le patate, lavarle e cuocerle per 30 minuti in acqua salata. Intanto in una casseruola, soffriggere l''aglio con 4 cucchiai d''olio. Prima che prenda colore aggiungere la polpa di pomodoro, salare e cuocere per 10 minuti. Unire il tonno, spruzzarlo con poco vino e alzare la fiamma per un istante. Quando le patate saranno cotte, scolarle, tagliarle a pezzi e unirle al tonno. Cospargere di prezzemolo tritato e di origano e cuocere ancora per 5 minuti.',2813);
INSERT INTO "ricette" VALUES (25847,'Tonno Con Piselli','Pesce','Tonno',4,' -','500 G Tonno In Trance,
350 G Pisellini,
50 G Burro,
1 Tazza Salsa Di Pomodoro,
5 Pomodori,
1 Cipolla,
1 Carota,
1 Costa Sedano,
Sale','Rosolare nel burro la cipolla, la carota e il sedano tritati, unire la salsa di pomodoro e i pomodori spezzettati e far cuocere per 6-7 minuti. Aggiungere le trance di tonno e i piselli scongelati, salare, far cuocere per circa 40 minuti e servire caldo.',1918);
INSERT INTO "ricette" VALUES (25848,'Tonno Di Coniglio','Carne','Coniglio',6,' -','1 Coniglio,
1 Costa Sedano,
1 Carota,
1 Cipolla,
1 Foglia Alloro,
2 Spicchi Aglio,
6 Foglie Salvia,
Abbondante Olio D''oliva,
Sale,
Pepe','Lessate il coniglio per un''ora e mezzo in abbondante acqua con cipolla, carota, sedano, alloro e poco sale. Quando è ancora tiepido disossatelo, sminuzzate la carne, salate e pepate. Sbucciate alcuni spicchi d''aglio. In una terrina di vetro o di porcellana disponete uno strato di carne, poi uno spicchio d''aglio e le foglie di salvia. Continuate fino a riempire 3/4 del contenitore. Versate a filo sulla superficie abbondante olio. Coprite e lasciate riposare al fresco per alcuni giorni. Vini di accompagnamento: Mimosa Sauvignon VdT Del Piemonte, Terlano Sauvignon DOC, Greco Di Tufo DOC.',2722);
INSERT INTO "ricette" VALUES (25849,'Tonno Di Coniglio (2)','Carne','Coniglio',6,' -','1 Coniglio Intero Pulito,
1 Cipolla,
2 Chiodi Di Garofano,
1 Carota,
3 Gambi Sedano,
1 Mazzetto Erbe Aromatiche Miste Legate Insieme (rosmarino, Salvia, Timo Alloro, Prezzemolo),
11 Foglie Salvia,
8 Spicchi Aglio,
50 Cl Olio D''oliva,
Sale,
Pepe In Grani','In una capace casseruola portate in ebollizione abbondante acqua con la cipolla, la carota, il sedano tagliato a pezzettini, il mazzetto di erbe aromatiche, i chiodi di garofano e 5-6 grani di pepe. Salate e immergetevi il coniglio intero, facendo in modo che rimanga coperto d''acqua. Lasciate cuocere sempre a leggero bollore e a fiamma bassa per circa un ora, finché la carne sia ben tenera e tenderà a staccarsi dall''osso.Spegnete e lasciate intiepidire il coniglio nella sua stessa acqua, a tegame coperto.Scolatelo prima che sia completamente freddo, pulite la carne da eventuali verdure rimaste aderenti e disossatelo staccando la carne a pezzetti nè troppo piccoli nè troppo grandi.Raccoglieteli man mano in una ciotola. Pelate gli spicchi d''aglio e pulite delicatamente le foglie di salvia.Ricoprite il fondo di una terrina con un velo d''olio, formate uno strato di pezzetti di coniglio, inframezzandoli con foglie di salvia e qualche spicchio d''aglio lasciato intero, irrorate d''olio, quindi alternate gli strati sino ad esaurire tutti gli ingredienti.Alla fine il coniglio deve risultare bene impregnato d''olio ma senza esserne tuttavia sommerso.Coprite con un foglio di carta forno e conservate in frigo, nella parte meno fredda, per almeno un giorno prima di servire.Potete comunque conservarlo per 10 giorni e consumare il coniglio come antipasto, accompagnato a piacere da sottaceti.',6403);
INSERT INTO "ricette" VALUES (25850,'Tonno Di Coniglio (3)','Carne','Coniglio',6,'Luogo: Piemonte. Luogo: Alba. Preparazione: 20 minuti. Cottura: 45 minuti.','1 Coniglio Pronto Per La Cottura,
30 Foglie Salvia,
20 Spicchi Aglio,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Fate lessare il coniglio in acqua bollente e salata per circa tre quarti d''ora. Toglietelo dalla pentola, lasciatelo intiepidire e quindi spolpatelo. I tocchetti di carne disponeteli in una terrina: fatene un primo strato cui aggiungete alcune foglie di salvia e qualche spicchio d''aglio; irroratelo d''Olio D''oliva Extra-vergine, salatelo leggermente e pepate. Passate quindi agli strati successivi ripetendo le stesse operazioni. Fate almeno tre strati. Mettete la terrina al fresco e lasciatela per una notte. Se la tenete in frigo, ricordatevi di toglierla almeno un''ora prima di consumare il coniglio marinato. Guarnite le porzioni con un''insalatina di sarsèt (valerianella). L''olio d''oliva extra-vergine deve coprire interamente la carne di coniglio, per cui conviene pressare bene gli strati di carne. Vino consigliato: Langhe Freisa.',2581);
INSERT INTO "ricette" VALUES (25851,'Tonno E Fagioli Stufati','Pesce','Tonno Al Naturale',4,' -','300 G Tonno In Scatola Al Naturale,
300 G Pomodori Pelati,
250 G Fagioli Bianchi Di Spagna,
4 Cucchiai Olio D''oliva,
Salvia,
Rosmarino,
Sale,
Pepe','La sera precedente mettete a bagno i fagioli in acqua fredda. Il giorno dopo sciacquate i fagioli e lessateli cuocendoli per circa 40 minuti in acqua non salata Verso la fine della cottura scaldate in un tegame preferibilmente di coccio 4 cucchiai di olio, fatevi soffriggere un trito di salvia e rosmarino, quindi aggiungete i pelati a pezzetti e i fagioli scolati e lasciate insaporire per 5 minuti. Aggiungete il tonno grossolanamente sbriciolato e lasciate cuocere per altri 5 minuti circa. Alla fine salate, pepate e servite in tavola.',2569);
INSERT INTO "ricette" VALUES (25852,'Tonno E Scampi','Pesce','Scampi Lessati',4,' -','200 G Fagioli Bianchi In Scatola,
2 Cespi Insalata Belga (indivia),
1 Mazzetto Insalata Rucola,
400 G Scampi Lessati,
200 G Tonno In Scatola,
1 Cucchiaino Curry,
Olio D''oliva,
Sale','Scolate i fagioli. Lavate e tagliate a listarelle l''insalata, spezzettate la rucola. Riunite le verdure in un''insalatiera, aggiungete gli scampi e il tonno. Diluite il curry con un po'' d''olio, salate. Condite l''insalata.',1739);
INSERT INTO "ricette" VALUES (25853,'Tonno Esagerato','Antipasto','Tonno',4,' -','1 Scatoletta Tonno (da 160 G),
1/2 Tazza Piselli Surgelati Già Scongelati,
1/2 Tazza Formaggio Spalmabile,
1 Pizzico Sale,
10 Crackers','Versare il tonno in una grossa ciotola e farlo a pezzettini con la forchetta. Aggiungere i piselli, il formaggio spalmabile e un pizzico di sale. Mescolare bene tutto con un grosso cucchiaio di legno. Mettere il tonno sui crackers.',824);
INSERT INTO "ricette" VALUES (25854,'Tonno Fresco All''aceto','Pesce','Tonno Fresco',4,' -','4 Tranci Tonno Fresco,
1 Spicchio Aglio,
Olio D''oliva,
1 Ciuffo Prezzemolo,
1 Cucchiaio Aceto Di Vino,
Sale,
Pepe','Lavate e asciugate il tonno fresco tagliato a tranci piuttosto grossi. Mettete in un tegame basso un po'' d''olio, insaporitelo con uno spicchio d''aglio intero o tagliuzzato. Quando l''olio è scaldato mettete il tonno, lasciatelo insaporire e rosolare leggermente, voltatelo, regolate sale e pepe, bagnatelo con un po'' d''acqua e aggiungete un ciuffo di prezzemolo tritato. Cuocete, a fuoco basso e coperto, per una ventina di minuti scarsi; in ultimo aggiungete una cucchiaiata di aceto per legare il sugo di cottura ristrettissimo.',2783);
INSERT INTO "ricette" VALUES (25855,'Tonno Fresco Coi Peperoni','Pesce','Tonno',4,' -','4 Tranci Tonno Fresco (tranci Da 200 G),
3 Limoni,
3 Peperoni Rossi,
Olio D''oliva Extra-vergine,
1 Manciata Foglie Di Salvia Fresche,
1 Manciata Foglie Di Maggiorana Fresche,
Sale Marino Integrale,
Pepe Bianco','Marinare i tranci di tonno con succo di limoni, sale, pepe, erbe aromatiche. Sistemarli in una pirofila. Arrostire e spellare i peperoni; ridurli a strisce e sistemarli intorno al pesce. Aggiustare di sale e di pepe. Irrorare con l''olio, un po'' d''acqua e cospargere di erbette sminuzzate. Infornare a 180 gradi per 25 minuti.',837);
INSERT INTO "ricette" VALUES (25856,'Tonno In Agrodolce','Pesce','Tonno',4,' -','800 G Tonno Fresco,
250 G Cipolle,
1/2 Bicchiere Aceto Di Vino,
Abbondante Olio D''oliva,
Farina,
Menta Fresca,
1 Cucchiaio Zucchero,
Pepe,
Sale','Spellare i tranci di tonno e tagliarli a pezzetti di 3 cm. Infarinarli e friggerli in abbondante olio. Quando saranno dorati scolarli e tenerli in caldo. Nello stesso olio friggere le cipolle affettate. Salarle, peparle e farle imbiondire. Cospargerle con lo zucchero e bagnarle con l''aceto. Mescolare, abbassare la fiamma e restringere il sugo. Rimettere il tonno nel tegame e farlo insaporire mescolando. Trasferire nel piatto da portata e guarnire con la menta.',3143);
INSERT INTO "ricette" VALUES (25857,'Tonno In Avocado','Antipasto','Tonno',4,' -','4 Avocado Maturi,
1 Uovo Sodo,
1 Cipolla,
1 Gambo Sedano,
250 G Tonno Al Naturale,
Sale,
Pepe,
1/2 Limone (succo),
2 Cucchiai Maionese,
1 Cucchiaio Prezzemolo Fresco Tritato','Sminuzzate l''uovo sodo, la cipolla, il sedano e il tonno, amalgamate con la maionese. Svuotate delicatamente gli avocado dopo averli divisi in due, in modo da formare delle ''coppette'' con le pareti spesse mezzo centimetro. Aggiungete la polpa al composto, condite con sale, pepe, il succo di limone e un filo d''olio d''oliva. Farcite le ''coppette'' di avocado e decoratele col prezzemolo tritato prima di servire.',1635);
INSERT INTO "ricette" VALUES (25858,'Tonno In Insalata Con Fagioli','Pesce','Tonno Fresco',4,' -','400 G Tonno Fresco,
1000 G Fagioli Bianchi Freschi,
40 G Pinoli,
4 Porri,
1 Cespo Insalata Scarola,
1 Pomodoro,
10 Foglioline Basilico,
1 Spicchio Aglio,
Olio D''oliva,
Sale,
Pepe','Lessate i fagioli. Tagliate a fettine la parte bianca dei porri e cuoceteli a vapore. Lavate e sgocciolate l''insalata. Tagliate il pomodoro, eliminate i semi e tagliatelo a fettine. Lavate e asciugate velocemente il tonno, spennellatelo più volte d''olio. Scaldate molto bene una griglia, adagiatevi il tonno e cuocetelo al grill del forno 10 minuti per parte. Profumate l''interno di un''insalatiera strofinandovi uno spicchio d''aglio schiacciato e mettete sul fondo una decina di foglioline spezzettate di basilico, pinoli, sale e pepe. Condite con olio versato a filo e mescolate. Aggiungete i fagioli, le verdure e il pesce sminuzzato. Servite con il tonno tiepido. Vini di accompagnamento: Lison-Pramaggiore Verduzzo DOC, Trebbiano Di Romagna DOC, Cirò Bianco DOC.',2860);
INSERT INTO "ricette" VALUES (25859,'Tonno In Salsa Cremosa','Pesce','Tonno',4,' -','600 G Tonno (tranci Da 150 G L''uno),
1 Cucchiaio Prezzemolo Tritato,
1 Cucchiaio Cerfoglio E Maggiorana Tritati,
1 Limone,
2 Tuorli D''uovo,
20 Cl Vino Bianco,
10 Cl Panna,
Sale,
Pepe','Lavate le fette di tonno e asciugatele delicatamente con carta assorbente da cucina. Dopodichè adagiatele in una larga casseruola dove possano stare in un solo strato; spargetevi sopra le erbe tritate, irrorate con il succo di limone, poi con il vino e unite un filo di acqua, sufficiente a coprire a livello le fette di pesce. Salate, pepate e cuocete per 10-12 minuti. Poi prelevate il pesce dal recipiente, con una paletta mettetelo su un piatto scaldato in precedenza e tenetelo in caldo. Filtrate il fondo di cottura, rimettetelo in una casseruolina, fatelo ridurre a pochi cucchiai: aggiungete i tuorli stemperati con la panna, regolate di sale, pepate, e cuocete la salsa molto dolcemente fino a che si sarà un po'' addensata. Versatela sul pesce e servite subito ben caldo.',2319);
INSERT INTO "ricette" VALUES (25860,'Tonno In Tegame','Pesce','Tonno Fresco',6,'Luogo: Sardegna.','1000 G Tonno Fresco Tagliato In 6 Fette,
2 Limoni (succo),
400 G Patate,
80 G Formaggio Pecorino Grattugiato,
1 Pizzico Zafferano In Polvere,
Olio D''oliva,
Sale,
Prezzemolo','Togliere la pelle dalle fette di tonno e lasciarle macerare nel succo di limone. Intanto pelare e tagliare a fette le patate. Oliare una teglia da forno e rivestire il fondo con le patate, spolverizzare con prezzemolo e con pecorino grattugiato; quindi adagiare le fette di tonno. Sopra disporre altre patate, altro prezzemolo e pecorino. Salare, distribuire lo zafferano, l''olio e infornare a 180 gradi per 40 minuti circa.',3654);
INSERT INTO "ricette" VALUES (25861,'Tonno In Umido','Pesce','Tonno',4,' -','400 G Tonno,
3 Cucchiai Salsa Di Pomodoro,
Burro,
Sedano,
Prezzemolo,
2 Cipolle','Tritate il prezzemolo, il sedano, le cipolle e fatele rosolare nel burro. Aggiungere 3 cucchiai si salsa di pomodoro un po'' d''acqua e il tonno tagliato a pezzi. Lasciate cuocere per mezz''ora.',1898);
INSERT INTO "ricette" VALUES (25862,'Tonno Marinato','Pesce','Tonno',6,' -','8 Tranci Tonno,
1 Cipolla,
4 Acciughe,
1 Bicchiere Vino Bianco,
2 Limoni,
Farina,
2 Cucchiai Aceto Di Vino,
Sale,
Pepe,
Poco Olio D''oliva','Preparare una marinata con 1/2 cipolla tritata, il succo dei limoni, sale e pepe e porvi i tranci di tonno per 1 ora. Scolarli, infarinarli e farli rosolare in una padella con poco olio. A parte soffriggere il resto della cipolla e le acciughe tritate, aggiungere il vino e 2 cucchiai di aceto e far sobbollire per 10 minuti. Versare questa salsina nella padella con il tonno e proseguire la cottura per altri 15 minuti.',3622);
INSERT INTO "ricette" VALUES (25863,'Tonno Stufato','Pesce','Tonno Fresco',4,' -','4 Trance Tonno Fresco,
200 G Carote,
200 G Rape,
200 G Fagiolini,
1 Scalogno,
Rosmarino,
Timo,
1/2 Bicchiere Vino Bianco,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Mondate e lavate fagiolini, carote e rape. Togliete la pelle alle trance, tagliatele in due, eliminate la cartilagine centrale. Scaldate due cucchiai d''olio in un tegame, adagiatevi il tonno e fatelo rosolare da entrambe le parti a fuoco vivo. Quando il tonno è pronto ritiratelo dal recipiente, eliminate il grasso in eccesso del fondo di cottura, lasciatevi appassire lo scalogno tritato e aggiungete le verdure. Salate, pepate, aromatizzate con timo e rosmarino. Fate stufare a fuoco medio per una decina di minuti. Ponete il tonno sulle verdure, bagnate con mezzo bicchiere di vino e un mestolo d''acqua calda, coprite il recipiente e cuocete, a fuoco basso, per circa mezz''ora. Sul piatto da portata disponete tonno e verdure. Servite caldo. Vini di accompagnamento: Friuli Latisana Pinot Bianco DOC, Bolgheri Bianco DOC, Capri Bianco DOC.',2634);
INSERT INTO "ricette" VALUES (25864,'Tonno Ubriaco','Pesce','Tonno',4,' -','600 G Tonno Fresco In Tranci,
1/2 Bicchiere Vino Rosso,
1 Cipolla,
1 Spicchio Aglio,
1/2 Cucchiaio Farina,
1 Manciatina Prezzemolo Tritato,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Affettare aglio e cipolla e farli appassire in 4 cucchiai di olio con una manciatina di prezzemolo per 5 minuti a fuoco basso. Unire i tranci di tonno, salarli, peparli e cuocerli 5 minuti per parte. Bagnare con 2 cucchiai di acqua calda, coprire, abbassare la fiamma e proseguire la cottura per altri 3 minuti. Aggiungere il vino. Diluire 1/2 cucchiaio di farina in poca acqua e unirla al tonno. Cuocere a fiamma vivace, rigirando il pesce, finché il fondo di cottura sarà denso.',2923);
INSERT INTO "ricette" VALUES (25865,'Tonno Vitellato','Pesce','Tonno Rosso Fresco',4,' -','4 Tranci Tonno Rosso Fresco,
150 G Polpa Di Vitello,
5 Capperi Dissalati,
2 Filetti D''acciughe Sott''olio,
1 Limone,
1 Scalogno,
Poco Vino Bianco,
2 Cucchiai Maionese Allo Yogurth,
Olio D''oliva,
Aglio,
Sale,
Pepe','Allo scalogno tritato e stufato unire la carne a straccetti e sfumare con poco vino, cuocendo 7 minuti. Fare intiepidire e frullare con i capperi, le acciughe, la scorza del limone, la maionese, sale e pepe. Lasciare raffreddare e compattare. Scottare il tonno in padella antiaderente con olio e aglio in camicia (3 minuti solo da un lato salando e pepando) e servire con la crema di vitello a temperatura ambiente.',3357);
INSERT INTO "ricette" VALUES (25866,'Tonné','Salsa','Tonno',4,'Preparazione: 20 minuti.','1 Tazza Maionese,
3 Acciughe,
1 Cucchiaino Capperi,
100 G Tonno In Scatola','Preparate una maionese con 2 tuorli d''uovo, 1 bicchiere di olio, sale e il succo di 1 limone e trasferitela in una terrina. Prendete poi 3 acciughe, lavatele e liberatele dalle lische, mettetele sul tagliere e tritate finemente con la mezzaluna insieme al tonno in scatola e ai capperi. Prendete il trito e passatelo al passaverdura, per ridurlo in poltiglia. Dovrete poi incorporare questo passato alla maionese: vi servirà per coprire le fette di vitello che avrete in precedenza bollito e fatto raffreddare. La salsa tonné può essere preparata anche in un altro modo più rapido e più semplice usando il frullatore. Pulite le acciughe e diliscatele, rompete il tonno a pezzi e aggiungete i capperi, il succo di limone, l''olio e il sale, mettendo tutto nel bicchiere frullatore. Aggiungete anche mezzo bicchiere di brodo. Frullate e la salsa è pronta per l''uso, con il vantaggio di non contenere uova e di essere perciò più leggera e conservabile in frigorifero. Questo piatto classico è semplice da preparare e di sicuro effetto.',693);
INSERT INTO "ricette" VALUES (25867,'Top','Bevande','Sloe-gin',1,' -','1/3 Apricot Brandy,
2/3 Sloe-gin,
1 Cucchiaio Succo Di Limone,
Per Servire:,
1 Scorza Di Limone','Scuotere nello shaker con cubetti di ghiaccio. Servire nel tumbler stretto, con una scorza di limone precedentemente spremuta nel bicchiere.',353);
INSERT INTO "ricette" VALUES (25868,'Top Bar','Bevande','Tequila',1,' -','1/3 Pernod,
2/3 Tequila,
1 Cucchiaio Succo Di Limone,
Per Servire:,
1 Fetta Tonda Limone','Agitare vigorosamente nello shaker con ghiaccio in cubetti. Servire nel gotto basso, con quattro cubetti di ghiaccio e una fetta tonda di limone.',413);
INSERT INTO "ricette" VALUES (25869,'Top Class','Bevande','Caffè',1,' -','4/10 Irish Whisky Bushmills,
2/10 Crema Cacao Bianca Buton,
1/10 Amaretto Di Saronno,
2/10 Caffè Lavazza,
1/10 Crema Latte,
Per Guarnire:,
Alcune Scaglie Cacao','Si prepara nello shaker. Servire nella classica coppetta da cocktail. Decorare con scaglie di cacao in superficie.',441);
INSERT INTO "ricette" VALUES (25870,'Top Class (2)','Bevande','Drambuie',1,' -','3/10 Drambuie,
1/10 Limoncello Toschi,
6/10 Wild Turkey Bourbon Whisky,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Versare gli ingredienti nel mixing glass con abbondante ghiaccio. Mescolare delicatamente e servire nella coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa al maraschino.',347);
INSERT INTO "ricette" VALUES (25871,'Top Club','Bevande','Sherry',1,' -','1/5 Sherry,
2/5 Cognac,
2/5 Rum,
10 Gocce Succo Di Limone','Versate nel mixer alcuni cubetti di ghiaccio e gli ingredienti indicati, a parte il limone. Mescolate con cura e prima di servire unite il succo di limone.',341);
INSERT INTO "ricette" VALUES (25872,'Topfenpalatschinken','Contorno','Ricotta',4,'Luogo: Austria.','Per La Pastella:,
150 G Farina,
2 Bicchieri Latte,
3 Uova,
1 Cucchiaio Zucchero,
1 Cucchiaio Olio D''oliva,
Burro,
Per Il Ripieno:,
50 G Burro,
50 G Zucchero,
2 Uova,
250 G Ricotta Fresca Setacciata,
Uvetta Sultanina,
3 Cucchiai Panna Acida (o Yogurth),
1 Limone (scorza),
Sale,
Per Condire:,
2 Bicchieri Latte,
2 Uova,
Zucchero','Topfenpalatschinken....che starebbe per sformato di omelette alla ricotta. Mescolare la farina setacciata insieme al latte e una presa di sale. Unite le uova, aggiungere l''olio e lo zucchero continuando a mescolare in modo da formare una pastella che lascerete riposare. Poi preparate con la pastella 6 omelette sottili. Montate burro, zucchero, sale, rosso d''uovo e scorza di limone e aggiungete la ricotta, l''uvetta sultanina e la panna acida. Montate a neve fissa le chiare ed incorporatele con attenzione. Spalmate il tutto sulle omelette, arrotolatele e disponetele in una teglia imburrata in modo che si sovrappongano in parte per lungo. Sbattete il latte rimasto con le uova e lo zucchero e versatelo sulle omelette che farete dorare in forno. Vanno servite tagliate trasversalmente.',3910);
INSERT INTO "ricette" VALUES (25873,'Topfenpalatschinken (2)','Contorno','Ricotta',4,'Luogo: Austria.','Per Il Ripieno:,
1/2 Tazza Uvetta Sultanina,
1 Tazza Acqua Bollente,
250 G Formaggio Fresco,
1/2 Tazza Marmellata Di Albicocche,
2 Uova,
1 Cucchiaino Scorza Di Limone,
1 Cucchiaino Vaniglia In Polvere,
1/4 Tazza Zucchero,
Per Le Crepes (circa 25):,
2 Uova,
3 Tazze Zucchero,
1 Tazza Latte,
Abbondante Zucchero A Velo','Per prima cosa preparate il ripieno: in un pentolino pieno d''acqua bollente fate ammorbidire l''uva passa per circa 15 minuti. Trascorso il tempo necessario, avvolgete l''uvetta nella carta assorbente. Passate nel mixer il formaggio fresco, la marmellata, i tuorli delle uova, la scorza di limone e la vaniglia in modo da ottenere impasto morbido e omogeneo. In una terrina aggiungete lo zucchero agli albumi e battete bene fino a formare una cremina compatta. Versatevi il composto di formaggio e marmellata, ottenuto col mixer, e infine aggiungetevi delicatamente l''uvetta. Preparate le crepes con gli ingredienti indicati. Riempitele con il composto e mettetele in forno preriscaldato a 200 gradi per 30/35 minuti. Cospargete di abbondante zucchero a velo e servite.',1953);
INSERT INTO "ricette" VALUES (25874,'Topinambur Al Burro','Contorno','Topinambur',4,' -','600 G Topinambur,
60 G Burro,
Prezzemolo,
Sale','Raschiare i topinambur, lavarli e tagliarli a spicchi. Gettarli in una pentola con acqua salata in ebollizione e cuocerli per circa 10 minuti. Scolarli e versarli in una casseruola con il burro, salare, coprire e cuocere a fuoco lento per circa 1 ora. Se necessario aggiungere un po'' di brodo. Tritare il prezzemolo e aggiungerlo 5 minuti prima del termine della cottura. Mescolare e servire.',592);
INSERT INTO "ricette" VALUES (25875,'Topinambur Al Forno','Contorno','Topinambur',4,' -','800 G Topinambur,
40 G Burro,
25 G Farina,
25 Cl Latte,
1 Tuorlo D''uovo,
Formaggio Parmigiano Grattugiato,
Pangrattato,
Prezzemolo,
Sale','Lessare i topinambur in acqua salata per circa 20 minuti, quindi sbucciarli e tagliarli a rondelle. Imburrare una teglia, cospargerla di pangrattato e disporvi le rondelle. A parte preparare una besciamella con 25 g di burro, il latte e la farina. Una volta tolta dal fuoco incorporarvi il tuorlo e una manciata di parmigiano. Distribuire bene la salsa sui topinambur e terminare cospargendo di pangrattato, prezzemolo tritato e fiocchetti di burro. Infornare e gratinare.',1518);
INSERT INTO "ricette" VALUES (25876,'Topinambur All''erba Cipollina','Contorno','Topinambur',4,' -','500 G Topinambur,
1 Mazzetto Erba Cipollina,
1/2 Spicchio Aglio,
2 Acciughe,
1/2 Bicchiere Vino Bianco,
1 Bicchiere Brodo,
30 G Burro,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Preparare un trito di prezzemolo, acciughe, aglio. Far appassire l''erba cipollina in poco olio. Unire i topinambur tagliati a fettine sottili e farli andare a fuoco vivo per qualche minuto, irrorarli col vino, farlo evaporare e aggiungere il brodo. Aggiustare di sale. Cuocere per 10 minuti a fuoco basso. Trasferire i topinambur su un piatto di servizio e cospargerli con fiocchi di burro e col trito aromatico. Aggiungere una macinata di pepe.',1186);
INSERT INTO "ricette" VALUES (25877,'Topinambur Alla Panna','Contorno','Topinambur',4,' -','700 G Topinambur,
25 Cl Panna,
1 Ciuffo Prezzemolo,
1 Noce Burro,
Sale','Pulite e lavate i topinambur, tagliateli a fettine sottili. In un tegame fate sciogliere una noce di burro, adagiatevi le fettine di topinambur, bagnatele con la panna e lasciate insaporire per 5 minuti. Salate e portate a cottura tenendo presente che la salsa deve addensarsi, quindi, se necessario, negli ultimi minuti scoprite e aumentate leggermente il calore. Ritirate dal fuoco, cospargete con un ciuffo di prezzemolo tritato, mescolate, passate sul piatto da portata e servite caldo.',1596);
INSERT INTO "ricette" VALUES (25878,'Topinambur In Insalata','Contorno','Topinambur',4,' -','400 G Topinambur,
400 G Mele,
250 G Sedano,
Olio D''oliva,
Limone,
Sale,
Pepe','Raschiare la buccia esterna dei topinambur, lavarli e asciugarli. Mondare e sbucciare le mele. Affettare gli uni e le altre sottilmente. Tagliare a julienne le coste di sedano. Unire tutti gli ingredienti in una insalatiera, condire con succo di limone, olio, sale, pepe e mescolare bene. Se si desidera un sapore più deciso si possono aggiungere capperi o senape.',872);
INSERT INTO "ricette" VALUES (25879,'Topinambur In Padella','Contorno','Topinambur',4,' -','400 G Topinambur,
Prezzemolo,
Aglio,
Brodo Vegetale,
1 Noce Burro,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulire i topinambur, raschiarli con un coltellino e tagliarli a fettine. Imbiondire l''aglio nell''olio ed unire i topinambur, facendoli saltare a fuoco vivace. Salare, pepare e portarli a cottura dolcemente aiutandosi con un po'' di brodo. A cottura ultimata unire prezzemolo finemente triturato e una noce di burro. Mescolare e servire.',1359);
INSERT INTO "ricette" VALUES (25880,'Topinambur In Salsa Verde','Contorno','Topinambur',4,' -','500 G Topinambur,
50 G Prezzemolo Tritato,
2 Acciughe Diliscate,
1 Manciata Capperi Sotto Sale,
1/2 Bicchiere Olio D''oliva,
Pepe Nero,
Succo Di Limone','Mettere nel mixer prezzemolo, acciughe e capperi, azionare il mixer e unire l''olio a filo. Aggiungere poche gocce di succo di limone. Trasferire la salsa in una ciotola e unire una macinata di pepe nero. Raschiare la buccia ai topinambur, lavarli, asciugarli e affettarli sottilmente. Disporre i topinambur nel piatto da portata e ricoprirli con la quantità di salsa desiderata. A questa salsa si può aggiungere un uovo sodo sminuzzato. Si ottiene in tal modo un piatto leggero di alto valore nutritivo.',829);
INSERT INTO "ricette" VALUES (25881,'Topinambur Trifolati','Contorno','Topinambur',4,' -','600 G Topinambur,
2 Spicchi Aglio,
1 Cucchiaio Prezzemolo Tritato,
Poco Brodo,
5 Cucchiai Olio D''oliva,
Pepe,
Sale','Raschiare, lavare e affettare i topinambur. In un tegame scaldare 5 cucchiai di olio, unire l''aglio schiacciato e farlo rosolare. Levarlo dall''olio e versarvi i topinambur, salarli, peparli e farli insaporire mescolando. Cuocere coperto, a fuoco moderato, bagnando ogni tanto con poco brodo. Prima di servirli condirli con il prezzemolo.',618);
INSERT INTO "ricette" VALUES (25882,'Tops Smile','Bevande','Cognac',1,' -','6/8 Cognac,
1/8 Liquore Di Ciliegia,
1/8 Drambuie,
1 Spruzzo Anisette,
2 Spruzzi Succo D''arancia,
2 Spruzzi Succo Di Limone','Versare gli ingredienti in un mixing-glass con alcuni cubetti di ghiaccio. Mescolare con il cucchiaio e passare in un bicchiere.',352);
INSERT INTO "ricette" VALUES (25883,'Tops Top','Bevande','Brandy',1,' -','1/8 Cherry Brandy,
1/8 Drambuie,
6/8 Brandy,
2 Gocce Succo Di Limone,
1 Goccia Anisette,
Per Servire:,
1 Scorza Di Limone','Agitare nello shaker con poco ghiaccio in cubetti. Servire nel calice panciuto, con una scorza di limone.',348);
INSERT INTO "ricette" VALUES (25884,'Torcetti Di Saint-vincent','Dessert','Burro',8,' -','250 G Farina,
100 G Burro,
1 Presa Lievito Di Birra,
1 Pizzico Sale,
1 Tazza Zucchero,
Burro Per La Piastra,
Farina Per La Piastra','Disponete la farina a fontana sulla spianatoia, formate un incavo al centro e mettetevi un pizzico di sale e una presa di lievito di birra, sciolto in poca acqua tiepida. Lavorate gli ingredienti con le mani, aggiungendo tanta acqua quanta ne occorre per ottenere un impasto omogeneo e consistente. Infine, raccogliete la pasta a palla e lasciatela riposare coperta, in un luogo tiepido, per un''ora. Trascorso questo tempo, lavorate di nuovo la pasta per 15 minuti, incorporando il burro ammorbidito, quindi fatela riposare per un''altra ora. A questo punto lavorate brevemente la pasta, poi dividetela a pezzettini e, aiutandovi con le mani, date loro la forma di bastoncini lunghi e sottili. Cospargete il piano di lavoro con un po'' di zucchero semolato e passatevi sopra i bastoncini, facendo in modo che risultino ben coperti. Dividete ogni bastoncino in segmenti di 10 cm di lunghezza, quindi riunite le estremità di ciascun pezzetto così da ottenere degli anelli a goccia. Sistemate i dolcetti sulla piastra del forno foderata con carta stagnola imburrata e infarinata e fateli cuocere nel forno a 210 gradi per circa 20 minuti. Sfornateli quando sono ben dorati e lasciateli raffreddare. Potete conservare i biscotti che non consumate in giornata avvolgendoli uno ad uno in quadratini di carta stagnola e sistemandoli poi in scatole di latta con coperchio.',2143);
INSERT INTO "ricette" VALUES (25885,'Tordi Ai Semi Di Finocchio','Pollame','Tordi',4,'Preparazione: 60 minuti.','12 Tordi,
1 Cucchiaio Semi Di Finocchio,
3 Foglie Alloro,
Vino Bianco Secco Corposo,
Sale','Frollatura: vanno mangiati subito o al massimo con due giorni di frollatura nella parte bassa del frigorifero. Pulire i tordi, coprirli di acqua leggermente salata, unire le foglie di alloro e i semi di finocchio schiacciati, far prendere l''ebollizione e cuocere a fuoco medio. Scolare i tordi, non devono essere completamente cotti, metterli in un recipiente di terracotta e coprirli di vino. Così preparati i tordi si conservano per parecchio tempo.',2334);
INSERT INTO "ricette" VALUES (25886,'Tordi All''aglio','Pollame','Tordi',4,' -','8 Tordi,
8 Fette Sottili Lardo,
3 Fette Alte Lardo Affumicato,
4 Spicchi Aglio,
100 G Crostini Di Pane,
Timo,
2 Cucchiai Olio D''oliva,
Burro,
Sale,
Pepe','Spennate i tordi, svuotateli, togliete le teste, salateli e avvolgeteli in una sottile fetta di lardo. In un tegame mettete 40 g di burro, 2 cucchiai d''olio e il lardo affumicato tagliato a dadini; fate rosolare e poi aggiungete i tordi, il timo, sale e pepe. Lasciate cuocere per 10 minuti. Intanto rosolate l''aglio a parte con un pezzetto di burro, unite i crostini di pane e lasciate insaporire. Successivamente unite il pane e l''aglio con i tordi e servite.',3652);
INSERT INTO "ricette" VALUES (25887,'Tordi All''uva','Pollame','Tordi',4,' -','8 Tordi,
4 Cucchiai Olio D''oliva Extra-vergine,
50 G Olive Nere,
15 Chicchi Uva Non Matura,
Alcuni Spicchi Aglio,
1 Pomodoro Maturo,
1 Mestolo Brodo,
Salvia,
Sale','Soffriggere nell''olio gli spicchi di aglio con la salvia e le olive; togliere l''aglio dorato e aggiungere il pomodoro spellato, privato dei semi e tritato; far insaporire. Deporre nell''intingolo i tordi e i chicchi d''uva; aggiustare di sale e far cuocere rivoltando ogni tanto i tordi. Aggiungere del brodo se il fondo di cottura asciuga troppo.',2532);
INSERT INTO "ricette" VALUES (25888,'Tordi Alle Olive','Pollame','Tordi',4,' -','16 Tordi,
70 G Burro,
100 G Olive Nere,
100 G Polpa Di Manzo Magra Macinata,
30 G Midollo,
1 Costa Sedano,
1 Carota,
1/2 Cipolla,
2 Pomodori Pelati,
Poco Brodo Di Carne,
Sale,
Pepe','Pulire i tordi (i buongustai preferiscono non vuotarli delle interiora) metterli in una casseruola con mezz''etto di burro, salarli e farli rosolare a fuoco vivo; appena hanno preso colore abbassare il fuoco e proseguire la cottura a calore moderato. Tritare finemente la cipolla, il sedano, la carota e il midollo, metterli in un tegame e farli soffriggere con il rimanente burro. Unire la carne tritata, far ben insaporire mescolando, aggiungere i pomodori tritati (eliminare i semi), salare, pepare, allungare con un poco di brodo e cuocere il sughetto per una mezz''ora; unire quindi la maggior parte delle olive intere e le rimanenti snocciolate e tritate (o pestate nel mortaio). Lasciar cuocere la salsa ancora per una decina di minuti; disporre i tordi su un piatto, cospargerli con la salsa e servire.',4286);
INSERT INTO "ricette" VALUES (25889,'Tordi In Salmì','Pollame','Tordi',4,' -','8 Tordi,
50 G Prosciutto Crudo,
50 G Olio D''oliva Extra-vergine,
Alcune Bacche Di Ginepro,
1 Spruzzatina Vino Marsala Secco,
Alcune Fette Pane Casereccio,
1 Mestolo Brodo,
Sale','Pulire i tordi, salarli e cuocerli allo spiedo o in forno. Una volta cotti togliere le testine e disossare 2 tordi. Pestare il tutto in un mortaio. In un tegamino cuocere lentamente per 30 minuti nell''olio, il prosciutto tritato, le bacche di ginepro schiacciate, un mestolo di brodo, una spruzzatina di marsala; filtrare al setaccio e riunire il ricavato in un tegame con la poltiglia pestata. Amalgamare; farvi insaporire i tordi per 10 minuti. Servire con fette di pane abbrustolito.',2840);
INSERT INTO "ricette" VALUES (25890,'Torello','Bevande','Kahlua',1,' -','1/2 Kahlua,
1/2 Vodka Eristow,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Mescolare delicatamente e servire nella coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa al maraschino.',381);
INSERT INTO "ricette" VALUES (25891,'Tori No Kara-age','Pollame','Pollo',4,'Luogo: Giappone.','2 Petti Di Pollo Disossati Tagliati A Cubetti,
3 Cucchiai Salsa Di Soia,
30 G Zenzero,
6 Spicchi Aglio,
Sale,
Pepe Nero Fresco In Granelli,
2 Cucchiai Farina Di Granturco,
2 Cucchiai Farina Di Grano Tenero,
2 Fette Limone','Fate marinare il pollo con la salsa di soia, lo zenzero, l''aglio, sale e pepe per 30 minuti. Mischiate la farina di granturco con la farina di grano tenero. Immergetevi i pezzi di pollo, che avete fatto marinare, fino a coprirli interamente. In una padella scaldate l''olio e friggete i pezzi di pollo per circa 5 minuti fino a quando non diventano dorati. Guarnite con fette di limone e servite su un piatto coperto da insalata.',1635);
INSERT INTO "ricette" VALUES (25892,'Torino-napoli','Bevande','Limoncello',1,' -','3/10 Bitter Campari,
5/10 Limoncello Toschi,
2/10 Vodka Keglevich Classica','Si prepara nello shaker con cubetti di ghiaccio. Agitare e servire nella coppetta da cocktail fredda. Guarnizioni fantasia.',382);
INSERT INTO "ricette" VALUES (25893,'Torly','Pesce','Cernia',4,'Luogo: Egitto.','500 G Filetto Di Cernia,
250 G Patate,
250 G Carote,
2 Bicchieri Sugo Di Pomodoro,
1 Bicchiere Acqua,
1 Spicchio Aglio,
2 Zucchine,
1 Cipolla Grande,
1/2 Peperone Verde,
1/2 Peperone Giallo,
Peperoncino,
Olio D''oliva,
Sale,
Pepe','Pulite il pesce, sfilettatelo e poi strofinatelo interamente con il sale. Pulite bene le verdure e tagliatele tutte a tocchetti non troppo grossi. Mettete il filetto di pesce in una padella insieme all''olio bollente e friggetelo da entrambi i lati. Toglietelo dalla padella quando sarà ben dorato e, nello stesso olio, mettete la cipolla affettata, l''aglio schiacciato, il sale, il pepe, il peperoncino, il sugo di pomodoro e l''acqua. Dopo 10 minuti aggiungete le verdure e fatele cuocere. Adagiate le verdure e il pesce in una pirofila e infornate per 10 minuti a 150 gradi.',1601);
INSERT INTO "ricette" VALUES (25894,'Torly (2)','Pesce','Branzino',4,'Luogo: Egitto.','500 G Filetto Di Branzino,
250 G Patate,
250 G Carote,
2 Bicchieri Sugo Di Pomodoro,
1 Bicchiere Acqua,
1 Spicchio Aglio,
2 Zucchine,
1 Cipolla Grande,
1/2 Peperone Verde,
1/2 Peperone Giallo,
Peperoncino,
Olio D''oliva,
Sale,
Pepe','Pulite il pesce, sfilettatelo e poi strofinatelo interamente con il sale. Pulite bene le verdure e tagliatele tutte a tocchetti non troppo grossi. Mettete il filetto di pesce in una padella insieme all''olio bollente e friggetelo da entrambi i lati. Toglietelo dalla padella quando sarà ben dorato e, nello stesso olio, mettete la cipolla affettata, l''aglio schiacciato, il sale, il pepe, il peperoncino, il sugo di pomodoro e l''acqua. Dopo 10 minuti aggiungete le verdure e fatele cuocere. Adagiate le verdure e il pesce in una pirofila e infornate per 10 minuti a 150 gradi.',1611);
INSERT INTO "ricette" VALUES (25895,'Tormento Di Mezzanotte','Bevande','Tequila',1,' -','3/10 Succo D''ananas Del Monte,
2/10 Vermouth Martini Dry,
1/10 Succo Di Lime,
4/10 Jose Cuervo Tequila,
Tonic Water Schweppes,
Per Guarnire,
1/2 Fetta Arancia,
1 Spirale Scorza Di Limone','Mescolare delicatamente i primi 4 ingredienti e completare con Tonic Water Schweppes. Guarnire con una spirale di buccia di limone, mezza fetta d''arancia e cannucce.',371);
INSERT INTO "ricette" VALUES (25896,'Tornado','Bevande','Whisky',1,' -','4/10 Whisky Ballantine''s,
3/10 Crema Cacao Scura Marie Brizard,
1/10 Vanilzucca,
2/10 Caffè Lavazza,
Per Completare:,
Panna Liquida,
Per Guarnire:,
Cacao In Polvere','Si prepara nello shaker. Servire nella classica coppetta da cocktail. Ultimare con lieve strato di panna liquida in superficie. Decorare con spolverata di cacao.',785);
INSERT INTO "ricette" VALUES (25897,'Tornado (2)','Bevande','Southern Comfort',1,' -','1/5 Succo D''arancia,
1/5 Apricot Brandy,
1/5 Gin,
2/5 Southern Comfort,
Per Servire:,
1 Scorza D''arancia,
1 Oliva','Agitare nel mixer con ghiaccio in cubetti. Servire nel calice basso, con una scorza d''arancia e un''oliva.',286);
INSERT INTO "ricette" VALUES (25898,'Toro Bravo','Bevande','Tequila',1,'Luogo: Messico.','2/3 Tequila,
1/3 Kahlua,
3 Gocce Succo Di Limone','In un mixer con ghiaccio a cubetti miscelare e servire nella coppetta da cocktail o in un bicchiere sour.',406);
INSERT INTO "ricette" VALUES (25899,'Toronto','Bevande','Whisky',1,' -','1/4 Fernet,
3/4 Whisky,
1 Spruzzo Angostura,
1/2 Cucchiaio Zucchero','Scuotere vigorosamente e a lungo nello shaker, con cubetti di ghiaccio.',366);
INSERT INTO "ricette" VALUES (25900,'Torpedo','Bevande','Cognac',1,' -','2/3 Calvados,
1/3 Cognac,
1 Spruzzo Gin','Scuotere nello shaker. Servire nel calice basso, con o senza ghiaccio.',319);
INSERT INTO "ricette" VALUES (25901,'Torre D''argento Champagne','Bevande','Vino Champagne',1,' -','1 Cucchiaino Cognac,
1 Cucchiaino Cointreau,
Vino Champagne Ben Ghiacciato,
1 Fetta Arancia,
1 Zolletta Zucchero,
1 Spruzzo Curacao Blu','Mettete nel flute o in un bicchiere a calice, che avrete provveduto a raffreddare in frigorifero, il cognac e il cointreau, poi riempite con lo champagne. Adagiate in superficie la fetta di arancia. Mettete la zolletta di zucchero in un cucchiaino, spruzzatela con il curacao blu, in modo che diventi azzurra, e appoggiatela sulla fetta di arancia.',186);
INSERT INTO "ricette" VALUES (25902,'Torre Di Melanzane Fredda','Contorno','Melanzane',4,' -','600 G Melanzane,
350 G Mozzarella,
4 Fette Pane Casereccio,
4 Pomodori Maturi,
1 Cipollotto,
Basilico,
Olio D''oliva,
Sale,
Pepe','Lavate le melanzane e tagliatele a fette alte mezzo centimetro. Mettetele sotto sale in un piatto inclinato e con un peso sopra per eliminare l''acqua amarognola. Dopo mezz''ora circa sciacquatele velocemente, asciugatele con cura, spennellatele con un po'' d''olio e fatele arrostire sulla griglia a fuoco vivace da entrambi i lati. Lavate, pelate, private dei semi i pomodori, tagliateli a fettine sottili e così pure la mozzarella e il cipollotto. Tostate leggermente le fette di pane, eliminate la crosta e sistematele su un piatto da portata profondo. Sopra distribuite uno strato di melanzane, salate e pepate. Continuate con uno di mozzarella, foglie di basilico, sale e pepe, poi un altro di pomodori con sale e pepe. Proseguite gli strati fino a esaurimento degli ingredienti, condite con olio versato a filo, distribuite qualche altra foglia di basilico. Lasciate riposare per un quarto d''ora e servite. Vini di accompagnamento: Riviera Ligure Di Ponente Vermentino DOC, Verdicchio Dei Castelli Di Jesi DOC, Guardiolo Bianco DOC.',2242);
INSERT INTO "ricette" VALUES (25903,'Torri Di Babele','Dessert','Anguria',4,'Preparazione: 40 minuti.','350 G Sorbetto Di Melone (v. Ricetta),
1 Anguria Matura,
2 Meloni Piuttosto Grandi,
Zucchero,
1 Bicchierino Rum','Preparate il ''Sorbetto di melone'' (v. Ricetta), dimezzando però le dosi. Tenete in frigorifero l''anguria e i meloni, fino a che saranno ben ghiacciati. Tagliate quindi dall''anguria quattro o cinque fette alte un dito e ricavate da queste, con un bicchiere da acqua capovolto, dodici dischi tutti uguali. Private i dischi di anguria dei semi, disponeteli in un piatto largo e spolverizzateli con dello zucchero. Prendete ora i meloni e tagliate anch''essi a fette molto larghe, che priverete della buccia; ricavate dalle fette otto dischi della stessa grandezza di quelli dell''anguria. Disponete i dischi di melone sopra quelli di anguria, spolverizzate con altro zucchero e irrorate con il rum. Lasciate quindi macerare per i ora. Trascorso questo tempo, estraete il sorbetto dal freezer. Procedete ora alla preparazione finale del dessert. Con l''aiuto dell''apposito utensile ricavate dall''anguria avanzata dodici palline e infilzatene tre alla volta in quattro spiedini. In un piatto da dolci componete le ''torri di Babele'' nella seguente maniera: sovrapponete un disco di melone, uno di anguria, uno di melone e infine un ultimo di anguria. Su questo adagiate una grossa pallottola del sorbetto di melone. Infilzate gli spiedini di anguria precedentemente preparati nelle pallottole di sorbetto e servite immediatamente. Si tratta di un dessert di grandissimo effetto.',1350);
INSERT INTO "ricette" VALUES (25904,'Torroncini','Dessert','Cioccolato',4,' -','100 G Nocciole Tostate A Granella,
100 G Mandorle Tostate A Granella,
100 G Miele Caldo,
300 G Cioccolato','Impastare nocciole, mandorle e miele e poi aggiungere il cioccolato fuso. Fare dei mucchietti su carta da forno, lasciare asciugare in frigo e servire.',3159);
INSERT INTO "ricette" VALUES (25905,'Torroncini Di Arachidi','Dessert','Arachidi',4,' -','250 G Arachidi Sgusciate,
320 G Miele,
3 Albumi D''uovo,
1 Cucchiaio Scorza D''arancia Grattugiata,
3 Gocce Succo Di Limone,
1 Pizzico Vaniglia In Polvere','Ponete gli albumi d''uovo in una casseruola e montateli a neve ben soda aggiungendo tre gocce di succo di limone. Incorporatevi quindi il miele, mescolando delicatamente per non smontare gli albumi e mettete la casseruola sul fuoco: fate cuocere il composto a calore dolcissimo per circa 2 ore, mescolando in continuazione con un cucchiaio di legno. Trascorso il tempo indicato aggiungete le arachidi, un cucchiaio di scorza d''arancia grattugiata e un pizzico di vaniglia in polvere. Amalgamate bene il tutto e trasferite il composto in una grande teglia foderata con carta oleata. Livellate la superficie con la lama di un coltello, facendo in modo che si formi uno strato spesso circa 2 cm. Lasciate raffreddare. Quando il torrone è ben freddo tagliatelo a pezzetti. Se non consumate in giornata tutto il quantitativo preparato, avvolgete i torroncini rimasti, uno ad uno, in fogli di carta stagnola e riponeteli in una scatola di latta dove si conserveranno fino a sei mesi. --- CONSIGLI. Questi deliziosi torroncini possono essere preparati, seguendo lo stesso procedimento, oltre che con le arachidi con altri tipi di frutta secca, quali nocciole, mandorle e gherigli di noci, usati singolarmente o mescolati fra loro.',2434);
INSERT INTO "ricette" VALUES (25906,'Torroncini Di Pasta Di Mandorle','Dessert','Mandorle',4,'Luogo: Ciociaria. Luogo: Lazio.','800 G Zucchero,
Acqua,
1000 G Mandorle Pelate,
1 Bustina Vaniglia,
1 Limone','Fare sciogliere a fuoco moderato in un polsonetto di rame 800 g di zucchero con due bicchieri di acqua. Poi aggiungere 1000 g di mandorle pelate e finemente tritate, 1 bustina di vaniglia e la buccia grattugiata di un limone. Girare continuamente il composto, sempre sul fuoco moderato, fin quando si staccherà dai bordi (circa 1 ora e più di cottura). Allora spianarlo su di una tavola infarinata, tenendolo spesso 2,5 cm. Lasciare raffredare, tagliare in pezzi di 10 cm x 3 cm e rivestire i torroncini, così ottenuti, con glassa di zucchero.',8904);
INSERT INTO "ricette" VALUES (25907,'Torrone','Dessert','Mandorle',8,' -','500 G Mandorle Pelate,
300 G Zucchero,
200 G Nocciole Pelate,
300 G Miele,
100 G Cedro E Arancia Canditi,
3 Albumi D''uovo,
2 Limoni,
Olio Di Mandorle','Fate cuocere il miele a bagnomaria per un''ora e mezzo, o fino a quando versandone un poco in acqua fredda, si formerà una lamina dura. Ponete in un altro tegame lo zucchero con 100 g d''acqua e fatelo cuocere a calore moderato fino a quando, versando nell''acqua una goccia del composto, si condenserà completamente. Montate a neve gli albumi, incorporateli al miele ancora sul fuoco, poi, mescolando sempre, unite lo zucchero, le mandorle, le nocciole leggermente tostate in forno, i canditi e la scorza grattugiata dei limoni. Distribuite il composto in una teglia rivestita di ostie, livellatelo con una spatola unta d''olio, copritelo con altre ostie e ponetevi sopra un peso. Lasciatelo indurire per un''ora, quindi tagliatelo a stecche larghe 8 cm, avvolgetele in carta oleata, poi nella stagnola e conservatele in vasi o in scatole di latta.',7219);
INSERT INTO "ricette" VALUES (25908,'Torrone (2)','Dessert','Miele',4,' -','500 G Miele,
330 G Nocciole,
330 G Mandorle,
330 G Pistacchi,
1 Limone,
Ostie','Tuffate le mandorle, le nocciole ed i pistacchi in acqua calda per pelarli meglio e dopo fateli asciugare in forno per dieci minuti. Fate sciogliere il miele in una casseruola fino a farlo bollire ed aggiungete mandorle, nocciole e pistacchi, mescolando col cucchiaio di legno. Su un piano di marmo disponete delle ostie e su queste versate il miele, sistematelo con una spatola di legno e lisciate la superficie con un limone tagliato a metà. Coprite con altre ostie e mettetevi un peso sopra lasciandolo raffreddare.',7587);
INSERT INTO "ricette" VALUES (25909,'Torrone Al Cioccolato','Dessert','Cioccolato',4,' -','750 G Nocciole Sgusciate,
400 G Zucchero,
300 G Miele,
270 G Cioccolato,
3 Uova,
Ostie','Tostare le nocciole e togliere la pellicina. Montare a neve gli albumi. Sul fuoco sciogliere 40 g di zucchero con 40 g di acqua. Quando diventa sciroppo unire il cioccolato tritato e scioglierlo mescolando. In un pentolino cuocere il miele a fuoco basso finché una goccia versata in acqua fredda si cristallizza. Far caramellare il restante zucchero con 1/2 bicchiere d''acqua e incorporarlo al miele. Mescolando unire albumi, cioccolato e nocciole. Versare il composto sulle ostie formando uno strato di 1,5 cm e coprire con altre ostie. Raffreddare.',9043);
INSERT INTO "ricette" VALUES (25910,'Torrone Con Noci E Fichi Secchi','Dessert','Noci',4,' -','600 G Fichi Secchi,
1500 G Miele,
600 G Gherigli Di Noci,
400 G Zucchero,
4 Albumi D''uovo,
Olio Di Mandorle,
1 Limone,
Cannella','Gli ingredienti sono per 1 torrone. Fate bollire il miele e fate proseguire la cottura a bagnomaria. Quando il miele avrà assunto un colore biancastro, unitevi gli albumi montati e portate avanti la cottura. Quando il miele risulterà indurito (fate la prova inserendo uno stecchino bagnato) aggregatevi la frutta secca tritata, la cannella e le bucce di limone grattugiato. Quando il composto sarà ben compatto, versatelo su un tagliere o marmo unto d''olio di mandorla e cercate di dargli una forma rettangolare alta circa 1 cm. Fate intiepidire l''impasto e tagliatelo a pezzi, avvolgeteli con fogli di carta argentata e posateli in una scatola di latta.',12259);
INSERT INTO "ricette" VALUES (25911,'Torrone D''alba','Dessert','Miele',4,' -','1000 G Miele,
200 G Zucchero,
1000 G Mandorle,
2 Albumi D''uovo,
Ostie','Tuffate le mandorle in acqua calda per pelarle e poi fatele asciugare in forno per dieci minuti. Fate sciogliere lo zucchero con mezzo bicchiere d''acqua, poi togliete dal fuoco ed aggiungete il miele e continuate la cottura a bagnomaria. Unite, ora, gli albumi montati a neve ed incorporateli delicatamente. Infine unite le mandorle e mescolate. Foderate uno stampo rettangolare con le ostie, versatevi il torrone e coprite con altre ostie.',9692);
INSERT INTO "ricette" VALUES (25912,'Torrone Di Cioccolata','Dessert','Cioccolata Amara',4,' -','230 G Cioccolata Amara Spezzettata,
4 Cucchiai Rum,
230 G Burro,
30 G Zucchero A Velo,
2 Tuorli D''uovo,
130 G Nocciole Tritate Grosse,
4 Albumi D''uovo,
12 Biscotti Secchi Tipo Marie (spezzettate)','Imburrare leggermente uno stampo liscio della capacità di un litro. Fate sciogliere il cioccolato nel rum a bagnomaria, mescolando. Quando il cioccolato sarà ben sciolto, toglietelo dal fuoco e lasciatelo raffreddare. Lavorate in una terrina il burro con lo zucchero e, quando sarà ben montato, unitevi i tuorli, uno alla volta, e aggiungetevi le nocciole e la cioccolata sciolta. Sbattete gli albumi a neve soda e uniteli al resto, aggiungendo poi anche i biscotti spezzettati. Versate il composto nello stampo, copritelo con carta d''alluminio e passatelo nel frigo per alcune ore prima di servirlo.',4902);
INSERT INTO "ricette" VALUES (25913,'Torrone Di Fichi','Dessert','Fichi Secchi',4,'Luogo: Abruzzo.','400 G Fichi Secchi,
250 G Gherigli Di Noci,
500 G Miele,
1 Scorza Limone,
200 G Zucchero,
2 Albumi D''uovo,
1 Presa Cannella In Polvere,
Olio D''oliva','In un polsonetto sciogliere il miele a bagnomaria, unire gli albumi montati a neve e levare dal fuoco. Aggiungere i fichi e le noci tritati, unire una presa di cannella e la scorza grattugiata e infine aggiungere lo zucchero. Impastare accuratamente il tutto. Oliare bene un ripiano di marmo e versarvi il composto; spianarlo con un coltello e lasciarlo raffreddare. Tagliare il torrone a rettangoli e conservarli in carta d''alluminio fino al momento di servire.',5734);
INSERT INTO "ricette" VALUES (25914,'Torrone Di Fichi Secchi','Dessert','Fichi Secchi',4,' -','1500 G Miele,
750 G Gherigli Di Noci,
750 G Fichi Secchi,
450 G Zucchero,
Cannella,
1 Limone,
4 Albumi D''uovo,
Olio Di Mandorle','Portare il miele ad ebollizione su fuoco basso e proseguire a bagnomaria. Quando diventa bianco unire gli albumi montati a neve e cuocere ancora mescolando sempre. È pronto quando una goccia buttata in acqua fredda si cristallizza. Unire i gherigli scottati, pelati e triturati ed i fichi a pezzettini. Cospargere di cannella ed unire zucchero e scorza di limone grattugiata far addensare l''impasto mescolando e versarlo su un piano unto d''olio di mandorle. Dargli una forma rettangolare alta 1-1,5 cm, tagliarlo, farlo freddare.',13849);
INSERT INTO "ricette" VALUES (25915,'Torrone Gelato','Dessert','Mandorle',4,'Luogo: Sicilia.','1000 G Zucchero,
100 G Mandorle Tritate,
100 G Pistacchi,
200 G Mandorle Intere,
100 G Frutta Candita,
200 G Cioccolato Fondente,
100 G Acqua,
1 Pizzico Cannella','In un tegame, sciogliere a fiamma bassa lo zucchero nell''acqua con un pizzico di cannella, fino a che caramella. Lasciar raffreddare e unire le mandorle tritate, le mandorle intere e il cioccolato a pezzi, i pistacchi e la frutta candita. Versare in uno stampo rettangolare, foderato con carta forno e mettere in freezer per una giornata intera.',7673);
INSERT INTO "ricette" VALUES (25916,'Torrone Sardo','Dessert','Miele',4,'Luogo: Sardegna.','500 G Miele,
2 Albumi D''uovo,
500 G Mandorle,
Per Rivestire Le Pareti:,
Ostie (nevole)','Sbollentare le mandorle per privarle della pellicina; tritarle e tostarle in forno. In un tegame (meglio se di rame) mettere il miele e gli albumi e accendere la fiamma bassissima, lavorando continuamente con un cucchiaio di legno per 45 minuti circa. Aggiungere le mandorle e continuare a lavorare. Dopo mezz''ora rovesciare il composto nelle formine rivestite di nevole (ostie) di farina di grano, appena inumidite; far freddare il torrone.',4619);
INSERT INTO "ricette" VALUES (25917,'Torta ''bonissima''','Dessert','Noci',8,' -','Per La Pasta Frolla:,
500 G Farina,
250 G Burro,
250 G Zucchero,
6 Tuorli D''uovo,
1/2 Limone (scorza Grattugiata),
1 Pizzico Sale,
Per Il Ripieno:,
300 G Gherigli Di Noci,
250 G Miele,
1/2 Bicchierino Rum,
Per Lo Stampo E La Spianatoia:,
Burro,
Farina','Per la pasta frolla, mettete sulla spianatoia la farina con il burro, morbido e a pezzetti. Impastate brevemente con le mani, rifate la fontana,al centro ponete un pizzico di sale, lo zucchero, 5 tuorli e una grattatina di buccia di limone. Impastate rapidamente, coprite la pasta con la pellicola trasparente e lasciatela riposare per almeno 30 minuti. Stendetela sulla spianatoia leggermente infarinata allo spessore di circa mezzo centimetro. Dividetela in due e rivestite con una metà uno stampo per crostate a bordo scanalato, bene imburrato. Scottate in acqua bollente i gherigli, sbucciateli e tritateli. In una ciotola, mescolateli col miele ed il rum. Versate il composto sulla base del dolce, stendetelo, coprite con la restante pasta, tagliando l''eccesso e sigillando lungo il bordo. Pennellate la superficie con un tuorlo, cuocete nel forno a 180 gradi per circa 40 minuti. Servite la torta fredda. Un tempo si copriva di cioccolato fondente o di glassa bianca di zucchero.',8903);
INSERT INTO "ricette" VALUES (25918,'Torta Agli Amaretti','Dessert','Biscotti Amaretti',4,' -','100 G Burro,
100 G Zucchero,
100 G Farina,
125 G Biscotti Amaretti,
2 Uova,
1 Cucchiaino Cacao Amaro,
1 Cucchiaino Lievito Per Dolci,
1 Pizzico Cannella In Polvere,
1 Bicchierino Rum,
Zucchero A Velo','Far ammorbidire il burro a temperatura ambiente per circa 30 minuti, lavorarlo con un cucchiaio di legno fino a renderlo spumoso, incorporarvi i tuorli e quando il composto sarà omogeneo unire amaretti sbriciolati, cacao, rum, cannella, farina e lievito. Lavorare bene l''impasto ed aggiungere infine gli albumi montati a neve. Versare il composto in una tortiera ed infornare a 200 gradi per 30 minuti. Cospargere di zucchero a velo.',2502);
INSERT INTO "ricette" VALUES (25919,'Torta Ai Broccoletti','Antipasto','Broccoletti',6,' -','300 G Pasta Sfoglia Surgelata,
500 G Broccoletti Romani,
250 G Formaggio Fontina Dolce Grattugiato,
30 G Burro,
Besciamella,
1 Uovo,
1 Pizzico Noce Moscata,
Sale','Scongelate la pasta a temperatura ambiente. Pulite i broccoletti eliminando la parte più dura dei gambi e sbollentateli in acqua salata per circa 5 minuti. Sgocciolateli, tagliuzzateli lasciando intera l''infiorescenza e insaporiteli in un tegame con il burro e poco sale. Stendete a sfoglia la pasta e adagiatela in una teglia foderata di carta da forno facendola risalire anche lungo il bordo. Bucherellate il fondo con i rebbi di una forchetta e cospargetelo con metà fontina mescolata a un pizzico di noce moscata. Adagiatevi sopra i broccoletti e ricopriteli con la besciamella nella quale avete incorporato la restante fontina. Ripiegate sul ripieno la pasta del bordo e spennellatela con il tuorlo sbattuto. Cuocete in forno preriscaldato a 180 gradi per circa 40 minuti. Vini di accompagnamento: Trentino Bianco DOC, Val D''Arbia DOC, Martina Franca DOC.',2593);
INSERT INTO "ricette" VALUES (25920,'Torta Ai Fiori Di Mandorlo','Dessert','Fiori Di Mandorlo',6,' -','350 G Farina,
160 G Zucchero,
4 Uova,
150 G Fragoline,
2 Cucchiai Fiori Di Mandorlo,
Gelatina Di Fragole,
60 G Mandorle Sbucciate,
1 Bustina Lievito','Impastate farina, uova, zucchero, mandorle tritate, lievito e i fiori di mandorlo. Imburrate una teglia, disponetevi la pasta tirata a sfoglia e cuocete mezz''ora circa a 200 gradi. Trasferite su un piatto, spalmate la superficie con la gelatina di fragole; sopra le fragole tagliate a metà.',2756);
INSERT INTO "ricette" VALUES (25921,'Torta Ai Formaggi','Antipasto','Formaggio Parmigiano',4,' -','50 G Farina,
25 Cl Latte,
100 G Formaggio Parmigiano,
100 G Formaggio Groviera,
3 Uova,
Sale,
Pepe,
30 G Burro','Stemperare la farina con il latte evitando la formazione di grumi. Aggiungere le uova sbattute con sale e pepe e i formaggi grattugiati. Ungere un recipiente che vada in forno, versarvi l''impasto e cuocere in forno a calore moderato durante i primi 15 minuti, dopo di che, poco per volta, alzare il fuoco. Dopo circa 30 minuti, togliere la torta dal forno e lasciarla raffreddare.',1573);
INSERT INTO "ricette" VALUES (25922,'Torta Ai Lamponi','Dessert','Lamponi',4,' -','200 G Farina,
6 Cucchiai Zucchero,
1 Pizzico Sale,
1 Uovo,
1/2 Bustina Lievito In Polvere,
80 G Burro,
2 Cucchiai Latte,
2 Cucchiai Panna,
500 G Lamponi','Far fondere 60 g di burro con il latte in una casseruolina, a fuoco basso; sbattere in una terrina 4 cucchiai di zucchero, l''uovo e 1 pizzico di sale; incorporare a poco a poco metà della farina, la panna, il resto della farina, il lievito ed infine il burro fuso ma tiepido. Foderare una tortiera con un foglio d''alluminio imburrato; versarvi la pasta e posarvi sopra i lamponi, cospargere con il resto dello zucchero e far cuocere in forno a temperatura media per 45 minuti.',1917);
INSERT INTO "ricette" VALUES (25923,'Torta Ai Peperoni','Contorno','Peperoni',8,' -','Per La Pasta:,
300 G Farina,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Per Il Ripieno:,
4 Peperoni Gialli,
1 Cipolla,
200 G Ricotta Di Pecora,
2 Uova,
2 Cucchiai Formaggio Parmigiano Grattugiato,
2 Cucchiai Olio D''oliva Extra-vergine,
Basilico,
Sale,
Pepe','Lavate i peperoni, divideteli in due, privateli del gambo, dei semi e dei filamenti bianchi interni e tagliateli a striscioline. Scaldate l''olio in un tegame e fatevi appassire la cipolla affettata sottilmente. Quando comincia a prendere colore, unitevi i peperoni, insaporite con sale e pepe e lasciateli cuocere a fuoco dolce e a recipiente coperto per una ventina di minuti. Controllate spesso la cottura: i peperoni dovrebbero cuocere con la sola acqua di vegetazione, senza aggiunta di liquido ma, se tendessero ad attaccare, potete aggiungere un cucchiaio d''acqua. Quando sono cotti e ben asciutti, spegnete la fiamma e mentre si intiepidiscono, preparate la pasta. Setacciate la farina sulla spianatoia, fate la fontana e versatevi l''olio, un pizzico di sale e un bicchiere scarso di acqua tiepida. Cominciate ad amalgamare gli ingredienti con una forchetta e poi lavorate la pasta con le mani fino ad averla liscia ed elastica ma abbastanza morbida. Raccoglietela a palla, copritela con un canovaccio piegato in quattro e preparate il ripieno. Sbattete le uova in una ciotola unitevi la ricotta, il parmigiano grattugiato, sale e pepe e amalgamate bene; aggiungete tutto il contenuto della padella e completate con cinque o sei foglie di basilico spezzettate. Dividete la pasta in due parti di cui uno poco più grande dell''altro e, con il mattarello, stendete il pezzo più grande in una sfoglia sottile. Ungete leggermente una tortiera da crostate [del diametro di 28 cm] e foderatela con la sfoglia preparata. Versatevi il composto di peperoni, pareggiatelo quindi stendete anche il secondo pezzo di pasta e appoggiatelo sul ripieno. Con un coltellino ritagliate la pasta in eccesso e pizzicatela tutto intorno per unire i due dischi. Con un pennello ungete leggermente la superficie della torta, bucatela in più punti con i denti di una forchetta e mettetela nel forno già scaldato a 200 gradi lasciandola cuocere per circa tre quarti d''ora. Servitela tiepida o fredda.',2865);
INSERT INTO "ricette" VALUES (25924,'Torta Ai Pinoli','Dessert','Pinoli',4,' -','200 G Pinoli,
150 G Farina,
50 G Burro,
300 G Zucchero,
9 Uova,
1 Limone,
1 Bicchierino Rum,
3 Cucchiai Marmellata Di Pesche','Fare la pasta con burro, farina, zucchero, scorza di limone un uovo intero. Lasciare riposare per trenta minuti. Tritare metà pinoli e unirli al rum in una terrina. Aggiungere 8 tuorli e 250 g di zucchero. Mescolare ed unire 20 g di farina. Montare a parte i bianchi d''uovo a neve ed unirli. Stendere la pasta col mattarello infarinato. Foderare la pirofila imburrata e infarinata. Mettere sulla pasta il composto di pinoli. Infornare a 200 gradi e cuocere per 40 minuti. Raffreddare la torta per 2 ore. Cospargere di marmellata e decorare con pinoli interi.',4274);
INSERT INTO "ricette" VALUES (25925,'Torta Ai Pistacchi','Dessert','Pistacchi',6,' -','400 G Farina,
200 G Zucchero,
2 Cucchiai Zucchero A Velo,
4 Uova,
1 Bustina Lievito,
1 Pizzico Sale,
Burro Per La Teglia,
Farina Per La Teglia,
80 G Pistacchi Sgusciati,
1 Bicchiere Latte,
100 G Marmellata Di Albicocche,
1 Bicchiere Olio D''oliva','Private i pistacchi della pellicina, sfregandoli fra le mani, poi tritateli finemente. Sbattete le uova in una terrina assieme allo zucchero, servendovi di una frusta, fino ad ottenere un composto spumoso. Aggiungete l''olio d''oliva, il latte e una presa di sale, mescolate con un cucchiaio di legno, poi unite anche i pistacchi tritati, la farina e il lievito. Lavorate il composto per una decina di minuti, in modo da renderlo gonfio e omogeneo, quindi trasferitelo in una teglia rotonda, imburrata e infarinata, e livellatene la superficie. Fate cuocere la torta nel forno preriscaldato (180 gradi) per circa 40 minuti. Trascorso questo tempo, togliete il dolce dal forno, sformatelo su un piatto di portata, lasciatelo raffreddare, infine ricopritelo con la marmellata di albicocche, cospargetelo con lo zucchero a velo e servite.',5050);
INSERT INTO "ricette" VALUES (25926,'Torta Ai Pistacchi (2)','Dessert','Pistacchi',6,' -','150 G Farina,
180 G Zucchero,
4 Uova,
100 G Burro,
1 Bustina Lievito,
1 Bicchiere Latte,
Marmellata Di Pesche,
250 G Pistacchi','Sbattere i tuorli con lo zucchero fino a renderli spumosi, unirvi il burro fuso, quindi incorporare poco alla volta, la farina alternata al latte. Continuare a sbattere, poi unire il lievito, gli albumi montati a neve e 70 g di pistacchi tritati. Imburrare una pirofila, spolverizzarla di farina, versarvi dentro il composto e metterla in forno caldo a 180 gradi per 45 minuti. Una volta raffreddata, ricoprire la superficie con la marmellata di pesche e distribuirvi sopra i rimanenti pistacchi tritati grossolanamente.',4170);
INSERT INTO "ricette" VALUES (25927,'Torta Al Bourbon','Dessert','Biscotti Amaretti',4,' -','450 G Biscotti Amaretti Sbriciolati,
1 Tazza Bourbon,
2 Tazze Burro,
1/2 Tazza Zucchero,
1/2 Tazza Zucchero Semolato,
12 Uova,
100 G Cioccolato Amaro Fuso,
1 Cucchiaino Vaniglia,
1 Tazza Noci Tritate,
12 Biscotti Savoiardi (ognuno Diviso In 2),
Panna Montata','Inzuppate gli amaretti nel bourbon. Lavorate burro e zucchero. Montate i tuorli e il cioccolato fuso. Aggiungete vaniglia e noci tritate. Montate gli albumi in neve ben soda e aggiungeteli al composto di cioccolato. Foderate i lati di uno stampo con i savoiardi. Coprite il fondo dello stampo con 1 strato di amaretti inzuppati nel bourbon. Fate un altro strato col composto di cioccolato. Alternate gli strati fino a che non avrete usato tutti gli amaretti e il composto di cioccolato. Refrigerate per 1 notte. Prima di servire rimuovete i lati dello stampo e guarnite con panna montata.',6508);
INSERT INTO "ricette" VALUES (25928,'Torta Al Cacao','Dessert','Cacao',6,' -','300 G Farina,
150 G Zucchero,
100 G Burro,
3 Uova,
1 Bicchiere Latte,
100 G Cacao,
1 Pizzico Sale,
1 Bustina Lievito','Sbattere in una terrina i tuorli d''uovo con lo zucchero, aggiungervi gradatamente il burro liquefatto a freddo, il cacao, il latte, la farina, il sale, gli albumi sbattuti a neve e infine il lievito, avendo cura di amalgamarlo bene. Travasare in una teglia imburrata e spolverata di farina bianca, passarla subito nel forno caldo e lasciarvela per 30 minuti a temperatura moderata e senza aprire lo sportello.',3023);
INSERT INTO "ricette" VALUES (25929,'Torta Al Cacao (2)','Dessert','Cacao',2,' -','150 G Burro (o Margarina),
175 G Zucchero,
120 G Farina,
150 G Latte,
75 G Cacao,
3 Uova,
1 Bustina Lievito,
Per Servire:,
Panna (o Zucchero A Velo)','Lavorare i tuorli con lo zucchero, aggiungere poi il burro fuso e la farina setacciata. In un''altra terrina montare a neve gli albumi ed unire i 2 composti. Nel contempo riscaldare il latte in un pentolino dove si provvederà a sciogliere il cacao, che non appena raffreddato verrà versato nel composto precedente. Al termine incorporare il lievito, lavorare il tutto e versare in una teglia precedentemente imburrata ed infornare a 180 gradi. Far riposare prima di servire. Servire fredda, con panna o cosparsa di zucchero a velo.',3033);
INSERT INTO "ricette" VALUES (25930,'Torta Al Cacao Morbidissima','Dessert','Cacao Amaro',4,' -','300 G Farina,
60 G Cacao Amaro,
250 G Latte,
300 G Zucchero,
3 Uova,
1 Bustina Lievito','Impastare tutti gli ingredienti tranne il latte e la bustina di lievito. Intiepidire il latte e unirlo poco per volta tenendone indietro un pochino. Sciogliere il lievito nel latte tenuto da parte (attenzione usate un contenitore alto perchè fa una schiuma tipo birra). Versare il composto in una teglia imburrata e infarinata. Cuocere in forno a 180 gradi per 45 minuti.',2758);
INSERT INTO "ricette" VALUES (25931,'Torta Al Caffè','Dessert','Caffè',4,' -','3 Uova,
300 G Zucchero A Velo,
300 G Burro,
150 G Cacao Amaro,
600 G Biscotti Secchi,
Caffè Forte','Ammorbidire il burro a temperatura ambiente per almeno 1 ora. Lavorarlo con un cucchiaio di legno unendo, poco per volta, lo zucchero. Quando è ben gonfio e cremoso aggiungere le uova, una alla volta, continuando a lavorare il composto. In un vassoio fare uno strato di biscotti imbevuti di caffè, ricoprirlo di crema e spolverizzare con il cacao. Continuare così fino ad esaurimento degli ingredienti. Tenere in frigo per circa 2 ore prima di servire.',6717);
INSERT INTO "ricette" VALUES (25932,'Torta Al Caffè (2)','Dessert','Caffè',4,' -','3 Uova,
300 G Zucchero A Velo,
300 G Burro,
150 G Cacao Amaro,
600 G Biscotti Secchi,
Caffè Caldo','Ammorbidire il burro a temperatura ambiente, poi lavorarlo con un cucchiaio di legno unendo, poco per volta, lo zucchero a velo. Aggiungere le uova una per volta continuando a lavorare l''impasto. Su un vassoio fare uno strato di biscotti inzuppati nel caffè, uno strato di crema e uno di cacao. Proseguire fino ad esaurimento degli ingredienti. Tenere in frigo per 2 ore prima di servire.',6717);
INSERT INTO "ricette" VALUES (25933,'Torta Al Caffè (3)','Dessert','Caffè',4,' -','120 G Farina,
4 Uova,
200 G Zucchero,
200 G Burro,
80 G Fecola,
1 Tazzina Caffè,
1 Bustina Lievito,
Alcuni Chicchi Caffè,
Crema Al Caffè','Montare lo zucchero con il burro, unire poi la farina e la fecola, il caffè e le uova (una per volta). Mescolare bene e aggiungere il lievito. Versare il composto in una teglia imburrata e infarinata. Quindi infornare per 40 minuti a 180 gradi. Quando la torta si è raffreddata guarnirla con la crema al caffè e con chicchi di caffè.',3536);
INSERT INTO "ricette" VALUES (25934,'Torta Al Caffè (4)','Dessert','Caffè Macinato',4,' -','1 Disco Pan Di Spagna (dischi Da 400 G),
400 G Ricotta,
150 G Zucchero,
60 G Caffè Macinato,
1 Bicchiere Maraschino,
1 Bicchiere Rum,
1 Bicchierino Liquore Al Caffè','Preparate innanzitutto la crema: mettete la ricotta in una terrina e lavoratela con una forchetta, poi unitevi lo zucchero e mescolate ancora; versate il composto in una casseruola e fatelo scaldare a bagnomaria, fino a quando si leverà un leggero bollore. Togliete quindi la crema dal fuoco e lasciatela raffreddare prima di utilizzarla per farcire la torta. Tagliate il pan di Spagna in tre strati. imbevete il disco di base, posto su un piatto da portata, con il maraschino misto di un''uguale quantità di acqua, spalmatelo con poco meno di un terzo della crema alla ricotta e cospargete con un terzo di polvere di caffè. Coprite con il disco centrale e ripetete l''operazione, bagnando però con il rum misto ad acqua. Spruzzate il lato interno dei disco superiore con il liquore al caffè e ponetelo, delicatamente per non romperlo, sul resto della torta; quindi completate il dolce, spalmandolo in superficie e lateralmente con la crema rimasta. Ponete la torta in frigorifero per almeno 3 ore. Prima di servirla, spolverizzatela con la polvere di caffè rimasta ed eventualmente decoratela con ciliegine candite e chicchi di caffè.',3781);
INSERT INTO "ricette" VALUES (25935,'Torta Al Caffè (5)','Dessert','Caffè',4,' -','120 G Farina,
4 Uova,
200 G Zucchero,
200 G Burro,
80 G Fecola,
1 Tazzina Caffè,
1 Bustina Lievito Bertolini','In una ciotola capiente, versate lo zucchero e aggiungete il burro che avrete tirato fuori dal frigorifero almeno 10 minuti prima dell''uso. Mescolate con cura fino a quando non otterrete un composto cremoso e poco per volta unite la farina e la fecola. Sempre mescolando unite il caffè le uova facendo attenzione ad incorporarle una per volta. Continuate a girare il composto energicamente servendovi di un cucchiaio di legno e per finire aggiungete il lievito che farete sciogliere ed amalgamare al resto. Nel frattempo imburrate ed infarinate una teglia e versate il composto uniformemente. Infornate quindi per circa 40 minuti a 180 gradi controllando di tanto in tanto, la cottura. Suggerimento: quando la torta si sarà raffreddata potrete guarnirla con della crema al caffè o semplicemente servirla spolverizzandola con zucchero a velo vanigliato e polvere di caffè.',3334);
INSERT INTO "ricette" VALUES (25936,'Torta Al Caffè (6)','Dessert','Caffè Forte',4,' -','2 Uova,
130 G Zucchero,
100 G Burro,
100 G Farina,
200 G Semolino,
1 Bicchiere Caffè Forte,
10 Gherigli Di Noci,
1 Bustina Lievito,
Per Ungere Lo Stampo:,
Burro','In una ciotola sbattere le uova con lo zucchero fino a che diventeranno spumose; poi unire il burro e montare il composto, finché risulterà cremoso. Unire a pioggia la farina e il semolino, sempre mescolando e alternandoli con il caffè, versato poco alla volta. Infine unire il lievito. Rovesciare il composto in uno stampo imburrato. Cospargere la superficie della torta con i gherigli di noci e cuocere in forno caldo a 200 gradi per 45 minuti',3898);
INSERT INTO "ricette" VALUES (25937,'Torta Al Cioccolato','Dessert','Cioccolato',6,' -','200 G Zucchero,
200 G Burro,
150 G Farina,
150 G Biscotti Amaretti,
50 G Cioccolato,
4 Uova,
3 Cucchiaini Lievito','Lavorare il burro e lo zucchero come una crema soffice; unite i tuorli e la farina poco alla volta, poi gli amaretti sbriciolati, il cioccolato tritato e infine gli albumi montati a neve e il lievito. Cuocere a 180 gradi per 45 minuti.',4185);
INSERT INTO "ricette" VALUES (25938,'Torta Al Cioccolato (2)','Dessert','Cioccolato',8,' -','170 G Burro A Temperatura Ambiente,
150 G Zucchero,
310 G Cioccolato Fondente,
6 Uova,
225 G Farina Setacciata,
1 Vasetto Gelatina Di Albicocche,
2 Cucchiai Latte,
Alcuni Cucchiai Zucchero A Velo,
1 Bicchierino Rum','Sciogliete sul fuoco il cioccolato (170 g) insieme a due cucchiai di latte mescolando con un cucchiaio. Montate a neve fermissima i 6 albumi. In una terrina sbattete a spuma il burro con lo zucchero, poi unitevi poco alla volta il cioccolato sciolto e tiepido, e i tuorli d''uova uno alla volta. Mescolatevi molto delicatamente la farina (meglio usare uno spargifarina o un setaccio) e gli albumi montati a neve. Versate il composto in una tortiera (larga circa 24 cm) imburrata e infarinata. Far cuocere in formo già caldo (200 gradi) per circa 30 minuti. Togliere dal forno, sformare e lasciare raffreddare. Tagliare la torta in due dischi (si può usare un filo resistente, che secondo me viene meglio che col coltello). Spennellare l''interno del disco di sotto con il rum, poi spalmarci sopra la gelatina di albicocche, poi ancora un po'' di rum. Chiudere con l''altro disco. Preparate la glassa facendo sciogliere la cioccolata (140 g) grattugiata a bagnomaria con lo zucchero a velo e con tanta acqua calda quanta ne servirà per ottenere una pasta densa ma colante e liscia. Ricoprite la torta con la glassa. Occorrono circa 3 ore (raffreddamenti compresi) e molta pazienza.',5371);
INSERT INTO "ricette" VALUES (25939,'Torta Al Cioccolato (3)','Dessert','Cioccolato',6,' -','400 G Farina,
250 G Zucchero,
1 Bustina Lievito,
100 G Cioccolato Fondente,
50 G Burro,
3 Uova,
1 Bustina Vaniglia,
1/2 Tazzina Caffè,
Rum','Versare lentamente sul cioccolato 1/2 tazza di acqua bollente e mescolare fino a scioglierlo. Far raffreddare e unire la farina, lo zucchero e il lievito, mescolare e unire il burro, il rum, le uova sbattute con la vaniglia, il latte e il caffè. Versare il composto in una teglia imburrata e infornare a 180 gradi per 1 ora.',3736);
INSERT INTO "ricette" VALUES (25940,'Torta Al Cioccolato (4)','Dessert','Cioccolato',8,' -','250 G Farina,
6 Uova,
250 G Zucchero,
300 G Cioccolato Fondente,
1/2 Bicchiere Latte,
250 G Margarina,
2 Cucchiaini Caffè Solubile,
100 G Zucchero A Velo,
100 G Cacao Amaro,
60 G Burro','In una fondina, lavorate a crema i tuorli con lo zucchero. Ottenuto un composto chiaro, gonfio e schiumoso, incorporatevi un miscuglio ben lavorato di cacao, margarina e caffè. Aggiungete il latte e gli albumi a neve; spargendola a manciate, incorporate la farina e battete il tutto fino a renderlo uniforme. Ungete una teglia di circa 24 cm di diametro e versatevi il preparato. Ponetela in forno preriscaldato a 190 gradi per 45 minuti. Quando la torta sarà cotta e intiepidita, ricopritela con una glassa di zucchero a velo, cioccolato, burro e acqua fredda (4 cucchiai). Levigatene la superficie e lasciate rassodare la copertura.',7167);
INSERT INTO "ricette" VALUES (25941,'Torta Al Cioccolato (5)','Dessert','Cioccolato',4,' -','200 G Zucchero,
50 G Burro,
150 G Farina,
6 Uova,
80 G Cacao In Polvere,
1 Pizzico Cannella','Setacciate insieme la farina e il cacao con un pizzico di cannella. Intanto, a bagnomaria, battete le uova con lo zucchero fino a farne una crema densa e liscia, poi togliete la pentola dall''acqua ed aggiungete farina e cacao. Amalgamate bene tutto ed unite il burro fuso, mescolate ancora e versate il composto in uno stampo imburrato ed infarinato. Infornate per 30-40 minuti a teniperatura media.',2479);
INSERT INTO "ricette" VALUES (25942,'Torta Al Cioccolato (6)','Dessert','Cioccolato',6,' -','100 G Cioccolato Fondente,
100 G Farina,
150 G Zucchero,
3 Uova,
50 G Burro,
1 Pizzico Sale','In un tegamino mettete il burro e il cioccolato spezzettati e lasciateli sciogliere a bagnomaria lavorandoli con una frusta fino a ottenere un composto liscio e omogeneo. In una larga ciotola sbattete le uova con lo zucchero, incorporatevi la farina setacciata e un pizzico di sale, poi amalgamate il tutto alla crema di cioccolato. Lavorate il composto per circa 10 minuti e versatelo in uno stampo imburrato. Cuocete in forno preriscaldato a 160 gradi per 20 minuti. Ritirate, fate raffreddare, sformate. Servite la torta con panna montata. Vini di accompagnamento: la tannicità del cioccolato contrasta con tutti i vini, mentre provocante e piacevole sarà l''abbinamento con Vermouth rosso o Barolo chinato.',2128);
INSERT INTO "ricette" VALUES (25943,'Torta Al Cioccolato (7)','Dessert','Cacao Amaro',6,' -','3 Uova,
200 G Zucchero,
100 G Burro,
75 G Farina,
75 G Fecola,
75 G Cacao Amaro,
1 Bustina Lievito,
1 Bustina Zucchero Vanigliato,
1 Bicchiere Latte,
Sale,
Per La Glassa:,
2 Albumi D''uovo,
350 G Zucchero,
1 Bustina Zucchero Vanigliato,
6 Cucchiai Acqua','Prendete le 3 uova e dividete il tuorlo dall''albume, quest''ultimo montatelo a neve. In un piatto sbattete i tuorli e unite lo zucchero, il burro sciolto, la fecola, la farina, il cacao, il lievito, lo zucchero vanigliato, il latte, un po'' di sale e gli albumi a neve. Mettete il tutto in una tortiera, che avrete precedentemente imburrato e lasciate cuocere per 45 minuti. Intanto preparate la glassa mettendo, in un recipiente a bagnomaria i due albumi, lo zucchero, lo zucchero vanigliato e l''acqua. Sbattete tutto per 8 minuti o comunque fino a quando la glassa diventi soda. Togliete il dolce dal forno, tagliatelo in tre parti orizzontali e farcitelo con una parte della glassa, il resto lo adopererete per ricoprire il dolce.',4089);
INSERT INTO "ricette" VALUES (25944,'Torta Al Cioccolato (8)','Dessert','Cioccolato Fondente',4,' -','125 G Cioccolato Fondente,
5 Uova,
250 G Zucchero Semolato,
125 G Burro Ammorbidito,
125 G Farina Setacciata','Sbattere i tuorli con lo zucchero fino a ottenere una miscela densa. Aggiungere il burro e il cioccolato e continuare a sbattere unendo poco alla volta la farina. Incorporare gli albumi montati e versare il composto in una tortiera imburrata. Cuocere in forno già caldo a 180 gradi per 30 minuti. Capovolgere la torta su una griglia e lasciar raffreddare.',3490);
INSERT INTO "ricette" VALUES (25945,'Torta Al Cioccolato E Alle Pere','Dessert','Pere',8,' -','200 G Farina,
150 G Burro,
80 G Zucchero,
4 Pere,
125 G Cioccolato Fondente,
10 Cl Panna,
25 G Mandorle Pelate,
Grand Marnier,
Sale','Fate una pasta brisée con la farina, 100 g di burro, 1/2 bicchiere d''acqua, un pizzico di sale e un cucchiaino di zucchero. Lasciatela riposare un''ora. Nel frattempo, tagliate a metà le pere, eliminate il torsolo, sbucciatele, cospargetele di zucchero, spruzzatele con il Grand Marnier e lasciate macerare. Stendete la pasta a disco dello spessore di mezzo centimetro. Adagiatelo in uno stampo da torta, modellatevi sopra un foglio d''alluminio, cospargete di fagioli secchi e cuocete per 10 minuti in forno preriscaldato a 180 gradi. Ritirate, eliminate carta e fagioli. Distribuite sulla pasta le mezze pere. Continuate la cottura a 180 gradi fino a quando la pasta diventa di colore dorato. Ritirate, fate raffreddare. Nel frattempo spezzettate il cioccolato, raccoglietelo in un tegamino, aggiungete un cucchiaio d''acqua e fate fondere a fuoco basso. Appena liquefatto aggiungete 50 g di burro e mescolate fino a ottenere una crema molto liscia. Ritirate e lasciate raffreddare. Montate la panna e incorporatela alla crema di cioccolato. Versate sulla torta, cospargetela di mandorle tritate e servite. Vini di accompagnamento: l''abbinamento ideale sarà con i vini ottenuti da uve passite o liquorosi: Recioto Della Valpolicella Liquoroso DOC, Aleatico Di Gradoli Liquoroso DOC, Moscato Passito Di Pantelleria Liquoroso Extra DOC.',3741);
INSERT INTO "ricette" VALUES (25946,'Torta Al Cioccolato E Banana','Antipasto','Banane',4,' -','3 Tazze Farina,
1 1/2 Tazza Zucchero,
1 Tazza Acqua,
1 Bustina Lievito Per Dolci,
2 Banane Mature Non Troppo Grandi,
200 G Cioccolato Fondente,
2/3 Tazza Olio D''oliva Extra-vergine,
1 Spolverata Zucchero A Velo','Fate sciogliere il cioccolato. Intanto mescolate la farina ben setacciata, lo zucchero, l''acqua e l''olio. Quando avrete prodotto un impasto fluido e ben amalgamato aggiungete il cioccolato fuso e il lievito. Infine incorporate le banane a tocchetti piccini piccini e cuocete per circa 50 minuti a forno a 160 gradi. Spolverate con zucchero a velo.',3787);
INSERT INTO "ricette" VALUES (25947,'Torta Al Cioccolato E Formaggio','Dessert','Cioccolato Fondente',8,'Ricetta inviata da: Mauro.','250 G Wafer Al Cioccolato (sbriciolati Per La Crosta),
6 Cucchiai Burro Fuso Per Il Ripieno,
700 G Formaggio Robiola,
250 G Zucchero,
1 Cucchiaino Vaniglia,
3 Uova Grandi,
220 G Cioccolato Fondente,
180 G Scaglie Di Cioccolato Bianco','Preriscaldare il forno a 165 gradi, ungere la teglia, di quelle che si aprono di circa 25 cm. Per fare la crosta mischiare in una ciotola le briciole dei wafer il burro fuso e premerlo sul fondo e sulle pareti. Per il pieno mescolare il formaggio lo zucchero fino a farlo diventare un composto cremoso senza grumi, aggiungere la vaniglia e 1 uovo per volta sempre mescolando, alla fine unire il cioccolato fuso (a bagnomaria) e le scaglie di quello bianco e versare il tutto nella teglia, avvolgere poi la teglia con della carta stagnola per impedire che l''acqua entri (mettere la teglia in un recipiente più grande pieno di acqua bollente e cuocere a bagno maria per 1 ora, togliere dal forno lasciare raffreddare, conservare la torta nel frigorifero, e poi aprite la teglia e decorare con delle scaglie di cioccolato bianco e scuro.',7877);
INSERT INTO "ricette" VALUES (25948,'Torta Al Cioccolato E Nocciole','Dessert','Cioccolato Fondente',4,' -','240 G Farina,
250 G Zucchero A Velo,
200 G Burro,
150 G Nocciole,
150 G Cioccolato Fondente,
30 G Cacao,
2 Cucchiai Miele,
5 Tuorli D''uovo,
4 Albumi D''uovo,
1 Cucchiaio Rum,
1 Pizzico Sale','Montare a spuma lo zucchero a velo con il burro morbido e un poco di sale; unire quindi i tuorli lentamente e, mescolando con un cucchiaio in legno, amalgamare la farina e il cacao setacciati insieme, il cioccolato tagliuzzato, le nocciole tritate grossolanamente, un cucchiaio di rum, due cucchiaiate di miele e metà degli albumi già montati a neve con un pizzico di sale. Infine, incorporare all''impasto gli albumi montati rimasti, mescolando delicatamente. Versare l''impasto in uno stampo rettangolare, imburrato e infarinato precedentemente, e far cuocere nel forno a 200 gradi per circa 20 minuti, coprendo il dolce con un foglio d''alluminio a metà cottura per evitare che diventi troppo scuro. Servire freddo e a fette piuttosto spesse.',5858);
INSERT INTO "ricette" VALUES (25949,'Torta Al Cocco','Dessert','Cocco',8,' -','Pasta Sfoglia,
1 Tazza Zucchero,
1/2 Tazza Fecola Di Mais O Di Farina,
1 Pizzico Sale,
3 Tazze Latte,
3 Uova Separate,
2 Cucchiai Burro,
Vaniglia,
1/2 Tazza Cocco','Srotolare la pasta e rivestirne una tortiera, premendo bene i bordi, punzecchiare il fondo e i bordi con una forchetta. Ricoprirla con fagioli secchi e cuocere a forno caldo durante 10-15 minuti. Nel frattempo, preparare la crema a bagnomaria o in una casseruola spessa: mescolare zucchero, fecola, sale. Aggiungere il latte. Portare a bollore a fuoco dolce. Cuocere durante 15 minuti mescolando sempre finché sia densa. Metterci i tuorli. Cuocere 3 minuti. Aggiungere il burro, la vaniglia e il cocco. Quando è raffreddata, versarla nella tortiera (dopo aver eliminato i fagioli). Preparare una meringa con gli albumi montati in quali ci aggiungiamo 6 cucchiai di zucchero. Metterla sulla crema di cocco. Cospargere la superficie con altro cocco. Passare la torta in forno molto caldo, facendo dorare la meringa e il cocco.',1923);
INSERT INTO "ricette" VALUES (25950,'Torta Al Cocco (2)','Dessert','Farina Di Cocco',4,' -','150 G Burro,
150 G Zucchero,
4 Uova,
1 Bicchierino Latte,
1 Bicchierino Liquore Dolce,
200 G Farina Di Cocco,
200 G Farina Per Dolci,
1 Bustina Lievito Vanigliato,
1 Pizzico Sale','Lavorare in una terrina 150 g di burro con 150 di zucchero; aggiungere, uno alla volta, 4 tuorli d''uovo,1 bicchierino di latte ed uno di liquore dolce. Unire, dopo averle mescolate tra loro, g. 200 di farina di cocco, 200 di farina per dolci ed 1 bustina di lievito vanigliato: dopo aver bene amalgamato, incorporare con delicatezza i 4 albumi montati a neve con un pizzico di sale. Infornare a 180 gradi per circa 45 minuti. Raffreddata, si può farcire con crema al gusto di frutta (suggerirei al limone), o spalmare di marmellata e spolverizzare con altro cocco.',3665);
INSERT INTO "ricette" VALUES (25951,'Torta Al Cocco E Ananas','Dessert','Cocco Grattugiato',8,'Preparazione: 105 minuti.','350 G Farina 00,
500 G Carote,
200 G Polpa Di Ananas,
100 G Cocco Grattugiato,
120 G Gherigli Di Noci,
350 G Zucchero Di Canna,
3 Uova,
18 Cl Olio Di Mais,
2 Cucchiai Lievito In Polvere Per Dolci,
2 Cucchiai Cannella In Polvere,
2 Cucchiai Estratto Di Vaniglia,
Burro E Farina Per Le Tortiere,
Per La Crema:,
400 G Ricotta,
220 G Zucchero A Velo,
80 G Polpa Di Ananas,
Per Decorare:,
Zucchero A Velo','Raschiate le carote, tagliatele a pezzi e cuocetele al vapore per circa 20 minuti, poi frullatele e lasciatele raffreddare. Fate tostare i gherigli di noci in un padellino antiaderente per un minuto e tritateli, quindi tagliate l''ananas a dadini. Riunite in una ciotola gli ingredienti preparati, aggiungete il cocco, l''olio, le uova leggermente sbattute, l''estratto, la cannella, lo zucchero e il lievito e mescolate con cura. Imburrate e infarinate due tortiere da 24 cm di diametro, distribuitevi dentro l''impasto e fatelo cuocere in forno ventilato a 180 gradi per un''ora. Trascorso questo tempo, lasciate riposare le due torte per 10 minuti, poi sformatele e fatele raffreddare completamente. Nel frattempo preparate la crema. Setacciate un paio di volte la ricotta e lavoratela con lo zucchero a velo. Unite poi l''ananas tagliato a dadini, mescolate con cura e lasciate riposare in frigo per almeno 15 minuti. Distribuitela poi sulla superficie di una torta, appoggiatevi sopra l''altra, completate con zucchero a velo a piacere e servite.',7721);
INSERT INTO "ricette" VALUES (25952,'Torta Al Cocco E Nutella','Dessert','Farina Di Cocco',4,' -','150 G Farina Di Cocco,
150 G Farina Tipo 00,
3 Uova,
200 G Zucchero,
100 G Burro,
1/2 Bicchiere Latte,
1 Bustina Lievito,
Per Farcire O Guarnire:,
Nutella','In un terrina sbattere le uova con lo zucchero, quando saranno amalgamate aggiungere il burro fuso. Poco alla volta aggiungere prima la farina 00 e poi la farina di cocco; continuando a mescolare, aggiungere il latte e quando si sarà amalgamato all''impasto mettere il lievito. Cuocere a 180 gradi per 20/25 minuti. Quando sarà raffreddata guarnire con la nutella, che si può anche mettere sopra la torta o nel mezzo.',3233);
INSERT INTO "ricette" VALUES (25953,'Torta Al Cocco Farcita Di Crema','Dessert','Cocco',16,' -','2 Noci Di Cocco Fresche,
50 G Zucchero,
4 Cl Rum Scuro,
1 Base Di Pan Di Spagna Di 26 Cm Diametro,
16 Ciliegine Candite,
Per La Crema:,
50 Cl Latte,
1 Stecca Vaniglia,
180 G Zucchero,
3 Tuorli D''uovo,
3 Albumi D''uovo','Bucate le noci di cocco e fate uscire il latte, raccogliendolo in una ciotola, quindi apritele, estraete la polpa e grattugiatela finemente. Versate 4 cl di latte di cocco in una casseruola, mescolatevi lo zucchero e portate ad ebollizione, quindi unitevi il rum. Tagliate il pan di Spagna in tre dischi. Fate bollire il latte in una casseruola insieme alla stecca di vaniglia tagliata e a 45 g di zucchero. In una scodella mescolate i tuorli d''uovo con 2 cucchiai di latte, uniteli al resto del latte bollente quindi fate addensare la crema su fuoco basso. In una terrina montate a neve gli albumi con il resto dello zucchero e incorporateli alla crema mescolando con una frusta. Quando tutti gli ingredienti sono ben amalgamati togliete la crema dal fuoco. Spalmate 1/3 scarso della crema sul disco di base, copritelo col secondo disco, inzuppate quest''ultimo con la miscela al rum e spalmate anch''esso con 1/3 circa di crema. Appoggiatevi sopra l''ultimo disco di pasta, inzuppatelo, quindi rivestite tutto il dolce con la crema rimasta. Fate raffreddare la torta, dopodichè cospargete tutta la superficie con la noce di cocco grattugiata e guarnite con le ciliegine.',5850);
INSERT INTO "ricette" VALUES (25954,'Torta Al Crumble','Dessert','Rabarbaro',8,'Preparazione: 90 minuti.','Per La Base:,
180 G Farina,
3 Uova,
700 G Rabarbaro,
200 G Zucchero Semolato,
180 G Burro,
3 Cucchiai Latte,
1 1/2 Cucchiaini Lievito In Polvere Per Dolci,
1 Pezzetto Zenzero Fresco Grattugiato,
1 Cucchiaio Sciroppo D''acero,
Burro E Farina Per Lo Stampo,
Per Il Crumble:,
120 G Farina,
90 G Burro,
60 G Zucchero','Preparate il crumble. Intridete con la punta delle dita il burro con la farina fino a renderlo granuloso, poi mescolatelo con lo zucchero. Preparate la base. Pulite e tagliate il rabarbaro a pezzetti di un paio di centimetri, poi mescolatelo in una ciotola con un cucchiaio di zucchero, lo zenzero e lo sciroppo di acero. A parte, montate il burro con lo zucchero rimasto, poi aggiungete le uova sbattute, poco alla volta, quindi la farina a pioggia, prima setacciata con il lievito, e il latte. Versate l''impasto ottenuto in uno stam