e Fresche,
1 Uovo,
40 G Farina,
50 G Formaggio Parmigiano,
2 Limoni,
Olio D''oliva,
Sale,
Pepe,
Prezzemolo','Pulire bene le acciughe, lavarle e tritarle finemente con il coltello o nel mortaio, mescolarvi l''uovo la farina e il formaggio, aggiustare di sale e pepe. Friggere le polpettine in olio caldo, scolarle e porle su fogli di carta paglia perché perdano l''unto in eccesso. Sistemarle su il piatto da portata, contornate di spicchi di limone.',2200);
INSERT INTO "ricette" VALUES (640,'Alici Con Puntarelle, Olive E Capperi','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe,
150 G Puntarelle,
100 G Formaggio Spalmabile,
80 G Olive Nere,
1 Cipolla Rossa,
50 G Capperi,
Panna,
Peperoncino,
Basilico,
Menta,
Prezzemolo,
Scorza Di Limone,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulire le acciughe, preparare un composto con formaggio, sale, pepe e olive nere tritate, poi spalmarlo sulle acciughe e cuocerle a vapore con basilico, menta, prezzemolo e 1 scorza di limone, 1 cipolla rossa. Condire le puntarelle con i capperi tritati, l''olio e il sale. Aromatizzare la panna con il peperoncino e metterla alla base del piatto con le alici e le puntarelle.',1972);
INSERT INTO "ricette" VALUES (641,'Alici Cotti D''a Lumia','Pesce','Acciughe',4,' -','1000 G Acciughe Minute,
4 Limoni (succo In Due Volte),
Abbondante Prezzemolo,
1 Peperoncino Rosso,
Aglio,
Olio D''oliva,
Sale,
Pepe','Cioè: acciughe crude cotte dal succo di limone. Diliscare e buttare le teste delle piccole acciuga della Plaja di Catania (che i pescatori mangiano anche crude) e metterle, così aperte, a cuocere a freddo nel succo di due limoni. Lasciarle in un grande piatto per circa mezz''ora, affinché l''azione dell''acido citrico possa cuocere la tenerissima carne delle acciughe che, da rossa che era, diventerà bianca. A questo punto buttare il primo succo di limone, dove rimarranno le tracce del sangue delle acciughe, se queste erano freschissime. Condire con olio d''oliva di prima spremitura, foglioline di prezzemolo intere, il succo degli altri due limoni, sale, pepe, un peperoncino rosso intero e guarnire con fette di limone.',1740);
INSERT INTO "ricette" VALUES (642,'Alici Croccanti Con Porri E Crema Di Patate','Pesce','Acciughe',4,' -','500 G Acciughe,
450 G Patate,
300 G Porri,
50 G Cipolla,
Semolino,
Alcune Gocce Aceto Balsamico,
5 Cl Brodo,
1 Bicchiere Latte,
70 G Burro,
4 Cucchiai Olio D''oliva,
Olio Di Semi Per Friggere,
Sale,
Pepe','Eviscerate le acciughe staccando la testa, apritele a libro, spinatele e lavatele; asciugatele, sistematele in un piatto, conditele con sale, pepe, qualche goccia di aceto balsamico e lasciatele insaporire. Intanto spuntate, lavate i porri, tagliateli a striscioline e fateli stufare a fuoco molto moderato in 2 cucchiaiate di olio riscaldato con una noce di burro; dovranno cuocere coperti almeno per 30 minuti, bagnandoli con un mestolino di acqua calda; alla fine conditeli con sale, pepe e una noce di burro fresco. Mentre i porri stanno cuocendo, sbucciate le patate, riducetele in dadolata e mettetele a rosolare dolcemente insieme con la cipolla tritata in 30 g di burro fatto riscaldare con 2 cucchiai di olio; quando incominceranno a prendere colore, bagnatele con il latte allungato con il brodo e lasciatele cuocere finché si spappoleranno assumendo consistenza cremosa; frullatele con il frullino a immersione, o passatele al frullatore. Sgocciolate le acciughe, passatele in abbondante semolino, scuotendo via quello in eccesso, quindi friggetele in pochissimo olio caldo. Sistemate le acciughe su un velo di crema di patate, accompagnatele con i porri stufati, spruzzando il tutto con qualche goccia di aceto balsamico.',4114);
INSERT INTO "ricette" VALUES (643,'Alici Croccanti E Guazzetto Di Provolone','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Filetti D''acciughe Freschissime,
Pangrattato,
3 Fettine Formaggio Provolone Dolce,
1/2 Finocchio,
1/2 Peperone Rosso,
1 Carota Piccola,
1 Zucchina Piccola,
1 Spicchio Aglio,
1 Radice Zenzero Fresco,
10 Cl Bevanda Alla Soia Naturale,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Per il guazzetto: tagliare il provolone a cubetti e unirlo al latte di soia. Scaldare sino a raggiungere i 50 gradi di temperatura e poi frullare in modo da ottenere una salsina cremosa. Tagliare a brunoise (a dadini piccolissimi) tutte le verdure (finocchio, peperone, carota e zucchina), grattugiare un po'' di zenzero fresco e scottare il tutto in padella con un filo d''olio ed un pizzico di sale. Disporre su ciascun filetto di alice un cubetto di provolone, arrotolare e chiudere con uno stuzzicadenti. Passare nel pangrattato e rosolare in padella con dell''olio e uno spicchio di aglio. Asciugare sopra un foglio di carta assorbente quindi rimuovere lo stuzzicadenti. Salare e pepare. Versare il guazzetto di provolone in un piatto fondo, aggiungere la brunoise di verdurine aromatizzate allo zenzero ed infine adagiare i filetti di alici rosolati.',1754);
INSERT INTO "ricette" VALUES (644,'Alici Crude','Antipasto','Acciughe',4,'Luogo: Sicilia. Luogo: Palermo. Luogo: Trapani.','500 G Acciughe,
Succo Di Limone,
Aglio,
Prezzemolo,
Olio D''oliva,
Sale,
Peperoncino Macinato','Pulite 500 g di acciughe, evisceratele, togliete con le mani la lisca centrale, lavatele e asciugatele. Sistematele a strati in una terrina, irrorando ogni strato con succo di limone. Cospargetele con aglio schiacciato e ponetele coperte in frigorifero per 24 ore. Quindi scolate le acciughe dal loro sugo, sciacquatele con succo di limone, ponetele in un piatto e cospargetele con un trito di aglio e prezzemolo, irroratele con olio d''oliva, salate e completate a piacere con peperoncino macinato.',1253);
INSERT INTO "ricette" VALUES (645,'Alici Dorate Al Mais Su Insalatina In Agrodolce','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe Grandi,
100 G Insalata Rucola,
Farina Di Mais,
20 G Bottarga Di Muggine,
Senape,
1/2 Limone,
Olio D''oliva,
Sale,
Pepe','Pulire, aprire a libretto e deliscare le acciughe. Passare i filetti nella farina di mais e bottarga grattugiata quindi friggerli in padella con un filo d''olio. Condire la rucola con olio emulsionato con poca senape e succo di limone. Salare e servire col pesce.',1276);
INSERT INTO "ricette" VALUES (646,'Alici E Peperoni','Antipasto','Acciughe',4,' -','600 G Acciughe,
600 G Peperoni,
Olio D''oliva,
Sale','Friggere in olio abbondante e bollente i peperoni tagliati a listarelle (10-15 minuti) tolti i peperoni e posati su carta da fritti, friggere nello stesso olio le acciughe (1-2 minuti) passare anche queste nella carta per asciugarle riunire il tutto e salare.',1414);
INSERT INTO "ricette" VALUES (647,'Alici Farcite Con Insalata','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','8 Filetti D''acciughe,
1 Spicchio Aglio,
50 G Pane,
Prezzemolo,
Latte,
Pangrattato,
20 G Pinoli,
1 Uovo,
1 Pompelmo,
100 G Insalata Rucola,
5 Olive Nere,
1 Carota,
1 Costa Sedano,
2 Fettine Prosciutto Crudo,
Olio D''oliva,
Sale,
Pepe','Frullare l''aglio con il prezzemolo, il pane bagnato nel latte ed un uovo; farcire col composto i filetti di acciughe; disporli su una placca da forno, cospargerli di olio, pangrattato ed infornarli per 5 minuti a 180 gradi. Servirle con una insalatiina fresca ottenuta con gli spicchi del pompelmo, la rucola, le olive nere, la carota e il sedano a listarelle con una julienne di prosciutto crudo.',2297);
INSERT INTO "ricette" VALUES (648,'Alici Fresche Al Limone','Antipasto','Acciughe Fresche',4,' -','800 G Acciughe Fresche,
2 Limoni,
3 Pomodori Ramati,
2 Spicchi Aglio,
2 Mazzetti Basilico,
4 Cucchiai Olio D''oliva,
1 Pizzico Sale,
Pepe','Pulire le acciughe. Pelare l''aglio, tagliarlo a fettine, inserirne una in ogni acciuga, insieme a una foglia di basilico, poi richiuderle. Tagliare i pomodori a fettine sottili insieme ai limoni. Ungere una pirofila rotonda del diametro di 18 centimetri con due cucchiai di olio d''oliva e sistemare la metà dei pomodori e dei limoni sul fondo, unite le foglie di basilico ben pulite, salare e pepare. Disporre le acciughe sui pomodori, accavallandole leggermente tra loro, sistemare le fette di pomodoro e di limone rimaste lungo la circonferenza della pirofila e coprire con altre foglie di basilico. Condire il tutto con altri 2 cucchiai di olio d''oliva, pepe e un pizzico di sale e cuocere in forno a 210 gradi per circa 15 minuti. Servire freddo.',2332);
INSERT INTO "ricette" VALUES (649,'Alici Fritte Con Peperonata, Lattuga Rossa E Caprino','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe,
200 G Peperone,
50 G Formaggio Caprino,
2 Uova,
Pangrattato,
Farina,
Olio Per Friggere,
1 Cipolla,
Olio D''oliva,
Sale','Pulire le acciughe, passarle nella farina, nell''uovo sbattuto e nel pangrattato. Friggerle in olio d''oliva. Tagliare i peperoni a cubetti e cuocerli in una casseruola con olio e cipolla tritata e preimbiondita. Unire i pomodori a metà cottura. Aggiungere il caprino in purezza a fine cottura, lontano dal fuoco. Servire le acciughe con la peperonata e la lattuga affettata e condita con olio e sale.',2547);
INSERT INTO "ricette" VALUES (650,'Alici Fritte Dorate Con Borraggine','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','400 G Acciughe,
Olio D''arachidi,
2 Uova,
200 G Borraggine,
Pangrattato,
Sale','Pulire le acciughe, fare una panatura con uova e pangrattato,nel frattempo portare l''olio a temperatura e friggere le acciughe. Pulire la borraggine, farla lessare in acqua calda e ripassarla con olio e peperoncino ed impiattare.',1673);
INSERT INTO "ricette" VALUES (651,'Alici Fritte Su Letto Di Scarola E Fasolari Gratinati','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Acciughe,
100 G Insalata Scarola,
8 Fasolari,
Pangrattato,
Olio Per Friggere,
Prezzemolo Tritato,
1 Filo Olio D''oliva,
Sale,
Pepe','Friggere i filetti di alice e servirli sulla scarola affettata e condita con olio e sale. Aprire i fasolari, condirli con sale, pepe e prezzemolo tritato e pangrattato e infornare con un filo d''olio d''oliva per alcuni minuti.',2087);
INSERT INTO "ricette" VALUES (652,'Alici Fritte, Marinate In Aceto E Porri','Pesce','Acciughe',6,'Preparazione: 40 minuti. Calorie: 157.','18 Acciughe Grandi,
2 Porri,
1 Ciuffetto Finocchietto Selvatico,
Farina,
Pangrattato,
1/2 Bicchiere Aceto Di Vino,
1 Filo Olio D''oliva Extra-vergine,
Sale,
Pepe','Staccate alle acciughe la testa poi spinatele aprendole a libro; lavatele rapidamente, asciugatele bene quindi passatele nella farina, nel pangrattato e friggetele in un velo d''olio. Mondate, riducete i porri a tocchetti e raccoglieteli in una casseruola insieme con mezzo litro d''acqua, un filo d''olio, un ciuffetto di finocchietto; portate il tutto su fuoco moderato e dopo 15 minuti di bollore aggiungete mezzo bicchiere di aceto, sale, pepe e, alla ripresa dell''ebollizione, spegnete e versate la marinata calda sulle acciughe fritte raccolte in un piatto piuttosto profondo; lasciatele marinare almeno 6 ore prima di servirle. Vino consigliato: Vino bianco giovane, secco, armonico, fragrante (Alto Adige Sylvaner, Colli Amerini Malvasia secco, Costa d''Amalfi bianco).',1305);
INSERT INTO "ricette" VALUES (653,'Alici Gratinate','Pesce','Acciughe',4,' -','800 G Acciughe Fresche,
1 Spicchio Aglio,
1 Bicchierino Aceto Di Vino,
2 Pizzichi Origano,
Sale,
Pepe Nero,
Olio D''oliva','Pulite le acciughe, tagliate la testa, togliete la lisca, e adagiatele aperte sul dorso in una teglia ben oliata. In una ciotola versate l''aceto, aggiungete 4/5 cucchiai d''olio, 2 pizzichi generosi di origano, sale e pepe nero; mescolate bene e versate il composto sulle acciughe. Ponete in forno un quarto d''ora a 200 gradi e servite subito.',1495);
INSERT INTO "ricette" VALUES (654,'Alici Gratinate (2)','Pesce','Acciughe',4,' -','400 G Acciughe,
3 Patate,
2 Limoni,
2 Spicchi Aglio,
Pangrattato,
Prezzemolo Tritato,
Olio D''oliva,
Sale','Sbucciare ed affettare sottilmente le patate. Disporle in una teglia larga e unta con olio. Lavare e asciugare le acciughe già diliscate e aperte, passarle nel succo dei limoni. Mescolare al pangrattato l''aglio tritato molto finemente ed il prezzemolo. Premere le acciughe sul pangrattato da entrambi i lati poi disporle sulle patate. Irrorare con olio e salare. Cuocere in forno caldo a 200 gradi per 15 minuti.',2053);
INSERT INTO "ricette" VALUES (655,'Alici Gratinate (3)','Pesce','Acciughe',4,' -','600 G Acciughe,
Pangrattato,
1 Mazzetto Prezzemolo,
1 Spicchio Aglio,
6 Cucchiai Olio D''oliva,
Sale,
Pepe','Squamare le acciughe, privarle della testa e della lisca centrale, lavarle e asciugarle.irrorare con 2 cucchiai d''olio 1 teglia; fare 1 strato di acciughe ben accostate tra loro; insaporirle con sale e pepe; cospargerle con prezzemolo e aglio tritati finemente, spolverizzarle con poco pangrattato e irrorare con un filo d''olio. Fare un secondo strato e continuare così fino alla fine degli ingredienti. Mettere in forno già caldo a 180 gradi per 10 minuti.',3119);
INSERT INTO "ricette" VALUES (656,'Alici Gratinate (4)','Pesce','Acciughe',4,' -','600 G Acciughe Freschissime,
2 Spicchi Aglio,
Abbondante Prezzemolo,
2 Peperoncini Rossi,
100 G Pangrattato,
Olio D''oliva Extra-vergine,
Sale','Pulire le alici privandole di interiora, lisca, testa e aprirle a libro, sciacquarle e asciugarle. Accomodarle in una pirofila oliata le une vicine alle altre; cospargere con un composto di pangrattato, prezzemolo e aglio tritati, peperoncino, salare e lasciar riposare per una decina di minuti. Irrorare d''olio e cuocere in forno a 180 gradi per 12 minuti.',1685);
INSERT INTO "ricette" VALUES (657,'Alici Gratinate Con Crema Di Melanzane','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','Per Le Acciughe:,
10 Filetti D''acciughe Fresche,
Pangrattato,
100 G Formaggio Grana Grattugiato,
Erbe Aromatiche (salvia, Rosmarino, Prezzemolo),
Gherigli Di Noci,
200 G Pomodorini,
Sale,
Olio D''oliva Extra-vergine,
Per La Crema:,
1 Melanzana,
Prezzemolo,
Sale,
Olio D''oliva Extra-vergine','Frullare il pangrattato con il grana, le erbe aromatiche, le noci, 3-4 pomodorini, un pizzico di sale e un filo d''olio. Adagiare la panure sulle acciughe e formare un tortino alternando le alici con i pomodorini tagliati a fettine. Infornare per 10 minuti a 180 gradi. Tagliare la melanzana a cubetti, stufarla in padella con un filo d''olio, 1 pizzico di sale e un goccio di acqua. Una volta pronta frullarla con qualche foglia di prezzemolo e un filo d''olio. Servire la crema di melanzana alla base del piatto e adagiarvi sopra il tortino di acciughe gratinate.',3000);
INSERT INTO "ricette" VALUES (658,'Alici Imbottite Con Insalatina Agrodolce','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','250 G Filetti D''acciughe,
1 Mozzarella Da 300 G,
2 Uova,
Pangrattato,
100 G Insalata Gentilina,
40 G Pinoli,
30 G Uvetta Sultanina,
Aceto Di Mele,
Olio D''oliva Extra-vergine,
Olio Di Semi Di Arachidi,
1 Pizzico Sale','Farcire i filetti d''acciughe con delle fettine di mozzarella, chiudere a mo'' di panino sovrapponendo ulteriori filetti quindi passare le alici imbottite nell''uovo sbattuto e successivamente nel pangrattato. Friggere in olio di semi profondo. A parte, condire l''insalata con l''uvetta precedentemente ammollata in un bicchiere di acqua tiepida, i pinoli, l''aceto di mele, l''olio d''oliva e 1 pizzico di sale.',3174);
INSERT INTO "ricette" VALUES (659,'Alici Imbottite Su Scarole Alla Monachina','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Filetti D''acciughe,
150 G Formaggio Provola,
1 Uovo,
Farina,
Formaggio Grana Grattugiato,
200 G Insalata Scarola,
1 Spicchio Aglio,
30 G Uvetta Sultanina,
30 G Pinoli,
20 G Capperi,
Olio D''oliva Extra-vergine','Passare i filetti d''acciughe nella farina e poi nell''uovo sbattuto con il grana; farcire con delle fettine di provola, sovrapporre con altri filetti e poi friggere in olio di semi. Sbollentare la scarola e poi rosolarla in padella con l''olio, l''aglio, l''uvetta, i pinoli ed i capperi. Servire le alici imbottite sopra un letto di scarola.',2362);
INSERT INTO "ricette" VALUES (660,'Alici Impanate','Pesce','Acciughe',1,' -','350 G Acciughe,
Sale,
Pepe,
Farina,
1 Uovo,
Pangrattato,
30 G Burro,
15 G Olio D''oliva','Pulite le acciughe con molta cura e tagliate le branchie con un paio di piccole forbici. Gli esemplari molto piccoli si possono lasciare interi ed è possibile mangiarne anche le spine senza problemi, mentre in quelli più grandi va eliminata la lisca centrale. Lavate ed asciugate i pesci ed insaporiteli con sale e pepe. Infarinateli leggermente, passateli nell''uovo sbattuto, quindi nel pangrattato, premendo leggermente. Fate scaldare il burro e l''olio in una padella e friggetevi le acciughe da entrambi i lati. Toglieteli dal recipiente di cottura quando sono ben dorati, tamponateli con carta assorbente da cucina per eliminare l''unto in eccesso e serviteli immediatamente.',1473);
INSERT INTO "ricette" VALUES (661,'Alici Impanate Con Provolone Del Monaco','Antipasto','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','8 Filetti D''acciughe,
100 G Formaggio Provolone Del Monaco,
1 Peperone,
1 Cipolla,
Farina,
1 Uovo,
Pangrattato,
Olio Di Semi Di Arachidi,
Sale','Farcire i filetti d''acciughe con il provolone grattugiato; passarli nell''uovo sbattuto, nella farina e nel pangrattato. Friggerli in olio di semi di arachidi. A parte, stufare il peperone tagliato a cubetti con la cipolla, frullare con un filo d''olio e regolare di sale. Servire le acciughe sopra la salsa di peperone.',1969);
INSERT INTO "ricette" VALUES (662,'Alici In Carpione Con Gentilina Ed Emulsione Di Mandarino','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Acciughe Fresche,
1 Cespo Insalata Gentilina Rossa,
1 Mandarino,
1 Cucchiaio Senape,
1 Costa Sedano,
1 Carota,
1/2 Cipolla,
Olio D''oliva,
Sale,
Pepe','Sfilettare le acciughe, cuocerle versandovi sopra una marinata calda di aceto, acqua e vino (in parti uguali) in cui si sia fatto precedentemente bollire per alcuni minuti un trito di sedano, carota e cipolla. Emulsionare l''olio con il succo del mandarino, la senape il sale e il pepe e condirvi l''insalata.',1061);
INSERT INTO "ricette" VALUES (663,'Alici In Forno','Pesce','Acciughe',4,' -','800 G Acciughe Freschissime E Ben Sode,
Alcuni Pomodorini,
1 Spicchio Aglio,
Origano,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Eviscerare le alici privandole della testa e lavarle. Accomodarle vicine vicine in due strati in una teglia oliata, inframmezzandole con sale, pepe, olio, origano, aglio a scagliette, pomodorini. Ricoprirle con qualche pomodorino spaccato, qualche scaglietta d''aglio, origano, salare, pepare, irrorare d''olio e cuoocere in forno a 180 gradi per 15 minuti.',1549);
INSERT INTO "ricette" VALUES (664,'Alici In Pangrattato','Pesce','Acciughe Fresche',1,'Luogo: Sicilia.','12 Acciughe Fresche,
30 G Capperi Sotto Sale,
1 Spicchio Aglio,
1 Mazzetto Prezzemolo,
Olio D''oliva,
2 Cucchiai Pangrattato,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Lavate i capperi privandoli del sale, scolateli ed asciugateli. Mettete nel frullatore i capperi ed il prezzemolo, unitevi il pangrattato, l''aglio, il parmigiano, 4 cucchiai di olio e un pizzico di sale e pepe. Frullate fino ad ottenere un composto omogeneo. Versate il composto su un piatto largo. Lavate le acciughe, asciugatele, apritele a metà lasciandole unite sul dorso. Privatele della testa e delle lische centrali lasciando le codine. Passate poi da entrambe le parti nel composto preparato. Arrotolate le acciughe in modo che le code restino in alto. Spennellate la pirofila con l''olio rimasto, ponetevi le acciughe, e premetele leggermente per evitare che si aprano durante la cottura. Ponete in forno già caldo e fate cuocere per circa 10 minuti.',1021);
INSERT INTO "ricette" VALUES (665,'Alici In Salsa Di Acetosella','Pesce','Acciughe Sott''olio',4,'Luogo: Trentino Alto-Adige','16 Acciughe Sott''olio,
1 Manciata Foglie Di Acetosella,
3 Spicchi Aglio,
1 Ciuffetto Erba Cipollina,
1 Cucchiaio Capperi,
1 Cucchiaio Concentrato Di Pomodoro,
75 G Burro,
Sale','Tritate finemente acetosella, aglio, erba cipollina e capperi. Sciogliere il burro a bagnomaria e unitevi il trito d''erbe aromatiche e il pomodoro. Salate e mescolate sino ad ottenere una crema omogenea. Disponete le acciughe su un piatto da portata e coprite con la salsa all''acetosella. Guarnite con alcuni capperi e accompagnate con fette di pane tostate in forno.',768);
INSERT INTO "ricette" VALUES (666,'Alici In Scapece','Antipasto','Acciughe',4,' -','500 G Acciughe Freschissime,
Alcuni Cucchiai Farina,
4 Foglie Alloro,
1 Cipolla Piccola,
1 Spicchio Aglio,
25 Cl Olio D''oliva,
1 Bicchiere Aceto Di Vino,
1/2 Bicchiere Acqua,
1 Presa Origano,
3 Granelli Pepe,
Poco Sale','Aprite con un coltello le acciughe nel senso della lunghezza (facendo però attenzione a lasciarle attaccate da un lato), liberandole della spina dorsale e della testa, ma lasciando la coda. Risciacquatele più volte con delicatezza, sgocciolatele con cura, asciugatele leggermente e passatele rapidamente nella farina; fatele quindi friggere in una padella di ferro, nell''olio bollente. Quando saranno pronte, estraetele dall''olio e passatele in fogli di carta assorbente, o su tovagliolini di carta, per eliminare ogni eccesso di unto. Dopo averle cosparse con un po'' di sale, sistematele a strati in un recipiente di terracotta o vetro provvisto di coperchio. Ponete ora in una piccola casseruola 1/2 bicchiere d''acqua, un bicchiere abbondante di aceto, uno spicchio d''aglio schiacciato, la cipolla tagliata a fettine sottili, le foglie di alloro, una presa abbondante di origano e 3 granelli di pepe, e lasciate sobbollire lentamente il tutto per 1/4 d''ora. Versate quindi la miscela aromatica sulle acciughe, avendo cura che ne risultino completamente sommerse. Lasciate infine raffreddare a temperatura ambiente, poi coprite il recipiente e fatelo riposare al fresco, per servire il giorno seguente.',2994);
INSERT INTO "ricette" VALUES (667,'Alici In Tortiera','Pesce','Acciughe',4,' -','500 G Acciughe Fresche,
3 Patate,
1 Cucchiaino Semi Di Finocchio,
1 Cucchiaio Pangrattato,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Lavate le patate per liberarle dall''eventuale terra che hanno attaccata, poi mettetele in una casseruola ben coperte con la buccia in abbondante acqua salata e cuocetele per 40 minuti; quindi scolatele e lasciatele raffreddare. Nel frattempo pulite le acciughe, eliminate la testa e la spina centrale, lavatele e mettetele a scolare su un tagliere leggermente inclinato. In una ciotola mettete un cucchiaino colmo di semi di finocchio, il pangrattato fine, una presa di sale, una macinata di pepe e mescolate. Ungete abbondantemente di olio una pirofila e sul fondo sistematevi tutte le patate sbucciate e tagliate a rondelle, allineatevi sopra i pesci ben scolati e richiusi. Spolverizzateli con il finocchio e il pangrattato, irrorateli con 2 cucchiai di olio e cuocete in forno caldo a 200 gradi per 18 minuti. Questo piatto è ottimo sia caldo sia freddo.',2619);
INSERT INTO "ricette" VALUES (668,'Alici In Tortiera (2)','Pesce','Acciughe',4,' -','800 G Acciughe Non Troppo Piccole,
4 Spicchi Aglio,
Olio D''oliva,
Sale,
Succo Di Limone,
Prezzemolo','Pulire le acciughe, spinarle e lavarle. Sistemarle quindi in una teglia con olio, sale, aglio e prezzemolo tritati, spolverare di pangrattato e spruzzare di succo di limone, infornare a fuoco vivace e portare a cottura.',1547);
INSERT INTO "ricette" VALUES (669,'Alici In Viola','Pesce','Acciughe',2,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe,
2 Patate,
1 Cavolo Rosso,
Olio Per Friggere,
Sale,
Pepe,
Erba Cipollina,
1 Limone,
1 Spicchio Aglio,
Per La Pastella:,
50 G Albume D''uovo,
100 G Farina,
100 G Birra,
100 G Olio D''oliva','Ricavare dalle patate sbucciate fili lunghi e sottili aiutandovi con una mandolina cinese. Lasciare le patate in acqua fredda per eliminare l''amido. Avvolgere le acciughe nei fili di patata, creando così un bell''effetto nido. Friggere in pastella. Stufare il cavolo rosso in olio e aglio, portare a cottura in brodo vegetale. Filtrare il liquido residuo e mettere da parte. Condire le foglie con olio, pepe e sale. Finitura e presentazione. Adagiare al centro del piatto le foglie del cavolo rosso, posare le acciughe appena fritte e aggiungere il fondo di cavolo rosa. Condire con sale e gocce di limone evidenziando cosi un cambiamento di colore nel fondo da viola a rosa tenue.',2545);
INSERT INTO "ricette" VALUES (670,'Alici Marinate','Antipasto','Acciughe',4,' -','1000 G Acciughe,
50 G Cipolle,
150 G Finocchio,
50 Cl Vino Bianco Secco,
50 Cl Acqua,
Sale,
5 Cl Aceto Di Vino Bianco,
5 Cl Olio D''oliva Extra-vergine,
1 Foglia Alloro,
1/2 Cucchiaino Pepe In Grani,
5 Bacche Ginepro,
Rametti Di Prezzemolo E Di Timo,
2 Spicchi Aglio','Pulite le acciughe, privatele delle spine e lavatele con cura sotto l''acqua corrente, infine sistematele in una pirofila dai bordi alti. Mondate la cipolla e il finocchio e tritateli finemente. Mescolate in una casseruola l''acqua, il vino, il sale necessario, le verdure tritate, l''aceto, l''olio, l''alloro, il pepe in grani, il ginepro, il timo, il prezzemolo e l''aglio, portate il tutto a ebollizione e lasciate cuocere a calore moderato fino a quando gli ortaggi sono teneri. A questo punto togliete il brodo dal fuoco e versatelo ancora bollente sui pesci. Lasciate raffreddare, poi fate marinare le acciughe in frigorifero per 12 ore prima di servire.',1895);
INSERT INTO "ricette" VALUES (671,'Alici Marinate (2)','Antipasto','Acciughe',4,' -','Acciughe Freschissime,
Aceto Di Vino,
Limone,
Olio D''oliva,
Sale,
Pepe In Grani,
Aglio (1 Spicchio Per 500 G D''acciughe),
Prezzemolo','Pulisci le acciughe e togli le lische, poi prepari un miscuglio con una parte di limone ed una di aceto, un pizzico di sale e qualche grano di pepe. Prendi un recipiente e fai uno strato di acciughe, lo copri col miscuglio e prosegui fino a finire le acciughe. Dopo 4 o 5 giorni di macerazione, in frigo, levi le acciughe dal miscuglio, le strizzi dalla salamoia (per esempio con lo scolapasta ed un po'' di scottex...). A questo punto prepari un trito con l''aglio ed il prezzemolo poi rifai lo strato di acciughe, trito ed olio... aggiungi anche qualcuno dei grani
di pepe della macerazione. Sono subito pronte da mangiare! (consigliabile mangiarle entro pochi giorni...)',850);
INSERT INTO "ricette" VALUES (672,'Alici Marinate (3)','Antipasto','Acciughe',2,'Preparazione: 15 minuti.','10 Acciughe Spinate (120 G),
20 G Capperi Sotto Sale,
1 Cipollotto,
1 Cuore Sedano,
1/2 Limone (succo),
Cerfoglio,
Prezzemolo,
1 Pizzico Peperoncino,
Insalata,
4 Cucchiai Olio D''oliva Extra-vergine,
1 Pizzico Sale','Disponete le acciughe in un piatto profondo e fatele marinare per 2 ore con un cipollotto affettato molto sottile, un cuore di sedano tritato (tenendo da parte qualche fogliolina), il succo di mezzo limone, un pizzichino di sale, uno di peperoncino e 2 cucchiaiate di olio. Lavate i capperi e mescolateli con le foglioline di sedano spezzettate, il cerfoglio, il prezzemolo, un pizzico di peperoncino, il succo di mezzo limone e due cucchiaiate di olio d''oliva extra-vergine. Servite le acciughe accompagnate da un''insalata mista e condite con la salsa ai capperi.',944);
INSERT INTO "ricette" VALUES (673,'Alici Marinate (4)','Pesce','Acciughe',4,' -','500 G Acciughe Freschissime,
2 Limoni,
2 Cucchiai Aceto Di Mele,
Sale,
Peperoncino,
Aglio,
Prezzemolo Tritato,
Olio D''oliva Extra-vergine','Pulire le acciughe togliendo testa e interiora, e lasciandole unite per il dorso; lavarle e scolarle. Disporle in una terrina; irrorandole con succo di limone e aceto fino a coprire. Far marinare per 2-3 ore e scolare. Disporre le acciughe a strati in una ciotola e condire ogni strato con aglio, peperoncino, sale, prezzemolo tritato. Irrorare il tutto con l''olio e servire dopo almeno 1 ora.',1273);
INSERT INTO "ricette" VALUES (674,'Alici Marinate (5)','Antipasto','Acciughe Fresche',4,' -','500 G Acciughe Fresche Piccole,
1 Spicchio Aglio,
2 Limoni (succo),
1 Manciata Prezzemolo Tritato,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe','Prima di tutto pulite bene le acciughe in questo modo: eliminate la testa, apritela completamente lungo il ventre, privatela della lisca e delle interiora, facendo attenzione a non dividere le due metà. Lavatela per bene e asciugatela delicatamente per evitare che si rompa dal momento che è molto delicata. Mettete le acciughe aperte a metà, in un piatto. Nel frattempo: mondate e lavate il prezzemolo, fatene un trito insieme all''aglio e spolverizzatelo sulle acciughe, aggiungendo sale e pepe a vostro gusto. Per la marinata: aggiungete alle acciughe l''olio ed il succo dei limoni, quindi coprite il piatto e lasciatelo macerare in un luogo fresco per circa 5 ore. Potete servire questo antipasto accompagnandolo con delle fette di pane casereccio tostate.',1197);
INSERT INTO "ricette" VALUES (675,'Alici Marinate Alla Menta','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe,
Aceto Di Vino Bianco,
Menta Fresca,
10 Olive Nere Mosciarelle,
1 Limone,
Olio D''oliva,
Sale,
Pepe','Marinare i filetti d''acciughe in olio ed aceto, intervallandoli a foglie di menta e fettine di limone. Pulire e sbollentare gli agretti, condirli con olio, sale e pepe, unire le orive nere mosciarelle denocciolate e tagliuzzate. Servire con i filetti d''acciughe marinati.',1009);
INSERT INTO "ricette" VALUES (676,'Alici Marinate Alle Erbette','Pesce','Acciughe',4,' -','500 G Acciughe,
4 Limoni,
Timo Fresco,
Maggiorana Fresca,
Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Pulire le alici privandole di testa, interiora, lische, aprirle a libro, lavarle e asciugarle. accomodarle in un piatto di servizio e irrorarle completamente con il succo di 3 limoni. Farle marinare in frigo per 1 ora, poi scolarle, accomodarle nuovamente nel piatto e condirle con un''emulsione preparata in anticipo di sale, olio, peperoncino e succo di limone. Far riposare, cospargere di maggiorana e timo freschi e servire.',1294);
INSERT INTO "ricette" VALUES (677,'Alici Marinate Con Bottarga E Zuppetta Di Pomodorini','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe,
Abbondante Sale Grosso,
200 G Pomodorini,
2 Fette Pane,
Bottarga In Polvere,
Olio D''oliva Extra-vergine','Pulire le acciughe, metterle in una teglia a marinare per 10 minuti con abbondante sale grosso. Sciacquarle ed asciugarle per eliminare il sale in eccesso. Tagliare i pomodori in 4 parti e cuocerli con il coperchio in un tegame con olio, sale e pepe. Frullare per ottenere una crema densa. Tagliare il pane a cubi e dorarli in un padellino con olio. Mettere la zuppetta di pomodorini in una fondina con i cubi di pane croccanti, adagiare le acciughe e la bottarga in polvere.',1408);
INSERT INTO "ricette" VALUES (678,'Alici Marinate In Umido','Pesce','Acciughe',4,' -','1000 G Acciughe Fresche,
Farina,
2 Spicchi Aglio,
Polpa Di Pomodoro,
Vino Bianco Secco,
Mentuccia,
Prezzemolo,
Origano,
Olio D''oliva,
Olio Di Semi Per Friggere','Mondate e lavate le acciughe, privandole della lisca, infarinatele e friggetele in abbondante olio caldo. Una volta pronte formate in una teglia uno strato di acciughe, cospargete con 2 cucchiai di vino, 2 di olio e 2 di pomodoro, cospargete con prezzemolo, aglio e mentuccia tritati insieme a un pizzico di origano. Formate, seguendo lo stesso procedimento, diversi strati fino ad esaurimento delle acciughe, terminando con il pomodoro e gli altri ingredienti. Passate in forno a 200 gradi per circa 15 minuti e servite.',2867);
INSERT INTO "ricette" VALUES (679,'Alici Ripiene Con Pesto Al Basilico E Lime','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','400 G Filetti D''acciughe,
150 G Formaggio Provola Affumicata,
Farina,
1 Uovo,
Pangrattato,
1 Mazzo Basilico,
40 G Pinoli,
1 Lime,
Sale,
Pepe,
Olio Di Semi Di Arachidi,
Olio D''oliva Extra-vergine','Farcire i filetti d''acciughe con dei pezzetti di provola, passarli nella farina, nell''uovo ed infine nel pangrattato profumato con la scorza del lime grattugiata. Ripetere l''operazione e poi friggere in olio di semi di arachidi ben caldo. A parte, frullare il basilico con i pinoli, la scorza del lime grattugiata, un filo d''olio d''oliva e regolare di sale e pepe. Servire le acciughe ripiene con il pesto.',3211);
INSERT INTO "ricette" VALUES (680,'Alici Ripiene Con Provola Affumicata E Pane Alle Erbe','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','400 G Filetti D''acciughe Già Pulite,
200 G Formaggio Provola Affumicata,
1 Uovo,
Pangrattato,
1 Mazzetto Erbe Fresche,
Olio Di Semi Di Arachidi','Prendere due filetti d''acciughe alla volta, farcirli con una fettina di provola, chiudere a mo'' di panino, passare il tutto prima nell''uovo poi nel pangrattato frullato con le erbe fresche ed infine friggere in olio di semi di arachidi profondo.',2077);
INSERT INTO "ricette" VALUES (681,'Alici Ripiene Con Tortino Di Patate Allo Zenzero','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe Sfilettate,
1 Formaggio Scamorza,
2 Uova,
100 G Mandorle A Scaglie,
100 G Pistacchi Sgusciati,
Mollica Di Pane Raffermo,
1 Limone,
1 Mazzetto Prezzemolo,
Olio D''oliva Extra-vergine,
100 Cl Olio Di Semi Di Arachidi,
Sale,
Pepe,
Per Il Tortino Di Patate:,
1000 G Patate Novelle,
1 Radice Zenzero,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Per il ripieno delle acciughe: frullare la mollica di pane raffermo con il prezzemolo e la scamorza tagliata a cubetti; condire con la buccia di limone grattugiata, l''olio d''oliva e regolare di sale e pepe. A parte, tritare finemente le mandorle e i pistacchi con un mixer in modo da ottenere una panure. Prendere due filetti d''acciughe alla volta: farcirne uno al centro con il composto precedentemente ottenuto e chiudere sovrapponendo il restante filetto. Passare le acciughe ripiene nell''uovo sbattuto e a seguire nella panure di frutta secca. Friggere in abbondante olio di semi di arachidi. Cuocere le patate in acqua bollente salata e schiacciarle con l''apposito attrezzo. Saltarle in padella con l''olio d''oliva, la radice di zenzero grattugiata e aggiustare di sale e pepe. Mettere le patate all''interno di un coppapasta posto al centro del piatto da portata e adagiarvi sopra le acciughe. Guarnire con delle foglie di prezzemolo e poi servire.',13252);
INSERT INTO "ricette" VALUES (682,'Alici Ripiene Di Scamorza Con Insalatina Di Radicchio','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Filetti D''acciughe,
150 G Formaggio Scamorza,
2 Uova,
Pangrattato,
1 Cespo Radicchio,
Aceto Di Mele,
Sale,
Olio Di Semi Di Arachidi','Farcire i filetti d''acciughe con un pezzetto di scamorza; chiudere con le restanti acciughe, passare prima nell''uovo sbattuto con 1 pizzico di sale poi nel pangrattato quindi friggere in olio di semi bollente. A parte, tagliare il radicchio a julienne e poi condire con sale, aceto di mele e olio d''oliva.',2036);
INSERT INTO "ricette" VALUES (683,'Alici Ripiene, Indorate E Fritte','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Filetti D''acciughe,
Farina,
2 Uova,
1 Spicchio Aglio,
Pangrattato,
Formaggio Grana Grattugiato,
300 G Spinaci,
Olio Di Semi Di Arachidi,
Sale,
Olio D''oliva Extra-vergine','Sbollentare gli spinaci, strizzarli, tagliarli finemente al coltello e rosolarli con dell''olio d''oliva. Mettere gli spinaci in una ciotola, amalgamarli con un trito di acciughe, aglio e grana. Farcire i filetti d''acciughe con il composto ottenuto, sovrapporre ulteriori filetti d''acciughe, passare nella farina, nell''uovo sbattuto con 1 pizzico di sale e nel pangrattato. Friggere in olio di semi bollente, tamponare con un foglio di carta assorbente, regolare di sale e poi servire.',2992);
INSERT INTO "ricette" VALUES (684,'Alici Salate','Pesce','Acciughe',4,'Luogo: Calabria.','Acciughe,
Sale Abbastanza Grosso','Pulite le acciughe eliminandone la testa e disponetele a strati (tre strati di acciughe e uno di sale) in un vaso cilindrico di terracotta. Coprite con un ultimo strato abbondante di sale e ponete sotto un peso consistente. Lasciatele così almeno per tre mesi, controllando di tanto in tanto che siano coperte dalla salamoia e aggiungendone se necessario, facendo sciogliere del sale in acqua (nove parti d''acqua e una parte di sale) e lasciando raffreddare prima di versarla sulle acciughe.',90);
INSERT INTO "ricette" VALUES (685,'Alici Sperone','Antipasto','Acciughe',4,'Luogo: Abruzzo.','1000 G Acciughe Freschissime,
3 Uova,
Farina,
Sale,
Olio D''oliva Per Friggere,
Prezzemolo Tritato,
Aglio Tritato,
Aceto Di Vino Forte','Nettate le acciughe (senza sfilettarle), asportando testa, lisca, interiora e coda; lavatele, poi asciugatele sopra un canovaccio. In una ciotola, sbattete con la frusta da pasticciere le uova, insieme al sale e a poca farina, sufficiente pe ottenere una pastella morbida; qui immergete la acciughe, poi tuffatele in padella, dove sfrigola l''olio, e friggetele; quando dorano, sgocciolatele, asciugatele su fogli di carta assorbente e disponetele nel piatto grande da portata; bagnatele con l''aceto, spolverizzatele con aglio e prezzemolo, quindi mettete in luogo fresco ad insaporire per qualche ora, prima di servirle.',2322);
INSERT INTO "ricette" VALUES (686,'Alici Su Cubi Di Zucca','Antipasto','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','3 Acciughe,
1 Fetta Zucca,
1 Rametto Rosmarino,
Basilico,
1 Filo Olio D''oliva,
Sale,
Pepe','Tagliare a cubi la zucca e sbollentarli. Avvolgervi attorno i filetti di acciughe e infilzarli con uno spiedino; cuocerli in padella con un filo d''olio, basilico e rosmarino.',443);
INSERT INTO "ricette" VALUES (687,'Alicioccole Di Trebisacce','Antipasto','Acciughe',4,'Luogo: Calabria. Luogo: Trebisacce.','Acciughe Piccole,
Sale,
Peperoncino Piccante Pestato,
Olio D''oliva','Lavate le minuscole acciughe, intere naturalmente, in acqua di mare e lasciatele sgocciolare e asciugare bene sopra un graticcio. In un vaso di creta fate un leggero strato di sale piuttosto fino (poiché dovrà sciogliersi completamente) e cospargete abbondantemente di peperoncino rosso piccante pestato nel mortaio. Se lo preferite, potete usare peperoncino piccante più peperoncino dolce (metà e metà). Fate uno spesso strato di acciughe, poi di sale e peperoncino e così via, fino a porre il disco di legno e, per peso, il sasso circolare. Dopo un paio di mesi di stagionatura, versate sulla superficie un dito d''olio d''oliva per evitare che abbiano contatto con l''aria e tenete in luogo freddo.',795);
INSERT INTO "ricette" VALUES (688,'Aliciotti Con Carciofi','Pesce','Acciughe',4,' -','800 G Acciughe,
8 Carciofi,
2 Limoni,
2 Spicchi Aglio,
Prezzemolo Tritato,
Olio D''oliva Extra-vergine,
Sale Marino,
Pangrattato','Eliminare le foglie dure dei carciofi; tagliarli a fettine; metterli in acqua acidulata col succo di 1 limone. Scolarli e brasarli con olio e aglio per 1/2 ora, unendo poca acqua. Pulire e diliscare le acciughe; disporne uno strato in una teglia oliata, salare, irrorare col succo di 1/2 limone; coprire coi carciofi e con un altro strato di acciughe; cospargere col restante succo, sale, pangrattato e prezzemolo. Cuocere in forno a 160 gradi per 20 minuti.',2041);
INSERT INTO "ricette" VALUES (689,'Aliciotti Con Indivia E Pompelmo E Carciofo Alla Giuda','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','500 G Acciughe,
1 Carciofo,
200 G Insalata Belga (indivia),
1 Pompelmo,
3 Spicchi Aglio,
Olio D''oliva,
Sale,
Pepe','Pulire,tagliare e salare l''indivia; lasciarla scolare per un paio d''ore in uno scolapasta per farle perdere l''acqua di vegetazione. Pulire le acciughe e unire i filetti due a due.Alternare nella teglia uno strato di acciughe con l''indivia, spicchi d''aglio e fettine di pompelmo. Condire con olio l''ultimo strato e mettere al forno per 10 minuti a 180 gradi. Pulire il carciofo e cuocerlo in padella con olio ed aglio.',1374);
INSERT INTO "ricette" VALUES (690,'Alivi Ammaccate','Antipasto','Olive Verdi',4,'Luogo: Calabria.','Olive Verdi,
Peperoncini Piccanti Grandi,
Aglio,
Olio D''oliva Extra -vergine,
Semi Di Finocchio,
Sale','Con un sasso, di quelli piatti che si trovano nella ghiaia, schiacciate le olive, eliminate i noccioli, mettete la polpa in acqua fredda per alcuni giorni, cambiandola almeno una volta al giorno. Allorquando saranno diventate dolci, senza perdere però del tutto l''amaro, sgocciolatele bene, conditele con olio vergine d''oliva, peperoncini rossi piccanti tagliuzzati finemente, aglio in pezzettini e semi di finocchio. Mettetele in vaso, pressatele leggermente, copritele magari d''olio e conservatele in luogo fresco.',860);
INSERT INTO "ricette" VALUES (691,'Alivi Chini','Antipasto','Olive',4,'Luogo: Sicilia. Luogo: Catania.','600 G Olive Bianche, In Salamoia E Senza Osso,
100 G Capperi Sott''olio,
50 G Peperone Rosso Arrostito E Sott''olio,
50 G Cetriolini Sott''aceto,
Olio D''oliva','Cioè: olive farcite. Farcire le olive, private dell''osso, con un cappero ed un pezzetto di filetto d''acciughe arrotolato. Negli ultimi tempi, cioè da quando l''industria ha monopolizzato l''antica ricetta catanese, è invalsa l''abitudine di chiudere la farcia con pezzettini di peperone rosso arrostito e conservato sott''olio e cetriolini sott''aceto, più che altro per apportare una nota di vivacità cromatica, apprezzabile dall''esterno del barattolo di vetro dove le olive, così farcite, vanno riposte ben coperte d''olio. Giudicheremo queste olive sorseggiando il Capo Bianco di Spinasanta (Messina) molto fresco.',1446);
INSERT INTO "ricette" VALUES (692,'Alivi Cunzati Alla Musco','Antipasto','Olive',4,'Luogo: Sicilia. Luogo: Catania.','600 G Olive Nere Salate,
1 Arancia (listarelle Scorza),
3 Spicchi Aglio,
50 G Semi Di Finocchio,
1 Limone Grande (succo),
1 Limone (listarelle Scorza)','Cioè: olive condite alla maniera di Angelo Musco. Il celebre attore e mimo catanese Angelo Musco si piccava di essere un grande gastronomo, anche se talvolta si compiaceva di certi paradossi, come la seguente dichiarazione, che soleva ripetere quando qualcuno cercava di dargli non richiesti consigli: ''Nta me vigna ci chiantu mirruzzi'' (nella mia vigna coltivo merluzzi). Questa ricetta, ricordata anche dal bollettino dell''Accademia della Cucina, non insegna a coltivare merluzzi, bensì a condire in maniera deliziosamente sicula le belle e carnose olive nere salate, che luccicano come ebano lustrato nei vivacissimi mercati di Catania. C''è bisogno di un bel barattolo di vetro con tappo a tenuta dove riporre le olive, assieme alle listarelle di buccia d''arancia e di limone,private della parte bianca amarognola. Spremere il succo di un grosso limone e mescolare gli spicchi d''aglio e i semi di finocchio. Tappare e servire dopo, almeno, dodici ore. E'' questo il primo ''chiama vinu'', per cui sorseggeremo con queste profumate olive, freschissimo, il Draceno dei vigneti della Valle del Belice.',1873);
INSERT INTO "ricette" VALUES (693,'Alivi Fritte','Antipasto','Olive Nere',4,'Luogo: Calabria.','6 Cucchiai Olive Nere Appassite,
2 Spicchi Aglio,
Peperoncino Rosso Piccante A Scagliette,
1/2 Bicchiere Olio D''oliva Extra-vergine,
Sale','Nella padella nera fate friggere gli spicchi d''aglio, unite le olive nere, cospargete abbondantemente di peperoncino piccante a scagliette e saltatele per alcuni minuti. Potete servirle sia calde che fredde.',1054);
INSERT INTO "ricette" VALUES (694,'Alivi Siracusani Scacciati','Antipasto','Olive',10,'Luogo: Sicilia. Luogo: Siracusa.','1000 G Olive Bianche Dolcificate In Salamoia,
70 G Capperi,
100 G Pangrattato Appena Tostato,
1 Ciuffetto Di Foglie Di Menta,
Origano,
Aglio,
Prezzemolo,
Peperoncino Rosso,
Olio D''oliva,
Aceto Di Vino','Cioè: olive di Siracusa schiacciate. Scegliere grandi olive bianche dolcificate in salamoia: schiacciarle e togliere il nocciolo condendole con olio, aceto, origano, aglio, prezzemolo, peperoncino a pezzetti e intero, mescolando poi i capperi tolti dalla salamoia, il pangrattato tostato e le foglie di menta. Poiché predomina l''aceto, nessun vino.',2310);
INSERT INTO "ricette" VALUES (695,'Allegretto','Bevande','Vodka Smirnoff',1,' -','2/4 Vodka Smirnoff,
1/4 Vermouth Dubonnet,
1/4 Triple Sec Bardinet,
Alcune Gocce Angostura Bitter,
Per Decorare:,
1 Ciliegina Al Maraschino','Si prepara nel mixing glass con ghiaccio. Si serve nella coppetta da cocktail. Si decora con 1 ciliegina al maraschino.',368);
INSERT INTO "ricette" VALUES (696,'Allegro','Bevande','Rum',1,' -','3/10 Cointreau,
2/10 Cordial Campari,
5/10 Myers''s Rum,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Si prepara nello shaker con cubetti di ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con ciliegina rossa al maraschino.',322);
INSERT INTO "ricette" VALUES (697,'Alleluia','Bevande','Tequila',1,' -','4/10 Tequila,
2/10 Curacao Blu,
2/10 Maraschino,
2/10 Succo Di Limone,
1 Cucchiaino Albume D''uovo,
Per Completare:,
Bitter Lemon Schweppes','Mescolare nell''ordine gli ingredienti nello shaker con cubetti di ghiaccio cristallino. Servire nel bicchiere tumbler con cubetti di ghiaccio, completando con Bitter Lemon Schweppes.',349);
INSERT INTO "ricette" VALUES (698,'Alleluia (2)','Bevande','Tequila',1,' -','4/10 Tequila,
2/10 Maraschino,
2/10 Curacao Blu,
2/10 Succo Di Limone,
Alcune Gocce Albume D''uovo,
Per Colmare:,
Limonata,
Per Guarnire:,
1 Fogliolina Menta Fresca,
2 Ciliegine','Versate i primi 4 ingredienti nello shaker e agitate aggiungendo alcuni cubetti di ghiaccio. Servite poi nei tumbler, colmando con della limonata. Guarnite con una fogliolina di menta fresca e due ciliegine.',339);
INSERT INTO "ricette" VALUES (699,'Alleluia Drink','Bevande','Succo D''ananas',1,' -','1/10 Melone Drink Boero,
5/10 Succo D''ananas Del Monte,
2/10 Vermouth Martini Dry,
2/10 Vodka Rossa Chazskaja,
Per Guarnire:,
1 Fetta Melone,
1 Ciliegina Rossa','Si prepara direttamente nel bicchiere tumbler alto con cubetti di ghiaccio. Mescolare delicatamente. Guarnire con fetta di melone, ciliegina rossa e cannucce.',286);
INSERT INTO "ricette" VALUES (700,'Allodole Al Crostone In Salsa','Pollame','Allodole',4,'Preparazione: 90 minuti.','16 Allodole,
16 Fettine Lardo,
16 Crostoni Pane,
100 G Burro,
1 Fegatino Di Pollo,
1 Cucchiaino Farina,
Poco Brodo,
1 Bicchierino Cognac,
Olio D''oliva,
Sale,
Pepe','Pulire le allodole (tenere da parte i fegatini), salarle, peparle, avvolgerle nelle fettine di lardo e legarle. Farle rosolare in una teglia con metà burro e poco olio a fuoco vivo; quando hanno preso colore, bagnarle con qualche cucchiaio di brodo e portare a termine la cottura in forno a temperatura media. Cuocere intanto i fegatini delle allodole e il fegatino di pollo con una noce di burro; passarli al setaccio, salare, pepare, bagnare con il cognac e far asciugare al fuoco. Friggere nel rimanente burro (tenerne da parte una noce) i crostoni di pane, scolarli, spalmarli con il passato di fegatini, disporli su un piatto e mettere su ciascuno una allodola. Aggiungere ancora un poco di brodo al sughetto di cottura delle allodole, rimetterlo al fuoco staccando bene il fondo con un cucchiaio di legno, incorporatevi la noce di burro tenuta da parte impastata con la farina, mescolare bene, fare addensare un poco la salsa, quindi versarla sulle allodole.',10347);
INSERT INTO "ricette" VALUES (701,'Allodole Arrosto Al Tartufo','Pollame','Allodole',4,' -','16 Allodole,
50 G Burro,
1 Cucchiaino Farina,
1 Rametto Rosmarino,
1 Tartufo Bianco,
Alcune Foglie Salvia,
Vino Bianco Secco,
Poco Brodo,
Sale,
Pepe','Pulire le allodole e farle rosolare in un tegame con 30 g di burro; salare, pepare, unire la salvia e il rosmarino e cuocere a fuoco vivo, bagnando ogni tanto con qualche cucchiaio di vino. Scolare le allodole su un piatto e incorporare al sughetto di cottura il rimanente burro impastato con la farina; diluire con un mestolino di brodo mescolando bene, rimettere nel tegame le allodole e portare a termine la cottura. Sgocciolare gli uccellini su un piatto di portata, cospargerli con il sughetto da cui si saranno eliminati la salvia e il rosmarino e distribuirvi sopra il tartufo a lamelle. Servire, volendo, con del riso al burro.',3353);
INSERT INTO "ricette" VALUES (702,'Allodole In Spiedini Alla Bresciana','Pollame','Allodole',4,'Preparazione: 90 minuti.','16 Allodole,
100 G Pancetta Tagliata Spessa,
50 G Burro,
1 Cucchiaio Pangrattato,
Alcune Foglie Salvia,
1 Pizzico Cannella,
Sale,
Pepe','Pulire le allodole. Infilarle a quattro a quattro su quattro spiedini in ferro o in legno, alternando ogni allodola con un pezzetto di pancetta e una foglia di salvia. Disporre gli spiedini su una teglia imburrata, salarli, peparli e insaporirli con un pizzico di cannella; cospargerli con il rimanente burro fuso e con il pangrattato. Cuocere in forno medio per una ventina di minuti, cospargendo ogni tanto gli uccelli con il sughetto raccolto sul fondo del recipiente. Servire ben caldo.',3757);
INSERT INTO "ricette" VALUES (703,'Alpino','Bevande','Grappa',1,' -','3/9 Grappa,
2/9 Infuso Di Menta,
2/9 Succo D''arancia,
2/9 Sciroppo Di Zucchero','Si prepara nello shaker e si serve nella coppetta da cocktail. Decorare con frutta fresca a fantasia.',250);
INSERT INTO "ricette" VALUES (704,'Alta Società','Bevande','Gin',1,' -','2/3 Vermouth Rosso,
1/3 Gin,
1 Spruzzo Grand Marnier,
Per Servire:,
1 Scorzetta Arancia','Agitare nel mixer con poco ghiaccio. Servire, con un cubetto di ghiaccio e una piccola scorza d''arancia, nel calice basso.',323);
INSERT INTO "ricette" VALUES (705,'Altea','Bevande','Gin',1,' -','4 Cucchiai Gin,
1 Cucchiaio Aperitivo Rossi,
1 Cucchiaio Sciroppo Di Lampone,
1 Cucchiaio Succo Di Limone,
Soda Schweppes,
Per Decorare:,
1 Fettina Limone,
3 Lamponi','Si prepara direttamente nel tumbler grande con 5 cubetti di ghiaccio. Si decora con 1 fettina di limone e 3 lamponi.',574);
INSERT INTO "ricette" VALUES (706,'Alternativa','Bevande','Rum',1,' -','2/5 Succo Di Limone,
1/5 Sciroppo Di Lampone,
2/5 Rum,
2 Cucchiaini Zucchero,
Per Servire:,
1 Spruzzo Seltz Freddo,
1 Fettina Limone,
1 Bastoncino Sedano','Agitare nel mixer, con ghiaccio tritato. Servire nel calice ampio, con uno spruzzo di seltz ben freddo, una fettina di limone e un bastoncino di sedano.',301);
INSERT INTO "ricette" VALUES (707,'Alto','Bevande','Whisky',1,' -','1/3 Vermouth,
2/3 Whisky,
1 Cucchiaio Crème Di Menta Bianca,
Per Servire:,
1 Foglia Insalata Verde','Agitare nello shaker, con ghiaccio. Servire nel tumbler, con una foglia d''insalata verde.',375);
INSERT INTO "ricette" VALUES (708,'Alto (2)','Bevande','Vermouth Dubonnet',1,' -','1/5 Succo Di Limone,
4/5 Vermouth Dubonnet,
Per Completare:,
Soda,
Per Servire:,
1 Scorza Di Limone','Agitare nel mixer con ghiaccio tritato. Riempire per metà il gotto basso e aggiungere un po'' di soda. Servire con una scorza di limone.',242);
INSERT INTO "ricette" VALUES (709,'Alto (3)','Bevande','Vermouth Dubonnet',1,' -','1/5 Succo Di Limone,
4/5 Vermouth Dubonnet,
Per Completare:,
Gazzosa,
Per Servire:,
1 Scorza Di Limone','Agitare nel mixer con ghiaccio tritato. Riempire per metà il gotto basso e aggiungere un po'' di gazzosa. Servire con una scorza di limone.',242);
INSERT INTO "ricette" VALUES (710,'Alzavole Allo Spiedo','Pollame','Alzavole',4,'Preparazione: 90 minuti.','2 Alzavole,
4 Fettine Pancetta,
1 Limone,
Sale,
Pepe','Pulire le alzavole. Salarle, peparle internamente ed esternamente, avvolgerne i petti nelle fettine di pancetta fermandole con un filo. Infilarle sullo spiedo e arrostirle; qualche minuto prima del termine della cottura eliminare la pancetta in modo da farle ben colorire. Servirle con spicchi di limone.',2919);
INSERT INTO "ricette" VALUES (711,'Amalfi','Bevande','Limoncello',1,' -','1/4 Limoncello,
3/4 Coca-cola','Mescolare gli ingredienti.',170);
INSERT INTO "ricette" VALUES (712,'Amandin Con Mandorle E Arance','Dessert','Arance',4,' -','115 G Zucchero Semolato,
100 G Farina,
100 G Mandorle In Polvere,
100 G Zucchero A Velo,
50 G Mandorle A Lamelle,
10 G Burro,
4 Arance,
4 Uova,
1 Pizzico Sale','Separate i tuorli dagli albumi e sbattete i primi con lo zucchero semolato, ottenendo un composto spumoso. Aggiungetevi le mandorle in polvere e la farina, la scorza grattugiata di un''arancia e il succo di 2 arance. Unite un pizzico di sale agli albumi, poi montateli a neve e incorporateli al composto preparato. Rivestite di carta da forno uno stampo quadrato. Imburrate la carta e, solo sulle pareti, fate aderire le mandorle a lamelle (tenetene qualcuna da parte). Versate nello stampo il composto e cuocete in forno già caldo a 180 gradi per circa 50 minuti. Spremete una delle arance rimaste, raccogliete il succo in un pentolino, unite lo zucchero a velo (tranne un cucchiaio che servirà per decorare) e scaldate la glassa sul fuoco, mescolando sempre, finché diventa filante. Sformate il dolce quando è freddo, versate la glassa sulla superficie facendola assorbire pian piano. Decorate con fettine di arancia, mandorle a filetti, e spolverizzate con lo zucchero a velo.',2772);
INSERT INTO "ricette" VALUES (713,'Amarene Alla Panna','Dessert','Amarene',4,' -','500 G Amarene,
150 G Zucchero,
1/2 Limone,
1 Bicchiere Vino Madera,
Panna Liquida','Lavare le amarene, snocciolarle, porle in una casseruola con lo zucchero, il succo di limone, un pezzetto di scorza, 1 bicchiere di Madera e 1/2 di acqua. Farle cuocere lentamente per evitare che si rompano poi scolarle e proseguire la cottura dello sciroppo per farlo addensare. Far raffreddare in frigo, separatamente, amarene, sciroppo e panna. Al momento di servire dividere in 4 coppe le amarene, coprirle con lo sciroppo (eliminare la scorza di limone) e servire la panna a parte in una brocca.',1136);
INSERT INTO "ricette" VALUES (714,'Amarene Chelibran','Dessert','Amarene',4,' -','1000 G Amarene Senza Picciolo,
1000 G Alcool,
3000 G Zucchero','Mettere per una giornata le amarene a sudare al sole. Così sudate si mettono in un barattolo di vetro con l''alcool e lo zucchero. Si mangiano dopo due mesi.',13810);
INSERT INTO "ricette" VALUES (715,'Amarene In Spirito','Dessert','Amarene',8,' -','1000 G Amarene,
500 G Zucchero,
300 G Alcool A 80 Gradi','Si puliscono le amarene con uno straccio senza lavarle; si toglie il nocciolo cercando di sciuparle il meno possibile, poi si mettono per 24 ore in un vaso alternando uno strato di amarene ed uno di zucchero. Dopo 24 ore si vuota il tutto in un vaso a chiusura ermetica aggiungendo l''alcool. Si mangiano a Natale.',2850);
INSERT INTO "ricette" VALUES (716,'Amarene Sciroppate','Dessert','Amarene',8,' -','2000 G Amarene,
2000 G Zucchero','Tagliate il picciolo delle amarene a circa un centimetro dalla base. Sciacquatele in una terrina ed asciugatele molto delicatamente, poi sistematele nei vasetti cercando di non lasciare spazi vuoti. Spolverizzatele con abbondante zucchero e chiudete ermeticamente. Mettete i vasetti al sole per circa 40 giorni, in questo modo le amarene e lo zucchero formeranno uno sciroppo. Ogni tanto capovolgete i vasetti e muoveteli un po''. Trascorso questo tempo potrete già gustarle o utilizzarle per guarnire dolci e gelati.',8660);
INSERT INTO "ricette" VALUES (717,'Amarene Sotto Spirito','Dessert','Amarene',8,' -','1000 G Amarene Con Il Nocciolo,
500 G Zucchero,
250 G Alcool','Si tiene al sole per una ventina di giorni, mescolando ogni tanto.',2770);
INSERT INTO "ricette" VALUES (718,'Amarene Ubriache','Dessert','Amarene',4,' -','1000 G Amarene Mature,
200 G Zucchero,
Alcool Per Dolci,
1 Pezzetto Cannella In Stecca,
Alcuni Chiodi Di Garofano,
Alcune Mandorle Amare','Tagliate il picciolo delle amarene a circa tre millimetri dalla base, sciaquatele e asciugatele all''aria. Versate le amarene in vasi muniti di coperchio a chiusura ermetica, attenzione alla perfetta pulizia di questi ultimi, altrimenti rischiate di mangiare amarene danzanti alla muffa verde; quindi aggiungete lo zucchero, la cannella, i chiodi di garofano, le mandorle e l''alcool in modo che le amarene siano coperte perfettamente. Chiudere il vasetto e conservatelo in un luogo ascitto e buio, dove i bambini hanno paura di entrare, in quanto bisogna aspettare almeno tre mesi prima di provarle. ....E pensare che a noi basterebbe rimanere immersi nell''alcool solo per tre ore per essere perfettamente ubriachi......',1471);
INSERT INTO "ricette" VALUES (719,'Amaretti','Dessert','Mandorle',4,' -','Mandorle,
Zucchero,
Albumi D''uovo,
1 Pizzico Sale','Passate le mandorle al mixer con un po'' di zucchero e tritatele finemente; passatele al setaccio ed eventualmente ripetete l''operazione fino a che non avrete ottenuto una farina di mandorle sottile. Unite il resto dello zucchero, mescolate e amalgamate accuratamente alle chiare che avrete montato a neve ferma con un pizzichino di sale. Formate con il composto delle palline di 4-5 centimetri di diametro. Rotolatele in una miscela di farina e zucchero e deponetele su una placca ricoperta da carta speciale. Infornate a forno medio (180 gradi) per 15 minuti fino a che non sono leggermente dorati.',657);
INSERT INTO "ricette" VALUES (720,'Amaretti (2)','Dessert','Mandorle Dolci',4,' -','1000 G Mandorle Dolci,
100 G Mandorle Amare,
2 Albumi D''uovo,
2 Limoni,
Zucchero','Immergete le mandorle, sia dolci che amare, in acqua bollente per poterle spellare meglio, dopodichè asciugatele in forno e poi tritatele nel frullatore. A questo punto pesatele ed aggiungete lo stesso quantitativo di zucchero, unite gli albumi, la buccia grattugiata dei limoni ed impastate delicatamente. Infarinate una teglia e con le mani formate delle palline ed adagiatevele sopra, ben distanti tra loro. Infornate per 20-30 minuti a temperatura media.',6416);
INSERT INTO "ricette" VALUES (721,'Amaretti (3)','Dessert','Mandorle Sbucciate',4,' -','200 G Mandorle Sbucciate,
200 G Zucchero,
1 Albume D''uovo,
Zucchero','Abbrustolite nel forno le mandorle per qualche minuto; dopodichè pestate in un mortaio con lo zucchero. Mescolate questo composto con l''albume d''uovo al fine di ottenere una pasta non troppo dura. Imburrate una piastra da forno e cospargetela di farina eliminando quella in eccesso. Mettete la pasta dentro una siringa per dolci e formate sopra la piastra dei tondini staccati l''uno dall''altro. Lasciate riposare per 2 ore e poi cuocete in forno a fuoco basso fino a quando non diventino dorati e asciutti.',1986);
INSERT INTO "ricette" VALUES (722,'Amaretti (4)','Dessert','Mandorle Amare',4,'Luogo: Guarcino. Luogo: Ciociaria. Luogo: Lazio.','200 G Mandorle Dolci,
20 G Mandorle Amare,
4 Albumi D''uovo,
300 G Zucchero A Velo,
Alcuni Dischetti Ostia','Ammollare le mandorle in acqua bollente, spellarle, passare al forno, pestarle in un mortaio e mescolarle allo zucchero in una terrina. Sbattere a neve i bianchi e unirli poco alla volta alle mandorle, mescolando delicatamente. Sistemare i dischetti di ostia su una placca spolverizzata di farina e disporvi l''impasto in mucchietti di forma ovale. Infornare a 180 gradi per 30 minuti.',2798);
INSERT INTO "ricette" VALUES (723,'Amaretti Aromatici','Dessert','Biscotti Amaretti',4,' -','50 G Mandorle,
50 G Cioccolata Fondente,
1 Cucchiaino Polvere Di Cacao,
1 Cucchiaino Polvere Di Caffè Solubile,
1 Cucchiaino Cannella E Chiodi Di Garofano,
2 Albumi D''uovo,
1 Pizzico Sale,
1 Cucchiaio Succo Di Limone,
75 G Pectina,
Per Guarnire:,
1 Arancia (scorza)','Mescolate insieme le mandorle tritate finemente, la cioccolata, la polvere di cacao e di caffè e gli aromi. Montate a neve l''albume unitamente al sale e al succo di limone, aggiungete lo zucchero e mescolate per circa 2 minuti. Aggiungete quindi le mandorle tritate. Con una siringa da pasticciere dalla bocchetta a forma di stella strizzate la pasta formando gli amaretti. Disponeteli su una teglia rivestita di carta da forno e cuoceteli per circa 15 minuti a 160 gradi in forno già caldo. Suggerimento: potete guarnire gli amaretti con una buccia d''arancia ritagliata, precedentemente riscaldata nello sciroppo.',859);
INSERT INTO "ricette" VALUES (724,'Amaretti Della Ciccia','Dessert','Mandorle',4,' -','300 G Mandorle,
1 Albume D''uovo,
1 Cucchiaio Pangrattato,
100 G Zucchero','Macinare le mandorle, montare i chiari e mescolare tutto; mettere in forno a 190 gradi su una carta oleata unta, finché non diventano rosa.',2270);
INSERT INTO "ricette" VALUES (725,'Amaretti Fritti','Dessert','Biscotti Amaretti',4,' -','200 G Biscotti Amaretti,
2 Cucchiai Rum,
1 Cucchiaio Cognac,
125 G Farina,
1 Uovo,
Olio D''oliva,
Sale,
Zucchero A Velo','Preparate una pastella morbida con la farina, il tuorlo, il cognac, 1 cucchiaio d''olio e acqua quanto basta; fate riposare 1 ora. Bagnate gli amaretti nel rum. Unite alla pastella gli albumi a neve. Immergetevi gli amaretti e friggeteli nell''olio bollente. Scolate e spolverate di zucchero a velo.',2485);
INSERT INTO "ricette" VALUES (726,'Amaretti Morbidi','Dessert','Biscotti Amaretti',4,' -','50 G Mandorle Amare,
150 G Mandorle Dolci,
300 G Zucchero A Velo,
10 Albumi D''uovo','Macinate nel mixer lo zucchero con i due tipi di mandorle. Montate a neve i bianchi d''uovo ed unitevi la polvere che avete ottenuto prima. Fate delle palline con un cucchiaio; mettetele su di un foglio di carta da macelleria e passate al forno caldo per un quarto d''ora.',2468);
INSERT INTO "ricette" VALUES (727,'Amaretti Morbidi (2)','Dessert','Biscotti Amaretti',4,' -','350 G Zucchero,
300 G Mandorle Pelate,
3 Albumi D''uovo,
1 Cucchiaio Farina Bianca,
1 Cucchiaino Fecola Di Patate,
Alcune Gocce Succo Di Limone,
Alcune Gocce Essenza Di Mandorle Amare,
Zucchero A Velo,
1 Pizzico Sale,
Per La Placca:,
Burro,
Farina','Tritare finissime le mandorle, unendo qualche cucchiaio di zucchero preso dal quantitativo prescritto, fino ad ottenere una farina. Mettere gli albumi in un paiolo di rame non stagnato, unire un pizzico di sale e qualche goccia di succo di limone e montarli a neve soda, con la frusta elettrica. Quando gli albumi saranno ben montati, unirvi la farina di mandorle, lo zucchero, 1 cucchiaio di farina bianca e 1 cucchiaino di fecola passate da un setaccio e, per finire, qualche goccia di essenza di mandorle amare. Mescolare bene e deporre sulla placca imburrata e infarinata dei mucchietti di composto, distanziati tra loro; spolverarli con lo zucchero a velo e lasciarli a riposo per 4-5 ore. Scaldare il forno a 100 gradi, infornare i biscotti e lasciarveli per almeno 1/2 ora, girando la placca ogni tanto per ottenere una cottura uniforme. Alla fine togliere la placca dal forno e, aiutandosi con una spatola, levare gli amaretti e lasciarli raffreddare su un tagliere di legno. Si conservano in scatole di latta.',4351);
INSERT INTO "ricette" VALUES (728,'Amaretti Prelibati','Dessert','Biscotti Amaretti',4,' -','Biscotti Amaretti Piccoli,
Crema Di Castagne,
Cioccolato Da Coperture','Accoppiate a due a due dei piccoli amaretti mettendo in mezzo della crema di castagne. Fate fondere del cioccolato da coperture e immergetevi gli amaretti farciti. Fateli rivestire di cioccolato poi metteteli ad asciugare su carta oleata e serviteli in pirottini.',881);
INSERT INTO "ricette" VALUES (729,'Amaretto','Bevande','Grappa',4,' -','100 Cl Grappa,
1 Scorza D''arancia Grattugiata,
2 Cime Assenzio,
30 G Radice Di Genziana Pestata','Si mette la scorza d''arancia (usare solo la parte gialla) a macerare per un paio di giorni nella grappa, agitando frequentemente. Poi si aggiunge l''assenzio e la genziana pestata. Si lascia macerare il tutto per un mese o poco meno, agitando due volte al giorno e tenendo il vaso esposto al sole. Quindi si filtra e si imbottiglia. Otterrete una bevanda dal sapore amarognolo, ma molto gradevole.',2516);
INSERT INTO "ricette" VALUES (730,'Amaretto Dolce Stil Novo','Dessert','Biscotti Amaretti',4,'Fonte: i4moschettieri.mastertopforum.net.','350 G Panna,
10 Biscotti Amaretti,
Per La Pasta Brisée:,
250 G Farina,
100 G Burro,
1 Uovo,
Acqua,
Zucchero A Velo','Lavorare gli ingredienti per la Brisée e stendere la sfoglia; infornarla per 15 minuti a 180 gradi e cospargerla di zucchero a velo. Servire il disco di frolla con la panna montata con amaretti sbriciolati.',3350);
INSERT INTO "ricette" VALUES (731,'Amaretto Exotic','Bevande','Amaretto',1,' -','1/2 Amaretto Di Saronno,
1/2 Orzata,
4 Cucchiai Succo D''ananas,
Per Allungare:,
Acqua Tonica,
Per Servire:,
1 Ananas Svuotato','Mescolare nell''ordine gli ingredienti nello shaker con ghiaccio. Servire in un ananas svuotato, allungando con acqua tonica.',885);
INSERT INTO "ricette" VALUES (732,'Amaretto Mist','Bevande','Amaretto',1,' -','3/3 Amaretto,
1 Spicchio Lime','Mettere l''amaretto in un bicchiere old-fashioned sopra il ghiaccio tritato. Aggiungere lo spicchio di lime e servire.',341);
INSERT INTO "ricette" VALUES (733,'Amaretto Mist (2)','Bevande','Amaretto',1,' -','3/3 Amaretto,
1 Spicchio Limone','Mettere l''amaretto in un bicchiere old-fashioned sopra il ghiaccio tritato. Aggiungere lo spicchio di limone e servire.',344);
INSERT INTO "ricette" VALUES (734,'Amaretto Sour','Bevande','Amaretto',1,' -','2/3 Amaretto Di Saronno,
1/3 Succo Di Limone','Si prepara nello shaker con ghiaccio tritato guarnito con scorzetta d''arancia.',229);
INSERT INTO "ricette" VALUES (735,'Amaretto Sour (2)','Bevande','Amaretto',1,' -','2/4 Succo Di Limone Non Zuccherato,
2/4 Amaretto,
Per Decorare:,
1 Spicchio Arancia','Mescolare amaretto e succo di limone con ghiaccio tritato e mettere in un bicchiere per whisky. Decorare con lo spicchio d''arancia e servire.',196);
INSERT INTO "ricette" VALUES (736,'Amarissimo','Bevande','Vermouth Rosso',1,' -','1/7 Vermouth Rosso,
1/7 Rabarbaro,
1/7 Bitter Campari,
1/7 Sciroppo Di Menta,
1/7 Vermouth Chinato,
2/7 Fernet','Mettete del ghiaccio nello shaker, versate gli ingredienti, agitate con energia e servite. E'' un ottimo digestivo.',275);
INSERT INTO "ricette" VALUES (737,'Amaro Al Carciofo','Antipasto','Carciofo',1,' -','20 Foglie Carciofo,
1 Sommità Fiorita Di Achillea,
2 Chiodi Di Garofano,
45 Cl Vino Bianco Secco,
45 Cl Brandy','Lasciate macerare per 2 giorni le erbe e le spezie nel brandy in un vaso a chiusura ermetica che avrete cura di agitare almeno due o tre volte al giorno. Unite poi il vino e ripetete l''operazione per altri due giorni. Al termine del tempo indicato filtrate ed imbottigliate. Attendete almeno 4 mesi prima di sorbire questo amaro digestivo che raccoglie in sè tutte le virtù del carciofo, pianta che contiene un principio amaro (la cinarina) prezioso per la sua azione epato-renale.',1408);
INSERT INTO "ricette" VALUES (738,'Amaro Alle Erbe','Bevande','Vermouth Bianco',4,' -','300 G Alcool Neutro A 96 Gradi,
650 G Vermouth Bianco,
150 G Zucchero,
14 Bacche Di Ginepro,
11 Aghi Di Rosmarino,
6 Foglie Di Melissa,
5 Foglie Salvia,
5 Chiodi Di Garofano,
2 Foglie Cardo Santo,
2 Foglie Menta Piperita,
1 Fiore Centaurea Minore,
1 Pezzetto Radice Contusa Di Calamo Aromatico,
1 Pezzetto Radice Contusa Di Genziana Maggiore,
1 Pezzetto Radice Contusa Di Carlina,
1 Pezzo Corteccia Di Cannella','Lasciate macerare tutte le erbe nell''alcool per 6 giorni in un vaso a chiusura ermetica, agitando il contenuto di tanto in tanto. Filtrate e tenete l''alcool da parte in una bottiglia tappata. Rimettete le erbe nel vaso e lasciatele macerare per altri 6 giorni con il vermouth in cui avrete fatto sciogliere lo zucchero. Filtrate anche il vermouth e unitelo all''alcool; dopo un giorno di riposo imbottigliate e tappate. Aspettate almeno 8 mesi prima di gustare.',2198);
INSERT INTO "ricette" VALUES (739,'Amaro Montchamp','Bevande','Alcool',4,' -','400 G Alcool A 95 Gradi,
320 G Zucchero,
280 G Acqua,
4 G Assenzio,
3 G Calamo Aromatico,
3 G Centaura,
2 G Radice Di Angelica,
2 G Enula Campana,
1 G Cannella','Questo rinomato amaro richiede un periodo di macerazione di 2 giorni nel vaso a chiusura ermetica. Nel frattempo curerete di rimestare una volta al giorno il macerato al quale aggiungerete infine lo zucchero disciolto nell''acqua calda. Lasciate riposare per una giornata, filtrate e imbottigliate. Per apprezzare il sapore di questo liquore fatelo riposare almeno sei mesi, quindi è conveniente tappare la bottiglia con sughero e ceralacca.',1902);
INSERT INTO "ricette" VALUES (740,'Amaro Orientale','Bevande','Grappa',4,' -','100 Cl Grappa,
25 G Cannella,
10 G Chiodi Di Garofano,
10 G Scorza D''arancia Amara,
10 G Galanga,
5 G Cardamomo,
5 G Zenzero','Frantumate le spezie in un mortaio di marmo e ponetele a macerare nella grappa per 12 giorni in un vaso chiuso agitando due volte al giorno. Filtrate e imbottigliate tappando con sughero e ceralacca. Così imbottigliato custodite il liquore in un posto fresco e asciutto. Attenderete almeno tre mesi prima di servire questo ottimo liquore dall''aroma esotico.',2546);
INSERT INTO "ricette" VALUES (741,'Amaro Tedesco','Bevande','Alcool',4,'Luogo: Germania.','350 G Alcool A 95 Gradi,
5 G Insalata Valeriana,
5 G Assenzio,
5 G Galanga,
15 G Arancia Amara (scorza),
10 G Menta,
5 G Zenzero,
4 G Legno Quassio,
5 G Centaurea,
350 G Zucchero','Versate 300 g di acqua molto calda sulle scorze d''arancia tagliate a pezzetti e lasciate in ammollo per 8 ore. Filtrate e aggiungete lo zucchero sciroppandolo. Una volta raffreddato unitelo alla macerazione alcolica che avrete ottenuto mettendo le altre spezie a macerare nell''alcool per 15 giorni in vaso chiuso, rimestate e filtrate. Attendete un giorno ed imbottigliate. Prima di servire, lasciate trascorrere almeno tre mesi.',1942);
INSERT INTO "ricette" VALUES (742,'Amatriciana Di Mezzanotte','Primo','Guanciale Di Maiale',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Pasta Tipo Mezze Maniche,
100 G Guanciale Di Maiale,
500 G Passata Di Pomodoro,
100 G Formaggio Pecorino Romano,
Sale','Tagliare il guanciale a cubetti e farlo rosolare in padella. A parte, cuocere la passata di pomodoro e regolare di sale. Cuocere le mezze maniche in acqua bollente salata, scolare e saltare in padella con il sugo. Unire il guanciale e il pecorino grattugiato, mescolare bene e poi servire.',1589);
INSERT INTO "ricette" VALUES (743,'Amazonas','Bevande','Rum Venezuelano',1,' -','3/4 Rum Venezuelano,
1/4 Benedictine Dom,
Alcune Gocce Succo Di Limone,
Alcune Gocce Granatina,
Per Completare:,
Succo D''arancia','Si prepara direttamente nel tumbler grande con cubetti di ghiaccio. Allungare con il succo d''arancia.',369);
INSERT INTO "ricette" VALUES (744,'Ambasciatore','Bevande','Gin',1,' -','1/4 Vermouth Bianco,
1/4 Crema Di Banana,
2/4 Gin,
1 Cucchiaio Succo Di Limone,
Per Servire:,
Alcuni Cubetti Ananas,
1 Ciliegia Sciroppata','Agitare nello shaker, con molto ghiaccio. Servire nel calice ampio, con cubetti di ananas e una ciliegia sciroppata.',343);
INSERT INTO "ricette" VALUES (745,'Ambassadeur Rose','Bevande','Vermouth Dry Cinzano',1,' -','1/3 Vermouth Dry Cinzano,
1/3 Mandarinetto Isolabella,
1/3 Vodka Eristow','Si prepara nel mixing glass con ghiaccio. Si serve in coppette da cocktail.',317);
INSERT INTO "ricette" VALUES (746,'Ambassador','Bevande','Whisky',1,' -','1 Tuorlo D''uovo,
1/4 Panna Liquida,
1/4 Apricot Brandy,
2/4 Whisky,
1/2 Cucchiaio Zucchero,
Per Servire:,
1 Pizzico Cacao Amaro','Agitare vigorosamente nello shaker con cubetti di ghiaccio. Servire nel tumbler stretto, con un pizzico di cacao amaro.',496);
INSERT INTO "ricette" VALUES (747,'Ambizioso','Bevande','Vodka',1,' -','3/10 Frullato Di Fragola,
3/10 Frullato Di Pera,
3/10 Vodka Liscia Artic,
1/10 Amaretto Di Saronno,
Vino Spumante Prosecco,
Per Decorare:,
2 Mezze Fragole,
1 Fetta Pera Sbucciata,
Mentuccia','Miscelare i primi quattro ingredienti nello shaker con ghiaccio. Si serve nel tumbler alto completando con il prosecco ben freddo. Decorare con due mezze fragole, una fetta di pera sbucciata e con della mentuccia.',272);
INSERT INTO "ricette" VALUES (748,'Ambra','Bevande','Sherry',1,' -','1/2 Sherry,
1/2 Cognac','Versate nel mixer e servite senza ghiaccio.',362);
INSERT INTO "ricette" VALUES (749,'Ambrosa','Bevande','Calvados',1,' -','1/2 Calvados,
1/2 Cognac,
2 Spruzzi Sciroppo Di Lampone,
Per Allungare:,
Vino Champagne,
Per Decorare:,
2 Lamponi','Versare i primi 3 ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in un flute e allungare con vino champagne. Mescolare con un cucchiaio prima di servire. Decorare con 2 lamponi freschi.',495);
INSERT INTO "ricette" VALUES (750,'Ambrosia','Bevande','Vino Bianco',4,' -','250 G Alcool A 70 Gradi,
400 G Vino Bianco Secco,
400 G Zucchero,
3 G Coriandolo,
1 G Anice Stellato Contuso,
3 Chiodi Di Garofano,
1/2 G Semi Di Angelica,
2 Gocce Tintura Di Muschio','Frantumate in un mortaio di marmo le spezie e chiudetele con l''alcool in un vaso ermetico, lasciandoli macerare per 10 giorni e rimestando due volte al giorno. Dopo questo periodo riaprite il vaso ed aggiungetevi il vino bianco genuino e dal sapore secco, richiudete e lasciate macerare per altri 10 giorni. Finalmente aggiungete lo zucchero e le due gocce di tintura di muschio, rimestate e chiudete di nuovo. Si lascia riposare per altri 5 giorni, si filtra e si imbottiglia.',2288);
INSERT INTO "ricette" VALUES (751,'American Beauty','Bevande','Cognac',1,' -','1/3 Cognac,
1/3 Vermouth Dry,
1/3 Crema Di Menta Bianca,
2 Gocce Orange Bitter','Inserire nello shaker gli ingredienti nell''ordine e scuotere bene.',272);
INSERT INTO "ricette" VALUES (752,'American Beauty (2)','Bevande','Vermouth Bianco',1,' -','4 Cubetti Ghiaccio,
2 Cl Granatina,
3 Cucchiai Succo D''arancia,
3 Cl Brandy,
5 Cl Vermouth Bianco,
1 Fettina Limone,
1 Ciliegia Al Maraschino,
1 Cucchiaino Vino Porto','Mescolate in un capace bicchiere (che potrebbe essere anche il mixing glass), granatina, succo d''arancia, brandy e vermouth bianco. Tritate il ghiaccio e disponetelo in un bicchiere a coppa, riempiendolo per metà circa. Con l''aiuto di un piccolo mestolo versate nella coppa la miscela preparata. Decorate con la fettina di limone e la ciliegina. Versate infine il drink con cannuccia e cucchiaino.',252);
INSERT INTO "ricette" VALUES (753,'American Beauty (3)','Bevande','Brandy',1,' -','1/4 Brandy,
1/4 Vermouth Bianco Secco,
1/4 Succo D''arancia Spremuta,
1/4 Sciroppo Di Granatina,
1 Spruzzo Crema Di Menta,
Per Completare:,
Vino Porto','Versare i primi 5 ingredienti in uno shaker riempito di cubetti di ghiaccio. Agitare. Passare in una coppetta da cocktail grande. Coprire con il vino Porto rosso versando delicatamente in modo che resti nella parte superiore del bicchiere.',463);
INSERT INTO "ricette" VALUES (754,'American Beauty Special','Bevande','Cognac',1,' -','1/3 Cognac,
1/3 Cointreau,
1/3 Rum Leggero,
Per Decorare:,
1 Scorza Di Limone','Versare i primi 3 ingredienti in uno shaker (o in un mixing-glass) con alcuni cubetti di ghiaccio. Agitare. Passare in una coppa da champagne. Decorare con la scorza di limone.',311);
INSERT INTO "ricette" VALUES (755,'American Breakfast','Primo','Salsicce',4,'Fonte: i4moschettieri.mastertopforum.net.','Per Il Pancake:,
115 G Farina 00,
1 Uovo,
15 Cl Latte,
30 G Burro,
1 Pizzico Sale,
1 Pizzico Zucchero,
Per I Fagioli In Umido:,
200 G Fagioli Precotti,
300 G Passata Di Pomodoro,
200 G Salsicce,
1 Scalogno,
Olio D''oliva Extra-vergine,
Per L''uovo In Camicia:,
1 Uovo,
3 Fette Bacon,
Aceto Di Vino Bianco','Per il pancake: amalgamare la farina con l''uovo, il latte, il burro, il sale e lo zucchero; cuocer il composto in padella fino a formare il pancake. Per i fagioli in umido: privare le salsicce della pelle e formare delle polpette; rosolare i fagioli in un tegame con l''olio e lo scalogno, unire la passata di pomodoro, regolare di sale ed infine aggiungere le polpette di salsiccia; proseguire fino al termine della cottura. Per l''uovo in camicia: in una pentola con dell''acqua bollente aromatizzata con l''aceto, creare un vortice e poi tuffarvi l''uovo sgusciato; cuocere fino a quando si sarà formata la camicia. Accompagnare l''uovo con le fette di bacon abbrustolito.',4315);
INSERT INTO "ricette" VALUES (756,'American Drink','Bevande','Succo Di Pompelmo',1,' -','6/10 Safari,
3/10 Succo Di Pompelmo Del Monte,
1/10 Succo D''ananas Del Monte,
Per Guarnire:,
1 Limone (scorza),
1 Ciliegina Rossa','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con piccola spirale buccia di limone, ciliegina rossa.',184);
INSERT INTO "ricette" VALUES (757,'American Flyer','Bevande','Rum Bianco',1,' -','1/2 Rum Bianco,
1/2 Succo Di Limone Verde,
1/2 Cucchiaino Zucchero,
Per Allungare:,
Vino Spumante','Versare i primi 2 ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in una flute. Allungare con vino spumante freddo.',265);
INSERT INTO "ricette" VALUES (758,'American Grog','Bevande','Rum',1,' -','1/4 Succo Di Limone,
3/4 Rum,
1 Cucchiaio Zucchero,
Acqua Bollente,
Per Completare:,
Whisky','Mescolare dolcemente nella bowl, poi aggiungere whisky. Servire nel cup.',524);
INSERT INTO "ricette" VALUES (759,'American Lemonade','Bevande','Vino Porto',1,' -','1/3 Succo Di Limone,
2/3 Vino Porto,
Per Servire:,
1 Spruzzo Soda,
1 Fetta Arancia,
1 Fetta Limone,
1 Ciliegina Sciroppata','Agitare nello shaker, con ghiaccio in cubetti. Servire nel tumbler ampio, con un po'' di ghiaccio tritato, uno spruzzo di soda, una fetta d''arancia, una fetta di limone e una ciliegina sciroppata.',205);
INSERT INTO "ricette" VALUES (760,'American Pousse','Bevande','Sciroppo Di Lampone',1,' -','1/5 Sciroppo Di Lampone,
1/5 Maraschino,
1/5 Chartreuse Gialla,
1/5 Curacao,
1/5 Cognac','Preparare direttamente nel flute avendo cura che gli ingredienti non si mescolino.',301);
INSERT INTO "ricette" VALUES (761,'American Pousse Cafè','Bevande','Sciroppo Di Lampone',1,' -','1/5 Sciroppo Di Lampone,
1/5 Maraschino,
1/5 Chartreuse Gialla,
1/5 Curacao,
1/5 Cognac','Preparare direttamente nel flute avendo cura che gli ingredienti non si mescolino.',301);
INSERT INTO "ricette" VALUES (762,'American Rose','Bevande','Cognac',1,' -','1/1 Cognac,
1 Spruzzo Pernod,
1 Spruzzo Granatina,
1/2 Pesca Molto Matura,
Per Completare:,
Vino Spumante','Versare i primi quattro ingredienti in uno shaker, con qualche cubetto di ghiaccio. Agitare bene. Passare in un grande bicchiere pieno di ghiaccio tritato. Allungare con lo spumante.',516);
INSERT INTO "ricette" VALUES (763,'American Salad Con Pollo Fritto','Contorno','Pollo',4,'Fonte: i4moschettieri.mastertopforum.net.','1 Petto Di Pollo Da 300 G,
Latte,
1 Limone,
Pangrattato,
100 G Mandorle A Filetti,
40 G Zucchero Di Canna,
100 G Insalata Lattuga,
100 G Formaggio Feta,
40 G Mirtilli Rossi,
Aceto Balsamico,
Olio Di Semi Di Arachidi,
Olio D''oliva Extra-vergine,
Sale','Far caramellare la metà delle mandorle con lo zucchero di canna. Marinare il petto di pollo con il latte e il succo di limone. Tagliare il pollo a striscioline, impanarlo con il pangrattato e le restanti mandorle quindi friggere in olio di semi bollente. Mettere in una grande ciotola le foglie di lattuga (precedentemente lavata ed asciugata) con la feta sbriciolata, i mirtilli rossi e le mandorle caramellate. Unire il pollo e condire il tutto con dell''olio d''oliva, il sale e delle gocce di aceto balsamico.',3210);
INSERT INTO "ricette" VALUES (764,'Americana','Bevande','Bourbon Whisky',1,' -','1 Cucchiaio Bourbon Whisky A 50 Gradi,
1/2 Cucchiaino Zucchero,
Per Completare:,
Vino Champagne Brut Ghiacciato,
1 Fettina Pesca','Mescolate bourbon e zucchero in coppe da champagne già fredde. Aggiungete lo champagne ed 1 fettina di pesca.',443);
INSERT INTO "ricette" VALUES (765,'Americano','Bevande','Bitter Campari',1,' -','5/10 Vermouth Rosso,
5/10 Bitter Campari,
Soda Water,
Per Guarnire:,
1 Fetta Limone','Si prepara direttamente nel bicchiere old fashion con alcuni cubetti di ghiaccio. Completare con soda water. Guarnire con fetta di limone.',207);
INSERT INTO "ricette" VALUES (766,'Americano (2)','Bevande','Bitter Campari',1,' -','1/2 Vermouth Dolce Bianco,
1/2 Bitter Campari,
Per Guarnire:,
1 Scorzetta Di Limone','Si versa sui cubetti di ghiaccio nel bicchiere alto. Si riempie con acqua frizzante o soda e si guarnisce con scorzetta di limone.',162);
INSERT INTO "ricette" VALUES (767,'Americano (3)','Bevande','Vermouth Rosso',1,' -','5/10 Vermouth Rosso,
5/10 Bitter Campari,
Per Completare:,
Soda Water,
Per Guarnire:,
1 Fetta D''arancia,
1 Fetta Di Limone','Si prepara direttamente nel bicchiere old fashion con alcuni cubetti di ghiaccio. Completare con soda water. Guarnire con fetta d''arancia e limone.',213);
INSERT INTO "ricette" VALUES (768,'Americano (4)','Bevande','Vermouth Rosso',1,' -','3/6 Vermouth Rosso,
3/6 Bitter Campari,
Ghiaccio,
Per Completare:,
Soda,
Per Decorare:,
1/2 Fettina Arancia','Si prepara direttamente nel piccolo tumbler (Old Fashioned), oppure nel bicchiere per whisky, con alcuni cubetti di ghiaccio; infine aggiungete, a piacere, qualche spruzzo di seltz o Soda Schweppes. Decorare con mezza fettina d''arancia.',171);
INSERT INTO "ricette" VALUES (769,'Americano (5)','Bevande','Vermouth Dolce',1,' -','1/2 Campari,
1/2 Vermouth Dolce,
1 Scorza Di Limone,
1 Spruzzo Seltz (facoltativo)','Agitate bene il Campari e il vermouth assieme ad un paio di cubetti di ghiaccio. Versate in un bicchiere da cocktail già freddo. Spremete 1 pezzetto di scorza di limone sul bicchiere e lasciatelo cadere dentro. Se preferite possono essere usati bicchieri old-fashioned con ghiaccio e 1 spruzzo di seltz.',184);
INSERT INTO "ricette" VALUES (770,'Americano (6)','Bevande','Vermouth Rosso',1,' -','2/3 Vermouth Rosso,
1/3 Bitter Campari,
Soda Water (o Seltz),
Alcuni Cubetti === Ghiaccio undefined,
Per Decorare:,
1 Scorza Di Limone','Mettere i cubetti di ghiaccio in un tumbler piccolo; versarvi sopra il Campari e il vermouth e completare con la soda o il seltz. Decorare con la scorza di limone.',204);
INSERT INTO "ricette" VALUES (771,'Amico Mio','Bevande','Vermouth',1,' -','3/10 Aperol,
2/10 Artic Vodka E Mandarino,
5/10 Vermouth Cinzano Dry,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Versare gli ingredienti nello shaker con molto ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con ciliegina rossa al maraschino.',338);
INSERT INTO "ricette" VALUES (772,'Amigo Rollups','Antipasto','Fagioli',4,' -','400 G Fagioli Precotti,
200 G Formaggio Fresco Morbido,
100 G Peperoncino Verde Tagliato,
2 Spicchi Aglio,
100 G Olive,
12 Focacce Di Granturco Sottili,
Sale','Mischiare bene tutti gli ingredienti (tranne ovviamente le focacce) finché il composto sia uniforme. Coprire perfettamente tutte le focacce scaldate. arrotolare bene le focacce. Mettere in un piatto. Attendere qualche minuto, quindi tagliare ogni 3 cm. Mettere in frigorifero e servire una volta raffreddato.',1157);
INSERT INTO "ricette" VALUES (773,'Amo''-amo''','Dessert','Meloni Gialli',4,' -','2 Meloni Gialli A Polpa Bianca O Verdina,
500 G Crema Di Yogurth Bianco,
7 Cucchiai Zucchero Di Canna,
2 Bicchieri Limoncello','Tagliare a metà i meloni per il largo; scavare la polpa, lasciando uno strato di circa 1 cm all''interno della buccia (da conservare!). Frullare la polpa, poi filtrare con un colino e usare solo la parte più densa. Mescolarla allo yogurth, allo zucchero da canna e al limoncello. Lasciare il tutto in frigo per circa 4 ore; a fine cena versare nei mezzi meloni scavati',2091);
INSERT INTO "ricette" VALUES (774,'Amor','Bevande','Vodka Keglevich Al Limone',1,' -','3 Cucchiai Parfait Amour,
2 Cucchiai Vodka Keglevich Al Limone,
1 Cucchiaio Succo Di Limone,
1 Cucchiaino Sciroppo Di Zucchero','Si prepara nello shaker con ghiaccio. Si serve nella doppia coppetta da cocktail.',494);
INSERT INTO "ricette" VALUES (775,'Amor Polenta Con Salsa Inglese E Fragole','Dessert','Fragole',4,'Fonte: i4moschettieri.mastertopforum.net.','Per L''amor Polenta:,
100 G Burro Morbido,
100 G Zucchero Semolato,
100 G Farina Di Mais,
100 G Farina 00,
2 Uova,
1/2 Bustina Lievito,
1 Limone (scorza Grattugiata),
Cannella In Polvere,
Per La Salsa Inglese:,
30 Cl Latte,
300 G Panna Fresca,
100 G Zucchero Semolato,
1 Stecca Vaniglia,
3 Tuorli D''uovo,
Per Il Resto:,
200 G Fragole,
Alcune Foglioline Menta Fresca','Per l''amor polenta: frullare il burro con lo zucchero, le due farine, le uova, il lievito, la scorza del limone e la cannella. Versare il composto in uno stampo e cuocere in forno a 180 gradi per 20 minuti. Nel frattempo, per la salsa inglese: cuocere a fuoco dolce il latte con la panna, unire lo zucchero amalgamato con i tuorli e i semi contenuti nella stecca di vaniglia dopo averla incisa con un coltello. Unire la metà delle fragole a pezzetti. Servire l''amor polenta sopra la salsa inglese, guarnire con le restanti fragole fresche ed alcune foglioline di menta.',4164);
INSERT INTO "ricette" VALUES (776,'Amour','Bevande','Vermouth Rosso',1,' -','1/3 Vermouth Rosso,
2/3 Sherry,
1 Pizzico Pepe,
Per Servire:,
1 Scorza Di Limone','Agitare nel mixer con poco ghiaccio in cubetti. Servire nel calice basso con una scorza di limone.',309);
INSERT INTO "ricette" VALUES (777,'Ananas Al Cognac','Dessert','Ananas',4,' -','1 Ananas Di 1000 G,
2 Cucchiai Zucchero,
1 Bicchierino Cognac','Tagliare l''ananas in fette di circa 1 cm ciascuna. Togliere la buccia con garbo, pulire bene tutte le fette, metterle su un piatto un po'' profondo e spolverizzarle di zucchero e cognac. Si preparano 4 o 5 ore prima di essere consumate.',630);
INSERT INTO "ricette" VALUES (778,'Ananas Al Naturale','Dessert','Ananas',4,' -','1 Ananas','Sbucciare e affettare l''ananas. Eliminare la parte legnosa centrale e servire.',460);
INSERT INTO "ricette" VALUES (779,'Ananas Al Rum','Dessert','Ananas',4,' -','1 Ananas Fresco,
4 Cucchiai Zucchero,
80 G Rum','Con un coltellino staccare la polpa interna dalla buccia dell''ananas, eliminando anche la parte coriacea centrale. Tagliare la polpa a fette alte un centimetro, disporle su un piatto lievemente concavo e cospargere di zucchero e rum. Lasciare in frigorifero almeno un''ora prima di servire.',801);
INSERT INTO "ricette" VALUES (780,'Ananas Alla Carota','Bevande','Succo D''ananas',1,' -','40 Cl Succo D''ananas,
1 Carota Piccola,
1 Arancia,
1 Cucchiaio Uvetta Sultanina','Frullate la frutta tagliata a pezzetti assieme agli altri ingredienti per un minuto. Aggiungete 3 cubetti di ghiaccio e frullate ancora per qualche secondo.',321);
INSERT INTO "ricette" VALUES (781,'Ananas Alla Carota (2)','Bevande','Succo D''ananas',1,' -','40 Cl Succo D''ananas,
1 Carota Piccola,
Poco Succo Di Limone,
1 Cucchiaio Uvetta Sultanina','Frullate la frutta tagliata a pezzetti assieme agli altri ingredienti per un minuto. Aggiungete 3 cubetti di ghiaccio e frullate ancora per qualche secondo.',247);
INSERT INTO "ricette" VALUES (782,'Ananas Alla Crema','Dessert','Ananas',4,' -','6 Fette Ananas Sciroppato,
6 Ciliegie Candite,
100 G Marmellata D''albicocche,
50 Cl Latte,
40 G Crema Di Riso,
3 Tuorli D''uovo,
100 G Zucchero,
2 Cucchiai Kirsch','Battere i tuorli a spuma con lo zucchero e unire la crema di riso e, mescolando, versare a filo il latte caldo. Cuocere a fuoco bassissimo per 15 minuti mescolando con una frusta. Levare dal fuoco e profumare con il kirsch. Versare la crema in un piatto da portata, disporvi sopra l''ananas e 1 ciliegia al centro di ogni fetta. Sciogliere la marmellata con 1 cucchiaio di kirsch e 2 di acqua, versarla sull''ananas. Servire fresco.',1798);
INSERT INTO "ricette" VALUES (783,'Ananas Alla Fiamma','Dessert','Ananas',4,' -','1 Ananas Da 1000 G Circa,
50 G Zucchero,
20 G Burro,
1 Bicchiere Brandy,
2 Chiodi Di Garofano','Pulire l''ananas e tagliarla a fette di circa 1 cm. Far sciogliere il burro in una padella, unirvi i chiodi di garofano e le fette di ananas. Spolverizzare di zucchero e lasciare insaporire, girando delicatamente. Versare metà del brandy e lasciare evaporare. Aggiungere il rimanente brandy, fiammeggiare e servire subito.',1146);
INSERT INTO "ricette" VALUES (784,'Ananas Alla Panna','Dessert','Ananas',4,' -','4 Fette Ananas In Scatola,
2 Banane,
200 G Panna Montata Zuccherata,
4 Ciliegie Sciroppate,
Brandy','Frullare le banane con qualche cucchiaio di brandy. Incorporare alla crema ottenuta la panna montata, mescolando delicatamente. Disporre le fette di ananas su 4 piattini, spruzzarle di brandy e su ogni fetta formare una piramide di crema alla banana. Sulla sommità sistemare una ciliegina e spruzzare ancora di brandy.',1302);
INSERT INTO "ricette" VALUES (785,'Ananas Alla Panna (2)','Dessert','Ananas',4,' -','1 Ananas Maturo,
1 Limone Verde,
300 G Panna Fresca,
4 Cucchiai Zucchero A Velo,
Essenza Di Vaniglia','Svuotare l''ananas e tagliare la polpa a dadini. In una terrina montare la panna, unirvi lo zucchero a velo, montare ancora. Aggiungere il succo del limone e poca essenza di vaniglia e continuare a montare finché diventa ben densa. Mettere in frigo la panna e l''ananas separatamente per almeno 1 ora. Mescolarli solo poco prima di servire e suddividere il composto in 4 coppe.',1801);
INSERT INTO "ricette" VALUES (786,'Ananas Alla Panna (3)','Dessert','Ananas',4,' -','4 Fette Ananas In Scatola,
2 Banane,
200 G Panna Montata Zuccherata,
4 Ciliegie Sciroppate,
Alcuni Cucchiai Brandy','Sbucciare le banane e frullarle con qualche cucchiaio di brandy. Incorporare alla purea di banane la panna montata delicatamente. Mettere l''ananas in 4 piattini e spruzzarlo di brandy. Su ogni fetta di ananas fare una cupola di crema alla banana. Decorare con la ciliegia e servire.',1415);
INSERT INTO "ricette" VALUES (787,'Ananas Caramellato','Dessert','Ananas',4,' -','1 Ananas,
120 G Zucchero Di Canna,
2 Limoni (succo),
Cannella In Polvere,
2 Confezioni Yogurth Alla Vaniglia','Private l''ananas della buccia e del torsolo centrale, poi tagliatelo a fette abbastanza sottili. Fate caramellare la metà dello zucchero e del succo di limone in una padella antiaderente con un pizzico di cannella. Unite poi la metà delle fette di ananas e lasciatele caramellare prima da un lato e poi dall''altro scuotendo continuamente la padella per non farle attaccare sul fondo, quindi trasferitele su della carta da forno e lasciatele raffreddare, in modo che lo zucchero cristallizzi. Ripetere lo stesso procedimento con gli ingredienti rimasti. Disponete le fette di ananas che avrete così preparato su un piatto da portata, alternando allo yogurth, spolverizzate con cannella a piacere e servite.',1130);
INSERT INTO "ricette" VALUES (788,'Ananas Cobbler','Bevande','Succo D''ananas',1,' -','1/3 Succo D''ananas,
2/3 Vino Champagne,
Alcuni Cubetti Ananas','Mescolare delicatamente il succo e lo champagne nel mixer. Versare nel tumbler sopra del ghiaccio finemente tritato misto a cubetti di ananas.',114);
INSERT INTO "ricette" VALUES (789,'Ananas Cocktail','Bevande','Gin',1,' -','1/4 Succo D''ananas,
1/4 Vermouth Bianco,
2/4 Gin,
Per Decorare:,
Alcuni Cubetti Ananas','Agitare forte nello shaker, con poco ghiaccio. Servire nei calici ampi, già pieni per metà di ghiaccio tritato, decorando con cubetti di ananas.',287);
INSERT INTO "ricette" VALUES (790,'Ananas Con Crema Di Banane','Dessert','Ananas',4,' -','3 Banane Mature,
1 Ananas Fresco,
10 Cl Rum,
1 Cucchiaio Zucchero,
Cioccolato Amaro (o Cannella),
150 G Panna Montata','Far macerare per 1/2 ora l''ananas tagliato a fette nel rum e nello zucchero. Schiacciare con una forchetta le banane e mescolarle alla panna. Disporre l''ananas nelle coppe, coprire con il liquore ottenuto dalla macerazione e con la crema di banane. Spolverizzare con il cioccolato o con la cannella.',2075);
INSERT INTO "ricette" VALUES (791,'Ananas Con Frutta','Dessert','Ananas',4,' -','1 Ananas,
2 Mandarini,
2 Arance,
2 Mele,
2 Banane,
Poco Vino Marsala (o Brandy)','Sbucciare e tagliare a fettine l''ananas. Disporlo su un piatto da portata. Sbucciare e tagliare il resto della frutta. Disporre la frutta sulle fette di ananas, cospargere con poco liquore e lasciar insaporire per 15 minuti.',1276);
INSERT INTO "ricette" VALUES (792,'Ananas Con La Frutta','Dessert','Ananas',5,' -','1 Ananas,
2 Mandarini,
2 Arance,
2 Mele,
2 Banane,
Vino Marsala','Sbucciare e tagliare a fettine l''ananas e disporlo in 1 piatto da portata. Poi sbucciare e tagliare il resto della frutta (le banane a fettine rotonde). Dopodichè disporre questa frutta sulle fette di ananas, cospargerle con un po'' di marsala e lasciar insaporire per circa 30 minuti.',1300);
INSERT INTO "ricette" VALUES (793,'Ananas Con La Frutta (2)','Dessert','Ananas',5,' -','1 Ananas,
2 Mandarini,
2 Arance,
2 Mele,
2 Banane,
Brandy','Sbucciare e tagliare a fettine l''ananas e disporlo in 1 piatto da portata. Poi sbucciare e tagliare il resto della frutta (le banane a fettine rotonde). Dopodichè disporre questa frutta sulle fette di ananas, cospargerle con un po'' di liquore e lasciar insaporire per circa 30 minuti.',1412);
INSERT INTO "ricette" VALUES (794,'Ananas Con La Panna','Dessert','Ananas',8,' -','2 Ananas,
100 Cl Panna Montata,
600 G Frutta Sciroppata,
100 G Ciliegie Candite','Dopo aver tolto le estremità e la polpa dell''ananas, e anche il torsolo centrale, cercare di allargare il foro raschiando fino a 7 cm circa. Frullare insieme la polpa estratta dell''ananas e la frutta sciroppata. Appoggiare l''ananas su un piatto di portata, versare nel foro il frullato, coprire con la panna e mettere in frigorifero per 1 ora. Dopodichè decorare con le ciliegie e servire.',5614);
INSERT INTO "ricette" VALUES (795,'Ananas Con Macedonia','Dessert','Ananas',4,' -','1 Scatola Ananas Sciroppato,
Prugne Nere Secche,
Datteri,
Noci,
Ciliegie Candite,
Alcune Fettine Arancia (o Mandarino),
Succo Di Limone,
1 Bicchiere Cognac,
100 G Zucchero A Velo,
Biscotti Amaretti','Tagliare le prugne, i datteri, le ciliegie a dadini o a fettine. Aggiungere le noci, le fettine di arancia o mandarino, lasciare macerare con lo zucchero, il limone e il cognac per 1 ora. Disporre le fettine di ananas in piccole coppe, guarnire con la frutta e gli amaretti, servire ghiacciato.',2630);
INSERT INTO "ricette" VALUES (796,'Ananas D''estate','Dessert','Ananas',6,' -','1 Ananas,
1 Banana,
1 Arancia,
Lamponi,
Fragole,
Pera (o Pesca),
Gelato Alla Vaniglia,
1 Bicchiere Vino Champagne,
2 Bicchierini Brandy,
Zucchero','Tagliate l''ananas orizzontalmente a metà. Con un cucchiaio togliete la polpa lasciando integro l''involucro. Riducete a dadini la polpa, così pure quella dell''altra frutta. Mescolate, zuccherate, spruzzate con un bicchiere di champagne e due bicchierini di brandy. Mettete in frigo la macedonia e anche i due gusci di ananas. Poco prima di servire riempite questi ultimi con la dadolata di frutta e, sopra, formate una cupola con il gelato di vaniglia che può essere comprato o fatto in casa. Su un piatto da portata distribuite uno strato di ghiaccio tritato, appoggiatevi sopra i mezzi ananas e servite.',1348);
INSERT INTO "ricette" VALUES (797,'Ananas Digestivo','Dessert','Ananas',4,' -','1 Ananas,
Zucchero Di Canna,
Cognac','Sbucciare l''ananas e affettarlo. Disporlo su un vassoio, spolverizzarlo di zucchero e bagnarlo con il cognac. Farlo riposare il più possibile prima di portarlo in tavola.',726);
INSERT INTO "ricette" VALUES (798,'Ananas Drink','Bevande','Succo D''ananas',1,' -','1/4 Succo D''ananas,
1/4 Vermouth Bianco,
2/4 Gin,
Alcuni Cubetti Ghiaccio,
Granatina,
Polpa D''ananas','Servendovi di uno shaker, versate nel boccale il succo d''ananas, il vermouth bianco, il gin e qualche cubetto di ghiaccio. Agitate energicamente il tutto per circa 10 secondi e versate il drink in bicchieri alti e capienti aggiungendo della granatina e polpa d''ananas.',468);
INSERT INTO "ricette" VALUES (799,'Ananas E Yogurth Con Salsa Mou','Dessert','Ananas',4,'Fonte: i4moschettieri.mastertopforum.net.','500 G Ananas Fresco (o Ananas Sciroppato),
500 G Yogurth Greco,
120 G Zucchero,
10 Cl Panna Fresca,
200 G Biscotti Millefoglie,
Sale','Gli ingredienti sono per 4 bicchieri. Mettete 100 G di zucchero in un pentolino d''acciaio dal fondo spesso e scioglietelo a fuoco dolce mescolando fino a ottenere un caramello dorato. Versate la panna sullo zucchero caramellato mescolando energicamente con un cucchiaio in modo da amalgamare bene gli ingredienti; togliete dal fuoco, aggiungete un generoso pizzico di sale e mescolate ancora bene. Mettete lo yogurth in una ciotola, unite lo zucchero rimasto e mescolate bene. Affettate l''ananas e poi tagliatelo a tocchetti. Coprite il fondo di 4 bicchieri con i biscotti sbriciolati, parte dello yogurth zuccherato e poi riempiteli alternando i tocchetti di ananas (tenendone da parte qualcuno per decorare) e il resto dello yogurth. Completate con la salsa mou preparata, decorate con qualche tocchetto di ananas tenuto da parte.',2133);
INSERT INTO "ricette" VALUES (800,'Ananas En Sauce D''avocat','Dessert','Ananas',4,'Luogo: Francia.','1 Ananas Grande Maturo Sodo,
2 Avocado,
1 Scatoletta Polpa Di Granchio (o Una Surimi),
Maionese,
Peperoncino Rosso Fresco Pili Pili,
2 Scalogni','Tagliate a metà nel senso della lunghezza il vostro ananas, eliminate il cuore legnoso e scavate la polpa che ridurrete a cubetti, badando a non rovinare la scorza del frutto. Sbucciate i due avocado, uno tagliatelo a cubetti e l¹altro riducetelo in purea aiutandovi con una forchetta. Mescolate la purea di avocado in parti uguali con la maionese; aggiungete peperoncino fresco a gusto, gli scalogni tritati e la polpa di granchio scolata. Unite tutti gli ingredienti all¹ananas e all''avocado a cubetti, mescolate molto delicatamente e riempite il guscio dell¹ananas. Decorate con fiori tropicali e portate in tavola.',1521);
INSERT INTO "ricette" VALUES (801,'Ananas Exotic','Bevande','Rum Bianco',1,' -','1 Ananas,
4 Cubetti Ghiaccio,
2 Cucchiai Rum Bianco,
2 Cucchiai Sherry Dry,
2 Cucchiai Galliano,
1/4 Bottiglietta Gassosa Schweppes,
2 Spruzzi Granatina','Tagliate la calotta dell''ananas e privatelo della polpa; versate il rum, il galliano, lo sherry e la granatina; aggiungete il ghiaccio e la gassosa e mescolate. Fate 2 fori nella calotta dell''ananas e infilatevi 2 cannucce.',1077);
INSERT INTO "ricette" VALUES (802,'Ananas Fantasia','Dessert','Ananas Fresco',4,' -','1 Ananas Fresco,
200 G Zucchero,
2 Cucchiai Kirsch','Aprite l''ananas e toglietene la polpa, raccogliendo il succo. Mischiate metà della polpa, resa in poltiglia, metà del succo e 200 g di zucchero; mettete questo composto nei bicchieri da gelato e riponeteli nel congelatore insieme all''ananas svuotato. Tagliate a grossi pezzi il resto della polpa, aggiungete un cucchiaio di zucchero, il kirsch e mettete anche questo composto nel congelatore. Quando il primo composto sarà denso, tagliatelo in grossi pezzi, riempiteci l''ananas, alternandoli a dadi di polpa.',1372);
INSERT INTO "ricette" VALUES (803,'Ananas Flambè','Dessert','Ananas',4,' -','8 Fette Ananas Sciroppato Al Naturale,
1/2 Cucchiaio Zucchero,
1/2 Cucchiaio Brandy','Disporre su un piatto resistente al calore le fette di ananas zuccherate. Metterle in forno a 200 gradi per 5 minuti. Bagnare con il brandy bollente e infiammare. Servire subito.',313);
INSERT INTO "ricette" VALUES (804,'Ananas Glacè','Dessert','Ananas',4,' -','1 Ananas Grande,
50 G Panna Da Montare,
100 G Zucchero A Velo,
70 G Biscotti Amaretti,
1 Bicchierino Vodka,
2 Albumi D''uovo','Con un coltello affilatissimo asportate all''ananas la calotta con il ciuffo. Poi, con un cucchiaio, scavate tutta la polpa interna, facendo attenzione a non rompere la buccia, che dovrà servire da ''contenitore''. Scartate la parte centrale della polpa, che è dura e legnosa. Tagliate la polpa rimasta a pezzettini e mettetela nel frullatore, dove la ridurrete in polti