lsa. Adagiare nella padella le fettine di carne e portarle a cottura girandole da entrambi i lati e regolando di sale. Cospargere con abbondante prezzemolo tritato e servire.',1266);
INSERT INTO "ricette" VALUES (9322,'Fettine All''origano','Carne','Manzo',4,' -','Olio D''oliva,
4 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cucchiaino Origano,
Sale,
500 G Carne Di Manzo A Fettine Sottili','Mescolare 6 cucchiai di olio, il parmigiano, l''origano e il sale. Cuocere per circa 20 secondi per parte le fettine di carne in olio caldo e a fuoco vivace. Via via che le fettine sono pronte sistemarle sul piatto di portata caldo, versarvi la salsetta all''origano e servire subito.',1582);
INSERT INTO "ricette" VALUES (9323,'Fettine Alla Crema Di Latte','Pollame','Tacchino',4,'Luogo: Molise.','4 Fette Petto Di Tacchino,
50 G Burro,
1 Cucchiaio Farina,
20 Cl Vino Bianco Secco,
20 Cl Latte Intero Fresco,
2 Tuorli D''uovo,
1 Limone,
1 Bicchierino Vino Marsala,
Alcuni Steli Erba Cipollina,
Sale,
Pepe','Rosolate le fettine nel burro caldo per 5-10 minuti, quindi eliminate il grasso che si sarà formato durante la cottura, unite il vino e lasciatelo evaporare a fuoco vivace. Aggiungete la farina stemperata nel latte e lasciate cuocere, coperto, per 20 minuti. A fine cottura, unite alla salsa di cottura i tuorli, il succo di mezzo limone e il Marsala, lasciate insaporire per qualche istante, quindi servite le fettine profumate con I''erba cipollina tagliuzzata.',1617);
INSERT INTO "ricette" VALUES (9324,'Fettine Alla Genovese','Carne','Vitello',4,'Luogo: Liguria. Luogo: Genova.','400 G Vitello A Fettine,
3 Cucchiai Olio D''oliva,
40 G Burro,
1 Spicchio Aglio,
Sale,
1/2 Limone,
1 Foglia Alloro','Scaldare in un tegame il burro, l''olio, l''aglio e il alloro. Adagiarvi le fettine, alzare la fiamma e far cuocere da ambo i lati non più di un minuto. Passarle su un piatto, salarle e intanto mantenere sul fuoco il tegame lasciando soffriggere un poco il fondo di cottura. Spegnere, togliere aglio e alloro, aggiungere il succo di limone, versare il sugo sulle fettine e servire.',1770);
INSERT INTO "ricette" VALUES (9325,'Fettine Alla Hawaiana','Carne','Maiale',4,'Luogo: Stati Uniti. Luogo: Isole Hawaii. Preparazione: 10 minuti. Cottura: 15 minuti.','8 Fettine Lonza Di Maiale (peso Totale 600 G),
3 Cipollotti Piccoli,
4 Fette Ananas (preferibilmente Fresco),
20 G Mandorle Affettate,
20 G Olio D''oliva Extra-vergine,
Sale,
Pepe Nero,
Peperoncino Macinato,
1/2 Cucchiaio Salsa Worcester (o Salsa Di Soia)','Sbucciate accuratamente l''ananas, tagliatelo a fette ed eliminate la parte centrale più dura. Dividete la polpa a spicchi. Mondate i cipollotti eliminando le radichette e la parte verde. Tagliateli in sei parti, per il lungo. Scaldate l''olio in una padella e fatevi appassire i cipollotti a fuoco medio per circa 5 minuti. Battete le fettine di carne per renderle più sottili e tenere. Sistematele quindi nella padella e lasciatele cuocere a fuoco medio per 6, 7 minuti per lato, finché saranno ben dorate. Sgocciolate la carne e tenetela da parte, al caldo. Gettate nella padella l''ananas e le mandorle, poi lasciate dorare bene, a fuoco vivace. Spruzzate con la salsa worcester o, se preferite un gusto meno forte, con la salsa di soia, quindi cospargete con un po'' di peperoncino macinato. Rimettete la carne nella padella e lasciate insaporire per un minuto a fuoco spento, avendo l''accortezza di tenere il coperchio ben chiuso. Servite caldo, accompagnando con riso pilaf allo zafferano.',1983);
INSERT INTO "ricette" VALUES (9326,'Fettine Alla Paprica','Carne','Vitello',4,' -','400 G Scaloppine Di Vitello,
100 G Cipolla Tritata,
1/2 Bicchiere Brodo,
1 Cucchiaino Paprica,
1 Cucchiaio Prezzemolo Tritato,
Burro,
Sale','Far appassire la cipolla tritata molto finemente nel burro, bagnare con il brodo e cuocere a fuoco dolce per circa 25 minuti. Passare al frullatore, unire la paprica e 1 cucchiaio di prezzemolo tritato. Saltare nel burro le scaloppine, salarle a fine cottura e disporle in un vassoio. Ricoprirle con la salsa e servirle.',1192);
INSERT INTO "ricette" VALUES (9327,'Fettine Alla Pizzaiola','Carne','Vitello',4,' -','Alcune Fettine Carne Di Vitello,
Burro,
Pomodoro,
Aglio,
Origano,
Sale','Scottare le fettine nel burro, levarle e nella stessa padella aggiungere pomodoro, origano ed aglio, fare insaporire, rimettere le fettine di carne, cuocere altri 5 minuti e servire.',1315);
INSERT INTO "ricette" VALUES (9328,'Fettine Alla Pizzaiola (2)','Carne','Manzo',4,' -','1 Spicchio Aglio,
1 Pezzetto Peperoncino,
Olio D''oliva,
4 Fettine Carne Di Manzo,
50 Cl Passato Di Pomodoro,
Acqua,
Origano,
Sale','Metti in un tegame 1 spicchio di aglio, un pezzetto di peperoncino e tanto olio quanto basta per coprirne il fondo. Fai soffriggere un poco l''aglio (che deve rimanere bianco) e metti dentro 4 fettine facendole rosolare per qualche minuto, dopo di che aggiungi 1/2 l di passato di pomodoro, un goccio di acqua, l''origano, il sale e fai cuocere il tutto per una mezz''ora circa, o fino a quando il sugo non si è ristretto.',1500);
INSERT INTO "ricette" VALUES (9329,'Fettine Alla Pizzaiola (3)','Carne','Vitello',4,' -','4 Fettine Carne Di Vitello,
500 G Pomodori Da Sugo,
Origano,
1 Spicchio Aglio,
Olio D''oliva,
Poco Burro,
Sale,
Pepe','Rosolate la carne in poco burro; in un altro tegame colorite nell''olio l''aglio tritato, unite i pomodori, pelati e tagliati a cubetti e cuocete dieci minuti. Salate, pepate. Versate la salsa sulla carne, spolverizzate con origano. Servite.',1295);
INSERT INTO "ricette" VALUES (9330,'Fettine Alla Rucola','Carne','Manzo',4,' -','Olio D''oliva,
Sale,
1 Manciata Insalata Rucola,
500 G Fettine Di Manzo Tagliate Sottili','Pulire e lavare la rucola. Scaldare l''olio e su fiamma vivace cuocere la carne 20 secondi per parte. Porla su un piatto di portata e salarla leggermente. Scaldare altri 2 cucchiai di olio nella stessa padella, unire la rucola, salare mescolare, mettere un coperchio e cuocere per circa 1 minuto. Distribuire sulla carne e servire subito.',1250);
INSERT INTO "ricette" VALUES (9331,'Fettine Con Barbabietola','Pollame','Pollo',4,' -','500 G Petto Di Pollo,
4 Barbabietole,
2 Bacche Anice,
1 Bastoncino Cannella,
2 Bacche Cardamomo,
Alcune Gocce Aceto Balsamico,
Olio D''oliva Extra-vergine,
Sale','Mondate e tagliate a spicchi le barbabietole, posatele in una teglia con le bacche di anice, la cannella, le bacche di cardamomo schiacciate, 5 cucchiai di olio d''oliva extra-vergine e un po'' di sale. Dopo aver mescolato il tutto infornate a 200 gradi per circa 1/2 ora. Tagliate a fette il petto di pollo e fatele dorare per pochi minuti in una padella con olio e sale; quindi adagiate le fette nella teglia con le barbabietole e lasciatelo cuocere ancora per 10/15 minuti. Servite il piatto caldo, con qualche goccia di aceto balsamico.',1445);
INSERT INTO "ricette" VALUES (9332,'Fettine Con Barbabietola (2)','Pollame','Tacchino',4,' -','500 G Petto Di Tacchino,
4 Barbabietole,
2 Bacche Anice,
1 Bastoncino Cannella,
2 Bacche Cardamomo,
Alcune Gocce Aceto Balsamico,
Olio D''oliva Extra-vergine,
Sale','Mondate e tagliate a spicchi le barbabietole, posatele in una teglia con le bacche di anice, la cannella, le bacche di cardamomo schiacciate, 5 cucchiai di olio d''oliva extra-vergine e un po'' di sale. Dopo aver mescolato il tutto infornate a 200 gradi per circa 1/2 ora. Tagliate a fette il petto di tacchino e fatele dorare per pochi minuti in una padella con olio e sale; quindi adagiate le fette nella teglia con le barbabietole e lasciatelo cuocere ancora per 10/15 minuti. Servite il piatto caldo, con qualche goccia di aceto balsamico.',1575);
INSERT INTO "ricette" VALUES (9333,'Fettine Della Nonna','Carne','Vitello',4,' -','Alcune Fettine Carne Di Vitello,
Farina,
Burro,
1 Spicchio Aglio,
Salvia,
Brodo,
Vino','Passare delle fettine di carne nella farina, saltarle leggermente nel burro, da ambo le parti, quindi, levarle dalla padella, in cui faremo rosolare uno spicchio d''aglio e della salvia. Levare l''aglio, rimettere le fettine di carne, allungare con una scodella di brodo e, poco dopo, con vino, finire di cuocere.',1709);
INSERT INTO "ricette" VALUES (9334,'Fettine Di Carne ''ci Vuole Coraggio A Mangiarne Ancora''','Carne','Vitello',2,' -','4 Fettine Carne Di Vitello,
Pepe,
Sale,
Rosmarino','Mettete un foglio di stagnola su una teglia da forno, disponete quindi la carne salata e pepata, aggiungete qualche foglia di rosmarino o se preferite origano. Riponete la teglia in un forno caldo (200 gradi) per circa 10 minuti e buona fortuna.....',380);
INSERT INTO "ricette" VALUES (9335,'Fettine Di Carne Alla Valdostana','Carne','Vitello',4,'Luogo: Val D''Aosta.','4 Fettine Sottofiletto Di Vitello (fette Da 100 G),
200 G Formaggio Fontina,
50 G Burro,
Alcuni Capperi,
Sale','Mettete in un tegame il burro, fatelo scaldare un po'', aggiungete la carne e fatela rosolare dalle due parti, salandola. Aggiungete la fontina tagliata a fettine, unite i capperi, coprite e fate cuocere a fuoco lento per 5 minuti. Ricordate che tutte le fettine più cuociono e più diventano dure.',1497);
INSERT INTO "ricette" VALUES (9336,'Fettine Di Carne Di Maiale Arrosto','Carne','Maiale',4,' -','8 Fettine Filetto Di Maiale,
Sale,
Pepe,
Rosmarino','Mettere sulla teglia del forno un foglio di carta stagnola, disporvi le fettine di carne, salatele, pepatele, mettete qualche foglia di rosmarino. Così preparate, ponete in forno caldo a 200 gradi per 10 minuti.',1512);
INSERT INTO "ricette" VALUES (9337,'Fettine Di Carne Di Pollo Arrosto','Pollame','Pollo',4,' -','8 Fettine Petto Di Pollo,
Sale,
Pepe,
Rosmarino','Mettere sulla teglia del forno un foglio di carta stagnola, disporvi le fettine di carne, salatele, pepatele, mettete qualche foglia di rosmarino. Così preparate, ponete in forno caldo a 200 gradi per 10 minuti.',1740);
INSERT INTO "ricette" VALUES (9338,'Fettine Di Carne Di Vitello Arrosto','Carne','Vitello',4,' -','8 Fettine Sottofiletto Di Vitello,
Sale,
Pepe,
Rosmarino','Mettere sulla teglia del forno un foglio di carta stagnola, disporvi le fettine di carne, salatele, pepatele, mettete qualche foglia di rosmarino. Così preparate, ponete in forno caldo a 200 gradi per 10 minuti.',564);
INSERT INTO "ricette" VALUES (9339,'Fettine Di Carote Con Salsa Guacamole','Antipasto','Carota',4,' -','1 Carota,
1 Avocado,
1/4 Cipolla Tritata Fina,
2 Pomodorini Tritati,
1 Cucchiaino Succo Di Limone,
Olio D''oliva','Amalgamare in una ciotola tutti gli ingredienti (meno la carota). Si serve con la carota a fettine.',993);
INSERT INTO "ricette" VALUES (9340,'Fettine Di Cetriolo In Salsa Tzaziki','Antipasto','Cetrioli',4,' -','250 G Yogurth Greco Bianco Scolato,
2 Cetrioli,
1 1/2 Spicchio Aglio,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe Bianco,
Origano','Tritare il cetriolo con la buccia e far perdere l''acqua amara tamponandolo con un foglio di carta da cucina. In una ciotola amalgamare lo yogurth, il cetriolo tritato, il sale, il pepe bianco, l''aglio grattugiato, l''origano, l''olio. Si può servire o con il cetriolo a fettine o in un bicchierino con il cetriolo a bastoncini.',503);
INSERT INTO "ricette" VALUES (9341,'Fettine Di Fesa Di Tacchino Alla Campagnola','Pollame','Tacchino',4,' -','Fettine Di Fesa Di Tacchino,
2 Spicchi Aglio,
Poco Prezzemolo Tritato,
1 Cucchiaio Olio D''oliva,
150 G Pomodori Pelati,
1 Presina Origano,
Sale,
Pepe','Mettere del burro in un tegame. A burro fuso cuocere le fettine di fesa ancora surgelate per circa 12 minuti rigirandole spesso verso la fine della cottura. Nel frattempo soffriggere in un tegame due spicchi d''aglio e un po'' di prezzemolo tritato con un cucchiaio d''olio. Aggiungere circa 150 g di pomodori pelati e una presina di origano, salare, pepare, lasciar bollire per mezz''ora circa, a fuoco lento. Aggiungere la salsa alle fettine di fesa e lasciare il tutto ad insaporire sul fuoco per una decina di minuti.',945);
INSERT INTO "ricette" VALUES (9342,'Fettine Di Fesa Di Tacchino Con I Funghi','Pollame','Tacchino',4,' -','Burro,
Fettine Di Fesa Di Tacchino,
Sale,
Funghi,
Prezzemolo,
Aglio,
Sale,
1 Cucchiaio Panna','Mettere del burro in un tegame. A burro fuso cuocere le fettine di fesa ancora surgelate per circa 12 minuti rigirandole spesso verso la fine della cottura. Salare, a piacere. Porre su ogni fettina una salsina preparata con funghi tagliati a fettine sottili, cotti nel burro con prezzemolo, aglio e sale, aggiungere un cucchiaio di panna e passare il tutto al forno caldo per qualche minuto, quindi servire.',1431);
INSERT INTO "ricette" VALUES (9343,'Fettine Di Lonza Alla Napoletana','Carne','Maiale',4,'Luogo: Campania. Luogo: Napoli.','4 Fette Lonza Di Maiale (fette Di 150 G Ognuna),
150 G Olio D''oliva,
1/2 Cipolla,
Aglio,
80 G Pinoli,
80 G Uvetta Sultanina,
400 G Doppio Concentrato Di Pomodoro,
Sale,
Pepe','Dopo aver battuto le fettine, allinearle sul tagliere e mettere sopra ognuna un po'' di uvetta, di pinoli, mezzo spicchio di aglio, sale e pepe. Arrotolate le fette e chiuderle con uno stecchino, quindi porle a rosolare in un tegame con olio, dove abbia già preso colore la cipolla finemente tritata. Dopo la rosolatura, aggiungere la salsa di pomodoro e, senza versare acqua, cuocere a fuoco lento, con coperchio.',3983);
INSERT INTO "ricette" VALUES (9344,'Fettine Di Lonza Alla Panna','Carne','Maiale',4,' -','400 G Fettine Di Lonza Di Maiale,
40 G Burro,
1 Cucchiaino Prezzemolo Tritato,
1 Cucchiaino Capperi,
200 G Panna Fresca,
Farina,
Sale,
Pepe,
1/2 Limone','Cuocere nel burro a fuoco vivo le fettine dopo averle leggermente infarinate, facendo loro prendere colore su ogni lato. Salare, pepare, aggiungere capperi tritati e prezzemolo, lasciar insaporire pochi minuti e versare la panna. Mescolare in continuazione e, a fiamma bassissima, ultimare la cottura per altri 5-10 minuti. Spruzzare quindi col succo di limone e servire subito.',2487);
INSERT INTO "ricette" VALUES (9345,'Fettine Di Lonza Speziate','Carne','Maiale',4,' -','600 G Lonza Di Maiale A Fettine,
Olio D''oliva,
1 Bicchiere Vino Bianco Secco,
6 Fette Limone,
1 Cucchiaino Curry,
Sale,
Pepe','Rosolate la carne in 4 cucchiai di olio, bagnate con metà del vino e cuocete per 5 minuti. Aggiungete il curry, sale, pepe e cuocete ancora per 10 minuti, bagnando poco per volta con il vino rimasto. Alzate la fiamma, unite le fette di limone e lasciate addensare il sugo. Servite ben caldo.',2477);
INSERT INTO "ricette" VALUES (9346,'Fettine Di Maiale In Padella','Carne','Maiale',4,' -','600 G Fettine Di Lonza Di Maiale,
1 Manciata Capperi Di Pantelleria,
1 Scalogno,
1/2 Limone,
Farina,
Vino Bianco Secco,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Infarinare le fettine di carne e rosolarle nell''olio scaldato con lo scalogno: salare e pepare. Sfumare col vino e unire i capperi dissalati sotto acqua corrente. Dopo pochi minuti unire il succo di mezzo limone, quindi togliere la carne e disporla sui piatti ben caldi; far addensare il fondo di cottura e napparvi le fettine di carne.',2771);
INSERT INTO "ricette" VALUES (9347,'Fettine Di Petto Di Pollo Alla Ave Ninchi','Pollame','Pollo',4,' -','Salvia,
Rosmarino,
50 G Burro,
Petti Di Pollo Surgelati,
2 Mestolini Brodo,
Sale','Soffriggere in una padella un po'' di salvia ed un po'' di rosmarino con circa 50 g di burro. Far dorare da entrambe le parti i petti di pollo ancora surgelati, aggiungere due mestolini di brodo (anche di dado) e lasciarli consumare. A cottura ultimata salare e servire ben caldo.',944);
INSERT INTO "ricette" VALUES (9348,'Fettine Di Petto Di Pollo Alla Valdostana','Pollame','Pollo',4,'Luogo: Val D''Aosta.','Burro,
Olio D''oliva,
Fettine Di Petto Di Pollo Surgelate,
Alcune Foglie Salvia Tritata Finemente,
Sale,
1 Fettina Formaggio Fontina,
1 Fettina Prosciutto','Mettere del burro e dell''olio in un tegame. A burro fuso cuocere le fettine di petto di pollo ancora surgelate per 10 minuti circa rigirandole spesso verso la fine della cottura. Spargere qualche foglia di salvia tritata finemente e un po'' di sale, coprire con una fettina di fontina ed una di prosciutto. Passare nel forno finché il formaggio sarà fuso e servire ben caldo.',2299);
INSERT INTO "ricette" VALUES (9349,'Fettine Di Polenta Guarnite','Primo','Polenta',4,' -','12 Fettine Polenta (fettine Poco Più Grandi Di Un Crostino),
12 Fettine Formaggio Fontina,
12 Gherigli Di Noci','Disponete sulle fettine di polenta una fettina di fontina e un gheriglio di noce. Passate in forno caldo per far sciogliere la fontina e servite.',6589);
INSERT INTO "ricette" VALUES (9350,'Fettine Di Tacchino Ai Formaggi','Pollame','Tacchino',4,' -','500 G Petto Di Tacchino A Fettine,
30 G Burro,
3 Cucchiai Olio D''oliva,
2 Cucchiai Farina,
20 G Formaggio Parmigiano Grattugiato,
20 G Formaggio Pecorino Grattugiato,
Pepe,
Sale','Infarinare la carne e rosolarla in burro e olio caldi, salare e pepare. Mescolare i due formaggi e distribuirli sulla carne poco prima di toglierla dal fuoco. Servire la carne coperta dal sugo di cottura e ben caldo.',2231);
INSERT INTO "ricette" VALUES (9351,'Fettine Di Tacchino Alla Crema Di Latte','Pollame','Tacchino',4,'Luogo: Molise.','4 Fette Petto Di Tacchino,
50 G Burro,
1 Cucchiaio Farina,
20 Cl Vino Bianco Secco,
20 Cl Latte Intero Fresco,
2 Tuorli D''uovo,
1 Limone,
1 Bicchierino Vino Marsala,
Alcuni Steli Erba Cipollina,
Sale,
Pepe','Rosolate le fettine nel burro caldo per 5-10 minuti, quindi eliminate il grasso che si sarà formato durante la cottura, unite il vino e lasciatelo evaporare a fuoco vivace. Aggiungete la farina stemperata nel latte e lasciate cuocere, coperto, per 20 minuti. A fine cottura, unite alla salsa di cottura i tuorli, il succo di mezzo limone e il Marsala, lasciate insaporire per qualche istante, quindi servite le fettine profumate con I''erba cipollina tagliuzzata.',1617);
INSERT INTO "ricette" VALUES (9352,'Fettine Di Vitello Al Forno','Carne','Vitello',4,' -','600 G Fettine Di Vitello,
1/2 Bicchiere Vino Bianco Secco,
Aglio,
Rosmarino,
Prezzemolo,
Salvia,
Timo,
Alloro,
Maggiorana,
4 Cucchiai Olio D''oliva,
1 Bicchiere Brodo,
Sale,
Pepe','Condire le fettine di carne con sale, pepe e il trito aromatico (con aglio, rosmarino, prezzemolo, salvia, timo, alloro, maggiorana, tutti tritati). Sistemarle in una pirofila, irrorare di olio, unire il brodo e il vino. Passare in forno già caldo a 180 gradi fino a quando si sarà formato un sugo ben ristretto.',2215);
INSERT INTO "ricette" VALUES (9353,'Fettine Di Vitello All''aceto','Carne','Vitello',4,' -','400 G Carne Di Vitello In Fettine,
40 G Burro,
1/2 Bicchiere Olio D''oliva,
1 Bicchiere Aceto Di Vino,
Sale,
Pepe','Battete le fettine di vitello. In una terrina sbattete mezzo bicchiere d''olio con un bicchiere d''aceto, sale e pepe. Immergetevi la carne e lasciatela marinare per un''ora. Sgocciolatela. In un tegame lasciate sciogliere il burro e cuocetevi le fettine a fuoco medio per 5 minuti da entrambi i lati. Regolate il sale. Passatele su un piatto da portata caldo e servite. Sprigioneranno un buon profumo e avranno un sapore diverso dal solito. Vini di accompagnamento: Nessun vino quando l''aceto è preponderante nella ricetta, ma i vini bianchi spumantizzati offrono un buon accostamento.',1352);
INSERT INTO "ricette" VALUES (9354,'Fettine Di Vitello All''arancia','Carne','Vitello',4,' -','8 Fettine Girello Di Vitello (fettine Alte 1 Cm),
50 G Mascarpone,
30 G Burro,
2 Cucchiai Pepe Verde,
1 Arancia,
8 Fette Pancarré,
Sale','Fate un profondo taglio verticale al centro della fettina; amalgamate mascarpone e pepe verde; con il composto riempite le fessure del girelli. Sciogliete il burro in un tegame, sistematevi la carne e cuocete sette minuti ; alzate la fiamma spruzzate con il succo d''arancia e fate evaporare. Salate. Disponete sul piatto da portata le fette di pane, bagnatele con il sugo e sopra adagiatevi le fettine. Servite ben caldo.',2381);
INSERT INTO "ricette" VALUES (9355,'Fettine Di Vitello All''uovo E Limone','Carne','Vitello',4,' -','500 G Carne Di Vitello In Fettine,
40 G Burro,
2 Tuorli D''uovo,
1 Limone,
Prezzemolo Tritato,
Farina,
Sale','Infarinate le fettine, cuocetele nel burro per 5 minuti, salatele, toglietele dal tegame e tenetele al caldo. Staccate il fondo di cottura e versate nel recipiente i tuorli sbattuti con il succo del limone e mescolate velocemente. Ricoprite la carne con la salsa ottenuta e cospargetela con prezzemolo tritato. Vini di accompagnamento: Bardolino Classico DOC, Colli Di Luni Rosso DOC, Colli Dell''Etruria Centrale Rosso DOC.',1331);
INSERT INTO "ricette" VALUES (9356,'Fettine Di Vitello Annodate','Carne','Vitello',4,' -','500 G Carne Di Vitello In Fettine Sottili,
Aglio,
1 Cipolla,
4 Foglie Salvia,
1 Rametto Rosmarino,
1/2 Bicchiere Vino Marsala Secco,
Olio D''oliva,
30 G Burro,
Farina,
Prezzemolo Tritato,
Sale,
Pepe','Tritate un rametto di rosmarino con quattro foglie di salvia, l''aglio e la cipolla; rosolateli in un tegame con olio e burro. Tagliate le fettine di carne a strisce e annodatele. Infarinatele e fatele colorire nel tegame girandole. Salate, pepate. Cuocete coperto 20 minuti. Fate addensare il sugo, spruzzate con il Marsala e fate evaporare. Cospargete di prezzemolo tritato. Vini di accompagnamento: Trentino Rosso DOC, La Stoppa VdT Dell''Emilia, Pentro Di Isernia DOC.',1874);
INSERT INTO "ricette" VALUES (9357,'Fettine Di Vitello Coi Peperoni','Carne','Vitello',4,' -','600 G Fettine Di Fesa Di Vitello,
30 G Burro,
2 Peperoni Rossi Carnosi,
2 Peperoni Verdi Carnosi,
1 Manciata Basilico,
1 Mazzetto Prezzemolo,
1 Limone (succo),
Poca Farina,
1/2 Bicchiere Vino Bianco Secco,
Olio D''oliva,
Sale,
Pepe','Battete leggermente le fettine di vitello e mettetele a marinare in qualche cucchiaiata di olio, il prezzemolo tritato, il succo di limone, sale e pepe. Ogni tanto rigirate le fettine di carne nella marinata perché si insaporiscano bene. Intanto infilate i peperoni su una forchetta e fiammeggiateli, strofinateli con un telo per eliminare la pellicina bruciacchiata che li riveste. Poi tagliateli a metè, scartate i semi e le nervature bianche, quindi tagliateli a listerelle sottili. Mettete al fuoco una casseruola con il burro e qualche cucchiaiata di olio, appena il grasso sarà caldo, adagiatevi le fettine di carne scolate dalla marinata e passate leggermente nella farina. Lasciatele rosolare prima a fuoco vivace, spruzzatele con il vino bianco che farete evaporare, quindi abbassate la fiamma e aggiungete i peperoni. Lasciateli ben appassire, poi bagnate la carne con un po'' di acqua o brodo bollente e completate la cottura mantenendo sempre il fuoco basso e mescolando di tanto in tanto. Prima di servire spolverizzate di basilico tritato.',1806);
INSERT INTO "ricette" VALUES (9358,'Fettine Di Vitello E Patate Al Tegame','Carne','Vitello',4,' -','4 Fettine Carne Di Vitello,
30 G Burro,
2 Cucchiai Olio D''oliva,
1 Spicchio Aglio,
1 Rametto Rosmarino,
1 Bicchiere Brodo,
5 Cucchiai Passato Di Pomodoro,
3 Patate,
Sale,
Pepe','Battete leggermente le fettine. In un tegame scaldate burro e olio con l''aglio e il rosmarino, togliendoli appena hanno preso colore. Adagiate nel recipiente la carne e cuocete a fuoco vivo da un parte e dall''altra per un minuto. Riducete il calore, aggiungete il passato e diluite con un po'' di brodo. Coprite e dopo dieci minuti unite le patate sbucciate e tagliate a spicchi. Mescolate, regolate sale e pepe. Coprite e ritirate dal fuoco quando le patate sono diventate morbide.',1595);
INSERT INTO "ricette" VALUES (9359,'Fettine Di Vitello Fumè','Carne','Vitello',4,' -','8 Fettine Carne Di Vitello,
8 Fettine Pancetta Affumicata,
30 G Burro,
2 Uova,
2 Cucchiai Panna,
Sale,
Pepe,
Farina','Salate e pepate le fettine di carne, passatele leggermente nella farina e cuocetele in un tegame con il burro e tre cucchiai di olio. Sbattete le uova, unite la pancetta tagliata a dadetti, la panna, non salate. Versate velocemente il composto sulle fettine, ritirate il tegame sull''angolo del fornello e mescolate la salsa d''uovo in modo che resti fluida e cremosa senza cuocere troppo. Servite con pane leggermente tostato.',4437);
INSERT INTO "ricette" VALUES (9360,'Fettine Di Vitello In Salsa D''olive','Carne','Vitello',4,' -','500 G Carne Di Vitello In Fettine,
12 Olive Verdi,
1 Falda Peperone Rosso In Agrodolce,
Vino Bianco Secco,
40 G Burro,
Olio D''oliva,
Farina,
Sale,
Pepe','In un tegame scaldate burro e olio. Adagiatevi le fettine infarinate e fatele rosolare bene, salate e pepate. Togliete la carne e tenetela al caldo. Versate nel tegame mezzo bicchiere di vino. Lasciate evaporare. Con un cucchiaio di legno staccate il fondo di cottura, aggiungete un po'' d''acqua, le olive snocciolate e la falda di peperone tritata. Scaldate, rimettete la carne nel recipiente e fate insaporire a fuoco vivo per alcuni minuti. Vini di accompagnamento: Rubino Di Cantavenna DOC, Rosso Piceno DOC, Alezio Rosato DOC.',1953);
INSERT INTO "ricette" VALUES (9361,'Fettine Di Vitello Spicciative','Carne','Vitello',4,' -','4 Fettine Vitello,
80 G Burro,
1/2 Misurino Olio D''oliva,
2 Uova,
1 Limone,
Prezzemolo Tritato,
Sale,
Pepe,
50 G Farina','Infarinare le fettine di vitello, rosolarle con burro e olio, quindi salare, pepare e far cuocere per circa 25 minuti. In una terrina sbattere le uova con prezzemolo tritato e succo di limone, quindi versare sulle fettine di vitello e far cuocere per altri 5 minuti.',2030);
INSERT INTO "ricette" VALUES (9362,'Fettine In Agrodolce','Carne','Vitello',4,' -','600 G Fesa Di Vitello A Fette,
50 G Burro,
3 Cucchiai Olio D''oliva,
Prezzemolo,
1 Cucchiaio Zucchero,
4 Cucchiai Aceto Di Vino Bianco,
1 Limone,
Sale','In un largo tegame rosolate le fettine con olio e poco sale. Appena dorate cospargete di prezzemolo tritato. In un altro recipiente sciogliete il burro, unite lo zucchero e fatelo sciogliere lentamente, poi diluite con l''aceto. Mescolate, versate sulla carne la salsa ottenuta, tenete ancora sul fuoco pochi minuti e servite.',2092);
INSERT INTO "ricette" VALUES (9363,'Fettine In Agrodolce (2)','Carne','Vitello',4,' -','600 G Fesa Di Vitello A Fette,
50 G Burro,
3 Cucchiai Olio D''oliva,
Prezzemolo Tritato,
1 Cucchiaio Zucchero,
4 Cucchiai Aceto Di Vino Bianco,
1 Limone,
1 Presa Sale','In 1 largo tegame far rosolare da entrambe le parti le fettine con l''olio e 1 presa di sale. Quando saranno dorate cospargerle col prezzemolo tritato. Intanto, in 1 altro recipiente, far sciogliere il burro e quando sarà colorito unire lo zucchero e lasciarlo sciogliere e appena caramellare, poi diluire con l''aceto. Mescolare, quindi versare sulla carne la salsa ottenuta. Tenere sul fuoco 2 minuti, infine disporre le fettine su 1 piatto da portata e guarnire con il limone tagliato a spicchi.',2092);
INSERT INTO "ricette" VALUES (9364,'Fettine In Salsa','Carne','Vitello',4,' -','400 G Polpa Di Vitellone A Fette,
1 Gambo Sedano,
1 Cipolla,
Prezzemolo,
200 G Pomodoro,
Vino Bianco,
Brodo,
Olio D''oliva,
Burro,
Sale,
1 Spicchio Aglio,
2 Filetti D''acciughe Sott''olio','Soffriggere un trito di sedano e cipolla con poco olio d''oliva, unire il pomodoro, l''aglio e il prezzemolo tritati e le acciughe spezzettate. Salare poco e cuocere coperto per 20 minuti. Sciogliere una noce di burro, unire le fette di carne leggermente salate e cuocerle 5 minuti per parte. Togliere la carne, staccare il fondo e diluirlo con alcuni cucchiai di vino. Unire la carne e il fondo al sugo e cuocere ancora per 5 minuti.',2317);
INSERT INTO "ricette" VALUES (9365,'Fettine Marinate','Carne','Vitello',4,' -','4 Fettine Carne Di Vitello,
3 Spicchi Aglio,
1/2 Bicchiere Olio D''oliva,
2 Cucchiai Prezzemolo Tritato,
Sale','Tritare finemente l''aglio con il prezzemolo. In una terrina mettere l''olio, il trito ed il sale, immergere le fettine di carne e lasciar marinare circa 2 ore. Riscaldare una griglia e mettere a cuocere le fettine una per una poi metterle in un piatto da portata e aggiungere la marinata.',1071);
INSERT INTO "ricette" VALUES (9366,'Fettine Ripiene','Carne','Manzo',4,' -','4 Fettine Manzo,
1 Cipolla,
2 Cucchiai Senape,
2 Cucchiai Olio D''oliva,
Sale','Battere le fettine leggermente con il batticarne fino a renderle molto sottili. Mondare e tritare finemente la cipolla e mescolarla con la senape. Stendere l''impasto in uno strato sottile sulle fettine, quasi fino ai bordi. Piegare le fettine su se stesse e premere bene con le dita lungo i bordi. Friggerle nell''olio bollente un paio di minuti per parte, salando alla fine. Servire ben calde.',1045);
INSERT INTO "ricette" VALUES (9367,'Fettuccine Agli Asparagi','Primo','Asparagi',4,' -','350 G Pasta Tipo Fettuccine,
700 G Asparagi,
10 Cl Latte,
1/2 Dado,
40 G Burro,
1 Cucchiaio Farina,
1 Cucchiaio Olio D''oliva,
Sale','Cuocere per 20 minuti gli asparagi mondati e legati a mazzetti e tenere da parte l''acqua di cottura. Frullare gli asparagi, unirli al latte e al dado e far sobbollire su fuoco dolce per 2 minuti, quindi unire il burro impastato con la farina. Versare l''olio nell''acqua di cottura degli asparagi e cuocervi la pasta. Scolarla, condirla con la crema di asparagi, insaporirla con pepe e servire.',2234);
INSERT INTO "ricette" VALUES (9368,'Fettuccine Agli Asparagi (2)','Primo','Asparagi',4,' -','500 G Asparagi,
320 G Pasta Tipo Fettuccine,
20 G Burro,
2 Uova,
1 Albume D''uovo,
1 Cucchiaino Formaggio Parmigiano Grattugiato,
10 Foglie Basilico,
1/2 Spicchio Aglio,
Olio D''oliva,
Latte,
Panna,
Sale,
Pepe','Mondate e lessate gli asparagi, badando che le punte restino fuori dall''acqua (la stessa acqua di cottura può essere utilizzata per lessare la pasta) poi separate le punte dal resto dei gambi verdi e tenete entrambi in frigo. Sbattete le uova con l''albume, sale, pepe, 1 cucchiaio di parmigiano, 3 di latte e un trito di 10 foglie di basilico e 1/2 spicchio d''aglio. Scaldate poco olio in una padella e con il composto preparate 2 frittatine sottili che arrotolerete e taglierete a listerelle. Conservate anch''esse in frigo. Frullate i gambi degli asparagi con 4 cucchiai di latte e altrettanta panna. Fate insaporire le punte nel burro, poi aggiungete il frullato e salate poco. Lessate le fettuccine, scolatele e conditele con la crema di asparagi e con le listerelle di frittata.',2671);
INSERT INTO "ricette" VALUES (9369,'Fettuccine Ai Fiori D''arancio','Primo','Fiori D''arancio',4,' -','400 G Pasta Tipo Fettuccine,
60 G Fiori D''arancio,
200 G Carne Macinata,
75 G Salsiccia,
4 Pomodori (o Pomodori Pelati),
1 Spicchio Aglio,
1/2 Cipolla,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','In una padella con quattro cucchiai d''olio fate soffriggere la carne tritata, la salsiccia a pezzetti, l''aglio intero (che poi toglierete), la cipolla tritata, quando sono rosolati unite i pomodori sbucciati e tritati o i pelati passati, allungando se necessario con poca acqua tiepida. A cottura quasi ultimata aggiungete i fiori d''arancio e mescolate molto delicatamente. Lessate le fettuccine in acqua salata a bollore, scolatele al dente, conditele con la salsa, decorate con qualche fiore d''arancio.',3489);
INSERT INTO "ricette" VALUES (9370,'Fettuccine Ai Funghi','Primo','Funghi Porcini Secchi',1,' -','1 Busta Funghi Porcini Secchi,
100 Cl Panna Liquida,
100 G Formaggio Parmigiano A Pezzettini,
1 Bicchiere Vino Bianco,
700 G Arista Di Maiale','Steccare la carne con il parmigiano a pezzettini, rosolarla in olio e sfumare con il vino bianco. Unire la panna liquida e cuocere lentamente per 1 ora, aggiungere i funghi rinvenuti e tagliati a pezzi lasciare cuocere ancora per 90 minuti. Condire le fettuccine e servire con parmigiano grattugiato.',6194);
INSERT INTO "ricette" VALUES (9371,'Fettuccine Ai Funghi Porcini','Primo','Funghi Porcini',4,'Luogo: Ciociaria. Luogo: Lazio.','Pasta Tipo Fettuccine,
Funghi Porcini,
Olio D''oliva,
Aglio,
Prezzemolo','Pulite bene i funghi e tagliateli in pezzi abbastanza grossi. Poneteli poi nell''olio caldo, aromatizzato con aglio, e fateli soffriggere. Quando saranno pronti aggiungetevi del prezzemolo fresco tagliato finemente e con la salsa ottenuta conditevi le fettuccine ben scolate. Servire caldo.',1887);
INSERT INTO "ricette" VALUES (9372,'Fettuccine Ai Funghi Porcini (2)','Primo','Funghi Porcini',4,'Luogo: Ciociaria. Luogo: Lazio.','Pasta Tipo Pasta All''uovo,
Funghi Porcini,
Olio D''oliva,
Aglio,
Prezzemolo Fresco,
Vino Bianco Secco,
Formaggio Parmigiano','Far soffriggere i funghi nell''olio d''oliva insaporito con l''aglio. Aggiustare di sale e bagnare con il vino bianco. Far evaporare il vino e completare la cottura. A cottura ultimata mantecate la pasta con la salsa ottenuta, spolverizzate con prezzemolo fresco e una piccola aggiunta di parmigiano.',2318);
INSERT INTO "ricette" VALUES (9373,'Fettuccine Al Burro Bruno','Primo','Burro',4,' -','280 G Pasta Tipo Fettuccine,
50 G Burro,
5 Cucchiai Sugo D''arrosto,
60 G Formaggio Grattugiato,
Sale','Lessate le fettuccine in abbondante acqua salata. Nel frattempo in una padella lasciate sciogliere il burro a fuoco dolce e poi diluitevi il sugo d''arrosto che deve essere piuttosto concentrato. Scolate poco la pasta, rovesciatela nella padella della salsa, mescolate e passate sul piatto da portata tenuto in caldo. Cospargete con il formaggio grattugiato e servite. Vini di accompagnamento: Trebbiano Di Romagna DOC, Orvieto DOC, Biferno Bianco DOC.',1889);
INSERT INTO "ricette" VALUES (9374,'Fettuccine Al Cognac','Primo','Cognac',4,' -','500 G Pasta Tipo Fettuccine All''uovo,
80 G Burro,
50 G Formaggio Parmigiano Grattugiato,
1 Bicchierino Cognac,
Sale,
Pepe','Cuocere le fettuccine al dente in abbondante acqua salata, scolarle e metterle in una terrina. Condirle con il burro fuso, il cognac, il parmigiano e il pepe e servirle calde.',2751);
INSERT INTO "ricette" VALUES (9375,'Fettuccine Al Forno','Primo','Mozzarella',4,' -','500 G Pasta Tipo Fettuccine All''uovo,
200 G Mozzarella,
100 G Burro,
1/2 Bicchiere Latte,
100 G Formaggio Parmigiano Grattugiato,
Sale,
1 Tazza Salsa Di Pomodoro','Scolate le fettuccine e conditele subito con 60 g di burro e 50 g di parmigiano. Imburrate una pirofila e disponetevi le fettuccine. Cospargete di mozzarella tagliata a dadini e bagnate con il latte. Versate sul tutto il pomodoro, il restante parmigiano e qualche fiocchetto di burro. Ponete in forno caldo finché la mozzarella sarà sciolta.',3536);
INSERT INTO "ricette" VALUES (9376,'Fettuccine Al Mais','Primo','Mais',4,' -','400 G Pasta Tipo Fettuccine All''uovo,
350 G Mais In Scatola,
300 G Pisellini Surgelati,
100 G Panna,
1/2 Cipolla,
Formaggio Grana Grattugiato,
Olio D''oliva,
Burro,
Sale,
Pepe','Far soffriggere la cipolla tritata in una casseruola con olio e burro; unire il mais, i piselli, il sale, il pepe e far cuocere coperto per circa 20 minuti; versare la panna e cuocere ancora per 5 minuti. Cuocere le fettuccine al dente in abbondante acqua salata, condirle con la salsa preparata e il grana e servire.',4228);
INSERT INTO "ricette" VALUES (9377,'Fettuccine Al Pesto Di Funghi','Primo','Funghi Porcini',4,' -','300 G Pasta Tipo Fettuccine All''uovo Secche,
400 G Funghi Porcini,
1 Spicchio Aglio,
4 Foglie Basilico,
1 Manciata Prezzemolo Tritato,
1 Manciata Pinoli,
Olio D''oliva Extra-vergine,
Sale Marino Integrale,
Pepe','Brasare i funghi con aglio e olio; aggiustare di sale e di pepe e cospargere di prezzemolo. In un mixer mettere il basilico, i pinoli, i funghi e frullare rapidamente facendo cadere olio crudo a filo. Condirvi la pasta al dente non troppo scolata.',2350);
INSERT INTO "ricette" VALUES (9378,'Fettuccine Al Pesto Di Mandorle','Primo','Mandorle Spellate',4,' -','400 G Pasta Tipo Fettuccine,
70 G Mandorle Spellate,
1 Spicchio Aglio,
1/2 Limone (scorza Gialla),
40 G Formaggio Parmigiano Grattugiato,
50 G Insalata Rucola,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Servendovi di un mixer, tritate insieme le mandorle, l''aglio, la buccia del limone, la rucola, il parmigiano grattugiato, il sale, il pepe e l''olio d''oliva extra-vergine fino ad ottenere una salsina cremosa e omogenea. Nel frattempo, scottate in acqua salata le fettuccine, scolatele al dente e conditele con il pesto di mandorle. Mescolate energicamente il tutto e se necessario, aggiungete un po'' d''acqua di cottura e continuate a mescolare. Servitele subito calde.',2768);
INSERT INTO "ricette" VALUES (9379,'Fettuccine Al Polpo','Primo','Polipo',4,' -','350 G Pasta Tipo Fettuccine,
600 G Polipo,
1 Cipolla,
4 Pomodori Maturi,
Aglio,
Prezzemolo,
Basilico,
Vino Bianco Secco,
Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Pulire il polpo, privarlo di becco e occhi e lavarlo bene; tagliarlo in pezzi e rosolarlo in un intingolo di aglio cipolla, peperoncino, olio e far saltare a fuoco vivo; sfumare col vino, unire la polpa dei pomodori in pezzi, prezzemolo e cuocere a fuoco lento per 40 minuti. Lessare le fettuccine , unirle all''intingolo e rifinire col basilico.',2534);
INSERT INTO "ricette" VALUES (9380,'Fettuccine Al Pomodoro','Primo','Pomodori',4,' -','500 G Pasta Tipo Fettuccine,
500 G Pomodori Da Sugo,
50 G Burro,
1 Cipolla,
Formaggio Parmigiano Grattugiato,
Basilico,
Olio D''oliva,
Sale','Far appassire la cipolla tritata nell''olio, unire i pomodori passati al setaccio, il sale, il basilico e far cuocere la salsa finché sarà ben densa. Cuocere le fettuccine al dente in abbondante acqua salata, condirli con la salsa preparata, il burro, il parmigiano e servire.',3435);
INSERT INTO "ricette" VALUES (9381,'Fettuccine Al Salmone','Primo','Salmone',4,' -','120 G Salmone Affumicato,
30 G Burro,
20 Cl Panna,
2 Manciata Formaggio Parmigiano,
300 G Pasta Tipo Tagliatelle All''uovo,
Sale,
Pepe','Cuocere le tagliatelle molto al dente. Tagliare il salmone a striscioline e metterlo in una padella con il burro. Saltare le tagliatelle nella padella con la panna e il grana. Quando la panna è completamente evaporata aggiungere il sale e il pepe. Volendo si può aggiungere alla fine una manciata di prezzemolo fresco tritato.',2586);
INSERT INTO "ricette" VALUES (9382,'Fettuccine Al Salmone (2)','Primo','Salmone',1,'Ricetta adatta a: bambini piccoli.','2 Nidi Pasta Tipo Fettuccine,
1 Omogeneizzato Di Salmone,
1 Cucchiaino Olio D''oliva Extra-vergine','Portate a bollore 250 g d''acqua e lessate le fettuccine per 8 muniti circa. Nel piatto, stemperate l''omogeneizzato con un paio di cucchiai d''acqua della pasta. Unite le fettuccine scolate, condite con l''olio e servite.',590);
INSERT INTO "ricette" VALUES (9383,'Fettuccine Al Salmone (3)','Primo','Salmone',3,' -','300 G Pasta Tipo Fettuccine Casarecce,
3 Noci Burro,
60 G Salmone Affumicato,
Panna Da Cucina,
Tabasco,
1 Pizzico Semi Di Finocchio,
Vodka','Far insaporire il burro con i semi di finocchio e scaldarvi il salmone precedentemente sminuzzato; a questo punto fiammeggiare con la vodka. Dopo aver aggiunto la panna e il Tabasco, passare le fettuccine in padella rimestando affinché possano insaporirsi per bene. Riporle in piatto caldo e servirle.',3643);
INSERT INTO "ricette" VALUES (9384,'Fettuccine Al Salmone E Vodka','Primo','Salmone Affumicato',4,' -','500 G Pasta Tipo Fettuccine All''uovo Fresche,
50 G Salmone Affumicato A Fettine Sottili,
25 Cl Panna Liquida,
60 G Burro,
1/2 Bicchierino Vodka,
Sale','Tagliare il salmone a striscioline e farlo saltare in padella con 20 g di burro per 2 minuti, unire la panna e rigirando con 1 cucchiaio di legno farla addensare a fuoco basso, quindi aggiungere la vodka continuando a rigirare. Intanto, lessare la pasta in acqua leggermente salata, scolarla e versarla nella padella. Mescolarla al condimento, unire il restante burro, rimescolare e servire subito.',3402);
INSERT INTO "ricette" VALUES (9385,'Fettuccine Al Tonno','Primo','Tonno',4,' -','500 G Pasta Tipo Fettuccine All''uovo,
4 Spicchi Aglio,
200 G Tonno,
1 Cucchiaio Capperi,
Prezzemolo,
Basilico,
Olio D''oliva,
Sale','Far dorare l''aglio nell''olio, unire il tonno sminuzzato, i capperi e far rosolare per pochi minuti. Cuocere le fettuccine al dente in abbondante acqua salata, metterle nella padella con il tonno, far insaporire, cospargere con il prezzemolo e il basilico tritati e servire.',3146);
INSERT INTO "ricette" VALUES (9386,'Fettuccine Al Tonno (2)','Primo','Tonno Sott''olio',4,' -','400 G Pasta Tipo Fettuccine,
80 G Tonno Sott''olio,
200 G Pomodori Pelati,
1 Cipolla,
2 Acciughe,
Sale,
Pepe,
Olio D''oliva','Rosolare la cipolla sottilmente affettata in olio di oliva e stemperarvi le acciughe dissalate, spinate e spezzettate, poi aggiungere i pomodori tritati e lasciar restringere a fuoco lento per 10 minuti. Unire il tonno sbriciolato con poco del suo olio, coprire e lasciar cuocere lentamente per altri 15-20 minuti. Condire la pasta.',2474);
INSERT INTO "ricette" VALUES (9387,'Fettuccine Alla Bottarga Di Tonno','Primo','Bottarga Di Tonno',1,' -','350 G Pasta Tipo Fettuccine,
200 G Panna Da Cucina,
70 G Burro,
30 G Formaggio Parmigiano Grattugiato,
1 Cucchiaio Bottarga Di Tonno A Filetti,
1/2 Scorza Di Limone','Sciogliere il burro in padella senza farlo friggere. Aggiungere, fuori dal fuoco, la bottarga riducendola in poltiglia con una forchetta e infine la panna. Lessare la pasta e versarla in una zuppiera aggiungendo il parmigiano e la buccia grattugiata di 1/2 limone. Intanto riscaldare il sughetto e, al primo bollore, versarlo sulle fettuccine.',2386);
INSERT INTO "ricette" VALUES (9388,'Fettuccine Alla Marinara','Primo','Cozze',4,' -','Per La Pasta:,
300 G Spinaci,
Sale,
400 G Farina,
4 Uova,
Per Il Condimento:,
1000 G Cozze,
1 Cipolla,
1 Carota,
1 Costa Sedano,
25 Cl Vino Bianco,
1 Mazzetto Basilico,
1 Ciuffo Prezzemolo,
1 Spicchio Aglio,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe,
2 Cucchiai Salsa Di Pomodoro','Mondate e lavate ripetutamente gli spinaci, poi cuoceteli con la sola acqua rimasta aderente dal lavaggio ed una manciata di sale grosso. Scolateli, lasciateli intiepidire un poco, quindi strizzateli bene e passateli al setaccio, raccogliendo il passato in una terrina. Disponete la farina a fontana sulla spianatoia, rompetevi nel centro le uova, unite una presa di sale ed il passato di spinaci. Cominciate impastando prima con delicatezza, quindi lavorate energicamente e a lungo e fate un panetto di pasta che metterete a riposare per 30 minuti, coperto da un panno umido. Nel frattempo strofinate energicamente le cozze sotto l''acqua corrente con una spazzola di saggina. Preparate un trito finissimo di cipolla, carota e sedano, opportunamente puliti e lavati, se necessario, e ponetelo in una casseruola insieme alle cozze e metà del vino. Mettete il recipiente su fuoco allegro: dopo qualche istante le cozze si apriranno spontaneamente. Levate la casseruola dalla fiamma, togliete i molluschi dalle conchiglie (eliminando quelli con le valve chiuse) e filtrate il liquido di cottura. Mondate, lavate, strizzate il basilico ed il prezzemolo e tritateli finemente insieme all''aglio sbucciato. Ponete il trito in un tegame con l''olio e fatelo colorire, quindi insaporite con una presa di sale ed un pizzico di pepe. A questo punto unite il sugo delle cozze e fatelo asciugare a fuoco vivace, aggiungendo infine la salsina di pomodoro ed il restante vino bianco. Lasciate cuocere per circa 10 minuti, tenendo la fiamma al minimo. Pochi istanti prima di togliere dal fuoco il tegame, unite anche i molluschi. Mettete ora a scaldare, in una pentola, l''acqua per cuocere la pasta, unite una manciata di sale grosso ed attendete che giunga ad ebollizione. Frattanto dividete in due parti il panetto di pasta e stendete con il matterello, sulla spianatoia infarinata, due sfoglie sottili, avvolgete ognuna su se stessa ed affettatela a listarelle di circa 1 cm. Fate cuocere quindi le tagliatelle in acqua bollente, scolatele bene al dente, versatele nella zuppiera e conditele con le cozze ed il loro sugo. Servite caldissimo.',3195);
INSERT INTO "ricette" VALUES (9389,'Fettuccine Alla Menta','Primo','Menta',4,' -','320 G Pasta Tipo Fettuccine,
1 Pugno Foglie Di Menta (30/50 G),
2 Limoni (scorza Gialla Grattugiata),
3 Cucchiai Formaggio Parmigiano Reggiano,
Olio D''oliva Extra-vergine,
Sale,
1 Pizzico Pepe Rosa,
1 Pizzico Pepe Verde','Tritare le foglie di menta, unire la buccia dei limoni e gli altri ingredienti. Mescolare accuratamente con l''olio fino a dare al tutto la consistenza di un pesto, che assume un bel colore tra il giallo e il verde. Intanto si fa bollire l''acqua per cuocere la pasta, circa 80 g a testa. Quando le fettuccine sono cotti, si scolano e si passano nel pesto, mescolando accuratamente. Dalla terrina si sprigionerà subito un profumo intenso di menta e limone.',2157);
INSERT INTO "ricette" VALUES (9390,'Fettuccine Alla Mozzarella','Primo','Mozzarella',4,' -','400 G Pasta Tipo Fettuccine,
200 G Mozzarella,
4 Filetti D''acciughe,
100 G Burro,
50 G Formaggio Parmigiano Grattugiato,
Sale,
1 Pizzico Pepe','Cuocere le fettuccine in acqua bollente, e nel frattempo tagliare la mozzarella a cubetti. Sciogliere il burro in tegame ed unire le acciughe. Una volta sciolto il burro, unite le fettuccine e mescolare. A questo punto aggiungete i cubetti di mozzarella e mescolate tenendo la fiamma bassa, dopodichè aggiungete un pizzico di pepe e di sale e il parmigiano servendo il tutto molto caldo.',2912);
INSERT INTO "ricette" VALUES (9391,'Fettuccine Alla Papalina','Primo','Prosciutto Cotto',4,' -','400 G Pasta Tipo Fettuccine Fresche,
100 G Prosciutto Cotto,
1/2 Cipolla,
40 G Burro,
150 G Piselli Freschi Sgranati,
2 Uova,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Soffriggere la cipolla affettata con il burro, aggiungere i piselli, e, a cottura ultimata, mettere il prosciutto tagliato a pezzettini; condire con sale e pepe. In una terrina sbattere le uova e unire 2 cucchiaiate di parmigiano. Far cuocere le fettuccine in abbondante acqua bollente salata, scolarle, unirle alle uova, aggiungere il prosciutto e piselli, un po'' di burro e parmigiano. Spolverizzare con pepe e servire subito.',2664);
INSERT INTO "ricette" VALUES (9392,'Fettuccine Alla Ricotta','Primo','Ricotta Romana',4,' -','400 G Pasta Tipo Fettuccine,
300 G Ricotta Romana,
1 Cucchiaio Latte,
Alcune Foglie Menta Fresca,
Olio D''oliva,
Sale,
1 Macinata Pepe','Cuocere le fettuccine in abbondante acqua salata. Intanto mettere la ricotta nel piatto da portata e incorporare 1 cucchiaio di latte, mescolando sino ad ottenere una crema omogenea. Scolare le fettuccine al dente e rovesciarle sopra la ricotta, mescolare delicatamente con 2-3 cucchiai d''acqua di cottura della pasta mista a olio. Cospargere con la menta e una macinata abbondante di pepe.',2626);
INSERT INTO "ricette" VALUES (9393,'Fettuccine Alla Risciò','Primo','Funghi Porcini',4,'Luogo: Ciociaria. Luogo: Lazio.','Pasta Tipo Tagliatelle,
Funghi Porcini,
Cipolla,
Piselli,
Pomodoro,
Panna,
Olio D''oliva,
Sedano,
Basilico,
Sale','Soffriggere la cipolla in un po'' d''olio e farla rosolare con pancetta e funghi. Aggiungere il pomodoro e proseguire fino a metà cottura. A questo punto unire i piselli e a cottura ultimata la panna. Mantecarvi le fettuccine e servire ben caldo.',2206);
INSERT INTO "ricette" VALUES (9394,'Fettuccine Alle Verdure','Primo','Piselli',4,' -','320 G Pasta Tipo Fettuccine,
300 G Piselli Surgelati,
200 G Punte Di Asparagi Surgelate,
2 Zucchine,
2 Porri,
Formaggio Parmigiano,
Olio D''oliva,
Prezzemolo,
Basilico,
Sale,
Pepe','Mondate e lavate le verdure poi tagliate a rondelle i porri e affettate le zucchine tagliandole per il lungo. In un tegame fate appassire in 3 cucchiai d''olio i porri, unite gli asparagi ancora surgelati, quindi le zucchine. Salate, pepate, mescolate e cuocete le verdure per 8/10 minuti. Fuori dal fuoco aggiungete un bel trito di prezzemolo e basilico e un filo d''olio. Lessate le fettuccine in abbondante acqua calda, scolatele ben al dente, versatele nella padella con le verdure e fatele saltare per qualche minuto. Trasferite in un piatto da portata, cospargete con abbondante parmigiano grattugiato e servite.',2655);
INSERT INTO "ricette" VALUES (9395,'Fettuccine Allo Speck','Primo','Speck',4,' -','350 G Pasta Tipo Fettuccine,
100 G Speck,
1 Cipolla,
Prezzemolo,
20 Cl Panna,
1 Bustina Zafferano,
Burro,
1 Cucchiaio Olio D''oliva,
Sale','Tritare la cipolla, lo speck e il prezzemolo. Rosolare speck e cipolla in 20 g di burro. Cuocere la pasta in acqua bollente con l''aggiunta dell''olio. Scolarla e rovesciarla nella padella con lo speck. Sciogliere lo zafferano nella panna, versarla sulla pasta, unire il prezzemolo, mescolare e far saltare qualche minuto.',3358);
INSERT INTO "ricette" VALUES (9396,'Fettuccine Con Fagioli','Primo','Fagioli Cannellini',6,' -','300 G Pasta Tipo Fettuccine,
200 G Fagioli Cannellini In Scatola,
800 G Polpa Di Pomodoro,
50 G Pancetta,
1 Cipolla,
1 Presa Origano,
Basilico,
Olio D''oliva,
Sale,
Pepe','Rosolare in olio la pancetta a dadini con la cipolla tritata poi unire il pomodoro, sale, pepe e basilico e cuocere per 15 minuti. Unire i fagioli sgocciolati, una presa di origano, mescolare e cuocere per 10- 15 minuti a fuoco basso. Lessare le fettuccine, scolarle e condirle con il sugo preparato.',2298);
INSERT INTO "ricette" VALUES (9397,'Fettuccine Con Polpa Di Granchio E Salsa Alle Erbe','Primo','Polpa Granchio',4,' -','300 G Pasta Tipo Fettuccine,
2 Cipollotti,
150 G Polpa Di Granchio,
1 Bicchierino Absolut Vodka,
1 Mazzetto Prezzemolo,
Erba Cipollina,
10 Cl Panna,
1 Cucchiaio Bacche Di Pepe Rosa,
4 Cucchiai Olio D''oliva,
Sale','Mondate i cipollotti, lavateli, tagliateli a striscioline e fateli soffriggere in una padella con 4 cucchiai d''olio, poi unite la polpa di granchio e bagnate con la vodka; fatela evaporare, aggiungete il prezzemolo tritato, l''erba cipollina tagliuzzata, la panna e il pepe rosa pestato e sbriciolato. Cuocete la salsa a fiamma bassissima, senza farle raggiungere l''ebollizione, per qualche minuto. Lessate la pasta al dente in abbondante acqua bollente salata, scolatela lasciandola leggermente umida, conditela con il sugo preparato e servite.',3251);
INSERT INTO "ricette" VALUES (9398,'Fettuccine Con Seppioline','Primo','Seppioline',4,' -','Per La Pasta:,
200 G Farina,
2 Uova,
Sale,
Per Il Condimento:,
350 G Seppioline,
200 G Bietole,
1 Scalogno,
3 Cucchiai Olio Di Girasole,
Peperoncino,
Prezzemolo,
Sale,
Pepe','Setacciate la farina e disponetela a fontana sulla spianatoia. Mettetevi al centro le uova e il sale e lavorate con le mani gli ingredienti fino a ottenere un impasto morbido e omogeneo. Lasciate riposare la pasta per mezz''ora circa in luogo fresco, dopo averla avvolta in un canovaccio umido. Nel frattempo private le seppioline della pellicina esterna e delle interiora; lavatele, scolatele, asciugatele e tagliatene una parte ad anelli. Mondate le bietoline, privatele dei gambo e utilizzate solo le foglie; lavatele, asciugatele con un canovaccio e tagliatele a listarelle. Con il matterello stendete la pasta in una sfoglia molto sottile. Infarinate la superficie della sfoglia, arrotolatela su sè stessa e, con un coltello ben affilato, ricavatene le fettuccine della larghezza di un centimetro circa. Stendetele sulla spianatoia infarinata e fatele asciugare. In un padella con l''olio e il peperoncino, fate appassire lo scalogno tritato; aggiungete le bietole e fatele rosolare per un minuto; unitevi le seppioline e fatele insaporire per 2 minuti circa, mescolando di tanto in tanto. Insaporite quindi con sale e pepe e continuate la cottura per 7-8 minuti a fuoco moderatissimo. Portate a ebollizione una pentola di acqua, salatela e fatevi cuocere le fettuccine; scolatele al dente e versatele nella padella con il composto di seppioline, cospargete con il prezzemolo tritato e mescolate delicatamente. Versate le fettuccine sul piatto di portata e servitele calde.',1640);
INSERT INTO "ricette" VALUES (9399,'Fettuccine Deliziose','Primo','Prosciutto',4,' -','250 G Pasta Tipo Fettuccine All''uovo,
100 G Prosciutto Crudo Grasso E Magro,
1 Bustina Funghi Secchi,
30 G Burro,
20 Foglioline Basilico Fresco,
40 G Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Lasciate ammorbidire i funghi nell''acqua, strizzateli e spezzettateli. In un pentolino insaporite nel burro il prosciutto tritato, i funghi e il basilico; salate e pepate. Lessate le fettuccine, scolatele, conditele con la salsa e cospargetele di formaggio grattugiato. Servite.',1804);
INSERT INTO "ricette" VALUES (9400,'Fettuccine Della Domenica','Primo','Uovo',4,' -','250 G Pasta Tipo Fettuccine All''uovo Fresche,
150 G Carne Di Vitello Magra Macinata,
1 Uovo,
100 G Formaggio Parmigiano Reggiano Grattugiato,
2 Zucchine,
1 Cipolla,
Olio D''oliva,
Sale,
Pepe','Preparate polpettine piccole come noci impastando la carne, salata e pepata, con l''uovo e il parmigiano. Fatele rosolate in un soffritto di cipolla e olio d''oliva, poi aggiungete le zucchine tagliate finemente. Fate cuocere per 10 minuti, aggiustate di sale e condite le fettuccine cotte in abbondante acqua salata.',2326);
INSERT INTO "ricette" VALUES (9401,'Fettuccine Di Carne','Carne','Manzo',4,' -','500 G Polpa Di Manzo,
Basilico,
1 Spicchio Aglio,
1/2 Bicchiere Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Far leggermente imbiondire l''aglio nell''olio, quindi eliminarlo e alzare la fiamma. Aggiungere subito la carne affettata sottilmente e tagliata a striscioline. Farla scottare per 2'', salare, pepare e unire il basilico spezzettato; bagnare con il vino e far ridurre a fuoco alto. Servire subito ben caldo.',1303);
INSERT INTO "ricette" VALUES (9402,'Fettuccine Di Carne Di Vitello','Carne','Vitello',4,' -','500 G Carne Di Vitello In Fettine,
Prezzemolo,
Salvia,
Timo,
10 Cipolline,
1/2 Bicchiere Vino Marsala,
1 Noce Burro,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate la carne a striscioline. In un tegame mettete tre cucchiai d''olio, le erbe aromatiche tritate, la carne, sale e pepe. Rosolate a fuoco basso, bagnando ogni tanto con poca acqua calda. Lessate in acqua salata le cipolline, scolatele, unitele alla carne, portate a cottura spruzzandole spesso con il Marsala. Prima di spegnere mantecate la salsa con una noce di burro. Vini di accompagnamento: Botticino DOC, Aprilia Merlot DOC, Don Pietro Rosso VdT Di Sicilia.',2280);
INSERT INTO "ricette" VALUES (9403,'Fettuccine Dorate','Primo','Pangrattato',4,' -','400 G Pasta Tipo Fettuccine All''uovo,
20 G Margarina,
2 Cucchiai Pangrattato,
Basilico,
Formaggio Pecorino Grattugiato,
Sale','Cuocere le fettuccine al dente in abbondante acqua salata. In una padella far dorare il pangrattato e il basilico tritato nella margarina, aggiungere le fettuccine e farle dorare a fuoco vivo, cospargere con il pecorino e servire.',2042);
INSERT INTO "ricette" VALUES (9404,'Fettuccine Fantasia','Primo','Peperone Rosso',4,' -','320 G Pasta Tipo Fettuccine,
1 Cipolla Fresca,
1 Peperone Giallo,
1 Peperone Rosso,
25 G Funghi Secchi,
Peperoncino,
6 Pomodorini Maturi,
Sale,
Olio D''oliva','Mettete i funghi a rinvenire in acqua tiepida (cambiatela almeno 3 volte per eliminare la terra). Tagliare a fettine la cipolla e fatela appassire in una casseruola con poco olio, aggiungete i peperoni tagliati a striscioline fate cuocere per qualche minuto e aggiungete i funghi e i pomodori tagliati a pezzetti e un po'' di peperoncino. Aggiustate di sale, fate cuocere per 10 minuti aggiungendo, se necessario, un po'' d''acqua. Cuocete le fettuccine in abbondante acqua salata e conditele con la salsa mantecando sul fuoco con un filo d''olio d''oliva.',2135);
INSERT INTO "ricette" VALUES (9405,'Fettuccine Fila E Fondi','Primo','Mozzarella',4,' -','400 G Pasta Tipo Fettuccine,
200 G Mozzarella,
4 Filetti D''acciughe Sott''olio,
100 G Burro,
Formaggio Parmigiano Grattugiato,
Sale,
Pepe','In una padella antiaderente, fate sciogliere il burro e unite i filetti d''acciughe sott''olio precedentemente tagliati a pezzetti. Lasciate insaporire per pochi minuti e nel frattempo, tagliate la mozzarella a dadini e disponetela in un recipiente. Nel frattempo, scottate in acqua salata bollente le fettuccine, scolatele al dente e versatele in padella. Aggiungete la mozzarella e amalgamate energicamente il tutto a fiamma regolare, unite il pepe, il parmigiano grattugiato e servite subito. Accorgimento: conservate l''acqua di cottura, potrebbe servire nel caso in cui le fettuccine tendessero ad asciugarsi.',3110);
INSERT INTO "ricette" VALUES (9406,'Fettuccine In Bella Vista','Primo','Peperoni',4,' -','500 G Pasta Tipo Fettuccine,
500 G Peperoni,
50 G Burro,
3 Spicchi Aglio,
Basilico,
50 G Guanciale Di Maiale,
Sale,
Pepe','Fate sbollentare per pochi minuti i peperoni, dopo averli tagliati a metà e liberati dai semi; quindi tagliateli a striscioline. Metteteli ad insaporire nella casseruola dove avrete fatto rosolare il burro con l''aglio, qualche foglia di basilico e il guanciale tagliato a pezzettini. Lasciate cuocere per 10 minuti; salate e pepate un momento prima di levare dal fuoco. Cuocete intanto la pasta in abbondante acqua bollente salata. Scolatela al dente e conditela con i peperoni e il loro intingolo.',2637);
INSERT INTO "ricette" VALUES (9407,'Fettuccine In Salsa','Primo','Salsiccia',4,' -','400 G Pasta Tipo Fettuccine,
150 G Manzo,
50 G Mortadella,
1 Scatola Pelati,
1/2 Bicchiere Vino,
4 Scalogni,
2 Cucchiai Olio D''oliva,
30 G Burro,
150 G Salsiccia,
100 G Piselli Surgelati,
2 Cucchiai Mascarpone,
2 Cucchiai Formaggio Parmigiano,
Basilico,
Sale,
Pepe','Imbiondire gli scalogni tritati nell''olio e burro. Unire la mortadella e il manzo tritati, la salsiccia sbriciolata e i pisellini e far rosolare. Unire il vino e, appena sarà evaporato, anche i pelati. Salare, pepare e cuocere 30'' a fuoco dolce. Lessare la pasta al dente e condirla con il sugo, il mascarpone, il parmigiano e il basilico sminuzzato.',3508);
INSERT INTO "ricette" VALUES (9408,'Fettuccine In Salsa Bianca','Primo','Panna',4,' -','Pasta Tipo Pasta All''uovo,
60 G Burro,
4 Cucchiai Panna,
80 G Formaggio Grattugiato,
Sale,
Pepe','Fate la pasta, tiratela a sfoglia, piegatela e tagliate le fettuccine. In un tegamino sciogliete a fuoco dolce il burro, aggiungete metà formaggio grattugiato e un po'' di pepe. Lessate le fettuccine in abbondante acqua salata. Scolatele rapidamente e mettetele di nuovo nel recipiente di cottura aggiungendo la panna e il restante formaggio. Mescolate e passate le fettuccine sul piatto da portata tenuto in caldo. Aggiungete il burro fuso e cospargete di pepe macinato. Servite. Vini di accompagnamento: Bianco Di Custoza DOC, Colli Martani Grechetto DOC, Gravina Bianco DOC.',2149);
INSERT INTO "ricette" VALUES (9409,'Fettuccine Leggere','Primo','Patata',2,' -','180 G Pasta Tipo Fettuccine,
100 G Bietole,
1 Patata,
40 G Formaggio Fontina,
20 G Burro,
20 G Formaggio Parmigiano Grattugiato,
6 Foglie Salvia,
Sale,
2 Cucchiai Olio D''oliva Extra-vergine','Mettete a cuocere in abbondante acqua salata la patata sbucciata e affettata con le bietole pulite e tagliate a pezzetti. Dopo 15 minuti aggiungete la pasta e finite la cottura. Scolate le fettuccine con la verdura e travasatele in una zuppiera alternandole con fettine sottili di fontina. Fate sciogliere il burro con la salvia. Spegnete e incorporate l''olio, quindi condite il contenuto della zuppiera. Aggiungete il formaggio grana e servite.',1606);
INSERT INTO "ricette" VALUES (9410,'Fettuccine Prosciutto E Mozzarella','Primo','Prosciutto',4,' -','400 G Pasta Tipo Fettuccine All''uovo,
100 G Prosciutto Cotto,
Mozzarella,
Burro','Tagliare a dadini la mozzarella ed il prosciutto; cuocere le fettuccine all''uovo e scolarle al dente; mettere in una zuppiera un po'' di burro, poi le fettuccine, il prosciutto e la mozzarella; mantecare il tutto, quindi servire calde.',2884);
INSERT INTO "ricette" VALUES (9411,'Fettuccine Rosa','Primo','Pomodori Pelati',4,' -','350 G Pasta Tipo Fettuccine,
30 G Formaggio Parmigiano,
30 G Formaggio Groviera,
300 G Pomodori Pelati,
Rosmarino,
Prezzemolo,
Aglio,
1 Cucchiaio Ketchup,
1 Bicchiere Panna,
1 Bicchiere Brandy,
Poca Paprica','Far insaporire in padella l''aglio e il rosmarino tritato con la panna, unire un cucchiaio di ketchup, il brandy, i pelati e far cuocere per 10 minuti. Cuocere le fettuccine al dente, versarle nella padella, cospargerle con parmigiano e groviera grattugiati, prezzemolo tritato e poca paprica e servire.',2304);
INSERT INTO "ricette" VALUES (9412,'Fettunta','Antipasto','Olio D''oliva',4,' -','Pane Casereccio Raffermo,
Aglio,
Pepe,
Olio D''oliva,
Sale','Tagliare il pane a fette lasciando la crosta che ha attorno e abbrustolito finché le due parti siano croccanti fuori, ma morbide dentro. Ancora calde strofinarle da una sola parte con aglio, salarle e peparle con pepe appena macinato. Cospargerle di abbondante olio d''oliva e servire calde.',1022);
INSERT INTO "ricette" VALUES (9413,'Fiadoni','Dessert','Formaggio',10,' -','Per La Pasta:,
1000 G Farina,
7 Uova Intere,
4 Tuorli D''uovo,
200 G Zucchero,
200 G Strutto,
Poco Sale,
Scorza Di Limone Grattugiata,
Per Il Ripieno:,
1000 G Formaggio Di Pecora Salato Fresco,
100 G Formaggio Parmigiano,
150 G Formaggio Secco Dolce,
200 G Zucchero,
5 Uova','Si lascia scolare il formaggio di pecora per circa 2 giorni. Si prepara la pasta. Si grattugiano insieme tutti i formaggi, poi vi si uniscono lo zucchero e le uova sbattute, mescolando bene. Si stende la pasta non troppo sottile e si taglia in dischi di circa 10 cm di diametro. Si mette si ogni disco un po'' di ripieno, si piega a metà, si sigilla e si indora con un po'' d''uovo. Si cuociono poi i fiadoni al forno.',11929);
INSERT INTO "ricette" VALUES (9414,'Fiammiferi Al Formaggio','Antipasto','Pasta Sfoglia',4,' -','1 Confezione Pasta Sfoglia Surgelata,
1 Cucchiaio Formaggio Groviera Grattugiato,
1/2 Cucchiaio Formaggio Parmigiano Grattugiato,
1/4 Besciamella Densa,
1 Pizzico Pepe','Stendere la pasta in una sfoglia rettangolare di 5 mm di spessore e larga 8 cm. Unire alla besciamella il groviera e il pepe, quindi spalmarla sulla sfoglia e spolverizzarla con il parmigiano grattugiato. Tagliare quindi la sfoglia in rettangoli di 2 cm di larghezza e disporli sulla placca da forno dopo averla inumidita con acqua fredda. Cuocere a 220 gradi per circa 10 minuti.',1460);
INSERT INTO "ricette" VALUES (9415,'Fiammingo','Bevande','Gin',1,' -','1/4 Succo Di Limone,
3/4 Gin,
Per Completare:,
Soda,
Per Servire:,
1 Scorza Di Limone','Agitare, con cubetti di ghiaccio, nello shaker. Riempire il gotto basso per metà, aggiungere soda ben fredda e servire con una scorza di limone.',312);
INSERT INTO "ricette" VALUES (9416,'Fichi Al Cioccolato','Dessert','Fichi Secchi',4,' -','16 Fichi Secchi Molto Morbidi,
150 G Cioccolato Fondente,
50 G Burro,
30 G Mandorle In Polvere,
16 Mandorle Pelate','Tagliate via il picciuolo ai fichi e aprite i frutti a metà nel senso della lunghezza. Spezzettate il cioccolato, mettetelo in una casseruola con 3 cucchiai di acqua e fatelo fondere in un bagnomaria tiepido. Levate dal fuoco, unite il burro a pezzettini, sempre sbattendo, e poi la polvere di mandorle. Fate raffreddare per un''ora in frigorifero. Formate delle noci di composto e inseritele nei fichi, affondandovi poi una mandorla intera. Richiudete i fichi e disponeteli in pirrottini di carta.',4274);
INSERT INTO "ricette" VALUES (9417,'Fichi Al Cognac','Dessert','Fichi',4,' -','1000 G Fichi Sodi,
500 G Zucchero,
1 Pezzo Cannella,
Chiodi Di Garofano,
Cognac','Lavate i fichi e punzecchiateli. Metteteli in una pentola in un unico strato e copriteli di zucchero. Portate a ebollizione su fuoco molto basso rigirando di tanto in tanto i fichi finché lo zucchero non sia sciolto. Alzate quindi la fiamma e fate cuocere per 5 minuti, dopodichè togliete dal fuoco e fate riposare per 24 ore a pentola coperta. Sistemate i fichi in 2 vasi da 1 l, unitevi la cannella e i chiodi di garofano e quindi il cognac fino a coprirli. Per avere un gusto meno forte è possibile mescolare in parti uguali cognac e sciroppo.',2836);
INSERT INTO "ricette" VALUES (9418,'Fichi Al Cognac (2)','Dessert','Fichi',4,' -','1000 G Fichi Sodi Non Troppo Maturi,
500 G Zucchero,
1 Pezzettino Cannella,
4 Chiodi Di Garofano,
Cognac','Lavare i fichi, punzecchiarli con un ago da cucina e metterli in unico strato in una casseruola. Coprire con lo zucchero e scaldare, smuovendoli fino a quando lo zucchero sia sciolto, quindi cuocere a fuoco vivo per 5 minuti. Togliere dal fuoco, coprire e far riposare i fichi per 24 ore. Sistemarli quindi in vasi di vetro da 1 litro con chiodi di garofano, cannella, metà sciroppo, metà cognac.',5090);
INSERT INTO "ricette" VALUES (9419,'Fichi Al Forno','Dessert','Fichi',4,' -','8 Fichi Grandi Maturi,
8 Cucchiai Zucchero,
2 Limoni (scorza)','Lavare delicatamente i fichi, poi senza asciugarli, rotolarli nello zucchero, in modo che ne rimangano coperti. Sistemarli in una pirofila che li contenga di misura, aggiungere un po'' d''acqua e la scorza dei limoni a pezzetti. Cuocerli in forno già caldo a 160 gradi per circa 10 minuti. Quando lo zucchero si sarà caramellato, toglierli dal forno e lasciarli raffreddare nello stesso recipiente di cottura. Servirli su piattini individuali.',631);
INSERT INTO "ricette" VALUES (9420,'Fichi Al Limone','Dessert','Fichi',4,' -','Succo Di Limone,
Fichi Ben Maturi,
Zucchero,
Sherry (o Vino Porto)','Prendere dei fichi ben maturi, dopo averli pelati e tagliati a metà, disponeteli a strati in un recipiente di vetro; su ogni strato di fichi mettere una buona quantità di zucchero e succo di limone. Continuare così fino a completare il recipiente. Tenerli per due ore a temperatura ambiente, in modo da ottenere una leggera fermentazione degli zuccheri che, combinandosi con il limone, formeranno un sugo molto gradevole. Metterli a raffreddare per un''oretta in frigo, prima di servirli. Si possono gustare anche al pomeriggio accompagnando i fichi con sherry o porto, subito dopo il primo assaggio.',383);
INSERT INTO "ricette" VALUES (9421,'Fichi Al Miele','Dessert','Fichi',4,' -','Fichi Neri,
Miele,
Granella Di Mandorle','Sbucciare i fichi e cospargerli di miele e granella di mandorle.',300);
INSERT INTO "ricette" VALUES (9422,'Fichi Al Porto','Dessert','Fichi',6,' -','24 Fichi,
1 Bicchiere Vino Porto,
6 Cucchiai Zucchero,
60 G Burro,
200 G Mandorle A Filetti,
Panna Montata Zuccherata','Sbucciare delicatamente i fichi per non romperli. In un tegame sciogliere il burro, disporvi i fichi e spolverizzarli con lo zucchero e le mandorle. Bagnare con il porto. Cuocere a fuoco medio per circa 5-10 minuti finché lo zucchero si sarà sciolto. Rigirare i fichi nel fondo di cottura e levare dal fuoco. Mettere i fichi in un vassoio, ricoprirli con il fondo di cottura e decorare i bordi del vassoio con la panna montata.',3182);
INSERT INTO "ricette" VALUES (9423,'Fichi Alla Panna','Dessert','Fichi',4,' -','12 Fichi,
25 Cl Panna,
2 Cucchiai Cognac','Lavare e asciugare i fichi senza sbucciarli. Tagliarli a quarti e sistemarli in coppe individuali. A parte mescolare la panna molto fredda con il cognac e versarla sui fichi. Tenerli nel frigorifero un''ora e più, servire molto fresco.',1570);
INSERT INTO "ricette" VALUES (9424,'Fichi Alla Panna (2)','Dessert','Fichi',4,' -','8 Fichi Bianchi,
200 G Panna Montata,
40 G Zucchero,
Rum','Sbucciate i fichi avendo cura di non romperli, tagliateli a stella, cospargeteli con lo zucchero, spruzzateli con il rum e lasciate in frigo un paio d''ore. Montate la panna senza aggiungere zucchero. Disponete i fichi su un piatto da portata rotondo, accomodate al centro di ognuno abbondanti cucchiaiate di panna e con un cucchiaino versatevi sopra un po'' del loro sugo.',1022);
INSERT INTO "ricette" VALUES (9425,'Fichi Alla Siriana','Dessert','Fichi Secchi',4,' -','500 G Fichi Secchi Senza Peduncoli,
25 Cl Succo D''arancia,
150 G Zucchero,
150 G Mandorle Sbucciate,
1 Cucchiaio Succo Di Limone,
1 Cucchiaio Scorza Di Limone Grattugiata','In una pentola mettere il succo d''arancia, quello di limone, la scorza di limone, i fichi 3 cucchiai di zucchero e portare a ebollizione. Abbassare il fuoco, coprire e far cuocere per circa 40 minuti. Sgocciolare e far raffreddare i fichi. Con un coltello inciderli e inserire 1 mandorla nel taglietto. Richiuderli e passarli nello zucchero.',2993);
INSERT INTO "ricette" VALUES (9426,'Fichi Alle Spezie','Dessert','Fichi',6,' -','12 Fichi Maturi,
200 G Zucchero,
2 Arance (scorza),
1 Stecca Cannella,
16 Grani Coriandolo,
10 Grani Pepe,
4 Chiodi Di Garofano,
2 Centimetri Zenzero Fresco Tagliato A Julienne,
2 Pizzichi Spezie (cannella, Coriandolo, Pepe)','Mettete in una pentola 100 cl di acqua insieme allo zucchero, alle bucce d''arancia e a tutte le spezie e fate bollire per 10 minuti. Immergete i fichi nello sciroppo e lasciateli, senza farli bollire, su fuoco dolce, per 5 minuti. Scolate i fichi, metteteli sul piatto fondo da portata e tenete da parte. Riducete lo sciroppo della metà senza farlo bollire e quando è freddo, dopo averlo passato in un colino, versatelo sui fichi. Usate le bucce d''arancia per decorare i fichi.',1381);
INSERT INTO "ricette" VALUES (9427,'Fichi Alle Spezie (2)','Dessert','Fichi',6,' -','12 Fichi Maturi,
100 G Zucchero,
1 Scorza D''arancia,
Cannella,
Coriandolo,
2 Chiodi Di Garofano,
Zenzero','In una casseruola mescolate le spezie, aggiungete lo zucchero, la buccia d''arancia a listerelle e mezzo litro d''acqua. Fate bollire per 10 minuti. Immergetevi i fichi interi per pochi minuti, senza portare a bollore. Lasciateli intiepidire nel loro sciroppo, poi sgocciolateli e metteteli in una coppa di vetro. A fuoco moderato fate ridurre lo sciroppo della metà e versatelo sui fichi in modo da coprirli. Lasciate raffreddare, servite.',927);
INSERT INTO "ricette" VALUES (9428,'Fichi Caramellati','Dessert','Fichi',4,' -','16 Fichi Verdi Ben Maturi,
200 G Zucchero','Pulite i fichi con uno strofinaccio umido senza rovinare la buccia e disponeteli su un piatto da portata. In un pentolino fate caramellare lo zucchero con circa 4 cucchiai d''acqua, ma attenzione a non farlo diventare troppo scuro. Quando è pronto versatelo sui fichi, lasciate rapprendere e mettete in frigo per qualche ora.',1376);
INSERT INTO "ricette" VALUES (9429,'Fichi Fritti','Dessert','Fichi',6,' -','12 Fichi Maturi,
125 G Farina,
100 G Vino,
50 G Zucchero A Velo,
2 Cucchiai Zucchero Semolato,
1 Uovo,
100 G Lamponi,
1/2 Cucchiaio Olio D''oliva,
Olio Per Friggere,
Per Guarnire:,
Menta,
Ribes','In una ciotola, amalgamate la farina con il tuorlo dell''uovo (conservate l''albume che va montato in neve ben soda con 40 g di zucchero a velo); stemperate l''impasto con il vino, quindi incorporatevi mezza cucchiaiata di olio d''oliva e l''albume montato. Lasciate riposare la pastella e, intanto, frullate circa 100 g di lamponi con 2 cucchiaiate di zucchero semolato, ottenendo una densa salsina che passerete al setaccio. Pelate i fichi che dovranno essere maturi ma sodi, passateli nella pastella, tuffateli nell''olio caldo, girateli affinché prendano un colore uniforme, quindi toglieteli con il mestolo forato, spolverizzateli abbondantemente di zucchero a velo e serviteli accompagnandoli con la salsina di lamponi e una guarnizione di ribes e menta.',2257);
INSERT INTO "ricette" VALUES (9430,'Fichi Ripieni','Dessert','Fichi',4,' -','8 Fichi Ben Sodi,
2 Cucchiai Pinoli,
2 Cucchiai Mandorle Tritate,
2 Albumi D''uovo,
2 Biscotti Amaretti,
2 Cucchiai Zucchero','Lavare i fichi e inciderli al centro aprendoli un po''. Tostare pinoli e mandorle in un padellino antiaderente. Montare a neve ferma gli albumi e incorporarvi i pinoli, le mandorle, lo zucchero e gli amaretti sbriciolati. Poggiare i fichi su una placca da forno e riempirli con il composto. Infornare per 15 minuti a 200 gradi, finché gli albumi non saranno ben dorati.',658);
INSERT INTO "ricette" VALUES (9431,'Fichi Sciroppati','Dessert','Fichi',4,' -','1000 G Fichi Maturi Sodi,
900 G Zucchero,
1 Limone,
1 Bustina Zucchero Vanigliato,
1/2 Bicchiere Vino Bianco','Distribuire i fichi sul fondo di una casseruola larga. Spolverizzateli con lo zucchero vanigliato. Bagnateli con il vino ed il succo di limone quindi ponete sul fornello e fate cuocere per circa 1 ora a fiamma bassa. Spegnete e sistemate i frutti in un vaso, facendo attenzione a non romperli. Coprite con lo sciroppo ottenuto dalla cottura e sterilizzate a bagnomaria per 30 minuti.',4241);
INSERT INTO "ricette" VALUES (9432,'Fichi Sciroppati (2)','Dessert','Fichi',4,' -','1000 G Fichi,
1 Bicchiere Aceto Di Vino,
400 G Zucchero,
1 Bastoncino Vaniglia','Mettete in una pentola i fichi con aceto, la vaniglia e 400 g di zucchero. Mescolate bene con un cucchiaio di legno in modo che i fichi rimangano interi e lasciate cuocere per 45 minuti. Togliete dal fuoco e mettete i fichi con il loro succo di cottura in vasi di vetro. Lasciate raffreddare e poi chiudete ermeticamente.',2214);
INSERT INTO "ricette" VALUES (9433,'Fichi Secchi Al Cioccolato','Dessert','Fichi Secchi',4,' -','500 G Fichi Secchi,
200 G Cioccolato Fondente,
100 G Mandorle Tostate,
1/2 Bicchiere Vermouth','In un pentolino, sciogliete a bagnomaria il cioccolato. Tagliate i fichi e introducete in ognuno di essi una mandorla tostata. Chiudeteli bene con le dita e immergeteli, servendovi di una forchetta, uno per volta nel cioccolato fuso. Subito dopo, disponeteli su un piano ricoperto con della carta da forno e lasciateli raffreddare in un luogo fresco. Serviteli dopo pranzo, accompagnandoli con un buon vino secco. Accorgimento: se il cioccolato fuso dovesse risultare troppo denso, diluitelo con qualche goccia di vermouth.',3270);
INSERT INTO "ricette" VALUES (9434,'Fichi Secchi Al Cioccolato (2)','Dessert','Fichi Secchi',4,' -','500 G Fichi Secchi,
200 G Cioccolato Fondente,
100 G Gherigli Di Noci,
1/2 Bicchiere Vermouth','In un pentolino, sciogliete a bagnomaria il cioccolato. Tagliate i fichi e introducete in ognuno di essi un gheriglio di noce. Chiudeteli bene con le dita e immergeteli, servendovi di una forchetta, uno per volta nel cioccolato fuso. Subito dopo, disponeteli su un piano ricoperto con della carta da forno e lasciateli raffreddare in un luogo fresco. Serviteli dopo pranzo, accompagnandoli con un buon vino secco. Accorgimento: se il cioccolato fuso dovesse risultare troppo denso, diluitelo con qualche goccia di vermouth.',3345);
INSERT INTO "ricette" VALUES (9435,'Fichi Ubriachi','Dessert','Fichi',4,' -','1000 G Fichi,
500 G Zucchero,
Alcool Per Liquori,
Cannella','Pulite i fichi con una pezzuola umida, punzecchiateli con uno stuzzicadenti e disponeteli in una casseruola a strati con lo zucchero. Coprite e lasciate sul fuoco basso finché inizia il bollore. Fate riposare per 24 ore, poi disponete i fichi nei vasi aggiungendo la cannella. Fate concentrare lo sciroppo rimasto sul fondo della pentola, aggiungetelo poi ai fichi. Lasciate raffreddare e completate con l''alcool.',2770);
INSERT INTO "ricette" VALUES (9436,'Fiesta','Bevande','Vodka',1,' -','1/5 Kummel,
1/5 Gin,
3/5 Vodka','Agitare nello shaker con ghiaccio in cubetti. Servire nel flute senza alcuna decorazione.',388);
INSERT INTO "ricette" VALUES (9437,'Fiesta (2)','Bevande','Rum Bianco',1,' -','5/8 Rum Bianco,
1/8 Cointreau,
2/8 Succo Di Limone,
1 Cucchiaino Zucchero In Polvere,
1 Cucchiaino Sciroppo Di Granatina,
Per Allungare:,
Acqua Gassata,
Per Decorare:,
1 Spirale Scorza Di Limone','Versare i primi 5 ingredienti in un mixing-glass con del ghiaccio frantumato. Mescolare bene con il cucchiaio. Passare in un bicchiere a tulipano. Allungare con acqua gassata. Decorare con una spirale di scorza di limone, un ombrellino di carta e una bambolina sempre di carta.',379);
INSERT INTO "ricette" VALUES (9438,'Fiesta Cocktail','Bevande','Rum Bianco',1,' -','2/4 Rum Bianco,
1/4 Calvados,
1/4 Vermouth Bianco Secco','Versare gli ingredienti in uno shaker con alcuni cubetti di ghiaccio. Mescolare. Versare in un bicchiere da cocktail.',299);
INSERT INTO "ricette" VALUES (9439,'Fifth Avenue','Bevande','Apricot Brandy',1,' -','1/3 Crema Cacao,
1/3 Apricot Brandy,
1/3 Panna Liquida','Versare delicatamente nel tumbler stretto in modo che gli ingredienti non si mescolino tra loro. Il bicchiere va precedentemente raffreddato nel frigorifero.',319);
INSERT INTO "ricette" VALUES (9440,'Fifty','Bevande','Cognac',1,' -','1 Tuorlo D''uovo,
1/2 Cucchiaio Salsa Worcester,
1/2 Cucchiaio Cognac,
1 Spruzzo Aceto Di Vino,
1 Spruzzo Succo Di Pomodoro,
1 Spruzzo Angostura,
Per Servire:,
1 Peperoncino Rosso Intero','Agitare energicamente nel mixer con ghiaccio in cubetti. Servire nel gotto basso, aggiungendo un peperoncino rosso intero.',269);
INSERT INTO "ricette" VALUES (9441,'Fiftyfive','Bevande','Vermouth Dry',1,' -','1/2 Vermouth Dry,
1/2 Gin','Mettete due cubetti di ghiaccio nel bicchiere da Martini, versate il vino e il liquore e mescolate delicatamente.',309);
INSERT INTO "ricette" VALUES (9442,'Fil De Fer','Bevande','Whisky',1,' -','4/6 Whisky Rye,
2/6 Granatina,
2/6 Succo Di Limone,
Poche Gocce Angostura','Shakerare gli ingredienti con ghiaccio e servire in bicchieri da cocktail aggiungendo qualche cubetto di ghiaccio. Adatto a tutte le occasioni',324);
INSERT INTO "ricette" VALUES (9443,'Filetti Agli Agrumi','Carne','Vitello',4,' -','4 Filetti Di Vitello Da 150 G Ciascuno,
30 G Burro,
3 Cucchiai Olio D''oliva,
1 Bicchiere Succo Di Limone E Pompelmo Filtrato,
1 Cucchiaino Estratto Di Carne,
Sale','In una padella rosolare la carne con olio e burro. Salarla e unire l''estratto di carne diluito in 1 cucchiaio di acqua. Spruzzare i filetti con il succo dei due agrumi e mescolare bene con un cucchiaio. Far cuocere a fiamma media per circa 10-12 minuti, finché il sugo è ben ristretto. Servire i filetti coperti dal fondo di cottura.',1899);
INSERT INTO "ricette" VALUES (9444,'Filetti Al Gin','Carne','Manzo',4,' -','400 G Filetto Di Manzo In 4 Fette,
40 G Burro,
4 Cucchiai Gin,
Poco Olio D''oliva,
Sale,
Pepe','Scaldare poco olio in una padella antiaderente e cuocervi i filetti da entrambi i lati a fuoco vivo. Togliere la carne dal fuoco e tenerla in caldo. Pulire la padella con carta da cucina e farvi fondere il burro a fuoco basso, unire il gin, sale e pepe. Disporre i filetti in un piatto da portata e versavi sopra la salsa calda.',1538);
INSERT INTO "ricette" VALUES (9445,'Filetti Alla Senape','Carne','Manzo',4,' -','400 G Filetti Di Manzo,
40 G Burro,
1 Cucchiaio Senape Piccante,
1 Cucchiaino Salsa Worcester,
6 Cucchiai Cognac,
Olio D''oliva,
Sale','Scaldare l''olio in una padella, cuocervi a fuoco vivo i filetti, levarli e tenerli in caldo. Eliminare l''olio dalla padella e farvi fondere metà burro, stemperarvi la senape, unire la salsa worcester, il cognac e una presa di sale. Cuocere la salsa mescolando a fuoco vivo. Fuori dal fuoco unire il burro rimasto e farlo sciogliere. Mettere i filetti su un piatto da portata, irrorarli con la salsa e servirli subito.',2048);
INSERT INTO "ricette" VALUES (9446,'Filetti Aromatici','Carne','Manzo',4,' -','4 Filetti Di Manzo,
1/2 Bicchiere Olio D''oliva,
Cipolla,
Sedano,
Prezzemolo,
Pepe,
Sale','Tritare la cipolla e le erbe. Mettere i filetti in un piatto dai bordi alti e coprirli con il trito, l''olio, sale e pepe. Lasciar marinare per 4-5 ore. Scolare i filetti e cuocerli sulla bistecchiera caldissima, spennellandoli con la marinata.',1439);
INSERT INTO "ricette" VALUES (9447,'Filetti D''anatra Ai Fichi','Pollame','Anatra',4,' -','1 Anatra Piccola,
25 Cl Vino Rosso,
2500 G Fichi Freschi,
50 G Burro,
Pancarré,
1 Limone,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe','Svuotate l''anatra, eliminate testa, collo e zampe. Delle interiora tenete da parte soltanto il fegato. Salatela e pepatela internamente. Legatela con lo spago bianco da cucina. Adagiatela in una teglia con 10 g di burro e l''olio. Cuocete per un''ora in forno a 230 gradi. Ritirate, tagliate le ali, il petto e le cosce. Rompete con il batticarne le carcasse. Versate nella teglia di cottura il vino rosso e mescolate. Disponetevi le carcasse e cuocete per 10 minuti in forno a 200 gradi. Poi passate il sugo al mulinetto e raccoglietelo in un pentolino, insaporitelo con un po'' di succo di limone. Tritate il fegato e aggiungetelo alla salsa. Tagliate i fichi quasi a metà, apriteli leggermente. Mettete su ognuno un fiocchetto di burro. Sistemateli in una teglia imburrata e lasciate colorire in forno. Ritirate e insaporite con sale e pepe. Dorate le fette di pancarré nel restante burro. Disossate le cosce e tagliatele a fettine. Tagliate a filetti anche il petto. Sistemate tutto al centro del piatto da portata e intorno disponete i fichi. Nappate con la salsa calda. Servite. Vini di accompagnamento: Ghemme DOC, Flaccianello VdT Di Toscana, Cabernet Sauvignon Di Regaleali VdT Di Sicilia.',5384);
INSERT INTO "ricette" VALUES (9448,'Filetti Del Buongustaio','Pollame','Tacchino',4,' -','4 Fette Tacchino,
4 Fettine Formaggio Emmenthal,
4 Fette Prosciutto Cotto,
1 Uovo,
50 G Pangrattato,
3 Cucchiai Olio D''oliva,
80 G Burro,
Sale,
Pepe','Nettate con cura le fette di tacchino, eliminando le eventuali parti grasse e le nervature appiattitele leggermente con il batticarne; passatele quindi nell''uovo sbattuto e nel pangrattato.Fatto ciò, ponete metà burro e l''olio d''oliva in un largo tegame e fate scaldare, quando i due condimenti arrivano a friggere, mettete in un tegame le fette di tacchino e fatele cuocere a calore moderato 4-5 minuti per parte; prima di toglierle dal fuoco, cospargetele con il sale necessario e una macinatina di pepe.Dopodichè, ungete una pirofila con il burro che resta, adagiatevi sul fondo i filetti di tacchino, senza sovrapporli, con il loro fondo di cottura, su ciascuna ponete una fetta di prosciutto cotto piegata in due e una fetta d''emmenthal tagliata in misura.Trasferite la pirofila in forno già caldo (200 gradi) e lasciate cuocere per 5-6 minuti, il tempo di far sciogliere il formaggio.Al termine, trasferite i filetti di tacchino sul piatto di portata, versatevi sopra il fondo di cottura e servite.',4478);
INSERT INTO "ricette" VALUES (9449,'Filetti Di Aringa Marinati','Pesce','Filetti Di Aringa',4,'Luogo: Belgio.','Filetti Di Aringa,
Limone,
Cipolla,
Olio D''oliva,
Aceto Di Vino,
Latte,
Tuorli D''uovo,
Prezzemolo,
Maionese,
Scalogno,
Per Servire:,
Fagioli Bianchi','E'' un piatto a base di filetti di aringa dal gusto molto particolare. Per realizzarlo fate marinare i filetti con limone e cipolla, olio e aceto. Miscelate il latte con i tuorli d''uovo sodo, il prezzemolo, la maionese e lo scalogno. E aggiungete questa mistura ai filetti. Lasciate riposare per un''ora. Servite freddo e con un contorno di fagioli bianchi.',1804);
INSERT INTO "ricette" VALUES (9450,'Filetti Di Aringhe Con Cipolle','Pesce','Aringhe Affumicate',4,' -','8 Aringhe Affumicate,
8 Cipolle Rosse,
1 Limone,
100 Cl Latte,
2 Bicchieri Aceto Di Vino,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulite le aringhe e ricavatene dei filetti che lascerete riposare nel latte bollente per almeno due ore. Per lo stesso tempo lasciate marinare le cipolle tagliate a rondelle nell''aceto, poi sciacquatele in acqua, asciugatele e conditele con olio, sale e pepe. Scolate e i filetti di aringa dal latte e asciugateli poggiandoli su della carta assorbente da cucina; poi disponeteli in un piatto di portata, conditeli con olio, succo di limone, sale, pepe e mescolateli assieme alle fettine di cipolla.',2429);
INSERT INTO "ricette" VALUES (9451,'Filetti Di Branzino Con Crema Di Cipolle','Pesce','Branzino',4,' -','1500 G Branzino (pesci Da 750 G L''uno),
800 G Cipolle Gialle,
50 G Pancetta Tesa A Fettine,
Prezzemolo,
120 G Olio D''oliva Extra-vergine,
Sale,
Pepe Nero','Infornate a 180 gradi le cipolle che dovranno essere di media grossezza, senza sbucciarle. Fatele cuocere per circa 1 ora, o finché saranno molto morbide. Mentre le cipolle cuociono, squamate i branzini, eviscerateli, lavateli e sfilettateli privandoli anche della pelle. Quando le cipolle saranno quasi cotte, salate, pepate i filetti di branzino, fateli rosolare a fuoco vivo in 20 g di olio e, separatamente, in una padella antiaderente, rosolate a fuoco moderato le fettine di pancetta ridotte a striscioline. Sfornate le cipolle, pelatele, passatele al mixer ottenendo una densa crema; insaporitela con un pizzico di sale, 100 g di olio e una generosa manciata di pepe. Distribuitela nei piatti da porzione, sopra sistematevi i filetti rosolati, completate con la pancetta e con un trito di prezzemolo, quindi servite.',3081);
INSERT INTO "ricette" VALUES (9452,'Filetti Di Cernia All''arancia','Pesce','Cernia',4,' -','2 Filetti Di Cernia,
1 Arancia,
30 G Burro,
Farina,
Prezzemolo,
Sale,
Pepe','Far fondere il burro, passarvi i filetti di cernia infarinati rosolandoli da ambo i lati, salare, pepare e bagnare con il succo d''arancia. Servire spolverizzando il tutto con il prezzemolo.',883);
INSERT INTO "ricette" VALUES (9453,'Filetti Di Cernia All''uvetta E Olive','Pesce','Cernia',4,' -','4 Filetti Cernia (filetti Da 150 G Ognuno),
600 G Polpa Di Pomodoro,
12 Olive Liguri,
2 Spicchi Aglio,
40 G Uvetta Sultanina,
1 Spruzzo Vino Bianco Secco,
Farina,
Prezzemolo,
Alcune Fette Pane Casereccio,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Sbucciate l''aglio e fatelo rosolare leggermente in un tegame largo, meglio se antiaderente, con 4 cucchiai di olio. Schiacciate lo spicchio con una forchetta, eliminatelo e mettete in pentola i filetti di cernia infarinati. Fateli insaporire per qualche istante e bagnateli con uno spruzzo di vino bianco. Alzate la fiamma e lasciate evaporare il vino. Togliete i filetti di cernia dal tegame e teneteli in caldo. Versate nel sughetto del pesce il pomodoro e l''uvetta. Salate, pepate e continuate la cottura per 10 minuti. Mettete di nuovo nel tegame i filetti di cernia, unite le olive e abbondante prezzemolo mondato, lavato e spezzettato con le mani e regolate di sale e pepe. Servite il pesce con qualche fetta di pane tostato in forno.',3205);
INSERT INTO "ricette" VALUES (9454,'Filetti Di Fagiano All''arancia','Pollame','Fagiano',4,' -','1 Fagiano,
1 Arancia,
60 G Burro,
1 Bicchiere Vino Bianco Secco,
Alcune Bacche Ginepro,
20 Cl Brodo,
Sale,
Pepe In Grani','Disossate il fagiano, tagliate la carne a fettine e tenete da parte la carcassa. In una padella lasciate sciogliere il burro con alcune bacche di ginepro, cuocetevi i filetti di carne a fuoco moderato per circa 20 minuti. In un''altra pentola versate il vino, il brodo, alcuni grani di pepe e il sale. Immergetevi la carcassa e portate a bollore. Continuate la cottura fino a quando il liquido è ridotto alla metà. Filtratelo ed eventualmente sgrassatelo. Al momento di servire riscaldate i filetti nella salsa, aggiungete il succo d''arancia, lasciate bollire ancora 2 minuti. Disponete sul piatto da portata, servite subito. Vini di accompagnamento: Oltrepò Pavese Pinot Nero DOC, Morellino Di Scansano DOC, Gioia Del Colle Rosso DOC.',2164);
INSERT INTO "ricette" VALUES (9455,'Filetti Di Fesa Di Tacchino Con Asparagi','Pollame','Tacchino',4,' -','400 G Fesa Di Tacchino,
300 G Punte Di Asparagi,
1 Scalogno,
1 Ciuffo Prezzemolo,
Pepe Verde,
30 G Burro,
1/2 Limone,
Olio D''oliva,
Sale,
8 Fette Pane Tostato','Tritate lo scalogno, fatelo insaporire in olio e burro. Unite le punte degli asparagi e un ciuffo di prezzemolo tritato; lasciate insaporire alcuni minuti, bagnate con qualche cucchiaio d''acqua, coprite e cuocete per 15 minuti. Tagliate la fesa di tacchino a filetti, appena gli asparagi sono cotti unite il pepe pestato e la carne. Mescolate e cuocete a fiamma bassa; salate, spruzzate con il succo di limone. Lasciate insaporire, suddividete carne e asparagi sulle fette di pane tostate e servite ben caldo.',2730);
INSERT INTO "ricette" VALUES (9456,'Filetti Di Halibut Con Funghi E Aromi','Pesce','Halibut',4,' -','4 Filetti Di Halibut,
200 G Funghi Champignon,
1 Spicchio Aglio,
1 Scalogno,
1 Cucchiaio Timo Fresco Tritato,
1 Cucchiaio Prezzemolo Fresco Tritato,
2 Pomodori Perini,
1 Cucchiaio Pangrattato,
2 Cucchiai Succo Di Limone,
Sale,
Pepe,
Olio D''oliva Extra-vergine','Innanzi tutto scalda il forno a 200 gradi. Schiaccia l''aglio e trita lo scalogno. Pulisci ed affetta i funghi. Scalda l''olio e facci imbiondire aglio e cipolla a fuoco medio. Unisci i funghi e falli scottare per pochi minuti. Profuma con le erbe tritate e aggiungi i pomodori che avrai pelato e tagliato a tocchetti, sale, pepe e pangrattato. Mescola e leva dal fuoco. Ungi una pirofila con dell''olio extra vergine e mettici i filetti di pesce. Copri con l''intruglio funghesco e spruzza con il succo di limone. Copri con dell''alluminio ed inforna per una 15 di minuti. Se il fondo di cottura dovesse risultare troppo liquido, scopri e rimetti in forno per pochi minuti, giusto per asciugare un po''. Servi con patate novelle cotte a vapore e irrorate con l''olio extra vergine.',1155);
INSERT INTO "ricette" VALUES (9457,'Filetti Di Manzo Agli Odori','Carne','Manzo',6,' -','1000 G Filetto Di Manzo,
50 G Pancetta,
2 Bicchieri Brodo,
1/2 Bicchiere Vino Marsala,
30 G Burro,
2 Cucchiai Olio D''oliva,
2 Foglie Salvia,
1 Carotina,
1 Gambo Sedano,
1 Rametto Rosmarino,
1 Pizzico Noce Moscata,
Sale,
Pepe','Tagliate la pancetta a fiammifero e picchettate con queste il filetto in più punti, poi legatelo. In una casseruola scaldate burro e olio, rosolatevi la carne girandola in continuazione. Salate. Aggiungete carota e sedano a pezzetti, gli odori. Bagnate il filetto con il vino e il Marsala, fate evaporare. Insaporite con un pizzico di noce moscata e uno di pepe. Coprite e lasciate cuocere a fuoco moderato per un''ora abbondante. Ritirate, lasciate riposare dieci minuti e tagliate a fette. Servite con contorno di rape bianche al burro.',2202);
INSERT INTO "ricette" VALUES (9458,'Filetti Di Manzo Al Pepe Rosa Su Crostone Di Pane Con Bieta','Carne','Manzo',4,' -','300 G Filetto Di Manzo,
2 G Pepe Rosa,
1 Bicchiere Vino Porto,
1 Fetta Pancarré,
500 G Bieta,
15 G Pinoli,
1 Spicchio Aglio,
Sale,
Pepe','Scottare i filetti di manzo, precedentemente conditi con sale, pepe e pepe rosa; aggiungere il vino ed ultimare la cottura. Intanto, in una padella con olio, mettere a cuocere il pane da entrambi i lati ed asciugarlo. Sbollentare la bieta in acqua salata e saltarla in padella con olio ed aglio, infine aggiungere i pinoli.',936);
INSERT INTO "ricette" VALUES (9459,'Filetti Di Manzo Al Ribes','Carne','Manzo',4,' -','4 Filetti Di Manzo,
Gelatina Di Ribes,
1 Cucchiaio Ribes,
Erbe Aromatiche Miste Tritate,
1/2 Bicchiere Vino Bianco Secco,
1 Bicchiere Vino Marsala,
1 Cipolla,
1 Carota,
1 Spicchio Aglio,
1 Arancia,
Olio D''oliva,
Sale,
Pepe','Insaporite nell''olio, erbe aromatiche, cipolla e carota tritate; versate il vino e cuocete cinque minuti, salate, pepate e lasciate insaporire la carne in questa marinata 2 ore. Sgocciolate i filetti e rosolateli in olio caldo per cinque minuti, irrorateli con un po'' di marinata passata da un colino, portate a cottura. Bollite, in una casseruola, il marsala con il succo e la scorza dell''arancia a filetti, unite la gelatina e i frutti di ribes. Disponete i filetti su un piatto da portata, irrorateli con la salsa e servite.',2001);
INSERT INTO "ricette" VALUES (9460,'Filetti Di Merluzzo Affogati In Salsa Di Yogurth Alla Mentuccia','Pesce','Merluzzo',4,' -','1 Merluzzo Da 500 G,
1 Vasetto Yogurth Intero,
1 Rametto Mentuccia,
1 Cucchiaio Farina,
1/2 Bicchiere Latte,
30 G Burro,
Sale,
Pepe','Sfilettare il pesce, salare e infarinare i filetti, rosolarli per 5 minuti nel burro e infornarli a 100 gradi. Nella stessa padella versare lo yogurth e il latte, spruzzare con farina, salare, pepare, unire la mentuccia, cuocere a fuoco lento per 10 minuti circa. Sfornare il pesce, coprirlo con la salsa e guarnire con la mentuccia.',780);
INSERT INTO "ricette" VALUES (9461,'Filetti Di Merluzzo Ai Capperi','Pesce','Merluzzo',4,' -','8 Tranci Merluzzo (anche Surgelati),
1 Cucchiaio Capperi Sotto Sale,
2 Cucchiai Prezzemolo Tritato,
1 Rametto Rosmarino,
1 Spicchio Aglio,
3 Cucchiai Pangrattato,
1 Bicchiere Vino Bianco,
Olio D''oliva','Sciacquate i capperi sotto l''acqua corrente e frullateli con il pangrattato, prezzemolo, un cucchiaino di rosmarino, lo spicchio d''aglio sbucciato e 4 cucchiai d''olio.Accendete il forno a 220 gradi Disponete i filetti di merluzzo in una teglia leggermente unta d''olio, copriteli con il trito aromatico e compattatelo con un cucchiaio. Versate intorno al pesce il vino, versategli sopra 4 cucchiai d''olio e cuocete in forno già caldo per 5-6 minuti. Servite caldo.',1614);
INSERT INTO "ricette" VALUES (9462,'Filetti Di Merluzzo Al Curry','Pesce','Merluzzo',4,' -','800 G Filetti Di Merluzzo Surgelati,
Olio D''oliva,
1 Cipollina,
1/2 Cucchiaio Curry,
1 Scatoletta Pomodori Pelati,
1 Fogliolina Alloro,
1 Pizzico Timo,
Sale','Rosolare nell''olio una cipollina; aggiungere mezzo cucchiaio di curry, mescolare e unire i pelati, un pizzico di timo, una fogliolina di alloro; cuocere la salsa per una decina di minuti. Mettere nella salsa il pesce ancora surgelato, salarlo e continuare la cottura a calore dolce per 15 minuti.',1324);
INSERT INTO "ricette" VALUES (9463,'Filetti Di Merluzzo Al Forno','Pesce','Merluzzo',4,' -','1000 G Filetti Di Merluzzo,
800 G Olive Nere,
100 G Olio D''oliva,
Sale,
Aceto Di Vino','Mettere i filetti scongelati in un tegame di terracotta insieme all''olio. Spruzzare con un poco di aceto i filetti, salarli e cospargerli con le olive snocciolate e tagliate a pezzi. Cuocere in forno moderato per 30 minuti e servire ben caldi.',4021);
INSERT INTO "ricette" VALUES (9464,'Filetti Di Merluzzo Al Forno (2)','Pesce','Filetti Di Merluzzo',4,' -','500 G Filetti Di Merluzzo,
2 Cucchiai Capperi,
4 Filetti D''acciughe Sott''olio,
Prezzemolo,
1 Spicchio Aglio,
100 G Olive Nere Snocciolate,
Pangrattato,
Olio D''oliva','Versate in un piatto da portata la farina, immergete i filetti di merluzzo ed infarinateli da entrambi i lati. Disponeteli in una pirofila unta d''olio e conditeli con un trito di prezzemolo e aglio (precedentemente sciacquati) e aggiungete le olive tagliate a rondelle, i capperi tritati, i filetti d''acciuga tagliati a pezzettini ed irrorate il tutto con olio d''oliva. Spolverizzate, infine, con del pangrattato e cuocete in forno già caldo per circa 15 minuti a 200 gradi.',1781);
INSERT INTO "ricette" VALUES (9465,'Filetti Di Merluzzo Al Prosciutto E Formaggio','Pesce','Filetti Di Merluzzo',4,' -','4 Filetti Di Merluzzo Da 180 G,
4 Fette Prosciutto Crudo,
4 Fette Formaggio Fontina,
2 Limoni,
100 G Margarina,
1 Tazzina Olio Di Mais,
Salvia,
Peperoni,
Pepe,
Per La Pastella:,
1 Bicchiere Latte,
2 Uova,
2 Cucchiai Farina Tipo 00,
1 Cucchiaino Sale','Pestare bene, senza romperli, i filetti, spianarli, aggiungere le fette di prosciutto, il formaggio, il pepe e la salvia. Arrotolare i filetti, infarinarli e passarli nella pastella che sarà stata passata nel colino per evitare i grumi. Friggere i filetti nell''olio e margarina bollenti, girandoli più volte fino a dorarli. Guarnire un piatto di servizio con delle fettine di limone e con tondini di peperone. Aggiungere gli arrotolati e serviteli caldi.',3658);
INSERT INTO "ricette" VALUES (9466,'Filetti Di Merluzzo Al Sugo','Pesce','Merluzzo',4,' -','400 G Filetti Di Merluzzo,
150 G Pomodori Pelati,
Farina,
3 Cucchiai Vino Bianco,
5 Cucchiai Olio D''oliva,
Aglio,
Prezzemolo,
Pepe,
Sale','Soffriggere lentamente in un tegame 5 cucchiai di olio ed uno spicchio d''aglio. Aggiungere i pomodori pelati e cuocere per qualche minuto. Tagliare i filetti ancora surgelati in 5 o 6 pezzi ed infarinarli. Mettere nel tegame, salare, pepare e coprire con un coperchio. Dopo 10 minuti circa, spruzzare con 3 cucchiai di vino bianco e lasciare condensare il sugo a tegame scoperto. 2 minuti prima di servire, cospargere di prezzemolo tritato.',1210);
INSERT INTO "ricette" VALUES (9467,'Filetti Di Merluzzo Al Vapore','Pesce','Merluzzo',4,' -','4 Filetti Di Merluzzo Surgelato,
Poco Olio D''oliva,
Limone,
1 Manciata Prezzemolo,
1 Pizzico Sale','Portate a ebollizione, in una pentola, abbondante acqua, quindi mettete sulla pentola un piatto con i filetti di merluzzo spruzzati con poco olio e con poco succo di limone e cosparsi con una manciata di prezzemolo tritato e un pizzico di sale. Coprite i filetti con un altro piatto e lasciate cuocere per circa 30 minuti. Servite con spicchi di limone.',788);
INSERT INTO "ricette" VALUES (9468,'Filetti Di Merluzzo Alla Panna','Pesce','Merluzzo',4,' -','400 G Filetti Di Merluzzo,
20 Cl Panna,
1 Cucchiaio Prezzemolo Tritato,
1 Bicchiere Vino Bianco Secco,
Burro,
Sale,
Pepe','Mettere in una pirofila i filetti di merluzzo cosparsi di fiocchetti di burro, del prezzemolo tritato e del vino bianco, salare e pepare. Cuocere in forno caldo per 15-20 minuti. Versare la panna, facendo amalgamare la salsina. Servire ben caldi con patate bollite. Accompagnare con vino bianco secco giovane.',1910);
INSERT INTO "ricette" VALUES (9469,'Filetti Di Merluzzo Alla Provenzale','Pesce','Merluzzo',4,'Luogo: Francia.','120 G Filetto Di Merluzzo,
1 Cucchiaio Pangrattato,
1 Cucchiaio Prezzemolo Tritato,
1 Spicchietto Aglio Tritato,
1 Pomodoro Grande,
Sale,
Pepe','Tagliare i pomodori a fettine di 1 cm e disporle in una forma per gratin. Mescolare il prezzemolo, l''aglio e il pangrattato. Condire il filetto di merluzzo e disporlo sopra le fettine di pomodoro. Coprire con il composto di pangrattato, prezzemolo e aglio, e gratinare in forno a circa 200 gradi per 20 minuti.',261);
INSERT INTO "ricette" VALUES (9470,'Filetti Di Merluzzo Alla Trevisana','Pesce','Merluzzo',4,' -','300 G Filetti Di Merluzzo Fresco,
200 G Insalata Trevisana In Cespi Di 100 G,
120 G Pancetta Tesa A Fettine,
120 G Cipolla,
120 G Sedano Verde,
Prezzemolo,
4 Cucchiai Olio D''oliva,
1 Cucchiaio Aceto Di Mele,
Sale,
Pepe Nero','Sul tagliere, sistemate le fettine di pancetta una accanto all''altra leggermente accavallate in modo da formare un rettangolo. Sopra disponete i filetti di pesce, quindi arrotolate e fermate il rotolo con alcuni stecchini. Mettetelo in una pirofila senza alcun condimento (basterà la pancetta per mantenerlo morbido) e passatelo nel forno già riscaldato a 200 gradi per 15 minuti circa. Intanto riducete in dadolata fine il sedano e la cipolla e brasate il tutto, a fuoco moderato, in 2 cucchiai d''olio per alcuni minuti, poi sfumate con l''aceto di mele e insaporite con sale, pepe e un pizzico di prezzemolo tritato. Lavate accuratamente i cespi di trevisana, sgocciolateli, quindi divideteli in 4 parti ciascuno. Conditeli con 2 cucchiai di olio e una macinata di pepe, poi cuoceteli brevemente sulla griglia ben calda, girandoli da tutti i lati. Quando tutti gli ingredienti saranno pronti, componete il piatto: tagliate a piccoli tranci il rotolo di pesce e mettetelo al centro. completate con la trevisana e le verdure brasate.',2709);
INSERT INTO "ricette" VALUES (9471,'Filetti Di Merluzzo Gratinati','Pesce','Merluzzo',4,' -','8 Filetti Di Merluzzo,
80 G Burro,
30 Cl Panna Da Cucina Liquida,
1/2 Bicchiere Vino Bianco Secco,
Sale,
Pepe','In una padella antiaderente, fate fondere il burro e rosolate i filetti di merluzzo per circa 5 minuti. Lasciateli dorare e cuocere da entrambe le parti girandoli di tanto in tanto con delicatezza. Subito dopo, salate, pepate e irrorate il tutto con il vino bianco secco. Alzate la fiamma, fino a quando sarà evaporato, dopodichè, sgocciolate il pesce e trasferitelo in una pirofila unta di burro. Copritelo con la panna e passatelo in forno già caldo per circa 10 minuti a 250 gradi. Servitelo subito caldo.',1846);
INSERT INTO "ricette" VALUES (9472,'Filetti Di Merluzzo Mornay','Pesce','Merluzzo',4,' -','8 Filetti Di Merluzzo Da 100 G Ciascuno,
25 Cl Vino Bianco Secco,
1 Bicchiere Acqua,
25 Cl Latte Bollente,
25 Cl Panna Liquida,
25 G Farina Bianca,
2 Tuorli D''uovo,
50 G Formaggio Parmigiano Grattugiato,
60 G Burro,
Sale','Lava ed asciuga bene il pesce. Mettilo in un tegame col vino e l''acqua; sala leggermente e lascia sobbollire per 20 minuti. Con la farina, il latte e la metà del burro prepara una bechamel che allungherai con il 