INSERT INTO "ricette" VALUES (1,'17 Marzo','Bevande','China Martini',1,' -','2/10 Panna Liquida,
Alcune Gocce Liquore Allo Zabaglione,
2/10 Vanil Zucca,
3/10 Illycaffè Espresso,
3/10 China Martini','Mettere i primi tre ingredienti nello shaker con ghiaccio. Mischiare la panna liquida con lo zabaglione. Versare il contenuto dello shaker nel bicchiere (doppia coppetta da cocktail) ed aggiungere il resto.',222);
INSERT INTO "ricette" VALUES (2,'1908','Bevande','Cointreau',1,' -','8/10 Vino Castelblanch Extra Brut,
1/10 Cointreau,
1/10 Passoa,
Per Decorare:,
1 Mandarino Cinese','Mettere il Cointreau e il Passoa nel bicchiere flute ghiacciato. Versare alla fine il Castelblanch ben freddo, mescolando delicatamente. Mettere il mandarino sul bordo del bicchiere.',169);
INSERT INTO "ricette" VALUES (3,'31 Marzo','Bevande','Aperol',1,' -','Alcune Gocce Bitter Campari,
1/4 Aperol,
1/4 Vermouth Martini Bianco,
2/4 Gin Beefeater,
Per Decorare:,
1 Rondella Scorza D''arancia','Versare gli ingredienti nel mixing glass con abbondante ghiaccio. Mescolare delicatamente e servire nella coppetta, decorandola con buccia d''arancia.',354);
INSERT INTO "ricette" VALUES (4,'333','Bevande','Calvados',1,' -','1/3 Calvados,
1/3 Cointreau,
1/3 Succo Di Pompelmo,
Per Decorare:,
1 Ciliegia Candita','Versare i primi 3 ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in un piccolo bicchiere con stelo. Decorare con 1 ciliegia candita.',203);
INSERT INTO "ricette" VALUES (5,'4 Luglio','Bevande','Vino Rosso',4,' -','5/10 Vino Rosso,
2/10 Succo Di Limone,
1/10 Vino Champagne,
1/10 Cognac,
1/10 Tè,
Poca Frutta Di Stagione','Versate i primi 5 ingredienti in una caraffa di vetro, aggiungete cubetti di ghiaccio e poca frutta di stagione a dadini. Mescolate e servite.',114);
INSERT INTO "ricette" VALUES (6,'57 Chevy','Bevande','Vodka',1,' -','1/3 Vodka,
Granatina,
Succo D''arancia,
1/3 Gin,
1/3 Southern Comfort,
Succo D''ananas','Mettere Southern Comfort, gin, vodka in un bicchiere. Colmare con succo d''arancia e succo di pompelmo, quindi mettere sopra la granatina. Non agitare.',588);
INSERT INTO "ricette" VALUES (7,'A And B','Bevande','Benedictine',1,' -','2 Cucchiai Applejack (calvados),
2 Cucchiai Benedictine','Versate nella coppetta da cocktail, senza mescolare.',256);
INSERT INTO "ricette" VALUES (8,'A B C (amici Bevete Cointreau)','Bevande','Cointreau',1,' -','3/10 Succo Di Limone,
4/10 Succo D''arancia Del Monte,
1/10 Gordon''s Gin,
2/10 Cointreau,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con ciliegina rossa al maraschino.',128);
INSERT INTO "ricette" VALUES (9,'A Chi Piace','Bevande','Aperol',1,' -','6/10 Aperol,
3/10 Vodka Glaciale Keglevich Alla Pesca,
1/10 Sciroppo Di Fragola Toschi,
Succo Di Frutta Passion Fruit,
Per Guarnire:,
Frutta Tropicale A Piacere','Si prepara nello shaker (''boston'') con ghiaccio versando i primi tre ingredienti. Agitare e servire nel bicchiere tumbler alto con ghiaccio completando con succo di frutta. Guarnizioni fantasia con frutta tropicale.',551);
INSERT INTO "ricette" VALUES (10,'A Lulu','Bevande','Rum Merito',1,' -','3/8 Rum Merito,
1/8 Crema De Noyaux Bols,
1/8 Galliano,
1/8 Passion Fruit Bectar Mynor,
2/8 Succo D''arancia','Si prepara nello shaker con ghiaccio. Si serve nella coppetta da cocktail.',231);
INSERT INTO "ricette" VALUES (11,'A Pizza Ca'' Pummarola Ncopp''','Primo','Pomodorini',8,'Luogo: Campania.','700 G Farina,
3500 Cl Acqua Tiepida,
1 Cucchiaino Sale,
1/2 Cucchiaino Zucchero,
1 Panetto Lievito Di Birra,
1 Scatola Pomodorini,
Basilico,
250 G Mozzarella','Mettere a fontana la farina, al centro sbriciolare il lievito aggiungere il sale lo zucchero e l''acqua lentamente cominciando ad impastare il tutto. Quando sentite che la pasta è abbastanza elastica e si stacca dalle pareti della terrina lasciatela lievitare per almeno un''ora e mezza. Ungere una teglia o anche due, perchè la pasta è abbondante, stendere ben bene una parte di pasta e ricoprirla di pomodoro, basilico, sale, un filo d''olio, quindi in forno già preriscaldato a 250 gradi per 30 minuti. Solo 5 minuti prima aggiungervi la mozzarella a dadini.',3045);
INSERT INTO "ricette" VALUES (12,'A Pizza Ca'' Pummarola Ncopp'' (2)','Primo','Passata Di Pomodoro',8,'Luogo: Campania.','700 G Farina,
3500 Cl Acqua Tiepida,
1 Cucchiaino Sale,
1/2 Cucchiaino Zucchero,
1 Panetto Lievito Di Birra,
50 Cl Passata Di Pomodoro,
Basilico,
250 G Mozzarella','Mettere a fontana la farina, al centro sbriciolare il lievito aggiungere il sale lo zucchero e l''acqua lentamente cominciando ad impastare il tutto. Quando sentite che la pasta è abbastanza elastica e si stacca dalle pareti della terrina lasciatela lievitare per almeno un''ora e mezza. Ungere una teglia o anche due, perchè la pasta è abbondante, stendere ben bene una parte di pasta e ricoprirla di pomodoro, basilico, sale, un filo d''olio, quindi in forno già preriscaldato a 250 gradi per 30 minuti. Solo 5 minuti prima aggiungervi la mozzarella a dadini.',3098);
INSERT INTO "ricette" VALUES (13,'A Pizza Ca'' Pummarola Ncopp'' (3)','Primo','Pomodorini',8,'Luogo: Campania.','700 G Farina,
3500 Cl Acqua Tiepida,
1 Cucchiaino Sale,
1/2 Cucchiaino Zucchero,
1 Panetto Lievito Di Birra,
15 Pomodorini Freschi,
Basilico,
250 G Mozzarella','Mettere a fontana la farina, al centro sbriciolare il lievito aggiungere il sale lo zucchero e l''acqua lentamente cominciando ad impastare il tutto. Quando sentite che la pasta è abbastanza elastica e si stacca dalle pareti della terrina lasciatela lievitare per almeno un''ora e mezza. Ungere una teglia o anche due, perchè la pasta è abbondante, stendere ben bene una parte di pasta e ricoprirla di pomodoro, basilico, sale, un filo d''olio, quindi in forno già preriscaldato a 250 gradi per 30 minuti. Solo 5 minuti prima aggiungervi la mozzarella a dadini.',3253);
INSERT INTO "ricette" VALUES (14,'A Tutto Tonno','Pesce','Tonno',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Tonno Fresco,
3 Pomodori Secchi,
200 G Melanzane,
100 G Fagioli Borlotti Precotti,
1 Cipolla,
1 Foglio Pasta Fillo,
1 Carota,
1 Costa Sedano,
1 Rametto Rosmarino,
Olio D''oliva,
Sale,
Pepe','Dividere il filetto di tonno in tre parti lavorarli e servirli come segue. Per la tartara battere a coltello il tonno e condirlo con olio, sale, pepe e aghi di rosmarino. Per il sandwich ricavare dei cerchi di melanzana e uno di tonno, grigliarli e salarli. Per la pepita avvolgere un cubo di tonno nella pasta fillo e friggerlo dopo averlo infilzato con uno spiedino. A parte cuocere i fagioli in padella con olio ed un fondo di carota, cipolla e sedano tritati. Frullare a cottura e servire a specchio sotto la pepita dorata.',2421);
INSERT INTO "ricette" VALUES (15,'A. B. C.','Bevande','Cognac',1,' -','7/10 Cognac,
1/10 Vermouth Rosso,
1/10 Vermouth Dry,
1/10 Cordial Campari,
Per Servire:,
1 Scorza Di Limone','Preparare nel mixer con ghiaccio e servire con 1 scorza di limone.',312);
INSERT INTO "ricette" VALUES (16,'A. J.','Bevande','Calvados',1,' -','1/2 Calvados,
1/2 Succo Di Pompelmo,
1 Spruzzo Sciroppo Di Granatina','versare gli ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in una coppetta da cocktail.',215);
INSERT INTO "ricette" VALUES (17,'Abaloni Alla Californiana','Pesce','Abaloni',4,'Luogo: Stati Uniti. Luogo: California.','4 Abaloni (orecchie Marine),
2 Uova,
Sale,
2 Cucchiai Bourbon Whisky,
Olio Di Semi,
50 G Pangrattato,
1 Cespo Insalata Lattuga,
1 Cucchiaio Prezzemolo Tritato,
1 Limone','L''abalone è un raffinatissimo mollusco a una sola valva e di grosse dimensioni, tipicamente californiano: potrete trovarlo surgelato nei migliori negozi di gastronomia; il corrispondente mediterraneo è ''l''orecchia marina'' o ''orecchia di san Pietro''. Pulite bene gli abaloni e lavateli sotto l''acqua corrente; poi togliete con delicatezza i molluschi dalle valve e tenete entrambi da parte. Sbattete in una terrina le uova con un pizzico di sale e il whisky: immergetevi gli abaloni, lasciandoli macerare per 15 minuti. Trascorso questo tempo, fate scaldare abbondante olio nella padella dei fritti. Passate gli abaloni nel pangrattato, quindi friggeteli bene da tutti i lati nell''olio bollente; non appena saranno pronti, poneteli a sgocciolare su un foglio di carta assorbente da cucina per privarli dell''unto eccedente e teneteli in caldo. Lavate la lattuga, asciugatela delicatamente e utilizzate le foglie più belle per foderare le valve dei molluschi. Disponete su ognuno di questi ''letti'' un mollusco fritto, cospargete di prezzemolo tritato e decorate con fettine di limone. Servite ben caldo.',1706);
INSERT INTO "ricette" VALUES (18,'Abat-jour','Bevande','Gin',1,' -','4/5 Gin,
1/5 Succo Di Limone,
1 Cucchiaino Zucchero,
2 Rametti Menta Fresca','Agitate il gin, il succo di limone e lo zucchero, assieme a un paio di cubetti di ghiaccio. Lavate bene le foglie di menta prima di aggiungerle al cocktail.',310);
INSERT INTO "ricette" VALUES (19,'Abate','Bevande','Gin',1,' -','1/3 Succo D''arancia,
2/3 Gin,
1 Spruzzo Vermouth Rosso,
2 Gocce Angostura,
Per Servire:,
1 Ciliegina Al Maraschino,
1 Pezzetto Insalata Lattuga Fresca','Agitare nello shaker, con cubetti di ghiaccio. Servire nel calice con una ciliegina al maraschino e un pezzetto di lattuga fresca.',323);
INSERT INTO "ricette" VALUES (20,'Abbacchio A Scottadito','Carne','Agnello',4,' -','400 G Costolette D''abbacchio,
1 Manciata Dragoncello,
Sale,
Pepe,
Olio D''oliva,
Limone','Bagnare l''abbacchio già tagliato a costoletta con sale, pepe, olio ed dragoncello. Mettere le costolette sulla piastra e farle rosolare da ambo i lati per 4 minuti. Servirle con limone.',1479);
INSERT INTO "ricette" VALUES (21,'Abbacchio A Scottadito (2)','Carne','Agnello',4,' -','1 Cosciotto Di Abbacchio Di 1000 G,
1000 G Patate,
1 Rametto Rosmarino,
2 Spicchi Aglio,
20 Cl Vino Bianco Secco,
Sale,
Olio D''oliva,
Origano,
Aceto Balsamico','Sbucciare le patate, lavarle, tagliarle a spicchi e metterle al forno. Tagliare a filetti i due spicchi di aglio e ridurre a piccoli ciuffetti il rosmarino. Picchettare con i ciuffetti di rosmarino, aglio e origano il cosciotto di agnello. All''esterno del cosciotto mettere delle fette di pancetta e legare il cosciotto con uno spago piuttosto sottile per permettergli di mantenere intatta la forma durante la cottura in forno. Cospargere la casseruola con un poco di olio, mettervi il cosciotto, condirlo con sale, spruzzarlo con vino bianco secco e aceto balsamico e passarlo in forno alla temperatura di 190 gradi. Durante la cottura (60 minuti) bagnarlo frequentemente con il suo fondo e rigirarlo di tanto in tanto con un forchettone. Slegare il cosciotto e disporlo su un piatto di servizio riscaldato; completare il fondo di cottura con il vino bianco e lasciarlo ridurre quasi completamente, quindi irrorare con questo sughetto ben ristretto l''abbacchio. Guarnire il piatto con le patate precedentemente arrostite in 10 cl d''olio e condite con sale.',2830);
INSERT INTO "ricette" VALUES (22,'Abbacchio A Scottadito (3)','Carne','Agnello',4,' -','16 Costolette D''abbacchio,
Aglio,
1 Rametto Maggiorana,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Accomodare su un tagliere le costolette e batterle lievemente con un batticarne e spennellarle poi con un rametto di maggiorana intinto in una marinata di olio, aglio, sale, pepe e lasciarle riposare per una mezz''oretta. Preparare una brace adeguata e cuocere alla griglia le costolette sui due lati, facendo attenzione a cuocerle senza bruciacchiarle.',2327);
INSERT INTO "ricette" VALUES (23,'Abbacchio Alla Cacciatora','Carne','Agnello',4,' -','1000 G Cosciotto Di Abbacchio (agnello) Disossato,
2 Acciughe Sotto Sale,
2 Peperoncini,
1 Spicchio Aglio,
Sale,
Pepe,
1/2 Bicchiere Vino Bianco Secco Dei Castelli Romani,
1/2 Bicchiere Aceto Di Vino,
4 Cucchiai Olio D''oliva Extra-vergine','Tagliare a piccoli pezzi l''abbacchio. In una padella fare sciogliere nell''olio, due acciughe dissalate e diliscate, aggiungendo lo spicchio d''aglio. Appena l''aglio sarà colorito mettere nella padella l''abbacchio, condire con sale e pepe, aggiungere il peperoncino a pezzetti e fare rosolare a fiamma viva, girando di continuo. Quando l''abbacchio sarà ben rosolato, aggiungere 1/2 bicchiere di vino e 1/2 bicchiere di aceto. Coprire la padella, abbassare la fiamma e fare finire di cuocere. Servire ben caldo.',1860);
INSERT INTO "ricette" VALUES (24,'Abbacchio Alla Cacciatora (2)','Carne','Agnello',4,' -','1000 G Abbacchio Tagliato A Pezzi Con La Rognonata,
7 Cucchiai Olio D''oliva,
3 Spicchi Aglio,
3 Rametti Rosmarino Con Le Foglie,
1 Rametto Salvia Con Le Foglie,
3 Acciughe Dissalate E Diliscate,
Aceto Di Vino Bianco','Mettete in infusione in un bicchiere per qualche ora, in metà acqua e metà aceto, l''aglio leggermente schiacciato, il rosmarino e la salvia. Rosolate nell''olio i pezzi di abbacchio salate, versate quindi tutto il contenuto del bicchiere e cuocete, coperto, a fuoco moderato per 45 minuti. Togliete aglio, rosmarino e salvia, pepate, aggiungete le acciughe e, appena saranno spappolate e il sughetto condensato, servite. L''abbacchio è l''agnellino da latte di 30-60 giorni. Si può preparare questa ricetta anche col capretto. Se usate agnello, i tempi di cottura dovranno aumentare in relazione all''età dell''ovino.',2373);
INSERT INTO "ricette" VALUES (25,'Abbacchio Alla Cacciatora (3)','Carne','Agnello',4,'Luogo: Lazio.','1500 G Abbacchio A Pezzi,
Olio D''oliva,
1/2 Bicchiere Aceto Di Vino,
1/2 Cucchiaio Farina,
2 Spicchi Aglio,
1 Rametto Rosmarino,
1 Foglia Salvia,
Sale,
Pepe','In una grande padella versate l''olio, il sale e l''aglio; aggiungete l''abbacchio e fate rosolare a fuoco vivo per 15 minuti. Aggiungete poi la salvia, il rosmarino, il pepe e mettere a fuoco basso aggiungendo l''aceto e lasciate rosolare per qualche minuto. Girate di tanto in tanto l''abbacchio per farlo rosolare uniformemente, aggiungete mezzo cucchiaio di farina e mezzo bicchiere d''acqua per addensare. Abbassate il fuoco, mettete un coperchio e cuocete per altri 15 minuti. Se il liquido si ritira troppo aggiungete un po'' d''acqua. Quando l''abbacchio è giunto a cottura, servitelo ben caldo.',2319);
INSERT INTO "ricette" VALUES (26,'Abbacchio Alla Cacciatora (4)','Carne','Agnello',4,'Luogo: Lazio. Preparazione: 75 minuti.','1 Cosciotto D''abbacchio Di 1000 G Tagliato A Pezzi,
Alcune Acciughe Sotto Sale,
2 Spicchi Aglio,
Rosmarino,
Salvia,
Timo,
Farina,
1/2 Bicchiere Aceto Di Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Infarinate i pezzi di cosciotto, salateli, pepateli e rosolateli nell''olio in modo uniforme, preferibilmente in una pentola di coccio. Tritate finemente alcune acciughe ben lavate dal sale, l''aglio, il rosmarino, la salvia e il timo e spolverate l''abbacchio con questo trito. Aggiungete l''aceto e un bicchiere di acqua, coprite la casseruola e cuocete per circa 50 minuti, rigirando di tanto in tanto la carne. Servite l''abbacchio caldissimo, accompagnandolo con fagioli o piselli lessati.',2104);
INSERT INTO "ricette" VALUES (27,'Abbacchio Alla Romana','Carne','Agnello',6,'Luogo: Lazio. Luogo: Roma.','1000 G Agnello,
1/2 Bicchiere Vino Bianco,
1 Dito Aceto Di Vino,
Rosmarino,
1 Spicchio Aglio,
2 Acciughe,
Sale,
Pepe','Lavate e asciugate la carne tagliata a pezzi, salate e pepate con abbondanza e mettete in una teglia precedentemente scaldata. Fate rosolare e quando avrà preso un colore uniforme, versate il vino oppure acqua e aceto ed aggiungete un trito di rosmarino, acciughe ed aglio. Lasciate cuocere a fuoco minimo per circa 30 minuti e poi servite ben caldo.',2199);
INSERT INTO "ricette" VALUES (28,'Abbacchio Alla Romana (2)','Carne','Agnello',4,'Luogo: Lazio. Luogo: Roma. Calorie: 649.','1000 G Carne D''agnello,
50 G Olio D''oliva,
1 Rametto Rosmarino,
2 Spicchi Aglio,
2 Acciughe Sotto Sale,
3 Cucchiai Aceto Di Vino Bianco,
Sale,
Pepe','Soffriggere nell''olio l''aglio schiacciato, unire l''agnello a pezzi regolari. Salare, pepare, unire il rosmarino tritato con le acciughe, l''aceto e portare a cottura. Servire l''agnello caldo, ricoperto con la sua salsina. Per la giusta esecuzione della ricetta il fuoco deve essere abbastanza vivace da rosolare bene la carne e abbastanza basso da non asciugare la salsina.',2598);
INSERT INTO "ricette" VALUES (29,'Abbacchio Alla Romana (3)','Carne','Agnello',4,'Luogo: Lazio. Luogo: Roma.','1 Cosciotto D''agnello Di 1000 G,
3 Cucchiai Olio D''oliva,
1 Bicchiere Vino Bianco,
1/2 Bicchiere Aceto Di Vino Bianco,
4 Patate,
3 Rametti Rosmarino Fresco,
4 Foglie Salvia,
1 Spicchio Aglio,
Farina,
Sale,
Pepe','Tagliate o fate tagliare a pezzi il cosciotto e infarinateli. In una larga teglia scaldate l''olio e rosolatevi l''agnello a fuoco vivo per circa 10 minuti. Salate e pepate. Unite i rametti di rosmarino e cospargete con la salvia e l''aglio tritati. Girate più volte i pezzi perché insaporiscano bene. Versate il vino mescolato con l''aceto e fate evaporare quasi completamente. Aggiungete ora un mestolo d''acqua bollente e le patate sbucciate e tagliate a spicchi. Coprite e mettete in forno preriscaldato a 180 gradi per mezz''ora abbondante. Se il sugo si riducesse troppo allungatelo con acqua calda mista ad aceto. Disponete l''agnello sul piatto da portata e servite caldissimo. Per una preparazione ancora più saporita, non aggiungete le patate, ma apportate questa variante. Mentre l''agnello finisce di cuocere, trasferite due o tre cucchiai del suo sugo di cottura in un tegamino e stemperatevi a fuoco basso tre acciughe diliscate. Quando sono completamente sciolte, mescolate bene e versate la salsa sulla carne. Lasciate insaporire per un momento. Passate sul piatto da portata caldo e servite. Vini di accompagnamento: Rosso Oltrepò DOC, Cesanese Del Piglio DOC, Cannonau Di Sardegna DOC.',3243);
INSERT INTO "ricette" VALUES (30,'Abbacchio Alla Scottadito','Carne','Agnello',4,'Fonte: i4moschettieri.mastertopforum.net.','4 Costolette D''agnello,
300 G Patate Novelle,
250 G Spinaci,
Rosmarino,
1 Spicchio Aglio,
Olio D''oliva Extra-vergine,
Sale','Tagliare le patate a metà e cuocerle in forno a 180 gradi per 20 minuti dopo averle condite con olio, sale e rosmarino. Spennellare le costolette d''agnello con dell''olio profumato con il rosmarino e l''aglio a pezzetti. Rosolarle sopra una griglia rovente e cuocere da ambo i lati. Far appassire gli spinaci sbollentati con un filo d''olio. Servire le costolette d''agnello sopra un letto di spinaci e accompagnarle con patate al forno.',1385);
INSERT INTO "ricette" VALUES (31,'Abbacchio Brodettato','Carne','Agnello',6,' -','1000 G Abbacchio,
1 Cucchiaio Strutto,
1 Cucchiaio Prosciutto Crudo Tagliato A Cubetti,
1/2 Cipolla,
1/2 Bicchiere Vino Bianco,
1/2 Cucchiaio Farina,
3 Tuorli D''uovo,
1 Limone,
Prezzemolo,
Maggiorana','In una casseruola si mette l''abbacchio in pezzi con lo strutto, il prosciutto e la cipolla tritata. Si fa imbiondire a fuoco moderato affinchè la cipolla non bruci e l''abbacchio non si colorisca troppo. Si condisce con sale e pepe e quando l''abbacchio si è imbiondito si fa cadere a pioggia mezzo cucchiaio di farina. Si mescola e dopo un paio di minuti si bagna con mezzo bicchiere di vino bianco. Quando il vino sarà asciugato si aggiunga dell''acqua fin quasi a coprire l''abbacchio. Si lasci cuocere fin quando il liquido si consuma (il sughetto che resta dovrà essere piuttosto denso). Dieci minuti prima di andare in tavola, mettere in una scodella 2 o 3 tuorli d''uovo, il succo di un limone, una cucchiaiata di prezzemolo tritato e una generosa pizzicata di foglie di maggiorana. Dopo aver battuto il tutto con la frusta si versa sull''abbacchio e si tiene la casseruola per 5/6 minuti sul fuoco bassissimo, affinchè l''uovo si addensi senza stracciarsi.',1953);
INSERT INTO "ricette" VALUES (32,'Abbacchio Con Asparagi','Carne','Agnello',4,' -','1000 G Abbacchio,
2 Spicchi Aglio,
Vino Bianco Secco,
1 Limone,
Timo,
Basilico,
2 Tuorli D''uovo,
Olio D''oliva,
Burro,
500 G Punte Di Asparagi Surgelate,
Sale,
Pepe','Rosolare l''abbacchio in pezzi con 40 g di burro, salare, pepare, unire un po'' di timo e basilico e bagnare con 1/2 bicchiere di vino. Cuocere a fuoco basso per 50 minuti. Rosolare l''aglio con 2 cucchiai di olio e 20 g di burro, eliminarlo, unire gli asparagi e cuocere per 10 minuti. Unirli, insieme a un po'' di succo di limone, alla carne già cotta e cuocere per 6 minuti. Togliere dal fuoco, incorporare i tuorli d''uovo e servire.',2960);
INSERT INTO "ricette" VALUES (33,'Abbacchio Dorato','Carne','Agnello',4,'Luogo: Lazio.','600 G Costolette D''abbacchio,
2 Uova,
Pangrattato,
Olio Per Friggere,
Poco Burro (o Margarina),
Pepe,
Sale,
Alcune Foglie Salvia','Battere uniformemente le costolette e immergerle nelle uova sbattute, quindi impanarle con cura. Rosolarle in padella con olio, poco burro e qualche foglia di salvia a fuoco lento per circa 5 minuti per parte, in modo che la carne rimanga bionda. Salare e pepare soltanto prima di servire ben calde.',2677);
INSERT INTO "ricette" VALUES (34,'Abbacchio E Carciofi','Carne','Agnello',4,' -','2 Rognonate Complete D''abbacchio,
10 Carciofi Riviera Piccoli,
2 Uova,
Pangrattato,
1/2 Limone,
2 Bicchieri Vino Bianco Secco,
Salvia,
Rosmarino,
Olio D''oliva,
Burro,
Sale,
Pepe','Lavate e asciugate bene la rognonata, poi mettete il tutto a rosolare in burro e olio, unendo qualche foglia di salvia, rosmarino e regolando di sale e pepe: bagnate in cottura con il vino bianco, piano piano e in modo che prima di aggiungerne altro sia stato assorbito il primo. Mentre la rognonata cuoce, pulite i carciofi, privateli delle foglie dure e delle spine e sbollentateli per una decina di minuti. Toglieteli poi dal fuoco e strizzateli delicatamente per togliere tutta l''acqua. Dividete i carciofi in due, asciugateli bene, poi passateli nelle uova battute e nel pangrattato, facendoli friggere a fuoco vivace con olio abbondante. In cottura spremete sui carciofi qualche goccia di limone, poi toglieteli dalla padella e metteteli ad asciugare su una carta che ne assorba l''unto eccedente; spolverizzateli poi con scorza grattugiata di limone. Completate la cottura della rognonata che deve risultare senza sugo; ponetela bollente al centro del piatto di portata e circondatela con i carciofi fritti. Servite caldissimo.',2627);
INSERT INTO "ricette" VALUES (35,'Abbeveraggio','Bevande','Artic Fragola',1,' -','1/3 Artic Fragola,
1/3 Vermouth Martini Dry,
1/3 Succo Di Limone,
Zucchero','Agitare velocemente e servire nella coppetta da cocktail ben fredda con il bordo zuccherato a metà.',200);
INSERT INTO "ricette" VALUES (36,'Abbraccio Di Mezze Maniche','Primo','Prosciutto Cotto',4,'Fonte: i4moschettieri.mastertopforum.net.','150 G Pasta Tipo Mezze Maniche,
50 G Fiocchi Di Latte,
50 G Prosciutto Cotto,
Prezzemolo,
Basilico,
1 Costa Sedano,
1 Carota,
2 Pomodori Pelati,
Vino Bianco,
Olio D''oliva,
Sale','Farcire le mezze maniche scottate in acqua bollente salata con una farcia composta da fiocchi di latte, prosciutto cotto, basilico e prezzemolo tritati; finire la loro cottura al vapore. Nel frattempo cuocere i pomodori pelati in padella con un soffritto di carota e sedano tritati, sfumando con vino bianco dopo alcuni minuti. Servire le mezze maniche farcite su tale salsa di pomodoro (finta genovese).',1685);
INSERT INTO "ricette" VALUES (37,'Abbraccio Di Verza E Asiago','Antipasto','Formaggio Asiago',4,'Fonte: i4moschettieri.mastertopforum.net.','1 Verza,
100 G Formaggio Asiago,
10 Cl Panna Fresca,
200 G Barbabietole Precotte,
1 Spicchio Aglio,
Aceto Di Vino Bianco,
Peperoncino,
Olio D''oliva Extra-vergine,
Sale','Lavare la verza, privarla della costa e tagliarla a losanghe. Cuocerla in una padella con l''olio extra-vergine, il peperoncino e l''aglio. Regolare di sale. Frullare le barbabietole con l''aceto e l''olio. In un tegamino sciogliere a fuoco dolce l''Asiago tagliato a cubetti con la panna. Servire mettendo la crema di barbabietole alla base del piatto con sopra la verza brasata; nappare il tutto con la salsa di Asiago.',1685);
INSERT INTO "ricette" VALUES (38,'Abbuott','Carne','Agnello',4,'Luogo: Lazio. Luogo: Ciociaria. Luogo: Roccasecca.','1 Coratella D''agnello,
1 Rete D''agnello,
Budellini D''agnello,
4 Uova,
1 Salsiccia Di Maiale,
Olio D''oliva Extra-vergine,
Sedano,
Prezzemolo,
Cipolla,
1 Bicchiere Vino Bianco,
Formaggio Parmigiano Grattugiato','Si faccia rosolare in una capace pentola la cipolla, il sedano e la coratella tagliata precedentemente a pezzetti. Quando si sarà giunti nel mezzo della cottura si potrà versare il bicchiere di vino bianco. Quando il vino sarà assorbito si aggiungeranno le uova precedentemente sbattute, il prezzemolo e un poco di parmigiano, lasciando amalgamare per circa 3-4 minuti. Stendere poscia la rezza, ammorbidita in acqua tiepida, sul tavolo di cucina e versarci il contenuto della pentola, aggiungendo la salsiccia a tocchetti piccoli. Ora è il momento di riavvolgere la rete come un involtino farcito legandola con i budellini ben lavati. Inserire al forno a fuoco medio per circa mezz''ora, facendo ben rosolare la parte esterna. Servire dopo aver lasciato riposare l''abbuott per un''altra mezz''ora.',6205);
INSERT INTO "ricette" VALUES (39,'Abbuticchi','Carne','Pecora',6,'Luogo: Ciociaria. Luogo: Lazio.','Trippa E Budella Di Una Pecora (o Di 2 Agnelloni),
3 Fette Mortadella,
Formaggio Pecorino A Pezzettini,
3 Fette Ventresca,
2 Uova Sode,
1 Bicchiere Vino Bianco,
1000 G Pomodoro Passato,
Aglio,
Prezzemolo,
Peperoncino,
Basilico,
Rosmarino','Passare velocemente la trippa in acqua calda, ma non bollente, per ammorbidirla e senza farla arricciare. Pulire bene raschiandola per liberarla dalle parti scure. Tagliarla a quadrati della misura giusta per fare dei piccoli involtini. Sulla parete liscia della trippa, al centro, mettere un pezzetto di mortadella, un pezzettino di pecorino, un po'' di ventresca, un quarto di uovo sodo, aglio, prezzemolo e peperoncino. Avvolgere bene e legare con le budella precedentemente aperte e lavate bene in acqua calda, oppure con del filo. Farla rosolare in un soffritto di olio e aglio. Bagnare con un bicchiere di vino e unire basilico e rosmarino. Far evaporare e aggiungere la passata di pomodoro e far cuocere per circa un''ora. Col sugo si può anche condire la pasta con aggiunta di pecorino.',3018);
INSERT INTO "ricette" VALUES (40,'Abc','Bevande','Vermouth Bianco',1,' -','1/4 Vermouth Bianco,
1/4 Vermouth Dry,
2/4 Cognac,
1 Bicchiere Cordial,
Per Servire:,
1 Scorza Di Limone','Agitare nel mixer con ghiaccio. Calice panciuto con scorza di limone.',542);
INSERT INTO "ricette" VALUES (41,'Abissinia','Bevande','Pernod',1,' -','Pernod,
1 Cucchiaio Anisette,
1 Scorza Di Limone','Scuotere nello shaker con cubetti di ghiaccio. Servire nel tumbler stretto, con una scorza di limone.',368);
INSERT INTO "ricette" VALUES (42,'Abissinia Frappé','Bevande','Pernod',1,' -','2/3 Pernod,
1/3 Anisette','Scuotere, energicamente, nello shaker, con ghiaccio in cubetti. Servire nel gotto riempito di ghiaccio tritato.',240);
INSERT INTO "ricette" VALUES (43,'Abricot Tropicale','Bevande','Rum Bianco',1,' -','1/3 Ardine,
2/3 Rum Bianco,
Succo Di Limone,
2 Cucchiaini Zucchero Di Canna,
Per Completare:,
Soda Water Fredda','Servire direttamente nel tumbler, mescolare e aggiungere soda water fredda.',414);
INSERT INTO "ricette" VALUES (44,'Absinthe Cocktail','Bevande','Pernod',1,' -','2/3 Pernod,
1/3 Gin,
1 Spruzzo Angostura,
2 Cucchiai Acqua','Si prepara nello shaker con ghiaccio tritato.',309);
INSERT INTO "ricette" VALUES (45,'Absinthe Cocktail (2)','Bevande','Pernod',1,' -','Pernod,
1 Cucchiaio Anisette,
Per Servire:,
1 Scorza Di Limone','Scuotere pernod e anisette nello shaker con cubetti di ghiaccio. Servire nel tumbler stretto, con una scorza di limone.',369);
INSERT INTO "ricette" VALUES (46,'Absinthe Frappé','Bevande','Pernod',1,' -','2/3 Pernod,
1/3 Anisette','Scuotere, energicamente, nello shaker, con ghiaccio in cubetti. Servire nel gotto già riempito di ghiaccio tritato.',240);
INSERT INTO "ricette" VALUES (47,'Absolut Lemonade','Bevande','Vodka',1,' -','1/2 Absolut Cedro,
1/2 Amaretto,
1 Spruzzo 7-up','Mettere tutti gli ingredienti in un bicchiere pieno di ghiaccio.',321);
INSERT INTO "ricette" VALUES (48,'Absolut Trouble','Bevande','Vodka',1,' -','3/8 Absolut Cedro,
1/8 Granatina,
2/8 Grand Marnier,
2/8 Succo D''arancia','Mescolare con forza in un bicchiere Old Fashioned con ghiaccio.',194);
INSERT INTO "ricette" VALUES (49,'Absolute Chocolate Chili Martini','Bevande','Absolute Peppar',4,' -','1/2 Absolute Peppar,
1/2 Crema Cacao,
1 Pezzettino Chili,
Per Decorare:,
Pepe Jalapeno','Si mettono i primi 3 ingredienti nell''ordine indicato in uno shaker pieno per 3/4 con ghiaccio e li si scuote per alcuni secondi, poi li si filtra attraverso lo strainer nella coppa Martini, decorando con pepe jalapeno.',241);
INSERT INTO "ricette" VALUES (50,'Absoluto','Bevande','Vodka',1,' -','2/4 Vodka Absolut,
1/4 Cointreau,
1/4 Succo D''arancia,
Per Guarnire,
1 Ciliegina Rossa','Versare gli ingredienti nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con ciliegina rossa.',309);
INSERT INTO "ricette" VALUES (51,'Acapulco','Bevande','Succo D''ananas',1,' -','3/10 Artic Pesca,
1/10 Fragola Drink Boero,
3/10 Succo D''ananas Del Monte,
3/10 Succo Di Pompelmo Del Monte,
Per Guarnire:,
1 Ciliegina Rossa,
Alcune Fette Ananas','Si prepara direttamente nel bicchiere tumbler alto con cubetti di ghiaccio. Mescolare delicatamente. Guarnire con fette d''Ananas, ciliegina rossa e cannucce.',223);
INSERT INTO "ricette" VALUES (52,'Acapulco (2)','Bevande','Tequila',1,' -','1/4 Succo Di Limone,
1/4 Succo D''ananas,
1/4 Triple Sec,
1/4 Tequila,
Per Servire:,
Alcuni Cubetti Ananas,
1 Spicchio Limone,
1 Fettina Carota','Agitare nello shaker, con ghiaccio tritato. Servire nel calice ampio, con cubetti di ananas, uno spicchio di limone e una fettina di carota.',234);
INSERT INTO "ricette" VALUES (53,'Acapulco (3)','Bevande','Tequila',1,' -','2 Cucchiai Tequila,
2 Cucchiai Liquore Strega,
2 Cucchiai Succo Di Limone,
1/2 Albume D''uovo','Si prepara nello shaker con ghiaccio spezzettato grossolanamente. Si serve nella doppia coppetta da cocktail.',399);
INSERT INTO "ricette" VALUES (54,'Acapulco (4)','Bevande','Tequila',1,' -','3/10 Tequila,
3/10 Succo D''ananas,
3/10 Succo Di Banana,
1/10 Coconut Mixybar,
Per Guarnire:,
1 Fettina Ananas,
2 Ciliegine Rosse','Miscelare nello shaker con ghiaccio cristallino e servire in un bicchiere tumbler alto. Guarnire con una fettina d''ananas verticale con ciuffo verde e due ciliegine rosse.',241);
INSERT INTO "ricette" VALUES (55,'Acapulco (5)','Bevande','Rum',1,' -','2/3 Rum,
1/3 Cointreau,
2 Cucchiaini Succo Di Limone,
1 Cucchiaino Zucchero','Versare gli ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in una coppetta da cocktail.',328);
INSERT INTO "ricette" VALUES (56,'Acapulco Di Sera','Bevande','Tequila',1,' -','1/4 Succo Di Limone,
3/4 Tequila,
1/2 Cucchiaio Zucchero,
Per Servire:,
Soda,
1 Fetta Limone,
1 Foglia Insalata Verde,
1 Ciliegia','Scuotere nello shaker, con ghiaccio tritato. Servire nel calice ampio con un po'' di soda, una fetta di limone, una foglia d''insalata verde e una ciliegia.',555);
INSERT INTO "ricette" VALUES (57,'Acapulco Gold','Bevande','Rum',1,' -','1/6 Rum,
1/6 Tequila,
2/6 Succo D''ananas,
1/6 Succo Di Pompelmo,
1/6 Crema Di Noce Di Cocco','Versare gli ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in un tumbler piccolo pieno di cubetti di ghiaccio.',258);
INSERT INTO "ricette" VALUES (58,'Acapulco Sour','Bevande','Tequila',1,' -','1/4 Succo Di Limone,
3/4 Tequila,
1/2 Cucchiaio Zucchero,
Per Servire:,
Soda,
1 Fetta Limone,
1 Foglia Insalata Verde,
1 Ciliegia','Scuotere nello shaker, con ghiaccio tritato. Servire nel calice ampio con un po'' di soda, una fetta di limone, una foglia d''insalata verde e una ciliegia.',555);
INSERT INTO "ricette" VALUES (59,'Acarajé','Antipasto','Fagioli Secchi',4,'Luogo: Brasile. Preparazione: 30 minuti (più 24 ore per i fagioli). Cottura: 15 minuti.','200 G Fagioli Secchi (fagioli Cannellini),
1 Cipolla,
Alcuni Rametti Coriandolo Fresco (o Menta),
Sale,
Olio Di Palma (o Olio D''oliva)','Frullate per qualche attimo i fagioli in modo da spezzarli senza sminuzzarli troppo. Metteteli in una ciotola e copriteli con abbondante acqua fredda. Lasciateli a bagno per 24 ore. Trascorso questo tempo, immergete le mani nella ciotola e smuoveteli, quindi eliminate con una schiumarola le bucce venute in superficie. Scolate i fagioli e frullateli di nuovo fino a ottenere una crema. Unite la cipolla, anch''essa frullata e il coriandolo sminuzzato. Salate e mescolate bene il tutto. Scaldate 2 tazze d''olio di palma o di oliva in una padella a fuoco moderato. Prelevate la crema a cucchiaiate e fatela cadere nell''olio caldo aiutandovi, per staccarla, con un altro cucchiaio. Friggete 6 o 7 acarajé per volta. Quando sono croccanti da una parte, girateli e friggeteli dall''altro lato. Deponeteli su un foglio di carta assorbente e proseguite nello stesso modo fino a quando avrete esaurito l''impasto. Servite gli acarajé caldi o tiepidi. Sono buoni così, ma potete anche aprirli un poco nel mezzo e insaporirli con qualche goccia di tabasco. Gli acarajé sono una specialità tipica di Bahia, dove si possono gustare per la strada. Li preparano in banchetti improvvisati le bahiane e, gustati appena fritti, sono uno spuntino delizioso.',1248);
INSERT INTO "ricette" VALUES (60,'Acciugata Estiva','Antipasto','Filetti D''acciughe',4,' -','4 Fette Pane Integrale Casereccio,
1 Spicchio Aglio,
Olio D''oliva,
400 G Fichi Maturi,
6 Filetti D''acciughe Sott''olio,
1 Cipollotto Fresco','Tostate il pane e sfregatelo con l''aglio, poi irroratelo con un filo d''olio. Pelate i fichi e tritateli nel mixer con le acciughe. Spalmate il composto sul pane, poi cospargete con il cipollotto tritato o affettato molto sottilmente.',1539);
INSERT INTO "ricette" VALUES (61,'Acciugata Estiva (2)','Antipasto','Acciughe',4,' -','4 Fette Pane Integrale Casereccio,
1 Spicchio Aglio,
Olio D''oliva,
400 G Fichi Maturi,
6 Filetti D''acciughe Sott''olio,
Erba Cipollina Tritata','Tostate il pane e sfregatelo con l''aglio, poi irroratelo con un filo d''olio. Pelate i fichi e tritateli nel mixer con le acciughe. Spalmate il composto sul pane, poi cospargete di erba cipollina tritata.',1525);
INSERT INTO "ricette" VALUES (62,'Acciugata Estiva (3)','Antipasto','Acciughe',4,' -','4 Fette Pane Integrale Casereccio,
1 Spicchio Aglio,
Olio D''oliva,
400 G Fichi Maturi,
6 Filetti D''acciughe Sott''olio,
Erba Cipollina Tritata','Tostate il pane e irroratelo con un filo d''olio. Pelate i fichi e tritateli nel mixer con le acciughe e l''aglio. Spalmate il composto sul pane, poi cospargete di erba cipollina tritata.',1525);
INSERT INTO "ricette" VALUES (63,'Acciugata Estiva (4)','Antipasto','Acciughe',4,' -','4 Fette Pane Integrale Casereccio,
1 Spicchio Aglio,
Olio D''oliva,
400 G Fichi Maturi,
6 Filetti D''acciughe Sott''olio,
1 Cipollotto Fresco','Tostate il pane e irroratelo con un filo d''olio. Pelate i fichi e tritateli nel mixer con le acciughe e l''aglio. Spalmate il composto sul pane, poi cospargete con il cipollotto tritato o affettato molto sottilmente.',1539);
INSERT INTO "ricette" VALUES (64,'Acciughe A Beccafico Con Arancia Caramellata','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Filetti D''acciughe,
200 G Pomodorini,
3 Fette Pane In Cassetta,
50 G Uvetta Sultanina,
50 G Pinoli,
Menta,
Prezzemolo,
Basilico,
1 Arancia,
1 Cucchiaio Zucchero Di Canna,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Frullare il pane in cassetta con l''uvetta, i pinoli, la menta, il prezzemolo e il basilico. Aprire a libro i filetti d''acciughe e farcirli con il composto ottenuto. Chiudere sovrapponendo con i restanti filetti in modo da formare un piccolo sandwich. Rosolare le acciughe in padella con dell''olio. Nel frattempo, tagliare a metà i pomodorini e farli appassire in forno con dell''olio. Regolare di sale e pepe. A parte, cuocere brevemente il succo d''arancia con lo zucchero e la buccia dell''arancia tagliata a julienne. Irrorare le acciughe con la salsa ottenuta e servire accompagnando con i pomodorini.',1985);
INSERT INTO "ricette" VALUES (65,'Acciughe Aceto E Olio','Antipasto','Acciughe',4,' -','250 G Acciughe Salate,
Aceto Di Mele,
Olio D''oliva Extra-vergine','Diliscare le acciughe lavandole bene sotto l''acqua perché perdano tutto il sale che le avvolge. Disporle ordinatamente in una ciotola e coprirle con l''aceto facendole marinare per 2 ore. Scolare completamente l''aceto e coprire le acciughe con l''olio. Far riposare per circa un''ora e servire con pane casereccio e riccioli di burro.',964);
INSERT INTO "ricette" VALUES (66,'Acciughe Affogate Nel Broccolo Romano','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Broccolo Romano,
2 Acciughe,
Menta,
1 Uovo,
Pangrattato,
30 G Uvetta Sultanina,
20 G Pinoli,
Olio D''oliva,
Sale,
Pepe','Aprire a libretto le acciughe. Bollire il broccolo e schiacciarlo con la menta tritata e olio d''oliva. Passare i filetti di acciughe nell''uovo, nel pangrattato e nell''uvetta e pinoli; friggerle.',1407);
INSERT INTO "ricette" VALUES (67,'Acciughe Al Finocchio','Antipasto','Acciughe',4,' -','12 Acciughe Freschissime Abbastanza Grandi,
Aglio,
Semi Di Finocchio,
Olio D''oliva Extra-vergine Delicato,
Sale Marino Integrale','Lavare e diliscare le acciughe; metterle a scolare. Intanto in abbondante olio far imbiondire dolcemente l''aglio; unirvi le acciughe e far rosolare unendo semi di finocchio pestati (perché sprigionino più aroma). Salare e cuocere a fuoco dolce rivoltando una volta le acciughe. Servire con polenta o pane abbrustolito.',819);
INSERT INTO "ricette" VALUES (68,'Acciughe Al Forno','Pesce','Acciughe',6,' -','800 G Acciughe,
3 Spicchi Aglio,
4 Cipolle Rosse Di Tropea,
5 Filetti D''acciughe Sott''olio,
Pangrattato,
Prezzemolo,
Basilico,
60 G Burro,
Olio D''oliva Extra-vergine','Mondate e lavate le acciughe. Preparate un soffritto con olio e burro, e un trito di cipolle, aglio, prezzemolo e basilico. In una pirofila, alternate uno strato di acciughe e uno di soffritto, fino ad esaurimento degli ingredienti. Finite con uno strato di acciughe, coprite di pangrattato. Condite con olio e infornate per circa mezz''ora in forno preriscaldato a 180 gradi.',2485);
INSERT INTO "ricette" VALUES (69,'Acciughe Al Limone','Pesce','Acciughe',4,' -','500 G Acciughe,
1 Limone,
1/2 Bicchiere Olio D''oliva,
Sale','Squamare le acciughe, togliere la testa e le interiora, lavarle, asciugarle ed allinearle in una pirofila larga. Sbattere l''olio con il succo di limone, versarlo sulle acciughe, regolare di sale e cuocere in forno caldo per circa 30 minuti. Servire le acciughe calde.',1183);
INSERT INTO "ricette" VALUES (70,'Acciughe Al Limone (2)','Antipasto','Acciughe',4,'Calorie: 191.','2 Limoni (o Aceto Di Vino Bianco),
2 Cipolline Fresche,
Prezzemolo,
Olio D''oliva,
Sale','Pulite le acciughe aprendole con le mani dalla parte della pancia. Eliminate la testa e la lisca centrale, lavatele accuratamente e asciugatele con carta da cucina. Allineate i filetti in una pirofila o in una fondina, salateli appena e copriteli con abbondante succo di limone filtrato o se preferite con dell''aceto di vino bianco. lasciate marinare per un giorno al fresco. Sgocciolate le acciughe dalla marinata, disponetele nel piatto da portata, cospargetele di prezzemolo tritato e di cipolline affettate a velo. irrorate con olio e servite subito. vini di accompagnamento: Cinqueterre DOC, Aquileia Riesling Renano DOC, Gravina DOC.',767);
INSERT INTO "ricette" VALUES (71,'Acciughe Al Limone (3)','Antipasto','Acciughe',4,' -','500 G Acciughe Fresche,
Succo Di Limone,
Sale,
Pepe,
Per Servire:,
Olio D''oliva,
Alcune Cipolline Fresche','Le acciughe così preparate si conservano per alcuni giorni. Pulire le acciughe tirando la testa: in tal modo si estraggono anche le interiora. Porle in una terrina salandole modestamente. Ricoprirle internamente di succo di limone e aggiungere un poco di pepe. Lasciare in fusione almeno un giorno, meglio se due. Prima di servire togliere le lische e condire i filetti delle acciughe, che saranno divenuti bianchissimi, con olio d''oliva e cipolline fresche tagliate a sottili rotelline. Al posto del succo di limone si possono far macerare le acciughe in aceto di vino bianco, in questo caso occorre meno tempo per la macerazione.',1245);
INSERT INTO "ricette" VALUES (72,'Acciughe Al Limone (4)','Antipasto','Acciughe',4,' -','Acciughe,
Succo Di Limone,
Olio D''oliva,
Pepe,
Sale','Spinate le acciughe, togliete la testa e pulitele all''interno. Sistematele in un vassoio e copritele interamente di succo di limone per 12 ore, successivamente conditele con olio, sale e pepe.',808);
INSERT INTO "ricette" VALUES (73,'Acciughe Al Limone (5)','Antipasto','Acciughe',4,' -','500 G Acciughe,
4 Limoni (succo),
Olio D''oliva Extra-vergine,
Sale,
Pepe','Spinare e lavare le acciughe e disporle in un piatto capiente. Versarvi il succo dei limoni e regolare di sale e di pepe. Far macerare per almeno 12 ore, quindi toglierle dalla marinata, ricoprirle con l''olio e servire.',1207);
INSERT INTO "ricette" VALUES (74,'Acciughe Al Limone (6)','Antipasto','Acciughe',4,' -','500 G Acciughe Grandi E Polpose,
1 Limone,
Prezzemolo,
Timo,
Pangrattato,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulire le acciughe privandole della testa e della lisca, aprendole a libro. Accomodarle vicine in una pirofila ed irrorarle con una emulsione di olio, limone, sale, pepe, prezzemolo e timo. Cospargere di pangrattato. Infornare a 180 gradi per 15-20 minuti.',1603);
INSERT INTO "ricette" VALUES (75,'Acciughe Al Pomodoro','Antipasto','Acciughe',4,' -','800 G Acciughe Freschissime,
400 G Pomodori Sbollentati Spellati E Sminuzzati,
3 Cucchiai Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
Prezzemolo,
Sale,
Poco Pepe Bianco','Pulire e diliscare le acciughe sotto acqua corrente, asciugarle su un panno. Fare un trito d''aglio e prezzemolo e poco pepe. Adagiare sul fondo di una teglia metà dei pomodori e salarli; accomodarvi sopra le acciughe, salare e cospargervi il trito preparato. Coprire coi pomodori restanti e olio e mettere in forno caldo a 180 gradi per 15-20 minuti. Servire con prezzemolo tritato fresco.',1422);
INSERT INTO "ricette" VALUES (76,'Acciughe Al Verde','Antipasto','Acciughe',4,' -','Acciughe Sotto Sale,
Aceto Di Vino,
Aglio,
Prezzemolo,
Olio D''oliva,
Basilico,
Peperoncino','Prendi una quantità adeguata di acciughe sotto sale; più sono belle spesse e grassottelle meglio è. Sciacquale bene, togli le lische, ed eventualmente passale pochi minuti in acqua e aceto.Pesta nel mortaio: aglio, prezzemolo, ottimo olio di frantoio. Prima pesta aglio e prezzemolo, poi diluisci un po'' con poco olio, poi finisci di stemperare il tutto in una scodella. Non devi ottenere una crema spessa, ma un bagnetto piuttosto fluido; la quantità dell''aglio dipende dalla tua tolleranza e quella del tuo prossimo; più ce n''è, meglio è. Facoltativa una presa di basilico per profumare; alcuni aggiungono anche un po'' di peperoncino, ma altera il gusto. Annega a strati alterni i filetti delle care bestiole in questa crema, che avrai preparato in quantità sufficiente a ricoprirle completamente.Fai stagionare in frigo, in un''area non troppo fredda, almeno una settimana. Si gustano come antipasto, o ottimo riempitivo per una bella pagnotta. In frigo si conservano per molto tempo, eventualmente rabboccando un po'' l''olio fino a coprirle.',862);
INSERT INTO "ricette" VALUES (77,'Acciughe Al Verde (2)','Antipasto','Acciughe',4,'Luogo: Piemonte. Luogo: Verbano-Cusio-Ossola. Luogo: Biella. Luogo: Asti. Luogo: Vercelli. Preparazione: 30 minuti.','200 G Acciughe,
Aceto Di Vino,
1 Spicchio Aglio,
Prezzemolo (solo Le Foglioline),
1 Peperoncino,
Mollica Di Pane,
Olio D''oliva','Prendete 200 g di acciughe, pulitele bene dal sale, togliete la lisca, lavatele in acqua e aceto e asciugatele. Preparate un trito di 1 spicchio d''aglio, prezzemolo (solo le foglioline), 1 peperoncino e un po'' di mollica di pane inzuppata nell''aceto; aggiungete l''olio e mescolate fino a ottenere una salsa morbida che verserete sulle acciughe ricoprendole. Servirle dopo almeno 24 ore.',1076);
INSERT INTO "ricette" VALUES (78,'Acciughe Al Vino Bianco','Antipasto','Acciughe',4,' -','800 G Acciughe,
2 Bicchieri Vino Bianco,
1 Carota,
1 Cipolla,
1 Gambo Sedano,
Olio D''oliva Extra-vergine,
Origano,
Aglio,
1 Pizzico Sale','In una padella fate bollire con 2 bicchieri di acqua e 2 bicchieri di vino la carota, il sedano, la cipolla e un pizzico di sale. Al primo bollore immergete per mezzo minuto le acciughe senza lisca, toglietele e fatele scolare bene. A parte preparate una salsa con olio d''oliva extra-vergine, sale, origano e aglio tagliato a fette. Servite le acciughe possibilmente tiepide.',1796);
INSERT INTO "ricette" VALUES (79,'Acciughe All''aglio','Antipasto','Acciughe',4,' -','700 G Acciughe Fresche,
1/2 Limone,
6 Spicchi Aglio,
4 Bicchieri Acqua,
1/2 Bicchiere Olio D''oliva,
Origano,
Pepe,
Sale','Pulire le acciughe, privarle della testa, lavarle e asciugarle. Affettare l''aglio. In una padella dai bordi larghi mettere l''olio, l''acqua, l''aglio, una presa di origano, sale e pepe. Far sobbollire finché il liquido si sarà un po'' ristretto. Unire le acciughe e cuocerle per circa 10 minuti a fuoco basso. Scolarle dal fondo di cottura, disporle sul piatto da portata e irrorarle col succo di limone.',1419);
INSERT INTO "ricette" VALUES (80,'Acciughe Alla Pizzaiola','Pesce','Acciughe',4,' -','600 G Acciughe Grandi,
400 G Pomodori Pachino Maturi,
Origano,
Aglio,
Olio D''oliva Extra-vergine,
Sale,
Pepe Bianco','Eviscerare e privare di testa e lisca le acciughe; lavarle in acqua leggermente acidulata con aceto. In una pirofila rosolare aglio e olio e unire i pomododori triturati, facendoli insaporire con sale, origano e pepe. Lasciar stiepidire, quindi farcire ogni alice con una cucchiaiata di pomodori. Accomodare le acciughe nella pirofila e coprirle coi pomodori restanti; salare, unire olio e origano e passare in forno a 180 gradi.',1384);
INSERT INTO "ricette" VALUES (81,'Acciughe Alla Povera','Pesce','Acciughe',4,' -','500 G Acciughe,
30 Cl Aceto Di Vino Non Troppo Acido,
Sale,
Olio D''oliva Extra-vergine,
1 Cipolla Rossa','Fatevi pulire dal vostro pescivendolo le acciughe (alcuni tolgono solo la testa e le interiora, altri addirittura la spina e le sfilettano perfettamente). Sciogliete un po'' di sale nell''aceto, e versatelo in una terrina dove avrete precedentemente sistemato i filetti d''acciughe. Lasciare al fresco per 3 o 4 ore, in modo che l''aceto cuocia il pesce. Togliere le acciughe dall''aceto, e sistemare a strati in un''altra terrina, ricoprendo con l''olio e guarnendo con anelli di cipolla. Mantenere al fresco per qualche ora, e quindi consumare insieme a pane e vino bianco fresco.',1227);
INSERT INTO "ricette" VALUES (82,'Acciughe Alla Povera (2)','Antipasto','Acciughe',4,' -','Acciughe Fresche,
Cipolle Rosse,
Olio D''oliva,
Sale,
Aceto Di Vino Bianco','Lavare bene le acciughe e togliere la lisca centrale. Mettere le acciughe in abbondante aceto per alcune ore. Disporre le acciughe a strati, alternandole con la cipolla a fettine e un poco di sale. Ricoprire con olio d''oliva.',820);
INSERT INTO "ricette" VALUES (83,'Acciughe Alla Povera (3)','Antipasto','Acciughe',6,'Luogo: Toscana. Luogo: Livorno.','600 G Acciughe,
Aceto Di Vino Bianco,
Cipolle Rosse,
Olio D''oliva Extra-vergine,
Alcuni Grani Pepe Nero,
Sale','Staccate la testa dalle acciughe, evisceratele e togliete la lisca centrale. Sistemate i filetti di acciuga a strati in una terrina con della cipolla rossa tagliata ad anelli fini, salate leggermente ogni strato. Questa operazione è fondamentale perchè il sale attenua l''acidità dell''aceto. Ricoprite interamente con l''aceto e lasciate macerare per 6/7 ore fino alla completa sbiancatura delle acciughe. Togliete i filetti di acciughe dall''aceto e sistemateli a strati in unaltra terrina alternandoli con la cipolla rossa. Ricoprite il tutto con olio e qualche grano di pepe per decorazione. Servite le acciughe come antipasto, si mantengono bene anche per alcuni giorni.',1320);
INSERT INTO "ricette" VALUES (84,'Acciughe Alla Povera (4)','Antipasto','Acciughe',4,'Luogo: Toscana. Luogo: Livorno.','500 G Acciughe Fresche,
1 Cipolla Rossa,
Aceto Di Vino Bianco,
Sale,
Pepe,
Olio D''oliva','Pulire le acciughe togliendo la testa e la lisca centrale, lavarle e asciugarle. Sciogliere un po'' di sale nell''aceto, e versarlo in una terrina dove avrete precedentemente sistemato i filetti di acciuga. Lasciare al fresco per 3 o 4 ore, in modo che l''aceto cuocia il pesce. Togliere le acciughe dall''aceto, e sistemare a strati in un''altra terrina, ricoprendo con l''olio e guarnendo con anelli finissimi di cipolla. Servire le acciughe fredde.',1218);
INSERT INTO "ricette" VALUES (85,'Acciughe Alla Rucola Con Salsa Di Barbabietole','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','100 G Acciughe,
2 Barbabietole Precotte,
1 Spicchio Aglio,
100 G Insalata Rucola,
Basilico,
Prezzemolo,
1 Limone,
2 Albumi D''uovo,
50 G Fecola,
1 Bustina Zafferano,
Olio D''oliva,
Sale,
Pepe','Cuocere le acciughe intere a vapore dopo aver aromatizzato l''acqua con basilico, prezzemolo, scorza di limone, rosmarino e poca rucola. Passare la restante rucola nella pastella di albume d''uovo, fecola e zafferano. Sbollentare e cuocere per altri 10 minuti in padella con olio ed aglio la barbabietola a pezzi, unire la mentuccia e lo zenzero e frullare a cottura. Servire le acciughe e le frittelle di rucola sulla salsa di barbabietola a specchio.',1160);
INSERT INTO "ricette" VALUES (86,'Acciughe Alla Sanremasca','Antipasto','Acciughe',4,'Luogo: Liguria. Luogo: Sanremo. Luogo: Imperia. Preparazione: 150 minuti.','800 G Acciughe,
2 Limoni (succo),
1/4 Bicchiere Olio D''oliva Extra-vergine,
Sale,
1 Spicchio Aglio,
Prezzemolo','Pulite, lavate e diliscate 800 g di acciughe. Disponetele aperte, in un solo strato, su un piatto di portata. A parte sbattete e amalgamate il succo di 2 limoni con 1/4 di bicchiere di vino bianco secco e 1/2 bicchiere di olio d''oliva extra-vergine, cui avrete aggiunto sale, 1 spicchio d''aglio e del prezzemolo tritati. Versate il condimento sulle acciughe e lasciatele marinare per almeno due ore. Tipica preparazione della parte più occidentale della riviera di ponente, questo antipasto semplice e naturale ha il pregio di lasciare intatto il sapore delle acciughe.',1157);
INSERT INTO "ricette" VALUES (87,'Acciughe Alla Siciliana','Pesce','Acciughe',4,'Luogo: Sicilia.','24 Acciughe,
400 G Pomodori Maturi,
2 Fette Pancarré,
2 Uova,
3 Cucchiai Formaggio Pecorino Dolce,
1 Cipolla Piccola,
2 Mazzetti Basilico,
2 Cucchiai Capperi Sotto Sale,
1 Pizzico Origano,
2 Cucchiai Farina,
Pangrattato,
1/2 Bicchiere Latte,
6 Cucchiai Olio D''oliva,
Sale,
Pepe','Ammorbidite il pancarré mettendolo a bagno nel latte. Sbollentate per qualche secondo i pomodori poi spellateli e tritateli grossolanamente. Fate appassire la cipolla affettata 4 cucchiaiate di olio quindi unitevi i pomodori, salate, pepate, unite anche l''origano e cuocete a fuoco vivace per una decina di minuti. Infine, aggiungete i capperi lavati per eliminare il sale e il basilico tritato. Pulite le acciughe lasciando attaccati tra di loro i due filetti. Lavatele bene e fatele sgocciolare su di un tagliere inclinato. Fate scaldare 2 cucchiai di olio in un padellino, unitevi 4 acciughe e fatele rosolare poi togliete il padellino dal fuoco e unite il pancarré strizzato, un uovo, il pecorino e un poco di sale e pepe. Lavorate bene il composto con una forchetta e poi distribuitelo all''interno delle altre acciughe che richiuderete a libro. Passate i pesci prima nella farina poi nell''uovo battuto con un poco di sale e pepe e infine nel pangrattato. Friggetele velocemente in olio ben caldo e servite subito accompagnate dal sugo di pomodoro preparato.',3962);
INSERT INTO "ricette" VALUES (88,'Acciughe Alle Olive','Pesce','Acciughe',4,' -','500 G Acciughe Fresche,
2 Spicchi Aglio,
1 Peperoncino,
1/2 Bicchiere Olio D''oliva,
3 Limoni,
100 G Olive Nere Snocciolate,
Prezzemolo','Pulite le acciughe, apritele in due senza dividerle, adagiatele in un tegame di terracotta, spruzzatele col succo dei limoni, coprite e lasciatele riposare al fresco. Tritate l''aglio con il prezzemolo, le olive e il peperoncino. Ponete le acciughe su un piatto, conditele con l''olio, spolverizzate col trito, decorate con qualche oliva intera e servite.',1552);
INSERT INTO "ricette" VALUES (89,'Acciughe Allinguate Su Caponata Al Miele','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','Per Le Acciughe:,
250 G Acciughe,
100 G Pangrattato,
1 Limone (succo),
20 G Uvetta Sultanina,
20 G Pinoli,
10 Foglie Menta Fresca,
Olio D''oliva Extra-vergine,
Sale,
Pepe,
Per La Caponata:,
1 Costa Sedano,
100 G Zucca,
50 G Olive Nere,
1/2 Cipolla,
50 G Capperi Dissalati,
20 G Miele,
20 G Aceto Di Vino Bianco,
Olio D''oliva Extra-vergine,
Sale,
Pepe','In una padella antiaderente mettere l''olio e tutte le verdure per la caponata, continuare la cottura per 10 minuti, salare, pepare ed aggiungere l''aceto ed il miele. Prendere le acciughe eviscerate e preparare il ripieno con pangrattato, succo di limone, pinoli, uvetta, menta, olio, sale e pepe. Mettere il ripieno all''interno delle acciughe aperte a libro. Cuocerle in una padella antiaderente e poi appoggiarle sulla caponata preparata precedentemente.',2442);
INSERT INTO "ricette" VALUES (90,'Acciughe Arraganate Con Cime Di Rapa','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Filetti D''acciughe,
200 G Cime Di Rapa,
1 Limone,
40 G Pangrattato,
100 G Formaggio Canestrato,
1 Uovo,
1 Filetto D''acciuga,
Origano,
Peperoncino,
Sale,
Pepe,
Olio D''oliva Extra-vergine','Amalgamare in una ciotola il pangrattato con la scorza grattugiata del limone, il canestrato grattugiato, l''uovo e regolare di sale e pepe. Aprire i filetti d''acciughe a libro, farcirli con il composto ottenuto, arrotolarli a mo'' di involtino, spolverarli con l''origano, bagnarli con un filo d''olio e cuocerli in forno a 180 gradi per 5 minuti. Rosolare le cime di rapa in una padella con l''olio, l''acciuga, il peperoncino e poi frullare. Servire le acciughe arraganate sopra la crema di cime di rapa.',1613);
INSERT INTO "ricette" VALUES (91,'Acciughe Con Peperoni','Pesce','Acciughe',4,' -','Acciughe,
Olio D''oliva,
Sale,
Peperoni','Friggere prima i peperoni tagliati a listelle: poi nello stesso olio friggere le acciughe. Passarle nella carta paglia per asciugarle, riunire e salare.',852);
INSERT INTO "ricette" VALUES (92,'Acciughe Con Porchetta','Antipasto','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe,
100 G Porchetta,
1 Uovo,
Pangrattato,
Per Le Polpette Di Acciughe:,
300 G Acciughe Fresche,
1 Uovo,
40 G Farina,
50 G Formaggio Parmigiano,
2 Limoni,
Olio D''oliva,
Sale,
Pepe,
Prezzemolo','Pulire bene le acciughe, lavarle e tritarle finemente con il coltello o nel mortaio, mescolarvi l''uovo la farina e il formaggio, aggiustare di sale e pepe. Friggere le polpettine in olio caldo, scolarle e porle su fogli di carta paglia perché perdano l''unto in eccesso. Sistemarle su il piatto da portata, contornate di spicchi di limone.',2200);
INSERT INTO "ricette" VALUES (93,'Acciughe Con Puntarelle, Olive E Capperi','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe,
150 G Puntarelle,
100 G Formaggio Spalmabile,
80 G Olive Nere,
1 Cipolla Rossa,
50 G Capperi,
Panna,
Peperoncino,
Basilico,
Menta,
Prezzemolo,
Scorza Di Limone,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulire le acciughe, preparare un composto con formaggio, sale, pepe e olive nere tritate, poi spalmarlo sulle acciughe e cuocerle a vapore con basilico, menta, prezzemolo e 1 scorza di limone, 1 cipolla rossa. Condire le puntarelle con i capperi tritati, l''olio e il sale. Aromatizzare la panna con il peperoncino e metterla alla base del piatto con le alici e le puntarelle.',1972);
INSERT INTO "ricette" VALUES (94,'Acciughe Con Salsa Verde','Antipasto','Acciughe',4,'Preparazione: 40 minuti. Calorie: 309.','8 Acciughe Sotto Sale,
1 Tuorlo D''uovo Sodo,
1 Spicchio Aglio,
1 Cucchiaio Aceto Di Vino,
Peperoncino,
Olio D''oliva,
Sale','Pulite e diliscate le acciughe e disponetele su un piatto da portata. Tritate finemente l''aglio insieme con il prezzemolo e il tuorlo; versate il composto in una terrina, unite l''olio, l''aceto, il peperoncino e il sale, mescolate bene e ricoprite le acciughe completamente con la salsa preparata e lasciate insaporire per molte ore prima di servire.',878);
INSERT INTO "ricette" VALUES (95,'Acciughe Croccanti E Guazzetto Di Provolone','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Filetti D''acciughe Freschissime,
Pangrattato,
3 Fettine Formaggio Provolone Dolce,
1/2 Finocchio,
1/2 Peperone Rosso,
1 Carota Piccola,
1 Zucchina Piccola,
1 Spicchio Aglio,
1 Radice Zenzero Fresco,
10 Cl Bevanda Alla Soia Naturale,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Per il guazzetto: tagliare il provolone a cubetti e unirlo al latte di soia. Scaldare sino a raggiungere i 50 gradi di temperatura e poi frullare in modo da ottenere una salsina cremosa. Tagliare a brunoise (a dadini piccolissimi) tutte le verdure (finocchio, peperone, carota e zucchina), grattugiare un po'' di zenzero fresco e scottare il tutto in padella con un filo d''olio ed un pizzico di sale. Disporre su ciascun filetto di alice un cubetto di provolone, arrotolare e chiudere con uno stuzzicadenti. Passare nel pangrattato e rosolare in padella con dell''olio e uno spicchio di aglio. Asciugare sopra un foglio di carta assorbente quindi rimuovere lo stuzzicadenti. Salare e pepare. Versare il guazzetto di provolone in un piatto fondo, aggiungere la brunoise di verdurine aromatizzate allo zenzero ed infine adagiare i filetti di alici rosolati.',1754);
INSERT INTO "ricette" VALUES (96,'Acciughe Crude','Antipasto','Acciughe',4,'Luogo: Sicilia. Luogo: Palermo. Luogo: Trapani.','500 G Acciughe,
Succo Di Limone,
Aglio,
Prezzemolo,
Olio D''oliva,
Sale,
Peperoncino Macinato','Pulite 500 g di acciughe, evisceratele, togliete con le mani la lisca centrale, lavatele e asciugatele. Sistematele a strati in una terrina, irrorando ogni strato con succo di limone. Cospargetele con aglio schiacciato e ponetele coperte in frigorifero per 24 ore. Quindi scolate le acciughe dal loro sugo, sciacquatele con succo di limone, ponetele in un piatto e cospargetele con un trito di aglio e prezzemolo, irroratele con olio d''oliva, salate e completate a piacere con peperoncino macinato.',1253);
INSERT INTO "ricette" VALUES (97,'Acciughe Crude Al Limone','Antipasto','Acciughe',4,' -','500 G Acciughe Freschissime,
5 Limoni (succo),
25 Cl Olio D''oliva (facoltativo),
Pepe Bianco,
1 Pizzico Sale','Pulite accuratamente le acciughe, togliete loro la testa e la spina dorsale, dividetele in filetti e ponetele, ben distese, in un piatto piuttosto ampio. Cospargetele con un pizzico di sale e un po'' di pepe bianco macinato, irroratele con il succo di 5 limoni e lasciate macerare almeno 12 ore, rivoltandole di tanto in tanto. Quando saranno ben schiarite, estraete le acciughe dalla marinata, deponetele a strati in una terrina di porcellana oppure di vetro e ricopritele con olio d''oliva. Si possono conservare per un giorno, ma sono sicuramente più gustose consumate subito, dopo la marinatura.',2762);
INSERT INTO "ricette" VALUES (98,'Acciughe Dorate Al Mais Su Insalatina In Agrodolce','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe Grandi,
100 G Insalata Rucola,
Farina Di Mais,
20 G Bottarga Di Muggine,
Senape,
1/2 Limone,
Olio D''oliva,
Sale,
Pepe','Pulire, aprire a libretto e deliscare le acciughe. Passare i filetti nella farina di mais e bottarga grattugiata quindi friggerli in padella con un filo d''olio. Condire la rucola con olio emulsionato con poca senape e succo di limone. Salare e servire col pesce.',1276);
INSERT INTO "ricette" VALUES (99,'Acciughe E Uova','Pesce','Acciughe',4,' -','8 Uova,
8 Filetti D''acciughe,
Olio D''oliva','Una preparazione da fare in tegamini singoli. In ognuno mettete due cucchiai d''olio e fatevi insaporire due filetti d''acciughe spezzettati. Quindi sgusciatevi sopra le uova e aiutandovi con una paletta di legno mescolate bene gli albumi perché si rapprendano facendo attenzione a non rompere i tuorli. Non salate.',1499);
INSERT INTO "ricette" VALUES (100,'Acciughe Farcite Con Insalata','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','8 Filetti D''acciughe,
1 Spicchio Aglio,
50 G Pane,
Prezzemolo,
Latte,
Pangrattato,
20 G Pinoli,
1 Uovo,
1 Pompelmo,
100 G Insalata Rucola,
5 Olive Nere,
1 Carota,
1 Costa Sedano,
2 Fettine Prosciutto Crudo,
Olio D''oliva,
Sale,
Pepe','Frullare l''aglio con il prezzemolo, il pane bagnato nel latte ed un uovo; farcire col composto i filetti d''acciughe; disporli su una placca da forno, cospargerli di olio, pangrattato ed infornarli per 5 minuti a 180 gradi. Servirle con una insalatiina fresca ottenuta con gli spicchi del pompelmo, la rucola, le olive nere, la carota e il sedano a listarelle con una julienne di prosciutto crudo.',2297);
INSERT INTO "ricette" VALUES (101,'Acciughe Fritte','Pesce','Acciughe',4,' -','700 G Acciughe,
Latte,
Farina,
Olio D''oliva,
Sale,
Per Guarnire:,
Alcuni Spicchi Limone,
Alcuni Ciuffi Prezzemolo','Eviscerare le acciughe, lavatele, asciugatele, tenetele a bagno nel latte mezz''ora. Scolatele, passatele nella farina e cuocetele nell''olio bollente. Scolatele, salatele, passatele nel piatto da portata e guarnite con spicchi di limone e ciuffi di prezzemolo. Vini di accompagnamento: Piave Tocai DOC, Cinque Terre DOC, Trebbiano Di Romagna DOC.',1797);
INSERT INTO "ricette" VALUES (102,'Acciughe Fritte Con Peperonata, Lattuga Rossa E Caprino','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe,
200 G Peperone,
50 G Formaggio Caprino,
2 Uova,
Pangrattato,
Farina,
Olio Per Friggere,
1 Cipolla,
Olio D''oliva,
Sale','Pulire le acciughe, passarle nella farina, nell''uovo sbattuto e nel pangrattato. Friggerle in olio d''oliva. Tagliare i peperoni a cubetti e cuocerli in una casseruola con olio e cipolla tritata e preimbiondita. Unire i pomodori a metà cottura. Aggiungere il caprino in purezza a fine cottura, lontano dal fuoco. Servire le acciughe con la peperonata e la lattuga affettata e condita con olio e sale.',2547);
INSERT INTO "ricette" VALUES (103,'Acciughe Fritte Dorate Con Borraggine','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','400 G Acciughe,
Olio D''arachidi,
2 Uova,
200 G Borraggine,
Pangrattato,
Sale','Pulire le acciughe, fare una panatura con uova e pangrattato,nel frattempo portare l''olio a temperatura e friggere le alici. Pulire la borraggine, farla lessare in acqua calda e ripassarla con olio e peperoncino ed impiattare.',1673);
INSERT INTO "ricette" VALUES (104,'Acciughe Fritte Su Letto Di Scarola E Fasolari Gratinati','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Acciughe,
100 G Insalata Scarola,
8 Fasolari,
Pangrattato,
Olio Per Friggere,
Prezzemolo Tritato,
1 Filo Olio D''oliva,
Sale,
Pepe','Friggere i filetti d''acciughe e servirli sulla scarola affettata e condita con olio e sale. Aprire i fasolari, condirli con sale, pepe e prezzemolo tritato e pangrattato e infornare con un filo d''olio d''oliva per alcuni minuti.',2087);
INSERT INTO "ricette" VALUES (105,'Acciughe Fritte, Marinate In Aceto E Porri','Pesce','Acciughe',6,'Preparazione: 40 minuti. Calorie: 157.','18 Acciughe Grandi,
2 Porri,
1 Ciuffetto Finocchietto Selvatico,
Farina,
Pangrattato,
1/2 Bicchiere Aceto Di Vino,
1 Filo Olio D''oliva Extra-vergine,
Sale,
Pepe','Staccate alle acciughe la testa poi spinatele aprendole a libro; lavatele rapidamente, asciugatele bene quindi passatele nella farina, nel pangrattato e friggetele in un velo d''olio. Mondate, riducete i porri a tocchetti e raccoglieteli in una casseruola insieme con mezzo litro d''acqua, un filo d''olio, un ciuffetto di finocchietto; portate il tutto su fuoco moderato e dopo 15 minuti di bollore aggiungete mezzo bicchiere di aceto, sale, pepe e, alla ripresa dell''ebollizione, spegnete e versate la marinata calda sulle acciughe fritte raccolte in un piatto piuttosto profondo; lasciatele marinare almeno 6 ore prima di servirle. Vino consigliato: Vino bianco giovane, secco, armonico, fragrante (Alto Adige Sylvaner, Colli Amerini Malvasia secco, Costa d''Amalfi bianco).',1305);
INSERT INTO "ricette" VALUES (106,'Acciughe Gratinate','Pesce','Acciughe',4,' -','600 G Acciughe,
1 Limone,
1/2 Bicchiere Olio D''oliva,
1 Spicchio Aglio,
Prezzemolo,
Pangrattato,
Sale','Togliere alle acciughe la testa e la spina centrale, lavarle e allinearle aperte in una teglia. Spargere sul pesce pezzettini di aglio, prezzemolo, pangrattato, sale. Sbattere l''olio con il succo di limone, versarlo sulle acciughe e cuocere nel forno caldo per circa 20 minuti.',1660);
INSERT INTO "ricette" VALUES (107,'Acciughe Gratinate (2)','Pesce','Acciughe',4,' -','800 G Acciughe,
1 Spicchio Aglio,
2 Pizzichi Origano,
1 Bicchierino Aceto Di Vino,
Olio D''oliva,
1 Pizzico Sale,
1 Pizzico Pepe','Pulite le acciughe, eliminate testa e lisca, apritele a libro in modo che restino unite sul dorso e adagiatele in una teglia spennellata con abbondante olio. In una ciotola versate un bicchierino d''aceto, unite 4-5 cucchiai d''olio, due pizzichi abbondanti di origano, uno spicchio d''aglio tritato, un pizzico di sale e uno di pepe nero. Mescolate, amalgamate con cura tutti gli ingredienti e versate il composto sulle acciughe. Cuocete in forno preriscaldato a 200 gradi per un quarto d''ora. Passate su un piatto da portata e servite caldo o freddo. Vini di accompagnamento: Gavi DOC, Castelli Di Jesi Verdicchio DOC, Vermentino Di Sardegna DOC.',1495);
INSERT INTO "ricette" VALUES (108,'Acciughe Gratinate (3)','Pesce','Acciughe',4,' -','600 G Acciughe,
Pangrattato,
1 Mazzetto Prezzemolo,
1 Spicchio Aglio,
6 Cucchiai Olio D''oliva,
Sale','Sbucciare ed affettare sottilmente le patate. Disporle in una teglia larga e unta con olio. Lavare e asciugare le acciughe già diliscate e aperte, passarle nel succo dei limoni. Mescolare al pangrattato l''aglio tritato molto finemente ed il prezzemolo. Premere le acciughe sul pangrattato da entrambi i lati poi disporle sulle patate. Irrorare con olio e salare. Cuocere in forno caldo a 200 gradi per 15 minuti.',3118);
INSERT INTO "ricette" VALUES (109,'Acciughe Gratinate Con Crema Di Melanzane','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','Per Le Acciughe:,
10 Filetti D''acciughe Fresche,
Pangrattato,
100 G Formaggio Grana Grattugiato,
Erbe Aromatiche (salvia, Rosmarino, Prezzemolo),
Gherigli Di Noci,
200 G Pomodorini,
Sale,
Olio D''oliva Extra-vergine,
Per La Crema:,
1 Melanzana,
Prezzemolo,
Sale,
Olio D''oliva Extra-vergine','Frullare il pangrattato con il grana, le erbe aromatiche, le noci, 3-4 pomodorini, un pizzico di sale e un filo d''olio. Adagiare la panure sulle acciughe e formare un tortino alternando le alici con i pomodorini tagliati a fettine. Infornare per 10 minuti a 180 gradi. Tagliare la melanzana a cubetti, stufarla in padella con un filo d''olio, 1 pizzico di sale e un goccio di acqua. Una volta pronta frullarla con qualche foglia di prezzemolo e un filo d''olio. Servire la crema di melanzana alla base del piatto e adagiarvi sopra il tortino di acciughe gratinate.',3000);
INSERT INTO "ricette" VALUES (110,'Acciughe Imbottite Con Insalatina Agrodolce','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','250 G Filetti D''acciughe,
1 Mozzarella Da 300 G,
2 Uova,
Pangrattato,
100 G Insalata Gentilina,
40 G Pinoli,
30 G Uvetta Sultanina,
Aceto Di Mele,
Olio D''oliva Extra-vergine,
Olio Di Semi Di Arachidi,
1 Pizzico Sale','Farcire i filetti d''acciughe con delle fettine di mozzarella, chiudere a mo'' di panino sovrapponendo ulteriori filetti quindi passare le alici imbottite nell''uovo sbattuto e successivamente nel pangrattato. Friggere in olio di semi profondo. A parte, condire l''insalata con l''uvetta precedentemente ammollata in un bicchiere di acqua tiepida, i pinoli, l''aceto di mele, l''olio d''oliva e 1 pizzico di sale.',3174);
INSERT INTO "ricette" VALUES (111,'Acciughe Imbottite Su Scarole Alla Monachina','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Filetti D''acciughe,
150 G Formaggio Provola,
1 Uovo,
Farina,
Formaggio Grana Grattugiato,
200 G Insalata Scarola,
1 Spicchio Aglio,
30 G Uvetta Sultanina,
30 G Pinoli,
20 G Capperi,
Olio D''oliva Extra-vergine','Passare i filetti d''acciughe nella farina e poi nell''uovo sbattuto con il grana; farcire con delle fettine di provola, sovrapporre con altri filetti e poi friggere in olio di semi. Sbollentare la scarola e poi rosolarla in padella con l''olio, l''aglio, l''uvetta, i pinoli ed i capperi. Servire le alici imbottite sopra un letto di scarola.',2362);
INSERT INTO "ricette" VALUES (112,'Acciughe Impanate','Pesce','Acciughe',4,' -','Acciughe,
Farina,
Uovo,
Pangrattato,
Olio D''oliva','Aprire a libro le acciughe, diliscarle, impanarle (passarle nella farina, poi nell''uovo, infine nel pangrattato) e friggerle.',1556);
INSERT INTO "ricette" VALUES (113,'Acciughe Impanate Con Provolone Del Monaco','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','8 Filetti D''acciughe,
100 G Formaggio Provolone Del Monaco,
1 Peperone,
1 Cipolla,
Farina,
1 Uovo,
Pangrattato,
Olio Di Semi Di Arachidi,
Sale','Farcire i filetti d''acciughe con il provolone grattugiato; passarli nell''uovo sbattuto, nella farina e nel pangrattato. Friggerli in olio di semi di arachidi. A parte, stufare il peperone tagliato a cubetti con la cipolla, frullare con un filo d''olio e regolare di sale. Servire le acciughe sopra la salsa di peperone.',1969);
INSERT INTO "ricette" VALUES (114,'Acciughe In Aceto','Pesce','Acciughe',4,' -','1 Pezzo Cipolla,
1 Cucchiaio Aceto Di Vino,
250 G Acciughe,
Sale,
1 Mazzetto Prezzemolo,
1 Spicchio Aglio,
Per Servire:,
Pepe,
Olio D''oliva,
Prezzemolo Tritato,
Aglio Tritato','Metterle in un tegame con un pezzo di cipolla intero, un cucchiaio di aceto ogni 250 g, sale, un mazzetto di prezzemolo, uno spicchio d''aglio. Cuocere a fuoco basso, coperte d''acqua per circa 10 minuti. Aprirle e diliscarle. Servirle aperte a libro condite con olio, pepe, prezzemolo e aglio tritati.',1010);
INSERT INTO "ricette" VALUES (115,'Acciughe In Carpione Con Gentilina Ed Emulsione Di Mandarino','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','200 G Acciughe Fresche,
1 Cespo Insalata Gentilina Rossa,
1 Mandarino,
1 Cucchiaio Senape,
1 Costa Sedano,
1 Carota,
1/2 Cipolla,
Olio D''oliva,
Sale,
Pepe','Sfilettare le acciughe, cuocerle versandovi sopra una marinata calda di aceto, acqua e vino (in parti uguali) in cui si sia fatto precedentemente bollire per alcuni minuti un trito di sedano, carota e cipolla. Emulsionare l''olio con il succo del mandarino, la senape il sale e il pepe e condirvi l''insalata.',1061);
INSERT INTO "ricette" VALUES (116,'Acciughe In Pangrattato','Pesce','Acciughe Fresche',1,'Luogo: Sicilia.','12 Acciughe Fresche,
30 G Capperi Sotto Sale,
1 Spicchio Aglio,
1 Mazzetto Prezzemolo,
Olio D''oliva,
2 Cucchiai Pangrattato,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Lavate i capperi privandoli del sale, scolateli ed asciugateli. Mettete nel frullatore i capperi ed il prezzemolo, unitevi il pangrattato, l''aglio, il parmigiano, 4 cucchiai di olio e un pizzico di sale e pepe. Frullate fino ad ottenere un composto omogeneo. Versate il composto su un piatto largo. Lavate le acciughe, asciugatele, apritele a metà lasciandole unite sul dorso. Privatele della testa e delle lische centrali lasciando le codine. Passate poi da entrambe le parti nel composto preparato. Arrotolate le acciughe in modo che le code restino in alto. Spennellate la pirofila con l''olio rimasto, ponetevi le acciughe, e premetele leggermente per evitare che si aprano durante la cottura. Ponete in forno già caldo e fate cuocere per circa 10 minuti.',1021);
INSERT INTO "ricette" VALUES (117,'Acciughe In Salsa Piemontese','Pesce','Acciughe',4,'Luogo: Piemonte.','200 G Acciughe Salate,
Aceto Di Vino,
Vino Bianco,
Capperi,
50 G Tonno,
Aglio,
1/4 Peperone,
Alloro,
Timo,
Basilico,
Senape,
Salsa Di Pomodoro,
Zucchero,
Olio D''oliva Extra-vergine','Dissalare le acciughe con acqua corrente e lavarle in aceto e vino. Disporle asciutte in un piatto irrorato d''olio. Frullare insieme tonno, erbe aromatiche, peperone, capperi, aglio, salsa di pomodoro, zucchero, un po'' d''aceto, senape, facendo cadere l''olio a filo fino fino ad ottenere una crema fluida. Versarla sulle acciughe e servire.',1412);
INSERT INTO "ricette" VALUES (118,'Acciughe In Saor','Antipasto','Acciughe',4,' -','600 G Acciughe Fresche,
25 Cl Olio Per Friggere,
2 Cipolle Grandi Affettate Sottili,
Alcuni Cucchiai Farina,
4 Cucchiai Olio D''oliva,
2 Bicchieri Aceto Di Vino Bianco,
50 G Pinoli,
40 G Uvetta Sultanina','Pulite con cura le acciughe. Liberatele della testa e della lisca centrale, lavatele e asciugatele delicatamente; passatele nella farina e fatele friggere in una padella di ferro nell''olio bollente. Quando saranno dorate da ambo le parti, toglietele con la paletta e deponetele sulla carta assorbente, perché perdano l''eccesso di unto. In un altro tegame versate intanto 4 cucchiai di olio e fatevi soffriggere, dolcemente, le cipolle affettate sottili sino a quando saranno ben imbiondite (ma non comincino a scurirsi), bagnatele con 2 bicchieri scarsi di aceto di vino bianco e lasciatele sobbollire per 3 minuti. Adagiate allora, a strati, dentro una terrina di ceramica o di vetro le acciughe fritte; distribuite sopra ogni strato un po'' di cipolle, di pinoli e di uvetta sultanina (fatta in precedenza rinvenire in acqua tiepida e poi ben strizzata) e spruzzate con un po'' di aceto caldo. Versate infine sui pesci il rimanente aceto, in modo che possano risultare ben coperti dal sugo aromatico.',4934);
INSERT INTO "ricette" VALUES (119,'Acciughe In Teglia','Antipasto','Acciughe',4,'Luogo: Liguria. Luogo: La Spezia. Preparazione: 20 minuti.','20 Acciughe Freschissime,
Abbondante Prezzemolo Tritato,
Pangrattato,
Sale,
Pepe,
Olio D''oliva,
Aceto Di Vino Bianco','E'' un modo sbrigativo ma gustosissimo di cucinare le acciughe. Lavate bene e togliete la testa a 20 acciughe freschissime. Disponetele in una teglia una accanto all''altra. Cospargetele di abbondante prezzemolo tritato, pangrattato, sale, pepe, inumiditele con olio e infine con aceto di vino bianco. Cuocetele in forno e offritele caldissime.',1215);
INSERT INTO "ricette" VALUES (120,'Acciughe In Viola','Pesce','Acciughe',2,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe,
2 Patate,
1 Cavolo Rosso,
Olio Per Friggere,
Sale,
Pepe,
Erba Cipollina,
1 Limone,
1 Spicchio Aglio,
Per La Pastella:,
50 G Albume D''uovo,
100 G Farina,
100 G Birra,
100 G Olio D''oliva','Ricavare dalle patate sbucciate fili lunghi e sottili aiutandovi con una mandolina cinese. Lasciare le patate in acqua fredda per eliminare l''amido. Avvolgere le acciughe nei fili di patata, creando così un bell''effetto nido. Friggere in pastella. Stufare il cavolo rosso in olio e aglio, portare a cottura in brodo vegetale. Filtrare il liquido residuo e mettere da parte. Condire le foglie con olio, pepe e sale. Finitura e presentazione. Adagiare al centro del piatto le foglie del cavolo rosso, posare le acciughe appena fritte e aggiungere il fondo di cavolo rosa. Condire con sale e gocce di limone evidenziando cosi un cambiamento di colore nel fondo da viola a rosa tenue.',2545);
INSERT INTO "ricette" VALUES (121,'Acciughe Marinate','Pesce','Acciughe',4,' -','500 G Acciughe Piccole,
1 Spicchio Aglio,
2 Limoni,
1 Ciuffo Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Pulite le acciughe, togliete testa, interiora e lisca, apritele a metà senza dividerle; disponetele a raggio in un piatto fondo. Tritate prezzemolo e aglio, unite il succo dei limoni, sale e pepe. Emulsionate e versate la salsa sui pesci; coprite e tenete al fresco alcune ore.',1241);
INSERT INTO "ricette" VALUES (122,'Acciughe Marinate (2)','Antipasto','Acciughe',4,' -','500 G Acciughe Freschissime,
2 Limoni,
2 Cucchiai Aceto Di Mele,
Sale,
Peperoncino,
Aglio,
Prezzemolo Tritato,
Olio D''oliva Extra-vergine','Pulire le acciughe togliendo testa e interiora, e lasciandole unite per il dorso; lavarle e scolarle. Disporle in una terrina; irrorandole con succo di limone e aceto fino a coprire. Far marinare per 2-3 ore e scolare. Disporre le acciughe a strati in una ciotola e condire ogni strato con aglio, peperoncino, sale, prezzemolo tritato. Irrorare il tutto con l''olio e servire dopo almeno 1 ora.',1273);
INSERT INTO "ricette" VALUES (123,'Acciughe Marinate (3)','Antipasto','Acciughe',4,'Luogo: Veneto.','20 Acciughe Fresche,
1 Cipolla,
1/2 Bicchiere Olio D''oliva,
1/2 Bicchiere Aceto Di Vino,
Sale','Lavate le acciughe; decapitatele e diliscatele. Disponetene uno strato in un largo piatto da portata e copritele con parte delle cipolle, mondate e tagliate a fettine sottili. Ripetete gli strati, alternando le acciughe alle cipolle. Alla fine, spargete sul preparato una emulsione di olio, aceto e sale. Fate marinare il tutto in luogo fresco (anche in frigo) per almeno 24 ore, prima di servire.',840);
INSERT INTO "ricette" VALUES (124,'Acciughe Marinate Al Vino','Pesce','Acciughe',4,' -','300 G Acciughe Salate,
1 Bicchiere Aceto Di Vino Bianco,
2 Bicchieri Vino Bianco,
Alloro,
Aglio,
Prezzemolo,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Dissalare molto bene le acciughe, privandole della testa e diliscarle dividendole i due filetti. Asciugarle e metterle a strati in una marinata di aceto, vino, alloro, aglio, pepe in grani. Farle riposare nella marinata per 24 ore, quindi sgoccioarle e accomodarle a strati con aglio e prezzemolo e coprire con olio.',1298);
INSERT INTO "ricette" VALUES (125,'Acciughe Marinate Alla Menta','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','10 Acciughe,
Aceto Di Vino Bianco,
Menta Fresca,
10 Olive Nere Mosciarelle,
1 Limone,
Olio D''oliva,
Sale,
Pepe','Marinare i filetti d''acciughe in olio ed aceto, intervallandoli a foglie di menta e fettine di limone. Pulire e sbollentare gli agretti, condirli con olio, sale e pepe, unire le orive nere mosciarelle denocciolate e tagliuzzate. Servire con i filetti d''acciughe marinati.',1009);
INSERT INTO "ricette" VALUES (126,'Acciughe Marinate Alla Sambenedettese','Pesce','Acciughe',4,'Luogo: Marche. Luogo: San Benedetto Del Tronto.','500 G Acciughe Fresche Pulite E Spinate,
2 Pugni Farina,
2 Spicchi Aglio Schiacciato,
1 Rametto Mentuccia,
1 Presa Peperoncino Macinato,
2 Bicchieri Aceto Di Vino Rosso,
Olio D''oliva Extra-vergine,
Olio Per Friggere,
Sale','Infarinare e friggere in abbondante olio bollente le acciughe, scolarle e salarle. In una piccola casseruola portare ad ebollizione l''aceto con l''aglio, le foglie di mentuccia e il peperoncino. In una terrina sistemare le acciughe fritte formando vari strati e, sopra, versare l''aceto bollente assieme a tutti gli aromi, fino a riscoprire completamente i pesci. Lasciar insaporire per 24 ore in frigorifero poi servire. Si possono conservare per alcuni giorni.',2250);
INSERT INTO "ricette" VALUES (127,'Acciughe Marinate Con Bottarga E Zuppetta Di Pomodorini','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe,
Abbondante Sale Grosso,
200 G Pomodorini,
2 Fette Pane,
Bottarga In Polvere,
Olio D''oliva Extra-vergine','Pulire le acciughe, metterle in una teglia a marinare per 10 minuti con abbondante sale grosso. Sciacquarle ed asciugarle per eliminare il sale in eccesso. Tagliare i pomodori in 4 parti e cuocerli con il coperchio in un tegame con olio, sale e pepe. Frullare per ottenere una crema densa. Tagliare il pane a cubi e dorarli in un padellino con olio. Mettere la zuppetta di pomodorini in una fondina con i cubi di pane croccanti, adagiare le acciughe e la bottarga in polvere.',1408);
INSERT INTO "ricette" VALUES (128,'Acciughe Olio E Limone','Antipasto','Acciughe',4,' -','500 G Acciughe,
1/2 Bicchiere Olio D''oliva,
2 Limoni,
Sale','Squamare le acciughe e privarle delle teste e delle interiora. Lavarle, asciugarle e disporle molto vicine in una pirofila. Emulsionare l''olio con il succo dei limoni e versare la salsa sul pesce. Salare e infornare a 180 gradi per circa 30 minuti.',1200);
INSERT INTO "ricette" VALUES (129,'Acciughe Piccanti','Antipasto','Acciughe',4,' -','400 G Acciughe Grandi,
2 Cucchiai Vino Bianco,
2 Pomodori Piccoli,
1 Cucchiaio Paprica Dolce,
1 Peperoncino Secco,
1 Spicchio Aglio,
1 Cipolla,
4 Cucchiai Olio D''oliva Extra-vergine,
1/2 Cucchiaio Aceto Di Vino,
1 Presa Sale','Eviscerare le acciughe, sciacquarle e asciugarle. Sbucciare l''aglio e tritarlo. Sbollentare i pomodori, quindi sbucciarli, eliminare i semi e tagliarli a pezzetti. Spezzettare il peperoncino. Mettere 2 cucchiai di olio, il peperoncino e l''aglio in una casseruola e lasciare insaporire. Aggiungere la paprica e la cipolla tagliata a fette sottili. Mescolare, unire le acciughe, bagnare con il vino e proseguire la cottura per 4 minuti. Stemperare una presa di sale nell''aceto versato in una ciotola e incorporare l''olio rimasto insieme al liquido di cottura delle acciughe. Disporre queste in un piatto di portata, distribuire sopra i pezzi di pomodoro, condire con la salsa e servire. ',1288);
INSERT INTO "ricette" VALUES (130,'Acciughe Ripiene','Pesce','Acciughe',4,' -','600 G Acciughe,
2 Panini,
Latte,
3 Uova,
70 G Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
Origano,
Pangrattato,
Olio D''oliva,
Alcuni Spicchi Di Limone','Pulire le acciughe e privarle della testa e della lisca centrale. Mescolare la mollica ammollata nel latte e strizzata con un uovo, il parmigiano, sale, pepe e origano. Appaiare le acciughe inframezzandole con il ripieno, farle aderire e passarle prima nelle uova sbattute con il sale e poi nel pangrattato. Dopo 30 minuti friggerle nell''olio bollente. Servirle ben calde con il limone.',2818);
INSERT INTO "ricette" VALUES (131,'Acciughe Ripiene (2)','Pesce','Acciughe',4,' -','600 G Acciughe,
2 Panini,
Latte,
2 Uova,
2 Cucchiai Formaggio Grattugiato,
Origano,
Pangrattato,
Olio D''oliva,
Sale,
Pepe,
Per Servire:,
Alcuni Spicchi Limoni','Togliete la testa, le interiora e la lisca alle acciughe; lavatele, asciugatele su carta da cucina assorbente. Ammorbidite nel latte la mollica dei panini strizzatela e raccoglietela in una ciotola unendo un uovo, due cucchiai di formaggio grattugiato, un po'' di origano, sale e pepe. Farcite con questo composto le acciughe, pressatele bene, passatele nell''uovo rimasto sbattuto con il sale e poi nel pangrattato. Fatele friggere nell''olio bollente, sgocciolatele e servitele con spicchi di limone.',2607);
INSERT INTO "ricette" VALUES (132,'Acciughe Ripiene Con Pesto Al Basilico E Lime','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','400 G Filetti D''acciughe,
150 G Formaggio Provola Affumicata,
Farina,
1 Uovo,
Pangrattato,
1 Mazzo Basilico,
40 G Pinoli,
1 Lime,
Sale,
Pepe,
Olio Di Semi Di Arachidi,
Olio D''oliva Extra-vergine','Farcire i filetti d''acciughe con dei pezzetti di provola, passarli nella farina, nell''uovo ed infine nel pangrattato profumato con la scorza del lime grattugiata. Ripetere l''operazione e poi friggere in olio di semi di arachidi ben caldo. A parte, frullare il basilico con i pinoli, la scorza del lime grattugiata, un filo d''olio d''oliva e regolare di sale e pepe. Servire le acciughe ripiene con il pesto.',3211);
INSERT INTO "ricette" VALUES (133,'Acciughe Ripiene Con Provola Affumicata E Pane Alle Erbe','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','400 G Filetti D''acciughe Già Pulite,
200 G Formaggio Provola Affumicata,
1 Uovo,
Pangrattato,
1 Mazzetto Erbe Fresche,
Olio Di Semi Di Arachidi','Prendere due filetti d''acciughe alla volta, farcirli con una fettina di provola, chiudere a mo'' di panino, passare il tutto prima nell''uovo poi nel pangrattato frullato con le erbe fresche ed infine friggere in olio di semi di arachidi profondo.',2077);
INSERT INTO "ricette" VALUES (134,'Acciughe Ripiene Con Tortino Di Patate Allo Zenzero','Pesce','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Acciughe Sfilettate,
1 Formaggio Scamorza,
2 Uova,
100 G Mandorle A Scaglie,
100 G Pistacchi Sgusciati,
Mollica Di Pane Raffermo,
1 Limone,
1 Mazzetto Prezzemolo,
Olio D''oliva Extra-vergine,
100 Cl Olio Di Semi Di Arachidi,
Sale,
Pepe,
Per Il Tortino Di Patate:,
1000 G Patate Novelle,
1 Radice Di Zenzero,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Per il ripieno delle acciughe: frullare la mollica di pane raffermo con il prezzemolo e la scamorza tagliata a cubetti; condire con la buccia di limone grattugiata, l''olio d''oliva e regolare di sale e pepe. A parte, tritare finemente le mandorle e i pistacchi con un mixer in modo da ottenere una panure. Prendere due filetti d''acciughe alla volta: farcirne uno al centro con il composto precedentemente ottenuto e chiudere sovrapponendo il restante filetto. Passare le acciughe ripiene nell''uovo sbattuto e a seguire nella panure di frutta secca. Friggere in abbondante olio di semi di arachidi. Cuocere le patate in acqua bollente salata e schiacciarle con l''apposito attrezzo. Saltarle in padella con l''olio d''oliva, la radice di zenzero grattugiata e aggiustare di sale e pepe. Mettere le patate all''interno di un coppapasta posto al centro del piatto da portata e adagiarvi sopra le acciughe. Guarnire con delle foglie di prezzemolo e poi servire.',13267);
INSERT INTO "ricette" VALUES (135,'Acciughe Ripiene Di Scamorza Con Insalatina Di Radicchio','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Filetti D''acciughe,
150 G Formaggio Scamorza,
2 Uova,
Pangrattato,
1 Cespo Radicchio,
Aceto Di Mele,
Sale,
Olio Di Semi Di Arachidi','Farcire i filetti d''acciughe con un pezzetto di scamorza; chiudere con le restanti acciughe, passare prima nell''uovo sbattuto con 1 pizzico di sale poi nel pangrattato quindi friggere in olio di semi bollente. A parte, tagliare il radicchio a julienne e poi condire con sale, aceto di mele e olio d''oliva.',2036);
INSERT INTO "ricette" VALUES (136,'Acciughe Ripiene, Indorate E Fritte','Pesce','Filetti D''acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','300 G Filetti D''acciughe,
Farina,
2 Uova,
1 Spicchio Aglio,
Pangrattato,
Formaggio Grana Grattugiato,
300 G Spinaci,
Olio Di Semi Di Arachidi,
Sale,
Olio D''oliva Extra-vergine','Sbollentare gli spinaci, strizzarli, tagliarli finemente al coltello e rosolarli con dell''olio d''oliva. Mettere gli spinaci in una ciotola, amalgamarli con un trito di acciughe, aglio e grana. Farcire i filetti d''acciughe con il composto ottenuto, sovrapporre ulteriori filetti d''acciughe, passare nella farina, nell''uovo sbattuto con 1 pizzico di sale e nel pangrattato. Friggere in olio di semi bollente, tamponare con un foglio di carta assorbente, regolare di sale e poi servire.',2992);
INSERT INTO "ricette" VALUES (137,'Acciughe Sotto Peperoncino','Antipasto','Acciughe Sotto Sale',4,' -','Acciughe Sotto Sale,
Prezzemolo,
Aglio,
Peperoncino,
Aceto Di Vino Bianco,
Olio D''oliva','Lavare le acciughe con l''aceto. Preparare un battuto di prezzemolo, aglio e peperoncino. Disporre le acciughe a strati alternando acciughe e trito. Coprire con trito e olio per finire. Consumare dopo alcuni giorni. Si conservano per molto tempo.',852);
INSERT INTO "ricette" VALUES (138,'Acciughe Sotto Pesto','Antipasto','Acciughe',4,' -','250 G Acciughe Salate,
Olio D''oliva,
Prezzemolo,
Aglio,
Pepe','Lavare bene le acciughe e spinarle. Farne dei filetti e porli in una zuppierina coperti di olio, di un abbondante trito di prezzemolo, aglio e pepe.',1003);
INSERT INTO "ricette" VALUES (139,'Acciughe Su Cubi Di Zucca','Antipasto','Acciughe',4,'Fonte: i4moschettieri.mastertopforum.net.','3 Acciughe,
1 Fetta Zucca,
1 Rametto Rosmarino,
Basilico,
1 Filo Olio D''oliva,
Sale,
Pepe','Tagliare a cubi la zucca e sbollentarli. Avvolgervi attorno i filetti di acciughe e infilzarli con uno spiedino; cuocerli in padella con un filo d''olio, basilico e rosmarino.',443);
INSERT INTO "ricette" VALUES (140,'Acciughe Tartufate','Antipasto','Acciughe',4,' -','600 G Acciughe Sotto Sale,
1 Tartufo Bianco,
Olio D''oliva','Dissalate con cura le acciughe sotto l''acqua corrente. Eliminate testa e lisca, dividetele in filetti e asciugateli bene. Pulite il tartufo e tagliatelo a fettine sottili. In un vasetto di vetro disponete uno strato d''acciughe, copritelo con uno di tartufo, spruzzate con olio. Continuate a strati sino a esaurimento degli ingredienti e condite con abbondante olio. Lasciate insaporire tenendo in luogo fresco per alcuni giorni. Vini di accompagnamento: Barbera D''Asti DOC, Colli Martani Sangiovese DOC, Cilento DOC.',1360);
INSERT INTO "ricette" VALUES (141,'Acciughe Tartufate (2)','Antipasto','Filetti D''acciughe',4,' -','Filetti D''acciughe Dissalati,
Tartufo Bianco,
Olio D''oliva','Disporre le acciughe a strati in un barattolo di vetro a chiusura ermetica, alternandole con sottili scaglie di tartufo bianco, coprendo il tutto con olio d''oliva. Si possono consumare subito o conservare a lungo.',826);
INSERT INTO "ricette" VALUES (142,'Acciughette Alla Ammiraglia','Antipasto','Acciughette',4,'Preparazione: 20 minuti. Riposo: 12 ore.','600 G Acciughe,
4 Limoni,
Olio D''oliva,
Sale,
Pepe,
Origano (facoltativo)','Pulite bene le acciughe fresche, diliscandole internamente, levate testa e coda e dividetele a filetti. Lavate i filetti in acqua fredda e poi asciugateli bene, disponendoli su un piatto di portata. Coprite completamente le acciughe con abbondante succo di limone filtrato bene e lasciate riposare 12 ore. Al momento di servire battete in una tazzina olio, pepe e poco sale, irrorate le acciughe e portate in tavola: per effetto del limone le acciughe si saranno cotte e appariranno bianchissime. Potrete completare a piacere con una spolverata di origano fresco.',1368);
INSERT INTO "ricette" VALUES (143,'Acciughine Di Trebisacce','Antipasto','Acciughine',4,'Luogo: Calabria. Luogo: Trebisacce.','Acciughe Piccole,
Sale,
Peperoncino Piccante Pestato,
Olio D''oliva','Lavate le minuscole acciughe, intere naturalmente, in acqua di mare e lasciatele sgocciolare e asciugare bene sopra un graticcio. In un vaso di creta fate un leggero strato di sale piuttosto fino (poiché dovrà sciogliersi completamente) e cospargete abbondantemente di peperoncino rosso piccante pestato nel mortaio. Se lo preferite, potete usare peperoncino piccante più peperoncino dolce (metà e metà). Fate uno spesso strato di acciughe, poi di sale e peperoncino e così via, fino a porre il disco di legno e, per peso, il sasso circolare. Dopo un paio di mesi di stagionatura, versate sulla superficie un dito d''olio d''oliva per evitare che abbiano contatto con l''aria e tenete in luogo freddo.',795);
INSERT INTO "ricette" VALUES (144,'Accordion','Bevande','Brandy',1,' -','3/5 Brandy,
1/5 Vermouth Dolce,
1/5 Vermouth Dry,
2 Cucchiai Triple Sec','Riempire per metà lo shaker con cubetti di ghiaccio. Mettere nello shaker tutti gli ingredienti e agitare bene. Mettere in un bicchiere da cocktail il composto ottenuto e servire.',423);
INSERT INTO "ricette" VALUES (145,'Accordo','Bevande','Whisky',1,' -','2/5 Champagne,
1/5 Vodka,
1/5 Whisky Americano,
1/5 Whisky','Mescolare con ghiaccio nel mixer. Servire nel calice alto.',266);
INSERT INTO "ricette" VALUES (146,'Ace','Bevande','Vodka Keglevich',1,' -','4 Cucchiai Vodka Keglevich,
1 Cucchiaio Brandy Stock 84,
1 Cucchiaio Curacao Blu,
Per Servire:,
1 Ciliegina Al Maraschino,
1 Sprizzo Buccia D''arancia','Si prepara nel mixing glass con ghiaccio. Si serve nella coppetta da cocktail, decorando con 1 ciliegina al maraschino e sprizzando il tutto con 1 buccia d''arancia',665);
INSERT INTO "ricette" VALUES (147,'Aceto','Salsa','Vino',4,' -','100 Cl Vino,
25 Cl Aceto Di Vino,
1 Panino (mollica) (facoltativo)','Usare un recipiente di terracotta non smaltata con vernici tossiche (capacità almeno 4 litri) o un bottalino di legno da 5 litri con rubinetto a spina. Versare un litro di vino (attenzione: per un buon risultato la gradazione del vino dev''essere intorno ai 10 gradi) e un quarto di buon aceto di vino. Chiudere il recipiente con un tappo di sughero, ma aprirlo ogni giorno per 30 minuti. Dopo due settimane si formerà la ''madre'' dell''aceto della consistenza vischiosa e l''aceto sarà pronto per l''uso, aggiungendo mano a mano altro vino per mantenere il livello costante. Chi usa il bottalino la prima volta lo dovrà prima lavare con acqua, poi con aceto scuotendolo bene, poi lo lascerà asciugare completamente. Per facilitare la fermentazione, si possono aggiungere al vino pochi trucioli di legno di faggio o di abete, oppure la mollica di un panino (in quest''ultimo caso si dovrà poi filtrare l''aceto). Si consiglia inoltre di levare l''aceto una volta l''anno, per ''lavare'' la madre e (se ci sono) i trucioli. Si lava bene il recipiente, lo si asciuga e infine si rimette dentro l''aceto passato attraverso un telo pulito, i trucioli e la ''madre'' lavata nel vino.',1041);
INSERT INTO "ricette" VALUES (148,'Aceto (2)','Salsa','Vino',4,' -','1 Bottiglia Vino','Esiste più di un metodo per ottenere del buon aceto, quello più semplice e veloce è sicuramente quello col recipiente di terracotta. Prendete un recipiente di terracotta ben lavato e asciugato e versatevi una bottiglia di vino genuino, coprite con un telo piegato e lasciatelo all''incirca un mese affinché la trasformazione risulti completa. Questo sistema è abbastanza efficace ma per avere un aceto a regola d''arte sarebbe ideale utilizzare il tinello, quel contenitore fatto con doghe di legno che una volta si trovava in tutte le case di campagna. Oggi lo si può vedere appeso alla parete di una cucina come abbellimento e sicuramente dà il suo tocco di rustico, ma sarebbe meglio saperlo anche utilizzare in occasioni come questa. Il procedimento è lo stesso del recipiente di terracotta ma il fatto è che con il legno il risultato è diverso. Bisogna comunque sempre ricordare che: il liquido non deve mai arrivare al bordo ma deve rimanere sempre sotto di tre dita; quando si toglie l''aceto per usarlo bisogna sempre ricordarsi di aggiungere dei fondi di vino nella stessa quantità; se il liquido comincia ad intorbidirsi bisogna filtrarlo; il tinello non deve essere mai lasciato scoperto perché la polvere potrebbe danneggiare il processo di acetilizzazione; se nel liquido si dovessero notare dei vermetti bisognerà farlo scaldare a 60-70 gradi per distruggerli.',750);
INSERT INTO "ricette" VALUES (149,'Aceto Agli Aromi','Salsa','Aceto Di Vino',4,' -','Alcuni Spicchi Aglio,
Alcuni Spicchi Scalogno,
1 Mazzetto Erbe Miste (maggiorana, Alloro, Basilico, Erba Cipollina),
Sale,
Pepe,
200 Cl Aceto Di Vino','Tritate l''aglio e lo scalogno. Fate bollire lentamente l''aceto finché si riduce a metà. Versatelo caldo in una ciotola dove avrete preparato tutti gli aromi. Coprite il recipiente e lasciate macerare 2 ore. Filtrate, imbottigliate, tappate ermeticamente le bottiglie. La perfetta riuscita dipende dalla freschezza e dalla varietà delle erbe. Serve per condire verdure crude o cotte.',157);
INSERT INTO "ricette" VALUES (150,'Aceto Agli Aromi (2)','Salsa','Aceto Di Vino Bianco',4,' -','100 Cl Aceto Di Vino Bianco,
1 Aglio Sbucciato,
2 Scalogni,
1 Rametto Maggiorana,
1 Rametto Timo,
1 Foglia Alloro','E'' utilizzato per condire peperoni, cipolle, insalate miste di verdure e la classica insalata con lattuga e pomodori. Si prepara mettendo in un recipiente di terracotta 1 litro d''aceto di vino bianco. Si porta ad ebollizione e si lascia ridurre a metà, si toglie dal fuoco e si aggiungono 1 aglio sbucciato e leggermente pestato, 2 scalogni, 1 rametto di maggiorana, 1 di timo e 1 foglia d''alloro. Il tutto si lascia macerare per 2 ore, poi viene colato, attraverso una garza, in una bottiglia di vetro scuro, si chiude perfettamente e si lascia riposare in un luogo fresco e buio per 6 giorni.',84);
INSERT INTO "ricette" VALUES (151,'Aceto Agli Aromi E Peperoncino','Salsa','Aceto Di Vino',4,' -','100 Cl Aceto Di Vino,
6 Peperoncini,
1 Spicchio Aglio,
1 Pizzico Sale,
1 Rametto Rosmarino','Si usa per cucinare e condire insalate e carni rosse. Si prepara mettendo in 100 cl d''aceto 6 peperoncini, 1 spicchio d''aglio pulito e schiacciato, un pizzico di sale e un rametto di rosmarino. Lasciate il tutto a macerare dieci giorni in un luogo asciutto dopodichè filtratelo con il colino, o meglio, con una pezzuola.',82);
INSERT INTO "ricette" VALUES (152,'Aceto Agli Aromi Misti','Salsa','Aceto Di Vino Bianco',4,' -','2 Spicchi Aglio,
1 Scalogno,
1 Cucchiaino Foglie Di Timo,
1 Manciata Foglie Di Prezzemolo,
1 Rametto Rosmarino,
3 Foglie Salvia,
3 Grani Pepe Nero,
1 Foglia Alloro,
2 Chiodi Di Garofano,
100 Cl Aceto Di Vino Bianco','Mettere in un recipiente con imboccatura larga 2 spicchi d''aglio leggermente schiacciati, 1 scalogno sbucciato e tagliato a metà, un cucchiaino di foglie di timo, una manciata di foglie di prezzemolo, un rametto di rosmarino, 3 foglie di salvia, 3 grani di pepe nero, una foglia d''alloro e 2 chiodi di garofano. Versare 100 cl di aceto di vino bianco, precedentemente portato a bollore, nel recipiente con tutti gli ingredienti e lasciare raffreddare. Chiudere bene il recipiente e utilizzare l''aceto dopo 3 mesi.',91);
INSERT INTO "ricette" VALUES (153,'Aceto Ai 5 Fiori','Salsa','Aceto Di Vino',4,' -','100 Cl Aceto Di Vino,
1 Manciata Fiori Di Sambuco,
1 Manciata Fiori Di Timo,
1 Manciata Fiori Di Salvia,
1 Manciata Fiori D''assenzio,
1 Manciata Fiori Di Tarassaco,
2 Rametti Dragoncello,
Alcuni Chiodi Di Garofano,
1 Cucchiaino Sale','Lasciate gli ingredienti in infusione ne||''aceto per 10 giorni, quindi filtrate il liquido e conservatelo in bottiglie ben chiuse.',104);
INSERT INTO "ricette" VALUES (154,'Aceto Ai Fichi Secchi','Salsa','Fichi Secchi',4,' -','100 Cl Aceto Di Vino Rosso,
12 Fichi Secchi,
4 Foglie Alloro,
2 Cucchiaini Pepe Verde,
10 Chiodi Di Garofano','Unire all''aceto rosso i fichi, le foglie di alloro i chiodi di garofano e il pepe verde lasciando in infusione per oltre un mese. Conservarlo al fresco avendo cura di agitare, ogni tanto, la bottiglia che contiene gli ingredienti. Questo aceto è ideale per tutti i piatti in addobbo e può accompagnare anche il gelato e ogni tipo di insalate miste.',2051);
INSERT INTO "ricette" VALUES (155,'Aceto Ai Frutti Di Bosco','Salsa','Frutti Di Bosco',4,' -','Aceto Di Vino Bianco,
Frutti Di Bosco Misti Freschi','Scegliere un contenitore e in base alla capienza di quest''ultimo decidere la quantità di frutti di bosco da utilizzare in modo che una volta riempito il contenitore, la percentuale di "spazio" occupata dai frutti di bosco sia all''incirca pari al 5% e il resto sarà occupato dall''aceto. Prima di utilizzare l''aceto sarà bene far passare all''incirca un mese (o più per contenitori con capienza superiore al litro) in modo tale che i frutti di bosco cedano il proprio profumo e sapore all''aceto. Al momento dell''utilizzo non è necessario che il liquido venga filtrato, basta