ncia,
Alcune Scorze Di Mandarino','Agitare con ghiaccio tritato nello shaker. Servire nel calice panciuto, decorando con scorze di limone, d''arancia e di mandarino.',426);
INSERT INTO "ricette" VALUES (27210,'Ventagli Di Chayote Stufati','Contorno','Chayote',4,' -','2 Chayote (di 300 G Ciascuno),
60 G Burro,
1 Scalogno,
1 Cucchiaio Zucchero,
Sale,
Pepe Bianco,
1/2 Limone (succo),
10 Cl Vino Bianco,
40 Cl Brodo Di Pollo O Di Verdura,
10 G Erba Cipollina','Sbucciate i chayote servendovi di un pelapatate, quindi tagliate in due ogni frutto nel senso della lunghezza ed eliminate il seme. Tagliate ogni mezzo chayote a fettine sottili, lasciando attaccate queste ultime ad un''estremità, quindi schiacciate leggermente i frutti in modo da ottenere i ventagli. In una pirofila con 40 g di burro fate soffriggere lo scalogno tagliato ad anelli, cospargetelo con lo zucchero e unite i ventagli di chayote. Insaporite con sale e pepe bianco, versate il succo di limone e il vino bianco e cuocete fino a far consumare quasi completamente il liquido. Aggiungete il brodo di pollo e chiudete la pirofila con un foglio di stagnola. Proseguite la cottura in forno a 180 gradi per circa 30-35 minuti. Passate al setaccio il fondo di cottura e fatelo ridurre fino ad ottenere 8 cl di liquido, quindi incorporatevi il resto del burro, freddo e a pezzetti. Servite i ventagli cosparsi con la salsina preparata e con qualche pezzetto di erba cipollina. --- CONSIGLI. I chayote sono ortaggi esotici che hanno forma simile ad una pera e polpa bianca e morbida. Sono particolarmente gustosi se cucinati con molte spezie, specialmente i chiodi di garofano, lo zenzero e la noce moscata.',932);
INSERT INTO "ricette" VALUES (27211,'Ventaglio Al Cioccolato Fondente E  Pesche Alla Menta','Dessert','Cioccolato Fondente',4,' -','300 G Cioccolato Fondente,
50 G Fecola Di Patate,
2 Tuorli D''uovo,
200 G Crema Di Latte,
200 G Latte,
500 G Pesche,
300 G Limone,
Menta Fresca,
Zucchero A Velo','Sciogliere a bagno maria il cioccolato. In una terrina di vetro sbattere le uova con la fecola il latte e la panna, fino a rendere il tutto liscio e omogeneo e unirvi a filo il cioccolato fuso. Scegliere  uno stampo a piacere e infornare a 180 gradi per 10 minuti circa. Pelare le pesche e affettarle sottilmente. Tagliamo a fette il tortino e le intervalliamole con le fettine di pesca, formando una raggiera. Guarniamo, quindi, con la menta e lo zucchero a velo.',2497);
INSERT INTO "ricette" VALUES (27212,'Ventaglio Di Banane Al Cointreau Con Coriandoli Di Frutta Fresca','Dessert','Banane',1,' -','1 Banana,
1 Noce Burro,
1 Cucchiaio Zucchero,
Succo D''arancia,
Cointreau,
1 Pizzico Cannella In Polvere,
Per La Guarnizione:,
Brunoise Di Kiwi,
Ananas,
Melone,
Frutti Di Bosco,
Per La Decorazione:,
Julienne Di Scorza D''arancia (solo Sul Bordo),
1 Fragolina Aperta A Ventaglio Sotto Le Banane','Scaldare la padella, sciogliere burro e zucchero, aggiungere banane con un pizzico di cannella e fare sciroppare. Flambare con Cointreau, aggiungere succo d''arancia. Insaporire per qualche istante e disporre nel piatto, a ventaglio. Unire la brunoise nel fondo di cottura e lasciare insaporire pochi secondi anch''essa e unire dall''altra parte del piatto.',1149);
INSERT INTO "ricette" VALUES (27213,'Venticinque','Bevande','Vermouth Dry',1,' -','1/3 Panna Liquida,
1/3 Vermouth Dry,
1/3 Curacao','Agitare, con ghiaccio tritato, nello shaker. Servire nel tumbler ampio.',283);
INSERT INTO "ricette" VALUES (27214,'Vera Cruz','Bevande','Gin',1,' -','1/4 Succo Di Limone,
3/4 Gin,
1 Cucchiaio Pernod,
1/2 Cucchiaio Zucchero,
1 Spruzzo Angostura,
Per Servire:,
1 Scorza Di Limone','Agitare a lungo nello shaker con ghiaccio tritato. Servire in calice con scorza di limone.',377);
INSERT INTO "ricette" VALUES (27215,'Verde','Bevande','Anisette',1,' -','2/5 Sciroppo Di Zucchero,
3/5 Anisette,
2 Spruzzi Angostura,
2 Spruzzi Curacao','Agitare nello shaker pieno a metà di ghiaccio tritato. Servire nel calice ampio.',450);
INSERT INTO "ricette" VALUES (27216,'Verdi','Bevande','Succo Di Pesca',1,' -','3/10 Jameson Irish Whisky,
1/10 Maraschino Luxardo,
3/10 Succo Di Pesca,
3/10 Succo D''ananas Bluebird,
Alcune Gocce Sciroppo Di Fragola Toschi,
Per Guarnire:,
Frutta A Piacere','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nel bicchiere tumbler alto con ghiaccio. Guarnire con spiedino di frutta e cannucce.',303);
INSERT INTO "ricette" VALUES (27217,'Verdi (2)','Bevande','Succo D''arancia',1,' -','3/10 Jameson Irish Whisky,
2/10 Vermouth Rosso Martini,
5/10 Succo D''arancia,
Per Guarnire:,
Frutta','Si prepara nello shaker con cubetti di ghiaccio. Agitare vigorosamente e servire nel bicchiere flute ghiacciato. Guarnire con spiedino di frutta.',329);
INSERT INTO "ricette" VALUES (27218,'Verdure Al Curry','Contorno','Curry',4,' -','1 Cipolla,
2 Carote,
300 G Patate,
150 G Fagiolini,
200 G Cavolfiore,
2 Pomodori Maturi,
125 G Yogurth,
Poco Olio D''oliva,
Zenzero,
1 Cucchiaino Semi Di Cumino,
2 Cucchiaini Curcuma Macinata,
1 Cucchiaino Coriandolo Macinato,
1 Peperoncino','In una padella con poco olio, fate scaldare la cipolla affettata fine e lo zenzero pelato e grattugiato. Aggiungete un cucchiaino di semi di cumino, due di curcuma macinata, uno di coriandolo macinato e un peperoncino. Unite le carote a rondelle, le patate, i fagiolini e il cavolfiore tagliati a pezzettini. Dopo 5 minuti unite i pomodori sbucciati e senza semi, lo yogurth e 20 cl d''acqua. Salate e lasciate cuocere per circa 20 minuti.',949);
INSERT INTO "ricette" VALUES (27219,'Verdure Al Forno','Contorno','Patate',4,' -','4 Patate,
4 Zucchine,
2 Melanzane,
3 Pomodori,
1 Cipolla,
Aglio Tritato,
Prezzemolo Tritato,
2 Cucchiai Formaggio Grana Grattugiato,
2 Cucchiai Pangrattato,
5 Cucchiai Olio D''oliva,
Brodo,
Aneto Tritato,
Sale,
Pepe','Appassire la cipolla tritata con 4 cucchiai di olio, salare, pepare. In una pirofila unta disporre a strati le verdure lavate e affettate cospargendo ogni strato con prezzemolo e aneto, salare e pepare. Versare infine la cipolla, un po'' di brodo bollente e cuocere in forno caldo a 180 gradi per 40''. A metà cottura cospargere con pangrattato e grana.',1840);
INSERT INTO "ricette" VALUES (27220,'Verdure Al Latte','Contorno','Latte',4,' -','50 Cl Latte,
4 Zucchine,
500 G Piselli,
4 Carote,
4 Cipolline,
Formaggio Parmigiano Grattugiato,
70 G Burro,
1 Cucchiaio Prezzemolo,
Pepe,
Sale','Mondare le verdure e tagliarle a dadini Rosolarle leggermente, insieme ai piselli, nel burro su fuoco dolce, mettendo in pentola prima le verdure più dure. Unire sale e pepe, coprirle con il latte e alzare la fiamma. Cuocere mescolando delicatamente ogni tanto. Infine spolverizzare con il prezzemolo e il parmigiano.',1744);
INSERT INTO "ricette" VALUES (27221,'Verdure Al Latte Di Cocco','Contorno','Latte Di Cocco',4,'Preparazione e cottura: 25 minuti.','30 Cl Latte Di Cocco,
2 Pomodori Grandi,
250 G Cavolo Cinese,
1/2 Cipolla,
1 Spicchio Aglio,
125 G Fagiolini Mangiatutto,
1/4 Cucchiaino Curcuma In Polvere,
2 Cucchiai Olio D''arachidi,
1 Pizzico Peperoncino In Polvere,
Sale','Pelate la cipolla e tritatela grossolanamente. Mondate l''aglio e tritatelo fine. Lavate i pomodori e tagliateli a pezzi grossi. Mondate i fagiolini mangiatutto. Mondate il cavolo, lavatelo, asciugatelo e tritatelo grossolanamente. Scaldate l''olio in un wok o in una padella, buttatevi la cipolla e l''aglio e lasciateli cuocere per due o tre minuti facendo attenzione che non prendano colore. Aggiungete i fagiolini mangiatutto, la curcuma e il peperoncino. Salate, bagnate con 15 cl di latte di cocco e lasciate cuocere per tre minuti, mescolando senza sosta. Aggiungete il cavolo e i pomodori, lasciate cuocere per altri tre minuti. Bagnate con il latte di cocco rimanente e fate sobbollire per uno o due minuti; la verdura deve essere calda ma croccante. Assaggiate, condite ancora se necessario, versate in un piatto di servizio caldo e servite.',1575);
INSERT INTO "ricette" VALUES (27222,'Verdure All''orientale','Contorno','Carote',2,' -','2 Uova,
1 Cucchiaio Semi Di Sesamo,
2 Cucchiaini Prezzemolo Tritato,
1 Pizzico Chili In Polvere,
2 Cucchiai Olio D''oliva,
4 Carote Lessate Affettate,
225 G Broccoli Surgelati,
6 Coste Sedano Affettate,
4 Cucchiai Succo D''arancia,
1/2 Cucchiaio Salsa Worcester,
1 Cucchiaino Zenzero In Polvere,
130 G Anacardi,
Sale,
Pepe','Mettete le uova in una ciotola e battetele leggermente. Aggiungetevi i semi di sesamo, il prezzemolo, il chili in polvere, sale e pepe. Fate scaldare un cucchiaio d''olio in una padella con il fondo antiaderente e versatevi dentro le uova condite. Fate cuocere come una frittata per 3 minuti, finché le uova si saranno addensate al centro. Girate delicatamente e fate cuocere per altri 3 minuti. Mettete la frittata su un tagliere e arrotolatela su se stessa. Avvolgetela con un foglio di carta oleata per mantenerla tiepida. Versate il resto dell''olio nella padella e fate soffriggere gli altri ingredienti finché i broccoletti e il sedano saranno cotti e la salsa leggermente ristretta. Tenendola arrotolata, tagliate la frittata ad anelli, disponeteli intorno al bordo della padella, e servite immediatamente.',1596);
INSERT INTO "ricette" VALUES (27223,'Verdure Alla Cinese','Contorno','Carota',4,'Luogo: Cina.','4 Cipolle A Fettine,
1/2 Cucchiaino Ginger Fresco Grattugiato,
1 Carota,
1 Peperone A Fettine,
110 G Piselli,
1 Gambo Sedano Tagliato Per Lungo,
8 Cl Acqua,
1 Cucchiaio Salsa Di Soia,
Olio D''oliva,
Sale','Fate scaldare l''olio in una larga padella e, quando è caldo, versateci le cipolle e il ginger e lasciateli per 1 minuti, girando continuamente. A questo punto aggiungete la carota, il peperone, i piselli e il gambo di sedano. Soffriggete a fuoco vivace per 2 minuti. Versate poi l''acqua e qualche goccia di salsa di soia. Mescolate bene in modo che tutti gli ingredienti vengano insaporiti dalla soia e lasciate sul fuoco, eventualmente aumentando la fiamma, finché l''acqua non bolle.',968);
INSERT INTO "ricette" VALUES (27224,'Verdure Alla Greca','Contorno','Zucchine',6,'Luogo: Grecia.','500 G Zucchine,
500 G Fagiolini,
2 Cipolle,
3 Peperoni,
800 G Pomodori Maturi,
3 Spicchi Aglio,
100 G Olive Greche,
Alloro,
Timo,
Origano,
1 Cucchiaio Prezzemolo Tritato,
Sale,
Olio D''oliva,
Pepe','Pulire tutte le verdure e tagliarle a tocchi. Far appassire le cipolle tritate e l''aglio schiacciato nell''olio per 5 minuti. Unire i peperoni e cuocere per 10 minuti. Aggiungere le altre verdure e farle insaporire. Trasferire il tutto in una pirofila, salare, pepare, cospargere con le erbe tritate e le olive. Coprire con alluminio e infornare a 180 gradi per 40 minuti. Servire cosparso di prezzemolo.',1290);
INSERT INTO "ricette" VALUES (27225,'Verdure Allo Yogurth','Contorno','Fagiolini',4,' -','2 Cetrioli Sodi,
200 G Fagiolini Teneri,
1 Cucchiaio Pepe Rosa In Salamoia,
1 Cipolla,
2 Spicchi Aglio,
1 Ciuffo Prezzemolo,
Sale,
Pepe','In una pentola portare ad ebollizione 2 l di acqua salata a cui era stato aggiunto il pepe, la cipolla a spicchi e l''aglio a fettine. Appoggiarvi un cestello in cui cuocere i fagiolini a vapore per 8 minuti. Affettare i cetrioli e immergerli in poca acqua bollente salata. Scolarli dopo 40 secondi. Asciugare entrambe le verdure e accompagnarle con una crema alla yogurth.',99);
INSERT INTO "ricette" VALUES (27226,'Verdure Allo Zafferano','Contorno','Zafferano',4,' -','500 G Patate Novelle,
500 G Cipolline Fresche,
600 G Piselli Novelli,
Sale,
1 Bustina Zafferano,
1 Limone (succo)','Sbucciate e lavate le patate, ponetele in un''ampia casseruola insieme alle cipolline pelate. Unite i piselli alle verdure, salate, aromatizzate con lo zafferano, irrorate con il succo del limone e coprite il tutto con acqua fredda. Cuocete 30 minuti a fiamma bassa, coperto, rimestando di tanto in tanto. A cottura ultimata l''acqua dovrà essere stata assorbita completamente lasciando un fondo gustoso e colorito.',977);
INSERT INTO "ricette" VALUES (27227,'Verdure Brasate Alla Cinese','Contorno','Funghi',4,'Luogo: Cina.','1 Sedano Bianco,
250 G Funghi Champignon,
3 Cucchiai Olio D''arachidi,
2 Cucchiai Salsa Di Soia,
1 Cucchiaino Zucchero,
Pepe','Mondate il sedano, separate le coste, lavatele, eliminate i fili. Tagliate le coste di sedano in diagonale, a pezzettini di 2,5 cm. Mondate e lavate accuratamente, gli champignon e assicuratevi che tutto il terriccio sia eliminato, asciugateli, tagliate le teste a filo. Scaldate l''olio in un wok o in una grande padella, aggiungete i pezzettini di sedano e fatelo saltare per tre minuti, mescolando in continuazione. Aggiungete gli champignon, pepate e lasciate cuocere ancora per tre minuti, mescolando ogni tanto con un cucchiaio di legno. Aggiungete la salsa di soia e lo zucchero, fate cuocere per quattro o cinque minuti finché il sedano è appena tenero. Versate le verdure in un recipiente caldo e servite immediatamente.',813);
INSERT INTO "ricette" VALUES (27228,'Verdure Cotte In Fozelèk','Contorno','Verdure Miste',4,' -','800 G Verdure Miste,
1 Cipolla,
1 Spicchio Aglio,
Sale,
Paprica,
1 Cucchiaio Farina,
1 Cucchiaio Aceto Di Vino,
1 Cucchiaio Zucchero,
1/2 Bicchiere Panna','Lessare 800 g. di verdure miste e scolarle. Rosolare in un cucchiaio di strutto 1 cipolla e 1 spicchio d''aglio tritati, condirli con sale e paprica. Unire 1 cucchiaio di farina e rimescolare. Bagnare con una tazzina dell''acqua di cottura delle verdure. Unire le verdure alla salsa e lasciar addensare il tutto a fiamma dolce. Alla fine condire con un cucchiaio di aceto, uno di zucchero e 1/2 bicchiere di panna. Scaldare la panna rimescolando e servire subito. Si possono sostituire le verdure con legumi misti.',433);
INSERT INTO "ricette" VALUES (27229,'Verdure Fritte Alla Milanese','Contorno','Carciofi',6,'Luogo: Lombardia. Luogo: Milano.','2 Carciofi,
1 Finocchio,
2 Zucchine,
1 Melanzana Piccola,
2 Uova,
Pangrattato,
Burro,
1 Limone,
Sale','Lessate al dente il finocchio in acqua salata e tagliatelo a fette; togliete le foglie più dure ai carciofi, sfregateli con il limone, tagliateli e a fette e sbollentateli appena in acqua bollente. Scolateli bene. Tagliate a fette le zucchine nel senso della lunghezza. Sbucciate la melanzana e tagliatela a fette. Sbattete le uova in un piatto fondo, salatele. Passate le fette delle verdure nell''uovo, poi nel pangrattato e infine doratele nel burro.',1481);
INSERT INTO "ricette" VALUES (27230,'Verdure Gratinate','Contorno','Cavolo',6,'Luogo: Irlanda. Preparazione: 20 minuti. Cottura: 60 minuti.','500 G Cavolo,
500 G Patate,
250 G Carote,
250 G Rape Piccole,
15 Cl Panna Da Cucina,
4 Cucchiai Pangrattato,
4 Cucchiai Formaggio Parmigiano Grattugiato,
2 Tuorli D''uovo,
125 G Burro,
Sale,
Pepe','Fate bollire due pentole di acqua salata. Togliete le foglie esterne del cavolo, lavatelo e tagliatelo in quattro togliendo la parte dura all''interno. Sbucciate le patate, lavatele e tagliatele a pezzetti uguali. Mettete il cavolo e le patate, separatamente, nelle due pentole di acqua bollente e lasciate cuocere per venti minuti circa finché non saranno teneri. Nel frattempo, mondate le carote e le rape, lavatele e tagliatele a bastoncini. Mettetele in un''altra pentola, copritele con acqua fredda e portate a ebollizione. Scolate le verdure e mettetele nuovamente nella pentola. Aggiungete 50 g di burro e quattro cucchiai di acqua, poi fate sobbollire per trenta minuti. Imburrate una pirofila. Disponetevi la metà del cavolo e delle patate in uno strato uniforme. Mettete quindi le carote e le rape nel centro, lasciando un margine intorno, poi ricoprite con il resto del cavolo e delle patate. Cospargete il tutto con pangrattato, parmigiano grattugiato e il rimanente burro a fiocchetti. Infornate e lasciate gratinare per trenta minuti. Questa ricetta deriva da un piatto irlandese, il ''colcannon'' a base di cavolo e purè di patate. E'' economica e può essere servita con lardo o pancetta fritti, costolette di maiale o salsicce.',2700);
INSERT INTO "ricette" VALUES (27231,'Verdure Gratinate (2)','Contorno','Finocchi',4,' -','2 Finocchi,
2 Carote,
200 G Cavolfiore,
2 Patate,
2 Cucchiai Formaggio Emmenthal Grattugiato,
2 Cucchiai Formaggio Parmigiano Grattugiato,
25 Cl Besciamella,
2 Cucchiai Pangrattato','Pulite le verdure e tagliatele a pezzetti, disponetele in un pirofila da forno imburrata, cospargete con i formaggi grattugiati, irrorate con la besciamella, cospargete col pangrattato e cuocete in forno caldo a 180 gradi per 10 minuti.',1264);
INSERT INTO "ricette" VALUES (27232,'Verdure Gratinate Al Formaggio','Contorno','Porri',4,'Preparazione: 30 minuti. Cottura: 120 minuti.','12 Porri Piccoli,
2 Carote Grandi,
500 G Patate,
1 Rapa Piccola,
2 Gambi Sedano,
150 G Formaggio Fontina,
50 G Burro,
50 Cl Brodo Di Pollo,
25 G Farina,
2 Cucchiai Prezzemolo Tritato,
Noce Moscata,
Sale,
Pepe','Raschiate le carote, lavatele e tagliatele a rondelle. Pelate la rapa, lavatela e tagliatela a dadini. Mondate il sedano e tagliatelo a pezzetti. Lavate i porri dopo aver eliminato i filamenti e tagliateli a pezzetti di circa 2 cm. Fate fondere il burro in una padella. Aggiungetevi la rapa, le carote e il sedano e rosolateli a fuoco medio per circa otto minuti mescolando. Fate scaldare il forno a 170 gradi (termostato 5). Togliete le verdure dalla padella con la schiumarola e mettetele su un piatto da forno. Nella stessa padella mettete a rosolare i porri per due o tre minuti, mescolandoli. Toglieteli con la schiumarola e aggiungeteli alle verdure nel piatto da forno. Cospargete la padella di farina, mescolate con la spatola e versatevi il brodo poco per volta. Portate a ebollizione, sempre mescolando, salate, pepate e aggiungete un pizzico di noce moscata. Fate sobbollire per tre minuti poi mettete il prezzemolo. Versate questa salsa sulle verdure; mescolate delicatamente. Sbucciate le patate, lavatele, affettatele e disponetele sulle verdure. Coprite il piatto da forno con carta di alluminio, e fate cuocere nel forno per un''ora e mezzo finché le patate non sono tenere. Quando le patate sono cotte, grattugiate il formaggio, cospargetelo sulle patate, mettete il piatto sotto il grill e fate dorare. Servite caldo nello stesso piatto di cottura. Se non avete brodo, potete sostituirlo con latte o acqua.',1982);
INSERT INTO "ricette" VALUES (27233,'Verdure In Agrodolce','Contorno','Cipolline',4,' -','500 G Cipolline,
6 Carciofi,
100 G Olive Verdi,
1/2 Cipolla Rossa,
2 Cucchiai Aceto Di Vino,
2 Cucchiai Zucchero,
Olio D''oliva,
Sale,
Pepe','Sbucciare le cipolline e cuocerle in acqua salata per 15 minuti. In una casseruola soffriggere con l''olio la cipolla tritata, unire i carciofi puliti e tagliati a spicchi e le cipolline; salare, pepare e cuocere coperto per mezz''ora. Aggiungere le olive snocciolate, l''aceto e lo zucchero, mescolare, lasciare cuocere per qualche minuto e servire.',1192);
INSERT INTO "ricette" VALUES (27234,'Verdure In Bignè','Contorno','Verdure Miste',4,' -','450 G Verdure Miste,
1 Tuorlo D''uovo,
50 G Farina,
Olio D''oliva,
Sale','Tagliare a pezzetti le verdure e lessarle per 15 minuti in acqua poco salata. Scolarle e farle raffreddare. Ottenere una pastella densa mescolando la farina con il tuorlo e farla riposare per 30 minuti. Immergere le verdure nella pastella e friggerle nell''olio caldo. Farle asciugare su carta da cucina e salarle prima di servire.',1034);
INSERT INTO "ricette" VALUES (27235,'Verdure In Cartoccio','Contorno','Melanzana',4,' -','1 Melanzana,
1 Zucchina,
1 Peperone,
1 Pomodoro,
50 G Pancetta Affumicata,
100 G Salsiccia,
Burro,
Sale','Tagliate le verdure a dadini e suddividetele su quattro fogli di alluminio imburrati. Aggiungete un po'' di salsiccia sbriciolata, pezzetti di pancetta, fiocchetti di burro, sale. Chiudete i cartocci e cuoceteli sotto la cenere calda vicino alla brace per 15 minuti, oppure in forno.',1548);
INSERT INTO "ricette" VALUES (27236,'Verdure In Maionese','Antipasto','Patate',4,' -','2 Patate,
2 Zucchine,
1 Mazzetto Carote Novelle,
Maionese,
Fagiolini,
12 Olive Verdi Snocciolate,
2 Peperoni Gialli,
1 Cucchiaio Capperi,
2 Uova,
Olio D''oliva,
Aceto Di Vino,
Vino Bianco','Lessate le verdure, bruciacchiate i peperoni e togliete loro la pellicina. Affettate il tutto e mettete in una insalatiera con le olive snocciolate, i capperi e condite con sale, pepe, olio e mezzo bicchiere di vino bianco. Fate la maionese con le uova e acidulate con aceto. Unite tutto il preparato con la maionese e servite.',1999);
INSERT INTO "ricette" VALUES (27237,'Verdure Lesse Con Salsa Allo Scalogno','Contorno','Finocchi',6,'Preparazione: 40 minuti.','300 G Finocchi,
300 G Rape,
200 G Verza,
200 G Bietole,
12 Funghi Champignon,
8 Carotine,
Burro,
Sale,
Pepe,
Per La Salsa:,
120 G Burro,
2 Tuorli D''uovo,
Scalogno,
1 Limone,
Aceto Di Vino,
Sale,
Pepe Bianco In Grani','Sfogliate la verza, lavate le foglie quindi lessatele scolandole al dente. Spuntate il finocchio, tagliatelo a spicchi e lessatelo insieme con le rape, prima pelate e tornite a botticella. Mondate, lavate in più acque le bietole quindi lessatele in poco acqua salata. Infine pulite le cappelle degli champignon e rosolatele in una noce di burro spumeggiante; salate e pepate. Preparate la salsa: sciogliete il burro senza farlo friggere, quindi filtratelo passandolo attraverso una pezzuolina appoggiata dentro un fine colino. Fate bollire 2 cucchiaiate d''aceto con mezzo scalogno fino a quando il liquido sarà ridotto di circa metà; allora filtratelo e lasciatelo raffreddare. Mettete i tuorli in un recipiente insieme con mezzo guscio d''uovo d''acqua fredda, la riduzione di aceto e un pizzico di sale. Immergete il recipiente in un bagnomaria tiepido e, tenendo il tutto su fuoco moderato, lavorate le uova con la frusta, fino a quando incominceranno ad addensarsi. Allora togliete dal bagnomaria e unite il burro, versandolo a filo e continuando sempre a mescolare. Infine incorporate il succo di un limone, una macinata di pepe e ancora un pizzichino di sale. Disponete le verdure in un largo piatto e conditele con la salsa tiepida e con una macinata di pepe fresco.',2247);
INSERT INTO "ricette" VALUES (27238,'Verdure Profumate','Contorno','Carote',4,' -','4 Carote,
4 Zucchine,
2 Cespi Insalata Belga (indivia),
40 G Burro,
Sale,
1/2 Limone (succo),
1 Arancia (succo)','Pulite le verdure e tagliatele a julienne (bastoncini molto sottili). Sciogliete il burro in padella, aggiungete le verdure, aggiustate di sale e fate cuocete a fiamma vivace per pochi minuti. Aggiungete il succo degli agrumi, lasciate insaporire per un paio di minuti e servite.',570);
INSERT INTO "ricette" VALUES (27239,'Verdure Ripiene','Contorno','Cipolla',4,' -','Per Il Ripieno:,
250 G Riso Giallo,
750 G Cipolla Tritata Finemente,
250 G Olio D''oliva,
25 G Pinoli,
25 G Uvetta Sultanina Nera,
1 Cucchiaino Sale,
1 Cucchiaino Zucchero,
250 G Acqua Bollente,
1/2 Rametto Prezzemolo,
1/2 Rametto Menta,
1/2 Rametto Finocchio,
Per Le Verdure:,
16 Peperoni Piccoli,
4 Pomodori Piccoli,
2 Tazzine Olio D''oliva,
1/2 Cucchiaino Sale,
1/2 Cucchiaino Zucchero,
1 Bicchiere Acqua','Per il ripieno: soffriggere le cipolle e gettarvi riso e pinoli, rimescolando continuamente a fuoco medio finché il riso sia indorato. Aggiungere sale, zucchero, uvetta e mescolare; aggiungere l''acqua bollente e mescolare, coprire e cuocere a fuoco dolce per 1/4 d''ora. Aggiungere gli odori, mescolare e lasciare coperto a raffreddare. Per le verdure: pulire l''interno dei peperoni svuotandoli dal picciolo, riempirli del ripieno e chiuderli con 1/4 di pomodoro; metterli in una casseruola, aggiungere l''acqua, l''olio, il sale, lo zucchero e cuocere a fuoco dolce finché l''acqua non sia evaporata (circa 45 minuti).',4608);
INSERT INTO "ricette" VALUES (27240,'Verdure Ripiene (2)','Contorno','Cipolle',4,' -','12 Cipolle Piccole,
12 Pomodori,
80 G Pangrattato,
4 Cucchiai Olio D''oliva,
120 G Tonno Sott''olio,
30 G Olive Snocciolate,
40 G Formaggio Grana Grattugiato,
150 G Maionese,
2 Cucchiai Pesto,
Prezzemolo,
1 Spicchio Aglio,
Sale','Lessate le cipolle sbucciate in acqua salata per 15 minuti; levate la calotta ai pomodori e togliete parte della polpa interna a entrambe le verdure. Scaldate il forno a 200 gradi. Frullate la polpa tolta con le olive, un ciuffo di prezzemolo, il tonno, sale e uno spicchio d''aglio, unite al composto il pangrattato tostato in metà dell''olio e il grana. Riempite con il composto i pomodori e le cipolle, disponeteli in una pirofila con l''olio rimasto e cuoceteli in forno per 25 minuti. Lasciate raffreddare e coprite. Le verdure si conservano per 24 ore.',3955);
INSERT INTO "ricette" VALUES (27241,'Verdure Ripiene (3)','Contorno','Zucchine',6,'Preparazione: 20 minuti. Cottura: 50 minuti.','4 Zucchine,
2 Cipolle Bionde,
20 G Pinoli,
10 G Funghi Secchi,
30 G Farina,
30 Cl Latte,
30 G Formaggio Parmigiano Grattugiato,
2 Rametti Maggiorana Fresca,
1 Cucchiaio Vino Bianco,
40 G Burro,
Olio D''oliva Extra-vergine,
1 Pizzico Noce Moscata,
Sale','Sbucciate le cipolle e cuocetele per 15 minuti in abbondante acqua. Scolatele e lasciatele intiepidire. Spuntate le zucchine, cuocetele in acqua bollente salata per 5 minuti, scolatele e fatele raffreddare. Tagliate le cipolle a metà (in orizzontale) e togliete le foglie centrali: lasciatene solo 2-3 per formare una coppetta. Tritate le foglie scartate e tenetele da parte. Dividete le zucchine per il lungo e, con uno scavino o un cucchiaino, prelevate il centro e tritatelo. Scaldate in un padellino un cucchiaio di olio e unite i pinoli e la polpa tritata delle zucchine. Fate insaporire per 2-3 minuti, salate, unite la maggiorana. Poi mescolate e spegnete. Ammorbidite i funghi in acqua tiepida, scolateli, strizzateli, tritateli e cuoceteli per 5 minuti con un cucchiaio di olio, la cipolla tritata, sale e il vino bianco. Preparate la besciamella. Fondete 30 g di burro in una casseruola, versate la farina in una sola volta e tostatela a fiamma bassissima per 2-3 secondi. Unite a filo il latte tiepido e mescolate con una frusta. Cuocete per 5-6 minuti a fiamma bassa e girando spesso. Salate e aggiungete un pizzico di noce moscata e 20 g di parmigiano. Mescolate metà besciamella al composto di zucchine e metà a quello di funghi. Riempite le cipolle con il primo e le zucchine con il secondo. Mettetele in una teglia unta, cospargetele con il parmigiano e il burro a dadini e cuocetele in forno caldo a 200 gradi per 25 minuti.',1701);
INSERT INTO "ricette" VALUES (27242,'Verdure Ripiene (4)','Contorno','Granulare Di Soia',4,' -','120 G Granulare Di Soia,
Prezzemolo,
2 Peperoni,
2 Zucchine,
2 Cipolle,
4 Funghi Champignon Piuttosto Grandi,
4 Foglie Verza,
1 Spicchio Aglio,
1 Uovo (facoltativo),
1 Cucchiaino Miso,
Sale,
Olio D''oliva Extra-vergine','Cuocete per circa 15 minuti il granulare di soia in abbondante acqua bollente salata, scolatelo, strizzatelo con le mani. Preparate le verdure: tagliate a metà i peperoni privandoli dei filamenti interni, le zucchine svuotandole dei semi aiutandovi con un cucchiaino, le cipolle svuotandole della polpa interna. Togliete il gambo ai funghi e scavateli leggermente. Scolate per 2/3 minuti. le foglie di verza. In una padella, soffriggete la polpa interna delle cipolle finemente affettata in 1 cucchiaio di olio,unite i gambi dei funghi tagliati a pezzettini aggiungete il granulare, fatelo insaporire bene per 5/6 minuti. proseguite la cottura per circa 10 minuti facendo attenzione che la preparazione risulti ben asciutta. Ponete in una terrina il granulare raffreddato, l''aglio ed il prezzemolo tritati, l''uovo e lavorate bene gli ingredienti regolando di sale. Riempite le verdure con il composto ottenuto, formate con le foglie di verza dei fagottini che legherete con dello spago da cucina e ponetele in una pirofila precedentemente unta. Cuocete in forno già caldo a 180 gradi per circa 30/40 minuti irrorando durante la cottura con una salsa ottenuta sciogliendo 1 cucchiaino di miso in 3/4 di bicchiere di acqua bollente. Servite su un piatto da portata con purè di patate.',1169);
INSERT INTO "ricette" VALUES (27243,'Verdure Ripiene Al Microonde','Contorno','Zucchine',4,'Preparazione: 60 minuti. Cottura: 20 minuti.','4 Melanzane,
4 Zucchine,
4 Peperoni,
4 Pomodori,
4 Cucchiai Formaggio Parmigiano Grattugiato,
2 Panini All''olio,
2 Uova,
400 G Arrosto Di Manzo (o Arrosto Di Vitello),
10 Cucchiai Pangrattato,
1 Mazzetto Prezzemolo,
1 Ciuffo Mentuccia,
1 Ciuffo Erba Cipollina,
1 Spicchio Aglio,
1 Rametto Basilico,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lavate le melanzane, le zucchine e i peperoni, privateli delle estremità. Mettete da parte 2 zucchine e tagliate tutte le altre verdure a metà nel senso della lunghezza. Incidete la polpa delle melanzane con un coltellino sottile, salate abbondantemente e lasciate riposare 30 minuti affinché perdano l''acqua di vegetazione. Private i peperoni dei semi e dei fili e salateli. Lavate, mondate e tagliate a metà i pomodori. Con un cucchiaio togliete i semi. Infine salateli internamente e lasciateli scolare capovolti per 30 minuti. Sciacquate e asciugate le melanzane sistematele con le zucchine in una pirofila e condite con 1 cucchiaio d''olio versato a filo. Passate le verdure nel forno per 2'' alla massima potenza. Nel frattempo preparate il ripieno per le melanzane e le zucchine: lavate il prezzemolo e la mentuccia e tritateli finemente insieme con la carne. Togliete la mollica dai panini. sbriciolatela grossolanamente e mettetela in una tazza. Coprite con acqua tiepida, lasciate ammorbidire per 2'' poi strizzatela bene. Scolate le verdure, scavatene la polpa e mettetela in una terrina. Aggiungete le uova, la carne tritata e aromatizzata con le erbe e il Parmigiano grattugiato. Regolate di sale e di pepe e mescolate bene fino a ottenere un composto omogeneo e farcite con questo i fondi di melanzane e di zucchine. Trasferitele su una pirofila e preparate il ripieno per le altre verdure. Tagliate a rondelle sottili le zucchine, trasferitele in una pirofila, regolate di sale, di pepe, condite con 2 cucchiai d''olio e passatele in forno per 5 minuti alla massima potenza. Nel frattempo lavate bene il basilico, la mentuccia e l''erba cipollina e tritatele tutte insieme finemente. In una ciotola riunite le erbe tritate, il pangrattato e i spicchio d''aglio schiacciato con l''apposito attrezzo. Mescolate con un cucchiaio di legno e legate il composto versando a filo l''olio necessario. Mescolate bene e, quando sarà ben omogeneo, farcite i pomodori. Distribuite le zucchine a rondelle nei peperoni. Allineate tutte le verdure ripiene in una pirofila e grigliatele per 5 minuti Servite subito.',3368);
INSERT INTO "ricette" VALUES (27244,'Verdure Ripiene Al Tofu','Contorno','Tofu',4,' -','Peperoni,
Zucchine,
Funghi Champignon,
Alcune Foglie Verza,
Cipolle,
Poco Olio D''oliva Extra-vergine,
Poco Vino Bianco,
1 Panetto Tofu Fresco,
Poco Sale Marino Integrale,
Peperoncino,
Basilico,
1 Cucchiaino Miso','Lavare e preparare per essere riempite, i peperoni, le zucchine (tagliate per la lunghezza e svuotate) i funghi champignon (togliere il gambo e svuotare leggermente la cappella), le foglie di verza (scottate in acqua bollente), le cipolle (tagliare la calotta e svuotare lasciando qualche strato esterno). In un tegame rosolare con poco olio extra-vergine d''oliva la parte interna tolta dalle cipolle e dai funghi, bagnare con poco vino bianco, far ritirare bene. Una volta raffreddate, unire alle verdure un panetto di tofu fresco sbriciolato, poco sale marino integrale, a piacere del peperoncino e del basilico. Riempire le verdure pressando bene il composto, con le foglie di verza, formare dei pacchettini che legherete con filo da cucina. Porre in una teglia unta con olio ed infornare a circa 180 gradi per circa 40 minuti. Preparare in una ciotola una salsina sciogliendo del miso (1 cucchiaino) con un po'' d''acqua calda e con questa, bagnare le verdure ripetutamente mentre cuociono.',680);
INSERT INTO "ricette" VALUES (27245,'Verdure Ripiene All''ortolana','Antipasto','Cipolle',8,'Preparazione: 70 minuti.','4 Cipolle Bianche,
2 Zucchine Grandi,
2 Peperoni,
4 Pomodori Piccoli Maturi,
Per Il Ripieno:,
400 G Riso,
1/2 Peperone Rosso,
1 Zucchina,
1 Carota,
4 Cucchiai Piselli Sgusciati,
4 Cucchiai Olio D''oliva Extra-vergine,
1 Cipollina,
40 G Formaggio Parmigiano Grattugiato,
50 G Burro,
Brodo,
Pepe','Private i pomodori della calotta e dei semi, poi salateli internamente e poneteli capovolti su una gratella per 30 minuti in modo che perdano l''acqua di vegetazione. Nel frattempo, lessate al dente in acqua bollente salata le cipolle, le zucchine e i peperoni (questi ultimi tagliati a metà e privati dei semi). Preparate il ripieno. Fate rosolare la cipollina tritata nell''olio caldo, poi unite i piselli e la zucchina, il peperone e la carota tagliati a dadini e lasciate cuocere per qualche istante. Aggiungete quindi il riso, lasciatelo tostare per un minuto, poi portatelo a cottura bagnando man mano col brodo bollente. Completate con 40 g di burro, pepe a piacere e il formaggio e lasciate intiepidire. Dividete quindi in 2 parti le zucchine, poi tagliatele a metà orizzontalmente e privatele della polpa con i semi. Tagliate a metà anche le cipolle e scavatele in modo da formare delle scodelline. Riempite le verdure col ripieno, sistemandole man mano in una pirofila unta col burro rimasto e cuocetele in forno caldo a 200 gradi per circa 15 minuti.',3081);
INSERT INTO "ricette" VALUES (27246,'Verdure Ripiene Alla Provenzale','Contorno','Cipolle',4,'Luogo: Francia. Luogo: Provenza. Preparazione: 60 minuti.','2 Melanzane Piccole,
2 Zucchine,
4 Pomodori,
4 Cipolle,
3 Cucchiai Olio D''oliva,
30 G Burro,
Sale,
Per La Farcia:,
150 G Vitello Tritato,
50 G Pancetta Affumicata,
3 Cucchiai Riso,
1 Cipolla,
2 Spicchi Aglio,
50 G Formaggio Parmigiano Grattugiato,
2 Cucchiai Erba Cipollina Tritata,
2 Cucchiai Prezzemolo Tritato,
1 Uovo,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Fate bollire dell''acqua salata in una pentola. Gettatevi il riso e fate cuocere per quindici minuti. Fate bollire dell''acqua salata in un tegame. Tagliate le estremità delle zucchine. Sbucciate le cipolle. Mettete melanzane, zucchine e cipolle nell''acqua bollente e lasciate cuocere per tre minuti. Sgocciolate e fate intiepidire. Lavate i pomodori. Ritagliate una calottina nella parte superiore dei pomodori e delle cipolle. Tagliate a metà nel senso della lunghezza melanzane e zucchine, senza togliere i peduncoli delle melanzane. Vuotate le verdure. Tritate la polpa levata dalle zucchine, pomodori e melanzane. Preparate il ripieno: tagliate la pancetta a dadini. Sbucciate la cipolla e tritatela. Pelate l''aglio e schiacciatelo. Rompete l''uovo in una ciotola e sbattetelo. Sgocciolate il riso e passatelo sotto l''acqua fredda. Mettetelo nella ciotola assieme all''aglio, all''erba cipollina, al prezzemolo e alla polpa delle verdure. Fate scaldare l''olio in una padella e rosolatevi vitello, pancetta e cipolla, schiacciando la carne con la forchetta. Aggiungetevi poi il contenuto della ciotola, salate, pepate e rosolate il tutto per qualche minuto mescolando sempre. Levate dal fuoco, aggiungete il parmigiano e mescolate ancora una volta. Fate scaldare il forno a 200 gradi (termostato 6). Farcite le verdure con il ripieno. Versate l''olio in un grande piatto da forno e deponetevi le verdure ripiene. Posate su ognuna un pezzettino di burro. Infornate e lasciate cuocere per trenta minuti. Servite caldo.',4032);
INSERT INTO "ricette" VALUES (27247,'Verdure Ripiene Di Carne','Carne','Carne Macinata',4,'Luogo: Turchia.','Per Il Ripieno:,
500 G Carne Macinata Mista,
150 G Riso Giallo,
5 Cipolle Tritate Fini,
1/2 Cucchiaio Sale,
Poco Pepe,
1/2 Mazzetto Erbe (finocchietto, Prezzemolo, Menta),
Per Le Verdure:,
16 Peperoni Piccoli,
4 Pomodori,
1 Cucchiaio Burro','Per il ripieno: salare le cipolle e lasciarle finché non diventano trasparenti, lavarle e ripetere l''operazione; mescolare tutti gli ingredienti. Per le verdure: lavare e pulire i peperoni all''interno tagliandone la coda. Riempirli di ripieno e chiudere il buco inserendo sotto la pelle 1/4 di pomodoro; metterli in una teglia, aggiungere 3 bicchieri d''acqua, 1 cucchiaio di burro, coprire e far cuocere per 1 ora a fuoco basso.',1754);
INSERT INTO "ricette" VALUES (27248,'Verdure Saltate Alla Cinese','Contorno','Soia',4,'Luogo: Cina. Preparazione: 15 minuti. Cottura: da 10 a 15 minuti.','500 G Verdure Varie,
2 Cucchiai Olio D''oliva,
1 Cucchiaio Soia,
1 Cucchiaino Grappa Di Riso (o Sherry),
1/4 Cucchiaino Sale','Mondate e lavate le verdure e tagliatele a dadini, a listarelle o a rondelle. Portate a ebollizione una grande pentola di acqua salata. Versatevi le verdure a poco a poco, incominciando da quelle che necessitano di una cottura più lunga (ci vorranno da cinque a sei minuti per le carote, tre minuti per le zucchine, due minuti per il sedano, ecc.). Sgocciolatele accuratamente. Scaldate l''olio in un wok o in una padella dal fondo spesso. Fatevi saltare le verdure per un minuto o due. Aggiungete il sale e 15 cl di acqua. prolungate la cottura per altri due o tre minuti. Versate la soia e il liquore nella padella e mescolate con una spatola di legno. Lasciate cuocere un minuto e servite immediatamente.',590);
INSERT INTO "ricette" VALUES (27249,'Verdure Saltate Alla Thailandese','Contorno','Carote',6,'Luogo: Thailandia. Preparazione e cottura: 45 minuti.','125 G Carote,
125 G Fagiolini Fini,
125 G Fagiolini Mangiatutto,
125 G Mazzetti Di Broccoli,
1 Peperone Rosso,
1 Peperone Verde,
4 Coste Sedano,
125 G Funghi Champignon,
4 Cucchiai Olio D''arachidi,
2 Cucchiai Salsa Di Soia Chiara,
1 Cucchiaio Succo Di Limone,
6 Gocce Tabasco,
2 Cucchiaini Zucchero','Grattate le carote, lavatele e tagliatele a rondelle sottili. Mondate i fagiolini, lavateli e tagliateli a pezzi di 5 cm. Mondate i fagiolini mangiatutto e apriteli in due, tagliateli a pezzi. Lavate delicatamente i mazzetti di broccoli. Lavate i peperoni, asciugateli, tagliateli, eliminate i semi e i filamenti bianchi, tagliateli a listarelle fini. Private dei fili le coste di sedano, lavatele e tagliatele in diagonale a pezzi di 1,5 cm. Eliminate i gambi degli champignon, lavate e asciugate le teste. Mettete le carote, i fagiolini e i fagiolini mangiatutto in una grande casseruola, copriteli di acqua fredda, portate a ebollizione e lasciate bollire per tre minuti. Togliete le verdure dalla casseruola con una schiumarola, conservate l''acqua di cottura. Passate le verdure sotto l''acqua fredda e sgocciolate. Mettete nella stessa acqua i broccoli, i peperoni e il sedano, portate a ebollizione e lasciate bollire per due minuti. Sgocciolate le verdure, passatele sotto l''acqua fredda e sgocciolatele di nuovo. Scaldate l''olio a fuoco vivace in un wok o in una padella larga, buttatevi tutte le verdure e gli champignon. Fate saltare a fuoco vivace, mescolando, per un minuto o due. Aggiungete la salsa di soia, il succo di limone, il tabasco e lo zucchero. Mescolate, lasciate cuocere per un minuto e servite immediatamente.',1171);
INSERT INTO "ricette" VALUES (27250,'Verdure Stufate All''uva','Contorno','Verdure Miste',6,' -','1200 G Verdure Miste Di Stagione,
Sale,
Pepe,
300 G Uva Bianca,
2 Mele,
1 Arancia,
1 Cuore Sedano,
1 Cucchiaio Prezzemolo Tritato,
Maggiorana,
1 Foglia Alloro,
4 Cucchiai Olio D''oliva Extra-vergine','Mondate e lavate tutte le verdure poi tagliatele a tocchetti e mettetele in un tegame di coccio con il prezzemolo tritato, qualche fogliolina di maggiorana e l''alloro. Pelate a vivo gli spicchi d''arancia, liberandoli dagli eventuali semi, sbucciate e tagliate a spicchi le mele, pelate gli acini d''uva e togliete loro i vinaccioli poi unite tutta la frutta alla verdura compreso il sedano a rondelle. Condite con sale, pepe e olio. Coprite il recipiente con un foglio d''alluminio e cuocete in forno a 200 gradi per circa 1 ora. Durante la cottura mescolate una volta la preparazione aggiungendo, se risultasse troppo asciutta, poca acqua bollente. Servite sia caldo sia freddo.',1345);
INSERT INTO "ricette" VALUES (27251,'Verdurine In Sfoglia Di Manzo Con Topinambur E Vino Rosso','Carne','Manzo',4,' -','4 Topinambur,
200 G Manzo A Fettine,
20 Cl Vino Rosso,
1 Rametto Rosmarino,
1 Spicchio Aglio,
1 Costa Sedano,
1 Carota,
Erbe Aromatiche Miste,
Olio D''oliva,
Sale,
Pepe','Pulire, sbucciare ed affettare sottile i topinambur; rosolarli in padella con olio sovrapponendoli a mucchietti come per un roesti di patate. Tagliare a cubetti altri due topinambur pelati e puliti e cuocerli in padella con poco olio, sale, pepe, sedano e carota a dadini; farcire col composto delle fettine di manzo battute sottili e disposte a raggiera in uno stampo; chiudere e rosolare in padella con poco olio da tutti i lati, aromatizzare con erbe aromatiche miste. Rosolare in un pentolino con olio, aglio e rosmarino gli scarti della carne, sfumare con vino rosso e ridurre a cottura; filtrare. Servire la sfoglia di manzo con verdure sopra il roesti di topinambur e nappare con la riduzione di vino rosso.',1236);
INSERT INTO "ricette" VALUES (27252,'Vermicelli','Primo','Pangrattato',6,' -','300 G Farina,
200 G Pangrattato Finissimo,
3 Uova,
50 G Formaggio Parmigiano Grattugiato,
1 Pizzico Sale,
Brodo','Mescolate farina e pagrattato, disponete a fontana e, al centro, sgusciatevi le uova, poi cospargete di formaggio parmigiano e aggiungete un pizzico di sale. Impastate, dilute con un pochino di acqua calda, fate una palla e lasciate riposare almeno mezz''ora. Suddividetela in piccoli pezzi, schiacciateli nel passapatate in modo che dai buchini fuoriescano sottili vermicelli. Portate il brodo a bollore e cuocetevi la pastina per circa 6/7 minuti.',2172);
INSERT INTO "ricette" VALUES (27253,'Vermicelli Ai Carciofi','Primo','Carciofi',4,' -','400 G Pasta Tipo Vermicelli,
4 Carciofi,
4 Filetti D''acciughe,
2 Spicchi Aglio,
1 Cucchiaio Capperi,
100 G Olive Nere Snocciolate,
300 G Mozzarella A Dadini,
1 Spolveratina Prezzemolo Tritato,
Olio D''oliva,
Sale','Pulite con cura i carciofi, eliminando le foglie più dure e le parti legnose. Subito dopo, tagliateli a spicchi ed immergeteli in acqua e limone per circa 30 minuti. Successivamente, sciacquateli più volte sotto l''acqua corrente e lasciateli scolare per circa 10 minuti. A parte, in una padella antiaderente, fate riscaldare l''olio e rosolate l''aglio. Aggiungete i filetti d''acciuga e lasciateli sciogliere a fiamma bassa per pochi minuti. Dopodichè, versate i carciofi e cuoceteli per circa 10 minuti mescolandoli di tanto in tanto. In seguito, unite i capperi e le olive e continuate la cottura per altri 20 minuti. Nel frattempo, cuocete i vermicelli in acqua salata, scolateli al dente e saltateli in padella. Aggiungete la mozzarella a dadini e mescolate energicamente il tutto amalgamando bene gli ingredienti. Infine, serviteli subito caldi e filanti con una spolveratina di prezzemolo tritato.',3131);
INSERT INTO "ricette" VALUES (27254,'Vermicelli Ai Frutti Di Mare','Primo','Gamberetti',4,' -','280 G Pasta Tipo Vermicelli,
400 G Frutti Di Mare (cozze, Vongole, Telline),
4 Scampi Piccoli,
150 G Nasello (o Anguilla),
150 G Gamberetti,
2 Spicchi Aglio,
1 Cucchiaio Prezzemolo Tritato,
4 Cucchiai Olio D''oliva Extra-vergine,
150 G Pomodori Perini Maturi,
Sale,
1 Peperoncino','Mettete a bagno le vongole per liberarle dall''eventuale sabbia e raschiate le cozze. Riunite i frutti di mare in una casseruola, mettete il coperchio e cuocete a fiamma vivace per alcuni minuti, in modo che il calore faccia aprire le conchiglie. Estraete i molluschi e gettate le conchiglie. Versate in una padella l''olio, scaldatelo, unitevi i due spicchi di aglio tritati, il peperoncino, i frutti di mare e il nasello a pezzetti. Fate insaporire per qualche istante a fiamma dolce, poi unite gli scampi e i gamberetti lavati e sgusciati. Salate e aromatizzate con il prezzemolo fresco tritato. Aggiungete i pomodori privati dei semi e tagliati a dadini. Mettete il coperchio e fate cuocere a fuoco basso per circa 10 minuti, mescolando di tanto in tanto. Nel frattempo cuocete i vermicelli in abbondante acqua bollente e salata. Scolateli al dente, metteteli nella padella contenente i frutti di mare, mescolate e servite.',2577);
INSERT INTO "ricette" VALUES (27255,'Vermicelli Ai Funghi','Primo','Funghi Cardoncelli',4,' -','400 G Pasta Tipo Vermicelli,
400 G Funghi Cardoncelli,
2 Spicchi Aglio,
1/2 Cipolla,
Olio D''oliva,
Brandy,
Sale,
Peperoncino In Polvere,
Prezzemolo Tritato','In un recipiente mettete a bagno i funghi, precedentemente privati delle parti meno tenere, sciacquateli abbondantemente sotto il gettito dell''acqua corrente e quando saranno privi di terra, lasciateli scolare per qualche minuto. Nel frattempo, in una padella capiente meglio se antiaderente, fate riscaldare abbondante olio e dorare aglio e cipolla tagliati a fettine sottili sottili precedentemente privati della buccia, sciacquati e asciugati con della carta assorbente. Successivamente, aggiungete i funghi tagliati a pezzetti e mescolateli servendovi di un cucchiaio di legno. Coprite la padella con un coperchio o con della carta alluminio e lasciate cuocere per i primi istanti. Subito dopo scoprite e insaporite il tutto con del sale fino, peperoncino in polvere e mescolate. A metà cottura, aumentate la fiamma e irrorate il tutto con il brandy che lascerete evaporare e addensare per qualche minuto e terminate la cottura. Scaldate i vermicelli in acqua salata, scolateli al dente e versateli nella padella con i funghi. Aggiungete un trito di prezzemolo, mescolate velocemente sulla fiamma e serviteli caldi.',2420);
INSERT INTO "ricette" VALUES (27256,'Vermicelli Ai Peperoni','Primo','Peperoni',4,' -','1 Peperone Corno Di Bue Giallo,
1 Peperone Corno Di Bue Rosso,
50 G Olive Di Gaeta,
1 Scalogno,
Basilico Riccio,
100 G Guanciale Di Maiale,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Nettare i peperoni, lavarli e tagliarli a quadrotti. Farli rosolare nell''olio con lo scalogno e il guanciale a dadini, salare e pepare. Lessare i vermicelli al dente, scolarli e mantecarli nell''intingolo di peperoni. Rifinire con il basilico.',1434);
INSERT INTO "ricette" VALUES (27257,'Vermicelli Ai Porri','Primo','Porri',4,' -','400 G Pasta Tipo Vermicelli,
4 Porri,
1 Pomodoro,
1 Cucchiaio Tamari (salsa A Base Di Soia Di Origine Orientale),
Poco Olio D''oliva Extra-vergine,
Sale','Pulite accuratamente i porri privandoli delle estremità verdi più legnose e tagliateli quindi a lamelle dello spessore di 1 cm. Saltateli poi con poco olio e stufateli per una decina di minuti a fuoco basso e tegame coperto. Nel frattempo lavate e tagliate a pezzi piuttosto grossolani il pomodoro e aggiungetelo ai porri. Lasciate cuocere a fuoco lento per 20 minuti dopo aver aggiunto un bicchiere di acqua calda, il tamari e un po'' di sale. Cuocete al pasta, scolatela al dente, conditela con il sugo ben caldo e portatela in tavola.',1887);
INSERT INTO "ricette" VALUES (27258,'Vermicelli Al Lardo','Primo','Lardo',4,'Luogo: Calabria.','400 G Pasta Tipo Vermicelli,
150 G Lardo,
5 Cl Olio D''oliva Extra-vergine,
3 Spicchi Aglio,
1 Peperoncino Rosso Piccante,
Sale,
1 Cucchiaio Prezzemolo Tritato','Tritate il più finemente possibile il lardo e soffriggetelo in un tegame con l''olio, l''aglio e il peperoncino in pezzetti, mentre i vermicelli cuociono in acqua leggermente salata. Sgocciolate al dente i vermicelli, versatevi sopra il soffritto e il prezzemolo tritato e rigirate prima di servire.',3157);
INSERT INTO "ricette" VALUES (27259,'Vermicelli Al Tartufo Nero','Primo','Tartufo Nero',4,' -','1 Tartufo Nero Umbro,
350 G Pasta Tipo Vermicelli Trafilati A Bronzo,
Aglio,
1 Acciuga,
Prezzemolo,
2 Pomodori Pelati,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Far imbiondire nell''olio 2 spicchi d''aglio schiacciato e unirvi l''acciuga dissalata e spinata, stemperandola nell''olio. Aggiungere la polpa triturata del pomodori e far insaporire per pochi minuti. Lessare al dente i vermicelli, scolarli e mantecarli nell''intingolo. Rifinire il piatto tagliandovi a lamelle sottilissime il tartufo ben raschiato e cospargendo di prezzemolo tritato.',1984);
INSERT INTO "ricette" VALUES (27260,'Vermicelli Al Tonno','Primo','Tonno Sott''olio',4,' -','400 G Pasta Tipo Vermicelli,
350 G Tonno Sott''olio,
2 Spicchi Aglio,
Peperoncino Tritato,
Prezzemolo,
Abbondante Olio D''oliva,
Sale','In una padella antiaderente fate riscaldare abbondante olio e aggiungete l''aglio che avrete precedentemente pulito, sciacquato e asciugato con della carta assorbente e il peperoncino. Successivamente, dopo aver fatto saltare in padella i primi ingredienti aggiungete il tonno in parte sgocciolato, il sale e lasciate cuocere per circa 10 minuti a fiamma bassa. Nel frattempo, scaldate i vermicelli in acqua salata e scolateli al dente. Versateli nella padella e mescolateli energicamente e velocemente a fiamma alta per qualche minuto. In ultimo, tritate il prezzemolo precedentemente lavato e asciugato con della carta assorbente e spolverizzate il tutto. Serviteli subito caldi. Accorgimento: dopo la cottura eliminate l''aglio dalla padella.',3185);
INSERT INTO "ricette" VALUES (27261,'Vermicelli Alla Carbonara','Primo','Pancetta Affumicata',4,' -','400 G Pasta Tipo Vermicelli,
100 G Pancetta Affumicata,
5 Cucchiai Formaggio Parmigiano,
4 Uova,
Prezzemolo,
30 G Burro,
2 Cucchiai Olio D''oliva Extra-vergine,
Sale,
1 Pizzico Pepe Nero','Battete le uova in una terrina e aggiungete 1 pizzico di pepe nero e parmigiano. Fate rosolate la pancetta affumicata precedentemente tagliata a quadratini, con l''olio d''oliva extra-vergine e il burro. Fate cuocere e scolate i vermicelli, versateli nella terrina con le uova e mescolate velocemente. Versate sopra la pancetta con il suo grasso di cottura. Cospargete di prezzemolo e servite immediatamente.',3273);
INSERT INTO "ricette" VALUES (27262,'Vermicelli Alla Crema Di Broccoletti','Primo','Broccoletti',4,' -','400 G Pasta Tipo Vermicelli,
500 G Broccoletti,
100 G Formaggio Pecorino,
1/2 Bicchiere Olio D''oliva,
1 Spicchio Aglio,
Sale,
Pepe Nero','Mondare i broccoletti, dividere le cime e lavarli. Metterli a cuocere per 15 minuti in acqua bollente, salare, quindi scolarli e passarli al passaverdure. Intanto, cuocere la pasta. Scaldare 1/2 bicchiere scarso d''olio d''oliva con 1 spicchio di aglio sminuzzato, unire il passato di broccoletti e far insaporire per 10 minuti. Aggiungere il pecorino grattugiato e continuare a mescolare abbassando la fiamma al minimo. Scolare i vermicelli al dente, versarli dentro la casseruola con il sugo, unire un po'' di pepe e mescolare bene.',2504);
INSERT INTO "ricette" VALUES (27263,'Vermicelli Alla Ghiottona','Primo','Formaggio Emmenthal',4,' -','240 G Pasta Tipo Vermicelli,
100 G Prosciutto Cotto (fette Da 100 G),
80 G Formaggio Emmenthal,
4 Cucchiai Formaggio Parmigiano,
1/2 Bicchiere Panna Da Cucina,
40 G Burro,
1/2 Tartufo Nero,
Sale,
Pepe','Cominciate col far lessare la pasta, intanto, mettete il burro in una casseruola, grande abbastanza da contenere poi anche la pasta, e fate scaldare; prima che il burro arrivi a friggere, unite il prosciutto cotto tagliato a dadini e lasciatelo rosolare a calore moderato per una decina di minuti. Subito dopo, tagliate a dadini anche l''emmenthal e tenetelo da parte. Quando la pasta sarà cotta al dente (ci vorranno circa 10-12 minuti) scolatela e sgocciolatela bene; mettetela in una casseruola con il prosciutto cotto e lasciatela insaporire per un paio di minuti, rigirandola senza interruzione perché non si attacchi al fondo. Dopodichè, bagnatela con mezzo bicchiere di panna, unite anche l''emmenthal e lasciate sul fuoco il tutto quel tanto che basta per ammorbidire il formaggio. Poco prima di togliere dal fuoco, cospargete la pasta di parmigiano e anche il prezzemolo, quindi trasferite il tutto in una zuppiera già calda, cospargete con il tartufo grattugiato e servite subito.',2244);
INSERT INTO "ricette" VALUES (27264,'Vermicelli Alla Maniera Di San Martino Di Finita','Primo','Guanciale Di Maiale',4,'Luogo: Calabria.','400 G Pasta Tipo Vermicelli,
150 G Guanciale Di Maiale,
2 Spicchi Aglio,
1 Cucchiaio Peperoncino Rosso Piccante Macinato,
5 Cl Olio D''oliva Extra-vergine,
70 G Formaggio Pecorino Grattugiato,
Sale','Tagliate il guanciale in minuscoli dadini e mettetelo a rosolare in un tegamino con l''aglio tagliato a pezzettini. Lessate i vermicelli in acqua leggermente salata, sgocciolateli al dente, conditeli con il soffrittino di guanciale e cospargeteli di pecorino grattugiato.',2677);
INSERT INTO "ricette" VALUES (27265,'Vermicelli Alla Posillipo','Primo','Cozze',6,' -','600 G Pasta Tipo Vermicelli,
500 G Cozze,
500 G Vongole,
500 G Gamberi (o Gamberetti),
2 Polipetti (o Calamaretti),
600 G Pomodori Freschi,
150 G Olio D''oliva,
4 Spicchi Aglio,
Abbondante Prezzemolo,
Abbondante Pepe','Preparate un sugo con aglio, olio e pomodoro e quando sarà ad un buon punto versatevi il pesce preventivamente cotto, cioè le vongole e le cozze aperte e sgusciate, i gamberetti o gamberi bolliti e sgusciati, i polipetti tagliati a pezzettini. Salate e pepate; lasciate sul fuoco ancora 5 minuti. Con questo sugo si condiranno i vermicelli scolati al dente; il tutto va guarnito con prezzemolo tritato.',4993);
INSERT INTO "ricette" VALUES (27266,'Vermicelli Alla Posillipo (2)','Primo','Vongole',4,' -','1 Confezione Vongole Surgelate Findus,
4 Cucchiai Olio D''oliva,
2 Spicchi Aglio,
Prezzemolo Tritato,
400 G Pasta Tipo Vermicelli','Dorare l''aglio tagliato a fettine ed unire le vongole con molto prezzemolo tritato. Lessare i vermicelli al dente, scolarli e saltarli in padella con le vongole.',2911);
INSERT INTO "ricette" VALUES (27267,'Vermicelli Alla Puttanesca','Primo','Olive Nere',4,' -','350 G Pasta Tipo Vermicelli,
350 G Pomodori Freschi (o Pomodori Pelati),
2 Spicchi Aglio,
50 G Capperi,
100 G Olive Nere Di Gaeta,
6 Acciughe Sotto Sale,
1 Ciuffo Prezzemolo,
1 Pezzetto Peperoncino Piccante,
10 Cl Olio D''oliva,
Ricotta Salata Stagionata,
Origano,
Sale','Preparate il sugo: in una casseruola fate rosolare nell''olio gli spicchi d''aglio interi. Lavate i capperi per dissalarli; fate lo stesso con le acciughe. Quando l''aglio avrà raggiunto un bel colore bruno, aggiungete nella casseruola i pomodori tagliati a pezzetti, se li usate freschi, o i pelati scolati con cura dal loro liquido di conservazione, i capperi, le olive,il peperoncino,origano. Salate poco e fate cuocere il sugo per una decina di minuti su fuoco vivo. Sarà pronto quando il liquido dei pomodori sarà quasi completamente assorbito e il sugo avrà assunto un aspetto lucente. Nel frattempo mettete sul fuoco una grossa pentola con abbondante acqua. Quando avrà raggiunto l''ebollizione, salatela e unite la pasta.Mescolatela e portatela a cottura, scolatela bene al dente, tenendo da parte qualche cucchiaio d''acqua di cottura,e mettetela in una larga ciotola. Un attimo primo di condire, aggiungete al sugo le acciughe a pezzetti, e abbondante prezzemolo tritato. Rovesciate sulla pasta il sugo: se fosse troppo asciutto,diluitelo con qualche cucchiaio dell''acqua di cottura tenuta da parte, spolverizzate con la ricotta grattugiata e portate a tavola.',2658);
INSERT INTO "ricette" VALUES (27268,'Vermicelli Alla Romana','Primo','Acciughe',4,'Luogo: Lazio. Luogo: Roma.','500 G Pasta Tipo Vermicelli,
5 Acciughe Salate,
80 G Formaggio Pecorino Grattugiato,
80 G Mollica Di Pane,
1/2 Bicchiere Olio D''oliva,
Sale','Pulire le acciughe, lavarle, spezzettarle, metterle in un pentolino con l''olio, unire la mollica di pane sbriciolata, regolare di sale e far insaporire per qualche minuto. Cuocere i vermicelli al dente in abbondante acqua salata, condirli con la salsa preparata e il pecorino e servire.',2920);
INSERT INTO "ricette" VALUES (27269,'Vermicelli Alla Siracusana','Primo','Melanzana',4,'Luogo: Sicilia. Luogo: Siracusa.','500 G Pasta Tipo Vermicelli,
2 Acciughe Sott''olio,
1 Melanzana,
5 Pomodori Maturi,
1 Peperone Giallo,
100 G Olive Nere,
50 G Capperi,
2 Spicchi Aglio,
Alcune Foglie Basilico,
Olio D''oliva,
Sale,
Pepe','Soffriggere l''aglio tritato, aggiungere le acciughe a pezzetti, la melanzana tagliata a tocchetti e i pomodori a sminuzzati. Cuocere per 10 minuti circa e poi aggiungere il peperone tagliato a listarelle, le olive snocciolate, i capperi e alcune foglie di basilico; salare, pepare e cuocere ancora per 20 minuti a fuoco lento. Nel frattempo cuocere gli spaghetti e condirli con la salsa preparata.',2891);
INSERT INTO "ricette" VALUES (27270,'Vermicelli Allo Scoglio','Primo','Cozze',4,' -','400 G Pasta Tipo Vermicelli,
500 G Cozze E Vongole,
200 G Polpa D''aragosta Fresca,
5 Scampi Piccoli,
5 Gamberoni,
500 G Pomodori Sodi Maturi,
1 Cipolla Piccola,
1 Manciata Basilico,
1/2 Bicchiere Vino Bianco Secco,
Alcuni Cucchiai Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Pulite i diversi tipi di pesce: sciacquate le conchiglie e lasciatele a bagno in acqua salata in modo che perdano la sabbia eventualmente chiusa tra le valve; sciacquate i crostacei e non sgusciateli. Fate schiudere cozze e vongole mettendole al fuoco con il vino bianco e, man mano che si aprono, separate i molluschi dal guscio (lasciatene alcune intere per guarnire); a fine operazione filtrate e tenete da parte il liquido rimasto sul fondo della padella. In un tegame capiente fate ammorbidire un trito fine di cipolla in qualche cucchiaio di olio; unite poi i pomodori che avrete pelato tuffandoli in acqua bollente, privati dei semi e tritati grossolanamente. Mettete a cottura nel sugo gli scampi e i gamberoni e, dopo qualche minuto, aggiungete anche la polpa dell''aragosta tagliata a fettine. Bagnate con il liquido di cottura di vongole e cozze, regolate di sale e insaporite con il peperoncino. Dopo 10 minuti unite al sugo anche i molluschi e lasciate insaporire prima di spegnere. Intanto lessate i vermicelli; scolateli bene al dente e spadellateli amalgamandoli con cura ala sugo insieme con una spolverata di basilico tritato.',4780);
INSERT INTO "ricette" VALUES (27271,'Vermicelli Con Fritto Di Zucchine','Primo','Zucchine',4,' -','400 G Pasta Tipo Vermicelli,
2 Zucchine Grandi,
200 G Mozzarella,
Olio D''oliva Extra-vergine,
1 Bicchiere Vino Bianco,
1 Uovo,
Pangrattato,
1 Spicchio Aglio,
Menta Fresca,
Sale,
Pepe','Spuntate le zucchine, lavatele con cura, asciugatele su fogli di carta assorbente e tagliatele a bastoncini. In una padella antiaderente, fate riscaldare l''olio e rosolate l''aglio. Aggiungete le zucchine che cuocerete a fiamma alta per circa 7 minuti. Subito dopo, aggiungete il vino bianco, il sale il pepe e continuate la cottura a fiamma bassa per altri 10 minuti. Infine, unite la menta e mescolate. In un''altra padella friggete la mozzarella tagliata a dadini e impanata 2 volte nel pangrattato. Scolatela su fogli di carta assorbente e tenetela in caldo. Nel frattempo, scottate i vermicelli in acqua salata, scolateli al dente e versateli nella prima padella con le zucchine. Aggiungete anche la mozzarella fritta e mescolate velocemente il tutto. Servite immediatamente.',3138);
INSERT INTO "ricette" VALUES (27272,'Vermicelli Con Gli Alici Freschi','Primo','Acciughe',4,'Luogo: Calabria.','400 G Pasta Tipo Vermicelli,
300 G Acciughe Fresche,
Alcuni Spicchi Aglio,
1 Ciuffetto Prezzemolo,
2 Cucchiai Pangrattato,
2 Cucchiai Formaggio Pecorino Grattugiato,
10 Cl Olio D''oliva Extra-vergine,
Sale,
Pepe Nero,
Per Guarnire:,
Alcune Foglie Prezzemolo','Diliscate le acciughe, lavatele e lasciatele ad asciugare aperte su un foglio di carta paglia. In una padella piuttosto ampia soffriggete l''aglio con l''olio e aggiungetevi il prezzemolo tagliuzzato finemente. Mettete nella padella le acciughe e fate cuocere per tre minuti, mescolando. Togliete dal fuoco e aggiungete i vermicelli che avrete lessato in acqua salata (ben sgocciolati al dente). Spolverate con un miscuglio (precedentemente preparato) di pangrattato, formaggio pecorino e pepe nero appena macinato. Saltate velocemente il tutto sul fuoco e fate rapidamente le porzioni poiché i vermicelli tenderanno ad attaccarsi al fondo. Prima di portare in tavola, guarnire i piatti con foglioline di prezzemolo.',2879);
INSERT INTO "ricette" VALUES (27273,'Vermicelli Con I Funghi','Primo','Funghi',4,'Luogo: Calabria.','400 G Pasta Tipo Vermicelli,
400 G Pomodori Pelati,
400 G Funghi Freschi,
1 Cipolla Media,
80 G Sugna,
1/2 Cucchiaio Prezzemolo Tritato,
1 Peperoncino Piccante,
Sale','Soffriggete con la sugna la cipolla tritata e, appena imbiondita, aggiungete i funghi e i pomodori tagliati a pezzetti, il peperoncino, il prezzemolo e il sale. Lessate i vermicelli in acqua leggermente salata, sgocciolateli al dente e conditeli con la salsa ai funghi.',2253);
INSERT INTO "ricette" VALUES (27274,'Vermicelli Con I Peperoni','Primo','Peperoni',4,'Luogo: Calabria.','400 G Pasta Tipo Vermicelli,
70 G Lardo,
10 Cl Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
4 Peperoni Gialli,
50 G Formaggio Pecorino Grattugiato,
Sale','In una teglia con l''olio mettete a rosolare il lardo tritato, i peperoni tagliati a pezzetti e l''aglio schiacciato. Unite il pecorino grattugiato e fatevelo stemperare. Condite con questo soffritto i vermicelli che avrete lessato in acqua leggermente salata e sgocciolato al dente.',3158);
INSERT INTO "ricette" VALUES (27275,'Vermicelli Con L''agliata','Primo','Aglio',4,' -','350 G Pasta Tipo Vermicelli,
3 Spicchi Aglio,
2 Cucchiai Olio D''oliva Extra-vergine,
Prezzemolo,
Sale Marino,
Peperoncino,
Formaggio Pecorino Romano','Spellare l''aglio, togliere il germoglio interno e pestarlo nel mortaio. Tritare finemente il prezzemolo. Mentre cuoce la pasta scaldare lievemente l''olio col peperoncino in una padella e versarvi l''aglio e il prezzemolo. Lasciar insaporire per 1 minuto. Versarvi la pasta al dente, rigirarla in padella pochi secondi e servirla con pecorino grattugiato.',1960);
INSERT INTO "ricette" VALUES (27276,'Vermicelli Con La Mollica Di Pane','Primo','Pane Raffermo',4,'Luogo: Calabria.','500 G Pasta Tipo Vermicelli,
2 Spicchi Aglio,
4 Acciughe Salate,
1 Peperoncino,
10 Cl Olio D''oliva,
100 G Pane Raffermo,
Sale','In padella fate imbiondire con l''olio gli spicchi d''aglio, eliminateli, mettete il peperoncino in pezzetti e stemperate nell''olio le acciughe dissalate e spinate. Aggiungete la mollica di pane raffermo, sbriciolata con le mani. Lessate in acqua leggermente salata i vermicelli, sgocciolateli al dente, versateli nella padella col soffrittino mescolato bene alla mollica abbrustolita. Mescolate ancora. Servite subito.',2906);
INSERT INTO "ricette" VALUES (27277,'Vermicelli Con Le Acciughe','Primo','Acciughe Salate',4,' -','320 G Pasta Tipo Vermicelli,
100 G Acciughe Salate,
Aglio Fresco,
1 Manciata Uvetta Sultanina,
1 Manciata Pinoli,
1 Mestolo Concentrato Di Pomodoro,
Pangrattato,
Olio D''oliva Extra-vergine,
Sale','Sciogliere in poco olio 2 acciughe, unirvi il pangrattato e rosolarlo. A parte rosolare nell''olio delicatamente le acciughe dissalate con l''aglio finemente affettato; aggiungere l''uvetta ammollata, i pinoli, il concentrato di pomodoro ed un bicchiere d''acqua. Cuocere 30 minuti. Lessare la pasta, scolarla, rigirarla nel''intingolo e rifinirla con il pangrattato.',3018);
INSERT INTO "ricette" VALUES (27278,'Vermicelli Con Le Acciughe Fresche','Primo','Acciughe',4,'Luogo: Calabria.','400 G Pasta Tipo Vermicelli,
300 G Acciughe Fresche,
Alcuni Spicchi Aglio,
1 Ciuffetto Prezzemolo,
2 Cucchiai Pangrattato,
2 Cucchiai Formaggio Pecorino Grattugiato,
10 Cl Olio D''oliva Extra-vergine,
Sale,
Pepe Nero,
Per Guarnire:,
Alcune Foglie Prezzemolo','Diliscate le acciughe, lavatele e lasciatele ad asciugare aperte su un foglio di carta paglia. In una padella piuttosto ampia soffriggete l''aglio con l''olio e aggiungetevi il prezzemolo tagliuzzato finemente. Mettete nella padella le acciughe e fate cuocere per tre minuti, mescolando. Togliete dal fuoco e aggiungete i vermicelli che avrete lessato in acqua salata (ben sgocciolati al dente). Spolverate con un miscuglio (precedentemente preparato) di pangrattato, formaggio pecorino e pepe nero appena macinato. Saltate velocemente il tutto sul fuoco e fate rapidamente le porzioni poiché i vermicelli tenderanno ad attaccarsi al fondo. Prima di portare in tavola, guarnire i piatti con foglioline di prezzemolo',2879);
INSERT INTO "ricette" VALUES (27279,'Vermicelli Con Le Cozze Al Basilico','Primo','Cozze',4,' -','350 G Pasta Tipo Vermicelli,
1000 G Cozze,
1 Cucchiaio Pangrattato,
1 Spicchio Aglio,
16 Foglie Basilico,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Rosolare l''aglio nell''olio; unirvi le cozze ben lavate, coprire e farle aprire, quindi prelevarle e tenere da parte l''acqua di vegetazione. A parte rosolare uno spicchio d''aglio con olio, sale e peperoncino e unirvi il basilico frullato con 3 cucchiai d''olio, una cucchiaiata di pangrattato e le cozze. Lessare la pasta molto al dente e scolarla; terminare la cottura nell''acqua delle cozze, mantecando infine con l''intingolo di basilico e cozze.',2391);
INSERT INTO "ricette" VALUES (27280,'Vermicelli Con Le Vongole','Primo','Vongole',4,' -','350 G Pasta Tipo Vermicelli,
1000 G Vongole,
2 Spicchi Aglio,
Prezzemolo,
1 Bicchiere Olio D''oliva,
Sale,
Pepe','Lavate e spazzolate sotto l''acqua corrente le vongole, poi mettetele in un tegame dove avete scaldato un bicchiere d''olio con gli spicchi d''aglio. Appena il calore dischiude le valve, ritirate il recipiente dal fuoco e con delicatezza estraete i molluschi. Filtrate il liquido di cottura delle vongole, versatelo in un tegame pulito e immergetevi i molluschi. Portate a bollore abbondante acqua leggermente salata, lessatevi i vermicelli, scolateli al dente, passateli nella padella del condimento per 2 minuti sollevando la pasta con due forchette. Regolate sale e pepe, cospargete con il prezzemolo tritato. Passate sul piatto da portata tenuto in caldo e servite. Vini di accompagnamento: Oltrepò Pavese Riesling Italico DOC, Verdicchio Dei Castelli Di Jesi DOC, Fiano Di Avellino DOC.',3290);
INSERT INTO "ricette" VALUES (27281,'Vermicelli Con Melanzane','Primo','Melanzane',4,'Luogo: Sicilia.','400 G Pasta Tipo Vermicelli,
100 G Melanzane,
500 G Pomodori Maturi,
2 Spicchi Aglio,
2 Acciughe Salate,
Olio D''oliva,
Sale,
Pepe,
Formaggio Pecorino Grattugiato','Sbucciate le melanzane, tagliatele a fette e tenetele sotto sale per mezz''ora. Fate rosolare in pentola in mezzo bicchiere d''olio due spicchi d''aglio tritati; mettete pure le acciughe lavate e senza spine e quando saranno sciolte aggiungete i pomodori passati al setaccio. Salate, pepate e lasciate cucinare per 20 minuti. Lavate le melanzane, asciugatele e friggetele in olio caldo; quindi aggiungetele nella salsa e cucinate per altri 15 minuti. Bollite i vermicelli in molta acqua salata, scolateli e uniteli alla salsa di pomodoro e cospargete poi con del pecorino grattugiato.',2546);
INSERT INTO "ricette" VALUES (27282,'Vermicelli Con Melanzane Fritte','Primo','Melanzane',4,'Luogo: Sicilia.','350 G Pasta Tipo Vermicelli Trafilati Al Bronzo,
4 Melanzane,
8 Pomodori San Marzano,
Aglio,
Basilico,
Ricotta Dura,
Olio D''oliva Extra-vergine,
Sale Di Trapani,
1 Presa Pepe','Nettare e lavare le melanzane, tagliarle a dadini e cospargerle con una presa di sale, facendole spurgare. Frattanto con la polpa triturata dei pomodori, aglio, olio e basilico fare un sughetto. Asciugare le melanzane e friggerle nell''olio. Lessare i vermicelli, scolarli, condirli col sugo, servirli e distribuire su ogni piatto le melanzane fritte, la ricotta grattugiata e il basilico.',2332);
INSERT INTO "ricette" VALUES (27283,'Vermicelli Con Salsiccia','Primo','Salsiccia',4,' -','200 G Salsiccia Piccante,
2 Cipollotti,
4 Pomodorini Secchi,
3 Cucchiai Olio D''oliva,
1/2 Bicchierino Vino,
400 G Pasta Tipo Vermicelli,
1 Cuore Insalata Scarola','Tagliare la salsiccia a fettine sottili e far rosolare con la cipolla tritata, i pomodorini a pezzetti e l''olio. Bagnare con vino, far evaporare, unire la scarola a listarelle, salare e cuocere per 5 minuti. Cuocere i vermicelli al dente e condirli con il sugo preparato.',3283);
INSERT INTO "ricette" VALUES (27284,'Vermicelli Con Sugo Di Asparagi','Primo','Asparagi',4,' -','500 G Pasta Tipo Vermicelli,
1 Confezione Punte D''asparagi Findus,
6 Cucchiai Olio D''oliva,
Sale,
Pepe,
80 G Formaggio Parmigiano','Scaldate l''olio in un tegame, unite le punte di asparagi, salate, pepate e fate cuocere a fuoco dolcissimo a recipiente coperto, mescolando ogni tanto. Se occorre, aggiungete acqua calda o brodo. Scolate la pasta al dente, rovesciatela nel tegame degli asparagi insieme al parmigiano; rimestate con delicatezza, lasciando il recipiente sul fuoco basso per qualche istante.',4207);
INSERT INTO "ricette" VALUES (27285,'Vermicelli Del Pirata','Primo','Vongole',4,' -','300 G Pasta Tipo Vermicelli,
100 G Polipetti,
100 G Gamberetti,
300 G Vongole,
400 G Polpa Di Pomodoro,
4 Cucchiai Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
1 Cucchiaio Prezzemolo Tritato,
5 Foglie Basilico,
Sale,
Pepe','È un piatto squisito, ideale per aprire in bellezza un menu a base di pesce; come tutti i piatti al cartoccio, porterà in tavola una ventata di gustosa allegria. La ricetta che vi proponiamo riscuoterà molto successo. Scaldate 2 cucchiai d''olio in un tegame e fatevi dorare i due spicchi di aglio pestati. Non appena avranno preso colore eliminateli e aggiungete tre o quattro grani di pepe pestati grossolanamente con il batticarne e la polpa di pomodoro. Salate e fate cuocere la salsa per un quarto d''ora a fiamma vivace. Nel frattempo, pulite i polipetti, tagliateli a pezzettini e metteteli a cuocere in una padella antiaderente con i restanti 2 cucchiai di olio. Lavate e risciacquate in abbondante acqua le vongole, mettetele in una casseruola, ponetela su fuoco vivace e copritela con un coperchio. Dopo qualche minuto per effetto del calore le conchiglie si apriranno. Scolatele e ponetele insieme ai gamberetti sgusciati e lavati nella padella con i polipetti. Lasciate insaporire il sugo di pesce per 5-6 minuti, poi unite la salsa di pomodoro preparata in precedenza. Mettete a cuocere i vermicelli in abbondante acqua salata bollente; scolateli molto al dente, disponeteli in una zuppiera e conditeli con la salsa Cospargeteli con un trito di prezzemolo e basilico, poi trasferiteli sulla piastra del forno sulla quale avrete già adagiato un grosso foglio di carta speciale. Avvicinate i lembi e richiudete in modo da formare un cartoccio. Infornate a 150 gradi per circa 10 minuti, sino a quando il cartoccio risulterà ben gonfio e dorato.',2205);
INSERT INTO "ricette" VALUES (27286,'Vermicelli In Salsa Abruzzese','Primo','Fiori Di Zucca',2,'Luogo: Abruzzo.','4 Fiori Di Zucca,
Zafferano,
2 Cucchiai Olio D''oliva Extra-vergine,
1/4 Dado Da Brodo,
Sale,
20 G Formaggio Pecorino,
1/2 Cipolla,
Prezzemolo,
1 Uovo,
Pepe Nero,
200 G Pasta Tipo Vermicelli','Pulite i fiori di zucca, lavateli, asciugateli e tagliateli finemente, con il prezzemolo e la cipolla. Prendete un tegame, versate l''olio e unite il trito preparato, lo zafferano con un po'' d acqua calda, sale e pepe e cuocete a fuoco vivo per qualche minuto. Passate le verdure e mettetele nel tegame. Togliete il tegame dal fuoco e unite l''uovo con il pecorino. Scolate la pasta e conditela con la salsa preparata.',1260);
INSERT INTO "ricette" VALUES (27287,'Vermicelli In Salsa Di Zafferano','Primo','Zafferano',4,' -','500 G Pasta Tipo Vermicelli,
1 Cipolla,
1 Mazzo Fiori Di Zucca,
3 Salsicce,
Brodo,
Olio D''oliva Extra-vergine,
Zafferano,
1 Uovo,
Prezzemolo,
Sale,
Pepe,
Formaggio Pecorino Grattugiato,
Concentrato Di Pomodoro','Fare soffriggere a fuoco molto basso nell''olio il trito di cipolla, fiori di zucca e prezzemolo. Aggiungere lo zafferano diluito in poco brodo, sale e pepe. Lasciar cuocere per un quarto d''ora. In un tegamino mettere le salsicce bucherellate con un dito d''acqua: quando avranno tirato fuori il grasso aggiungere due cucchiaini di concentrato di pomodoro e lasciar cuocere aggiungendo un po'' di brodo. In una pentola fare cuocere i vermicelli che vanno scolati al dente. Gettarli in una padella insieme al pecorino grattugiato. Aggiungere la salsa ottenuta che deve essere stata precedentemente passata al passino fine, e amalgamata con un tuorlo d''uovo. Fare saltare per un minuto a fuoco vivo, servire dopo aver versato sulla pasta le salsicce tagliate a pezzi con la loro salsetta rossa.',4090);
INSERT INTO "ricette" VALUES (27288,'Vermicelloni Alici E Pangrattato','Primo','Pasta D''acciughe',6,' -','600 G Pasta Tipo Vermicelloni,
1/2 Tubetto Pasta D''acciughe,
Peperoncino,
Prezzemolo,
3 Spicchi Aglio,
1 Bicchiere Olio D''oliva Extra-vergine,
Pangrattato','In una padella fate sciogliere la pasta d''acciughe nell''olio d''oliva extra-vergine per circa 2 minuti insieme al peperoncino. Scottate in un padellino il pangrattato in poco olio d''oliva extra-vergine con l''aglio pestato. Lessate i vermicelloni in abbondante acqua salata, scolateli ma non troppo. Fateli saltare nel padellone con l''olio e le acciughe. Aggiungete prima di servire il pangrattato e il prezzemolo fresco tritato.',3796);
INSERT INTO "ricette" VALUES (27289,'Vermicelloni All''amatriciana In Bianco','Primo','Pancetta Affumicata',4,' -','400 G Pasta Tipo Vermicelloni,
200 G Pancetta Affumicata A Dadini,
100 G Formaggio Pecorino Stagionato,
Olio D''oliva,
Sale,
Pepe','In una padella capiente, meglio se antiaderente, fate riscaldare abbondante olio d''oliva e rosolate la pancetta affumicata per circa 2 minuti. Subito dopo, quando i dadini saranno dorati e croccanti, scottate in acqua salata i vermicelloni e grattugiate il pecorino. Scolate la pasta al dente, versatela in padella, condite con il pecorino, il pepe e amalgamate velocemente il tutto dopodichè, servite subito.',3574);
INSERT INTO "ricette" VALUES (27290,'Vermicelloni Alla Provenzale','Primo','Pomodori Secchi Sott''olio',4,'Luogo: Francia. Luogo: Provenza.','400 G Pasta Tipo Vermicelloni,
250 G Pomodori Secchi Sott''olio,
Alcune Olive Nere,
1 Cipolla,
Origano,
Abbondante Olio D''oliva','Tagliate a pezzi i pomodori secchi sott''olio e lasciateli insaporire per qualche minuto in una padella antiaderente, nella quale avrete fatto soffriggere abbondante olio e la cipolla tritata finemente. Aggiungete le olive nere e l''origano e continuate la cottura per ancora qualche minuto. Nel frattempo, scottate i vermicelloni, scolateli al dente e versateli in padella amalgamando velocemente il tutto. Mangiateli subito caldi.',2816);
INSERT INTO "ricette" VALUES (27291,'Vermicelloni Del Pastore','Primo','Guanciale Di Maiale Affumicato',4,' -','400 G Pasta Tipo Vermicelloni,
200 G Guanciale Di Maiale Affumicato,
1 Cipolla,
Formaggio Pecorino Grattugiato,
Olio D''oliva','Sbucciate la cipolla, sciacquatela con cura sotto l''acqua corrente, asciugatela con fogli di carta assorbente e affettatela finemente. Nel frattempo, fate riscaldare abbondante olio d''oliva in una padella piuttosto capiente, meglio se antiaderente, dopodichè, versatela la e cuocetela per qualche minuto fino a dorarla. Successivamente, aggiungete il guanciale affumicato e lasciatelo insaporire al resto per pochi minuti. Nel frattempo, scottate i vermicelloni in acqua salata e bollente, scolateli al dente e versateli nella padella amalgamandoli velocemente agli ingredienti. Spolverizzate con il pecorino grattugiato e serviteli subito caldi. Suggerimento: per rendere ancora più stuzzicanti i vermicelloni, potreste aggiungere una spolveratina di pepe nero. Accorgimento: conservate l''acqua di cottura, potrebbe essere utile per mescolare al meglio i vermicelli. Non aggiungete sale al condimento, è sufficiente il sapore del guanciale affumicato e del pecorino grattugiato.',3596);
INSERT INTO "ricette" VALUES (27292,'Vermouth','Bevande','Vino Bianco',4,' -','100 Cl Vino Bianco Secco,
Alcuni Pizzichi Cannella,
Alcuni Pizzichi Chiodi Di Garofano,
Alcuni Pizzichi Assenzio,
Alcuni Pizzichi Salvia,
Alcuni Pizzichi Coriandolo,
Alcuni Pizzichi Genziana,
2 Arance,
150 G Zucchero','Ponete qualche pizzico di ogni spezia (che potrete trovare in erboristeria) in infusione nel vino insieme alla buccia grattugiata delle arance per tre giorni. Dopo procedete con il filtraggio, aggiungete lo zucchero, mescolate ed imbottigliate. Potrete berlo già dopo quindici giorni. Nota: l''operazione di filtraggio va fatta con un imbuto foderato con carta da filtro oppure ostruito con un batuffolo d''ovatta o con l''aiuto di un colino molto fitto.',1568);
INSERT INTO "ricette" VALUES (27293,'Vermouth Cassis','Bevande','Vermouth Dry',1,' -','2/3 Vermouth Dry,
1/3 Crema De Cassis,
Per Completare:,
Soda','Agitare nel mixer con ghiaccio in cubetti. Riempire per due terzi il tumbler stretto e aggiungere soda.',285);
INSERT INTO "ricette" VALUES (27294,'Vermouth Cassis (2)','Bevande','Vermouth Dry',1,' -','2/3 Vermouth Dry,
1/3 Crema De Cassis,
1 Spruzzo Seltz Ghiacciato','Versate il vermouth e la Crema De Cassis in un bicchiere old-fashioned già freddo, dopra uno o due cubetti di ghiaccio. Scuotete. Aggiungete il seltz.',254);
INSERT INTO "ricette" VALUES (27295,'Vermouth Cocktail','Bevande','Vermouth Dry',1,' -','1/2 Vermouth Dry,
1/2 Vermouth Bianco Dolce,
1 Spruzzo Angostura,
Per Servire:,
1 Ciliegina Al Maraschino','Si prepara nel miscelatore con ghiaccio tritato. Si serve con una ciliegina al Maraschino.',299);
INSERT INTO "ricette" VALUES (27296,'Vermouth Curacao','Bevande','Vermouth Dry',1,' -','4/5 Vermouth Dry,
1/5 Curacao,
Per Completare:,
Soda,
Per Servire:,
1 Scorza Di Limone','Agitare nel mixer con ghiaccio in cubetti. Riempire per due terzi il tumbler stretto e aggiungere soda. Servire con una scorza di limone.',289);
INSERT INTO "ricette" VALUES (27297,'Vermouth Maraschino','Bevande','Vermouth Dry',1,' -','4/6 Vermouth Dry,
1/6 Maraschino,
1/6 Succo Di Limone,
4 Gocce Angostura,
1 Ciliegia Al Maraschino','Scuotete bene i primi 4 ingredienti. Versate tutto su 2 cubetti di ghiaccio, in un bicchiere old-fashioned già freddo. Guarnite con la ciliegia.',247);
INSERT INTO "ricette" VALUES (27298,'Vermouth Orange','Bevande','Gin',1,' -','1/6 Succo D''arancia,
2/6 Vermouth,
1/6 Triple Sec,
2/6 Gin,
Per Servire:,
1 Fetta Arancia,
1 Fetta Pompelmo','Agitare vigorosamente nello shaker con abbondante ghiaccio in cubetti. Servire nel tumbler ampio, con una fetta d''arancia e una di pompelmo.',273);
INSERT INTO "ricette" VALUES (27299,'Vermouth Seltz','Bevande','Vermouth Bianco',1,' -','Vermouth Bianco,
1 Spruzzo Seltz,
1 Spruzzo Bitter All''arancia,
Per Servire:,
1 Scorza D''arancia','Preparare direttamente nel tumbler stretto. Servire con scorza d''arancia.',219);
INSERT INTO "ricette" VALUES (27300,'Vermouth Seltz (2)','Bevande','Vermouth Rosso',1,' -','Vermouth Rosso,
1 Spruzzo Seltz,
1 Spruzzo Bitter All''arancia,
Per Servire:,
1 Scorza D''arancia','Preparare direttamente nel tumbler stretto. Servire con scorza d''arancia.',219);
INSERT INTO "ricette" VALUES (27301,'Vermouth Semplice','Bevande','Vino Bianco',4,' -','200 Cl Vino Bianco,
4 G Punte D''assenzio,
4 G Centaura Minore,
4 G Cardo,
4 G Coriandolo,
4 G China,
4 G Scorza Di Limone,
4 G Scorza D''arancia,
1 G Cannella,
1 G Chiodi Di Garofano Polverizzati,
60 G Zucchero,
60 G Alcool Neutro A 90 Gradi','Mettete in un contenitore 200 cl di vino bianco, 4 g di punte d''assenzio, 4 g di centaura minore, 4 g di cardo, 4 g di coriandolo, 4 g di china, 4 g di scorza di limone, 4 g di scorza d''arancia tutti questi ingredienti vanno pestati, aggiungere poi 1 g di: cannella, noce moscata, chiodi di garofano polverizzati, 60 g di zucchero e 60 g di alcool neutro a 96 gradi leggermente allungato con acqua. Chiudete il contenitore e fate macerare per 10 giorni, togliete le droghe e filtratelo.',1841);
INSERT INTO "ricette" VALUES (27302,'Vermouth-gin','Bevande','Gin Dry',1,' -','1/2 Gin Dry,
1/2 Vermouth Rosso Italiano','Si tratta di un cocktail aperitivo, detto anche ''gin and it'', da preparare direttamente nei bicchieri usando vermouth rosso italiano. Gli ingredienti ben freddi si mescolano gentilmente nei bicchieri gelati.',309);
INSERT INTO "ricette" VALUES (27303,'Vermouth-gin (2)','Bevande','Gin Dry',1,' -','80 G Gin Dry,
80 G Vermouth Rosso Italiano','Si tratta di un cocktail aperitivo, detto anche ''gin and it'', da preparare direttamente nei bicchieri usando vermouth rosso italiano. Gli ingredienti ben freddi si mescolano gentilmente nei bicchieri gelati.',309);
INSERT INTO "ricette" VALUES (27304,'Veronica','Bevande','Vodka',1,' -','1/8 Succo Di Limone,
1/8 Cointreau,
6/8 Vodka','Agitare nello shaker. Servire nel flute con un cubetto di ghiaccio.',368);
INSERT INTO "ricette" VALUES (27305,'Veronike','Bevande','Vino Spumante Secco',1,' -','5/8 Vino Spumante Secco,
2/8 Succo D''arancia,
1/8 Cognac','Mescolate gli ingredienti nel mixer, con alcuni cubetti di ghiaccio, e servite nel flute.',117);
INSERT INTO "ricette" VALUES (27306,'Very Good','Bevande','Gin',1,' -','1/6 Succo D''arancia,
1/6 Cherry Brandy,
2/6 Vermouth Dubonnet,
2/6 Gin,
Per Servire:,
1 Spirale Scorza D''arancia','Agitare nello shaker. Servire nel tumbler stretto con due cubetti di ghiaccio e una spirale di scorza d''arancia.',289);
INSERT INTO "ricette" VALUES (27307,'Verza Al Gratin','Contorno','Cavolo Verza',4,' -','1 Cavolo Verza,
100 G Guanciale,
2 Cipolle,
1/4 Brodo Di Pollo (o Vegetale),
Olio D''oliva Extra-vergine,
30 G Formaggio Provolone Dolce,
Formaggio Grana Grattugiato,
Sale,
Pepe','Pulire la verza lasciando le foglie intere, ma prive della costa centrale. Lessarle al dente e adagiarle su di un canovaccio. Brasare la cipolla tritata con olio e guanciale a dadini. Foderare il fondo di una pirofila oliata con foglie di verza; distribuire a strati parte delle cipolle, dadini di provolone, grana, altra verza. Irrorare col brodo e cuocere in forno.',1845);
INSERT INTO "ricette" VALUES (27308,'Verza Ripiena','Carne','Carne Macinata',6,' -','1 Cavolo Verza,
200 G Carne Macinata Di Vitello,
200 G Salsiccia Del Tipo A Metro,
2 Panini Raffermi,
1 Uovo,
2 Cucchiai Formaggio Parmigiano Grattugiato,
1/2 Cucchiaino Aglio,
1/2 Cucchiaino Prezzemolo,
1 Noce Burro,
Latte,
Sale,
Pepe','Mettete a bagno i panini in poco latte tiepido. Mondate la verza delle foglie esterne eventualmente danneggiate poi lavatela bene e tuffatela, intera, in acqua salata a bollore, cuocendola per circa 15 minuti. Intanto fate insaporire nel burro la carne tritata insieme con la salsiccia spellata. Estraete la verza, sgocciolatela bene e appoggiatela su un piatto. Con estrema delicatezza allargate la verza foglia per foglia, arrivando fino al cuore. Staccatelo con un coltellino (senza intaccare il torsolo per non ''bucare'' la verza) poi tritatelo finemente e mettetelo in una ciotola. Unitevi le carni rosolate, i panini ben strizzati e sbriciolati, un cucchiaino di aglio e prezzemolo tritati, il formaggio, l''uovo, sale e pepe. Amalgamate bene tutti gli ingredienti fino ad ottenere un impasto omogeneo. Introducetelo allora con un cucchiaio all''interno della verza, distribuendolo anche tra una foglia e l''altra. Richiudete allora il cavolo, ''impacchettatelo'' in un canovaccio pulito e legatelo, poi immergetelo in acqua salata a bollore. Cuocete per 1 ora poi estraete la preparazione e togliete il canovaccio.',2470);
INSERT INTO "ricette" VALUES (27309,'Verza Ripiena (2)','Contorno','Verza',4,' -','500 G Verza,
100 G Funghi,
3 Cipolle,
1 Spicchio Aglio,
300 G Castagne,
Acqua,
Olio D''oliva,
Sale','Arrostite le castagne in forno e quindi sbucciatele. Nel frattempo pulite la verza e bollitela per qualche minuto in poca acqua leggermente salata. Tritate le cipolle e rosolatele in una pentola con poco olio, sino a quando diventino morbide e trasparenti; aggiungete l''aglio affettato finemente. Dopo qualche minuto unite anche i funghi precedentemente lavati, asciugati e affettati sottilmente; lasciate rosolare, abbassate quindi la fiamma e continuate la cottura a fuoco lento per una ventina di minuti, aggiustando di sale prima di togliere dal fuoco. Riempite quindi le foglie di verza con la salsa di funghi e arrotolatele, legandole poi con un filo. Disponetele in una pentola unta d''olio, versateci le castagne tutt''intorno, coprite e lasciate cuocere a fuoco molto moderato,con una retina frangifiamma, per un''ora circa.',1427);
INSERT INTO "ricette" VALUES (27310,'Verza Stufata','Contorno','Cavolo Verza',4,' -','1 Cavolo Verza,
2 Spicchi Aglio,
2 Pomodori Pelati,
1 Peperoncino,
100 G Olio D''oliva,
Sale','Tagliare a pezzi la verza. Imbiondire l''aglio con l''olio ed il peperoncino, aggiungere i pomodori a pezzi e la verza. Coprire e cuocere a fuoco lento aggiungendo un bicchiere d''acqua. A cottura ultimata salare e far asciugare il brodo a pentola scoperta.',1146);
INSERT INTO "ricette" VALUES (27311,'Verze E Ostriche','Pesce','Ostriche',4,'Preparazione: 20 minuti. Cottura: 16 minuti. Calorie: 128.','16 Ostriche,
1 Carota,
150 G Foglie Di Verza,
30 G Scalogno,
5 Cl Vino Bianco Secco,
1 Pizzico Zucchero,
1/2 Cucchiaio Aceto Di Vino Bianco,
3 Cucchiai Olio D''oliva Extra-vergine,
40 G Burro,
Sale,
Pepe','Aprite le ostriche, raccogliete il loro liquido in una ciotola e filtratelo. Pulite le verdure. Tagliate la carota a bastoncini, ponetela in una padella con un cucchiaio di olio e un cucchiaio di acqua, salate, pepate e cuocete per 5 minuti, mescolando. Unite le foglie di verza tagliate a tocchi, un cucchiaio di acqua e uno di olio, salate, pepate e lasciate sul fuoco per altri 2 minuti. Cuocete in un pentolino gli scalogni tagliati a spicchi con 2 cucchiai di acqua e l''olio rimasto, l''aceto e lo zucchero per 4 minuti. Sgocciolateli e trasferiteli in una insalatiera insieme con la carota e la verza e mescolate. Mettete nel pentolino il vino e il burro e scaldate per 3 minuti, poi aggiungete il liquido delle ostriche e mescolate per un minuto. Unite le ostriche senza guscio, fatele insaporire poi versate il tutto sulle verdure e servite.',1018);
INSERT INTO "ricette" VALUES (27312,'Vesuvio','Bevande','Limoncello',1,' -','Aranciata,
1/3 Fragolino,
1/3 Mandarino,
1/3 Limoncello,
1 Cucchiaino Sciroppo Di Granatina,
Per Guarnire:,
Scorza D''arancia','Mescolare tutti gli ingredienti. Guarnire con buccia d''arancia.',407);
INSERT INTO "ricette" VALUES (27313,'Via Firenze''s Coffee','Bevande','Caffè',1,' -','3/10 Crema Cacao Stock,
2/10 Crema Banana Bols,
2/10 Rum Havana Club Chiaro,
2/10 Caffè Lavazza,
1/10 Panna,
Per Guarnire:,
Alcune Scaglie Cioccolato','Si prepara nello shaker. Servire in doppia coppetta. Decorare con scaglie di cioccolato.',721);
INSERT INTO "ricette" VALUES (27314,'Vichingo','Bevande','Vermouth Noilly Prat',1,' -','2/3 B & B (benedictine E Brandy),
1/3 Vermouth Noilly Prat,
Per Completare:,
1 Spruzzo Succo Di Limone','Si prepara nello shaker con ghiaccio cristallino; aggiungere uno spruzzo di limone e servire freschissimo.',306);
INSERT INTO "ricette" VALUES (27315,'Vichyssoise','Salsa','Porri',4,' -','3 Patate,
40 G Burro,
150 Cl Brodo Di Pollo,
250 Cl Panna,
Sale,
Pepe,
3 Porri,
Cipolla','Affettare il bianco dei porri e la cipolla. Ammorbidite queste verdure per qualche minuto nel burro scaldato, poi aggiungete le 3 patate sbucciate e a dadini. Unite il brodo di pollo e cuocete a fuoco basso, in pentola coperta, per circa 20 minuti. Passate le verdure al mulinetto, rimettetele nel brodo di cottura, regolate sale e pepe e aggiungete la panna. Si può servire fredda con prezzemolo tritato.',10895);
INSERT INTO "ricette" VALUES (27316,'Vichyssoise (2)','Salsa','Porri',4,' -','500 G Porri,
250 G Patate,
50 Cl Latte,
6 Cucchiai Panna,
1 Ciuffetto Erba Cipollina,
Sale,
Pepe','Mondate i porri dalle radici dalla parte verde e dalla foglia esterna; lavateli e tagliateli a tronchetti alti 1 cm circa. Pelate e lavate le patate tagliatele a fette alte 1 cm. Riunite nella pentola le due verdure, il latte, 1/4 di litro d''acqua, sale e pepe. Chiudete la pentola, mettetela su una fiamma vivace. Al sibilo riducete la fiamma al minimo, date 8 minuti di cottura. Aprite la pentola, frullate, lasciate raffreddare, poi passate in frigorifero per un paio d''ore o fino al momento dell''uso. Mescolate alla crema di verdura la panna liquida; servitela cospargendo la superficie con l''erba cipollina tagliata a piccoli pezzi, o in mancanza con prezzemolo tritato.',1096);
INSERT INTO "ricette" VALUES (27317,'Vichyssoise (3)','Salsa','Porri',4,' -','6 Porri Grandi,
250 G Patate,
Burro,
1 Mazzetto Guarnito,
1 Bicchiere Panna,
Erba Cipollina,
Sale,
Pepe Bianco','Mondare i porri, eliminando la barbetta, la prima foglia esterna e la parte verde (che si conserverà per decorare alla fine). Ridurre a pezzetti solo il bianco, sbucciare le patate, lavarle e tagliarle a pezzi grossi. In una casseruola fare fondere 50 g di burro e unirvi i pezzi di porro, lasciandoli insaporire senza che perdano colore. Aggiungere le patate e rigirarle a lungo nel condimento. Insaporire il tutto con una grossa macinata di pepe bianco, poi bagnare con 150 cl di acqua, salare, aggiungere il mazzetto guarnito (un paio di steli di prezzemolo, una foglia di alloro, un rametto di cerfoglio) e portare ad ebollizione. Abbassare il fuoco e fare sobbollire per circa 40 minuti, tenendo il recipiente semicoperto. Togliere le patate dal recipiente, separandole dai porri, e passarle allo schiacciapatate. Ridurre i porri in crema, mettendoli nel frullatore insieme con qualche cucchiaio di brodo di cottura. Riunire il passato di patate e quello di porri e aggiungere qualche cucchiaio di liquido di cottura e un bicchiere di panna. Mescolare bene e mettere in casseruola a fuoco basso e, sbattendo con una frusta, portare al limite del bollore. Togliere la vichyssoise dal fuoco e farla raffreddare, poi metterla nel frigo per almeno un ora. Lavare l''erba cipollina e tagliarla con le forbici. Suddividere la minestra gelata in tazze da brodo o fondine, cospargerla con l''erba cipollina e con rondelle di verde di porro (scottate in acqua bollente per 10 minuti).',1339);
INSERT INTO "ricette" VALUES (27318,'Victor','Bevande','Gin',1,' -','2/4 Vermouth Rosso,
1/4 Cognac,
1/4 Gin,
Per Servire:,
1 Scorza D''arancia','Agitare con cubetti di ghiaccio nel mixer. Servire nel calice panciuto con un cubetto di ghiaccio e una scorza d''arancia precedentemente spremuta nel bicchiere.',326);
INSERT INTO "ricette" VALUES (27319,'Victor Victoria','Bevande','Caffè',1,' -','6/10 Caffè Lavazza,
2/10 Vino Porto Offley,
2/10 Vodka Eristow,
1 Cucchiaino Zucchero Di Canna,
Per Completare:,
Crema Latte','Si prepara nello shaker. Servire nella classica coppetta da cocktail. Ultimare con lieve strato di crema di latte.',262);
INSERT INTO "ricette" VALUES (27320,'Victory','Bevande','Pernod',1,' -','1/2 Granatina,
1/2 Pernod,
Per Servire:,
Soda','Agitare nello shaker con ghiaccio in cubetti. Servire nel calice panciuto, con soda ben fredda.',291);
INSERT INTO "ricette" VALUES (27321,'Vie En Rose','Bevande','Gin',1,' -','1/6 Succo Di Limone,
1/6 Granatina,
2/6 Kirsch,
2/6 Gin,
Per Servire:,
1 Fetta Limone,
1 Fetta Pompelmo','Agitare a lungo nello shaker. Servire nel tumbler stretto con ghiaccio tritato, una fetta di limone e una di pompelmo.',262);
INSERT INTO "ricette" VALUES (27322,'Vienna','Bevande','Vermouth Dry',1,' -','2/6 Vermouth Dry,
1/6 Panna Liquida,
2/6 Curacao,
1/6 Gin','Scuotere vigorosamente nello shaker con cubetti di ghiaccio. Servire nel gotto basso.',278);
INSERT INTO "ricette" VALUES (27323,'Viking','Bevande','Cherry Brandy',1,' -','1/6 Bitter Amaro,
2/6 Cherry Brandy,
3/6 Vodka,
1 Spruzzo Granatina,
Per Servire:,
1 Scorza D''arancia Lunga','Agitare nel mixer con poco ghiaccio tritato. Servire nel flute con una lunga scorza d''arancia.',413);
INSERT INTO "ricette" VALUES (27324,'Vin Blanc Cassis','Bevande','Vino Bianco Secco',1,' -','2/3 Vino Bianco Secco,
1/3 Crema De Cassis,
1 Spruzzo Seltz Ghiacciato','Versate il vino e la Crema De Cassis in un bicchiere old-fashioned già freddo, dopra uno o due cubetti di ghiaccio. Scuotete. Aggiungete il seltz.',174);
INSERT INTO "ricette" VALUES (27325,'Vin Brulè','Bevande','Vino Rosso',1,' -','1 Tazza Vino Rosso,
2 Cucchiaini Miele,
Semi Di Finocchio,
Cannella,
Chiodi Di Garofano','Prendere un pentolino, versarci il vino rosso, miele, semi di finocchio, cannella e chiodi di garofano. Attendere che inizi a sobbollire; non appena i vapori d''alcool cominciano a salire, prendere un fiammifero ed incendiare (fare attenzione alle mani!). Quando il fuoco di sopra si illanguidisce, spegnere il gas; attendere che finisca di fiammeggiare, filtrare e bere più che bollente. Il solo aspirarne l''aroma (quando è ancora caldissimo) è un ottimo rimedio contro il raffreddore.',208);
INSERT INTO "ricette" VALUES (27326,'Vin Brulè (2)','Bevande','Vino Rosso',1,' -','Vino Rosso,
Miele,
Cannella,
Chiodi Di Garofano,
Semi Di Finocchio,
1 Limone (scorza)','In un pentolino far bollire vino rosso, miele, cannella, chiodi di garofano, semi di finocchio e scorza di limone. Quando bolle allegramente, accostare un fiammifero ed accendere i vapori, senza spegnere sotto; quando il fuoco di sopra si spegne per esaurimento dell''alcool, bere bollente, inalandone i vapori tra una sorsata e l''altra.',237);
INSERT INTO "ricette" VALUES (27327,'Vin Brulè (3)','Bevande','Vino Rosso',4,' -','50 Cl Vino Rosso,
100 G Zucchero,
1 Manciata Chiodi Di Garofano,
Alcuni Pezzetti Cannella,
3 Foglie Alloro,
1 Limone','In una casseruola fate caramellare lo zucchero con un po'' d''acqua, aggiungete il vino e fate bollire fino a che non si è sciolto lo zucchero. Aggiungete una manciata di chiodi di garofano, tre foglie di alloro, qualche pezzetto di cannella e la buccia del limone ben lavata e tagliata a striscioline. Filtrate e bevetelo caldo. E'' ideale contro un principio di raffreddore e contro il freddo invernale.',878);
INSERT INTO "ricette" VALUES (27328,'Vin Brulè (4)','Bevande','Vino Rosso Corposo',4,' -','1 Parte Vino Rosso Corposo,
1 Scorza Di Limone,
3 Chiodi Di Garofano,
1 Cucchiaio Zucchero,
Cannella','Fate scaldare gli ingredienti in un pentolino e appena bolle toglietelo dal fuoco. Servite caldissimo in tazze da punch. Ideale contro i malanni da raffreddamento.',125);
INSERT INTO "ricette" VALUES (27329,'Vin Brulè (5)','Bevande','Vino Rosso',4,' -','100 Cl Vino Rosso,
250 G Zucchero,
10 Chiodi Di Garofano,
1 Stecca Cannella,
2 Limoni','Versate il vino rosso in una pentola capiente e cuocete a fiamma bassa aggiungendo poco per volta lo zucchero, i chiodi di garofano, la cannella e la scorza tagliata sottilmente di 1 limone. Portate a bollore il tutto per circa 10 minuti dopodichè, togliete dal fuoco, filtrate e servite caldo con 1/2 fettina di limone.',1798);
INSERT INTO "ricette" VALUES (27330,'Vin Brulè (6)','Bevande','Vino Barolo',4,'Luogo: Piemonte. Luogo: Alba. Preparazione: 20 minuti.','50 Cl Vino Barolo,
50 G Zucchero,
3 G Cannella Intera,
3 G Chiodi Di Garofano,
3 G Macis,
3 G Coriandolo,
3 Grani Pepe Nero,
1/2 Limone (scorza),
1 Foglia Alloro,
1 Pizzico Cardamomo,
1 Pezzo Bastoncino Di Vaniglia (o Un Pizzico Di Vaniglina),
1 Foglia Salvia,
1 Rametto Rosmarino','Versate in un pentolino il Barolo e metteteci tutti gli altri ingredienti: portate a bollore e fate bollire per sei o sette minuti. Filtrate il liquore alla tovaglia e servitelo bollente in tazza. Questa ricetta ha quasi 150 anni e viene bene anche se non avete a portata di mano il macis, il coriandolo e il cardamomo. Prosit, soprattutto quando siete giù di morale oppure raffreddati: contro il raffreddore il vin brulè è un toccasana, parola dei nostri anziani.',620);
INSERT INTO "ricette" VALUES (27331,'Vin Brulè Con Alloro','Bevande','Vino Rosso',1,' -','Vino Rosso,
Miele,
Cannella,
Chiodi Di Garofano,
Semi Di Finocchio,
1 Limone (scorza),
Alcune Foglie Alloro','In un pentolino far bollire vino rosso, miele, cannella, chiodi di garofano, semi di finocchio e scorza di limone, alcune foglie di alloro. Quando bolle allegramente, accostare un fiammifero ed accendere i vapori, senza spegnere sotto; quando il fuoco di sopra si spegne per esaurimento dell''alcool, bere bollente, inalandone i vapori tra una sorsata e l''altra.',247);
INSERT INTO "ricette" VALUES (27332,'Vin Brulè Con Bacche Di Ginepro','Bevande','Vino Rosso',1,' -','Vino Rosso,
Miele,
Cannella,
Chiodi Di Garofano,
Semi Di Finocchio,
1 Limone (scorza),
Alcune Bacche Ginepro','In un pentolino far bollire vino rosso, miele, cannella, chiodi di garofano, semi di finocchio e scorza di limone, alcune bacche di ginepro. Quando bolle allegramente, accostare un fiammifero ed accendere i vapori, senza spegnere sotto; quando il fuoco di sopra si spegne per esaurimento dell''alcool, bere bollente, inalandone i vapori tra una sorsata e l''altra.',247);
INSERT INTO "ricette" VALUES (27333,'Vin Brulè Con Brandy','Bevande','Vino Rosso',1,' -','Vino Rosso,
Miele,
Cannella,
Chiodi Di Garofano,
Semi Di Finocchio,
1 Limone (scorza),
Brandy','In un pentolino far bollire vino rosso, miele, cannella, chiodi di garofano, semi di finocchio e scorza di limone, brandy. Quando bolle allegramente, accostare un fiammifero ed accendere i vapori, senza spegnere sotto; quando il fuoco di sopra si spegne per esaurimento dell''alcool, bere bollente, inalandone i vapori tra una sorsata e l''altra.',463);
INSERT INTO "ricette" VALUES (27334,'Vin Brulè Con Zenzero E Cardamomo','Bevande','Vino Rosso',1,' -','1 Tazza Vino Rosso,
2 Cucchiaini Miele Allo Zenzero (v. Ricetta),
8 Semi Cardamomo,
1 Tronchetto Cannella,
5 Chiodi Di Garofano','Prendere un pentolino, versarci il vino rosso, miele, semi di cardamomo, cannella e chiodi di garofano. Attendere che inizi a sobbollire; non appena i vapori d''alcool cominciano a salire, prendere un fiammifero ed incendiare (fare attenzione alle mani!). Quando il fuoco di sopra si illanguidisce, spegnere il gas; attendere che finisca di fiammeggiare, filtrare e bere più che bollente. Il solo aspirarne l''aroma (quando è ancora caldissimo) è un ottimo rimedio contro il raffreddore. Il miele allo zenzero è miele in cui si lascia per un mese dello zenzero fresco tritato: 50 g. di zenzero per 200 g. di miele.',254);
INSERT INTO "ricette" VALUES (27335,'Vin Brulè Con Zenzero Essiccato','Bevande','Vino Rosso',1,' -','Vino Rosso,
Miele,
Cannella,
Chiodi Di Garofano,
Semi Di Finocchio,
1 Limone (scorza),
Zenzero Essiccato','In un pentolino far bollire vino rosso, miele, cannella, chiodi di garofano, semi di finocchio e scorza di limone, zenzero essiccato. Quando bolle allegramente, accostare un fiammifero ed accendere i vapori, senza spegnere sotto; quando il fuoco di sopra si spegne per esaurimento dell''alcool, bere bollente, inalandone i vapori tra una sorsata e l''altra.',257);
INSERT INTO "ricette" VALUES (27336,'Vin Brulè Grog','Bevande','Vino Rosso',1,' -','Vino Rosso,
Alcune Scorze Di Limone,
1 Pezzetto Cannella,
2 Chiodi Di Garofano,
Zucchero,
Per Servire:,
1 Scorza Di Limone','Mettere in una casseruola (il vino deve essere sufficiente a coprire gli altri ingredienti), coprire e portare ad ebollizione. Servire nel cup con una scorza di limone.',144);
INSERT INTO "ricette" VALUES (27337,'Vin Santo','Bevande','Vino Marsala',4,' -','300 Cl Vino Marsala,
50 G Genziana,
150 G Melissa,
60 G Rabarbaro','Ponete le spezie a macerare nel marsala, in un recipiente ampio, coperto da un panno, per circa 20-30 giorni in un luogo fresco e ben aerato. Mescolate un paio di volte al giorno con un cucchiaio di legno. Trascorso questo tempo filtrate il liquido ed imbottigliate. Questo vino è ideale per accompagnare un dessert.',3461);
INSERT INTO "ricette" VALUES (27338,'Vin Speziato','Bevande','Vino Rosso',6,' -','1 Bottiglia Vino Rosso Robusto,
3 Arance,
90 G Zucchero,
4 Chiodi Di Garofano,
1 Stecca Cannella,
1/2 Cucchiaino Noce Moscata,
1 Bicchiere Brandy,
Alcuni Kumquat'