e la salsa di pomodoro. Lasciate sobbollire a fiamma molto bassa per almeno 3/4 ore. Togliete la metà dei fagioli e lo stinco e passate tutto il resto al setaccio riducendolo in una purea liquida. Rimettete i fagioli nella zuppa e aggiungete il dado facendo addensare, se necessario, il liquido. Tagliate la polpa dello stinco a dadini grossolani e rimettetela nel tegame aggiungete i maltagliati. La zuppa sarà migliore se lasciata riposare per una mezz''oretta prima di servirla con parmigiano grattugiato e un filo d''olio d''oliva extra-vergine.',6032);
INSERT INTO "ricette" VALUES (17485,'Pasta E Fagioli Padovana','Primo','Fagioli Borlotti Secchi',4,'Luogo: Veneto. Luogo: Padova.','250 G Fagioli Borlotti Secchi,
180 G Pasta Tipo Tagliatelle Secche All''uovo,
1 Cucchiaio Farina,
3 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Passata Di Pomodoro,
1 Spicchio Aglio,
Rosmarino,
Prezzemolo,
Formaggio Parmigiano Grattugiato','Sciacquate i fagioli e metteteli a mollo in acqua appena tiepida per almeno 8 ore. Quindi scolateli, metteteli in una casseruola e copriteli con circa 150 cl di acqua fredda. Salate e fate cuocere lentamente per circa 2 ore. Quando i fagioli saranno cotti, tritate finissimo l''aglio con una manciatina di prezzemolo quindi scaldate l''olio in una casseruolina, mettetevi il trito preparato e qualche fogliolina di rosmarino e dopo 30 minuti, unite la farina. Mantenete la fiamma al minimo e mescolate continuamente per circa 2 minuti quindi, quando la farina comincia a scurirsi, bagnatela con la passata di pomodoro diluita in 1/2 tazza di acqua calda. Quando la salsa riprende il bollore, versatela nella pentola dei fagioli, mescolate bene e insaporite con sale e pepe. Buttate la pasta e fatela cuocere, mescolandola spesso. Lasciate un po'' intiepidire la minestra prima di servirla, spolverata di parmigiano grattugiato. Per rendere la minestra più densa, potete passare dal passaverdura la metà dei fagioli, prima di buttare la pasta. Piatto tipicamente italiano, si può dire che le minestre di pasta e fagioli sono tante quante sono le famiglie italiane. A seconda delle regioni, si usano varietà diverse di fagioli e, a seconda delle latitudini, il condimento può essere di olio o di lardo, magari arricchito con l''osso di prosciutto o con qualche cotenna di maiale. Tranne che nella versione veneta, la pasta e fagioli non viene completata con il formaggio ma piuttosto con una macinata di pepe o con un filo di olio crudo.',2322);
INSERT INTO "ricette" VALUES (17486,'Pasta E Fagioli Padovana (2)','Primo','Fagioli Borlotti Secchi',4,'Luogo: Veneto. Luogo: Padova.','250 G Fagioli Borlotti Secchi,
180 G Pasta Tipo Ditalini,
1 Cucchiaio Farina,
3 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Passata Di Pomodoro,
1 Spicchio Aglio,
Rosmarino,
Prezzemolo,
Formaggio Parmigiano Grattugiato','Sciacquate i fagioli e metteteli a mollo in acqua appena tiepida per almeno 8 ore. Quindi scolateli, metteteli in una casseruola e copriteli con circa 150 cl di acqua fredda. Salate e fate cuocere lentamente per circa 2 ore. Quando i fagioli saranno cotti, tritate finissimo l''aglio con una manciatina di prezzemolo quindi scaldate l''olio in una casseruolina, mettetevi il trito preparato e qualche fogliolina di rosmarino e dopo 30 minuti, unite la farina. Mantenete la fiamma al minimo e mescolate continuamente per circa 2 minuti quindi, quando la farina comincia a scurirsi, bagnatela con la passata di pomodoro diluita in 1/2 tazza di acqua calda. Quando la salsa riprende il bollore, versatela nella pentola dei fagioli, mescolate bene e insaporite con sale e pepe. Buttate la pasta e fatela cuocere, mescolandola spesso. Lasciate un po'' intiepidire la minestra prima di servirla, spolverata di parmigiano grattugiato. Per rendere la minestra più densa, potete passare dal passaverdura la metà dei fagioli, prima di buttare la pasta. Piatto tipicamente italiano, si può dire che le minestre di pasta e fagioli sono tante quante sono le famiglie italiane. A seconda delle regioni, si usano varietà diverse di fagioli e, a seconda delle latitudini, il condimento può essere di olio o di lardo, magari arricchito con l''osso di prosciutto o con qualche cotenna di maiale. Tranne che nella versione veneta, la pasta e fagioli non viene completata con il formaggio ma piuttosto con una macinata di pepe o con un filo di olio crudo.',2254);
INSERT INTO "ricette" VALUES (17487,'Pasta E Fagioli Padovana (3)','Primo','Fagioli Borlotti Secchi',4,'Luogo: Veneto. Luogo: Padova.','250 G Fagioli Borlotti Secchi,
180 G Pasta Tipo Maccheroncini,
1 Cucchiaio Farina,
3 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Passata Di Pomodoro,
1 Spicchio Aglio,
Rosmarino,
Prezzemolo,
Formaggio Parmigiano Grattugiato','Sciacquate i fagioli e metteteli a mollo in acqua appena tiepida per almeno 8 ore. Quindi scolateli, metteteli in una casseruola e copriteli con circa 150 cl di acqua fredda. Salate e fate cuocere lentamente per circa 2 ore. Quando i fagioli saranno cotti, tritate finissimo l''aglio con una manciatina di prezzemolo quindi scaldate l''olio in una casseruolina, mettetevi il trito preparato e qualche fogliolina di rosmarino e dopo 30 minuti, unite la farina. Mantenete la fiamma al minimo e mescolate continuamente per circa 2 minuti quindi, quando la farina comincia a scurirsi, bagnatela con la passata di pomodoro diluita in 1/2 tazza di acqua calda. Quando la salsa riprende il bollore, versatela nella pentola dei fagioli, mescolate bene e insaporite con sale e pepe. Buttate la pasta e fatela cuocere, mescolandola spesso. Lasciate un po'' intiepidire la minestra prima di servirla, spolverata di parmigiano grattugiato. Per rendere la minestra più densa, potete passare dal passaverdura la metà dei fagioli, prima di buttare la pasta. Piatto tipicamente italiano, si può dire che le minestre di pasta e fagioli sono tante quante sono le famiglie italiane. A seconda delle regioni, si usano varietà diverse di fagioli e, a seconda delle latitudini, il condimento può essere di olio o di lardo, magari arricchito con l''osso di prosciutto o con qualche cotenna di maiale. Tranne che nella versione veneta, la pasta e fagioli non viene completata con il formaggio ma piuttosto con una macinata di pepe o con un filo di olio crudo.',2254);
INSERT INTO "ricette" VALUES (17488,'Pasta E Fasoi','Primo','Fagioli Lamon Secchi',4,' -','200 G Fagioli Lamon Secchi,
150 G Pasta Tipo Tagliatelle Di Semola,
150 G Cotenna Di Maiale,
1 Cipolla Grande,
1 Carota,
1 Costa Sedano,
Rosmarino,
Alloro,
Sale,
Pepe,
Olio D''oliva','Tenere i fagioli a mollo per 1 notte. Tuffare la cotenna in acqua bollente e farla bollire 5 minuti; scolarla e raschiarla. Cuocere i fagioli a fuoco basso in 200 cl d''acqua con la cotenna, un trito di cipolla, carota e sedano, il rosmarino e l''alloro. Salare. Una volta cotti passare 1/3 dei fagioli al setaccio e riunirli al resto. Cuocervi la pasta e togliere dal fuoco. Servire nei piatti singoli e far intiepidire. Tagliare la cotenna a listarelle e disporla sui piatti. Condire con pepe e olio a crudo.',2411);
INSERT INTO "ricette" VALUES (17489,'Pasta E Fasoi Alla Padovana','Primo','Fagioli Borlotti',4,'Luogo: Veneto. Luogo: Padova.','200 G Fagioli Borlotti Sgranati,
200 G Pasta Tipo Ditalini,
4 Cucchiai Olio D''oliva,
1 Spicchio Aglio,
1 Rametto Rosmarino,
Prezzemolo,
1 Cucchiaio Farina,
1 Cucchiaio Salsa Di Pomodoro,
Formaggio Parmigiano,
Sale','Tenere a bagno i fagioli per 1 notte. Lessarli in 150 cl di acqua non salata. In una casseruola rosolare l''olio col rosmarino; togliere il rosmarino ed unirvi un trito d''aglio e prezzemolo e la farina. Mescolare e quando la farina è cotta unire 1 cucchiaio di pomodoro e 2 mestoli di brodo di cottura dei fagioli. Portare ad ebollizione, riunire il tutto ai fagioli e salare. Aggiungere la pasta e farla cuocere, quindi togliere dal fuoco, spolverizzare di parmigiano grattugiato e servire.',3084);
INSERT INTO "ricette" VALUES (17490,'Pasta E Fieno Al Salmone','Primo','Salmone',4,' -','400 G Pasta Tipo Paglia E Fieno,
300 G Salmone In Scatola,
1 Spicchio Aglio,
5 Cucchiai Olio D''oliva,
Prezzemolo,
Sale','Lessare la pasta in abbondante acqua salata. Sbucciare l''aglio e metterlo a colorire in un tegame con 5 cucchiai di olio. Unire il salmone ben sgocciolato dal liquido di conserva e sminuzzato, lasciandolo crogiolare per 5 minuti a fuoco basso. Scolare la pasta, condirla con il sugo di salmone e cospargere la superficie con prezzemolo tritato.',2273);
INSERT INTO "ricette" VALUES (17491,'Pasta E Finocchi','Primo','Finocchi',4,'Luogo: Calabria.','400 G Pasta Tipo Spaghetti,
Sale,
700 G Finocchi Selvatici,
1 Spicchio Aglio,
1 Peperoncino Piccante,
5 Cl Olio D''oliva Extra-vergine','Lessate gli spaghetti in acqua leggermente salata nella quale avrete già cotto piccoli finocchi verdi selvatici, che poi mescolerete alla pasta stessa dopo averli tagliuzzati. Aggiungete un soffrittino d''aglio, olio e peperoncino.',1915);
INSERT INTO "ricette" VALUES (17492,'Pasta E Finocchi (2)','Primo','Finocchio Selvatico',4,' -','2 Pugni Finocchio Selvatico (o 2 Finocchi),
500 G Pasta Tipo Bucatini,
Olio D''oliva','Cuocete in una pentola d''acqua salata del finocchio selvatico, quindi toglietelo, tritatelo e tenetelo da parte. Nell''acqua di cottura lessate dei bucatini, che condirete con finocchio ed olio d''oliva crudo.',2390);
INSERT INTO "ricette" VALUES (17493,'Pasta E Formaggi','Primo','Formaggio Provolone',6,' -','500 G Pasta Tipo Qualsiasi,
1 Cespo Radicchio Di Chioggia,
100 G Formaggio Provolone,
100 G Ricotta Dura,
100 G Formaggio Scamorza,
100 G Formaggio Grana,
1 Mazzetto Ravanelli,
1 Scalogno,
1/2 Cucchiaio Semi Di Finocchio,
Peperoncino In Polvere,
Aceto Di Vino Rosso,
Olio D''oliva,
Sale,
Pepe','Schiacciate i semi di finocchio, tritate lo scalogno raccoglieteli in una ciotolina col peperoncino olio, aceto sale e pepe. Affettate i ravanelli, tagliate a cubetti i formaggi e a listarelle l''insalata. Unite la pasta lessata e raffreddata e condite con la salsina eventualmente filtrata. Tenete in fresco e al momento di servire potete appoggiare l''insalata di pasta su delle foglie di radicchio che avete lasciato da parte.',3542);
INSERT INTO "ricette" VALUES (17494,'Pasta E Funghi Ubriachi','Primo','Funghi',4,' -','Abbondante Olio D''oliva,
2 Spicchi Aglio,
1/2 Cipolla,
400 G Funghi Champignon Affettati,
1 Bicchiere Vino Rosso,
1/2 Dado,
200 G Prosciutto Cotto,
Salvia,
Pepe,
Maggiorana,
4 Cucchiai Polpa Di Pomodoro,
Pasta Tipo Qualsiasi','Preparate una pentola con abbondante olio d''oliva; soffriggetevi due spicchi d''aglio ed una mezza cipolla, poi metteteci dentro 400 g di champignon affettati e lasciate cuocere un po''. Aggiungete un bicchiere di vino rosso, mezzo dado, 200 g di prosciutto cotto tagliato a listarelle, salvia, pepe, maggiorana e quattro cucchiai di polpa di pomodoro. Lasciate consumare, mescolando di tanto in tanto mentre cuocete la pasta, dopodichè condite la pasta con il sughetto.',3037);
INSERT INTO "ricette" VALUES (17495,'Pasta E Legumi','Primo','Ceci',6,'Luogo: Egitto.','400 G Riso,
300 G Pasta Tipo Filini,
300 G Pasta Tipo Maccheroni Piccoli,
200 G Ceci,
200 G Lenticchie,
200 G Sugo Di Pomodoro Fresco,
2 Cipolle Grandi,
4 Cucchiai Farina,
2 Uova,
Olio D''oliva,
Cipolla,
Aglio,
Peperoncino,
Sale,
Pepe','Fate cuocere separatamente i ceci e le lenticchie finché saranno ben cotti ma non disfatti e poi scolateli. Lessate separatamente anche la pasta filini, i maccheroni e il riso, scolateli e teneteli al caldo. Impanate le cipolle tagliate ad anelli prima nelle uova leggermente sbattute e poi nella farina e quindi friggetele finché diventano dorate. Disponete nei piatti il riso, la pasta filini, i maccheroni, i ceci e le lenticchie. Cospargete il koshari con il sugo di pomodoro soffritto in olio con aglio, cipolla, peperoncino, sale e pepe, disponete le cipolle fritte intorno al piatto e servite il tutto ben caldo.',5840);
INSERT INTO "ricette" VALUES (17496,'Pasta E Lenticchie','Primo','Lenticchie',4,' -','350 G Pasta Tipo Tubetti Piccoli,
200 G Lenticchie,
3 Pomodori Pelati,
2 Spicchi Aglio,
Olio D''oliva,
Sale,
Prezzemolo','Cuocere le lenticchie nell''acqua a fuoco lento. Quando saranno tenere aggiungere l''olio, l''aglio grattugiato, il sale e i pomodori. Cuocere ancora per 30 minuti. Gettare la pasta nella minestra, portare a cottura e unire il prezzemolo tritato.',2549);
INSERT INTO "ricette" VALUES (17497,'Pasta E Lenticchie (2)','Primo','Lenticchie',4,' -','160 G Lenticchie,
240 G Pasta Tipo Tubetti Piccoli,
5 Cl Olio D''oliva Extra-vergine,
1 Cucchiaino Concentrato Di Pomodoro,
2 Spicchi Aglio,
3 Pomodori,
Sale,
Pepe,
1 Costa Sedano,
1 Carota,
1 Cipolla,
Santoreggia','Mettere le lenticchie in una pentola, coprirle con acqua che le sopravanzi di 4 cm e portarle ad ebollizione con carota, cipolla, sedano, santoreggia e cuocere a fuoco lento per circa 1 ora. Unire l''olio, il concentrato di pomodoro, i pomodori freschi sbollentati, pelati e fatti a pezzetti, l''aglio. Aggiustare di sale. A parte lessare per 5 minuti i tubetti piccoli, unirli alle lenticchie, finire di cuocere. Servire con il pepe.',1873);
INSERT INTO "ricette" VALUES (17498,'Pasta E Melanzane Alla Siciliana','Primo','Melanzane',4,'Luogo: Sicilia.','1 Melanzana,
Pasta Tipo Qualsiasi,
Sugo Di Pomodoro,
Olio D''oliva','Tagliare una melanzana a fette e salare le fette. Mettere su la pasta ed un normale sugo di pomodoro (con un po'' di cipolla e basilico). Friggere le fette di melanzana in olio, senza impanarle. Tagliare le melanzane cotte a pezzettini e mescolarle a pasta e sugo.',1793);
INSERT INTO "ricette" VALUES (17499,'Pasta E Patate','Primo','Patate',4,'Luogo: Ciociaria. Luogo: Lazio.','Patate,
Pasta Tipo Pasta Corta,
Cipolla,
Pomodoro,
Sedano,
Sale,
Olio D''oliva','In una pentola capace si fa soffriggere la cipolla nell''olio bollente e si aggiungono il pomodoro ed il sedano. Dopo una breve cottura, si versa nella pentola una quantità d''acqua sufficiente per la cottura delle patate tagliate a pezzetti e della pasta. Al termine della cottura, il composto non dovrà risultare nè troppo liquido nè troppo denso.',2034);
INSERT INTO "ricette" VALUES (17500,'Pasta E Patate ''a Ra Tieddra''','Primo','Patate',4,'Luogo: Calabria.','400 G Patate,
400 G Pasta Tipo Pasta Corta Grande,
500 G Pomodori Freschi,
2 Cipolle,
Pangrattato,
1 Pizzico Origano,
Peperoncino Tagliuzzato,
70 G Formaggio Pecorino Grattugiato,
1 Spruzzata Olio D''oliva Extra-vergine,
Sale','In un tegame a bordi alti, possibilmente di rame stagnato (''a tieddra), sistemate a strati, dopo averlo unto di olio, la pasta cruda, le patate affettate in dischi sottili, le cipolle anch'' esse finemente affettate, i pomodori e il sedano tagliuzzati, una spolverata di formaggio, un pizzico di origano, peperoncino e sale, una spruzzata d''olio. Continuate a formare gli strati, spolverando di pangrattato la superficie, dopo l''ultima abbondante spruzzata di olio. Cuocete in forno con il tegame coperto. E'' un piatto dell''antiquariato Cosentino e originariamente andava collo nel forno di campagna con carbonelle roventi sistemate sul coperchio di stagno. Nelle campagne del Cosentino c''è ancora chi esegue questa antica tipica cottura.',2818);
INSERT INTO "ricette" VALUES (17501,'Pasta E Patate (2)','Primo','Patate',4,'Luogo: Ciociaria. Luogo: Lazio.','400 G Pasta Tipo Cannolicchi,
300 G Patate,
1 Carota,
1 Pomodoro Maturo,
1/2 Cipolla Tritata,
1 Costa Sedano Tritato,
100 Cl Acqua,
2 Dadi Per Brodo,
20 G Formaggio Pecorino,
Olio D''oliva','Portare a ballare l''acqua con i dadi. Pelare le potute, lavarle e tagliarle a cubetti. In una casseruola soffriggere il trito di carota, cipolla e sedano, aggiungere le patate e il pomodoro, versare il brodo bollente, coprire e cuocere a fuoco lento per circa 45 minuti. Alzare il bollore e aggiungere la posta. A cottura ultimata lasciare riposare la minestra per qualche minuto prima di servire.',2477);
INSERT INTO "ricette" VALUES (17502,'Pasta E Patate (3)','Primo','Patate',4,' -','500 G Patate A Pasta Gialla,
200 G Pasta Tipo Ditaloni,
1 Cuore Sedano,
2 Pomodori Pelati San Marzano,
Aglio,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Sbucciare le patate e tagliarle a dadini. In una pentola di coccio far imbiondire nell''olio l''aglio, unire le patate col sedano tritato e togliere l''aglio. Dopo aver fatto soffriggere un po'', unire i pomodori tritati, far insaporire ed aggiungere 50 cl d''acqua calda, portando ad ebollizione. Quando le patate sono quasi cotte, unire la pasta e portare a cottura.',1879);
INSERT INTO "ricette" VALUES (17503,'Pasta E Piselli','Primo','Piselli',4,' -','400 G Pasta Tipo Qualsiasi,
300 G Piselli Surgelati Findus,
250 G Pomodori Pelati,
80 G Burro,
1 Cipolla,
100 G Pancetta Affumicata,
Sale,
Pepe','Fondere il burro, unire la cipolla affettata finemente, la pancetta tagliata a dadini. Unire i piselli e soffriggere per 10 minuti, aggiungere i pelati, il sale e portare a cottura lentamente. Lessare la pasta e unirla ai piselli, infine insaporire con sale e pepe.',2782);
INSERT INTO "ricette" VALUES (17504,'Pasta E Piselli (2)','Primo','Piselli',4,' -','400 G Piselli,
100 G Prosciutto Cotto,
70 G Burro,
4 Cucchiai Olio D''oliva,
1/2 Cipolla,
Sale,
Pepe,
60 G Formaggio Parmigiano Grattugiato,
350 G Pasta Tipo Corallini','Dorare la cipolla affettata sottilmente nell''olio e burro. Unire il prosciutto a dadini e i piselli. Salare, pepare, aggiungere un bicchiere piccolo di acqua e cuocere a fuoco moderato per circa 35 minuti. Lessare al dente i corallini, scolarli e unirli ai piselli, mescolare su fuoco vivo per qualche minuto, cospargere con il parmigiano e servire.',4205);
INSERT INTO "ricette" VALUES (17505,'Pasta E Piselli Con Zucchine Farcite Con Il Bimby','Primo','Zucchine',6,' -','Per Le Zucchine Farcite:,
3 Zucchine Grandi,
50 G Prosciutto Cotto,
50 G Formaggio Parmigiano,
1 Panino Secco,
1 Uovo,
Sale,
Pepe,
Prezzemolo,
Per La Pasta E Piselli:,
40 G Olio D''oliva,
1/2 Cipollina,
50 G Pancetta,
300 G Piselli,
2 Pomodori Pelati,
800 G Acqua,
1 Cucchiaio Dado Bimby,
250 G Pasta Tipo Ditaloni,
Sale','Inserisci nel boccale il parmigiano, il pane e il prezzemolo: 10 secondi a velocità Turbo. Taglia le zucchine per la lunghezza e privale della polpa. Unisci la polpa al trito, aggiungi il prosciutto, l''uovo, il sale, il pepe ed amalgama il tutto per 20 secondi a velocità 5. Farcisci con il composto le zucchine, sistemandole nel Varoma. Inserisci nel boccale olio, cipolla e pancetta: 3 minuti a temperatura 100 velocità 4. Unisci i pelati sminuzzati, l''acqua, il dado e i piselli: chiudi il boccale, posiziona il Varoma e cuoci per 20 minuti a temperatura Varoma velocità 1. Togli il Varoma, unisci la pasta, riposiziona il Varoma e continua la cottura a velocità 1 temperatura Varoma per il tempo indicato sulla confezione della pasta. Disponi le zucchine in un piatto da portata, aggiusta di sale la pasta e portala in tavola.',2569);
INSERT INTO "ricette" VALUES (17506,'Pasta E Zucca','Primo','Zucca',4,' -','300 G Pasta Tipo Tubetti,
700 G Zucca,
2 Spicchi Aglio,
Peperoncino Forte,
Olio D''oliva,
Sale,
Abbondante Prezzemolo','Imbiondire l''aglio con l''olio, quindi eliminarlo. Sbucciare la zucca, privarla dei semi, tagliarla a pezzi e farla insaporire nell''olio con sale e peperoncino per 10 minuti. Unire 1 bicchiere di acqua bollente, coprire e cuocere a fuoco dolce finché sarà disfatta. Unire la pasta scolata molto al dente e farla saltare mescolando continuamente. Infine unire il prezzemolo tritato. Far riposare 5 minuti prima di portare in tavola.',1851);
INSERT INTO "ricette" VALUES (17507,'Pasta E Zucca (2)','Primo','Zucca Gialla',4,' -','180 G Pasta Tipo Spaghetti Spezzati,
200 G Zucca Gialla,
10 Olive Nere,
1 Manciata Capperi,
Olio D''oliva Extra-vergine,
Sale','Tagliare la zucca a dadini, soffriggerla nell''olio, aggiungere 4 capperi al sale e aspettare che la zucca si sfaldi. A metà cottura aggiungere 10 olive nere, amalgamare la pasta lessata con la salsa di zucca e servire.',1558);
INSERT INTO "ricette" VALUES (17508,'Pasta E Zucchine','Primo','Zucchine',4,' -','300 G Pasta Tipo Rigatoni,
7 Zucchine,
4 Patate,
Burro,
Formaggio Parmigiano','Affettate le zucchine e le patate a dischetti, qualcuna più fina e qualcuna meno. Mettete le zucchine e le patate a cuocere nella stessa pentola in cui cuocerà la pasta. Lasciate bollire per qualche minuto prima di aggiungere la pasta. Dovete regolarvi con i tempi di cottura della pasta per avere la cottura giusta sia della pasta che della verdura. A cottura ultimata scolate tutto mantenendo un paio di cucchiai d''acqua, condite con del burro ed una buona dose di parmigiano grattugiato. Alcuni dischi di verdura si saranno sfarinati, altri saranno rimasti interi. Pe'' le dosi potete da fa come ve pare, si ve piace più la verdura, ne mettete de più, sinnò nun ce la mettete pe'' gnente, cosã ve fate un ber piatto de pasta ar buro.',3064);
INSERT INTO "ricette" VALUES (17509,'Pasta E Zucchine (2)','Primo','Zucchine',4,' -','4 Zucchine,
1 Cipollina Novella,
300 G Pasta Tipo Farfalle,
1 Pezzettino Burro,
2 Cucchiai Latte,
1 Cucchiaio Pesto,
1 Cucchiaio Formaggio Pecorino Grattugiato,
1 Pezzetto Formaggio Provola Affumicata','Tagliato 4 zucchine a rondelle e friggerle insieme ad una cipollina novella. Poi lessare 300 g di farfalle (pasta) e saltarle in padella insieme alle zucchine, un pezzettino di burro 2 cucchiai di latte, 1 cucchiaio di pesto, 1 cucchiaio di pecorino grattugiato; aggiungere un pezzetto di provola affumicata, tagliandola a dadini.',1420);
INSERT INTO "ricette" VALUES (17510,'Pasta Esotica','Primo','Avocado',4,' -','300 G Cuori Di Palma In Scatola,
1 Avocado,
300 G Piselli Surgelati,
300 G Tonno,
2 Tuorli D''uovo,
Limone,
1 Bicchierino Vino,
Crescione,
Basilico,
4 Cucchiai Panna,
Olio D''oliva,
Sale,
Pepe,
Pasta Tipo Qualsiasi','Ridurre a fettine i cuori di palma e a dadini l''avocado. Spezzettare basilico e crescione. Lessare i piselli. Cuocere la pasta, raffreddarla e condirla con le verdure, gli aromi preparati e poco olio Frullare il tonno, unirvi un cucchiaio di succo di limone, i tuorli e montare la salsa versando a filo un bicchiere d''olio. Unirvi, poco per volta, il vino e la panna. Versare sulla pasta e servire.',3579);
INSERT INTO "ricette" VALUES (17511,'Pasta Esotica (2)','Primo','Avocado',4,' -','400 G Pasta Tipo Pennette Lisce,
1 Avocado Grande,
1/2 Bicchiere Vino Porto,
5 Cucchiai Panna Fresca,
1 Noce Burro,
Sale','Cuocere le pennette al dente. Intanto, aprire a metà l''avocado, togliere il nocciolo centrale, poi staccare la buccia. Tagliare la polpa a pezzettini e frullarla con la panna. Poi versare il composto in una capace terrina. Unire alla salsa il porto, salare e mescolare bene. Scolare la pasta e rovesciarla nella terrina, tenuta in caldo, con il condimento. Unire 1 noce di burro, rimescolare di nuovo e servire calda.',2573);
INSERT INTO "ricette" VALUES (17512,'Pasta Estate','Primo','Mozzarella',4,' -','400 G Pasta Tipo Penne Rigate,
1 Scatola Pomodori Pelati,
250 G Mozzarella,
5 Acciughe,
100 G Olive Nere,
1 Mazzetto Basilico,
Olio D''oliva,
Origano,
Sale,
Pepe','Frullare i pomodori, salare, pepare e unire una manciata di origano, le acciughe sminuzzate e qualche cucchiaio di olio. Mescolare, aggiungere le olive, coprire il recipiente e far macerare per 2 ore. Cuocere la pasta, scolarla, passarla sotto l''acqua fredda. Scolarla nuovamente e versarla nel sugo. Mescolare e aggiungere la mozzarella e il basilico.',3001);
INSERT INTO "ricette" VALUES (17513,'Pasta Estiva','Primo','Pomodori San Marzano',4,' -','350 G Pasta Tipo Farfalle,
3 Pomodori San Marzano,
1 Melanzana,
250 G Mozzarella,
2 Peperoni,
1 Limone,
Rosmarino,
Origano,
Basilico,
Olio D''oliva,
Sale,
Pepe','Tagliare la melanzana a dadini e rosolarla in poco olio. Tagliare a filetti i peperoni e appassirli in olio. Tagliare a cubetti pomodori e mozzarella e porli in una grande zuppiera. Unire i peperoni, le melanzane e mescolare bene. Lessare la pasta al dente, scolarla e passarla sotto l''acqua fredda. Versarla nella zuppiera. Condirla con il succo di limone, olio, sale, pepe e le erbe, mescolare e tenere in frigo almeno 1 ora prima di servire.',2627);
INSERT INTO "ricette" VALUES (17514,'Pasta Filante','Primo','Formaggio Fontina',4,' -','400 G Pasta Tipo Sedani Rigati,
100 G Formaggio Fontina,
50 G Panna,
50 G Burro','Lessare la pasta. Tagliare a scaglie la fontina e metterla in una zuppiera posta su una pentola con acqua bollente. Scaldare la panna e fondere il burro. Scolare la pasta e unirla alla fontina, aggiungere il burro e la panna. Mescolare e servire subito.',2283);
INSERT INTO "ricette" VALUES (17515,'Pasta Filante (2)','Primo','Formaggio Fontina',4,' -','400 G Pasta Tipo Pasta Corta,
100 G Formaggio Fontina,
50 G Panna,
50 G Burro,
1 Pizzico Sale','Tagliare a scaglie la fontina e metterle in una zuppiera posata su una pentola con acqua bollente. Scaldare la panna e far fondere il burro. Cotta la pasta (1 pizzico di sale) unirvi prima le scaglie di formaggio, poi il burro e la panna.',2284);
INSERT INTO "ricette" VALUES (17516,'Pasta Fredda','Primo','Mozzarella',4,' -','Pasta Tipo Conchiglie,
Pomodori Maturi,
Sedano,
Peperoni Rossi,
Peperoni Gialli,
Peperoni Verdi,
Basilico Fresco,
Senape,
Mozzarella','Mentre cuoce la pasta, tagliare a pezzetti la verdura e la mozzarella. Condire con olio, sale e un cucchiaio di senape. Scolare la pasta e mescolare con ''l''insalata'' preparata.',1561);
INSERT INTO "ricette" VALUES (17517,'Pasta Fredda Ai Wurstel','Primo','Wurstel Di Maiale',4,' -','400 G Pasta Tipo Panna Corta,
8 Wurstel Di Maiale,
1 Peperone Verde,
100 G Formaggio Dolce,
2 Uova,
300 G Pisellini Surgelati,
Olive Nere,
Olive Verdi,
Olio D''oliva,
Sale','Cuocere la pasta al dente, passarla sotto l''acqua fredda e metterla in una insalatiera. Unire i wurstel tagliati a rondelle, i piselli lessati, il formaggio a dadini, l''olio, il sale e mescolare bene. Guarnire con le uova sode, le falde del peperone e le olive e servire.',3615);
INSERT INTO "ricette" VALUES (17518,'Pasta Fredda Alla Greca','Primo','Formaggio Feta',4,'Luogo: Grecia.','400 G Pasta Tipo Pasta Corta (pasta Tipo Fusilli O Pasta Tipo Farfalle),
250 G Formaggio Feta,
1 Peperone Verde,
1 Cetriolo,
1 Confezione Olive Nere,
Pomodorini (tipo Ciliegino O Sardo),
Olio D''oliva Extra-vergine,
Aceto Balsamico,
Sale','Cuocere la pasta in abbondante acqua salata aggiungendo un po'' d''olio durante la cottura in modo da non farla attaccare in seguito. Una volta ultimata la cottura (meglio se al dente) e prima di scolarla, aggiungere un po'' di acqua fredda per fermare la cottura. Nel frattempo lavare, pulire e tagliare il peperone a listarelle (eventualmente conservare qualche listarella per la presentazione); lavare e tagliare i pomodorini in quarti o metà (secondo i gusti) e la feta a cubetti. Pelare e tagliare il cetriolo a fettine sottili; snocciolare le olive (sempre che non lo siano già). Versare tutti gli ingredienti in una grossa terrina (che dovrà in seguito contenere anche la pasta) e condire con un po'' di olio e sale. Una volta pronta la pasta, versarla nella terrina con gli ingredienti tagliati, aggiungere ancora un po'' d''olio e condire con aceto balsamico. Rimestare il tutto e lasciar insaporire: più tempo resta e meglio è. Prima di servire guarnire con qualche listarella di peperone e qualche pomodorino.',3299);
INSERT INTO "ricette" VALUES (17519,'Pasta Fredda Alla Mediterranea','Primo','Mozzarella',4,' -','500 G Pasta Tipo Tagliatelle,
Pomodoro A Cubetti,
Basilico,
Olio D''oliva Extra-vergine,
200 G Mozzarella,
Olive Nere Snocciolate','Cuoci la pasta e raffreddala a temperatura ambiente cospargendola con un velo di olio, girandola di volta in volta. Taglia i pomodori a cubetti e mettili in una terrina, aggiungi, sale, pepe, basilico tritato, la mozzarella a cubetti, le olive nere e l''olio d''oliva extra-vergine fai insaporire molto bene, quindi condisci la pasta.',3185);
INSERT INTO "ricette" VALUES (17520,'Pasta Fredda Col Tonno','Primo','Tonno',4,'Preparazione: 20 minuti.','Tonno Sott''olio,
Limoni,
Capperi,
Prezzemolo,
Acciughe,
Pasta Tipo Pasta Corta,
Olio D''oliva,
Pepe','Cuocere la pasta nel modo canonico e a fine cottura raffreddarla sotto il getto dell''acqua fredda. Mentre la pasta cuoce sbriciolare in una terrina il tonno e la polpa di limone a pezzetti. Aggiungere il prezzemolo, i capperi e le acciughe. Unire la pasta fredda e condire con olio e pepe.',2123);
INSERT INTO "ricette" VALUES (17521,'Pasta Fredda Di Pesce','Primo','Gamberi',4,' -','300 G Pasta Tipo Ditali,
120 G Gamberi,
12 Olive Verdi Snocciolate,
12 Olive Nere Snocciolate,
8 Acciughe Marinate,
8 Fasolari,
8 Cuori Di Mare (noci Di Mare),
6 Foglie Basilico,
Erba Cipollina,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Cuocete la pasta in acqua salata per 10 minuti, scolatela, fatela raffreddare sotto l''acqua corrente e mettetela su un vassoio ungendola con 2 cucchiai d''olio d''oliva. In una padella mettete con un filo d''olio i fasolari e i cuori di mare per farli aprire. Tagliate le olive a rotelline e preparate un trito con 6 foglie di basilico e un po'' di erba cipollina. Mettete in una ciotola la pasta fredda, i gamberi precedentemente lessati e sgusciati, le acciughe sgocciolate, i fasolari e i cuori tolti dalle conchiglie, le olive e il trito. Mescolate bene il tutto e aggiungete un po'' d''olio d''oliva e un po'' di pepe.',2420);
INSERT INTO "ricette" VALUES (17522,'Pasta Fresca Con Calamari','Primo','Calamaro',4,' -','150 G Farina,
2 Uova,
1 Calamaro Di 200 G,
2 Pomodori,
3 Cucchiai Olio D''oliva Extra-vergine,
1 Spicchio Peperoncino,
Acqua,
Prezzemolo,
Sale','Preparare la pasta. Rosolare l''aglio con il peperoncino, unire il calamaro pulito e tagliato a rondelle e far insaporire. Aggiungere i pomodori, il sale, il prezzemolo, e poca acqua di cottura della pasta, cuocere per 15 minuti circa. Scolare la pasta al dente e saltarla in padella.',1400);
INSERT INTO "ricette" VALUES (17523,'Pasta Fritta Con Nutella','Dessert','Nutella',4,' -','240 G Pasta Tipo Vermicelli,
Strutto,
Nutella','Lessate i vermicelli in acqua bollente e quando sono cotti scolateli, ma avendo cura di non sgocciolare completamente per evitare che si attacchino. Con una forchetta formate delle piccole matasse arrotolate. Immergete ogni matassina nello strutto bollente fin quando non abbia assunto un colore dorato. Scolatele, mettetele su carta assorbente e poi disponetele su un piatto da portata cosparse di Nutella fusa.',2000);
INSERT INTO "ricette" VALUES (17524,'Pasta Frolla','Dessert','Burro',4,' -','300 G Farina,
150 G Burro,
100 G Zucchero,
1 Uovo Intero,
2 Tuorli D''uovo,
1/4 Cucchiaino Sale','Setacciate la farina sulla spianatoia disponendola a fontana, fate un incavo al centro e ponetevi il burro spezzettato, le uova, il sale e lo zucchero. Impastate gli ingredienti con le mani fino ad ottenere una pasta liscia e soda. Non lavoratela oltre, perché così facendo il burro diventerebbe troppo caldo e l''impasto si sbriciolerebbe. Raccogliete la pasta a palla, avvolgetela nella pellicola trasparente e tenetela al fresco per 2-3 ore prima di utilizzarla.',2786);
INSERT INTO "ricette" VALUES (17525,'Pasta Frolla (10)','Dessert','Burro',6,' -','200 G Farina,
100 G Zucchero,
100 G Burro,
2 Tuorli D''uovo,
Scorza Di Limone,
1 Pizzico Sale','Lasciate ammorbidire il burro. Disponete a fontana farina e zucchero mescolati. Nel pozzetto, mettete il burro, i tuorli, un pizzico di sale, un po'' di buccia di limone grattugiata. Amalgamate gli ingredienti e lavorateli brevemente. Avvolgete la pasta nella pellicola trasparente e lasciatela riposare per un''ora in frigorifero. Al momento di utilizzarla, stendetela rapidamente a sfoglia con il matterello oppure adagiatela direttamente nella tortiera infarinata e allargatela, fino a coprire il fondo, pressandola con il palmo della mano. La pasta frolla pronta surgelata, se di buona marca, garantisce eccellenti risultati.',2003);
INSERT INTO "ricette" VALUES (17526,'Pasta Frolla (11)','Dessert','Burro',6,' -','200 G Farina,
80 G Burro,
2 Tuorli D''uovo,
Scorza Di Limone,
Sale','Questa ricetta consente di realizzare crostate particolarmente leggere da fine tavola. Lasciate ammorbidire il burro. Mescolate farina e zucchero, disponeteli a fontana, al centro mettete il burro a pezzetti, l''uovo intero e il tuorlo, un pizzico di sale. Lavorate rapidamente gli ingredienti. Avvolgete la pasta nella pellicola trasparente e lasciatela riposare in frigorifero almeno per un''ora. Ritiratela, eliminate la pellicola, lasciate una piccola porzione della pasta per la grata, tirate il resto a sfoglia di alcuni millimetri, adagiatela nella tortiera imburrata. Spalmate sulla superficie la marmellata prescelta. Decorate con la grata di pasta e completate con un cordoncino lungo la circonferenza. Cuocete in forno preriscaldato a 180 gradi per circa 20 minuti.',1461);
INSERT INTO "ricette" VALUES (17527,'Pasta Frolla (12)','Dessert','Burro',4,' -','300 G Farina,
150 G Burro,
150 G Zucchero,
2 Tuorli D''uovo,
1 Bustina Vaniglina,
1 Limone','Sciogliere il burro e versarlo in una terrina piuttosto capiente sopra lo zucchero e incominciare a mescolare. Quando si vede che si è amalgamato il tutto, versare la farina setacciata. impastare nuovamente. Aggiungere poi i 2 tuorli, la vaniglina e la scorza di limone grattugiata. Continuare a impastare fino a quando non si ottiene un composto ben amalgamato. A piacere, aggiungere un bicchierino di liquore Strega per dare un tocco in più di sapore. Quindi imburrare una teglia di diametro di circa 20 cm e versare l''impasto e mettere in forno già caldo per circa 40 minuti a 200 gradi circa. Avvertenza: il burro serve per amalgamare l''impasto: non essere parchi nella sua dose!',2915);
INSERT INTO "ricette" VALUES (17528,'Pasta Frolla (13)','Dessert','Uova',4,'Preparazione: 15 minuti.','250 G Farina Bianca,
150 G Zucchero,
150 G Margarina,
2 Uova Intere,
Scorza Di Limone Grattugiata,
1/2 Bustina Lievito Per Dolci','Occorre una teglia 25 x 40, altezza 3-4 cm. Disporre la farina e lo zucchero a fontana, rompere le uova , mescolarle alla margarina ammorbidita (non sciolta) alla scorza di limone e allo lievito. Mescolare ed impastare velocemente. Stenderla e metterla nella teglia. Alle prossime uscite per la preparazione delle torte.',2740);
INSERT INTO "ricette" VALUES (17529,'Pasta Frolla (2)','Dessert','Burro',4,' -','500 G Farina,
200 G Burro,
200 G Zucchero,
3 Uova,
1/2 Bicchiere Vino Marsala','Fai ammorbidire il burro. Impasta tutti gli ingredienti (se hai un robot da cucina fa tutto lui), fai una palla e avvolgila nella carta di alluminio, metti in frigo per almeno un''ora, poi la puoi usare.',4258);
INSERT INTO "ricette" VALUES (17530,'Pasta Frolla (3)','Dessert','Burro',4,' -','200 G Farina,
200 G Zucchero,
100 G Burro,
2 Tuorli D''uovo,
1 Bustina Vaniglina,
1 Limone (scorza),
Sale','Disponi la farina e lo zucchero a fontana, al centro metti il burro (freddo) tagliato a pezzettini, sale, vaniglina, e scorza di limone. Lavora farina e burro con la punta delle dita fino ad ottenere un composto simile alla mollica di pane sbriciolata. Riunisci il tutto di nuovo a fontana, unisci i tuorli e lavora l''impasto velocemente (la pasta non si deve essere scaldata dal calore delle mani). Lascia la pasta (chiusa nella pellicola) riposare nella parte meno fredda del frigo per 2 ore.',2405);
INSERT INTO "ricette" VALUES (17531,'Pasta Frolla (4)','Dessert','Burro',4,' -','300 G Farina,
150 G Zucchero,
150 G Burro,
1 Uovo Intero,
1 Limone (scorza),
Sale','Fai la fontana con la farina e lo zucchero. Metti nel mezzo il burro a pezzetti (deve essere freddo), l''uovo e la scorzetta. Aggiungi un pizzico di sale. Lavora gli ingredienti velocemente fino ad ottenere una palla di pasta. Non devi lavorarla troppo perché altrimenti non risulta croccante dopo la cottura. Mettila in frigo 1/2 ora a riposare.',2776);
INSERT INTO "ricette" VALUES (17532,'Pasta Frolla (5)','Dessert','Burro',6,' -','200 G Farina,
100 G Burro,
2 Tuorli D''uovo,
1 Pizzico Sale','Fate la fontana su un piano di lavoro con la farina e mettete nel centro il burro tagliato a pezzettini, i tuorli d''uovo e un pizzico di sale. Impastate senza aggiungere acqua. Formate una palla, copritela con un canovaccio; mettetela in frigo per trenta minuti.',1605);
INSERT INTO "ricette" VALUES (17533,'Pasta Frolla (6)','Dessert','Burro',4,' -','250 G Farina,
125 G Burro,
100 G Zucchero,
1 Uovo,
1 Tuorlo D''uovo','Versate la farina a pioggia nell''asse. Fate un buco al centro e aggiungete, il burro fuso, lo zucchero, l''uovo e il tuorlo. Amalgamate bene il tutto finché non si sarà formato un impasto omogeneo. Lasciate riposare per un''ora prima di utilizzarla.',2331);
INSERT INTO "ricette" VALUES (17534,'Pasta Frolla (7)','Dessert','Burro',4,' -','300 G Farina,
200 G Burro,
150 G Zucchero,
1 Uovo,
1 Tuorlo D''uovo,
1 Limone,
1 Pizzico Sale','Disponete la farina a fontana sulla spianatoia e al centro mettete il burro a pezzettini, lo zucchero, l''uovo, il tuorlo, la buccia grattugiata del limone e 1 pizzico di sale. Cominciate a lavorare gli ingredienti tutti assieme facendoli amalgamare bene. Ogni tanto raffreddatevi le mani in acqua fredda (per non far sgretolare la pasta). Non lavorate la pasta troppo a lungo, per non farla indurire troppo. Non appena l''impasto è omogeneo, formate una palla ed avvolgetela nella pellicola. Mettetela quindi a riposare mezz''ora in frigorifero prima di stenderla e di preparare le vostre crostate.',3269);
INSERT INTO "ricette" VALUES (17535,'Pasta Frolla (8)','Dessert','Burro',4,' -','250 G Farina,
150 G Burro,
1 Uovo Intero,
1 Tuorlo D''uovo,
1 Limone (scorza Grattugiata),
100 G Zucchero','Prima fai ammorbidire il burro a temperatura ambiente e poi lo lavori con lo zucchero. Aggiungi le uova e poi la farina e la buccia di limone grattugiata (in assenza puoi anche usare dell''aroma al limone). La pasta va lavorata molto velocemente e ''pizzicandola'', altrimenti si scalda e poi si rompe tutta. Va comunque fatta riposare in frigorifero, anche una giornata intera se puoi, però se la congeli già si riposa.',2525);
INSERT INTO "ricette" VALUES (17536,'Pasta Frolla (9)','Dessert','Burro',4,' -','100 G Burro Sciolto A Bagnomaria,
100 G Zucchero,
1 Uovo,
1/2 Bustina Lievito In Polvere,
250 G Farina','Lavora bene il burro con lo zucchero, quindi aggiungi l''uovo e farina con il lievito e lavora l''impasto fino a formare una palla ben compatta. Lascia riposare mezz''ora e poi stendila, oppure forma un panetto rettangolare, avvolgilo nella pellicola trasparente e mettilo a congelare. Quando lo userai considera che ci vogliono circa 2 ore per scongelarlo.',2057);
INSERT INTO "ricette" VALUES (17537,'Pasta Frolla Con Il Bimby','Dessert','Uovo',4,' -','300 G Farina,
130 G Burro Morbido,
1 Uovo Intero,
1 Tuorlo D''uovo,
75 G Zucchero,
1 Scorza Di Limone Grattugiata,
1 Pizzico Sale,
1/2 Cucchiaino Lievito Vanigliato (facoltativo)','Inserisci tutti gli ingredienti nel boccale e impasta per 25 secondi a velocità 7. Avvolgi l''impasto in un canovaccio e lascialo in frigorifero per 15 minuti prima di utilizzarlo. È un''ottima base per crostate.',2441);
INSERT INTO "ricette" VALUES (17538,'Pasta Frolla Per Pasticcini','Dessert','Burro',4,' -','250 G Farina Bianca,
175 G Burro,
75 G Zucchero Semolato,
Poco Albume D''uovo,
1/2 Bustina Vaniglina,
Sale','Con un cucchiaio di legno, montate in una ciotola il burro insieme allo zucchero e alla vaniglina; incorporate due cucchiaiate di albume montato in neve ben soda e un pizzico di sale. Unite la farina setacciata mescolando con delicatezza; coprite la ciotola con pellicola trasparente e mettetela in frigorifero per almeno un''ora. Trascorso questo tempo l''impasto, che si presentava piuttosto morbido, si sarà rassodato e si potrà quindi stendere molto facilmente. Per preparare i pasticcini occorrono degli stampini semisferici; oggi vengono anche venduti riuniti in un unica placca ed è utile per molte altre preparazioni. Prima di mettervi la pasta imburrateli, quindi sistematevi la frolla modellandola con un dito. senza che esca dal bordo; ovviamente la pasta deve essere di spessore uniforme. Metteteli in forno già caldo a 190 gradi cuocendoli per circa 10 minuti; lasciateli raffreddare fuori dal forno indi toglieteli con delicatezza dalle formine e riempiteli con una confettura a piacere e con panna montata a minuscoli ciuffetti, oppure con una crema (''pasticciera'' o ''all''inglese'').',2436);
INSERT INTO "ricette" VALUES (17539,'Pasta Frolla Salata','Antipasto','Burro',4,' -','250 G Farina,
125 G Burro Tagliato A Cubetti,
1 Tuorlo D''uovo,
1 Pizzico Sale,
2 Cucchiai Acqua','Setacciate la farina raccogliendola sul piano di lavoro. Disponetela a fontana e collocatevi nel centro il burro, il tuorlo d''uovo e il sale. Mischiate bene con una paletta, aggiungete l''acqua e lavorate l''impasto con le mani fino a formare una palla liscia. Lavorate con rapidità in modo che non si sciolga il burro. Raccogliete l''impasto a palla, avvolgetelo in una pellicola e lasciatelo refrigerare per circa 30 minuti, dopodichè usate la pasta preparata come è richiesto in ciascuna ricetta.',1848);
INSERT INTO "ricette" VALUES (17540,'Pasta Frolla Senza Le Uova','Dessert','Burro',6,' -','120 G Farina,
120 G Fecola Di Patate,
150 G Burro,
100 G Zucchero,
Scorza Di Limone','In una ciotola lavorate il burro con lo zucchero e un po'' di buccia di limone grattugiata fino a ottenere una crema. Mescolate e setacciate farina e fecola di patate, disponetela a fontana, nel pozzetto mettete la crema di burro e impastate velocemente. Avvolgete la pasta nella pellicola trasparente e lasciatela riposare in frigorifero per un''ora. Al momento di usarla stendetela a sfoglia con il matterello. Questa frolla ha un gusto più fine di quella con le uova, ma contiene più burro.',2312);
INSERT INTO "ricette" VALUES (17541,'Pasta Frolla Vegetariana','Antipasto','Germe Di Grano',4,'Ricetta adatta a: vegetariani.','2 Tazze Farina Semintegrale,
1/2 Tazza Olio Di Germe Di Mais,
Acqua Fredda,
Sale Marino','Si lavora brevemente la farina con l''olio, il sale e l''acqua fredda quanto basta per amalgamare bene gli ingredienti. Per impastare non usate le mani ma servitevi di un cucchiaio di legno. Questo per evitare che il glutine della farina si indurisca e che l''impasto risulti troppo compatto. Stendete la pasta con il mattarello formando uno strato sottile e mettetela nella teglia unta d''olio, facendo i bordi abbastanza alti perché dovranno racchiudere il ripieno. Bucherellate la pasta con una forchetta e mettetela nel forno, a fuoco lento, per circa 15 minuti. Metteteci sopra un ripieno di vostro gradimento (se questo è salato, come nel caso delle verdure, queste devono essere già cotte) e rimettetela nel forno per completare la cottura. Variazioni: se usate la pasta frolla per preparare un dolce, impastatela con succo di mela naturale al posto dell''acqua.',1077);
INSERT INTO "ricette" VALUES (17542,'Pasta Genovese','Dessert','Burro',4,'Luogo: Liguria. Luogo: Genova.','100 G Farina Bianca 00,
100 G Zucchero Semolato,
50 G Burro Freschissimo,
3 Uova,
1 Pizzico Vaniglina,
Sale','Rompete le uova in un polsonetto, unite lo zucchero, la vaniglina, e un pizzico di sale. Ponete il recipiente su fuoco basso mettendovi sotto uno spartifiamma e sempre sbattendo con la frusta scaldate il composto sino ad una temperatura di circa 40 gradi (tiepido ma non caldo); levate allora il recipiente dal fuoco e continuate a sbattere vigorosamente, ottenendo un impasto freddo e considerevolmente aumentato di volume. Incorporatevi allora la farina fatta cadere a pioggia da un setaccino, mescolando con il cucchiaio di legno dal basso in alto e viceversa, ma non in senso rotatorio. unite poi il burro sciolto e tiepido fatto scendere a filo. Imburrate ed infarinate uno stampo quadrato, avente il lato di cm 20 ed a parete alta cm 10, leggermente svasata; versate in esso il composto. Passatelo in forno già caldo (180 gradi) per circa 30 minuti; sformate poi la pasta sulla gratella coperta da un canovaccio rivoltandola subito e lasciandola raffreddare. Solitamente questa pasta viene tagliata a strati e farcita con creme diverse come ad esempio ''crema al burro'', ''crema pasticciera'', ''chantilly'', ''crema all''inglese'' ed anche ''zabaglione''. Si può rivestire la superficie con cioccolato o zucchero fondente, oppure servire il dolce decorato semplicemente con frutta e confettura.',1370);
INSERT INTO "ricette" VALUES (17543,'Pasta Genovese (2)','Dessert','Burro',6,' -','120 G Farina,
140 G Zucchero,
50 G Burro,
5 Uova,
1 Pizzico Sale','Lasciate ammorbidire il burro a temperatura ambiente. Sgusciate le uova in una casseruola media con il doppio fondo, aggiungete lo zucchero. Ponete il recipiente sul fornello, fiamma al minimo, continuate a mescolare fino a quando il composto è raddoppiato di volume. Ogni tanto spostate il recipiente sull''angolo del fornello per evitare che le uova attacchino sul fondo. Ritirate dal fuoco e continuate a lavorare il composto fino a quando si è raffreddato. A pioggia, poca alla volta e, sempre mescolando, unite la farina, un pizzico di sale e il burro. Amalgamate fino a ottenere un composto omogeneo, si può usare anche una frusta elettrica). Disponete l''impasto in una teglia imburrata e leggermente infarinata. Cuocete in forno preriscaldato a 170 gradi per circa 40 minuti.',1783);
INSERT INTO "ricette" VALUES (17544,'Pasta Gratinata Alle Melanzane','Primo','Melanzane',4,' -','400 G Pasta Tipo Paccheri,
2 Melanzane,
500 G Sugo Di Pomodoro Fresco,
200 G Formaggio Provola,
80 G Formaggio Grana Grattugiato,
Olio D''oliva Extra-vergine,
Sale','Mondare e lavare le melanzane, sbucciarle e tagliarle a fette di 1/2 cm; friggerle in olio ben caldo e adagiarle su carta da fritti. Lessare molto al dente i paccheri, scolarli e condirli col sugo, quindi disporli a strati in una pirofila infammezzandoli con strati di melanzane, provola e formaggio; terminare con una generosa manciata di parmigiano. Gratinare in forno.',3031);
INSERT INTO "ricette" VALUES (17545,'Pasta Gratinata Con Quadrucci Di Prosciutto','Antipasto','Prosciutto',4,' -','150 G Pasta Tipo Pasta Piccola Quadrata,
180 G Prosciutto,
40 G Burro,
40 G Farina,
20 Cl Latte,
15 Cl Crema Di Latte Acida,
3 Tuorli D''uovo,
3 Albumi D''uovo,
1 Uovo Intero,
Sale,
Pepe,
Noce Moscata,
Burro,
Formaggio Parmigiano Grattugiato','Sciogliete il burro, rosolate la farina e versate il latte caldo, dopodichè sbattete a filo e fate cuocere per alcuni minuti. Terminata la cottura fate raffreddare un po'', aggiungete i tuorli d''uovo e l''uovo intero e poi sbattete. Tagliate il prosciutto a dadini piccoli e sbattetelo nella besciamella insieme con la pasta cotta al dente e la crema di latte acida, dopodichè condite. Sbattete la neve, amalgamate e versate lo sformato in una teglia imburrata, cospargetelo di parmigiano e lasciatelo nel forno a 180 gradi per 40 minuti circa.',3495);
INSERT INTO "ricette" VALUES (17546,'Pasta In Salsa','Primo','Peperoni Rossi',4,' -','400 G Pasta Tipo Fusilli,
2 Peperoni Rossi,
100 G Panna,
Burro,
Sale,
1 Macinata Pepe','Cuocere la pasta in acqua salata. Intanto mondare e lavare i peperoni, tagliarli a metà e togliere i semi. Metterli nel frullatore con la panna e 1 pizzico di sale. Frullare pochi istanti fino ad ottenere una salsa rosata. In una casseruola far sciogliere il burro; unire la salsa, mescolare e farla appena scaldare. Scolare la pasta al dente, metterla in una terrina, versarvi sopra la salsa tiepida, aggiungere 1 grossa macinata di pepe, mescolare e servire subito.',2520);
INSERT INTO "ricette" VALUES (17547,'Pasta In Salsa Di Formaggio','Primo','Formaggio Parmigiano',4,' -','400 G Pasta Tipo Pasta Corta,
1/2 Cucchiaio Farina,
1 Bicchiere Latte,
1 Grattugiata Noce Moscata,
7 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
40 G Burro','Unire poco a poco alla farina metà del latte facendo attenzione a non formare grumi. Porre su fuoco dolce e, mescolando, far addensare il composto unendo poco alla volta il rimanente latte. Unire la noce moscata, il parmigiano e un po'' di sale. Lasciare su fiamma minima, sempre mescolando, finché la pasta è cotta. Scolarla e condirla con il burro e la salsa.',2298);
INSERT INTO "ricette" VALUES (17548,'Pasta Incasciata','Primo','Olive',4,' -','150 G Pasta Tipo Spaghetti,
1 Spicchio Aglio,
1/2 Peperone,
10 Olive,
10 Capperi,
2 Pomodori Pelati,
100 G Formaggio Pecorino,
100 G Pasta Di Pane,
Olio D''oliva,
Sale','Rosolare i cubi di carne in padella con olio e aglio, unire il 1/2 peperone a julienne, le olive denocciolate e tagliate, i capperi e il pomodoro pelato. Scolare la pasta cotta al dente in acqua salata e mantecarla in padella con pecorino. Trasferirla in una cocotte rivestita di pasta di pane e chiudere con i lembi di pasta in avanzo. Infornare per 10 minuti a 170 gradi.',1941);
INSERT INTO "ricette" VALUES (17549,'Pasta Lievitata Zuccherata','Dessert','Latte',4,' -','450 G Farina Bianca 00,
250 G Latte,
70 G Burro,
40 G Zucchero Semolato,
25 G Lievito Di Birra,
1/2 Limone,
Sale','Mescolate insieme 400 g di farina, un pizzicone di sale. lo zucchero e la scorza grattugiata di un quarto di limone: fate la fontana e ponetevi al centro 50 g di burro ammorbidito ed a fiocchetti, il latte tiepido nel quale avrete sciolto il lievito di birra. Impastate sino ad ottenere un composto liscio ed omogeneo, ponetelo in una ciotola spolverizzata di farina e copritelo con un tovagliolo, lasciandolo riposare in luogo tiepido per circa un''ora. Lavorate nuovamente la pasta e ricavate da essa dei panini, dei filoncini, delle ciambelline o altro. Ponete i dolcetti su una placca imburrata, distanziandoli, e passateli in forno già caldo (180 gradi) per circa 15 minuti.',2380);
INSERT INTO "ricette" VALUES (17550,'Pasta Maddalena Grassa','Dessert','Fecola',4,' -','150 G Zucchero Semolato,
75 G Farina Bianca,
75 G Fecola Di Patate,
50 G Burro,
6 Uova,
1 Limone,
Sale,
Per La Tortiera:,
Poco Burro,
Poca Farina','Mettete in un tegamino il burro e fatelo sciogliere a bagnomaria o su fuoco minimo, poi lasciatelo raffreddare. Accendete il forno sui 170 gradi, imburrate e infarinate uno stampo del diametro di cm 25, apribile a cerniera e con parete alta. Versate in una ciotola quattro uova intere e due tuorli, lo zucchero e la scorzetta grattugiata del limone, prima ben lavato; mescolate e fate intiepidire il composto a bagnomaria. Dopo di che montatelo; se possedete la sbattitrice elettrica usatela, ottenendo un risultato finale di gran lunga migliore che non con la lavorazione a mano; adoperate altrimenti una frusta o un frullino, sino ad avere una massa soffice e gonfia. Unite allora il burro sciolto e freddo facendolo scendere a filo, mescolando con delicatezza, un pizzico di sale, la farina e la fecola fatte scendere insieme a pioggia da un setaccino. Versate il composto nella tortiera, livellatelo in superficie e passatelo per 40 minuti nel forno che sarà già caldo alla temperatura indicata. A cottura avvenuta capovolgete la pasta sopra una gratella da pasticceria, lasciandola raffreddare. Potete servirla così o farcirla con panna montata o con zabaglione o altro tipo di crema.',2322);
INSERT INTO "ricette" VALUES (17551,'Pasta Margherita','Dessert','Uova',4,' -','4 Uova,
200 G Zucchero,
100 G Fecola Di Patate,
1 Limone (scorza Grattugiata),
1 Cucchiaino Lievito Per Pasticceria','Si montano i tuorli con lo zucchero, poi vi si unisce la fecola e la raschiatura di buccia di limone ed infine gli albumi montati a neve ed il lievito in polvere. Versate questo composto in una teglia che avrete già imburrata ed infarinata e fatelo cuocere in forno non troppo caldo, finché, infilandovi uno stecchino, lo ritrarrete asciutto. Togliete la torta dal forno, capovolgetela e fatela raffreddare su una gratella.',1506);
INSERT INTO "ricette" VALUES (17552,'Pasta Margherita (2)','Dessert','Zucchero A Velo',4,' -','200 G Zucchero A Velo,
120 G Farina Bianca 00,
100 G Fecola Di Patate,
100 G Burro Freschissimo,
10 Uova,
1 Bustina Vaniglina,
Miele','Imburrate uno stampo quadrato della capacità di circa 3 litri, a parete alta e leggermente svasata, poi spolverizzatelo con un pizzico di farina rigirando bene lo stampo in modo che se ne rivesta alla perfezione. Fate sciogliere (non friggere!) 80 g di burro. Versate quindi in una casseruola, possibilmente di rame non stagnato, quattro uova intere, la vaniglina e lo zucchero a velo: con una piccola frusta sbattete bene, poi unite uno alla volta sei tuorli, non mettendo il successivo se il precedente non sarà stato bene amalgamato. Sistemate il recipiente su fuoco bassissimo o a bagnomaria e, sempre mescolando, lasciatevi il composto sino a quando sarà divenuto tiepido; levatelo allora dal fuoco, unite una puntina di miele e continuate a sbattere energicamente il composto sino a quando sarà diventato freddo, ben gonfio e ben montato. Unite allora, facendole cadere a pioggia da un setaccino, la fecola e 100 g di farina amalgamandole con molta delicatezza; in ultimo incorporatevi il burro sciolto e freddo. Versate la crema nello stampo preparato poi mettetelo in forno già caldo lasciandovelo poco più di mezz''ora. Questa è la ricetta classica della pasta Margherita ma s''intende che si può preparare usando anche uno stampo del formato che si desidera. Non è una pasta difficile a farsi, ma la sua lavorazione a mano è pesante e di conseguenza faticosa: si risolve in poco tempo con l''impastatrice elettrica.',3295);
INSERT INTO "ricette" VALUES (17553,'Pasta Margherita (3)','Dessert','Burro',6,' -','150 G Farina,
50 G Fecola,
100 G Burro,
200 G Zucchero,
6 Uova,
1 Limone,
1 Pizzico Sale','In una larga terrina lavorate i tuorli con lo zucchero fino a farli diventare bianchi e spumosi. Aggiungete, a poco a poco, la farina e la fecola mescolate e setacciate, il burro fuso a bagnomaria, un pizzico di sale e la buccia grattugiata del limone. Con delicatezza incorporate al composto gli albumi montati a neve soda e amalgamate. Versate l''impasto in una teglia o in una tortiera imburrata e leggermente infarinata. Cuocete in forno preriscaldato a 180 gradi e cuocete per 30-35 minuti. Questa torta si può offrire spolverizzata e farcita con marmellate o creme di sapore e colore diversi, per esempio: zabaglione e cioccolato, marmellata di ciliegie e crema inglese.',2759);
INSERT INTO "ricette" VALUES (17554,'Pasta Mascarpone E Piselli','Primo','Mascarpone',4,' -','Piselli,
Pasta Tipo Qualsiasi,
Mascarpone','Butti un po'' di piselli nell''acqua della pasta (quelli surgelati vanno benissimo), poi ci butti anche la pasta e, quando è cotta, tuffi il tutto nel mascarpone (come se fosse burro).',1528);
INSERT INTO "ricette" VALUES (17555,'Pasta Mediterranea','Primo','Olive Nere',4,' -','300 G Pasta Tipo Fusilli,
1 Spicchio Aglio,
8 Olive Nere Snocciolate E Tritate,
3 Filetti D''acciughe Sott''olio A Pezzettini,
2 Pomodori Maturi Sbucciati E Tagliati,
Basilico,
100 G Ricotta,
Olio D''oliva,
Sale,
Pepe,
Formaggio Parmigiano','Mentre cuoce la pasta mettete in una padella 3 cucchiai d''olio, aggiungete l''aglio finemente tritato e mescolatevi insieme le olive le acciughe, i pomodori, il basilico, la ricotta. Salate e saltateci la pasta aggiungendo il parmigiano e il pepe.',2394);
INSERT INTO "ricette" VALUES (17556,'Pasta Mista Con Gamberi, Fagioli E Zucchine','Primo','Gamberi',4,' -','160 G Pasta Tipo Pasta Mista,
1 Tazza Fagioli Cannellini,
2 Zucchine,
5 Gamberi,
1 Costa Sedano,
Aglio,
Prezzemolo,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Soffriggere aglio, zucchine e prezzemolo. Dopo 5 minuti unire i fagioli e bagnare con poca acqua calda. Aggiungere i gamberi sgusciati. Salare, pepare e cuocere per altri 5 minuti. Scolare la pasta e saltarla in padella. Servire cospargerla di prezzemolo.',1756);
INSERT INTO "ricette" VALUES (17557,'Pasta Per Bignè','Dessert','Burro',6,' -','150 G Farina,
100 G Burro,
1/2 Cucchiaino Sale,
1 Cucchiaino Zucchero,
25 Cl Acqua,
4 Uova','Le dosi sono per 24 bignè. Versate l''acqua in una casseruola, aggiungete il sale, lo zucchero e il burro. portate a bollore, versate in un sol colpo la farina. Lavorate l''impasto e cuocetelo per circa 8 minuti, si deve staccare dalle pareti della casseruola. Togliete dal fuoco e aggiungete un uovo; quando è ben amalgamato unite, uno alla volta, gli altri ma non prima che il precedente sia ben incorporato. Con un cucchiaio fate dei mucchietti di pasta e disponeteli ben distanziati sulla placca del forno. Cuocete a calore moderato fino a quando diventano ben gonfi. Riempiteli con creme dolci o salate.',1626);
INSERT INTO "ricette" VALUES (17558,'Pasta Per Bignè Salata','Dessert','Formaggio',6,' -','150 G Farina,
100 G Burro,
25 Cl Acqua,
200 G Formaggio Grattugiato,
4 Uova,
Sale,
Pepe Bianco','In una casseruola versate l''acqua, salate, pepate con parsimonia. Aggiungete il burro. Quando il liquido alza il bollore unite la farina mescolando vigorosamente senza smettere fino a quando l''impasto si stacca dalle pareti del recipiente. Ritirate dal fuoco, lasciate raffreddare, incorporate all''impasto un uovo alla volta mescolando con energia. Aggiungete il formaggio grattugiato e mescolate bene. Con un cucchiaio prendete un po'' d''impasto alla volta e fatene delle palline grandi poco più di una noce. Allineatele su una teglia leggermente imburrata e infarinata. Cuocete in forno preriscaldato a 180 gradi per circa 20 minuti o fino a quando i bignè gonfiandosi hanno raddoppiato il loro volume. Ritirate dal forno e fate raffreddare. Riempite i bignè con fonduta, besciamella o altra crema salata. Una variante di questo impasto consiste nel sostituire il formaggio grattugiato con altrettanto prosciutto cotto tritato oppure con salame (tipo ungherese) tritato finemente. Il formaggio può essere metà Emmenthal e metà parmigiano o anche tutto parmigiano.',2337);
INSERT INTO "ricette" VALUES (17559,'Pasta Per Biscotto Arrotolato','Dessert','Uova',4,' -','125 G Farina Bianca 00,
125 G Zucchero Semolato,
6 Uova','Mettete in una ciotolina quattro uova intere e due tuorli, aggiungete la zucchero e con la frusta montate sino ad avere un composto soffice e gonfio. Unite la farina fatta cadere a pioggia da un setaccino, mescolando delicatamente con il cucchiaio di legno. Imburrate leggermente due placche, copritele poi con un foglio di carta oleata imburrato e cosparso di farina, indi versate su ognuna la metà del composta stendendolo uniformemente con una spatola flessibile. Infornatele a 220 gradi lasciandovele da 5 a 7 minuti; rovesciate una placca sopra un asciughino adeguato molto inumidita, pennellate la carta oleata con acqua fredda poi staccatela tenendo ferma con una mano la pasta per aiutarsi in questo lavoro. Arrotolate quindi la pasta abbastanza strettamente nell''asciughino, che impedirà al ''biscotto arrotolato'' di appiccicarsi, chiudendo le estremità dell''involto con uno spago. Procedete allo stesso modo con l''altra pasta. Lasciatele quindi riposare al fresca a in frigorifero per 20 minuti circa, indi srotolatele, spalmate ognuna di confettura o di crema e arrotolatele su se stesse. Ponetele separatamente su un piatto lungo e stretta e decoratele a piacere con panna montata e ciliegine, o altra frutta candita.',1477);
INSERT INTO "ricette" VALUES (17560,'Pasta Per Brioche','Dessert','Burro',8,' -','250 G Farina,
200 G Burro,
4 Uova,
15 G Zucchero,
10 G Lievito Di Birra,
1 Pizzico Sale','È una pasta che richiede tre successive fasi di lievitazione. Disponete a fontana sul tavolo 60 g di farina, mettete nel pozzetto centrale il lievito stemperato con poca acqua tiepida. Impastate con cura, formate una pagnottella, incidete la superficie con un taglio a croce, coprite con un tovagliolo. Lasciate lievitare in luogo tiepido per 2 o 3 ore. Disponete a fontana la restante farina, al centro mettete un uovo, lo zucchero, un pizzico di sale. Amalgamate gli ingredienti, unite il burro ammorbidito a pezzettini, continuate a impastare aggiungendo, uno alla volta, le altre due uova. Quando la prima pasta ha raddoppiato il suo volume unitela a questo impasto. Lavoratelo con le mani, formate una grande palla, copritela con un tovagliolo e lasciatela lievitare per 2 o 3 ore. Quando anche questa pasta è raddoppiata di volume lavoratela di nuovo con le mani leggermente infarinate. Se volete preparare una sola grande brioche riempite con l''impasto due terzi di uno stampo imburrato, praticate un taglio a croce sulla superficie e lasciate lievitare ancora un po''. Intanto sbattete leggermente l''uovo avanzato, spennellatelo sulla superficie della pasta e cuocete in forno preriscaldato a 200 gradi per 50 minuti circa. Controllate la cottura infilando uno stecchino nella brioche che, se cotta a puntino, deve uscire asciutto. Se, invece, volete preparate brioche singole, suddividete l''impasto in otto parti, date loro la forma desiderata, lasciatele lievitare un poco, spennellatele con l''uovo sbattuto, punzecchiatele con una forchetta, allineatele sulla placca del forno leggermente imburrata e infarinata, cuocetele in forno preriscaldato a 200 gradi per 15-20 minuti.',2745);
INSERT INTO "ricette" VALUES (17561,'Pasta Per Ciechi','Primo','Mozzarella',4,' -','400 G Pasta Tipo Qualsiasi,
2 Pomodori,
300 G Mozzarella,
10 Foglie Basilico,
Pepe,
Sale,
Olio D''oliva','Mettete in una scodella i pomodori e la mozzarella tagliati a dadini insieme al basilico tritato. Condite con sale, olio e pepe e lasciatela riposare in salotto. Bollite la pasta, dopo averla scolata (ovvio) aggiungetevi il sughetto che dopo 6 soap opera sarà totalmente rincoglionito, e penserà di essere Maddalena la monaca cieca di Santa Maria in croce della serie ''Non ti ho più rivisto''. Per una buona riuscita di questo veloce piatto dovrete: oscurare completamente la casa e servire in piatti neri.',2760);
INSERT INTO "ricette" VALUES (17562,'Pasta Per Dolci Lievitata','Dessert','Lievito Di Birra',4,' -','220 G Farina,
10 Cl Latte,
1 Uovo,
35 G Burro,
30 G Zucchero,
5 G Lievito Di Birra','Lasciate ammorbidire il burro. In una terrina sbriciolate il lievito diluito con il latte tiepido, unite lo zucchero, l''uovo intero e il burro. Mescolando unite la farina setacciata. Amalgamate e lavorate il composto. Copritelo e lasciate lievitare per un''ora e mezzo in luogo tiepido. Stendete la pasta con il matterello in due sfoglie lasciando intorno un bordo più spesso. Adagiatele in due tortiere imburrate e cuocete in forno preriscaldato a 180 gradi per 30 minuti.',1232);
INSERT INTO "ricette" VALUES (17563,'Pasta Per Fondo Torta','Dessert','Burro',6,' -','250 G Farina,
130 G Burro,
80 G Zucchero,
1 Uovo,
1 Pizzico Sale,
Fagioli Secchi','In una larga terrina lavorate il burro con lo zucchero e un pizzico di sale fino a ottenere un crema e poi incorporatevi l''uovo e la farina tutta in una volta. Rovesciate sul tavolo e lavorate la pasta con le mani in modo che la farina venga assorbita. Dividete la pasta in quattro pezzi, sovrapponeteli, premete il panetto tre volte, avvolgetelo nella pellicola e lasciate riposare per un''ora circa. Tirate la pasta a disco di mezzo centimetro di altezza, adagiatelo in una tortiera imburrata e fatelo risale un po'' anche sulle pareti. Modellate sulla pasta un foglio d''alluminio e sopra distribuite un po'' di fagioli secchi. Cuocete in forno preriscaldato a 180 gradi per circa 25 minuti. Ritirate, togliete carta e fagioli, lasciate raffreddare e su questo fondo torta disponete frutta fresca o creme diverse.',2440);
INSERT INTO "ricette" VALUES (17564,'Pasta Per Pan Di Spagna','Dessert','Fecola Di Patate',6,' -','80 G Farina,
80 G Fecola Di Patate,
150 G Zucchero,
6 Uova,
Burro','In una ciotola lavorate i tuorli con lo zucchero fino a farli diventare chiari e spumosi, quindi incorporatevi delicatamente gli albumi montati a neve ben soda. Poco per volta aggiungete al composto farina e fecola setacciate. Imburrate leggermente una tortiera, spolverizzatela di farina, versatevi l''impasto e cuocete in forno preriscaldato a 180 gradi per circa 40 minuti. Ritirate, lasciate raffreddare e sformate. La pasta di pan di Spagna è ideale per realizzare torte farcite con la crema.',2422);
INSERT INTO "ricette" VALUES (17565,'Pasta Per Pane O Pizza Con Il Bimby','Primo','Farina',4,' -','500 G Farina,
1 Cubetto Lievito Di Birra,
200 G Acqua,
100 G Latte,
1 Cucchiaio Olio D''oliva,
Sale','Inserisci nel boccale l''olio, il lievito, l''acqua, il latte tiepido e il sale: 5 secondi a velocità 6. Aggiungi la farina: 20 secondi a velocità 6 e 1 minuto a velocità Spiga. Lascia lievitare l''impasto coperto per circa 1/2 ora, prima di utilizzarlo.',2004);
INSERT INTO "ricette" VALUES (17566,'Pasta Per Pizza','Antipasto','Farina Integrale',4,' -','250 G Farina Integrale,
10 G Lievito Fresco,
15 Cl Acqua Calda,
1/2 Cucchiaino Sale','Sciogliere il lievito nell''acqua calda, aggiungere la farina e il sale, impastare a mano o con l''impastatrice fino a formare una massa morbida ed elastica. Coprire e lasciar lievitare in luogo caldo per circa 1/2 ora.',811);
INSERT INTO "ricette" VALUES (17567,'Pasta Per Pizza Gigante Con Il Bimby','Primo','Farina',4,' -','700 G Farina,
1 Cubetto Lievito Di Birra,
300 G Acqua,
100 G Latte,
2 Cucchiai Olio D''oliva,
Sale','Inserisci nel boccale l''olio, il lievito, l''acqua, il latte tiepido e il sale: 5 secondi a velocità 6. Aggiungi dall''alto a pioggia, la farina: 30 secondi a velocità 6 e 1 minuto e 1/2 a velocità spiga. Lascia lievitare l''impasto coperto per circa 1/2 ora, prima di utilizzarlo.',2749);
INSERT INTO "ricette" VALUES (17568,'Pasta Per Pizze','Primo','Farina',4,' -','500 G Farina,
25 Cl Acqua Tiepida,
30 G Lievito Di Birra,
1 Cucchiaio Olio D''oliva,
1 Pizzico Sale','Disponete la farina a montagnetta, aperta al centro. Versate nel ''cratere'' il sale, l''olio, il lievito di birra e aggiungete gradualmente l''acqua impastando il tutto con le mani, fino ad ottenere una pasta morbida ed elastica che si stacchi facilmente dal piano. Cospargete di farina la pagnotta così ottenuta, ponetela in una ciotola, copritela con un panno e lasciatela lievitare per due ore, fin quando non sia raddoppiata di volume. Prendete la pasta e lavoratela ancora, schiacciandola accuratamente. Ricordatevi solo di rialzare un po'' il bordo per creare il cornicione, quando stenderete la pasta nella teglia.',1990);
INSERT INTO "ricette" VALUES (17569,'Pasta Per Pizze (2)','Primo','Farina',4,' -','350 G Farina,
100 G Farina Per La Lavorazione,
20 G Lievito Di Birra,
20 Cl Acqua A Temperatura Ambiente,
8 G Sale,
5 G Zucchero,
3 Cucchiai Olio D''oliva','Sciogliete il lievito in una tazza con un poco di acqua della dose, setacciate la farina su di un piano di lavoro, che può essere in legno o in marmo, e disponetela a fontana. Al centro mettete lo zucchero, il sale, l''olio e l''acqua; mescolate gli ingredienti con la punta delle dita. Quando la farina avrà assorbito tutta l''acqua, incorporate poco ala volta il lievito sciolto ed impastate con cura. Quindi lavorate l''impasto con energia a piene mani sollevandolo e sbattendolo sul piano per circa 10 minuti o finché la pasta non si staccherà completamente dalle mani e dal piano di lavoro. A questo punto formate una palla e mettetela in una ciotola fonda leggermente infarinata, coprite tutto con un canovaccio e fate lievitare la pasta in un luogo tiepido (25  gradi circa) per 1/2 ora o finché si sarà raddoppiato il volume. Trascorso tale tempo rimettete la pasta sul piano di lavoro ed impastatela ancora per qualche minuto per interrompere la lievitazione, quindi stendetela ripetutamente con il matterello finché non sarà diventata morbida. A questo punto riformate una palla, lasciatela lievitare per altri 15 minuti, stendetela bene con le mani sino ad ottenere fa grandezza voluta e adagiatela in una teglia precedentemente unta con olio. Nel sistemarla con la punta delle dita fate in modo che risulti più sottile al centro.',2561);
INSERT INTO "ricette" VALUES (17570,'Pasta Per Sablè','Dessert','Mandorle Dolci',6,' -','200 G Farina,
100 G Zucchero,
120 G Burro,
3 Tuorli D''uovo,
70 G Mandorle Dolci,
2 Mandorle Amare,
1 Pizzico Sale','Togliete il burro dal frigorifero e lasciatelo ammorbidire a temperatura ambiente. Sbollentate le mandorle, spellatele e asciugatele per alcuni minuti in forno. Tritatele insieme a metà dello zucchero. Disponete la farina a fontana, al centro mettete il burro ammorbidito, lo zucchero avanzato, i tuorli, le mandorle, un pizzico di sale. Impastate con leggerezza, fatene una palla, avvolgetela nella pellicola trasparente e lasciate riposare per un''ora. Tirate la pasta a sfoglia non tanto sottile e con le formine ritagliate le sagome desiderate. Adagiatele sulla piastra del forno leggermente inumidita e cuocete in forno preriscaldato a 180 gradi per 15 minuti. Ritirate, lasciate raffreddare, staccate i biscottini dalla lastra e serviteli con il tè.',2705);
INSERT INTO "ricette" VALUES (17571,'Pasta Piccante','Primo','Cime Di Rapa',4,'Luogo: Calabria.','350 G Pasta Tipo Orecchiette,
600 G Cime Di Rapa,
4 Cucchiai Olio D''oliva,
4 Acciughe Salate,
2 Spicchi Aglio,
1 Cucchiaio Capperi,
Sale,
Pepe','Lessate le cime di rapa in abbondante acqua per 15 minuti. Poi prelevatele e nell''acqua di cottura fate lessare le orecchiette. Nel frattempo in una casseruola fate scaldare l''olio, rosolatevi l''aglio e le acciughe prima dissalate. Dopodichè unite al condimento le cime di rapa ben scolate e le orecchiette cotte al dente. Pepate e servite subito.',2783);
INSERT INTO "ricette" VALUES (17572,'Pasta Piccante (2)','Primo','Peperoncino Piccante',6,' -','350 G Pasta Tipo Penne,
50 G Burro,
1 Peperoncino Piccante,
4 Cucchiai Concentrato Di Pomodoro,
10 Cl Panna,
1 Bicchierino Vodka,
1 Cucchiaino Brandy,
Formaggio Pecorino Grattugiato,
Sale','Lessare la pasta in abbondante acqua salata. Intanto fondere il burro in un largo tegame a fuoco basso, unirvi il peperoncino a pezzetti e il concentrato di pomodoro e far insaporire. Aggiungere la panna, far sobbollire pochi secondi poi versare 1 bicchierino di vodka e 1 cucchiaino di brandy. Mescolare e versare nel tegame la pasta scolata. Mantecare a fuoco vivo il tempo necessario ad amalgamare la pasta con il sugo e condire con il pecorino.',2517);
INSERT INTO "ricette" VALUES (17573,'Pasta Prelibata','Primo','Pomodoro',4,' -','400 G Pasta Tipo Pasta Corta,
1 Cipolla,
1 Spicchio Aglio,
1 Carota,
1 Zucchina,
1 Costa Sedano,
500 G Pomodori Pelati,
Prezzemolo,
Basilico,
Olio D''oliva,
Formaggio Grana Grattugiato,
Sale,
Pepe','Far soffriggere l''aglio e la cipolla tritati con l''olio, unire la carota, la zucchina e il sedano tagliati a dadini, i pomodori frullati, il prezzemolo e il basilico tritati, il sale, il pepe e far cuocere per circa un''ora. Condire con questo sugo e il grana la pasta cotta al dente.',2630);
INSERT INTO "ricette" VALUES (17574,'Pasta Primavera','Primo','Carote',4,' -','400 G Pasta Tipo Pennette,
3 Carote,
3 Zucchine,
2 Peperoni Rossi,
300 G Fagiolini,
Sale,
Pepe,
Aglio,
Olio D''oliva','Prima prendere i peperoni, lavarli, metterli nel forno e far abbrustolire la pelle; poi pelarli e tagliarli a listerelle. A parte lessare le carote, i fagiolini e le zucchine. Tagliare le carote e le zucchine a rondelle, a pezzetti i fagiolini. Prendere un tegame, mettere olio ed aglio ed aggiungervi tutte le verdure, sale, pepe e far insaporire bene. A parte cuocere le pennette. Quando sono pronte, scolarle ed unirle alle verdure, insaporendo insieme pasta e verdure.',2320);
INSERT INTO "ricette" VALUES (17575,'Pasta Profumata','Primo','Aglio',4,' -','500 G Pasta Tipo Sedani,
1 Spicchio Aglio,
Basilico,
Prezzemolo,
Menta,
Formaggio Pecorino,
Olio D''oliva,
Sale,
Pepe','Far rosolare in una padella l''aglio con l''olio, unire il basilico, il prezzemolo e la menta tritati e far insaporire. Cuocere la pasta in abbondante acqua salata, scolarla al dente, condirla con l''olio alle erbe, spolverizzarla di pepe e pecorino grattugiato e servire.',2805);
INSERT INTO "ricette" VALUES (17576,'Pasta Radicchio E Zucca','Primo','Radicchio',4,' -','350 G Pasta Tipo Pasta Corta,
300 G Zucca,
1 Cespo Radicchio,
1 Scalogno,
5 Cucchiai Olio D''oliva,
Prezzemolo Tritato,
Sale,
Pepe','Pulire la zucca privandola della buccia dei semi e dei filamenti, lavarla e tagliarla a bastoncini; farli scottare per 1 minuto in acqua salata bollente e scolarli. Lavare il radicchio e tagliarlo a listarelle. Tritare lo scalogno e farlo appassire in un tegame con l''olio senza farlo colorire. Unire la zucca e farla rosolare, versare un mestolino d''acqua, salare, pepare e cuocere per 10-15 minuti a fuoco moderato e a tegame coperto. Cinque minuti prima del termine della cottura, unire le listarelle di radicchio e un po'' di prezzemolo tritato. In una pentola portare ad ebollizione abbondante acqua salata e lessare la pasta. Scolarla al dente, condirla con il ragù di zucca e radicchio e cospargere con il rimanente prezzemolo tritato.',1743);
INSERT INTO "ricette" VALUES (17577,'Pasta Rasa','Primo','Formaggio Parmigiano',4,' -','150 G Pangrattato,
150 G Formaggio Parmigiano Grattugiato,
3 Cucchiai Farina Bianca,
3 Uova Intere,
Sale,
Poca Noce Moscata,
100 Cl Brodo Di Carne','Mescolate insieme il pangrattato, il parmigiano, la farina, le uova, il sale e la noce moscata fino ad ottenere un impasto compatto. Grattugiate l''impasto e ponetelo ad asciugare su un tagliere infarinato. Dopo alcune ore smuovete appena per evitare che la pasta si attacchi. Dopo qualche ora potrete versare la ''pasta rasa'' nel brodo in ebollizione, lasciandola cuocere non più di 4/5 minuti. Servitela calda cospargendola con una bella manciata di Parmigiano grattugiato.',1915);
INSERT INTO "ricette" VALUES (17578,'Pasta Reale','Primo','Uova',4,' -','120 G Farina,
70 G Burro,
4 Uova,
30 Cl Acqua,
Sale','Si tratta, in sostanza di una pasta per choux, e si procede in modo identico. Acqua e burro sul fuoco, si aspetta il bollore, si tira via il pentolino e si butta la farina in un colpo solo nel pentolino. Ora mescola bene e rimetti sul fuoco: fa'' cuocere la cosa un pochino a fuoco non molto alto: assomiglia ad un unico polpettone bianco che si attacca al cucchiaio di legno e si stacca dalle pareti? Bene... Vuol dire che è pronto! Mettila in una ciotola e falla raffreddare. Sbatti ora le uova - una ad una - e aggiungile bene (è fondamentale per il gonfiaggio) al polpettone. Prosegui così, per tutte le uova. Prendi una tasca da pasticciere e forma delle palline grosse come nocciole sulla placca del forno coperta da carta forno. Le fai cuocere in forno a circa 180 gradi. Non cuocerle nel brodo: lo scaldi bene e ce le tuffi dentro un attimo prima di servire.',1284);
INSERT INTO "ricette" VALUES (17579,'Pasta Reale (2)','Primo','Uova',4,' -','25 Cl Acqua,
250 G Farina,
4 Uova,
20 G Burro,
Olio D''oliva,
Sale,
Brodo','Portate a bollore l''acqua. Ritirate dal fuoco, versatevi in un sol colpo tutta la farina e mescolate vigorosamente per evitare la formazione di grumi. Ponete di nuovo sul fornello e continuate a mescolare finché la pasta si stacca dalle pareti del recipiente. Incorporatevi i tuorli uno alla volta .In una padella scaldate l''olio e lasciatevi cadere a cucchiaini il composto che si gonfierà formando tante palline leggere. lasciate colorire leggermente. Ritiratele, asciugatele su carta assorbente. Suddividetele nelle fondine, aggiungete brodo bollente e servite.',2061);
INSERT INTO "ricette" VALUES (17580,'Pasta Reale (3)','Dessert','Mandorle Pelate',6,' -','500 G Mandorle Pelate,
1500 G Zucchero,
100 Cl Acqua,
4 Limoni (succo)','Tritate finissime le mandorle con 500 g di zucchero fino a ottenere una farina. Preparare il fondant. Unite in una casseruola lo zucchero rimasto e l''acqua, e portate a ebollizione. Spremete i quattro limoni, e raccoglietene il succo. Fate cuocere a fuoco medio il tutto senza mescolare, per 10 minuti, se non c''è il termometro oppure fino alla temperatura di 115-120 gradi: una goccia fatta cadere in un bicchiere di acqua fredda deve formare una pallina dura. Togliete la casseruola dal fuoco e unite il succo dei limoni. Versate il fondant e la farina di mandorle nell''impastatrice e lavorate con l''uncino a velocità media, fino a ottenere una pasta omogenea. Lasciate raffreddare.',8766);
INSERT INTO "ricette" VALUES (17581,'Pasta Rosa','Primo','Pomodoro',4,' -','500 G Farina,
4 Uova,
1 Cucchiaino Sale,
1 Cucchiaio Olio D''oliva,
3 Cucchiai Concentrato Di Pomodoro','Rompete le uova nel frullatore, aggiungete il concentrato di pomodoro e frullate fino a che la miscela è omogenea. Versate l''olio e 3 cucchiai d''acqua fredda e frullate ancora. Setacciate la farina col sale e disponetela a fontana sulla spianatoia; versatevi al centro la miscela e amalgamate il tutto. Lavorate l''impasto energicamente fino a che diventa sodo (se è troppo molle unite altra farina). Quando avrete ottenuto una palla, lavoratela spingendola e riportandola verso di voi con le mani per 15 minuti fino a che diventa morbida ed elastica. Vi accorgerete di aver terminato l''operazione quando compariranno delle piccole bolle d''aria sulla superficie. Avvolgete la palla in un panno e fatela riposare all''asciutto per almeno 1 ora. Trascorso questo tempo stendetela e ritagliatela a vostro gusto.',2373);
INSERT INTO "ricette" VALUES (17582,'Pasta Rustica','Primo','Fagioli',1,'Ricetta adatta a: bambini piccoli.','2 Cucchiai Pasta Tipo Gemmine,
2 Cucchiai Fagioli Borlotti,
1 Cucchiaino Formaggio Parmigiano Grattugiato,
1 Cucchiaino Olio D''oliva Extra-vergine','Lessate in abbondante acqua i fagioli, precedentemente ammollati. Estraeteli con il mestolo forato e passateli al passaverdure con il disco a fori piccoli direttamente nel piatto. Portate a bollore il brodo di cottura quindi unite la pastina e fate cuocere per qualche minuto. Versate la minestrina amalgamandola alla purea di fagioli. Completate con il formaggio e l''olio d''oliva extra-vergine.',335);
INSERT INTO "ricette" VALUES (17583,'Pasta Rustica Con Fagiolini','Primo','Fagiolini',4,'Preparazione: 5 minuti. Cottura: 20 minuti','220 G Pasta Tipo Farfalle,
250 G Fagiolini Bianchi,
200 G Funghi Champignon,
12 Olive Nere,
6 Pomodori Secchi Tritati Grossolanamente,
1 Spicchio Aglio,
1 Cucchiaio Origano E Maggiorana Secca,
4 Cucchiai Olio D''oliva Extra-vergine,
Pepe,
Sale','Fate saltare in una padella funghi a fettine con l''olio e l''aglio per 10 minuti circa, quindi eliminate l''aglio e unite i pomodori e le olive a filetti. Aggiungete le farfalle lessate al dente in acqua bollente salata, l''origano e la maggiorana e lasciate insaporire un paio di minuti rigirando. Pepate e servite.',1968);
INSERT INTO "ricette" VALUES (17584,'Pasta Sablée','Dessert','Burro',4,' -','200 G Farina,
100 G Burro,
1/4 Cucchiaino Sale,
1 Uovo','Gli ingredienti sono per 300 g di pasta. Tagliate 100 g di burro a dadini. Setacciate 200 g di farina e impastatela con il burro, con la punta delle dita. Sfregate la miscela tra le mani finché prende l''aspetto del pangrattato. Fate una fontana e aggiungete un uovo e 1/4 di cucchiaino di sale. Mescolate rapidamente con le dita fino a ottenere una pasta omogenea. Lasciate riposare la pasta in frigo il più a lungo possibile.',1486);
INSERT INTO "ricette" VALUES (17585,'Pasta Saporita','Primo','Formaggio Fontina',1,' -','100 G Formaggio Fontina Tagliato A Dadini,
100 G Formaggio Parmigiano Reggiano,
1/2 Confezione Panna Da Cucina,
200 G Pasta Tipo Pasta Corta,
Poco Burro,
2 Cucchiai Pangrattato','Sciogliere in una pirofila la panna, la fontina tagliata a dadini e 50 g di parmigiano grattugiato. Nel frattempo far cuocere la pasta e, una volta scolata, versarla nella pirofila con i formaggi. Amalgamare bene il tutto con il restante parmigiano, ricoprire la pasta con fiocchetti di burro e il pangrattato. In ultimo, mettere in forno a gratinare.',1949);
INSERT INTO "ricette" VALUES (17586,'Pasta Sardine E Peperone','Primo','Sardine Sott''olio',4,' -','400 G Pasta Tipo Pennette,
120 G Sardine Sott''olio,
1 Peperone Rosso,
1 Spicchio Aglio,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Arrostire il peperone e spellarlo. Tagliarlo a metà, eliminare i semi e i filamenti e sfilettarlo. Scolare le sardine, aprirle a metà, diliscarle e tagliarle a pezzetti. Rosolare un trito di aglio e prezzemolo in olio. Unire il peperone, lasciarlo insaporire qualche minuto poi unire le sardine e cuocere a fuoco basso. Lessare le pennette, scolarle e versarle nel tegame con il condimento. Alzare la fiamma, mescolare rapidamente e servire.',2602);
INSERT INTO "ricette" VALUES (17587,'Pasta Sfoglia','Dessert','Burro',4,' -','100 G Farina,
100 G Burro,
3 Cucchiai Acqua,
1 Pizzico Sale','Le proporzioni possono variare a seconda se si vogliono sfoglie più magre o no. Preparate la pasta e mantenetela a forma di palla. Preparare una palla con il burro, magari aiutandovi con della carta oleata per non sporcarvi troppo. Ora l''abilità sta nel procurare che sia la pasta che la palla di burro abbiano più o meno la stessa consistenza, lavorando sempre in ambiente fresco (il burro si scioglie facilmente). Nel frattempo che stendete la pasta, mettete in frigo il burro. Stesa la pasta in forma quadrata, prendete la palla di burro e ponetela leggermente schiacciata al centro del quadrato. Piegate il quadrato di pasta ponendo gli angoli sopra la palla di burro, di modo che questo venga racchiuso dalla pasta. Con il mattarello iniziate a stendere in forma rettangolare, facendo attenzione che il burro non si sciolga schizzando fuori dal fazzoletto di pasta. Non cercate di ottenere un rettangolo sottile. Appena risulta sufficiente ad essere piegato in tre parti, ripiegate il rettangolo in modo da ottenere tre strati e mettete in frigo. In una ventina di minuti il burro tra la pasta avrà recuperato consistenza, riprendete quindi il ''libretto'' di pasta e burro, ristendetelo in rettangolo e ripiegatelo in tre, ristendete ancora e ripiegate. A questo punto il burro avrà perso consistenza, quindi è il momento di rimettere il libretto in frigo per un''altra ventina di minuti. Ripetete ancora una volta la sequenza e rimettete in frigo.',1074);
INSERT INTO "ricette" VALUES (17588,'Pasta Sfoglia (2)','Dessert','Burro',4,' -','500 G Farina Bianca 00,
500 G Burro,
10 G Sale Fino','Versate sulla spianatoia 400 g di farina e il sale, fate la fontana e unendo acqua fredda (250-300 g), impastate velocemente, per non scaldare la pasta (in estate è consigliabile tuffare le mani in acqua ghiacciata). Lavoratela energicamente per 7 minuti quindi mettetela nel frigo per circa 20 minuti. Disponete poi 100 g di farina sulla spianatoia ed impastatevi il burro (che non dovrà essere stato appena tolto dal frigo, ma nemmeno tanto molle), fate un panetto, avvolgetelo in carta oleata o in un telo, ponetelo su un piatto e mettetelo in frigorifero, non nel freezer. Con il matterello stendete la prima pasta fatta, formando un rettangolo largo e lungo quanto basta per potervi avvolgere il panetto di burro (se il panetto sarà riuscito rotondo, stendete un disco di pasta, che lo contenga agevolmente). Togliete il panetto dal frigorifero e sistematelo al centro della pasta, indi ripiegate sul burro i quattro lembi della pasta, usando il matterello stendete la pasta e il panetto, badando però di spingere il matterello sempre in avanti (non a destra e a sinistra come si fa con le tagliatelle) facendo così un rettangolo. Se durante questa operazione la pasta si attaccasse alla spianatoia, spolverizzatela leggermente con un poco di farina bianca (mettete farina il meno possibile per non alterare le dosi iniziali). Con il matterello pigiate un poco la pasta al centro (in lunghezza) poi ripiegate le due estremità del rettangolo unendole al centro della pasta, dove è stata premuta, indi ripiegate nuovamente la pasta sovrapponendo le due metà: avrete così la pasta piegata quattro volte. Rigirate il panetto portando il lato destro o il sinistro verso l''alto: stendete di nuovo la pasta sfogliata, sempre spingendo il matterello in avanti, ripiegatela ancora in quattro, avvolgetela in carta oleata, mettetela su un piatto e ponetela in frigorifero per 30 minuti. Dopo che avrà riposato il tempo necessario stendetela per altre due volte ripiegando sempre la pasta in quattro, mettetela in frigorifero (avvolta) per un''altra mezz''ora poi stendetela per altre due volte (sei in tutto) sempre ricordando di spingere il matterello in avanti, badando di toccare il meno possibile la pasta con le mani (sono calde e il burro si scioglie facilmente). Trascorsi gli ultimi 30 minuti di riposo stendete la pasta ancora due volte quindi adoperatela per quanto necessita preparare. Dopo aver confezionato quello che si desidera. lasciate riposare la pasta una decina di minuti. perché cuocendo è meno facile che si sformi. La pasta sfogliata anche in pezzi piccoli, si cuoce in genere in forno a 200 gradi. Ad evitare che si abbassi non scuotete la placca sulla quale è posta e non aprite il forno durante la cottura. Anche se viene impiegata per preparazioni dolci, la ''sfoglia'' non deve mai essere addolcita.',5476);
INSERT INTO "ricette" VALUES (17589,'Pasta Sfoglia (3)','Dessert','Burro',4,' -','250 G Farina,
250 G Burro,
5 G Sale Fino','Disponete la farina sulla spianatoia insieme al sale e a 10 cl d''acqua fredda e cominciate a impastare con la punta delle dita. Quando avrete ottenuto un impasto consistente fatene una palla, avvolgetela nella pellicola e mettetela in frigo per mezz''ora. Trascorso questo tempo, stendetela formando un quadrato di circa 20 cm di lato e al centro ponetevi il burro ammorbidito. Ripiegate gli angoli verso il centro, coprendo il burro e con il matterello stendete ancora la pasta facendo incorporare il burro. Cercate di ottenere un rettangolo e poi piegatelo a libro formando nuovamente un quadrato. Questo è il primo giro di pasta. Dopo 10-15 minuti stendete ancora la pasta, formate un rettangolo e piegatelo a libro formando un altro quadrato e procedete in questo modo fino al sesto giro di pasta (intervallate però il terzo e il quarto ponendo la pasta in frigorifero per mezz''ora). Dopo il sesto giro la pasta è pronta per essere utilizzata.',2681);
INSERT INTO "ricette" VALUES (17590,'Pasta Sfoglia A Quattro Giri','Dessert','Burro',4,'Preparazione: 60 minuti. In frigorifero: 60 minuti.','500 G Farina,
225 G Burro Ben Freddo,
125 G Strutto,
1 Cucchiaio Succo Di Limone,
1/2 Cucchiaino Sale','Gli ingredienti sono per 900 g di pasta. Tagliate il burro freddo a dadini. Setacciate la farina e il sale sopra una ciotola. Aggiungete la metà del burro tagliato e fatelo penetrare nella farina con la punta delle dita fino a ottenere una miscela che assomigli al pangrattato. Scavate un pozzo. Misurate 15 cl di acqua ghiacciata e versatela in mezzo al pozzo, insieme al succo di limone. Girate vigorosamente con un coltello largo portando poco a poco la farina verso il centro del pozzo. Incorporate tutta la farina aggiungendo, se necessario, un po'' di acqua a cucchiaiate, fino a ottenere una palla di pasta nè troppo umida nè troppo asciutta. Posate la pasta sul piano da lavoro leggermente infarinato. Lavoratela con dolcezza per lisciarla. Schiacciate la pasta per ottenere un rettangolo di 40 x 20 cm mantenendo i bordi dritti e gli angoli retti. Se avete lavorato la pasta troppo vigorosamente questa resisterà prima di raggiungere le dimensioni richieste; schiacciatela delicatamente. Con il dorso di un coltello tracciate una riga sulla larghezza del rettangolo delimitandone un terzo. Con l''aiuto di un coltello distribuite la metà dello strutto, in fiocchetti. grandi come una nocciola, sui due terzi di pasta rimanenti fino alla riga tracciata. Lasciate un bordo di 1,5 cm sui tre lati esterni. Piegate il rettangolo in tre: ripiegate il terzo senza materia grassa per primo, poi ricopritelo con il terzo rimanente. Sigillate i bordi con il mattarello o con la mano. Avvolgete la pasta con un foglio di pellicola, poi con un panno umido e mettetela in frigorifero quindici minuti. A questo punto la pasta avrà avuto un giro. Dopo quindici minuti togliete la pasta dal frigorifero e posatela sul piano da lavoro leggermente infarinato, con la piega alla vostra sinistra e il lato lungo sigillato a destra. Stiratela di nuovo fino ad avere un rettangolo di 40 x 20 cm, con movimenti decisi e uniformi, partendo dal centro e andando verso di voi e poi verso l''estremità opposta. Mai sui lati e mai in diagonale. Ripetete l''operazione dei fiocchetti e quella della piegatura utilizzando la metà del burro restante. Sigillate i bordi, avviluppate di nuovo la pasta e riponetela in frigorifero per quindici minuti. È finito il secondo giro Date alla pasta il terzo e il quarto giro con il resto dello strutto per il terzo e il resto del burro per il quarto e ultimo giro, facendola ogni volta riposare in frigo quindici minuti.',3413);
INSERT INTO "ricette" VALUES (17591,'Pasta Sfoglia Classica','Dessert','Burro',8,'Preparazione: 180 minuti.','500 G Farina,
500 G Burro,
2 Cucchiai Succo Di Limone (o Aceto Di Vino Bianco),
1/2 Cucchiaio Sale','Tagliate a dadini 40 g di burro. Setacciate la farina sopra una ciotola fredda; aggiungete il burro e lavoratelo con le dita finché sia ben avvolto dalla farina. Fate un pozzo nel centro. Versate 25 cl di acqua ghiacciata e il succo di limone o l''aceto nel centro del pozzo e lavorate con le mani fino a ottenere una pasta umida ma non appiccicosa. Aggiungete, se necessario, una o due cucchiaiate di acqua ghiacciata. Rovesciate l''impasto su una superficie infarinata e lavoratelo aggiungendo farina sia sul piano da lavoro che sulla palla di pasta, finché quest''ultima non sia più umida. Schiacciate la palla di pasta fino a uno spessore di 3 cm e lasciatela quindici minuti in frigorifero avvolta in un foglio di pellicola. Evitate naturalmente di usare il freezer. Posate il resto del burro su un piano leggermente infarinato e schiacciatelo con le mani fino a farne un rettangolo di 15 x 12 cm. Mettete in frigorifero. Togliete la pasta dal frigo, schiacciatela con le mani sul piano da lavoro infarinato fino a ottenere un rettangolo. Continuate a stirare la pasta, procedendo sempre dal centro verso i bordi. Rettificate i bordi con un righello. Togliete la farina in eccesso dalla superficie della pasta, posate il mattone di burro in mezzo al rettangolo e piegate sopra i quattro bordi. Sigillate i bordi. Fate il primo giro: tirate la pasta fino a ottenere un rettangolo di 38 x 30 cm. Tracciate due righe con il dito per dividere il rettangolo in tre parti, nel senso della lunghezza. Piegate il terzo davanti a voi verso il centro fino alla seconda riga, poi portate sopra il terzo opposto facendo coincidere i bordi. Sigillate i bordi. Girate la pasta di 90 gradi (a questo punto la pasta avrà già avuto un giro). Per il secondo giro abbassate la pasta fino a ottenere un rettangolo di 38 x 30 cm. Tracciate una riga sulla larghezza al centro della sfoglia, poi ripiegate i due lati corti fino a congiungerli sopra il tratto. Piegate quindi una metà sull''altra. Chiudete bene i bordi e girate la pasta di 90 gradi, in modo che la piega si trovi alla vostra sinistra. Lasciate riposare la pasta in frigorifero per almeno quindici minuti, avvolta in un foglio di pellicola per alimenti. Ripetete due volte i due giri nello stesso modo, verificando prima di stirare la pasta che il lato lungo si trovi verso di voi. Questa pasta si congela perfettamente. Schiacciatela un po'' con il mattarello, poi tagliatela con un coltello ben affilato e infarinate il taglio per sigillare il burro. Chiudete la pasta in sacchetti per congelare da 500 o 250 g ed etichettateli.',5365);
INSERT INTO "ricette" VALUES (17592,'Pasta Sfoglia Con Il Bimby','Dessert','Burro',4,' -','150 G Burro Congelato A Pezzi,
150 G Farina,
7 Cl Acqua Gelata,
1 Pizzico Sale','Inserisci tutti gli ingredienti nel boccale: 15 secondi a velocità 6. Stendi la pasta in un rettangolo e ripiegala in 3 parti. Ripeti la stessa operazione altre 3 o più volte (per ogni lato del rettangolo), tirando ogni volta la pasta con il mattarello. È ottima per la preparazione di vol-au-vent, cannoncini, ecc...',1610);
INSERT INTO "ricette" VALUES (17593,'Pasta Sfoglia Con Le Mandorle','Dessert','Mandorle',4,' -','400 G Pasta Sfoglia Surgelata,
60 G Mandorle Pelate,
1 Cucchiaio Zucchero A Velo,
1 Cucchiaio Cacao Amaro,
1 Uovo,
Olio D''oliva','Scongelate la pasta sfoglia e stendetela. Tritate finissime le mandorle. In una ciotola mettete lo zucchero a velo e il cacao, bagnate con due cucchiai d''acqua, mescolate bene e unite le mandorle e l''uovo. Mescolate fino ad ottenere una pastella omogenea. Spalmate il composto, su metà della pasta sfoglia, quindi ripiegate questa su se stessa e premete leggermente. Con una rondella per dolci ritagliate delle ''losanghe''. Fate scaldare l''olio d''oliva e immergetevi i dolci. Quando saranno dorati da una parte girateli dall''altra con una paletta. Appoggiateli sulla carta per fritti per togliere l''unto.',2723);
INSERT INTO "ricette" VALUES (17594,'Pasta Sfoglia Danese','Dessert','Farina',4,'Luogo: Danimarca.','500 G Farina,
1 Pizzico Sale,
50 G Zucchero,
2 Bustine Lievito Per Torte,
15 Cl Latte,
1 Uovo,
150 G Burro','Mescolate la farina con lo zucchero e il sale. Sciogliete il lievito in un po'' di latte freddo. Mettetelo in una casseruola in cui avrete mescolate il resto del latte con l''uovo sbattuto. Unite il composto ottenuto alla farina. Mescolate fino ad ottenere una pasta soffice. Stendete l''impasto su una teglia. Spalmate piccole quantità di burro su due terzi dell''impasto. Piegate, quindi, la pasta in tre strati come se doveste piegare un tovagliolo: prima la parte senza burro e poi le altre. Stendete e piegate di nuovo. Ripetete tre o quattro volte. Lasciate riposare in frigo o in un luogo fresco per mezz''ora. Fate cuocere la pasta in forno fino a quando non diventa dorata.',3131);
INSERT INTO "ricette" VALUES (17595,'Pasta Sfoglia Express','Dessert','Burro',4,'Preparazione: 40 minuti. In frigorifero: 60 minuti.','450 G Farina,
175 G Burro,
1 Cucchiaino Succo Di Limone,
1 Pizzico Sale','Le quantità sono per 500 g di pasta. Setacciate la farina e il sale sopra una ciotola. Tagliate il burro a dadini di 1,5 cm e gettateli nella farina. Aggiungete il succo di limone e 12 cl di acqua ghiacciata, poi mescolate rapidamente fino a ottenere una pasta leggera. Aggiungete, se necessario, uno o due cucchiaiate di acqua. Posate la pasta su una superficie leggermente infarinata e abbassatela a un rettangolo di 30 x 15 cm, mantenendo i lati e gli angoli ben dritti con l''aiuto di un righello. Ripiegate un terzo della pasta verso il centro del rettangolo, poi il terzo restante sopra gli altri due. Sigillate i bordi, fate girare la pasta di 90 gradi. Stirate, piegate e girate la pasta due volte. Avvolgete la pasta in un foglio di pellicola, poi in un panno umido e lasciatela in frigorifero, prima di modellarla.',2758);
INSERT INTO "ricette" VALUES (17596,'Pasta Sfoglia Rapida','Dessert','Burro',6,' -','150 G Farina,
100 G Burro,
1 Pizzico Sale','La pasta sfoglia è una preparazione è una preparazione raffinata e molto impegnativa tanto che, quasi sempre, si preferisce utilizzare quella surgelata. A chi volesse tentare almeno una volta tale esperimento, suggeriamo questa versione semplificata. Impastate 30 g di farina con il burro usando una spatola per evitare che il calore delle mani faccia diventare il composto troppo morbido: infatti, il segreto della buona riuscita della sfoglia è il giusto equilibrio di calore fra i diversi ingredienti. Quando il burro ha assorbito tutta la farina, date alla pasta la forma di un quadrati alto mezzo centimetro. Impastate la restante farina con un po'' d''acqua e un pizzico di sale fino a ottenere un composto morbido, fatene un panetto e adagiatelo al centro del quadrato preparato. Sollevate delicatamente i quattro angoli della pasta e riuniteli al centro coprendo il panetto. Spianate con il matterello fino a ottenere un rettangolo con il lato corto verso di voi. Spostatelo in modo d''avere dalla vostra parte il lato lungo. Sollevate il lato corto di destra e ripiegatelo verso il centro del rettangolo. Fate la stessa cosa con il lato sinistro. Ripiegate ancora la pasta in due su se stessa ottenendo una specie di libro quadrato. Avete così fatto il primo giro di pasta. Con il matterello, spingendo sempre nella stessa direzione, stendete il quadrato fino a trasformarlo in un lungo rettangolo e ripetete le operazioni indicate. Così per quattro volte. Fra un giro e l''altro fate riposare la pasta in frigorifero per 10 minuti. La pasta sfoglia deve cuocere in forno preriscaldato a 200-220 gradi per circa 20 minuti se la preparazione è di piccole dimensioni, un po'' di più per pasticci e torte.',1233);
INSERT INTO "ricette" VALUES (17597,'Pasta Speedy','Primo','Olive Nere',4,' -','100 G Olive Nere,
200 G Tonno,
10 Cl Olio D''oliva,
1 Limone (succo),
Formaggio Galbanino,
Pasta Tipo Qualsiasi,
Sale,
1 Pizzico Pepe','Sgocciolate bene le olive nere, tagliatele a pezzetti, mettetele in una insalatiera. Sbriciolate il tonno e versatelo nelle olive nere poi aggiungete la metà dell''olio, mescolate e lasciate riposare il tutto per 2 ore in frigorifero. Fate lessate la pasta in abbondante acqua salata e scolatela al dente. Unitela al tonno e alla olive nere, mescolate bene e aggiungete un pizzico di pepe, il succo di limone e il resto dell''olio. Mescolate, e servite fredda con guarnizione di cubotti di Galbanino.',3030);
INSERT INTO "ricette" VALUES (17598,'Pasta Tiepida Al Tonno','Primo','Tonno Sott''olio',4,'Preparazione: 15 minuti. Cottura: 10 minuti.','300 G Pasta Tipo Pasta Corta,
150 G Pomodorini,
100 G Mozzarelline,
150 G Tonno Sott''olio Sgocciolato,
4 Foglie Basilico,
1 Pizzico Sale,
Per La Salsa Rosa:,
2 Cucchiai Maionese,
1 Cucchiaio Ketchup','Lavate bene i pomodorini e asciugateli con uno strofinaccio. Lavate delicatamente le foglie di basilico e asciugatele senza strofinarle troppo. Togliete le mozzarelline dal latte di conservazione e asciugatele. Deponete il tonno sgocciolato su un doppio strato di carta assorbente per eliminare l''olio in eccesso. Mescolate la maionese con il ketchup in un''insalatiera. Tagliate le mozzarelline e i pomodorini in 4 parti. Mettete nell''insalatiera i tocchetti di pomodoro. Unite il tonno sbriciolato e le foglie di basilico spezzettate con le dita. Lessate la pasta in abbondante acqua salata e toglietela dal fuoco quando è ancora al dente. Lasciatela scolare e mettetela ancora calda nell''insalatiera. Mescolate bene con la salsina che avete già preparato sul fondo. Assaggiate e aggiungete, se è necessario, un pizzico di sale.',1978);
INSERT INTO "ricette" VALUES (17599,'Pasta Verde','Primo','Spinaci',4,' -','350 G Farina,
3 Uova,
1/2 Cucchiaino Sale,
250 G Spinaci Surgelati','Lessate gli spinaci e poi scolateli, ma non del tutto, e frullateli fino ad ottenere un purè sufficientemente umido. Setacciate la farina con il sale e disponetela a fontana; mettetevi al centro le uova ed il purè di spinaci ed amalgamate il tutto. Lavorate l''impasto energicamente fino a che diventa sodo (se è troppo molle unite altra farina). Quando avrete ottenuto una palla, lavoratela spingendola e riportandola verso di voi con le mani per 15 minuti fino a che diventa morbida ed elastica. Vi accorgerete di aver terminato l''operazione quando compariranno delle piccole bolle d''aria sulla superficie. Avvolgete la palla in un panno e fatela riposare all''asciutto per almeno 1 ora. Trascorso questo tempo stendetela e ritagliatela a vostro gusto.',1457);
INSERT INTO "ricette" VALUES (17600,'Pasta Verde (ricetta Base)','