on un po'' di limone affinché non anneriscano), tagliate infine a dadini anche la polpa degli avocado. Mescolate delicatamente ogni cosa e bagnate ancora il composto con poco succo di limone e qualche goccia d''olio.',1891);
INSERT INTO "ricette" VALUES (12808,'Insalata Ricca','Contorno','Insalata',4,' -','4 Carote,
100 G Mais,
100 G Germogli Di Soia,
2 Cucchiai Salsa Di Soia, Dragoncello,
1000 G Insalata (insalata Lattuga, Insalata Cicoria, Insalata Rucola),
1000 G Peperoni,
500 G Funghi,
1 Cucchiaio Capperi,
6 Cucchiai Olio D''oliva','Lavare le verdure, tagliare a fiammifero le carote e a lamelle i funghi. Unire tutti gli ingredienti in una grande insalatiera trasparente. Sbattere l''olio con la salsa di soia, aggiungere le foglioline fresche di dragoncello spezzettate e condire l''insalata.',3202);
INSERT INTO "ricette" VALUES (12809,'Insalata Ricca (2)','Contorno','Pomodori',8,' -','1000 G Insalate (insalata Lattuga, Insalata Cicoria, Insalata Rucola),
1000 G Pomodori,
1000 G Peperoni,
4 Carote,
500 G Funghi,
100 G Mais,
100 G Germogli Di Soia,
1 Cucchiaino Capperi,
6 Cucchiai Olio D''oliva,
2 Cucchiai Salsa Di Soia,
Dragoncello','Lavare le verdure, tagliare a fiammifero le carote e a lamelle i funghi. Unire tutti gli ingredienti in una grande insalatiera trasparente. Sbattere l''olio con la salsa di soia, aggiungere le foglioline fresche di dragoncello spezzettate e condire l''insalata.',3370);
INSERT INTO "ricette" VALUES (12810,'Insalata Ricca (3)','Contorno','Patate',4,' -','350 G Patate,
2 Uova Sode,
50 G Formaggio Fontina,
6 Ravanelli,
2 Pomodori,
200 G Fagioli Borlotti In Scatola,
1 Spicchio Aglio,
Basilico,
Menta,
Sale,
1 Cucchiaio Aceto Di Vino,
4 Cucchiai Olio D''oliva,
2 Cucchiai Yogurth Bianco','Lessare le patate, pelarle e tagliarle a dadini. Unire i ravanelli a fettine, 1 uovo a spicchi, la fontina a dadini, i fagioli scolati, i pomodori a spicchi e del basilico spezzato con le mani. Mescolare bene. Fare una salsa frullando l''altro uovo con l''aglio, 1 cucchiaio di aceto, 4 di olio, menta, sale, pepe e 2 cucchiai di yogurth bianco. Versare la salsa sull''insalata e servire.',2307);
INSERT INTO "ricette" VALUES (12811,'Insalata Ricca (4)','Contorno','Avocado',4,' -','300 G Palmito In Scatola,
40 G Pinoli,
1 Cespo Insalata Belga Riccia (indivia Riccia),
1 Cespo Insalata Belga Rossa (indivia Rossa),
1 Avocado,
1 Limone,
1 Cucchiaino Salsa Worcester,
Olio D''oliva,
Sale,
Pepe','Sbucciate e snocciolate l''avocado, tagliate la polpa a fettine sottili e spruzzatele con qualche goccia di limone. Mondate e lavate le insalate, tagliate a striscioline l''indivia rossa, spezzettate quella riccia. Raccogliete tutto in un''insalatiera, aggiungete i pinoli e il palmito scolato e tagliato a rondelle. In una ciotola emulsionate l''olio con un cucchiaino di Worcester, succo di limone, sale e pepe. Condite, mescolate e servite. Vini di accompagnamento: Trentino Pinot Grigio DOC, Trebbiano D''Abruzzo DOC, Nuragus Di Cagliari DOC.',1982);
INSERT INTO "ricette" VALUES (12812,'Insalata Ricca (5)','Contorno','Insalata Rucola',6,' -','500 G Insalata Rucola,
200 G Germogli Di Soia,
2 Pomodori Maturi,
60 G Olive Nere,
100 G Porri,
100 G Formaggio Pecorino,
Basilico,
Olio D''oliva Extra-vergine,
Succo Di Limone,
Sale,
Pepe','Lavate la rucola e i germogli di soia, sgocciolateli bene e poneteli in un''insalatiera. Aggiungete i porri tagliati fini, i pomodori a spicchi e senza semi, le olive nere e il pecorino a dadini. A parte emulsionate il succo di limone con il sale, il pepe e l''olio, versate sull''insalata e mescolate con cura. Guarnite con il basilico. Ideale per accompagnare carne alla griglia o uova.',2107);
INSERT INTO "ricette" VALUES (12813,'Insalata Ricca (6)','Contorno','Melanzana',4,' -','1 Melanzana,
1 Peperone Rosso,
1 Peperone Verde,
1 Peperone Giallo,
3 Pomodori Maturi Sodi,
1 Confezione Mais Naturale,
Erba Cipollina,
Olio D''oliva,
Sale,
Pepe','Lavate e asciugate le melanzane. Tagliatele a fette sottili. Spennellatele con l''olio e salatele. Scaldate il grill del forno e fatevi grigliare le melanzane da entrambi i lati fino a quando sono tenere. Spennellatele di olio durante la cottura. Lavate e asciugate i peperoni. Tagliateli a metà, eliminate i peduncoli, i semi e i filamenti bianchi. Tagliate la polpa a listarelle. Scaldate in una padella abbondante olio e friggetevi i peperoni. Scolateli e fateli asciugare su carta assorbente, quindi salateli. Tritate grossolanamente l''erba cipollina. Sbollentate i pomodori per qualche istante in acqua bollente. Scolateli, pelateli e tagliateli a fette. Trasferite melanzane, peperoni e pomodori in una grande insalatiera. Sgocciolate, sciacquate e lasciate sgocciolare di nuovo il mais. Trasferitelo nell''insalatiera. Salate, pepate e irrorate con un filo di olio. Mescolate delicatamente, cospargete di erba cipollina e servite.',1119);
INSERT INTO "ricette" VALUES (12814,'Insalata Ricca (7)','Contorno','Cetriolo',4,' -','1 Cetriolo,
8 Pomodori,
200 G Formaggio Pecorino Non Stagionato,
10 Olive Nere Snocciolate,
Aceto Di Vino,
Olio D''oliva,
Origano,
Pepe,
2 Cipolle','Sbucciare ed affettare il cetriolo, le cipolle e i pomodori e disporli su un piatto da portata. Tagliare a lamelle il pecorino sulle verdure usando l''affettatartufi. A parte sbattere l''olio con l''aceto, il pepe e l''origano. Versare il condimento sull''insalata, guarnire con le olive e servire.',1875);
INSERT INTO "ricette" VALUES (12815,'Insalata Ricca (8)','Contorno','Germogli Di Soia',4,' -','300 G Germogli Di Soia Freschi,
200 G Insalata Lattughino,
2 Zucchine,
1 Avocado,
10 Noci,
150 G Funghi Champignon,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe,
1 Limone','Sbollentare i germogli per 5 minuti. Lavare il lattughino e metterlo in un''insalatiera con i germogli. Aggiungere le zucchine crude tagliate a julienne e la polpa dell''avocado tagliata a cubetti. Sgusciare le noci, tritare grossolanamente i gherigli e aggiungerli all''insalata. Affettare i funghi e unirli al resto. Sbattere il succo del limone con 1/2 bicchiere di olio, sale e pepe e versare la salsina sull''insalata. Mescolare con cura e servire.',2706);
INSERT INTO "ricette" VALUES (12816,'Insalata Ricca (9)','Contorno','Pomodori',4,' -','4 Pomodori Maturi,
1 Peperone Giallo,
1 Cetriolo,
1 Mazzetto Insalata Rucola,
1 Cespo Insalata Lattuga,
1 Cipolla,
4 Ravanelli,
1 Zucchina,
Basilico,
1 Limone,
20 Capperi,
Olio D''oliva,
Sale','Mondare e lavare tutte le verdure e le insalate. Tagliare a spicchi i pomodori. Affettare cipolla, cetriolo, zucchina e ravanelli. Tagliare a julienne il peperone. Spezzettare rucola e lattuga. Mettere tutto in una insalatiera e mescolare. Sminuzzare il basilico e unirlo all''insalata insieme ai capperi. Condire con il succo di limone, olio e sale. Rimescolare ancora e far riposare qualche minuto prima di servire.',1010);
INSERT INTO "ricette" VALUES (12817,'Insalata Rilassante','Contorno','Cipolline Fresche',4,' -','2 Cipolline Fresche,
200 G Avena Lessata,
200 G Tofu (formaggio Di Soia),
3 Patate Lessate,
150 G Insalata Mista (crescione, Insalata Valerianella, Insalata Lattuga),
Alcune Foglie Basilico,
Per La Salsetta:,
Olio D''oliva Extra-vergine,
Sale Marino,
Aceto Balsamico','Preparare la salsa amalgamando gli ingredienti indicati. Lavate e asciugate in un panno le insalate, affettate le cipolline e tagliate le patate a dadini. Mescolate tutti gli ingredienti e condite con la salsa.',1941);
INSERT INTO "ricette" VALUES (12818,'Insalata Rossa Di Melanzane','Contorno','Melanzane',4,' -','1 Peperone Rosso A 4 Punte,
3 Melanzane,
2 Pomodori,
1/2 Cipolla,
12 Noci,
Olio D''oliva,
1/2 Limone,
Prezzemolo,
Sale','Rompere le noci e sminuzzare i gherigli; tritare la cipolla; pelare i pomodori. Spremere il limone. Grigliare le melanzane (circa 20 minuti) e pelarle (meglio raffreddarle in acqua fredda); schiacciarne la polpa con la forchetta e mettere in una ciotola; aggiungere le noci, la cipolla, il limone, l''olio, volendo un po'' di peperoncino, ed il sale; mescolare per amalgamare il tutto. Grigliare il peperone e pelarlo. Unire alle melanzane il peperone ed i pomodori e mescolare bene si può decorare con del prezzemolo spezzettato.',1726);
INSERT INTO "ricette" VALUES (12819,'Insalata Rucola E Speck','Contorno','Insalata Rucola',4,' -','200 G Speck,
2 Mazzetti Insalata Rucola,
2 Patate Lesse,
1 Limone,
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Mondate e lavate la rucola, disponetela in un''insalatiera e aggiungetevi le patate lessate e tagliate a fettine e lo speck a dadini. Mescolando delicatamente condite con olio, limone, sale e pepe.',1339);
INSERT INTO "ricette" VALUES (12820,'Insalata Russa','Primo','Riso',4,' -','2 Carote,
2 Patate,
1 Pezzetto Sedano,
1 Manciata Piselli Abbastanza Grandi,
2 Uova,
1 Bicchiere Olio D''arachidi,
1 Vaso Piccolo Insalata Giardiniera All''aceto Di Vino Bianco,
1 Limone,
Sale,
Pepe,
1 Mazzolino Prezzemolo (per Decorare)','Lessare al dente le carote, le patate, il sedano e i piselli, scolare e lasciare raffreddare; scolare dall''aceto e strizzare le verdure della giardiniera. Preparare la maionese. Tagliare in piccoli pezzi le verdure lessate e quelle della giardiniera. Porre in una ciotola le verdure tagliate e unire un po'' alla volta la maionese tenendone indietro qualche cucchiaio per la ricopertura finale. Amalgamare l''insalata aggiustando di sale. Disporla in un vassoio di portata, ricoprirla con un sottile strato di maionese rimasta, guarnire a piacere.',2022);
INSERT INTO "ricette" VALUES (12821,'Insalata Russa (2)','Antipasto','Fagiolini',4,'Luogo: Russia.','3/4 Patata,
1 Cavolfiore,
200 G Fagiolini,
200 G Piselli,
1 Barbabietola,
50 G Tonno Sott''olio,
Pepe,
Sale,
Olio D''oliva,
Aceto Di Vino,
Besciamella,
Maionese,
Succo Di Limone,
Alcune Fettine Limone,
Alcuni Filetti D''acciughe,
Capperi','Lessate separatamente il cavolfiore, le patate, i fagiolini, i piselli. Sbucciate le patate e la barbabietola e tagliate tutto a pezzetti, unitevi anche un pochino di tonno a pezzetti. Mettete nell''insalatiera e condite questo misto di verdure con olio, sale e poco aceto e in ultimo la maionese che avrete alleggerita con parecchio succo di limone. Unto uno stampo rettangolare da biscotto, mettetevi la verdura premendola col cucchiaio perché resti ben compatta e mettete lo stampo al freddo in ghiaccio per qualche ora. Al momento di servirla, sformerete l''insalata russa sul piatto oblungo e la coprirete con altra maionese ben densa e con giardiniera sott''aceto tagliata a fettine, capperi, filetti di acciughe e fettine di limone.',2395);
INSERT INTO "ricette" VALUES (12822,'Insalata Russa (3)','Contorno','Patate',4,'Luogo: Russia.','200 G Patate,
150 G Carote,
4 Cetriolini Sott''aceto,
1 Manciata Capperi Sott''aceto,
1 Cucchiaino Senape Francese,
Sale,
Pepe Bianco Macinato,
1 Tazza Maionese,
150 G Piselli','Lessare separatamente le carote e le patate tagliate a cubetti e i piselli. Mescolare le verdure cotte e condirle con 2/3 della maionese alla quale si sarà aggiunta la senape. Distribuire in 4 coppe e guarnire con la rimanente maionese, i cetriolini, i capperi e una rondella di uovo sodo.',783);
INSERT INTO "ricette" VALUES (12823,'Insalata Russa (4)','Antipasto','Patate',4,' -','200 G Patate,
100 G Carote,
100 G Fagiolini,
100 G Piselli,
100 G Giardiniera,
30 G Tonno,
25 G Capperi,
4 Uova,
Sale,
Aceto Di Vino','Lessate le verdure in acqua salata e quando saranno fredde, tagliatele a dadini. Aggiungete il tonno, i capperi e la giardiniera. Nel frattempo fate una maionese con 2 uova e poi mischiatela con il composto precedentemente preparato, mischiando bene il tutto e condendo con sale e aceto. Mettete il tutto in un piatto e dategli la forma di piramide. Decorate con maionese, piselli e 2 uova sode tagliate a fette. Lasciate riposare 1 ora prima di servire.',751);
INSERT INTO "ricette" VALUES (12824,'Insalata Russa (5)','Antipasto','Fagiolini',4,' -','150 G Fagiolini,
2 Zucchine,
100 G Piselli Sgranati,
2 Carote,
2 Patate,
50 G Sottaceti,
300 G Maionese,
1 Cucchiaio Capperi Sott''aceto','Lessare le patate. Cuocere al dente a vapore carote e zucchine. Lessare separatamente i piselli per 10 minuti e i fagiolini per 15 minuti. Tritare finemente i capperi e i sottaceti. Ridurre a dadini patate, zucchine e carote e a pezzetti i fagiolini. Riunire le verdure, unire capperi, sottaceti e maionese meno qualche cucchiaio. Disporre su un piatto e decorare con la maionese rimasta.',2936);
INSERT INTO "ricette" VALUES (12825,'Insalata Russa Con Il Bimby','Antipasto','Maionese',4,' -','Maionese,
400 G Patate Medie,
300 G Carote,
300 G Piselli Lessati (o Piselli Surgelati),
60 G Sottaceti Vari,
1 Cucchiaio Capperi,
900 G Acqua,
10 Cl Aceto Di Vino,
Sale','Metti la maionese in una ciotola. Senza lavare il boccale inserisci l''acqua, l''aceto, il sale, le carote tagliate a dadini poi le patate sempre a dadini, i piselli e cuoci per 25 minuti a temperatura 100 gradi velocità 1, per una cottura al dente. Scola molto bene le verdure allargale e lasciale raffreddare. Uniscile alla maionese con i capperi e i sottaceti. Amalgama bene il tutto, e metti in frigorifero prima di servire.',1106);
INSERT INTO "ricette" VALUES (12826,'Insalata Russa Di Sampierdarena','Contorno','Piselli',6,'Luogo: Liguria. Luogo: Genova.','6 Patate,
1 Tazza Maionese,
400 G Piselli Sgranati,
2 Carote,
2 Gambi Sedano,
1 Manciata Olive Verdi,
3 Cetriolini Sott''aceto,
6 Filetti Peperone Sott''aceto','Fate cuocere le patate in acqua bollente salata: sbucciatele e schiacciatele, ancora calde, in una terrina. Incorporate alle patate una tazza di maionese. Unite i piselli lessati, le carote e il sedano lessati e tagliati a pezzettini, le olive snocciolate, i cetriolini e i peperoni sminuzzati. Mescolate bene e delicatamente: disponete poi a cupola l''insalata russa su un piatto e coprite con altra maionese. Potrete decorarla con striscioline di peperone e di cetriolino.',2017);
INSERT INTO "ricette" VALUES (12827,'Insalata Rustica','Contorno','Patate',4,' -','Patate,
Fagiolini,
Fagioli Borlotti,
Cipolla,
Olio D''oliva,
Aceto Di Vino,
Basilico,
Sale','Mescolate le patate bollite e tagliate a dadini con i fagiolini e i fagioli borlotti precedentemente lessati; cospargete con anelli fini di cipolla. Condite con una salsetta di olio, aceto, basilico tritato e sale.',1115);
INSERT INTO "ricette" VALUES (12828,'Insalata Saporita','Contorno','Pomodori',4,' -','5 Pomodori,
2 Coste Sedano,
2 Carote,
1 Zucchina,
2 Cipollotti,
1 Mazzo Basilico,
1 Spicchio Aglio,
4 Cucchiai Olio D''oliva,
1 Cucchiaio Aceto Di Vino,
Sale,
Pepe','Lavare il basilico e frullarlo con 4 cucchiai di olio, 1 di aceto, sale e pepe Strofinare le pareti di un''insalatiera con l''aglio. Tagliare i pomodori a spicchi, le carote e il sedano a julienne, la zucchina e i cipollotti a fettine sottilissime. Mettere tutte le verdure nell''insalatiera e condirle con la salsa al basilico mescolando bene.',1706);
INSERT INTO "ricette" VALUES (12829,'Insalata Sfiziosa','Contorno','Carciofi',4,' -','4 Carciofi,
100 G Formaggio Grana,
2 Limoni,
Olio D''oliva,
Sale,
Pepe Verde','Mondare i carciofi, lavarli, tagliarli a metà e metterli a bagno in acqua fredda con il succo di limone per 30 minuti. Scolarli, asciugarli, affettarli sottilmente e sistemarli in una insalatiera. Sbattere con una forchetta 5 cucchiai di olio con una presa di sale e il succo di mezzo limone. Versare la salsa sui carciofi e mescolare. Al momento di servire aggiungere il formaggio a scaglie sottili e insaporire con una macinata di pepe verde.',1167);
INSERT INTO "ricette" VALUES (12830,'Insalata Sfiziosa (2)','Contorno','Mortadella',4,'Luogo: Umbria.','1 Cestino Radicchio Rosso,
1 Cestino Insalata Riccia,
1 Mazzetto Insalata Rucola,
1 Fetta Spessa Mortadella,
100 G Formaggio Provolone Dolce,
Olio D''oliva Extra-vergine,
Sale','Pulire accuratamente il radicchio rosso e tagliarlo a listarelle. Lavare accuratamente anche le foglie dell''insalata riccia e della rucola, unendole in una insalatiera al radicchio. Preparare dei cubetti di mortadella e di provolone ed unirli alle verdure. Prima di servire condire l''insalata con olio d''oliva extra-vergine e sale a piacere.',2014);
INSERT INTO "ricette" VALUES (12831,'Insalata Sfiziosa Di Soncino','Contorno','Insalata Soncino',6,' -','200 G Insalata Soncino,
1 Melagrana,
Olio D''oliva,
Succo Di Limone,
Sale,
Senape Dolce','In una insalatiera unite il soncino ai semi di melagrana e condite con una vinaigrette a base di olio, succo di limone, sale e senape dolce.',934);
INSERT INTO "ricette" VALUES (12832,'Insalata Siciliana','Contorno','Insalata Rucola',4,'Luogo: Sicilia.','2 Limoni Cedrati,
2 Mazzetti Insalata Rucola,
2 Mazzetti Insalata Soncino,
2 Mazzetti Insalata Cicoria,
Alcuni Ravanelli,
1 Cipollotto,
1 Limone,
1 Tazza Germogli Di Soia,
1 Ciuffo Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Mondate e lavate molto bene la rucola, la cicoria e il soncino. Pulite il cipollotto e i ravanelli e, dopo averli tenuti a bagno in acqua fredda, tagliateli a fettine sottili. Lavate i limoni cedrati, sbucciateli al vivo e tagliateli a rondelle. Mettete il tutto in un''insalatiera e aggiungete i germogli di soia. In una ciotola emulsionate succo di limone filtrato al colino, sale, pepe e aggiungete olio a filo sbattendo con la frusta. Unite alla salsa un ciuffo di prezzemolo tritato e versatela a filo sull''insalata. Mescolate delicatamente e servite subito. Vini di accompagnamento: Bianco Di Custoza DOC, Bianco Di Pitigliano DOC, Etna Bianco DOC.',1218);
INSERT INTO "ricette" VALUES (12833,'Insalata Solare','Contorno','Cavolfiore',4,' -','1 Cavolfiore Lesso,
Alcuni Chicchi Mais Al Naturale,
Alcune Carote,
Maionese,
1 Cucchiaino Senape,
1 Cucchiaino Pasta D''acciughe','Sistemare su un piatto da portata rotondo un cavolfiore lesso (meglio ancora al vapore, ma ci vuole un po'' più di tempo), circondatelo con un giro di chicchi di mais al naturale e terminate con un ultimo giro di fettine di carote tagliate a striscioline sottili (tipo julienne). Dovrebbe risultare un sole stilizzato molto simpatico che potrete accompagnare con una salsa maionese molto liquida alla quale avrete aggiunto un cucchiaino di senape ed un cucchiaino di pasta d''acciughe.',673);
INSERT INTO "ricette" VALUES (12834,'Insalata Stuzzicante','Contorno','Insalata Lattuga',6,' -','1 Insalata Lattuga,
1 Mazzo Ravanelli,
1 Cipollotto,
1 Pomodoro Verde,
1 Gambo Sedano,
1 Peperone Giallo,
1 Peperone Verde,
1 Tuorlo D''uovo Sodo,
1 Ciuffo Prezzemolo,
1 Cucchiaino Senape Forte,
Peperoncino Rosso,
Alcuni Cucchiai Olio D''oliva,
Sale,
Pepe,
Aceto Di Vino','Mondate e lavate le verdure in abbondante acqua fresca. Scolatele bene. Tagliate la lattuga a striscioline, affettate il cipollotto, tagliate i ravanelli molto sottili con il tagliatartufi, il sedano a pezzetti, i peperoni a listarelle e il pomodoro a fettine. Mettete tutte le verdure in un''insalatiera. Preparate il condimento sbattendo in una terrina l''aceto con il tuorlo d''uovo tritato, la senape, il sale, il peperoncino e il prezzemolo tritati e alcuni cucchiai di olio. Versate sulle verdure e mescolate bene.',1725);
INSERT INTO "ricette" VALUES (12835,'Insalata Super','Contorno','Sedano Bianco',4,' -','4 Coste Sedano Bianco,
1/2 Sedano Rapa Tagliato A Julienne,
1 Mela Acidula,
50 G Formaggio Emmenthal,
8 Olive Verdi Snocciolate,
Olio D''oliva,
Succo Di Limone,
Sale,
Pepe','Tagliare a fettine sottili il sedano bianco, unire il sedano rapa, la mela affettata sottile, il formaggio a bastoncini e le olive tagliate a metà. Condire con olio, succo di limone, sale e pepe.',1118);
INSERT INTO "ricette" VALUES (12836,'Insalata Svedese','Primo','Filetti D''aringa Affumicati',4,'Luogo: Svezia.','200 G Filetti D''aringa Affumicati,
200 G Carne Di Vitello Lessata,
2 Patate Bollite,
2 Mele Verdi Dolci,
1 Barbabietola Cotta,
1 Cipolla,
Alcune Foglie Insalata Lattuga,
Per Guarnire:,
Maionese,
1 Uovo Sodo Tritato,
Capperi,
Olive Verdi','Tagliate a pezzetti i filetti d''aringa e a dadini la carne di vitello, le patate, le mele sbucciate e la barbabietola. Versate il tutto in una terrina e poi aggiungetevi anche la cipollina a fette sottili, mescolate bene. Mettete in frigo e lasciate riposare per tutta la notte. Al momento di servire ricoprite il fondo di un piatto di portata con delle foglie tenere di lattuga, mescolate all''insalata la maionese sufficiente per amalgamare bene tutti gli ingredienti e versatela sulla lattuga. Guarnite a piacere con ciuffetti di maionese, uovo sodo tritato, capperi e olive verdi.',1936);
INSERT INTO "ricette" VALUES (12837,'Insalata Terra E Mare','Antipasto','Funghi Porcini',4,' -','400 G Gamberi Precotti Già Sgusciati,
200 G Funghi Porcini,
1 Cespo Insalata Belga (indivia),
8 Cucchiai Olio D''oliva Extra-vergine,
1 Limone (succo),
Sale,
Pepe','Pulite l''insalata e tagliatela piuttosto sottile. Disponetela sul fondo di una insalatiera. Lavate i gamberi in acqua bollente, fateli scolare e metteteli nell''insalatiera. Pulite i funghi, tagliateli a fettine sottili e aggiungeteli ai gamberi e all''insalata. Preparate il condimento frullando il succo di limone con l''olio, il sale e un po'' di pepe, versatelo nell''insalatiera a filo, senza mescolare gli ingredienti.',1792);
INSERT INTO "ricette" VALUES (12838,'Insalata Thai Di Mango Verde','Contorno','Mango Verde',4,'Luogo: Thailandia.','500 G Mango Verde Pelato Grattugiato,
2 Cucchiai Gamberetti Secchi Messi A Mollo In Acqua,
2 Cucchiai Olio D''oliva,
7 Spicchi Aglio Finemente Tritato,
2 Peperoncini Occhio D''uccello Sbriciolati,
20 G Carne Di Maiale Macinata,
2 Cucchiai Salsa Thai Di Pesce,
1 Cucchiaino Zucchero,
1/2 Tazza Foglie Di Basilico,
2 Cucchiai Arachidi Tostate Sbriciolate,
1/2 Tazza Foglie Di Coriandolo','Rimuovere l''eccesso di liquido dal mango con una carta assorbente. Togliere ogni parte dura dai gamberi e asciugarli accuratamente. Rosolare velocemente l''aglio, facendo attenzione a non bruciarlo; aggiungere i gamberi e il peperoncino. Unire e mescolare la carne macinata di maiale, la salsa thai di pesce e lo zucchero. Togliere il tutto da fuoco. Tagliare le foglie di basilico in un recipiente, incorporare il maiale, l''aglio, il mango, le arachidi, le foglie di coriandolo e sistemare il tutto su un piatto da portata. Servire con riso cotto la vapore.',1246);
INSERT INTO "ricette" VALUES (12839,'Insalata Tiepida Con Pollo, Ananas E Pomodorini','Pollame','Pollo',4,' -','200 G Pollo,
1 Ananas,
1 Limone,
4 Pomodorini,
5 Asparagi,
Olio D''oliva,
Salsa Di Soia,
Sale,
Pepe','Tagliare a tagliatelle il pollo e scottarlo in padella con olio e salsa di soia. Tagliare l''ananas a millepunti, i pomodori a cubetti; tagliare gli asparagi pelati a becco di flauto e rosolarli velocemente in padella con olio e sale. Unire il tutto in modo armonico e servire con un''emulsione di olio, succo di limone ed ananas, sale e pepe.',1678);
INSERT INTO "ricette" VALUES (12840,'Insalata Tiepida Di Cavolfiore','Contorno','Cavolfiore',4,' -','1 Cavolfiore Medio-piccolo,
2 Uova,
3 Cucchiai Olio D''oliva Extra-vergine,
1 Cucchiaio Aceto Aromatico Di Vino Rosso,
Sale Marino,
4 Grani Pepe','Far rassodare le uova ed estrarne il tuorlo. Lavare il cavolfiore, dividerlo in cimette e lessarlo a vapore molto al dente; tenerlo in caldo in una insalatiera dopo averlo cosparso di sale e 4 grani di pepe. Preparare una emulsione con olio, aceto aromatico, tuorlo e poca acqua. Condirvi il cavolfiore.',980);
INSERT INTO "ricette" VALUES (12841,'Insalata Tiepida Di Gamberetti E Moscardini','Antipasto','Gamberetti',4,' -','400 G Moscardini,
400 G Gamberetti,
50 G Porri,
6 Cucchiai Olio D''oliva Extra-vergine,
10 G Pinoli,
1/2 Limone,
1/2 Bicchiere Vino Bianco,
5 G Peperoncino,
Basilico,
Prezzemolo,
Sale','Per l''insalata: in una casseruola lessare i moscardini per 20 minuti. Scolarli e metterli da parte. Prendere il porro, tagliarlo a rondelle e farlo soffriggere in padella con 2 cucchiai di olio d''oliva. Aggiungere i pinoli e farli imbiondire per 5 minuti, quindi versare i moscardini e i gamberetti pelati. Spadellare per qualche minuto, bagnare con il vino bianco, salare, mettere il peperoncino a pezzetti e lasciar cuocere per 10 minuti. Nel frattempo, tritare alcune foglie di prezzemolo e basilico, mescolarle in una tazza con l''olio rimanente e il succo di 1/2 limone. Sbattere bene l''emulsione con una forchetta e lasciarla riposare. Per servire: una volta lasciato intiepidire, sistemare il pesce spadellato su un piatto e condirlo con il composto di olio, limone, prezzemolo e basilico.',1329);
INSERT INTO "ricette" VALUES (12842,'Insalata Tiepida Di Patate','Contorno','Patate',4,' -','1 Mestolo Fagioli Lamon Già Lessati,
2 Patate Medie,
1 Mazzetto Insalata Rucola,
2 Cucchiai Olio D''oliva Extra-vergine,
2 Coste Sedano Bianco,
Prezzemolo Tritato,
Aceto Balsamico,
Sale Marino','Lessare le patate, pelarle e ancora calde metterle in una insalatiera. Unirvi i fagioli caldi, la rucola e il sedano tritati finemente. Condire con sale, aceto e olio e cospargere di prezzemolo tritato. Servire tiepida con pane casereccio leggermente abbrustolito.',973);
INSERT INTO "ricette" VALUES (12843,'Insalata Tiepida Di Polipo','Antipasto','Polipetti',4,'Preparazione: 20 minuti. Cottura: 80 minuti.','800 G Polipetti,
1 Cipollina,
1/2 Bicchiere Aceto Di Vino Bianco,
1 Foglia Alloro,
200 G Piselli Sgranati,
400 G Patate Non Farinose,
Menta,
Basilico,
1 Limone (succo),
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Controllate ogni tanto la cottura dei polipi pungendoli all''attaccatura dei tentacoli con uno spiedino. Pulite i polipi e strofinateli a lungo sotto l''acqua corrente, quindi lasciateli scolare. In una capace casseruola fate bollire 2 litri circa dì acqua con la cipolla affettata, l''aceto, l''alloro e poco sale. Aggiungete i polipi, coprite e fateli sobbollire un''oretta o fino a quando sono teneri. Lasciateli intiepidire nell''acqua dì cottura, spellateli e tagliateli a pezzetti. Nel frattempo, lessate a parte i piselli. In un altra casseruolina cuocete le patate intere e con la buccia, poi spellatele, fatele intiepidire e tagliatele a cubetti. Riunite in una ciotola polipi, patate e piselli e condite con l''olio emulsionato con il succo filtrato del limone, poco sale e una buona presa dì pepe. Aggiungete qualche foglia di basilico e di menta spezzettate e mescolate con cura. Servite l''insalata tiepida.',1675);
INSERT INTO "ricette" VALUES (12844,'Insalata Tiepida Di Pollo','Pollame','Pollo',4,' -','600 G Petti Di Pollo,
50 G Cedro Candito,
50 G Uvetta Sultanina,
50 G Noci Sgusciate,
50 G Pinoli Tostati,
50 G Carote In Agrodolce,
200 G Insalatine (radicchio Rosso, Riccia),
Olio D''oliva,
Aceto Balsamico,
Succo Di Limone,
Sale,
Pepe,
200 Cl Brodo Di Pollo','Dopo avere pulito i petti di pollo se ne fanno filetti, che si cuociono nel brodo di pollo a una temperatura non superiore a 80 gradi per 3 o 4 minuti; si tolgono dal fuoco e si fanno riposare per 20 minuti. Preparare le insalatine sui piatti e disporre il cedro, le noci, l''uvetta, i pinoli e le carote. Con l''olio, il limone, l''aceto balsamico, sale e pepe si prepara la salsa e si condisce l''insalata. Tagliate i petti e disponeteli sopra l''insalata e condite con la salsa rimasta.',2976);
INSERT INTO "ricette" VALUES (12845,'Insalata Tiepida Di Punte D''asparagi, Sedano E Tartufo','Contorno','Asparagi',4,' -','400 G Asparagi,
200 G Sedano Bianco,
100 G Insalata Rucola,
1 Tartufo Bianco,
50 G Pomodori,
3 Cucchiai Succo Di Limone,
5 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Lavate bene gli asparagi, privateli della parte bianca e fateli lessare, in una asparagiera, per 25-30 minuti, finché le punte non saranno tenere; quindi tagliate le punte e lasciatele intiepidire. Nel frattempo preparate le altre verdure: tagliate il sedano a striscioline sottilissime, il tartufo a scaglie, mondate e lavate la rucola, tagliate i pomodori sbucciati a filetti, versate queste verdure in un''insalatiera e condite con la vinaigrette preparata con l''olio, il sale, il pepe e il succo di limone. Servite gli asparagi tiepidi accompagnati dall''insalata mista di tartufi.',647);
INSERT INTO "ricette" VALUES (12846,'Insalata Tiepida Di Quaglie','Pollame','Quaglie',4,' -','2 Quaglie Pronte Per La Cottura,
Sale,
Pepe Bianco,
2 Rametti Timo,
2 Cucchiai Olio D''oliva,
1 Cucchiaio Semi Di Sesamo,
80 G Foglie Di Portulaca,
1 Piccolo Cuore Insalata Riccia,
8 Pomodorini Ciliegia,
Per La Vinaigrette:,
2 Cucchiai Aceto Di Vino Bianco,
1/2 Cucchiaino Senape Piccante,
Sale,
Alcuni Grani Pepe Rosa,
1 Cucchiaio Cipollotti Tritati,
4 Cucchiai Olio D''oliva,
1 Peperoncino','Cospargete le quaglie con sale e pepe e inserite nella cavità addominale un rametto di timo. Fate scaldare l''olio in un tegame e rosolatevi le quaglie a fuoco vivo da ogni lato, fino a quando saranno dorate in modo uniforme. Cospargetele con i semi di sesamo e passatele in forno (200 gradi) per 20-25 minuti. Nel frattempo lavate e asciugate l''insalata e i pomodorini, quindi tagliate questi a metà. Quando le quaglie sono pronte, lasciatele intiepidire leggermente, poi dividetele in quarti e mettetele in quattro piatti individuali, insieme all''insalata e ai pomodorini. In una ciotolina mescolate tutti gli ingredienti per la vinaigrette, quindi versatela sulla carne e sulla verdura e servite.',2336);
INSERT INTO "ricette" VALUES (12847,'Insalata Tiepida Di Seppie Con Asparagi Verdi','Pesce','Seppie',6,' -','300 G Asparagi Verdi,
500 G Seppie,
1 Cucchiaio Prezzemolo Tritato,
1 Spicchio Aglio,
1 Cucchiaino Coriandolo Macinato,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate le punte degli asparagi e il gambo in pezzetti di circa 5 centimetri e tagliateli per il lungo. Sbollentateli in acqua salata. Scolateli e passateli sotto un getto d''acqua fredda. Tagliate le seppie a striscioline sottili e insaporitele in una padella con tre cucchiai d''olio. Salate e pepate, aggiungete un cucchiaio di prezzemolo tritato, uno spicchio d''aglio, un cucchiaino di semi di coriandolo e infine gli asparagi. Mescolate tutti gli ingredienti molto velocemente e ritirate il recipiente. Passate sul piatto da portata e servite questa insalata tiepida. Vini di accompagnamento: Isonzo Bianco DOC, Torgiano Chardonnay DOC, Castel Del Monte Pinot Bianco DOC.',1459);
INSERT INTO "ricette" VALUES (12848,'Insalata Tricolore','Contorno','Peperoni',4,' -','4 Peperoni,
Alcuni Fili Erba Cipollina,
1 Limone,
Olio D''oliva,
Sale,
Pepe,
8 Foglie Vite','Ridurre i peperoni a julienne finissima e conservarli in un recipiente a chiusura ermetica. 1/4 d''ora prima di servire, condire i peperoni con il succo di limone, olio, sale e pepe. A piacere porre una cucchiaiata di questa insalata su 8 foglie di vite (o di fico o più semplicemente di lattuga). Sminuzzare sopra i peperoni l''erba cipollina (in sostituzione si può usare il basilico) e servire.',857);
INSERT INTO "ricette" VALUES (12849,'Insalata Tropicale','Contorno','Avocado',4,'Preparazione: 20 minuti.','1 Scatola Palmito,
1 Avocado Maturo,
3 Piantine Insalata Belga (indivia),
100 G Formaggio Groviera,
2 Uova,
Olio D''oliva,
Aceto Di Vino,
Sale,
Pepe','Sgocciolate il palmito e tagliatelo in rondelle che raccoglierete in una ciotola o in una insalatiera, pulite (scartando le eventuali foglie esterne sciupate), lavate bene le piante di indivia belga e poi tagliatele in rondelle, tagliate a bastoncini il groviera, rassodate le uova, fatele raffreddare sotto l''acqua fredda e tagliatele a fette non troppo sottili; condite con olio, sale, pepe e aceto mescolando in una tazza il condimento e facendo una salsina. Per ultimo aggiungete l''avocado che taglierete in due e scaverete con uno scavino formando delle palline, oppure con un cucchiaino da caffè formando delle scaglie. Mescolate delicatamente e servite.',1652);
INSERT INTO "ricette" VALUES (12850,'Insalata Tutta Fresca','Contorno','Insalata Lattuga',1,' -','130 G Insalata Lattuga,
65 G Pomodori,
50 G Ravanelli,
50 G Arance,
5 G Succo Di Limone,
15 G Formaggio Caprino,
5 G Senape,
Pepe','Fare una salsa con il succo di limone, la senape, il succo d''arancia, il formaggio e il pepe. Tagliare le verdure e condirle con questa salsa.',115);
INSERT INTO "ricette" VALUES (12851,'Insalata Valeriana Con Barbabietole Rosse E Tonno Al Sesamo','Contorno','Insalata Valeriana',4,' -','150 G Insalata Valeriana,
2 Barbabietole Rosse,
200 G Tonno,
1 Cucchiaio Aceto Di Vino,
Olio D''oliva Extra-vergine,
Semi Di Sesamo,
Sale','Salare e cospargere di sesamo il tonno a cubetti. Saltare a fuoco vivace per 2 minuti. Sistemare la valeriana al centro dei piatti e cospargerla con una dadolata di barbabietole. Condire con il succo delle barbabietole mescolato con olio, sale, aceto. Servire con sopra il tonno tiepido.',1340);
INSERT INTO "ricette" VALUES (12852,'Insalata Valesio','Contorno','Ravanelli',4,' -','Ravanelli,
Insalata Rucola,
Germogli,
Formaggio','Unire ravanelli a fettine sottili, rucola e germogli di soia. Aggiungere il formaggio a scagliette come i tartufi, anziché a dadini.',379);
INSERT INTO "ricette" VALUES (12853,'Insalata Variopinta','Contorno','Carote',4,' -','1/2 Sedano Rapa,
2 Carote,
Insalata Lattuga,
Insalata Rossa Di Chioggia,
1 Peperone Giallo Sott''olio,
12 Cipolline Sott''aceto,
Alcuni Cucchiai Yogurth Intero,
1 Cucchiaio Senape,
1 Spruzzo Salsa Worcester,
Succo Di Limone,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Porre in un''insalatiera il sedano rapa e le carote tagliate a julienne, unire le insalate e il peperone a listarelle e le cipolline tagliate a metà. Diluire con lo yogurth la senape, unire la worcester, un po'' di succo di limone, l''olio, sale e pepe e condire l''insalata.',1326);
INSERT INTO "ricette" VALUES (12854,'Insalata Variopinta (2)','Contorno','Insalata Lattuga',4,' -','3 Cuori Insalata Lattuga,
1 Mazzetto Insalata Rucola,
2 Pomodori Rossi,
2 Carote,
5 Cucchiai Olio D''oliva,
1 Cucchiaino Aceto Di Vino,
1 Cucchiaino Senape Dolce,
Sale','Lavare e mondare l''insalata, la rucola e i pomodori. Raschiare le carote, spuntarle e ridurle a julienne, usando l''apposito utensile. Tagliare l''insalata e la rucola a pezzetti di 3 cm circa e ridurre i pomodori a spicchi. In un''insalatiera disporre le carote al centro, la lattuga e la rucola tutt''intorno e, sopra questa, gli spicchi di pomodori, a corona. In 1 ciotola mescolare 5 cucchiai d''olio, 1 cucchiaino d''aceto e 1 di senape, sale. Portare l''insalata in tavola con il condimento a parte.',613);
INSERT INTO "ricette" VALUES (12855,'Insalata Variopinta (3)','Contorno','Cavolfiore',4,' -','200 G Cavolfiore,
80 G Prosciutto Cotto (fette Da 80 G),
2 Carote,
2 Pomodori,
1 Peperone,
1 Cipollotto Fresco,
1 Zucchina,
1 Petto Di Pollo Bollito,
1 Uovo,
12 Olive Verdi E Olive Nere,
1 Cespo Insalata,
Olio D''oliva Extra-vergine,
1 Limone','Rassodate l''uovo, raffreddatelo sotto l''acqua corrente e pelatelo. Bollite per circa 10 minuti il cavolfiore mondato lavato e tagliato a cimette, poi scolatelo. Lessate le carote e la zucchina. Mondate e lavate le verdure, tagliate a listerelle il peperone, a spicchi i pomodori, a fettine sottili le carote lesse e la zucchina, affettate il cipollotto. Tagliate a listerelle anche il petto di pollo e a dadini il prosciutto. Riunite in un''insalatiera tutti gli ingredienti compresi l''uovo sbriciolato (il bianco tritato grossolanamente), l''insalata e le olive. Condite con olio, succo di limone e sale.',1863);
INSERT INTO "ricette" VALUES (12856,'Insalata Verdure E Formaggio','Contorno','Radicchio Di Treviso',4,' -','300 G Radicchio Di Treviso,
200 G Insalata Cicoria,
100 G Formaggio Emmenthal,
50 G Formaggio Gorgonzola,
1 Spicchio Aglio,
1 Cucchiaio Senape,
Aceto Di Vino,
Pochissimo Brandy,
Olio D''oliva,
Sale,
Pepe','Lavare e asciugare le verdure. Strofinare l''interno di un''insalatiera con l''aglio sbucciato. Versarvi le verdure spezzettate con le mani. Aggiungere i formaggi tagliati a dadini. In una ciotola preparare una salsa con la senape, pochissimo brandy, aceto di vino, olio, sale e pepe. Emulsionarla bene e versarla sull''insalata. Mescolare con cura e servire.',1418);
INSERT INTO "ricette" VALUES (12857,'Insalata Volvox','Contorno','Sedano Rapa',4,' -','1 Sedano Rapa,
Alcune Carote,
Alcune Noci,
Alcune Mele Renette,
Maionese,
Sale,
Limone','Scottare il sedano rapa in acqua salata bollente per 10 minuti, lasciarlo raffreddare e poi tagliarlo a julienne (bastoncini). Tagliare a julienne anche le carote, le mele a fettine. Mescolare infine tutti gli ingredienti.',1146);
INSERT INTO "ricette" VALUES (12858,'Insalata Waldorf','Contorno','Cavolo Cinese',2,'Preparazione: 20 minuti. Calorie: 511.','1/2 Cavolo Cinese,
1 Carota,
50 G Gherigli Di Noci,
1 Gambo Sedano,
1 Mela Piccola,
10 G Uvetta Sultanina,
100 G Tofu,
3 Cucchiai Olio D''oliva,
1/2 Cucchiaino Semi Di Sesamo','Abbrustolite in forno i gherigli e spezzettateli. Tagliate il cavolo a striscioline. Spuntate la carota alle estremità e tagliatela a bastoncini. Fate lo stesso con il sedano, dopo averlo mondato dei filamenti. Sbucciate la mela e dividetela a spicchi sottili. Fate rinvenire l''uvetta in acqua tiepida. In una ciotola schiacciate il tofu con la forchetta, unitevi l''olio e i semi di sesamo. Dovrete ottenere una salsina cremosa, ben amalgamata. Riunite tutti gli ingredienti preparati in un''insalatiera, condite con la salsa al tofu, mescolate delicatamente e servite.',1698);
INSERT INTO "ricette" VALUES (12859,'Insalata Waldorf (2)','Contorno','Sedano',4,' -','300 G Cuori Di Sedano,
2 Mele,
75 G Nocciole Non Tostate,
1 Limone,
Maionese,
Sale,
Pepe','Lavare i cuori di sedano. Lavare le mele, eliminare i semi e non sbucciarle. Tagliare sedano e mele a dadini e farli macerare nel succo di limone per 1 ora. Scolarli e condirli con poco pepe e maionese quanto basta. Cospargere con le nocciole tritate e tenere in frigo prima di servire.',1114);
INSERT INTO "ricette" VALUES (12860,'Insalata Waldorf Astoria','Contorno','Mele Renette',4,' -','250 G Mele Renette,
250 G Sedano Bianco,
70 G Mandorle Pelate,
6 Cucchiai Maionese,
1/2 Limone (succo),
Sale','Scottare il sedano tagliato a dadini per 2 minuti in acqua salata, poi scolarlo e passarlo sotto l''acqua fredda; metterlo poi a riposare in frigo per un''ora con le mele, anch''esse a dadini, il limone ed un po'' di sale. All''ultimo, aggiungere la maionese e le mandorle sfilettate. Mescolare 3/4 delle mandorle all''insalata ed usare le altre da mettere sopra.',1517);
INSERT INTO "ricette" VALUES (12861,'Insalata Waldorf Astoria (2)','Contorno','Mela',4,' -','1 Mela,
Insalata Lattuga,
Noci,
Formaggio Emmenthal,
Olio D''oliva,
Sale,
Succo Di Limone','Sbucciare la mela e tagliarla a pezzetti, spremervi su un po'' di succo di limone per non farla annerire. Lavare la lattuga e tagliarla a pezzetti. Spezzettare le noci sgusciate. Tagliare a cubetti l''emmenthal. Mescolare gli ingredienti e condire con olio e sale.',1858);
INSERT INTO "ricette" VALUES (12862,'Insalata Waldorf Astoria (3)','Contorno','Sedano Rapa',4,' -','250 G Sedano Rapa,
250 G Mele Renette,
60 G Mandorle (o Nocciole),
6 Cucchiai Maionese,
1/2 Limone (succo),
Pepe,
Sale','Riducete a dadini il sedano, quindi tuffatelo per qualche minuto in acqua salata in ebollizione, scolatelo, passatelo sotto il getto dell''acqua fredda e scolatelo di nuovo. Sbucciate le mele, tagliatele a dadini come il sedano e mettete entrambi gli ingredienti in una terrina con il succo di limone e poco sale. Lasciate riposare per circa un''ora, poi unite la maionese, sbriciolate tre quarti delle mandorle, sale e pepe. Rigirate accuratamente e disponete l''insalata in un piatto di servizio. Decorate la superficie con le altre mandorle e servite in tavola.',1445);
INSERT INTO "ricette" VALUES (12863,'Insalatina Ai Capperi','Contorno','Capperi',4,' -','1 Carota,
1 Mazzo Tarassaco,
1 Finocchio,
1 Cespo Insalata Lattuga Riccia,
Olio D''oliva,
2 Cucchiai Capperi,
Basilico,
Aceto Di Vino,
Sale','Mondate, lavate bene le insalate e tagliatele a strisce sottili. Tagliate la carota a julienne e il finocchio lavato a fettine sottilissime. Riunite il tutto in un''insalatiera. In una ciotola emulsionate l''olio con l''aceto e il sale. Unite i capperi dissalati e il basilico spezzettato. Condite l''insalata, mescolate e servite.',837);
INSERT INTO "ricette" VALUES (12864,'Insalatina Con Cetrioli','Contorno','Cetrioli',4,' -','Cetrioli,
Carote,
Olio D''oliva,
Succo Di Limone,
Sale','Affettare i cetrioli con la buccia e unirli alle carote tagliate a julienne, all''olio, al succo di limone e al sale.',792);
INSERT INTO "ricette" VALUES (12865,'Insalatina Di Alici Marinate','Antipasto','Acciughe Freschissime',4,' -','500 G Acciughe Freschissime,
40 G Insalata Soncino,
20 Olive Nere Taggiasche,
2 Limoni (succo),
Olio D''oliva,
Prezzemolo Tritato,
Sale,
Pepe Bianco','Pulite le acciughe, sciacquatele e asciugatele con carta da cucina. Dopo aver preparato la marinata con il succo di limone, l''olio e un po'' di prezzemolo tritato, adagiatevi le acciughe aperte: le lascerete così per 15 minuti. Condite quindi a parte il soncino, con una leggera vinaigrette di olio, limone e poco sale. Aggiungete le olive denocciolate. Disponete infine l''insalata in ogni piattino singolo, con sopra le acciughe a raggiera',1648);
INSERT INTO "ricette" VALUES (12866,'Insalatina Di Asparagi','Contorno','Asparagi',4,' -','1000 G Asparagi Sottili,
4 Uova,
Prezzemolo,
Olio D''oliva,
1 Pizzico Sale,
Succo Di Limone,
1 Pizzico Pepe','Lessate gli asparagi in acqua salata e scolateli. Rassodate le uova, sgusciatele, togliete i tuorli e sbriciolateli. Disponete gli asparagi sul piatto da portata, cospargete sulla superficie i tuorli sbriciolati, irrorate versando l''olio a filo, spruzzate con il succo di limone, spolverizzate con un pizzico di pepe e uno di sale. Servite.',1331);
INSERT INTO "ricette" VALUES (12867,'Insalatina Di Bianchetti','Antipasto','Bianchetti',4,' -','500 G Bianchetti,
1/2 Limone,
4 Cucchiai Olio D''oliva,
Sale,
Pepe Bianco','Lavate i bianchetti con attenzione e a lungo perché contengono molta sabbia. Sbollentateli pochi minuti in acqua salata. Scolateli con molta cura e lasciateli raffreddare. In una ciotola emulsionate l''olio con il succo del limone filtrato al colino, insaporite con sale e un pizzico di pepe bianco. Versate tutto sui bianchetti, mescolate. Dopo 10 minuti servite. Vini di accompagnamento: Riviera Ligure Di Ponente Vermentino DOC, Bianchello Del Metauro DOC, Bianco D''Alcamo DOC.',1850);
INSERT INTO "ricette" VALUES (12868,'Insalatina Di Finocchi Alla Romana','Contorno','Finocchio',4,'Luogo: Lazio. Luogo: Roma.','1 Finocchio,
10 Foglie Menta Fresca,
5 Olive Nere,
Sale,
Pepe,
Olio D''oliva Extra-vergine','Lavare e pulire i finocchi, tagliarli sottili alla julienne e condire con olio emulsionato con mentuccia e olive nere.',804);
INSERT INTO "ricette" VALUES (12869,'Insalatina Di Maggio','Contorno','Insalata Belga (indivia)',4,' -','2 Cespi Insalata Belga (indivia),
2 Mazzetti Insalata Valerianella,
1 Finocchio,
1 Mazzetto Insalata Rucola,
150 G Germogli Di Soia,
20 Olive Nere Snocciolate,
1 Limone,
3 Cucchiai Olio D''oliva,
Sale,
Pepe Nero','Lavare e asciugare tutte le verdure. Tagliarle finemente e disporle nell''insalatiera. Mondare il finocchio e tagliarlo a fettine sottili. Affettare a rondelle le olive. Unirli alle insalate. Condire con il succo di limone, 3 cucchiai di olio, sale e pepe. Mescolare accuratamente e servire.',1911);
INSERT INTO "ricette" VALUES (12870,'Insalatina Di Polipo E Rucola','Antipasto','Polipo',6,' -','800 G Polipo,
2 Mazzetti Insalata Rucola,
30 G Pinoli,
1 Limone,
1/2 Bicchiere Vino Bianco Secco,
1 Cucchiaino Sale Grosso,
1/2 Mela,
Olio D''oliva,
Sale,
Pepe Nero','In una pentola mettete poca acqua, aggiungete il vino e il pepe in grani. Portate a bollore, unite il sale grosso e immergetevi il polipo pulito e lavato. Lasciate sul fuoco fino a quando i tentacoli più grossi cedono alla puntura della forchetta. Spegnete e lasciate raffreddare il polipo nella sua acqua per almeno 20 minuti. Nel frattempo lavate la rucola, spezzettatela, mescolatevi i pinoli, la mela sbucciata e tagliata a cubetti, il polipo sgocciolato, spellato con cura e tagliato a pezzettini. In una ciotola preparate una salsa emulsionando olio, succo di limone filtrato al colino, sale e pepe e conditevi il polipo. Vini di accompagnamento: Lison Pramaggiore Pinot Grigio DOC, Bianco Delle Colline Lucchesi DOC, Etna Bianco DOC.',1407);
INSERT INTO "ricette" VALUES (12871,'Insalatina Di Pollo','Pollame','Pollo',4,' -','1 Petto Di Pollo,
3 Coste Sedano,
4 Cetriolini Sott''aceto,
1 Cuore Insalata Lattuga,
1 Tazza Maionese,
1/2 Bicchiere Panna,
1 Cucchiaio Ketchup,
1 Cucchiaio Brandy,
Sale','Tagliare a filetti il petto di pollo lessato, mescolarlo con il sedano affettato, i cetriolini tagliati a rondelle e un cuore di lattuga a listarelle. Amalgamare la maionese con il ketchup, la panna, il brandy e il sale, versare sull''insalatina, mescolare e servire.',1128);
INSERT INTO "ricette" VALUES (12872,'Insalatina Di Pompelmo Rosa','Contorno','Pompelmo Rosa',4,' -','1 Pompelmo Rosa,
100 G Insalata Valerianella,
1 Cespo Insalata Belga (indivia),
1 Mazzetto Insalata Rucola,
1 Limone,
Olive Infornate,
Sale Marino,
Mandorle Tostate','Lavare le insalatine e centrifugarle; disporle nella insalatiera sminuzzando la rucola con le mani. Sbucciare con cura il pompelmo eliminando le parti bianche; tagliarlo a dadini e unirlo al resto nell''insalatiera. Spremere il limone, unirvi il sale e l''olio ed emulsionare ottenendo una salsina; condirvi l''insalata. Unire le mandorle.',880);
INSERT INTO "ricette" VALUES (12873,'Insalatina Di Ravanelli','Contorno','Ravanelli',4,' -','Ravanelli Con Foglie Tenere,
Olio D''oliva,
Sale,
Alcune Gocce Aceto Balsamico','Affettare i ravanelli con le loro foglie più tenere, condirli quindi con olio, sale e alcune gocce di aceto balsamico.',714);
INSERT INTO "ricette" VALUES (12874,'Insalatina Di Rucola E Pomodori','Contorno','Insalata Rucola',4,' -','Insalata Rucola,
Pomodori,
Olio D''oliva Extra-vergine,
Sale','Unire alla rucola i pomodori, l''olio e il sale e mescolare bene.',750);
INSERT INTO "ricette" VALUES (12875,'Insalatina Di Scampi E Fichi','Antipasto','Scampi',4,' -','500 G Scampi,
4 Pomodori Perini,
4 Fichi,
4 Cucchiai Olio D''oliva,
1 Melone,
1/2 Limone,
1/2 Pompelmo,
1 Mazzetto Insalata Rucola,
Tabasco,
Sale,
Pepe','Lessate gli scampi, sgusciateli e metteteli da parte. Lavate i pomodori, eliminate i semi, spellateli, frullateli con il succo di limone, il succo di pompelmo, alcune gocce di tabasco, sale e pepe. Versate la salsina in una ciotola, aggiungete l''olio a filo. Con l''apposito scavino ricavate dalla polpa del melone una quarantina di palline. Sbucciate i fichi e tagliateli con un coltello bagnato e molto affilato in quattro spicchi. Componete ora i piattini singoli ponendo al centro la rucola e disponendo a raggiera i fichi, le code di scampi e le palline di melone. Prima di servire condite con abbondante salsa. Vini di accompagnamento: Alto Adige Sauvignon DOC, Colli Bolognesi Sauvignon DOC, Castel Del Monte Sauvignon DOC',2575);
INSERT INTO "ricette" VALUES (12876,'Insalatina Primaverile','Contorno','Carciofi',4,'Preparazione: 15 minuti.','Carciofi,
Succo Di Limone,
Carotine,
Formaggio Emmenthal,
Sale,
Pepe,
Olio D''oliva Extra-vergine','E'' una preparazione delicata che si serve come contorno, ma può anche figurare tra gli antipasti di magro, o in una cena fredda. Mondate i carciofi, metteteli per qualche tempo a bagno in acqua acidulata con succo di limone perché non anneriscano; sgocciolateli, scartate tutte le parti legnose o pungenti e poi affettateli sottilmente. Raschiate e lavate le carotine e grattugiatele con l''apposita grattugia a fori larghi in modo da ottenere delle asticciole simili a fiammiferi. Con lo stesso attrezzo grattugiate pure l''emmenthal. Riunite i tre ingredienti in una ciotola, condite con sale, pepe e olio extra vergine e portate subito in tavola.',1162);
INSERT INTO "ricette" VALUES (12877,'Insalatina Profumata','Contorno','Carciofi',4,' -','6 Carciofi Freschissimi,
600 G Filetto Di Manzo Tritato,
100 G Insalatina Tenera A Foglie Piccole (insalata Soncino, Insalata Rucola, Insalata Riccia),
2 Cipollotti,
2 Limoni,
50 G Formaggio Parmigiano,
1 Cucchiaino Senape Forte,
Erba Cipollina,
Olio D''oliva Extra-vergine,
Alcune Gocce Aceto Balsamico,
Sale,
Pepe Bianco In Grani','Eliminate il gambo e le foglie esterne più dure dei carciofi. Tagliateli a metà, togliete il fieno e immergeteli in una ciotola con acqua fredda acidulata con il succo di un limone. Mondate, lavate e sgocciolate l''insalata e i cipollotti. Affettate sottilmente i cipollotti. Emulsionate qualche cucchiaio d''olio con la senape, il sale, una macinata di pepe e l''erba cipollina tagliuzzata fine. Separatamente, preparate il condimento per l''insalata con un poco di succo di limone, sale, pepe e 4 cucchiai d''olio. Sgocciolate i carciofi, asciugateli e affettateli molto sottili. Mescolateli all''insalata, unite i cipollotti e condite con la salsina preparata. Aggiungete qualche goccia di aceto balsamico e una leggera macinata di pepe. Insaporite la carne di manzo tritato con il condimento alla senape e distribuitela al centro dell''insalata. Cospargete il tutto con piccole scaglie di parmigiano e portate subito in tavola.',1810);
INSERT INTO "ricette" VALUES (12878,'Insalatina Selvatica Di Primavera','Contorno','Porro Selvatico',4,' -','Porro Selvatico,
Borraggine,
Raponzolo,
Crescione,
Finocchietto,
Pimpinella,
Mentuccia,
Insalata Rucola,
Uova Sode,
Succo Di Limone,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Raccogliere o acquistare presso mercatini rionali dai contadini le erbette di campo; lavarle, scrollarle delicatamente eliminando l''acqua e accomodarle in una insalatiera. Unire le uova sode a spicchi. Condire con sale, pepe, succo di limone e olio e servire.',1098);
INSERT INTO "ricette" VALUES (12879,'Insalatona Deliziosa','Contorno','Cavolo Cappuccio',4,'Luogo: Lazio.','150 G Foglioline Di Spinaci Novelli (tenerissime),
100 G Germogli Di Grano,
100 G Germogli Di Soia,
100 G Cavolo Cappuccio,
1 Carota,
1 Peperone,
1 Ciuffetto Prezzemolo,
1 Cucchiaio Aceto Aromatico,
Alcuni Cucchiai Olio D''oliva,
1 Presa Sale,
1 Macinata Pepe','Lavate a lungo sotto l''acqua corrente tutte le verdure (dopo aver raschiato la carota); poi asciugatele con carta assorbente da cucina. Riducete cavolo e peperone a strisciolini sottili con l''apposito utensile e grattugiate la carota. Mettete gli ingredienti preparati in una insalatiera e unitevi le foglie di spinaci intere e i germogli di soia e di grano. Preparate quindi un''emulsione con qualche cucchiaio di olio, l''aceto, il prezzemolo tritato, una presa di sale e una macinata di pepe. Versate la salsa preparata sull''insalata, mescolate delicatamente e portate subito in tavola.',1945);
INSERT INTO "ricette" VALUES (12880,'Insalatona Invernale','Contorno','Carota',4,' -','1 Carota,
1 Cespo Insalata Belga (indivia),
1 Cespo Insalata Trevisana,
1 Patata Lessata,
1 Cespo Insalata Lattuga,
50 G Pancetta Affumicata,
2 Cucchiai Gherigli Di Noci,
2 Cucchiai Formaggio Grana A Scaglie,
2 Cucchiai Aceto Di Vino,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate la pancetta a cubetti e fatela rosolare in una padella antiaderente per 3 minuti senza aggiungere condimento. Le carote vanno grattugiate, la patata lessata tagliata a dadi. Pulite le insalate e tagliatele piuttosto fini. Mescolate tutto in una insalatiera insieme con i gherigli tritati e la pancetta rosolata. Per condire, fate emulsionare 2 cucchiai di aceto, 4 cucchiai d''olio, sale e pepe. Mescolate ancora e servite dopo aver aggiunto le scaglie di grana.',2339);
INSERT INTO "ricette" VALUES (12881,'Insalatona Jolly','Contorno','Insalata Rucola',1,' -','130 G Insalata Rucola,
40 G Radicchio Verde,
65 G Pomodori,
25 G Carote,
25 G Porri,
25 G Mais,
65 G Tonno In Scatola Sgocciolato,
65 G Gamberi,
1 Goccio Olio D''oliva Extra-vergine,
Succo Di Limone','Pulire e lavare tutte le verdure, tagliarle e condirle con un goccio di olio d''oliva extra-vergine. Unire il tonno e i gamberetti, il succo di limone e mescolare il tutto.',355);
INSERT INTO "ricette" VALUES (12882,'Insolita Insalata','Contorno','Insalata Lattuga',4,' -','1 Cuore Insalata Lattuga,
2 Gambi Sedano,
1 Cetriolo,
2 Pomodori,
1 Mela Granny Smith,
1/2 Banana,
Maionese','Lavare le verdure. Spezzettare la lattuga e affettare finemente tutte le altre verdure, la mela e la banana e mescolare il tutto in un''insalatiera. Condire con la maionese.',644);
INSERT INTO "ricette" VALUES (12883,'Integralini','Dessert','Germe Di Grano',4,' -','80 G Germe Di Grano,
40 G Zucchero Semolato,
40 G Burro Freschissimo,
4 Cucchiai Latte,
2 Tuorli D''uovo,
1/2 Bustina Vaniglina,
1 Pizzico Sale,
Per La Placca:,
Poco Burro,
Poca Farina','Le dosi sono per 24 biscottini. Mescolate in una ciotola il germe di grano, lo zucchero, la vaniglina e un pizzico di sale; fate la fontana e mettetevi al centro il latte freddo, i due tuorli, il burro ammorbidito ed a fiocchetti. Impastate alla perfezione e quando avrete ottenuto un impasto liscio ponetelo in una tasca di tela impermeabile munita di bocchetta rotonda liscia; su una placca imburrata e infarinata formate delle ''Z'' piuttosto chiuse, distanziando una dall''altra. Passate i biscotti in forno già caldo a 190 gradi per circa 10 minuti; staccateli poi dalla placca e metteteli a raffreddare su carta bianca da cucina. Anche se in questo caso si usa solamente il germe di grano, senza aggiunta di farina, i biscottini risultano lo stesso sodi.',1296);
INSERT INTO "ricette" VALUES (12884,'International Coffee','Bevande','Caffè',1,' -','2 Caffè Bollenti Zuccherati,
3 Cucchiai Gran Liquore Mammuth,
1 Cucchiaio Amaretto Dell''orso,
2 Cucchiai Panna Montata,
1 Spruzzo Tropical Blu Fabbri,
1 Ciliegina Rossa (facoltativa)','Si prepara direttamente nel ballon (ben riscaldato con acqua bollente) versando per primo il caffè, poi i due liquori, quindi aggiungete la panna montata e fresca, infine, goccia a goccia, versate il Tropical Blu Mixybar.',440);
INSERT INTO "ricette" VALUES (12885,'Internazionale','Bevande','Cognac',1,' -','1/2 Cognac,
1/2 Chartreuse,
2 Spruzzi Succo D''ananas,
2 Spruzzi Gin,
Per Servire:,
1 Scorzetta Di Limone','Si prepara nel miscelatore con ghiaccio tritato e si serve con una scorzetta di limone.',432);
INSERT INTO "ricette" VALUES (12886,'Internazionale (2)','Bevande','Gin',1,' -','1/3 Vermouth Dry,
2/3 Gin,
1 Cucchiaio Pernod,
Per Servire:,
2 Chicchi Caffè','Agitare, con poco ghiaccio in cubetti, nel mixer. Servire nel calice basso, con due chicchi di caffè.',376);
INSERT INTO "ricette" VALUES (12887,'Intingolo Di Melanzane','Contorno','Melanzane',4,' -','2 Melanzane Grandi,
1 Peperone Rosso,
1 Cipolla Gialla Piccola Tritata,
4 Pomodori A Dadolata,
1 Spicchio Aglio Tritato,
Pepe Nero Da Macinare Fresco,
Sale','Disporre le melanzane su una vecchia teglia da forno per biscotti. Metterla sul fuoco basso, girando ogni tanto le melanzane e facendole arrostire per circa 30 minuti. Fate abbrustolire la pelle e fate cuocere la polpa. Togliete le verdure dalla teglia e fatele raffreddare. Pelatele. Schiacciate bene la polpa con una forchetta o fate passare delicatamente nel mixer. Mentre le melanzane sono sul fuoco, fate soffriggere in una padella antiaderente la cipolla e il peperone. Mescolate tutti gli ingredienti, anche l''aglio e il pepe, con la polpa di melanzana. Servite caldo, a temperatura ambiente o freddo sui crostini.',226);
INSERT INTO "ricette" VALUES (12888,'Intingolo Di Melanzane (2)','Contorno','Melanzane',4,' -','3 Melanzane,
1 Peperone Rosso,
1 Cipolla Gialla Piccola Tritata,
3 Pomodori A Dadolata,
1 Spicchio Aglio Tritato,
Pepe Nero Da Macinare Fresco,
Sale','Disporre le melanzane su una vecchia teglia da forno per biscotti. Metterla sul fuoco basso, girando ogni tanto le melanzane e facendole arrostire per circa 30 minuti. Fate abbrustolire la pelle e fate cuocere la polpa. Togliete le verdure dalla teglia e fatele raffreddare. Pelatele. Schiacciate bene la polpa con una forchetta o fate passare delicatamente nel mixer. Mentre le melanzane sono sul fuoco, fate soffriggere in una padella antiaderente la cipolla e il peperone. Mescolate tutti gli ingredienti, anche l''aglio e il pepe, con la polpa di melanzana. Servite caldo, a temperatura ambiente o freddo sui crostini.',254);
INSERT INTO "ricette" VALUES (12889,'Intrigoni','Dessert','Grappa',4,' -','600 G Farina,
3 Uova,
3 Cucchiai Grappa,
3 Cucchiai Zucchero,
3 Cucchiai Olio Di Semi,
1 Bustina Vaniglia','Montare a neve gli albumi. Preparate la sfoglia impastando gli ingredienti. Tiratela molto sottile e tagliatela a nastrini ai quali darete la forma desiderata. Friggete gli intrigoni in olio di semi.',3167);
INSERT INTO "ricette" VALUES (12890,'Invasion','Bevande','Rum',1,' -','1/6 Succo Di Limone,
1/6 Apricot Brandy,
1/6 Cognac,
3/6 Rum,
Per Servire:,
1 Fetta Limone,
1 Foglia Insalata Verde','Scuotere nello shaker con ghiaccio tritato. Servire nel gotto alto, con una fetta di limone e una foglia d''insalata verde.',306);
INSERT INTO "ricette" VALUES (12891,'Involtini Ai Carciofi','Carne','Vitello',4,' -','500 G Fesa Di Vitello A Fettine,
100 G Pancetta,
4 Carciofi,
1 Spicchio Aglio,
1 Rametto Rosmarino,
1 Limone,
1 Mestolo Brodo,
1/2 Bicchiere Vino Bianco Secco,
2 Cucchiai Olio D''oliva Extra-vergine,
50 G Burro,
Sale,
Pepe','Mondate i carciofi e tagliateli a spicchi ponendoli in acqua acidulata con il succo del limone. Battete le fettine di carne e pareggiatele tutt''intorno il più possibile e ponete su ciascuna una fettina di pancetta e un paio di spicchi di carciofo. Spolverizzate con un pizzico di sale e pepe e avvolgete su se stesse le fettine in modo da ottenere degli involtini. Infilzate ogni involtino con un paio di stecchini per evitare che si aprano durante la cottura. Fate rosolare in una padella lo spicchio d''aglio con il burro, l''olio e il rosmarino, unite gli involtini e fateli dorare da tutte le parti. Bagnateli con il vino, lasciatelo evaporare quindi cuocete gli involtini per un''oretta a fuoco basso e a recipiente coperto, bagnandoli con un poco di brodo caldo e rigirandoli di tanto in tanto.',1829);
INSERT INTO "ricette" VALUES (12892,'Involtini Ai Carciofi (2)','Carne','Vitello',4,' -','400 G Fesa Di Vitello In Fettine,
150 G Prosciutto Cotto,
2 Carciofi Puliti,
60 G Burro,
Sale','Stendere sopra ogni fetta di carne una fettina di prosciutto e unire uno spicchio di carciofo già scongelato. Arrotolare e legare con il filo apposito. Far rosolare gli involtini nel burro. Salarli e bagnarli ogni tanto con qualche cucchiaino di acqua. Servirli caldi con il loro fondo di cottura, oppure freddi, coperti di gelatina.',1472);
INSERT INTO "ricette" VALUES (12893,'Involtini Ai Due Sapori','Carne','Maiale',4,' -','300 G Fesa Di Vitello,
300 G Lonza Di Maiale,
100 G Pancetta,
100 G Prosciutto,
50 G Formaggio Groviera,
Vino Bianco Secco,
Salvia,
Rosmarino,
Semi Di Finocchio,
Burro,
Margarina,
1 Dado','Battete bene le fettine di fesa e di lonza, senza romperle, ripulitele dagli eventuali nervetti o dal grasso. Sulle fettine di fesa mettete una fettina di pancetta, una foglia di salvia e una strisciolina di groviera; sulle fettine di lonza mettete una fettina di prosciutto cotto, una foglia di salvia e due semi di finocchio. Formate degli involtini che chiuderete con due stuzzicadenti o se preferite con un pezzo di spago da cucina. In un largo tegame fate sciogliere il burro e la margarina con un rametto di rosmarino e uno di salvia. Non appena il condimento sarà sciolto, aggiungete gli involtini, facendoli rosolare molto bene e rigirandoli per farli colorire da tutti i lati. Bagnate con mezzo bicchiere di vino bianco secco, pepate e lasciate cuocere lentamente per almeno 30-40 minuti. Durante la cottura, tenete la carne morbida con un dado e acqua calda. Mettete il tegame sul fuoco, aggiungendo una tazza di caffè di acqua e lasciandolo scaldare molto dolcemente. Fate addensare il sughetto di cottura e servite con un purè.',3813);
INSERT INTO "ricette" VALUES (12894,'Involtini Al Bacon','Antipasto','Bacon',4,' -','8 Cespi Insalata Trevisana,
8 Tronchetti Di Salsiccia,
8 Fette Bacon,
4 Cucchiai Passato Di Pomodoro,
3 Cucchiai Brodo Di Verdure,
Sale,
Pepe,
1 Spicchio Aglio,
1 Cucchiaio Olio D''oliva','Far imbiondire in una pirofila l''aglio nell''olio d''oliva, unire il pomodoro, il brodo, sale e pepe e cuocere per 6'', quindi eliminare l''aglio. Porre al centro di ogni cespo di insalata un pezzo di salsiccia e avvolgerli in fette di bacon. Sistemarli nella pirofila, coprire con alluminio e cuocere in forno caldo per 25 minuti. Infine passare sotto il grill.',7029);
INSERT INTO "ricette" VALUES (12895,'Involtini Al Burro E Salvia','Carne','Vitello',4,' -','500 G Fesa Di Vitello A Fettine Sottili,
100 G Mortadella,
70 G Formaggio Fontina Affettato,
1 Cucchiaio Prezzemolo Tritato,
1 Rametto Rosmarino,
40 G Burro,
Vino Bianco Secco,
Olio D''oliva,
Sale,
Pepe','Salate e pepate leggermente le fette di carne. Tagliate le fette di mortadella a metà. Stendete su ogni fettina di carne mezza fetta di mortadella e una fettina di fontina, quindi spolverizzatele con un po'' di prezzemolo tritato. Arrotolate le fettine su se stesse badando che gli ingredienti della faccia non sbordino dalla carne, e fermatele con uno stuzzicadenti, oppure legatele con un filo bianco. Mettete al fuoco il burro con qualche cucchiaiata di olio e il rametto di rosmarino appena saranno caldi, fatevi rosolare gli involtini rigirandoli spesso. Salateli, pepateli, spruzzateli, non appena si presenteranno ben coloriti, con mezzo bicchiere di vino bianco e fatelo evaporare. Togliete a questo punto il rosmarino per evitare che, seccandosi, le foglioline si perdano nel sughetto. Gli involtini impiegheranno a cuocere 15 minuti circa. Serviteli subito in tavola decorando i bordi del piatto con delle fettine di carote lessate alternate con dei pisellini cotti nel burro.',2225);
INSERT INTO "ricette" VALUES (12896,'Involtini Al Cartoccio','Contorno','Spinaci',4,' -','500 G Spinaci,
8 Fettine Formaggio Fuso,
4 Fette Prosciutto Cotto,
1/2 Cipolla,
Vino Bianco Secco,
Salvia,
Erba Cipollina,
Burro,
Panna,
Sale,
Pepe','Mondate e lavate gli spinaci. Battete leggermente le fettine, quindi disponete su ciascuna una fetta di prosciutto cotto e una foglia di salvia. Arrotolate le fettine formando degli involtini che fisserete con degli stecchini di legno. Tritate la cipolla finemente, fatene appassire metà in un tegame e metà in un altro, sempre con una noce di burro. Dopodichè, in un tegame fate rosolare gli involtini, bagnate con mezzo bicchiere di vino, salate, pepate. Nell''altro tegame stufate gli spinaci, versando alla fine 2/3 cucchiai di panna(o anche del latte) per legare. Sistemate in un cartoccio gli spinaci, adagiatevi gli involtini, cospargetevi con filo di erba cipollina tagliuzzata e richiudetelo. Passate in forno caldo a 180 gradi per una decina di minuti.',2410);
INSERT INTO "ricette" VALUES (12897,'Involtini Al Praga','Antipasto','Prosciutto Cotto Di Praga',4,' -','300 G Prosciutto Cotto Di Praga,
50 G Pistacchi,
150 G Formaggio Philadelphia','Servendovi di un mixer, tritate grossolanamente i pistacchi e versateli in una terrina. Subito dopo, aggiungete il formaggio e mescolate fino a quando non avrete ottenuto un composto omogeneo. Disponete le fettine di prosciutto su di un piano e farcitele con la cremina ottenuta. Arrotolatele su se stesse e fermatele con uno stecchino, dopodichè, cuocete il tutto in forno già caldo per circa 5 minuti e servite.',1986);
INSERT INTO "ricette" VALUES (12898,'Involtini Al Prosciutto','Antipasto','Prosciutto',1,' -','30 G Formaggio Emmenthal,
300 G Patate,
1 Uovo,
120 G Prosciutto Cotto,
Sale,
1 Cucchiaino Burro','Far lessare le patate con la buccia, pelarle e passarle con lo schiacciapatate. In una terrina unire le patate, l''uovo, il sale e amalgamare bene. Prendere le fette di prosciutto cotto, riempirle con il composto ottenuto e arrotolarle. Adagiare gli involtini in una pirofila precedentemente imburrata e cospargerli con l''emmenthal a scaglie. Infornare per mezz''ora circa.',1124);
INSERT INTO "ricette" VALUES (12899,'Involtini Al Prosciutto (2)','Antipasto','Prosciutto Cotto',4,' -','300 G Prosciutto Cotto Di Praga A Fette,
50 G Pistacchi,
150 G Formaggio Morbido (formaggio Philadelphia O Formaggio Robiola)','Dalle fette di prosciutto cotto, ricavate delle striscioline di circa 4 x 8 cm. Subito dopo, sgusciate i pistacchi, tritateli e lavorateli in una terrina con il formaggio fino ad ottenere un composto omogeneo. Disponete le striscioline di prosciutto cotto su un piano da lavoro, farcitele con il composto e arrotolatele su se stesse fermandole con uno stecchino. Infine, servitele.',2112);
INSERT INTO "ricette" VALUES (12900,'Involtini Al Prosciutto Con Il Bimby','Carne','Vitello',6,' -','600 G Magatello Di Vitello (12 Fettine Molto Sottili),
30 G Formaggio Parmigiano,
100 G Prosciutto Crudo,
Prezzemolo,
Basilico,
5 Cl Acqua,
450 G Pomodori Pelati,
1/2 Spicchio Aglio,
40 G Olio D''oliva,
Sale,
Pepe','Inserisci nel boccale il prezzemolo, il basilico, l''aglio e il parmigiano: 10 secondi a velocità 9. Con questo trito farcisci ogni fetta di carne, aggiungendo una fettina di prosciutto e poco sale. Forma degli involtini e sistemali in piedi nel cestello unto di olio. Metti nel boccale l''olio, i pomodori, l''acqua, il sale e il pepe; inserisci il cestello e cuoci per 20 minuti a temperatura 100 velocità 4 e 10 minuti a temperatura Vroma velocità 4. Disponi gli involtini sul piatto di portata e servili con il loro sugo.',1566);
INSERT INTO "ricette" VALUES (12901,'Involtini Al Prosciutto Cotto E Carciofi','Contorno','Carciofi',6,' -','600 G Filetto Di Vitello,
200 G Prosciutto Cotto,
3 Carciofi A Spicchi,
80 G Burro,
Sale','Tagliare il filetto a piccole fette, assottigliarle con il batticarne. Stendere sopra ognuna una fettina di prosciutto cotto e 1 spicchio di carciofo. Arrotolare e legare con un filo. Mettere gli involtini in 1 tegame con il burro e farli rosolare. Salarli e ogni tanto bagnarli con qualche cucchiaino d''acqua e far finire di cuocere. Servirli caldi con il loro fondo di cottura.',2030);
INSERT INTO "ricette" VALUES (12902,'Involtini Al Radicchio E Provolone Piccante','Contorno','Radicchio',4,' -','250 G Pezza Di Manzo,
2 Cespi Radicchio,
100 G Formaggio Provolone Piccante,
1/2 Cipolla,
2 Cucchiai Vino Bianco,
1/2 Bicchiere Panna,
Olio D''oliva,
Sale,
Pepe','Tagliare il radicchio e cucinarlo al burro. Formare degli involtini con le fettine di carne, il radicchio ed il provolone tagliato a bastoncini e fermarli con uno stuzzicadenti. In un tegame imbiondire la cipolla tritata, aggiungere gli involtini e rosolarli. Bagnare col vino e far evaporare. Aggiungere le panna, lasciar ridurre, regolare di sale e di pepe e servire.',1675);
INSERT INTO "ricette" VALUES (12903,'Involtini Al Salmone','Antipasto','Salmone Affumicato',4,' -','12 Fette Salmone Affumicato (fette Non Troppo Grandi),
100 G Salmone Affumicato In Ritagli,
200 G Formaggio Robiola,
200 G Formaggio Quark (tipo Philadelphia),
1 Mazzetto Erba Cipollina,
1 Cespo Radicchio Di Treviso,
1 Spolverata Noce Moscata,
1 Pizzico Pepe Nero,
1 Filo Olio D''oliva,
1 Spruzzata Succo Di Limone','Impastate i formaggi, metà dell''erba cipollina tritata, il radicchio pulito e tritato, i ritagli di salmone. Condite con un pizzico di pepe nero e una spolverata di noce moscata. Distribuite il composto sulle 12 fette di salmone, chiudetele a involtino, cospargete con la rimanente erba cipollina, condite con un filo d''olio d''oliva e una spruzzata di succo di limone, servite dopo aver tenuto in frigo almeno 1 ora.',3042);
INSERT INTO "ricette" VALUES (12904,'Involtini Al Sesamo','Pollame','Tacchino',4,' -','400 G Petto Di Tacchino A Fette,
4 Cucchiai Formaggio Emmenthal Grattugiato,
1 Cucchiaio Semi Di Sesamo,
1 Cucchiaio Farina,
1/2 Bicchiere Vino Bianco Secco,
1/2 Bicchiere Brodo Vegetale,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Prendete le fette di tacchino e schiacciatele con il batticarne. Tagliatele a rettangoli non troppo grossi e disponeteli sul piano di lavoro. Tostate i semi di sesamo in una padellina, senza condirli. Uniteli al formaggio grattugiato e condite con del pepe. Salate le fette di tacchino e spolveratele con il composto al formaggio e sesamo. Arrotolatele e infilzatele con degli stecchini per fermarle. Fate rosolare gli involtini nell''olio caldo dopo averli infarinati. Passateli in un tegame dove avrete scaldato del brodo, avendo cura di togliere gli stecchini. Versate mezzo bicchiere di vino caldo e fatelo evaporare. Continuate a cuocere ancora per 3 minuti; se necessario aggiungete ancora del brodo. Spolverizzate con il prezzemolo tritato e servite su un piatto da portata. Come contorno aggiungete delle carote glassate.',1346);
INSERT INTO "ricette" VALUES (12905,'Involtini Al Sesamo (2)','Antipasto','Prosciutto Cotto',4,' -','1 Confezione Pasta Sfoglia Surgelata,
100 G Prosciutto Cotto,
100 G Formaggio Fontina (o Di Altro Formaggio Filante),
1 Uovo,
1 Cucchiaio Semi Di Sesamo','Lasciate scongelare la pasta sfoglia, tirandola fuori dal surgelatore almeno 15 minuti prima dell''uso. Dopodichè, stendetela su un piano da lavoro spolverizzato di farina e assottigliatela servendovi di un matterello. Dividete la pasta in 12 parti di forma pressocchè quadrata e su ognuna disponete il prosciutto cotto e la fontina tagliati a pezzetti. Subito dopo, pennellate con il battuto d''uovo i bordi e arrotolate la pasta su se stessa fino a formare degli involtini. Sigillate bene tutti i bordi, cospargeteli con i semini di sesamo ed infornateli per circa 20 minuti a 200 gradi. Serviteli subito caldi e croccanti.',2178);
INSERT INTO "ricette" VALUES (12906,'Involtini Al Tonno','Antipasto','Tonno',4,' -','4 Peperoni,
Insalata Lattuga,
1 Scatola Tonno,
1 Peperoncino,
Olio D''oliva,
Zenzero,
Succo Di Limone,
Sale,
Pepe','Arrostire i peperoni e privarli della pellicola e dei semi. Quindi tagliarli a grosse falde. Tritare finemente il tonno, unire il peperoncino tritato, sale, pepe, succo di limone, zenzero ed olio sufficiente per ottenere un impasto morbido. Distribuire il composto sulle falde di peperone e arrotolarle ad involtino. Disporre gli involtini su un letto di lattuga. Condire con poco sale e olio buono.',2135);
INSERT INTO "ricette" VALUES (12907,'Involtini All''emiliana','Carne','Vitello',4,'Luogo: Emilia-Romagna.','600 G Fettine Di Vitello In Fette Di 75 G,
100 G Mortadella,
200 G Cipolla,
1 Cucchiaino Zucchero,
2 Cucchiai Aceto Di Vino,
4 Cucchiai Vino Bianco Secco,
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Affettate le cipolle sottilmente e fatele cuocere lentamente in un tegame con 2 cucchiai di olio evitando di farle imbiondire; salare, pepare e, qualche minuto prima di togliere dal fuoco, aggiungere l''aceto nel quale si sarà fatto sciogliere lo zucchero. Battete un poco le fettine di carne, salatele, pepatele, stendete su ciascuna una fettina di mortadella e cospargete con uno strato di cipolle cotte. Arrotolate le fette di carne su se stesse e fissatele con degli stecchini. Scaldate 2 cucchiai di olio in un tegame, fatevi rosolare gli involtini, spruzzateli con il vino bianco, salateli un poco e cuoceteli a calore moderato per una ventina di minuti. Durante la cottura, se necessario, unite qualche cucchiaio di acqua calda o brodo. Servite caldi.',1881);
INSERT INTO "ricette" VALUES (12908,'Involtini Alla Crema Di Formaggio','Carne','Vitello',4,' -','4 Fette Fesa Di Vitello,
1 Bicchiere Latte,
3 Fette Pancarré,
100 G Formaggini Alle Erbe,
50 G Prosciutto Cotto Tritato,
Prezzemolo,
1 Pugno Pistacchi Tritati,
Formaggio Parmigiano,
Sale,
Olio D''oliva,
Burro,
Vino Bianco','Ammorbidire nel latte il pancarré e strizzarlo, mescolarvi il formaggio, il prosciutto, il prezzemolo, i pistacchi, il parmigiano e il sale. Suddividere il composto sulle fette di fesa, formare degli involtini e cuocerli in olio, burro e vino bianco.',4103);
INSERT INTO "ricette" VALUES (12909,'Involtini Alla Elisa','Contorno','Asparagi',4,' -','8 Fette Prosciutto Cotto,
16 Asparagi Grandi,
8 Cucchiai Besciamella,
Formaggio Grana Grattugiato','Lessare gli asparagi. Mettere nelle fette di prosciutto, che avrete cura di far tagliare un po'' spesse, 2 asparagi, un cucchiaio di besciamella e un po'' di grana grattugiato. Avvolgere ad involtino ed adagiare in una teglia da forno. Terminata questa operazione coprire con un po'' di besciamella e di grana e fare gratinare.',2238);
INSERT INTO "ricette" VALUES (12910,'Involtini Alla Maggiorana','Carne','Vitello',4,' -','4 Fettine Vitello,
60 G Formaggio Grana Grattugiato,
80 G Mollica Di Pane Bagnata Nel Latte,
1 Manciata Maggiorana,
Prezzemolo Tritato,
30 G Burro,
Olio D''oliva,
1/2 Bicchiere Vino Bianco Secco,
Sale,
Pepe','Lavate, asciugate e tritate le foglie di maggiorana. Amalgamate la mollica di pane, il grana, il prezzemolo, la maggiorana sale e pepe. Mettete su ogni fettina una parte del composto, formate degli involtini e chiudeteli con uno stecchino. Rosolateli in padella con burro e olio, bagnate col vino e cuocete ancora 5 minuti.',1823);
INSERT INTO "ricette" VALUES (12911,'Involtini Alla Siciliana','Carne','Vitello',4,'Luogo: Sicilia.','600 G Fesa Di Vitello A Fettine,
2 Carciofi,
50 G Prosciutto Crudo,
1/2 Bicchiere Vino Bianco,
50 G Burro,
3 Cucchiai Olio D''oliva Extra-vergine,
1 Limone (succo),
1/2 Bicchiere Brodo Vegetale,
2 Cucchiai Farina,
Sale,
Pepe,
Alcuni Cucchiai Salsa Di Pomodoro (facoltativo)','Pulite i carciofi, togliete le foglie dure e le spine e scottateli per 5 minuti in acqua bollente, leggermente salata e acidulata con il succo di limone. Scolateli e lasciateli asciugare su un canovaccio. Tritate intanto il prosciutto, mettetelo in una terrina e impastatelo con il burro. Tagliate a piccoli spicchi i carciofi, stendete sul tagliere le fette di carne, ponete su ognuna un po'' dei composto e due spicchi di carciofo. Salate e pepate leggermente, arrotolate, legate gli involtini con il filo e passateli nella farina. Mettete l''olio in un tegame, fate imbiondire la cipolla e unite gli involtini, lasciandoli dorare da ogni parte. Unite il vino e continuate a cuocere a fiamma bassa, aggiungendo, se occorre, poco brodo caldo per volta. Una volta ben cotti, ponete gli involtini con il loro sugo in un piatto di servizio riscaldato e portate subito in tavola. A piacere si può versare sugli involtini qualche cucchiaio di salsa di pomodoro.',1974);
INSERT INTO "ricette" VALUES (12912,'Involtini Alla Siciliana (2)','Carne','Vitello',4,'Luogo: Sicilia.','400 G Fettine Di Vitello,
100 G Pangrattato,
50 G Uvetta Sultanina,
30 G Pinoli,
120 G Formaggio Pecorino Fresco,
Alcune Foglie Alloro,
1 Cipolla,
Olio D''oliva,
Sale,
Pepe','Preparare il ripieno mescolando in 1 ciotola circa 100 g di pangrattato con l''uvetta (ammorbidita in acqua tiepida), i pinoli, lavati e asciugati e il pecorino tagliato a dadini. Salare e pepare. Spargere sulle fettine di carne 1 parte di ripieno, poi arrotolarle formando degli involtini. Infilarli su 1 spiedino alternandoli con foglie d''alloro e fettine di cipolla. Far scaldare 1 padella antiaderente unta d''olio e cuocerli per 10 minuti rigirandoli spesso.',2214);
INSERT INTO "ricette" VALUES (12913,'Involtini Alle Erbe','Pollame','Pollo',4,' -','4 Fette Petto Di Pollo,
Mentuccia,
Maggiorana,
Prezzemolo,
1 Cipollotto,
80 G Formaggio Grana Grattugiato,
100 G Pangrattato,
2 Uova,
Farina,
Vino Bianco Secco,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Mescolare al pangrattato il formaggio, le erbe finemente tritate, sale, pepe, uova. Dopo aver battuto ogni fetta di carne, adagiare la farcia su metà fetta e ripiegarvi sopra l''altra metà cucendo con filo da cucina. Infarinare i fagottini e rosolarli nell''olio col cipollotto tritato. Irrorare col vino e terminare la cottura in forno.',3191);
INSERT INTO "ricette" VALUES (12914,'Involtini Alle Olive','Carne','Vitello',4,' -','4 Scaloppine Di Vitello,
4 Lardelli,
50 G Burro,
100 G Olive Verdi,
100 G Mollica Di Pane,
1/2 Bicchiere Latte,
125 G Funghi,
1/2 Spicchio Aglio,
Prezzemolo,
Sale,
Pepe','Mescolate insieme il pane imbevuto di latte, l''aglio tritato, i funghi, il prezzemolo, il sale e il pepe. Dividete il tutto in 4 parti e ponetelo sopra le 4 scaloppine, arrotolatele, e circondatele di lardelli fissando il tutto con lo spago. In un tegame mettete olio, burro e la carne lasciando cuocere per 30 minuti. Intanto snocciolate le olive e mettetele a bagno per 2 minuti in acqua bollente. A 15 minuti dalla fine della cottura della carne aggiungete intorno le olive. Tritate gli spinaci che avrete precedentemente fatto bollire per 15 minuti in acqua salata, e serviteli intorno agli involtini.',1460);
INSERT INTO "ricette" VALUES (12915,'Involtini Alle Olive (2)','Carne','Vitello',4,' -','450 G Noce Di Vitello,
50 G Fegato Di Vitello,
30 G Burro,
1 Acciuga Salata,
1 Bacca Di Ginepro,
30 G Olive Nere,
Olio D''oliva,
Pepe,
Sale','Appiattire col batticarne le fettine di vitello. Preparare un impasto con il burro, l''acciuga lavata e spezzettata, il fegato tritato e la bacca di ginepro schiacciata. Distribuire l''impasto sulle fettine di vitello e formare degli involtini. Rosolarli a fuoco vivo in olio, salare, pepare e unire qualche cucchiaio di acqua calda. Verso la fine della cottura aggiungere le olive snocciolate e tritate, lasciar insaporire e servire ben caldi.',1498);
INSERT INTO "ricette" VALUES (12916,'Involtini Allo Speck','Antipasto','Speck',4,' -','8 Fette Speck,
4 Uova,
200 G Formaggio Caprino,
Salvia,
Burro,
Sale,
Pepe','La prima cosa da fare è preparare il ripieno, quindi, lessate le uova in acqua bollente per circa 8 minuti aggiungendo un pizzico di sale. Subito dopo, passatele sotto l''acqua fredda corrente e sgusciatele. In un recipiente piuttosto capiente unite i tuorli precedentemente separati dall''albume, il caprino, il sale, il pepe e mescolate con cura servendovi di un cucchiaio di legno. Nel frattempo, stendete su un ripiano le fette di speck e aggiungete al centro di ciascuna un po'' dell''impasto. Chiudete a fagottino ogni fetta di speck ripiena fissando una foglia di salvia e infilzando entrambi con uno stecchino. Disponete gli involtini in una teglia, meglio se antiaderente, cospargeteli con fiocchetti di burro e lasciate dorare in forno preriscaldato per circa 5 minuti a 200 gradi. Serviteli subito caldi.',1932);
INSERT INTO "ricette" VALUES (12917,'Involtini Appetitosi','Carne','Vitellone',4,' -','8 Fette Polpa Di Vitellone,
4 Fette Prosciutto Cotto,
8 Fettine Mozzarella,
8 Carciofini Sott''olio,
Burro,
Brodo,
Vino Bianco,
Alcune Foglie Salvia,
Sale','Battere le fette di carne e disporre su ognuna 1 fetta di prosciutto, 1 di mozzarella e 1 carciofino a fettine. Salarle, avvolgerle a involtino e chiudere con 1 stecchino, infilando 2 foglie di salvia. Far sciogliere in 1 padella un po'' di burro, adagiarvi gli involtini, spruzzarli di vino e, quando sarà evaporato, aggiungere 1 mestolo di brodo. Salare, coprire e cuocere per 20 minuti, unendo, se occorre, un po'' di brodo.',3479);
INSERT INTO "ricette" VALUES (12918,'Involtini Con Castagne','Carne','Vitello',4,' -','8 Fettine Fesa Di Vitello,
8 Fette Prosciutto Cotto,
1 Ciuffo Salvia,
1 Bicchiere Vino Marsala,
2 Cucchiai Olio D''oliva,
30 G Burro,
200 G Castagne Lessate E Sbucciate,
Brodo,
4 Cucchiai Panna Liquida,
Sale,
Pepe','Disponete le fettine di carne su un tagliere, copritele con le fette di prosciutto, arrotolatele con un paio di foglie di salvia e fermatele con uno stuzzicadenti. Mettete gli involtini a dorare in una padella con l''olio ed il burro. Aggiungete poco brodo e continuate la cottura. A pochi minuti dal termine unite le castagne, il marsala e la panna. Controllate il sale e servite.',3670);
INSERT INTO "ricette" VALUES (12919,'Involtini Con I Funghi','Carne','Vitello',4,' -','16 Fettine Girello Di Manzo,
8 Funghi Champignon,
Aglio,
Prezzemolo,
Farina,
1 Uovo,
Abbondante Olio Per Friggere,
Sale,
Pepe','Per la buona riuscita di questo piatto lo spessore delle fettine deve essere veramente sottile. Stendete bene 8 fettine di carne e sistematele al centro di ognuna un fungo tagliato a scaglie, un pizzico di prezzemolo e aglio tritati assieme, sale e pepe. Sistemate sopra le fettine così farcite, altre fettine di carne. Formate degli involtini avvolgendo su se stesse le doppie fettine, passatele nella farina e poi nell''albume dell''uovo sbattuto. Scaldate una dose abbondante di olio, quando sarà fumante immergete per pochi minuti gli involtini. Scolateli bene e adagiateli sopra un foglio di carta assorbente, quindi disponeteli in un grande piatto e servite.',2479);
INSERT INTO "ricette" VALUES (12920,'Involtini Con La Ricotta','Carne','Vitellone',4,' -','8 Fettine Vitellone,
8 Fettine Lardo,
80 G Ricotta Marzotica,
Aglio,
Prezzemolo,
600 G Pomodori Pelati Sammarzano,
1 Cipolla,
Vino Rosso,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Condire ogni fettina con sale, pepe, aglio, prezzemolo, una fettina di lardo, scaglie di ricotta. Arrotolare ad involtino e chiudere con uno stecchino. Rosolare nell''olio la cipolla, unire gli involtini e rosolare a fuoco vivo qualche minuto. Sfumare col vino, aggiungere i pomodori frullati, aggiustare di sale e cuocere 2 ore.',3022);
INSERT INTO "ricette" VALUES (12921,'Involtini Con Salsiccia','Carne','Vitello',4,' -','8 Scaloppine Di Vitello,
150 G Salsiccia,
Rosmarino,
16 Foglie Basilico,
5 Pomodori Pelati,
3 Cucchiai Farina,
30 G Burro,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Allineare le scaloppine su 1 tagliere e salarle. Tagliare in 8 pezzi la salsiccia, privata della pelle. Distribuire su ogni fetta qualche ago di rosmarino e 2 foglie di basilico spezzettate. Avvolgere strettamente le fettine formando degli involtini e fissare ognuno con 1 stecchino e poi passarli nella farina. Farli rosolare in 1 padella con l''olio e il burro. Tagliuzzare i pomodori e unirli alla carne; salare, pepare e cuocere ancora per altri 15 minuti.',1844);
INSERT INTO "ricette" VALUES (12922,'Involtini Con Sedano E Carota','Carne','Manzo',4,'Luogo: Lazio.','500 G Fettine Di Manzo,
Sedano,
3 Carote,
100 G Pancetta,
1 Cipolla,
Vino Bianco Secco,
Farina,
3 Pomodori Pelati,
Olio D''oliva,
Sale,
Pepe','Lavate e sbucciate il sedano e le carote, poi tagliateli a listelli di circa 3 cm. Tagliate a filetti anche la pancetta. In ogni fettina di manzo mettete un pezzetto di sedano, di carota e di pancetta; avvolgete e chiudete con uno stecchino. Scaldate in una padella dell''olio d''oliva e depositatevi sopra gli involtini, aggiungendo la cipolla tritata, vino bianco secco e un po'' di farina. Mescolate a fuoco alto e aggiungete tre pomodori pelati sbucciati e schiacciati, sale e pepe. Cuocere il tutto per 15-20 minuti. ',2222);
INSERT INTO "ricette" VALUES (12923,'Involtini D''agnello Ai Cavoli','Carne','Agnello',6,' -','300 G Agnello,
2 Foglie Menta,
3 Cucchiai Riso,
5 Uova,
1 Cavolo,
50 G Burro,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe','Tritate finemente la carne e lessate per 3 minuti 15 foglie di cavolo. In una teglia mettete la carne tritata, 1 uovo, 2 foglie di menta tritate, sale, pepe e 3 cucchiai di riso. Mescolate il tutto. Stendete le foglie del cavolo mettendo al centro un po'' di questo ripieno e arrotolatele. In un tegame mettete burro, olio e sistemate sopra questi involtini di cavolo, salate e lasciate cuocere. Dopo 15 minuti dall''inizio della cottura coprite il tutto con acqua e continuate a cuocere. Intanto frullate le 4 uova rimaste salandole, pepandole e versatele sopra la carne; lasciate che diventino cremose.',2203);
INSERT INTO "ricette" VALUES (12924,'Involtini Di Bresaola','Antipasto','Bresaola',4,' -','200 G Bresaola,
4 Tomini Freschi,
Olio D''oliva,
Pepe','Amalgamate i tomini in una scodella con olio e pepe, spalmate la salsa sulle fettine di bresaola, arrotolatele e disponetele sul piatto di portata.',1737);
INSERT INTO "ricette" VALUES (12925,'Involtini Di Bresaola (2)','Antipasto','Bresaola',4,' -','200 G Bresaola,
400 G Ricotta,
Olio D''oliva,
Pepe','Amalgamate la ricotta in una scodella con olio e pepe, spalmate la salsa sulle fettine di bresaola, arrotolatele e disponetele sul piatto di portata.',1737);
INSERT INTO "ricette" VALUES (12926,'Involtini Di Bresaola (3)','Antipasto','Bresaola',4,' -','2 Confezioni Formaggio Fiorello Locatelli,
100 G Formaggio Gorgonzola Piccante,
200 G Bresaola,
1 Sedano Bianco,
Sale,
Pepe,
Olio D''oliva','Tritate il cuore del sedano insieme alle foglioline più tenere; tagliate a rondelle 4-5 gambi. Mescolate il fiorello con il gorgonzola e con il cuore del sedano tritato (comprese le foglioline più tenere). Distribuite questo composto al centro di ogni fetta di bresaola, poi avvolgete le fette ottenendo tanti involtini. Sistemateli su un piatto da porzione, mettete tutt''intorno il sedano e conditelo con olio sale e pepe appena macinato. (A piacere potrete legare gli involtini con un filo di erba cipollina.)',1950);
INSERT INTO "ricette" VALUES (12927,'Involtini Di Bresaola (4)','Antipasto','Bresaola',2,' -','8 Fette Bresaola,
100 G Formaggio Robiola Fresca,
1 Cuore Sedano,
1 Cuore Carciofo,
1 Cucchiaio Succo Di Limone,
4 Cucchiai Olio D''oliva Extra-vergine,
Alcune Gocce Tabasco,
1 Presa Sale','Tritate le verdure e unitele alla robiola, condite con un pizzico di sale e lavorate fino a ottenere una crema. Mettete le fette di bresaola su un piano e aggiungete un po'' della crema al centro di ciascuna. Chiudete poi le fette come a farne dei piccoli fagottini. Mescolate ed emulsionate l''olio con il succo di limone, una presa di sale e qualche goccia di salsa di tabasco e condite con questa salsa.',2041);
INSERT INTO "ricette" VALUES (12928,'Involtini Di Bresaola (5)','Antipasto','Bresaola',4,' -','100 G Bresaola,
Formaggio Fresco (formaggio Stracchino O Formaggio Robiola O Formaggio Philadelphia),
Succo Di Limone,
1 Spolveratina Pepe,
Olio D''oliva,
Per Guarnire:,
Alcune Foglie Insalata Rughetta','Porre al centro di ogni fettina di bresaola un po'' di formaggio e arrotolare, disporre su un piatto di portata, condire con succo di limone, una spolveratina di pepe, olio, e infine guarnire con foglie di rughetta.',1245);
INSERT INTO "ricette" VALUES (12929,'Involtini Di Bresaola (6)','Antipasto','Bresaola',4,' -','200 G Bresaola,
400 G Ricotta,
Olio D''oliva,
Pepe','Lavorare la ricotta con olio e pepe. Spalmare un po'' di ricotta su ogni fettina di bresaola, arrotolarle e disporle su un piatto da portata.',1737);
INSERT INTO "ricette" VALUES (12930,'Involtini Di Bresaola (7)','Antipasto','Bresaola',4,' -','8 Fettine Bresaola,
2 File Formaggi Caprini,
Pasta Di Olive,
Formaggio Grana Grattugiato,
Succo Di Limone,
Olio D''oliva,
Sale,
Pepe','Disporre le fettine di bresaola su 1 largo piatto, spruzzarle con succo di limone, cospargerle con olio e spolverizzare con abbondante pepe e lasciar insaporire per 10 minuti. Intanto, mettere i caprini in 1 terrina e lavorarli con 1 cucchiaio di legno fino a ridurli in crema. Unire alla crema di formaggio la pasta di olive, l''olio, il grana, il sale, il pepe e mescolare bene. Distribuire il composto al centro delle fettine di bresaola e avvolgerle su se stesse.',2966);
INSERT INTO "ricette" VALUES (12931,'Involtini Di Bresaola Alla Ricotta','Antipasto','Bresaola',4,' -','200 G Bresaola,
200 G Ricotta,
Insalata Rucola,
2 Gocce Olio D''oliva,
1 Pizzico Sale','Chiedete di tagliare la bresaola a fettine sottili. In una ciotola lavorate a crema la ricotta e mettetene un cucchiaio su ogni fettina, cospargete con rucola sminuzzata, insaporite con due gocce d''olio e un pizzico di sale. Arrotolate formando degli involtini e tenete al fresco. Serviteli con pane appena tostato. Vini di accompagnamento: Oltrepò Pavese Riesling Renano DOC, Colli Martani Grechetto DOC, Falerno Del Massico Bianco DOC.',832);
INSERT INTO "ricette" VALUES (12932,'Involtini Di Bresaola E Caprino','Antipasto','Bresaola',4,' -','200 G Formaggio Caprino Fresco,
12 Fette Bresaola,
1 Limone,
1 Arancia,
3 Cucchiai Olio D''oliva Extra-vergine,
200 G Insalatina,
1 Mazzetto Erba Cipollina,
Sale,
1 Spolverata Pepe','Per gli involtini: in una terrina amalgamare il caprino con un pizzico di sale, una spolverata di pepe, 1 cucchiaio di olio e 1 cucchiaino di buccia di limone e arancia grattugiata. Riempire una tasca da pasticciere con il composto e, utilizzando una bocchetta rigata, farcire le fette di bresaola, quindi formare dei coni. Per l''insalatina: emulsionare l''olio di oliva extra-vergine rimasto con 1 cucchiaio di succo di limone e 1 di succo di arancia, il sale e l''erba cipollina tagliata a striscioline sottili. Lavare e asciugare l''insalatina e condirla con l''emulsione agli agrumi. Per servire: disporre l''insalatina condita su un piatto di portata e completare con gli involtini di bresaola, decorandoli con la buccia del limone e dell''arancia tagliata a striscioline sottili.',2748);
INSERT INTO "ricette" VALUES (12933,'Involtini Di Caffè','Antipasto','Caffè',4,' -','240 G Farina,
2 Cucchiaini Lievito Artificiale,
1 Pizzico Sale,
120 G Burro,
1/2 Tazza Latte,
1/4 Tazza Caffè,
3 Cucchiai Melassa,
Poco Zucchero A Velo,
1 Cucchiaio Cioccolata In Polvere,
Zucchero','Mescolare 240 g di farina, due cucchiaini di lievito artificiale ed un pizzico di sale; passare al setaccio ed impastare con 60 g di burro. Ora mescolare mezza tazza di latte, un quarto di tazza di caffè, tre cucchiaiate di melassa ed un po'' di zucchero a velo. Unire i due preparati, lavorare la pasta ottenuta e stenderla in una teglia. Quindi spalmare sopra altri 60 g di burro e spolverare una cucchiaiata di cioccolata in polvere e zucchero; arrotolare il tutto, tagliare il tronco ottenuto in fette, da sistemare a distanza in una teglia. Far cuocere a fuoco caldo per una decina di minuti.',2086);
INSERT INTO "ricette" VALUES (12934,'Involtini Di Capesante E Coste','Pesce','Capesante',4,' -','12 Foglie Coste,
Sale,
160 G Filetto Di Pesce (sogliola O Merluzzo),
8 Capesante,
1 Uovo Intero,
1 Pizzico Pepe Di Caienna,
16 Cl Panna,
5 Cl Brodo Di Pesce,
3 Bacche Ginepro,
1 Cipolla,
25 Cl Salsa Di Vino Bianco (v. Ricetta),
1 Pizzico Peperoncino,
40 G Burro All''astice (v. Ricetta)','Preparate il burro all''astice e la salsa di vino bianco come indicato nelle ricette corrispondenti. Lavate con cura le coste e scottatele in una pentola con acqua bollente salata per 5 secondi. Fatele raffreddare sotto l''acqua corrente, mettetele a sgocciolare su un canovaccio pulito, poi passatele nel frigorifero. Aprite le capesante, estraete i frutti, eliminate da ciascuno di essi il bordo grigio e separate la polpa dal corallo. Frullate l''uovo con il sale, il pepe di Caienna, il corallo e il filetto di pesce. Passate al setaccio il composto ottenuto, raccoglietelo in una terrina posta in un recipiente colmo di ghiaccio e incorporatevi la panna. Togliete alle foglie delle coste la grossa venatura centrale, coprite la fessura con mezza foglia, poi stendetevi sopra la farcia preparata, lasciando un margine libero largo circa 1 cm. Ponete un mollusco vicino alla base di ogni foglia, poi arrotolatele richiudendo all''interno il ripieno. Versate il brodo sul fondo di una casseruola munita dell''apposito cestello per la cottura al vapore. Mettete nel brodo una cipolla ridotta ad anelli e le bacche di ginepro; se lo desiderate, potete profumare il brodo aggiungendo dragoncello o aneto. Ponete gli involtini nel cestello e fate cuocere al vapore per 5-6 minuti. In una casseruolina portate ad ebollizione la salsa al vino bianco, insaporitela con una presa di sale e un pizzico di peperoncino e incorporatevi il burro all''astice. Mettete nel piatto di ogni commensale due involtini con un po'' di salsa e servite.',3082);
INSERT INTO "ricette" VALUES (12935,'Involtini Di Carne','Carne','Vitello',4,' -','Alcune Fettine Girello Di Vitello Tagliato Sottile,
Formaggio Parmigiano Grattugiato,
Pangrattato,
Olio D''oliva,
Burro','Fare un impasto con parmigiano e pangrattato, in dosi uguali, legati da un filo d''olio e mettere un poco d''impasto su ogni fettina già striata con del burro. Cuocere in padella o al forno.',2680);
INSERT INTO "ricette" VALUES (12936,'Involtini Di Carne (2)','Carne','Manzo',4,'Luogo: Turchia.','Per La Pasta:,
150 G Burro,
4 Uova,
2 Cucchiai Olio D''oliva,
150 G Yogurth,
1 Cucchiaino Bicarbonato Di Sodio,
1 Cucchiaino Sale,
Farina,
Per Il Ripieno:,
250 G Carne Di Manzo Macinata,
3 Cipolle Medie Tritate','Mescolare al burro 3 uova, l''olio, il bicarbonato, il sale, lo yogurth e tanta farina quanto basta per ottenere la consistenza  dicono i turchi  di ''un lobo d''orecchio''; lavorare la pasta stendendola e ristendendola alcune volte e metterla per 2 ore nel freezer. Poi tagliarla, sgelarla, farne una sfoglia e tagliarla a quadrotti  una quarantina  ripassandoli poi col rullo per farne dei rettangoli. In ciascuno dei quali mettere un cucchiaino di carne preventivamente amalgamata a burro e cipolla, e chiudere a pressione come un raviolo. Metterli in forno su una teglia imburrata pennellandoli d''uovo e farli dorare.',2643);
INSERT INTO "ricette" VALUES (12937,'Involtini Di Carne Di Manzo','Carne','Manzo',2,' -','2 Fettine Carne Di Manzo Magra (fettine Di 100 G A Fettine Sottili E Battute),
1/2 Rapa Gialla,
1/2 Sedano Rapa,
1/2 Fetta Pane Bigio,
Senape,
Sale,
Aglio In Polvere,
1 Cipolla Tritata,
30 G Prosciutto Magro Tagliato A Cubetti,
1 Cucchiaino Purea Di Pomodori,
5 Cl Vino Rosso,
Prezzemolo Tritato,
1 Cucchiaio Fiocchi Di Patate,
1 Cucchiaino Olio D''oliva','Spalmare la senape sulle fettine di carne e condire con sale, pepe e aglio in polvere. Tagliare a striscioline la rapa, il sedano e il pane bigio. Disporre 1 strisciolina di ogni ingrediente sulla fettina di carne in modo da formare un involtino. Chiudere con uno stuzzicadenti. Ungere il fondo di una padella con olio d''oliva e far rosolare l''involtino da tutte le parti finché sarà ben dorato. Unire i cubetti di prosciutto, la cipolla tritata e la purea di pomodoro, bagnare con il vino rosso e il brodo e far cuocere a fuoco lento per circa 30 minuti. Versare i fiocchi di patate nella salsa e portare a ebollizione. Eventualmente condire ancora la salsa. Cospargere la salsa con il prezzemolo tritato.',817);
INSERT INTO "ricette" VALUES (12938,'Involtini Di Cavolo Al Farro','Contorno','Farro',6,'Preparazione: 30 minuti. Calorie: 262.','18 Foglie Cavolo Verza,
120 G Farro Intero,
250 G Funghi Finferli,
2 Spicchi Aglio,
1 Porro Piccolo,
1 Carota,
1 Gambo Sedano,
4 Cucchiai Sedano,
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe,
Brodo Di Verdure,
Per Condire:,
2 Spicchi Aglio,
4 Cucchiai Olio D''oliva Extra-vergine,
1500 G Pomodori Ramati,
Origano Fresco','Mettete a bagno il farro in acqua fredda per 12 ore. Cuocetelo in abbondante acqua salata per 1 ora e mezza e scolatelo. Pulite il porro, la carota e il sedano e tritateli finemente. Pulite i funghi eliminando la parte terrosa del gambo, passateli con un canovaccio inumidito e tritateli grossolanamente. In una padella scaldate l''olio e rosolatevi il trito di sedano, porro e carota con l''aglio schiacciato per 5 minuti. Aggiungete i funghi e cuocete per circa 20 minuti, bagnando con qualche cucchiaio di brodo. Eliminate l''aglio, unite il farro e fatelo insaporire per 4-5 minuti. Regolate di sale e pepate. Scottate in abbondante acqua salata, poche alla volta, le foglie di cavolo per 2-3 minuti circa. Prelevatele con una schiumarola e lasciatele asciugare su un canovaccio. Immergete i pomodori in acqua bollente per pochi istanti quindi spellateli, tagliateli a metà, privateli dei semi e tritateli grossolanamente. In una padella scaldate l''olio e rosolatevi gli spicchi d''aglio schiacciati, per 2-3 minuti. Unite i pomodori e cuocete a fiamma viva per 15-20 minuti. Salate e pepate. Distribuite nelle foglie di verza ormai fredde il composto di farro. Procedete così per il resto delle foglie. Adagiatele nella padella con il sugo di pomodoro, spolverizzate d''origano a piacere e lasciate insaporire per 7-8 minuti. Servite gli involtini cosparsi di sugo.',1943);
INSERT INTO "ricette" VALUES (12939,'Involtini Di Coda Di Rospo Con Gamberetti','Pesce','Coda Di Rospo (rana Pescatrice)',6,' -','1200 G Coda Di Rospo (rana Pescatrice),
200 G Gamberetti,
3 Melanzane Lunghe,
1/2 Bicchiere Vino Bianco Secco,
50 G Olive Nere,
4 Scalogni,
25 G Farina,
1/2 Mazzetto Insalata Rucola,
1 Spicchio Aglio,
1 Limone,
Salsa Worcester,
Olio D''oliva,
Sale,
Pepe','Spellate la coda di rospo, eliminate la spina centrale e ricavatene tanti filetti. Incideteli nella parte più polposa e inseritevi alcuni gamberetti sgusciati. Tagliate le melanzane nel senso della lunghezza a fette sottili, fatele dorare velocemente in un padellino antiaderente con poco olio. Avvolgete i filetti di coda di rospo nelle fette di melanzana, legate gli involtini con spago bianco da cucina e disponeteli in una teglia. Cuocete in forno preriscaldato a 180 gradi per 25 minuti: ritirate la teglia, bucherellate gli involtini e lasciateli riposare 5 minuti, poi toglieteli dal recipiente e teneteli al caldo. Spolverizzate di farina il fondo di cottura, spruzzate con mezzo bicchiere di vino bianco, il succo di limone filtrato al colino e la salsa Worcester, mescolate. Aggiungete un mestolo di fumetto di pesce e fate addensare la salsa. In una casseruola lasciate appassire gli scalogni tritati con uno spicchio d''aglio, un cucchiaio d''olio, unite le olive snocciolate e spezzettate, mezzo mazzetto di rucola tritata, il fondo di cottura del pesce, salate e pepate. Cuocete per 5 minuti. Tagliate gli involtini a rondelle spesse, disponetele sul piatto da portata, copritele con la salsa calda. Vini di accompagnamento: Valle D''Aosta Chardonnay DOC, Val D''Arbia DOC, Regaleali Bianco IGT Di Sicilia.',2624);
INSERT INTO "ricette" VALUES (12940,'Involtini Di Cotenna In Umido','Carne','Maiale',4,' -','8 Rettangoli Cotenna Di Maiale,
150 G Carne Di Maiale Tritata,
50 G Piselli Lessati,
2 Fette Pancarré (fette Ammollate Nel Latte),
50 G Funghi Trifolati,
Passata Di Pomodoro,
1 Mela,
100 G Fagioli Borlotti Lessi,
Prezzemolo Tritato,
Aglio,
Sale,
Pepe,
Poco Olio D''oliva','Preparare il ripieno con la carne, i piselli, il pane ammollato, i funghi, sale e pepe, formare degli involtini con la cotenna e il ripieno, legarli. In una casseruola, rosolare l''aglio con poco olio, versare la passata e sistemare gli involtini, salare, pepare e cuocere a fuoco basso per 75 minuti. A fine cottura, mettere i fagioli e la mela tagliata a dadini, cospargere il prezzemolo e servire.',3142);
INSERT INTO "ricette" VALUES (12941,'Involtini Di Crepes Maria Luisa','Contorno','Uova',4,' -','3 Uova,
Sale,
2 Cucchiai Farina,
1 Bicchiere Birra,
150 G Burro,
400 G Funghi Champignon,
2 Cipolline,
1 Spicchio Aglio,
Pepe,
3 Fette Prosciutto Cotto,
100 G Panna Da Cucina,
50 G Formaggio Parmigiano Grattugiato','Sbattete le uova in un piatto con un''abbondante presa di sale; in un altro piatto fondo stemperate lentamente la farina con la birra, cercando di eliminare tutti i grumi. Versate quindi, il miscuglio sulle uova, mescolando ancora bene e sbattendo con una forchetta, per far leggermente montare le uova. Ponete al fuoco un padellino da crepes, largo non più di un palmo, con una nocciolina di burro; non appena questo sarà imbiondito, versatevi un mescolino di composto, spandendolo bene nel recipiente, in modo da ottenere una crepe molto sottile; fatela dorare da entrambe le parti e fatela poi scivolare su un piatto. Preparate allo stesso modo altre sette crepes, aggiungendo ogni volta una nocciolina di burro. Ora pulite accuratamente i funghi e tagliateli a striscioline; mettete al fuoco un tegame con 50 g di burro e un trito di cipolline e aglio, lasciateli imbiondire e unitevi i 