 gradi per 30-40 minuti. Ritirate, lasciate intiepidire e sformate. Questa torta di mele può essere servita subito calda oppure lasciata raffreddare e completata con una crema. Vini di accompagnamento: Loazzolo DOC, Trentino Vin Santo DOC, Cinque Terre Sciacchetrà DOC.',2584);
INSERT INTO "ricette" VALUES (26055,'Torta Con Salsiccia E Sedano','Antipasto','Salsiccia',6,' -','Per La Pasta:,
200 G Farina,
100 G Burro,
Sale,
Per Il Ripieno:,
200 G Salsiccia,
6 Gambi Sedano,
4 Uova,
1/2 Bicchiere Latte,
Formaggio Parmigiano Grattugiato,
1 Pizzico Sale','Impastate la farina con il burro, un pizzico di sale e l''acqua necessaria per avere una massa di giusta consistenza. Imburrate una tortiera, ponete al centro la pasta e battendola con il palmo delle mani stendetela sul fondo facendola risalire anche verso i bordi. Sminuzzate la salsiccia in un tegame poi lasciatela rosolare. Unite i gambi di sedano sfilettati e tagliati a pezzetti, cuocete per circa mezz''ora. Mettete il composto in una terrina, unite le uova, il latte e il parmigiano. Distribuitelo sulla torta e cuocete in forno preriscaldato a 170 gradi per circa 40 minuti. Servite questa squisita torta tiepida per meglio gustarne il particolare sapore.',2961);
INSERT INTO "ricette" VALUES (26056,'Torta Con Susine E Granelli','Dessert','Susine',12,' -','1500 G Susine,
Burro Per La Teglia,
Farina Per La Teglia,
Per La Pasta Lievitata:,
300 G Farina,
20 G Lievito Di Birra,
12 Cl Latte,
30 G Burro,
30 G Zucchero,
1/2 Limone (scorza Grattugiata),
1/4 Cucchiaino Sale,
2 Uova,
Per I Granelli:,
350 G Farina,
200 G Burro,
200 G Zucchero','Preparate la pasta: setacciate la farina in una capace terrina, fate un incavo al centro e mettetevi il lievito. Scioglietelo con il latte tiepido e impastatelo con un po'' di farina, quindi coprite la terrina con un canovaccio e lasciate riposare il panetto per un quarto d''ora circa. Fate fondere il burro in una casseruola, mescolatevi lo zucchero, le uova, la scorza di limone grattugiata e il sale e incorporate il composto ottenuto al panetto lievitato e al resto della farina. Lavorate il tutto fino ad ottenere una pasta liscia, omogenea e piuttosto morbida. Quando la pasta comincia a formare delle bolle smettete di lavorarla, copritela con un canovaccio e lasciatela lievitare in un luogo caldo fino a quando sarà raddoppiata di volume. A questo punto, stendete la pasta in una teglia rettangolare di 43 x 33 cm, imburrata e infarinata, e bucherellatela con i rebbi di una forchetta. Lavate le susine, privatele del nocciolo e tagliatele in quarti, quindi disponetele sulla pasta in modo regolare. Impastate velocemente in una terrina la farina, lo zucchero e il burro, sbriciolate il composto ottenuto e distribuitelo sulla frutta. Lasciate lievitare la torta per 10-15 minuti, dopodichè cuocetela nel forno preriscaldato (200 gradi per 30-35 minuti. Durante la cottura controllate spesso il fondo della torta, per evitare che scurisca troppo. --- CONSIGLI. Questo dolce può essere preparato in numerose varianti, che si differenziano per il tipo di pasta usato (pasta frolla o pasta lievitata) e per l''eventuale farcitura, che può essere costituita da crema pasticciera o ricotta ed eventualmente completata con frutta secca tritata. L''unico ingrediente fisso è la frutta, ossia le susine, che devono essere ben mature ma ancora ben sode, in modo che non si spappolino con la cottura.',5923);
INSERT INTO "ricette" VALUES (26057,'Torta Con Uvette','Dessert','Uvetta Sultanina',6,'Luogo: Regno Unito. Luogo: Scozia.','3 Tazze Farina,
3 Cucchiaini Lievito,
1 Tazza Grasso Animale,
1 Tazza Uvetta Sultanina,
1/2 Tazza Uvette Tritate,
3/4 Tazza Zucchero,
1 Cucchiaino Cannella In Polvere,
1 Cucchiaino Spezie Miste,
1/2 Cucchiaino Bicarbonato Di Sodio,
1 Uovo Sbattuto,
2 Tazze Latte Con Aggiunta Di Limone','Con il burro fuso ungete una pentola a vapore per pudding della capacità di un litro. Setacciate la farina in un grande recipiente, poi aggiungete il grasso, la frutta, lo zucchero, le spezie e il bicarbonato e mescolate bene. Fate un buco nel centro del composto e versatevi il latte (con aggiunta di limone) e l''uovo. Amalgamate bene gli ingredienti senza lavorare a lungo l''impasto. Con un cucchiaio mettete il composto nella pentola a vapore e livellatene la superficie. Coprite con un foglio di alluminio unto di burro e con un coperchio, e adagiate la pentola in un''altra pentola più grande. Versate nella pentola grande una quantità di acqua bollente tale da sfiorare 2/3 della pentola a vapore e coprite. Lasciate cuocere a fuoco basso per 2 ore e 30 minuti, aggiungendo acqua per mantenere il livello, se necessario. Estraete il dolce dalla pentola e adagiatelo su un piatto da portata. Servite caldo o freddo con crema pasticciera o panna montata.',2491);
INSERT INTO "ricette" VALUES (26058,'Torta Corcovado','Dessert','Burro',8,' -','600 G Farina,
600 G Burro,
3 Uova Intere,
3 Tuorli D''uovo,
50 G Fecola Di Patate,
250 G Zucchero Semolato,
1 Limone (scorza Grattugiata),
1 Cucchiaino Lievito In Polvere,
1 Pizzico Sale,
1 Cucchiaio Rum,
50 G Cacao Amaro,
50 Cl Latte,
120 G Zucchero A Velo,
1 Tazza Panna Montata','Lavorate la farina con il sale, il lievito, 3 uova intere, 3 tuorli, lo zucchero semolato, la scorza grattugiata del limone e 300 g di burro ammorbidito e a pezzetti. Raccogliete l''impasto a palla e fatelo riposare in frigorifero per 30 minuti. Trascorso questo tempo dividetelo in cinque parti, una leggermente più grande dell''altra, e stendete ognuna di esse in una sfoglia piuttosto sottile di forma ovale. Fate cuocere le sfoglie, una alla volta, nel forno, adagiate sulla piastra imburrata, alla temperatura di 220 gradi per 10 minuti. Ponete il cacao e la fecola di patate in una terrina, unitevi un bicchiere di latte e mescolate fino a quando avrete ottenuto un composto omogeneo. Portate ad ebollizione in una casseruola il resto del latte, incorporatevi il composto al cacao e fate cuocere a calore dolcissimo per 3-4 minuti, dopodichè togliete la crema dal fuoco e lasciatela raffreddare. In un''altra terrina lavorate a crema il burro rimasto, poi incorporatevi lo zucchero a velo, un cucchiaio di rum e la crema al cacao. Spalmate le sfoglie ormai fredde con la crema preparata, sovrapponendole man mano in modo da formare una piramide. Stendete la crema anche sull''ultima sfoglia, poi copritela con la panna montata, fatta uscire da una tasca di tela con bocchetta a stella. Lasciate riposare il dolce in frigorifero per un''ora prima di servire.',9454);
INSERT INTO "ricette" VALUES (26059,'Torta Del Bosco','Dessert','Frutti Di Bosco',8,' -','300 G Pasta Frolla Surgelata,
100 G Zucchero,
50 G Farina,
4 Tuorli D''uovo,
50 Cl Latte,
1 Busta Vaniglina,
1/2 Vasetto Gelatina,
3 Vaschette Frutti Di Bosco Misti,
Per La Tortiera:,
Burro,
Farina','Fate scongelare la pasta frolla. Accendete il forno a 180 gradi. Tirate la pasta ricavandone un disco e posatela in una teglia imburrata e infarinata. Bucherellate il fondo con una forchetta, coprite con un foglio di carta da forno o di alluminio, riempite di fagioli secchi o riso in modo che non si sollevi in cottura e fate cuocere per circa 40 minuti, poi lasciate raffreddare. Nel frattempo preparate la crema. In una terrina montate i tuorli con lo zucchero e la vaniglina, aggiungete farina e latte, sbattendo il composto con una frusta. Ponete sul fuoco e portate a ebollizione, mescolando in continuazione. Poi lasciate raffreddare. Lavate e mondate i frutti di bosco. Versate la crema sulla crostata, distribuitela in maniera uniforme e e completate con la gelatina. Decorate con i frutti di bosco e tenete al fresco fino al momento di servire.',3812);
INSERT INTO "ricette" VALUES (26060,'Torta Delicata Agli Amaretti','Dessert','Biscotti Amaretti',6,' -','210 G Burro,
200 G Farina,
150 G Biscotti Amaretti,
200 G Zucchero,
50 G Uvetta Sultanina,
100 G Mandorle,
4 Uova,
1 Bustina Lievito Per Dolci,
1 Bustina Vaniglina,
Liquore All''amaretto,
Per Lo Stampo:,
Burro,
Farina','Lavate l''uvetta e mettetela in una tazza, bagnatela con il liquore e lasciatela rinvenire. Tritate molto finemente le mandorle e pestate gli amaretti riducendoli in polvere, tenetene da parte una decina per la guarnizione. Imburrate una tortiera di circa 26 centimetri di diametro e spolverizzatela con la farina, scuotetela per far scendere la farina in eccesso. Mettete il burro ammorbidito in una terrina e con il cucchiaio di legno lavoratelo energicamente fino a ottenere una crema, unite poco alla volta lo zucchero e la vaniglina. Versate in una tazza le uova e sbattetele leggermente, solo quel che basta per amalgamare i tuorli con gli albumi. Versate nel burro una cucchiaiata di liquore e incorporatevi poco alla volta la farina a cui avrete mescolato il lievito e la polvere di amaretti. Unite le uova e amalgamate alla perfezione, unite per ultime le mandorle e l''uvetta scolata. Versate il composto nella tortiera preparata, livellatelo e sistematevi sopra gli amaretti interi formando una decorazione. Ungete gli amaretti con del burro perché non si brucino durante la cottura oppure spalmateli con del bianco d''uovo. Passate nel forno e cuocete per 40 minuti circa a 180 gradi. Levate la torta dal forno e quando sarà ben dorata, sformatela e appoggiatela sul piatto da portata. Lasciatela riposare per una giornata prima di servirla.',6141);
INSERT INTO "ricette" VALUES (26061,'Torta Delicata Di Merluzzo Agli Champignon','Antipasto','Merluzzo',6,' -','250 G Pasta Brisée,
1000 G Funghi Champignon,
Burro,
100 G Formaggio Groviera,
6 Filetti Di Merluzzo,
2 Uova,
2 Cucchiai Panna,
2 Chiodi Di Garofano,
1 Cipolla Grande,
50 Cl Vino Bianco Secco,
Besciamella,
Alcune Foglie Prezzemolo,
Maggiorana,
Timo,
Sale,
Pepe,
Legumi Secchi','Versate in una casseruola mezzo litro d''acqua, aggiungete il vino e la cipolla tagliata a metà aromatizzata con i chiodi di garofano. Portate a bollore, immergetevi i filetti di pesce e cuocete a fuoco basso per circa 20 minuti. Sgocciolateli. Lasciate il brodo sul fuoco per farlo ridurre un po''. Pepate e profumate il pesce con alcune foglioline di prezzemolo, maggiorana e timo. Pulite i funghi. Tagliateli a lamelle e insaporiteli in una padella con un po'' di burro, dopo circa 10 minuti spegnete e mettete da parte. In un''altra casseruola preparate la besciamella usando metà latte e metà brodo di pesce. Quando è pronta incorporatevi i funghi e la groviera grattugiata. Salate e pepate. Aggiungete la panna e le uova. Stendete la pasta brisée a disco, adagiatela in una tortiera imburrata, punzecchiatela, foderatela con carta da forno, riempitela di legumi secchi e cuocete un quarto d''ora a 160 gradi. Ritirate, eliminate carta e legumi. Spezzettate i filetti di pesce, distribuiteli sulla pasta. Copriteli con la besciamella, rimettete in forno a 180 gradi per 40 minuti. Servitela tiepida. Vini di accompagnamento: Alto Adige Schiava Grigia DOC, Bolgheri Rosato DOC, Gioia Del Colle Rosato DOC.',3894);
INSERT INTO "ricette" VALUES (26062,'Torta Dell''orto','Contorno','Carciofi',8,'Preparazione: 40 minuti. Cottura: 30 minuti.','Sale,
Olio D''oliva,
2 Cucchiai Panna,
Formaggio Parmigiano,
100 G Formaggio Emmenthal,
2 Carciofi,
100 G Asparagi,
100 G Piselli,
6 Patate Novelle,
150 G Zucchina,
6 Carote Piccole,
400 G Pasta Sfoglia','Stendete la pasta sfoglia in un disco sottile di pochi millimetri di spessore. Rivestite con carta da forno uno stampo rotondo del diametro di 24 cm e dai bordi alti e sulla carta sistemate il disco di pasta. Eliminate la pasta eccedente. Pulite e lavate le verdure. Cuocete i pisellini in acqua bollente salata per dieci minuti. Scolateli e lasciateli raffreddare. Pelate le carote e tagliatele a metà nel senso della lunghezza e poi a pezzetti. Lessate i pezzetti di carota per dieci minuti in acqua bollente salata. Lavate le patatine e cuocetele al vapore per dieci minuti, poi pelatele e tagliatele a pezzetti. Accendete il fuoco a 200 gradi e quando avrà raggiunto la temperatura infornate lo stampo con la pasta e fatelo cuocere per dieci minuti. Mondate gli asparagi, eliminate la parte dura dei gambi e conservate solo le punte. lessatele in acqua bollente salata per dieci minuti. Mondate i carciofi ed eliminate le foglie esterne e i gambi. Tagliate il cuore dei carciofi a spicchi. Scaldate l''olio in una padella antiaderente e rosolatevi i carciofi per dieci minuti. Nel frattempo mondate le zucchine e tagliatele a rondelle. Unitele ai carciofi, salate e continuate la cottura per altri dieci minuti mescolando con un cucchiaio di legno. Tagliate l''emmenthal a fette. Disponete sulla pasta il formaggio e irrorate con la panna. Versate poi tutte le verdure e spolverizzate con il parmigiano. Infornate di nuovo e lasciate cuocere fino a quando il formaggio è completamente sciolto e la superficie è dorata e croccante. Vino consigliato: Bardolino.',4272);
INSERT INTO "ricette" VALUES (26063,'Torta Della Domenica','Dessert','Nutella',6,' -','1 Scodella Pangrattato,
160 G Zucchero,
3 Uova,
80 G Burro,
100 G Biscotti Amaretti,
150 G Nutella,
1 Manciata Pinoli,
1 Bustina Lievito','Unite al pangrattato il latte per ottenere un impasto piuttosto solido. Aggiungete al composto 120 g di zucchero, 1 3 tuorli d''uovo, 50 g di burro, precedentemente fuso, la Nutella, gli amaretti tritati e il lievito. Mescolate energicamente ed aggiungete gli albumi montati a neve. Cospargete di burro una tortiera e spolverizzatela con il pangrattato. Versatevi il composto e cospargete la superficie con lo zucchero e i pinoli. Cuocete in forno preriscaldato a 180 gradi per 60 minuti circa.',3547);
INSERT INTO "ricette" VALUES (26064,'Torta Della Foresta Nera','Dessert','Ciliegie',16,' -','460 G Ciliegie Sciroppate,
25 Cl Succo Di Ciliegie,
100 G Zucchero,
1/2 Bastoncino Cannella,
2 Cucchiaini Fecola Di Patate,
1 Pan Di Spagna Al Cioccolato (26 Cm),
75 Cl Panna,
6 Cl Kirsch,
4 Cl Sciroppo Di Zucchero,
Rotolini Di Cioccolato,
Zucchero A Velo','Sgocciolate bene le ciliegie; mescolate in una casseruola il succo di ciliegie con 40 g di zucchero e la cannella e portate ad ebollizione. Unite la fecola, fate riprendere il bollore alcune volte, in modo che il liquido si addensi, quindi unite le ciliegie e mescolate delicatamente, usando una frusta, così da non schiacciare i frutti. Portate ad ebollizione ancora una volta, quindi levate dal fuoco e mettete da parte 16 ciliegie per la guarnizione. Tagliate il pan di Spagna in tre dischi. In una ciotola montate la panna con lo zucchero rimasto. Spalmate il primo disco con un sottile strato di panna e mettetevi sopra parte delle ciliegie, ormai fredde, col loro fondo di cottura. Appoggiatevi sopra il secondo disco, inzuppatelo con una miscela ottenuta mescolando il kirsch e lo sciroppo di zucchero, e coprite anch''esso con la panna e le ciliegie. Terminate con l''ultimo disco inzuppato con la miscela al kirsch. Rivestite completamente il dolce con la panna montata, mettete quella rimasta in una tasca di tela con bocchetta a stella, formate lungo il bordo della torta 16 rosette e guarnite ciascuna di esse con una ciliegia. Ponete al centro del dolce i rotolini di cioccolato e cospargeteli con lo zucchero a velo.',6419);
INSERT INTO "ricette" VALUES (26065,'Torta Della Foresta Nera (2)','Dessert','Cacao',8,' -','180 G Farina,
160 G Zucchero,
50 G Cacao,
6 Uova,
8 Cucchiai Cherry Brandy,
8 Cucchiai Sciroppo Di Ciliegie,
Burro E Farina Per Lo Stampo,
Per Guarnire:,
500 G Ciliegie Nere Sciroppate,
60 Cl Panna Fresca,
1 Cucchiaino Amido Di Mais,
Per Decorare:,
80 G Cioccolato Amaro','Rompete le uova in una bastardella (recipiente di metallo a semisfera) che poserete su una casseruola di acqua in leggera ebollizione. Aggiungete lo zucchero e montate le uova finché diventano bianche e spumose. Toglietele dal bagnomaria e lasciatele raffreddare continuando a montarle. Incorporate delicatamente la farina e il cacao setacciati. Imburrate 2 stampi di 18 centimetri di diametro e infarinateli. Dividete l''impasto nei due stampi e cuocete le basi in forno medio per 30-40 minuti. Quando la pasta risulta soda e asciutta sotto le dita toglietela dal forno e sformatela dopo 15 minuti su 2 griglie. Quando le basi sono fredde (potete prepararle il giorno prima), tagliatele a metà orizzontalmente, spennellatele con lo sciroppo di ciliegie e il cherry brandy e lasciatele macerare qualche ora. Scolate le ciliegie (conservate 15 cl di sciroppo) e snocciolatele. Montate la panna ben fredda e distribuitene un quarto sul primo disco di pasta. Distribuite le ciliegie sulla panna facendole affondare leggermente. Ripetete l''operazione con altri 2 dischi di pasta e coprite con il quarto. Spalmate un po'' di panna rimasta sui lati del dolce, grattugiate il cioccolato e fatelo aderire alle pareti. Decorate la superficie con uno strato di ciliegie lasciando liberi 2 centimetri di bordo. Distribuite la panna rimasta sui bordi con una tasca di tela con bocchetta stellata. Diluite l''amido di mais in un bicchiere di acqua, incorporatela allo sciroppo di ciliegie e scaldate il tutto sul fuoco finché lo sciroppo comincia ad addensarsi. Versatelo sulle ciliegie appena intiepidito. Tenete in frigorifero almeno un''ora prima di servire la torta.',6711);
INSERT INTO "ricette" VALUES (26066,'Torta Della Foresta Nera (3)','Dessert','Nocciole',4,' -','4 Tuorli D''uovo,
200 G Zucchero,
50 G Cioccolata Grattugiata,
200 G Nocciole Macinate,
4 Albumi D''uovo Montati A Neve,
30 Cl Panna Da Montare,
Kirsch,
50 G Fogli Di Cioccolata,
Alcune Ciliegine Sciroppate','Imburrate una tortiera del diametro di circa 20-22 cm e dai bordi alti, spolverizzatela di farina,poi capovolgete lo stampo per far cadere la farina eccedente. Versate in una zuppierina i tuorli con lo zucchero. Con una piccola frusta sbattete energicamente fino ad avere le uova ben soffici. Unite la cioccolata mischiando poco poi con un mestolo di legno bucato amalgamate molto delicatamente le nocciole e gli albumi montati a neve. Quando tutti gli ingredienti saranno perfettamente amalgamati versate il composto nella tortiera, livellatene la superficie e ponete in forno già caldo (170-200 gradi) facendo cuocere per circa 40 minuti. Dividete la foresta nera in due o tre parti. Ponete sul piatto di portata il disco di base irroratelo con il succo delle ciliegine, il kirsch e qualche pezzetto di ciliegine poi spalmatela con la terza parte (se l''avete divisa in tre parti se no dividete in due) di panna precedentemente montata. Mettete sopra il secondo disco e procedete come prima collocatevi sopra l''ultimo disco e con la restante panna coprite uniformemente la foresta nera. Guarnitela con i fogli di cioccolata e qualche ciliegina intera. Se non la guarnite subito potete conservarla qualche giorno in frigo avvolta in un foglio di carta metallizzata.',4092);
INSERT INTO "ricette" VALUES (26067,'Torta Della Foresta Nera (4)','Dessert','Cioccolata',4,' -','3 Tuorli D''uovo,
1 Cucchiaio Acqua Tiepida,
60 G Zucchero,
40 G Cioccolata In Polvere,
1 Cucchiaio Cacao,
40 G Farina,
3 Albumi D''uovo Montati A Neve,
Per Guarnire:,
50 G Fogli Di Cioccolata,
Alcune Ciliegine Sciroppate','Sbattete energicamente i tuorli con l''acqua e lo zucchero. Aggiungete la cioccolata in polvere e il cucchiaio di cacao mescolando poco. Amalgamate la farina setacciata e fatta cadere a pioggia con gli albumi montati a neve molto delicatamente con un mestolo di legno bucato. Versate il composto nella tortiera e livellatene la superficie e ponete in forno già caldo (170-200 gradi) per circa 30 minuti. Guarnitela con i fogli di cioccolata e qualche ciliegina intera.',1333);
INSERT INTO "ricette" VALUES (26068,'Torta Della Nonna','Dessert','Cioccolato',6,' -','200 G Cioccolato Fondente,
Burro,
100 G Zucchero,
Farina,
3 Uova','Fondere a bagnomaria il cioccolato con 100 g di burro. Incorporare 2 cucchiai colmi di farina, lo zucchero, i tuorli e infine gli albumi montati a neve. Trasferire il composto in una teglia imburrata e infarinata e cuocere in forno a 180 gradi per 20 minuti.',2871);
INSERT INTO "ricette" VALUES (26069,'Torta Della Nonna (2)','Dessert','Pinoli',4,' -','300 G Farina,
300 G Zucchero,
200 G Pinoli,
150 G Burro,
4 Uova,
1 Limone,
50 Cl Crema Pasticciera Classica','Si lavorano i tuorli con una piccola frusta, sbattendo bene e incorporando un po'' alla volta il burro fuso, lo zucchero, la scorza grattugiata di mezzo limone, e metà del suo succo filtrato. Si aggiungono poi mescolando con un cucchiaio di legno, la farina setacciata, i pinoli e gli albumi montati a neve fermissima. Si versa l''impasto in uno stampo di 24 cm di diametro e si fa cuocere per 30 minuti in forno preriscaldato a 180 gradi. Quando è cotta e raffreddata, si taglia in due dischi si farcisce con la crema pasticciera e si ricompone. Va tenuta al fresco fino al momento di gustarla.',6291);
INSERT INTO "ricette" VALUES (26070,'Torta Della Nonna (3)','Dessert','Uova',6,' -','125 G Farina,
125 G Burro,
125 G Zucchero,
3 Uova,
Scorza Di Limone,
1 Cucchiaio Liquore','In una ciotola mescolate lo zucchero con le uova fino a quando non diventi spumoso. Aggiungete burro fuso, farina e mescolate bene il tutto. Imburrate una tortiera e versateci questo preparato in cui avrete messo anche la buccia tritata del limone e un cucchiaio di liquore. Infornate per 1 ora; la torta sarà cotta quando mettendo un ferro in mezzo al dolce questo ne uscirà asciutto.',2179);
INSERT INTO "ricette" VALUES (26071,'Torta Della Nonna Nani','Dessert','Uvetta Sultanina',8,'Preparazione: 60 minuti.','250 G Burro,
250 G Farina Bianca,
250 G Zucchero,
4 Uova,
3 Cucchiai Lievito,
1 Limone (succo E Scorza Tritata),
100 G Uvetta Sultanina,
1 Bicchiere Liquore,
Semolino (o Pangrattato),
Zucchero A Velo','Si lavora il burro da solo per almeno mezz''ora, fino a quando non diventa ben cremoso. Sempre mescolando, si aggiunge quindi lo zucchero a cucchiai fino al suo completo assorbimento. Continuando a mescolare, a questo punto viene aggiunto il succo di limone, la buccia tritata ed infine il bicchiere di liquore. A questo punto si aggiunge la farina, cucchiaino per cucchiaino, badando di ottenere un composto ben amalgamato, nel quale verranno immesse l''uvetta, preventivamente messa in acqua calda, asciugata e passata in zucchero e farina. Quando l''impasto è fatto, vi si aggiunge il lievito, pressandolo leggermente con il cucchiaio. Per la cottura, la forma viene preparata in precedenza cospargendola di burro ben distribuito: un aiuto è fornito dal riscaldamento preventivo del contenitore; sopra il burro così distribuito verrà sparso un velo di pangrattato o, meglio ancora, di semolino; il pangrattato o il semolino in eccesso verrà gettato via. La torta cuoce a fuoco vivo sui 280-300 gradi per 15 minuti, quindi si abbassa il forno sui 250-200 gradi, lasciando cuocere per circa altri 30 minuti. E'' importante non aprire il forno fino al termine della cottura. Quindi sfornare e infiorare con un capriccio di zucchero a velo. Questa è una torta abbastanza facile, il risultato è sempre ottimo.',5148);
INSERT INTO "ricette" VALUES (26072,'Torta Della Salute','Dessert','Yogurth Intero',4,' -','2 Uova,
1 Bicchiere Zucchero,
1/2 Bicchiere Farina,
1 Vasetto Yogurth Intero,
1 Bustina Lievito,
4 Cucchiai Olio Di Semi,
1/2 Limone (scorza),
1 Mela Gialla,
1 Mela Rossa','Sbattete le uova con lo zucchero, aggiungete a poco a poco la farina, il lievito, la scorza di limone, lo yogurth e l''olio di semi. Amalgamare con cura finché il composto non sarà liscio e cremoso. Pulite le mele, tagliatele a dadini e aggiungete la frutta al composto. Versate in una tortiera foderata con carta da forno e cuocete per 40/45 minuti a 180 gradi in forno già caldo.',1540);
INSERT INTO "ricette" VALUES (26073,'Torta Delle Demoiselles Tatin','Dessert','Pasta Sfoglia',4,' -','220 G Pasta Sfoglia,
150 G Burro,
170 G Zucchero,
2 Cucchiai Miele,
6 Mele Sbucciate,
1 Limone (scorza Grattugiata),
1 Cucchiaio Aghi Di Rosmarino Fresco','Scongelare una confezione di pasta sfoglia (circa 220 g). Spianarla formando un disco di circa 22 cm. di diametro che si conserverà, su di un piatto, in frigo. In un tegame antiaderente mettere 150 g di burro, 170 di zucchero e due cucchiai di miele, scaldando su fuoco moderato e mescolando ogni tanto, finché la miscela non sarà brunita. Aggiungere 6 mele sbucciate e tagliate in quarti,la buccia grattugiata di un limone non trattato ed un cucchiaio di aghi di rosmarino fresco. Rimestare delicatamente con un cucchiaio di legno finché le mele non saranno tenere (attenti a non spappolarle!). Con una schiumarola scolare le mele e metterle in una teglia di circa 22 cm. di diametro, con il fondo coperto da un disco di carta-forno. Far bollire lo sciroppo per 1-2 minuti, per farlo addensare ancora un po'', poi versarlo sulle mele e lasciar raffreddare. Scaldare il forno a 200 gradi, coprire le mele con il disco di pasta bucherellata con una forchetta ed infornare per circa 20 minuti. Lasciar raffreddare per una mezz''oretta, capovolgere su un piatto e servire tiepida. Nota: Le sorelle Tatin possedevano un alberghetto a Lamotte-Beuvron, presso la Loira, e si resero famose per l''eccellente gestione, oltre che per aver inventato uno dei primi tipi di torta ''upside-down''; la cuocevano in un piccolo forno metallico appoggiato sulla carbonella e pare che questo garantisse un particolare effetto-caramello.',3167);
INSERT INTO "ricette" VALUES (26074,'Torta Delle Rose','Dessert','Burro',6,' -','300 G Farina Bianca,
3 Tuorli D''uovo,
1 Limone (scorza Grattugiata),
3 Cucchiai Olio D''oliva,
200 G Zucchero,
100 G Burro,
50 G Lievito Di Birra,
1 Pizzico Sale,
1/2 Bicchiere Latte','Togliere dal frigorifero il burro almeno 2 ore prima. Impastare la farina, i tuorli, l''olio, il sale e 2 cucchiai di zucchero tolti dai 200 g. Fare intiepidire il latte e sciogliere il lievito, aggiungere la buccia del limone e impastare il tutto per almeno 15 minuti. Stendere la pasta col mattarello fino ad ottenere un rettangolo di 1/2 cm. di spessore. A questo punto lavorare il burro con il rimanente zucchero, fino ad ottenere una crema spumosa. Stenderla sulla pasta in modo uniforme e arrotolare a forma di salame fino a farlo diventa lungo circa 40-45 cm. Tagliarlo poi a pezzi di 7-8 cm. che arrotoleremo a spirale fino a formare una rosa. Disporli in posizione verticale e distanti fra di loro, in una teglia non molto grande e foderata con la carta forno. Mettere la teglia in forno spento per 1/2 ora. Accendere poi il forno sui 170 gradi per 45 minuti.',4008);
INSERT INTO "ricette" VALUES (26075,'Torta Delle Rose Al Microonde','Dessert','Noci',8,' -','Per L''impasto:,
350 G Farina,
120 G Zucchero,
1/2 Bustina Lievito,
1 Uovo Intero,
1 Tuorlo D''uovo,
100 G Burro,
Per Il Ripieno:,
250 G Noci Tritate,
150 G Uvetta Sultanina,
12 Fette Pancarré Sbriciolato,
2 Cucchiai Zucchero,
1 Limone (scorza Grattugiata),
1/2 Bicchiere Latte,
1 Uovo','Amalgamate farina, zucchero, uova, burro e lievito fino ad ottenere una pasta morbida ed omogenea. In una terrina mescolate le noci, l''uvetta, le fette di pancarré mondate dei bordi e sminuzzate finemente, i due cucchiai di zucchero, la buccia di limone, il latte e l''uovo. Stendete la pasta con il mattarello e fate tante strisce larghe circa 4-5 cm e lunghe circa 12 cm. Su ogni striscia spalmate un po'' di ripieno e arrotolate tipo girella. Disponete tutte le girelle in modo concentrico sul piatto crisp foderato con carta da forno, allargandone le parti superiori in modo che sembrino delle rose. Spennellate con tuorlo d''uovo sbattuto con latte e un cucchiaino di zucchero. Cuocete nel forno a microonde con funzione crisp per circa 16 minuti. Prima di servire potete spolverizzare a piacere con zucchero a velo.',6309);
INSERT INTO "ricette" VALUES (26076,'Torta Delle Vacanze','Dessert','Arance',4,' -','200 G Farina,
200 G Zucchero,
2 Uova,
100 G Ricotta,
2 Arance,
1 Pera,
Lievito,
Burro Per La Teglia','Mescolare la farina e lo zucchero in uguali quantità, circa 2 etti di ciascuno, le uova, la ricotta, il succo e la buccia grattugiata di un''arancia. Tagliare l''altra arancia a fettine e disporle sul fondo di uno stampo imburrato e inzuccherato, dopodichè si fa caramellare. Aggiungere il lievito e la pera a cubetti all''impasto, che poi si mette nella teglia con le arance e quindi in forno. Una volta cotto presentare dalla parte delle pere o dalla parte delle arance.',2194);
INSERT INTO "ricette" VALUES (26077,'Torta Di Adriana','Dessert','Biscotti Amaretti',4,' -','8 Biscotti Amaretti,
4 Uova,
150 G Mandorle,
4 Cucchiai Zucchero,
1 Scorza D''arancia,
Zucchero A Velo','Sbattere i tuorli con lo zucchero e la scorza di arancia grattugiata, aggiungere gli amaretti pestati, le mandorle tritate e le chiare montate a neve. Versare il tutto in una teglia imburrata e infarinata. Mettere in forno caldo 170 gradi per 45 minuti, quando il dolce è freddo si spolverizza con zucchero a velo.',1735);
INSERT INTO "ricette" VALUES (26078,'Torta Di Agrumi A Freddo','Dessert','Arance',4,' -','1 Disco Pan Di Spagna Già Pronto,
2 Arance,
1 Pompelmo,
4 Mandarini,
2 Tuorli D''uovo,
4 Cucchiai Zucchero,
25 Cl Latte,
Maizena,
Scorza D''arancia,
1/2 Bicchiere Succo D''arancia,
4 Cucchiai Marmellata Di Arance (non A Pezzi)','Preparate una crema pasticciera scaldando il latte con una scorza di arancia e aggiungendovi i tuorli sbattuti con lo zucchero e un cucchiaio di maizena. Portate lentamente a ebollizione sempre mescolando con cura. Fate cuocere un paio di minuti, aggiungete un paio di cucchiai di succo di arancia e lasciate raffreddare. Sbucciate la frutta e dividetela in spicchi. Disponete la crema sul disco di pan di spagna, poi partendo dall''esterno formate dei cerchi con gli spicchi di frutta alternati. Preparate una gelatina scaldando in un pentolino 4 cucchiai di marmellata d''arance con il succo di arancia rimasto, spennellate la torta e lasciatela riposare in frigo almeno un''ora prima di servire.',3432);
INSERT INTO "ricette" VALUES (26079,'Torta Di Albicocche','Dessert','Albicocche',4,' -','800 G Albicocche,
250 G Zucchero,
250 G Burro,
4 Uova,
420 G Farina,
1 Bustina Lievito,
40 G Pistacchi Tritati','Sbollentate le albicocche per 15 secondi, spellatele, snocciolatele, dividete ognuna in quattro pezzi. Montate il burro con lo zucchero fino a rendere il tutto ben soffice; incorporate alla crema un uovo alla volta. Unite la farina e mescolate bene; aggiungete la dadolata di albicocche e mescolate ancora. sciogliete il lievito in pochissima acqua tiepida e unitelo al composto. Versate l''impasto in una teglia imburrata e infarinata, cospargete con i pistacchi e cuocete a 190 gradi per circa un''ora.',5084);
INSERT INTO "ricette" VALUES (26080,'Torta Di Albicocche Con Granelli','Dessert','Albicocche',12,' -','Per La Pasta Lievitata:,
250 G Farina,
20 G Lievito Di Birra,
12 Cl Latte,
30 G Burro,
30 G Zucchero,
1 Uovo,
1/4 Cucchiaino Sale,
Burro Per La Teglia,
Farina Per La Teglia,
Per Farcire:,
1000 G Albicocche,
600 G Ricotta,
3 Uova,
150 G Zucchero,
1 Limone (scorza Grattugiata),
4 Cucchiai Fecola Di Patate,
1 Cucchiaio Burro,
150 G Gherigli Di Noci Tritati,
80 G Zucchero A Velo,
1 Albume D''uovo,
50 G Ciliegie Tritate,
Per I Granelli:,
175 G Farina,
100 G Burro,
100 G Zucchero,
1/4 Cucchiaino Cannella In Polvere,
Zucchero A Velo Per Guarnire','Preparate la pasta: setacciate la farina in una capace terrina, fate un incavo al centro e mettetevi il lievito. Scioglietelo con il latte tiepido e impastatelo con un po'' di farina, quindi coprite la terrina con un canovaccio e lasciate riposare il panetto per un quarto d''ora circa. Fate fondere il burro in una casseruola, mescolatevi lo zucchero, l''uovo e il sale e incorporate il composto ottenuto al panetto lievitato e al resto della farina. Lavorate il tutto fino ad ottenere una pasta liscia, omogenea e piuttosto morbida. Quando la pasta comincia a formare delle bolle smettete di lavorarla, copritela con un canovaccio e lasciatela lievitare in un luogo caldo fino a quando sarà raddoppiata di volume. Scottate brevemente le albicocche in acqua bollente, dopodichè sbucciatele, dividetele a metà e privatele del nocciolo. Imburrate e infarinate una tortiera di 35 cm di diametro e rivestitene il fondo e i bordi con la pasta lievitata. Bucherellate questa con i rebbi di una forchetta per evitare che si gonfi durante la cottura. Mettete in una terrina la ricotta, lo zucchero, le uova, la scorza grattugiata di un limone e la fecola di patate e mescolate il tutto fino ad ottenere un composto omogeneo. Stendete la crema ottenuta sulla pasta, quindi copritela con le mezze albicocche, disponendole con il lato tagliato verso l''alto. Fate fondere il burro in una casseruolina a calore dolcissimo, mescolatevi le noci tritate, l''albume e le ciliegie e lavorate il tutto fino ad ottenere un composto morbido e omogeneo. Ponetelo in una tasca di tela con bocchetta liscia e distribuitelo nelle cavità delle mezze albicocche. Mescolate in una terrina la farina, lo zucchero, il burro e la cannella, impastateli rapidamente con le mani e sbriciolate il composto ottenuto, quindi cospargetelo sulla frutta. Lasciate lievitare la torta per 10-15 minuti. Trascorso questo tempo, cuocete il dolce nel forno preriscaldato (200 gradi) per 35-40 minuti. Servite la torta fredda, cosparsa con lo zucchero a velo.',7378);
INSERT INTO "ricette" VALUES (26081,'Torta Di Albicocche E Di Ciliegie','Dessert','Albicocche Sciroppate',8,' -','250 G Farina,
100 G Burro,
1 Uovo,
2 Cucchiai Zucchero,
1 Scatola Albicocche Sciroppate,
1 Scatola Ciliegie Sciroppate,
1 Vasetto Panna,
100 G Mandorle Sgusciate','Fate una pasta frolla con farina, burro sciolto, 1 uovo, un po'' di acqua e un cucchiaio di zucchero. Fate una palla con la pasta e lasciate riposare per 15 minuti. Imburrate una tortiera e stendeteci la pasta, facendo sul fondo, dei fori con una forchetta; cuocete in forno fino a quando la pasta diventa dorata. Frullate la panna con un cucchiai di zucchero e quando è diventata molto densa aggiungete metà delle mandorle tritate. Spargete la panna sul fondo della torta, metteteci sopra le albicocche e le ciliegie e sopra queste il resto delle mandorle tritate.',2730);
INSERT INTO "ricette" VALUES (26082,'Torta Di Albumi','Dessert','Albumi D''uovo',4,'Luogo: Lazio.','150 G Farina,
4 Albumi D''uovo,
80 G Zucchero,
80 G Burro,
1/2 Bustina Lievito,
1 Arancia,
1 Pizzico Cannella,
1 Pizzico Sale,
Per La Salsina:,
4 Kiwi,
1 Bustina Vaniglina Zuccherata,
3 Cucchiai Zucchero A Velo','In una ciotola mescolate la farina (setacciata con il lievito) con lo zucchero, il burro (fatto fondere e lasciato intiepidire), la scorza grattugiata dell''arancia e la cannella. Unite al composto gli albumi montati a neve ben ferma con un pizzico di sale. Versate il tutto in una tortiera imburrata e infarinata, e fate cuocere in forno già caldo a 180 gradi per 35-40 minuti. Intanto preparate la salsina di accompagnamento: sbucciate i kiwi, tagliateli a pezzetti e frullateli in un mixer con lo zucchero e la vaniglina. Servite la torta fredda con la salsina preparata.',1857);
INSERT INTO "ricette" VALUES (26083,'Torta Di Ananas Al Microonde','Dessert','Ananas',4,'Preparazione: 20 minuti. Cottura: 15 minuti.','150 G Farina,
2 Uova,
1 Albume D''uovo,
60 G Burro,
200 G Zucchero Di Canna,
4 Fette Ananas Sciroppato,
1 Bustina Lievito,
1 Limone Non Trattato,
1 Arancia Non Trattata','In una tortiera di vetro mettete il burro e 100 g di zucchero. Cuocete per 3 minuti a media potenza. Nel frattempo sgocciolate le fette d''ananas, avendo cura di conservare il liquido in una tazza. Trascorsi i 3 minuti togliete la pirofila dal forno, mescolate bene e adagiate sul fondo le fette di ananas. In una terrina sbattete 2 tuorli con lo zucchero rimanente. Quando saranno ben gonfi incorporate la farina setacciata e mescolate bene con un cucchiaio di legno. Aggiungete lo sciroppo d''ananas e il lievito e mescolate bene fino a ottenere un composto omogeneo. In un''altra ciotola montate a neve ben ferma 3 albumi Trasferite gli albumi in una ciotola capiente e, mescolando dall''alto verso il basso, incorporate i tuorli lavorati con lo zucchero, la farina e lo sciroppo di ananas. Versate la preparazione nella tortiera, coprite e cuocete per 10 minuti alla massima potenza. Spegnete il forno e lasciate riposare per 5 minuti la torta all''ananas. Trasferite il dolce su una portata. Servitelo tiepido o freddo.',2151);
INSERT INTO "ricette" VALUES (26084,'Torta Di Ananas Rovesciata','Dessert','Ananas',8,' -','200 G Zucchero,
140 G Burro,
1 Uovo,
Latte Tiepido,
200 G Farina,
Sale,
1 Bustina Lievito,
Per La Tortiera:,
Burro,
Zucchero,
Alcune Fette Ananas,
Ciliegine Candite','Lavorare a lungo lo zucchero con 140 g di burro, toglierne 100 g e al resto aggiungere, lavorando ancora bene, un uovo intero, la farina, un pizzico di sale, il lievito e continuare a lavorare, aggiungendo latte tiepido per ottenere una pasta morbida. Spalmare in una tortiera il burro e lo zucchero (messi precedentemente da parte) e decorare con fette d''ananas in conserva, fatte precedentemente sgocciolare e asciugare bene. Al centro delle fette si mette una ciliegina candita, si dividono altre fette a pezzetti per coprire i buchi lasciati tra l''una e l''altra. Versare la pasta sopra a tutto e infornare a 180 gradi per circa 60 minuti. Voltare la tortiera su una pirofila da forno, lasciar intiepidire, togliere la tortiera e spolverizzare la torta di zucchero. Metterla sotto il grill del forno perché si formi il caramello e imbibire, prima di servire.',3819);
INSERT INTO "ricette" VALUES (26085,'Torta Di Arance','Dessert','Arance',6,' -','500 G Arance,
70 G Farina,
20 G Fecola Di Patate,
60 G Zucchero,
2 Uova,
40 G Burro,
1 Bustina Vaniglina,
2 Cucchiai Gelatina Di Albicocche,
3 Cucchiai Rum','Sciogliete il burro in un tegamino. Nel frattempo in una terrina lavorate bene (con una forchetta o meglio con una frusta) le uova e lo zucchero; poi, poco alla volta unitevi la farina, la fecola, la vaniglina ed il burro fuso. Portate il forno a 180 gradi, imburrate la teglia e infarinatela. Versatevi il composto ed infornate per circa mezz''ora. Quando il dolce è cotto, toglietelo dal forno e lasciatelo raffreddare. Una volta freddo, adagiatelo su una tortiera o un vassoio, bagnatelo col rum allungato con un po'' di acqua. Sbucciate le arance e tagliatele a rotelline, e con queste decorate la torta. Scaldate la gelatina di albicocche con un cucchiaio d''acqua e distribuitela sul dolce. Servitelo freddo.',1583);
INSERT INTO "ricette" VALUES (26086,'Torta Di Asparagi','Antipasto','Asparagi',4,' -','300 G Asparagi,
100 G Formaggio Fontina,
3 Uova,
Limone,
100 G Mascarpone,
50 G Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
Burro','Lessare gli asparagi, scolarli e sistemarli in una pirofila imburrata con il formaggio a pezzetti. Sbattere le uova con il mascarpone, il parmigiano, un po'' di succo di limone, sale e pepe. Versare il composto sugli asparagi. Cuocere in forno a 200 gradi per circa 10 minuti.',2130);
INSERT INTO "ricette" VALUES (26087,'Torta Di Asparagi (2)','Antipasto','Asparagi',4,' -','400 G Pasta Sfoglia,
2000 G Asparagi Sottili,
1000 G Coste Di Sedano Tenero,
2 Uova,
30 G Burro,
6 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Mondare asparagi e coste e scottarle separatamente in acqua salata, scolarle bene, tagliarle grossolanamente e ripassarle in padella con il burro. Quando sono fredde unire le uova, il formaggio e regolare di sale e pepe. Foderare una teglia unta con metà della sfoglia, riempirla con il composto e coprire con la rimanente sfoglia sigillandola bene. Fare in mezzo alla sfoglia un foro e cuocere in forno a 200 gradi per circa 40 minuti.',3003);
INSERT INTO "ricette" VALUES (26088,'Torta Di Asparagi (3)','Antipasto','Asparagi',4,' -','Per La Pasta:,
100 G Farina,
50 G Burro,
1/2 Cucchiaio Acqua,
Sale,
Per Il Ripieno:,
1000 G Asparagi,
25 G Burro,
1 Cucchiaio Farina,
3 Uova,
80 G Formaggio Groviera,
1 Bicchiere Latte,
Noce Moscata,
Sale,
Pepe','Mescolate burro e farina, poi sbriciolate il composto fra le mani, disponetelo a fontana sulla spianatoia, versate nel mezzo l''acqua, un pizzico di sale e impastate il tutto. Dategli la forma di una palla e lasciatela riposare mezz''ora. Pulite e lessate gli asparagi. Appena cominciano a diventare teneri, scolateli, asciugateli, tagliateli a pezzetti e fateli insaporire con un po'' di burro. Sbattete in una terrina le uova con sale, pepe, noce moscata, groviera grattugiata e latte. Stendete la pasta a sfoglia sottile e con questa foderate una tortiera imburrata. Disponetevi sul fondo gli asparagi e sopra versate il composto di uova e latte. Cuocete in forno preriscaldato a 170 gradi per circa una ventina di minuti. Servite la torta tiepida.',1872);
INSERT INTO "ricette" VALUES (26089,'Torta Di Baccalà','Pesce','Baccalà',4,' -','300 G Pasta All''olio,
600 G Baccalà Bagnato,
50 Cl Latte,
2 Patate,
20 G Pinoli,
30 G Uvetta Sultanina,
Olive Di Gaeta Snocciolate,
Olio D''oliva Extra-vergine,
Sale,
Pepe Bianco','Cuocere nel latte il baccalà a pezzi, ripulito dalle spine, e frullarlo con il latte. Spianare la pasta all''olio e foderarvi una teglia da forno oliata. Foderare il fondo con fette sottilissime di patate, salare e oliare. Versarvi sopra il baccalà frullato, unire uvetta, pinoli, olive, pepe, olio. Decorare la superficie con strisce di pasta e cuocere in forno. ',2767);
INSERT INTO "ricette" VALUES (26090,'Torta Di Banane','Dessert','Banane',4,' -','150 G Zucchero,
100 G Burro,
150 G Farina,
4 Banane,
50 G Mandorle Tritate,
50 G Frutta Candita,
2 Uova,
1 Limone,
1 Bustina Lievito,
1 Pizzico Sale','Lavorate il burro con 100 g di zucchero fino ad ottenere un composto spumoso, aggiungete le uova ed infine la farina setacciata col lievito ed un pizzico di sale. Mescolate tutto, fate amalgamare bene gli ingredienti ed infine aggiungete i canditi a pezzettini. Imburrate ed infarinate uno stampo rettangolare, versatevi il composto e livellatelo. Sbucciate le banane e tagliatele a fette in verticale, disponetele sull''impasto, bagnatele col succo di limone e cospargetele col resto dello zucchero e le mandorle tritate. Infornate per circa un''ora a calore moderato.',3057);
INSERT INTO "ricette" VALUES (26091,'Torta Di Bietole','Antipasto','Bietole',4,' -','250 G Farina,
1000 G Bietole,
400 G Quagliata,
1 Cipolla Bianca,
1 Bicchiere Olio D''oliva Extra-vergine,
Sale,
Acqua','Formare un impasto consistente amalgamando la farina, due cucchiai d''olio, un po'' d''acqua e il sale. Dividerlo in due parti e lasciarlo riposare coperto per circa un''ora. Lavare le bietole, togliere la parte inferiore, tagliarle a strisce e lessarle per due minuti in acqua salata. Lasciare raffreddare e strizzare con l''ausilio di un canovaccio. Fare soffriggere nell''olio la cipolla tritata, aggiungervi le bietole e il sale, far cuocere per circa 6-7 minuti. Preparare due sfoglie e dopo averle unte, sistemarne una sul fondo di una teglia preventivamente bagnata con un velo d''olio. Versare il ripieno ormai freddo, e spalmarvi la quagliata, salare e coprire con l''altra sfoglia. Chiudere le sfoglie tutt''intorno formando un orlo. Cuocere in forno a fuoco medio (160 gradi) per 40 minuti.',2696);
INSERT INTO "ricette" VALUES (26092,'Torta Di Borraggine E Ricotta','Antipasto','Borraggine',4,'Luogo: Liguria.','400 G Borraggine,
200 G Ricotta,
200 G Farina,
80 G Burro,
1 Uovo,
80 G Formaggio Pecorino Grattugiato,
Sale,
Pepe','Impastare la farina acqua con uovo e sale e formare una palla, che va poi coperta con un panno e lasciata riposare per circa 60 minuti. Bollire e strizzare la borraggine quindi rosolarla sminuzzata nel burro per alcuni minuti; preparare un composto di ricotta, pepe e pecorino, aggiungere il sale e la borraggine. Stendere a sfoglia, la pasta e metterla sul fondo di una teglia imburrata. Riempire con il composto di ricotta, pecorino, borraggine, e chiudere la superficie con la pasta sfoglia. Infornare per 60 minuti a 160 gradi.',1991);
INSERT INTO "ricette" VALUES (26093,'Torta Di Broccoli Alle Nocciole','Contorno','Broccoli',1,' -','1 Uovo,
80 G Ricotta Magra,
40 G Blanc Battu (cagliata Di Formaggio Fresco Magro),
20 G Pangrattato,
50 G Farina,
1 Cucchiaino Lievito In Polvere,
10 G Nocciole Grattugiate,
120 G Rosette Di Broccoli','Mescolare bene sbattendo tutti gli ingredienti, salvo i broccoli. Foderare con carta da forno una tortiera di circa 20 cm di diametro. Stendere la pasta sul fondo e distribuirvi sopra le rosette di broccoli, premendole leggermente nella pasta. Cuocere per circa 30-35 minuti nel forno preriscaldato a 200 gradi.',636);
INSERT INTO "ricette" VALUES (26094,'Torta Di Broccoli E Formaggio','Antipasto','Broccoli',6,'Preparazione: 30 minuti. Cottura: 60 minuti.','500 G Pasta Sfoglia,
400 G Formaggio Bianco,
100 G Formaggi Caprini Freschi,
750 G Foglie Di Broccoli,
1 Spicchio Aglio,
4 Uova,
1 Tuorlo D''uovo,
1 Pizzico Origano,
Sale,
Pepe','Lavate i broccoli, sgocciolateli, divideteli in ciuffetti e lessateli. Cuoceteli per dieci minuti. Sbucciate e tritate l''aglio. Schiacciate il formaggio di capra e mescolatelo al formaggio bianco scelto. Rompete le uova in una ciotola, sbattetele con la forchetta, salate, pepate, aggiungete aglio e origano e incorporatele ai vari formaggi. Sgocciolate i broccoli e mescolateli alla preparazione precedente. Assaggiate e aggiustate il condimento. Fate scaldare il forno a 230 gradi (termostato 7). Dividete la pasta sfoglia in due parti disuguali: due terzi e un terzo. Stendete la parte più grande con il mattarello e guarnitene uno stampo dal fondo amovibile del diametro di 24 cm, lasciando un bordo in eccedenza tutt''intorno. Versatevi la preparazione e lisciatene la superficie. Formate con l''altra parte della pasta un disco di 24 cm di diametro. Aggiungete un cucchiaino di acqua al tuorlo d''uovo previsto per la doratura, sbattetelo con la forchetta e spennellatelo sulla superficie della preparazione contenuta nella tortiera. Posate sopra il disco dì pasta e spalmate anche questo con il tuorlo d''uovo. Ripiegate il bordo con le dita per sigillarlo con il coperchio di pasta. Con un coltellino appuntito praticate un foro al centro del coperchio di pasta e mantenetelo aperto con un piccolo cilindro di cartone. Rigate il coperchio con i denti di una forchetta. Mettete in forno e fate cuocere per venti minuti. Riducete la temperatura a 170 gradi (termostato 5) e lasciate cuocere ancora per 25 minuti. Servite caldo, tiepido o freddo. Non è indispensabile imburrare lo stampo in quanto, essendo unta, la pasta sfoglia non si attacca. In alternativa, questa torta potete prepararla senza coperchio. In questo caso le dosi della pasta sfoglia vanno dimezzate.',4001);
INSERT INTO "ricette" VALUES (26095,'Torta Di Cacao Alla Nutella','Dessert','Nutella',6,' -','200 G Farina,
150 G Zucchero,
50 G Burro,
4 Cucchiai Cacao In Polvere,
4 Uova,
Nutella,
Zucchero A Velo','Sbattete in un recipiente i tuorli con lo zucchero, unitevi la farina, il cacao e metà degli albumi montati a neve. Mescolate il composto ed aggiungetevi il resto degli albumi non montati. Fate sciogliere il burro in un padellino e quando si sarà raffreddato unitelo al composto, quindi mescolate. Imburrate ed infarinate uno stampo rotondo del diametro di circa 20 cm, versatevi il composto e mettete nel forno preriscaldato a 200 gradi per circa 30 minuti. Disponete la torta su un piano e fatela raffreddare, quindi tagliatela in senso orizzontale così da ottenere due dischi. Coprite la superficie di uno dei dischi con abbondante Nutella e ponete l''altro disco sopra quello farcito. Spolverizzate con zucchero a velo.',2595);
INSERT INTO "ricette" VALUES (26096,'Torta Di Cacao E Mandorle','Dessert','Cacao',4,' -','75 G Cacao,
150 G Maizena,
5 Uova Intere,
150 G Zucchero,
150 G Burro,
30 G Mandorle Sbucciate','Lavorate a lungo i tuorli con lo zucchero, unite il burro fuso, il cacao e la maizena. Tenete da parte una ventina di mandorle per decorare e tritate finemente le altre e aggiungetele all''impasto mescolando bene. Battete a neve ferma gli albumi e uniteli all''impasto mescolando dall''alto al basso. Foderate una tortiera di 22 cm. di diametro con carta da forno, versate l''impasto, pareggiate la superficie, decorate con le mandorle e fate cuocere in forno già caldo a 220 gradi per 35 minuti.',3117);
INSERT INTO "ricette" VALUES (26097,'Torta Di Caffè','Dessert','Caffè',6,' -','120 G Farina,
200 G Zucchero,
200 G Burro,
80 G Fecola,
1 Tazzina Caffè,
4 Uova,
1 Bustina Lievito,
Alcuni Chicchi Caffè,
Crema Al Caffè','Montare il burro con lo zucchero, unire la farina e la fecola, il caffè e le uova, una alla volta, incorporandole molto bene. Infine unire il lievito. Versare il composto in una teglia imburrata e infarinata, infornare per 40 minuti a 180 gradi. Quando è fredda guarnire la torta con la crema al caffè e con i chicchi di caffè.',3536);
INSERT INTO "ricette" VALUES (26098,'Torta Di Carciofi','Antipasto','Carciofi',4,'Preparazione: 80 minuti.','500 G Farina Bianca,
12 Carciofi,
6 Limoni,
1 Cipolla,
1 Ciuffo Prezzemolo,
2 Bicchieri Olio D''oliva Extra-vergine,
10 G Formaggio Grana Grattugiato,
100 G Mollica Di Pane,
1 Bicchiere Latte,
8 Uova,
200 G Cagliata,
Sale','Pulire, tagliare a spicchi e mettere a bagno i carciofi. Tritare prezzemolo, cipolla e far rosolare in un cucchiaio di olio, unire i carciofi. Amalgamare il tutto con il formaggio, le foglie di maggiorana, la mollica di pane bagnata nel latte e 4 uova. Fare un impasto con la farina. le uova, l''olio e lasciar riposare 10 minuti. Stendere la pasta in una teglia, versare il composto e ricoprire con un altro strato di pasta. Spolverare la superfice col parmigiano e infornare.',6122);
INSERT INTO "ricette" VALUES (26099,'Torta Di Carciofi (2)','Antipasto','Carciofi',6,' -','400 G Pasta Sfoglia,
1 Uovo,
500 G Fondi Di Carciofo Surgelati,
25 G Burro,
15 G Farina,
15 Cl Latte,
3 Cucchiai Panna,
2 Cucchiai Succo Di Limone,
1/2 Cucchiaino Senape,
2 Cucchiai Prezzemolo Tritato,
100 G Prosciutto,
150 G Formaggio Groviera Grattugiato,
Sale,
Pepe','Portate a ebollizione una pentola con abbondante acqua salata. Aggiungete un cucchiaio dì succo di limone. Immergetevi i fondi di carciofo e lasciateli cuocere per dieci minuti dall''inizio del bollore, fino a quando diventeranno teneri. Nel frattempo fate sciogliere il burro in una casseruola, spolverate di farina e mescolate per un minuto. Irrorate con un po'' di latte e mescolate fino a quando la miscela inizierà a bollire. Togliete la casseruola dal fuoco, incorporatevi il groviera, la panna, il resto del succo di limone, la senape e il prezzemolo; salate e pepate. Lasciate raffreddare completamente. Sgocciolate i fondi di carciofo e tritateli grossolanamente con un coltello. Tritate anche il prosciutto. Aggiungete questi ingredienti alla salsa. Scaldate il forno a 230 gradi (termostato 7). Dividete a questo punto la pasta in due parti. Con una parte di pasta formate un cerchio del diametro di 22 cm e con l''altra parte formatene un altro di 24 cm. Aggiungete un cucchiaino d''acqua fredda all''uovo e sbattetelo con una forchetta. Disponete il cerchio di pasta più piccolo sulla placca del forno. Spennellate metà del perimetro con l''uovo sbattuto su una fascia larga 2,5 cm. Stendete tutta la farcia fredda sulla pasta. Piegate in due l''altro cerchio di pasta. Partendo dalla piega e fermandovi a 2,5 cm dal bordo, praticate dei tagli a una distanza di 1,5 cm l''uno dall''altro. Spiegate con cautela. Avvolgete la pasta sul mattarello leggermente infarinato e disponetela sul cerchio farcito. Saldate quindi il bordo inferiore con quello superiore e sistemate le strisce di pasta. Premete bene i bordi e fate delle striature con l''aiuto di un coltello. Spennellate con tuorlo d''uovo tutta la torta avendo cura che non coli sulla farcia. Fate cuocere in forno caldo per quindici minuti a mezza altezza. Riducete quindi la temperatura del forno a 200 gradi (termostato 6) e fate cuocere per altri dieci minuti fino a quando cioè la superficie sarà della torta diventata dorata. Servite caldo o freddo.',3264);
INSERT INTO "ricette" VALUES (26100,'Torta Di Carciofi (3)','Antipasto','Carciofi',6,' -','1 Confezione Pasta Sfoglia,
8 Carciofi,
2 Patate,
100 G Formaggio Pecorino Dolce,
12 Olive Verdi Snocciolate,
1 Spicchio Aglio,
Olio D''oliva,
2 Uova,
50 G Formaggio Parmigiano Grattugiato,
1/2 Bicchiere Panna,
1 Ciuffo Prezzemolo,
Sale,
Pepe','Pulite i carciofi, lavateli e tagliateli a fettine. Scaldate in un tegame due cucchiai di olio con lo spicchio d''aglio e mettetevi a rosolare i carciofi. Salate, pepate, lasciate cuocere coperto mezz''ora. Quando sono i carciofi sono pronti passateli in una terrina, unite il parmigiano e il pecorino grattugiati, la panna, le uova, le olive. Mescolate. Imburrate una tortiera, foderatela con la pasta sfoglia tirata a disco, versatevi il composto e cuocete in forno preriscaldato a 170 gradi per circa quaranta minuti. Ritirate dal forno e servite questa torta tiepida, ma non troppo.',3503);
INSERT INTO "ricette" VALUES (26101,'Torta Di Carciofi (4)','Antipasto','Carciofi',4,' -','1 Disco Pasta Sfoglia Pronta,
400 G Ricotta,
4 Carciofi,
1 Spicchio Aglio,
Olio D''oliva,
100 G Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
2 Uova','Pulite i carciofi, eliminate le foglie esterne e tagliateli a fettine sottili. Fate imbiondire l''aglio in poco olio, aggiungete i carciofi, salate pepate e fate cuocere per 10 minuti. Sbattete le uova con un pizzico di sale, incorporate la ricotta e il parmigiano. Stendete in una pirofila da forno la pasta sfoglia, versatevi metà del composto di ricotta, i carciofi, il rimanente composto. Cuocete in forno già caldo a 180 gradi per 30 minuti.',2619);
INSERT INTO "ricette" VALUES (26102,'Torta Di Carciofi (5)','Contorno','Carciofi',4,' -','120 G Farina,
400 G Carciofi,
250 G Pomodori Pelati,
2 Uova,
20 G Formaggio Groviera Grattugiato,
5 Cl Latte,
1 Filo Olio D''oliva,
Sale,
Succo Di Limone','Lavorare la farina con una presa di sale e tanta acqua quanto basta ad ottenere un impasto elastico. Scottare in acqua bollente acidulata con limone i carciofi, affettarli e cuocerli per 20 minuti in padella con i pomodori. Sbattere le uova con il latte e il groviera. Stendere la pasta in una teglia unta, coprirla con i carciofi, le uova sbattute e un filo d''olio. Salare e infornare a 200 gradi per 30 minuti.',1202);
INSERT INTO "ricette" VALUES (26103,'Torta Di Carciofi (6)','Contorno','Carciofi',1,' -','2 Carciofi,
2 Uova,
25 G Formaggio Grana,
2 Cucchiai Olio D''oliva','Tagliare i carciofi a spicchi e lessarli. Unire le uova sbattute, il grana e i carciofi. Cuocere in forno a 180 gradi per 15 minuti.',671);
INSERT INTO "ricette" VALUES (26104,'Torta Di Carciofi Alla Mozzarella','Antipasto','Carciofi',4,' -','8 Carciofi,
1 Mozzarella,
Pasta Sfoglia Surgelata,
2 Uova,
Formaggio Grattugiato,
Burro,
Olio D''oliva,
Limone,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
Sale,
Pepe','Dividete i carciofi a spicchi e cuoceteli in acqua acidulata con limone per 15 minuti. Imburrate uno stampo da crostata, stendetevi la pasta sfoglia, sopra disponete metà mozzarella tagliata a fettine. In una ciotola amalgamate le uova con il formaggio grattugiato, uno spicchio d''aglio con un ciuffo di prezzemolo tritati e la restante mozzarella a dadini. Distribuite i carciofi sulla pasta, ricopriteli con il composto preparato, salate, pepate, irrotate d''olio e passate nel forno a 180 gradi per 40 minuti.',2930);
INSERT INTO "ricette" VALUES (26105,'Torta Di Carote','Dessert','Carote',4,' -','100 G Zucchero,
250 G Carote,
250 G Farina,
2 Uova,
1 Bustina Lievito In Polvere,
150 G Mandorle,
1 Bicchierino Latte,
1 Noce Burro,
1/2 Limone (scorza)','Mescolare lo zucchero con le carote frullate, avendo cura di eliminare prima tutto il liquido che si formerà. Unire la farina, le uova ben sbattute, poi le mandorle tritate, 1 l di latte e una noce di burro. Aggiungere la bustina di lievito e la scorza del limone. Mescolare molto bene per amalgamare i vari ingredienti e versare in una teglia imburrata. L''impasto deve avere la consistenza di una crema. Far cuocere in forno ben caldo (non sono indicati nè la temperatura nè il tempo di cottura..). Lasciare raffreddare. Note: prima di infornare aggiungere un pizzico di sale fino; le dimensioni della teglia sono di circa 30 cm di diametro.',2838);
INSERT INTO "ricette" VALUES (26106,'Torta Di Carote (10)','Dessert','Carote',6,' -','1500 G Carote,
25 Cl Latte,
6 Uova,
2 Cucchiai Farina,
125 G Zucchero A Velo,
1 Noce Burro','Preparate la crema sbattendo 2 tuorli d''uovo con lo zucchero e aggiungendo la farina e il latte bollente. Mettete la vaniglia e lasciate cuocere per 3 minuti o comunque fino a quando è diventata densa. Cuocete la carote e poi fatene un purè e mescolatelo alla crema. Aggiungete 4 tuorli d''uovo e mescolate il tutto aggiungendo gli albumi montati a neve. Imburrate una tortiera e versateci dentro il composto. Lasciate cuocere per 1 ora o comunque fino a quando, mettendo un ago nel centro del dolce, ne esca asciutto.',2102);
INSERT INTO "ricette" VALUES (26107,'Torta Di Carote (2)','Dessert','Carote',4,' -','100 G Farina Bianca,
400 G Carote Raschiate Senza Estremi E Tritate,
200 G Mandorle Dolci,
200 G Zucchero,
3 Uova,
2 Cucchiai Latte,
5 G Lievito In Polvere,
Zucchero A Velo Vanigliato','Sbollentare le mandorle, sgocciolarle, privarle della pelle, asciugarle e passarle infine nel tritamandorle. In una ciotola metto i tuorli (conservo gli albumi) con lo zucchero; lavoro bene con un cucchiaio di legno sino ad ottenere una crema liscia, aggiungo quindi le carote, le mandorle, il latte, il lievito e mescolo il tutto. Aggiungo quindi gli albumi montati a neve e verso il composto nella tortiera; passo in forno (175 gradi) per 40 minuti circa.',2684);
INSERT INTO "ricette" VALUES (26108,'Torta Di Carote (3)','Dessert','Carote',4,' -','Carote,
Uova,
4 Cucchiai Acqua Calda,
Zucchero Vanigliato,
150 G Zucchero,
200 G Nocciole Tritate,
1 Cucchiaio Rum,
Lievito,
Sale,
4 Cucchiai Pangrattato,
1 Limone','Raschiare e lavare le carote, poi grattugiarle finemente. Sgusciare le uova separando i tuorli dagli albumi. Mettere i tuorli in una terrina, aggiungere l''acqua calda e sbatterli bene con una frusta aggiungendo lentamente lo zucchero vanigliato e lo zucchero fino a ottenere una crema densa. Unire al composto le carote grattugiate, le nocciole tritate, il rum, il pangrattato, la scorza grattugiata del limone, il lievito e amalgamare bene. Montare gli albumi a neve con un pizzico di sale e con un po'' di zucchero. Incorporarli al composto mescolando delicatamente dal basso verso l''alto. Ungere uno stampo di 24 cm di diametro, cospargerlo con un po'' di pangrattato, quindi versarvi il composto. Livellarlo bene, poi mettere la torta in forno caldo a 180 gradi per un''ora.',2604);
INSERT INTO "ricette" VALUES (26109,'Torta Di Carote (4)','Dessert','Carote',4,' -','300 G Carote,
300 G Mandorle,
300 G Zucchero,
30 G Farina O Fecola,
6 Uova Intere,
1 Limone (scorza),
1 Bustina Vaniglina,
Rum','Dopo aver lavato e raschiato leggermente le carote, grattugiatele finemente e raccoglietele in un telo. Lasciate che depositino la loro acqua, quindi cambiate e asciugatele strofinandole delicatamente. Ripetete questa operazione più volte se necessario.Tritate finissime le mandorle senza sbucciarle. Montate a neve fermissima gli albumi con un pizzico di sale e aggiungetevi, facendo attenzione a non smontarli, lo zucchero, le carote, le mandorle, la fecola e la buccia grattugiata di un limone. Battete i tuorli con il rum e incorporateli poco alla volta al composto. Imburrate e infarinate una tortiera di 24 cm di diametro, versatevi l''impasto e infilate nel forno (preriscaldato a 170 gradi). Cuocete la torta per 35-40 minuti. Lasciatela intiepidire prima di sfornarla. Toglietela dal forno dopo 15-20 minuti, adagiatela su un piatto da portata e ricopritela di zucchero a velo.Servitela quando sarà completamente raffreddata.',3864);
INSERT INTO "ricette" VALUES (26110,'Torta Di Carote (5)','Dessert','Carote',4,' -','450 G Carote,
250 G Mandorle,
120 G Farina,
3 Uova,
50 G Burro,
120 G Zucchero,
Poco Latte,
1 Bicchierino Brandy,
1 Bustina Vaniglina,
1 Bustina Lievito,
1 Bustina Zucchero Vanigliato','Sbattere a spuma i tuorli con lo zucchero, unire la farina, il burro fuso, le carote e le mandorle tritate, il brandy, la vaniglina, il lievito diluito con poco latte e gli albumi a neve. Versare il composto in una teglia imburrata e infarinata e cuocere in forno già caldo per 30 minuti. Spolverizzare con zucchero vanigliato.',3184);
INSERT INTO "ricette" VALUES (26111,'Torta Di Carote (6)','Dessert','Carote',4,' -','300 G Carote,
150 G Mandorle,
200 G Fecola,
3 Uova,
100 G Zucchero,
1 Bustina Lievito,
1 Pizzico Sale,
1 Limone (succo)','Tritare, intanto, le carote e le mandorle e porle a parte. Montare i tuorli con lo zucchero, aggiungere la fecola, il succo del limone e il lievito, unire i bianchi montati a parte a neve ed il composto di carote e mandorle. Mettere in una tortiera unta ed infarinata e cuocere in forno a 180 gradi per circa 50''.',2075);
INSERT INTO "ricette" VALUES (26112,'Torta Di Carote (7)','Dessert','Carote',4,' -','450 G Carote,
250 G Mandorle Tritate,
3 Uova,
120 G Farina,
50 G Burro,
120 G Zucchero,
1 Bicchierino Brandy,
1 Bustina Vaniglina,
1 Bustina Lievito,
Zucchero A Velo','Lavare e grattugiare le carote e mescolarle alle mandorle. Battere i tuorli con lo zucchero e unirvi la farina, il burro fuso, la vaniglina, carote e mandorle, il brandy. Sciogliere il lievito e aggiungerlo al composto. Montare a neve soda gli albumi e unirli all''impasto. Versare il tutto in uno stampo imburrato e infarinato e infornare a 180 gradi per 30''. Far raffreddare la torta, sfornarla e spolverizzarla di zucchero a velo.',3189);
INSERT INTO "ricette" VALUES (26113,'Torta Di Carote (8)','Dessert','Carote',4,' -','320 G Carote,
200 G Mandorle Tritate,
100 G Nocciole Tritate,
250 G Zucchero,
3 Uova,
Scorza Di Limone,
50 G Farina,
1 Bustina Lievito','Pulite le carote, grattugiatele finemente e impastatele in una ciotola con i tuorli delle uova (conservate l''albume), la farina, il lievito, lo zucchero, le mandorle e le nocciole. Ottenuto un impasto omogeneo, grattugiate un po'' di buccia di limone e poi incorporate gli albumi montati a neve ferma. Foderate con la carta da forno uno stampo da dolci e versatevi il composto. Cuocete a 180 gradi (forno preriscaldato) per 50 minuti. Fate raffreddare prima di servire.',3262);
INSERT INTO "ricette" VALUES (26114,'Torta Di Carote (9)','Dessert','Carote',4,' -','700 G Carote,
150 G Mandorle Sgusciate,
150 G Zucchero,
70 G Fecola Di Patate,
4 Uova,
1 Limone,
1 Bustina Lievito Bertolini,
Burro,
Zucchero A Velo','Spuntate le carote, pelatele, lavatele con cura, asciugatele con della carta assorbente e frullatele servendovi di un mixer da cucina. In un recipiente piuttosto capiente, unite i tuorli, lo zucchero e cominciate a mescolare energicamente aiutandovi con una frusta fino a quando non otterrete un composto spumoso. Aggiungete anche le carote grattugiate, la buccia del limone lavata e grattugiata e le mandorle tritate senza spellarle. Amalgamate con cura l''impasto e infine, aggiungete la fecola e incorporate poco per volta anche gli albumi montati a neve. Girate il composto e per finire unite il lievito. Versate il tutto in una tortiera, precedentemente imburrata e spolverizzata con della farina e cuocete in forno già caldo per circa 40 minuti a 180 gradi controllando di tanto in tanto la cottura. Lasciate intiepidire la torta e cospargetela con dello zucchero a velo.',3038);
INSERT INTO "ricette" VALUES (26115,'Torta Di Carote Agli Agrumi','Dessert','Carote',4,' -','200 G Farina,
100 G Zucchero,
4 Cucchiai Latte,
8 Cucchiai Olio D''oliva,
200 G Carote Grattugiate,
100 G Mandorle Tritate,
100 G Formaggio Philadelphia,
5 Cucchiai Miele,
1 Arancia (scorza Grattugiata),
1 Limone (scorza Grattugiata),
1/2 Bustina Lievito','Impastate la farina col lievito, il latte, l''olio e lo zucchero, lavorate l''impasto aggiungendo se necessario qualche cucchiaio d''acqua, poi formate una palla, copritela con uno strofinaccio umido e fatela riposare in frigo per 1 ora. Impastate le carote grattugiate col formaggio, il miele, la scorza di arancia e limone e le mandorle tritate. Stendete la pasta col mattarello, rivestite uno stampo da dolci apribile e versatevi il composto di carote. Cuocete in forno già caldo a 180 gradi per 40 minuti.',3685);
INSERT INTO "ricette" VALUES (26116,'Torta Di Castagne','Dessert','Castagne',10,' -','900 G Passato Di Castagne,
1 1/2 Bustina Lievito,
240 G Burro,
9 Tuorli D''uovo,
120 G Cioccolato Fondente,
420 G Zucchero,
100 G Mandorle,
6 Cucchiai Rum,
Per La Crema:,
6 Tuorli D''uovo,
120 G Zucchero,
375 G Mascarpone,
300 Cl Panna,
180 G Passato Di Castagne','Lessare le castagne precedentemente incise i modo da poterle sbucciare con facilità Fare bollire per 30 minuti. Fate ammorbidire il burro e sciogliere il cioccolato a bagno maria. Sbattere i tuorli con lo zucchero, la scorza di limone, la vaniglina, un pizzico di sale. Amalgamare il composto con il burro e cioccolato, unite alle mandorle polverizzate, il passato di castagne, il rum e il lievito fino ad ottenere un composto soffice. Incorporate al composto gli albumi montati a neve. Versate il composto finale in due stampi di circa 25 cm di diametro e mettere nel forno già a 190 gradi per 50 minuti. Sbattere i tuorli con lo zucchero e incorporateli al mascarpone, ad un cucchiaio di rum, al passato di castagne e alla panna montata. Prendete i due dischi di pasta cotta e farciteli con il composto ottenuto. Spolverate di zucchero a velo e servite.',20923);
INSERT INTO "ricette" VALUES (26117,'Torta Di Castagne (10)','Dessert','Castagne',4,' -','500 G Castagne,
250 G Panna Montata,
250 G Burro,
150 G Farina,
150 G Zucchero,
10 Uova,
1 Presa Sale,
Per La Tortiera:,
15 G Burro,
Farina','Fate cuocere le castagne in una pentola piena d''acqua per circa 1 ora, poi scolatele, sbucciatele, privatele della pellicina e passatele al setaccio. Spaccate le uova, separando i tuorli dagli albumi, e montate questi albumi a neve ben soda. Mettete il burro in una terrina, unitevi lo zucchero e lavoratelo con un cucchiaio di legno fino a ottenere un composto cremoso e omogeneo, quindi amalgamatevi la presa di sale, le castagne, i tuorli, la farina, e mescolando delicatamente per non smontarli, gli albumi montati a neve. Imburrate una tortiera e cospargetela di farina; versatevi il composto, livellatelo e infornate a 180 gradi per 1 ora. A cottura ultimata, togliete la tortiera dal forno, lasciatela raffreddare e sformatela sopra un piatto da portata; ricavatene due dischi inferiori, sovrapponetevi il secondo disco, ricomponendo la torta, e , mediante una tasca da pasticciere, decoratene la superficie con la panna rimasta.',5948);
INSERT INTO "ricette" VALUES (26118,'Torta Di Castagne (2)','Dessert','Castagne',6,' -','600 G Castagne,
200 G Zucchero,
100 G Burro A Pezzetti,
100 G Mandorle Tritate,
3 Uova,
1/2 Limone (scorza Grattugiata),
Sale,
Farina','Sbucciare e lessare le castagne in acqua salata. Passarle al passaverdure e mettere la purea in una terrina. Battere i tuorli con lo zucchero e montare a neve soda gli albumi. Unire i tuorli, il burro, le mandorle e la scorza di limone alla purea di castagne e amalgamare. Aggiungere gli albumi. Versare il composto in una tortiera imburrata e infarinata e cuocere in forno caldo a 180 gradi per circa 40 minuti.',3800);
INSERT INTO "ricette" VALUES (26119,'Torta Di Castagne (3)','Dessert','Castagne',4,' -','300 G Farina Di Castagne,
50 G Zucchero,
25 Cl Latte,
30 G Burro,
50 G Uvetta Sultanina,
50 G Pinoli,
2 Cucchiai Olio D''oliva,
1 Arancia,
10 Noci','Mettete la farina di castagne in una terrina, aggiungetevi lo zucchero, l''olio e il latte un po'' alla volta, mescolando col cucchiaio di legno e se l''impasto non sarà abbastanza molle diluite con un po'' d''acqua. Aggiungete poi l''uvetta, ammollata in acqua tiepida, noci e pinoli tritati e la buccia d''arancia grattugiata. Amalgamate tutti gli ingredienti. Imburrate ed infarinate una teglia, versatevi il composto, livellatelo, copritelo con un filo d''olio ed infornate per un''ora.',3008);
INSERT INTO "ricette" VALUES (26120,'Torta Di Castagne (4)','Dessert','Castagne',4,' -','5 Uova,
200 G Burro,
150 G Zucchero,
160 G Farina Di Castagne,
80 G Fecola,
1 Manciata Uvetta Sultanina,
1 Manciata Pinoli,
1 Cucchiaio Lievito In Polvere,
7 Marroni Canditi','Far rinvenire l''uvetta. Mescolare la farina con la fecola e il lievito. In una terrina lavorare a spuma il burro e lo zucchero poi incorporare uno alla volta i tuorli delle uova e mescolare sino ad ottenere un composto soffice. Montare a neve gli albumi delle uova. Continuando a mescolare, aggiungere alla crema di burro delle cucchiaiate di neve alternate a cucchiaiate di farina e lievito. Per ultimo unire l''uvetta, i pinoli e i marroni spezzettati. Cuocere a 170 gradi per circa 50 minuti.',4779);
INSERT INTO "ricette" VALUES (26121,'Torta Di Castagne (5)','Dessert','Castagne',4,' -','600 G Castagne,
200 G Zucchero Semolato,
100 G Burro,
80 G Mandorle Dolci Pelate,
3 Uova,
1 Limone (scorza Grattugiata),
Per La Tortiera:,
Burro,
Farina','Sbucciate le castagne e fatele lessare in acqua leggermente salata. Dopo averle scolate, togliete la pellicina e passatele al passaverdura ottenendo un purè fine che metterete in una terrina. In un''altra ciotola battete i tuorli d''uovo con lo zucchero, unitevi il burro a pezzetti, il passato di castagne, le mandorle tritate e la scorza del limone grattugiato. A parte, montate a neve soda gli albumi e incorporatele al composto un poco alla volta. Imburrate e infarinate leggermente una tortiera, versatevi il composto, livellatelo e passate al forno ben caldo per 40 minuti. Controllate la cottura infilando uno stecchino nella torta: deve essere asciutto. Sfornate e lasciate intiepidire, quindi servite.',4439);
INSERT INTO "ricette" VALUES (26122,'Torta Di Castagne (6)','Dessert','Farina Di Castagne',4,' -','200 G Farina Di Castagne,
2 Cucchiai Olio D''oliva,
1 Limone (scorza Grattugiata),
50 G Pinoli,
Latte,
1 Bustina Lievito Bertolini,
Sale','In un recipiente capiente disponete la farina di castagne, aggiungete l''olio, un pizzico di sale, la scorza del limone grattugiata e il latte. Mescolate con cura tutti gli ingredienti servendovi di un cucchiaio di legno, fino ad ottenere un composto omogeneo, morbido e senza grumi. Nel frattempo, ungete d''olio uno stampo per dolci spolverizzandolo con della farina e versate il composto distribuendolo uniformemente. Mettete in forno già caldo e lasciate cucinare per circa 30-35 minuti a 180 gradi controllando di tanto in tanto la cottura. Sfornate infine la torta, lasciatela raffreddare e servite. Accorgimento: togliete la torta dal forno solo quando la superficie sarà dorata e l''interno asciutto. Potreste verificarlo, con uno stecchino. Suggerimento: servite la torta spolverizzandola con dello zucchero a velo o del cacao amaro.',1365);
INSERT INTO "ricette" VALUES (26123,'Torta Di Castagne (7)','Dessert','Castagne',4,' -','150 G Burro,
200 G Zucchero,
1000 G Castagne Bollite,
150 G Cioccolata Grattugiata,
8 Biscotti Amaretti,
Panna Montata','Impastare bene il burro e lo zucchero, unite le castagne bollite, pelate e passate al setaccio, la cioccolata grattugiata e gli amaretti tritati. Foderate uno stampo con una leggera garza e versateci l''impasto che terrete in fresco almeno per una notte. Prima di servire capovolgete lo stampo e guarnite con panna montana e cioccolata.',5020);
INSERT INTO "ricette" VALUES (26124,'Torta Di Castagne (8)','Dessert','Castagne Secche',4,' -','400 G Castagne Secche,
1 Pizzico Sale,
1 Foglia Alloro,
100 G Mandorle,
100 G Burro A Temperatura Ambiente,
200 G Zucchero,
4 Uova,
1 Limone (scorza Grattugiata),
Burro (o Margarina),
Per La Tortiera:,
Pangrattato','Lessate le castagne in abbondante acqua, con l''alloro e un pizzico di sale. Scolatele e passatele ancora calde nel passaverdure. Immergete le mandorle in acqua bollente, spellatele e tritatele finemente. In una terrina sbattete con un cucchiaio di legno il burro con lo zucchero, aggiungendo i tuorli, uno per volta, la buccia di limone e rimescolate energicamente. Incorporate le mandorle e le castagne e infine gli albumi montati a neve fermissima, mescolate il tutto. Versate il composto in una tortiera di circa cm 24 di diametro, imburrata e passata con il pangrattato. Infornare a 210 gradi per 40 minuti circa. La torta sarà cotta quando, introducendo uno stecchino, questo uscirà pulito. Si serve calda o fredda.',4791);
INSERT INTO "ricette" VALUES (26125,'Torta Di Castagne (9)','Dessert','Castagne',4,' -','400 G Castagne,
250 G Burro,
180 G Zucchero,
150 G Farina Bianca,
9 Uova,
200 G Panna Montata','Pelare le castagne, farle bollire e passarle al passaverdura. In una terrina sbattere a lungo il burro con lo zucchero e aggiungere a poco a poco, sempre mescolando, 280 g della purea di castagne, e poi 1 alla volta i 9 tuorli. Montare gli albumi a neve ed aggiungere anche questi al composto, mescolando molto delicatamente, per ultimo unire la farina bianca setacciata. Versare l''impasto in uno stampo di circa 30 cm di diametro precedentemente imburrato e infarinato, quindi passare in forno a 180 gradi. Dopo circa 1 ora la torta sarà cotta: lasciarla raffreddare, toglierla dallo stampo, tagliarla in 2-3 strati e farcirla con la panna montata e con la purea di castagne rimasta.',5211);
INSERT INTO "ricette" VALUES (26126,'Torta Di Cavolo E Cavolfiore','Antipasto','Cavolo',6,' -','800 G Cavolfiore,
400 G Cavolo,
60 G Burro,
150 G Formaggio Fontina,
1 Scalogno,
3 Uova,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe,
Per La Pasta:,
125 G Farina Bianca,
125 G Farina Integrale,
100 G Burro,
Sale','Lavate il cavolfiore e lessatelo al dente in acqua leggermente salata. Scolatelo, dividetelo a cimette e fatele rosolare in un tegame con lo scalogno tritato, un po'' di burro e un cucchiaio di olio. Tagliate il cavolo a listarelle, unitele al cavolfiore e lasciatele appassire. Salate e pepate. Rassodate le uova. Impastate la farina con il burro, un po'' d''acqua e un pizzico di sale. Fate riposare la pasta per un''ora, poi dividetela a metà, stendetene una parte a sfoglia e adagiatela in una tortiera imburrata facendola risalire anche lungo il bordo. Distribuite sul fondo uno strato di fettine di uova sode, uno di cavolo, uno di fettine di fontina, uno di cavolfiore e via di seguito fino a esaurimento degli ingredienti. Coprite con la restante pasta sfoglia anch''essa tirata a disco, bucherellate la superficie, spennellatela di olio e cuocete in forno preriscaldato a 170 gradi per mezz''ora. Servite la torta tiepida.',3525);
INSERT INTO "ricette" VALUES (26127,'Torta Di Ciliegie','Dessert','Ciliegie',4,' -','150 G Zucchero,
150 G Burro,
150 G Farina,
50 G Mandorle Tritate,
4 Uova,
350 G Ciliegie,
1 Bicchiere Rum','Lavate le ciliegie, togliete il gambo, snocciolatele ed immergetele nel rum per mezz''ora. Lavorate il burro insieme allo zucchero e poi aggiungete la farina e i tuorli. Montate gli albumi ed aggiungete anche questi insieme alle mandorle tritate. Imburrate ed infarinate uno stampo rettangolare, versatevi l''impasto, livellatelo e copritelo con le ciliegie sgocciolate. Infornate per 40 minuti.',3362);
INSERT INTO "ricette" VALUES (26128,'Torta Di Ciliegie (2)','Dessert','Ciliegie',4,' -','400 G Ciliegie Snocciolate,
3 Uova,
200 G Zucchero,
250 G Farina,
1 Bustina Lievito,
100 G Nocciole Tritate,
1 Pizzico Sale','Sbattete le uova con lo zucchero, aggiungete la farina, il lievito, un pizzico di sale e le nocciole tritate. Foderate uno stampo con la carta da forno, versateci l''impasto. Aggiungete le ciliegie (in questo modo non si depositeranno tutte sul fondo del dolce). Cuocete in forno caldo a 180 gradi per 45 minuti.',2675);
INSERT INTO "ricette" VALUES (26129,'Torta Di Ciliegie Con Granelli','Dessert','Ciliegie',12,' -','Per La Pasta Lievitata:,
250 G Farina,
20 G Lievito Di Birra,
12 Cl Latte,
40 G Burro,
30 G Zucchero,
1 Uovo,
1/2 Limone (scorza Grattugiata),
1 Cucchiaino Sale,
Burro Per La Teglia,
Farina Per La Teglia,
Per Farcire:,
25 Cl Latte,
20 G Fecola Di Patate,
1/2 Stecca Vaniglia,
3 Tuorli D''uovo,
60 G Pasta Di Mandorle,
1000 G Ciliegie,
Per I Granelli:,
350 G Farina,
200 G Burro,
200 G Zucchero,
1/2 Stecca Vaniglia','Preparate la pasta: setacciate la farina in una capace terrina, fate un incavo al centro e mettetevi il lievito. Scioglietelo con il latte tiepido e impastatelo con un po'' di farina, quindi coprite la terrina con un canovaccio e lasciate riposare il panetto per un quarto d''ora circa. Fate fondere il burro in una casseruola, mescolatevi lo zucchero, l''uovo, la scorza grattugiata del limone e il sale e incorporate il composto ottenuto al panetto lievitato e al resto della farina. Lavorate il tutto fino ad ottenere una pasta liscia, omogenea e piuttosto morbida. Quando la pasta comincia a formare delle bolle smettete di lavorarla, copritela con un canovaccio e lasciatela lievitare in un luogo caldo fino a quando sarà raddoppiata di volume. Nel frattempo preparate la farcitura: versate il latte, tranne due cucchiai, in una casseruola, unitevi la stecca di vaniglia e portatelo ad ebollizione. In una scodella mescolate il resto del latte con i tuorli e la fecola, aggiungetelo al latte caldo e fate bollire il tutto a calore moderato fino a quando si sarà formata una crema densa. Toglietela dal fuoco, cospargetela con un po'' di zucchero a velo e lasciatela raffreddare. Incorporate alla crema fredda la pasta di mandorle sminuzzata, servendovi di una frusta. Rivestite con la pasta lievitata una teglia rettangolare di 43 x 33 cm, imburrata e infarinata, bucherellatela con una forchetta, copritela con la crema e distribuite sopra questa le ciliegie, lavate e snocciolate. Mescolate in una terrina la farina, lo zucchero, il burro e l''interno della stecca di vaniglia, impastateli rapidamente con le mani e sbriciolate il composto ottenuto, quindi cospargetelo sulla frutta. Lasciate lievitare la torta per 10-15 minuti, dopodichè cuocetela nel forno già caldo (210-220 gradi) per circa 40 minuti.',6557);
INSERT INTO "ricette" VALUES (26130,'Torta Di Cioccolato','Dessert','Cioccolato Amaro Fondente',4,'Luogo: Sardegna.','125 G Burro Freschissimo,
200 G Cioccolato Amaro Fondente,
125 G Zucchero,
3 Uova,
2 Cucchiai Farina Bianca','Far fondere il cioccolato con 2 cucchiai di acqua a bagnomaria, aggiungere lo zucchero e il burro a pezzi. Togliete dal fuoco, mettere in una ciotola e unire i rossi d''uovo. Quando l''impasto si è raffreddato, aggiungere la farina bianca e gli albumi delle uova montati a neve. Mettere l''impasto in una tortiera di 24 cm di diametro e infornare a 200 gradi. Togliere dopo 40 minuti per non lasciare indurire la torta. Se desiderate, potete montare un piccola confezione di panna liquida come guarnizione.',2769);
INSERT INTO "ricette" VALUES (26131,'Torta Di Cioccolato All''arancia','Dessert','Cacao Amaro',8,' -','375 G Zucchero,
250 G Burro,
250 G Farina,
5 Uova Grandi,
5 Cucchiai Cacao Amaro,
1 Cucchiaino Lievito Vanigliato,
2 Arance Grandi Non Trattate,
Per Guarnire:,
Scorza D''arancia Candita,
Zucchero A Velo,
Marmellata Di Arance','Tagliate il burro a pezzetti e lasciatelo ammorbidire in ambiente tiepido. Rompete le uova in una ciotola, unitevi lo zucchero e montatele con la frusta elettrica fino a che diventeranno chiare e spumose. Aggiungete il burro e continuate a lavorare il composto con la frusta finché tutto sarà ben amalgamato e perfettamente liscio. Mescolate la farina con il lievito e aggiungetela all''impasto facendola cadere un po'' alla volta da un setaccino e amalgamandola con un cucchiaio di legno con un movimento dall''alto in basso. Unite la scorza delle arance grattugiata e mescolate ancora. Spremete le arance, versate la metà del succo in un pentolino e scaldatelo leggermente. Scioglietevi il cacao e aggiungete questa miscela al composto. Versate il resto del succo nel pentolino per recuperare tutto il cacao e versate anche questo nella ciotola. Lavorate l''impasto con la frusta per un altro minuto per amalgamare perfettamente tutti gli ingredienti. Imburrate una tortiera del diametro di 26 cm, foderatela con la carta da forno (un disco e una striscia), imburrate anche questa e versatevi il composto che risulterà piuttosto fluido. Mettete la torta nel forno precedentemente scaldato a 180 gradi e lasciatelo cuocere per circa tre quarti d''ora. Lasciatela raffreddare, sformatela e decoratela a piacere con zucchero a velo e scorze di arancia candite. A piacere potete accompagnare la torta con una marmellata di arancia diluita con poca acqua calda zuccherata.',5492);
INSERT INTO "ricette" VALUES (26132,'Torta Di Cioccolato Alla Melassa','Dessert','Cacao Amaro',6,' -','230 G Burro,
180 G Farina,
250 G Zucchero Di Melassa,
120 G Olio Di Semi Di Mais,
1/2 Bustina Lievito In Polvere,
50 G Cacao Amaro,
2 Cucchiai Succo Di Limone,
230 G Zucchero Di Canna,
80 G Mascarpone,
4 Uova,
3 Cucchiai Zucchero A Velo','Ponete in una terrina il burro ammorbidito, l''olio e lo zucchero di melassa e lavorate il tutto con una frusta fino ad ottenere un composto cremoso. Incorporatevi, poco per volta, le uova sbattute, la farina, il cacao e il lievito, precedentemente setacciati assieme, e continuate a lavorare gli ingredienti fino a quando l''impasto sarà liscio e omogeneo. Distribuitelo in parti uguali in due teglie di 20 cm di diametro, imburrate e infarinate, e fatelo cuocere nel forno caldo (180 gradi) per 30-35 minuti. Trascorso questo tempo, togliete le teglie dal forno, lasciate riposare le due torte per alcuni minuti, dopodichè sformatele su una griglia e fatele raffreddare. Nel frattempo riunite in una terrina il mascarpone, lo zucchero di canna e i due cucchiai di succo di limone e lavorateli con una frusta fino a quando avrete ottenuto una crema densa e omogenea. A questo punto adagiate una delle due torte su un piatto di portata, spalmatevi sopra la crema e ricopritela con la seconda torta. Cospargete il dolce con lo zucchero a velo e servite.',6311);
INSERT INTO "ricette" VALUES (26133,'Torta Di Cioccolato E Pere','Dessert','Pere',4,' -','1000 G Pere,
150 G Farina,
50 G Cacao,
100 G Zucchero,
3 Uova,
125 G Burro,
1 Cucchiaio Lievito,
Alcuni Cucchiai Latte,
Zucchero A Velo','Battete i tuorli con lo zucchero finché saranno giallini, aggiungete la farina, il cacao, il lievito, il burro fuso e lavorate fino ad avere un impasto liscio. Sbucciate le pere, tagliatele a fettine e unitele all''impasto e mescolate con cura. Battete gli albumi a neve ferma e incorporateli delicatamente. Versate in una tortiera imburrata o foderata con carta da forno e fate cuocere in forno già caldo a 200 gradi per un''ora. Togliete la tortiera dal forno, sformate il dolce e spolverate la superficie con lo zucchero a velo.',3033);
INSERT INTO "ricette" VALUES (26134,'Torta Di Cipolle','Contorno','Cipolle',4,' -','500 G Patate,
200 G Lievito Di Birra,
1/2 Bicchiere Olio D''oliva Extra-vergine,
Sale Grosso,
Acqua','Lavare le Patate, lessarle in abbondante acqua lievemente salata e quindi colarle. Lasciare raffreddare, pelare le patate e schiacciarle nell''apposito utensile. Formare un morbido impasto amalgamando la purea di patate con la farina e l''olio. Sciogliere il lievito con un po'' d''acqua tiepida, unirlo all''impasto, amalgamare per alcuni minuti e lasciare riposare coperto per 30-35 minuti. Ungere tutto l''interno di una teglia, sistemarvi l''impasto schiacciandolo con le punta delle dita. Irrorare con olio e porvi un po'' di grani di sale. Fare cuocere in forno a fuoco medio-alto per circa 20 minuti.',1313);
INSERT INTO "ricette" VALUES (26135,'Torta Di Cipolle (2)','Contorno','Cipolle',6,'Preparazione: 30 Minuti. Cottura: 60 Minuti. Riposo Pasta: 60 Minuti.','200 G Farina,
120 G Burro,
75 G Formaggio Parmigiano Grattugiato,
1 Tuorlo D''uovo,
Peperoncino Di Caienna,
1/2 Cucchiaino Sale,
Per La Farcia:,
100 G Burro,
2 Cipolle Grandi,
3 Uova,
30 Cl Panna,
1 Cucchiaio Farina,
1 Pizzico Noce Moscata,
Sale,
Pepe','Preparate la pasta: setacciate in una ciotola 175 g di farina con mezzo cucchiaino di sale e un pizzico di peperoncino. Incorporatevi 100 g di burro a pezzettini e lavorate con le dita fino a ottenere la consistenza di briciole di pane. Incorporatevi formaggio, tuorlo d''uovo e due o tre cucchiai d''acqua. Mescolate e lavorate la pasta finché diventa soda e omogenea. Fatene una palla e mettetela in frigorifero per un''ora. Trascorso questo tempo accendete il forno a 200 gradi (termostato 6). Infarinate la spianatoia e stendetevi la pasta. Imburrate una tortiera del diametro di 24 cm e foderatela con la pasta. Bucherellate il fondo con la forchetta e copritelo con carta pergamenata e fagioli secchi. Fate cuocere in forno per dieci minuti; togliete carta e fagioli e lasciate cuocere ancora per otto minuti. Fate raffreddare la base di torta. Non spegnete il forno. Nel frattempo preparate la guarnizione. Fate fondere il burro in un tegame. Mondate e tritate le cipolle. Fatele rosolare nel burro per circa quindici minuti finché sono diventate trasparenti. Togliete il tegame dal fuoco e fate raffreddare. Incorporatevi la farina. Sbattete le uova e la panna con la forchetta e aggiungetele, sempre sbattendole, alle cipolle. Condite di sale, pepe e noce moscata. Abbassate il forno a 170 gradi (termostato 5). Versate la farcia sulla base di torta e fate cuocere in forno per circa quarantacinque minuti. Servite caldo.',4216);
INSERT INTO "ricette" VALUES (26136,'Torta Di Cipolle (3)','Antipasto','Cipolle',6,' -','400 G Pasta Frolla Surgelata,
800 G Cipolle,
2 Cucchiai Farina,
2 Uova,
100 G Burro,
2 Cucchiai Latte,
1/2 Bicchiere Panna,
100 G Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Stendete la pasta a disco e foderatevi una tortiera imburrata. Bucherellate il fondo con una forchetta. Pulite e affettate le cipolle, insaporitele nel burro e cuotele coperte mezz''ora senza farle colorire. Bagnatele con il latte, salate e pepate. Sbattete le uova con la panna e, sempre mescolando, versate il composto sulle cipolle. Spolverizzate di parmigiano grattugiato, quindi distribuite qua e là fiocchetti di burro. Cuocete in forno preriscaldato a 190 gradi per circa mezz''ora. Servite tiepida.',3420);
INSERT INTO "ricette" VALUES (26137,'Torta Di Cipolle All''antica','Antipasto','Cipolle',6,' -','200 G Pasta Brisée,
1000 G Cipolle,
60 G Burro,
150 G Uvetta Sultanina,
25 Cl Vino Bianco Secco,
Midollo Di 2 Ossa Di Bue,
1 Pizzico Zucchero,
Sale,
Pepe,
Legumi Secchi','Mettete l''uvetta a macerare nel vino. Imburrate e infarinate una teglia e foderatela con la pasta brisée tirata a disco avendo cura di farla risalire un po'' anche sul bordo. Bucherellate il fondo e i bordi con la forchetta. Sopra modellatevi un foglio di carta d''alluminio e controllate che aderisca bene alle pareti. Riempite con legumi secchi. Mettete in forno a 160 gradi per 15 minuti. Tagliate a fettine sottili le cipolle e lasciatele appassire in un tegame con il burro. Appena sono dorate aggiungete il midollo di bue, l''uvetta sultanina con il vino, un pizzico di zucchero. Mescolate, salate, pepate e fate evaporare il vino. Togliete dalla tortiera carta e legumi, versatevi il composto. Distribuitelo bene e poi rifinite con una grata di sottili strisce ricavate dai ritagli di pasta. Spennellatele con un poco di burro fuso. Cuocete in forno a 180 gradi mezz''ora. Servitela tiepida tagliata a spicchi. Vini di accompagnamento: Barbera D''Alba DOC, Rosso Piceno DOC, Donnici DOC.',2482);
INSERT INTO "ricette" VALUES (26138,'Torta Di Couscous','Dessert','Couscous',4,'Ricetta adatta a: vegetariani.','Couscous Integrale,
Couscous Bianco,
Succo Di Mela Naturale,
Albicocche Secche,
Mele Secche,
Mandorle,
Farina Di Cocco,
Sale Marino','Riempite una teglia per metà di uno strato uniforme di couscous precotto, metà bianco e metà integrale (o solo bianco). Trasferite il couscous in una terrina servendovi di un mestolo e prendete nota di quanti mestoli sono. Fate bollire per qualche minuto la frutta secca tagliata a piccoli cubetti nel succo di mela; quando questa si è ammorbidita versate il tutto sopra il couscous, calcolando due mestoli di succo per ogni mestolo di couscous. Coprite e lasciate riposare per una decina di minuti. Rimettete il tutto nella teglia, pressando bene con le mani. Guarnite con le mandorle tostate e tritate e il cocco grattugiato. Potete mangiarla così com''è oppure informarla per qualche minuto. Un consiglio: preparatela alla sera poiché mangiata il giorno dopo è molto più saporita.',1903);
INSERT INTO "ricette" VALUES (26139,'Torta Di Crespelle E Mele','Dessert','Mele',12,' -','Per Le Crespelle:,
250 G Latte,
120 G Farina,
20 G Burro,
2 Uova,
1 Pizzico Sale,
Per La Pasta Brisée:,
300 G Farina,
150 G Burro,
70 G Zucchero,
1 Pizzico Sale,
Per La Crema Pasticciera:,
500 G Latte,
150 G Zucchero,
50 G Farina,
4 Tuorli D''uovo,
3 Cucchiai Rum Scuro,
1 Bustina Vaniglina,
Per Completare:,
550 G Mele,
15 G Burro,
6 Biscotti Amaretti,
1 Cucchiaio Zucchero A Velo','Preparate le crespelle (anche il giorno prima): nella padellina sciogliete il burro senza farlo friggere. In una ciotola mescolate le uova con la farina e un pizzico di sale. Stemperate l''impasto con il latte freddo, versandolo a filo, quindi aggiungete il burro fuso. Riscaldate la padellina già unta e versatevi un mestolino di composto facendolo allargare sul fondo. Non appena si sarà rappreso, girate la crespella per completarne la cottura, quindi sformatela su un piatto e ripetete l''operazione fino ad esaurimento della pastella. Sulla spianatoia, impastate rapidamente la farina con il burro morbido, lo zucchero, un pizzichino di sale e 75 g di acqua fredda. Avvolgete la pasta in poca pellicola trasparente e ponetela in frigo per 30 minuti. Per la crema pasticciera, mescolate i tuorli con la farina e lo zucchero. Stemperate il composto con il latte caldo, portatelo su fuoco moderato e fatelo bollire per 5-6 minuti; infine aromatizzate la crema con la vaniglina e con il rum. Sbucciate le mele, tagliatele a fettine sottili e rosolatele nel burro. Preparate infine il pasticcio: tirate la pasta brisée a 4 millimetri di spessore e rivestite con essa uno stampo a cerniera mobile di 26 centimetri di diametro, lasciandola debordare. Sul fondo allargate un velo di crema, quindi proseguite a strati, con mele, crespelle e crema. Cospargete l''ultimo strato con gli amaretti sbriciolati e, infine, ribaltate verso l''interno la parte eccedente della pasta brisée, smerlandone il bordo. Passate il pasticcio in forno, già scaldato a 200 gradi, per 40 minuti circa. Servitelo tiepido, con una spolveratina di zucchero a velo.',5512);
INSERT INTO "ricette" VALUES (26140,'Torta Di Erbette E Carciofi','Antipasto','Carciofi',6,' -','500 G Farina,
500 G Erbette,
12 Carciofi,
100 G Formaggio Pecorino,
50 G Formaggio Parmigiano,
50 G Burro,
2 Fette Pancarré,
Olio D''oliva,
Latte,
Succo Di Limone,
1 Cucchiaio Maggiorana Fresca Tritata,
Cipolla,
1 Pizzico Sale,
Pepe','Disponete la farina a fontana e al centro mettete un po'' d''acqua e d''olio, un pizzico di sale. Impastate e poi tenete in frigorifero per mezz''ora. Lessate le erbette in acqua salata, scolatele al dente, strizzatele e tritatele. Eliminate tutte le foglie dure dei carciofi, tagliate le punte, lavateli e lasciateli in acqua e succo di limone per una decina di minuti. Sgocciolateli, tritateli e metteteli in una padella con poco olio e la cipolla affettata a velo. Lasciate appassire a fuoco basso. Quindi aggiungete le erbette, i formaggi grattugiati, la mollica del pancarré bagnata nel latte e strizzata. Amalgamate con cura il tutto, salate, pepate e cospargete con un cucchiaio di maggiorana tritata. Tirate la pasta in due dischi, uno più grande dell''altro. Adagiate quello più grande in una teglia imburrata e fatelo risalire anche sui bordi. Versatevi il composto di verdure, coprite il ripieno con il secondo disco sigillando bene i bordi. Con i rebbi di una forchetta bucherellate disegnando un motivo a spirale. Cuocete in forno a 200 gradi per 40 minuti o più. Questa torta può essere servita calda, tiepida e fredda. Vini di accompagnamento: Alto Adige Traminer Aromatico DOC, Collio Malvasia Istriana DOC, Frascati Canellino DOC.',4197);
INSERT INTO "ricette" VALUES (26141,'Torta Di Fagioli','Dessert','Farina Di Fagioli',4,' -','100 G Burro,
250 G Zucchero,
300 G Farina Bianca 00,
150 G Farina Di Fagioli,
2 Uova,
1 Bustina Lievito Per Dolci,
1 Pizzico Sale,
Latte','In una terrina montare burro e zucchero, aggiungere le uova ed incorporare lentamente le farine, il lievito ed il sale, quindi delicatamente le chiare montate a neve. Se l''impasto risulta troppo asciutto aggiungere un poco di latte. Imburrare e infarinare una teglia, versare l''impasto e infornare a 160 gradi per 45 minuti.',3497);
INSERT INTO "ricette" VALUES (26142,'Torta Di Fagiolini','Antipasto','Fagiolini',6,' -','1 Confezione Pasta Sfoglia Surgelata,
1000 G Fagiolini,
1 Spicchio Aglio,
2 Bicchieri Panna,
1 Bicchiere Latte,
4 Uova,
Farina,
Formaggio Parmigiano Grattugiato,
Burro,
Sale,
Pepe','Lasciate scongelare la pasta sfoglia. Pulite e lessate al dente i fagiolini. Scolateli, tagliateli a pezzetti e fateli rosolare in un tegame con il burro e lo spicchio d''aglio. Stendete la pasta sfoglia a uno spessore di pochi millimetri, foderatevi uno tortiera imburrata. Sbattete le uova con la panna, il latte, sale e pepe. Distribuite i fagiolini sulla pasta, ricopriteli con il composto di uova e latte, spolverizzate di parmigiano grattugiato. Cuocete in forno preriscaldato a 170 gradi per circa 45 minuti.',4070);
INSERT INTO "ricette" VALUES (26143,'Torta Di Fave E Piselli','Antipasto','Fave',6,' -','Per La Pasta:,
200 G Farina,
100 G Burro,
Sale,
Per Il Ripieno:,
300 G Fave Secche,
300 G Piselli Secchi,
300 G Patate,
2 Uova,
1 Cipolla,
60 G Burro,
Sale,
Pepe','Tenete a bagno i piselli e le fave per una notte. Sgocciolateli e fateli insaporire in un tegame con il burro e la cipolla tritata per circa mezz''ora. Intanto preparate la pasta mescolando la farina con il burro, un po'' d''acqua e il sale. Imburrate e infarinate una tortiera, adagiatevi la pasta stesa a disco con il matterello. Passate al tritaverdure le fave e i piselli, versate il passato in una terrina, incorporatevi le uova, regolate sale e pepe e versate il composto nella tortiera. Cuocete in forno preriscaldato a 170 gradi per circa mezz''ora.',4062);
INSERT INTO "ricette" VALUES (26144,'Torta Di Fichi','Dessert','Fichi Freschi',4,' -','300 G Farina,
600 G Fichi Freschi,
1 Uovo,
3 Cucchiai Zucchero,
1 Bicchiere Vino Marsala,
1 Bustina Lievito,
1 Limone (buccia Grattugiata),
Burro','Pulite con un canovaccio i fichi (che non devono essere troppo maturi), tritateli finemente con la loro buccia e metteteli in una terrina. Aggiungete la farina, lo zucchero, l''uovo e la scorza grattugiata del limone; amalgamate con cura unendo anche il Marsala e, per ultimo, il lievito. Mescolate a lungo fino ad ottenere una pasta morbida e omogenea. imburrate una teglia, versate il composto e mettete in forno caldo per 45 minuti.',2494);
INSERT INTO "ricette" VALUES (26145,'Torta Di Finocchi','Antipasto','Finocchi',6,' -','6 Finocchi,
100 G Burro,
200 G Formaggio Taleggio,
1 Bicchiere Latte,
3 Uova,
1 Tuorlo D''uovo,
1 Confezione Pasta Sfoglia Surgelata,
Olio D''oliva,
Sale,
Pepe','Pulite i finocchi, eliminate le parti più dure, lavateli, tagliateli a pezzi e fateli rosolare in un tegame con una noce di burro. Stendete la pasta e con i due terzi di questa foderate una tortiera imburrata. Distribuitevi sopra i finocchi e taleggio tagliato a fettine. In una ciotola sbattete le uova con latte, sale e pepe, versate il composto sui finocchi. Coprite con la restante pasta tirata a disco, spennellate con il tuorlo la superficie. Cuocete in forno preriscaldato 180 gradi per quaranta minuti circa.',4012);
INSERT INTO "ricette" VALUES (26146,'Torta Di Fiocchi','Dessert','Fiocchi Di Mais',4,'Ricetta adatta a: vegetariani.','300 G Fiocchi Di Mais,
100 G Fiocchi D''avena,
150 G Uvetta Sultanina Biologica,
3 Cucchiai Malto Di Mais,
150 G Noci Tostate,
Succo Di Mela Senza Zucchero,
1 Pizzico Sale Marino,
Agar Agar In Fiocchi,
Cocco Grattugiato','Mettete l''uvetta a bagno nel succo di mela e bollitela per 20 minuti; aggiungete un pizzico di sale, il malto e fate bollire per altri 2 o 3 minuti. Tenete i fiocchi a bagno in questo composto per circa 30 minuti, poi disponeteli in una teglia formando un primo strato di mele a rondelle (tagliate a fette trasversalmente e mondate). Preparate una glassa con malto e acqua in cui avete fatto bollire per qualche minuto due cucchiai di agar agar in fiocchi e con questa ricoprite appena lo strato superiore. Infornate per 30-40 minuti a 180 gradi. Guarnite con cocco grattugiato e fate raffreddare completamente prima di tagliare e servire.',3328);
INSERT INTO "ricette" VALUES (26147,'Torta Di Foglie Miste','Contorno','Foglie Miste Di Insalata',4,' -','Per La Pasta:,
250 G Farina,
125 G Burro,
1 Uovo,
Per Il Ripieno:,
3 Uova,
1 Tuorlo D''uovo,
100 G Panna,
300 G Foglie Miste Di Insalata,
100 G Formaggio Emmenthal,
Sale,
Peperoncino,
20 G Burro','Preparate la pasta e stendetela in una tortiera con il bordo scanalato. Punzecchiate la pasta con una forchetta e cuocete in forno preriscaldato a 200 gradi e a metà altezza per circa 15 minuti, poi levatela dal forno. Nel frattempo fate insaporire le foglie lavate e tagliate a listarelle con il burro e il peperoncino (se poi preferirete levarlo, lasciatelo intero). In una terrina sbattete le uova più il tuorlo, aggiungete la panna e il formaggio, tagliato a fettine molto sottili. Quando le foglie saranno cotte unitele al composto a base di uova (eliminate il peperoncino, se volete), aggiustate di sale. Riempite la pasta con il ripieno, rimettete nel forno e cuocete per circa 30 minuti. Secondo me, è buona servita a temperatura ambiente.',3185);
INSERT INTO "ricette" VALUES (26148,'Torta Di Formaggio','Antipasto','Formaggio Emmenthal',6,' -','1 Confezione Pasta Sfoglia Surgelata,
250 G Ricotta,
150 G Mozzarella,
150 G Formaggio Emmenthal,
2 Uova,
1 Tuorlo D''uovo,
1 Cucchiaio Formaggio Grattugiato,
Farina,
Burro,
Sale,
Pepe','Fate scongelare la pasta secondo le istruzioni della confezione. Dividetela a metà. Con un matterello leggermente infarinato stendetene una parte e adagiatela in una tortiera foderata con carta da forno leggermente imburrata. In una ciotola lavorate la ricotta con un mestolo, aggiungete la mozzarella e l''Emmenthal tagliati a dadini. Incorporatevi le due uova e un cucchiaio di formaggio grattugiato. Regolate sale e pepe. Mescolate il tutto e distribuite il composto sulla sfoglia. Ricopritela con l''altra metà della pasta stesa a sfoglia. Premete lungo i bordi per sigillare bene la torta. Spennellate la superficie con il tuorlo. Cuocete in forno preriscaldato a 180 gradi per circa 35 minuti. Ritirate la torta, lasciatela riposare 10 minuti. Vini di accompagnamento: Colli Piacentini Gutturnio DOC, Rosso Piceno DOC, Castel Del Monte Rosso DOC.',3986);
INSERT INTO "ricette" VALUES (26149,'Torta Di Formaggio (2)','Contorno','Formaggio Gorgonzola Dolce',4,' -','100 G Formaggio Gorgonzola Dolce,
250 G Formaggio Fresco Tipo Caprino,
50 G Formaggio Fresco Alle Erbe,
200 G Panna Da Montare,
1 Pizzico Sale,
1 Pizzico Pepe,
1 Manciata Insalata Riccia,
Per Servire:,
Alcune Fette Pancarré','Mettete il gorgonzola tagliato a fettine in una terrina, bagnatelo con una o due cucchiaiate di panna liquida e schiacciatelo. Mettete