tto, spezzettatelo e fate appassire tutto a fuoco basso nell''olio d''oliva extra-vergine, al termine scolate e fate asciugare su carta da cucina. Sbattete le uova in una ciotola abbastanza capiente, unite la cipolla e il finocchietto, le acciughe, il latte, sale e pepe e mescolate per 2 minuti. Mettete l''olio d''oliva in una padella, portate a calore elevato e versatevi il contenuto della ciotola facendo rapprendere la frittata da un lato a fiamma vivace. Giratela dall''altra parte aiutandovi con un piatto e fate prendere colore anche dall''altro lato. Servite la frittata in tavola dopo averla fatta riposare per qualche minuto.',1523);
INSERT INTO "ricette" VALUES (10176,'Frittata Di Acciughe (9)','Contorno','Acciughe',4,' -','6 Uova,
300 G Acciughe,
Prezzemolo,
Sale,
Olio D''oliva,
Pepe,
Burro,
2 Cucchiai Latte','Pulite il pesce eliminando la lisca centrale, poi friggetelo in abbondante olio bollente. Sgocciolate le acciughe fritte su carta assorbente da cucina e riducetele in pezzetti. Sbattete le uova con 2 cucchiai di latte, pepe, sale e prezzemolo tritato, poi unite le alici e mescolate bene. Fate sciogliere in una padella un po'' di burro, poi unite un cucchiaio di olio. Quando il tutto sarà ben caldo, unite le uova sbattute e procedete come una normale frittata. Servite la frittata ben calda.',2346);
INSERT INTO "ricette" VALUES (10177,'Frittata Di Acciughe Al Forno','Contorno','Acciughe',6,' -','Uova,
Formaggio Pecorino Grattugiato,
Olio D''oliva Extra-vergine,
Prezzemolo,
Pangrattato,
Sale,
Basilico','Togliete le teste e diliscate delicatamente le acciughe. Lavatele sotto acqua corrente e mettetele ad asciugare su un canovaccio. Sistemate le acciughe su una placca da forno leggermente unta con l''olio d''oliva (oppure su un foglio di carta da forno), disponendole a strati e condendo ognuno con 1 pizzico di sale, il prezzemolo tritato finemente e il pecorino grattugiato. Condite l''ultimo strato come gli altri e versatevi sopra le uova sbattute. Spolverizzate con il pangrattato e terminate con 1 filo di olio d''oliva. Cuocete in forno a 200 gradi per circa 30 minuti. Servite le acciughe ben calde nei singoli piatti decorando, a piacere, con 1 foglia di basilico e spolverizzando con prezzemolo tritato.',1775);
INSERT INTO "ricette" VALUES (10178,'Frittata Di Albumi E Code Di Cipolle','Contorno','Uova',4,' -','5 Uova,
Code Di Un Mazzo Di Cipolle Novelle Di Tropea,
Olio D''oliva Extra-vergine,
2 Pizzichi Sale,
Peperoncino','Tagliare le code delle cipolle, eliminarne la parte terminale e tagliuzzarle, quindi brasarle nell''olio aiutandosi eventualmente con poca acqua, un pizzico di sale, facendole ammorbidire. Separare i tuorli dagli albumi e montare un po'' questi ultimi con un pizzico di sale finchè risultino spumosi. Versarli allora sulle cipolle e farli rapprendere, quindi servirli con peperoncino sminuzzato.',1195);
INSERT INTO "ricette" VALUES (10179,'Frittata Di Alici','Contorno','Acciughe',4,'Luogo: Abruzzo.','500 G Acciughe Piccole,
5 Uova,
60 G Formaggio Pecorino Grattugiato,
2 Cucchiai Prezzemolo Tritato,
Peperoncino Piccante Macinato,
Sale,
Per Friggere:,
Olio D''oliva','Lavate accuratamente le acciughe, poi lasciatele sgocciolare entro un colino. Nel frattempo, in una ciotola capiente, sbattete le uova con il formaggio, il prezzemolo, il peperoncino e il sale. Unite le acciughe ed amalgamatele bene al composto di uova. Versate il composto in padella, dove avrete già scaldato bene l''olio. Cucinate la frittata, girandola almeno una volta; asciugatela sopra fogli di carta assorbente, servitela quindi calda o fredda, tagliata a spicchi.',1899);
INSERT INTO "ricette" VALUES (10180,'Frittata Di Alici (2)','Contorno','Acciughe',4,'Luogo: Abruzzo.','500 G Acciughe,
4 Uova Fresche,
1 Manciata Prezzemolo Tritato,
1 Cucchiaio Formaggio Pecorino Grattugiato,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale Fino,
Pepe Nero Appena Macinato','Pulire le acciughe capitozzandole, eviscerandole e spinandole. Fare un rapido risciacquo senza indugiare nel tenerle in acqua per evitare che le acciughe perdano la naturale salinità. Porle ben ordinatamente a scolare. Rompere le uova in una terrina, il numero preciso dipende dalla loro grandezza, agitarle moderatamente condendole con il prezzemolo, il formaggio, sale e pepe. Il formaggio deve essere poco per evitare che sovrasti il gusto pur sempre delicato del pesce. Porre a scaldare su fiamma moderata una padella con dimensioni che facciano in modo che lo spessore della frittata non superi le due dita o anche meno, possibilmente in ferro, unta con l''olio, appena accenna ad essere ben calda, versarvi le uova battute, facendo seguire le alici in maniera molto ben ordinata, con una forchetta staccare dalla parete l''uovo che si va man mano rapprendendo e aiutare l''uovo ancora liquido a sovrastare le alici, solo quando l''uovo sarà quasi del tutto rappreso rigirare la frittata servendosi di un coperchio o di un piatto, che abbiano il diametro ben superiore a quello della padella per evitare pericolosi sbrodolino pericolosi liquidi ustionanti, ponendoli a coperchio e rigirando velocemente, per poi lasciarla nuovamente scivolare in padella, facendo, ovviamente, andar sotto il lato meno cotto. La frittata sarà cotta quando sarà ben soda e staccata dalla padella, anche un moderatissimo accenno di bruciacchiatura non guasta, questo si ottiene senza fretta con fiamma moderata, poco olio molto ben distribuito e una sola rigirata a frittata quasi cotta.',1495);
INSERT INTO "ricette" VALUES (10181,'Frittata Di Alici (3)','Contorno','Acciughe',4,'Luogo: Abruzzo.','500 G Acciughe Piccole,
3 Uova,
50 G Formaggio Grattugiato,
1 Bicchiere Olio D''oliva,
Prezzemolo,
Pepe','Dopo aver rotto le uova, aggiungere tutti gli ingredienti, comprese le acciughe, formando una frittata. Cuocere e servire.',2252);
INSERT INTO "ricette" VALUES (10182,'Frittata Di Alici (4)','Contorno','Acciughe',4,'Luogo: Abruzzo.','500 G Acciughe,
6 Uova,
1 Spicchio Aglio,
1 Cucchiaio Prezzemolo Tritato,
1 Peperoncino Fresco,
Origano,
1 Pizzico Sale,
1 Pizzico Pepe','Pulite le alici: eliminate la testa con le interiora, apritele a metà e privatele della lisca, cercando di non dividere le due metà. Lavate bene e lasciate scolare. Lavate il peperoncino, tagliatelo a metà, privatelo dei semini e tritatelo. Sbattete le uova con il peperoncino tritato, 1 pizzico di sale  e pepe e l''origano. In una padella fate soffriggere nell''olio 1 spicchio di aglio, quindi toglietelo e mettete a rosolare, da entrambi i lati, le acciughe ben aperte. Cospargete con il prezzemolo tritato e versatevi sopra le uova. Mettete il coperchio e fate cuocere per 15 minuti, girando la frittata. Servite subito.',1072);
INSERT INTO "ricette" VALUES (10183,'Frittata Di Alici (5)','Contorno','Acciughe',4,'Luogo: Abruzzo.','6 Acciughe,
4 Uova,
2 Cucchiai Formaggio Pecorino Romano,
Prezzemolo Tritato,
Peperoncino,
1 Spicchio Aglio,
Sale','Se avete a disposizione delle acciughe fresche procedete in questo modo, prendete una padella e mettete a rosolare a fuoco basso lo spicchio d''aglio, nel frattempo lavate e pulite bene le acciughe; aggiungete acciughe e peperoncino e togliete l''aglio, fate scottare le acciughe fresche per un paio di minuti da entrambi i lati. Sbattete le uova con prezzemolo, 1 pizzico di sale e con il pecorino romano, sbattete bene dopodiché aggiungete le uova alle accighe; coprite con un coperchio ed a fiamma bassissima lasciate cuocere per almeno 4-5 minuti per parte, la frittata di acciughe è pronta. Se avete invece delle acciughe sotto sale o filetti d''acciughe già in vasetto potete evitare il primo passaggio ovvero quello della cottura preventiva, potete dunque aggiungere i filetti d''acciughe direttamente nelle uova e cuocere tutto insieme eliminando anche l''aglio ed il soffritto, come preferite, ma sappiate che con le acciughe fresche questa frittata ha una marcia in più, in entrambi i casi vi consigliamo di provarla perché è davvero buona.',595);
INSERT INTO "ricette" VALUES (10184,'Frittata Di Alici (6)','Contorno','Acciughe',4,' -','8 Uova,
250 G Acciughe,
Formaggio Pecorino Grattugiato,
Prezzemolo,
Aglio,
Olio D''oliva,
Pepe Nero,
Sale','Privare i pesci delle interiora e delle teste; spinarli, lavarli e passarli per pochi minuti in una padella, nella quale bisogna fare imbiondire l''aglio nell''olio. A parte, sbattere le uova, salarle, peparle e insaporirle con il prezzomolo lavato e tritato finemente. Amalgamare uova e pesci, friggere in modo che la frittata resti morbida.',2109);
INSERT INTO "ricette" VALUES (10185,'Frittata Di Alici (7)','Contorno','Acciughe',4,' -','6 Uova,
300 G Polpa Di Pomodoro,
6 Filetti D''acciughe,
Prezzemolo,
Sale,
1 Pizzico Pepe,
3 Cucchiai Olio D''oliva,
Formaggio Parmigiano Grattugiato (facoltativo)','Mettere in una padella 1 cucchiaio d''olio d''oliva ed 1 spicchio d''aglio; far imbiondire l''aglio ed aggiungere le acciughe tritate ed il prezzemolo tritato, quindi aggiungere e mescolarvi la polpa di pomodoro; salare e mettere anche 1 pizzico di pepe. Lasciate cuocere per circa dieci minuto sul fuoco moderato. Versate il composto in un recipiente e aggiungete le 6 uova. Nella padella mettere 1 cucchiaio d''olio e versarvi il composto preparato; mescolare bene. Fare dorare da un lato, poi versare la frittata in un piatto e fare nuovamente fumare in padella un altro cucchiaio di olio. Per finire riversare in padella la frittata, facendo ben attenzione di cuocere, stavolta, la parte non dorata. Al termine della cottura far scivolare la frittata in un piatto rotondo e servire ben caldo, cospargendo magari, se preferite, con abbondante parmigiano grattugiato.',2135);
INSERT INTO "ricette" VALUES (10186,'Frittata Di Alici (8)','Contorno','Acciughe',4,'Luogo: Abruzzo.','300 G Acciughe,
5 Uova,
2 Cucchiai Latte,
2 Cucchiai Olio D''oliva Extra-vergine,
1/2 Cipolla,
1 Rametto Finocchietto Selvatico,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe','Pulite le acciughe eliminando le teste, le code e le viscere, apritele e scartate la lisca centrale, quindi ricavate i filetti, sciacquate e asciugate con carta da cucina. Affettate molto finemente la cipolla, lavate le parti morbide del finocchietto, spezzettatelo e fate appassire tutto a fuoco basso nell''olio d''oliva extra-vergine, al termine scolate e fate asciugare su carta da cucina. Sbattete le uova in una ciotola abbastanza capiente, unite la cipolla e il finocchietto, le acciughe, il latte, sale e pepe e mescolate per 2 minuti. Mettete l''olio d''oliva in una padella, portate a calore elevato e versatevi il contenuto della ciotola facendo rapprendere la frittata da un lato a fiamma vivace. Giratela dall''altra parte aiutandovi con un piatto e fate prendere colore anche dall''altro lato. Servite la frittata in tavola dopo averla fatta riposare per qualche minuto.',1523);
INSERT INTO "ricette" VALUES (10187,'Frittata Di Alici (9)','Contorno','Acciughe',4,' -','6 Uova,
300 G Acciughe,
Prezzemolo,
Sale,
Olio D''oliva,
Pepe,
Burro,
2 Cucchiai Latte','Pulite il pesce eliminando la lisca centrale, poi friggetelo in abbondante olio bollente. Sgocciolate le acciughe fritte su carta assorbente da cucina e riducetele in pezzetti. Sbattete le uova con 2 cucchiai di latte, pepe, sale e prezzemolo tritato, poi unite le alici e mescolate bene. Fate sciogliere in una padella un po'' di burro, poi unite un cucchiaio di olio. Quando il tutto sarà ben caldo, unite le uova sbattute e procedete come una normale frittata. Servite la frittata ben calda.',2346);
INSERT INTO "ricette" VALUES (10188,'Frittata Di Alici Al Forno','Contorno','Acciughe',6,' -','Uova,
Formaggio Pecorino Grattugiato,
Olio D''oliva Extra-vergine,
Prezzemolo,
Pangrattato,
Sale,
Basilico','Togliete le teste e diliscate delicatamente le acciughe. Lavatele sotto acqua corrente e mettetele ad asciugare su un canovaccio. Sistemate le acciughe su una placca da forno leggermente unta con l''olio d''oliva (oppure su un foglio di carta da forno), disponendole a strati e condendo ognuno con 1 pizzico di sale, il prezzemolo tritato finemente e il pecorino grattugiato. Condite l''ultimo strato come gli altri e versatevi sopra le uova sbattute. Spolverizzate con il pangrattato e terminate con 1 filo di olio d''oliva. Cuocete in forno a 200 gradi per circa 30 minuti. Servite le acciughe ben calde nei singoli piatti decorando, a piacere, con 1 foglia di basilico e spolverizzando con prezzemolo tritato.',1775);
INSERT INTO "ricette" VALUES (10189,'Frittata Di Asparagi','Contorno','Asparagi',4,' -','Asparagi,
Aglio,
Uova,
Sale,
Pepe,
Olio D''oliva','Togliere la parte dura agli asparagi (meglio se selvatici), sciacquarli in acqua corrente e gettarli, ancora bagnati in un padellino in cui insieme all''olio di oliva sta appassendo un trito di aglio fresco. Farli cuocere lentamente senza portarli a rosolatura (se ne perderebbe il profumo che è massimo quando sono teneri) e versare nel padellino le uova battute e salate in quantità sufficiente: quindi aggiungere una presina di pepe e mescolare. Fare la solita frittata, cuocendone ambo le parti.',1056);
INSERT INTO "ricette" VALUES (10190,'Frittata Di Asparagi Di Campo','Contorno','Asparagi Di Campo',4,' -','350 G Punte Di Asparagi Di Campo,
5 Uova,
60 G Formaggio Pecorino Grattugiato,
Olio D''oliva Extra-vergine,
1 Pizzico Sale,
1 Pizzico Pepe','Mondare gli asparagi, lavarli e lessarli brevemente al dente. Scolarli e unirle alle uova sbattute con un pizzico di sale e pepe e al formaggio. Scaldare l''olio in una padella ampia e quando è ben caldo versarvi il composto, cuocendo la frittata su entrambi i lati.',1473);
INSERT INTO "ricette" VALUES (10191,'Frittata Di Asparagi Selvatici','Contorno','Asparagi Selvatici',4,' -','Asparagi Selvatici,
Porro,
Rigatino (pancetta),
Uova,
Olio D''oliva,
Sale','Pulire gli asparagi togliendo la parte dura. Pulire il porro e tagliarlo a rondelline. Cuocere gli asparagi ed il porro lentamente in una padellina antiaderente con un poco di olio e di acqua. Tagliare il rigatino a fettine ed aggiungerlo agli asparagi. Sbattere le uova e salare, aggiungere agli asparagi e coprire, lasciando cuocere lentamente. Meglio se si può mettere in forno caldo a 150 gradi per alcuni minuti. Tagliare a rombi e servire.',1642);
INSERT INTO "ricette" VALUES (10192,'Frittata Di Bianchetti','Contorno','Bianchetti',4,' -','150 G Bianchetti,
6 Uova,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
1 Noce Burro,
Sale,
Pepe','Lavate i bianchetti. In una terrina sbattete le uova con un po'' di sale e pepe, aggiungetevi i bianchetti e il parmigiano grattugiato. In una padella antiaderente lasciate sciogliere una noce di burro e quando è leggermente dorato versatevi il composto di uovo. Cuocete la frittata da entrambe le parti e, al momento di girarla, aiutatevi con un piatto. Potete servirla calda o fredda.',1294);
INSERT INTO "ricette" VALUES (10193,'Frittata Di Carne','Contorno','Carne',4,' -','150 G Carne,
4 Uova,
1 Ciuffo Prezzemolo,
Alcuni Cucchiai Latte,
Burro,
1 Cucchiaio Olio D''oliva,
1 Pizzico Sale','Tritate finemente la carne e insaporitela in un tegamino con una noce di burro e un pizzico di sale. Si possono usare anche avanzi di carne già cotta, in questo caso non occorre insaporire. Sbattete le uova, salate, pepate poi unite la carne, il prezzemolo tritato e, se il composto fosse asciutto, ammorbiditelo con alcuni cucchiai di latte. In una padella scaldate una noce di burro e un cucchiaio d''olio, versatevi il composto e fate dorare da entrambe le parti. Servitela calda o fredda.',1672);
INSERT INTO "ricette" VALUES (10194,'Frittata Di Carote','Contorno','Carote',4,' -','6 Uova,
4 Carote,
100 G Formaggio Groviera,
100 G Pane Sbriciolato Fresco,
Burro,
Sale,
Pepe','Raschiate le carote e grattugiatele. In una terrina sbattete le uova con sale e pepe; unite le carote, il formaggio a fettine, il pane. In una padella scaldate una noce di burro, versate il composto d''uova e cuocete la frittata da entrambe le parti. Servite su un piatto da portata, guarnite con ciuffi di prezzemolo e servite.',2091);
INSERT INTO "ricette" VALUES (10195,'Frittata Di Cime Di Rapa','Contorno','Cime Di Rapa',6,'Luogo: Campania.','500 G Friarielli (cime Di Rapa),
6 Uova,
2 Cucchiai Formaggio Parmigiano,
1 Cucchiaio Formaggio Pecorino Romano,
Peperoncino A Piacere,
1 Spicchio Aglio,
Sale','Lessare i friarielli. Soffriggere nell''olio, l''aglio. Aggiungere il peperoncino. Togliere l''aglio. Versare i friarielli a fuoco basso. Fare insaporire per 15 minuti. Battere le uova con il sale e i formaggi. Aggiungere i friarielli. Mettere su una padella un po'' di olio. Versare il miscuglio e spianare. Cuocere la frittata a fuoco molto basso per evitare che si bruci al centro. Cotta la prima faccia, rivoltare con l''aiuto di un coperchio, e cuocere la seconda faccia. Servire calda.',895);
INSERT INTO "ricette" VALUES (10196,'Frittata Di Cipolle','Contorno','Cipolle',4,' -','6 Uova,
3 Cipolle Bianche,
40 G Burro,
Sale,
Pepe','Spellate le cipolle e tagliatele a fettine sottili. Fate sciogliere il burro in un tegame. Quando comincia a soffriggere unitevi le cipolle e cuocetele lentamente a fuoco moderato mescolando ogni tanto. Nel frattempo sgusciate le uova in un piatto, sbattetele con la forchetta, salate e pepate. Quando le cipolle cominciano a prendere un bel colore dorato, versatevi sopra le uova e lasciatele rapprendere morbidamente. Aiutandovi con un piatto voltate la frittata fatela dorare anche dall''altra parte. Rovesciatela su un piatto da portata, tagliatela a quadratini e servite.',933);
INSERT INTO "ricette" VALUES (10197,'Frittata Di Cipolle (2)','Contorno','Cipolle',6,'Luogo: Piemonte. Luogo: Alba. Preparazione: 30 minuti. Cottura: 10 minuti.','4 Cipolle,
6 Uova,
1 Manciata Formaggio Parmigiano Grattugiato,
1 Pizzico Sale,
Per Friggere:,
Olio D''oliva Extra-vergine,
Per Guarnire:,
Alcune Foglie Insalata','Tagliate a fette le quattro cipolle e fatele dorare, a fuoco lento, in una padella con poco olio. In una terrina sbattete le uova intere, poi unite le cipolle, il parmigiano grattugiato e un pizzico di sale. Versate il composto ottenuto nella padella usata precedentemente e fatelo cuocere in olio d''oliva. Dopo qualche minuto girate la frittata aiutandovi con il coperchio di una pentola: continuate la frittura su questo lato ricordandovi che il fuoco non deve mai essere violento. Infine, tolta dalla padella, passate la frittata su carta assorbente. Servitela calda, a fette, guarnita con qualche foglia d''insalata. Vino consigliato: Langhe Chardonnay.',1667);
INSERT INTO "ricette" VALUES (10198,'Frittata Di Cipolle E Zucchine','Contorno','Zucchine',4,' -','600 G Zucchine Piccole Fresche,
400 G Cipolle Bianche,
4 Uova,
4 Cucchiai Olio D''oliva Extra-vergine,
Basilico,
Prezzemolo,
Sale,
Pepe','Spellate le cipolle, dividetele in due per il lungo e affettatele a velo. Spuntate le zucchine, lavatele e tagliatele a fettine regolari. Scaldate tre cucchiai d''olio in una larga padella e, a fuoco moderato, fatevi appassire le cipolle mescolandole spesso. Quando saranno diventate trasparenti e prima che prendano colore, unitevi le zucchine, rialzate la fiamma e lasciate cuocere per circa mezz''ora, mescolando spesso. Insaporitele con sale e pepe e toglietele dal fuoco non appena saranno cotte ma ancora consistenti. Sbattete le uova in una terrina, salatele e mescolatevi le zucchine tiepide e il prezzemolo e il basilico tritati. Scaldate un cucchiaio d''olio in una padella antiaderente, versatevi il composto di uova e pareggiate. Fate cuocere la frittata in maniera uniforme quindi voltatela aiutandovi con un coperchio e terminate la cottura.',1310);
INSERT INTO "ricette" VALUES (10199,'Frittata Di Cipolle E Zucchine (2)','Contorno','Cipolle',6,' -','6 Uova,
300 G Cipolle,
300 G Zucchine,
2 Cucchiai Olio D''oliva,
1 Bicchiere Latte,
Noce Moscata,
6 Pizzichi Sale,
6 Cucchiai Formaggio Parmigiano','Pulire le cipolle e le zucchine, lavarle ed asciugarle. Mettere in 1 padella 50 g di burro e unire le cipolle tagliate a fette sottili e le zucchine, coprire e far cuocere per 15 minuti a fuoco moderato. Salare le verdure, e mentre cuociono, mettere in 1 ciotola uova, sale, parmigiano, noce moscata e latte e sbattere bene il tutto. Quando le verdure sono cotte unire il composto e far cuocere nella padella da ambo i lati per 5 minuti.',1589);
INSERT INTO "ricette" VALUES (10200,'Frittata Di Cipolline Al Formaggio','Contorno','Cipolline',4,' -','6 Uova,
300 G Cipolline,
50 G Formaggio Parmigiano Grattugiato,
1 Cucchiaio Zucchero,
Brodo,
30 G Burro,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulite le cipolline e fate sciogliere in una padella il burro. Quando è caldo unite le cipolline, salate e pepate. Cospargete le cipolline con lo zucchero e lasciatele dorare a fiamma viva. Coprite e cuocete a fuoco basso rigirando e bagnando di tanto in tanto con brodo caldo. Sbattete in una terrina le uova con un pizzico di sale e pepe. Sempre sbattendo incorporate il formaggio. Quando le cipolline saranno cotte e glassate, unitele al composto di uova e formaggio mescolando. Ponete in una padella non troppo larga (la frittata dovrà risultare spessa e le cipolline dovranno essere ricoperte dal composto di uova) l''olio e cuocete la frittata rigirando almeno una volta. Per una presentazione elegante e raffinata, potete poi tagliare la frittata con uno stampino a forma di cuore in 4 cuoricini che adagerete su un letto di insalata fresca guarnita da ravanelli.',1695);
INSERT INTO "ricette" VALUES (10201,'Frittata Di Cozze','Pesce','Cozze',4,' -','1000 G Cozze,
6 Uova,
Prezzemolo,
1 Spicchio Aglio,
Basilico,
Maggiorana,
1 Panino (mollica),
1 Cucchiaio Formaggio Pecorino,
1 Cucchiaio Succo Di Limone,
Poco Latte,
Olio D''oliva,
Poco Sale,
Poco Pepe','Far aprire le cozze sul fuoco, togliere i molluschi dalle valve, porli in una scodella e unire succo di limone e poco pepe. Sbattere le uova, unire prezzemolo, aglio e basilico tritati, maggiorana, pecorino, mollica di pane bagnata nel latte e strizzata e poco sale. Unire i molluschi. Cuocere la frittata e servirla con insalata.',2190);
INSERT INTO "ricette" VALUES (10202,'Frittata Di Crostini','Contorno','Pancarré',4,' -','6 Uova,
3 Fette Pancarré,
1 Cucchiaio Prezzemolo Tritato,
Sale,
Pepe,
Poco Olio D''oliva','Tagliate le fette di pane a dadini. Fateli tostare in una padella in poco olio. Sbattete le uova con sale, pepe e un cucchiaio di prezzemolo tritato, versatele sui crostini, mescolate e cuocete la frittata da ambo le parti. Tagliatela a spicchi e servitela.',1864);
INSERT INTO "ricette" VALUES (10203,'Frittata Di Erbe','Contorno','Uova',4,' -','8 Uova,
30 G Formaggio Pecorino Grattugiato,
1 Filetto D''acciughe,
1 Cucchiaio Erbe Aromatiche (timo, Maggiorana, Prezzemolo, Origano),
2 Cucchiai Olio D''oliva,
Sale','Sbattere le uova con il pecorino e unire le erbe tritate. Salare. Sciogliere l''acciuga in 2 cucchiai di olio in una padella e versarvi le uova battute. Cuocere per 5 minuti e rigirare la frittata a metà cottura.',1227);
INSERT INTO "ricette" VALUES (10204,'Frittata Di Fagioli','Contorno','Fagioli Borlotti',4,' -','400 G Fagioli Borlotti In Scatola,
100 G Lardo,
100 G Formaggio Emmenthal,
3 Cucchiai Olio D''oliva,
1 Presa Sale,
1 Presa Pepe','Scolare i fagioli e frullarli. Tritare il lardo e farlo rosolare in un tegame. Unire la purea di fagioli, una presa di pepe e sale e cuocere mescolando finché il lardo sarà stato completamente assorbito. Aggiungere emmenthal tagliato a dadini. Scaldare 3 cucchiai di olio in una padella e versarvi il composto di fagioli e formaggio. Friggere finché il formaggio sarà sciolto poi rigirare la frittata e farla dorare. Servire subito molto calda.',2531);
INSERT INTO "ricette" VALUES (10205,'Frittata Di Fegato','Carne','Vitello',4,' -','4 Uova,
150 G Fegato Di Vitello A Fettine,
Alloro,
50 G Burro,
1/2 Bicchiere Vino Marsala,
Sale,
Pepe','Far sciogliere in 1 padella 30 g di burro con 2 foglie d''alloro lavate, farvi rosolare il fegato, da entrambe le parti, poi irrorarlo col marsala e lasciarlo cuocere per 5 minuti. Salare, pepare e frullare il tutto. Sbattere le uova, salarle, unirvi la crema di fegato e rovesciare il composto in 1 padella antiaderente unta col burro rimasto. Quando la frittata sarà dorata nella parte inferiore, girarla e farla rosolare anche dall''altro lato, a fuoco basso, affinché cuocia anche all''interno.',989);
INSERT INTO "ricette" VALUES (10206,'Frittata Di Fiori D''acacia','Contorno','Fiori D''acacia',4,' -','1 Gambo Sedano,
1 Carotina,
1 Cipollotto,
Alcune Foglie Menta,
Alcune Foglie Melissa,
Alcune Foglie Basilico,
Olio D''oliva,
Burro,
Alcune Gocce Aceto Di Vino,
6 Uova,
Sale,
Pepe,
1 Manciata Formaggio Grattugiato,
3 Cucchiai Fiori D''acacia,
Per Decorare:,
Alcuni Fiori D''acacia Freschi','Tritate 1 gambo di sedano, 1 carotina, 1 cipollotto, alcune foglie di menta, di melissa e di basilico. Fate soffriggere un po'' d''olio e burro e unitevi la verdura tritata facendola appassire dolcemente spruzzandola con alcune gocce d''aceto. Sbattete 6 uova con sale, pepe, 1 manciata di formaggio grattugiato; unitevi 3 cucchiai di fiori d''acacia privati della parte verde e il trito di erbe. Scaldare olio e burro in una larga padella, versarvi il composto formando la frittata, rigiratela e servitela ben calda decorata con qualche fiore d''acacia fresco.',2408);
INSERT INTO "ricette" VALUES (10207,'Frittata Di Friarielli','Contorno','Cime Di Rapa',6,'Luogo: Campania.','500 G Friarielli (cime Di Rapa),
6 Uova,
2 Cucchiai Formaggio Parmigiano,
1 Cucchiaio Formaggio Pecorino Romano,
Peperoncino A Piacere,
1 Spicchio Aglio,
Sale','Lessare i friarielli. Soffriggere nell''olio, l''aglio. Aggiungere il peperoncino. Togliere l''aglio. Versare i friarielli a fuoco basso. Fare insaporire per 15 minuti. Battere le uova con il sale e i formaggi. Aggiungere i friarielli. Mettere su una padella un po'' di olio. Versare il miscuglio e spianare. Cuocere la frittata a fuoco molto basso per evitare che si bruci al centro. Cotta la prima faccia, rivoltare con l''aiuto di un coperchio, e cuocere la seconda faccia. Servire calda.',895);
INSERT INTO "ricette" VALUES (10208,'Frittata Di Gamberetti','Contorno','Gamberetti',4,' -','250 G Gamberetti Sgusciati,
12 Olive Nere Sminuzzate,
1 Cucchiaio Prezzemolo,
130 G Riso,
1 Cucchiaino Pepe Di Caienna,
1 Cucchiaino Pepe Bianco,
2 Cucchiaini Burro,
5 Uova,
4 Cucchiai Formaggio Parmigiano Reggiano,
1 Cucchiaino Succo Di Limone','Fate cuocere a vapore per circa tre minuti i gamberetti, le olive, il prezzemolo, il riso, il pepe di Caienna e il sale. In una terrina sbattere le uova, il sale e il pepe bianco. Mettere in una padella antiaderente il burro e cuocere fino a che si formano le prime bolle. Allora spargere la superficie con il composto di uova e i gamberetti. Spolverare con parmigiano reggiano. Cuocere per sette o otto minuti, alzando i bordi della frittata ogni tanto. Tagliare in quarti e spruzzare con succo di limone prima di servire.',2029);
INSERT INTO "ricette" VALUES (10209,'Frittata Di Gamberetti (2)','Contorno','Gamberetti',4,' -','200 G Gamberetti,
6 Uova,
1/2 Cipolla,
1/2 Spicchio Aglio,
Olio D''oliva,
Sale,
Pepe','Lavare e sgusciare i gamberetti. Tritare aglio e cipolla e farli imbiondire in 2 cucchiai di olio. Unire i gamberetti e cuocerli a fuoco vivo. Sbattere le uova con sale e pepe e versarle nella padella con i gamberetti. Cuocere la frittata per 2-3 minuti finché il fondo si sarà rappreso, poi rigirarla e cuocerla per altri 3 minuti. Servirla tiepida o fredda.',1485);
INSERT INTO "ricette" VALUES (10210,'Frittata Di Gamberetti (3)','Antipasto','Gamberetti',4,' -','200 G Gamberetti,
4 Uova,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Friggere i gamberetti in padella fino al colore rosso. Sbattere le uova con sale e pepe; versarle nella padella dei gamberetti e portare a cottura in forno caldo. Servire immediatamente.',1284);
INSERT INTO "ricette" VALUES (10211,'Frittata Di Gamberi','Pesce','Gamberi',4,' -','8 Uova,
100 G Gamberi Già Sgusciati,
5 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Sgusciate le uova in una terrina e sbattetele leggermente, unendo una presa di sale e una di pepe. Ponete i gamberi in una padella con l''olio e fateli soffriggere per 5 minuti. Poi versatevi le uova e, quando la frittata sarà rappresa da una parte, rivoltatela con un piatto o con un coperchio, facendola cuocere anche dall''altro lato. Servite la frittata ben calda in tavola, disposta su un piatto.',1301);
INSERT INTO "ricette" VALUES (10212,'Frittata Di Lampascioni','Contorno','Lampascioni',4,' -','6 Uova,
500 G Lampascioni,
300 G Pomodori Maturi,
4 Cucchiai Formaggio Pecorino Grattugiato,
1/2 Bicchiere Olio D''oliva,
Sale','Pulite i lampascioni, togliete le prime foglie, quindi strofinateli con un canovaccio umido per eliminare ogni traccia di terriccio e riduceteli a fettine sottili. Fateli cuocere in una pentola piena d''acqua bollente salata, in modo che perdano l''amaro, e scolateli dopo 15 minuti. Fate scaldare l''olio d''oliva in una padella e rosolatevi i lampascioni, a calore moderato per 10 minuti, mescolando spesso con un cucchiaio di legno. Quando i lampascioni sono quasi cotti, mettete nella padella i pomodori, privati dei semi e tagliati a filetti, salate, unite le uova sbattute a parte con il Pecorino grattugiato, livellate il composto con una paletta e lasciatele rapprendere, per 4-5 minuti; girate la frittata e cuocetela per lo stesso tempo anche dall''altro lato. Servitela ben calda. --- CONSIGLI. I lampascioni, detti anche cipollacci col fiocco o ''''lapasciuoli'''', sono bulbi commestibili di una pianta il cui nome scientifico è Muscari comosum. I lampascioni, vagamente simili nell''aspetto alle cipolle, sono diffusissimi allo stato spontaneo, ma vengono anche coltivati, soprattutto nelle regioni dell''Italia meridionale, e raccolti da novembre a marzo. Il loro caratteristico sapore amarognolo, che non tutti gradiscono, può essere attenuato con la bollitura, prima di procedere alla realizzazione del piatto che si desidera preparare.',2084);
INSERT INTO "ricette" VALUES (10213,'Frittata Di Lampascioni (2)','Contorno','Lampascioni',4,' -','600 G Lampascioni,
5 Uova,
50 G Formaggio Pecorino Dolce Grattugiato,
Prezzemolo,
Sale,
Pepe Bianco,
Olio D''oliva Extra-vergine','Pulire i lampascioni, lavarli e praticare un taglio a croce alla base. Lessarli in acqua salata per 3/4 d''ora. Sbattere le uova, incorporare formaggio, prezzemolo tritato, sale e pepe macinato. Unire al composto i lampascioni cotti e schiacciati. In una padella far scaldare a fuoco vivo qualche cucchiaio d''olio senza farlo fumare e versarvi il composto. Dopo 1 minuto abbassare la fiamma e coprire. Trascorsi 5 minuti controllare che la frittata sia ben dorata sotto, rivoltarla facendola cuocere dall''altra parte senza coperchio. Servire tiepida.',1892);
INSERT INTO "ricette" VALUES (10214,'Frittata Di Lattuga','Contorno','Insalata Lattuga',4,' -','5 Uova,
1 Cespo Insalata Lattuga,
40 G Burro,
Sale,
Pepe Bianco','Lavate la lattuga, tagliatela a striscioline, insaporitela in 30 g di burro per dieci minuti, salate, pepate. Sbattete le uova, salatele appena; sciogliete il resto del burro nella padella per frittate, e versate la lattuga mescolata al composto d''uova. Cuocete a fiamma bassa in modo che la frittata cuocia fuori e resti un po'' morbida dentro. Servite ben calda.',808);
INSERT INTO "ricette" VALUES (10215,'Frittata Di Lumache Di San Giuseppe','Contorno','Lumache',4,' -','20 Lumache,
6 Uova,
Alcuni Pezzetti Sedano,
Basilico,
Formaggio Parmigiano,
Aglio,
Pepe,
Sale','Fate spurgare le lumache. Per far spurgare le lumache, tenerle per dieci giorni circa in cantina in un tino coperto a digiunare e ogni giorno vanno cosparse con manciate di crusca. Passato il tempo. dopo, aver scartato quelle morte, lavate quelle che sono ancora vive con acqua e aceto finché l''acqua resterà pulita. Per una frittata ne occorrono almeno una ventina. Lessatele, sgusciatele e pulitele bene. Aggiungetele ad un composto di rossi di uova battuti con bianchi montati a neve e poi incorporati. Calcolate circa sei uova ogni venti lumache. Potete aggiungere qualche pezzetto di sedano, sale, prezzemolo, basilico a piacere, formaggio, parmigiano grattugiato. aglio, pepe. Fate cuocere la frittata nella padella di ferro, rigirandola al solito modo.',1974);
INSERT INTO "ricette" VALUES (10216,'Frittata Di Maccheroni','Primo','Uova',6,' -','600 G Pasta Tipo Vermicelli,
7 Uova,
150 G Burro,
100 G Formaggio Parmigiano','Lessare e scolare al dente i vermicelli, condire con il burro e il parmigiano. Sbattere e salare le uova, poi mescolarle con i vermicelli. Intanto mettere sul fuoco una padella con un po'' d''olio. Quando l''olio sarà caldo versare nella padella i vermicelli, abbassare la fiamma e, quando la pasta sarà cotta da un lato, rivoltare per far cuocere l''altro lato.',4169);
INSERT INTO "ricette" VALUES (10217,'Frittata Di Maccheroni (2)','Primo','Uova',4,'Luogo: Lazio. Luogo: Ciociaria. Luogo: Roccasecca.','500 G Pasta Tipo Maccheroni,
4 Uova,
Abbondante Prezzemolo,
Abbondante Basilico,
Olio D''oliva Extra-vergine,
Formaggio Parmigiano Grattugiato,
Sale','Questo piatto si può fare con maccheroni cotti al dente o anche avanzati da precedente lessatura. Si prepari una salsa composta dalle uova sbattute in una terrina, il prezzemolo, il basilico, il parmigiano ed il sale; si mescolino i maccheroni alla salsa e si versi il tutto in una larga padella in cui sia stato fatto scaldare olio (o burro nella variante partenopea). Si lasci cuocere e ben rosolare la frittata su ambo i lati a fuoco dolce e si disponga infine su un piatto grande. Ottima sia calda che fredda da portare in occasione di pic-nic, pellegrinaggi, incontri di calcio, etc.',3157);
INSERT INTO "ricette" VALUES (10218,'Frittata Di Mele','Dessert','Mele',4,' -','200 G Farina,
25 Cl Latte,
2 Uova,
1 Manciata Uvetta Sultanina,
300 G Mele,
Sale,
Burro,
Zucchero','Ammollare l''uvetta. Sbucciare e affettare sottilmente le mele. Setacciare la farina, unirvi una presa di sale, le uova e il latte freddo. Mescolare fino ad avere una pastella liscia. Ungere con il burro una padella antiaderente, porla su fuoco medio, versarvi metà della pastella e quando comincia a cuocersi disporvi l''uvetta strizzata e le mele. Farle ammorbidire poi coprire con l''altra pastella. Farla rapprendere, girarla come una frittata e portare a cottura. Servire tiepida cosparsa di zucchero.',2004);
INSERT INTO "ricette" VALUES (10219,'Frittata Di Moleche','Pesce','Moleche',4,' -','500 G Moleche,
4 Uova,
Olio D''oliva Extra-vergine,
Farina,
Sale,
Prezzemolo Tritato Finemente','Infarinare e friggere le moleche in olio caldo ma non rovente; tagliarle a pezzi e mescolarle in una terrina alle uova battute; salare e aggiungere il prezzemolo tritato finemente. Col composto procedere alla preparazione di una normale frittata.',1913);
INSERT INTO "ricette" VALUES (10220,'Frittata Di Ortiche','Contorno','Ortiche',4,' -','7 Uova,
4 Cucchiai Latte,
1 Cucchiaino Farina Bianca,
1 Cipollotto,
100 G Salame Morbido,
Sale,
Pepe,
250 G Punte D''ortica Lavate, Scottate A Vapore, Scolate E Tritate','Sbattere le uova con la farina, il latte, il sale e il pepe, unite il salame sbriciolato e incorporate le ortiche mescolando bene. Scaldare il burro in una padella rosolandovi il cipollotto tritato, versarvi il composto, lasciare indorare, rivoltare e cuocere dall''altra parte. Servire con insalatina fresca.',1266);
INSERT INTO "ricette" VALUES (10221,'Frittata Di Ortiche (2)','Contorno','Ortiche',2,' -','4 Uova Fresche,
1/2 Bicchiere Latte,
1 Pizzico Sale,
1 Manciata Foglie Di Ortica,
4 Foglie Basilico','Sbattere 4 uova fresche in una terrina; aggiungere 1/2 bicchiere di latte, 1 pizzico di sale, 1 manciata di foglie di ortica e 4 foglie di basilico, quindi mescolare bene e versare il composto in una teglia antiaderente. Mettere nel forno precedentemente fatto scaldare e fare cuocere per circa 30 minuti.',442);
INSERT INTO "ricette" VALUES (10222,'Frittata Di Ortiche (3)','Contorno','Ortiche',4,' -','6 Uova,
700 G Germogli D''ortica Teneri,
30 G Formaggio Parmigiano Reggiano Grattugiato,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Muniti di guanti mondare e lavare le ortiche, quindi cuocerle per 5 minuti in pochissima acqua leggermente salata. Strizzarle e triturarle. Sbattere poco le uova con sale, pepe, parmigiano e unirvi le ortiche. Versare il composto in olio ben caldo e cuocere la frittata sui due lati.',1492);
INSERT INTO "ricette" VALUES (10223,'Frittata Di Patate','Contorno','Patate',4,'Preparazione: 15 minuti. Cottura: 20 minuti.','6 Uova,
300 G Patate,
4 Scalogni,
1 Rametto Rosmarino,
40 G Burro,
1 Cucchiaio Olio D''oliva Extra-vergine,
2 Pizzichi Sale,
1 Macinata Pepe','Sbucciate gli scalogni e tagliateli a spicchietti. Sbucciate le patate, lavatele e tagliatele a cubetti. Fatele rosolare con gli scalogni in una padella con il burro, un cucchiaio di olio e il rosmarino. Proseguite la cottura a fiamma media finché le patate sono tenere e dorate. Battete le uova con due pizzichi di sale e una macinata di pepe, versate il composto sulle patate e fatelo rapprendere. Girate poi la frittata e cuocetela anche sull''altro lato, finché sarà ben dorata. Servitela calda o tiepida, tagliata a spicchi.',1500);
INSERT INTO "ricette" VALUES (10224,'Frittata Di Piselli','Contorno','Piselli',4,' -','300 G Piselli,
1 Pomodoro Maturo,
1 Spicchio Aglio,
Prezzemolo,
1 Cucchiaio Pangrattato,
6 Uova,
1 Cucchiaio Formaggio Grana Grattugiato,
Poco Olio D''oliva,
Poco Burro,
Basilico,
1 Cespo Insalata Lattuga,
1 Manciata Insalata Rucola,
1 Cipollotto,
Sale,
Pepe','Soffriggere per 5 minuti in poco olio e burro un trito di aglio e prezzemolo e il pomodoro pelato a pezzetti. Unire i piselli, sale, pepe e cuocere coperto per 30 minuti, bagnando, se occorre, con acqua calda. Sbattere le uova con grana, pangrattato, basilico e i piselli cotti. Cuocere la frittata come al solito e servirla con lattuga, rucola e cipollotto tagliuzzati.',1636);
INSERT INTO "ricette" VALUES (10225,'Frittata Di Piselli (2)','Contorno','Piselli',4,' -','500 G Piselli Sgranati,
6 Uova,
2 Cipollotti Novelli,
Prezzemolo,
Brodo Vegetale,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Imbiondire i cipollotti triturati nell''olio; unire i piselli, farli saltare, allungare con un po'' di brodo e stufarli, salando. In una ciotola sbattere le uova; salarle, peparle, unirvi il prezzemolo finemente tritato e infine i piselli ben cotti e stiepiditi. Scaldare l''olio in una padella e quando è ben caldo, versarvi il composto di uova e piselli, facendo cuocere sui due lati.',1715);
INSERT INTO "ricette" VALUES (10226,'Frittata Di Pomodoro','Contorno','Pomodori San Marzano',4,' -','5 Uova,
250 G Pomodori San Marzano,
Aglio,
Prezzemolo,
Basilico,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Tagliare a dadolata i pomodori e farli saltare nell''olio per 5 minuti con aglio e olio. Unire poi del basilico sminuzzato. Farli raffreddare in un colabrodo, poi unirli alle uova sbattute con un po'' di sale e pepe; mescolare bene il composto e versarlo in una padella con olio ben caldo; cuocere la frittata da entrambi i lati e servire con prezzemolo tritato finemente.',1257);
INSERT INTO "ricette" VALUES (10227,'Frittata Di Ricotta','Contorno','Ricotta',4,' -','200 G Ricotta,
2 Cucchiai Formaggio Parmigiano,
2 Uova','Amalgamare il tutto e cuocere con un pizzico di burro.',608);
INSERT INTO "ricette" VALUES (10228,'Frittata Di Riso','Contorno','Riso',4,' -','300 G Riso Lessato,
3 Uova,
30 G Burro,
40 G Formaggio Parmigiano Grattugiato,
1 Scalogno,
Sale,
Pepe','In una padella scaldate il burro, fatevi appassire lo scalogno. Sbattete le uova, salatele, pepatele, unite il riso e il parmigiano. Versate il composto nella padella e fate colorire da entrambe le parti il tempo necessario. Servite ben caldo con salsa di pomodoro a parte se piace.',1687);
INSERT INTO "ricette" VALUES (10229,'Frittata Di Riso Agli Asparagi','Contorno','Asparagi',4,'Luogo: Trentino-Alto Adige. Luogo: Trentino.','6 Uova,
120 G Riso,
300 G Asparagi Surgelati,
100 G Speck (fette Da 100 G),
40 G Formaggio Grana Grattugiato,
Brodo Vegetale,
1 Cipolla Piccola,
60 G Burro,
Sale,
Pepe','Fate scongelare gli asparagi, tagliateli poi a tocchetti regolari e rosolateli in una casseruola con la cipolla tritata e mondata, 50 g di burro e lo speck tagliato a listarelle. Unite quindi il riso, lasciatelo tostare per qualche istante, poi bagnatelo con un mestolo di brodo caldo e portatelo a cottura tenendolo al dente, unendo man mano dell''altro brodo. Regolate di sale e pepate a piacere, quindi trasferite il risotto ottenuto in una ciotola e lasciatelo intiepidire, mescolando spesso. Sbattete leggermente le uova con un po'' di sale e pepe, unitevi il grana e il risotto e mescolate bene. Versate il composto in una padella antiaderente, in cui avrete fatto sciogliere il burro rimasto, e fatelo rassodare, prima da un lato e poi dall''altro, aiutandovi, nel girarlo con un coperchio piatto. Servite subito.',1803);
INSERT INTO "ricette" VALUES (10230,'Frittata Di Riso Con Asparagi','Contorno','Asparagi',4,' -','6 Uova,
120 G Riso,
300 G Asparagi,
100 G Speck (fette Da 100 G),
40 G Formaggio Grana Grattugiato,
Brodo Vegetale,
1 Cipolla Piccola,
60 G Burro,
Sale,
Pepe','Fate scongelare gli asparagi, tagliateli poi a tocchetti regolari e rosolateli in una casseruola con la cipolla tritata e mondata, 50 g di burro e lo speck tagliato a listarelle. Unite quindi il riso, lasciatelo tostare per qualche istante, poi bagnatelo con un mestolo di brodo caldo e portatelo a cottura tenendolo al dente, unendo man mano dell''altro brodo. Regolate di sale e pepate a piacere, quindi trasferite il risotto ottenuto in una ciotola e lasciatelo intiepidire, mescolando spesso. Sbattete leggermente le uova con un po'' di sale e pepe, unitevi il grana e il risotto e mescolate bene. Versate il composto in una padella antiaderente, in cui avrete fatto sciogliere il burro rimasto, e fatelo rassodare, prima da un lato e poi dall''altro, aiutandovi, nel girarlo con un coperchio piatto. Servite subito.',1803);
INSERT INTO "ricette" VALUES (10231,'Frittata Di Sabrina','Contorno','Uova',4,' -','4 Uova,
4 Patate,
1 Rametto Rosmarino,
Sale,
Pepe,
Olio D''oliva','Sbucciate le patate, sciacquatele con cura, asciugatele con della carta assorbente e tagliatele a dadini regolari. Nel frattempo, lasciate riscaldare l''olio d''oliva preferibilmente in una padella antiaderente e quando sarà ben caldo, versate le patate. Fatele cuocere fino a dorarle, insaporitele con il sale e giratele di tanto in tanto servendovi di un cucchiaio di legno, evitando così di spappolarle. Successivamente, versate il battuto d''uova al quale avrete unito il pepe e un pizzico di sale, e aggiungete il rosmarino, che avrete precedentemente sciacquato sotto l''acqua corrente. Continuate la cottura fino a quando l''uovo si sarà rassodato, dopodichè, facendo attenzione a non scottarvi, capovolgete la frittata servendovi di un piatto piano e lasciate cuocere e dorare l''altra parte. A cottura ultimata, disponetela in un piatto e servitela subito calda e croccante.',1799);
INSERT INTO "ricette" VALUES (10232,'Frittata Di Spaghetti','Contorno','Spaghetti',4,' -','6 Uova,
1 Piatto Pasta Tipo Spaghetti Freddi Con Salsa Di Pomodoro,
1 Cucchiaio Prezzemolo Tritato,
3 Cucchiai Formaggio Parmigiano Grattugiato,
Olio D''oliva,
Sale,
Pepe','Tagliate gli spaghetti a pezzetti. Sbattete le uova con un po'' di sale e pepe, il prezzemolo tritato, il formaggio grattugiato, aggiungete gli spaghetti. Amalgamate e versate il composto in una padella dove l''olio è già caldo. Fate dorare da ambo le parti. Tagliate la frittata a spicchi e servitela.',1824);
INSERT INTO "ricette" VALUES (10233,'Frittata Di Spaghetti (2)','Contorno','Funghi Champignon',4,' -','100 G Pasta Tipo Spaghetti,
100 G Funghi Champignon,
1 Spicchio Aglio,
3 Uova,
6 Olive Verdi,
6 Olive Nere,
Sale,
1 Cucchiaio Olio D''oliva Extra-vergine,
Prezzemolo,
Formaggio Parmigiano,
Noce Moscata','Sbattere le uova con un po'' di sale e noce moscata. Pulire gli champignon e tagliarli a fettine. Saltare i funghi in padella con olio, aglio e prezzemolo ed unirli poi con le uova sbattute, il burro, le olive tritate, gli spaghetti lessati e fare una frittata. Aggiungere parmigiano e voltare la frittata, quindi romperla con 2 palette e far saltare il tutto.',1544);
INSERT INTO "ricette" VALUES (10234,'Frittata Di Trota','Pesce','Trota',4,' -','250 G Filetti Di Trota,
1 Spicchio Cipolla,
1 Cucchiaio Olio D''oliva Extra-vergine,
1 Cucchiaio Prezzemolo,
4 Uova,
2 Cucchiai Latte,
20 G Burro,
Sale','Scaldate l''olio in una padella antiaderente, aggiungete i filetti di trota e la cipolla intera. Cuocete per 6-7 minuti girando il pesce più volte. Salate, eliminate la cipolla e sminuzzate il pesce con la forchetta. Battete le uova con un pizzico di sale e il prezzemolo tritato, aggiungete il latte e la trota sminuzzata. Fate fondere il burro nella padella, versate il composto di uova e pesce e cuocete la frittata a fuoco lento.',1127);
INSERT INTO "ricette" VALUES (10235,'Frittata Di Uva','Dessert','Uva Nera',4,' -','6 Uova,
24 Acini Uva Nera,
25 G Burro,
3 Cucchiai Zucchero,
Brandy,
Zucchero A Velo,
Cannella In Polvere,
1 Cucchiaio Pangrattato','Pulire gli acini e metterli a macerare in una zuppiera con zucchero e brandy per 1 ora. Battere i tuorli con il pangrattato e unire gli albumi montati a neve, mescolando delicatamente. Friggere il burro in una teglia e rovesciarvi il composto di uova. Farlo rapprendere e poi disporvi sopra gli acini. Levare la teglia dal fuoco e passarla in forno sotto il grill già caldo per alcuni minuti. Servire la frittata fredda spolverizzata di zucchero a velo e cannella',1369);
INSERT INTO "ricette" VALUES (10236,'Frittata Di Ventresca E Asparagi','Contorno','Asparagi',4,'Luogo: Ciociaria. Luogo: Lazio.','100 G Pancetta Affumicata,
Asparagi Di Montagna,
1 Cipollina Fresca,
Olio D''oliva,
Sale','Si fanno soffriggere la pancetta, gli asparagi e la cipollina in una padella unta d''olio. A parte si battono le uova con il sale. Non appena il soffritto è dorato, si uniscono le uova battute e si fa dorare la frittata da ambo le parti.',1320);
INSERT INTO "ricette" VALUES (10237,'Frittata Di Vermicelli','Primo','Uova',6,' -','600 G Pasta Tipo Vermicelli,
7 Uova,
150 G Burro,
100 G Formaggio Parmigiano','Lessare e scolare al dente i vermicelli, condire con il burro e il parmigiano. Sbattere e salare le uova, poi mescolarle con i vermicelli. Intanto mettere sul fuoco una padella con un po'' d''olio. Quando l''olio sarà caldo versare nella padella i vermicelli, abbassare la fiamma e, quando la pasta sarà cotta da un lato, rivoltare per far cuocere l''altro lato.',4169);
INSERT INTO "ricette" VALUES (10238,'Frittata Di Vongole','Contorno','Vongole',4,' -','6 Uova,
1000 G Vongole,
Prezzemolo,
2 Spicchi Aglio,
4 Cucchiai Olio D''oliva,
2 Cucchiai Latte,
1 Bicchiere Vino Bianco,
Pepe,
Sale','Lavate le vongole e mettetele in un tegame con acqua per farle aprire. Sgusciatele, lasciandone da parte qualcuna per guarnire. Filtrate la loro acqua. In una padella fate rosolare 2 spicchi di aglio, il prezzemolo tritato e 4 cucchiai d''olio. Dopodichè unite le vongole, pepate e salate pochissimo, bagnate il tutto con un bicchiere di vino bianco. Lasciate cuocere per qualche minuto. Sbattete le uova salandole e aggiungete 2 cucchiai di latte; con questo composto fate una frittata. Successivamente versate nel centro della frittata le vongole con il loro sugo, chiudete la frittata e guarnite con le vongole intere rimaste.',2894);
INSERT INTO "ricette" VALUES (10239,'Frittata Di Zucca E Cipolla','Contorno','Zucca',4,' -','200 G Zucca,
1 Cipolla Di Tropea,
40 G Formaggio Grana,
8 Uova,
Olio D''oliva Extra-vergine,
Sale Marino','Affettare sottilmente la zucca e la cipolla. Farle stufare in poca acqua, quindi unire un po'' d''olio e far rosolare brevemente. Aprire le uova in una ciotola; unire sale, grana grattugiato; batterle delicatamente. Amalgamarvi zucca e cipolle scolate dall''olio. Cuocere in un''ampia padella (di ferro) appena unta d''olio.',1644);
INSERT INTO "ricette" VALUES (10240,'Frittata Di Zucca E Cipolla Con Aceto','Contorno','Zucca',4,' -','200 G Zucca,
1 Cipolla Di Tropea,
40 G Formaggio Grana,
8 Uova,
Olio D''oliva Extra-vergine,
Sale Marino,
1 Spruzzatina Aceto Di Vino Rosso','Affettare sottilmente la zucca e la cipolla. Farle stufare in poca acqua, quindi unire un po'' d''olio e far rosolare brevemente. Aprire le uova in una ciotola; unire sale, grana grattugiato; batterle delicatamente. Amalgamarvi zucca e cipolle scolate dall''olio. Cuocere in un''ampia padella (di ferro) appena unta d''olio. Servire con una spruzzatina di buon aceto di vino rosso.',1645);
INSERT INTO "ricette" VALUES (10241,'Frittata Di Zucchine','Contorno','Zucchine',2,' -','4 Uova Fresche,
1 Pizzico Sale,
2 Zucchine,
4 Foglie Basilico,
1/2 Bicchiere Latte Fresco','Sbattere 4 uova fresche in una terrina, aggiungere 1 pizzico di sale, 2 zucchine tagliate a rondelle, 4 foglie di basilico, 1/2 bicchiere di latte fresco. Versare il composto in una teglia antiaderente e porre in forno già caldo per 35 minuti. Può essere consumata anche fredda.',476);
INSERT INTO "ricette" VALUES (10242,'Frittata Di Zucchine Alla Menta','Contorno','Zucchine',4,' -','750 G Zucchine Con I Fiori,
9 Uova,
1 Manciata Formaggio Parmigiano Grattugiato,
1 Spicchio Aglio,
1 Manciata Foglioline Di Menta,
Sale,
Poco Olio D''oliva Extra-vergine','Pulite le zucchine separando i fiori. Lavatele e tagliate le prime a fette ed i secondi a spicchi dopo aver eliminato il pistillo e la base dura. Fate rosolare le zucchine con 1 spicchio di aglio schiacciato e poco olio e con la menta tritata grossolanamente. Quando sono a metà cottura unite anche i fiori. Lasciate raffreddare, ed eliminate lo spicchio di aglio. Versate le zucchine in una ciotola, scolando ogni liquido prodotto in cottura, unite il parmigiano, le uova, aggiustate di sale e mescolate per amalgamare il tutto. Cuocete la frittata in una padella con un po'' di olio, girandola con l''aiuto di un coperchio a metà cottura; oppure se preferite una preparazione più leggera e facile versate il composto in una teglia antiaderente velata di olio e spolverata di pangrattato e cuocetela in forno caldo a 180 gradi. Potete anche cuocerla nel microonde in un contenitore adatto.',1664);
INSERT INTO "ricette" VALUES (10243,'Frittata Di Zucchine E Champignon','Contorno','Zucchine',4,'Luogo: Lazio.','8 Uova,
300 G Funghi Champignon,
40 G Formaggio Parmigiano Grattugiato,
3 Cucchiai Latte,
2 Spicchi Aglio,
2 Zucchine,
2 Cucchiai Semi Di Sesamo,
1 Rametto Timo,
60 G Burro,
Sale,
Pepe','Mondate i funghi, privandoli della parte terrosa, lavateli, affettateli e, in un tegame, fateli cuocere per una ventina di minuti insieme con 30 g di burro e l''aglio, che poi eliminerete. Unite le zucchine (spuntate, pulite e tagliate a rondelle sottili), il timo, sale e pepe a piacere, e continuate la cottura per una decina di minuti, poi lasciate intiepidire. In una ciotola, sgusciate le uova e sbattetele con il formaggio, 3 cucchiaiate di latte e un pizzico di sale e pepe. Aggiungetevi i funghi e le zucchine, mescolate bene e versate il tutto in un tegame antiaderente in cui avrete fatto sciogliere il burro. Cuocete la preparazione a fuoco moderato per un paio di minuti, poi cospargete con il sesamo, copritela con un coperchio e cuocetela fino a quando risulterà rassodata. Mettete il tegame sotto il grill del forno (avendo cura di rivestire il tegame di carta stagnola) e cuocete la fritta finchè risulterà dorata.',1534);
INSERT INTO "ricette" VALUES (10244,'Frittata Di Zucchine E Cipolla','Contorno','Zucchine',4,' -','Cipolle,
Olio D''oliva,
1/2 Dado,
Zucchine,
8 Uova,
Noce Moscata Grattugiata (o Paprica)','Fare un battuto di cipolle e soffriggere in un po'' d''olio e 1/2 dado; affettare le zucchine e aggiungerle alla cipolla semirosolata; sbattere le uova (2 per persona) e aggiungervi noce moscata grattugiata (o altre spezie a piacere, paprica dolce ad esempio). Quando le zucchine sono cotte si uniscono le uova sbattute e si rosola da ambo le parti oppure lo si copre col coperchio e lo si lascia asciugare.',1537);
INSERT INTO "ricette" VALUES (10245,'Frittata Di Zucchine E Ricotta','Contorno','Zucchine',4,' -','800 G Zucchine,
6 Uova,
200 G Ricotta,
40 G Formaggio Parmigiano,
1 Spicchio Aglio,
Prezzemolo,
Sale,
Olio D''oliva','Pulite le zucchine, tagliatele a rondelle e insaporitele a fuoco dolce con alcuni cucchiai d''olio, lo spicchio d''aglio, un po'' di prezzemolo tritato e un pizzico di sale. Sminuzzate la ricotta e lavoratela con un mestolo per ridurla a crema, unitevi il parmigiano, le zucchine insaporite (togliete l''aglio), mescolate delicatamente. In una padella scaldate due o tre cucchiai d''olio, mettevi il composto di zucchine, versategli sopra le uova sbattute e salate quanto basta. Cuocete come una normale frittata e servite calda.',1826);
INSERT INTO "ricette" VALUES (10246,'Frittata Dolce','Antipasto','Uova',2,' -','3 Uova,
50 G Zucchero,
12 Cl Panna Liquida,
Burro,
1 Pizzico Cannella,
1 Limone (scorza),
Liquore Dolce','Sbattere i rossi d''uovo con lo zucchero il burro ammorbidito, il pizzico di cannella, il sale, la panna e la buccia di limone grattugiata; sbattere e unire le chiare d''uovo. Scaldare il burro, versare dentro il composto, dargli la forma di frittata e cuocere. Servire dopo aver bagnato con un poco di liquore e cosparso con un velo di zucchero.',1960);
INSERT INTO "ricette" VALUES (10247,'Frittata Dolce (2)','Contorno','Uova',4,' -','4 Uova,
5 Zollette Zucchero,
1 Arancia,
1/2 Bicchiere Rum,
100 G Zucchero Semolato,
Burro','Separare i tuorli dagli albumi. Montare i primi con lo zucchero per ottenere un composto cremoso. Sciogliere le zollette nel rum. Incorporare alla crema di tuorli il rum e il succo di arancia. Montare a neve gli albumi e unirli ai tuorli. Versare il composto in una pirofila imburrata e passare in forno caldo a 220 gradi per 10 minuti.',1872);
INSERT INTO "ricette" VALUES (10248,'Frittata Dolce (3)','Dessert','Mele',4,' -','2 Uova,
2 Mele,
40 G Burro,
3 Cucchiai Farina,
1/2 Bicchiere Latte,
Calvados,
Zucchero A Velo','Diluire la farina setacciata con il latte poi unire i tuorli e mescolare bene. Montare a neve soda gli albumi e incorporarli al composto. Sbucciare le mele, privarle del torsolo e tagliarle a fettine sottili. In una padella antiaderente sciogliere il burro e farvi dorare le fettine di mele per alcuni minuti. Spruzzarle con il calvados e farlo evaporare poi versare il composto di uova. Cuocere la frittata da entrambi i lati e servirla calda e spolverizzata di zucchero a velo.',1081);
INSERT INTO "ricette" VALUES (10249,'Frittata Dolce (4)','Dessert','Uova',4,' -','6 Uova,
2 Cucchiai Cacao Amaro,
2 Cucchiai Zucchero,
1 Bicchierino Liquore Al Cacao,
1 Cucchiaino Fecola,
50 G Pinoli,
25 G Burro','Sgusciare le uova, separando i tuorli dagli albumi. Sbattere i primi con lo zucchero, poi unire il cacao e la fecola mescolando con 1 cucchiaio di legno. Bagnare con il liquore, unire i pinoli e gli albumi montati a neve. Mettere sul fuoco 1 padella antiaderente, farvi sciogliere il burro, versarvi il composto e lasciare rapprendere la frittata da 1 parte. Rivoltarla con 1 coperchio, farla scivolare di nuovo nella padella e cuocerla anche dall''altro lato.',1340);
INSERT INTO "ricette" VALUES (10250,'Frittata Dolce Di Uva','Dessert','Uva',4,' -','6 Uova,
1 Cucchiaio Pangrattato,
2 Cucchiai Zucchero A Velo,
3 Cucchiai Zucchero Semolato,
25 G Burro,
12 Acini Uva Bianca,
12 Acini Uva Nera,
1 Bicchierino Brandy','Sbattere i tuorli con il pangrattato, unire le chiare montate a neve e versare il composto in una padella con il burro. Adagiarvi gli acini d''uva fatti macerare per 1 ora con il brandy e lo zucchero semolato, infornare per pochi minuti, spolverizzare di zucchero a velo e servire fredda.',1242);
INSERT INTO "ricette" VALUES (10251,'Frittata Doppia Piccante','Contorno','Uova',4,' -','6 Uova,
2 Cipolline,
1 Salamino Tipo Ungherese,
2 Cucchiai Olio D''oliva,
Burro,
Sale,
Pepe','Sbucciate le cipolline e tagliatele a fettine sottili. Tagliate a fettine anche il salamino e poi spezzettatele grossolanamente. In un tegame scaldate due cucchiai di olio, lasciatevi sfinire le cipolline, salate e pepate con moderazione, versatevi sopra tre uova sbattute e cuocete la frittata da entrambi i lati. Fate un''altra frittata di uguale dimensione con le restanti uova e il salame. Sovrapponete le due frittate, tagliatele in quattro spicchi e servite.',2634);
INSERT INTO "ricette" VALUES (10252,'Frittata Gustosa','Contorno','Fegatini Di Pollo',4,' -','6 Uova,
200 G Fegatini Di Pollo,
100 G Funghi Coltivati,
Sale,
Pepe,
1 Bicchierino Vino Marsala Secco,
2 Cucchiai Olio D''oliva,
2 Cucchiai Farina,
1 Mazzetto Prezzemolo,
1 Spicchio Aglio,
80 G Burro','Pulite i funghi, eliminate la parte terrosa dei gambi, strofinateli con una spazzolina e un canovaccio umido, infine tritateli finemente con la mezzaluna. Mondate il prezzemolo e tritate anch''esso insieme allo spicchio d''aglio. Pulite i fegatini, lavateli con cura sotto l''acqua corrente, asciugateli e passateli nella farina. Fate fondere dolcemente metà del burro in una casseruola, unitevi i funghi e il trito di aglio e prezzemolo, insaporite con una macinata di pepe e lasciate cuocere a calore moderato per 20 minuti. Trascorso questo tempo mettete nel recipiente anche i fegatini infarinati, lasciate insaporire tutt''assieme per alcuni istanti, unite il Marsala e lasciate cuocere per 5 minuti. Rompete le uova in una terrina, unite il sale necessario e una macinata di pepe e sbattetele accuratamente servendovi di una frusta. Fate scaldare il resto del burro e l''olio d''oliva in una padella, versatevi le uova sbattute e lasciatele cuocere per 3-4 minuti. Girate quindi la frittata e cuocetela anche dall''altro lato. Al termine, trasferite la frittata su un piatto di portata, versatevi sopra l''intingolo di fegatini, ben caldo, e servitela. Se preferite, potete cuocere quattro piccole frittate invece che una grande, e servirle direttamente nei piatti individuali.',1954);
INSERT INTO "ricette" VALUES (10253,'Frittata In Insalata','Contorno','Zucchine',4,'Preparazione: 30 minuti. Cottura :10 minuti. Calorie: 182.','4 Uova,
300 G Zucchine,
100 G Insalata Rucola,
20 G Formaggio Parmigiano Grattugiato,
10 G Basilico,
30 G Salsa Di Pomodoro,
5 G Bottarga Grattugiata,
30 G Olio D''oliva,
10 Cl Vino Bianco Tipo Vernaccia,
Sale,
Pepe','Sbattete in una ciotola le uova con il parmigiano, una presa di sale e una macinata di pepe. Dividete in due il composto e unite a una metà la salsa di pomodoro e all''altra il basilico spezzettato. Preparate 4 frittatine in una padella antiaderente appena unta con un goccio di olio, fatele raffreddare e tagliatele a striscioline. Spuntate le zucchine, tagliatele a strisce per il lungo con un pelapatate e scottatele in acqua bollente leggermente salata per un minuto. Suddividete la rucola in 4 piatti piani, mescolate le zucchine con la frittata e sistematele al centro dei piatti. Scaldate in un pentolino l''olio con il vino bianco e fate ridurre a fuoco medio per 2 minuti, unite la bottarga e condite con questa salsina le insalate.',868);
INSERT INTO "ricette" VALUES (10254,'Frittata Infiammata Al Brandy','Contorno','Brandy',4,' -','6 Uova,
120 G Zucchero,
50 G Burro,
10 Cl Brandy','Battere i tuorli con 90 g di zucchero per ottenere un composto vellutato, unire gli albumi a neve ferma. Scaldare il burro, versarvi il composto, passare nel forno a calore moderato per 15 minuti, facendo attenzione che la superficie non colori troppo. Sformare il dolce e cospargerlo con zucchero. Con un ferro rovente fare degli intagli in superficie, versarvi il brandy intiepidito, infiammarlo e servire ancora in fiamme.',1630);
INSERT INTO "ricette" VALUES (10255,'Frittata Invernale','Contorno','Uova',4,' -','3 Porri,
80 G Prosciutto Cotto Tagliato A Dadini,
6 Uova,
50 G Formaggio Parmigiano Reggiano Grattugiato,
50 G Formaggio Emmenthal Grattugiato,
1 Cucchiaio Prezzemolo Tritato,
Olio D''oliva,
Sale','Pulite i porri, tagliateli a fettine sottili e fateli cuocere in olio aggiungendo poco a poco un po'' d''acqua in modo da non farli scurire. Aggiungete il prosciutto cotto, aggiustate di sale e fate cuocere ancora per qualche minuto facendo asciugare il sughetto di cottura. Sbattete le uova con i formaggi grattugiati, un pizzico di sale e il prezzemolo tritato. Unite ai porri e cuocete la frittata da entrambi i lati in una teglia antiaderente piuttosto ampia.',1996);
INSERT INTO "ricette" VALUES (10256,'Frittata Marinara','Contorno','Cozze',6,' -','8 Uova,
1000 G Cozze,
200 G Gamberetti,
1 Cucchiaio Panna Liquida,
1 Cipolla,
Pepe,
Sale,
Prezzemolo,
Burro,
2 Bicchieri Vino Bianco','Pulite le cozze e mettetele in un tegame con 2 bicchieri di vino bianco, sale, pepe, cipolla e prezzemolo tritati. Lasciate bollire per 5 minuti e poi togliete le cozze dal guscio. In una padella fate sciogliere un po'' di burro e unite le cozze e i gamberetti, che avrete precedentemente lessato in acqua salata. Quando tutto sarà dorato aggiungete un cucchiaio di panna liquida. Dopodichè sbattete le uova, salatele, pepatele e cuocete nel burro come una frittata. Riempite questa frittata con le cozze, i gamberetti e richiudete.',2563);
INSERT INTO "ricette" VALUES (10257,'Frittata Ortolana','Contorno','Zucchina',4,' -','4 Uova,
1 Cucchiaio Farina Di Grano Saraceno,
1 Peperone Rosso,
1 Zucchina,
1 Cipolla,
1 Ciuffo Prezzemolo,
Alcuni Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate a fettine sottili il peperone e la cipolla e a rondelle le zucchine. Lasciatele insaporire con alcuni cucchiai d''olio in una padella antiaderente per 15 minuti coperto e a fuoco basso. Sbattete le uova, salate, pepate, unite la farina di grano saraceno e il prezzemolo tritato. Versate il composto sulle verdure e lasciate rapprendere. Quindi cuocete la frittata dall''altro lato. Servite.',1980);
INSERT INTO "ricette" VALUES (10258,'Frittata Piccante','Contorno','Cipolle',4,' -','4 Cipolle,
8 Uova,
1 Peperone Giallo,
2 Filetti D''acciughe,
2 Cucchiai Birra Bionda,
30 G Formaggio Parmigiano Grattugiato,
50 G Burro,
1 Cucchiaio Paprica Dolce,
Sale','Cuocere per 20 minuti, a tegame coperto, la cipolla affettata con il burro, una presa di sale e la paprica. Incorporare il peperone e le acciughe a pezzetti e la birra e continuare la cottura, a tegame scoperto, per altri 20 minuti. Battere le uova con il formaggio e il sale e unirle al composto di cipolle e peperone. Cuocere la frittata da entrambi i lati.',1464);
INSERT INTO "ricette" VALUES (10259,'Frittata Pomodori E Peperoni','Contorno','Pomodori',4,' -','1 Pizzico Sale,
1 Pizzico Pepe,
3 Spicchi Aglio,
Prezzemolo,
80 G Burro,
10 Uova,
300 G Pomodori,
1 Peperone Rosso,
1 Peperone Verde,
1 Peperone Giallo','Pulite i peperoni, tagliate a striscioline la polpa, passate queste striscioline in padella con un cucchiaio di burro. Passate al setaccio i pomodori, fate cuocere ciò che ricavate in tegame con due cucchiai di burro e un pizzico di sale. Sbattete le uova in una terrina, unite l''aglio e una manciata di prezzemolo tritati, un pizzico di sale, uno di pepe, unite anche la polpa dei pomodori, per ultimi i peperoni; mescolate bene per distribuire gli ingredienti, versate tutto in padella in altro burro bollente; formate e cuocete la frittata, passandola da tutte e due le parti.',1705);
INSERT INTO "ricette" VALUES (10260,'Frittata Provenzale','Contorno','Pomodori',4,'Luogo: Francia. Luogo: Provenza.','6 Uova,
4 Pomodori,
Alcuni Cucchiai Olio D''oliva,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
50 G Olive Nere,
Sale,
Pepe','Sbattete le uova, salatele, pepatele, unite uno spicchio d''aglio tritato con un ciuffo di prezzemolo e le olive snocciolate tagliate a rondelle. Scaldate in una padella alcuni cucchiai d''olio d''oliva, aggiungete i pomodori spellati, privati dei semi e tagliati a dadini, cuocete per circa un quarto d''ora: la salsa si deve addensare. Versatevi sopra le uova, cuocete la frittata da entrambi i lati. Deve riuscire ben dorata. Ottima sia calda sia fredda con un contorno di insalata verde mista.',2229);
INSERT INTO "ricette" VALUES (10261,'Frittata Ripiena','Contorno','Funghi',4,' -','4 Uova,
200 G Funghi Freschi,
50 G Lingua,
50 G Prosciutto Cotto,
50 G Formaggio Groviera,
1 Noce Burro,
Sale,
Pepe','Sbattete le uova, salate, pepate. In una larga padella cuocete la frittata con una noce di burro in modo che riesca sottile. In un tegamino sciogliete 30 g di burro e insaporitevi i funghi a lamelle. Tagliate a dadini il prosciutto, la lingua e il formaggio, uniteli ai funghi quando questi sono cotti. Stendete il ripieno su mezza frittata, spennellate di burro l''altra metà e ripiegatela sul ripieno. Adagiate la frittata su un piatto che regga il calore e ponete in forno alcuni minuti il tempo necessario perché la groviera si sciolga bene. Servitela subito calda.',1413);
INSERT INTO "ricette" VALUES (10262,'Frittata Riso E Frutta','Contorno','Riso',4,' -','70 G Riso,
50 Cl Latte,
Uvetta Sultanina,
Mele Tagliate A Quadretti,
Zucchero','Cuocere il riso nel latte, lasciar raffreddare ed aggiungere mescolando l''uvetta sultanina, le mele e lo zucchero e fare con questo impasto una piccola frittata ben colorita da entrambe le parti.',929);
INSERT INTO "ricette" VALUES (10263,'Frittata Rognosa','Contorno','Arrosto Di Vitello',6,'Luogo: Piemonte. Luogo: Alba. Preparazione: 30 minuti. Cottura: 10 minuti.','6 Uova,
200 G Salame Cotto,
200 G Arrosto Di Vitello (anche Del Giorno Prima),
1 Manciata Formaggio Parmigiano Grattugiato,
Sale,
Per Friggere:,
Olio D''oliva Extra-vergine','Tritate il salame cotto e la carne dell''arrosto di vitello con la mezzaluna. In una terrina sbattete con la frusta le uova intere, poi unite il trito di salame e arrosto, il parmigiano grattugiato e il sale. Amalgamate bene e versate questo composto in una padella con l''olio d''oliva già bollente: fate cuocere per una decina di minuti, scuotendo la frittata rognosa energicamente ogni tanto affinché non attacchi e rivoltandola a metà cottura aiutandovi col coperchio di una pentola. Prima di servirla calda, passatela su carta assorbente per eliminare l''eventuale unto. Un tempo era la frittata degli avanzi degli arrosti e del bollito: la carne rimasta (qualche ritaglio un po'' grasso e un po'' bruttino, sgradevole, rognos nel dialetto locale) veniva insaporita con qualche fetta di salame cotto e la cena del lunedì era pronta. Vino consigliato: Dolcetto di Diano d''Alba.',2658);
INSERT INTO "ricette" VALUES (10264,'Frittata Rognosa (2)','Contorno','Uova',4,' -','5 Uova,
50 G Salame A Dadini,
1 Cipolla,
40 G Burro,
Prezzemolo,
Pepe Nero,
Sale','Affettare la cipolla e farla appassire in 10 g di burro. Sbattere le uova, incorporarvi il salame, la cipolla e il prezzemolo tritato. Salare con moderazione e pepare. Fondere il resto del burro in una padella e versarvi il composto. Quando sarà rappreso rigirarlo e cuocerlo dall''altro lato per pochi minuti. Servire la frittata ben calda.',1049);
INSERT INTO "ricette" VALUES (10265,'Frittata Rustica','Contorno','Salame',4,' -','5 Uova,
Sale,
Pepe,
100 G Salame,
4 Cucchiai Formaggio Parmigiano Grattugiato','Tagliate il salame a pezzettini, poneteli in una padella antiaderente e fateli rosolare a fuoco dolce per alcuni minuti. Rompete le uova in una terrina, sbattetele con cura servendovi di una frusta, quindi insaporitele con il sale necessario e una macinata di pepe. Incorporate alle uova quattro cucchiai di Parmigiano grattugiato, poi versatele nella padella con il salame. Rimestate brevemente con un cucchiaio di legno, appiattite la frittata premendola con una paletta e lasciatela cuocere a calore moderato per circa 4-5 minuti. Quando è ben cotta da un lato, rovesciatela e fatela cuocere anche dall''altro, infine servite.',1241);
INSERT INTO "ricette" VALUES (10266,'Frittata Rustica (2)','Contorno','Uova',4,' -','5 Uova,
2 Porri,
1 Patata Lessa,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
2 Cucchiai Formaggio Parmigiano Grattugiato,
3 Cucchiai Latte,
Olio D''oliva,
Sale,
Pepe','Mondate e lavate i porri, tagliateli a rondelle poi fateli appassire in un tegame con un cucchiaio d''olio, alla fine salate, pepate, unite un trito di prezzemolo e aglio e mescolate. Togliete dal fuoco quindi aggiungete la patata lessata. In una ciotola sbattete le uova con il parmigiano grattugiato, sale, pepe e il latte. A questo punto unite pure il composto di patate e porri e rigirate. Ungete con un cucchiaio d''olio un tegame antiaderente, scaldatelo e versatevi il preparato. Cuocete la frittata 5-7 minuti per parte e rigiratela aiutandovi con un grosso coperchio o con un piatto.',1491);
INSERT INTO "ricette" VALUES (10267,'Frittata Saporita','Contorno','Acciughe Salate',4,' -','6 Uova,
2 Acciughe Salate,
2 Cucchiai Olio D''oliva,
1 Spicchio Aglio,
200 G Polpa Di Pomodoro,
Prezzemolo,
Sale','Dissalare le acciughe e tritarle con il prezzemolo, metterli in un tegame con l''olio e l''aglio schiacciato e far rosolare. Unire la polpa di pomodoro, salare, pepare e cuocere per 10 minuti a fuoco basso. Levare dal fuoco e far raffreddare. Sbattere le uova senza sale, unire la salsa preparata e mescolare. Rimettere il tegame sul fuoco e versarvi il composto. Cuocere la frittata da entrambi i lati.',998);
INSERT INTO "ricette" VALUES (10268,'Frittata Saporita (2)','Contorno','Formaggio Caciotta',6,' -','6 Uova,
200 G Farina,
80 G Burro,
3 Bicchieri Latte,
120 G Formaggio Caciotta,
Paprica,
Sale','In una padella sbattere le uova aggiungendo la farina, un po'' per volta, condire con sale e aggiungere il latte. In 1 pirofila mettere il burro e farlo sciogliere. Unire i composti e mettere al forno per 40 minuti dopo aver cosparso il tutto con fettine di caciotta e paprica. Attendere per 5 minuti circa e servire.',2413);
INSERT INTO "ricette" VALUES (10269,'Frittata Semplice','Contorno','Uova',4,' -','8 Uova,
80 G Burro,
Pepe,
Sale','Sbattere le uova, salarle e peparle.',1348);
INSERT INTO "ricette" VALUES (10270,'Frittata Soffiata','Contorno','Uova',4,' -','6 Uova,
Sale,
Pepe,
Formaggio Parmigiano Grattugiato,
1 Cucchiaio Birra,
100 G Prosciutto Cotto,
30 G Burro','Rompere le uova, separando i tuorli dagli albumi; mettere i primi in 1 piatto fondo, unirvi sale e pepe in abbondanza, poi il parmigiano e sbattere con 1 forchetta. Diluire con 1 cucchiaio di birra e aggiungere il prosciutto tritato. Montare a neve 4 albumi e incorporarli al composto, mescolando con delicatezza. Imburrare una larga pirofila, versarvi il composto preparato e mettere in forno a calore medio, lasciando cuocere per 15 minuti. Servire nel recipiente stesso di cottura.',1594);
INSERT INTO "ricette" VALUES (10271,'Frittata Sostanziosa','Contorno','Uova',1,'Ricetta adatta a: bambini piccoli.','1 Tazza Brodo Vegetale,
1 Uovo,
1 Cucchiaio Latte,
Poco Burro,
1 Pizzico Sale','Sbattiamo l''uovo in una terrina con il sale e il latte. Ungiamo una piccola padella con un po'' di burro e prepariamo una frittatina ben cotta; tagliamola a listarelle e poi a quadretti. Sistemiamo i quadretti di frittata in una fondina e versiamoci sopra il brodo molto caldo.',289);
INSERT INTO "ricette" VALUES (10272,'Frittata Tre Sapori','Contorno','Uova',4,' -','5 Uova,
70 G Mortadella In Una Sola Fetta,
70 G Fagiolino Surgelato,
80 G Mozzarella,
1 Cucchiaio Formaggio Grana,
6 Foglie Basilico,
Olio D''oliva,
Burro,
1 Presa Sale,
1 Macinata Pepe,
Prezzemolo Per Decorare','Lessate i fagiolini (ancora surgelati) in acqua bollente salata, scolateli un po'' al dente, tagliateli a pezzetti e fateli insaporire per 3 minuti in 10 g di burro. Tagliate a dadini la mozzarella e la mortadella. In una terrina sbattete leggermente le uova con una presa di sale, una macinata di pepe e un cucchiaio di grana grattugiato. In una padella antiaderente fate rosolare con un cucchiaio d''olio i dadini di mortadella, prelevateli e uniteli alle uova, con i fagiolini, la mozzarella, il basilico mondato, lavato e stracciato con le mani; mescolate. Versate il composto nella padella in cui avete rosolato la mortadella e fate cuocere la frittata da un lato. Rigiratela aiutandovi con un coperchio e completate la cottura. Trasferitela in un piatto da portata e decoratela con del prezzemolo.',2497);
INSERT INTO "ricette" VALUES (10273,'Frittata Unica','Contorno','Uova',4,' -','4 Uova,
150 G Prosciutto Cotto A Dadini,
1 Cipolla,
1 Falda Peperone Sott''olio,
4 Cucchiai Formaggio Grana Grattugiato,
Sale,
Pepe,
Olio D''oliva,
Prezzemolo','In un tegame soffriggere la cipolla affettata e il peperone a pezzetti. Togliere dal fuoco e aggiungere il prosciutto. Sbattere le uova in una ciotola con sale, pepe e il grana, unirvi il composto di prosciutto e amalgamare bene. Versare il tutto in una padella molto calda e ben unta e cuocere. Decorare con prezzemolo tritato prima di servire.',2036);
INSERT INTO "ricette" VALUES (10274,'Frittata Vediamo Se La Giro','Contorno','Patate',4,' -','250 G Patate,
6 Uova,
10 Cl Olio D''oliva,
1 Cipolla,
100 G Funghetti Sott''olio,
Sale,
Pepe','Pelate le patate, lavatele e tagliatele a fettine sottili. Tagliate fine la cipolla ed unitela all''olio già bollente in padella e alle lacrime che avete versato, stile ''Via col vento''; soffriggete il tutto per un momento ed unite quindi le patate. Fatele cuocere fino a che non saranno tenere (crude fanno schifo!). Sbattete le uova come solo la vostra mamma sa fare, unite quindi pepe, sale, i funghetti e naturalmente le patate, altrimenti perché le avete cotte? Versate il tutto in una padella unta, ciò non significa sporca, ma con un po'' d''olio dentro, fate cuocere (cruda fa schifo, vedi le patate!) a fuoco allegro, prima da un lato poi se riuscirete a girarla dall''altro, la cottura dei bordi non è indispensabili.... per fortuna!!',1734);
INSERT INTO "ricette" VALUES (10275,'Frittate Dolci Di Uova','Dessert','Uova',4,' -','4 Uova,
400 G Pane Raffermo,
50 G Burro,
50 G Zucchero,
1 Limone,
Sale','Sbriciolare il pane e metterlo a mollo. Passarlo al setaccio. Versarlo insieme alle uova intere, sale, scorza di limone, e 40 g di zucchero. Mescolare bene. Sciogliere il burro in padella. Versarvi il composto della terrina. Cuocere per 5 minuti. Girare la frittata nei due lati. Spolverare con lo zucchero rimasto.',2086);
INSERT INTO "ricette" VALUES (10276,'Frittatina Alle Erbe','Contorno','Uova',4,' -','6 Uova,
1 Manciata Erbe Miste (erba Cipollina, Menta, Maggiorana, Basilico, Prezzemolo),
1 Manciata Formaggio Parmigiano Grattugiato,
2 Cucchiai Olio D''oliva Extra-vergine,
Sale Marino Integrale,
Pepe','Sbattere brevemente le uova in una ciotola senza far perdere loro nerbo; unire sale, pepe, erbette triturate e formaggio e mescolare delicatamente. Far scaldare, ma non arroventare, 2 cucchiai d''olio in una padella e versarvi il composto; far cuocere la frittata rigirandola una o più volte.',1240);
INSERT INTO "ricette" VALUES (10277,'Frittatina Con Salsa Al Pomodoro E Acciughe Piccanti','Contorno','Acciughe Piccanti',4,' -','200 G Pasta Tipo Spaghetti,
2 Cipollotti,
10 Cl Passata Di Pomodoro,
2 Uova,
6 Acciughe Piccanti,
1 Spicchio Aglio,
2 Cucchiai Olio D''oliva Extra-vergine,
Sale','Cuocere la pasta e raffreddare. Stufare i cipollotti, affettarli e unire 2 cucchiai d''olio. Mescolarli alla pasta e unire le uova. Fare la frittata e servire con la salsa di pomodoro in cui si sono fatte sciogliere le acciughe.',1330);
INSERT INTO "ricette" VALUES (10278,'Frittatina Saporita','Contorno','Uova',1,' -','1 Uovo,
1 Cucchiaio Formaggio Parmigiano Reggiano Grattugiato,
1 Fetta Pancetta,
1 Pizzico Sale,
1 Noce Burro','Sbattete l''uovo con un pizzico di sale e col parmigiano. Fate sciogliere una noce di burro in una teglia antiaderente, lasciatevi rosolare la pancetta finché il grasso non sarà trasparente, versate l''uovo e cuocete la frittata da entrambi i lati.',1093);
INSERT INTO "ricette" VALUES (10279,'Frittatine Al Gorgonzola','Contorno','Formaggio Gorgonzola',6,' -','2 Uova,
1/2 Bicchiere Latte,
2 Cucchiai Farina Bianca,
50 G Burro,
200 G Formaggio Gorgonzola','Sbattete bene le uova, unite il latte, due cucchiaiate colme di farina, e salate. Sciogliete poco burro per volta in un tegamino e fate delle frittatine, usando per ciascuna un paio di cucchiaiate del composto: fatele ben colorire da tutti e due i lati e tenetele in caldo in un piatto a parte. Mettete poi al centro di ogni frittatina dei pezzetti di gorgonzola; arrotolate la frittatina. Allineatele poi tutte in una teglia imburrata, e passatele in forno già caldo per 5-6 minuti.',1417);
INSERT INTO "ricette" VALUES (10280,'Frittatine Alla Rucola','Contorno','Insalata Rucola',4,' -','200 G Mascarpone,
2 Uova,
100 G Farina,
20 Cl Latte,
3 Mazzetti Insalata Rucola,
Formaggi Caprini,
3 Pomodori Maturi,
Sale,
Pepe,
Formaggio Parmigiano','Sbattete le uova con farina, latte e sale ottenendo una pastella e preparate delle frittatine sottili in padella antiaderente. Mettete in una terrina il formaggio, due cucchiaiate di mascarpone, la rucola tritata ed i pomodori pelati e tagliati a pezzettini. Mescolate con sale e pepe sino ad ottenere una crema morbida con la quale spalmerete le frittatine. Sistematele arrotolate in una teglia. Mescolate il resto del mascarpone con il parmigiano in modo da ottenere una crema che distribuirete sulla superficie. Fate gratinare per 30 minuti circa in forno caldo, facendo attenzione che non secchino troppo.',2249);
INSERT INTO "ricette" VALUES (10281,'Frittatine Allo Zafferano','Contorno','Zafferano',4,' -','6 Uova,
1 Cipolla,
50 G Burro,
1 Bicchiere Latte,
1 Cucchiaino Concentrato Di Pomodoro,
1/2 Cucchiaino Zafferano,
Sale,
Pepe,
Poco Olio D''oliva,
3 Cucchiai Farina','Affettate la cipolla, fatela dorare in poco olio, unite un cucchiaino di concentrato di pomodoro e mezzo di zafferano sciolti in poca acqua calda. Cuocete per circa dieci minuti, salate, pepate. Stemperate in una ciotola tre cucchiai di farina con un bicchiere di latte, unite le uova sbattute, salate e pepate. In un padellino sciogliete un po'' di burro, mettete un po'' di composto e fate tante frittatine, al centro di ognuna disponete un po'' di soffritto, ripiegatele, sistematele su un piatto da portata caldo e servitele subito.',1594);
INSERT INTO "ricette" VALUES (10282,'Frittatine Arrotolate','Contorno','Pomodori',4,' -','8 Uova,
4 Pomodori Piccoli Non Troppo Maturi,
4 Fette Formaggio Fuso,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Latte,
Olio D''oliva,
Maggiorana Secca,
Basilico,
Sale,
Pepe','Lavate e mondate i pomodori, tagliateli a dadini e metteteli a macerare in una ciotola con 2 cucchiai d''olio e il basilico. Intanto sbattete poco le uova con il parmigiano, 2 cucchiai di latte, un pizzico di maggiorana, sale e pepe. Scaldate un cucchiaio d''olio in una padella larga, versatevi la quarta parte delle uova sbattute e cuocete senza voltare la frittata; toglietela dal tegame e preparate le altre tre. Distribuite in parti uguali sulle frittate il pomodoro lasciato insaporire nel basilico. Arrotolate avvolgendovi insieme una fetta di formaggio fuso. Per chiudere fissate con un stuzzicadenti, facendo attenzione a non rompere la frittata. Passate in forno già caldo a 180 gradi per 5 minuti e servite subito.',1966);
INSERT INTO "ricette" VALUES (10283,'Frittatine Con Spinaci','Contorno','Spinaci',6,' -','2 Uova,
1/2 Bicchiere Latte,
2 Cucchiai Farina Bianca,
50 G Burro,
400 G Spinaci,
150 G Ricotta','Sbattete bene le uova, unite il latte, due cucchiaiate colme di farina, e salate. Sciogliete poco burro per volta in un tegamino e fate delle frittatine, usando per ciascuna un paio di cucchiaiate del composto: fatele ben colorire da tutti e due i lati e tenetele in caldo in un piatto a parte. Dopo averli lavati, mettete gli spinaci in una casseruola e salate. Cuoceteli per quindici minuti: poi scolateli, strizzateli bene e tagliateli grossolanamente. Metteteli in una terrina e aggiungete, amalgamandola, la ricotta. Distribuite a cucchiaini il composto al centro di ogni frittatina, arrotolatela e disponete le frittatine in una teglia, con qualche fiocchetto di burro. Ponete la teglia in forno già caldo per 8-10 minuti.',1021);
INSERT INTO "ricette" VALUES (10284,'Frittatine Di Novellame','Antipasto','Acciughe',4,'Luogo: Molise.','500 G Acciughe,
Olio D''oliva,
1 Noce Burro,
6 Uova Fresche,
50 G Formaggio Pecorino Grattugiato,
50 G Formaggio Parmigiano Grattugiato','Sciacquare e asciugare le alici disiliscate. Mettere a soffriggere dell''olio abbondante con 1 noce di burro. A parte sbattere le uova, con i 2 tipi di formaggi grattugiati. Impastare col novelllame. Prendere l''impasto con un cucchiaio e soffriggere a fuoco lento. Togliere le frittatine ottenute e mangiare bollenti.',2624);
INSERT INTO "ricette" VALUES (10285,'Frittatine In Brodo','Primo','Uova',4,' -','100 Cl Brodo,
2 Uova,
1/2 Bicchiere Latte,
30 G Burro,
Formaggio Grattugiato,
Sale,
Pepe','Sbattete le uova, salate leggermente. In un padellino sciogliete un po'' di burro alla volta e fate due o tre frittatine sottili. Arrotolatele separatamente e tagliatele a striscioline. Lasciatele raffreddare. Scaldate il brodo, mettetevi le striscioline. Dopo due minuti togliete il recipiente dal fuoco. Suddividete le frittatine in brodo in quattro fondine e servite con formaggio grattugiato a parte.',1219);
INSERT INTO "ricette" VALUES (10286,'Frittatona Di Ciliegie','Dessert','Ciliegie',4,' -','300 G Ciliegie Snocciolate,
25 G Farina,
25 G Burro,
Zucchero A Velo,
Latte,
Zucchero,
Brandy,
4 Uova,
Cannella In Polvere,
Sale','Spruzzare le ciliegie con il brandy e farle macerare per un''ora. Sbattere i tuorli con lo zucchero, unirvi il sale, la farina e un po'' di latte; mescolare e unire gli albumi montati a neve. Imburrare 1 pirofila, disporvi sul fondo in un solo strato le ciliegie scolate dal liquore, versarvi sopra le uova e passare in forno a 160 gradi per 30 minuti. Appena le uova si saranno rapprese e la frittata sarà dorata, sfornarla, cospargerla di zucchero a velo, mescolato alla cannella',1026);
INSERT INTO "ricette" VALUES (10287,'Frittedda','Contorno','Carciofi',4,' -','6 Carciofi,
500 G Piselli Freschi Sgranati,
800 G Fave Verdi Tenere,
200 G Cipolla Scalogna,
1/2 Bicchiere Aceto Di Vino,
Succo Di Limone,
100 G Olio D''oliva,
Sale,
Pepe','E'' questa una sicilianissima pietanza che non ha riscontro altrove. Può darsi, che nel nome, derivi dal latino frigere, giacché è nella grande padella che si forma questo appetitoso contorno, usato sempre più spesso nella Sicilia occidentale (dove nasce) come antipasto, durante la precoce primavera siciliana e dura finché gli ortaggi di cui si compone risultino tenerissimi, essendo ancora delle primizie. Spuntare i carciofi, tagliarli a quarti e ammollarli in acqua fredda con succo di limone. A parte lessare la cipolla al dente, e poi rosolarla nell''olio, finché diventi cremosa. A questo punto unire i carciofi, dopo averli ben sgocciolati; aggiungere olio ed unire le fave e, per ultimo, i piselli. Condire con sale, pepe e mezzo bicchiere d''aceto, continuando la cottura finché l''aceto non sia quasi del tutto evaporato. Conservare in frigo la frittedda e servirla il giorno dopo.',1842);
INSERT INTO "ricette" VALUES (10288,'Frittella Polacca','Antipasto','Formaggio',4,'Luogo: Polonia.','Per L''impasto:,
225 G Farina,
4 Uova,
30 Cl Latte,
30 Cl Acqua,
1 Cucchiaio Olio D''oliva,
1 Noce Moscata,
1 Cucchiaio Sale,
25 G Burro,
Per Il Ripieno:,
250 G Formaggio A Scaglie,
25 G Burro,
1 Tuorlo D''uovo,
Zucchero,
1 Cucchiaio Essenza Di Vaniglia','Prima fate il ripieno mescolando tutti gli ingredienti fino a formare una crema. Per le frittelle, mettete la farina in una scodella larga. Aggiungetevi tre tuorli d''uovo, latte, acqua, olio e noce moscata e mescolate insieme. In una scodella separata, sbattete il bianco delle uova con il sale. Scaldate una padella e ungetela di olio. Versatevi la pasta e cuocete per 1-2 minuti circa. Mettete poi un po'' di ripieno e piegate.',2923);
INSERT INTO "ricette" VALUES (10289,'Frittelle A Quadri','Dessert','Uvetta Sultanina',6,' -','1000 G Pasta Da Pane,
80 G Uvetta Sultanina,
70 G Frutta Candita A Dadini,
150 G Burro,
120 G Zucchero,
Zucchero A Velo,
Olio D''oliva','Lavorare la pasta con l''uvetta, la frutta candita, burro e zucchero. Stenderla con il matterello ad una altezza di 1 cm circa. Tagliare la pasta a quadri di 4 cm di lato. Lasciarli lievitare per 1 ora circa. Friggere le frittelle quadrate in olio bollente, scolarle mano a mano con la schiumarola e spolverizzarle di zucchero a velo.',4933);
INSERT INTO "ricette" VALUES (10290,'Frittelle A Spirale','Dessert','Latte',4,' -','200 G Farina,
2 Cucchiai Burro,
25 Cl Latte,
2 Uova,
2 Cl Grappa,
Sale,
Olio Per Friggere,
Per Servire:,
Zucchero A Velo,
Panna Montata (o Mirtilli Rossi O Frutta Cotta)','Salare il latte tiepido e mescolate prima la farina e dopo i rossi d''uova e la grappa. Montare il chiaro d''uova ed aggiungerlo lentamente. Una volta ottenuto l''impasto, va fritto passandolo da un imbuto e versandolo direttamente nell''olio bollente formando una spirale rotonda, grande come un piatto. Quando ha preso colore su tutte e due le parti servirla con zucchero a velo e a seconda dei gusti con panna montata, mirtilli rossi o frutta cotta.',2522);
INSERT INTO "ricette" VALUES (10291,'Frittelle Al Bacon','Antipasto','Bacon',4,' -','Pasta Per Bignè,
3 Fette Bacon,
1/2 Cucchiaio Prezzemolo Tritato,
Poco Burro,
Abbondante Olio D''oliva,
1 Puntina Senape,
1 Pizzico Pepe Nero','Preparate la pasta per bignè e tenetela da parte. In poco burro fate dorare le fette di bacon fino a renderle croccanti, poi tritatele e mescolate con il prezzemolo, un pizzico di pepe, una puntina di senape. Incorporate questo composto alla pasta per bignè. Formate tante piccole palline e friggetele in abbondante olio caldo per pochi minuti. Le frittelle devono risultare ben gonfie e dorate. Servitele ben calde',3165);
INSERT INTO "ricette" VALUES (10292,'Frittelle Al Camembert','Antipasto','Formaggio Camembert',4,'Luogo: Francia. Luogo: Normandia.','1 Formaggio Camembert,
2 Cucchiai Farina,
2 Uova,
50 G Mollica Di Pane Secco,
1 Pizzico Peperoncino Di Caienna,
Olio Per Friggere,
2 Mele','Tagliate il camembert in otto parti uguali. Grattugiate la mollica del pane. Sbattete le uova.Mescolate la farina al peperoncino di caienna. Passate ogni porzione di camembert prima nella farina, poi nell''uovo e infine nel pangrattato. Scaldate abbondante olio in una friggitrice o in una padella finché non raggiunge il calore giusto per friggere (provate a immergere un pezzettino di pane: deve venire immediatamente a galla e dorarsi in un minuto). Fate friggere le porzioni di camembert finché siano ben dorate (circa un minuto) e asciugatele con carta assorbente. Lavate le mele, tagliatele in quarti e disponetele tra le frittelle sul piatto da portate.Le frittelle devono essere servite ben calde.',1525);
INSERT INTO "ricette" VALUES (10293,'Frittelle Al Cocco','Dessert','Riso',4,' -','300 G Riso,
100 Cl Latte,
100 G Zucchero,
2 Uova,
100 G Uvetta Sultanina,
100 G Cocco Grattugiato Essiccato,
1 Pizzico Sale','Portare a ebollizione il latte con lo zucchero e un pizzico di sale, unire il riso, l''uvetta e il cocco. Cuocere a fuoco basso, mescolando, finché il latte è assorbito. Far intiepidire e unire le uova. Versare sul piano di lavoro unto d''olio e livellarlo fino a fare un quadrato alto 3 cm. Tagliare a losanghe, infarinarle e friggerle in olio bollente. Sgocciolarle sulla carta assorbente e servirle cosparse con altro cocco.',2716);
INSERT INTO "ricette" VALUES (10294,'Frittelle Al Mascarpone','Dessert','Mascarpone',4,' -','450 G Mascarpone,
200 G Uvetta Sultanina,
150 G Fecola,
2 Uova,
150 G Latte,
15 G Lievito Per Dolci,
200 G Zucchero A Velo,
1 Arancia,
Olio D''oliva','Stemperare la fecola nel latte e unire lo zucchero a velo, il succo dell''arancia e la scorza grattugiata. Sciogliere il lievito in poco latte e incorporarlo al composto insieme al mascarpone. Amalgamare bene fino ad ottenere una crema densa e senza grumi. Far riposare per 30 minuti. Scaldare abbondante olio in una padella e versarci il composto a cucchiaiate, far dorare le frittelle su tutti i lati, levarle dal fuoco, spolverizzarle di zucchero a velo e servire.',4884);
INSERT INTO "ricette" VALUES (10295,'Frittelle All''uvetta','Dessert','Uvetta Sultanina',4,' -','200 G Farina,
50 G Burro,
3 Uova,
100 G Uvetta Sultanina,
50 G Zucchero,
25 Cl Acqua,
Scorza Di Limone,
1 Cucchiaino Lievito,
Zucchero A Velo,
Olio D''oliva','In una pentola mettete il burro, aggiungete l''acqua e portate a ebollizione. Ritirate dal fuoco, versate tutta la farina, mescolate fino a quando la pasta diventa una palla ben liscia; ponete sul fuoco, incorporate zucchero, buccia di limone grattugiata e un uovo alla volta mescolando bene: la pasta deve avere una consistenza filante; fate raffreddare, aggiungete lievito e uvetta già bagnata e strizzata. Scaldate bene l''olio d''oliva e friggetevi a cucchiaiate l''impasto. Scolate e spolverate di zucchero a velo.',2503);
INSERT INTO "ricette" VALUES (10296,'Frittelle All''uvetta (2)','Dessert','Uvetta Sultanina',4,' -','1000 G Pasta Di Pane,
80 G Uvetta Sultanina,
70 G Frutta Candita Mista,
150 G Burro,
120 G Zucchero,
Olio D''oliva,
Zucchero A Velo','Impastare la pasta con l''uvetta, il burro, lo zucchero e la frutta candita tagliata a dadini. Lavorare molto bene l''impasto per amalgamare gli ingredienti. Stendere la pasta con il matterello lasciandola alta circa 1/2 cm. Tagliarla a quadrati di 3 cm di lato e farla lievitare per 1 ora. Scaldare l''olio in una padella di ferro e friggervi le frittelle. Ritirarle quando saranno ben dorate da entrambi i lati e spolverizzarle di zucchero a velo.',4933);
INSERT INTO "ricette" VALUES (10297,'Frittelle Alla Cannella','Antipasto','Cannella',4,' -','150 G Riso,
70 Cl Latte,
1 Limone,
20 G Burro,
50 G Zucchero Semolato,
40 G Farina Bianca,
2 Cucchiai Rum,
50 G Uvetta Sultanina,
Olio Di Semi,
3 Uova,
1 Cucchiaio Lievito In Polvere,
Zucchero A Velo,
Cannella In Polvere,
250 G Marmellata Di Fragole,
Curacao (o Altro Liquore All''arancia)','Sciacquare l''uvetta, trasferirla in una tazza e irrorarla con il rum. Scaldare il latte e appena bolle unire lo zucchero, mescolare e aggiungere il riso, poi far cuocere per 15 minuti, mescolando di tanto in tanto, sino a quando il latte non sarà, stato assorbito e il riso non risulterà asciutto. Spegnere e unirvi la scorza grattugiata di mezzo limone, la farina e il lievito setacciati, mescolare e incorporare le uova e l''uvetta con il rum. In una pentola far scaldare abbondante olio d''arachidi. Appena e caldo mettere a cuocere il composto di riso a cucchiaiate. Regolare la temperatura in modo che le frittelle non diventino troppo scure. Appena risultano dorate da una parte girarle e terminare la cottura. Quando saranno cotte scolarle e poggiarle su carta assorbente, spolverizzare con cannella in polvere e zucchero a velo. Accompagnare con la salsa di fragola fatta così: in tegame mettere la marmellata (anzi la confettura) con 2 cucchiaiate di acqua e 2 di liquore all''arancia, fare scaldare la salsa e metterla in coppette in modo che ogni persona possa servirsi a piacere.',3536);
INSERT INTO "ricette" VALUES (10298,'Frittelle Alla Cannella (2)','Dessert','Cannella',6,' -','500 G Farina,
150 G Zucchero,
4 Uova,
2 Bicchieri Latte,
1 Limone (scorza Grattugiata),
1 Cucchiaino Cannella In Polvere,
1 Bustina Lievito Per Dolci,
1 Presa Sale,
3 Cucchiai Zucchero A Velo,
Olio D''oliva','Unire allo zucchero le uova e montare a spuma il composto con una frusta. Unire sale, scorza di limone, cannella, latte e farina a pioggia. Mescolare ancora energicamente con la frusta e infine unire il lievito. Versare il composto a cucchiaiate nell''olio bollente. Friggere le frittelle, eliminare l''unto in eccesso e spolverizzare con zucchero a velo.',3595);
INSERT INTO "ricette" VALUES (10299,'Frittelle Alle Mele','Dessert','Mele',4,' -','2 Mele Asprigne,
1 Limone (succo),
1 Cucchiaio Rum,
30 G Zucchero Cristallino,
1 Presa Cannella,
Grasso Per Dolci,
Zucchero Vanigliato A Velo','Sbucciate le mele, estraetene il torsolo, tagliatele a fettine spesse 1 cm, impregnatele con il succo di limone e il rum e cospargetele di zucchero e cannella. Infilate le fette di mela in una pasta da dolci e friggetele a 170 gradi in abbondante grasso bollente finché diventano dorate. Fatele sgocciolare e cospargetele di zucchero vanigliato a velo. Eventualmente potete servire le frittelle guarnendole con della marmellata di albicocche o con un po'' di salsa di frutta.',954);
INSERT INTO "ricette" VALUES (10300,'Frittelle Alle Prugne Secche E Al Cioccolato','Dessert','Prugne Secche',4,' -','Pasta Per Dolci,
200 G Prugne Secche Grandi Disossate,
30 G Mandorle,
Grasso Per Dolci,
50 G Cioccolata,
20 G Zucchero A Velo','Lasciate a mollo le prugne per un periodo da 2 a 4 ore, a seconda di quanto sono secche, scolatele, farcitele con le mandorle, unitele alla pasta e friggetele a 170 gradi in abbondante grasso caldo. Scolatele, arrotolatele in cioccolata grattugiata fine mischiata con zucchero a velo e servitele. Queste frittelle sono ancora più buone se servite con una salsa alla vaniglia o dello chadeau.',1688);
INSERT INTO "ricette" VALUES (10301,'Frittelle Alle Rose','Dessert','Rose Rosa',4,' -','500 G Zucchero,
2 Vasetti Yogurth Intero,
130 G Farina,
20 G Burro,
1/2 Bustina Lievito,
50 G Uvetta Sultanina,
25 Cl Latte,
Abbondante Olio D''oliva,
3 Rose Rosa (petali),
1 Cucchiaino Sambuca','Sciogliete in mezzo litro d''acqua lo zucchero. Lasciate sobbollire cinque minuti finché il liquido diventa denso; profumate con un cucchiaino di sambuca e fate raffreddare. Setacciate la farina col lievito, stemperatela con un po'' di latte, unite burro, yogurth e il resto del latte. Con il composto fate delle polpettine e al centro mettete alcune uvette. Friggetele in una padella con abbondante olio. Scolatele su carta assorbente, immergetele nello sciroppo di zucchero, cospargetele coi petali di rosa.',3838);
INSERT INTO "ricette" VALUES (10302,'Frittelle Allo Yogurth','Dessert','Yogurth',4,' -','125 G Yogurth,
80 G Burro,
50 G Zucchero,
30 G Uvetta Sultanina,
3 Uova,
400 G Farina,
1 Bustina Lievito Vanigliato,
Cannella In Polvere,
Olio D''oliva','Ammollare l''uvetta in acqua tiepida. Lavorare a crema il burro con lo zucchero poi incorporare le uova una alla volta, lo yogurth, la farina setacciata con il lievito, la cannella e l''uvetta strizzata. Amalgamare bene gli ingredienti. Scaldare abbondante olio in una padella per fritti. Raccogliere il composto a cucchiaiate e gettarle nell''olio, dorare le frittelle da entrambi i lati, scolarle e servirle ben calde.',3264);
INSERT INTO "ricette" VALUES (10303,'Frittelle Con Fiori Di Zucchine','Dessert','Fiori Di Zucchine',4,'Preparazione: 60 minuti.','150 G Farina Bianca,
100 G Latte,
75 G Zucchero Semolato,
20 Fiori Di Zucchine Freschi,
1/2 Limone (scorza),
1 Tuorlo D''uovo,
1 Cucchiaio Olio D''oliva (o Olio Di Semi),
2 Cucchiai Acquavite (o Grappa),
1/2 Cucchiaino Lievito,
1 Pizzico Sale','Togliete ai fiori di zucchine la parte centrale e apriteli, controllando che all''interno non vi siano insetti o terriccio; passateli con un sottile telo umido e spezzettateli. Mettete in una ciotola il tuorlo e sbattetelo con lo zucchero, la scorzetta grattugiata del mezzo limone, una cucchiaiata di olio d''oliva e due cucchiaiate di Acquavite: dovete ottenere un composto liscio ed omogeneo. Unite allora il latte freddo e la farina mescolata al lievito, facendola cadere a pioggia da un setaccino; lavorate tutto bene con un cucchiaio di legna badando che non si formino dei grumi, poi unite i fiori di zucchina spezzettati, un pizzico di sale e rimescolate. Ponete sul fuoco l''apposita casseruola dei fritti con abbondante olio di semi fresco (cioè non usato per altre cotture); quando sarà ben caldo ma non bollente mettetevi una parte del composto a cucchiaiate, lasciando cuocere e dorare le frittelle sui due lati. Sgocciolatele, posatele su carta da cucina, tenetele al caldo e proseguite a cuocerne altre, sino all''esaurimento del composto. Sistemate infine le frittelle in un piatto coperto con un tovagliolini e servitele subito.',1499);
INSERT INTO "ricette" VALUES (10304,'Frittelle Con L''uvetta','Contorno','Uvetta Sultanina',4,' -','50 G Uvetta Sultanina Ammorbidita In Acqua,
25 Cl Latte,
200 G Farina,
3 Uova,
1/2 Limone (scorza Grattugiata),
Sale,
100 G Zucchero Semolato,
Olio Per Friggere','Aggiungere alla farina, poco per volta, il latte sino ad ottenere una pastella piuttosto densa ma liscia. Unire il sale, la scorza di limone, le uova (una alla volta) e l''uvetta strizzata. Scaldare l''olio e versarvi il composto a cucchiaiate. Friggere le frittelle a fuoco medio, passarle nella carta assorbente e poi nello zucchero. Servirle calde.',2266);
INSERT INTO "ricette" VALUES (10305,'Frittelle Con Marmellata Di Prugne','Dessert','Panini',4,' -','4 Panini Di Pane Bianco,
60 G Marmellata Di Prugne,
25 Cl Latte,
Zucchero Vanigliato,
1 Cucchiaio Rum,
Cannella,
2 Uova Intere,
Grasso Per Dolci,
Zucchero Vanigliato A Velo','Togliete la crosta dai panini o dalle fette di pane, tagliateli in due in senso orizzontale, spalmatevi sopra la marmellata di prugne, unite le due metà e lasciatele a mollo nel latte condito con il rum, la vaniglia e la cannella; a questo punto immergetele nelle uova sbattute e friggetele velocemente nel grasso bollente finché diventano croccanti, fate scolare il grasso superfluo e zuccherate. Queste frittelle, chiamate a Vienna ''cavalieri poveri'', possono essere appoggiate su dei pezzettini di mandorle o pistacchi. Di solito vi si aggiunge anche una salsa di frutta.',2292);
INSERT INTO "ricette" VALUES (10306,'Frittelle Del Sole','Antipasto','Mais Al Naturale',4,' -','250 G Mais Al Naturale,
2 Uova Intere,
4 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cucchiaio Farina,
1 Rametto Timo,
Olio D''oliva,
Alcuni Pomodorini,
1 Ciuffo Menta,
Sale','Eliminate dal mais il liquido di conservazione. In una insalatiera, battete le due uova con un po'' di sale. Unite, continuando a mescolare con una forchetta, il parmigiano grattugiato, la farina bianca e il timo tritato. Aggiungete il mais e lasciare riposare per 2 o 3 minuti. In una padella antiaderente mettere un filo d''olio. Versate il composto a cucchiaiate nell''olio formando frittelle di circa 5 cm di diametro. Fatele cuocere dai due lati e, appena cotte, appoggiatele su carta assorbente per farle asciugare. Guarnire con un pomodorino tagliato in due e un ciuffo di menta fresca.',1525);
INSERT INTO "ricette" VALUES (10307,'Frittelle Della Nonna','Antipasto','Uvetta Sultanina',4,' -','500 G Farina,
3 Uova,
200 G Uvetta Sultanina,
4 Cucchiai Zucchero,
80 G Burro,
2 Bicchieri Latte,
1 Bustina Lievito,
Sale,
1 Bicchierino Rum,
Olio D''oliva,
Zucchero A Velo','Ammorbidire l''uvetta sultanina per 20 minuti in acqua tiepida, asciugarla e unirla al rum. Sbattere le uova, unire lo zucchero, il sale, la farina e l''uva scolata. Aggiungere il burro fuso, il latte e il lievito. Versare il composto a cucchiai nell''olio bollente e friggere le frittelle. Una volta fredde cospargerle con lo zucchero a velo e servire.',4152);
INSERT INTO "ricette" VALUES (10308,'Frittelle Delle Langhe','Antipasto','Uova',6,'Luogo: Piemonte. Luogo: Alba. Preparazione: 30 minuti. Cottura: 6 minuti.','300 G Farina Di Grano 00,
4 Uova,
1 Bicchiere Latte,
1 Cucchiaio Lievito Naturale,
Sale,
Per Friggere:,
Olio Di Semi Di Arachidi','Sbattete i tuorli in una terrina, aggiungete il latte, dopodichè incorporate la farina delicatamente e il lievito naturale, infin