,'Versate il vino in una casseruola, unite un''arancia in cui avrete infilzato i chiodi di garofano, la cannella, la scorza e il succo di 2 arance, lo zucchero e la noce moscata grattugiata. Scaldate tutto quanto fino a che lo zucchero si sarà sciolto poi allontanate dal fuoco e lasciate in infusione per 30 minuti. Infine filtrate il vino e scaldatelo ancora. All''ebollizione unite il brandy. Guarnite con fettine di kumquat e servite ben caldo.',1734);
INSERT INTO "ricette" VALUES (27339,'Vinaigrette','Salsa','Aceto',4,' -','3 Bicchieri Olio D''oliva,
1 Bicchiere Aceto Di Vino','Versare aceto e olio in un barattolo con tappo a vite. Agitate il barattolo per mescolare gli ingredienti.',4056);
INSERT INTO "ricette" VALUES (27340,'Vinaigrette (2)','Salsa','Olio D''oliva',4,'Calorie: 130.','1 Cipolla Tritata,
2 Cetrioli Sott''aceto Tritati,
2 Cucchiai Capperi,
1 Pomodoro Senza Semi Tagliato A Cubetti,
2 Cucchiai Aceto Di Vino Bianco,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe','Mescolare bene tutti gli ingredienti. Utile per accompagnare verdura cruda o patate lesse.',427);
INSERT INTO "ricette" VALUES (27341,'Vinaigrette Alle Fragoline','Salsa','Fragoline',6,' -','250 G Fragoline Di Bosco,
6 Cucchiai Aceto Di Vino,
300 G Olio D''oliva Extra-vergine,
Sale,
Pepe','Versate in una ciotolina l''aceto e stemperatevi il sale. Unitevi poco a poco l''olio, versandolo a filo e battendo il composto con una frusta a mano. Quando tutto sarà ben emulsionato, aggiungete le fragoline, accuratamente mondate, sciacquate e asciugate con un telo pulito e assorbente. Mescolate alla vinaigrette, sempre usando la frusta, in modo che la maggior parte di esse si frantumino, unendosi all''emulsione e formando un tutt''uno con essa. Lasciate macerare per un''ora o più, quindi servite questa delicata salsa come accompagnamento a carni bianche bollite o grigliate.',2784);
INSERT INTO "ricette" VALUES (27342,'Vinaigrette Profumata','Salsa','Erba Cipollina',4,' -','2 Cucchiai Aceto Di Vino,
6 Cucchiai Olio D''oliva,
Sale Grosso,
Pepe Nero,
Abbondante Erba Cipollina','Versare in una ciotola l''aceto,unire un pizzico di sale e una macinata di pepe. Mescolare e incorporare l''olio. Battere energicamente con una forchetta per ottenere una miscela piuttosto densa e ben emulsionata, quindi profumarla con un trito di erba cipollina.',2229);
INSERT INTO "ricette" VALUES (27343,'Vinarterta','Dessert','Prugne Secche',4,' -','Per Il Fondo:,
250 G Burro,
350 G Zucchero A Velo,
2 Uova,
2 Cucchiai Yogurth Bianco Intero,
800 G Farina,
1 Bustina Lievito,
1 Fialetta Estratto Di Mandorle,
2 Cucchiaini Cardamomo In Polvere,
Per Il Ripieno:,
500 G Prugne Secche','In una casseruola portare a ebollizione il composto per il ripieno. Togliere dal fuoco e tenere al caldo. Sciogliere il burro a bagnomaria, aggiungere lo zucchero poco alla volta e le uova. Setacciate gli ingredienti asciutti e versateli nel composto. Unite estratto di mandorle e cardamomo e lo yogurth. Impastate e dividete in sei parti uguali. Sulla carta da forno tirate la pasta fino a formare un disco grande come la teglia dove cuocerete la torta (usate la teglia come stampo, così verranno della grandezza esatta). Cuocete su una teglia piatta per circa 10 minuti a 180-190 gradi. Togliere dalla piastra e far raffreddare. Farcite come se fosse un panino a più piani (disco di pasta, crema di prugne, disco di pasta, ecc). Per comprimere la torta, fate riposare con un libro appoggiato sulla superficie (usate un foglio di carta da forno per non far toccare libro e torta!). Potete far raffreddare in frigo e consumarla almeno il giorno dopo la preparazione: sarà più saporita. Servite con gelato o ciuffi di panna montata.',7132);
INSERT INTO "ricette" VALUES (27344,'Vincent','Bevande','Whisky',1,' -','1/3 Latte,
2/3 Whisky,
1 Cucchiaio Miele','Aggiungere nel mixer un cucchiaio di miele e mescolare. Servire freddo (con ghiaccio tritato) oppure caldo (aggiungendo un po'' d''acqua bollente).',286);
INSERT INTO "ricette" VALUES (27345,'Vincente','Bevande','Brandy Osborne',1,' -','2/4 Brandy Osborne,
1/4 Vermouth Bianco,
1/4 Succo D''ananas,
Alcune Gocce Bitter Campari,
Per Servire:,
1 Dadino Ananas','Si prepara nello shaker con ghiaccio cristallino e si serve nei bicchieri da cocktail ben ghiacciati guarnendo con un dadino d''ananas.',272);
INSERT INTO "ricette" VALUES (27346,'Vincisgrassi','Primo','Semolino',8,' -','500 G Farina Bianca,
300 G Semolino,
5 Uova,
300 G Regaglie Di Pollo,
200 G Cervella E Filoni,
150 G Animella,
130 G Burro,
1 Cucchiaio Olio D''oliva Extra-vergine,
100 G Grasso Di Prosciutto,
1 Carota,
1/4 Cipolla,
1/2 Bicchiere Vino Bianco Secco,
1 Bicchierino Vin Santo,
1 Cucchiaio Concentrato Di Pomodoro,
1 Bicchiere Brodo,
Latte,
6 Cucchiai Formaggio Parmigiano Grattugiato,
Per La Besciamella:,
50 G Burro,
50 G Farina,
50 Cl Latte,
Sale,
Pepe,
Noce Moscata','Vincisgrassi, così a Macerata chiamano le lasagne. Lo strano nome deriva da quello (italianizzato) di un generale austriaco che, dopo un soggiorno nelle Marche, divenne un tale estimatore della cucina di questa regione, che non volle più rinunciarvi e costrinse il suo cuoco ad ''adottarla''. Anche questo è un piatto sostanzioso che, in alcune zone, subisce leggere variazioni: per esempio animella e cervella sono spesso sostituite con polpa macinata, ma è molto diffusa anche la ricetta che prevede l''aggiunta di funghi freschi al ragù. Infine oggi, per risparmiare tempo, si sta diffondendo l''abitudine di usare lasagne di tipo tradizionale. Questa che vi proponiamo è la ricetta autentica, a voi la scelta di eventuali varianti o sostituzioni. Preparate un impasto con la farina, il semolino, 5 uova, 50 g di burro fuso, una presa di sale e il vin santo. Impastate energicamente e a lungo; quando la pasta sarà liscia e soda, stendetela in una sfoglia sottile. Ritagliate lasagne larghe 10 centimetri e lunghe quanto la teglia che dovrà contenerle. Fatele lessare come di consueto, poche alla volta, in abbondante acqua salata in ebollizione a cui avrete aggiunto un cucchiaio di olio. Scolatele ad una ad una e mettetele ad asciugare su un canovaccio inumidito. Preparate intanto il ragù. Fate un battuto fine con il grasso del prosciutto e mettetelo a rosolare in un tegame con 40 g di burro, una carota dimezzata e uno spicchio intero di cipolla. Fate imbiondire le verdure, eliminatele e aggiungete le regaglie di pollo (senza fegatini). Bagnate con il vino bianco e, appena sarà evaporato, versate il concentrato di pomodoro precedentemente diluito con un mestolo di brodo caldo. Salate e pepate, mettete il coperchio e fate cuocere un paio d''ore a fuoco dolce, mescolando con un cucchiaio di legno e incorporando di tanto in tanto un cucchiaio di latte. Nel frattempo scottate in acqua bollente salata la cervella, l''animella e i filoni, scolateli, tagliateli a dadini e incorporateli al ragù mezz''ora prima del termine della cottura. Regolate di sale. Quando il ragù è quasi cotto, unite i fegatini di pollo ridotti a pezzetti. Intanto preparate la salsa besciamella. Frullate mezzo litro di latte con 50 g di farina. Fate sciogliere 50 g di burro in una casseruola, versatevi il frullato e fate bollire la salsa per 5 minuti, mescolando continuamente con un cucchiaio di legno. Salatela, pepatela e aromatizzatela con noce moscata. Imburrate la teglia, ricoprite il fondo con le lasagne, spalmatele con un po'' di besciamella, cospargete di parmigiano, unite il ragù e qualche fiocchetto di burro; sovrapponete altre lasagne e ripetete le operazioni sino ad esaurimento degli ingredienti. Terminate con uno strato di lasagne e lasciate riposare la preparazione per 6 ore al fresco. Trascorso questo tempo, accendete il forno e, quando è ben caldo (2000), infornate le lasagne che lascerete gratinare per circa 20 minuti.',7804);
INSERT INTO "ricette" VALUES (27347,'Vincisgrassi (2)','Primo','Semolino',8,' -','Per La Pasta:,
350 G Farina,
200 G Semolino,
30 G Burro,
3 Cucchiai Vin Santo (o Vino Marsala),
3 Uova,
Sale,
Per Il Ripieno:,
200 G Rigaglie Di Pollo,
100 G Animelle,
1 Petto Di Pollo,
1 Tartufo Nero,
30 G Funghi Secchi,
1/2 Bicchiere Vino Marsala Secco,
80 G Formaggio Grattugiato,
50 G Burro,
Besciamella,
1/2 Cipolla,
Brodo,
Olio D''oliva,
Sale,
Pepe','Preparate il ripieno. Ammorbidite in acqua tiepida i funghi. Sbollentate le animelle, fatele raffreddare, tagliatele a dadini e insaporitele in un po'' di burro per pochi minuti. Tagliate il petto di pollo a striscioline. In una casseruola scaldate burro e olio, lasciatevi appassire la cipolla tritata, aggiungete i funghi a pezzetti e il tartufo (spazzolato, lavato, asciugato) a dadini, diluite con un po'' di brodo. Unite il petto di pollo facendolo colorire a fuoco vivace, poi le rigaglie e, dopo pochi minuti, il vino Marsala, abbassate la fiamma e fatene evaporare la metà. Coprite a filo con acqua calda, salate, pepate, cuocete, coperto, a fiamma dolce mezz''ora circa. Aggiungete le animelle. Fate la pasta con gli ingredienti indicati, tiratela a sfoglia, ricavatene delle strisce sottili larghe circa 10 centimetri e lunghe 50. Lessate le strisce in acqua salata, scolatele a metà cottura e tuffatele in una terrina colma d''acqua fredda, poi adagiatele ben distese su una telo bagnato e strizzato. Imburrate la teglia e disponetevi le strisce incrociandole in modo che il fondo risulti coperto e poi lasciate sporgere oltre il bordo la parte che avanza. Le altre strisce di pasta tagliatele a rettangoli. Riempite la teglia alternando strati di lasagne, ragù cosparso di formaggio grattugiato e cucchiai di besciamella. Finite con la besciamella. Ripiegate verso il centro le strisce eccedenti oltre il bordo e chiudete il pasticcio. Cuocete a bagnomaria in forno caldo a 180 gradi per mezz''ora. Vini di accompagnamento: Oltrepò Pavese Rosso DOC, Rosso Piceno DOC, Savuto DOC.',5046);
INSERT INTO "ricette" VALUES (27348,'Vinha D''alhos','Carne','Maiale',4,'Luogo: Portogallo.','1000 G Polpa Di Maiale,
25 Cl Aceto Di Vino,
2 Spicchi Aglio Schiacciato,
6 Peperoncini Piccanti Rossi,
1 Foglia Alloro,
Sale,
6 Chiodi Di Garofano,
1 Cucchiaino Timo,
Alcune Foglie Salvia,
Olio D''oliva','Tagliare la polpa di maiale a cubetti. Unire l''aceto, l''aglio il peperoncino, l''alloro, il sale, i chiodi di garofano, il timo e la salvia. Versare sulla carne e far marinare per tutta la notte in frigorifero. Cuocere il maiale nel liquido della marinata per 20 minuti e poi scolare. Scaldare l''olio in una padella, aggiungere la carne e far rosolare piano per 10 o 15 minuti, fino a far dorare la superficie.',3515);
INSERT INTO "ricette" VALUES (27349,'Vino','Bevande','Uva',4,' -','Uva','Utilizzare uva perfettamente matura e sana, pulirla, versarla nel mastello e pigiarla bene con qualsiasi mezzo pulito. Per la pigiatura usare una cassa stretta e lunga, bucherellata sul fondo e sulle pareti per far uscire il mosto appena spremuto. L''uva pigiata dev''essere messa nel tino lavato con acqua salata, sciacquato, risciacquato e fatto asciugare. Ma non riempitelo completamente, perché l''uva, fermentando, bolle e aumenta di volume. Sopra mettete una specie di reticolato di legno, mantenuto fermo da tre o quattro grosse pietre il quale serve per impedire che, durante la fermentazione, venga alla superficie il cosiddetto cappello del mosto, formato dalle vinacce. Il tino, pieno d''uva pigiata, deve rimanere in un ambiente dalla temperatura di 18-20 gradi, altrimenti la fermentazione non avviene. L''ambiente dev''essere anche perfettamente aerato, perché le esalazioni che emana l''uva in via di fermentazione possono essere molto pericolose. Finita la fermentazione (ve ne accorgerete dall''odore diverso e dal fatto che cessa il ronzio dell''ebollizione), si spilla il vino, facendolo uscire da un foro che si trova sul fondo del tino, e chiuso da uno zipolo che funziona da rubinetto. Il vino spillato va raccolto in fusti precedentemente ben lavati con molta acqua. Dopo aver spillato il primo vino, nel tino rimangono ancora le vinacce che trattengono altro liquido, quasi la metà di quello spillato. Per recuperarlo, sarebbe necessario poterlo torchiare, oppure si può ripiegare su un metodo più semplice. Aprite lo zipolo che si trova sul fondo del tino, e ogni quarto d''ora innaffiate con un innaffiatoio, per distribuire l''acqua in modo uniforme. Quest''operazione dev''essere molto lenta, affinché l''acqua impregni bene tutte le vinacce. Dal foro del tino deve uscire il vino rimasto, perché l''acqua sposta le vinacce, spingendo il vino verso l''uscita. Il liquido che zampilla attraverso lo zipolo ha stesso colore e sapore del vino già uscito. Non appena vi accorgerete che il che esce dal tino tende a diventare sempre più chiaro, sospendete l''innaffiatura. Con le vinacce sbriciolate (dopo 1 settimana di macerazione) si può ottenere il vinello, leggermente acidulo e poco alcolico, da consumare subito. Per l''imbottigliamento sono da preferirsi le bottiglie di vetro scuro che debbono essere pulite e asciutte. Si riempiono a metà d''acqua calda soda, si scuotono bene, introducendovi la spazzola lunga e stretta, si sciacquano con acqua pura e si lasciano scolare capovolte. I tappi debbono essere nuovi, di sughero morbido, non macchiato. Mai adoperare turaccioli vecchi che possono essere bucati e allora il vino si trasforma in aceto per colpa di quel filo d''aria che filtra attraverso i buchi. Oppure, i tappi usati, che hanno già subito l''azione dell''umidità, possono dare al vino un gusto di turacciolo ammuffito, molto sgradevole. Il vino può diventare aceto se: la cantina supera di 12 gradi di temperatura; il vino non ha almeno 9 gradi. Se il vino ha già sapore di aceto bruciare nel fusto dello zolfo. Per vini diventati filanti (trasparenti) mettere 1 bicchiere di alcool per ogni 100 litri di vino. Per vini torbidi o dal colore comunque alterato usare 6-8 g di bisolfito di potassa per ogni 100 litri di vino. Per correggere sapori di muffa e guasto usare farina di senape sciolta in acqua bollente: dopo 30 minuti togliere l''acqua, unire un po'' di vino genuino e versare la pappetta nei fusti (10-15 g per ogni 100 litri di vino) e mescolare parecchie volte. Infine si consiglia di mantenere nelle botti un giusto livello, aggiungendo il vino necessario (in 1 anno una botte di 225 litri perde per evaporazione 13-15 litri il primo anno, 8-10 litri all''anno in seguito).',54);
INSERT INTO "ricette" VALUES (27350,'Vino Al Ginseng','Bevande','Vino Bianco',4,' -','200 Cl Vino Bianco Secco,
100 G Ginseng,
60 G Vaniglia,
60 G Cannella,
60 G Rabarbaro','Fate macerare tutti gli ingredienti nel vino bianco per almeno 20 giorni, avendo cura di agitare con un mestolo almeno una volta al giorno. Trascorso questo tempo filtrate il tutto attraverso un colino ed imbottigliate.',1866);
INSERT INTO "ricette" VALUES (27351,'Vino All''arancia','Bevande','Vino Bianco',4,' -','200 Cl Vino Bianco Secco,
1 Bicchiere Brandy,
2 Arance,
1 Limone,
Chiodi Di Garofano,
100 G Zucchero','Lavate bene gli agrumi e tagliateli a fettine con tutte le bucce. In una caraffa mescolate lo zucchero col brandy, fatelo sciogliere e poi aggiungete il vino con le arance e il limone tagliati a fettine. Mescolate bene e tenete in frigo qualche ora prima di servirlo in tavola come aperitivo.',2408);
INSERT INTO "ricette" VALUES (27352,'Vino Alle Mele','Bevande','Mele',8,' -','20000 G Mele','Lavate e sbucciate le mele. Tagliatele a pezzi e ponetele in un grosso recipiente e spappolatele con un pestello di legno. Coprite con un panno e lasciate fermentare per 6 giorni. Dopo travasate il liquido in un altro recipiente e fate continuare a fermentare per due mesi. Ora potete filtrare, facendo attenzione a non smuovere il fondo che si è formato, ed imbottigliare.',9000);
INSERT INTO "ricette" VALUES (27353,'Vino Aromatico','Bevande','Vino',4,' -','100 Cl Vino Rosso,
3 G Chiodi Di Garofano,
3 G Coriandolo,
7 Stecche Cannella,
1 G Vaniglia,
1 Foglia Alloro,
4 Foglie Salvia,
100 G Zucchero Di Canna','Si lasciano macerare le droghe nel vino per 12 ore in un recipiente coperto, poi si fa bollire sino a ridurlo di un terzo. Si serve bollente. E'' frequente la correzione con un goccio di Brandy al momento di servire per rinforzare alcolicamente il gusto.',1334);
INSERT INTO "ricette" VALUES (27354,'Vino Aromatizzato Alla Genziana','Bevande','Genziana',1,' -','Genziana Amabile (v. Ricetta),
100 Cl Vino Bianco,
1 Chiodo Di Garofano,
6 Bacche Ginepro,
1 Stecca Cannella,
500 G Zucchero,
300 Cl Vino Bianco Amabile,
Alcool','Preparare la ''Genziana amabile'' (vedi ricetta), quindi recuperare le radici (ormai morbide), tagliuzzarle e metterle in infusione in 1 litro di vino bianco unitamente ad 1 chiodo di garofano, 6 bacche di ginepro (biennali, ossia di colore nero e rugose al tatto) e 1 stecca di cannella. Quanto precede per 40 giorni. Decantare nuovamente ed aggiungere 500 g di zucchero e 2-3 litri (secondo il gusto) di vino bianco amabile. Aggiungere alcool. Ripetere quanto precede per 3 volte ancora. Secondo il gusto sia l''alcool che lo zucchero possono essere variati.',5177);
INSERT INTO "ricette" VALUES (27355,'Vino Bianco Aromatizzato','Bevande','Vino Bianco',4,' -','1 Pezzo Scorza Di Cetriolo,
1 Arancia (scorza),
1 Pizzico Borraggine Fresca Tritata,
2 Zollette Zucchero,
1 Bicchierino Brandy,
1 Bottiglia Vino Bianco Secco,
1 Bicchiere Soda O Acqua Di Seltz','Versare in una brocca di vetro il pezzo di buccia di cetriolo, la buccia dell''arancia, il pizzico di borraggine fresca tritata, le zollette di zucchero e il bicchierino di brandy. Lasciar macerare il tutto a temperatura ambiente per 30 minuti e quindi aggiungere una bottiglia di vino bianco secco e un bicchiere di soda o acqua di seltz. Rimescolare bene finché lo zucchero sarà completamente sciolto e mettere la brocca in frigorifero per almeno due ore prima di servire.',988);
INSERT INTO "ricette" VALUES (27356,'Vino Brulè','Bevande','Vino Rosso',4,' -','100 Cl Vino Rosso,
100 G Zucchero,
Alcuni Chiodi Di Garofano,
1/4 Noce Moscata,
1 Pezzetto Cannella,
1 Scorza Di Limone','Mettere al fuoco una casseruola con 1 litro di buon vino rosso, 100 g di zucchero, alcuni chiodi di garofano, un quarto di noce moscata, un pezzetto di cannella e la buccia tagliata sottile a nastro di un limone. Fare bollire e, quando lo zucchero sarà completamente sciolto, levare dal fuoco; passare attraverso una tela bagnata e strizzata e servire ben caldo.',1173);
INSERT INTO "ricette" VALUES (27357,'Vino Caldo Alla Frutta','Dessert','Albicocche',6,' -','6 Albicocche Secche,
6 Prugne Secche Senza Nocciolo,
30 G Uvetta Sultanina,
1 Bottiglia Vino Rosso (barbera),
1 Stecca Cannella,
2 Chiodi Di Garofano,
1 Pezzetto Scorza Di Limone,
2 Cucchiai Zucchero','Fate scaldare il vino con la stecca di cannella, i chiodi di garofano e la scorza di limone. Quando inizia a bollire, aggiungete la frutta secca e l''uvetta; spegnete il fuoco e lasciate riposare coperto per 2 ore. La frutta dovrà risultare morbida e leggermente gonfia. Al momento di servire riscaldate il vino e la frutta e suddividete in bicchieri caldi.',1535);
INSERT INTO "ricette" VALUES (27358,'Vino Caldo Con Frutta','Dessert','Vino Rosso',6,' -','1 Bottiglia Vino Rosso,
1 Stecca Cannella,
2 Chiodi Di Garofano,
1 Pezzetto Scorza Di Limone,
2 Cucchiai Zucchero,
6 Albicocche Secche,
6 Prugne Secche Senza Nocciolo,
30 G Uvetta Sultanina','Scaldare il vino con la cannella, i chiodi di garofano e la scorza di limone. Quando inizia a bollire unire la frutta secca e l''uvetta, spegnere il fuoco e far riposare coperto per 2 ore. La frutta dovrà risultare morbida e leggermente gonfia. Al momento di servire riscaldare e suddividere in bicchieri caldi.',1535);
INSERT INTO "ricette" VALUES (27359,'Vino Cotto','Bevande','Mosto Di Vino Rosso',1,'Luogo: Emilia-Romagna. Luogo: Lombardia.','Mosto Di Vino Rosso','E'' uno sciroppo d''uva, specialità emiliana e della bassa lombarda, che viene usato per preparare deliziose bibite. Mettete del mosto di vino rosso, appena fatto, in una casseruola (in Emilia usano il paiolo di rame non stagnato), ponete il recipiente sul fuoco e, appena il mosto inizia a bollire, abbassate la fiamma. Lasciate cuocere, mescolando spessissimo, sino a che nel recipiente sarà rimasto circa un terzo del liquido iniziale. Lasciatelo raffreddare, quindi versatelo in bottiglie da vino pulitissime, tappatele molto bene e conservatele. Il vino cotto si manterrà per moltissimi mesi, anche per qualche anno.',75);
INSERT INTO "ricette" VALUES (27360,'Vino Di Acacia','Bevande','Acacia',4,' -','20 G Acacia (fiori Essiccati),
100 Cl Vino Rosso','Lasciare i fiori nel vino bollente per 15 minuti. Utile per curare l''anemia.',753);
INSERT INTO "ricette" VALUES (27361,'Vino Di Artemisia','Bevande','Artemisia',1,' -','50 G Sommità Fiorite Di Artemisia,
100 Cl Vino','Far macerare le sommità fiorite nel vino per 30 giorni. Utile per risvegliare l''appetito (1 bicchierino prima dei pasti).',760);
INSERT INTO "ricette" VALUES (27362,'Vino Di Assenzio','Bevande','Assenzio',1,' -','40 G Foglie E Fiori Essiccati Di Assenzio,
60 G Acquavite Di 28 Gradi,
100 Cl Vino Bianco','Macerare le foglie e i fiori nell''acquavite per una settimana. Aggiungere il vino bianco e far riposare per una settimana. Filtrare e versare in una bottiglia. Utile per curare l''anoressia (1 bicchierino prima dei pasti).',803);
INSERT INTO "ricette" VALUES (27363,'Vino Di Camedrio','Bevande','Camedrio',1,' -','40 G Sommità Fiorite Essiccate Di Camedrio,
100 Cl Vino','Lasciare le sommità fiorite nel vino bollente per 15 minuti. Conservare in flacone ben chiuso. Utile per curare l''anoressia (1 bicchierino prima dei pasti).',758);
INSERT INTO "ricette" VALUES (27364,'Vino Di Camomilla Romana','Bevande','Camomilla Romana',1,' -','50 G Fiori Di Camomilla Romana,
100 Cl Vino','Macerare i fiori nel vino per 30 giorni. Filtrare. Utile per curare l''anoressia (1 bicchierino prima dei pasti).',760);
INSERT INTO "ricette" VALUES (27365,'Vino Di Capperi','Bevande','Capperi',1,' -','40 G Scorza Di Radici Secche Di Capperi,
80 G Corteccia Di Frassino,
100 Cl Vino Rosso','Macerare la scorza di radici con la corteccia nel vino rosso per 4 giorni. Filtrare. Utile per curare l''anoressia (1 bicchierino due volte al giorno).',774);
INSERT INTO "ricette" VALUES (27366,'Vino Di Cardo Mariano','Bevande','Cardo Mariano',1,' -','30 G Foglie E Radici Di Cardo Mariano,
100 Cl Vino Rosso','Lasciare foglie e radici nel vino rosso bollente per 30 minuti. Fare raffreddare. Un bicchiere piccolo prima dei pasti. Utile per risvegliare l''appetito.',760);
INSERT INTO "ricette" VALUES (27367,'Vino Di Cardo Santo','Bevande','Cardo Santo',1,' -','30 G Sommità Fiorite Di Cardo Santo,
100 Cl Vino','Lasciare le sommità fiorite nel vino rosso bollente. Un bicchierino prima di uno dei pasti principali. Utile per risvegliare l''appetito.',760);
INSERT INTO "ricette" VALUES (27368,'Vino Di Centaurea Minore','Bevande','Centaurea Minore',1,' -','30 G Sommità Fiorite Secche Di Centaurea Minore,
100 Cl Vino','Lasciare le sommità fiorite nel vino rosso bollente per 30 minuti. Filtrare e conservare in una bottiglia nel chiusa. Un bicchierino prima dei pasti. Utile per risvegliare l''appetito.',760);
INSERT INTO "ricette" VALUES (27369,'Vino Di Cotogna','Bevande','Mela Cotogna',4,' -','100 G Mela Cotogna (polpa In Pezzetti),
100 Cl Vino','Mettere la polpa nel vino e lasciar macerare per almeno 10 giorni. Filtrare. Utile per curare infiammazioni alla gola.',775);
INSERT INTO "ricette" VALUES (27370,'Vino Di Finocchio Selvatico','Bevande','Finocchio Selvatico',4,' -','30 G Semi Di Finocchio Selvatico,
100 Cl Vino Rosso','Macerare 30 g di semi di finocchio selvatico in 1 litro di buon vino rosso per 2 settimane. Filtrare. E'' un utile energetico (dose consigliata: 2 bicchierini al giorno).',755);
INSERT INTO "ricette" VALUES (27371,'Vino Di Frassinella','Bevande','Frassinella',4,' -','40 G Frassinella (scorza Della Radice),
100 Cl Vino','Bollire la scorza nel vino per 5 minuti. Lasciare in infusione per 15 minuti e poi filtrare. Utile per curare l''anemia.',760);
INSERT INTO "ricette" VALUES (27372,'Vino Di Genziana Maggiore','Bevande','Genziana',4,' -','30 G Genziana Maggiore (radice Secca),
100 Cl Vino Bianco','Lasciare la radice nel vino per 10 giorni, quindi filtrare. Utile per curare l''anemia.',756);
INSERT INTO "ricette" VALUES (27373,'Vino Di Genziana Minore','Bevande','Genziana Minore',1,' -','40 G Radici Essiccate Spezzettate Di Genziana Minore,
100 Cl Vino Bianco','Macerare le radici nel vino per 12 giorni. Filtrare e conservare in un flacone ben chiuso. Un bicchiere prima dei pasti. Utile per risvegliare l''appetito.',762);
INSERT INTO "ricette" VALUES (27374,'Vino Di Ginepro','Bevande','Ginepro',4,' -','50 G Bacche Di Ginepro,
10 G Scorza Di Limone (parte Gialla),
100 Cl Vino Bianco','Unire 50 g di bacche di ginepro a 10 g di buccia di limone (solo la parte gialla); pestare la miscela e versarla in 100 cl di vino bianco, lasciando in infusione per circa una settimana. Filtrare e conservare in una bottiglia ben chiusa. Consumato alla dose di 3 bicchierini durante la giornata, è un eccellente diuretico. Negli attacchi di asma, alla dose di 2 bicchierini al giorno, è un buon coadiuvante.',761);
INSERT INTO "ricette" VALUES (27375,'Vino Di Ginepro (2)','Bevande','Ginepro',1,' -','1000 G Bacche Di Ginepro,
2000 Cl Acqua','Far macerare e lasciar fermentare le bacche nell''acqua in un barilotto per 1 mese, quindi spillare e conservare in bottiglia ben chiusa. Un bicchiere prima dei pasti. Utile per risvegliare l''appetito.',201);
INSERT INTO "ricette" VALUES (27376,'Vino Di Lamponi','Bevande','Vino Rosso',4,' -','100 Cl Vino Rosso,
800 G Zucchero,
1000 G Lamponi','Lavate con cura i lamponi, passateli al setaccio e poneteli in una casseruola. Versatevi il vino e portate ad ebollizione, poi fate cuocere un''oretta dopodichè mettete in un luogo fresco per 48 ore. Trascorsi questi due giorni filtrate, aggiungete lo zucchero e sulla fiamma media fate bollire per 20-30 minuti mescolando continuamente. Fate intiepidire e filtrate di nuovo, imbottigliate e conservate in un luogo fresco. Lo potrete gustare già da subito come aperitivo o per accompagnare i dessert.',4186);
INSERT INTO "ricette" VALUES (27377,'Vino Di Liquirizia','Bevande','Liquirizia',4,' -','100 G Liquirizia (radice A Pezzetti),
100 Cl Vino Bianco','Far macerare la liquirizia nel vino bianco per 10 giorni. Utile per migliorare l''alito.',770);
INSERT INTO "ricette" VALUES (27378,'Vino Di Marrubio','Bevande','Marrubio',1,' -','50 G Sommità Fiorite E Foglie Essiccate Di Marrubio,
100 Cl Vino Bianco','Macerare le sommità e le foglie nel vino per 15 giorni. Filtrare. Un bicchierino prima dei pasti principali. Utile per risvegliare l''appetito.',765);
INSERT INTO "ricette" VALUES (27379,'Vino Di Melissa','Bevande','Melissa',4,' -','20 G Melissa (foglie E Fiori),
100 Cl Vino Bianco','Bollire le foglie e i fiori nel vino per 10 minuti, quindi lasciare raffreddare e filtrare. Utile per curare l''anemia.',753);
INSERT INTO "ricette" VALUES (27380,'Vino Di Melissa (2)','Bevande','Melissa',4,' -','20 G Sommità Fiorite Di Melissa,
100 Cl Vino Bianco','Bollire le sommità nel vino per 3 minuti. 3 cucchiai da tavola 3 volte al giorno. Utile per risvegliare l''appetito.',756);
INSERT INTO "ricette" VALUES (27381,'Vino Di Pervinca','Bevande','Pervinca',4,' -','50 G Foglie Secche Di Pervinca,
20 G Fiori Di Camomilla Romana,
100 Cl Vino Rosso','Macerare le foglie con i fiori nel vino per 10 giorni. Filtrare. Un bicchierino prima dei pasti. Utile per risvegliare l''appetito.',771);
INSERT INTO "ricette" VALUES (27382,'Vino Di Rabarbaro','Bevande','Rabarbaro',1,' -','100 G Radici Secche Di Rabarbaro,
100 Cl Acquavite Di 28 Gradi,
100 G Zucchero,
10 G Buccia D''arancia,
100 Cl Vino Rosso','Macerare le radici nell''acquavite per 8 giorni. A parte preparare lo zucchero e la buccia d''arancia nel vino. Mescolare i due preparati, togliere la buccia d''arancia, far riposare per 8 giorni, filtrare e conservare in bottiglia ben chiusa. Un bicchierino prima dei pasti. Utile per risvegliare l''appetito.',1251);
INSERT INTO "ricette" VALUES (27383,'Vino Di Ribes Rosso','Bevande','Ribes Rosso',1,' -','100 G Germogli Di Ribes Rosso,
100 Cl Vino','Lasciare i germogli nel vino bollente per 20 minuti. Filtrare. Un bicchiere prima dei pasti. Utile per risvegliare l''appetito.',800);
INSERT INTO "ricette" VALUES (27384,'Vino Di Trifoglio Fibrino','Bevande','Trifoglio Fibrino',1,' -','10 G Foglie Fresche Di Trifoglio Fibrino,
100 Cl Vino Rosso','Lasciare le foglie nel vino bollente per 10 minuti. 2 cucchiai prima dei pasti. Utile per risvegliare l''appetito.',752);
INSERT INTO "ricette" VALUES (27385,'Vino Digestivo','Bevande','Vino Bianco',4,' -','200 Cl Vino Bianco Secco,
100 G Semi Di Anice,
100 G Semi Di Finocchio,
30 G Ruta','Ponete le spezie a macerare nel vino, in un recipiente coperto da un panno, per circa 15 giorni in un luogo aerato. Mescolate ogni tanto con un cucchiaio di legno. Trascorso questo tempo filtrate il liquido ed imbottigliate.',1538);
INSERT INTO "ricette" VALUES (27386,'Vino Medicinale','Bevande','Vino Bianco Secco',4,' -','50 G Fiori Di Camomilla,
50 Cl Vino Bianco Secco','Mettete in un vaso di vetro i fiori di camomilla e coprite con il vino. Lasciate a macerare per 5 giorni, filtrate e utilizzate all''occorrenza. Utile contro la cattiva digestione.',385);
INSERT INTO "ricette" VALUES (27387,'Vino Medicinale (10)','Bevande','Vino Marsala',4,' -','25 G Bulbi Di Colchico,
15 G Foglie Di Frassino,
25 G Fiori Di Spirea,
5 G Foglie Di Issopo,
50 Cl Vino Marsala','Mettete in un vaso di vetro i primi 4 ingredienti. Coprite con 50 cl di vino marsala e lasciate macerare per 10 giorni, quindi filtrate. Utile contro i reumatismi: 1 bicchierino al giorno.',585);
INSERT INTO "ricette" VALUES (27388,'Vino Medicinale (11)','Bevande','Vino Rosso Corposo',4,' -','6 Cucchiaini Chiodi Di Garofano,
50 Cl Vino Rosso Corposo','Mettete in un vaso i chiodi di garofano, coprite con il vino e lasciate macerare per mezza giornata. Filtrate. Utile contro l''insensibilità sessuale: 1 bicchierino dopo i pasti.',393);
INSERT INTO "ricette" VALUES (27389,'Vino Medicinale (12)','Bevande','Vino Marsala',4,' -','25 G Radici Di Galanga,
15 G Foglie Di Damiana,
25 G Semi Di Coriandolo,
50 Cl Vino Marsala','Mettete a macerare i primi 3 ingredienti nel vino. Dopo 10 giorni filtrate. Utile contro l''insensibilità sessuale: 1 bicchierino dopo i pasti.',584);
INSERT INTO "ricette" VALUES (27390,'Vino Medicinale (13)','Bevande','Vermouth Bianco',4,' -','300 G Vermouth Bianco,
100 G Essenza Di Bardana','Mettete in un vaso di vetro il vermouth e l''essenza di bardana, tappate e lasciate macerare per 1 settimana. Utile contro l''acne: 1 bicchierino ogni giorno.',580);
INSERT INTO "ricette" VALUES (27391,'Vino Medicinale (14)','Bevande','Vermouth Rosso',4,' -','300 G Vermouth Rosso,
100 G Essenza Di Bardana','Mettete in un vaso di vetro il vermouth e l''essenza di bardana, tappate e lasciate macerare per 1 settimana. Utile contro l''acne: 1 bicchierino ogni giorno.',580);
INSERT INTO "ricette" VALUES (27392,'Vino Medicinale (15)','Bevande','Vino Bianco Secco',4,' -','100 Cl Vino Bianco Secco,
100 G Aglio Tagliato A Pezzetti,
Alcuni Fiori Di Assenzio','Utile contro i parassiti intestinali. Mettete gli ingredienti in un vaso di vetro. Lasciate macerare per 2 settimane, poi filtrate e bevetene 1 bicchierino ogni mattina, a digiuno. Il gusto è abbastanza intenso, ma l''efficacia è assicurata.',878);
INSERT INTO "ricette" VALUES (27393,'Vino Medicinale (2)','Bevande','Vino Rosso',4,' -','45 G Radici Di Genzianella,
100 Cl Alcool A 60 Gradi,
2 Bottiglie Vino Rosso','Macerate le radici nell''alcool per un giorno intero, quindi aggiungete il vino e attendete 2 settimane di macerazione. Infine filtrate. Utile contro la cattiva digestione.',3115);
INSERT INTO "ricette" VALUES (27394,'Vino Medicinale (3)','Bevande','Vino Marsala',4,' -','50 Cl Vino Marsala,
25 G Essenza Di Rabarbaro,
25 G Essenza Di Arancio Amaro','Mescolate gli ingredienti. Dopo 5 giorni di riposo filtrate e bevetene 1 bicchierino dopo i pasti. Utile contro il mal di fegato.',630);
INSERT INTO "ricette" VALUES (27395,'Vino Medicinale (4)','Bevande','Vino Marsala',4,' -','50 Cl Vino Marsala,
15 G Essenza Di Melissa,
10 G Essenza Di China,
10 G Essenza Di Insalata Valeriana,
10 G Essenza Di Rabarbaro','Sciogliete le essenze nel vino. Utilizzate subito questo vino medicinale, prima dei pasti. Utile contro la gastrite.',624);
INSERT INTO "ricette" VALUES (27396,'Vino Medicinale (5)','Bevande','Vino Rosso Corposo',4,' -','500 G Bacche Di Sambuco,
50 Cl Vino Rosso Corposo,
250 G Zucchero','Mettete in un vaso di vetro le bacche, coprendole con il vino. Lasciate riposare una notte intera. Quindi aggiungete lo zucchero e fate scaldare a fuoco basso. Infine filtrate, imbottigliate e lasciate ancora una settimana. Utile contro la gastrite.',1455);
INSERT INTO "ricette" VALUES (27397,'Vino Medicinale (6)','Bevande','Vino Bianco Secco',4,' -','10 Foglie Carciofo,
50 Cl Vino Bianco Secco','Mettete in un vaso di vetro le foglie e il vino. Dopo 5 giorni filtrate e prendetene due cucchiaini prima dei pasti. Utile contro la ritenzione idrica.',400);
INSERT INTO "ricette" VALUES (27398,'Vino Medicinale (7)','Bevande','Vino Bianco Secco',4,' -','100 Cl Vino Bianco Secco,
50 G Rosmarino','Bollite il vino e il rosmarino per pochi minuti. Filtrate e imbottigliate. Utile contro la ritenzione idrica: bevetene due cucchiaini ogni mattina a stomaco vuoto.',760);
INSERT INTO "ricette" VALUES (27399,'Vino Medicinale (8)','Bevande','Vino Bianco Secco',4,' -','100 Cl Vino Bianco Secco,
250 G Essenza Di Cascara Sagrada,
60 G Essenza Di Arancio Amaro','Mescolate gli ingredienti. Dopo 5 giorni di riposo filtrate. Utile contro la stitichezza: 1 cucchiaio mattina e sera.',1120);
INSERT INTO "ricette" VALUES (27400,'Vino Medicinale (9)','Bevande','Vino Bianco',1,' -','40 G Foglie Di Ippocatano Essiccate,
50 Cl Vino Bianco','Mettete in un vaso di vetro le foglie e il vino e lasciate macerare per un giorno. Quindi filtrate. Utile contro le emorroidi: 1 bicchiere al giorno',381);
INSERT INTO "ricette" VALUES (27401,'Vino Santo','Bevande','Vino Marsala',4,' -','300 Cl Vino Marsala,
50 G Genziana,
150 G Melissa,
60 G Rabarbaro','Ponete le spezie a macerare nel marsala, in un recipiente ampio, coperto da un panno, per circa 20-30 giorni in un luogo fresco e ben aerato. Mescolate un paio di volte al giorno con un cucchiaio di legno. Trascorso questo tempo filtrate il liquido ed imbottigliate. Questo vino è ideale per accompagnare un dessert.',3461);
INSERT INTO "ricette" VALUES (27402,'Violino Notturno','Bevande','Vermouth Rosso',1,' -','2/10 Apricot Brandy Marie Brizard,
6/10 Southern Comfort,
2/10 Vermouth Rosso Martini,
Per Guarnire:,
Alcune Ciliegine Rosse','Si prepara nel mixing glass con cubetti di ghiaccio. Mescolare delicatamente e servire nella coppetta da cocktail ben fredda. Guarnire con ciliegine rosse.',324);
INSERT INTO "ricette" VALUES (27403,'Vip','Bevande','Gin',1,' -','3/10 Bitter Campari,
4/10 Tanqueray Gin,
3/10 Vermouth Cinzano Dry','Si prepara nel mixing glass con abbondante ghiaccio. Mescolare delicatamente e servire nella coppetta da cocktail ben fredda.',230);
INSERT INTO "ricette" VALUES (27404,'Vip (2)','Bevande','Gin',1,' -','2/8 Succo D''ananas,
1/8 Succo Di Limone,
1/8 Vermouth Dry,
2/8 Gin,
2/8 Rum,
Per Servire:,
1 Fetta Limone,
1 Cubetto Ananas','Scuotere a lungo nello shaker con poco ghiaccio tritato. Servire nel calice panciuto, con una fettina di limone e un cubetto di ananas.',234);
INSERT INTO "ricette" VALUES (27405,'Vip Punch','Bevande','Vino Bianco',1,' -','3/6 Vino Bianco,
1/6 Vino Champagne,
1/6 Triple Sec,
1/6 Kirsch,
Per Decorare:,
Alcune Fragole','Mescolare dolcemente nella bowl con molto ghiaccio in cubetti. Servire nel cup decorando con fragole.',166);
INSERT INTO "ricette" VALUES (27406,'Virgin','Bevande','Gin',1,' -','1/4 Succo Di Pompelmo,
1/4 Crema Di Menta Bianca,
2/4 Gin,
Per Servire:,
1 Fetta Pompelmo,
Alcune Foglie Insalata Verde','Agitare a lungo nel mixer. Servire nel calice ampio, con una fetta di pompelmo e foglie di insalata verde.',286);
INSERT INTO "ricette" VALUES (27407,'Virgoletta','Bevande','Succo D''ananas',1,' -','3 G Angostura,
2/10 Aperol,
2/10 Tanqueray Gin,
6/10 Succo D''ananas,
Per Guarnire:,
1 Fetta Ananas','Si prepara direttamente nel bicchiere tumbler con ghiaccio. Mescolare delicatamente e guarnire con una fetta d''ananas e cannucce.',207);
INSERT INTO "ricette" VALUES (27408,'Virtual','Bevande','Vodka',1,' -','2 G Fragola Drink Boero,
3/10 Succo D''arancia,
3/10 Succo Di Pompelmo,
4/10 Vodka Smirnoff,
Per Guarnire:,
1 Fetta Arancia,
1 Ciliegina Verde','Si prepara direttamente nel bicchiere tumbler con ghiaccio versando gli ingredienti nell''ordine. Mescolare delicatamente. Guarnire con una fetta d''arancia, una ciliegina verde e cannucce.',242);
INSERT INTO "ricette" VALUES (27409,'Viscottu Alla Caponata','Primo','Pomodori',4,'Luogo: Calabria.','4 Biscotti Di Farina Integrale,
300 G Passato Di Pomodoro Crudo,
16 Pomodori,
1 Peperoncino Rosso Piccante,
1 Cucchiaio Basilico Tritato,
Origano,
Sale,
Abbondante Olio D''oliva Extra-vergine','Inzuppate i biscotti in passato di pomodori, mettetevi sopra pomodori in pezzetti, peperoncino tagliuzzato, basilico tritato, origano e sale. Condite con abbondante olio d''oliva.',1342);
INSERT INTO "ricette" VALUES (27410,'Vispa Teresa','Bevande','Passoa',1,' -','4/10 Passoa,
4/10 Vodka Smirnoff,
1/10 Vermouth Martini Dry,
1/10 Succo Di Limone,
Per Guarnire:,
1 Pallina Avocado','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una pallina d''avocado sul bordo del bicchiere.',382);
INSERT INTO "ricette" VALUES (27411,'Vitalità','Bevande','Cognac',1,' -','2/6 Bitter All''arancia,
1/6 Cherry Brandy,
1/6 Vodka,
2/6 Cognac,
Per Servire:,
1 Spruzzo Succo Di Pomodoro','Scuotere con poco ghiaccio tritato nello shaker. Servire nel calice ampio, con uno spruzzo di succo di pomodoro.',275);
INSERT INTO "ricette" VALUES (27412,'Vitalità (2)','Bevande','Vodka',1,' -','6 Cubetti Ghiaccio,
5 Cucchiai Vodka,
1 Cucchiaino Martini Dry,
1 Cucchiaino Curacao Blu,
1 Spruzzo Cointreau','Questo short drink va preparato nel mixing-glass, in precedenza ben gelato. Mettete nel bicchiere miscelatore i cubetti di ghiaccio e unite, nell''ordine, gli altri ingredienti. Mescolate il cocktail per alcuni secondi e versatelo in una coppetta, filtrandolo attraverso il colino da bar (strainer).',697);
INSERT INTO "ricette" VALUES (27413,'Vitel Tonné','Carne','Vitello',10,'Luogo: Piemonte. Luogo: Alba. Preparazione: 15 minuti. Cottura: 90 minuti.','1000 G Rotonda Di Vitello,
50 Cl Aceto Di Vino Bianco,
1 Cipolla,
6 Chiodi Di Garofano,
5 Grani Pepe Nero,
1 Pezzo Cannella,
Alcune Foglie Alloro,
Sale,
10 Acciughe Sotto Sale,
2 Noci Burro,
3 Tuorli D''uovo Sodo,
10 Capperi Sotto Sale','Prendete la rotonda della coscia o girello di un vitello di fassone, mettetelo in una terrina e copritelo con aceto ed acqua (mezzo litro di aceto bianco dovrebbe bastare), aggiungete la cipolla affettata grossolanamente, i chiodi di garofano, il pepe nero, la cannella, l''alloro e il sale. Lasciate la carne a macerare nella marinata almeno 12 ore, ovvero una notte. Adesso fate brasare il girello: prendete una casseruola, fatevi sciogliere due noci di burro e poi disponete la carne ben sgocciolata e fatela rosolare un po'' affinché faccia una sottile crosta. A questo punto aggiungete le acciughe dissalate e diliscate e fatele sciogliere nel burro, quindi versate nell''intingolo il tuorlo d''uovo sodo sbriciolato. Rimestate e aggiungete subito la marinata. Fate cuocere a casseruola scoperta fino a quando il sugo si è ben ristretto. La cottura, comunque, non deve essere troppo prolungata, altrimenti la carne, quando sarà servita fredda e a fette, apparirà asciutta e prosciugata dei suoi umori. Togliete la carne e affettatela non troppo sottilmente, versate sopra le fette il fondo di cottura dopo averlo passato al setaccio e guarnito coi capperi precedentemente lavati sotto l''acqua corrente. Il vitel tonné va servito freddo. Questo piatto, come avrete notato, nulla ha a che spartire col vitello tonnato odierno, vivanda nobilissima a base di carne di vitello lessa, tagliata e ricoperta con una salsa ottenuta da maionese, tonno e capperi e una spruzzata di succo di limone. Il francesismo tonné (ovvero tannè) starebbe per conciato, ossia accomodato, secondo Luciano De Giacomi. Ma significa pure scuro, cupo, come del resto appare la salsa d''acciughe che guarnisce questo piatto. Vino consigliato: Dolcetto di Dogliani.',2639);
INSERT INTO "ricette" VALUES (27414,'Vitella Alla Provenzale','Carne','Vitella',4,'Luogo: Francia. Luogo: Provenza.','4 Braciole Di Vitella,
4 Pomodori Maturi,
Poco Olio D''oliva,
Aglio,
Origano,
Farina,
1 Bicchiere Vino Bianco Secco,
Sale,
Pepe','Preparate un trito d''aglio finissimo. Salate, pepate e infarinate le braciole, fatele rosolare in poco olio da entrambe le parti, poi cospargetele con il trito d''aglio, bagnatele col vino e cuocete fino a far evaporare il sugo. Tagliate i pomodori a fette e disponeteli sulla carne. Spolverate con l''origano, fate cuocere coperto per qualche minuto e servite.',1628);
INSERT INTO "ricette" VALUES (27415,'Vitello Ai Peperoni','Carne','Vitello',4,'Luogo: Sardegna.','600 G Spezzatino Magro Di Vitello,
30 G Funghi Secchi,
150 G Peperoni In Salamoia,
1 Bicchiere Vino Bianco Secco,
Aglio,
Basilico,
Alloro,
1 Limone (scorza),
Alcuni Cucchiai Olio D''oliva','Mettete ad ammorbidire i funghi in acqua tiepida. In una casseruola fate scaldare qualche cucchiaio di olio e fatevi rosolare la carne a fuoco vivace. Salate e pepate. Bagnate con il vino bianco e fatelo evaporare, sempre a fuoco vivace, poi diminuite la fiamma e cuocete coperto per 20 minuti circa. Intanto scolate i funghi, strizzateli e asciugateli bene, poi uniteli alla carne continuando la cottura sempre a fuoco moderato. Tritate insieme l''aglio, il basilico, l''alloro e la scorza di limone e tenete da parte il trito aromatico. Dopo aver cotto lo spezzatino ancora per 25 minuti unite i peperoni e mescolate bene. Aggiungete il trito aromatico, cuocete ancora un minuto e servite ben caldo con un contorno dal sapore neutro come un purè di patate.',2227);
INSERT INTO "ricette" VALUES (27416,'Vitello Ai Porcini Con I Mirtilli','Carne','Vitello',4,' -','600 G Filetto Di Vitello,
1 Mazzetto Insalata Rucola,
4 Funghi Porcini Sott''olio Piccoli,
1 Cespo Insalata Di Stagione,
Olio D''oliva,
1 Cestino Mirtilli,
Sale,
Pepe,
Per La Salsa:,
Olio D''oliva Extra-vergine,
Aceto Aromatizzato Ai Mirtilli,
Prezzemolo,
Erba Cipollina,
Scalogno,
Sale,
Pepe','Tagliate a dadini la carne. Preparate la salsa tritando finemente le erbe e lo scalogno e mescolandoli agli altri ingredienti. Lavate le foglie di insalata e di rucola ed i mirtilli. Tagliate a metà i funghi sott''olio. Fate rosolare a fiamma bassissima la carne con una cucchiaiata di salsa alle erbe. Salatela leggermente, mescolate, toglietela dal fuoco e lasciatela intiepidire. Riunite tutti gli ingredienti in un piatto e condite con la salsa.',2124);
INSERT INTO "ricette" VALUES (27417,'Vitello Ai Sapori Dell''orto','Carne','Vitello',4,' -','Carne Di Vitello,
Panna Da Cucina,
Funghetti,
Cipolline,
Peperoni,
Sedano','Al fondo della cottura dell''arrosto di vitello, aggiungete la panna e cuocete delicatamente funghetti, cipolline, peperoni e sedano. Affettate il vitello e ricopritelo con questa salsa.',589);
INSERT INTO "ricette" VALUES (27418,'Vitello Al Caffè','Carne','Vitello',4,' -','500 G Vitello,
70 G Burro,
100 G Pinoli,
100 G Mandorle,
2 Bicchieri Brodo Vegetale,
1 Tazzina Caffè,
2 Cucchiai Olio D''oliva,
Sale','Fate sciogliere un terzo del burro in una piccola teglia antiaderente, cuocetevi per pochi minuti i pinoli e le mandorle grossolanamente sminuzzate. In un tegame fate rosolare la carne con il burro rimasto e l''olio. Quando avrà preso colore aggiungete la frutta secca e bagnate il tutto col caffè. Passate in forno caldo a 180 gradi e cuocete per 1 ora e mezzo, bagnando via via col brodo.',2601);
INSERT INTO "ricette" VALUES (27419,'Vitello Al Latte','Carne','Vitello',4,' -','700 G Filetto Di Vitello,
1 Cipolla,
1 Rametto Rosmarino,
Alcune Foglie Salvia,
Alcuni Rametti Timo,
100 Cl Latte,
20 G Burro,
Sale,
Pepe','Immergere la carne nel latte e metterla in frigo per almeno 4 ore. Disporre in una pirofila la cipolla a fettine, 20 g di burro a fiocchi, un rametto di rosmarino, qualche foglia di salvia e qualche rametto di timo. Adagiarvi la carne, salare e pepare. Cuocere per 1 ora in forno già caldo a 180 gradi. A metà cottura bagnare con 10 cl del latte usato. Servire la carne a fette insieme al fondo di cottura.',1340);
INSERT INTO "ricette" VALUES (27420,'Vitello Al Latte (2)','Carne','Vitello',4,' -','800 G Carne Di Vitello,
5 Bicchieri Latte,
40 G Burro,
Farina,
Sale,
Pepe','Infarinate leggermente la carne, legatela con alcuni giri di filo da cucina e fatela rosolare a fuoco vivace in un tegame con il burro girandola in continuazione. Quando è ben colorita da tutte le parti, salate e pepate. Lasciate insaporire due minuti, riducete la fiamma e versate il primo bicchiere di latte lasciando che venga assorbito del tutto prima di aggiungere il secondo. E così fino a esaurimento della quantità indicata nella ricetta. Ritirate dal fuoco, lasciate riposare dieci minuti, slegate la carne e tagliatela a fettine. Nappatele con la loro saporita salsetta e servite con contorno di purè di patate.',1729);
INSERT INTO "ricette" VALUES (27421,'Vitello Al Limone','Carne','Vitello',4,' -','800 G Spalla Di Vitello,
2 Limoni,
Basilico,
Olio D''oliva,
Sale,
Pepe','Tagliare la carne a dadini e metterla in una casseruola con l''olio e il basilico; versare il succo dei limoni e far cuocere coperto per circa 40 minuti. A cottura ultimata salare, pepare, mettere in un piatto da portata, decorare con basilico e fettine di limone e servire.',1482);
INSERT INTO "ricette" VALUES (27422,'Vitello Al Limone (2)','Carne','Vitello',4,' -','800 G Noce Di Vitello,
1 Cipolla,
1 Bicchiere Vino Bianco,
2 Bicchieri Brodo,
1 Limone,
40 G Burro,
Sale,
Pepe','Porre in una pentola il burro, la carne, la cipolla e il limone affettati finemente, versarvi il vino e il brodo e passare al forno già caldo a 200 gradi. Ogni tanto estrarre dal forno, girare la carne e irrorare con il suo condimento. Salare e pepare. Ritirare la carne e passare al setaccio il fondo di cottura. Affettare l''arrosto, disporlo su piatto di servizio e irrorarlo con il suo sugo.',1303);
INSERT INTO "ricette" VALUES (27423,'Vitello Al Limone (3)','Carne','Vitello',1,' -','100 G Vitello Magro,
10 G Succo Di Limone,
Olio D''oliva Extra-vergine','Porre il vitello in una casseruola con l''olio e il limone, coprire e cuocere per 5 minuti a fuoco bassissimo.',793);
INSERT INTO "ricette" VALUES (27424,'Vitello Al Limone E Aromi','Carne','Vitella',4,' -','600 G Vitella A Fettine Sottili,
1 Manciata Foglie Di Prezzemolo,
3 Foglie Salvia,
1 Limone Non Trattato,
1 Spicchio Aglio,
2 Fette Peperone In Agrodolce,
1/2 Bicchiere Vino Bianco,
4 Cucchiai Olio D''oliva Extra-vergine','Tritate le foglie di prezzemolo e quelle di salvia ben lavate e asciugate, con lo spicchio d''aglio e un pezzetto di scorza di limone lavata. A parte tritate anche le falde di peperone dopo averle ben sgocciolate dal liquido di conservazione. Mettete l''olio in una padella antiaderente; quando sarà ben caldo, aggiungete le fettine di fesa di vitello e lasciatele cuocere per tre minuti a fuoco abbastanza vivace; poi voltatele con una paletta, salatele e cuocetele per tre minuti anche dall''altra parte. Trasferite la carne in un piatto di portata che terrete in caldo mentre completate la preparazione. Aggiungete al condimento rimasto nella padella in cui avete cotto la carne le falde di peperone tritate, fate insaporire per qualche minuto poi bagnate con il vino bianco; alzate la fiamma e lasciatelo evaporare. Abbassate di nuovo la fiamma e mescolando con un cucchiaio di legno per amalgamare bene tutti gli ingredienti, aggiungete il trito preparato di prezzemolo, aglio, limone, salvia; quindi diluiti con due cucchiai d''acqua.Salate poco, pepate, cuocete per qualche istante ancora,quindi versate la salsina ottenuta sulle scaloppine e servite subito.',1385);
INSERT INTO "ricette" VALUES (27425,'Vitello Al Marsala','Carne','Vitello',4,' -','400 G Magatello Di Vitello,
1 Cipolla,
40 G Burro,
1 Bicchierino Vino Marsala,
Prezzemolo Tritato','Tagliare a fettine il magatello, poi ridurre le fette a striscioline. Saltarle in un soffritto di cipolla e burro, spruzzarle con il marsala, salare e cuocere per 15 minuti, unendo alla fine il prezzemolo.',759);
INSERT INTO "ricette" VALUES (27426,'Vitello Al Pomodoro','Carne','Vitello',4,' -','4 Nodini Di Vitello,
2 Cucchiai Olio D''oliva,
2 Spicchi Aglio,
Sale,
Pepe,
1 Ciuffo Prezzemolo,
1 Cipolla,
500 G Pomodori Pelati,
40 G Burro','Porre i nodini in un tegame, salarli, peparli, unire i pomodori schiacciati, l''olio, il burro, la cipolla e il prezzemolo tritati finemente, coprire e cuocere per 30 minuti a fuoco lento. Scoprire e cuocere su fuoco alto per far restringere il sugo.',1341);
INSERT INTO "ricette" VALUES (27427,'Vitello Al Rafano','Carne','Vitello',4,' -','300 G Scaloppine Di Vitello,
40 G Burro,
1 Cucchiaio Rafano In Pasta,
Sale,
Farina','Passate le scaloppine nella farina, fate sciogliere il burro in una padella e fate dorare la carne da entrambe le parti. Salate, portate a metà cottura e poi aggiungete la pasta di rafano ammorbidita con un po'' d''acqua. Finite la cottura a fuoco basso diluendo se necessario con un po'' d''acqua.',902);
INSERT INTO "ricette" VALUES (27428,'Vitello Al Rosmarino','Carne','Vitello',4,' -','350 G Scaloppine Di Vitello,
1/2 Cucchiaio Rosmarino Tritato,
1 Limone (scorza),
30 G Burro,
Sale,
Olio D''oliva','Scaldare l''olio in una padella e adagiarvi le scaloppine. Farle dorare a fuoco vivo per circa 1 minuto per parte. Abbassare la fiamma e proseguire la cottura per circa 5 minuti girando la carne. Tritare la scorza di limone e mescolarla al rosmarino. Levare le scaloppine dal fuoco e tenerle in caldo. Nella padella mettere rosmarino e scorza, 2 cucchiai di acqua e il burro e scaldare bene. Versare questa salsina sulle scaloppine e servire.',1257);
INSERT INTO "ricette" VALUES (27429,'Vitello Al Vino Rosso','Carne','Vitello',4,' -','1 Stinco Di Vitello Di 1500 G,
60 G Pancetta,
2 Carote,
2 Porri,
2 Coste Sedano,
1 Rametto Salvia,
1 Rametto Rosmarino,
2 Foglie Alloro,
3 Chiodi Di Garofano,
1 Bottiglia Vino Rosso,
Farina,
Olio D''oliva,
Sale,
Pepe','Tagliare a dadini la pancetta e farla soffriggere con 4 ore di olio. Unire la carne infarinata e farla rosolare a fuoco vivo. Unire le verdure a pezzetti, poi le erbe aromatiche e i chiodi di garofano racchiusi in una sacchetto di tela. Salare e pepare. Versare il vino e far evaporare in parte, coprire e cuocere a fuoco lento per 3 ore.',3524);
INSERT INTO "ricette" VALUES (27430,'Vitello All''ostrica','Carne','Vitello',6,'Luogo: Campania.','600 G Carne Di Vitello,
2 Limoni,
4 Cucchiai Olio D''oliva,
30 G Burro,
Sale,
Pepe','Scegliete un pezzo di vitello magro, mettetelo in un tegame ove entri giusto, conditelo con sale e pepe, l''olio e il succo di un limone e mezzo. Mettete un foglio di carta oleata con olio sopra il tegame, chiudete mettendo un leggero peso sul coperchio e fate cuocere a fuoco moderato per un''ora. Al momento di servire affettate la carne e coprite con il sugo.',2254);
INSERT INTO "ricette" VALUES (27431,'Vitello All''uccelletto','Carne','Vitello',4,' -','500 G Fesa Di Vitello A Fettine Sottili,
50 G Burro,
1 Cucchiaio Olio D''oliva,
10 Cl Vino Bianco,
2 Foglie Alloro,
Sale,
Pepe','Soffriggere il burro e l''olio con le foglie di alloro, unire le fettine di carne, insaporire con sale e pepe e farle colorare per qualche minuto a fuoco vivace. Abbassare la fiamma e completare la cottura. Disporre la carne sul piatto di servizio. Versare il vino nel fondo di cottura e farlo ridurre a fuoco vivo Versarlo sulla carne e servire.',1275);
INSERT INTO "ricette" VALUES (27432,'Vitello Alla Bretone','Carne','Vitello',6,'Luogo: Francia. Luogo: Bretagna.','1800 G Girello Di Vitello Arrotolato,
1 Bicchiere Vino Bianco Secco,
1 Bicchiere Brodo,
2 Cipolle,
4 Carote,
1 Piedino Di Vitello,
8 Cuori Carciofi In Scatola,
75 G Burro,
1 Mazzetto Odori,
Sale,
Pepe','Portate a ebollizione una pentola di acqua. Immergetevi il piedino di vitello e lasciatelo bollire per cinque minuti. Scolatelo e rinfrescatelo sotto acqua fredda corrente. Pelate le cipolle e tritatele; mondate le carote e tagliatele a rondelle.Sciogliete 50 g di burro in una casseruola e fatevi rosolare a fuoco vivo la carne su tutti i lati.Toglietela con un mestolo forato e fate rinvenire le carote e la cipolla per un paio di minuti nella stessa casseruola. Riponete la carne nella casseruola, irroratela di vino e di brodo, unitevi il piedino di vitello e il mazzetto di odori, salate e pepate.Coprite, portate a ebollizione e lasciate cuocere a fuoco dolce per due ore. Dieci minuti prima del termine della cottura scolate i cuori di carciofo e sciaquateli in acqua tiepida.Sciogliete il burro rimanente in una padella e fatevi rosolare i cuori di carciofo. Affettate il vitello.Staccate la polpa dal piedino di vitello e tagliatela a dadini.Disponete la carne in un piatto da portata e guarnitela con le cipolle, le carote e i cuori di carciofo. Versate la salsa rimasta in una salsiera e servitela a parte.',2945);
INSERT INTO "ricette" VALUES (27433,'Vitello Alla Campagnola','Carne','Vitello',4,'Preparazione: 150 minuti. Cottura: 15 minuti.','Pepe,
Sale,
15 Cl Crema Di Pollo,
15 Cl Panna,
15 Cl Sidro,
40 G Burro,
1 Cipolla,
1 Carota,
2 Cucchiai Olio D''oliva,
100 G Pancetta Affumicata,
1000 G Garrese Di Vitello','Il garrese di vitello deve essere tagliato in quattro fette spesse. Scaldate il forno a 140 gradi. Tagliate la pancetta a dadini e mettetela in una casseruola. Copritela di acqua fredda, portate a ebollizione, sgocciolatela immediatamente e asciugatela su carta assorbente. Mondate la carota e la cipolla e tagliatele a dadini piccolissimi. Scaldate l''olio in una pentola di terracotta o di ghisa abbastanza grande da contenere giusto la carne e la sua guarnizione. Rosolate la pancetta, la carota e la cipolla due o tre minuti a fuoco moderato, senza lasciare che prenda colore. Aggiungete 25 g di burro nella padella. Appena il burro è fuso fatevi saltare le fette di carne per cinque minuti, girandole. Salate e pepate. Aggiungete la crema di pollo e il sidro. Mescolate per uno o due minuti a fuoco dolce. Ungete un disco di carta pergamena con il burro rimanente e posatelo direttamente sul contenuto della pentola. Coprite la pentola, infornate e lasciate cuocere un''ora, bagnando una volta la carne con il sugo di cottura. Dopo un''ora di cottura togliete il coperchio e lasciate il disco di carta pergamena. infornate di nuovo e lasciate cuocere ancora un''ora, bagnando una volta la carne con il sugo di cottura. Togliete il disco di carta pergamena, aumentate la temperatura del forno a 230 gradi. Lasciate cuocere ancora quindici minuti a scoperto finché la salsa prende un colore brillante. Sgrassate la superficie della salsa con un mestolo o con carta assorbente, versate in un piatto di servizio fondo molto caldo e servite. Potete sostituire il garrese con petto, spalla o collo di vitello. Vino consigliato: Donnaz.',3066);
INSERT INTO "ricette" VALUES (27434,'Vitello Alla Crema Di Sogliole','Carne','Vitello',4,' -','800 G Magatello Di Vitello,
1 Cipolla,
1 Carota,
1 Gambo Sedano,
1 Foglia Alloro,
2 Dadi,
Per La Salsa:,
2 Sogliole Intere,
1 Cestino Lamponi,
Aceto Di Lamponi,
Salsa Worcester,
Tabasco,
10 Cl Olio D''oliva,
1 Uovo,
Succo Di Limone,
3 Cucchiai Sherry,
2 Mazzetti Insalata Rucola,
Per Guarnire:,
Alcune Foglie Crescione','Fate cuocere a vapore i1 magatello con la cipolla, la carota, il sedano, l''alloro e i dadi. Con i tuorli, l''olio e il limone preparate la maionese. Spellate le sogliole, cuocetele a vapore poi spinatele e tagliate a pezzetti la polpa. Incorporate alla maionese. Unite i lamponi, l''aceto di lamponi, la salsa di worcester, il tabasco, lo sherry. Salate e pepate se necessario. Foderate il piatto di portata con uno strato di rucola, disponete sopra il magatello tagliate a fette e copritelo con la salsa di sogliole e lamponi. Guarnite la preparazione con foglie di crescione.',3002);
INSERT INTO "ricette" VALUES (27435,'Vitello Alla Fiamminga','Carne','Vitello',8,' -','1000 G Noce Di Vitello,
80 G Burro,
400 G Prugne Secche,
200 G Albicocche Secche,
200 G Uvetta Sultanina,
Sale,
Pepe','Mettere le prugne, le albicocche e l''uva in acqua per farle ammorbidire; sistemate sul fuoco la carne, il burro e un po'' d''acqua e lasciate cuocere per circa 1 ora. Aggiungete la frutta e fate cuocere per un''altra ora.',3240);
INSERT INTO "ricette" VALUES (27436,'Vitello Alla Marchigiana','Carne','Vitello',4,'Luogo: Marche.','1000 G Noce Di Vitello,
80 G Pancetta A Dadini,
80 G Lardo Affettato,
1 Cipolla,
1 Carota,
1 Gambo Sedano,
1 Spicchio Aglio,
Alcuni Rametti Maggiorana,
Vino Bianco Secco,
Vino Rosso Secco,
400 G Polpa Di Pomodoro,
1 Limone,
Brodo,
Olio D''oliva,
Sale,
Pepe,
Per Servire:,
Polenta Morbida Preparata Con 400 G Di Farina Gialla E 170 Cl Di Acqua','Immergete i dadini di pancetta in una ciotola con un bicchiere di vino bianco. Dopo 30 minuti scolateli e rotolateli in un trito fine fatto con l''aglio, una scorzetta di limone non trattato e abbondante pepe. Fate dei taglietti abbastanza profondi nella noce di vitello: usate la punta di un coltellino ben affilato. Introducete nei tagli i dadini di pancetta marinati e sgocciolati. Poi legate la carne con dello spago da cucina in modo che, durante la cottura, mantenga la forma. Pulite e tritate le verdure con il lardo e la maggiorana. Fate appassire questo trito in una casseruola con 2 cucchiai di olio, unite la carne e lasciatela insaporire per qualche istante. Bagnate con mezzo bicchiere di vino rosso e fatelo evaporare in parte. Salate, pepate e aggiungete la polpa di pomodoro e un litro circa di brodo caldo. Coprite la casseruola, abbassate il fuoco e continuate la cottura per 2 ore. Alla fine, togliete la carne dalla pentola e, a fuoco vivace, fate addensare il sugo. Affettate la carne in umido, mettetela sopra un piatto di portata e servitela irrorata con il sugo. Potete accompagnarla con la polenta o il purè.',3335);
INSERT INTO "ricette" VALUES (27437,'Vitello Alla Milanese','Carne','Vitello',4,'Luogo: Lombardia. Luogo: Milano.','4 Fettine Di Fesa Di Vitello,
Succo Di Limone,
Aglio Tritato Finissimo,
50 G Burro,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Battere le fettine e tenerle per circa 2 ore e 30 minuti nella marinata di succo di limone ed aglio, rivoltandole qualche volta. Soffriggere nell''olio e nel burro le fettine di carne e farle dorare a calore vivo. Abbassare il fuoco, versare la marinata, condire con sale e pepe e, a fuoco dolcissimo, completare la cottura. Servire molto calde con purea di patate.',1995);
INSERT INTO "ricette" VALUES (27438,'Vitello Alla Milanese (2)','Carne','Vitello',4,'Preparazione: 20 minuti.','2 Lombate Di Vitello Da 300 G,
2 Uova,
5 Foglie Salvia,
4 Cucchiai Pangrattato,
4 Cucchiai Olio D''oliva Extra-vergine,
30 G Burro,
1 Pizzico Sale,
1 Pizzico Pepe','Pulire le lombate privandole delle eventuali parti grasse e delle nervature. Lavare la salvia, tritarla finemente e amalgamarla al pangrattato (oppure frullare insieme il pangrattato con le foglie di salvia spezzettate). In una terrina battere leggermente le uova con una forchetta, immergervi le lombate, scolarle, passarle nel pangrattato con la salvia, premere bene con il palmo della mano per far aderire il pane e scuoterle un poco per eliminare l''eccesso. In una padella antiaderente far scaldare l''olio con il burro, adagiarvi le lombate e farle cuocere per 5-6 minuti da ogni parte facendole dorare leggermente; scolarle sopra un foglio di carta di tipo assorbente da cucina, insaporirle con un pizzico di sale e di pepe, farle riposare per qualche minuto al caldo, quindi tagliarle a fettine in sbieco. Servire la tagliata di vitello, accompagnandola con insalatina fresca di stagione.',1973);
INSERT INTO "ricette" VALUES (27439,'Vitello Alle Olive','Carne','Vitello',4,' -','400 G Fesa Di Vitello A Fettine Sottili,
1 Uovo,
100 G Pangrattato,
150 G Olive Verdi Snocciolate,
5 Cucchiai Olio D''oliva,
1 Cucchiaino Senape Dolce,
Sale','Sbattere l''uovo con poco sale e immergervi le fettine di carne, quindi passarle nel pangrattato. Soffriggere 2 cucchiai di olio e dorarvi le scaloppine per qualche minuto. Adagiarle su carta assorbente. Frullare olive, senape e il rimanente olio per ottenere una salsa consistente. Versare a cucchiaini sulla carne e servire.',1458);
INSERT INTO "ricette" VALUES (27440,'Vitello Alle Verdure','Carne','Vitello',6,' -','600 G Carne Di Vitello,
50 G Pancetta,
150 G Carote,
150 G Patatine Novelle,
150 G Piselli,
150 G Fagiolini,
150 G Cipolline,
1 Pomodoro,
1 Insalata Lattuga,
50 G Burro,
Vino Bianco,
Sale,
Pepe,
Erbe Aromatiche','In una teglia mettere il burro, la cipolla tritata, le erbe aromatiche e la carne; lasciatela rosolare bagnandola con vino bianco. Tagliate a pezzetti tutte le verdure e aggiungetele alla carne. Bagnate con acqua, salate, pepate e lasciate cuocere per circa 2 ore.',1607);
INSERT INTO "ricette" VALUES (27441,'Vitello Allo Yogurth','Carne','Vitello',4,' -','Salvia,
Rosmarino,
Sale,
Pepe,
800 G Fesa Di Vitello (pezzi Da 800 G),
1 Bicchierino Cognac,
1 Mestolo Brodo,
1 Spicchio Aglio,
1 Vasetto Yogurth','Tritare finemente il rosmarino, la salvia e l''aglio. Scaldare il cognac con il trito, unire la carne e farla insaporire bene. Bagnare con il brodo e continuare la cottura a fuoco basso e con il coperchio per circa 1 ora e mezza. 20 minuti prima del termine salare, pepare e unire lo yogurth. Infine tagliare la carne a fette e servirla con il suo sugo.',998);
INSERT INTO "ricette" VALUES (27442,'Vitello Allo Zafferano','Carne','Vitello',4,' -','700 G Vitello,
3 Cipolle,
70 G Panna,
60 G Burro,
Latte,
Vino Bianco Secco,
Farina,
Prezzemolo,
4 Cucchiai Olio D''oliva,
Sale,
Pepe,
1 Cucchiaino Zafferano','Tagliate il vitello in pezzetti e passateli nella farina; fateli quindi rosolare in padella con 30 g di burro e 3 cucchiai d''olio. Intanto tritate molto finemente le cipolle e fatele appassire in un''altra casseruola con il rimanente burro e 1 cucchiaio d''olio. Unite al soffritto la carne spruzzata con il vino, alzate la fiamma e fatelo evaporare, poi bagnate con un po'' d''acqua calda, alzate ancora la fiamma e fate asciugare. Unite la panna e un bicchiere di latte; cuocete a fuoco moderato e coperto per 40 minuti, mescolando spesso. A cottura ultimata, insaporite la carne con un cucchiaino di zafferano, salate e pepate. Mettete su un piatto da portata caldo e cospargete di prezzemolo tritato.',3340);
INSERT INTO "ricette" VALUES (27443,'Vitello Aromatizzato','Carne','Vitello',1,' -','160 G Vitello Magro,
Olio D''oliva Extra-vergine,
Aglio,
Rosmarino,
Salvia','Fare un trito con gli odori e l''aglio. Aggiungere un po'' di olio e lasciarvi macerare la carne. Dopodiché cuocerla alla piastra e condirla con gli odori.',897);
INSERT INTO "ricette" VALUES (27444,'Vitello Arrosto','Carne','Vitello',6,' -','1000 G Vitello,
2 Dita Vino Bianco Secco,
Sale,
Pepe','In una casseruola fatta scaldare ponete la carne e fatela rosolare da tutte le parti. Quando ha preso un bel colore uniforme, conditela con sale e pepe e una spruzzata di vino bianco secco. Coprite la pentola e lasciate cuocere per 30 minuti, trascorso questo tempo voltate la carne sull''altro lato e cuocete ancora per altri 30 minuti. A cottura ultimata tagliate la carne a fette sottili. Potete servirla condita con il proprio sugo e con un contorno di purè di patate, oppure di spinaci.',952);
INSERT INTO "ricette" VALUES (27445,'Vitello Con Funghi','Carne','Vitello',4,' -','500 G Fesa Di Vitello,
300 G Funghi,
1 Scalogno,
6 Cucchiai Panna,
25 G Burro,
Salsa Worcester,
Alcune Gocce Tabasco,
Sale','Soffriggere nel burro lo scalogno tritato. Unire i funghi, salare e cuocere per circa 10 minuti. Tagliare la carne a fette di circa 1/2 cm di spessore e poi a listarelle lunghe 2 cm e aggiungerla ai funghi. Cuocere per circa 10 minuti a fuoco medio-alto e mescolando. Regolare di sale, spruzzare con la Worcester, qualche goccia di tabasco e unire la panna. Mescolare rapidamente e servire.',1248);
INSERT INTO "ricette" VALUES (27446,'Vitello Delicato Con Insalata Caterina De Medici','Carne','Vitello',4,' -','350 G Carne Di Vitello,
1 Carota,
1 Costa Sedano,
1 Cipolla,
20 Cl Panna,
100 G Insalata Foglia Di Quercia,
20 G Capperi,
20 G Noci,
20 G Pinoli,
20 G Uvetta Sultanina,
20 G Acciughe,
50 G Formaggio Provolone Dolce,
Olio D''oliva,
Sale,
Pepe','Tagliare il vitello a cubi, scottarli in padella con olio e tenerli in caldo. In un padellino a parte con olio brasare sedano, carota e cipolla tritati. Unire la carne e la panna, ridurre e servire assieme a cubetti di formaggio ed una insalatina di lattuga condita col resto degli ingredienti.',2421);
INSERT INTO "ricette" VALUES (27447,'Vitello Di Mare Al Pomodoro','Pesce','Palombo',4,' -','500 G Palombo Tagliato A Fette Grandi,
2 Cipolle,
4 Pomodori Maturi,
2 Carote,
1 Gambo Sedano,
Sale,
Pepe','Preparare un trito composto dalle cipolle, le carote e il sedano, tagliare a piccoli pezzi i pomodori e inserire il tutto in una casseruola, a freddo, adagiando per ultimo il palombo, portare al giusto grado di calore, chiudere con il coperchio e cuocere.',568);
INSERT INTO "ricette" VALUES (27448,'Vitello Farcito','Carne','Vitello',6,' -','1500 G Vitello,
1 Piatto Mollica Di Pane Raffermo,
25 Cl Latte,
150 G Salsiccia,
200 G Polpa Di Vitello,
100 G Lardo Affumicato,
2 Cucchiai Prezzemolo Tritato,
1 Uovo,
50 G Burro,
Alcune Cipolle,
500 G Patate,
Sale,
Pepe','Acquistate un petto di vitello aperto. Per il ripieno, tritate la carne e la salsiccia. In una padella rosolate le cipolle con il lardo e il ripieno, aggiungete la mollica ti pane, il prezzemolo, l''uovo, sale e pepe. Riempite il petto di vitello con il composto e ricucite. Mettetelo in una teglia cospargendolo di burro fuso, cipolline, e patate. Lasciate cuocere per 1 ora e 30 minuti.',4371);
INSERT INTO "ricette" VALUES (27449,'Vitello Farcito (2)','Carne','Vitello',4,'Luogo: Basilicata.','600 G Fesa Di Vitello (fette Da 600 G),
500 G Insalata Cicoria,
2 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cipolla,
1 Carota,
1 Costa Sedano,
1 Uovo,
Maggiorana,
Rosmarino,
Salvia,
1/2 Bicchiere Vino,
Olio D''oliva,
Sale','Pulire la cicoria, cuocerla in poca acqua bollente salata e poi tagliarla a pezzettini. Mettere il tuorlo in una scodella con parmigiano e cicoria e mescolare. Battere la carne e salarla. Appoggiarla su un tagliere e metterci sopra la cicoria e un po'' di maggiorana. Arrotolare la carne e legarla. Mettere il rotolo su una teglia con un po'' di olio e farlo dorare. Tagliare le verdure a pezzettini e unirle alla carne insieme alla salvia. Infine bagnare con mezzo bicchiere di vino. Scaldare il forno a 200 gradi e infornare la teglia per 60 minuti. Togliere la carne dal forno, farla intiepidire e tagliarla a fettine non troppo sottili. Frullare il sughetto e servirlo con la carne.',1708);
INSERT INTO "ricette" VALUES (27450,'Vitello Farcito Al Profumo Di Erbe','Carne','Vitello',4,'Luogo: Basilicata. Luogo: Lucania.','600 G Fesa Di Vitello (fette Da 600 G),
500 G Insalata Cicoria,
2 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cipolla,
1 Carota,
1 Costa Sedano,
1 Uovo,
Alcune Foglie Maggiorana,
1 Rametto Rosmarino,
Alcune Foglie Salvia,
1 Bicchiere Vino Bianco,
5 Cucchiai Olio D''oliva Extra-vergine,
Sale','Lavate e pulite la cicoria. Versate poca acqua in una pentola, mettetela sul fuoco e aggiungete un pizzico di sale. Quando l''acqua bolle, aggiungete la cicoria. Fate cuocere per 34 minuti e poi scolatela. Tagliatela a pezzettini minuscoli. Ora sgusciate l''uovo e poi separate l''albume dal tuorlo. Mettete il tuorlo in una scodella, aggiungete i due cucchiai di parmigiano e la cicoria. Con un forchetta mescolate il tuorlo dell''uovo, il parmigiano e la cicoria. Passate poi alla carne. Prendete la fetta di fesa, e battete la carne fino a quando si è allargata e assottigliata. Salate la carne su ambedue i lati. Poggiate la fetta di carne su un tagliere di legno e spargetevi sopra la cicoria mescolata con l''uovo e il parmigiano. Aggiungete poi un cucchiaino di foglioline di maggiorana. Arrotolate la carne fino a formare un grande rotolo e legatelo. Ora mettete il rotolo su una teglia e aggiungete i 4 cucchiai di olio. Mettete la teglia sul fuoco e fate cuocere a fuoco vivace finché la carne non diventa dorata. Togliete la carne dal fuoco. A parte tagliate la carota a dischetti, la costa di sedano a pezzetti e la cipolla in 4 parti. Aggiungete alla carne la carota, il sedano e la cipolla, un rametto di rosmarino e 3 foglie di salvia. Infine bagnate la carne con mezzo bicchiere di vino bianco. Nel frattempo fate scaldare il forno a 200 gradi e infornate la teglia per circa un''ora. Togliete la carne dal forno, poggiatela su un tagliere e lasciatela intiepidire. Tagliate l''arrosto a fette non troppo sottili. Dal sugo di cottura, che è rimasto nella teglia, togliete il rosmarino e la salvia. Versate il sugo di cottura, le carote, il sedano e la cipolla in un frullatore, oppure in un passaverdure. Frullate alla massima velocità per un minuto. Disponete la carne su un piatto di portata e servitela con la salsa ottenuta.',1499);
INSERT INTO "ricette" VALUES (27451,'Vitello Farcito Al Profumo Di Erbe (2)','Carne','Manzo',4,'Luogo: Basilicata. Luogo: Lucania.','600 G Fesa Di Manzo (fette Da 600 G),
500 G Insalata Cicoria,
2 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cipolla,
1 Carota,
1 Costa Sedano,
1 Uovo,
Alcune Foglie Maggiorana,
1 Rametto Rosmarino,
Alcune Foglie Salvia,
1 Bicchiere Vino Bianco,
5 Cucchiai Olio D''oliva Extra-vergine,
Sale','Lavate e pulite la cicoria. Versate poca acqua in una pentola, mettetela sul fuoco e aggiungete un pizzico di sale. Quando l''acqua bolle, aggiungete la cicoria. Fate cuocere per 34 minuti e poi scolatela. Tagliatela a pezzettini minuscoli. Ora sgusciate l''uovo e poi separate l''albume dal tuorlo. Mettete il tuorlo in una scodella, aggiungete i due cucchiai di parmigiano e la cicoria. Con un forchetta mescolate il tuorlo dell''uovo, il parmigiano e la cicoria. Passate poi alla carne. Prendete la fetta di fesa, e battete la carne fino a quando si è allargata e assottigliata. Salate la carne su ambedue i lati. Poggiate la fetta di carne su un tagliere di legno e spargetevi sopra la cicoria mescolata con l''uovo e il parmigiano. Aggiungete poi un cucchiaino di foglioline di maggiorana. Arrotolate la carne fino a formare un grande rotolo e legatelo. Ora mettete il rotolo su una teglia e aggiungete i 4 cucchiai di olio. Mettete la teglia sul fuoco e fate cuocere a fuoco vivace finché la carne non diventa dorata. Togliete la carne dal fuoco. A parte tagliate la carota a dischetti, la costa di sedano a pezzetti e la cipolla in 4 parti. Aggiungete alla carne la carota, il sedano e la cipolla, un rametto di rosmarino e 3 foglie di salvia. Infine bagnate la carne con mezzo bicchiere di vino bianco. Nel frattempo fate scaldare il forno a 200 gradi e infornate la teglia per circa un''ora. Togliete la carne dal forno, poggiatela su un tagliere e lasciatela intiepidire. Tagliate l''arrosto a fette non troppo sottili. Dal sugo di cottura, che è rimasto nella teglia, togliete il rosmarino e la salvia. Versate il sugo di cottura, le carote, il sedano e la cipolla in un frullatore, oppure in un passaverdure. Frullate alla massima velocità per un minuto. Disponete la carne su un piatto di portata e servitela con la salsa ottenuta.',1643);
INSERT INTO "ricette" VALUES (27452,'Vitello In Crosta Di Mandorle','Carne','Vitello',4,'Luogo: Calabria.','500 G Fettine Di Fesa Di Vitello,
2 Uova,
200 G Scaglie Di Mandorle,
Farina,
30 G Burro,
4 Cucchiai Olio D''oliva,
Sale','Battere leggermente le fettine e infarinarle. Rompere le uova in un piatto fondo, salare e sbattere con una forchetta. Stendere le scaglie di mandorle su un ampio vassoio. Passare le fette di carne nell''uovo sbattuto, quindi appoggiarle sulle mandorle, premendo per farle aderire. Intanto scaldare 4 cucchiai di olio e 30 g di burro in una padella. Cuocere le fettine, girandole per farle dorare. Sgocciolare, salare e servirle ben calde.',3133);
INSERT INTO "ricette" VALUES (27453,'Vitello In Salsa','Carne','Vitello',4,' -','600 G Girello Di Vitello (pezzi Da 600 G),
1 Dado Per Il Brodo,
1 Carota,
1 Cipolla,
1 Gambo Sedano,
1 Bicchiere Vino Bianco Secco,
Sale,
Per La Salsa:,
Pepe,
2 Tuorli D''uovo Sodo,
1 Tuorlo D''uovo Crudo,
1/2 Bicchiere Olio D''oliva Extra-vergine,
2 Mazzetti Basilico,
1 Cucchiaio Capperi,
3 Cetriolini Sott''aceto,
1 Cucchiaino Aceto Di Vino,
Sale,
Pepe','Mettete a cuocere la carne con le verdure mondate, il dado, il vino e la giusta dose di sale. Lasciatela raffreddare nel brodo, quindi sgocciolatela, tagliatela a fette sottili e sistematela sul piatto da portata. Preparate la salsa: schiacciate con una forchetta i tuorli delle uova sode e lavorateli con l''aceto. Incorporate il tuorlo crudo, salate, pepate e versate l''olio come per la maionese. Quando la salsa sarà pronta unitevi i capperi, i cetriolini e il basilico tritati, mescolando accuratamente. Con questa salsa ricoprite le fette di carne che terrete un po'' al fresco prima di servire.',1774);
INSERT INTO "ricette" VALUES (27454,'Vitello In Salsa (2)','Carne','Vitello',4,' -','8 Scaloppine Di Vitello,
1 Spicchio Aglio,
1 Cipolla,
1 Costa Sedano,
1 Peperone,
1 Carota,
1 Bicchiere Brodo,
Basilico,
Olio D''oliva,
Burro,
Sale','Rosolare con olio e aglio un trito di cipolla, carota, sedano e peperone, bagnare con il brodo, salare, far cuocere per circa 40 minuti, levare l''aglio e unire il basilico tritato e 1/2 bicchiere di olio. Cuocere le scaloppine nel burro, coprirle con la salsa e servire.',2070);
INSERT INTO "ricette" VALUES (27455,'Vitello In Salsa Gialla','Carne','Vitello',4,' -','4 Fettine Di Fesa Di Vitello,
50 G Burro,
2 Uova,
1 Limone,
Sale,
Pepe','Rosolare le fettine nel burro e, a cottura quasi ultimata, salare e pepare. Quando saranno cotte toglierle dal tegame. Sbattere le uova con il succo di limone, salare, pepare e versare nel tegame, accendere di nuovo il fuoco, mescolare e, non appena il sugo si sarà rappreso, versarlo sulle fettine tenute in caldo.',1081);
INSERT INTO "ricette" VALUES (27456,'Vitello In Salsa Rosa','Carne','Vitello',4,' -','800 G Magatello Di Vitello,
100 G Pisellini,
1 Vasetto Maionese,
3 Cucchiai Tomato Ketchup,
4 Cucchiai Panna,
80 G Tonno,
2 Spicchi Aglio,
3 Cucchiai Olio D''oliva,
30 G Burro,
Sale,
Pepe','Rosolare il magatello in 3 cucchiai di olio e 30 g di burro. Unire l''aglio a lamelle, salare, pepare, bagnare con 1 bicchiere di acqua calda, coprire e cuocere in forno caldo a 180 gradi per 1 ora. Mescolare alla maionese la panna, la tomato, il tonno ridotto a crema e tenere in frigo. Lessare i piselli e unirli alla salsa. Affettare il vitello e coprirlo con la salsa. Servire freddo.',3673);
INSERT INTO "ricette" VALUES (27457,'Vitello In Salsa Sfiziosa','Carne','Vitello',4,' -','700 G Magatello Di Vitello,
1 Cipolla,
1 Gambo Sedano,
1 Carota,
1 Foglia Alloro,
1 Rametto Prezzemolo,
4 Chiodi Di Garofano,
Sale,
5 Grani Pepe Nero In Grani,
Per La Salsa Alle Verdure:,
60 G Piselli Sgusciati,
1 Carota,
1 Zucchina,
1 Costa Sedano,
1 Cipolla,
10 Mandorle Sgusciate Spellate,
1 Fetta Pane Casereccio,
1/2 Arancia (succo),
1/2 Limone (scorza Grattugiata),
1 Rametto Maggiorana,
1 Cucchiaino Zenzero In Polvere,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Portate a ebollizione una pentola di acqua con la cipolla, steccata con i chiodi di garofano, la carota, raschiata e tagliata a pezzi, il sedano, la foglia di alloro, 5 grani di pepe e il prezzemolo. Immergete quindi la carne e lasciatela cuocere per circa un''ora e 15 minuti, salando quasi a fine cottura, quindi estraetela dalla casseruola, avvolgetela in un foglio di alluminio e lasciatela raffreddare. Nel frattempo, preparate la salsa. Fate insaporire in un filo d''olio la fetta di pane e le mandorle, poi frullateli fino a sbriciolarli. Tagliate a dadini la cipolla, la zucchina, il sedano e la carota. Fate scaldare 4 cucchiai d''olio in una padella con lo zenzero, poi unite le verdure preparate e fatele cuocere per circa 5 minuti. Aggiungete quindi i piselli e il succo di arancia e proseguite la cottura per 15 minuti a fuoco dolce. Unite poi il pane frullato, le foglie di maggiorana, la buccia di limone, sale e pepe a piacere e mescolate bene. Servite il magatello affettato sottilmente con la salsa preparata.',1946);
INSERT INTO "ricette" VALUES (27458,'Vitello In Salsa Tonnata','Carne','Vitello',4,' -','1000 G Vitello (girello),
200 G Tonno Sott''olio,
1 Maionese,
25 G Capperi,
3 Filetti D''acciughe,
6 Cetriolini Sott''aceto,
1 Cipolla,
1 Costa Sedano,
1 Carota,
1 Spicchio Aglio,
1 Mazzetto Prezzemolo,
Succo Di Limone,
Sale','Legate il pezzo di carne mettetelo in una casseruola, copritelo di acqua fredda, aromatizzate l''acqua con la carota, la cipolla tagliata a metà, il gambo di sedano, il mazzetto di prezzemolo lo spicchio di aglio, salate e fate cuocere per una ora e mezzo circa. Scolate poi la carne dal brodo, slegatela e lasciatela raffreddare. Nel frattempo preparate la maionese. Tenete a parte tre cetrioli e alcuni capperi che vi serviranno per decorare il piatto. Frullate il tonno con i rimanenti capperi, i cetriolini tritati e le acciughe. Se non avete il frullatore tritate il tutto molto finemente con la mezzaluna. Aggiungete tutti gli ingredienti frullati alla salsa maionese, mescolando. Unite anche un po'' di limone. Tagliate la carne a fette piuttosto sottili e appoggiatele, accavallandole leggermente, su un piatto di portata. Versate sulla carne la salsa pronta, stendetela con una spatola in modo da ricoprire completamente le fette di vitello e decorare con i rimanenti capperi e i cetrioli tagliati a fettine.',2380);
INSERT INTO "ricette" VALUES (27459,'Vitello In Umido','Carne','Vitello',4,' -','600 G Polpa Di Vitello,
1 Cipolla,
3 Cucchiai Conserva Di Pomodoro,
150 G Olive Verdi,
1 Foglia Alloro,
1 Spolverata Farina,
Burro,
Olio D''oliva,
Sale,
Brodo,
Pepe','Affettare la cipolla e farla appassire in olio e burro, unire la carne tagliata a tocchetti e farla insaporire. Aggiungere una foglia di alloro, una spolverata di farina, sale, pepe, la conserva di pomodoro e 3 mestoli di brodo. Cuocere per 1 ora e 30 minuti, unendo altro brodo se necessario. Poco prima della fine aggiungere le olive snocciolate e tagliate a metà.',2311);
INSERT INTO "ricette" VALUES (27460,'Vitello Marinato','Carne','Vitello',4,' -','8 Fettine Di Magatello Di Vitello,
1 Uovo,
Pangrattato,
1 Limone,
Aglio,
Cipolla,
Sedano,
Prezzemolo,
Basilico,
Senape,
Olio D''oliva,
Burro','Far marinare le fettine di carne con olio, succo di limone e un trito di prezzemolo, basilico, aglio, cipolla e sedano. Dopo 2 ore sgocciolarle, spalmarle con un velo di senape, passarle nell''uovo sbattuto e nel pangrattato, friggerle in burro caldo e servire.',2912);
INSERT INTO "ricette" VALUES (27461,'Vitello Primavera','Carne','Vitello',8,' -','1000 G Carne Di Vitello,
1000 G Fagiolini,
Carote,
2 Pomodori,
500 G Patate,
Sale,
Pepe,
Burro','Fate cuocere per 1 ora l''arrosto nel forno. Intanto in un tegame con acqua cuocete le carote, le patate senza buccia e i fagiolini. 20 minuti prima della fine della cottura dell''arrosto aggiungete sale, pepe e innaffiate con il suo sugo; aggiungete carote, fagiolini, pomodori tagliati in 4. Con le patate preparate un purè. Servite tagliando l''arrosto a fette con intorno la verdura e sopra il purè.',2320);
INSERT INTO "ricette" VALUES (27462,'Vitello Rosso','Carne','Vitello',1,'Ricetta adatta a: bambini piccoli.','2 Cucchiai Semolino,
1 Vasetto Omogeneizzato Di Vitello,
2 Pomodori Maturi,
1 Carota,
1 Pezzetto Sedano,
1 Cucchiaino Formaggio Parmigiano,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Pizzico Sale','Cuocere le verdure in circa 500 g d''acqua leggermente salata, quindi separarle dal brodo di cottura, sbucciare i pomodori eliminando i semi e ridurre il tutto in purea. A 200 g di brodo di cottura ben caldo, aggiungere 3 cucchiai della purea di verdure, versare a pioggia il semolino e amalgamare con cura il vitello. Aggiungere il parmigiano e condire con l''olio d''oliva extra-vergine.',425);
INSERT INTO "ricette" VALUES (27463,'Vitello Speciale','Carne','Vitello',4,'Luogo: Lombardia.','4 Fette Fesa Di Vitello,
2 Pomodori Maturi,
1 Mozzarella Piccola,
2 Acciughe Sotto Sale,
Farina,
50 G Burro,
Origano,
Sale,
Pepe','Infarinate le fette di fesa e fatele rosolare da entrambe le parti per pochi istanti in 20 g di burro. Salatele, pepatele e mettetele in una pirofila imburrata. Su ogni scaloppina adagiate 2 o 3 fette di pomodoro ed un po'' di mozzarella tagliata a dadini. In una casseruola mettete 30 g di burro e le acciughe, dissalate, diliscate e tagliate a pezzetti. Con i denti di una forchetta cercate di sciogliere le acciughe nel burro, poi versate il tutto sulle scaloppe; spolverizzate con un po'' di origano e mettete in forno caldo a 200 gradi per 7-8 minuti, finché la mozzarella si sarà fusa.',1644);
INSERT INTO "ricette" VALUES (27464,'Vitello Tartufato','Carne','Vitello',6,' -','2 Filetti Di Vitello,
120 G Pancetta Tagliata A Fette Grandi,
35 G Pasta Di Tartufi Neri,
20 G Tartufo Nero Fresco,
12 Scalogni,
24 Castagne Secche Tenute A Bagno La Notte,
6 Foglie Cavolo Bianco,
1 Bicchiere Vino Bianco Secco,
1 Mestolo Brodo Vegetale,
Olio D''oliva,
Sale,
Pepe','Lessate le castagne in acqua bollente leggermente salata per 30 minuti, scolatele e tenetele da parte. Salate e pepate i filetti di vitello, spalmateli di pasta di tartufo, avvolgeteli nella pancetta e legateli con spago da cucina. Rosolate la carne in una casseruola con tre cucchiai di olio. Quando gli arrostini saranno dorati su tutti i lati, innaffiateli con il vino che lascerete sfumare, poi continuate la cottura in forno a 180 gradi per 45 minuti, bagnando ogni tanto con il brodo. Nel frattempo sbucciate gli scalogni, divideteli a metà e saltateli in padella con tre cucchiai di olio. Salateli, pepateli e cuoceteli per 15 minuti a fuoco basso. Unite i cavoli tagliati a quadretti e le castagne, lasciate insaporire e proseguite la cottura bagnando ogni tanto con brodo vegetale finché tutte le verdure non saranno tenere. Quando i filetti saranno pronti slegateli, tagliateli a fette spesse e filtrate il fondo di cottura. Disponete nei piani da portata le fette di carne con il contorno di scalogni e di castagne,'' versatevi la salsa e grattugiate il tartufo nero fresco.',3466);
INSERT INTO "ricette" VALUES (27465,'Vitello Tonnato','Carne','Vitello',4,' -','500 G Carne Di Vitello,
150 G Tonno Sott''olio,
1 Cucchiaio Capperi,
Alcuni Rametti Prezzemolo,
Aceto Di Vino Bianco,
1 Cipolla,
Alcune Foglie Basilico,
1 Chiodo Di Garofano,
4 Acciughe Salate,
1 Foglia Alloro,
1 Gambo Sedano,
1 Carota,
2 Limoni,
Olio D''oliva Extra-vergine,
Pepe In Grani,
Sale','Legare in più punti il vitello con uno spago incolore. Lavare e diliscare le acciughe quindi dividerne due a metà e infilare i filetti ricavati tra lo spago e la carne. Porre a fuoco in una casseruola ovale, larga a sufficienza per farvi stare il pezzo di vitello non di più, l''acqua necessaria per lessarlo, unire la cipolla con conficcato il chiodo di garofano, il gambo di sedano, il prezzemolo, il basilico, la foglia di alloro, precedentemente ben lavati, la carota lavata e raschiata, cinque grani di pepe e mezzo bicchiere circa di aceto. Porre il recipiente sul fuoco e, quando si alza il bollore, mettervi la carne, dopo poco salare e lasciarla cuocere a fuoco moderato per circa un''ora e mezza. A cottura ultimata scolarla, metterla su un piatto, porre sopra un secondo piatto e su questo un leggero peso, quindi lasciarla raffreddare. Nel frattempo preparare la salsa: tritare finissime le restanti acciughe, il tonno, i capperi (anche con il moulinex), poi porre il trito in una ciotola ed incorporarvi mezzo bicchiere d''olio e il succo filtrato di due limoni (oppure della maionese già fatta), salare e pepare. Tagliare il vitello ormai freddo a fettine sottilissime. Sistemare su un piatto da portata uno strato di fettine di carne e ricoprirle di un sottile strato di salsa, continuare così fino ad esaurimento degli ingredienti.',1702);
INSERT INTO "ricette" VALUES (27466,'Vitello Tonnato (2)','Carne','Vitello',4,' -','800 G Carne Di Vitello Magro,
250 G Tonno Sott''olio,
4 Acciughe,
2 Cipolle,
50 Cl Vino Bianco Secco,
Olio D''oliva,
1 Limone (succo),
Sale,
Pepe','In un tegame sistemate la carne, il tonno sminuzzato, le cipolle tagliate a fette sottilissime, le acciughe dissalate, sale e pepe. Ricoprite con il vino allungato con poca acqua. Coprite e cuocete piano per un paio d''ore. Ritirate la carne, frullate la salsa rimasta nella pentola e diluitela con un bicchiere di olio e il succo passato di un limone. Tagliate il vitello a fette e ricopritelo con la sua salsa.',2539);
INSERT INTO "ricette" VALUES (27467,'Vitello Tonnato (3)','Carne','Vitello',4,' -','1000 G Spalla Di Vitello,
1 Cipolla Steccata Con Alloro E Chiodi Di Garofano,
3 Carote Pelate,
1 Pezzo Sedano Rapa,
150 Cl Brodo Di Verdura,
Pepe In Grani,
Per La Salsa:,
10 Filetti D''acciughe,
20 Cl Olio D''oliva,
1 Scatola Tonno Sgocciolato (160 G),
1 Tazza Grande Maionese Al Limone,
Aceto Di Vino,
Succo Di Limone,
Sale,
Pepe,
Per Guarnizione:,
Capperi,
Cetrioli Sott''aceto,
Olive,
Uova Sode In Quarti,
Erba Cipollina,
Filetti D''acciughe','Preparare il brodo con cipolla, carote e sedano poi aggiungere la carne. Cuocere a calore moderato per un''ora e 1/4 poi lasciar raffreddare la carne nel brodo. Ridurre in purea tonno, filetti d''acciughe, olio aggiungendo 20 cl di brodo. La salsa deve risultare abbastanza densa. Aromatizzare con aceto, succo di limone pepe e sale. Togliere la carne dal brodo e tagliarla a fette sottili con le quali ricoprirete un piatto. Tagliate quindi a cubetti le carote e il sedano. Cospargete poi la carne con le verdure e la salsa ottenuta. Mettere nel frigorifero per 8-12 ore. Guarnire a piacimento. Accompagnare con insalata verde e pane fresco o pane all''aglio. Suggerimento: potete sostituire la spalla di vitello con altre parti (noce, magatello o anche punta o collo), o con carne di maiale (lonza).',4817);
INSERT INTO "ricette" VALUES (27468,'Vitello Tonnato (4)','Carne','Vitello',6,' -','800 G Magatello Di Vitello,
Carota,
Sedano,
Cipolla,
Maionese,
1 Scatola Tonno,
Cetriolini Sott''aceto,
10 Capperi,
2 Acciughe Sott''olio,
1/4 Bicchiere Aceto Di Vino Bianco,
Sale','Fate bollire la carne con la carota, il sedano e la cipolla, quando è cotta toglietela dall''acqua e lasciatela raffreddare. Frullate nel mixer la scatola di tonno, i cetriolini, le acciughe, i capperi, l''aceto di vino bianco e poi unite la maionese. Tagliate il magatello a fettine sottili e mettete su un piatto di portata. Coprite con la salsa e decorate con capperi e cetriolini.',2566);
INSERT INTO "ricette" VALUES (27469,'Vitello Tonnato Alla Moda Antica','Carne','Vitello',10,'Luogo: Piemonte. Luogo: Alba. Preparazione: 15 minuti. Cottura: 90 minuti.','1000 G Rotonda Di Vitello,
50 Cl Aceto Di Vino Bianco,
1 Cipolla,
6 Chiodi Di Garofano,
5 Grani Pepe Nero,
1 Pezzo Cannella,
Alcune Foglie Alloro,
Sale,
10 Acciughe Sotto Sale,
2 Noci Burro,
3 Tuorli D''uovo Sodo,
10 Capperi Sotto Sale','Prendete la rotonda della coscia o girello di un vitello di fassone, mettetelo in una terrina e copritelo con aceto ed acqua (mezzo litro di aceto bianco dovrebbe bastare), aggiungete la cipolla affettata grossolanamente, i chiodi di garofano, il pepe nero, la cannella, l''alloro e il sale. Lasciate la carne a macerare nella marinata almeno 12 ore, ovvero una notte. Adesso fate brasare il girello: prendete una casseruola, fatevi sciogliere due noci di burro e poi disponete la carne ben sgocciolata e fatela rosolare un po'' affinché faccia una sottile crosta. A questo punto aggiungete le acciughe dissalate e diliscate e fatele sciogliere nel burro, quindi versate nell''intingolo il tuorlo d''uovo sodo sbriciolato. Rimestate e aggiungete subito la marinata. Fate cuocere a casseruola scoperta fino a quando il sugo si è ben ristretto. La cottura, comunque, non deve essere troppo prolungata, altrimenti la carne, quando sarà servita fredda e a fette, apparirà asciutta e prosciugata dei suoi umori. Togliete la carne e affettatela non troppo sottilmente, versate sopra le fette il fondo di cottura dopo averlo passato al setaccio e guarnito coi capperi precedentemente lavati sotto l''acqua corrente. Il vitel tonné va servito freddo. Questo piatto, come avrete notato, nulla ha a che spartire col vitello tonnato odierno, vivanda nobilissima a base di carne di vitello lessa, tagliata e ricoperta con una salsa ottenuta da maionese, tonno e capperi e una spruzzata di succo di limone. Il francesismo tonné (ovvero tannè) starebbe per conciato, ossia accomodato, secondo Luciano De Giacomi. Ma significa pure scuro, cupo, come del resto appare la salsa d''acciughe che guarnisce questo piatto. Vino consigliato: Dolcetto di Dogliani.',2639);
INSERT INTO "ricette" VALUES (27470,'Vitello Tonnato Caldo','Carne','Vitello',6,' -','800 G Magatello Di Vitello,
40 G Burro,
Olio D''oliva,
1 Bicchiere Vino Bianco Secco,
1 Carota,
1 Costa Sedano,
100 G Tonno Sott''olio,
2 Acciughe Sotto Sale,
1 Limone,
Cetriolini Sott''aceto,
Sale,
Pepe','In una casseruola scaldate burro e olio e rosolatevi il magatello. Salate, pepate e dopo 5 minuti versate il vino. Lasciate evaporare. Aggiungete la carota e la costa di sedano interi e un bicchiere d''acqua. Coprite e continuate la cottura a fuoco basso per un''ora e mezzo. Ogni tanto girate la carne. Nel frattempo tritate il tonno, le acciughe dissalate e diliscate, alcuni cetriolini e diluite il tutto con il succo del limone. Togliete dalla pentola la carne, la carota e il sedano. Versatevi la salsa di tonno, amalgamatela al sugo di cottura. Tagliate la carne a fette non tanto spesse e ricoprite con la salsa calda. Vini di accompagnamento: Oltrepò Pavese Barbera DOC, Sangiovese Di Romagna DOC, Regaleali Rosato VdT Di Sicilia.',2202);
INSERT INTO "ricette" VALUES (27471,'Vitello Tonnato Freddo','Carne','Vitello',6,' -','800 G Magatello Di Vitello,
Olio D''oliva,
Aceto Di Vino,
1 Carota,
1 Cipolla,
Sedano,
Sale,
Per La Salsa:,
200 G Tonno Sott''olio,
3 Filetti D''acciughe,
2 Cucchiai Capperi,
2 Tuorli D''uovo Sodo,
Olio D''oliva,
1 Limone (succo)','Legate il magatello con lo spago bianco da cucina e lessatelo in acqua calda salata con carota, cipolla, sedano, un cucchiaio abbondante d''aceto e uno d''olio. Cuocete a fuoco basso e coperto per circa 2 ore. Raffreddate la carne nel suo brodo. Passate al tritatutto il tonno, i filetti d''acciughe, i capperi, i tuorli; diluite il composto con alcuni cucchiai d''olio, un po'' del brodo di cottura e il succo del limone. Slegate la carne, affettatela e ricopritela con la salsa. Lasciate insaporire alcune ore. Vini di accompagnamento: Riviera Ligure Di Ponente Pigato DOC, Vernaccia Di San Gimignano DOCG, Castel Del Monte Chardonnay DOC.',2971);
INSERT INTO "ricette" VALUES (27472,'Vittoria','Bevande','Gin',1,' -','2/3 Anisette,
1/3 Gin,
1 Cucchiaino Panna Fresca','Scuotere bene nello shaker con cubetti di ghiaccio. Servire nel flute.',314);
INSERT INTO "ricette" VALUES (27473,'Viva Villa','Bevande','Tequila',1,' -','1 Bicchierino Tequila,
1 Limone Piccolo (succo),
1 Cucchiaino Zucchero,
Per Il Bordo Del Bicchiere:,
Sale','Si prepara nello shaker con ghiaccio tritato. Si serve nel bicchiere basso e largo bordato con sale.',156);
INSERT INTO "ricette" VALUES (27474,'Vodka Arancio','Bevande','Vodka',1,' -','3/5 Succo D''arancia,
2/5 Vodka','Preparare nello shaker pieno a metà di ghiaccio tritato. Servire nel flute.',213);
INSERT INTO "ricette" VALUES (27475,'Vodka Collins','Bevande','Vodka',1,' -','1/2 Limone (succo),
4/4 Vodka,
1 Ciliegia,
2 Spicchi Arancia,
Acqua Gassata,
1 Cucchiaio Zucchero In Polvere','Mescolare vodka, succo di limone e zucchero con ghiaccio e mettere in un bicchiere Collins. Aggiungere alcuni cubetti di ghiaccio, completare con acqua gassata e agitare. Decorare con gli spicchi d''arancia e sopra mettere la ciliegia. Servire.',564);
INSERT INTO "ricette" VALUES (27476,'Vodka Collins (2)','Bevande','Vodka',1,' -','1/4 Succo Di Limone,
3/4 Vodka,
1/2 Cucchiaio Zucchero,
Per Completare:,
Soda Fredda,
Per Decorare:,
1 Fetta Arancia,
1 Ciliegia','Agitare nello shaker con ghiaccio in cubetti. Servire nel tumbler ampio, riempiendo il bicchiere a metà. Aggiungere soda ben fredda e decorare con una fetta d''arancia e una ciliegia.',426);
INSERT INTO "ricette" VALUES (27477,'Vodka Daisy','Bevande','Vodka',1,' -','1/8 Succo Di Limone,
1/8 Granatina,
6/8 Vodka,
Per Completare:,
Seltz,
Per Servire:,
Alcuni Cubetti Frutta','Scuotere nello shaker con ghiaccio in cubetti. Riempire a metà il cup, aggiungere seltz e cubetti di ghiaccio. Servire con cubetti di frutta.',435);
INSERT INTO "ricette" VALUES (27478,'Vodka E Tonic','Bevande','Vodka',1,' -','1/2 Acqua Tonica,
1/2 Vodka,
Per Servire:,
1 Fetta Limone','Preparare direttamente nel tumbler ampio, con cubetti di ghiaccio e una fetta di limone, mescolando dolcemente.',282);
INSERT INTO "ricette" VALUES (27479,'Vodka Gim','Bevande','Vodka',1,' -','1/4 Succo Di Limone,
3/4 Vodka,
Per Servire:,
1 Fetta Limone,
1 Scorza Di Pompelmo','Agitare nel mixer con poco ghiaccio tritato. Servire nel gotto basso, con una fetta di limone e una scorza di pompelmo.',364);
INSERT INTO "ricette" VALUES (27480,'Vodka Gimlet','Bevande','Vodka',1,' -','3/5 Vodka,
2/5 Succo Di Lime,
1 Cucchiaio Zucchero In Polvere','Agitare tutti gli ingredienti con ghiaccio, mettere in un bicchiere da cocktail e servire.',316);
INSERT INTO "ricette" VALUES (27481,'Vodka Gipsy','Bevande','Vodka',1,' -','1/4 Benedictine,
3/4 Vodka,
1 Spruzzo Angostura','Agitare nel mixer con ghiaccio in cubetti. Servire nel flute.',429);
INSERT INTO "ricette" VALUES (27482,'Vodka Grasshopper','Bevande','Vodka',1,' -','1/3 Vodka,
1/3 Crema Menta Verde,
1/3 Crema Cacao Bianca','Si prepara nello shaker con ghiaccio tritato.',310);
INSERT INTO "ricette" VALUES (27483,'Vodka Martini','Bevande','Vodka',1,' -','8/10 Vodka,
2/10 Vermouth Dry,
Per Guarnire:,
Scorza Di Limone','Si prepara nel mixing glass con cubetti di ghiaccio. Servire nella coppetta da cocktail ben fredda. Guarnire con scorza di limone.',459);
INSERT INTO "ricette" VALUES (27484,'Vodka Martini (2)','Bevande','Vermouth',1,' -','2 Cucchiaini Vermouth Dry,
5/5 Vodka,
Per Guarnire:,
1 Oliva Verde','Riempire il mixer per metà con cubetti di ghiaccio. Mettere vodka e vermouth nel mixer e agitare bene. Mettere in un bicchiere da cocktail il composto ottenuto. Guarnire con 1 oliva verde.',523);
INSERT INTO "ricette" VALUES (27485,'Vodka Martini (3)','Bevande','Vermouth Martini Dry',1,' -','2/3 Vermouth Martini Dry,
1/3 Vodka A 40 Gradi','Si prepara nello shaker.',304);
INSERT INTO "ricette" VALUES (27486,'Vodka Sour','Bevande','Vodka',1,' -','1/2 Limone (succo),
1/2 Spicchio Limone,
4/4 Vodka,
1/2 Cucchiaio Zucchero,
1 Ciliegia','Mescolare vodka, succo di limone e zucchero con ghiaccio e mettere in bicchiere per whisky. Decorare con il mezzo spicchio di limone e mettere sopra la ciliegia. Servire.',479);
INSERT INTO "ricette" VALUES (27487,'Vodka Special','Bevande','Vodka',1,' -','1/4 Succo Di Limone,
1/4 Crema Cacao,
2/4 Vodka,
Per Servire:,
1 Spolverata Cioccolato Grattugiato','Agitare energicamente e a lungo nello shaker con due cubetti di ghiaccio. Servire nel flute con un cubetto di ghiaccio e una spolverata di cioccolato grattugiato.',514);
INSERT INTO "ricette" VALUES (27488,'Vodka Sprint','Bevande','Vodka',1,' -','1/3 Crema Di Menta Verde,
1/3 Crema Cacao,
1/3 Vodka,
Per Servire:,
Cioccolato In Polvere','Scuotere a lungo ed energicamente nello shaker con due cubetti di ghiaccio. Servire nel flute con un cubetto di ghiaccio e una spolverata di cioccolato in polvere.',711);
INSERT INTO "ricette" VALUES (27489,'Vodka Stinger','Bevande','Vodka',1,' -','2/4 Crema Di Menta Bianca,
2/4 Vodka','Mescolare gli ingredienti con ghiaccio, mettere in un bicchiere da cocktail e servire.',345);
INSERT INTO "ricette" VALUES (27490,'Vodka Stinger (2)','Bevande','Vodka',1,' -','1/3 Crema Di Menta Bianca,
2/3 Vodka','Agitare nello shaker con due cubetti di ghiaccio. Servire nel flute.',380);
INSERT INTO "ricette" VALUES (27491,'Vodka Tonic','Bevande','Vodka',1,' -','1 Bicchierino Vodka,
Acqua Tonica,
Per Decorare:,
1 Scorzetta Di Limone','Versare la vodka sopra dei cubetti di ghiaccio nel bicchiere alto. Riempire di acqua tonica e decorare con una scorzetta di limone.',172);
INSERT INTO "ricette" VALUES (27492,'Vodka Vip','Bevande','Vodka',1,' -','1/2 Vermouth Dry,
1/2 Vodka,
Per Servire:,
2 Cipolline','Agitare nel mixer con ghiaccio in cubetti. Servire nel flute con due cipolline.',376);
INSERT INTO "ricette" VALUES (27493,'Voilà','Bevande','Vodka',1,' -','1/4 Succo Di Limone,
3/4 Vodka,
1 Cucchiaio Pernod,
1 Cucchiaio Kirsch','Agitare nello shaker con ghiaccio in cubetti. Servire nel flute.',467);
INSERT INTO "ricette" VALUES (27494,'Vol-au-vent','Antipasto','Pasta Sfoglia',4,' -','Pasta Sfoglia,
Farina,
Uova','Stendete la pasta sfoglia allo spessore di 1/2 centimetro e con lo stampino o con un bicchiere dal bordo infarinato ritagliate 18 dischetti del diametro di 6 centimetri circa. Mettetene da parte 6 e ritagliate al centro gli altri con uno stampino o con un bicchierino di 4 centimetri ottenendo così degli anelli. Se necessario impastate di nuovo la pasta avanzata. Sbattete l''uovo, pennellate il fondo dei dischetti grandi e adagiate sopra ciascuno un anello di pasta. Pennellate ogni anello quindi ricoprite ciascuno con un altro anello e pennellate ancora con l''uovo battuto. Allineate i vol-au-vent sulla placca del forno ricoperta con carta oleata e cuocete per 30 minuti nel forno già caldo a 220 gradi. Toglieteli quando sono gonfi e dorati. La pennellatura di uovo sbattuto serve per far aderire i vari strati di pasta e ottenere una superficie dorata. Attenzione però a non far colare l''uovo sui bordi altrimenti la pasta non gonfierà bene e i vol-au-vent risulteranno di forma irregolare. Se preparate più vol-au-vent di quanti ne servano potete congelare quelli in eccedenza. Procedete in questo modo: sovrapponete i vari strati di pasta senza pennellarli con l''uovo e avvolgete i vol-au-vent singolarmente nella pellicola facendoli quindi gelare. Riuniteli poi in un sacchetto e conservateli nel congelatore. Per cuocerli allineateli ancora congelati sulla placca del forno rivestita con un foglio di alluminio, pennellateli con l''uovo sbattuto e cuoceteli per 30 minuti nel forno già caldo a 220-240 gradi. Potete preparare allo stesso modo un solo vol-au-vent gigante, ritagliando un disco di pasta del diametro di circa 22 centimetri e 3 anelli proporzionati. Riempite i vol-au-vent solo all''ultimo momento. Se li preparate in anticipo tenete separatamente pasta e farcia e 15 minuti prima di servire accendete il forno a 190-200 gradi, quindi riempite i vol-au-vent e fateli scaldare per circa 10 minuti.