ettere la trota affumicata a pezzetti, il caprino, la ricotta, una macinata di pepe e amalgamare per 2 minuti aggiungendo un filo d''olio. Far tostare in forno i crostini, imburrarli e spalmarli con la crema ottenuta. Guarnire con fette di limone e servirli freschi.',7902);
INSERT INTO "ricette" VALUES (7725,'Crostini Al Fegato','Antipasto','Fegatini Di Pollo',4,'Preparazione: 30 minuti. Luogo: Trentino Alto-Adige. Luogo: Trentino.','1 Pancarré,
100 G Fegatini Di Pollo,
100 G Prosciutto Crudo,
5 Acciughe,
3 Cucchiai Brodo,
1 Pizzico Cannella,
1 Cucchiaio Aceto Di Vino,
Olio D''oliva','Pestare finemente il fegato, soffriggerlo in un po'' d''olio, aggiungere il prosciutto tagliato finemente con la mezzaluna, far passare nel tegame a fuoco moderato per 5-6 minuti, aggiungere le acciughe e lasciare che si sciolgano con il calore, aggiungere 3 cucchiai di brodo, 1 pizzico di cannella e 1 cucchiaio di aceto e controllare che il composto sia saporito di sale. Tagliare il pancarrè a metà e far dorare le fette da entrambi i lati, quindi porre la salsa su ogni fetta. Servire caldi.',2838);
INSERT INTO "ricette" VALUES (7726,'Crostini Al Formaggio Parmigiano Reggiano','Antipasto','Formaggio Parmigiano',6,' -','75 G Formaggio Parmigiano Reggiano Grattugiato,
100 G Panna,
3 Tuorli D''uovo,
Sale,
Pepe,
Farina,
Noce Moscata,
Pangrattato,
Olio Per Friggere,
100 Cl Besciamella','Alla besciamella raffreddata incorporate il parmigiano e due tuorli, la panna e una grattatina di noce moscata. Versare il composto in una placca imburrata formando uno strato alto circa mezzo centimetro, pareggiarne bene la superficie, poi lasciate riposare in frigorifero per 2 ore. Tagliare il composto in quadrati o in rombi, passarli nella farina poi nel tuorlo diluito con acqua, poi nel pangrattato e infine friggere nell''olio bollente. Servire ben caldi.',3582);
INSERT INTO "ricette" VALUES (7727,'Crostini Al Gorgonzola','Antipasto','Formaggio Gorgonzola',4,' -','100 G Formaggio Gorgonzola Dolce,,
3 Cucchiai Mascarpone,
Carote,
Crostini Ovali','Spezzettare in una ciotola il gorgonzola, unire il mascarpone e lavorare con un cucchiaio di legno fino ad ottenere una crema morbida. Suddividere il composto sui crostini e decorare con le carote fresche raschiate, lavate e tagliate a julienne.',943);
INSERT INTO "ricette" VALUES (7728,'Crostini Al Gorgonzola (2)','Antipasto','Formaggio Gorgonzola',4,' -','4 Fette Pane Casereccio,
60 G Formaggio Gorgonzola Piccante,
50 G Formaggio Stracchino,
Peperoncino In Polvere','In una ciotola mescolate a lungo i formaggi fino ad ottenere una crema quasi omogenea; insaporite il tutto con poco peperoncino. Distribuite il composto sulle fette di pane e passatele in forno caldo (170 gradi) per cinque minuti. Disponetele su un piatto da portata e servitele ben calde',938);
INSERT INTO "ricette" VALUES (7729,'Crostini Al Miele','Dessert','Miele',4,' -','4 Fette Pane Casereccio,
8 Cucchiai Miele,
20 Gherigli Di Noci,
Burro','Servendovi di un mixer, tritate grossolanamente le noci e riunitele in una terrina. Aggiungete il miele e mescolate con cura per pochi minuti, dopodichè, spalmate le fette di pane con il burro (che avrete tirato fuori dal frigorifero almeno 20 minuti prima dell''uso) e farcitele con il composto ottenuto. Per finire, disponete il tutto su una piastra da forno ed infornate per circa 5 minuti a 180 gradi. Suggerimento: ottimi da consumare per la prima colazione o per un nutriente spuntino pomeridiano.',2932);
INSERT INTO "ricette" VALUES (7730,'Crostini Al Paté Di Funghi','Antipasto','Funghi',4,'Preparazione: 20 minuti.','1 Uovo,
200 G Funghi Misti Surgelati,
1 Rametto Timo Fresco,
1 Cuore Insalata Lattuga (alcune Foglie),
2 Fette Pane Per Tramezzini Senza Crosta,
1 Cucchiaio Maionese,
1 Cucchiaio Yogurth Greco Denso,
20 G Burro,
Pepe,
Sale','Mettete il burro in una padellina antiaderente, unite i funghi, un pizzico di sale e qualche fogliolina di timo e cuocete con il coperchio per circa 10 minuti. Rassodate l''uovo in acqua per 10 minuti dal momento dell''ebollizione, scolatelo, raffreddatelo sotto l''acqua corrente e sgusciatelo. Riunite in un piccolo mixer i funghi, tranne qualche pezzetto che userete per decorare, l''uovo, la maionese, un pizzico di sale e uno di pepe, lo yogurth e mezzo cucchiaino di timo tritato. Frullate fino ad ottenere una crema omogenea. Ricavate dalle fette di pane otto tartine, tostatele leggermente sotto il grill del forno, spalmatele con il paté di funghi e uova e decorate a piacere con i funghi tenuti da parte e un pezzettino di foglia di lattuga.',714);
INSERT INTO "ricette" VALUES (7731,'Crostini Al Paté Tartufato','Antipasto','Tartufo',4,' -','Alcune Fette Pane Casereccio (fette Sottili),
Paté Al Tartufo Umbro,
Alcune Gocce Succo Di Limone,
Poco Prezzemolo Finemente Tritato','Preparate alcune fette sottili di pane casereccio, tostatele al forno e ancora calde spalmatele con uno strato di paté umbro al tartufo, aggiungete qualche goccia di succo di limone e un poco di prezzemolo finemente tritato. Possibilmente servite calde.',690);
INSERT INTO "ricette" VALUES (7732,'Crostini Al Prosciutto E Noci','Antipasto','Prosciutto Cotto',4,'Preparazione: 20 minuti. Luogo: Trentino Alto-Adige. Luogo: Trentino.','1 Pancarré,
Gherigli Di Noci,
100 G Prosciutto Cotto,
3 Cucchiai Formaggio Morbido Saporito,
Burro','Tritare finemente il prosciutto, incorporarvi il formaggio mescolando bene, in modo che il composto risulti omogeneo. Tagliare in quattro le fette di pancarrè e soffriggerle nel burro da un solo lato. Spalmare il composto di prosciutto e formaggio sul lato non fritto delle fette. Guarnire ogni fetta con mezzo gheriglio di noce.',3537);
INSERT INTO "ricette" VALUES (7733,'Crostini Al Radicchio','Antipasto','Radicchio',6,' -','1 Filoncino Pane Bianco,
1/2 Cespo Radicchio Di Chioggia,
1 Cipolla Bianca,
2 Formaggi Caprini,
Olio D''oliva,
Aceto Di Vino,
Sale','In un tegame fate scaldare due cucchiai d''olio e lasciatevi sfinire la cipolla tagliata a fettine molto sottili. Quando sono diventate trasparenti unite i caprini e mescolate riducendo a una crema. Regolate il sale. Tagliate a striscioline il radicchio e mescolatelo alla crema tenendo sul fuoco mezzo minuto o giusto il tempo per amalgamare bene il tutto. Ritirate dal fuoco, spruzzate il composto con un po'' di aceto e mettetelo a mucchietti sulle fettine di pane. Servite freddo, ma non da frigorifero.',2532);
INSERT INTO "ricette" VALUES (7734,'Crostini Al Rafano','Antipasto','Rafano',4,' -','Burro,
1 Pezzo Rafano,
Sale,
Pane Casereccio Per Crostini','Grattugiare un pezzo di rafano ed unirvi in una ciotola una uguale quantità di burro; aggiustare di sale e lavorare il burro con una forchetta impastando il tutto. Tostare in forno i crostini di pane e spalmarvi la crema di rafano. Servire come antipasto piccante.',1063);
INSERT INTO "ricette" VALUES (7735,'Crostini Al Robiola','Antipasto','Formaggio Robiola',4,' -','Pane Per Circa 20 Crostini,
150 G Trota Affumicata,
150 G Formaggio Robiola,
100 G Ricotta,
Burro,
2 Limoni,
1 Macinata Pepe Bianco,
1 Filo Olio D''oliva Extra-vergine','In un mixer mettere la trota affumicata a pezzetti, il robiola, la ricotta, una macinata di pepe e amalgamare per 2 minuti aggiungendo un filo d''olio. Far tostare in forno i crostini, imburrarli e spalmarli con la crema ottenuta. Guarnire con fette di limone e servirli freschi.',7915);
INSERT INTO "ricette" VALUES (7736,'Crostini Al Tartufo','Antipasto','Tartufo',4,' -','1 Tartufo,
6 Fette Pancarré,
1 Cucchiaio Burro,
1/2 Spicchio Aglio,
Prezzemolo,
3 Acciughe,
2 Cucchiai Olio D''oliva','Lavate, togliete le lische e tritate le acciughe con mezzo spicchio di aglio e prezzemolo. In un tegame mettete 1 cucchiaio di burro e 2 cucchiai di olio e fateci rosolare il composto che avete appena preparato. Dopo 3 minuti di cottura aggiungeteci un tartufo a fette e lasciate cuocere per 5 minuti. Tagliate a metà ogni fetta di pane in modo da formare dei triangoli, passateli nel burro e disponeteci sopra la salsa al tartufo che avrete preparato.',1835);
INSERT INTO "ricette" VALUES (7737,'Crostini Al Tartufo (2)','Antipasto','Tartufi Bianchi',4,'Luogo: Marche.','8 Fettine Pane Abbrustolito,
20 Cl Brodo,
30 G Burro,
80 G Formaggio Parmigiano Grattugiato,
1/2 Limone (succo),
80 G Tartufi Bianchi,
Sale,
Pepe','Sciogliere il burro in un padellino e, con il brodo e il parmigiano, formare una salsa omogenea, non troppo densa, salare e pepare. Spruzzare di limone le fettine di pane che verranno ricoperte dalla salsa calda e dai tartufi tagliati a lamelle.',1754);
INSERT INTO "ricette" VALUES (7738,'Crostini Al Tartufo Bianco','Antipasto','Tartufo Bianco',4,'Luogo: Piemonte.','50 G Tartufo Bianco D''alba,
100 G Burro,
1 Acciuga Sotto Sale,
1 Fettina Aglio,
Poco Prezzemolo,
4 Fette Pancarré,
Olio D''oliva','Fare un trito con l''acciuga dissalata e diliscata, l''aglio e il prezzemolo. Spazzolare il tartufo. In un tegame mettere 30 g di burro e qualche cucchiaio d''olio,unirvi il trito e far rosolare delicatamente a fuoco basso. Aggiungere il tartufo affettato sottilmente e cuocere per 10 minuti a fuoco molto basso. Tagliare a metà le fette di pancarré e friggerle nel restante burro. Disporvi sopra la salsina preparata e servire i crostini ben caldi.',2487);
INSERT INTO "ricette" VALUES (7739,'Crostini Al Tartufo Nero','Antipasto','Tartufi Neri',6,' -','6 Fette Pane,
100 G Tartufi Neri A Fettine O In Paté,
Olio D''oliva Extra-vergine,
1 Spicchio Aglio,
Sale,
Pepe,
Succo Di Limone','Pestare i tartufi assieme all''aglio, condirli poi con olio, sale, pepe e limone, quanto basta, amalgamare il tutto a crudo, tostare le fette di pane, insaporire con un poco di olio e limone, quindi spalmare la salsa di tartufo che avete preparato, servire subito.',1604);
INSERT INTO "ricette" VALUES (7740,'Crostini Al Tonno','Antipasto','Tonno Al Naturale',8,' -','4 Patate,
250 G Tonno Al Naturale,
2 Acciughe,
1 Limone,
1 Filone Pane Integrale Cotto A Legna,
1 Ciuffo Prezzemolo,
Olio D''oliva Extra-vergine,
Sale Marino Integrale','Lessare le patate, quindi sbucciarle. In un mixer mettere le patate a tocchi, il tonno ben sgocciolato, il prezzemolo, le acciughe e frullare, facendo cadere a filo una emulsione di succo di limone olio e sale, fino ad ottenere una crema omogenea. Adagiare in scodelline individuali, decorare con prezzemolo e servire con crostini di pane tostato.',3119);
INSERT INTO "ricette" VALUES (7741,'Crostini Alla Cecco Beppe','Antipasto','Cetriolini',4,' -','30 G Burro,
2 Cucchiai Olio D''oliva,
2 Spicchi Aglio,
1 Rametto Rosmarino,
Alcune Foglie Salvia,
Alcune Foglie Alloro,
250 G Milza,
Sale,
Pepe,
1/2 Bicchiere Brodo Di Dadi,
4 Filetti D''acciughe,
5 Cetriolini,
60 G Capperi,
6 Fette Pancarré','Fate scaldare il burro e l''olio in un tegame e ponetevi ad appassire un trito finissimo di aglio, rosmarino, salvia e alloro. Dividete la milza in pezzetti e fatela rosolare, a fuoco allegro, nel condimento, rimestando velocemente. Insaporite poi con sale e pepe e bagnate con il vino. Quando questo sarà evaporato, irrorate con mezzo bicchiere di brodo e proseguite la cottura per 15 minuti. Trascorso questo tempo, passate la milza con il suo intingolo al passaverdura o al setaccio e rimettetela nella casseruola, insieme con un trito fine di acciughe, cetriolini e capperi. Bagnate con il restante brodo e fate addensare il composto. Dividete il pancarré diagonalmente e liberatelo della crosta. Tostate i triangoli così ottenuti per 2-3 minuti in forno caldo a 220 gradi (o nel tostapane), quindi copriteli con il composto preparato e disponeteli su un piatto caldo, per servirli subito.',2094);
INSERT INTO "ricette" VALUES (7742,'Crostini Alla Crema Di Formaggio','Antipasto','Formaggio Parmigiano',4,' -','100 G Farina,
80 Cl Latte,
60 G Formaggio Parmigiano,
Alcuni Crostini Quadrati Tagliati Nelle Fette Di Pane A Cassetta Abbrustolite','Fate una besciamella molto soda con farina, latte e parmigiano. Lavorate la besciamella fino a ottenere una salsa densa e bene omogenea, che stenderete poi sui crostini. Al momento di servire, passate i crostini per qualche minuto appena nel forno ben caldo.',1336);
INSERT INTO "ricette" VALUES (7743,'Crostini Alla Milza','Antipasto','Milza Di Vitellone',4,'Preparazione e cottura: 40 minuti. Luogo: Trentino Alto-Adige. Luogo: Trentino.','1 Pancarré,
1 Milza Di Vitellone,
3 Acciughe,
1 Cipolla Piccola,
1 Spicchio Aglio,
1/2 Carota,
Olio D''oliva,
Burro,
Vino Bianco,
Brodo Vegetale','Tagliare finemente 1 cipolla piccola, 1 spicchio d''aglio e 1/2 carota e farli rosolare in un tegame con olio e un po'' di burro. Aggiungere la milza (alla quale sarà stata tolta la pelle) e far cuocere aggiungendo un po'' di vino bianco e un po'' di brodo vegetale. Quando il composto è cotto, passarlo al tritatutto assieme alle acciughe, quindi rimettere nel tegame e tenere in caldo mentre si prepara il pancarrè fritto nel burro. Spalmare il composto sulle fette e portare in tavola i crostini ben caldi.',3521);
INSERT INTO "ricette" VALUES (7744,'Crostini Alla Milza In Brodo','Primo','Milza Di Vitello',4,'Cottura: 10 minuti. Luogo: Trentino Alto-Adige. Luogo: Trentino.','Brodo,
1 Milza Di Vitello,
1 Tuorlo D''uovo,
Pane Raffermo,
Latte,
Sale,
Burro','Togliere dall''involucro la parte molle della milza di vitello e metterla in una scodella con un po'' di sale e un tuorlo d''uovo, spalmarla su delle fette di pane raffermo che in precedenza passate rapidamente nel latte. Rosolare quindi le fette in un po'' di burro, disporle nei piatti e coprirle con il brodo fumante.',1645);
INSERT INTO "ricette" VALUES (7745,'Crostini Alla Pancetta','Antipasto','Pancetta',4,' -','4 Fette Pane Casereccio,
100 G Formaggio Fontina,
4 Fette Pancetta Affumicata,
Pepe,
Nero','Disponete il pane sulla placca del forno unta d''olio. Su ogni fetta adagiatene una di fontina tagliata su misura, spolverizzate con poco pepe, coprite con le fettine di pancetta. Mettete in forno caldo per circa dieci minuti. Quando la pancetta diventa trasparente e leggermente dorata, ritirate i crostini e serviteli subito ben caldi',3337);
INSERT INTO "ricette" VALUES (7746,'Crostini Alla Ponticiana','Antipasto','Prosciutto Crudo',4,' -','Alcune Fette Pane Casereccio,
2 Mozzarelle,
150 G Prosciutto Crudo,
Funghi Trifolati,
Burro,
Sale,
Pepe','Rosolate nel burro le fette di pane. Quando saranno dorate guarnitele con qualche fettina di mozzarella, una fetta di prosciutto crudo e una cucchiaiata di funghi trifolati. Passate al forno caldo per qualche minuto e servite.',2888);
INSERT INTO "ricette" VALUES (7747,'Crostini Alla Romana','Antipasto','Prosciutto Cotto',4,'Luogo: Lazio. Luogo: Roma.','4 Fette Pancarré,
4 Fette Sottilette,
1 Uovo,
Sale,
4 Fette Prosciutto Cotto,
1 Cucchiaio Burro,
1 Cucchiaio Pasta D''acciughe,
Olio D''oliva','Impanare nell''uovo il pancarré, metterlo in 1 padella con un po'' d''olio e rigirarlo quasi subito. Porre quindi su ogni fetta di pane la sottiletta e il prosciutto cotto. Sciogliere in 1 pentolino la pasta d''acciughe con un po'' di burro. Prendere il sughetto che si è formato e versarlo sulle fette di pane tolte dal fuoco e servire caldissime.',3084);
INSERT INTO "ricette" VALUES (7748,'Crostini Alla Toscana','Antipasto','Vitello',4,'Luogo: Toscana. Preparazione: 60 minuti.','500 G Pane Toscano Tagliato A Fette,
150 G Milza Di Vitello,
2 Fegatini Di Pollo,
Capperi,
1/2 Cipolla,
1 Gambo Sedano,
2 Bicchieri Vino Bianco Secco,
10 Cl Brodo,
Sale,
Pepe,
Olio D''oliva','Le operazioni preliminari sono le più lunghe: spellate la milza e togliete il fiele ai fegatini, tritate il sedano e la cipolla e fateli rosolare in poco olio, aggiungendo poi milza e fegatini tagliati a pezzetti. Lasciate cuocere per alcuni minuti, quindi versate il vino bianco e fate evaporare, dopo aver aggiunto, in giusta misura, sale, pepe e capperi tritati. Fate cuocere per mezz''ora bagnando di tanto in tanto con un po'' di brodo. Passate il composto nel frullatore e nel frattempo fate friggere le fette di pane toscano nell''olio bollente. Quando sono ben dorate fatele asciugare su un foglio di carta assorbente e spalmatele con il composto di milza e fegatini.',2793);
INSERT INTO "ricette" VALUES (7749,'Crostini Alla Toscana (2)','Antipasto','Pomodori',4,'Luogo: Toscana.','4 Fette Pane Toscano,
2 Pomodori,
1 Cipollina,
Basilico,
Olio D''oliva,
4 Filetti D''acciughe,
Sale','Tostate il pane, sopra ogni fetta mettete un filetto d''acciughe, una rondella di pomodoro, poca cipolla tritata, basilico. Irrorate con un filo d''olio, salate. Passate pochi minuti in forno caldo e servite. Vini di accompagnamento: Tutti gli Spumanti classificati ''Brut'', Vino ''Novello'' o il tradizionale Chianti ''giovane'' DOCG (dell''ultima vendemmia).',1341);
INSERT INTO "ricette" VALUES (7750,'Crostini Alla Toscana Con Le Acciughe','Antipasto','Acciughe',6,'Luogo: Toscana.','Pane Di Segale,
200 G Acciughe Sotto Sale,
50 G Capperi,
1 Spicchio Aglio,
1 Cipolla Piccola,
Prezzemolo,
Mollica Di Pane,
Peperoncino,
6 Cucchiai Olio D''oliva,
3 Cucchiai Aceto Di Vino','Dissalate, diliscate, lavate le acciughe lasciandole scolare su un piatto inclinato. Tritate insieme prezzemolo, mezza cipolla, uno spicchio d''aglio, capperi, peperoncino e la mollica di pane bagnata e strizzata. Amalgamate con sei cucchiai d''olio e tre d''aceto. Ponete in un''insalatiera uno strato di acciughe alternato a uno di salsa e lasciate riposare per un giorno. Al momento di servire tostate le fette di pane, spalmatele con un velo di burro e disponetevi sopra il composto di acciughe.',2914);
INSERT INTO "ricette" VALUES (7751,'Crostini Alle Cipolle','Antipasto','Cipolline',4,' -','12 Fettine Pane Tipo Filoncino,
2 Cipolle Bianche Piccole,
60 G Formaggio Parmigiano,
1/2 Tazza Besciamella,
3 Cucchiai Olio D''oliva,
Sale,
Pepe Bianco','In un tegame scaldate l''olio e lasciatevi sfinire le cipolle tagliate a fettine molto sottili. Salate. Quando sono diventate trasparenti, ritirate dal fuoco. Sgocciolatele bene, fatele raffreddare. Unite alla besciamella (potete usare anche quella già pronta) le cipolle, il parmigiano grattugiato, regolate sale e pepe. Spalmate il composto sulle fettine di pane e scaldate in forno a 220 gradi per 10 minuti. Servite subito.',1725);
INSERT INTO "ricette" VALUES (7752,'Crostini Barny','Antipasto','Pancetta Affumicata',4,' -','8 Fette Pancarré,
300 G Pancetta Affumicata A Dadini,
300 G Mozzarella Tritata,
Burro,
1 Cucchiaio Pinoli','Eliminate la crosta dalle fette di pancarré e dividetele a metà. A parte, in una padella antiaderente, fate tostare per circa 5 minuti la pancetta affumicata, dopodichè, nella stessa padella, insieme al grasso di cottura, fate dorare le fette di pane. Successivamente, disponete i crostini in una teglia unta di burro e cospargeteli con la pancetta, i pinoli e la mozzarella tritata. Infornate il tutto per circa 5-7 minuti e servite immediatamente. Ottimi da mangiare in un solo boccone e ideali per una cena in piedi o con l''aperitivo.',4557);
INSERT INTO "ricette" VALUES (7753,'Crostini Caldi Al Tartufo','Antipasto','Tartufo',4,' -','1 Acciuga,
1 Spicchio Aglio,
1 Mazzetto Prezzemolo,
100 G Tartufo D''alba,
130 G Burro,
2 Cucchiai Olio D''oliva,
6 Fette Pane (o Pane Integrale)','Diliscate l''acciuga, lavatela e pestatela nel mortaio con l''aglio e il prezzemolo, fino ad avere ottenuto un composto liscio e omogeneo. Pulite bene i tartufi, spazzolandoli, lavandoli e asciugandoli. Mettete in un tegame 30 g di burro e l''olio e fatevi rosolare, a fiamma bassa, il trito preparato. Dopo qualche istante unite i tartufi affettati finemente (meglio se tagliati con l''apposito utensile). Mescolate e fate cuocere, sempre a fiamma bassa, per 10 minuti. Nel frattempo tagliate a metà le fette di pane a cassetta, formando dei triangoli, e friggetele nel restante burro. Quando i crostini saranno ben dorati, scolateli e copriteli con i tartufi; disponeteli su un piatto resistente al calore e passateli in forno a calore medio per 5 minuti, quindi serviteli.',2239);
INSERT INTO "ricette" VALUES (7754,'Crostini Caldi Di Pesce','Antipasto','Totano',4,' -','1 Totano Piccolo,
2 Polpettini,
Muscoli,
Arselle,
Gamberetti,
1/2 Bicchiere Olio D''oliva,
Aglio,
Pepe,
Prezzemolo,
Sale','Pulire i due polpettini ed il totano, aprire i muscoli, le arselle e sgusciare i gamberi. Tagliare tutto a piccoli pezzi. Mettere al fuoco in mezzo bicchiere d''olio. Quando è un poco rosolato aggiungere un poco di vino bianco, prezzemolo e aglio tritati più un poco di pepe. Controllare il sale. Lasciare cuocere bene a fuoco vivo fino a cottura del pesce che triterete poi, il più finemente possibile, assieme agli odori già cotti. Si formerà un amalgama. Preparare le fette di pane sottili e farle abbrustolire. Ancora calde, bagnarle.',1967);
INSERT INTO "ricette" VALUES (7755,'Crostini Casalinghi Alla Rucola','Antipasto','Acciughe',4,' -','4 Fette Pane Casereccio,
4 Fette Formaggio Fondente,
4 Filetti D''acciughe,
1 Mazzetto Insalata Rucola,
Latte,
Olio D''oliva,
Aceto Di Vino,
Sale,
Pepe','Lavate la rucola, spezzettatela a mano e conditela con olio, aceto, sale e pepe. Ungete d''olio la placca del forno, disponetevi le fette di pane, inumiditele con un po'' di latte e un filo d''olio. Fatele dorare a 180 gradi per dieci minuti. Ritirate la placca, sistemate al centro di ogni fetta un filetto d''acciughe e coprite con una fetta di formaggio. Ponete di nuovo in forno e togliete appena la superficie diventa dorata. Disponete i crostini su un piatto da portata e cospargeteli con la rucola. Servite.',2352);
INSERT INTO "ricette" VALUES (7756,'Crostini Con Acciughe E Fegatini','Antipasto','Acciughe',4,' -','200 G Fegatini Di Pollo,
50 G Burro,
2 Acciughe,
1/2 Cucchiaio Farina,
1 Manciata Capperi,
Alcune Fette Pancarré (o Pane Casereccio),
Sale,
Pepe,
Per Friggere I Crostini:,
Olio D''oliva','Tritare i fegatini di pollo molto finemente e metterli a rosolare nel burro già caldo, in padella. Lasciare soffriggere a fuoco non troppo alto, aggiungendo di quando in quando qualche cucchiaio di acqua, affinché non diventino troppo secchi. Tritare intanto le acciughe dissalate e diliscate insieme ai capperi e aggiungerli ai fegatini, mescolare e procedere nella cottura per qualche minuto, dosando di sale e pepe. Infine stemperare nel composto la farina bianca diluita in poca acqua, mescolare, lasciare sul fuoco ancora per pochi minuti fino a cottura e a salsa resa ben omogenea. Fritte nel frattempo le fette di pane nell''olio (o se si preferisce, nel burro), cospargere con il composto i crostini ancora caldi e servire.',2369);
INSERT INTO "ricette" VALUES (7757,'Crostini Con Acciughe E Fichi','Antipasto','Acciughe',4,' -','8 Granetti,
12 Fichi Molto Maturi,
4 Filetti D''acciughe,
1 Spicchio Aglio Sbucciato,
Olio D''oliva Extra-vergine','Sbucciare i fichi e frullate la loro polpa con i filetti d''acciughe, antecedentemente ben lavati e tritati, e lo spicchio d''aglio. Bagnate con un filo d''olio d''oliva i granetti. Spalmate il composto sopra i granetti e otterrete un piatto incantevole per stuzzicare l''appetito. Marisa aggiunge che si tratta di una antica ricetta mediterranea con molta probabilità di origine corsa.',1476);
INSERT INTO "ricette" VALUES (7758,'Crostini Con Alici','Antipasto','Acciughe',4,'Luogo: Lazio.','300 G Mozzarella,
150 G Burro,
Pane Casereccio,
Alcuni Cucchiai Latte,
2 Acciughe Salate, Pulite E Diliscate,
Sale,
Pepe','Tagliare il formaggio a fettine e condirlo con sale e pepe. Tagliare il pane nello stesso formato del formaggio e infilare in uno spiedo, alternandole, una fetta di pane e una di mozzarella, pressandole fino a riempire lo spiedo. Disporre gli spiedini in una teglia e infornare a 200 gradi per una ventina di minuti, spennellando ogni tanto col burro fuso. In un padellino, soffriggere il restante burro con le due acciughe pestate; allungare con poco latte bollente e versare questa salsina sugli spiedini disposti in un piatto si servizio caldo. Servire subito. ',2155);
INSERT INTO "ricette" VALUES (7759,'Crostini Con Bottarga','Antipasto','Bottarga',4,' -','Alcune Fette Pane,
Burro,
Bottarga','Tostare delle fette di pane; per ogni fetta stendere sopra un velo di burro e una fettina di bottarga.',1414);
INSERT INTO "ricette" VALUES (7760,'Crostini Con Bottarga E Pomodoro','Antipasto','Bottarga',4,' -','Alcune Fette Pane,
Burro,
Bottarga,
Pomodoro','Tostare delle fette di pane; per ogni fetta stendere sopra un velo di burro, una fettina di bottarga e una fettina di pomodoro.',1446);
INSERT INTO "ricette" VALUES (7761,'Crostini Con Champignon','Antipasto','Funghi Champignon',4,' -','400 G Funghi Champignon,
1 Cipolla Media,
2 Spicchi Aglio,
2 Cucchiai Olio D''oliva Extra-vergine,
50 G Pancetta Magra,
2 Cucchiai Passata Di Pomodoro,
Prezzemolo Tritato,
20 Fette Sottili Pane','Mondate i funghi come di consueto, quindi lavateli rapidamente ed asciugateli. Tritate finemente la cipolla insieme agli spicchi d''aglio e la pancetta (potete tritare tutti e tre questi ingredienti assieme, mettendoli nel mixer). Scaldate l''olio in un largo tegame e, a fuoco moderato, fate rosolare il tutto. Nel frattempo mettete i funghi sul tagliere e tritateli grossolanamente con un coltello e, quando il soffritto sarà pronto, versateli nel tegame insieme alla passata di pomodoro. Mescolate, insaporite con sale ed un''abbondante macinata di pepe e lasciate cuocere per una ventina di minuti fino a che i funghi si saranno asciugati. Togliete la crosta alle fettine di pane e tostatele leggermente. Disponetele poi su un piatto di portata e distribuitevi il composto di funghi spolverando di prezzemolo tritato. Serviteli ben caldi insieme ad un bicchiere di Vernaccia fresca (o analogo).',742);
INSERT INTO "ricette" VALUES (7762,'Crostini Con Crema Di Ceci','Antipasto','Ceci',4,' -','1 Scatola Ceci Lessati,
1 Carota,
4 Fette Pancarré,
1 Costa Sedano,
3 Cucchiai Olio D''oliva Extra-vergine,
8 Olive Nere Snocciolate,
1 Cucchiaio Formaggio Pecorino Grattugiato,
1/2 Cucchiaino Timo Grattugiato,
1/2 Cucchiaino Maggiorana Grattugiata,
1 Spicchio Aglio,
1 Pizzico Semi Di Sesamo,
Sale,
Pepe','Scolate i ceci dal liquido di conservazione, risciacquateli, quindi sgocciolateli bene e travasateli nel mixer elettrico. Unite la costola di sedano e la carota raschiata tagliate a pezzetti e lo spicchio d''aglio, poi frullate i vari ingredienti fino a ottenere un composto liscio e omogeneo. Raccoglietelo in una terrina,incorporatevi il pecorino grattugiato, l''olio e condite la preparazione con una presa di sale e con un pochino di pepe macinato al momento. Insaporitela infine con il trito di erbe aromatiche e con i semi di sesamo leggermente tostati. Private ora le fette di pancarré della crosticina, dividetele a metà diagonalmente e lasciatele tostare leggermente in forno caldo. Distribuite sopra i crostini la crema di ceci preparata e decorate ogni crostino con le olive nere.',2650);
INSERT INTO "ricette" VALUES (7763,'Crostini Con Fegatini Di Pollo','Antipasto','Fegatini Di Pollo',6,' -','Pane Integrale,
6 Fegatini Di Pollo,
2 Tuorli D''uovo,
1 Limone,
1 Carota,
1/2 Cipolla,
1 Costa Sedano,
1 Cucchiaio Capperi,
Vino Bianco Secco,
Aceto Di Vino,
Olio D''oliva,
Sale,
Pepe','Preparate un battuto con carota, cipolla e sedano e fatelo appassire in una casseruolina con due cucchiai d''olio. Aggiungete i fegatini lavati, passati nell''aceto e asciugati. Spruzzate con mezzo bicchiere di vino. Regolate sale e pepe, lasciate rosolare mescolando. Togliete i fegatini, tritateli finemente e rimetteteli nel recipiente perché insaporiscano ancora 2 minuti. Ritirate dal fuoco e incorporatevi i tuorli d''uovo sbattuti con il succo di limone filtrato al colino. Spalmate sulle fette di pane leggermente tostate e decorate con i capperi. Servite. Vini di accompagnamento: Breganze Pinot Nero DOC, Aprilia Merlot DOC, Cirò Rosato DOC.',1891);
INSERT INTO "ricette" VALUES (7764,'Crostini Con Fegatini E Prosciutto','Antipasto','Fegatini Di Pollo',6,' -','Pane Casereccio,
150 G Fegatini Di Pollo,
130 G Prosciutto Crudo,
40 G Burro,
3 Cucchiai Olio D''oliva,
1 Cipolla,
Latte (o Brodo),
2 Foglie Salvia,
8 Rametti Rosmarino','In una casseruola di grandezza medio-piccola scaldate metà burro con l''olio, insaporitevi il prosciutto e la cipolla tritati e, per almeno mezz''ora, mescolate con pazienza aggiungendo ogni tanto brodo o latte tiepidi in modo da mantenere al composto una certa umidità. Aggiungete i fegatini tagliati a pezzetti e le foglie di salvia. Fate bollire per 3 minuti esatti sempre mescolando. Ritirate dal fuoco, tritate il composto e ponetelo di nuovo sul fornello. Portate a bollore unendo alcune gocce di brodo o di latte se occorre. Amalgamate al composto il burro crudo avanzato, fate cuocere ancora 3 minuti e spegnete. Tagliate il pane, distribuitevi sopra il composto di fegatini. Sul fondo di un piatto da portata disponete a grata i rametti di rosmarino e sopra adagiatevi i crostini. Vini di accompagnamento: Tutti i vini ''novelli'' o Bardolino DOC.',2541);
INSERT INTO "ricette" VALUES (7765,'Crostini Con Fonduta','Antipasto','Formaggio Fontina',4,' -','Per La Fonduta:,
300 G Formaggio Fontina,
1 Bicchiere Latte,
Sale,
50 G Burro,
3 Tuorli D''uovo,
1 Tartufo,
Per I Crostini:,
16 Fette Pane,
150 G Burro','Per prima cosa predisponete la fontina per la fonduta: privatela della crosta, tagliatela a dadini e mettetela in una casseruola di smalto (o anche in una ciotola); copritela con il latte, insaporitela con una presa di sale e lasciatela riposare, coperta, per 3 ore. Poco prima che scada questo tempo, cominciate a preparare i crostini. Tagliate il pancarré a fette alte circa un dito; poi con uno stampino tagliapasta rotondo ricavate da ogni fetta un disco. Friggete i crostini, pochi alla volta, nel burro spumeggiante (non mettete il burro tutto insieme nella padella, ma aggiungetelo ogni volta che friggete), lasciandoli dorare da entrambe le parti; quindi distribuiteli in quattro casseruoline di terracotta da porzione, mettendoli leggermente sovrapposti, e teneteli in caldo nel forno (prima acceso e poi spento). Ora ponete sulla fiamma una casseruola di smalto con il quantitativo di burro indicato per la fonduta. Quando il condimento si sarà fuso, unitevi la fontina con tutto il suo latte. Fate sciogliere il formaggio a fiamma bassissima (meglio ancora sarebbe a bagnomaria), mescolando continuamente con un cucchiaio di legno o sbattendo con una frustina, fino ad aver ottenuto una crema densa e omogenea. Incorporate allora i tre tuorli, amalgamando bene, poi levate dal fuoco; regolate di sale e, se volete, unite un buon pizzico di pepe bianco. Versate la fonduta, ancora ben calda, sui crostini di pane caldi e affettatevi sopra una o più lamelle di tartufo (questo non è proprio indispensabile per la buona riuscita del piatto). Servite subito, caldissimo.',5299);
INSERT INTO "ricette" VALUES (7766,'Crostini Con Funghi E Capperi','Antipasto','Funghi Porcini',6,' -','1 Filone Di Pane,
300 G Funghi Porcini,
1 Cucchiaio Capperi,
1 Spicchio Aglio,
Brodo,
Prezzemolo,
1/2 Cucchiaio Maggiorana Tritata,
Olio D''oliva,
Sale,
Pepe','Pulite i funghi con uno spazzolino morbido e un panno umido. Tritateli e rosolateli in un padellino con alcuni cucchiai d''olio, uno spicchio d''aglio e la maggiorana. Cuocete a fuoco medio per 20 minuti versando del brodo quando occorre. Aggiungete un cucchiaio di capperi e un po'' di prezzemolo tritati. Salate e pepate. Rimettete sul fuoco e fate asciugare il liquido formatosi. Spalmate sulle fettine di pane abbrustolite. Vini di accompagnamento: Trentino Chardonnay (anche ''Spumante'') DOC, Colli Martani Grechetto DOC, Fiano Di Avellino DOC.',3655);
INSERT INTO "ricette" VALUES (7767,'Crostini Con Funghi In Guazzetto','Antipasto','Funghi',6,' -','Pane Toscano,
300 G Funghi Misti,
2 Salsicce Fresche,
150 G Pomodori Pelati,
Aglio,
Prezzemolo,
Alcune Foglie Menta,
1 Bicchiere Vino Bianco Secco,
Brodo,
Olio D''oliva,
Sale,
Pepe','Tritate la salsiccia, uno spicchio d''aglio e un po'' di prezzemolo, mettete a rosolare in un tegame con poco olio. Bagnate con il vino e fate evaporare. Aggiungete i funghi grossolanamente tritati, lasciate insaporire alcuni minuti e unite i pelati. Portate a cottura versando il brodo a mano a mano che occorre. Regolate sale e pepe. Abbrustolite le fette di pane. Strofinatele con l''aglio e sopra distribuite il composto di funghi. Guarnite con foglioline di menta fresca e servite subito. Vini di accompagnamento: Trentino Marzemino DOC, Chianti Colli Aretini DOCG, Copertino Rosato DOC.',2022);
INSERT INTO "ricette" VALUES (7768,'Crostini Con Gamberi E Asparagi','Antipasto','Gamberi',4,' -','4 Fette Pane Casereccio,
16 Gamberoni,
16 Asparagi,
Aglio,
Prezzemolo,
1 Limone,
Olio D''oliva Extra-vergine,
Sale Di Cervia,
Pepe Bianco','Lavare i gamberi, cuocerli a vapore e sgusciarli. Pulire gli asparagi, spezzarli, lavarli e cuocerli nell''asparagiera. Abbrustolire leggermente il pane, strofinarlo con aglio e metterlo in un piatto. Adagiarvi sopra i gamberi e gli asparagi e condire con sale, succo di limone, olio e pepe.',2156);
INSERT INTO "ricette" VALUES (7769,'Crostini Con Il Caviale','Antipasto','Caviale',4,' -','8 Fette Pancarré,
Caviale,
Burro,
Limone,
Prezzemolo','Fate abbrustolire leggermente le fette di pane, imburratele. Condite il caviale con il succo di limone, fate uno strato sui crostini. Potrete usare caviale nero e caviale rosso per ottenere un piatto dall''aspetto più decorativo; Servite i crostini sul piatto da portata ornato con fettine di limone e ciuffi di prezzemolo.',2341);
INSERT INTO "ricette" VALUES (7770,'Crostini Con Il Pompelmo','Antipasto','Pompelmo',6,' -','Pancarré,
150 G Formaggio Olandese,
1 Cucchiaio Formaggio Groviera Grattugiata,
2 Pompelmi,
2 Cucchiai Panna,
1 Tuorlo D''uovo,
Burro,
Sale,
Pepe','Spremete i pompelmi e versate il succo filtrato in una casseruola. Aggiungete una noce di burro, la groviera e il formaggio olandese grattugiati. Salate e pepate. Amalgamatevi la panna e cuocete per 10 minuti mescolando molto bene. Spegnete e incorporate il tuorlo al composto. Ponete di nuovo sul fuoco e, senza far bollire, continuate a mescolare fino a quando la crema risulterà liscia e omogenea. Togliete la crosta alle fette di pane e spalmatele con il composto. Ponetele sulla placca del forno leggermente imburrata e fate dorare in forno preriscaldato a 180 gradi. Servitele calde. Vini di accompagnamento: Lugana DOC, Bianchello Del Metauro DOC, Bianco D''Alcamo DOC.',2095);
INSERT INTO "ricette" VALUES (7771,'Crostini Con La Bottarga','Antipasto','Bottarga',4,' -','1 Bottarga Di 150 G,
Olio D''oliva Extra-vergine,
Succo Di Limone,
Pepe Bianco,
Alcuni Crostini Di Pane Tostato','Spellare la bottarga e tagliarla a fettine sottili; disporre le fettine in una ciotola e condirle con succo di limone, olio e pepe. Far insaporire per 30 minuti quindi disporre sui crostini caldi.',1308);
INSERT INTO "ricette" VALUES (7772,'Crostini Con La Bottarga (2)','Antipasto','Bottarga',4,' -','1 Bottarga Di 150 G,
Olio D''oliva Extra-vergine,
Basilico Fresco,
Pepe Bianco,
Alcuni Crostini Di Pane Tostato','Spellare la bottarga e tagliarla a fettine sottili; disporre le fettine in una ciotola e condirle con basilico fresco, olio e pepe. Far insaporire per 30 minuti quindi disporre sui crostini caldi.',1301);
INSERT INTO "ricette" VALUES (7773,'Crostini Con La Bottarga (3)','Antipasto','Bottarga',4,' -','1 Bottarga Di 150 G,
Olio D''oliva Extra-vergine,
Basilico Fresco,
Pomodorini Ciliegia,
Pepe Bianco,
Alcuni Crostini Di Pane Tostato','Spellare la bottarga e tagliarla a fettine sottili; disporre le fettine in una ciotola e condirle con basilico fresco, olio, pomodorini e pepe. Far insaporire per 30 minuti quindi disporre sui crostini caldi.',1333);
INSERT INTO "ricette" VALUES (7774,'Crostini Con La Salsiccia','Antipasto','Salsicce',6,' -','Pane Casereccio,
3 Salsicce Fresche,
150 G Formaggio Stracchino,
Semi Di Finocchio,
Sale','Spellate le salsicce, sbriciolatele in una ciotola e impastatele con lo stracchino prima ammorbidito e un cucchiaio scarso di semi di finocchio. Regolate il sale se occorre. Lavorate il composto amalgamandolo molto bene. Spalmatelo generosamente sulle fette di pane. Ponetele in forno preriscaldato a 180 gradi per un quarto d''ora. Ritirate, trasferite le fette su un piatto da portata e servitele subito molto calde. Vini di accompagnamento: Barbera D''Asti ''Frizzante'' DOC, Chianti Montalbano DOCG, Cilento Rosso DOC',1889);
INSERT INTO "ricette" VALUES (7775,'Crostini Con Le Melanzane','Antipasto','Melanzane',4,' -','8 Fettine Pane Di Segale,
1 Melanzana,
2 Pomodori,
1 Cipolla,
1 Gambo Sedano,
Salvia,
Formaggio Parmigiano Grattugiato,
Burro,
Olio D''oliva,
Sale,
Pepe','Tritate cipolla, salvia, sedano e pomodori; rosolate tutto nel burro. Affettate la melanzana, friggetela nell''olio. Distribuite il soffritto sul pane, sopra adagiatevi una fetta di melanzana, cospargete di parmigiano e passate in forno caldo per alcuni minuti.',3280);
INSERT INTO "ricette" VALUES (7776,'Crostini Con Le Regaglie','Antipasto','Regaglie',4,' -','Regaglie,
Cipolla,
Pancetta,
Peperoni Sott''aceto,
Sale,
Zucchero,
Aceto Di Vino','Si cuociono le regaglie, tagliate a pezzettini, con cipolla, pancetta, peperoni e si insaporiscono con sale, zucchero, aceto; si ricoprono con il composto crostini di pane fritti.',750);
INSERT INTO "ricette" VALUES (7777,'Crostini Con Melanzane','Antipasto','Melanzane',4,'Preparazione: 20 minuti. Cottura: 15 minuti. Calorie: 278.','3 Melanzane,
4 Fette Pane Casereccio,
1 Cucchiaio Capperi,
1 Spicchio Aglio,
1 Pizzico Origano,
Basilico,
Olio D''oliva,
Sale,
Pepe','Tostate le fette di pane da entrambi i lati. Fate cuocere le melanzane nel forno finché diverranno tenere, sbucciatele tagliateli in piccoli pezzi, mettetele in una terrina insieme con i capperi e basilico tritati, olio, un pizzico d''origano, il sale e il pepe. Strofinate lo spicchio d''aglio sulle fette di pane, irroratele con un filo d''olio, distribuitevi il composto preparato e servite. Il pane tostato alla brace acquista una fragranza particolare, tuttavia il forno di casa o una piastra di ghisa daranno lo stesso un buon risultato. E'' possibile anche utilizzare melanzane surgelate già grigliate.',1428);
INSERT INTO "ricette" VALUES (7778,'Crostini Con Polpa Di Olive','Antipasto','Olive Nere Dolci Appassite',4,' -','400 G Olive Nere Dolci Appassite,
1 Costa Sedano,
1 Spicchio Aglio Pestato,
1 Arancia (scorza),
1/2 Bicchiere Olio D''oliva Extra-vergine,
1 Bicchiere Vino Bianco Secco,
Sale,
Pepe','Snocciolare le olive e porle in un tegame ad insaporire a fuoco lento con tutti gli ingredienti ben tritati, aggiungete il vino e fate evaporare e a fine cottura unite due cucchiai di polpa di olive mescolando bene. Passate tutto al setaccio e spalmate su delle fette di pane tostato.',2038);
INSERT INTO "ricette" VALUES (7779,'Crostini Con Radicchio Rosso E Formaggio','Antipasto','Radicchio',10,' -','10 Fette Pancarré,
8 Ciuffi Radicchio Di Chioggia Piccolo,
8 Fettine Pancetta Affumicata,
150 G Formaggio Groviera Tagliato A Fettine,
1 Mazzetto Insalata Rucola,
1/2 Cipolla Tagliata','Formate due rettangoli da ogni fetta di pancarré e tostateli leggermente. Tagliate ogni ciuffo di radicchio in quattro parti, lavateli e asciugateli; indi stufateli in una larga padella con della cipolla. Dividete ogni fetta di pancetta a metà e fatela leggermente tostare in una padella per fare perdere il grasso. Disponete sopra il pancarré un ciuffetto di radicchio poi una mezza fettina di pancetta e per ultima la fettina sottile di formaggio. Mettete i crostini in una teglia imburrata e fate gratinare in forno (grill) per pochi minuti. NB: Si può servire con un insalata di rucola.',5227);
INSERT INTO "ricette" VALUES (7780,'Crostini Con Uovo Sodo E Mascarpone','Antipasto','Uova Sode',4,' -','250 G Mascarpone,
4 Uova Sode,
Pasta D''acciughe,
Alcune Fettine Pane','Dopo aver assodato le uova sminuzzarle il più possibile con la forchetta. Unire il mascarpone ed un po'' di pasta d''acciughe. Amalgamare il tutto fino a formare una crema spalmabile da stendere su fettine di pane a scelta.',1967);
INSERT INTO "ricette" VALUES (7781,'Crostini Cremosi','Antipasto','Formaggio Parmigiano',4,' -','4 Fette Pane Toscano,
100 G Formaggio Parmigiano Grattugiato,
50 G Formaggio Groviera Grattugiato,
2 Albumi D''uovo,
Burro,
Sale,
Pepe','Montate gli albumi a neve, salateli, incorporatevi i formaggi. Sistemate le fette di pane imburrate sulla placca del forno, distribuite sulla superficie la crema al formaggio, lasciatele scaldare per circa dieci minuti a 180 gradi e fate dorare.',1923);
INSERT INTO "ricette" VALUES (7782,'Crostini Del Fattore','Antipasto','Melanzane',4,'Preparazione: 15 minuti. Cottura: 15 minuti. Calorie: 366.','2 Melanzane,
200 G Mozzarella,
4 Fette Pane Casereccio,
Basilico Tritato,
Olio D''oliva,
Sale,
Pepe','Tagliate le fette di melanzane piuttosto spesse e nel senso della lunghezza; fatele arrostire sulla brace o su piastra di ghisa. Disponetele quindi in una terrina, irroratele con olio e insaporitele con sale, pepe, basilico tritato. Tagliate la mozzarella in quattro fette. Tostate il pane, conditelo con un filo d''olio e adagiate su ogni fetta la mozzarella e due fette di melanzane. Ultimate con una spolverizzata di sale, passate i crostini sotto al grill per qualche minuto e servite subito. Il pane tostato alla brace acquista una fragranza particolare, tuttavia il forno di casa o una piastra di ghisa daranno lo stesso un buon risultato. E'' possibile anche utilizzare melanzane surgelate già grigliate.',1818);
INSERT INTO "ricette" VALUES (7783,'Crostini Dello Zar','Antipasto','Caviale',12,'Preparazione: 20 minuti. Calorie: 178.','2 Confezioni Pane Integrale Affettato,
18 Fette Pancarré,
80 G Salmone Affumicato Affettato In Busta,
50 G Caviale Russo Pastorizzato,
50 G Burro','Le dosi sono per 36 tartine per colore. Ritagliate con un tagliapaste a forma di goccia, della larghezza di circa cm 4, 36 crostini dal pane nero e altrettanti dal pancarré. Tostate i crostini di pane bianco nel forno già a 190 gradi per circa 2 minuti. Tagliate con un tagliapaste a goccia più piccolo del precedente (circa cm 3), 36 gocce dalle fette di salmone. Mettete in una ciotola il burro, morbido e a pezzetti e, con un cucchiaio di legno, mescolatelo finché avrà raggiunto la densità di una crema. Appoggiate le gocce di salmone sui tostini di pane nero. Ammucchiate un po'' di caviale al centro dei tostini bianchi. Mettete la crema di burro in un imbutino di carta oleata con un piccolo buco sul fondo e, premendolo, fatene uscire un filino decorando con esso il contorno delle tartine.',8523);
INSERT INTO "ricette" VALUES (7784,'Crostini Di Acciuga','Antipasto','Acciughe',4,' -','80 G Burro,
8 Fette Pancarré,
2 Mozzarelle,
4 Acciughe,
2 Pomodori,
Origano,
Sale,
Pepe','Spinate le acciughe, dividetele a metà e tagliate i filetti in due parti. Tagliate a metà le fette di pane e spalmatele di burro; su ogni mezza fetta di pane mettete una fettina di mozzarella, qualche pezzo di pomodoro, un pezzo di acciuga e condite con sale, pepe e origano. Mettete i crostini nel forno e lasciateli cuocere fino a che la mozzarella non si sarà sciolta.',2869);
INSERT INTO "ricette" VALUES (7785,'Crostini Di Caprino Alle Melagrane','Antipasto','Melagrana',6,' -','250 G Formaggio Caprino Fresco,
50 G Mascarpone,
1 Melagrana Ben Matura,
Alcuni Crostini Pane Tostato','Stemperare il caprino amalgamandolo col mascarpone. Sgranare la melagrana e mescolare metà dei grani al caprino schiacciandoli in modo che rilascino il succo. Amalgamare bene e acconciare in una terrina. Decorare cospargendo con i restanti grani di frutto. Servire come antipasto.',1452);
INSERT INTO "ricette" VALUES (7786,'Crostini Di Cipolla Rossa','Antipasto','Cipolle Rosse',4,' -','2 Cipolle Rosse Di Tropea,
Alcune Noci Burro,
Farina,
1 Dado,
Pane Cotto A Legna','Tagliare le cipolle a fettine sottilissime e metterle in una padella su fuoco basso con qualche noce di burro finché non saranno completamente ammorbidite girando continuamente perché non devono assolutamente attaccarsi o arrostire. Preparare un poco di besciamella leggera (il brodo di dado al posto del latte). Unire la besciamella alle cipolle e mettere sulle fettine di pane precedentemente arrostite in forno. Non far freddare troppo è bene servire i crostini tiepidi.',1486);
INSERT INTO "ricette" VALUES (7787,'Crostini Di Fagioli Al Finocchietto','Antipasto','Fagioli',4,' -','200 G Fagioli Del Purgatorio Di Gradoli,
1 Ciuffo Finocchietto Selvatico Fresco,
Aglio,
Olio D''oliva Extra-vergine,
Sale,
Peperoncino,
8 Crostini Pane Casereccio','Lessare i fagioli senza metterli a bagno, con uno spicchio di aglio salandoli verso fine cottura. Imbiondire aglio e peperoncino nell''olio, aggiungere i fagioli con un po'' d''acqua di cottura ed il finocchietto tritato. Servire i fagioli caldi sui crostini di pane abbrustoliti.',2080);
INSERT INTO "ricette" VALUES (7788,'Crostini Di Fegatini','Antipasto','Fegatini Di Pollo',4,' -','4 Fegatini Di Pollo,
4 Acciughe Salate,
1 Manciata Capperi,
6 Foglie Salvia,
Sale,
Pepe Bianco Macinato,
1/2 Bicchiere Vino Bianco,
Olio D''oliva,
Per Guarnire:,
1 Foglia Prezzemolo','Fare rosolare i fegatini in olio con aggiunta di sei foglie di salvia. Quando sono rosolati aggiungere mezzo bicchiere di vino e, quando il vino è evaporato, portarli a cottura aggiungendo man mano una tazza di brodo. Salare e pepare. Aggiungere ai fegatini le acciughe diliscate, una manciata di capperi e tritare il tutto finemente. Rimettere al fuoco il composto nel sugo di cottura dei fegatini, rigirarlo sveltamente per due o tre minuti per farlo ben amalgamare e quando è pronto ritirarlo dal fuoco. Stendere quindi il composto sui crostini, che non devono essere troppo sottili e bagnati da una sola parte con un poco di brodo. Guarnire con una foglia di prezzemolo.',1202);
INSERT INTO "ricette" VALUES (7789,'Crostini Di Fegatini Di Pollo','Antipasto','Fegatini E Cuori Di Pollo',4,' -','200 G Fegatini E Cuori Di Pollo,
Brodo Di Pollo,
1 Cipolla,
3 Cucchiai Vin Santo,
40 G Burro,
4 Fette Pane Toscano Raffermo','Mondare i fegatini, lavarli, asciugarli. Fare un trito di cipolla ed appassirlo dolcemente nel burro; salare. Unire i cuori e rosolarli a fuoco vivo per 2-3 minuti; aggiungere i fegatini e farli colorire, quindi il Vin Santo; far evaporare e togliere dal fuoco. Passare al mixer e rimettere in padella bagnando con il brodo fino ad avere una crema. Abbrustolire il pane e spruzzarvi un''idea di Vin Santo. Spalmarvi il paté.',1305);
INSERT INTO "ricette" VALUES (7790,'Crostini Di Fegatini Di Pollo (2)','Antipasto','Paté Di Fegatini Di Pollo',4,' -','Paté Di Fegatini Di Pollo,
8 Fette Pane Francese Tostato,
Capperi Dissalati','Spalmate il paté di fegatini di pollo sulle fette di pane e guarnite coi capperi.',1266);
INSERT INTO "ricette" VALUES (7791,'Crostini Di Fegato','Pollame','Pollo',4,'Luogo: Campania.','800 G Fegatini Di Pollo,
250 G Cipolla,
Aglio,
Filetti D''acciughe,
100 G Capperi,
Burro,
Olio D''oliva,
500 G Pane','Per prima cosa pulite e lavate i fegatini. Fate imbiondire una cipolla nell''olio quindi aggiungete 1 spicchio di aglio tritato e i fegatini cuocendoli a fiamma viva per circa 5 minuti. Aggiungere quindi i capperi, 3-4 filetti d''acciughe e 1 noce abbondante di burro. Ultimata la cottura tritate il composto e diponetelo sulle fette di pane tostate in forno. Servite caldi.',4022);
INSERT INTO "ricette" VALUES (7792,'Crostini Di Filetti Di Sogliola Alla Crema Di Tartufo Bianco','Antipasto','Filetti Di Sogliola',6,' -','12 Filetti Di Sogliola,
300 G Funghi Coltivati,
100 G Burro,
6 Fette Pancarré,
100 G Crema Di Latte,
1 Bicchiere Vino Marsala,
Farina,
Sale,
Pepe,
50 G Tartufi Bianchi','Mettere a dorare in una teglia 50 g di burro, unire i filetti infarinati, coprire con il marsala, condire con sale e pepe e passare al forno caldo per 15 minuti. Togliere dal forno, sgocciolare i filetti e tenerli da parte in un piatto, aggiungere al fondo di cottura i funghi lavati e passati al setaccio e la crema di latte, far bollire per qualche minuto, poi unire le fettine di tartufo e una noce di burro. Soffriggere a parte i crostini di pancarré nel burro. Adagiare i filetti sopra i crostini fritti, cospargere con la salsa e servire.',4387);
INSERT INTO "ricette" VALUES (7793,'Crostini Di Finocchio Selvatico','Antipasto','Finocchio',4,' -','Pane Casereccio A Fette,
Finocchio Tenero Selvatico,
Formaggio Sardo Vaccino','Tostare le fette di pane e disporle sopra ad una pirofila unta. Far bollire del finocchio selvatico a piccoli pezzi fino a farlo diventare tenero. Scolarlo e disporlo sui crostini in modo che l''acqua bagni un poco il pane. Grattugiare un formaggio tenero. Mettere in forno finché il formaggio non si è squagliato.',616);
INSERT INTO "ricette" VALUES (7794,'Crostini Di Lepre','Antipasto','Lepre',4,' -','1 Lepre,
2 Salsicce,
2 Fette Pancetta,
Salvia,
Rosmarino,
1 Spicchio Aglio,
2 Acciughe Salate,
Pepe,
2 Bicchieri Aceto Di Vino,
1 Bicchiere Vino,
1 Cucchiaio Conserva Di Olive,
1/2 Bicchiere Olio D''oliva','Dopo aver lavato bene il magro della lepre insieme con il fegato e il cuore tritarlo con la salvia, l''aglio, il rosmarino le salsicce la pancetta e le due acciughe. Soffriggere in un tegame con mezzo bicchiere di olio d''oliva uno spicchio d''aglio insieme a un poco di pepe. Quando l''aglio incomincia a imbiondire versare tutto il tritato nel tegame, unire un bicchiere di vino e lasciare cuocere a tegame coperto per circa un''ora aggiungendo se necessario un poco di brodo. Quando la cottura è raggiunta unire un cucchiaio di salsa di olive e due cucchiai di aceto e lasciare insaporire al fuoco ancora per qualche minuto. Versare quindi il composto a cucchiaiate sui crostini di pane ben caldi.',4261);
INSERT INTO "ricette" VALUES (7795,'Crostini Di Mare Alla Portofino','Antipasto','Cozze',4,' -','1 Filone Pane,
400 G Frutti Di Mare (cozze, Ostriche),
Sale,
Peperoncino In Polvere,
Prezzemolo Tritato,
50 G Burro,
1 Limone (succo)','Tagliate il pane a fette alte e asportate da queste una parte di mollica, creando un incavo che possa contenere i frutti di mare. Estraete i molluschi dalle conchiglie, che avrete ben lavato e aperto con la punta di un coltellino; poi sistemateli, crudi, sulle fette di pane, spolverizzandoli di sale e di peperoncino e cospargendoli di prezzemolo. Sbriciolate la mollica di pane asportata, fatela soffriggere nel burro e distribuite anche questa sui frutti di mare. Disponete ora i crostini così preparati sulla placca del forno o su un piatto resistente al calore, spruzzateli con il succo di limone, quindi infornateli a 180 gradi per 15 minuti. Serviteli ben caldi.',2012);
INSERT INTO "ricette" VALUES (7796,'Crostini Di Milza','Carne','Vitello',4,' -','8 Fette Pane Raffermo,
300 G Milza Di Vitello,
3 Cucchiai Olio D''oliva Extra-vergine,
1 Cipolla,
1 Spicchio Aglio,
2 Acciughe Sotto Sale,
1 Cucchiaio Capperi Salati,
1 Pizzico Pepe,
1 Pizzico Sale,
1 Rametto Rosmarino','tagliate a fette sottili le cipolle e fatele rosolare con l''olio. Dopo 5 minuti aggiungete lo spicchio d''aglio e la milza tagliata a pezzetti, precedentemente bollita per circa 40 minuti. Quando il tutto è bene amalgamato aggiungete le acciughe diliscate e i capperi salati. Continuate la cottura per altri dieci minuti; salate e pepate e spegnete il fuoco. Passate al tritatutto per ottenere un composto omogeneo. Abbrustolite le fette di pane raffermo che dovranno essere non più alte di un centimetro, e su queste spalmate la milza. C''è chi la sostituisce con i fegatini di pollo, ma la ricetta tradizionale è quella che vi abbiamo dato.',1994);
INSERT INTO "ricette" VALUES (7797,'Crostini Di Milza (2)','Antipasto','Milza',4,'Luogo: Toscana.','150 G Milza,
2 Acciughe,
20 G Burro,
2 Cucchiai Olio D''oliva,
Sedano,
Cipolla,
Carota,
Crostini,
Pepe','Questi crostini sono una specialità toscana e sono molto saporiti. Togliete la pelle alla milza e cuocetela nel soffritto di cipolla, sedano e carota tritati finissimi e rosolati nell''olio e burro. Quando la milza sarà cotta la passerete al tritatutto insieme alle acciughe prima pulite e diliscate. Mettete di nuovo la milza tritata nella casseruola dove sarà rimasto il sugo di cottura e fatela scaldare prima di spalmarla sui crostini di pane abbrustolito e imburrato che avrete già preparato.',1012);
INSERT INTO "ricette" VALUES (7798,'Crostini Di Pesce','Pesce','Sgombro',4,' -','Sarde,
Acciughe,
500 G Sgombro,
2 Spicchi Aglio,
10 Cl Olio D''oliva Extra-vergine,
Sale,
Pepe,
300 G Pane Casereccio','Nella padella nera versate l''olio, soffriggetevi l''aglio schiacciato e, dopo averlo eliminato, gettatevi il pesce, che avrete ben pulito, lavato e diliscato perfettamente. Aggiungete un po'' di sale e il pepe e fate cuocere, schiacciando bene il pesce finché sarà ridotto quasi in pasta. Togliete la crosta al pane, tagliatelo in fette, arrostitele e distendetevi il pesce, aiutandovi con la lama di un coltello.',2886);
INSERT INTO "ricette" VALUES (7799,'Crostini Di Polenta','Antipasto','Polenta',4,'Luogo: Veneto.','4 Fette Grandi Polenta Avanzata,
4 Fette Mortadella Tagliata Spessa,
4 Fette Pancetta Affumicata (fette Piuttosto Sottili),
4 Fette Formaggio Fontina,
4 Cucchiai Formaggio Grana Grattugiato,
50 G Burro,
2 Uova,
1/2 Cucchiaino Curry,
1 Grattata Noce Moscata,
Sale','Fate rosolare le fette di polenta in una casseruola con il burro spumeggiante, finché saranno ben dorate da entrambe le parti. Salatele leggermente. Adagiate quindi su ogni fetta di polenta prima la pancetta, poi la mortadella e infine il formaggio. Abbassate la fiamma, coprite il recipiente e lasciate fondere il formaggio. Sbattete le uova in una terrina insieme con il grana, il curry e una grattata di noce moscata. Suddividete il preparato sulla polenta nella casseruola, fate rapprendere le uova per 5 minuti circa, poi servite, ben caldo. Vino in abbinamento proposto: Piave - Raboso.',6011);
INSERT INTO "ricette" VALUES (7800,'Crostini Di Polenta Con Frutti Di Mare','Antipasto','Polenta',4,'Preparazione: 20 minuti. Cottura: 40 minuti. Calorie: 575.','300 G Moscardini,
300 G Gamberetti,
300 G Cozze,
8 Fette Polenta,
3 Pomodori Maturi,
1 Spicchio Aglio,
1/2 Cipolla,
1/2 Bicchiere Vino Bianco Secco,
Peperoncino Rosso,
Olio D''oliva,
Sale','Mettete le cozze e i gamberetti in una casseruola con un po'' d''acqua, coprite, ponete sul fuoco e lasciate che tutte le cozze si aprano. Sgusciate i gamberetti e le cozze e tenete tutto in parte. In un po'' d''olio e un cucchiaio d''acqua, fate appassire la cipolla e l''aglio tritati finemente e appena prendono colore unite i moscardini già precedentemente puliti. Bagnate con il vino e lasciate evaporate; tagliate i pomodori a pezzetti metteteli nella casseruola insieme con mezzo bicchiere d''acqua, salate, aggiungete un po'' di peperoncino sbriciolato e lasciate cuocere a fuoco basso per quaranta minuti. Intanto abbrustolite da ambo i lati le fette di polenta su una piastra rovente. Qualche minuto prima della cottura dei moscardini, aggiungete al sugo i gamberetti e le cozze fate insaporire e poi versate un poco per parte sui crostini di polenta. Questo piatto deve essere servito ancora fumante.',3445);
INSERT INTO "ricette" VALUES (7801,'Crostini Di Polenta Con Le Noci','Antipasto','Noci',4,' -','Polenta Già Pronta,
Formaggio Fontina A Fette,
Burro,
Peperoncino In Polvere,
Gherigli Di Noci','Tagliare la polenta a rettangoli da disporre su una teglia appena unta di burro. Su ogni pezzo mettere una fetta di fontina, un pochino di burro e spolverizzare di peperoncino. Passare in forno caldo molto rapidamente e, prima di servire, decorare ogni crostino con un gheriglio di noce.',2080);
INSERT INTO "ricette" VALUES (7802,'Crostini Di Pollo E Formaggio','Antipasto','Petto Di Pollo',4,'Preparazione: 20 minuti. Calorie: 173.','8 Fette Pancarré,
200 G Petto Di Pollo,
200 G Latte,
100 G Panna Liquida,
100 G Formaggio Caprino,
20 G Burro,
15 G Farina Bianca,
1 Cucchiaino Senape Aromatica,
1/2 Cucchiaino Paté Di Olive,
1 Filetto D''acciuga,
10 Fili Erba Cipollina,
Prezzemolo,
Sale,
Pepe,
Per La Teglia:,
Burro','Tritate il petto di pollo, crudo, con il tritatutto elettrico a centrifuga. Preparate un trito con 10 fili di erba cipollina e un po'' di prezzemolo; unitelo al pollo, salate e pepate. Amalgamatevi la panna e il caprino. Imburrate una teglia da forno, appoggiatevi le fette di pancarré e doratele nel forno normale a 250 gradi. Mescolate mezzo cucchiaino di paté di olive con il filetto d''acciuga, spappolato, e spalmate con esso le fette tostate. Fondete per 20 secondi nel microonde a 1/3 della potenza il burro posto in una pirofila. Amalgamatevi la farina e diluite con il latte mescolando, poi cuocete nel microonde a potenza max per 4 minuti. Insaporite la salsa con un pizzico di sale e un cucchiaino di senape. Spalmate i crostini in maniera uniforme con la farcia di pollo e formaggio. Cuocete i crostini nel microonde a 2/3 della potenza per 3 minuti, poi rifilateli, tagliateli in due e serviteli con la salsa.',3319);
INSERT INTO "ricette" VALUES (7803,'Crostini Di Ricotta','Antipasto','Ricotta Romana',4,' -','200 G Ricotta Romana,
4 Fette Pane In Cassetta,
1 Mazzetto Erbe Odorose Fresche,
Limone,
Olio D''oliva,
Sale,
Pepe Bianco','Lavate e asciugate le erbe odorose, tritatele finemente esclusi i gambi del prezzemolo. In una ciotola lavorate con un mestolo di legno la ricotta in modo da ottenere una crema morbida, poi insaporitela con alcune gocce di limone passato al colino e mescolate ancora con cura. Se l''impasto fosse troppo sodo aggiungete un cucchiaino o due di acqua tiepida. Unite le erbe tritate, salate, pepate, condite con un filo d''olio e spalmate la crema sulle fette di pane tagliate a triangolo. Tenete in frigo prima di servire.',1573);
INSERT INTO "ricette" VALUES (7804,'Crostini Di Salsa Di Olive','Antipasto','Olive Nere',4,' -','500 G Olive Nere,
1 Arancia Piccola,
1 Limone Piccolo,
100 G Acciughe Salate,
50 Cl Olio D''oliva,
1 Cucchiaio Aceto Di Vino,
Salvia,
Alcune Foglie Rosmarino,
1 Carota,
3 Spicchi Aglio,
Capperi,
Prezzemolo','Snocciolare le olive nere e metterle a cuocere in un tegame con un bicchiere d''olio, la salvia, alcune foglie di rosmarino, 3 spicchi d''aglio, una carota ed un cucchiaio d''aceto. Lasciare cuocere per circa un''ora quindi unire alle olive cotte l''arancia e il limone, le acciughe e i capperi e tritare tutto finemente o meglio passare nel tritatutto. Rimettere l''impasto al fuoco per qualche minuto aggiungendo ancora dell''olio e assaggiare di sale. Quando il composto sarà della giusta consistenza spalmarlo su crostini di pane freddi. Questa salsa oltre che per i crostini viene utilizzata anche in altre preparazioni e si conserva benissimo mettendola in un vasetto di vetro coperta da uno strato d''olio.',6303);
INSERT INTO "ricette" VALUES (7805,'Crostini Di Salsiccia E Stracchino','Antipasto','Salsiccia',4,' -','Formaggio Stracchino,
Salsiccia,
Alcune Fettine Pane,
1 Pizzico Pepe','Si unisce dello stracchino e della salsiccia sbriciolata, si spalma su fettine di pane (tipo le baguette), si mette un pizzico di pepe e si passano in forno caldo per una decina di minuti.',1088);
INSERT INTO "ricette" VALUES (7806,'Crostini Di Tonno','Antipasto','Tonno',4,' -','250 G Tonno In Scatola,
300 G Pomodorini,
2 Scalogni,
Limone,
Basilico,
Olio D''oliva Extra-vergine,
1 Filoncino Pane,
Sale','Scolate l''olio dal tonno; sbriciolatelo e raccoglietelo in una ciotola. Affettate finemente gli scalogni. Dividete in due il limone, tagliatene metà a fettine sottilissime e spremete l''altra. Unite al tonno scalogni, le fettine di limone e il succo passato al colino, quattro cucchiai d''olio. Mescolate delicatamente, aggiungete i pomodori spellati, privati dei semi e tagliati a cubetti, qualche fogliolina di basilico. Tagliate il pane a fette, tostatele e distribuite sopra il composto di tonno.',2823);
INSERT INTO "ricette" VALUES (7807,'Crostini Di Uova Sode','Antipasto','Uova',4,' -','6 Uova,
1 Pugno Capperi Salati,
4 Filetti D''acciughe,
Aceto Di Mele,
Salsa Verde,
Sale,
Olio D''oliva Extra-vergine','Far rassodare le uova e separare i tuorli. Metterli in un mixer con capperi, acciughe, sale, 1 cucchiaino di aceto di vino, 1 cucchiaino di salsa verde, l''albume di 1 uovo. Frullare, facendo scendere a filo l''olio, finché si ottenga una consistenza cremosa. Spalmare su crostini di pane tostato aggiungendo al momento ancora un filo d''olio.',1496);
INSERT INTO "ricette" VALUES (7808,'Crostini Dorati','Antipasto','Uova',4,' -','Fette Di Pancarré (o Pane Casereccio A Fette),
3 Uova,
Latte,
Sale,
Pepe,
Olio D''oliva Per Friggere','Sbattere bene le uova entro una terrina larga, aggiungendo a poco a poco del latte, così da ottenere un composto piuttosto liquido, che va poi dosato di sale e pepe. Immergere quindi nel composto le fette di pane o pancarré lasciandovele per qualche minuto affinché si imbevano bene e poi friggerle nell''olio già bollente in padella. Si servono guarniti in vari modi o così semplicemente, come antipasti caldi.',1330);
INSERT INTO "ricette" VALUES (7809,'Crostini Dorati (2)','Antipasto','Pane Raffermo',4,'Luogo: Val D''Aosta.','1 Uovo,
Alcune Fette Pane Raffermo Con Mollica Compatta,
Zucchero,
Latte Tiepido,
Farina Bianca,
Olio D''oliva,
Burro','Sbattere l''uovo intero sino a che non è spumoso. Zuccherare il latte e intingervi velocemente le fette di pane che vanno poi passate nell''uovo. Disporre il pane così imbevuto su di un piatto e lasciar riposare per alcuni minuti. Nel frattempo, far scaldare l''olio e il burro, passare le fette nella farina bianca e soffriggerle. Scolarle su una carta assorbente da cucina e spolverarle di zucchero. Servire tiepidi o freddi.',2516);
INSERT INTO "ricette" VALUES (7810,'Crostini Filanti Ai Wurstel','Antipasto','Wurstel',4,' -','4 Fette Pancarré,
4 Fette Formaggio,
15 G Burro Ammorbidito,
2 Cucchiaini Senape,
4 Wurstel','Riscaldare il forno a 200 gradi. Privare le fette di pancarré della crosta, quindi spalmarle con il burro e la senape. Adagiare su ogni fetta di pancarré una di formaggio, poi tagliare le fette in 4, ricavando da ognuna 4 crostini quadrati. Tagliare i wurstel a metà nel senso della lunghezza e poi nell''altro senso; sistemarne 1 pezzetto su ogni crostino poi metterli sulla placca del forno e cuocerli per 5 minuti circa, finché il formaggio sarà fuso. Servire subito.',2435);
INSERT INTO "ricette" VALUES (7811,'Crostini Golosi','Antipasto','Mandorle Sgusciate',4,' -','4 Fette Pane Casereccio,
50 G Mandorle Sgusciate,
2 Cucchiai Cacao Dolce In Polvere,
1 Cucchiaio Cacao Amaro In Polvere,
5 Cucchiai Rum,
5 Cucchiai Alchermes','Sbollentate le mandorle, privatele della pellicina, disponetele in una teglia e passatele in forno per circa 10 minuti a 180 gradi. Subito dopo, munitevi di un mixer da cucina e tritatele per pochi secondi grossolanamente raccogliendole in seguito in una ciotola, nella quale unirete le due varietà di cacao. Mescolate con cura e versate un po'' per volta il rum fino ad ottenere un composto omogeneo e morbido. Nel frattempo, tagliate a metà le fette di pane, spalmatele con la cremina ottenuta, sistematele ordinatamente su un piatto piano da portata, spruzzatele con l''alchermes e servite. Suggerimento: in alternativa potete tostare le fette di pane in forno ben caldo per qualche minuto e decorarle, subito dopo averle spalmate di crema, con granella di mandorle.',1827);
INSERT INTO "ricette" VALUES (7812,'Crostini In Agrodolce','Antipasto','Uvetta Sultanina',6,' -','1 Filoncino Pane,
80 G Capperi,
60 G Uvetta Sultanina,
30 G Pinoli Sgusciati,
50 G Prosciutto Crudo,
30 G Burro,
3 Cucchiai Aceto Di Vino Bianco,
1 Cucchiaino Zucchero,
1 Arancia Piccola,
Farina,
Sale,
Pepe','Tritate grossolanamente i capperi, l''uvetta bagnata e strizzata, i pinoli. Unite il prosciutto tritato finissimo. Impastate il burro con un cucchiaino di zucchero, mezzo cucchiaio di farina e fatelo sciogliere in un tegamino. Quando inizia a spumeggiare versatevi il succo d''arancia filtrato al colino e tre cucchiai d''aceto. Lasciate cuocere per alcuni minuti. Aggiungete questa salsa al composto di prosciutto, regolate sale e pepe mescolando con molta cura. Tagliate il filoncino a fettine diagonali, abbrustolitele leggermente e poi spalmatele con abbondante composto. Disponetele sul piatto da portata e servitele tiepide. Sono buone anche fredde. Questi crostini hanno un sapore insolito, ma vale la pena provarli. Vini di accompagnamento: Bianco Di Custoza DOC, Galestro VdT Di Toscana, Gravina DOC.',2595);
INSERT INTO "ricette" VALUES (7813,'Crostini Marinari','Antipasto','Calamaretti',6,' -','1 Filoncino Pane,
250 G Calamaretti,
250 G Gamberi,
1 Uovo,
1 Spicchio Aglio,
Pangrattato,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Pulite e lavate i calamaretti, sgusciate i gamberi e tritate grossolanamente il tutto. Amalgamate con l''uovo, aggiungete l''aglio e un ciuffo di prezzemolo tritati, due cucchiai di pangrattato freschissimo. Insaporite con olio, sale e pepe. Tagliate in diagonale le fette di pane e sopra distribuitevi uno strato abbondante d''impasto. Mettete in forno preriscaldato a 170 gradi per un quarto d''ora. Ritirate e servite subito a tavola. Vini di accompagnamento: Grave Del Friuli Bianco DOC, Verdicchio Dei Castelli Di Jesi (anche ''Spumante'') DOC, Vermentino Di Sardegna DOC.',2923);
INSERT INTO "ricette" VALUES (7814,'Crostini Montanari Con Speck E Crema Di Mele','Antipasto','Speck',6,' -','1 Filoncino Pane,
200 G Speck,
1 Pezzetto Radice Di Rafano (cren),
1 Mela Verde,
1/2 Bicchiere Yogurth Magro,
Limone,
Panna,
Sale,
Pepe','Prendete un pezzetto di radice di rafano di circa cinque centimetri, pulitela e grattugiatela. Sbucciate la mela e tritatela. Riunite l''uno e l''altra in una ciotola, mescolate e amalgamate spruzzando un po'' di succo di limone. Versate 1/2 bicchiere di yogurth e mescolate ancora con cura. Aggiungete mezzo bicchiere di panna al composto. Regolate sale e pepe. Spalmate la crema sulle fettine di pane tagliate in diagonale, adagiate su ognuna una fettina di speck e servite a tavola. Vini di accompagnamento: Aldo Adige Sylvaner DOC, Montecarlo Bianco DOC, Contessa Entellina Chardonnay DOC.',1977);
INSERT INTO "ricette" VALUES (7815,'Crostini Napoletani','Antipasto','Acciughe',4,'Luogo: Campania. Luogo: Napoli.','8 Fette Pancarré Raffermo Un Giorno Senza Crosta,
50 G Burro (o Margarina),
1 Mozzarella,
4 Acciughe Dissalate E Diliscate,
4 Pomodori Pelati,
1 Pizzico Origano,
Sale,
Pepe,
1 Filo Olio D''oliva','Imburrate la placca del forno, disponetevi le fette di pane spalmate di burro sulla parte superiore. Su ognuna mettete una fetta di mozzarella, un filetto d''acciughe, mezzo pomodoro, salate, pepate e distribuite un pizzico di origano. Su tutto versate un filo d''olio. Mettete in forno a 250 gradi per una decina di minuti.',2620);
INSERT INTO "ricette" VALUES (7816,'Crostini Per L''aperitivo','Antipasto','Funghi Champignon',4,'Preparazione: 45 minuti. Cottura: 45 minuti.','400 G Funghi Champignon,
1 Cipolla Media,
2 Spicchi Aglio,
50 G Pancetta Magra (o Gambuccio Di Prosciutto Crudo),
2 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Passata Di Pomodoro,
Prezzemolo,
20 Fette Pane Casereccio (fette Piccole E Sottili)','Mondate i funghi eliminando l''estremità dei gambi quindi lavateli rapidamente e asciugateli. Tritate finemente la cipolla insieme agli spicchi d''aglio. Tritate finissima anche la pancetta (potete tritare tutti e tre questi ingredienti mettendoli insieme nel mixer). Scaldate l''olio in un largo tegame e, a fuoco moderato, fatevi rosolare tutto quanto il preparato. Nel frattempo mettete i funghi sul tagliere e tritateli grossolanamente con un coltellone e, quando il soffritto sarà pronto, versateli nel tegame insieme alla passata di pomodoro. Mescolate, insaporite con sale e un''abbondante macinata di pepe e lasciate cuocere per una ventina di minuti fino a che i funghi si saranno asciugati. Togliete la crosta alle fettine di pane e tostatele leggermente quindi allineatele su un piatto da portata, distribuitevi il composto di funghi e spolverateli di prezzemolo tritato. Serviteli ben caldi insieme ad un bicchiere di Vernaccia fresca.',3552);
INSERT INTO "ricette" VALUES (7817,'Crostini Piccanti Al Pomodoro','Antipasto','Cipolla',4,' -','1 Confezione Pancarré,
Burro,
1/2 Cipolla,
Zenzero,
Latte,
1 Tuorlo D''uovo,
Alcuni Pomodori','Le fette di pancarré arrostitele e spalmatele leggermente, quando sono ancora calde, di burro da una parte sola, preparate un battuto con la cipolla, fatela colorire in un bel pezzo di burro, insieme con uno zenzero piccolo tritato finissimo, aggiungetevi pomodori pelati e tritati e lasciate cuocere fino a che si sia formata una salsa ben densa, cui unirete alla fine un sorso di latte. Togliete dal fuoco e, dopo un po'' aggiungetevi il tuorlo, lavorando bene. Stendete il composto su ogni fetta di pane già preparata sul piatto di servizio. Passate un momento in forno e servite.',2503);
INSERT INTO "ricette" VALUES (7818,'Crostini Profumati','Antipasto','Prosciutto',4,' -','120 G Prosciutto (fette Da 60 G),
100 G Fagiolini Surgelati,
70 G Formaggio Gorgonzola,
70 G Formaggini Petit-suisse,
2 Steli Erba Cipollina,
1 Ciuffetto Prezzemolo,
Pancarré Rotondo A Fette,
Sale','Cuocete i fagiolini in acqua bollente salata e scolateli leggermente al dente. In una ciotola mescolate il gorgonzola con i petit-suisse. Tritate erba cipollina e prezzemolo e incorporateli ai formaggi. Stendete le fette di prosciutto su un piano di lavoro, e spalmatele con il composto. Nel mezzo fate 9 file di fagiolini, arrotolate strettamente le fette di prosciutto, avvolgetele in pellicola trasparente e mettetele in frigo per 2 ore. Al momento di servire, tagliate delle rondelle spesse e appoggiatene una su ogni fetta di pane tostato.',1313);
INSERT INTO "ricette" VALUES (7819,'Crostini Rosa','Antipasto','Salsicce',4,' -','8 Fette Pane Nero,
8 Salsicce,
Burro Normale,
Burro All''aglio,
Semi Di Cumino','Friggete il pane nel burro normale. In un padellino cuocete le salsicce con due o tre cucchiai di acqua; bucherellatele con i rebbi della forchetta. Spalmate i crostini con il burro all''aglio, adagiatevi sopra una salsiccia spellata e tagliata a metà in senso verticale, cospargete con semi di cumino e servite.',5536);
INSERT INTO "ricette" VALUES (7820,'Crostini Rustici','Antipasto','Formaggio Galbanino',4,' -','4 Fette Pane Casereccio,
200 G Formaggio Galbanino,
20 Cl Birra Chiara,
1 Cucchiaino Senape Rustica,
1 Cucchiaino Salsa Worcester','Versate in un pentolino il formaggio (precedentemente grattugiato), la birra, la senape e la salsa worcester. Cuocete il tutto a fiamma bassa, mescolando continuamente con un mestolo di legno fino ad ottenere un composto cremoso. Dopodichè, spalmatelo uniformemente su ogni singola fetta di pane e fate tostare e gratinare in forno caldo per circa 5-6 minuti.',1367);
INSERT INTO "ricette" VALUES (7821,'Crostini Rustici (2)','Antipasto','Filetti D''acciughe',4,' -','8 Filetti D''acciughe,
100 G Noci,
1 Spicchio Aglio,
1 Bicchiere Olio D''oliva,
1 Cucchiaino Senape,
1 Cucchiaino Aceto Di Vino Bianco,
1 Pizzico Pepe,
4 Fette Pane Casereccio','Tagliare a metà le fette di pane e abbrustolirle sulla graticola. Pestare nel mortaio i gherigli con l''aglio e i filetti d''acciuga, versando l''olio a filo, poco per volta. Quando il composto sarà omogeneo unire 1 cucchiaino di senape, 1 di aceto e un pizzico di pepe. Amalgamare bene e spalmare la crema sulle fette di pane.',2638);
INSERT INTO "ricette" VALUES (7822,'Crostini Saporiti','Antipasto','Formaggio Provolone Piccante',4,' -','Pane Da Crostini,
Formaggio Provolone Piccante,
1 Cipollina Fresca (o Cipolla Fresca),
Maionese','Mettere la cipolla in bagno di acqua per togliere il sapore forte sciacquando bene quindi tritarla insieme al provolone ed amalgamare con pochissima maionese. Spalmare il composto su fettine di pane fresco.',1009);
INSERT INTO "ricette" VALUES (7823,'Crostini Saporiti (2)','Antipasto','Tonno Al Naturale',4,' -','4 Fette Pane Integrale Di Grano Duro Cotto A Legna,
100 G Tonno Al Naturale,
10 Olive Di Gaeta,
Capperi,
1 Spicchio Aglio,
Olio D''oliva Extra-vergine,
1 Grattatina Noce Moscata,
1 Macinata Pepe Nero,
Sale Marino','Strofinare con uno spicchio d''aglio le fette di pane dopo averle abbrustolite. Unire al tonno sgocciolato le olive snocciolate e i capperi triturati insieme grossolanamente. Irrorare con dell''ottimo olio e rifinire con una grattatina di noce moscata e una macinata di pepe.',1476);
INSERT INTO "ricette" VALUES (7824,'Crostini Sfiziosi','Antipasto','Formaggio Gorgonzola',4,' -','Pane,
Burro,
80 G Formaggio Gorgonzola,
100 G Prosciutto Crudo,
Sale,
Pepe,
Paprica','Tagliate alcune fette di pane raffermo, spalmatele con un poco di burro e fatele tostare leggermente nel forno. Nel frattempo preparate in una terrina la salsa al gorgonzola. Mettete nella ciotola il formaggio, la paprica, il sale e il pepe e amalgamate bene il tutto. Togliete le fette dal forno e spalmatele con la crema al formaggio e rimettetele nel forno a 150 gradi fino a quando il formaggio non si sarà sciolto. Servite i crostini con delle fette di prosciutto sopra.',1795);
INSERT INTO "ricette" VALUES (7825,'Crostini Sfiziosi (2)','Antipasto','Formaggio Gorgonzola',4,' -','Pane,
Burro,
80 G Formaggio Gorgonzola,
100 G Prosciutto Cotto,
Sale,
Pepe,
Paprica','Tagliate alcune fette di pane raffermo, spalmatele con un poco di burro e fatele tostare leggermente nel forno. Nel frattempo preparate in una terrina la salsa al gorgonzola. Mettete nella ciotola il formaggio, la paprica, il sale e il pepe e amalgamate bene il tutto. Togliete le fette dal forno e spalmatele con la crema al formaggio e rimettetele nel forno a 150 gradi fino a quando il formaggio non si sarà sciolto. Servite i crostini con delle fette di prosciutto sopra.',1773);
INSERT INTO "ricette" VALUES (7826,'Crostini Su Una Zampa Sola','Antipasto','Olive Nere',4,' -','Pane Raffermo,
Olive Nere,
2 Fette Formaggio Caciottina,
3 Fette Salame Contadino,
1 Pizzico Origano','Ho tagliato a pezzettini sul tagliere: il formaggio, il salame e le olive nere, ho tirato sopra un bel pizzico di origano, mescolato e spalmato sulle fette di pane appena tostate.',1193);
INSERT INTO "ricette" VALUES (7827,'Crostini Tonno E Basilico','Antipasto','Tonno Sott''olio',6,' -','4 Fette Pancarré,
1 Uovo,
120 G Tonno Sott''olio,
1 Pomodoro,
1 Cipollotto,
Alcune Foglie Di Basilico,
Olio D''oliva,
Sale','Private le fette di pancarré della crosta, passatele nell''uovo precedentemente sbattuto con un pizzico di sale e friggetele in una padella antiaderente con abbondante olio d''oliva. Successivamente, disponete le fette di pane su fogli di carta assorbente e nel frattempo, preparate il condimento. Lavate con cura il pomodoro e il cipollotto e tritateli molto finemente, dopodiché, versateli in una ciotolina nella quale aggiungerete il tonno sgocciolato, il basilico tritato, il sale, un goccino d''olio d''oliva e mescolate fino ad ottenere un composto omogeneo. Infine, tagliate a triangoli le fette di pancarré fritte e versate su ognuna il composto ottenuto. Regolate di sale e servite.',2111);
INSERT INTO "ricette" VALUES (7828,'Crostini Tosco-romagnoli','Antipasto','Pane Toscano',4,' -','400 G Fegatini Di Pollo,
Aceto Di Vino,
Aglio,
Cipolla,
Carota,
Salvia,
Sale,
Pepe,
Acqua,
1/4 Dado,
2 Cucchiai Pomodoro In Cubetti,
1 Manciata Capperi Sminuzzati Finemente,
1 Noce Burro,
Alcune Fette Pane Toscano Non Salato','Prendere 4 etti di fegatini di pollo. Lavarli e tenerli un po'' sotto aceto. Soffriggere aglio, cipolla,carota, salvia (poco di tutto). Aggiungere i fegatini e farli soffriggere bene, salare e pepare. Quando sono soffritti aggiungere un po'' d''acqua calda e 1/4 di dado, 2 cucchiai di pomodoro in cubetti e fare sobbollire fino a che non sono cotti. Macinare il tutto con il vecchio passatutto a mano. Rimettere sul fuoco, aggiungere una manciata di capperi sminuzzati finemente, aggiungere una noce di burro e poche gocce di aceto. Spalmare su fette di pane rigorosamente toscano (non salato) a caldo.',1670);
INSERT INTO "ricette" VALUES (7829,'Crostino Con Philadelphia, Mosto Cotto E Pistacchi Tritati','Antipasto','Formaggio Philadelphia Light',4,' -','1/2 Scatola Formaggio Philadelphia Light,
2 Cucchiai Mosto Cotto,
Pane,
Sale,
Pepe,
Per Decorare:,
Pistacchi Tritati','Impastare il formaggio con il mosto cotto, il sale e il pepe. Spalmare sulle fette di pane, coprire con i pistacchi tritati.',683);
INSERT INTO "ricette" VALUES (7830,'Crostino Di Spinaci E Capesante','Antipasto','Capesante',4,' -','250 G Capesante Pulite,
40 G Burro,
1 Pezzetto Cipolla,
1 Pezzetto Peperoncino,
300 G Spinaci Saltati In Padella,
8 Fette Pancarré,
4 Cucchiai Formaggio Grana Grattugiato,
Sale','Levate il corallo alle capesante e sciacquatele. Prendete una padella, fate insaporire nel burro il pezzetto di cipolla, poi cuocetevi le capesante 1 minuto circa per parte. Unite il corallo e mescolate. levate le capesante dal fuoco e affettatele. Mettete in padella il pezzetto di peperoncino e gli spinaci. Fateli insaporire e correggete di sale. Togliete la crosta alle fette di pancarré e tagliatele in diagonale. Distribuite su ogni metà un po'' di spinaci e qualche fettina di capesanta. Spolverizzate di grana e mettete in forno a 200 gradi per circa 10 minuti. Servire subito.',2268);
INSERT INTO "ricette" VALUES (7831,'Crostoli Di Carnevale','Dessert','Uova',4,' -','250 G Farina,
2 Uova,
1 Noce Burro,
1/2 Cucchiaio Zucchero,
1 Cucchiaio Vino Bianco,
1 Pizzico Sale,
Olio Di Semi Per Friggere,
Zucchero A Velo Per I Dolci','Fate fondere il burro a fuoco basso. Mettete la farina sul piano di lavoro, fate la fontana e versatevi il burro, le uova intere, il vino bianco e lo zucchero. Sbattete gli ingredienti e, quando l''impasto si sarà un po'' rassodato, lavoratelo con le mani impastando per una decina di minuti, fino a quando sarà morbido. Raccoglietelo a palla, mettetelo in una ciotola infarinata, coprite con un canovaccio piegato in quattro e lasciatelo riposare per un''oretta. Trascorso questo tempo, dopo aver infarinato leggermente il piano di lavoro, dividete la palla in due pezzi e stendetela, con il mattarello, ad uno spessore di due o tre mm. Con la rotellina dentata ricavatene delle strisce larghe un paio di cm che potrete annodare morbidamente. Riempite a metà la padella con l''olio e quando sarà caldo friggete due o tre frittelle alla volta lasciandoli dorare due minuti per parte. Scolateli, passateli su un doppio foglio di carta assorbente e, quando saranno tutti pronti e intiepiditi, spolverateli abbondantemente di zucchero a velo.',2277);
INSERT INTO "ricette" VALUES (7832,'Crostone All''uovo E Prosciutto','Antipasto','Uovo',6,' -','100 G Burro,
200 G Farina,
25 Cl Latte,
5 Uova,
150 G Prosciutto Cotto,
200 G Formaggio Groviera Grattugiato,
Sale,
Pepe','Setacciate la farina sulla spianatoia, disponendola a fontana, fate un incavo al centro e mettetevi 80 g di burro, ammorbidito e a pezzetti, e una presa di sale. Lavorate rapidamente gli ingredienti, aggiungendo tanta acqua quanta ne occorre per ottenere un impasto omogeneo e sodo. Raccoglietelo a palla e lasciatelo riposare in un luogo fresco per un''ora, coperto con un canovaccio umido. Mettete in una scodella i tuorli d''uovo, versate il latte e mescolate in continuazione con un cucchiaio di legno, in modo da amalgamare bene gli ingredienti ed ottenere un composto cremoso. Aggiungetevi il prosciutto cotto, tritato finemente, il Groviera grattugiato, il sale necessario e una macinata di pepe e rimestate con cura. In una terrina montate a neve ben ferma gli albumi, con una frusta o uno sbattitore elettrico, poi incorporateli delicatamente al composto di tuorli e prosciutto, facendo attenzione a non smontarli. A questo punto stendete la pasta in una sfoglia sottile, ponetela in una teglia rotonda, unta col resto del burro, e fatela cuocere in forno a 180 gradi per un quarto d''ora. Trascorso questo tempo, sfornate la pasta e distribuitevi sopra il composto preparato. Passate la torta nel forno, sempre alla stessa temperatura, per altri 10 minuti, o fino a quando il ripieno risulterà ben gonfio. Dopodichè estraete il tortino dal forno, lasciatelo riposare per qualche minuto a temperatura ambiente, quindi estraetelo delicatamente dalla teglia, trasferitelo su un piatto di portata e servitelo.',3419);
INSERT INTO "ricette" VALUES (7833,'Crostone Alla Napoletana','Antipasto','Acciughe',4,'Luogo: Campania. Luogo: Napoli.','1 Fetta Grande Pane (biscottato),
Burro,
2 Filetti D''acciughe,
3 Fettine Mozzarella,
Pezzetti Di Pomodoro Rosso E Sodo','Imburrate leggermente il pane, posatevi sopra i filetti d''acciughe e la mozzarella, distribuite qua e la il pomodoro. Posate su un piatto e passate in forno, a piena potenza, per 30-40 secondi o finché la mozzarella comincia a fondersi. Lasciate raffreddare per 1-2 minuti. Potete infine cospargere con origano o basilico tritato.',1090);
INSERT INTO "ricette" VALUES (7834,'Crostone Consovero','Antipasto','Formaggio Gorgonzola',3,' -','1 Fetta Pagnotta Grande,
1 Uovo,
1 Fetta Formaggio Gorgonzola,
Sale','Tagliare una fetta di pane spessa 2 cm circa, praticare un foro al centro con le dita e posare sulla piastra o su una pentola molto calda. Rompere l''uovo e versarlo all''interno del foro. Lasciare cuocere, salare, girare con una spatola, stendere sopra del gorgonzola e lasciare fondere. L''uovo deve ancora essere molle.',548);
INSERT INTO "ricette" VALUES (7835,'Crostoni Agli Asparagi','Antipasto','Asparagi',4,' -','2 Confezioni Punte Di Asparagi Surgelate,
Sale,
120 G Burro,
8 Fette Pancarré,
50 G Formaggio Parmigiano Grattugiato,
60 G Formaggio Emmenthal Grattugiato','Fate lessare in acqua bollente salata le punte di asparagi ancora surgelate e scolatele bene (se avete acquistato gli asparagi freschi, lavateli con cura e fateli cuocere, in piedi in una casseruola, legati a mazzetti, dopo averne pareggiato il gambo, in modo che risultino tutti della stessa altezza). Quando gli asparagi saranno cotti, fateli insaporire in un tegame largo con una noce di burro, rigirandoli una sola volta con delicatezza. In un altro tegame fate friggere le fette di pane private della crosta con 50 g di burro; lasciatele dorare da un solo lato, fate sgocciolare il condimento, quindi adagiatele in una grande teglia imburrata. Distribuitevi gli asparagi (che avrete tagliato della stessa lunghezza delle fette di pane) e cospargete con entrambi i formaggi grattugiati e con qualche fiocchetto di burro. Ponete la teglia in forno a calore moderato e lasciatevela per 15 minuti circa, in modo che il formaggio possa gratinarsi.',2702);
INSERT INTO "ricette" VALUES (7836,'Crostoni Agli Scampi','Antipasto','Scampi',4,' -','20 Scampi Con Il Guscio,
Sale,
4 Fette Pancarré,
80 G Burro,
25 G Farina,
25 Cl Brodo Di Dadi,
Pepe,
100 G Formaggio Parmigiano,
3 Tuorli D''uovo','Lavate gli scampi e scottateli per 5 minuti in acqua bollente salata; poi scolateli, lasciateli intiepidire e sgusciateli. Private le fette di pancarré della crosta e imburratele abbondantemente; guarnitele con gli scampi, quindi disponetele, ben ravvicinate, su un piatto che possa andare in forno e che avrete unto di burro. Fate fondere ora il restante burro (circa 25 g) in una casseruolina e stemperatevi la farina, rimestando con un cucchiaio di legno per eliminare eventuali grumi; diluite con il brodo caldo, regolate di sale e di pepe e lasciate cuocere per altri 10 minuti, senza mai smettere di rimestare. Togliete dal fuoco la salsa vellutata così ottenuta e incorporatevi il parmigiano grattugiato e i tuorli, amalgamando tutto alla perfezione. Coprite ora i crostoni con la salsa, infornateli a 200 gradi per 15 minuti, quindi serviteli.',3468);
INSERT INTO "ricette" VALUES (7837,'Crostoni Ai Funghi','Antipasto','Funghi',4,' -','300 G Funghi Champignon,
1 Cucchiaino Farina,
1/2 Limone,
10 Cl Vino Bianco Secco,
2 Tuorli D''uovo,
8 Fette Pane In Cassetta,
Olio D''oliva,
Burro,
Sale','Sciogliere 70 g di burro, unire la farina e, mescolando, soffriggere fino a quando sarà leggermente dorata. Unire i funghi, mescolare, bagnare con il succo di limone, salare, coprire e cuocere per 15 minuti. Scaldare poco olio, friggere le fette di pane e disporle su un piatto da tenere al caldo. Bagnare i funghi con 10 cl di vino e far evaporare, togliere dal fuoco e incorporare i tuorli. Distribuire i funghi sul pane e servire subito.',2972);
INSERT INTO "ricette" VALUES (7838,'Crostoni Ai Funghi (2)','Antipasto','Funghi',4,' -','8 Fette Pane Pugliese (o Baguette),
500 G Funghi Porcini,
50 Cl Salsa Mornay,
1 Ciuffo Prezzemolo,
Formaggio Grana Grattugiato,
Formaggio Groviera Grattugiato','Tagliare il pane a fette regolari, possibilmente tonde. Pulire i porcini lavandoli con uno straccio umido, tagliarli a fettine, mettere in una padella un velo d''olio con uno spicchio di aglio intero, quando l''olio sarà ben caldo far trifolare i funghi per 3 minuti girandoli continuamente, aggiustare di sale, togliere dal fuoco e aggiungere il prezzemolo tritato finemente. Quindi a questo punto aggiungere i funghi trifolati alla salsa Mornay, amalgamare bene il tutto, depositare la salsa con l''aiuto di un cucchiaio sopra ad ogni crostone, spolverare con del grana, l''emmenthal tagliato a fettine piccole e gratinare in forno, servire molto caldo.',2732);
INSERT INTO "ricette" VALUES (7839,'Crostoni Ai Gamberi','Pesce','Gamberi',4,' -','8 Fette Pancarré (o Pane Raffermo),
500 G Gamberetti Sgusciati,
1 Ciuffo Prezzemolo,
1 Rametto Maggiorana,
14 Foglie Basilico,
2 Foglie Salvia,
2 Spicchi Aglio,
200 G Formaggio Robiola,
Vino Bianco Secco,
Paprica,
Burro,
Sale,
Pepe','Mescolare il formaggio con tutte le erbe aromatiche tritate, lasciando da parte un po'' di prezzemolo, e con una macinata di pepe e un pizzico di sale. Scaldare in una padella 30 g di burro con l''aglio, insaporirvi i gamberetti, spruzzare di vino, salare e pepare, aromatizzare con paprica e prezzemolo e, evaporato il vino, toglierli dal fuoco. (N.B.Se usate quelli surgelati basta scottarli appena in poca acqua bollente e poi ripassarli in padella, a fuoco già spento, dopo aver proceduto come sopra.-ho scoperto che così facendo i gamberetti non si riducono ai minimi termini, mantengono il sapore e restano carnosi-). Tostare il pancarré senza crosta (se usate il pane raffermo potete lasciarla), spalmare 4 fette con il composto di formaggio, coprire con le altre 4, velare i bordi con la crema rimasta (potete anche non farlo tanto al primo morso il formaggio deborda e si ottiene lo stesso effetto). Suddividere sui crostoni i gamberetti e servire.',3342);
INSERT INTO "ricette" VALUES (7840,'Crostoni Ai Peperoni','Antipasto','Peperoni',4,' -','8 Fette Pane Toscano,
2 Peperoni Gialli Grandi E Carnosi,
1 Cipolla,
1 Spicchio Aglio,
80 G Prosciutto Crudo,
100 G Pomodori Pelati,
1/2 Bicchiere Vino Bianco,
1 Ciuffo Prezzemolo,
1 Cucchiaio Capperi,
1 Mestolo Brodo,
Sale','Mondare i peperoni, lavarli, privarli del picciolo e dei semi e tagliarli a listarelle sottili. Lavare con cura il prezzemolo, eliminare i gambi e tritare finemente le foglie. Tritare anche la cipolla e il prosciutto e mettere questi ultimi in una casseruola con uno spicchio di aglio e il brodo. Lasciare insaporire un poco il tutto, poi aggiungere i peperoni, i pomodori pelati e i capperi. Irrorare con il vino bianco, aggiustare di sale e lasciare cuocere il tutto a fuoco basso per 30 minuti circa. A fine cottura eliminare lo spicchio di aglio, unire il prezzemolo tritato e distribuire il tutto sulle fette di pane tostate.',1686);
INSERT INTO "ricette" VALUES (7841,'Crostoni Al Formaggio','Antipasto','Formaggio Taleggio',4,' -','4 Fette Pane Casereccio,
6 Fette Formaggio Taleggio,
100 G Prosciutto Cotto Tritato,
200 G Funghi Champignon,
Prezzemolo Tritato,
1 Tuorlo D''uovo,
Vino Bianco,
4 Cucchiai Olio D''oliva,
Paprica Dolce,
Sale,
50 G Formaggio Emmenthal Grattugiato,
50 G Formaggio Olandese Grattugiato,
1 Spicchio Aglio','Far saltare in padella i funghi affettati con 1 cucchiaio di olio e l''aglio, unire il vino e portare a cottura. Eliminare l''aglio, unire prezzemolo, prosciutto, formaggi grattugiati e tuorlo, mescolare e salare. Tostare il pane unto con olio d''oliva, cospargerlo con il composto, coprirlo con il taleggio, cospargere con paprica e passarlo sotto il grill.',4146);
INSERT INTO "ricette" VALUES (7842,'Crostoni Al Gorgonzola','Antipasto','Formaggio Gorgonzola',4,' -','8 Fette Pancarré,
4 Fette Prosciutto Cotto,
50 G Burro,
100 G Formaggio Gorgonzola,
60 G Ricotta','Mettete le fette di pancarré sul tagliere, dividetele a metà trasversalmente e privatele della crosta. Tagliate a triangolo anche le fette di prosciutto cotto, facendo in modo che abbiano le stesse dimensioni di quelle di pane. Mettete il burro, un poco ammorbidito, in una terrina e incorporatevi il gorgonzola a pezzetti e la ricotta. Amalgamate gli ingredienti lavorandoli con un cucchiaio di legno fino a quando avrete ottenuto un composto cremoso. Coprite i triangoli di pane con la crema di gorgonzola, quindi riunitene due alla volta, facendo combaciare le parti spalmate di crema e inserendovi un triangolo di prosciutto. Infornate i crostoni a 220 gradi per 5 minuti; serviteli caldissimi, su un piatto da portata coperto da un tovagliolo.',2928);
INSERT INTO "ricette" VALUES (7843,'Crostoni Al Paté Di Olive Nere','Antipasto','Formaggio Camembert',4,' -','12 Fette Pane,
Paté Di Olive Nere,
150 G Formaggio Camembert,
4 Cipollotti,
Olio D''oliva,
Pepe','Mondare i cipollotti e affettarli ad anelli. Spalmare abbondantemente le fette di pane con il paté di olive, ricoprirle con fettine di formaggio e cospargerle con gli anelli di cipollotto. Condire con un filo di olio, pepare e servire.',1702);
INSERT INTO "ricette" VALUES (7844,'Crostoni Al Salmone','Antipasto','Salmone',4,' -','8 Fette Pane Casereccio,
8 Fette Salmone Affumicato,
70 G Burro,
1 Limone,
5 Rametti Menta,
2 Cucchiai Olio D''oliva','Sistemate le fette di pane casereccio sulla piastra del forno e fatele tostare a 200 gradi per pochi minuti da entrambe le parti. Sfornatele quando sono leggermente dorate e trasferitele sul piano di lavoro. Fate ammorbidire il burro a temperatura ambiente e spalmatelo con un coltello sulle fette di pane. Ponete su ciascuna anche una o due fette di salmone, a seconda delle dimensioni, e cospargetele con un filo d''olio d''oliva. Insaporite ogni crostone con qualche goccia di succo e una grattatina di scorza di limone, infine metteteli su un piatto di portata. Guarnite con i rametti di menta, lavati e asciugati, e con mezzo limone tagliato a rondelle sottili.',3357);
INSERT INTO "ricette" VALUES (7845,'Crostoni Al Taleggio','Antipasto','Formaggio Taleggio',4,' -','8 Fette Pancarré,
250 G Formaggio Taleggio,
1 Melanzana,
1 Zucchina,
Olio D''oliva,
Sale,
Pepe Nero','Mondate, lavate e asciugate la melanzana e la zucchina, tagliatele a fettine di alcuni millimetri di spessore nel senso della lunghezza, cuocetele brevemente alla griglia dai due lati e conditele con un po'' d''olio, sale, pepe e tenetele da parte. Fate grigliare le fette di pancarré, irroratele con poco olio versato a filo, insaporite con un pizzico di sale. Disponete sopra il pane le verdure, copritele con due fettine di taleggio, spolverizzatele con un po'' di pepe macinato al momento. Passate i crostoni alcuni minuti in forno a calore moderato, evitando però di far sciogliere il formaggio. Serviteli tiepidi. Vini di accompagnamento: Oltrepò Pavese Pinot Nero (in bianco) DOC, Verdicchio Castelli Di Jesi DOC, Alezio Rosato DOC.',2867);
INSERT INTO "ricette" VALUES (7846,'Crostoni All''emmenthal','Antipasto','Formaggio Emmenthal',4,' -','1 Pancarré Da 500 G,
150 G Formaggio Emmenthal,
100 G Burro,
1 Cucchiaio Farina,
25 Cl Brodo Di Dadi,
Sale,
Pepe Bianco,
Noce Moscata Grattugiata,
1 Tuorlo D''uovo','Tagliate tutta la crosta al pancarré, poi riducetelo a fette alte circa un centimetro. Grattugiate l''Emmenthal. Ponete al fuoco una casseruolina con 50 g di burro, fatelo fondere, quindi aggiungete la farina, mescolando bene per evitare la formazione di grumi. Non appena questa avrà preso colore, diluitela con il brodo caldo, continuando a mescolare; salate appena, insaporite con un pizzico di pepe bianco e una presa di noce moscata. Fate addensare la besciamella, lasciandola cuocere, a fuoco basso, per circa 10 minuti, senza smettere di rimestare. Poi levate il recipiente dal fuoco e incorporatevi metà dell''Emmenthal grattugiato e il tuorlo, amalgamando bene. Fate friggere nel restante burro le fette di pancarré, senza però lasciarle dorare troppo, e scolatele dall''unto di cottura su un foglio di carta assorbente da cucina. Quando tutte le fette saranno pronte, spalmate su di esse il composto preparato, cospargetele con il restante Emmenthal, adagiatele sulla placca del forno e fatele dorare per circa 10 minuti a 200 gradi. Servite i crostoni all''Emmenthal ben caldi.',3112);
INSERT INTO "ricette" VALUES (7847,'Crostoni Alla Boscaiola','Antipasto','Funghi Porcini',1,' -','8 Fette Pane Casereccio,
Olio D''oliva Extra-vergine,
5 Spicchi Aglio,
1 Pizzico Pepe Nero Macinato Al Momento,
2 Pomodori,
Alcuni Funghi Porcini,
1 Mazzetto Prezzemolo Fresco Tritato,
Vino','Tostare le fette di pane. Sfregarle con l''aglio e cospargerle con poco olio. In un tegame fare soffriggere in un po'' di olio i funghi porcini a fette; salare, pepare e bagnare col vino che verrà fatto evaporare. Da ultimo aggiungere il prezzemolo. Tagliare i pomodori a cubetti piccoli. Distribuire il pomodoro crudo sul pane e aggiungere il composto di funghi dopo averlo fatto raffreddare un po''.',2154);
INSERT INTO "ricette" VALUES (7848,'Crostoni Alla Hollywood','Antipasto','Paté Di Fegato',6,' -','2 Filoni Pane Fresco,
200 G Paté Di Fegato,
200 G Lingua Salmistrata,
1 Cipolla,
1 Uovo Per Ogni Fetta Di Pane,
Gelatina In Briciole','Tagliate il pane a fette e spalmatevi sopra 1-2 cm di paté di fegato. Coprite con la lingua salmistrata, quindi cospargete di cipolla cruda tritata finissima. Su questa deponete un uovo in camicia che avrete regolato di forma con un bicchiere. Quindi se gradite, coprite l''uovo con dadini piccolissimi di gelatina.',3992);
INSERT INTO "ricette" VALUES (7849,'Crostoni Alla Mozzarella','Antipasto','Mozzarella',4,' -','1 Forma Di Pane Toscano,
2 Mozzarelle,
8 Foglie Salvia,
Olio D''oliva,
Sale,
Pepe,
3 Pomodori,
1 Uovo,
100 G Pangrattato,
Per La Salsa:,
3 Cucchiai Olio D''oliva,
2 Rametti Prezzemolo,
1/2 Cipolla,
1 Bicchiere Brodo','Preparate la salsa: in una casseruolina con l''olio fate soffriggere il prezzemolo e la cipolla tritati, bagnate con il brodo e mescolate con un cucchiaio di legno. Tagliate il pane toscano ricavando 16 fette uguali, spesse circa 1/2 cm. Scottate i pomodori in una pentola con acqua bollente, pelateli e privateli dei semi; affettate le mozzarelle. Disponete sul piano di lavoro otto fette di pane, adagiate su ciascuna due fette di mozzarella, una foglia di salvia e alcuni filetti di pomodoro, condite con sale e pepe, infine ricoprite con le fette di pane rimaste. In una terrina sbattete l''uovo con un pizzico di sale, immergetevi velocemente i panini, facendo in modo che vengano rivestiti su entrambi i lati, quindi passateli nel pangrattato. Fermate i tramezzini ottenuti con due stecchini di legno, poneteli in una padella con abbondante olio d''oliva, già caldo, e fateli friggere a fuoco medio fino a quando il pane sarà diventato dorato e croccante. Trasferite i crostoni su un piatto di portata, cospargeteli con un poco della salsina preparata e serviteli subito passando a parte il resto della salsa.',5760);
INSERT INTO "ricette" VALUES (7850,'Crostoni Alla Mozzarella (2)','Antipasto','Mozzarella',4,' -','4 Fette Pane Casereccio,
4 Cucchiai Olio D''oliva,
4 Cucchiai Aceto Di Vino,
125 G Mozzarella,
4 Filetti D''acciughe Sott''olio,
1 Cucchiaino Capperi','Mettete il pane sulla placca del forno rivestita con carta da forno o di alluminio. Emulsionate insieme olio e aceto e spruzzateli sul pane. Tagliate a dadini la mozzarella e mescolatevi le acciughe tritate e i capperi. Disponete il composto sul pane e fate gratinare per qualche minuto nel forno ben caldo.',2328);
INSERT INTO "ricette" VALUES (7851,'Crostoni Alla Pizzaiola','Antipasto','Pomodori',4,' -','Alcune Fette Pane Raffermo Con La Mollica Ben Compatta,
2 Spicchi Aglio,
4 Pomodori Maturi,
1 Mozzarella,
Origano,
Sale,
Pepe','Tagliate delle fette di pane raffermo (usate possibilmente il pane pugliese o simile, col quale otterrete delle fette grandi) spesse un dito, abbrustolitele sulla piastra del forno e, ancora calde, profumatele con l''aglio schiacciato. Disponete le fette in una larga teglia (possibilmente con fondo antiaderente e senza condimenti) e su ogni fetta distribuite 1 cucchiaio di pomodoro passato e 1 dischetto di mozzarella, spolverizzando con sale, pepe e origano. Passate in forno caldo per 5 minuti e servite i crostoni molto caldi.',1098);
INSERT INTO "ricette" VALUES (7852,'Crostoni Alla Russa','Antipasto','Formaggio Fontina',4,'Luogo: Russia.','1 Confezione Pancarré,
1 Uovo Intero,
25 Cl Latte,
50 G Prosciutto Cotto,
60 G Formaggio Fontina,
Olio D''oliva','Tagliate il pancarré a fette di mezzo centimetro. Bagnate leggermente le fette nel latte, poi disponete sopra ad ognuna una fetta di prosciutto e una sottile di formaggio e coprite con un''altra fetta di pancarré preparata allo stesso modo. Legate in croce con un filo sottile, passate nell''uovo sbattuto e friggete in olio bollente. Togliete i fili e servite su un piatto scaldato.',2845);
INSERT INTO "ricette" VALUES (7853,'Crostoni Alla Svedese','Antipasto','Anguilla',4,'Luogo: Svezia.','600 G Anguilla Affumicata,
1 Pancarré Da 500 G,
2 Pomodori,
50 G Burro,
Sale,
1 Tazza Maionese,
1 Limone (facoltativo)','Spellate l''anguilla e sfilettatela. Tagliate a fette il pancarré levate tutta la crosta e imburrate abbondantemente ogni fetta. Riducete i filetti di anguilla alle dimensioni di mezza fetta di pane. Adagiate su un lato di ogni fetta il filetto di anguilla e, accanto, un paio di fette di pomodoro, tagliate in modo che non sporgano dal pane; salatele leggermente. Con la maionese fate delle decorazioni su ogni crostone, formando una specie di grata che ricopra l''anguilla e i pomodori. Vi suggeriamo una variante: al posto dei pomodori, potete disporre sul pancarré due fettine di limone private della buccia e su queste due filetti di anguilla disposti trasversalmente.',4312);
INSERT INTO "ricette" VALUES (7854,'Crostoni Alle Acciughe','Antipasto','Acciughe',4,' -','8 Fette Pane In Cassetta,
60 G Burro,
250 G Acciughe Fresche,
4 Uova,
3 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cucchiaio Prezzemolo Tritato,
Sale','Passare le fette di pane private della crosta in 2 uova sbattute con sale e farle dorare nel burro, sgocciolarle e sistemarle sulla placca del forno. Mescolare alle acciughe, pulite e tagliate a pezzetti, uova, parmigiano e sale. Distribuire il composto sul pane e cuocere in forno caldo per 20 minuti circa. Spolverizzare di prezzemolo e servire caldo.',2421);
INSERT INTO "ricette" VALUES (7855,'Crostoni Con Crema Di Formaggio','Antipasto','Formaggio Robiola',4,' -','6 Crostoni Pane Casereccio,
250 G Formaggio Cremoso (formaggio Robiola),
50 G Foglie Di Insalata Rucola,
1 Cucchiaio Senape,
Sale,
Pepe','Affettate il pane e passatelo in forno per cinque minuti. Nel frattempo servendovi di un mixer da cucina, frullate insieme le foglie di rucola precedentemente lavate e asciugate con carta assorbente, il formaggio, la senape, il sale e il pepe. Mescolate per 