o solida) e incorporateli al composto, servendovi di un cucchiaio di legno, un attimo prima di friggere per ottenere una pastella morbida. Aggiungete gli albumi poco alla volta per poter controllare la consistenza della pastella: se diventa troppo liquida, si potrebbe disfare durante la cottura. Tamponate i pezzi di pesce per asciugarli in modo che la pastella aderisca bene. Salate e pepate leggermente. Servendovi di una forchetta, immergete un pezzo alla volta nella pastella e giratelo in modo da rivestirlo completamente. Immergete i pezzi di pesce nella friggitrice con l''olio d''oliva riscaldato a 180 gradi. Se non disponete di una friggitrice elettrica, regolatevi come segue per verificare la temperatura dell''olio: immergete nell''olio un poco di pastella o un pezzettino di pane bianco. Se intorno al pane o alla pastella si formano tante bollicine sfrigolanti, l''olio è caldo al punto giusto. Friggete la carpa fino a quando è ben dorata da tutti i lati. Togliete i pezzi di pesce dalla friggitrice e fateli sgocciolare sulla carta assorbente. Servite subito. --- CONSIGLI. Per preparare la pastella ci sono diverse varianti, fra cui quella che prevede l''utilizzo dell''acqua minerale frizzante al posto della birra: si ottiene una pastella ugualmente croccante, ma dal sapore più neutro e delicato.',3746);
INSERT INTO "ricette" VALUES (18393,'Pesce Gatto Alla Moda Del Delta','Pesce','Pesci Gatto',4,' -','4 Pesci Gatto,
Patata,
Carota,
Cipolla,
Sedano,
Prezzemolo,
Aglio,
1 Limone,
Salsa Di Pomodoro,
Vino Bianco Secco,
Farina,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Eviscerare e lavare i pesci, quindi infarinarli e friggerli in olio caldo. Brasare in poco olio un trito d''aglio e prezzemolo e le altre verdure affettate finemente; salare, pepare. Sfumare col vino e unire scorza di limone grattugiata, pomodoro, un mestolino d''acqua; accomodarvi i pesci. Incoperchiare e cuocere pochi minuti.',2782);
INSERT INTO "ricette" VALUES (18394,'Pesce Gatto Alla Polesana','Pesce','Pesci Gatto',4,' -','4 Pesci Gatto Da 350 G,
Olio D''oliva Extra-vergine,
Aglio,
Prezzemolo,
1 Cipolla,
1 Carota,
1 Patata,
2 Coste Sedano,
Vino Trebbiano Di Romagna,
1/2 Limone (scorza),
Salsa Di Pomodoro,
Farina,
Burro,
Sale,
Pepe,
Spezie','Friggere i pesci (lavati ed eviscerati) infarinati nell''olio ben caldo. In 2 cucchiai d''olio far appassire un trito d''aglio e prezzemolo con le verdure a fettine; salare; pepare. Unire vino, buccia grattugiata, pomodoro, un po'' di burro, 2-3 cucchiai d''acqua, poi i pesci. Cuocere coperto per 5 minuti e poi addensare il fondo di cottura. Servire sulla polenta.',3649);
INSERT INTO "ricette" VALUES (18395,'Pesce Gatto Fritto','Pesce','Pesci Gatto',4,' -','8 Pesci Gatto Da 200 G,
500 G Strutto,
Farina Di Mais,
Sale Marino','Lavare, eviscerare e decapitare i pesci gatto. Spellarli (se sono d''allevamento si spellano più facilmente) e infarinarli molto bene con farina di mais molto fine. Friggerli nello strutto a temperatura elevata (lo strutto regge bene le temperature elevate). Salarli e mangiarli come pannocchie di pesce.',6429);
INSERT INTO "ricette" VALUES (18396,'Pesce Gatto In Umido','Pesce','Pesci Gatto',4,' -','4 Pesci Gatto Da 350 G,
2 Cucchiai Aceto Di Vino,
1 Mestolino Salsa Di Pomodoro,
Carota,
Sedano,
Cipolla,
Olio D''oliva Extra-vergine,
Alcune Foglie Basilico,
Sale,
Pepe','Lavare ed eviscerare i pesci; soffriggere nell''olio carota, sedano e cipolla, quindi unirvi i pesci facendo prendere sapore; sfumare con l''aceto e un poco d''acqua e far evaporare. Unire la salsa di pomodoro, aggiustare di sale e di pepe e far cuocere. A fine cottura cospargere basilico fresco sminuzzato. Servire con polenta abbrustolita.',2194);
INSERT INTO "ricette" VALUES (18397,'Pesce Gratinato Con Salsa Allo Yogurth','Pesce','Yogurth',6,' -','1 Pesce Intero Di 1500 G (orata, Dentice),
1 Lime,
Sale,
4 Cucchiai Olio D''oliva,
1 Peperoncino Verde,
2 Peperoncini Rossi,
Alcune Foglie Di Coriandolo,
Per La Salsa Allo Yogurth:,
1 Cucchiaio Olio D''oliva,
1 Cucchiaio Zenzero Fresco Grattugiato,
2 Spicchi Aglio,
1 Scalogno,
2 Peperoncini Rossi,
1/2 Cucchiaino Cumino,
1 Pizzico Cannella,
1 Grattatina Noce Moscata,
Pepe,
1 Rametto Citronella,
20 Cl Yogurth','Pulite il pesce, raschiatene la superficie con la lama di un coltello per eliminare le squame, quindi lavatelo internamente ed esternamente e asciugatelo con della carta assorbente da cucina. Praticate su entrambi i fianchi del pesce dei tagli paralleli, distanti 2 cm l''uno dall''altro, che incidano la pelle e parzialmente anche la polpa sottostante. Ponete il pesce in un piatto fondo, cospargetelo con il succo di lime e il sale, facendo in modo che i due ingredienti penetrino nei tagli, infine copritelo con un foglio di carta stagnola e lasciatelo marinare per circa mezz''ora. Nel frattempo preparate la salsa allo yogurth: fate scaldare l''olio in una padella e rosolatevi lo zenzero grattugiato, l''aglio pelato e schiacciato, la citronella e lo scalogno tritati, a calore moderato per 4-5 minuti. Dividete a metà i peperoncini rossi, privateli dei semi e tritate finemente la polpa. Unite i peperoncini al soffritto di spezie e lasciatelo raffreddare, quindi mescolatevi il cumino, la cannella, una macinata abbondante di pepe e la noce moscata e legate tutto con lo yogurth. Ungete una capace pirofila con due cucchiai d''olio d''oliva, mettetevi il pesce e copritelo con la salsa preparata. Passate la preparazione nel forno caldo (220 gradi) per 25-30 minuti: il pesce è cotto quando la spina dorsale può essere estratta con facilità. Fate scaldare il resto dell''olio d''oliva in una casseruola e rosolatevi dolcemente i peperoncini rossi e quello verde, tagliati a metà e privati dei semi, per alcuni minuti mescolando continuamente. Distribuite i peperoncini e il loro olio sul pesce, cospargetelo con le foglie di coriandolo e servite insieme a patate bollite o riso lessato. --- CONSIGLI. Si tratta di un piatto tipico dell''India meridionale, dove viene chiamato ''''Masala Dum Machchi''''. E'' una preparazione molto piccante, dato l''abbondante uso di peperoncino, il cui sapore ''''ardente'''' viene solo parzialmente attenuato dallo yogurth. Il risultato è assai gustoso, anche se un po'' forte per il nostro palato.',3244);
INSERT INTO "ricette" VALUES (18398,'Pesce In Carpione','Pesce','Tinche',6,' -','1000 G Tinche Non Troppo Grandi,
25 Cl Olio D''oliva,
1/2 Bicchiere Acqua,
3/4 Bicchiere Aceto Di Vino,
1/2 Tazza Farina,
1/2 Cipolla Affettata,
8 Foglie Salvia,
Sale,
Pepe In Grani Pestato','Pulite bene il pesce, infarinatelo e friggetelo nell''olio bollente (tenendone a parte un cucchiaio per il soffritto). Preparate la marinata: fate soffriggere in un cucchiaio d''olio la cipolla, aggiungete la salvia e, dopo qualche minuto, l''acqua e l''aceto; portate a ebollizione, facendo leggermente ridurre. Mettete il pesce fritto in una vaschetta di vetro (o in una terrina); salatelo e vensatevi sopra la marinata calda. Aggiungete il pepe in grani pestato, quindi coprite bene e lasciate marinare per 12 ore prima di servire. In luogo fresco e aerato il pesce in carpione si conserva anche per 15-20 giorni: se lo si tiene in frigorifero, va tolto almeno 3 ore prima di servirlo.',3186);
INSERT INTO "ricette" VALUES (18399,'Pesce In Carpione (2)','Pesce','Pesce Piccolo Misto',6,' -','1000 G Pesce Piccolo Misto,
25 Cl Olio D''oliva,
1/2 Bicchiere Acqua,
3/4 Bicchiere Aceto Di Vino,
1/2 Tazza Farina,
1/2 Cipolla Affettata,
8 Foglie Salvia,
Sale,
Pepe In Grani Pestato','Pulite bene il pesce, infarinatelo e friggetelo nell''olio bollente (tenendone a parte un cucchiaio per il soffritto). Preparate la marinata: fate soffriggere in un cucchiaio d''olio la cipolla, aggiungete la salvia e, dopo qualche minuto, l''acqua e l''aceto; portate a ebollizione, facendo leggermente ridurre. Mettete il pesce fritto in una vaschetta di vetro (o in una terrina); salatelo e vensatevi sopra la marinata calda. Aggiungete il pepe in grani pestato, quindi coprite bene e lasciate marinare per 12 ore prima di servire. In luogo fresco e aerato il pesce in carpione si conserva anche per 15-20 giorni: se lo si tiene in frigorifero, va tolto almeno 3 ore prima di servirlo.',3186);
INSERT INTO "ricette" VALUES (18400,'Pesce Persico','Pesce','Pesce',4,' -','4 Filetti Di Pesce,
5 Cucchiai Olio D''oliva,
2 Cipolle,
2 Spicchi Aglio,
Burro,
Pomodori Maturi,
1 Limone,
Sale','Far rosolare in olio, cipolla e aglio, imburrare in un tegame, metterci il pesce, mettere il soffritto, pomodoro e buccia grattugiata di limone, cospargere di fiocchetti di burro e metterli nel forno e congelare.',1712);
INSERT INTO "ricette" VALUES (18401,'Pesce Persico Alla Comasca','Pesce','Pesce Persico',4,'Luogo: Lombardia. Luogo: Como.','600 G Filetti Di Pesce Persico,
Succo Di Limone,
Aromi,
Olio D''oliva,
Farina,
2 Uova,
Pangrattato,
Abbondante Burro,
Sale','Far marinare i filetti di pesce con olio, aromi e succo di limone. Scolarli, asciugarli, passarli nella farina, nelle uova sbattute e infine nel pangrattato. Friggerli in abbondante burro e servirli ben caldi.',3186);
INSERT INTO "ricette" VALUES (18402,'Pesce Persico Alla Maniera Umbra','Pesce','Pesce Persico',4,'Luogo: Umbria.','800 G Filetti Di Persico,
1 Manciata Capperini Selvatici,
Farina,
1 Noce Piccola Burro,
Olio D''oliva Extra-vergine Umbro,
1 Bicchiere Vino Bianco Grechetto,
1 Limone (succo),
Sale,
Pepe','Infarinare i filetti di pesce e dorarli in olio e burro. Sfumare con 1 bicchiere di vino e unire i capperi. Spruzzare di succo di limone, aggiustare di sale e pepe e far cuocere a fuoco vivo. Servire ben caldi, irrorati col fondo di cottura.',2152);
INSERT INTO "ricette" VALUES (18403,'Pesce Persico Alla Milanese','Pesce','Pesce Persico',4,'Luogo: Lombardia. Luogo: Milano.','600 G Filetti Di Pesce Persico,
1 Limone,
Farina,
1 Uovo,
Pangrattato,
Abbondante Burro,
Olio D''oliva,
Sale','Lasciate macerare per un''ora i filetti di pesce in olio e succo di limone. Sgocciolateli, infarinateli leggermente, scuotete l''eccedenza e poi passateli nell''uovo sbattuto e salato e nel pangrattato. In un tegame lasciate sciogliere abbondante burro a fuoco moderato, cuocete i filetti per 6-7 minuti girandoli una volta. Su entrambi i lati deve formarsi una crosticina dorata e morbida. Ritirateli con la paletta forata, asciugateli su carta assorbente, passateli sul piatto da portata caldo, salateli. Vini di accompagnamento: Lugana DOC, Orvieto DOC, Gravina DOC.',3063);
INSERT INTO "ricette" VALUES (18404,'Pesce Persico Alla Salvia','Pesce','Pesce Persico',4,' -','600 G Filetti Di Pesce Persico,
60 G Burro,
8 Foglie Salvia,
Farina,
Sale,
Pepe','Lavate in acqua fredda e asciugate bene i filetti di persico. Infarinateli leggermente e scuotete l''eccedenza di farina. In un tegame lasciate sciogliere il burro insieme alle foglie di salvia e quando è spumeggiante adagiatevi i filetti di pesce e fateli dorare a fuoco moderato. Girate, salate e pepate i vari pezzi che non devono cuocere per più di 7-8 minuti. Serviteli. Vini di accompagnamento: Valle D''Aosta Blanc De Morgex DOC, Bianco Vergine Valdichiana DOC, Gioia Del Colle Bianco DOC.',1231);
INSERT INTO "ricette" VALUES (18405,'Pesce Persico Alle Acciughe','Pesce','Pesce Persico',4,' -','600 G Filetti Di Pesce Persico,
3 Acciughe,
1/2 Bicchiere Vino Bianco Secco,
Limone,
1 Spicchio Aglio,
1 Ciuffetto Prezzemolo,
Farina,
Pepe Di Caienna,
3 Cucchiai Olio D''oliva,
Sale','Lavate, asciugate e infarinate leggermente i filetti. Scaldate in un tegame due cucchiai d''olio e fatevi dorare il pesce da entrambi i lati. Dissalate, diliscate e tritate le acciughe insieme a uno spicchio d''aglio e a un ciuffetto di prezzemolo. Unite un po'' di succo di limone filtrato al colino, il pepe di Caienna, un cucchiaio d''olio e mezzo bicchiere di vino bianco. Amalgamate gli ingredienti e versate il tutto sui filetti di pesce. Salate, pepate, cuocete per 15 minuti circa a fuoco basso. Vini di accompagnamento: Cortese Dell''Alto Monferrato DOC, Bianchello Del Metauro DOC, Taburno Falanghina DOC.',1961);
INSERT INTO "ricette" VALUES (18406,'Pesce Persico Allo Zenzero','Pesce','Pesce Persico',4,' -','Alcuni Filetti Pesce Persico,
Scorza Di Limone Grattugiata,
Succo Di Limone,
Sale,
Fette Sottili Radice Di Zenzero','Cuocere per poco al forno il pesce dopo averlo cosparso con la scorza grattugiata e il succo di limone, il sale, le fette di radice di zenzero.',409);
INSERT INTO "ricette" VALUES (18407,'Pesce Persico In Teglia Alla Crema Verde','Pesce','Pesce Persico',4,' -','8 Filetti Di Persico,
20 Cl Panna,
1 Bicchiere Vino Bianco Secco,
50 G Burro,
Abbondante Cerfoglio,
Abbondante Basilico,
Pangrattato,
Sale,
Pepe','Lavate e asciugate i filetti di pesce, sistemateli in una teglia, cospargeteli con alcuni fiocchetti di burro. Ricopriteli con abbondante cerfoglio e basilico tritati, sale e pepe. Spruzzate sui filetti un bicchiere di vino, versate la panna liquida e distribuite in superficie il pangrattato. Mettete in forno preriscaldato a 180 gradi per circa 10-15 minuti. Servite nel recipiente di cottura. Vini di accompagnamento: Erbaluce Di Caluso DOC, Bianco Vergine Valdichiana DOC, Gioia Del Colle Bianco DOC.',2350);
INSERT INTO "ricette" VALUES (18408,'Pesce San Pietro Con Taccole','Pesce','Pesce San Pietro',4,' -','1 Pesce San Pietro Da 1500 G,
500 G Taccole,
100 G Burro,
Farina,
Barbe Di Finocchio,
Sale,
Pepe','Spuntate le taccole, togliete i fili e insaporitele in un tegame con 60 g di burro. Regolate sale e pepe. Bagnate con un mestolo d''acqua e cuocete coperto, a fuoco basso, per mezz''ora. Intanto pulite il pesce, eliminando testa e coda, togliendo le viscere e ricavandone quattro filetti. Meglio se fate fare questo lavoro al negoziante. In un tegame lasciate sciogliere 40 g di burro, adagiatevi i filetti leggermente infarinati, cuocete, a fuoco moderato, fino a quando hanno preso un bel colore dorato. Disponete su un piatto da portata taccole e filetti, guarnite con le barbe del finocchio e servite. Vini di accompagnamento: Soave Superiore DOC, Montecarlo Bianco DOC, Greco Di Tufo DOC.',2340);
INSERT INTO "ricette" VALUES (18409,'Pesce Sciabola Panato','Pesce','Pesce Sciabola',4,' -','2 Filetti Pesce Sciabola (filetti Da 800 G),
2 Uova,
Prezzemolo,
1 Limone,
Pangrattato,
Olio D''oliva Extra-vergine,
Sale,
1 Macinata Pepe Bianco','Tagliare i filetti in pezzi di una decina di centimetri, liberarli da spine residue, lavarli, asciugarli. Passarli nell''uovo battuto, quindi ben bene in un composto di pangrattato, prezzemolo finemente triturato, poco olio; friggere in olio ben caldo e servire con sale, una macinata di pepe, prezzemolo tritato e scorza di limone a julienne.',1429);
INSERT INTO "ricette" VALUES (18410,'Pesce Sfoglia Con Gianchetti','Antipasto','Gianchetti',6,'Preparazione: 40 minuti. Calorie: 487.','400 G Pasta Sfoglia Surgelata In Rotoli (2 Rotoli),
Per La Spianatoia:,
Farina,
Per Pennellare:,
Uovo,
Per La Placca:,
Burro,
Per Farcire:,
400 G Gianchetti,
150 G Zucchine,
100 G Germogli Di Soia,
1 Cucchiaio Prezzemolo Tritato,
1/2 Bicchiere Vino Bianco Secco,
2 Cucchiai Olio D''oliva,
Sale','Fate scongelare la pasta sfoglia. Appena pronta, srotolatela sulla spianatoia leggermente infarinata e pennellate i 2 pezzi con un poco d''uovo battuto. Sovrapponeteli facendo combaciare perfettamente le due parti, pennellate, una contro l''altra. Con un coltello appuntito e affilatissimo ricavate dalla sfoglia la sagoma di un pesce, leggermente panciuto e provvisto di pinne dorsali e ventrali. (Se non vi sentite sicuri del risultato, preparate un modello in cartoncino). Incidete, marcandole, le pinne e la coda poi, seguendo i contorni del pesce, ritagliatelo verso l''interno a cm 1 dal bordo ma limitando l''incisione allo strato di pasta superiore. Togliete la sfoglia ritagliata e otterrete una specie di grosso vol-au-vent, a forma di pesce, appunto. Pennellatelo ancora tutto d''uovo, dopo aver marcato anche l''occhio. Punzecchiate il pesce con i rebbi di una forchetta quindi sistematelo su una placca imburrata e passatelo nel forno già a 200 gradi per circa 15-18 minuti. Intanto mondate, spuntate le zucchine e tagliatele a bastoncini. Passate rapidamente i gianchetti sotto l''acqua corrente e così pure i germogli di soia. Ponete a riscaldare in una larga padella 2 cucchiaiate d''olio e fatevi rosolare le verdure a fuoco vivo. Sbollentate intanto i gianchetti per circa 2 minuti in abbondante acqua salata e addizionata con mezzo bicchiere di vino. Scolateli e aggiungeteli alle zucchine e ai germogli di soia nella padella. Aggiustate di sale e tenete su fuoco vivace ancora per 2 minuti poi spegnete. Sfornate il pesce-sfoglia e riempitelo con i gianchetti. Cospargete la preparazione con una cucchiaiata di prezzemolo tritato e servitela subito.',3827);
INSERT INTO "ricette" VALUES (18411,'Pesce Spada A Bagnomaria','Pesce','Pesce Spada',4,' -','800 G Pesce Spada,
400 G Olio D''oliva,
2 Spicchi Aglio,
Prezzemolo Tritato,
Succo Di Limone,
Sale,
Pepe Appena Macinato,
100 G Farina','Tagliare il pesce spada in otto fettine piuttosto sottili. Disporli quindi in una cocotta con olio sotto e sopra, aggiungendo l''aglio, il prezzemolo, il succo di limone, sale e pepe. Disporre la farina con acqua sul bordo della cocotta in modo che ponendo sopra il coperchio non possa uscire il vapore. Mettere in forno a bagnomaria, per circa venti minuti. Aprire quando si e portata la cocotta sulla tavola, in modo che il profumo faccia venire l''acquolina.',4843);
INSERT INTO "ricette" VALUES (18412,'Pesce Spada A Giotta','Pesce','Pesce Spada',4,' -','800 G Pesce Spada,
100 G Olio D''oliva,
20 G Capperi Piccoli,
Prezzemolo Tritato,
100 G Salsa Di Pomodoro,
50 G Cipolla Affettata,
Farina,
Sale,
Pepe','Tagliare il pesce spada in quattro fette infarinarlo e farlo cuocere in una padella con l''olio, farlo ben colorare da entrambi i lati. Toglierlo e metterlo in una pirofila. Nella stessa padella e nello stesso olio, rosolare la cipolla ed aggiungere i capperi, il prezzemolo, la salsa di pomodoro, sale e pepe, ed in un secondo tempo le olive. Fare cuocere per pochi minuti e versare sul pesce caldo. Servire',2150);
INSERT INTO "ricette" VALUES (18413,'Pesce Spada Affumicato In Fantasia','Pesce','Pesce Spada',6,' -','12 Fettine Pesce Spada Affumicato,
2 Cespi Insalata Trevigiana,
150 G Sedano,
Per La Salsa:,
200 G Finocchio Lessato,
150 G Mascarpone,
60 G Olio D''oliva,
1 Tuorlo D''uovo,
1 Cucchiaino Aceto Balsamico,
1 Spruzzo Aceto Di Vino Bianco,
Sale,
Pepe','Riunite in un frullatore il finocchio tagliato a pezzetti, il mascarpone, l''olio, il tuorlo e frullate fino a quando avrete ottenuto una crema liscia e compatta. Aggiungete un cucchiaio d''acqua tiepida, uno spruzzo d''aceto bianco, un cucchiaino d''aceto balsamico, sale e pepe. Frullate ancora fino a quando la salsa avrà acquistato una consistenza più fluida. Mondate l''insalata, lavatela, sgocciolatela e disponete le foglie a corona su un piatto da portata. Al centro mettete le fettine di pesce e intorno il sedano tagliato a julienne. Versate un po'' della salsa all''aceto e servite la rimanente in salsiera. Vini di accompagnamento: Collio Müller-Thurgau DOC, Vernaccia Di San Gimignano DOCG, Castel Del Monte Bianco Da Pinot Nero DOC.',2736);
INSERT INTO "ricette" VALUES (18414,'Pesce Spada Agli Aromi','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada (altezza 2 Cm),
Farina,
1 Bicchiere Vino Bianco,
2 Spicchi Aglio,
Prezzemolo,
Menta,
Timo,
Alloro,
Maggiorana,
Peperoncino,
Burro,
Sale,
Pepe','Steccare le fette di pesce con l''aglio e passarle in un velo di farina. Far spumeggiare 50 g di burro nella pentola a pressione, adagiarvi il pesce e cuocere a fuoco vivo 1 minuto per parte. Bagnare con il vino, salare, pepare, unire alloro, maggiorana, timo, menta, prezzemolo e peperoncino. Chiudere la pentola e calcolare 1 minuto e mezzo dal momento del sibilo.',2145);
INSERT INTO "ricette" VALUES (18415,'Pesce Spada Agli Aromi (2)','Pesce','Pesce Spada',4,' -','4 Tranci Pesce Spada (tranci Da 200 G),
1 Spicchio Aglio,
100 G Pangrattato,
1 Limone,
Olio D''oliva Extra-vergine,
Salvia,
Timo,
Rosmarino,
Maggiorana,
Basilico,
Menta,
1 Pizzico Sale Marino Integrale,
1 Macinata Pepe Bianco','Mescolare al pangrattato un trito di aglio ed erbette; unire un pizzico di sale ed una macinata di pepe. Panare i tranci di pesce spada con questo composto e adagiarli in una pirofila. Irrorare con olio e una spruzzatina di limone. Infornare per 30 minuti a 200 gradi.',2030);
INSERT INTO "ricette" VALUES (18416,'Pesce Spada Ai Capperi','Pesce','Pesce Spada',4,' -','4 Trance Pesce Spada,
25 G Capperi,
Olio D''oliva,
Succo Di Limone,
Prezzemolo,
Sale,
Pepe','In un tegame scaldate tanto olio quanto basta a velare il fondo, cuocetevi le trance di pesce tre minuti da ogni parte, salatele. Tritate insieme capperi e prezzemolo, diluite con un po'' d''olio e il succo di 1/2 limone passato al colino. Passate il pesce sul piatto da portata. Versate nel tegame il trito di capperi e succo di limone, mescolate e versatelo sulle trance.',1616);
INSERT INTO "ricette" VALUES (18417,'Pesce Spada Ai Ferri','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada (fette Di 200 G),
1 Pizzico Sale,
1 Pizzico Pepe','Accendete il fuoco sotto ad una padella antiaderente o di ferro in attesa che il recipiente diventi bollente. Quindi adagiatevi dentro, una ad una, le fette di spada badando che cuociano solo per 3 o 4 minuti da entrambe le parti. A fine cottura spegnete il fuoco e deponetele in un piatto salandole e pepandole moderatamente.',874);
INSERT INTO "ricette" VALUES (18418,'Pesce Spada Ai Funghi','Pesce','Pesce Spada',4,' -','800 G Pesce Spada,
150 G Funghi Champignon,
100 G Gamberetti,
100 G Burro,
30 G Farina,
2 Uova,
Cipolla,
Prezzemolo,
1 1/2 Limone,
1/2 Bicchiere Vino Bianco,
Sale,
Pepe,
1/2 Mestolo Brodo','Lavate e asciugate i tranci di pesce spada, poneteli su un piatto, irrorateli con il succo di un limone e lasciate marinare 15 minuti. Cospargete il pesce di sale e pepe poi rosolatelo in una pirofila con 50 g di burro. Cuocete per 10 minuti, unite un trito di prezzemolo e cipolla, quindi fate insaporire il tutto. Bagnate poi con mezzo bicchiere di vino bianco, lasciate evaporare per 5 minuti, quindi togliete dal fuoco e tenete in caldo. Preparate la salsa mescolando la farina con il burro fuso e sciogliendo il tutto con mezzo mestolo di brodo caldo e il fondo di cottura del pesce. Pulite e affettate gli champignon, uniteli alla salsa e cuocete per 30 minuti, aggiungendo 5 minuti prima del termine della cottura i gamberetti puliti. In una terrina sbattete i tuorli d''uovo con un pizzico di sale, aggiungete il succo di mezzo limone e unite questo composto alla salsa. Distribuitela sul pesce e servite.',2203);
INSERT INTO "ricette" VALUES (18419,'Pesce Spada Al Burro Bianco','Pesce','Pesce Spada',4,' -','4 Tranci Pesce Spada (tranci Da 150 G),
1 Scalogno,
80 G Burro,
Sale','Pelare e tritare lo scalogno non troppo finemente e metterlo in una padella con poco sale e 1 dito d''acqua. Portare a ebollizione a fuoco vivo e adagiarvi le trance di pesce. Abbassare la fiamma e cuocerle per circa 5 minuti per parte. Levarle dal fuoco e tenerle in caldo. A fuoco vivo ridurre il fondo di cottura poi unire il burro e farlo fondere. Versare la salsa sul pesce e servire.',1267);
INSERT INTO "ricette" VALUES (18420,'Pesce Spada Al Cartoccio','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
4 Cucchiai Capperi,
1 Limone,
Prezzemolo,
Olio D''oliva,
4 Cucchiai Aceto Di Vino,
Sale,
Pepe','Appoggiare le fette di pesce spada su un foglio di carta di alluminio unto di olio. Bagnarle con un cucchiaio di aceto, sale, pepe, spolverizzare con il prezzemolo e mettere una fetta di limone. Aggiungere i capperi, altro olio e chiudere accuratamente il cartoccio. Mettere in forno a 180 gradi per 15 minuti. Servire molto caldo.',1633);
INSERT INTO "ricette" VALUES (18421,'Pesce Spada Al Finocchio Selvatico','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
Farina,
2 Cucchiai Olio D''oliva,
1 Spicchio Aglio,
1 Pugno Pinoli,
1/2 Bicchiere Vino Bianco,
1 Ciuffo Finocchio Selvatico (o Cimette Di Finocchio),
Sale,
Pepe','Lavate e asciugate le fette di pesce spada, infarinatele e adagiatele in una padella capace dove avrete fatto rosolare lo spicchio d''aglio con l''olio. Bagnate tutto con il vino bianco, regolate di sale e pepe e lasciate cuocere per 5 minuti sul fuoco basso girando le fette di pesce. Aggiungete un bicchiere scarso di acqua, i pinoli, il finocchio selvatico sminuzzato e continuate la cottura per altri 15 minuti. Servite le fette di pesce spada ben coperte con il loro fondo di cottura.',1925);
INSERT INTO "ricette" VALUES (18422,'Pesce Spada Al Forno','Pesce','Pesce Spada',4,' -','4 Trance Pesce Spada,
1 Cipolla,
Aglio,
Abbondante Prezzemolo,
1 Bicchiere Vino Bianco,
1 Bicchiere Olio D''oliva,
Sale,
Pepe','Tritate cipolla, aglio e abbondante prezzemolo. Mettetene un po'' in una pirofila, sopra sistemate le trance di pesce, salate, pepate, ricoprite con il trito rimasto e condite con un bicchiere d''olio e uno di vino bianco. Cuocete in forno preriscaldato a 180 gradi per mezz''ora, bagnando spesso il pesce con il sugo. Vini di accompagnamento: Colli Orientali Del Friuli Tocai DOC, Pomino Bianco DOC, Don Pietro Bianco IGT Di Sicilia.',2400);
INSERT INTO "ricette" VALUES (18423,'Pesce Spada Al Forno (2)','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
6 Cucchiai Olio D''oliva,
Sale,
Burro,
Aglio,
Cipolla,
Prezzemolo,
Farina,
1 Bicchiere Vino Bianco Secco,
1 Limone (succo)','Rosolare nell''olio il pesce spada, salarle e porle in una pirofila. Appassire nel burro un trito di aglio, cipolla, prezzemolo, cospargere con un po'' di farina, diluita con il vino e il succo di limone, poi versare sul pesce e cuocere in forno a 200 gradi per 7 minuti.',4287);
INSERT INTO "ricette" VALUES (18424,'Pesce Spada Al Limone','Pesce','Pesce Spada',4,' -','600 G Pesce Spada (trance Di 150 G),
4 Limoni,
2 Cucchiai Olio D''oliva,
Origano,
Pepe,
Sale','Cuocete il pesce sulla graticola appena un ta. Preparate a parte il sughetto con i limoni, l''olio d''oliva, l''origano, il pepe e il sale. Mescolate gli ingredienti in un recipiente a bagno maria affinché tutto sia ben amalgamato. Servite il pesce bagnandolo con il sughetto.',1094);
INSERT INTO "ricette" VALUES (18425,'Pesce Spada Al Pepe Verde','Pesce','Pesce Spada',6,'Preparazione: 10 minuti. Cottura: 30 minuti. Calorie: 206.','1 Trancio Pesce Spada Da 1000 G,
2000 G Sale Grosso,
200 G Insalata Belga (indivia),
1 Scalogno,
1 Cucchiaio Pepe Verde,
1 Cucchiaino Maizena,
1 Cucchiaio Olio D''oliva','Ponete il trancio di spada in una teglia, su uno strato di sale grosso. Ricopritelo completamente con il sale e infornate a 250 gradi per mezz''ora. Affettate finemente lo scalogno e fatelo appassire in un tegame con l''olio e un po'' d''acqua. Aggiungete l''indivia tagliata a listerelle, versate mezzo bicchiere d''acqua, coperchiate e cuocete a fuoco basso per 15 minuti. Frullate il tutto e rimettete la salsa sul fuoco. Sciogliete l''amido di mais in poca acqua e unitelo alla salsa, mescolando con una frusta finché la salsa risulta morbida. Estraete la teglia del pesce dal forno, liberatelo dalla crosta di sale grosso, affettatelo in sei fette e servitelo irrorato dalla salsa all''indivia, alla quale avrete aggiunto il pepe verde pestato.',1517);
INSERT INTO "ricette" VALUES (18426,'Pesce Spada Al Pomodoro','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
600 G Pomodori Pelati,
1 Cucchiaio Capperi,
100 G Olive Verdi,
1 Cipolla,
Basilico,
Farina,
Sedano,
1 Spicchio Aglio,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe','Saltare nell''olio le fette di pesce infarinate e scolarle. Nello stesso olio appassire la cipolla, l''aglio e il sedano tritati, unire i capperi, i pomodori, e le olive snocciolate. Cuocere, coperto, a fuoco dolce per 10 minuti. Sistemare il pesce in una pirofila, cospargere con il sugo e con il basilico, coprire a filo di acqua, salare, pepare e portare a fine cottura in forno.',2148);
INSERT INTO "ricette" VALUES (18427,'Pesce Spada Al Pomodoro (2)','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
600 G Pomodori Maturi,
1 Cucchiaio Capperi,
100 G Olive Verdi,
1 Cipolla,
Basilico,
Farina,
1/2 Bicchiere Olio D''oliva,
Sedano,
Sale,
Pepe,
1 Spicchio Aglio','Privare i pomodori della buccia, dei semi e spezzettarli. Infarinare le fette di pesce e farle saltare in 1/2 bicchiere d''olio, scolarle e tenerle da parte. Nello stesso olio far appassire la cipolla con l''aglio e il sedano tritati, unire capperi lavati, olive snocciolate e pomodori. Coprire e cuocere per 10 minuti. Sistemare il pesce in 1 pirofila, cospargerlo con il sugo, coprire a filo con acqua, basilico, salare, pepare e terminare la cottura in forno.',2148);
INSERT INTO "ricette" VALUES (18428,'Pesce Spada Al Salmoriglio','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada (fette Di 200 G),
Burro,
Alcune Foglie Prezzemolo,
Succo Di Limone,
2 Bicchieri Olio D''oliva,
Pepe In Grani,
Sale,
Aglio,
Rosmarino','Preparare il salmoriglio scaldando a bagnomaria due bicchieri di olio, con il succo di limone, aggiungendo aglio tagliato a fettine, rosmarino, qualche fogliolina tagliuzzata di prezzemolo, sale e pepe macinato al momento. Cuocere il pesce spada alla griglia con burro e cospargerlo abbondantemente di salsa.',4383);
INSERT INTO "ricette" VALUES (18429,'Pesce Spada Al Salmoriglio (2)','Pesce','Pesce Spada',4,'Luogo: Calabria.','4 Tranci Pesce Spada,
1/2 Limone (succo),
Olio D''oliva,
Origano,
Prezzemolo,
Sale,
Aglio In Polvere','Arroventare una padella antiaderente e cuocere le fette di pesce spada 5 minuti per lato, senza aggiungere olio. Intanto emulsionare l''olio con il succo di limone, il sale, l''aglio, il prezzemolo e l''origano. Porre le fette di pesce su un piatto da portata e irrorare con la salsina preparata (salmoriglio). Servire subito.',1626);
INSERT INTO "ricette" VALUES (18430,'Pesce Spada Al Timo','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
2 Spicchi Aglio,
Farina,
Olio D''oliva,
Timo,
Sale','Lavare le fette di pesce spada, infarinarle e adagiarle in un grande tegame. Irrorarle d''olio, cospargerle di timo e di aglio; salare. Far cuocere, a recipiente coperto, per circa 30 minuti e servire.',1925);
INSERT INTO "ricette" VALUES (18431,'Pesce Spada Al Verde','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
1 Spicchio Aglio,
Prezzemolo,
Vino Bianco,
Farina,
2 Cucchiai Aceto Di Vino,
Olio D''oliva,
Sale,
Pepe','Preparare un trito con aglio e prezzemolo. Lavare e asciugare le fette di pesce spada. Infarinarle e gettarle in una padella con 1/2 bicchiere di olio caldo e cuocerle 5 minuti per lato. Bagnarle con 1/2 bicchiere di vino e proseguire la cottura a tegame coperto per 15 minuti. A parte far appassire il trito in 4 cucchiai di olio, 2 di aceto e 2 di vino. Poco prima di levare il pesce dal fuoco irrorarlo con il trito e il suo sugo e servirlo ben caldo.',1997);
INSERT INTO "ricette" VALUES (18432,'Pesce Spada All''aceto','Pesce','Pesce Spada',4,' -','4 Trance Pesce Spada,
1 Carota,
2 Cipolline,
1 Foglia Alloro,
1/2 Bicchiere Aceto Di Vino Bianco,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe Nero','Pulire, lavare e tagliare a rondelle sottili la carota e le cipolline. In una padella far scaldare l''olio e mettere le trance di pesce, le carote, le cipolle e l''alloro. Far cuocere il pesce per 4 minuti per parte girandolo una sola volta, poi toglierlo dalla padella scolandone l''olio e passarlo su un piatto. Continuare la cottura delle cipolle e carote per 15 minuti e poi versarvi l''aceto facendone evaporare la metà. Unire di nuovo il pesce aggiustando di sale e pepe.',1593);
INSERT INTO "ricette" VALUES (18433,'Pesce Spada All''arancia','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
2 Limoni,
2 Arance,
4 Cucchiai Olio D''oliva,
2 Spicchi Aglio,
Sale,
Pepe In Grani','Tagliare a fettine arancia e limone e metterle sul fondo di una pirofila unta Sopra sistemare le fette di pesce e cospargere con pepe, aglio tritato e un poco di sale. Irrorare il pesce con succo di arancia e limone, un filo d''olio e infornare per 30 minuti a temperatura media.',2510);
INSERT INTO "ricette" VALUES (18434,'Pesce Spada All''uccelletto','Pesce','Pesce Spada',2,' -','Aglio,
Alloro,
2 Porzioni Pesce Spada,
1 Cucchiaio Vino Bianco,
2 Cucchiai Prezzemolo Fresco','Porre in poca acqua un trito di aglio e alloro, adagiare le porzioni di pesce spada e far cuocere. Poco prima di ultimare la cottura, spruzzare con il vino bianco. Servire dopo aver spolverizzato con il prezzemolo fresco.',504);
INSERT INTO "ricette" VALUES (18435,'Pesce Spada Alla Fiorentina','Pesce','Pesce Spada',4,'Luogo: Toscana. Luogo: Firenze.','800 G Pesce Spada,
200 G Spinaci Lessi,
300 G Salsa Mornay,
100 G Burro,
Cipolla Tritata,
Vino Bianco,
Sale,
Pepe,
2 Tuorli D''uovo,
50 G Formaggio Parmigiano Grattugiato,
300 G Besciamella','Tagliare il pesce spada in quattro scaloppe da 200 g cadauno. Rosolare in un tegame una cipolla tritata con 40 g di burro e mettervi dentro il pesce spada insaporendolo con sale e pepe. Mettere il pesce spada a cuocere, nel tegame coperto, nel forno per dieci minuti, con del vino bianco sopra. Lessare gli spinaci e saltarli al burro, quindi disporli in una pirofila in modo da coprirne tutto il fondo . Preparare una salsa Mornay con 300 g di besciamella, due tuorli d''uovo e parmigiano. Togliere il pesce spada cotto dal forno e disporlo sugli spinaci. Aggiungere il vino rimasto dalla cottura del pesce, facendo attenzione che non sia troppo liquido, mescolare e mettere il tutto sul pesce. Infornare a forno caldo per pochi minuti, finché prenda un colore oro. Servire dividendo in porzioni.',3030);
INSERT INTO "ricette" VALUES (18436,'Pesce Spada Alla Ghiotta Con Il Bimby','Pesce','Pesce Spada',4,' -','800 G Tranci Di Pesce Spada,
1 Cipolla Media,
1 Gambo Sedano Con Le Foglie,
5 Cl Acqua,
90 G Olio D''oliva,
15 Olive Verdi Snocciolate,
2 Cucchiai Capperi,
700 G Passata Di Pomodoro,
Sale,
Pepe','Inserisci nel boccale la cipolla e il sedano e tritali per 15 secondi a velocità 4. Unisci l''acqua e cuoci per 3 minuti a temperatura 100 velocità 1. Unisci 60 G di olio, i capperi e le olive: 3 minuti a temperatura 100 velocità 1. Alterna nel Varoma e nel suo vassoio le fette di pesce spada, qualche cucchiaio di pomodoro, parte del sughetto già preparato e irrora col rimanente olio. Inserisci nel boccale la passata di pomodoro rimasta, poco sale e pepe e cuoci per 25 minuti a temperatura Varoma velocità 3 e dopo 5 minuti posiziona il Varoma. A metà cottura rigira le fette di pesce. Terminata la cottura disponi il pesce in un piatto da portata con un poco di sugo e usa il sugo rimasto per condire spaghetti o linguine.',1951);
INSERT INTO "ricette" VALUES (18437,'Pesce Spada Alla Golosa','Pesce','Pesce Spada',4,' -','600 G Pesce Spada (tranci Da 150 G Ognuno),
400 G Pomodori Maturi,
1 Cucchiaio Olive Verdi Snocciolate,
30 G Uva Passa,
1 Cucchiaio Capperi,
30 G Pinoli,
1 Gambo Sedano,
1 Cipolla,
1 Spicchio Aglio,
6 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Farina,
Sale,
Pepe','Mettete a bagno l''uvetta in poca acqua tiepida. Infarinate leggermente le fette di pesce e rosolatele in una teglia con 4 cucchiaiate d''olio. Sgocciolatele e disponetele in una pirofila, salatele e pepatele. Fate appassire in 2 cucchiai di olio la cipolla tritata con uno spicchio d''aglio. Unite i pinoli, il gambo di sedano tritato, l''uvetta strizzata, i capperi, le olive e i pomodori tagliati a filetti e privati dei semi. Irrorate le fette di pesce con la salsa e ponete a cuocere in forno caldo (200 gradi) per circa 15 minuti. Appena sfornato, spolverizzate con le foglie del sedano spezzettate, quindi servite. Ottimo anche sostituendo al sedano del basilico; in questo caso non soffriggetelo ma cospargetene la pirofila prima della cottura e poi ancora prima di portarlo in tavola.',1677);
INSERT INTO "ricette" VALUES (18438,'Pesce Spada Alla Griglia','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada (150 G Ognuna),
2 Spicchi Aglio,
4 Filetti D''acciughe,
1 Limone,
1 Bicchiere Vino Bianco Secco,
1 Cucchiaio Prezzemolo Tritato,
1 Manciatina Origano,
1 Rametto Rosmarino,
1 Cucchiaio Pangrattato,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe','Mescolate in una terrina un bicchiere di vino bianco secco, un cucchiaio di prezzemolo tritato, una manciatina di origano, il sale necessario e una macinata abbondante di pepe. Lavate le fette di pesce spada sotto l''acqua corrente, asciugatele tamponandole con un canovaccio e cospargetele con sale e pepe, quindi immergetele nella marinata al vino bianco e lasciatele insaporire per almeno due ore. Trascorso questo tempo, scolate le fette di pesce spada e incidetene la superficie servendovi di un coltellino. Steccate ogni fetta con fettine d''aglio e pezzetti di rosmarino, quindi fatele cuocere sulla griglia ben calda per circa un quarto d''ora. Ricordate di girare spesso le fette di pesce spada e di spennellarle ogni tanto con la marinata. A metà cottura cospargetele da ambo le parti con un velo di pangrattato. Nel frattempo mescolate in una casseruolina le acciughe tritate finemente, mezzo bicchiere d''olio d''oliva e la scorza grattugiata di un limone. Fate scaldare questa salsetta per qualche minuto a calore moderato, quindi servitela col pesce.',1659);
INSERT INTO "ricette" VALUES (18439,'Pesce Spada Alla Griglia (2)','Pesce','Pesce Spada',2,' -','400 G Pesce Spada (tranci Da 200 G Ognuno),
4 Cucchiai Olio D''oliva Extra-vergine,
1 Cucchiaio Gambi Di Prezzemolo Tritati,
2 Cucchiai Succo Di Limone,
Sale','Grigliate i tranci di pesce spada su una griglia calda, a calore medio. Per la cottura calcolate approssimativamente dai 6 ai 10 minuti (naturalmente, per poter cuocere bene, i tranci vanno girati una volta a metà cottura). Nel frattempo preparate la salsina: versate in una ciotola l''olio, sbattetelo con una frusta unendo il succo di limone, i gambi del prezzemolo tritati e un pizzico di sale in modo da avere una salsina omogenea; con essa condite il pesce appena tolto dalla griglia.',1165);
INSERT INTO "ricette" VALUES (18440,'Pesce Spada Alla Palermitana','Pesce','Pesce Spada',4,'Luogo: Sicilia. Luogo: Palermo.','20 Cl Olio D''oliva,
20 Cl Vino Bianco,
4 Fette Pesce Spada (200 G Ognuna),
2 Cipolle Affettate,
2 Foglie Alloro,
Sale,
Pepe In Grani,
Origano,
Alcune Fette Limone','In una terrina mescolate l''olio con il vino, sbattendoli energicamente con una forchetta. Nettate accuratamente le fette di pesce spada, quindi lavatele velocemente sotto l''acqua corrente, asciugatele servendovi di un foglio assorbente e mettetele in una casseruola; bagnatele con l''emulsione preparata, mettetevi sopra le cipolle, le foglie di alloro sminuzzate e condite quindi con sale e pepe in grani leggermente pestato. Coprite la casseruola con un foglio di pellicola trasparente e lasciate marinare per 2-3 ore. Eliminate l''alloro e le cipolle, passate le fette di pesce spada da entrambi i lati nell''origano e fatele quindi cuocere 5 minuti per parte in padella oppure sopra una griglia, girandole più volte affinché cuociano senza bruciacchiarsi. Servite subito, accompagnando a piacere il pesce con spicchi di limone.',2896);
INSERT INTO "ricette" VALUES (18441,'Pesce Spada Alla Scogliera','Pesce','Pesce Spada',4,' -','800 G Pesce Spada,
600 G Cozze,
200 G Vongole,
50 G Gamberi,
100 G Pomodoro,
100 G Cipolla Tritata,
Poco Prezzemolo Tritato,
Vino Bianco,
100 G Burro,
Sale,
Pepe,
Aglio','Tagliare quattro fette di pesce spada da 200 g cadauno e passarle nella farina. Quindi farlo dorare in padella con 100 g di burro, dopo di che metterlo in una pirofila, che sarà tenuta in caldo. Preparare la salsa in padella facendo rosolare con il burro un po'' di cipolla ed una punta di aglio, aggiungere quindi i gamberi le cozze e le vongole, facendo cuocere pochi minuti; quindi sfumare con vino bianco attendendo il tempo necessario per farlo evaporare; quindi aggiungere il pomodoro, il prezzemolo tritato, il sale ed il pepe quanto basta. Fare cuocere per circa 10 minuti e versare questa salsa sul pesce, che così e pronto per essere servito.',2253);
INSERT INTO "ricette" VALUES (18442,'Pesce Spada Alle Erbe','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
2 Spicchi Aglio,
1 Bicchiere Vino Bianco Secco,
1 Limone,
2 Carote,
3 Scalogni,
1 Cuore Sedano,
1 Trito Di Salvia, Alloro E Rosmarino,
Poco Olio D''oliva,
Sale,
Pepe','Insaporire il pesce spada con il trito aromatico, distribuirvi l''aglio a filetti e premere per farlo aderire, salare e pepare. Tagliare a dadini piccoli carote, scalogni e sedano e scottarli nel vino per 3 minuti. Scaldare poco olio, rosolarvi il pesce, unire il vino con le verdure e cuocere per 5 minuti, poco prima di togliere dal fuoco unire 3-4 spicchi di limone. Servire subito.',1518);
INSERT INTO "ricette" VALUES (18443,'Pesce Spada Alle Erbe (2)','Pesce','Pesce Spada',4,' -','800 G Tranci Di Pesce Spada,
2 Cucchiai Olio D''oliva Extra-vergine,
25 Cl Vino Bianco,
1 Manciata Foglioline Di Maggiorana,
6 Foglie Salvia,
5 Foglie Basilico,
Prezzemolo,
Semi Di Coriandolo,
1 Scalogno,
1 Spicchio Aglio,
Sale Marino Integrale','Imbiondire nell''olio aglio e scalogno con le erbe sminuzzate e il coriandolo; unire il pesce e far cuocere per 3 minuti per lato a fuoco vivace. Sfumare col vino, salare e cuocere per altri 5-6 minuti girandolo. Sistemare il pesce nei piatti caldi; addensare il fondo di cottura con un po'' di farina, versarlo sul pesce e servire.',1489);
INSERT INTO "ricette" VALUES (18444,'Pesce Spada Alle Olive','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada,
2 Cipolle,
200 G Pomodori,
1 Peperoncino,
10 Olive Nere Snocciolate,
Prezzemolo,
Olio D''oliva,
Sale','Friggere il pesce in olio bollente, un minuto per lato, poi tenerlo da parte. Nel fondo di cottura soffriggere a fuoco basso le cipolle tritate, unire i pomodori a filetti e un po'' di sale. Soffriggere per 10 minuti, quindi rimettere nel tegame il pesce e le olive. Insaporire con peperoncino e tenere ancora un minuto sul fuoco. Prima di servire unire il prezzemolo tritato.',1886);
INSERT INTO "ricette" VALUES (18445,'Pesce Spada Alle Olive (2)','Pesce','Pesce Spada',4,' -','1 Trancio Pesce Spada (tranci Da 1000 G),
150 G Calamari Puliti,
2 Pomodori,
8 Olive Nere,
2 Rametti Rosmarino,
Olio D''oliva,
Sale,
Pepe','Disponete sulla placca del forno un foglio di carta da forno, sopra sistemateci il trancio di pesce, i calamaretti, due rametti di rosmarino, le olive, i pomodori a spicchi, sale, pepe; condite il tutto con un po'' d''olio. Chiudete il cartoccio e cuocete in forno a 200 gradi per 35 minuti.',2034);
INSERT INTO "ricette" VALUES (18446,'Pesce Spada Allo Spumante','Pesce','Pesce Spada',4,' -','4 Fette Pesce Spada (800 G),
1/2 Bottiglia Vino Spumante Secco,
Farina,
4 Cucchiai Olio D''oliva,
Pepe,
Sale','Mettete in un tegame capiente 4 cucchiai d''olio d''oliva ed aggiungere le 4 fette di pesce spada infarinate. Fatele rosolare da un lato e quindi dall''altro, aggiustando di sale e di pepe. Versare sopra la mezza bottiglia di spumante e fate continuare la cottura finché il vino non si consumi e in fondo al tegame si formi una salsa piuttosto densa. Togliete le fette di pesce spada dal tegame e disponetele su un piatto da portata, copritele con la salsa preparata e adornate con fettine di limone e insalata.',2959);
INSERT INTO "ricette" VALUES (18447,'Pesce Spada Avvolto Con Melanzane E Parmigiano','Pesce','Pesce Spada',4,' -','250 G Pesce Spada,
1/2 Cipolla,
1/2 Cucchiaio Capperi,
1/2 Melanzana,
40 G Formaggio Grana,
Aceto Balsamico,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Tagliare il pesce a fettine e batterle tra 2 fogli di carta da forno. Grigliare le melanzane a fette sottili e tonde. Avvolgere il pesce con dentro una fetta di melanzana, 2 fettine di grana e 5 capperi. Cuocere gli involtini sulla griglia e infornarli per 5 minuti. Servire con le altre melanzane e con un salsa di olio, aceto e capperi.',1160);
INSERT INTO "ricette" VALUES (18448,'Pesce Spada Con Insalata Di Finocchi E Patate','Pesce','Pesce Spada',4,' -','200 G Tranci Di Pesce Spada,
1 Cucchiaio Olio D''oliva Extra-vergine,
1/2 Finocchio,
2 Patate Novelle,
Succo Di Limone,
1 Arancia,
Sale,
Pepe','Tagliare le patate a fettine sottili, cuocerle in padella con olio fino alla doratura e salarle. Tagliare il pesce, rosolarlo, salarlo, peparlo e disporlo su un piatto con al centro il finocchio tagliato fine circondato dalle patate e dall''arancia pelata. Condire con olio e succo di limone.',1040);
INSERT INTO "ricette" VALUES (18449,'Pesce Spada Farcito','Pesce','Pesce Spada',4,' -','4 Fette Spesse Pesce Spada,
4 Spicchi Aglio,
Rosmarino,
1 Limone,
Olio D''oliva,
Sale,
Pepe','Lavare e asciugare i tranci di pesce. Porli su un vassoio e bagnarli con il succo di limone, olio, salarli e peparli. Lasciar insaporire il pesce per almeno 1 ora poi incidere con un coltellino le fette e introdurre nei tagli aglio a fettine e qualche ago di rosmarino. Disporre le fette di pesce spada in una pirofila unta e cuocere in forno caldo a 180 gradi per 15-20 minuti.',1626);
INSERT INTO "ricette" VALUES (18450,'Pesce Spada Gratinato','Pesce','Pesce Spada',4,' -','4 Tranci Pesce Spada (tranci Alti 1 Cm),
2 Pomodori Maturi Sodi,
4 Cucchiai Formaggio Pecorino Piccante,
2 Cucchiai Capperi Dissalati,
1 Limone (succo),
2 Fette Pancarré Leggermente Raffermo,
Pochissimo Olio D''oliva Extra-vergine,
Sale,
Peperoncino Secco In Polvere','Accendete il forno a 180 gradi. Private il pancarré della crosta e grattugiatelo. Ungete leggermente una teglia da forno e cospargetela con metà pangrattato. Salate e insaporite con il peperoncino le fette di pesce spada, posatele nella teglia, bagnate con il succo di limone e coprite con un foglio di alluminio o di carta speciale da forno. Cuocete per 15 minuti. Intanto grattugiate anche il pecorino. Trascorso il tempo indicato, togliete il pesce dal forno e cospargetelo con il pangrattato e il pecorino. Accendete il grill e lasciatevi il pesce finché il formaggio si è leggermente sciolto e il pangrattato un po'' dorato. Servite con qualche cappero e i pomodori a fette.',1926);
INSERT INTO "ricette" VALUES (18451,'Pesce Spada Gratinato Alla Calabrese','Pesce','Pesce Spada',4,'Luogo: Calabria.','800 G Pesce Spada,
100 G Burro,
200 G Mollica Di Pane,
50 G Prezzemolo,
50 G Formaggio Parmigiano Grattugiato,
Origano,
Capperi Tritati,
Olive Verdi Tritate,
Olio D''oliva,
Sale,
Pepe','Tagliare il pesce spada in 8 fette sottili, poi disporlo in una pirofila imburrata e spolverarlo con un po'' di sale e pepe. Fare un impasto con la mollica, il prezzemolo, il parmigiano, l''origano, i capperi, le olive tritate sale, pepe ed un po'' di olio (quanto basta). Ricoprire il pesce con questo impasto, mettendo sopra qualche nocciola di burro. Infornare e cuocere per circa 10 minuti, finché prende colore. dopodichè è pronto per essere servito.',3233);
INSERT INTO "ricette" VALUES (18452,'Pesce Spada Impanato','Pesce','Pesce Spada',4,' -','8 Fette Pesce Spada,
3 Uova,
Pangrattato,
Farina,
Olio D''oliva,
Sale,
Per Decorare:,
Prezzemolo,
Limone','Salare il pesce e lasciarle insaporire per 10 minuti. Sbattere le uova, tuffarvi il pesce, poi passarlo nella farina, quindi nel pangrattato. Premere bene per far aderire la panatura. Dorarle nell''olio caldo, girandole con una paletta. Metterle a perdere unto su carta da cucina. Sistemarle su un piatto da portata e decorare a piacere con prezzemolo e limone.',3327);
INSERT INTO "ricette" VALUES (18453,'Pesce Spada Impanato Aromatizzato','Pesce','Pesce Spada',4,' -','400 G Pesce Spada,
1 Uovo,
50 G Farina Bianca,
50 G Pangrattato,
10 G Semi Di Finocchio,
Olio Di Semi,
Maionese','Tagliare il pesce a bastoncini, infarinarli, passarli nell''uovo e nel pangrattato profumato con semi di finocchio, quindi friggerli. Preparare la maionese e con questa guarnire il pesce.',1968);
INSERT INTO "ricette" VALUES (18454,'Pesce Spada In Carpaccio','Pesce','Carpaccio Di Pesce Spada',4,' -','400 G Carpaccio Di Pesce Spada,
150 G Pomodori Pachino Ben Maturi,
Basilico,
1/2 Limone (succo),
Olio D''oliva Extra-vergine,
1 Spruzzata Pepe Bianco,
1 Pizzico Sale','Preparate su un piatto da portata le fette di pescespada condite col limone e con una spruzzata di pepe bianco e mettetele in frigo. Tagliate i pomodori e scottateli in olio d''oliva col basilico tritato e un pizzico di sale. Fate cuocere per qualche minuto, poi passateli al passaverdura per ottenere una salsa omogenea e priva di bucce, che farete ritirare a fuoco medio se troppo liquida. Servite il pesce accompagnato dalla salsa ben raffreddata.',1247);
INSERT INTO "ricette" VALUES (18455,'Pesce Spada In Cartoccio','Pesce','Pesce Spada',4,' -','4 Trance Pesce Spada,
150 G Gamberetti,
250 G Cozze,
250 G Vongole,
2 Pomodori,
1 Peperone Giallo,
1 Peperoncino,
1 Ciuffo Prezzemolo,
1 Spicchio Aglio,
Alcune Foglie Basilico,
Olio D''oliva,
Sale,
Pepe','Lavate le cozze e le vongole. Fatele aprire a fuoco vivace in un tegame con tre cucchiai d''olio e uno spicchio d''aglio. Sgusciate i gamberetti, lavateli, asciugateli e insaporiteli in un tegame con due cucchiai d''olio per pochi minuti. Nello stesso recipiente unitevi le cozze e le vongole non sgusciate, i pomodori tagliati grossolanamente, il peperone tagliato a falde, alcune foglie di basilico sminuzzate, il peperoncino e il liquido delle cozze filtrato. Cuocete per 5 minuti. Lavate le trance di pesce, asciugatele e cuocetele in un tegame con un po'' d''olio per 5 minuti da entrambi i lati. Disponetele sulla carta d''alluminio, salate, pepate. Sopra distribuite le cozze, le vongole e i gamberetti. Cospargete con prezzemolo fresco tritato e irrorate con un filo d''olio. Chiudete bene il cartoccio e cuocete in forno preriscaldato a 200 gradi per circa 10 minuti. Adagiate il cartoccio sul piatto da portata, dischiudetelo appena e portatelo subito a tavola. Vini di accompagnamento: Riviera Ligure Di Ponente Pigato DOC, Verdicchio Dei Castelli Di Jesi Classico DOC, Regaleali Bianco IGT Di Sicilia.',2126);
INSERT INTO "ricette" VALUES (18456,'Pesce Spada In Salmoriglio','Pesce','Pesce Spada',4,' -','2 Limoni,
250 G Olio D''oliva Extra-vergine,
1 Cucchiaio Prezzemolo Tritato,
1 Spicchio Aglio,
1 Cucchiaino Origano','In una ciotola mettere l''olio e batterlo delicatamente con la frusta. Senza smettere di sbattere aggiungere 1/2 bicchiere d''acqua calda, succo di 2 limoni, prezzemolo, origano e aglio schiacciato. Continuare ad amalgamare il composto finché la salsa non diventi omogenea e di consistenza vellutata. Al momento di servirla scaldarla a bagnomaria e versarla su carne o pesce.',2295);
INSERT INTO "ricette" VALUES (18457,'Pesce Spada In Salsa','Pesce','Pesce Spada',4,' -','2 Fette Pesce Spada,
1/2 Bicchiere Panna,
2 Cucchiai Farina,
4 Filetti D''acciughe,
2 Cucchiai Sherry,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Tagliate a metà le fette di pesce. Mescolate la farina con il sale e il pepe e infarinate il pesce. Ungete di olio 4 fogli di alluminio, suddividetevi i filetti d''acciughe a pezzetti e le fette di pesce. Mescolate la panna con lo sherry e incorporate 3 gocce di tabasco: bagnate con questa salsa il pesce e chiudete i cartocci sulla placca del forno e cuoceteli a 180 gradi per 30 minuti. Aprite i cartocci, cospargete il pesce di prezzemolo tritato e servite.',1410);
INSERT INTO "ricette" VALUES (18458,'Pesce Spada In Salsa Piccante','Pesce','Pesce Spada',6,' -','6 Fette Pesce Spada,
70 G Olive Nere,
5 Filetti D''acciughe Sott''olio,
4 Pomodori,
1 Manciata Capperi,
Prezzemolo Tritato,
1 Bicchiere Vino Bianco Secco,
Poco Olio D''oliva,
Sale,
Pepe','Sbucciare i pomodori e lavarli; snocciolare le olive e tritarle. Mettere in un tegame i pomodori, le acciughe e i capperi a pezzetti. Far soffriggere in poco olio poi versare un po'' d''acqua e far cuocere per 15 minuti. Poi spellare il pesce e metterlo nel sugo. Aggiungere il vino e lasciar cuocere per altri 15 minuti. Unire il prezzemolo, salare, pepare; far addensare la salsa e servire.',2180);
INSERT INTO "ricette" VALUES (18459,'Pesce Spada In Umido','Pesce','Pesce Spada',4,' -','4 Trance Pesce Spada,
300 G Polpa Di Pomodoro,
Alloro,
1 Spicchio Aglio,
Cerfoglio,
Basilico,
60 G Olive Nere,
15 G Capperi,
Sedano,
1 Cipolla,
1 Carota,
40 G Formaggio Parmigiano,
Vino Bianco Secco,
Olio D''oliva,
1 Pizzico Sale,
1 Pizzico Pepe','Disponete le trance di pesce in una teglia con una fogliolina d''alloro e uno spicchio d''aglio intero, cospargete di cerfoglio e basilico freschi tritati, condite con due giri d''olio versato a filo, spolverizzate con un pizzico di sale e di pepe. Ponete sul fornello a fuoco medio e lasciate insaporire per mezz''ora, girando il pesce ogni tanto. Quindi passate in forno preriscaldato a 180 gradi per un quarto d''ora scarso, spruzzando spesso le trance con un po'' di vino bianco. Scaldate in un tegame due cucchiai d''olio e rosolatevi la cipolla, il sedano e la carota tritati. Aggiungete la polpa di pomodoro tagliata a pezzetti, i capperi, le olive snocciolate e cuocete per circa 10 minuti aggiungendo, se necessario, un po'' d''acqua perché la salsa deve essere un po'' abbondante. Versatela sul pesce, cospargete di parmigiano a scaglie e ponete di nuovo in forno ben caldo per circa un quarto d''ora. Lasciate riposare e insaporire alcuni minuti prima di servire. Vini di accompagnamento: Trentino Pinot Grigio DOC, Montecarlo Bianco DOC, Etna Bianco DOC.',2146);
INSERT INTO "ricette" VALUES (18460,'Pesce Spada Marinato','Pesce','Pesce Spada',4,' -','400 G Pesce Spada A Fette Sottili,
4 Funghi Champignon,
3 Cucchiai Olio D''oliva,
5 Cucchiai Succo Di Limone,
Sale,
Pepe','Emulsionare 3 cucchiai di olio d''oliva con 4 cucchiai di succo di limone e versare sul pesce spada. Salare, pepare e lasciare marinare per 3 ore. Affettare i funghi e spruzzarli di limone. Coprire le fette di pesce spada con i funghi e servire.',1538);
INSERT INTO "ricette" VALUES (18461,'Pesce Spada Marinato (2)','Pesce','Pesce Spada',4,' -','300 G Pesce Spada,
100 G Insalata Cicoria,
100 G Insalata Rucola,
1 Rametto Cerfoglio,
3 Limoni,
Olio D''oliva,
Sale,
Pepe','Fatevi tagliare il pesce spada a fettine molto sottili, sistematele su un piatto, conditele con un po'' d''olio, bagnatele con il succo di due limoni, salate, pepate, coprite e lasciate in frigorifero per circa 2 ore. Lavate e asciugate le insalate, spezzettatele e raccoglietele in una ciotola. Unite il cerfoglio e mescolate. Disponete le fettine di pesce a corona sul piatto da portata e al centro mettete le foglie delle due insalate. Condite con la marinata e guarnite con alcune fettine di limone. Vini di accompagnamento: Friuli Aquileia Riesling Renano DOC, Torgiano Pinot Grigio DOC, Bianco D''Alcamo DOC.',1114);
INSERT INTO "ricette" VALUES (18462,'Pesce Spada Marinato Con Carciofi','Pesce','Pesce Spada',4,' -','4 Carciofi,
400 G Pesce Spada A Fettine Sottilissime,
Sale,
Pepe Verde,
Semi Di Coriandolo,
Olio D''oliva,
Succo Di Limone','Mondare i carciofi, privarli delle foglie dure, tagliarli a fettine e metterli in acqua acidulata col limone. Far marinare le fettine di pesce spada con grani di pepe verde, semi di coriandolo, succo di limone. Predisporre un letto di fettine di carciofi; adagiarvi sopra le fettine di pesce spada, salare e condire con olio d''oliva extra-vergine.',1243);
INSERT INTO "ricette" VALUES (18463,'Pesce Spada Marinato Con Scaglie Di Formaggio Parmigiano, Menta E Pere','Pesce','Pesce Spada',4,' -','100 G Pesce Spada,
1 Limone,
1 Bicchiere Aceto Di Vino,
1 Bicchiere Vino Bianco,
Sale,
Formaggio Parmigiano,
Zucchero,
5 Bacche Di Ginepro,
1 Pera,
Olio D''oliva Extra-vergine','Fare una marinatura con vino, limone, ginepro, zucchero e sale. Adagiare sopra il pesce tagliato sottile e lasciare marinare per 20 minuti. Tagliare la pera a metà ed inciderla, aprirla a ventaglio sul piatto sistemando il carpaccio di pesce spada a fianco. Unire le scaglie di parmigiano e condire con olio, menta e succo di limone.',1440);
INSERT INTO "ricette" VALUES (18464,'Pesce Spada Piccante','Pesce','Pesce Spada',4,' -','600 G Pesce Spada,
4 Cucchiai Olio D''oliva,
1 Cucchiaio Pinoli,
1 Cucchiaio Uvetta Sultanina Ammorbidita Nel Limone,
Sale,
Peperoncino','Tagliare a listarelle il pesce, farlo saltare in padella con l''olio, unire i pinoli e l''uvetta, sale e peperoncino. Cuocere per 10 minuti e servire.',2264);
INSERT INTO "ricette" VALUES (18465,'Pesce Spada Saporito','Pesce','Pesce Spada',4,' -','4 Tranci Pesce Spada,
Cipolla,
Aglio,
Prezzemolo,
1 Bicchiere Vino Bianco,
1 Limone (succo),
Farina,
Sale,
6 Cucchiai Olio D''oliva,
Burro','Rosolare i tranci di pesce spada in 6 cucchiai di olio, salarli e metterli in una pirofila. Appassire nel burro un trito di cipolla, aglio e prezzemolo. Diluire poca farina nel vino e nel succo di limone e unire il tutto al trito. Mescolare bene e versare questa salsina sul pesce. Infornare a 200 gradi per non più di 10 minuti.',4287);
INSERT INTO "ricette" VALUES (18466,'Pesce Spada Saporito (2)','Pesce','Pesce Spada',4,' -','400 G Pesce Spada,
1 Cipolla,
150 G Polpa Di Pomodoro A Cubetti,
10 Olive Snocciolate,
1 Cucchiaio Prezzemolo Tritato,
2 Cucchiai Olio D''oliva Extra-vergine,
Sale','Pulite il pesce e tagliatelo a cubetti. Tritate la cipolla e fatela appassire a fuoco basso con 2 cucchiai di olio, quindi unite il pomodoro e, quando la salsa è ben ristretta, il pesce. Mescolate e cuocete a fuoco moderato per circa 10 minuti, controllando che il fondo di cottura sia di nuovo ben ristretto. Salate, aggiungete il prezzemolo e le olive tritate, fate insaporire qualche minuto e servite.',925);
INSERT INTO "ricette" VALUES (18467,'Pesce Spada Saporito (3)','Pesce','Pesce Spada',4,' -','4 Tranci Pesce Spada,
1 Spicchio Aglio,
Prezzemolo,
1/2 Bicchiere Olio D''oliva,
1/2 Bicchiere Vino Bianco Secco,
1 Cucchiaino Capperi,
Sale','Togliere la pelle al pesce e salarlo. Preparare un trito con aglio, prezzemolo e capperi; metterne una parte in una pirofila con metà dell''olio indicato e adagiarvi le fette di pesce. Ricoprirle con il resto del trito, l''olio e il vino bianco. Infornare a calore piuttosto elevato per circa 30 minuti.',1631);
INSERT INTO "ricette" VALUES (18468,'Pesce Spada Ubriaco','Pesce','Pesce Spada',4,' -','4 Tranci Pesce Spada,
500 Cl Vino Spumante Secco,
Farina,
Olio D''oliva Extra-vergine,
Pepe,
Sale','In una padella antiaderente, lasciate riscaldare l''olio d''oliva extra-vergine e quando sarà ben caldo, aggiungete i tranci di pesce che avrete precedentemente infarinato da entrambi i lati. Lasciateli dorare per pochi minuti a fiamma bassa, girandoli con una forchetta, salateli e pepateli. Dopodichè, irrorateli con lo spumante secco a fiamma alta, fino a quando l''alcool non sarà evaporato. Togliete le fette dalla padella e disponetele su un piatto piano da portata. Cospargete il tutto con il sughetto denso e servite subito.',5144);
INSERT INTO "ricette" VALUES (18469,'Pescestocco Alla Messinese','Pesce','Stoccafisso',4,'Luogo: Sicilia. Luogo: Messina.','8 Pezzi Stoccafisso Norvegese Già Ammollato,
1500 G Patate Novelle Medie,
200 G Passato Di Pomodoro,
300 G Cipolle,
100 G Gambi Di Sedano,
50 G Capperi,
200 G Olive Verdi In Salamoia,
100 Cl Olio D''oliva,
Sale,
Pepe Nero','E'' la ricetta regina della cucina messinese. E'' una pietanza gustosa e robusta e va servita come primo piatto accompagnata da un vigoroso e soprattutto genuino vino rosso preferibilmente preparato sotto il personale controllo dell''ospite. Una cena a base di pescestocco alla messinese non può concludersi senza un assaggio di profumati ''Spaghetti alle restatine'' che vanno conditi con il sugo residuo del pescestocco. In una terrina ricolma di acqua versate i capperi che avrete precedentemente lavato in abbondante acqua per togliere l''eccesso del sale di conservazione. Lavate e tagliate in piccoli cubetti i gambi di sedano che avrete pulito da tutti i filamenti e della pellicola esterna. Triturate la cipolla in pezzetti non molto piccoli, snocciolate le olive verdi in 2 semigusci. Pelate le patate, tagliatele in spicchi di medie dimensioni e ponetele in una terrina ricolma d''acqua per evitare l''annerimento dovuto al contatto prolungato con l''aria. In una casseruola preparate un battuto con la cipolla tritata, i cubetti di sedano ed i capperi: aggiungete mezzo bicchiere d''acqua, dell''olio d''oliva e cuocete a fuoco lento fino ad esaurimento dell''acqua; fate rosolare per alcuni minuti curando di mescolare continuamente il battuto con un cucchiaio di legno. Aggiungete, quindi, il passato di pomodoro, 1/2 litro di acqua, sale, pepe nero e la parte restante dell''olio d''oliva. Dopo aver mescolato il tutto immergete i pezzi di stoccafisso già lavati nella salsa avendo cura di porli con la pelle rivolta verso il basso evitando di sovrapporli e fate cuocere a fuoco lento. Dopo circa 20 minuti aggiungere le patate precedentemente tagliate ponendole negli spazi vuoti lasciati dal pesce e ricoprendo lo stesso con uno strato uniforme in modo da lambire il bordo superiore del liquido. Continuare la cottura per circa 90 minuti e, comunque, fino a completa cottura del pesce e delle patate avendo cura di non mescolare gli ingredienti ma di spostarli leggermente e delicatamente con l''aiuto di un cucchiaio di legno scuotendo la pentola. Suggerimenti. Per una perfetta riuscita della ricetta è indispensabile seguire scrupolosamente la scelta degli ingredienti e le fasi di preparazione. In considerazione del fatto che la preparazione riveste particolari difficoltà a coloro che si cimentano per la prima volta nella realizzazione di questa ricetta suggeriamo di provarla senza alcun impegno con ospiti e con dosi dimezzate al fine di prendere familiarità con quelli che sono classificati come ''segreti della cucina'' e che assicurano la perfetta riuscita della ricetta. Selezionare le parti migliori dello stoccafisso che deve essere ben ammollato ma altrettanto sodo e compatto. Le parti migliori sono quelle dorsali centrali e quelle di coda. Preparare tutti gli ingredienti seguendo scrupolosamente le modalità di preparazione e la sequenza d''impiego. La parte più difficile riguarda il tempo di cottura dal momento che lo stoccafisso e le patate non hanno la stessa consistenza e richiedono, pertanto, tempi di cottura differenti dipendenti dalla qualità della patata utilizzata e che va calcolato con una buona dose di esperienza.',14441);
INSERT INTO "ricette" VALUES (18470,'Pesche Agli Amaretti','Dessert','Pesche',4,' -','8 Mezze Pesche Sciroppate,
100 G Biscotti Amaretti,
1 Uovo,
60 G Zucchero,
80 G Burro,
1 Bicchierino Liquore,
Zucchero A Velo','Scolate bene le pesche. Prendete due mezze pesche, tagliatele a pezzettini e unitevi gli amaretti sbriciolati, il tuorlo d''uovo, lo zucchero e il burro: mescolate molto bene e riempite con questo composto le mezze pesche. Disponete le pesche in una teglia leggermente imburrata e passatele al forno per qualche minuto. Prima di servire, spolverate con zucchero a velo.',1804);
INSERT INTO "ricette" VALUES (18471,'Pesche Al Cioccolato','Dessert','Pesche',4,' -','1000 G Pesche Mature,
1 Cucchiaio Zucchero,
2 Cucchiai Cacao Amaro In Polvere,
10 Biscotti Amaretti','Tagliare le pesche a pezzetti di media grandezza, unire lo zucchero e farle cuocere ancora per 10 minuti dopo che avranno raggiunto il bollore. A questo punto, aggiungere il cacao in polvere e gli amaretti tritati. Lasciare cuocere ancora per pochi minuti. Lasciare raffreddare, poi mettere in frigo. Sono ottime come fresco dessert estivo. Per i più golosi, si propone di utilizzarle come guarnizione per una buona crema gialla.',812);
INSERT INTO "ricette" VALUES (18472,'Pesche Al Cioccolato (2)','Dessert','Pesche',4,' -','100 G Cioccolato Amaro,
4 Pesche Bianche,
1 Barattolo Pesche Sciroppate,
100 G Nocciole,
5 Cl Panna,
30 G Zucchero A Velo','Immergete per alcuni minuti le pesche nell''acqua calda e poi spellatele delicatamente senza rovinare la polpa. Frullate le pesche sciroppate, raccogliete il passato in una terrina e tenete nel congelatore per un''ora abbondante. Intanto, in una casseruolina, fate sciogliere a calore moderato il cioccolato con la panna e lo zucchero a velo e, quando il composto ha assunto la consistenza di una crema omogenea, ritirate il recipiente dal fuoco e mescolando fate raffreddare. Togliete dal congelatore il passato di pesche quando non è ancora del tutto ghiacciato, ma comincia ad avere una consistenza granulosa. Disponetelo su un piatto da portata e sopra adagiatevi le pesche bianche spellate, divise a metà e private del nocciolo. Tenete in frigorifero. Versate la salsa fredda sulle pesche e poi decoratele con le nocciole sgusciate e tritate.',1877);
INSERT INTO "ricette" VALUES (18473,'Pesche Al Forno','Dessert','Pesche',4,' -','Pesche Non Ancora Mature','Mettere le pesche nel forno caldo per 20 minuti, senza sbucciarle; pelatele prima di servirle.',72);
INSERT INTO "ricette" VALUES (18474,'Pesche Al Forno (2)','Dessert','Pesche',4,' -','5 Pesche Gialle,
100 G Biscotti Amaretti,
2 Cucchiai Vino Marsala,
Alcune Mandorle Tritate,
30 G Burro,
50 G Zucchero','Sbucciate le pesche e dividetele a metà; sbriciolate gli amaretti, unite lo zucchero e le mandorle tritate;aggiungete al composto una pesca e frullate; insaporite con il marsala. Riempite con la crema ottenuta le mezze pesche, mettete su ognuna un fiocchetto di burro e infornate a 200 gradi per mezz''ora. Fate raffreddare e servite.',1283);
INSERT INTO "ricette" VALUES (18475,'Pesche Al Riso','Dessert','Pesche',4,'Preparazione: 45 minuti.','150 G Riso,
4 Pesche Gialle,
50 G Biscotti Amaretti,
75 Cl Latte,
100 G Zucchero,
2 Uova,
20 G Burro,
1 Bicchiere Vino Marsala,
1 Pizzico Sale,
Limone','Lessate il riso nel latte al quale avrete aggiunto un pizzico di sale e la scorza grattugiata del limone. Quando sarà cotto, toglietelo dal fuoco ed unite gli amaretti sbriciolati, 50 g di zucchero, i tuorli delle uova, il burro ed infine gli albumi montati a neve. Tagliate le pesche a metà, togliete il nocciolo, scavate la polpa (che unirete al riso) e riempite il vuoto con il composto. Disponetele in una teglia imburrata, cospargetele di zucchero, versate il marsala e cuocete per 20 minuti circa. Potete servirle sia calde che fredde.',2183);
INSERT INTO "ricette" VALUES (18476,'Pesche Al Rum','Dessert','Pesche',4,' -','1000 G Pesche,
100 G Zucchero,
1 Bicchiere Rum','Mettere le pesche intere in acqua in ebollizione e farle bollire per 2-3 minuti. Sbucciarle, privarle del nocciolo, tagliarle a pezzi e coprirle con lo zucchero e il rum. Lasciare in frigorifero per circa 2 ore e servire.',1031);
INSERT INTO "ricette" VALUES (18477,'Pesche Al Rum (2)','Dessert','Pesche',4,' -','1000 G Pesche,
1 Bicchiere Rum,
100 G Zucchero','Mettere per 2-3 minuti le pesche intere in acqua in ebollizione. Pelarle e coprirle con lo zucchero e il rum. Servire fredde.',1031);
INSERT INTO "ricette" VALUES (18478,'Pesche Al Vino','Dessert','Pesche',4,' -','4 Pesche Gialle Duracine,
4 Cucchiai Zucchero,
Vino Rosso','Lavare le pesche, tagliarle a fette e metterle in una grande coppa. Cospargerle di zucchero, coprirle di vino e lasciarle insaporire. Mettere in frigorifero per circa 2 ore e servirle fredde.',379);
INSERT INTO "ricette" VALUES (18479,'Pesche Al Vino Rosso','Dessert','Pesche Bianche',4,' -','800 G Pesche Bianche,
100 Cl Vino Rosso,
170 G Zucchero,
1 Bustina Zucchero Vanigliato,
1 Chiodo Di Garofano,
1 Pizzico Noce Moscata','Per 5 minuti immergete le pesche in una casseruola d''acqua bollente. Sgocciolatele, passatele sotto l''acqua fredda e sbucciatele. Tagliatele in due ed eliminate il nocciolo. In una casseruola cuocete per circa 10 minuti il vino con lo zucchero, una bustina di zucchero vanigliato, il chiodo di garofano e un pizzico di noce moscata. Aggiungete le pesche, lasciate cuocere per altri 10 minuti e sgocciolatele. Fate ridurre lo sciroppo, versatelo sulle pesche e lasciate macerare mezza giornata.',1685);
INSERT INTO "ricette" VALUES (18480,'Pesche Alla Crema','Dessert','Pesche',4,' -','4 Pesche Gialle,
Liquore,
8 Ciliegie Candite,
4 Tuorli D''uovo,
100 G Zucchero,
40 G Farina,
1 Pizzico Sale,
50 Cl Latte,
1 Scorza Di Limone','Sbucciare le pesche, dividerle a metà, togliere un po'' di polpa, tritarla e metterla da parte. Sbattere i tuorli con lo zucchero, unire la farina, il sale e il latte caldo profumato con la scorza di limone. Cuocere la crema finché sarà densa. Disporla nelle mezze pesche, cospargere con la polpa tritata mescolata al liquore e decorare con le ciliegie.',1743);
INSERT INTO "ricette" VALUES (18481,'Pesche Alla Crema (2)','Dessert','Pesche',6,' -','10 Pesche Gialle,
1 Tazza Crema Pasticciera,
10 Biscotti Amaretti,
30 G Zucchero,
1 Bicchiere Vino Moscato,
Per La Teglia:,
Burro','Tagliare le pesche a metà, snocciolarle e levare con un cucchiaino parte della polpa. Unire alla crema pasticciera gli amaretti sbriciolati, amalgamare bene e riempire le pesche. Disporle su una teglia imburrata, spolverizzarle di zucchero, bagnarle con il vino e passarle in forno, a calore moderato, per 1 ora. Prima di servirle, versarvi sopra il fondo di cottura.',1938);
INSERT INTO "ricette" VALUES (18482,'Pesche Alla Crema Di Vino','Dessert','Pesche',8,' -','4 Pesche,
25 Cl Vino Rosso,
4 Tuorli D''uovo,
125 G Zucchero,
4 Cucchiai Gelatina Di Ribes O Gelatina Di Lamponi,
Per Decorare:,
Alcuni Lamponi','Pelate le pesche, ponetele in una casseruola, copritele con il vino rosso, mettete il coperchio e lasciate cuocere a fuoco medio fino a che saranno diventate morbide. Nel frattempo sbattete i tuorli con lo zucchero fino ad ottenere una crema omogenea. Levate le pesche dal vino e tenetele da parte per farle raffreddare. Nel vino di cottura ponete la gelatina di frutta e il composto di uova. Fate a cuocere a fuoco basso mescolando. Spegnete il fuoco e mescolate fino a che non sarà raffreddato. Tagliate a metà le pesche e privatele del nocciolo. Disponete due metà su un piattino e ricopritele con la crema. Mettete in frigorifero per mezz''ora prima di servire, decorando a piacere con i lamponi ogni piattino.',1428);
INSERT INTO "ricette" VALUES (18483,'Pesche Alla Melba','Dessert','Pesca',4,' -','1/2 Pesca,
Gelato Misto,
Mandorle,
Cioccolato Caldo,
Panna Montata','Mettete in una coppa mezza pesca e sopra sistemate 3 palline di gelato misto. Guarnite il tutto con mandorle e coprite con cioccolato caldo; infine cospargete di panna montata.',1412);
INSERT INTO "ricette" VALUES (18484,'Pesche Alla Parigina','Dessert','Mezze Pesche Sciroppate',4,'Luogo: Francia. Luogo: Parigi.','8 Mezze Pesche Sciroppate,
50 G Burro,
50 G Zucchero,
50 G Biscotti Amaretti,
50 G Mandorle,
25 G Farina,
2 Uova,
1 Limone,
Zucchero Vanigliato','Tostare le mandorle in forno e tritarle. Sbattere le uova con la farina poi unire le mandorle, gli amaretti tritati molto finemente, lo zucchero e la scorza di limone grattugiata. Amalgamare bene il composto. Fondere il burro in una teglia e disporvi le mezze pesche; riempirle con il composto e spolverizzarle con lo zucchero vanigliato. Cuocere in forno caldo per circa 25 minuti finché il ripieno si sarà rassodato.',1707);
INSERT INTO "ricette" VALUES (18485,'Pesche Alle Fragoline','Dessert','Pesche Gialle',4,' -','6 Pesche Gialle,
300 G Fragoline,
100 G Zucchero,
50 Cl Vino Bianco Dolce,
3 Cucchiai Marmellata Di Fragole','Sbollentate le pesche per alcuni minuti e spellatele. Tagliatele in due ed eliminate il nocciolo. Adagiatele in un piatto da portata. Spolverizzatele di zucchero e riempite con le fragoline l''incavo delle pesche. Diluite tre cucchiai di marmellata con due o tre cucchiai di vino dolce, versatela sulle fragoline. Lasciate insaporire al fresco per alcune ore prima di servire.',1230);
INSERT INTO "ricette" VALUES (18486,'Pesche Allo Sciroppo Con Gelato All''amaretto','Dessert','Pesche',4,' -','500 G Pesche Saporite Non Troppo Mature,
270 G Zucchero Di Canna,
120 G Biscotti Amaretti Sbriciolati,
300 G Panna,
3 Tuorli D''uovo','Fare bollire la panna, a parte intanto in una ciotola sbattere i tuorli con 70 g di zucchero, sino anche siano diventati spumosi. Unire, poco alla volta, la panna mescolando bene; aggiungere 100 g di amaretti, amalgamare bene il composto e, quando si sarà raffreddato, metterlo nella gelatiera. Preparare le pesche mettendole in un tegame, dopo averle lavate, con il resto dello zucchero e acqua quanto basta fino a ricoprirle. A seconda della dimensione dovranno cuocere per 15-20 minuti, in modo che, pur rimanendo sode, si possano facilmente sbucciare. Toglierle dal fuoco, cuocendo ancora un poco lo sciroppo affinché si restringa. Quando il tutto sarà freddo preparare un piatto di portata con lo sciroppo come salsa sul fondo, le pesche affettate e disposte a raggiera sopra e, al centro, il gelato. Cospargere le pesche con gli amaretti rimasti.',3248);
INSERT INTO "ricette" VALUES (18487,'Pesche Allo Zabaglione','Dessert','Pesche',4,' -','6 Pesche,
1 Bicchiere Vino Marsala,
3 Tuorli D''uovo,
75 G Zucchero','Sbucciate le pesche ben mature, apritele togliendo il nocciolo e posate ciascuna in una coppa. Versate sopra ad ognuna un cucchiaio di marsala e lasciate macerare per un''ora. Preparate intanto uno zabaglione con tre tuorli d''uovo, un bicchiere di marsala e lo zucchero. A preparazione ultimata versate lo zabaglione sulle pesche. Prima di servire fatele ghiacciare in frigo.',999);
INSERT INTO "ricette" VALUES (18488,'Pesche Allo Zabaglione (2)','Dessert','Pesche Gialle',4,' -','4 Pesche Gialle,
2 Chiodi Di Garofano,
1 Pezzetto Cannella,
2 Bicchieri Vino Bianco,
7 Cucchiai Zucchero,
4 Tuorli D''uovo,
1 Bicchierino Vino Marsala','Cuocere le pesche con il vino, i chiodi di garofano, 3 cucchiai di zucchero, la cannella e un po'' d''acqua. Bollire finché le pesche diventano morbide e levarle. Far ridurre lo sciroppo a fuoco vivace. Togliere dal fuoco e eliminare le spezie. Pelare le pesche, disporle in 4 coppe, coprirle con lo sciroppo e mettere in frigo. Preparare uno zabaglione con i tuorli, il Marsala e lo zucchero, metterlo nelle coppe e servire.',1135);
INSERT INTO "ricette" VALUES (18489,'Pesche Allo Zabaglione (3)','Dessert','Pesche',6,' -','6 Pesche,
Zucchero,
Per Lo Zabaglione:,
3 Tuorli D''uovo,
3 Cucchiai Zucchero,
3 Mezzi Gusci Vino Bianco (o Vino Marsala)','Preparate lo zabaglione. Pelate le pesche e tagliatele a spicchi. Disponetele in una coppa, spolverizzate di zucchero e versate sopra lo zabaglione. Mettete in frigo per qualche ora e servite.',785);
INSERT INTO "ricette" VALUES (18490,'Pesche Argentate','Dessert','Pesche',4,' -','4 Pesche Gialle,
4 Noci,
50 G Zucchero,
30 G Cacao,
30 G Burro,
2 Biscotti Amaretti','Prendete delle pesche belle, grosse e sode, lavatele, sbucciatele, tagliatele a metà e togliete il nocciolo. Preparate un ripieno con le noci tritate, lo zucchero, gli amaretti sminuzzati e il cacao. Distribuite il composto nell''incavo di ciascuna mezza pesca, adagiate su ciascuna un fiocchetto di burro ed avvolgetela in un foglio di carta stagnola chiudendo bene il cartoccio. Mettete in forno mezz''ora a 180 gradi.',998);
INSERT INTO "ricette" VALUES (18491,'Pesche Bellini','Dessert','Pesche A Polpa Bianca',4,' -','4 Pesche A Polpa Bianca,
4 Cucchiai Zucchero,
Vino Spumante Secco,
Poche Gocce Essenza Di Vaniglia,
Cannella In Polvere','Pelare le pesche, affettarle e dividerle in 4 coppette. Spolverizzarle con lo zucchero e la cannella, unire poche gocce di vaniglia e coprire con lo spumante. Tenere in frigo fino al momento di servire.',415);
INSERT INTO "ricette" VALUES (18492,'Pesche Calde','Dessert','Mezze Pesche Sciroppate',4,' -','10 Mezze Pesche Sciroppate,
8 Biscotti Amaretti,
50 G Frutta Secca Mista (noci, Noccioline, Nocciole, Mandorle),
2 Tuorli D''uovo,
1 Cucchiaio Miele Fluido,
Cannella In Polvere,
Burro','Scolare le pesche dallo sciroppo e frullarne 2. Tritare nel mixer gli amaretti e la frutta secca. Unire alla purea di pesche i tuorli, il trito di frutta e biscotti, il miele e un po'' di cannella. Mescolare bene e suddividere il composto nelle altre mezze pesche. Disporle in una pirofila poco imburrata e infornare a 200 gradi per 15 minuti.',1823);
INSERT INTO "ricette" VALUES (18493,'Pesche Col Ripieno','Dessert','Pesche Sciroppate',4,' -','8 Mezze Pesche Sciroppate,
4 Biscotti Amaretti,
2 Albumi D''uovo,
50 G Cioccolata Amara,
Burro','Sbriciolate gli amaretti e la cioccolata, aggiungete gli albumi montati a neve e versate il composto nelle mezze pesche, disposte in una teglia da forno imburrata. Cuocete a 180 gradi per mezz''ora. Servite tiepido.',1435);
INSERT INTO "ricette" VALUES (18494,'Pesche Con Amaretti','Dessert','Pesche',4,'Preparazione: 30 minuti.','4 Pesche,
100 G Biscotti Amaretti,
50 G Zucchero,
20 G Panna,
3 Cucchiai Liquore Amaretto,
30 G Burro','Lavare le pesche, farle scottare in acqua bollente e farle raffreddare in acqua fredda; privarle della buccia, dividerle a metà ed eliminare il nocciolo. Sbriciolare finemente gli amaretti; metterli in una terrina, aggiungere lo zucchero, la panna, il liquore e mescolare gli ingredienti con un cucchiaio di legno fino a ottenere un composto omogeneo. Distribuire il composto nelle mezze pesche preparate, adagiarle in una pirofila imburrata e spennellarle con il burro, diviso a pezzetti e fuso in un tegamino a bagnomaria. Porre la pirofila in forno preriscaldato a 180 gradi e far cuocere le pesche per 10-15 minuti finché saranno leggermente gratinate. Toglierle quindi dal forno e servirle tiepide oppure fredde.',1402);
INSERT INTO "ricette" VALUES (18495,'Pesche Farcite Al Cacao','Dessert','Pesche Gialle',4,' -','4 Pesche Gialle,
100 G Zucchero,
50 G Mandorle,
50 G Biscotti Amaretti,
25 G Burro,
1 Tuorlo D''uovo,
2 Cucchiai Cacao Amaro,
1 Scorza Di Limone,
Poco Brandy','Sbucciare le pesche, tagliarle a metà, eliminare il torsolo e, con un cucchiaino, scavare un po'' di polpa nella parte interna e raccoglierla in 1 terrina; mescolarvi la metà dello zucchero, il cacao, la scorza grattugiata del limone, le mandorle sbucciate e tritate, gli amaretti pestati e il tuorlo; mescolare e unire poco brandy. Riempire con il composto la cavità delle pesche, disporle in 1 tegame, cospargerle con il rimanente zucchero e infornare a 180 gradi per 15 minuti.',1588);
INSERT INTO "ricette" VALUES (18496,'Pesche Gratinate','Dessert','Pesche Gialle',4,' -','4 Pesche Gialle,
100 G Lamponi,
50 G Zucchero A Velo,
1 Cucchiaio Grand Marnier,
Per La Crema:,
4 Tuorli D''uovo,
4 Albumi D''uovo,
80 G Zucchero Semolato,
80 G Zucchero A Velo,
160 G Ricotta,
6 Gocce Estratto Di Mandorle,
1 Cucchiaio Mandorle A Scaglie,
1 Cucchiaio Panna Montata','Frullate i lamponi con il liquore e lo zucchero a velo, passateli da un setaccio fine e versateli sulle pesche pelate e tagliate a spicchi. Lasciate marinare per 1 ora. Sbattete intanto i tuorli con lo zucchero semolato. Quando sono gonfi e spumosi, amalgamatevi la ricotta passata al setaccio, l''estratto di mandorle e le mandorle a scaglie. Montate a neve gli albumi con lo zucchero a velo e uniteli delicatamente al composto di uova con un movimento dall''alto in basso. Unite allo stesso modo la panna montata. Al momento di servire, riscaldate brevemente in forno caldissimo le pesche con la marinata, distribuitele in 4 piatti, copritele con la crema e fatele gratinare sotto il grill.',1911);
INSERT INTO "ricette" VALUES (18497,'Pesche In Ghiaccio','Dessert','Pesche',4,' -','4 Pesche,
50 G Zucchero A Velo,
6 Quadretti Zucchero,
1 Limone','Lavare le pesche e sbollentarle per 2 minuti; quindi scolarle e pelarle subito. Allargare su un foglio di carta lo zucchero a velo e farvi rotolare le pesche, in modo che ne rimangano completamente rivestite. Lavare e asciugare il limone e strofinare i quadretti di zucchero sulla scorza affinché si impregnino della sua essenza. Disporre le pesche in un recipiente di vetro ampio, e distribuire i quadretti di zucchero fra le pesche. Mettere il recipiente nel frigo per 3 ore e servire ben ghiacciato.',477);
INSERT INTO "ricette" VALUES (18498,'Pesche Intere Sciroppate','Dessert','Pesche Gialle',4,' -','8 Pesche Gialle A Polpa Dura Non Troppo Grosse,
Primo Sciroppo:,
150 Cl Acqua,
500 G Zucchero,
Secondo Sciroppo:,
500 G Acqua,
750 G Zucchero,
100 Cl Alcool Per Liquori','Sbucciare le pesche e forarle in più punti con uno spillone, arrivando fino al nocciolo. Disporle in una terrina a bordi alti in un solo strato e coprirle con lo sciroppo (primo) bollente. Coprire con un canovaccio e lasciar riposare per 24 ore. Togliere le pesche e sistemarle in vasi di vetro che si possano chiudere ermeticamente. Preparare il secondo sciroppo e lasciarlo raffreddare, poi unirvi l''alcool. Aromatizzare a piacere con un po'' di vaniglia in polvere. Versare sulle pesche e coprirle bene prima di chiudere i vasi.',6792);
INSERT INTO "ricette" VALUES (18499,'Pesche Melba','Dessert','Pesche',4,' -','4 Pesche,
Gelatina Di Lamponi,
Gelato Alla Vaniglia,
4 Cucchiai Panna Montata,
Amarene Sciroppate,
Zucchero','Sbucciare le pesche e cuocerle per 5 minuti in acqua e zucchero. Farle raffreddare, metterle in una coppa, cospargerle con la gelatina di lamponi diluita e unire il gelato. Aggiungere un cucchiaio di panna e una amarena per ciascuna pesca e servire.',948);
INSERT INTO "ricette" VALUES (18500,'Pesche Meringate','Dessert','Pesche',4,' -','4 Pesche Grandi,
2 Cucchiai Brandy,
3 Cucchiai Zucchero,
6 Biscotti Amaretti,
3 Albumi D''uovo,
100 G Zucchero A Velo,
Per La Pirofila:,
Burro','Dividete a metà le pesche, scartate il nocciolo e allineatele in una casseruola, con la parte tagliata in basso. Bagnatele con il liquore, cospargete di zucchero, coprite e cuocete 5 minuti a fiamma bassa. Estraete le mezze pesche, fatele intiepidire e spellatele. Allineatele in una pirofila imburrata, con la parte tagliata in alto. Sbriciolate gli amaretti, inumiditeli con il liquido di cottura e distribuiteli sulle pesche. Montate a neve fermissima gli albumi, amalgamatevi lo zucchero a velo e ricoprite le pesche con la meringa preparata. Ponete sotto il grill del forno ben caldo per qualche minuto, fino a quando la meringa ha preso leggermente colore. Servite caldo, tiepido o freddo.',1852);
INSERT INTO "ricette" VALUES (18501,'Pesche Ripiene','Dessert','Pesche',4,' -','4 Pesche,
8 Biscotti Amaretti,
1 Carota,
1 Uovo,
1/2 Bicchierino Vino Porto,
Burro,
Zucchero','Sbucciare le pesche, dividerle a metà, e togliere il nocciolo; sbriciolare gli amaretti; grattugiare la carota. Mescolare gli amaretti con la carota e l''uovo e farcire le pesche con questo composto. Imburrare una teglia, disporvi le pesche, bagnare con il liquore, cuocere in forno per circa 20 minuti, cospargere di zucchero, infornare per altri 5 minuti, far caramellare e servire.',1354);
INSERT INTO "ricette" VALUES (18502,'Pesche Ripiene (2)','Dessert','Pesche Gialle',4,' -','5 Pesche Gialle,
60 G Zucchero,
30 G Cacao,
30 G Burro,
4 Biscotti Amaretti,
2 Tuorli D''uovo','Lavate quattro pesche, asciugatele, dividetele a metà senza sbucciarle ed eliminate il nocciolo. Togliete un po'' di polpa al centro, raccoglietela in una ciotola, aggiungete tutta la polpa della restante pesca, lo zucchero, gli amaretti sbriciolati, i tuorli e il cacao. Mescolate e riempite con questo composto le mezze pesche dando al ripieno la forma di cupoletta. Alla sommità di ognuna mettete un fiocchetto di burro. Imburrate una teglia, adagiatevi le pesche e cuocete in forno preriscaldato a 160 gradi per un''ora. Servitele calde o tiepide.',1094);
INSERT INTO "ricette" VALUES (18503,'Pesche Ripiene (3)','Dessert','Pesche',6,'Luogo: Piemonte. Luogo: Alba. Preparazione: 30 minuti. Cottura: 30 minuti.','6 Pesche Gialle Mature,
100 G Biscotti Amaretti,
2 Cucchiai Cacao Amaro In Polvere,
2 Cucchiai Zucchero,
2 Tuorli D''uovo','Le pesche migliori sono quelle sciaparine, ovvero che si spaccano in mezzo per una leggera pressione delle dita: a La Morra le chiamano persi del porèt e sono leggermente ovali, a forma di limone, al quale assomigliano anche per il colore e la superficie della buccia. Prendete queste pesche oppure di un altro cultivar e sbollentatele rapidamente, quindi spaccatele a metà, sbucciatele e privatele dei noccioli. Si possono anche non sbucciare, tuttavia l''operazione è consigliabile onde evitare il fastidio in bocca della buccia indurita per la cottura, soprattutto nelle persone già allergiche di per sè alla buccia vellutata. In una terrina sbriciolate gli amaretti piuttosto finemente e uniteli al cacao, allo zucchero e ai tuorli d''uovo: amalgamate con cura e deponete questa farcia nell''incavo delle pesche dopo averlo adeguatamente (ma non troppo) allargato con un cucchiaino. Sistemate le pesche così riempite in una teglia da forno e infornate a 160 gradi per mezz''ora circa. Lasciate raffreddare e servite. Vino consigliato: Moscato d''Asti.',1130);
INSERT INTO "ricette" VALUES (18504,'Pesche Ripiene (4)','Dessert','Mezze Pesche Sciroppate',4,' -','8 Mezze Pesche Sciroppate,
8 Biscotti Amaretti,
1 Carota Piccola,
1 Uovo,
Burro,
Zucchero,
1/2 Bicchierino Vino Porto','Polverizzare gli amaretti e grattugiare molto finemente la carota. Metterli in una ciotola e unirvi l''uovo, amalgamare bene il composto e usarlo per farcire le mezze pesche. Deporre le pesche in una teglia imburrata, irrorarle con il porto e cuocerle in forno caldo a 200 gradi per 20 minuti; 5 minuti prima di estrarle dal forno cospargerle con lo zucchero e terminare la cottura.',1483);
INSERT INTO "ricette" VALUES (18505,'Pesche Ripiene Di Amaretti Con Salsa Alla Nutella','Dessert','Pesche',4,' -','5 Pesche,
2 Cucchiai Zucchero,
1 Tuorlo D''uovo,
25 G Burro,
4 Cucchiai Nutella,
10 Biscotti Amaretti','Aprite quattro pesche a metà, snocciolatele e levate solo un po'' di polpa da ciascuna di esse. Disponete la polpa in una terrina e aggiungetevi l''altra pesca, gli amaretti tritati e il burro. Lavorate energicamente. Riempite con il composto ciascuna pesca e disponete i frutti in una teglia da forno imburrata; fate cuocere in forno già caldo a 180 gradi per 50 minuti circa. Servite tiepide con un cucchiaio di Nutella fusa a guarnire.',1345);
INSERT INTO "ricette" VALUES (18506,'Pesche Sciroppate','Dessert','Pesche',4,' -','Pesche,
4 Cucchiai Zucchero,
1/2 Bicchiere Acqua','Tagliare le pesche in due parti, seguendo il solco che parte dal picciolo; reggendo con una mano una metà, ruotare con forza l''altra metà in modo da staccarla dal nocciolo; liberare anche l''altra metà dal nocciolo aiutandosi con un cucchiaio. Sbucciare le mezze pesche e disporle nei barattoli; aggiungere, per ogni barattolo da 1/2 litro, 4 cucchiai di zucchero e 1/2 bicchiere d''acqua. Far bollire per 1/4 d''ora, togliere poi con un tubo l''acqua e far raffreddare i barattoli coperti.',233);
INSERT INTO "ricette" VALUES (18507,'Pesche Sciroppate Alla Panna','Dessert','Panna Montata',4,' -','4 Pesche Sciroppate,
100 G Biscotti Savoiardi,
100 G Panna Montata,
2 Cucchiai Sciroppo D''amarena','Sbriciolate o frullate i savoiardi. Raccogliete il ricavato in una ciotola e amalgamateli con la panna montata e lo sciroppo di amarena. Riempite con il composto le mezze pesche e tenete in frigo fino al momento di servire.',1205);
INSERT INTO "ricette" VALUES (18508,'Pesche Sciroppate Con Crema Zabaglione','Dessert','Pesche',8,' -','Per La Crema Zabaglione:,
200 G Vino Marsala Secco,
200 G Panna Montata,
120 G Zucchero,
6 Tuorli D''uovo,
Per Completare:,
4 Pesche Grandi,
300 G Zucchero,
250 G Fragoline Di Bosco,
1 Pezzetto Cannella','Per lo zabaglione: in una ciotola immerso in un bagnomaria caldo, tenuto sul fuoco moderatissimo montate, con una frusta, i tuorli, lo zucchero e il Marsala, ottenendo un composto denso e spumoso; toglietelo dal bagnomaria, fatelo raffreddare bene, poi incorporatevi la panna montata. Fate attenzione che questo sia ben freddo altrimenti la panna si smonta. Spaccate le pesche a metà, pelatele e cuocetele per 3 minuti in uno sciroppo ottenuto portando a bollore 700 g di acqua con 200 g di zucchero e un pezzetto di cannella; sgocciolate poi le mezze pesche e lasciatele raffreddare. Schiacciate con la forchetta 200 g di fragoline addolcite con 100 g di zucchero, ottenendo una specie di salsina. Versate nelle coppette lo zabaglione freddo, accomodatevi le pesche sciroppate, irroratele con la salsina di fragole, guarnitele con le fragoline rimaste e portatele subito a tavola. NB. Si possono utilizzare anche le pesche sciroppate pronte, ma quelle preparate in casa, specie se mature al punto giusto, risultano decisamente più gradevoli.',3347);
INSERT INTO "ricette" VALUES (18509,'Pesche, Vino E Zucchero','Dessert','Vino',4,' -','1 Pesca Sugosa,
Vino Rosso,
Zucchero','In un bicchiere, spezzettare una bella pesca sugosa, vino rosso (annacquatissimo per i bimbi), zucchero a pioggia. Da mangiare rigorosamente con lo stuzzicadenti.',151);
INSERT INTO "ricette" VALUES (18510,'Pesciolini Della Vigilia','Pesce','Pesce Di Paranza',4,' -','600 G Minutaglia Di Pesce Di Paranza,
1 Cipolla Grande,
Abbondante Mentuccia,
1 Scorzetta D''arancia,
Farina,
2 Cucchiai Aceto Di Mele,
Olio D''oliva Extra-vergine,
Sale','Lavare i pesciolini, asciugarli sopra un canovaccio, infarinarli e friggerli nell''olio interi, mettendoli su carta assorbente, salandoli. Brasare nell''olio la cipolla finemente affettata e umettarla con un po'' d''aceto, salare, quindi versarla sui pescetti. Rifinire con foglie di mentuccia e scorzette di arancia a fiammifero.',1724);
INSERT INTO "ricette" VALUES (18511,'Pestata Di Lardo Alla Lombarda','Salsa','Lardo',4,'Luogo: Lombardia.','100 G Lardo,
1 Mazzetto Prezzemolo Fresco,
1 Spicchio Aglio','Togliete la cotenna al lardo, tagliatelo quindi a piccoli pezzi e disponetelo sul tagliere di legno, insieme al prezzemolo di cui avrete scelto unicamente le foglioline più verdi. Unite l''aglio grossolanamente schiacciato e tritate finemente con la mezzaluna o il coltellaccio da cucina. Ponete questo battuto in una casseruola e fate soffriggere a fuoco moderato fino alla quasi completa liquefazione del grasso. È questa la base di quasi tutte le buone minestre lombarde, anche se altri componenti possono entrare di volta in volta in tante variazioni altrettanto tradizionali.',906);
INSERT INTO "ricette" VALUES (18512,'Pesto','Salsa','Basilico',4,' -','50 Foglie Basilico Fresco,
25 G Formaggio Parmigiano Grattugiato,
25 G Formaggio Pecorino Grattugiato,
1 Cucchiaio Pinoli,
3 Spicchi Aglio,
Olio D''oliva,
Sale','Il pesto si può ottenere sia con l''aiuto di un mortaio che con il frullatore. Gli ingredienti, sia nell''uno che nell''altro caso vanno messi tutti insieme, poi, pian piano, aggiungete l''olio a filo in quantità tali da rendere il composto cremoso e compatto.',1058);
INSERT INTO "ricette" VALUES (18513,'Pesto (2)','Salsa','Basilico',6,' -','40 Foglie Basilico Ligure A Foglia Piccola,
1 Pizzico Sale Grosso,
3 Spicchi Aglio,
1 Cucchiaio Formaggio Pecorino Sardo,
1 Cucchiaio Formaggio Parmigiano,
10 Cl Olio D''oliva Extra-vergine','Mettere nel mortaio di marmo il basilico, il sale e l''aglio e schiacciarli con movimento rotatorio contro le pareti. Quando sono tritati unire i formaggi grattugiati e continuare a lavorare con una spatola di legno. Ottenuta una pasta omogenea unire l''olio a filo continuando a lavorare la pasta fino ad avere una crema.',1101);
INSERT INTO "ricette" VALUES (18514,'Pesto (3)','Salsa','Basilico',6,' -','40 Foglie Basilico Ligure A Foglia Piccola,
1 Pizzico Sale Grosso,
2 Spicchi Aglio,
1 Cucchiaio Formaggio Pecorino Sardo,
1 Cucchiaio Formaggio Parmigiano,
10 Cl Olio D''oliva Extra-vergine,
40 G Pinoli','Mettere nel mortaio di marmo il basilico, il sale, i pinoli e l''aglio e schiacciarli con movimento rotatorio contro le pareti. Quando sono tritati unire i formaggi grattugiati e continuare a lavorare con una spatola di legno. Ottenuta una pasta omogenea unire l''olio a filo continuando a lavorare la pasta fino ad avere una crema.',1321);
INSERT INTO "ricette" VALUES (18515,'Pesto (4)','Salsa','Basilico',4,' -','25 Foglie Basilico,
25 G Formaggio Parmigiano,
25 G Formaggio Pecorino,
40 G Pinoli,
1/2 Bicchiere Olio D''oliva,
Sale','Lavate e asciugate molto bene le foglioline di basilico. Mettetele nel frullatore insieme a mezzo bicchiere di puro olio d''oliva, aggiungete i pinoli, un po'' di sale e frullate brevemente a media velocità. Unite i formaggi grattugiati, frullate ancora.',1105);
INSERT INTO "ricette" VALUES (18516,'Pesto (5)','Salsa','Basilico',4,'Luogo: Liguria.','100 G Foglie Di Basilico,
10 G Pinoli,
30 G Formaggio Pecorino,
2 Spicchi Aglio,
1/2 Bicchiere Olio D''oliva,
Sale','Si prende un mortaio da cucina e vi si mettono le foglie di basilico, l''aglio tagliato a pezzetti, e i pinoli e si comincia a pestare (pistu, appunto) questi ingredienti fino a ridurli in poltiglia; si aggiunge pian piano l''olio e il sale. Quando si avrà una salsa densa si aggiunge il formaggio grattugiato e si mescola ancora.',873);
INSERT INTO "ricette" VALUES (18517,'Pesto (6)','Salsa','Basilico',4,'Luogo: Liguria.','100 G Foglie Di Basilico,
10 G Pinoli,
30 G Formaggio Parmigiano,
1 Spicchio Aglio,
1/2 Bicchiere Olio D''oliva,
Sale','Si prende un mortaio da cucina e vi si mettono le foglie di basilico, l''aglio tagliato a pezzetti, e i pinoli e si comincia a pestare (pistu, appunto) questi ingredienti fino a ridurli in poltiglia; si aggiunge pian piano l''olio e il sale. Quando si avrà una salsa densa si aggiunge il formaggio grattugiato e si mescola ancora.',865);
INSERT INTO "ricette" VALUES (18518,'Pesto Alla Genovese','Salsa','Basilico',4,'Luogo: Liguria. Luogo: Genova. Preparazione: 20 minuti.','4 Mazzo Basilico,
2 Spicchi Aglio,
1 Cucchiaio Pinoli,
50 G Formaggio Grana Grattugiato,
50 G Olio D''oliva Extra-vergine,
Sale','Pulire il basilico e schiacciarlo nel mortaio con aglio, pinoli olio e sale, fino a formare una salsa. infine aggiungere il parmigiano.',713);
INSERT INTO "ricette" VALUES (18519,'Pesto Alla Genovese (2)','Salsa','Basilico',4,'Luogo: Liguria. Luogo: Genova.','4 Mazzo Basilico,
2 Spicchi Aglio,
1 Cucchiaio Pinoli,
50 G Formaggio Pecorino Grattugiato,
3 Cucchiai Olio D''oliva Extra-vergine,
Poco Sale Grosso','Pulire il basilico. Metterlo nel mortaio di marmo con il sale grosso, l''aglio e i pinoli. Pestare bene e a lungo. Aggiungere i due formaggi. Amalgamarli bene, diluendo a poco a poco con l''olio il composto. Per condire aggiungere un cucchiaio d''acqua di cottura della pasta.',880);
INSERT INTO "ricette" VALUES (18520,'Pesto Alla Genovese (3)','Salsa','Basilico',4,'Luogo: Liguria. Luogo: Genova.','3 Mazzetti Basilico,
25 G Formaggio Pecorino Sardo Poco Piccante,
25 G Formaggio Parmigiano Stagionato,
2 Spicchi Aglio,
10 Cl Olio D''oliva Extra-vergine,
1 Presa Sale Grosso,
25 G Pinoli (facoltativo)','Usate solo le foglioline del basilico che pesterete nel mortaio con gli spicchi d''aglio e una presa di sale. Quando il tutto sarà ridotto a poltiglia incominciate ad aggiungere i due tipi di formaggio. Man mano che lavorate aggiungete l''olio goccia a goccia. Questo è il sistema classico, ma si possono aggiungere anche 25 g di pinoli e invece del mortaio usare il frullatore. A preparazione ultimata, la salsa può essere diluita con un cucchiaio d''acqua di cottura della pasta, se deve condire quest''ultima; con un cucchiaio di brodo, se deve essere utilizzata per il minestrone. Ideale per paste asciutte e minestroni.',1260);
INSERT INTO "ricette" VALUES (18521,'Pesto Alla Genovese (4)','Salsa','Basilico',4,'Luogo: Liguria. Luogo: Genova.','40 Foglie Basilico A Foglie Piccole,
40 G Formaggio Parmigiano Reggiano,
20 G Pinoli,
1 Spicchio Aglio,
1 Pizzico Sale,
Olio D''oliva Extra-vergine','Lavate e asciugate il basilico, grattugiate il parmigiano reggiano e metteteli nel mixer insieme allo spicchio d''aglio e a un pizzico di sale. Frullate finché è ben triturato. Togliete dal mixer e mettete in una ciotola. Aggiungete del buon olio extra-vergine e amalgamate con un cucchiaio di legno. Potete conservarlo in frigorifero, coperto con abbondante olio, anche per alcuni giorni.',1000);
INSERT INTO "ricette" VALUES (18522,'Pesto Alla Genovese (5)','Salsa','Basilico',6,'Luogo: Liguria. Luogo: Genova.','40 Foglie Basilico Genovese,
4 Spicchi Aglio,
2 Cucchiai Formaggio Pecorino Sardo,
2 Cucchiai Formaggio Parmigiano,
Olio D''oliva Extra-vergine Delicato,
30 G Pinoli,
Sale Marino Integrale Grosso','In un mortaio di marmo pestare insieme il basilico, il sale, i pinoli e l''aglio. Quando gli ingredienti sono ben pestati unire il formaggio e lavorare il composto con una spatola di legno affinché diventi omogeneo. Unire l''olio a filo continuando a lavorare il composto fino a quando diventa una crema.',1228);
INSERT INTO "ricette" VALUES (18523,'Pesto Alla Genovese (6)','Salsa','Basilico',4,'Luogo: Liguria. Luogo: Genova.','2 Mazzi Basilico (le Foglie Devono Essere Tenere, Piccole E Profumate),
1 Manciata Pinoli,
1 Spicchio Aglio,
1 Cucchiaino Sale,
Formaggio Parmigiano Grattugiato,
Olio D''oliva Extra-vergine,
Burro','Togliere le foglie del basilico dal gambo e lavarle in acqua fredda corrente. Macinarle con i pinoli e l''aglio e aggiungere sale e olio finché l''amalgama raggiunge la consistenza desiderata. Un pesto dal sapore forte si ottiene lasciando gli ingredienti a grani più grossi. Alla fine aggiungere il parmigiano e unire il tutto con poco burro fatto sciogliere nel piatto da portata che precedentemente scalderemo sulla pentola che cuoce la pasta La pasta ideale per il pesto sono le trenette. Ma possono essere usate tutte le paste a grande superficie rigata, come le fettuccine. Assolutamente inadeguati gli spaghetti, i bucatini, maccheroni, penne o farfalle. Ottimi gnocchi e trofie. Da provare anche come condimento nel minestrone.',2244);
INSERT INTO "ricette" VALUES (18524,'Pesto Alla Genovese (7)','Salsa','Basilico',4,'Luogo: Liguria. Luogo: Genova.','Basilico,
Aglio,
Pinoli,
Sale,
Olio D''oliva Extra-vergine','Frullare insieme tutti gli ingredienti.',1298);
INSERT INTO "ricette" VALUES (18525,'Pesto Alla Genovese Con Il Bimby','Salsa','Basilico',6,' -','80 G Basilico Lavato E Asciugato,
50 G Formaggio Parmigiano,
30 G Formaggio Pecorino,
30 G Pinoli,
1 Spicchio Aglio,
15 Cl Olio D''oliva,
Sale','Inserisci nel boccale il parmigiano, il pecorino, i pinoli e l''aglio: 30 secondi a velocità turbo. Raccogli il trito con la spatola e unisci il basilico, l''olio e il sale 20 secondi a velocità 4 e 20 secondi a velocità 8. Serve per condire trenette, gnocchi, lasagne. Consigli: se vuoi renderlo più fluido aggiungi 1 cucchiaio di acqua di cottura della pasta.',1838);
INSERT INTO "ricette" VALUES (18526,'Pesto Alla Siciliana','Salsa','Basilico',4,'Luogo: Sicilia.','1 Mazzetto Basilico,
3 Spicchi Aglio,
50 G Pinoli,
1 Mazzetto Prezzemolo,
Alcune Foglie Sedano,
Alcuni Pomodorini Ciliegia,
Olio D''oliva Extra-vergine Siciliano Saporito,
Sale,
Pepe','Pestare gli ingredienti nel mortaio unendo l''olio un po'' alla volta fino ad ottenere una salsa omogenea e morbida. Condirvi la pasta appena scodellata e servire subito.',1114);
INSERT INTO "ricette" VALUES (18527,'Pesto Alla Trapanese','Salsa','Aglio',4,'Luogo: Trapani. Luogo: Sicilia.','Alcuni Spicchi Aglio,
Poco Sale,
Alcune Mandorle,
1 Pugno Basilico,
Alcuni Pomodori Freschi,
1 Filo Olio D''oliva Extra-vergine','E'' come un pesto alla genovese, ma un po'' più ruvido e colorato. Si fa così: pesta in un mortaio qualche spicchio di aglio con un po'' di sale e alcune mandorle. Buttaci dentro un bel pugno di basilico e qualche pomodoro fresco. Alla fine aggiungi un filo d''olio buono, e condisci la pasta.',598);
INSERT INTO "ricette" VALUES (18528,'Pesto Di Aglio Orsino','Salsa','Aglio Orsino',4,' -','100 G Foglie Fresche Di Aglio Orsino,
100 G Mandorle,
300 Cl Olio D''oliva Extra-vergine,
Sale,
1 Peperoncino (facoltativo)','Pestate il tutto con molta calma, oppure utilizzate il t