ersate il sugo sullo stinco. Vini di accompagnamento: Valle D''Aosta Chambave Rosso DOC, Pignolo VdT Del Friuli, Bruno Di Rocca VdT Di Toscana.',7041);
INSERT INTO "ricette" VALUES (24288,'Stinco Di Vitello Al Vino','Carne','Vitello',4,' -','1 Stinco Di Vitello,
2 Bicchieri Vino Bianco Secco,
1 Rametto Rosmarino,
2 Cipolline,
Brodo,
Olio D''oliva,
Burro,
Sale,
Pepe','Liberate lo stinco dai tendini, praticate dei taglietti qui e là e inseritevi una lamella di aglio prima passata nel sale e pepe. Spennellate lo stinco di olio, salate, pepate, adagiatelo in una teglia con tre cucchiai di olio e una noce di burro, le cipolline, il rosmarino e ponete in forno preriscaldato a 190 gradi per tre ore. Ogni quarto d''ora bagnatelo con il suo sugo di cottura o con un po'' di brodo caldo. Quando lo stinco è cotto disponetelo sul piatto da portata. Nel recipiente di cottura versate il vino, mescolate e fate ridurre fino a ottenere un sughetto denso da servire il salsiera ben caldo.',3113);
INSERT INTO "ricette" VALUES (24289,'Stinger','Bevande','Brandy',1,' -','3/10 Crema Menta Bianca,
7/10 Brandy','Si prepara nello shaker con cubetti di ghiaccio. Servire nella coppetta da cocktail ben fredda.',309);
INSERT INTO "ricette" VALUES (24290,'Stinger (10)','Bevande','Brandy',1,' -','4 Cubetti Ghiaccio,
6 Cl Brandy,
3 Cl Crema Di Menta Bianca','Mettete i cubetti di ghiaccio nello shaker ed unitevi il brandy e la crema di menta bianca. Chiudete Io shaker e agitatelo vigorosamente per qualche istante e con continuità, poi versate il cocktail nell''apposita coppetta (ben raffreddata nel freezer), avendo cura di trattenere il ghiaccio nello shaker.',185);
INSERT INTO "ricette" VALUES (24291,'Stinger (11)','Bevande','Cognac',1,' -','7/10 Cognac,
3/10 Crema Di Menta Incolore,
1 Spruzzo Succo Di Limone (facoltativo)','Versare il cognac e la crema di menta in uno shaker con alcuni cubetti di ghiaccio. Si può anche aggiungere 1 spruzzo di succo di limone. Agitare bene. Passare in una coppetta da cocktail.',311);
INSERT INTO "ricette" VALUES (24292,'Stinger (2)','Bevande','Brandy',1,' -','3/4 Brandy,
1/4 Crema Menta Bianca','Si prepara nello shaker con ghiaccio tritato.',314);
INSERT INTO "ricette" VALUES (24293,'Stinger (3)','Bevande','Brandy',1,' -','3/4 Brandy,
1/4 Crema Di Menta Bianca','Mescolare gli ingredienti con ghiaccio, mettere in un bicchiere da cocktail e servire.',314);
INSERT INTO "ricette" VALUES (24294,'Stinger (4)','Bevande','Brandy',1,' -','2/3 Brandy,
1/3 Crema Di Menta Bianca','Squisito digestivo, si prepara agitando nello shaker con ghiaccio i due ingredienti.',306);
INSERT INTO "ricette" VALUES (24295,'Stinger (5)','Bevande','Brandy',1,' -','180 G Brandy,
90 G Crema Di Menta Bianca','Squisito digestivo, si prepara agitando nello shaker con ghiaccio i due ingredienti.',4576);
INSERT INTO "ricette" VALUES (24296,'Stinger (6)','Bevande','Brandy',1,' -','2/3 Brandy,
1/3 Crema Di Menta Bianca','Versare gli ingredienti nello shaker. Agitare bene e servire nelle coppette da cocktail. Questo cocktail è particolarmente apprezzato dagli anglosassoni.',306);
INSERT INTO "ricette" VALUES (24297,'Stinger (7)','Bevande','Cognac',1,' -','1/3 Pippermint Get,
2/3 Cognac','Si prepara nello shaker con ghiaccio cristallino, versando il cognac e il Pippermint. Agitare in due riprese, versare servendo nei bicchieri da cocktail, possibilmente refrigerati. Questo cocktail viene considerato un ottimo digestivo.',306);
INSERT INTO "ricette" VALUES (24298,'Stinger (8)','Bevande','Cognac',1,' -','1/3 Crema Di Menta Bianca,
2/3 Cognac,
Per Servire:,
4 Gocce Succo Di Limone (facoltativo)','Agitare nello shaker con poco ghiaccio. Servire nel calice panciuto, aggiungendo direttamente nel bicchiere (se gradite) 4 gocce di succo di limone.',308);
INSERT INTO "ricette" VALUES (24299,'Stinger (9)','Bevande','Southern Comfort',1,' -','1/5 Succo Di Limone,
1/5 Crema Di Menta Bianca,
3/5 Southern Comfort,
Per Servire:,
1 Fetta Limone','Agitare vigorosamente e a lungo nello shaker con ghiaccio in cubetti. Servire nel tumbler stretto con una fetta di limone.',194);
INSERT INTO "ricette" VALUES (24300,'Stiracchio','Contorno','Lesso Avanzato',4,' -','400 G Lesso Avanzato,
2 Cipolle,
500 G Pomodori Maturi (o Pomodori Pelati),
2 Spicchi Aglio,
8 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe,
Salvia','In un tegame con 8 cucchiai d''olio d''oliva extra-vergine, rosolare l''aglio e la salvia, aggiungere le cipolle tagliate a fettine e subito dopo i pomodori, aggiustare di sale e pepe e cuocere il tutto per mezz''ora. Preparare il lesso in piccoli bocconcini o fettine, ed aggiungerlo al sugo preparato dove dovrà cuocere per circa 15 minuti. Noterete che il lesso si sfibrerà quasi come se fosse, appunto ''stiracchiato''.',1902);
INSERT INTO "ricette" VALUES (24301,'Stoccafisso A Gghiotta','Pesce','Stoccafisso',4,' -','600 G Stoccafisso Già Ammollato,
500 G Cavolfiore,
400 G Pomodori Maturi,
100 G Olive Verdi,
20 G Capperi,
1 Cipolla,
Olio D''oliva,
1 Pizzico Sale','Lavate lo stoccafisso e lessatelo a metà cottura in abbondante acqua salata. Scolatelo, diliscatelo, spellatelo e tagliatelo a pezzi. Mondate il cavolfiore, lavatelo e cuocetelo per una decina di minuti in acqua salata. Immergete i pomodori per qualche minuto in acqua bollente, spellateli e tritateli. In un largo tegame, possibilmente di terracotta, rosolate in un po'' d''olio una cipolla di media grandezza tagliata a fettine; aggiungete i pomodori e lasciate cuocere per qualche minuto a fuoco basso. Unite le olive e i capperi lavati e strizzati, un pizzico di sale e dopo un altra decina di minuti di cottura i pezzi di stoccafisso e il cavolfiore tagliato a fettine. Terminate di cuocere e servite caldo.',3172);
INSERT INTO "ricette" VALUES (24302,'Stoccafisso Accomodato Con Crostino Di Ciauscolo E Indivia Brasata','Pesce','Stoccafisso',4,' -','300 G Stoccafisso,
Aglio,
Prezzemolo,
1 Cucchiaio Pinoli,
50 G Olive Nere,
1 Bicchiere Vino Bianco,
4 Fette Pancarré,
100 G Ciauscolo,
1 Cespo Insalata Belga (indivia),
Poco Olio D''oliva','Il ciauscolo è un insaccato tipico delle Marche. Rosolare l''aglio e il prezzemolo, aggiungere lo stoccafisso a pezzetti, bagnare con del vino bianco e terminare la cottura con olive e pinoli tostati. Disporre in una coppa pasta alternando con delle fettine di pancarré tostato e spalmato con il ciauscolo. Accompagnare con il cespo di indivia rosolato in padella velocemente con poco olio. Terminare la cottura con un coperchio.',3804);
INSERT INTO "ricette" VALUES (24303,'Stoccafisso Agli Odori','Pesce','Stoccafisso',4,' -','1 Filetto Di Stoccafisso Di 800 G,
4 Patate Piccole,
2 Cipolle,
4 Spicchi Aglio,
Timo Fresco,
Prezzemolo Fresco,
Menta Fresca,
Olio D''oliva Extra-vergine,
1 Grattatina Zenzero,
Sale Marino Integrale,
Pepe In Grani','Tagliare lo stoccafisso in pezzi e salarli in superficie. In un''ampia padella far imbiondire la cipolla sottile sottile. Unire 3 mestoli d''acqua calda, le patate a fettine, un trito di aglio e prezzemolo, e inoltre timo e menta sminuzzati a mano. Unire lo stoccafisso in pezzi; regolare di sale e pepe e rifinire con una grattatina di zenzero; cuocere dolcemente.',4276);
INSERT INTO "ricette" VALUES (24304,'Stoccafisso Al Latte','Pesce','Stoccafisso',6,' -','Olio D''oliva,
Vino Bianco Secco,
50 G Acciughe Salate,
100 Cl Latte,
1000 G Stoccafisso Ammollato,
Cipolla,
Prezzemolo,
Alloro,
Formaggio Parmigiano Grattugiato,
Farina,
Pepe,
Sale,
Aglio','Privare lo stoccafisso di pelle e spina e tagliarlo a grossi pezzi. Preparare un soffritto con olio d''oliva, aglio prezzemolo e cipolla tritati e le acciughe spinate e lavate a pezzetti. Bagnare con vino e far evaporare. Porre i pezzi infarinati di stoccafisso in una pirofila, unire il soffritto, latte, parmigiano, alloro, sale e pepe. Infornare per 2 ore.',5647);
INSERT INTO "ricette" VALUES (24305,'Stoccafisso Al Latte (2)','Pesce','Stoccafisso',6,' -','1000 G Stoccafisso Ammollato,
Olio D''oliva,
1 Bicchiere Vino Bianco Secco,
50 G Acciughe,
100 Cl Latte,
Aglio,
Cipolla,
Prezzemolo,
Alloro,
Formaggio Parmigiano Grattugiato,
Farina,
Pepe,
Sale','Spellare lo stoccafisso, togliere la spina e tagliarlo a grossi pezzi. Preparare un soffritto con l''olio, l''aglio, il prezzemolo e la cipolla tritati, e le acciughe, lavate e spinate, a pezzetti; bagnarlo con il vino bianco e farlo evaporare a fuoco vivo. Allineare i pezzi di stoccafisso infarinati in una pirofila, versarvi sopra il soffritto, il latte, il parmigiano e l''alloro. Salare, pepare e infornare per circa 2 ore.',5681);
INSERT INTO "ricette" VALUES (24306,'Stoccafisso Al Vapore Alla Purea Di Olive','Pesce','Stoccafisso',4,' -','800 G Stoccafisso,
Olio D''oliva Extra-vergine,
Sale Marino Integrale,
Scalogno,
Pasta Di Olive E Capperi Fatta In Casa','Dividere lo stoccafisso in 4 pezzi, salarli bene all''esterno e porli nel cestello di una pentola per la cottura a vapore (quando l''acqua bolle). Far cuocere coperti 15-20 minuti. Adagiare i pezzi di stoccafisso nei piatti singoli e coprirli con la pasta di olive e capperi disciolta con un cucchiaio d''acqua di cottura; cospargere di scalogno sottilmente affettato e irrorare con olio crudo.',3864);
INSERT INTO "ricette" VALUES (24307,'Stoccafisso Al Vino Bianco','Pesce','Stoccafisso',4,' -','800 G Stoccafisso,
Sale Marino Integrale,
25 Cl Vino Bianco Secco,
Prezzemolo Tritato,
Pepe Bianco In Grani,
Olio D''oliva Extra-vergine,
Aglio','Salare i pezzi di stoccafisso all''esterno; adagiarli nel cestello di una pentola per la cottura a vapore sul cui fondo è stato versato il vino con grani di pepe. Cuocere ben coperto per 15 minuti dal momento in cui bolle. Adagiare sui piatti e condire con scagliette di aglio, prezzemolo tritato e olio crudo.',3777);
INSERT INTO "ricette" VALUES (24308,'Stoccafisso All''anconetana','Pesce','Stoccafisso',8,'Luogo: Marche. Luogo: Ancona. Preparazione e cottura: 240 minuti.','1 Stoccafisso Di 2500 G Battuto, Ammollato E Scolato,
200 G Acciughe Sotto Sale,
2500 G Patate,
600 G Pomodorini Pachino,
1 Cipolla,
6 Spicchi Aglio,
1 Mazzo Prezzemolo,
Alcuni Rametti Rosmarino,
1 Pugno Capperi,
2 Manciate Olive Nere,
50 Cl Vino Bianco Secco,
100 Cl Olio D''oliva Extra-vergine','Aprite lo stoccafisso, diliscatelo e tagliatelo a pezzi regolari di circa 10 centimetri di lato. Sbucciate e tagliate a grossi spicchi le patate. Con la cipolla, l''aglio, il prezzemolo, il rosmarino, i capperi, le acciughe (dissalate e diliscate) preparate un battuto finissimo e diluitelo con l''olio d''oliva extra-vergine. Sistemate sul fondo di una pentola uno strato di canne di bambù, che impedirà al pesce di attaccare. Mettete poi uno strato di stoccafisso (con la pelle rivolta verso il basso), uno di pezzi di patate, un altro di pesce e continuate a strati intervallando con qualche cucchiaiata di salsa. Alla fine versate la salsa rimanente, le olive snocciolate intere, i pomodorini eventualmente tagliati a metà e il vino. Fate prendere il bollore a fuoco vivace, poi coprite, abbassate la fiamma al minimo e proseguite la cottura per altre due ore e mezzo-tre ore, senza mescolare nè muovere la pentola. Lasciate riposare la pietanza per un quarto d''ora prima di portarla in tavola, distribuendo nei piatti patate, stoccafisso e intingolo.',12334);
INSERT INTO "ricette" VALUES (24309,'Stoccafisso Alla Genovese','Pesce','Stoccafisso',4,'Luogo: Liguria. Luogo: Genova.','500 G Stoccafisso,
4 Pomodori Pelati Maturi,
1 Cucchiaio Pinoli,
1 Manciata Uvetta Sultanina,
2 Patate Grandi,
1 Cipollina,
4 Spicchi Aglio,
1 Mazzetto Prezzemolo','Prendete dello stoccafisso già bagnato: toglietegli le lische e spellatelo. Tagliatelo poi a dadini e rosolatelo per qualche minuto in una pentola possibilmente di terracotta con mezzo bicchiere di olio e un battuto di cipolla, aglio e prezzemolo. Aggiungete i pomodori tagliuzzati, i pinoli, l''uvetta sultanina (che avrete messo a mollo mezz''ora prima in acqua tiepida), salate, pepate e cuocete a fuoco lento e a pentola coperta per un''ora, aggiungendo - se occorresse - un mestolino di acqua. A questo punto mettete le patate tagliate a pezzetti irregolari, aggiungete un po'' di acqua e lasciate ancora sul fuoco (a fiamma bassa) per un''ora. Unite prima di servire 1 cucchiaio di prezzemolo tritato.',2529);
INSERT INTO "ricette" VALUES (24310,'Stoccafisso Alla Livornese','Pesce','Stoccafisso',4,'Luogo: Toscana. Luogo: Livorno.','800 G Stoccafisso Ammollato,
4 Patate Grandi,
Sale,
1 Spicchio Aglio,
1 Peperoncino Piccante,
4 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Salsa Di Pomodoro,
100 G Olive Nere','Pulite lo stoccafisso, privandolo delle lische e della pelle. Quindi tagliatelo a pezzi piuttosto grandi e ponetelo in una larga pentola, la quale possa poi contenere tutti gli altri ingredienti. Sbucciate le patate e lasciatele da parte, poiché esse andranno unite al resto, soltanto a metà tempo di cottura del pesce. Coprite lo stoccafisso con acqua fredda; aggiustate di sale, essendo il pesce già molto salato di per se, aggiungete lo spicchio d''aglio, sbucciato ma intero, il peperoncino piccante, l''olio, la salsa di pomodoro e le olive. Coprite il recipiente, portate ad ebollizione, quindi abbassate la fiamma e lasciate cuocere lentamente per 1 ora e 30 minuti. Come già detto, a metà di questo tempo, unite agli ingredienti le patate, a pezzi, e continuate la cottura. Alla fine della preparazione, le patate risulteranno un pochino sfatte e lo stoccafisso sarà sbriciolato: è così che dovrà risultare il tutto. Servite caldo, irrorando con il liquido di cottura.',4614);
INSERT INTO "ricette" VALUES (24311,'Stoccafisso Alla Mediterranea','Pesce','Stoccafisso',4,' -','800 G Stoccafisso,
80 G Acciughe Sotto Sale,
250 G Pomodori Pelati,
1 Cucchiaio Capperi Interi,
1 Ciuffetto Prezzemolo,
1 Cipolla,
1 Spicchio Aglio,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe','Tritate una cipolla, uno spicchio d''aglio e un ciuffetto di prezzemolo. In un tegame scaldate mezzo bicchiere d''olio, fatevi insaporire il composto tritato, poi adagiate nel recipiente lo stoccafisso sgocciolato tagliato a pezzi piuttosto grandi e cuoceteli 5 minuti per parte. Aggiungete i pelati spezzettati, sale e pepe, cuocete ancora per 10 minuti. Lavate, dissalate e diliscate le acciughe, riducetele a pezzetti, unitele alla salsa. Quando sono disciolte, fate ancora insaporire per 5 minuti e, un minuto prima di togliere il recipiente dal fuoco, unite un cucchiaio di capperi interi. Vini di accompagnamento: Roero Arneis DOC, Verdicchio Castelli Di Jesi Classico DOC, Greco Di Tufo DOC.',3692);
INSERT INTO "ricette" VALUES (24312,'Stoccafisso Alla Messinese','Pesce','Stoccafisso',4,'Luogo: Sicilia. Luogo: Messina.','800 G Stoccafisso Ammollato,
4 Pomodori,
1 Cipolla,
2 Coste Sedano,
Capperi,
Olive,
2 Patate,
Uvetta Sultanina,
Pinoli,
Olio D''oliva Extra-vergine,
Sale','Dividere lo staccafisso in pezzi, infarinare e rosolare brevemente da entrambi i lati, togliere e tenere da parte. Far brasare nell''olio cipolla e sedano finemente tritati, capperi, olive. Unire i pomodori sbollentati, pelati e frantumati, 2 mestoli di brodo vegetale, le patate a tocchi e far cuocere a fuoco lento per 3/4 d''ora. Riunire lo stoccafisso e cuocere per altri 20 minuti.',4978);
INSERT INTO "ricette" VALUES (24313,'Stoccafisso Alla Vicentina','Pesce','Stoccafisso',4,'Luogo: Veneto. Luogo: Vicenza.','500 G Stoccafisso,
100 Cl Latte,
3 Spicchi Aglio,
Sale,
Burro,
Olio D''oliva Extra-vergine,
Prezzemolo Tritato','Mettere a bagno lo stoccafisso almeno 3 giorni prima della preparazione, in acqua fredda corrente. Tritare finemente l''aglio, farlo rosolare in olio e burro, quindi aggiungere lo stoccafisso tagliato a pezzetti senza pelle, farlo rosolare ed aggiungere il latte e 4 cucchiai di olio d''oliva extra-vergine, fare cuocere a fuoco lento per mezz''ora circa. A cottura ultimata lo stoccafisso si presenterà come una purea abbastanza densa, servire cospargendolo di prezzemolo tritato e olio d''oliva extra-vergine crudo.',3762);
INSERT INTO "ricette" VALUES (24314,'Stoccafisso Con Le Prugne','Pesce','Stoccafisso',4,' -','500 G Stoccafisso Già Ammollato,
1 Noce Burro,
12 Prugne Secche,
2 Cipolle,
50 Cl Vino Bianco,
1 Manciata Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Pulite lo stoccafisso dalla pelle e dalle lische e dividetelo in piccole trance. Scaldate 2-3 cucchiai d''olio e il burro in un largo tegame e versatevi le cipolle affettate sottilmente. Fate imbiondire e unite le trance di pesce. Salate leggermente, pepate e versate il vino. Mettete nel tegame le prugne, coprite e lasciate cuocere a fuoco basso per circa un''ora e un quarto, rigirando ogni tanto le trance di pesce con un cucchiaio di legno. Se il liquido di cottura dovesse asciugarsi troppo unite un po'' d''acqua calda. A fine cottura, spolverizzate con abbondante prezzemolo tritato. Servite con crostoni di pane o con polenta abbrustolita. Questo piatto può essere cotto anche in anticipo e poi può essere trasferito in una pirofila con le fette di polenta e scaldato in forno all''ultimo momento.',4270);
INSERT INTO "ricette" VALUES (24315,'Stoccafisso Con Patate','Pesce','Stoccafisso',6,' -','1000 G Stoccafisso (merluzzo Essiccato),
600 G Patate,
Olio D''oliva Extra-vergine,
1 Spicchio Aglio,
1 Limone,
Prezzemolo,
Sale','Mettere a bagno lo stoccafisso per 4 giorni o più, cambiando spesso l''acqua. Quando è ammorbidito togliere le spine e farlo bollire per 5 minuti in acqua salata e passarlo poi subito in acqua e ghiaccio. Nell''acqua di bollitura cuocere le patate a dadini. Disporre tutto in un piatto e condire con una salsa preparata con un trito di aglio e prezzemolo, succo di limone e olio.',4843);
INSERT INTO "ricette" VALUES (24316,'Stoccafisso Con Purea Di Sedano Rapa','Pesce','Stoccafisso',4,' -','1 Filetto Di Stoccafisso Ammollato,
Farina,
1 Patata,
1 Sedano Rapa,
50 G Formaggio Caciocavallo Fresco Grattugiato,
3 Spicchi Aglio,
Olio D''oliva Extra-vergine,
Sale Marino','Tagliare in pezzi lo stoccafisso, salarli all''esterno, infarinarli e soffriggerli dolcemente in aglio e olio per 15 minuti. Sbucciare e tagliare a dadini sedano rapa e patata; lessarli in acqua bollente salata e ancora caldi frullarli con un po'' d''acqua di cottura e olio a filo; mantecare col formaggio. Disporre la purea calda sui singoli piatti e adagiarvi lo stoccafisso con il suo intingolo.',4249);
INSERT INTO "ricette" VALUES (24317,'Stoccafisso Con Uvetta E Pinoli','Pesce','Stoccafisso',4,' -','800 G Stoccafisso Qualità Ragno (non Salato) Già Ammollato,
400 G Pomodori Pelati,
1 Spicchio Aglio,
1 Cipolla,
Olio D''oliva Extra-vergine,
30 G Uvetta Sultanina,
30 G Pinoli,
Sale Marino,
4 Grani Pepe Bianco,
Prezzemolo','In un tegame imbiondire nell''olio l''aglio e la cipolla affettata; unire i pomodori spezzettati e dopo alcuni minuti i pinoli, l''uva passa, sale e pepe. Cuocere 10 minuti a fuoco moderato; unire lo stoccafisso in pezzi salati in superficie e cuocerlo coperto 5-6 minuti per parte. Cospargere di prezzemolo e far riposare.',3910);
INSERT INTO "ricette" VALUES (24318,'Stoccafisso E Pomodori','Pesce','Stoccafisso',4,' -','800 G Stoccafisso Già Ammollato,
1 Cipolla,
Sedano,
2 Carote,
500 G Pomodorini Ciliegia,
50 G Olive Nere,
Vino Bianco,
Olio D''oliva,
Sale,
Peperoncino','Spinare e spellare il pesce. Tritare cipolla, sedano e carote e farli stufare con poco olio, a fuoco dolce. Unire il pesce, bagnare con il vino e rosolare per circa 10 minuti. Aggiungere i pomodorini spellati, le olive e un pezzetto di peperoncino e portare a cottura.',3949);
INSERT INTO "ricette" VALUES (24319,'Stoccafisso In Agrodolce','Pesce','Stoccafisso',6,'Luogo: Liguria.','1000 G Stoccafisso Bagnato,
10 Cl Olio D''oliva,
1 Cucchiaio Prezzemolo Tritato,
70 G Uvetta Sultanina,
60 G Pinoli,
60 G Burro,
2 Cucchiai Zucchero,
1 Cucchiaio Aceto Di Vino,
Sale,
Pepe','Bagnare l''uvetta in acqua e strizzarla. Privare lo stoccafisso di pelle e lische. In un tegame mettere 4 cucchiai d''olio, disporre i pezzi di stoccafisso e distribuirvi sopra prezzemolo, sale, pepe, un filo d''olio e pezzetti di burro. Far rosolare. Intanto in una padellina sciogliere lo zucchero con l''aceto e, mentre caramella, versare un po'' di acqua, sempre mescolando. Unire anche uvetta e pinoli. Versare la salsa sul pesce e terminare la cottura.',5518);
INSERT INTO "ricette" VALUES (24320,'Stoccafisso In Potacchio','Pesce','Stoccafisso',4,' -','400 G Stoccafisso Secco (o 800 G Di Stoccafisso Bagnato),
300 G Pomodori Maturi,
4 Filetti D''acciughe Sott''olio,
1 Cipolla,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
1 Bicchiere Vino Bianco Secco,
1 Rametto Rosmarino,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Battete lo stoccafisso con il batticarne e mettetelo a bagno in una terrina con abbondante acqua fredda per 2 giorni, cambiando spesso l''acqua. Dopo di che sgocciolate lo stoccafisso, asciugatelo, eliminate le lische e tagliatelo a pezzi. Sbucciate la cipolla e affettatela a velo, mettetela in una casseruola e fatela rosolare nell''olio, su fuoco basso. Sgocciolate le acciughe dall''olio, mondate il prezzemolo, lavatelo e staccate gli aghi di rosmarino dal rametto. Sbucciate lo spicchio d''aglio e preparate un trito con tutti gli aromi. Quando la cipolla sarà ben rosolata unite il trito aromatico, mescolate con un cucchiaio di legno e fate insaporire per qualche minuto. Scottate i pomodori in acqua bollente, pelateli, tagliateli a metà, eliminate i semini e tagliate la polpa a pezzetti. Aggiungete i pomodori nella casseruola, mescolate e fate cuocere per 5-6 minuti. Dopo di che unite i pezzi di stoccafisso e portate a cottura (circa 3 ore), mantenendo il fuoco basso. A metà cottura bagnate con il vino, salate e pepate a piacere. Se necessario durante la cottura unite un pochino di acqua calda.',2208);
INSERT INTO "ricette" VALUES (24321,'Stoccafisso In Salsa D''arancia D''ispirazione Rinascimentale','Pesce','Stoccafisso',4,' -','800 G Stoccafisso,
Olio D''oliva Extra-vergine,
Farina,
3 Arance (succo),
Chiodi Di Garofano,
Pepe In Grani,
1 Pizzico Cannella,
Zenzero,
Scorza D''arancia,
Sale Marino Integrale','Tagliare in pezzi lo stoccafisso ed infarinarlo bene dopo averlo salato all''esterno. Far dorare leggermente nell''olio a fuoco moderato. A parte far restringere sul fuoco il succo d''arancia con le spezie. Unirlo allo stoccafisso e far insaporire per qualche minuto a fuoco moderato. Decorare con scorza d''arancia sottilissima.',4043);
INSERT INTO "ricette" VALUES (24322,'Stoccafisso Mantecato','Pesce','Stoccafisso',4,'Luogo: Veneto. Preparazione: 40 minuti.','700 G Stoccafisso Bagnato,
Prezzemolo,
1 Spicchio Aglio,
1 Cipolla,
3 Patate,
2 Limoni,
Olio D''oliva,
Pepe,
Sale','Bollire lo stoccafisso per 10 minuti, con patate e cipolle. Tritare aglio e prezzemolo, farne un soffritto, aggiungere il limone. Prendere lo stoccafisso e spolparlo, tagliare le cipolle e le patate a rondelle. Mettere il tutto in una terrina e far finire di cuocere scuotendo energicamente.',3817);
INSERT INTO "ricette" VALUES (24323,'Stoccafisso Mantecato Alla Veneta','Pesce','Stoccafisso',4,'Luogo: Veneto.','600 G Stoccafisso,
150 G Olio D''oliva,
100 G Latte,
1/2 Cipolla,
Sale,
Pepe','Mettete lo stoccafisso già ammollato in una casseruola. Copritelo d''acqua, portate a bollore e lasciate sobbollire un quarto d''ora. Nel caso il pesce non fosse diventato abbastanza tenero proseguite la cottura ancora per una decina di minuti. Fatelo raffreddare nello stesso liquido, sgocciolatelo. Toglietegli la pelle, eliminate le lische ed eventuali particelle fibrose. Tagliatelo a piccoli pezzi. In un tegame scaldate quattro cucchiai d''olio e lasciatevi appassire la cipolla tritata. Adagiate nel recipiente lo stoccafisso e, sopra, versatevi lentamente il latte caldo e l''abbondante olio avanzato mescolando energicamente. Cuocete un''ora a fuoco basso mantenendo il liquido in leggera ebollizione. Il composto deve diventare bianco, spumoso, cremoso. Regolate sale e pepe. Servite con polenta. Vini di accompagnamento: Colli Euganei Pinot Bianco DOC, Orvieto DOC, Bianco D''Alcamo DOC.',3519);
INSERT INTO "ricette" VALUES (24324,'Stoccafisso Ripieno','Pesce','Stoccafisso',4,' -','1 Stoccafisso Da 500 G,
300 G Mollica Grattugiata,
300 G Olive Snocciolate,
30 G Burro,
4 Spicchi Aglio,
Rosmarino,
1/2 Bicchiere Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Amalgamare la mollica con l''aglio tritato, le olive intere e olio quanto basta per ottenere un composto omogeneo. Riempire lo stoccafisso, unendo il rosmarino e fiocchi di burro. Arrotolare il pesce e legarlo con filo da cucina. Cuocere a fuoco dolce per circa 2 ore in 1/2 bicchiere d''acqua, vino e abbondante olio.',4213);
INSERT INTO "ricette" VALUES (24325,'Stocco Alla Messinese','Pesce','Stoccafisso',4,'Luogo: Sicilia. Luogo: Messina.','600 G Stoccafisso Già Ammollato,
6 Patate,
1/2 Cipolla,
20 G Capperi,
50 G Olive,
1 Costa Sedano,
100 G Pomodori Pelati,
50 G Olio D''oliva,
30 G Uvetta Sultanina,
30 G Pinoli,
Sale,
Pepe','Imbiondire nell''olio la cipolla a fettine, unire i capperi, le olive, il sedano tritato, far insaporire qualche minuto, quindi unire i pelati, lo stoccafisso e le patate a pezzi. Salare, pepare e cuocere per 40 minuti a fuoco dolce. A metà cottura unire i pinoli e l''uvetta ammollata. Servire ben caldo.',4016);
INSERT INTO "ricette" VALUES (24326,'Stocco Alle Erbe','Pesce','Stoccafisso',4,' -','800 G Stoccafisso,
2 Cucchiai Olio D''oliva Extra-vergine,
1 Mazzetto Odoroso (timo, Maggiorana, Nepitella, Erba Cipollina, Prezzemolo, Rosmarino),
1 Limone,
2 Spicchi Aglio,
Pepe Bianco In Grani,
Sale Marino Integrale','Tagliare in pezzi lo stoccafisso e salarlo all''esterno. Preparare una marinata con olio, succo del limone, grani di pepe, erbe sminuzzate, aglio. Lasciar marinare per 90 minuti, quindi rigirandoli di tanto in tanto. Cuocere alla griglia spennellando con la marinata.',3269);
INSERT INTO "ricette" VALUES (24327,'Stocco In Agrodolce','Pesce','Stoccafisso',4,' -','800 G Stoccafisso,
30 G Pinoli,
30 G Uvetta Sultanina,
Farina,
Prezzemolo,
2 Cucchiaini Aceto Di Mele,
1 Cucchiaio Zucchero Di Canna,
Olio D''oliva Extra-vergine,
Sale Marino Integrale,
Pepe Bianco In Grani','Tagliare in 4 pezzi lo stoccafisso, salarli all''esterno e infarinarli. Farli dorare a fuoco moderato nell''olio con i grani di pepe. A parte caramellare lo zucchero e unirvi l''aceto; aggiungere 1/2 bicchiere d''acqua, i pinoli, l''uvetta fatta prima rinvenire. Far addensare leggermente la salsa e condirvi lo stoccafisso.',4149);
INSERT INTO "ricette" VALUES (24328,'Stollen','Dessert','Farina',4,' -','500 G Farina,
1 Bustina Lievito,
200 G Zucchero,
1 Bustina Zucchero Vanigliato,
1 Pizzico Sale,
4 Gocce Aroma Di Mandorle Amare,
4 Gocce Aroma Di Limone,
1 Fialetta Aroma Di Rum,
2 Pizzichi Cardamomo Macinato,
2 Pizzichi Noce Moscata,
2 Uova,
125 G Burro (o Margarina),
50 G Strutto,
250 G Ricotta,
40 G Canditi,
125 G Uvetta Sultanina Scura (korinten),
125 G Uvetta Sultanina Chiara (rosinen),
125 G Mandorle (o Nocciole)','Mescolare farina e lievito sul tavolo. Formare una conca e nel mezzo versarvi zucchero, uova, aromi e sale. Con parte della farina formare una poltiglia e sopra di essa mettere il burro freddo tagliato a pezzi, lo strutto, la ricotta, i canditi, l''uvetta sultanina e le mandorle macinate. Schiacciare tutto assieme e impastare velocemente. Se la pasta è appiccicosa aggiungere un po'' di farina. Dare la forma tipica dello stollen e mettere sulla lastra del forno unta e infarinata. Cuocere per circa 75 minuti a temperatura media (150-175 gradi). Al termine della cottura spalmare con burro fuso (50 g) e cospargere con zucchero a velo (50 g).',5955);
INSERT INTO "ricette" VALUES (24329,'Stone','Bevande','Cherry Brandy',1,' -','1/4 Vermouth Rosso,
2/4 Cherry Brandy,
1/4 Rum,
Per Servire:,
1 Ciliegia','Agitare nel mixer con ghiaccio in cubetti. Servire nel calice panciuto, con un cubetto di ghiaccio e una ciliegia.',330);
INSERT INTO "ricette" VALUES (24330,'Stop','Bevande','Scotch Whisky',1,' -','2/3 Scotch Whisky,
1/3 Punt E Mes,
3 Cubetti Ghiaccio,
2 Spruzzi Bitter','Shakerate i primi 3 ingredienti. Sopra versate 2 spruzzi di bitter. Agitate per poco tempo e versate in un calice tenuto fino a quel momento in frigorifero.',327);
INSERT INTO "ricette" VALUES (24331,'Storione Affumicato In Salsa','Antipasto','Storione',4,' -','300 G Storione Affumicato A Fettine,
1 Tazza Maionese,
1 Limone,
10 Fili Erba Cipollina,
10 Grani Pepe Rosa','Disponete le fettine di storione su un piatto da portata. Aggiungete alla maionese un cucchiaino alla volta di succo di limone, l''erba cipollina tritata finemente e una decina di grani di pepe rosa. Versate sulle fettine di pesce affumicato e servite.',759);
INSERT INTO "ricette" VALUES (24332,'Storione Al Forno All''emiliana','Pesce','Storione',4,'Luogo: Emilia-Romagna.','1 Storione Da 1000 G,
25 Cl Vino Bianco Albana,
1 Spicchio Aglio,
Salvia,
Rosmarino,
Olio D''oliva Extra-vergine Di Brisighella,
1 Limone,
Sale','Pulire lo storione. Salarlo all''interno e all''esterno. Farcirlo con rosmarino, aglio schiacciato, fettine di limone. Adagiarlo in una pirofila con olio, aglio, rosmarino, salvia; rosolare e unire il vino e appena prende bollore passare in forno caldo a 180 gradi e portare a termine la cottura bagnando di tanto in tanto con succo di limone.',1970);
INSERT INTO "ricette" VALUES (24333,'Storione All''aceto Balsamico','Pesce','Storione',8,' -','4 Trance Storione,
4 Acciughe Sotto Sale,
Poche Gocce Aceto Balsamico,
Vino Bianco,
1 Cipolla,
1 Costa Sedano,
Prezzemolo,
1 1/2 Spicchio Aglio,
Poco Olio D''oliva,
Sale,
Pepe','Tritate cipolla, spicchio d''aglio e sedano. Mettetene metà in una terrina, sopra adagiatevi il pesce, cospargetelo con il restante trito, sale e pepe. Spruzzate poche gocce di aceto balsamico e un po'' di vino. Marinate per circa 2 ore. In un tegame sciogliete in poco olio le acciughe dissalate e diliscate, aggiungete mezzo spicchio d''aglio e un po'' di prezzemolo tritati e rosolatevi le trance, da entrambe le parti. Vini di accompagnamento: Lugana DOC, Montecarlo Bianco DOC, Gravina DOC.',1392);
INSERT INTO "ricette" VALUES (24334,'Storione Alla Griglia','Pesce','Storione',4,' -','4 Trance Storione,
1/2 Bicchiere Vino Bianco Secco,
Aglio,
1 Rametto Timo,
Rosmarino,
1 Limone (succo),
1 Ciuffo Prezzemolo,
1 Bicchiere Olio D''oliva,
Sale,
Pepe','Versate in una terrina un bicchiere d''olio e mezzo di vino, il succo di un limone, un rametto di timo e uno di rosmarino, un ciuffo di prezzemolo, sale e pepe. Fate marinare per un''ora le trance di storione. Sgocciolatele, steccate le trance con pezzetti d''aglio e aghi di rosmarino. Scaldate la griglia, allineatevi le trance e cuocetele al grill del forno per un quarto d''ora. Spruzzatele con la marinata se dovessero asciugare. Vini di accompagnamento: Soave Superiore DOC, Verdicchio Dei Castelli Di Jesi DOC, Fiano Di Avellino DOC.',2283);
INSERT INTO "ricette" VALUES (24335,'Storione Alla Moda Di Ferrara','Pesce','Storione',4,'Luogo: Emilia-Romagna. Luogo: Ferrara.','800 G Storione Sfilettato,
50 Cl Vino Trebbiano Di Romagna,
2 Acciughe,
Poca Salsa Di Pomodoro,
Olio D''oliva Extra-vergine Di Brisighella,
Aglio,
Cipolla,
Sedano,
Alloro,
Prezzemolo,
Sale,
Pepe','Cospargere il fondo di una terrina con metà trito d''aglio, cipolla, sedano; adagiarvi lo storione tagliato a fette. Coprire col trito rimasto, foglie di alloro, sale, pepe; irrorare col vino. Marinare 3 ore. Rosolare in olio un trito d''aglio e prezzemolo e acciughe stemperate; unire lo storione e far insaporire. Unire metà vino filtrato e pomodoro. Cuocere piano e far restringere.',2051);
INSERT INTO "ricette" VALUES (24336,'Storione Allo Yogurth','Pesce','Storione',4,' -','4 Cucchiai Senape Di Digione In Grani,
Poco Aceto Di Vino,
1 Trancio Storione Affumicato (da 300 G),
8 Cucchiai Yogurth Intero,
1 Trito Aneto O Cerfoglio O Prezzemolo','Mescolare con cura la senape e lo yogurth fino a ottenere un composto amalgamato. Insaporire con il trito aromatico e, usando una frusta, montare leggermente la salsa. Tagliare a fettine sottilissime lo storione, disporle su un piatto da portata e napparle con la salsa. Guarnire a piacere con rametti di aneto o cerfoglio o prezzemolo.',543);
INSERT INTO "ricette" VALUES (24337,'Storione Arrosto Alla Giuliana','Pesce','Storione',4,'Luogo: Friuli.','1 Storione Da 1000 G,
1 Filo Olio D''oliva Extra-vergine,
50 G Burro,
2 Listarelle Lardo,
1 Limone Grande (succo),
1 Bicchiere Ribolla Friulana,
Sale,
Pepe','Pulire lo storione privandolo della pelle; praticare nella polpa dei tagli ed introdurvi le listarelle di lardo. Soffregare con sale e pepe, bagnare con succo di limone, vino e un filo d''olio e far marinare così per 1 ora. Disporre lo storione in una pirofila, irrorare con la marinata e cospargere di fiocchetti di burro. Infornare a 180 gradi per 40 minuti.',2223);
INSERT INTO "ricette" VALUES (24338,'Storione Con Carciofi','Pesce','Storione',4,' -','4 Trance Storione,
4 Carciofi,
1 Spicchio Aglio,
4 Pomodori,
Alcune Foglie Mentuccia,
6 Cucchiai Olio D''oliva,
1 Pizzico Sale,
1 Pizzico Pepe','Tagliate il gambo ai carciofi. Disponeteli dritti in una casseruola, versate acqua fino a metà altezza del carciofo, aggiungete tre cucchiai d''olio, uno spicchio d''aglio, alcune foglioline di mentuccia, un pizzico di sale e pepe. Cuoceteli coperti, a fuoco piuttosto basso, per circa 40 minuti. Alla fine il liquido dovrebbe essere quasi del tutto assorbito. In caso contrario, scoprite il recipiente e proseguite la cottura per farlo evaporare. In un tegame scaldate tre cucchiai d''olio e cuocetevi le trance di storione 3 o 4 minuti per parte, girandole una volta soltanto. Tagliate a metà i pomodori, eliminate i semi, cospargeteli con un pizzico d''aglio tritato e cuoceteli in forno preriscaldato a 180 gradi sulla griglia per 5 o 6 minuti. Sul piatto da portata tenuto in caldo disponete a raggiera i carciofi tagliati a metà, al centro mettete le scaloppe di pesce leggermente sovrapposte e, fra un carciofo e l''altro, sistemate le scodelline di pomodoro. Servite subito. Vini di accompagnamento: Collio Traminer Aromatico DOC, Cervaro Della Sala IGT Dell''Umbria, Arenarie Alghero DOC.',3133);
INSERT INTO "ricette" VALUES (24339,'Storione Con Salsa Ai Peperoni','Pesce','Storione',4,' -','800 G Filetto Di Storione,
800 G Peperoni Rossi,
Vino Bianco Secco,
Cipolla,
1 Foglia Alloro,
1 Spicchio Aglio,
Cerfoglio,
Dragoncello,
Olio D''oliva,
Sale,
Pepe','Pulite i peperoni, privateli dei piccioli e dei semi, tagliateli a falde. Scaldate in un tegame tre cucchiai d''olio e lasciatevi appassire una cipolla tritata. Unite i peperoni, salate, pepate e cuocete, a tegame coperto e a fuoco moderato, per circa mezz''ora. Bagnate ogni tanto i peperoni con un po'' d''acqua calda. Intanto pulite e lavate il pesce, asciugatelo e mettetelo in una teglia, spennellatelo con un filo d''olio, unite cerfoglio, dragoncello, uno spicchio d''aglio e una foglia d''alloro intera. Salate, pepate e cuocete in forno preriscaldato a 180 gradi per circa mezz''ora. Durante la cottura spruzzate ogni tanto lo storione con il vino. Appena i peperoni sono cotti, frullateli sino a ottenere una salsa di giusta consistenza. Se è eccessivamente liquida, fatela ridurre a fuoco vivace. Se è troppo densa, allungatela con un po'' d''acqua tiepida. Versate la salsa sul fondo del piatto da portata, sopra disponetevi il filetto di storione. Servite subito. Vini di accompagnamento: Alto Adige Sauvignon DOC, Colli Martani Grechetto DOC, Castel Del Monte Sauvignon DOC.',1833);
INSERT INTO "ricette" VALUES (24340,'Storione E Salmone A Listarelle','Antipasto','Storione',6,' -','120 G Fettine Di Storione Affumicato (o Fettine Di Storione Bollito),
120 G Fettine Sottili Di Salmone Affumicato,
4 Cucchiai Olio D''oliva,
1 Cucchiaio Aceto Di Vino,
Pancarré Grigliato Caldo,
Pepe Macinato','Tagliate a listarelle corte e sottili lo storione e il salmone, disponetele in due piccole vaschette e condite con olio, aceto, e un pochino di pepe macinate. Non aggiungete sale. Servite accompagnando con pancarré fatto tostare al momento, e ben caldo. Lo storione può essere affumicato, o anche fresco, già bollite, e venduto a fette dal salumiere. Volendo, il pancarré può essere sostituito da blinis.',2048);
INSERT INTO "ricette" VALUES (24341,'Storione In Umido','Pesce','Storione',4,' -','4 Tranci Storione,
Sedano,
Aglio,
Cipolla,
Alloro,
Prezzemolo,
5 Filetti D''acciughe,
1 Mestolino Sugo Di Pomodoro,
50 Cl Vino Bianco Secco,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Privare lo storione della pelle, lavarlo, asciugarlo, accomodare i tranci in una terrina in uno strato unico. Rosolare, salare, pepare, unire un trito di alloro, sedano, cipolla e coprire col vino, facendo marinare in frigo per 2 ore. In un coccio imbiondire un trito d''aglio e prezzemolo con le acciughe; rosolarvi lo storione; unire, poi, parte della marinata filtrata, il sugo e cuocere.',2071);
INSERT INTO "ricette" VALUES (24342,'Storione Per Antipasto','Antipasto','Storione',4,' -','1 Trancio Di Storione Di 600 G,
100 Cl Court-bouillon Al Vino Bianco,
10 Cl Olio D''oliva,
1 Limone (succo)','Lavate e asciugate il pesce. Ponete il court-bouillon in una capace casseruola, portatelo a ebollizione e mettetevi il trancio di storione. Lasciate cuocere a fuoco moderato per 15 minuti, quindi spegnete il fuoco e lasciate riposare il pesce nello stesso court-bouillon per una decina di minuti. Scolate lo storione, lasciatelo raffreddare completamente, quindi eliminate la pelle e con un coltello affilato tagliatelo a fette. Disponete le fette di pesce su un piatto di portata, conditele con l''olio e il succo di limone filtrato attraverso un colino e lasciate marinare per circa 2 ore prima di servire.',1894);
INSERT INTO "ricette" VALUES (24343,'Stormy Night','Bevande','Tequila',1,' -','5/10 Jose Cuervo Tequila,
2/10 Crema Banana De Kuyper,
1/10 Galliano,
1/10 Papaia Drink Boero,
1/10 Lemon Sour Boero Diluito,
Per Guarnire:,
Ananas,
1 Ciliegina Rossa,
1 Fetta Arancia','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella flute ben ghiacciata. Guarnire con spiedino con ananas, una ciliegina rossa, una fetta d''arancia e cannucce colorate.',442);
INSERT INTO "ricette" VALUES (24344,'Straccetti Al Vino','Carne','Manzo',4,' -','500 G Braciole Di Manzo Tagliate Piuttosto Sottili,
1 Bicchiere Vino Rosso,
1 Cespo Radicchio Di Treviso,
1 Cipolla,
Olio D''oliva,
Sale','Tagliate la carne a pezzetti e mettetela a insaporire nel vino. Tagliate la cipolla sottile e fatela appassire nell''olio d''oliva a fuoco basso coperta, in modo che non si secchi troppo. Lavate, pulite e tagliate il radicchio piuttosto fine, aggiungetelo alla cipolla e fatelo stufare per un paio di minuti. Aggiungete la carne e il vino, aggiustate di sale e fate cuocere per 10 minuti.',2195);
INSERT INTO "ricette" VALUES (24345,'Straccetti Alla Rigoletto','Carne','Straccetti',4,' -','600 G Straccetti Di Carne,
2 Limoni,
Poco Olio D''oliva Extra-vergine,
Sale,
Pepe','Mettete un filo d''olio nel tegame, fate scaldare a fuoco moderato. Mettetice li straccetti, quelli che ce capino (quelli che c''entrano) senza che li mettete uno sopra all''altro. Per cuocerli non ci vuole ne anche un minuto, una girata, una voltata, aggiungete un bel po'' di limone spremuto, salate, pepate e togliete dal fuoco. Continuate così con gli altri straccetti. M''arriccomanno (mi raccomando) dovete essere veloci, dovete aggiungere il limone quando ancora si vede il sangue, altrimenti.... la ciccia si secca.',988);
INSERT INTO "ricette" VALUES (24346,'Straccetti Con La Rucola','Carne','Manzo',6,'Luogo: Ciociaria. Luogo: Lazio.','400 G Carne Di Manzo A Fettine Sottili,
3 Pomodori Freschi,
100 G Insalata Rucola,
1 Cucchiaio Olio D''oliva Extra-vergine,
Sale','Lavate e mondate le verdure. Tagliate a dadini i pomodori e disponete la rucola su un piatto di portata. A parte scaldate una padella e fatevi saltare senza grasso la carne per qualche minuto. Posatela bollente sulla rucola e mettete al centro i pomodori a dadini. Salate e versatevi sopra l''olio senza rimestare. Servite subito.',890);
INSERT INTO "ricette" VALUES (24347,'Straccetti Di Maiale Con Insalata Di Cavoletti Di Bruxelles E Ortiche','Carne','Maiale',4,' -','200 G Arista Di Maiale,
200 G Cavolini Di Bruxelles,
300 G Ortica,
1 Spicchio Aglio,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lessare in acqua salata i cavolini e le ortiche e tenerli da parte. Tagliare la carne a fettine sottili e scottarle. Adagiarle in un piatto e nella stessa padella saltarvi le ortiche con aglio e unirvi i cavoletti. Servire ponendo gli ortaggi intorno alla carne.',1362);
INSERT INTO "ricette" VALUES (24348,'Straccetti Di Manzo Ai Pepi In Cestino Croccante E Pesto Di Rucola','Carne','Manzo',4,' -','200 G Straccetti Di Manzo,
100 G Formaggio Grana,
1 Rametto Rosmarino,
100 G Insalata Rucola,
Olio D''oliva,
Sale Grosso,
Sale,
Pepe','Grattugiare il grana su un foglio di carta oleata ed infornarlo al microonde per 3 minuti a 600 watt. Lasciarlo freddare sopra una coppetta rovesciata per formare un cestino. Scottare gli straccetti di carne in padella con olio, rosmarino e sale grosso. Lavare la rucola e condirla con olio, sale e pepe. Servirvi sopra gli straccetti, all''interno del cestino di grana.',1320);
INSERT INTO "ricette" VALUES (24349,'Straccetti Saporiti','Carne','Manzo',6,'Luogo: Ciociaria. Luogo: Lazio.','400 G Carne Di Manzo A Fettine Sottili,
3 Pomodori Freschi,
100 G Insalata Rucola,
1 Cucchiaio Olio D''oliva Extra-vergine,
Sale','Lavate e mondate le verdure. Tagliate a dadini i pomodori e disponete la rucola su un piatto di portata. A parte scaldate una padella e fatevi saltare senza grasso la carne per qualche minuto. Posatela bollente sulla rucola e mettete al centro i pomodori a dadini. Salate e versatevi sopra l''olio senza rimestare. Servite subito.',890);
INSERT INTO "ricette" VALUES (24350,'Stracchino Gelato Della Zia Marietta','Dessert','Latte',4,' -','100 Cl Latte,
Zucchero,
1 Bastoncino Vaniglia,
Poca Scorza Di Limone Grattugiata,
8 Tuorli D''uovo,
16 Fogli Colla Di Pesce,
Panna','Fate bollire un litro di latte con zucchero, un bastoncino di vaniglia e poca raschiatura di limone. Diluite in essa gli 8 tuorli e rimettetela al fuoco mescolando di continuo finché la crema sia sufficientemente densa. Ritiratela ed aggiungetevi la di colla di pesce che avrete fatto sciogliere in un po'' d''acqua. Passate questo preparato in uno staccio assai fine. Aggiungete alquanta panna sbattuta, mescolate bene e versate il composto in uno stampo che avrete collocato nel ghiaccio tritato e servite su di un tovagliolo piegato.',1800);
INSERT INTO "ricette" VALUES (24351,'Stracchino Inglese','Dessert','Panna',8,'Luogo: Regno Unito. Luogo: Inghilterra.','10 Tuorli D''uovo,
8 Cucchiai Zucchero,
Estratto Di Caffè,
100 Cl Panna,
2 Cucchiai Zucchero Di Canna,
Vaniglina','Si montano bene i tuorli con gli 8 cucchiai di zucchero, poi si unisce la vaniglia, l''estratto di caffè e la panna. Si fa caramellare in uno stampo adeguato lo zucchero grosso (di canna) e si fa in modo che ne rivesta le pareti, si versa nello stampo il composto preparato e lo si cuoce a bagnomaria: in forno a 200 gradi per un''ora. Si fa raffreddare bene prima di capovolgerlo in un piatto e di servirlo. E'' più simile, quindi, a una crema rovesciata che a un tiramisù.',5294);
INSERT INTO "ricette" VALUES (24352,'Stracci Agli Agretti','Primo','Agretti',4,' -','1/2 Fascio Agretti,
1 Scalogno,
50 G Pancetta Affumicata,
100 G Farina,
1 Uovo,
Olio D''oliva Extra-vergine,
Sale','Preparare la pasta e ricavarne dei pezzi irregolari. Rosolare lo scalogno e la pancetta a cubetti, unirvi gli agretti sbollentati e tagliuzzati. Scolare la pasta e saltarla in padella col sugo.',1461);
INSERT INTO "ricette" VALUES (24353,'Stracci Agli Astici','Primo','Astici',6,' -','350 G Pasta Tipo Stracci,
2 Astici,
1 Cipolla,
1/2 Melanzana,
1 Zucchina,
1/2 Finocchio Cotto,
3 Pomodori Perini,
1 Spicchio Aglio,
2 Gambi Prezzemolo,
Burro,
5 Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate a bastoncini di 3 cm zucchina, sedano e melanzana, lo stesso fate con i finocchi. Tritate la cipolla e cuocetela con una noce di burro. Sbollentate i bastoncini di sedano. In un tegame scaldate tre cucchiai d''olio con due gambi di prezzemolo e l''aglio, fate rosolare, togliete gli aromi, aggiungete la cipolla cotta, zucchine, melanzane, sedano e finocchi, sale e pepe. Portate tutto a cottura. Lessate gli astici 8 minuti, estraete la polpa, insaporitela alcuni minuti con i pomodori spellati e tagliati a dadini e due cucchiai d''olio. Lessate gli stracci (sono quadrati di pasta all''uovo), scolateli nella padella delle verdure, mescolate, aggiungete gli astici, servite. Vini di accompagnamento: Soave Classico DOC, Orvieto Classico DOC, Gravina DOC.',3856);
INSERT INTO "ricette" VALUES (24354,'Stracci Agli Scampi E Asparagi','Primo','Scampi',4,' -','Per La Pasta:,
200 G Farina,
2 Uova,
1 Tuorlo D''uovo,
Sale,
Per Il Piatto:,
20 Asparagi,
30 G Olio D''oliva Extra-vergine,
30 G Burro,
1 Cucchiaino Cipolla Tritata,
20 Scampi Freschi,
Sale,
Pepe,
4 Cucchiaini Sherry Secco,
1 Spicchio Aglio','Impastare la farina con le uova ed il rosso d''uovo, aggiungere sale, e continuare per 10 minuti fino a quando l''impasto è soffice ed omogeneo. Stendere la pasta e tagliarla irregolarmente in modo da ottenere gli stracci. Bollire o cuocere al vapore gli asparagi, togliere poi i gambi. Lasciare in disparte 12 punte di asparagi e tagliare il resto in piccoli pezzi. Rosolare la cipolla tritata in una padella con 1 cucchiaino d''olio e 1 cucchiaio di burro. Aggiungere gli scampi e gli asparagi tagliati, sale e pepe. Innaffiare con lo Sherry e cuocere fino a farlo evaporare. Cuocere la pasta in acqua salata fino a renderla al dente. Mentre la pasta bolle, mettere uno spicchio d''aglio e un cucchiaino d''olio nell''acqua. Scolare la pasta e metterla nella padella con gli scampi. Mantecare energicamente su fuoco alto fino a far evaporare il succo rimasto. Rimuovere dalla padella l''aglio ed aggiungere altro olio, con del brodo e il burro rimasto. Mantecare, togliere dal fuoco e servire con le punte di asparagi accantonate.',2673);
INSERT INTO "ricette" VALUES (24355,'Stracci Con Ragù Di Fave','Primo','Fave',6,' -','Per Gli Stracci (pasta):,
200 G Farina,
2 Uova,
1 Cucchiaio Olio D''oliva,
Sale,
Per Il Condimento:,
240 G Piselli E Fave Sbollentati,
12 Code Di Gambero Sgusciate,
8 Fiori Di Zucca,
1 Spicchio Aglio,
Timo,
Maggiorana,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Per la pasta: lavorate energicamente la farina con le uova, un pizzico di sale e l''olio; passate l''impasto nella macchinetta per ottenere le sfoglie che taglierete poi a rombi irregolari (stracci). Per il condimento: rosolate le code di gambero in 1 cucchiaio d''olio caldo. In una larga padella, stufate, con 2 cucchiai d''olio e aglio tritato, le fave e i piselli; unite i fiori di zucca puliti, gli stracci già lessati al dente, sale, pepe e saltate il tutto a fuoco vivo. Completate la pasta con le code di gambero, il trito aromatico di timo e maggiorana e servite subito.',2352);
INSERT INTO "ricette" VALUES (24356,'Stracci Di Antrodoco','Primo','Carne Macinata',4,'Luogo: Antrodoco. Luogo: Sabina. Luogo: Lazio.','250 G Pomodoro,
250 G Carne Macinata,
150 G Mozzarella,
3 Cucchiai Farina,
2 Uova,
Strutto,
Formaggio Pecorino Grattugiato,
Prezzemolo Tritato,
3 Cucchiai Olio D''oliva Extra-vergine,
1 Pizzico Sale','Sbattere le uova con un pizzico di sale, aggiungere la farina passata al setaccio e 3 cucchiai d''acqua. Mescolare il tutto fino ad ottenere un impasto senza grumi. Preparare delle frittatine sottili in una padella unta con lo strutto. Rosolare la carne macinata con 3 cucchiai d''olio e intanto, a parte scaldare il sugo di pomodoro. Mettere al centro di ogni frittatina un cucchiaio di carne macinata, una piccola fetta di mozzarella, una spolverata di pecorino, un cucchiaio di sugo e prezzemolo tritato. Dopo aver avvolto le frittatine come fossero dei cannelloni disporle nella teglia unta, condirle con il sugo e una spolverata di pecorino. Mettere la teglia in forno a 200 gradi per 20 minuti.',2778);
INSERT INTO "ricette" VALUES (24357,'Stracci E Salsa Di Carote','Primo','Carote',4,'Luogo: Emilia-Romagna.','Per Gli Stracci:,
250 G Farina Di Semola Di Grano Duro,
100 G Farina,
2 Tuorli D''uovo,
1 Uovo,
1 Cucchiaio Olio D''oliva,
1 Ciuffo Erba Cipollina,
1 Pizzico Sale,
Per La Salsa:,
400 G Carota,
2 Scalogni,
3 Zucchine Piccole,
1 Cucchiaio Prezzemolo Tritato,
4 Fiori Di Zucca,
60 G Ricotta Dura,
5 Cucchiai Olio D''oliva,
1 Peperoncino,
Sale,
Pepe','Setacciate insieme le 2 farine con un pizzico di sale, poi lavoratele con i tuorli, l''uovo, l''olio e, poco alla volta, 10 cl circa di acqua, fino a ottenere un impasto liscio e sodo, che farete riposare, avvolto nella pellicola, per 10 minuti. Stendere la pasta con il matterello, in sfoglie sottili. Distribuite 8-10 steli di erba cipollina su ogni sfoglia, piegatela a metà e ripassatela nei rulli per 4 volte ripiegandola a metà. Tritate finemente lo scalogno e fatelo stufare in una padella con 3 cucchiai di olio, 5 di acqua e il peperoncino. Mondate le verdure, poi grattugiate le carote e tagliate a fettine le zucchine, unitele allo scalogno e fatelo rosolare a fuoco vivace per 3 minuti, mescolando spesso, quindi salate e pepate. Private i fiori del pistillo, poi riduceteli a listarelle. Lessate la pasta e conditela subito con la salsa alle carote, il prezzemolo, i fiori, l''olio e la ricotta.',2519);
INSERT INTO "ricette" VALUES (24358,'Stracci Verdi All''astice','Primo','Astice',4,' -','Per Gli Stracci Verdi:,
250 G Farina Bianca,
50 G Spinaci Lessati E Tritati,
2 Uova,
Sale,
Per Il Condimento:,
600 G Astice,
400 G Panna Liquida,
200 G Salsa Di Pomodoro,
80 G Zucchine,
1 Spicchio Aglio,
1 Costa Sedano,
2 Carote,
1 Cipolla,
Coriandolo,
4 Fondi Di Carciofo,
2 Bicchierini Vodka,
Burro,
Sale,
Pepe','Preparate gli stracci: impastate la farina con le uova, gli spinaci, un pizzico di sale, lavorando a lungo per ottenere una pasta soda ma elastica; lasciatela riposare per 30 minuti avvolta in pellicola trasparente, poi tiratela con l''apposita macchinetta in sfoglie sottili che taglierete a quadrotti. Per il condimento, sgusciate l''astice e mettete la polpa della coda a marinare cosparsa con foglioline di coriandolo e una manciata di pepe. Fate invece rosolare, con una noce di burro e uno spicchio d''aglio, gli scarti, le chele e il carapace; aggiungete quindi una costa di sedano, una carotina e una cipolla, il tutto a tocchetti, bagnate con un bicchierino di vodka e quando questa sarà evaporata, unite la salsa di pomodoro, la panna, sale, pepe e lasciate sobbollire per circa 40 minuti, poi passate ad un colino fitto, premendo chele e scarti per farne uscire tutto l''umore possibile. Tagliate a dadini una carota, la zucchina e i fondi di carciofo; sbollentate il tutto poi rosolatelo a fuoco vivo in una noce di burro insieme con la polpa dell''astice marinata, anch''essa ridotta a dadini; insaporite con sale, una manciatina di pepe, qualche fogliolina di coriandolo, fiammeggiate con un bicchierino di vodka e, quando l''alcool sarà evaporato, unite il sugo ottenuto dagli scarti dell''astice. Lasciate leggermente addensare, poi condite gli stracci lessati al dente.',4208);
INSERT INTO "ricette" VALUES (24359,'Stracciatella','Dessert','Cioccolato',4,' -','150 G Zucchero,
300 G Latte,
200 G Panna,
1 Pizzico Vaniglina,
50 G Cioccolato Fondente','Sciogliete lo zucchero con un po'' di latte freddo; aggiungete il rimanente latte e la panna, profumate con la vaniglina e preparate il gelato. Quando il gelato sarà pronto, travasatelo in una ciotola e unite il cioccolato che avrete grattugiato non troppo finemente. Mescolate per distribuire il cioccolato in modo uniforme e servite o riponete in freezer.',1775);
INSERT INTO "ricette" VALUES (24360,'Stracciatella (2)','Primo','Uova',4,' -','2 Cespi Insalata Lattuga,
3 Uova,
100 G Formaggio Grana,
4 Fette Pane Biscottato,
75 Cl Brodo Di Dado,
Sale','Pulite la lattuga, tagliate le foglie a listarelle e lessatele nel brodo 10 minuti. Sbattete le uova, aggiungete il grana grattugiato, salate e versate il composto nel brodo mescolando con una forchetta in modo da ''stracciare'' le uova che si rapprendono. Disponete sul fondo di quattro ciotole il pane, versatevi sopra la stracciatella e servite. Vini di accompagnamento: Colli Tortonesi Cortese DOC, Bianco Di Custoza DOC, Colli Lanuvi DOC.',1522);
INSERT INTO "ricette" VALUES (24361,'Stracciatella (3)','Primo','Uova',4,' -','30 G Pangrattato,
40 G Formaggio Grattugiato,
3 Uova,
150 Cl Brodo,
1/2 Cucchiaio Prezzemolo Tritato,
Sale','In una terrina mescolate pangrattato, formaggio, uova e sale. Scaldate il brodo, versatene un mestolo sul composto, mescolate formando una cremina. Portate il brodo a bollore, versatevi la crema che tornerà a galla in una massa piuttosto unita, dividetela leggermente con i rebbi di una forchetta. Aggiungete mezzo cucchiaio di prezzemolo tritato e servite.',1088);
INSERT INTO "ricette" VALUES (24362,'Stracciatella (4)','Primo','Uova',4,'Luogo: Lazio.','200 Cl Brodo Di Carne,
4 Uova,
100 G Formaggio Parmigiano Grattugiato,
1 Grattata Noce Moscata,
Olio D''oliva Extra-vergine,
Sale,
1 Limone (scorza Grattugiata)','Versate in una scodella le uova, il parmigiano, una grattata di noce moscata e la scorza di limone grattugiata. Sbattete tutto energicamente con una forchetta o una frusta. Versate tutto nella pentola con il brodo caldo e l''olio e portare a bollore. Mescolate e agitate forte con una forchetta, formando minuscoli straccetti (la stracciatella). Lasciate ancora per altri 2 minuti a fuoco moderato e servire calda.',2233);
INSERT INTO "ricette" VALUES (24363,'Stracciatella (5)','Primo','Uova',3,'Luogo: Lazio.','2 Uova,
Poco Sale,
3 Cucchiai Formaggio,
1 Cucchiaio Pangrattato,
Noce Moscata,
100 Cl Brodo Di Carne Di Manzo','Si sbattono ben bene due uova, si aggiunge poco sale, 3 cucchiai di formaggio e 1 cucchiaio di pangrattato. Se piace l''odore di noce moscata, grattatene un po''. Quando il brodo, ben colato, bolle, vi si getta questa pastella, si agita con la forchetta, si fa cuocere pochi minuti. Minestrina sostanziosa che non sfigura ad un pranzo elegante.',909);
INSERT INTO "ricette" VALUES (24364,'Stracciatella Alla Romana','Primo','Uova',4,'Luogo: Lazio. Luogo: Roma.','100 Cl Brodo Vegetale (o Brodo Di Carne),
2 Uova,
3 Cucchiai Formaggio Parmigiano Grattugiato,
1 Pizzico Sale','Sbattete con una forchetta le uova nella terrina con un pizzico di sale e, sempre mescolando, unite il formaggio grattugiato e, poco per volta, un mestolo di brodo freddo. Mettete il brodo rimasto nella pentola, portatelo ad ebollizione su fuoco vivace, versatevi il composto e, sbattendo con una frusta metallica, portate nuovamente ad ebollizione. Lasciate bollire per due minuti, versate nella zuppiera la stracciatella e servite immediatamente.',781);
INSERT INTO "ricette" VALUES (24365,'Stracciatella Con Brodo Di Gallina','Primo','Gallina',4,'Luogo: Ciociaria. Luogo: Lazio.','Per Il Brodo:,
1 Gallina Di 1000 G,
2 Pomodori Maturi,
1 Cipolla,
2 Coste Sedano,
200 Cl Acqua,
Sale,
Per La Pasta:,
4 Uova Intere,
1 Limone (succo),
4 Cucchiai Formaggio Parmigiano Grattugiato,
1 Pizzico Sale','Pulire e lavare la gallina, eliminando il collo e la punta delle ali, e tagliarla a tocchi. Mettere in una pentola capace l''acqua con la gallina e le verdure tagliate grossolanamente. Coprire e far cuocere per un paio d''ore. Nel frattempo sbattere le uova in una zuppiera con il formaggio grattugiato, il succo di limone e un pizzico di sale. Versare il composto nel brodo bollente gi filtrato, rimescolando velocemente con la frusta, e lasciar bollire qualche minuto a fuoco moderato. Versare nella zuppiera e portare in tavola. La gallina lessata si serve come secondo piatto.',2618);
INSERT INTO "ricette" VALUES (24366,'Stracciatella Con Piselli','Primo','Piselli',4,' -','4 Uova,
25 Cl Brodo Di Carne,
2 Cucchiai Pangrattato,
4 Cucchiai Formaggio Parmigiano Grattugiato,
100 G Pasta Tipo Pastina,
150 G Piselli Sgusciati,
1 Manciata Prezzemolo Tritato,
30 G Burro,
Sale,
Pepe','Sgusciare le uova in una ciotola, unire pangrattato, parmigiano, 1 manciata di prezzemolo tritato, sale e pepe e sbattere bene con la frusta. Portare ad ebollizione il brodo e versarvi i piselli e la pastina. Quando la pasta sarà cotta, alzare la fiamma e versare il composto di uova, abbassare di nuovo il fuoco, mescolare con la frusta, unire il burro e cuocere ancora per pochi minuti.',1589);
INSERT INTO "ricette" VALUES (24367,'Stracciatella Di Insalata Lattuga','Antipasto','Insalata Lattuga',4,' -','1 Cespo Insalata Lattuga Tenera,
100 Cl Brodo,
30 G Burro,
2 Uova,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
Alcuni Crostini Di Pane Tostati In Forno','Tagliare le foglie più tenere della lattuga in striscette e rosolarle nel burro per 10 minuti. Sbattere le uova con un po'' di pepe, sale e il formaggio. Portare ad ebollizione il brodo, versarvi la lattuga e dopo 5 minuti le uova sbattendo con una frusta per 2 minuti. Servire con i crostini.',1374);
INSERT INTO "ricette" VALUES (24368,'Stracciatella Di Riso, Vongole E Gamberetti','Primo','Vongole',4,' -','100 Cl Brodo,
2 Uova,
50 G Vongole,
100 G Gamberetti,
150 G Riso,
Prezzemolo Tritato,
Formaggio Parmigiano,
1/2 Bicchiere Vino Bianco','Fate cuocere il riso nel brodo. Dopo 10 minuti mettete le vongole surgelate, dopo 15 minuti i gamberetti e dopo 17 minuti le uova sbattute, il prezzemolo tritato e il vino bianco. Servite subito e volendo spolverate con il parmigiano grattugiato.',1657);
INSERT INTO "ricette" VALUES (24369,'Stracciatella In Crosta','Antipasto','Funghi Misti',4,'Preparazione: 25 minuti. Cottura: 35 minuti.','3 Uova,
1 Tuorlo D''uovo,
Abbondante Noce Moscata Grattugiata,
Prezzemolo Tritato,
400 G Funghi Misti,
450 G Pasta Sfoglia Pronta Già Stesa,
Burro,
3 Cucchiai Formaggio Grana Grattugiato,
2 Cucchiai Semolino,
100 Cl Brodo Di Carne,
Sale,
Pepe','Mondate i funghi privandoli della parte terrosa, affettateli e cuoceteli in padella per circa 15 minuti con 40 g di burro; salate e pepate. Sgusciate 3 uova in una ciotola, unite il formaggio, il semolino, sale, pepe, abbondante noce moscata grattugiata e prezzemolo tritato; sbattete con una forchetta. In una casseruola portate il brodo a ebollizione, versatevi il composto di uova, abbassate la fiamma, mescolate con una frusta e cuocete per qualche istante. Aggiungete i funghi, mescolate e distribuite la stracciatella in 4 zuppierine o ciotole che possano passare in forno. Pennellate i bordi delle zuppierine con il tuorlo. Ritagliate nella pasta sfoglia 4 dischi leggermente più larghi delle zuppierine e posateli sopra, premendo delicatamente i bordi; spennellate con il tuorlo anche la superficie della pasta. Passate in forno già a 200 gradi per circa 15 minuti; aspettate qualche minuto prima di servire. La crosta di pasta potrà essere gustata tagliata a pezzetti (come fossero crostini) insieme alla stracciatella.',3692);
INSERT INTO "ricette" VALUES (24370,'Stracotto All''italiana','Carne','Manzo',8,' -','1500 G Carne Di Manzo,
4 Carote,
3 Cipolle,
1 Spicchio Aglio,
100 Cl Vino Rosso,
1000 G Pomodoro,
10 Carote Rotonde,
1 Mazzo Cipolline Fresche,
150 G Olive Nere,
250 G Funghi,
Sale,
Pepe,
Timo,
Alloro,
Brandy','Il giorno prima mettete la carne nel vino rosso con le carote tagliate, le cipolline tagliate e un po'' d''aglio; girate di tanto in tanto la carne. Il giorno successivo fondete in una teglia burro e olio e aggiungete la carne con un pochino di cipolle e l''aglio, ma non il composto della macerazione. Quando la carne è rosolata fate fiammeggiare con il brandy e poi versateci sopra il composto della macerazione. Lasciate cuocere per 2 ore. Intanto tagliate a pezzi i pomodori e metteteli in un tegame con le cipolline fresche, le carote rotonde, i funghi, le olive, il timo e l''alloro. Lasciate cuocere per 2 ore e poi aggiungete questo composto alla carne, lasciandolo cuocere per un''ulteriore ora.',3813);
INSERT INTO "ricette" VALUES (24371,'Stracotto Con I Funghi','Carne','Manzo',4,' -','1000 G Carne Di Manzo (girello),
30 G Lardo (o Prosciutto Cotto Grasso),
20 G Burro,
25 G Funghi Secchi,
1 Spicchio Aglio,
1 Cipolla,
1 Carota,
1 Costa Sedano,
1 Manciata Prezzemolo,
50 Cl Brodo,
5 Cucchiai Salsa Di Pomodoro Casalinga,
Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Ammollate i funghetti in acqua fredda. Mondate il prezzemolo e tritatelo con lo spicchio di aglio. Steccate il pezzo di carne con il lardo o il prosciutto tagliato a bastoncini e legatelo con uno spago sottile. Fate rotolare il girello nel trito di prezzemolo ed aglio. Tritate la cipolla con la carota e il sedano, versate il trito in una casseruola con qualche cucchiaiata di olio e il burro; quando le verdure si saranno ben appassite appoggiatevi sopra il pezzo di carne, salatelo, pepatelo e fatelo rosolare bene da ogni parte, rigirandolo. Dopo di che spruzzatelo con mezzo bicchiere di vino bianco che farete evaporare. Aggiungetevi infine la salsina di pomodoro diluita con 40 cl di brodo. Scoperchiate e cuocete, a fuoco lento per circa 2 ore e 1/2. A metà cottura unitevi i funghi tritati. Aggiungete durante la cottura, a mano a mano che il sughetto ispessisce dell''altro brodo caldo. Disponete lo stufato affettato sul piatto e cospargetelo con il sughetto di funghi passato al setaccio.',2702);
INSERT INTO "ricette" VALUES (24372,'Stracotto D''asino','Carne','Asino',4,' -','800 G Carne D''asino,
50 G Burro,
50 G Lardo,
1/2 Cipolla,
1 Costa Sedano,
1 Carota,
2 Spicchi Aglio,
2 Cucchiai Salsa Di Pomodoro,
1 Cucchiaino Estratto Di Carne','Tagliare gli spicchi d''aglio in filetti e infilarli in piccoli tagli praticati nella carne. Mettere in una pentola il burro e le verdure precedentemente tritate insieme al lardo, e farli soffriggere per pochi minuti, quindi aggiungere la carne e farla ben rosolare rigirandola spesso; bagnare con qualche mestolino d''acqua calda in cui si sarà sciolto l''estratto di carne e la salsa di pomodoro. Coprire la pentola e, a fuoco molto lento, portare a cottura la carne, rigirandola di tanto in tanto e bagnandola, quando occorre,con qualche mestolino d''acqua calda. A metà cottura, salare e pepare a piacere. Per avere un ottimo stracotto occorre che la che la fiamma sia bassissima e che la carne resti al fuoco per almeno quattro ore: come risultato si avrà una carne tenera, gustosissima e un intingolo vellutato come una crema. Va servito tagliato a grosse fette cosparse del loro sugo; buono l''accompagnamento di verdura fresca in insalata quali radicchi rossi, lattuga, ecc.',1783);
INSERT INTO "ricette" VALUES (24373,'Stracotto D''oca','Pollame','Oca',8,' -','1 Oca Di 3000 G,
Alcune Fettine Pancetta,
1 Bottiglia Vino Bianco Secco,
2 Bicchieri Aceto Di Vino,
Brodo,
2 Cipolle,
1 Foglia Alloro,
1 Pizzico Maggiorana,
1 Pizzico Rosmarino,
2 Cucchiai Olio D''oliva,
Sale,
Alcuni Grani Pepe,
Per La Salsa:,
2 Limoni,
2 Acciughe,
Burro','Fasciate l''oca con le fettine di pancetta, adagiatela sulla griglia del forno e cuocetela per un''ora e mezzo in forno preriscaldato a 190 gradi. Ritiratela, eliminate la pancetta, sistemate il volatile in una pentola su misura con due cucchiai d''olio. Versate vino, aceto e brodo fino a coprirlo. Aggiungete alcuni grani di pepe, l''alloro e le cipolle intere, un pizzico di maggiorana e di rosmarino tritati e salate. Cuocete ancora per un''ora sul fornello a fuoco basso, poi togliete l''oca dal recipiente e tenetela al caldo. Preparate la salsa. Unite al fondo di cottura la polpa a dadini di un limone sbucciato al vivo, le acciughe dissalate, diliscate e tritate. Mescolate, ritirate dal fuoco e mantecate il composto con una noce di burro. Disponete l''oca tagliata a fette su un piatto da portata. Ricopritela con la salsa e guarnitela con l''altro limone a fettine. Vini di accompagnamento: Bricco Manzoni VdT Del Piemonte, Tazzelenghe VdT Del Friuli, Salice Salentino Rosso DOC.',4583);
INSERT INTO "ricette" VALUES (24374,'Stracotto Di Manzo Al Barolo','Carne','Manzo',6,' -','1000 G Carne Di Manzo Magra (coscia),
Prezzemolo,
Salvia,
Aglio,
Cipolla,
Carota,
Sedano,
Poca Farina,
1 Bottiglia Vino Barolo,
Olio D''oliva,
Poco Burro,
Noce Moscata,
Sale,
Pepe','Ponete nella casseruola qualche cucchiaiata di burro, olio e cipolla affettata. Soffriggete questi ingredienti, poi sistematevi la carne dopo averla passata nella farina, spolverizzatela con prezzemolo, aglio, rosmarino e il resto delle verdure tritate. Fate dorare la carne da tutte le parti, quindi bagnate con il Barolo. Fate evaporare quindi salate e pepate. Proseguite poi la cottura per circa tre ore a recipiente coperto. Servite la carne a fette coprendola con il suo sugo, ben denso passato prima al setaccio.',3000);
INSERT INTO "ricette" VALUES (24375,'Stracotto Di Manzo Alla Fiorentina','Carne','Manzo',6,'Luogo: Toscana. Luogo: Firenze.','1000 G Polpa Di Manzo,
40 G Pancetta,
4 Cucchiai Olio D''oliva,
1 Bicchiere Vino Rosso,
500 G Pomodori,
2 Carote,
1/2 Cipolla,
1 Costa Sedano,
Sale,
Pepe','Steccate la carne con alcuni bastoncini di carota e pezzetti di pancetta; strofinatela con sale e pepe; legatela con lo spago bianco da cucina. Mettetela in una casseruola con l''olio, due o tre carote tagliate a pezzi, sedano e cipolla grossolanamente tritati. Iniziate la cottura a fuoco vivo e fate colorire per bene da tutte le parti. Bagnatela con il vino e lasciate evaporare. Aggiungete i pomodori a pezzi, spellati e senza semi. Coprite e cuocete piano piano per circa 2 ore. Slegate la carne, tagliatela a fette, disponetele sul piatto da portata. Copritele con il sugo e le verdure passati al mulinetto. Vini di accompagnamento: Valpolicella Superiore DOC, Chianti Chianti Classico Riserva DOCG, Don Pietro Rosso VdT Di Sicilia.',2930);
INSERT INTO "ricette" VALUES (24376,'Stracotto Di Manzo Alla Montanara','Carne','Manzo',4,' -','1000 G Carne Di Manzo Abbastanza Magra,
2 Cipolle Grandi,
2 Spicchi Aglio,
5 Pomodori,
1 Ciuffo Prezzemolo,
2 Foglie Alloro,
Timo,
Dragoncello','Scaldare una casseruola, di cui la carne non occupi più di 2/3 della capacità, fino a raggiungere il giusto grado di calore; sistemare la carne, indorarla da tutte le parti, ridurre la fiamma al minimo e unirvi i pomodori finemente triturati, le cipolle tagliate ad anelli, gli spicchi d''aglio interi, il prezzemolo, il timo e il dragoncello; salare e pepare quanto basta. Chiudere con il coperchio e lasciare cuocere per circa un''ora e mezza; controllare di tanto in tanto ed eventualmente aggiungere un mestolo d''acqua.',1289);
INSERT INTO "ricette" VALUES (24377,'Stracotto Di Manzo Romagnolo','Carne','Manzo',4,'Luogo: Emilia-Romagna.','1000 G Polpa Di Manzo,
50 G Lardo Di Maiale,
Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
2 Bicchieri Vino Rosso,
2 Chiodi Di Garofano,
3 Foglie Alloro,
Noce Moscata,
1/2 Cucchiaio Conserva Di Pomodoro,
1 Cipolla,
1 Mestolo Brodo Di Manzo,
Burro,
Sale','In una pignatta soffriggere cipolla tritata e aglio in olio e lardo pestato; sistemarvi la carne salata all''esterno. Unire 3/4 del vino, chiodi di garofano, alloro, noce moscata; far evaporare metà vino a fuoco vivo. Unire 1 mestolo di brodo con 1/2 cucchiaio di conserva. Coprire con un piatto fondo contenente il restante vino e cuocere per 6 ore.',3311);
INSERT INTO "ricette" VALUES (24378,'Stracotto Di Struzzo','Pollame','Struzzo',4,' -','500 G Muscolo Di Struzzo,
200 G Conserva Di Pomodoro,
50 Cl Vino Bianco,
50 Cl Brodo Vegetale,
2 Carote,
Sedano,
Cipolla,
Aromi,
7 Cucchiai Olio D''oliva,
Farina,
Sale,
Pepe','Raccogliete gli aromi (alloro, chiodi garofano, salvia e rosmarino, bacche di ginepro, cannella, noce moscata) in un sacchetto di garza molto sottile e chiudetelo bene alla sommità. Tritate finemente carote, sedano e cipolla, metteteli in un tegame a bordi alti, aggiungete 4 cucchiai d''olio e fate soffriggere a fiamma moderata. Tagliate la carne in 16 grandi cubi e infarinateli. In un tegame scaldate tre cucchiai d''olio e rosolatevi la carne. Passate i cubi nel recipiente del soffritto, aggiungete il vino, il brodo vegetale, la conserva di pomodoro, il sacchetto degli aromi, sale e pepe. Coprite e cuocete a fuoco moderato per 40 minuti. Vini di accompagnamento: Roero Superiore DOC, Rosso Conero DOC, Lizzano Rosso DOC.',2761);
INSERT INTO "ricette" VALUES (24379,'Stracotto Di Tonno','Pesce','Tonno',4,' -','1 Trancio Di Tonno Da 600 G,
50 Cl Vino Bianco,
2 Carote,
4 Pomodori,
1 Costa Sedano,
1 Cipolla,
Salvia,
Rosmarino,
Alcune Fettine Limone,
Prezzemolo,
Sale Grosso,
Olio D''oliva','Sciacquare bene il pesce e legarlo con uno spago, punzecchiarlo e metterlo con le verdure tagliate a pezzetti. Unire gli aromi, qualche fettina di limone e bagnare con il vino, lasciando marinare per 4 ore. Togliere il limone, mettere in pentola, unire sale grosso e portare a bollore per 30 minuti circa, girandolo ogni tanto. Togliere il pesce, far ridurre il sugo, frullarlo e unire l''olio. Servire il pesce a fette con il suo sugo.',2480);
INSERT INTO "ricette" VALUES (24380,'Stracotto Di Vitello Con Frutti Di Sottobosco','Carne','Vitello',4,' -','800 G Vitello,
2 Funghi Freschi,
50 G Prosciutto Crudo Tritato,
1 Gambo Sedano,
1 Carota,
1/2 Cipolla,
2 Pomodori Tagliati A Spicchi,
Mirtilli (o Lamponi),
Sale,
Pepe','In una casseruola di cui il pezzo di carne non occupi più di 2/3 della capacità e portata al giusto grado di calore, rosolare la carne da entrambe le parti; aggiungere i funghi, il prosciutto, il sedano, la carota, la cipolla ed i pomodori, il tutto triturato finemente. Aggiungervi 2 mestoli di acqua e chiudere con il coperchio. Lasciare cuocere per circa 2 ore. Al momento di servire, unire i mirtilli o i lamponi finemente passati assieme al sugo di cottura.',1079);
INSERT INTO "ricette" VALUES (24381,'Strangolapreti','Primo','Spinaci',4,'Luogo: Emilia-Romagna.','300 G Pane Raffermo,
1 Bicchiere Latte,
3 Uova,
300 G Spinaci Lessati E Tritati,
3 Cucchiai Farina Bianca 0,
Sale,
Formaggio Parmigiano Grattugiato,
Burro Fuso,
1 Pizzico Pepe Nero','Bagnare 300 g di pane raffermo spezzettato in 1 bicchiere di latte, strizzarlo bene e passarlo al passaverdure. Unirvi 3 uova, 300 g di spinaci lessati, scolati e tritati e mescolarvi 3 cucchiai di farina bianca 0. Aggiustare di sale e far riposare a lungo. Da questo impasto ricavare tanti gnocchetti che saranno bolliti in acqua salata, scolati e conditi con parmigiano grattugiato, burro fuso e un pizzico di pepe nero.',2546);
INSERT INTO "ricette" VALUES (24382,'Strangolapreti (2)','Primo','Patate',4,'Luogo: Calabria.','1000 G Patate,
200 G Farina,
70 G Formaggio Pecorino Grattugiato,
Sugo D''agnello (o Ragù Di Maiale),
Sale','Fate lessare a meta le patate in acqua salata, sgocciolatele, pelatele e passatele al passatutto raccogliendone la purea sulla spianatoia cosparsa di farina. Incorporatevi la farina fino ad ottenerne un impasto morbido. Dividetelo in pezzi e con le palme delle mani infarinate formate dei bastoncini del diametro di due centimetri e mezzo, tagliateli trasversalmente in pezzi lunghi tre centimetri e mezzo e incavateli via via leggermente con le dita. Allineateli su un canovaccio cosparso di farina evitando che si tocchino. Gettateli in un''ampia pentola con abbondante acqua leggermente salata e bollente e quando vengono a galla tirateli col mestolo bucherellato sgocciolandoli bene, metteteli in un piatto da portata concavo, cospargeteli di una parte del pecorino grattugiato e di una parte della salsa e mescolate. Fate le porzioni individuali, passando il resto del formaggio e della salsa',1930);
INSERT INTO "ricette" VALUES (24383,'Strangolapreti Agli Spinaci','Primo','Spinaci',4,'Preparazione: 90 minuti.','1000 G Spinaci,
200 G Pane Raffermo,
2 Uova,
4 Cucchiai Farina,
1 Cipolla,
60 G Burro,
Alcune Foglie Salvia,
Formaggio Parmigiano Grattugiato,
Latte,
Sale,
Pepe','Tagliate a pezzi il pane, mettetelo in una ciotola, copritelo a filo con del latte e lasciatelo ammorbidire. Mondate gli spinaci e lessateli con la sola acqua del lavaggio e una presa di sale, quindi strizzateli bene, tritateli e trasferiteli in una ciotola. Unite il pane, ben strizzato e passato al passaverdure, la farina e le uova, sbattute con una presa di sale e pepe a piacere, e mescolate bene. Versate il composto a cucchiaiate in una casseruola contenente acqua bollente salata e cuocete gli gnocchi finché saliranno a galla. Conditeli infine con il burro, in cui avrete rosolato la cipolla tritata e la salvia, e parmigiano a piacere e servite. Gli strangolapreti tradizionali, tipici dell''emilia romagna, non hanno nell''impasto gli spinaci e vengono conditi anche in altri modi, ad esempio con ragù di salsiccia o sugo ai funghi porcini.',2092);
INSERT INTO "ricette" VALUES (24384,'Strangolapreti Rustici','Primo','Pomodori Pelati',4,'Luogo: Cervaro. Luogo: Ciociaria. Luogo: Lazio.','1000 G Pasta Tipo Strangolapreti,
1 Cipolla,
2 Coste Sedano,
1 Carota,
2 Spicchi Aglio,
1 Cucchiaio Prezzemolo E Basilico Tritati,
Burro,
Olio D''oliva,
1 Scatola Pomodori Pelati (scatole Di 450 G),
3 Fette Salame Cotto (fette Di 50 G),
100 G Fegatini Di Pollo,
Alcune Foglie Salvia,
Sale,
Pepe','Mondate, lavate e tritate la cipolla, il sedano, la carota e gli spicchi d''aglio: mettete il trito in una casseruola larga e bassa, unite il prezzemolo e il basilico pure tritati, 30 g di burro e due cucchiai di olio; fate rosolare a fiamma bassa, rimestando spesso, fino a quando le verdure saranno ben stufate. Aggiungete, quindi, i pelati pasati al setaccio o il passato di pomodoro, mescolando bene. Salate, pepate e fate cuocere, molto piano, per circa 40 minuti a recipiente coperto, unendo, se occorre, poca acqua calda. Passate, quindi, la salsa al setaccio, rimettetela nella casseruola e unite il salame cotto tagliato a dadini. Mescolate bene. Nel frattempo avrete messo sul fuoco l''acqua per la cottura degli strangolapreti. Appena bolle, salatela e buttatevi gli strangolapreti, scolandoli con una schiumarola non appena verrano a galla. In questi pochi minuti, lavate e tritate i fegatini e fateli saltare con una noce di burro, qualche foglia di salvia, sale e pepe. Scolate gli strangolapreti, metteteli in una zuppiera e conditeli con il sugo e con i fegatini, mescolando bene.',5813);
INSERT INTO "ricette" VALUES (24385,'Strangolapreti Su Crema Di Gorgonzola Al Mascarpone','Primo','Formaggio Gorgonzola',4,' -','200 G Mollica Di Pane,
Latte,
100 G Formaggio Gorgonzola Al Mascarpone,
40 G Burro,
30 G Formaggio Grana,
Olio D''oliva,
Sale','Bagnare i cubi di pane col latte; sbollentare gli spinaci, scolarli, strizzarli e frullarli assieme al pane ammollato ed ad 1 uovo ottenendo un impasto denso. Ricavare degli gnocchi (strangolapreti trentini) e cuocerli in acqua bollente salata. Sciogliere a bagnomaria il gorgonzola al mascarpone e servirlo sul piatto di servizio, a specchio. Sopra gli strangolapreti scolati e spadellati con burro e grana grattugiato.',2078);
INSERT INTO "ricette" VALUES (24386,'Strangozzi Al Tartufo Nero','Primo','Tartufi Neri',6,' -','500 G Pasta Tipo Strangozzi,
100 G Olio D''oliva Extra-vergine,
100 G Tartufi Interi Puliti Dalla Terra E Lavati O Tartufo In Fettine O In Paté,
1 Spicchio Aglio,
1 Acciuga Diliscata,
Sale,
Pepe','Per preparare la salsa scaldare in un tegame largo l''olio, l''aglio e l''acciuga a pezzetti, mescolando finché non si sarà completamente disciolta, ritirare dal fuoco non appena l''aglio sarà dorato, togliere l''aglio, attendere che l''olio si raffreddi un poco e unire i tartufi grattugiati o tritati. Salare e pepare. Scolare gli strangozzi al dente, metterli nel tegame della salsa appena preparata e saltarli un minuto a fuoco vivace.',2630);
INSERT INTO "ricette" VALUES (24387,'Strangozzi Alla Norcina','Primo','Salsicce Di Maiale',4,'Luogo: Umbria. Luogo: Norcia.','500 G Farina,
25 Cl Acqua,
2 Salsicce Di Maiale,
1 Spicchio Aglio,
4 Cucchiai Latte,
2 Cucchiai Panna,
1 Cucchiaino Farina,
Olio D''oliva Extra-vergine,
Sale','Spellare le salsicce e sbriciolarle in padella; rosolarle con aglio schiacciato. A doratura avveuta spolverare di farina, aggiungere latte e panna, cuocere per 5 minuti e condirvi la pasta precedentemente preparata tagliandola a strisce sottili.',3244);
INSERT INTO "ricette" VALUES (24388,'Stranguglia Prieviti','Primo','Patate',4,'Luogo: Calabria.','1000 G Patate,
200 G Farina,
70 G Formaggio Pecorino Grattugiato,
Sugo D''agnello (o Ragù Di Maiale),
Sale','Fate lessare a meta le patate in acqua salata, sgocciolatele, pelatele e passatele al passatutto raccogliendone la purea sulla spianatoia cosparsa di farina. Incorporatevi la farina fino ad ottenerne un impasto morbido. Dividetelo in pezzi e con le palme delle mani infarinate formate dei bastoncini del diametro di due centimetri e mezzo, tagliateli trasversalmente in pezzi lunghi tre centimetri e mezzo e incavateli via via leggermente con le dita. Allineateli su un canovaccio cosparso di farina evitando che si tocchino. Gettateli in un''ampia pentola con abbondante acqua leggermente salata e bollente e quando vengono a galla tirateli col mestolo bucherellato sgocciolandoli bene, metteteli in un piatto da portata concavo, cospargeteli di una parte del pecorino grattugiato e di una parte della salsa e mescolate. Fate le porzioni individuali, passando il resto del formaggio e della salsa.',1930);
INSERT INTO "ricette" VALUES (24389,'Strauben','Dessert','Latte',4,' -','200 G Farina,
2 Cucchiai Burro,
25 Cl Latte,
2 Uova,
2 Cl Grappa,
Sale,
Olio Per Friggere,
Per Servire:,
Zucchero A Velo,
Panna Montata (o Mirtilli Rossi O Frutta Cotta)','Salare il latte tiepido e mescolate prima la farina e dopo i rossi d''uova e la grappa. Montare il chiaro d''uova ed aggiungerlo lentamente. Una volta ottenuto l''impasto, va fritto passandolo da un imbuto e versandolo direttamente nell''olio bollente formando una spirale rotonda, grande come un piatto. Quando ha preso colore su tutte e due le parti servirla con zucchero a velo e a seconda dei gusti con panna montata, mirtilli rossi o frutta cotta.',2522);
INSERT INTO "ricette" VALUES (24390,'Strawberry','Bevande','Cachaca',1,' -','4/10 Cachaca Nuga Ful,
4/10 Fragole Frullate,
1/10 Succo Di Limone,
1/10 Zucchero Semolato,
Per Guarnire:,
1 Fragola','Si prepara nello shaker con molto ghiaccio. Agitare vigorosamente e servire nel bicchiere old fashioned con ghiaccio pilè. Guarnire con una fragola intera sul bordo del bicchiere e due cannucce corte.',119);
INSERT INTO "ricette" VALUES (24391,'Strawberry Colada','Bevande','Rum',1,' -','8/15 Succo D''ananas,
3/15 Crema Di Cocco,
6 Fragole Mature,
2/15 Rum Bianco,
2/15 Rum Scuro,
Per Guarnire:,
1 Fetta Ananas,
1 Ciliegia Al Maraschino','Mettere tutti gli ingredienti nel mescolatore. Mescolare bene ad alta velocità. Mettere il composto ottenuto in un bicchiere Collins. Guarnire con la fetta d''ananas e la ciliegina al maraschino.',232);
INSERT INTO "ricette" VALUES (24392,'Strawberry Drink ''95','Bevande','Vodka',1,' -','1/5 Cordial Campari,
2/5 Crema Banana De Kuyper,
3/5 Vodka Smirnoff,
2 G Fragola Drink Boero,
Per Guarnire:,
1 Fragola,
1 Foglia Menta','Si prepara nello shaker con ghiaccio. Servire nella coppetta da cocktail ben fredda. Guarnire con una fragola e una foglia di menta.',427);
INSERT INTO "ricette" VALUES (24393,'Strawberry Margarita','Bevande','Schnapps',1,' -','1/6 Schnapps Alle Fragole,
2/6 Tequila,
1/6 Triple Sec,
2/6 Succo Di Limone,
Sale','Strofinare il bordo di un bicchiere da cocktail prima con il succo di limone e poi con il sale. Mescolare schnapps, tequila, triple sec, succo di limone con ghiaccio e servire.',245);
INSERT INTO "ricette" VALUES (24394,'Strawberry Sunrise','Bevande','Schnapps',1,' -','4/5 Schnapps Alle Fragole,
Succo D''arancia,
1/5 Granatina,
1 Fragola','Mettere schnapps e granatina in un bicchiere Highball sopra cubetti di ghiaccio. Completare con succo d''arancia e agitare. Aggiungere la fragola e servire.',280);
INSERT INTO "ricette" VALUES (24395,'Strike','Bevande','Tequila',1,' -','1/4 Crema De Cassis,
3/4 Tequila,
Per Servire:,
1 Fetta Limone,
1 Ciliegia','Preparare direttamente nel gotto basso già pieno di ghiaccio tritato. Servire con una fetta di limone e una ciliegia.',536);
INSERT INTO "ricette" VALUES (24396,'Striole','Dessert','Farina Bianca',4,'Luogo: Vico Nel Lazio. Luogo: Ciociaria. Luogo: Lazio.','500 G Farina Bianca,
Olio Per Friggere,
50 G Zucchero','Impastare la farina con l''acqua in una terrina fino ad ottenere un composto semifluido. Far riscaldare l''olio in una padella e versarci, un cucchiaio per volta, la pastella. Quando è ben colorita, toglierla dal fuoco e spolverizzare con lo zucchero.',2496);
INSERT INTO "ricette" VALUES (24397,'Strip','Bevande','Gin',1,' -','1/4 Calvados,
3/4 Gin,
1 Cucchiaio Succo Di Limone,
1 Spruzzo Granatina,
Per Servire:,
1 Scorza Di Limone','Agitare nello shaker con poco ghiaccio in cubetti. Servire nel tumbler stretto, con una scorza di limone.',354);
INSERT INTO "ricette" VALUES (24398,'Strisce Di Peperone In Salsina','Contorno','Peperoni',6,' -','3 Peperoni Carnosi,
1 Bicchiere Olio D''oliva,
3 Spicchi Aglio,
1 Mazzetto Prezzemolo,
Pepe Macinato,
Pepe In Grani,
Sale','Abbrustolite i peperoni interi sulla fiamma per una ventina di minuti, in modo da poterli spellare facilmente. Apriteli, puliteli e tagliateli a listerelle. Preparate una salsina con 1 bicchiere d''olio, un trito finissimo di aglio e prezzemolo, sale e pepe: emulsionatela bene. Stendete le strisce di peperone in una piccola terrina e versatevi sopra la salsina. Spargete alcuni grani di pepe nero e lasciate in infusione, prima di consumare, almeno una giornata.',1448);
INSERT INTO "ricette" VALUES (24399,'Striscioline Di Vitello','Carne','Vitello',4,' -','400 G Fettine Di Vitello,
1 Cipolla,
Vino Marsala,
Burro,
Prezzemolo Tritato,
Sale','Tagliare a striscioline di 2 cm di larghezza la carne. Tritare la cipolla e soffriggerla nel burro poi aggiungere la carne e farla saltare a fuoco vivo. Bagnare con il marsala, farlo evaporare poi salare le striscioline. Abbassare la fiamma e cuocere per circa 15 minuti. Prima di servire guarnire con il prezzemolo.',1279);
INSERT INTO "ricette" VALUES (24400,'Strong Bronx','Bevande','Gin',1,' -','6/10 Gin,
2/10 Succo D''arancia,
1/10 Vermouth Dry,
1/10 Vermouth Dolce','Agitate bene con ghiaccio e versate in un bicchiere da cocktail già freddo.',266);
INSERT INTO "ricette" VALUES (24401,'Strozzapetri Con Ragù Di Salsiccia, Melanzane E Basilico','Primo','Salsiccia',4,' -','2 Uova,
200 G Farina,
1 Salsiccia,
100 G Melanzana,
Basilico Fresco,
Olio D''oliva,
Sale','Stendere la sfoglia di acqua e farina e tirare la sfoglia ricavarne degli strozzapreti passando i pezzetti di pasta tra le mani. Cuocerli in acqua bollente salata. Nel frattempo rosolare in olio la polpa della salsiccia, privata del budello, unire le melanzane a cubetti e portare il ragù a cottura in 10 minuti. Profumare con basilico fresco e mantecarvi la pasta scolata al dente.',1914);
INSERT INTO "ricette" VALUES (24402,'Strozzapreti Al Pomodoro','Primo','Salsa Di Pomodoro',4,' -','500 G Bietole,
400 G Ricotta,
2 Uova,
100 G Formaggio Grana Grattugiato,
4 Cucchiai Farina,
2 Cucchiai Panna,
1 Tazza Salsa Di Pomodoro,
Noce Moscata,
Olio D''oliva,
Sale,
Pepe','Lessare le bietole, tritarle e asciugarle in padella. Mescolarvi la ricotta, il grana, le uova e la farina ottenendo un impasto morbido. Salare, pepare e unire un po'' di noce moscata. Ricavarne tante palline e far riposare per 1 ora. Lessare in acqua salata per 10 minuti. Condire con olio e servire con la salsa di pomodoro diluita con la panna.',2270);
INSERT INTO "ricette" VALUES (24403,'Strozzapreti Al Radicchio','Primo','Radicchio',4,' -','4 Cipolle,
5 Radicchi Rossi Trevigiani Di Medie Dimensioni,
Aceto Balsamico,
1 Cucchiaio Curry Molto Profumato,
20 Cl Panna,
Sale,
Pepe,
Olio D''oliva Extra-vergine,
1000 G Pasta Tipo Strozzapreti Freschi','Tritare abbastanza finemente la cipolla e rosolarla nell''olio. Quando la cipolla diventa trasparente aggiungere il radicchio tritato grossolanamente e proseguire la cottura. A cottura quasi ultimata spruzzare con aceto balsamico (1/2 bicchiere circa) e farlo asciugare completamente. Salare, unire il curry, la panna e la pasta cotta al dente e ben scolata. Saltare per alcuni minuti e servire.',5240);
INSERT INTO "ricette" VALUES (24404,'Strozzapreti Al Sugo Di Canocchie','Primo','Canocchie',6,'Luogo: Emilia-Romagna.','500 G Pasta Tipo Strozzapreti,
800 G Canocchie,
6 Pomodori Grandi Maturi E Sodi,
2 Scalogni,
1 Pizzico Peperoncino,
Alcune Foglie Basilico Fresco,
Olio D''oliva,
Vino Bianco,
Sale','Gli strozzapreti sono un tipo di pasta caratteristico della cucina romagnola: pare che i parroci della riviera adriatica ne fossero talmente ghiotti da rischiare di rimanere strozzati dalla troppa voracità con cui ne mangiavano. Si prestano a svariati condimenti, ma la loro morte migliore è con sughi di pesce o con un buon ragù. Quasi obbligatorio l''abbinamento di questa versione con un Albana di Romagna o con un Trebbiano fermo. Se amate impastare potete preparare gli strozzapreti con circa 500 grammi di farina di grano duro, sale e acqua tiepida quanto basta. Impastate il tutto sino ad ottenere una pasta soda ed elastica, che stenderete sottile sulla spianatoia dopo averla lasciata riposare per circa mezz''ora. Ritagliate dei rettangoli di circa cm. 3 per 2, ed arrotolateli a sigaretta in diagonale, ottenendo una sorta di maccheroncino. Tagliate la canocchie in due o tre pezzi (secondo la dimensione), conservandone alcune intere per guarnire il piatto. In una larga padella fate imbiondire leggermente lo scalogno tritato con il peperoncino, quindi aggiungete le canocchie e cuocete per alcuni minuti rivoltandole delicatamente. Aggiungete un bicchiere di buon vino bianco e fate cuocere fino a che l''alcool sarà evaporato. Aggiungete a questo punto i pomodori preventivamente pelati, privati dai semi e grossolanamente tritati, e fate cuocere mescolando delicatamente per non più di dieci minuti. Nel frattempo cuocete gli strozzapreti in abbondante acqua salata, scolateli e conditeli con il sugo cui avrete aggiunto all''ultimo alcune foglie di basilico fresco. Guarnite il piatto di portata con le canocchie che avrete conservato intere e servite ben caldo.',3637);
INSERT INTO "ricette" VALUES (24405,'Strozzapreti Al Tartufo Nero','Primo','Tartufo Nero',4,'Luogo: Umbria. Luogo: Norcia.','350 G Pasta Tipo Strozzapreti,
100 G Tartufo Nero Di Norcia,
Olio D''oliva Extra-vergine Umbro,
20 G Burro,
Aglio,
Sale','Pulire adeguatamente il tartufo e grattugiarlo. Farlo brasare a fuoco basso nell''olio con uno spicchio d''aglio in camicia e un pizzico di sale per circa 10 minuti. A parte cuocere la pasta; a cottura ultimata scolarla bene e mescolarvi il burro. Condire quindi con l''intingolo di tartufo.',2184);
INSERT INTO "ricette" VALUES (24406,'Strozzapreti Alle Acciughe','Primo','Acciughe',4,' -','180 G Strozzapreti,
1 Cucchiaio Capperi Sotto Sale,
1/2 Cipolla,
1 Scalogno Piccolo,
1 Ciuffo Basilico,
1 Ciuffo Prezzemolo,
4 Filetti D''acciughe Sott''olio,
1 Spicchio Aglio,
Olio D''oliva,
Sale,
Pepe','Fate cuocere cipolla e scalogno in 2 cucchiai d''olio a fuoco basso e coperto. Tritate l''aglio con le acciughe, i capperi, il basilico e il prezzemolo. Unite il trito alla cipolla e fate rosolare per un paio di minuti. Quando la pasta è cotta rovesciatela sulla padella del sugo, condite e servite.',1396);
INSERT INTO "ricette" VALUES (24407,'Strozzapreti Con Funghi Porcini','Primo','Funghi Porcini',4,'Luogo: Ciociaria. Luogo: Lazio.','400 G Farina Di Grano Duro,
Acqua,
1 Pizzico Sale,
Per Il Sugo:,
400 G Funghi Porcini,
1 Manciata Prezzemolo,
1/2 Peperoncino,
2 Spicchi Aglio,
Olio D''oliva,
1 Pizzico Sale','Sulla spianatoia impastare la farina con sale e acqua, fino a ottenere un impasto omogeneo. Suddividerlo in tanti bastoncini grossi come una matita e allungarli a mano uno per uno. Raschiare i funghi con un coltellino, togliendo tutta le terra, separare i gambi dalle cappelle, passarli con uno straccio umido senza lavarli e affettarli sottilmente. In una padella far imbiondire nell''olio gli spicchi d''aglio e il peperoncino, quindi toglierli e aggiungere i funghi. Cuocere a fuoco vivace rimescolando spesso. Appena i funghi avranno consumato la loro acqua, aggiungere una manciata di prezzemolo e salare. Nel frattempo lessare gli strozzapreti in abbondante acqua salata, scolarli al dente e versarli nella padella. Mantecare con il sugo per qualche minuto e servire.',2115);
INSERT INTO "ricette" VALUES (24408,'Strozzapreti Con Le Triglie','Primo','Triglie',4,' -','450 G Pasta Tipo Strozzapreti Freschi,
500 G Triglie,
400 G Pomodori Pelati San Marzano,
Prezzemolo,
Aglio,
Vino Bianco Secco,
Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Far imbiondire dolcemente l''aglio con un po'' di peperoncino nell''olio. Unirvi i pomodori triturati; salare, far insaporire e aggiungere i soli filetti delle triglie, lasciando cuocere per pochi minuti. Lessare in abbondante acqua salata gli strozzapreti, scolarli e condirli con l''intingolo di triglla. Rifinire con prezzemolo tritato.',2942);
INSERT INTO "ricette" VALUES (24409,'Strudel','Dessert','Mele',8,' -','1000 G Mele,
100 G Uvetta Sultanina,
25 G Pinoli,
10 Noci,
100 G Zucchero,
1 Pizzico Cannella,
1 Limone (scorza),
Pangrattato,
Pasta Sfoglia','Fare l''impasto con mele tagliate sottili, noci, pinoli, zucchero, cannella, scorza e lasciare riposare per circa 30 minuti. Tirare la pasta sfoglia cospargere di pangrattato fatto rosolare nel burro. Mettere l''impasto sulla pasta sfoglia stesa e arrotolare. Mettere a cuocere nel forno già a 190 gradi per circa 1 ora.',2551);
INSERT INTO "ricette" VALUES (24410,'Strudel (2)','Dessert','Mele',4,'Ricetta adatta a: vegetariani.','400 G Farina Integrale Setacciata,
1000 G Mele E Pere,
Uvetta Sultanina,
Mandorle (o Noci Tostate),
2 Cucchiai Olio D''oliva,
Sale Marino,
Malto Di Mais','Mettete in una terrina la farina e portate a bollore una tazza d''acqua con 2 cucchiai di olio e un pizzico di sale, quindi versatela ancora bollente sulla farina. Mescolate bene e, quando si è raffreddata, impastate con le mani. Fate riposare la pasta (che avrà assunto una consistenza abbastanza insolita) per mezz''ora; distendete sul tavolo uno strofinaccio da cucina pulito e cospargetelo di farina, stendetevi sopra la pasta con le mani: deve essere abbastanza sottile. Versatevi sopra la frutta tagliata a pezzetti, l''uvetta ammollata e le noci o le mandorle, spargetevi un pizzico di sale. Ora, aiutandovi sollevando lo strofinaccio da un''estremità, arrotolate la pasta su se stessa e sigillate i bordi con una forchetta. Mettete lo strudel in una teglia oleata con molta delicatezza e facendo attenzione che la chiusura del rotolo sia rivolta verso l''alto. Fate qualche foro sulla parte superiore e infornate a forno medio per circa quaranta minuti. Sciogliete un po'' di malto di mais in un bicchiere d''acqua con cui spennellerete il dolce appena tolto dal forno, per lucidarlo. Lasciate raffreddare bene prima di mangiarlo.',3113);
INSERT INTO "ricette" VALUES (24411,'Strudel (3)','Dessert','Mele',4,' -','500 G Mele,
250 G Farina,
90 G Zucchero,
Uvetta Sultanina,
1 Uovo,
Sale,
Latte,
Scorza Di Limone,
Burro','Disporre sulla tavola la farina, unire il sale, l''uovo e un po'' di burro. Impastare aggiungendo un po'' alla volta il latte. Lavorare bene, avvolgere la pasta in un panno e far riposare per 30 minuti. Stenderla con il matterello e ricoprire la sfoglia con le mele sbucciate e tagliate, l''uvetta, la scorza di limone, lo zucchero e una parte del burro fuso. Arrotolare la sfoglia su se stessa, metterla in uno stampo imburrato; ricoprire con il resto del burro fuso, cospargere di zucchero e infornare per 45 minuti circa.',2535);
INSERT INTO "ricette" VALUES (24412,'Strudel Al Cocco','Dessert','Cocco',4,' -','250 G Farina,
140 G Burro,
3 Uova,
160 G Zucchero,
140 G Cocco In Polvere,
100 G Panna Fresca,
50 G Canditi Misti,
1 Pizzico Sale,
1 Limone (scorza Grattugiata),
Zucchero A Velo','Mescolate la farina con 1 cucchiaio di zucchero, un pizzico di sale, 1 uovo e 40 g di burro morbido. Impastate il tutto energicamente, unendo, se occorre, 1 cucchiaio d''acqua tiepida. Avvolgete la pasta in un telo umido e lasciatela riposare per 30 minuti. Lavorate a crema 60 g di burro con 40 g di zucchero, 20 g di cocco in polvere, la scorza grattugiata del limone, la panna e 3 tuorli d''uovo, unendoli uno alla volta. Poi incorporate gli albumi montati a neve densa. Inumidite un telo, infarinatelo leggermente e stendetevi sopra la pasta in una sfoglia spessa circa 1/2 centimetro. Spennellatela con 20 g di burro fuso. Amalgamate il cocco in polvere rimasto con i canditi e il resto dello zucchero. Spalmate la pasta prima con questo composto e poi con la crema. Arrotolate il dolce strettamente, sigillate bene le estremità e fatelo scivolare sulla placca del forno imburrata. Cuocete a 180 gradi per un''ora. Servite il dolce tiepido, cosparso di zucchero a velo.',3853);
INSERT INTO "ricette" VALUES (24413,'Strudel Con Le Mele','Dessert','Mele',4,' -','Per La Pasta:,
50 G Farina Bianca,
40 G Burro,
1 Uovo,
Zucchero A Velo,
Per La Placca:,
Burro,
Per Stendere:,
Farina,
Per Il Ripieno:,
750 G Mele,
2 Fette Mollica Di Pane,
40 G Uvetta Sultanina,
100 G Zucchero Semolato,
1 Cucchiaino Cannella,
Pinoli','Fate la fontana con la farina. Al centro, mettetevi il burro, morbido a pezzetti, e sgusciatevi l''uovo. Unite 4 cucchiaiate d''acqua, poi impastate il tutto. Dovete ottenere un palla di impasto molto elastica e omogenea. Copritela e mettetela a riposare per circa 30 minuti. Intanto: mettete a bagno l''uvetta e sbucciate la frutta che ridurrete a tocchetti. Su un ampio tovagliolo leggermente infarinato stendete la pasta, prima con il mattarello e poi con il dorso delle mani finché sarà sottilissima, quasi trasparente. Cospargetela allora con la mollica di pane, con i pezzi di frutta e con l''uvetta ben strizzata, spolverizzate il tutto con lo zucchero semolato e con mezzo cucchiaino di cannella. Arrotolate lo strudel su se stesso aiutandovi con lo strofinaccio (o con la carta da forno).Saldate le estremità, poi poggiatelo sulla placca imburrata dandogli la forma di una mezzaluna. Cuocetelo per circa 30 minuti nel forno già scaldato a 200 gradi e servitelo, tiepido o freddo, cosparso di zucchero a velo.',3389);
INSERT INTO "ricette" VALUES (24414,'Strudel Con Le Pesche','Dessert','Pesche',4,' -','Per La Pasta:,
50 G Farina Bianca,
40 G Burro,
1 Uovo,
Zucchero A Velo,
Per La Placca:,
Burro,
Per Stendere:,
Farina,
Per Il Ripieno:,
750 G Pesche,
2 Fette Mollica Di Pane,
40 G Uvetta Sultanina,
100 G Zucchero Semolato,
1 Cucchiaino Cannella,
Pinoli','Fate la fontana con la farina. Al centro, mettetevi il burro, morbido a pezzetti, e sgusciatevi l''uovo. Unite 4 cucchiaiate d''acqua, poi impastate il tutto. Dovete ottenere un palla di impasto molto elastica e omogenea. Copritela e mettetela a riposare per circa 30 minuti. Intanto: mettete a bagno l''uvetta e sbucciate la frutta che ridurrete a tocchetti. Su un ampio tovagliolo leggermente infarinato stendete la pasta, prima con il mattarello e poi con il dorso delle mani finché sarà sottilissima, quasi trasparente. Cospargetela allora con la mollica di pane, con i pezzi di frutta e con l''uvetta ben strizzata, spolverizzate il tutto con lo zucchero semolato e con mezzo cucchiaino di cannella. Arrotolate lo strudel su se stesso aiutandovi con lo strofinaccio (o con la carta da forno).Saldate le estremità, poi poggiatelo sulla placca imburrata dandogli la forma di una mezzaluna. Cuocetelo per circa 30 minuti nel forno già scaldato a 200 gradi e servitelo, tiepido o freddo, cosparso di zucchero a velo.',3277);
INSERT INTO "ricette" VALUES (24415,'Strudel Con Ripieno Di Frutta','Dessert','Frutta Fresca',4,' -','Per La Pasta:,
50 G Farina Bianca,
40 G Burro,
1 Uovo,
Zucchero A Velo,
Per La Placca:,
Burro,
Per Stendere:,
Farina,
Per Il Ripieno:,
750 G Frutta Fresca (mele, Pesche),
2 Fette Pancarré,
40 G Uvetta Sultanina,
100 G Zucchero Semolato,
1 Cucchiaino Cannella,
Pinoli','Fate la fontana con la farina. Al centro, mettetevi il burro, morbido a pezzetti, e sgusciatevi l''uovo. Unite 4 cucchiaiate d''acqua, poi impastate il tutto. Dovete ottenere un palla di impasto molto elastica e omogenea. Copritela e mettetela a riposare per circa 30 minuti. Intanto: mettete a bagno l''uvetta e sbucciate la frutta che ridurrete a tocchetti. Su un ampio tovagliolo leggermente infarinato stendete la pasta, prima con il mattarello e poi con il dorso delle mani finché sarà sottilissima, quasi trasparente. Cospargetela allora con il pancarré sbriciolato, con i pezzi di frutta e con l''uvetta ben strizzata, spolverizzate il tutto con lo zucchero semolato e con mezzo cucchiaino di cannella. Arrotolate lo strudel su se stesso aiutandovi con lo strofinaccio (o con la carta da forno).Saldate le estremità, poi poggiatelo sulla placca imburrata dandogli la forma di una mezzaluna. Cuocetelo per circa 30 minuti nel forno già scaldato a 200 gradi e servitelo, tiepido o freddo, cosparso di zucchero a velo.',3746);
INSERT INTO "ricette" VALUES (24416,'Strudel Con Ripieno Di Frutta (2)','Dessert','Mele',4,' -','Per La Pasta:,
50 G Farina Bianca,
40 G Burro,
1 Uovo,
Zucchero A Velo,
Per La Placca:,
Burro,
Per Stendere:,
Farina,
Per Il Ripieno:,
750 G Mele,
2 Fette Mollica Di Pane,
40 G Uvetta Sultanina,
100 G Zucchero Semolato,
1 Cucchiaino Cannella,
Pinoli','Fate la fontana con la farina. Al centro, mettetevi il burro, morbido a pezzetti, e sgusciatevi l''uovo. Unite 4 cucchiaiate d''acqua, poi impastate il tutto. Dovete ottenere un palla di impasto molto elastica e omogenea. Copritela e mettetela a riposare per circa 30 minuti. Intanto: mettete a bagno l''uvetta e sbucciate la frutta che ridurrete a tocchetti. Su un ampio tovagliolo leggermente infarinato stendete la pasta, prima con il mattarello e poi con il dorso delle mani finché sarà sottilissima, quasi trasparente. Cospargetela allora con la mollica di pane, con i pezzi di frutta e con l''uvetta ben strizzata, spolverizzate il tutto con lo zucchero semolato e con mezzo cucchiaino di cannella. Arrotolate lo strudel su se stesso aiutandovi con lo strofinaccio (o con la carta da forno).Saldate le estremità, poi poggiatelo sulla placca imburrata dandogli la forma di una mezzaluna. Cuocetelo per circa 30 minuti nel forno già scaldato a 200 gradi e servitelo, tiepido o freddo, cosparso di zucchero a velo.',3389);
INSERT INTO "ricette" VALUES (24417,'Strudel Con Ripieno Di Frutta (3)','Dessert','Pesche',4,' -','Per La Pasta:,
50 G Farina Bianca,
40 G Burro,
1 Uovo,
Zucchero A Velo,
Per La Placca:,
Burro,
Per Stendere:,
Farina,
Per Il Ripieno:,
750 G Pesche,
2 Fette Mollica Di Pane,
40 G Uvetta Sultanina,
100 G Zucchero Semolato,
1 Cucchiaino Cannella,
Pinoli','Fate la fontana con la farina. Al centro, mettetevi il burro, morbido a pezzetti, e sgusciatevi l''uovo. Unite 4 cucchiaiate d''acqua, poi impastate il tutto. Dovete ottenere un palla di impasto molto elastica e omogenea. Copritela e mettetela a riposare per circa 30 minuti. Intanto: mettete a bagno l''uvetta e sbucciate la frutta che ridurrete a tocchetti. Su un ampio tovagliolo leggermente infarinato stendete la pasta, prima con il mattarello e poi con il dorso delle mani finché sarà sottilissima, quasi trasparente. Cospargetela allora con la mollica di pane, con i pezzi di frutta e con l''uvetta ben strizzata, spolverizzate il tutto con lo zucchero semolato e con mezzo cucchiaino di cannella. Arrotolate lo strudel su se stesso aiutandovi con lo strofinaccio (o 