Frutta Secca Mista),
3 Cucchiai Zucchero,
1 Uovo Intero,
50 G Burro Sciolto,
Poco Latte,
1/2 Bicchierino Rum (o Vino Marsala O Cognac)','In un recipiente mescolare le gallette e le nocciole tritate con il macinino. Aggiungere l''uovo crudo (volendo si può montare a neve il bianco) il burro fuso ma freddo, il cacao zuccherato, lo zucchero, il rum e un po'' di latte. Mescolare bene. Se l''impasto è troppo secco aggiungere un po'' di latte. Deve essere un impasto omogeneo, bagnato, ma non troppo. Formare delle palline e passarle sul cioccolato amaro (variante sfiziosa: inserire all''interno una nocciola!). Mettere le praline in congelatore per qualche ora. Prima di servirle farle scongelare, devono rimanere morbide ma non fredde (circa 1 ora o 2).',2276);
INSERT INTO "ricette" VALUES (19816,'Praline Al Cioccolato (2)','Dessert','Cacao Amaro',4,' -','2 Pacchi Biscotti Secchi,
250 G Cacao Amaro,
2 Cucchiai Zucchero,
250 G Burro,
200 G Cacao Dolce,
Latte','Fate ammorbidire il burro a temperatura ambiente, tritare i biscotti abbastanza finemente. Mettere in una terrina aggiungere il cacao amaro e lo zucchero e amalgamare in modo omogeneo. Unire il burro a pezzetti e, poco alla volta, il latte, i biscotti ed impastare con le mani fino a quando il composto non sia elastico e morbido. Formare delle palline, passarle nel cacao dolce e disporre in una terrina. Prima di servirle, lasciarle in frigorifero per almeno 2 ore.',5202);
INSERT INTO "ricette" VALUES (19817,'Praline Al Miele','Dessert','Miele',4,' -','90 G Pinoli,
1 Cucchiaio Olio D''oliva Insapore,
60 G Ciliegie Tritate Finemente,
60 G Datteri Snocciolati E Tritati Finemente,
60 G Scorza D''arancia Candita Tritata Fine,
90 G Noci Tritate Finemente,
1/2 Cucchiaino Cannella,
2 Cucchiai Miele,
60 G Mandorle Macinate Finemente,
1 Albume D''uovo','In una padella, su fiamma media, friggete i pinoli finché sono ben dorati. Vanno poi scolati su carta da cucina e tritati non troppo fini. Riunite in una ciotola ciliegie, datteri, scorza d''arancia, noci e cannella. Scaldate il miele in una casseruola, versatelo nella ciotola e mescolate. Aggiungete infine le mandorle macinate e l''albume. Ricavatene delle palline e rotolatele nel trito di pinoli. Accomodatele in un piatto e fatele rassodare in frigorifero.',2283);
INSERT INTO "ricette" VALUES (19818,'Pranzetto Veloce Di Galletto','Pollame','Galletto',4,' -','1 Galletto,
1 Finocchio Intero (maschio),
Alcuni Pomodorini A Grappolo,
Alcune Olive Nere Toscane,
Alcune Patate Novelle,
1 Scalogno','Tagliare il galletto e le patate a pezzi. In una padella, fare un soffritto con lo scalogno, aggiungere le patate e il galletto. Fare rosolare, aggiungere sale, pepe e rosmarino e poi continuare a cuocere per 10-15 minuti. Durante che il pollo cuoce, fare un''insalata con i pomodorini (divisi a metà), le olive e la parte bianca del finocchio (tagliata in fettine fine nel senso della lunghezza). Aggiungerci olio e aceto. Mangiare (o servire) uno dopo l''altro: il pranzo sarà completo.',1280);
INSERT INTO "ricette" VALUES (19819,'Prataioli Farciti Al Pollo Con Contorno Di Fiori Di Zucca Alle Verdure','Contorno','Funghi Prataioli',4,' -','6 Funghi Prataioli,
200 G Macinato Di Pollo,
4 Fiori Di Zucca,
1 Carota,
1 Costa Sedano,
1 Cipolla,
1 Tuorlo D''uovo,
1 Spicchio Aglio,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Privare i funghi dei gambi e scottarli in padella con aglio e cipolla. Farcirli con la carne e infornarli a 200 gradi per 10 minuti . Tritare le verdure, passarle in padella con olio, cipolla, sale e pepe. Mescolare con uovo e riempirvi i fiori di zucca, ungerli e infornarli per pochi minuti.',1104);
INSERT INTO "ricette" VALUES (19820,'Prato Verde','Bevande','Gin',1,' -','1/10 Kiwi Drink Boero,
2/10 Vermouth Martini Dry,
4/10 Beefeater Gin Blu,
3/10 Triple Sec De Kuyper,
Per Guarnire:,
1 Ciliegina Rossa Boero,
1 Foglia Menta','Versare gli ingredienti nell''ordine nello shaker con ghiaccio. Agitare vigorosamente e servire nella doppia coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa Boero e una foglia di menta.',355);
INSERT INTO "ricette" VALUES (19821,'Preboggion Trascinato','Carne','Preboggion',6,'Preparazione: 50 minuti.','1000 G Preboggion,
1 Spicchio Aglio,
2 Acciughe,
1 Cucchiaio Olio D''oliva,
Sale','Pulire, lavare, lessare il preboggion. Tritare l''aglio e le acciughe, aggiungere la verdura e fare cuocere per 10 minuti.',1380);
INSERT INTO "ricette" VALUES (19822,'Pregio','Bevande','Vodka',1,' -','5 Cubetti Ghiaccio,
3 Cucchiai Vodka,
1 Cucchiaino Aceto Di Vino Bianco,
Sale,
1 Cucchiaino Salsa Worcester,
2 Cucchiai Succo Di Pomodoro,
1 Cucchiaio Tomato Ketchup,
1 Spruzzo Tabasco (2 Gocce),
1 Tuorlo D''uovo,
Pepe Di Caienna','Questo long drink a base di pomodoro e salse piccanti si prepara nello shaker. Mettete in quest''ultimo il ghiaccio, la Vodka, l''aceto, un pizzico di sale e tutti gli altri ingredienti, eccettuati il tuorlo e il pepe. Shakerate con vigore per alcuni secondi, quindi versate il miscuglio in un bicchiere ''old fashioned'' (tumbler medio). Ora adagiate delicatamente sulla superficie il tuorlo e insaporitelo con un pizzico di pepe di Caienna. Servite con cannuccia.',530);
INSERT INTO "ricette" VALUES (19823,'Preludio','Bevande','Artic Silver',1,' -','3/10 Artic Silver,
1/10 Bitter Campari,
1/10 Succo Di Pompelmo Del Monte,
3/10 Vodka Alla Pesca Seremeq,
2/10 Vermouth Martini Bianco,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa al maraschino.',334);
INSERT INTO "ricette" VALUES (19824,'Presa Diretta','Bevande','Gin',1,' -','2/5 Bitter Amaro,
1/5 Calvados,
2/5 Gin,
1 Spruzzo Anisette','Scuotere, con poco ghiaccio in cubetti, nello shaker. Servire nel flute.',249);
INSERT INTO "ricette" VALUES (19825,'Presnitz','Dessert','Mandorle',4,'Luogo: Friuli. Luogo: Trieste.','Per La Sfoglia:,
1 Confezione Pasta Sfoglia (o Pasta Da Strudel),
Per Il Ripieno:,
200 G Mandorle Pelate Tritate,
200 G Noci Tritate,
100 G Uvetta Sultanina,
100 G Pinoli,
100 G Burro,
50 G Zucchero,
50 G Frutta Candita,
1 Uovo,
Farina,
Rum','Scongelare la sfoglia. Ammollare l''uvetta passa in rum (o in acqua tiepida se si è astemi). Spolverare il piano di lavoro di farina e con il matterello formare un quadrato di circa 30 cm. Ricoprire con mandorle, noci, uva passa, pinoli, fiocchi di burro, frutta candita a pezzetti e spolverare di zucchero, avendo cura di lasciare liberi i bordi per la larghezza di circa 2 cm. Rompere l''uovo separando tuorlo da albume. Spalmare con un pennello l''albume sui bordi della sfoglia, arrotolarla su se stessa; fare pressione sui bordi per sigillare. Imburrare una teglia, disporvi il rotolo con la forma di un ferro di cavallo o di una spirale. Spennellare con il tuorlo. Cucinare 45 minuti-60'' (dipende dal forno) e sfornare. Lasciar raffreddare. Avvolgere in una stagnola e lasciar riposare una settimana. Consumare il giorno di Pasqua. Nota: dolce pasquale triestino, ricetta di famiglia. Il Presnitz appartiene alla numerosissima famiglia degli Strudel (che in tedesco vuol dire vortice, gorgo) di cui noi conosciamo solo l''apfelstrudel (strudel di mele). E'' stato creato dall''allora più famoso pasticciere triestino in occasione della visita della principessa Sissi (moglie di Francesco Giuseppe) a Trieste, ed a lei dedicato.',6303);
INSERT INTO "ricette" VALUES (19826,'Press','Bevande','Vodka',1,' -','1/5 Whisky,
4/5 Vodka,
2 Gocce Bitter Amaro,
2 Gocce Liquore Strega,
Per Servire:,
1 Scorza D''arancia,
Per Guarnire:,
1 Chicco Caffè','Agitare nello shaker con cubetti di ghiaccio. Servire in calice con una buccia di arancia sprizzata nel bicchiere. Guarnire con un chicco di caffè.',495);
INSERT INTO "ricette" VALUES (19827,'Pressing','Bevande','Gin',1,' -','4/10 Beefeater Gin,
2/10 Fragola Drink Boero,
2/10 Vermouth Martini Bianco,
2/10 Succo D''arancia Del Monte','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnizioni fantasia.',290);
INSERT INTO "ricette" VALUES (19828,'Prestigio','Bevande','Brandy',1,' -','1/3 Rosso Antico,
1/3 Brandy Royal Stock,
1/3 Succo D''arancia,
Alcune Gocce Succo Di Limone,
Per Guarnire:,
1 Angolo Fettina D''arancia','Si prepara nello shaker con ghiaccio cristallino e si serve nei bicchieri da cocktail ben ghiacciati guarnendo con un angolo di fettina d''arancia.',217);
INSERT INTO "ricette" VALUES (19829,'Presto','Bevande','Cognac',1,' -','1/6 Vermouth,
4/6 Cognac,
1/6 Succo D''arancia,
1 Spruzzo Pernod','Agitare, con alcuni cubetti di ghiaccio, nello shaker. Servire nel calice alto.',305);
INSERT INTO "ricette" VALUES (19830,'Prima Pappa','Primo','Crema Di Riso',1,'Ricetta adatta a: bambini piccoli.','3 Cucchiai Crema Di Riso,
1 Vasetto Omogeneizzato D''agnello,
1 Patata,
1 Carota,
1 Zucchina,
1 Pezzetto Sedano,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Cucchiaino Formaggio Parmigiano','In 500 g d''acqua aggiungere le verdure ben lavate e, al caso, pelate; portare ad ebollizione e cuocere fino a ridurre l''acqua a circa la metà. Separare le verdure cotte dal brodo di cottura. Stemperare la crema di riso e l''omogeneizzato in 200 g del brodo di verdure ben caldo, aggiungere l''olio d''oliva extra-vergine e la spolveratina di parmigiano.',686);
INSERT INTO "ricette" VALUES (19831,'Primavera','Bevande','Aperol',1,' -','4/10 Aperol,
2 G Granatina Toschi,
3/10 Limoncello Toschi,
3/10 Ron Pampero White,
Per Guarnire:,
1 Fettina Arancia,
1 Ciliegina','Si prepara nello shaker con ghiaccio. Agitare e servire nella coppetta da cocktail fredda. Guarnire con una fettina d''arancia e una ciliegina.',389);
INSERT INTO "ricette" VALUES (19832,'Primavera (2)','Bevande','Caffè',1,' -','3/10 Caffè Lavazza,
3/10 Vanilzucca,
3/10 Artic Banana,
1/10 Panna','Si prepara nello shaker. Servire nella classica coppetta da cocktail.',177);
INSERT INTO "ricette" VALUES (19833,'Primavera (3)','Bevande','Cognac',1,' -','3 Uova Fresche,
15 Cl Birra Fredda,
60 G Zucchero,
100 Cl Birra Riscaldata,
1 Cucchiaio Zenzero E Noce Moscata In Polvere,
1 Bicchiere Cognac','Battere tre uova fresche con un decilitro e mezzo di birra fredda e sessanta grammi di zucchero. Quando il liquido è diventato ben schiumoso aggiungere, a poco a poco, un litro di birra riscaldata assieme ad un cucchiaio di zenzero e noce moscata in polvere. Aggiungere anche un bicchiere di cognac. Servire, appena pronto, nel cup.',1396);
INSERT INTO "ricette" VALUES (19834,'Primavera (4)','Bevande','Vino Porto Rosso',1,' -','4/5 Vino Porto Rosso,
1/5 Curacao,
Alcune Gocce Sciroppo Di Fragole,
1 Fettina Limone','Versate i liquidi nel mixer, con del ghiaccio. Spremete la fettina di limone, agitate con energia e servite.',277);
INSERT INTO "ricette" VALUES (19835,'Primera','Bevande','Cachaca',1,' -','5/10 Cachaca Nuga Ful,
2/10 Cointreau,
1/10 Orzata Sacco,
2/10 Succo Di Lime,
Per Guarnire:,
1 Spirale Scorza Di Lime,
1 Ciliegina Rossa','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una sottile spirale di buccia di lime e una ciliegina rossa.',211);
INSERT INTO "ricette" VALUES (19836,'Primo Piatto Alla Menta','Primo','Menta',4,'Preparazione: 20 minuti. Cottura: 50 minuti. Calorie: 386.','300 G Farro,
6 Carciofi Teneri,
3 Scalogni,
1/2 Bicchiere Vino Bianco Secco,
2 Rametti Menta Fresca,
100 Cl Brodo Vegetale,
4 Cucchiai Olio D''oliva Extra-vergine,
1 Pizzico Sale,
1 Macinata Pepe','Tritate gli scalogni finemente dopo averli sbucciati. Scaldate 4 cucchiai d''olio in una casseruola e fatevi rosolare a fiamma dolce gli scalogni. Mondate i carciofi, eliminate le foglie più dure e le spine, tagliateli a metà e privateli del fieno. Affettateli sottilmente e metteteli subito nella casseruola mescolandoli al soffritto. Bagnate con il vino bianco e lasciate sfumare. Unite il farro, mescolatelo ai carciofi e poi aggiungete 4 mestoli di brodo bollente. Proseguite la cottura a fiamma vivace, mescolando e aggiungendo man mano il brodo necessario. Proseguite in questo modo come se si trattasse di un risotto. A fine cottura (40 minuti circa, dipende dal tipo di farro) aggiungete una macinata di pepe, un pizzico di sale e un filo d''olio crudo. Profumate con le foglie di menta ridotte a pezzetti, mescolate bene e portate subito in tavola.',1333);
INSERT INTO "ricette" VALUES (19837,'Primo Sale Alle Erbe','Antipasto','Erbe Aromatiche',4,' -','Formaggio Primo Sale,
1/2 Bicchiere Olio D''oliva Extra-vergine Medio-fruttato,
Erbe Aromatiche Fresche (timo, Maggiorana, Mentuccia, Rosmarino, Salvia),
Scalogno,
Sale Marino','Preparare un trito di erbette aromatiche e scalogno e metterlo in una ciotola con 1/2 bicchiere d''olio; far macerare per alcune ore. Tagliare il primo sale a fette non grandi e irrorare ciascuna con l''olio aromatico un po'' prima di servire. Può essere un antipasto inconsueto e fresco.',1021);
INSERT INTO "ricette" VALUES (19838,'Prince','Bevande','Rum',1,' -','2 Spruzzi Pernod,
1 Spruzzo Angostura,
Rum,
1/2 Cucchiaio Zucchero,
Per Servire:,
Succo Di Limone,
Zucchero','Agitare nel mixer con ghiaccio tritato. Servire nel tumbler stretto il cui bordo, bagnato di succo di limone, sia stato precedentemente passato nello zucchero.',400);
INSERT INTO "ricette" VALUES (19839,'Prince Charles','Bevande','Brandy',1,' -','1/3 Brandy,
1/3 Drambuie,
1/3 Succo Di Limone,
Per Servire:,
1 Fettina Limone','Versare i primi 3 ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in un bicchiere ballon. Decorare con 1 fettina di limone sul bordo del bicchiere.',198);
INSERT INTO "ricette" VALUES (19840,'Prince Charles (2)','Bevande','Cognac',1,' -','1/3 Cognac,
1/3 Drambuie,
1/3 Succo Di Limone,
Per Servire:,
1 Fettina Limone','Versare i primi 3 ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare. Passare in un bicchiere ballon. Decorare con 1 fettina di limone sul bordo del bicchiere.',198);
INSERT INTO "ricette" VALUES (19841,'Princess','Bevande','Rum',1,' -','5/10 Grand Marnier,
5/10 Myers''s Rum,
Panna,
2 G San Marzano Borsci,
Per Guarnire:,
Cacao Amaro In Polvere','Si prepara nello shaker con cubetti di ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con cacao amaro in polvere.',834);
INSERT INTO "ricette" VALUES (19842,'Princess (2)','Bevande','Apricot Brandy',1,' -','1/3 Panna Liquida,
2/3 Apricot Brandy,
Per Servire:,
1 Ciliegia','Preparare, con alcuni cubetti di ghiaccio, nello shaker. Servire nel calice basso, con una ciliegia.',358);
INSERT INTO "ricette" VALUES (19843,'Princess Pride Cocktail','Bevande','Calvados',1,' -','2/4 Calvados,
1/4 Vermouth Rosso,
1/4 Vermouth Dubonnet','Versare gli ingredienti in uno shaker con alcuni cubetti di ghiaccio. Agitare e passare in una coppetta da cocktail.',236);
INSERT INTO "ricette" VALUES (19844,'Princeton','Bevande','Gin Dry',2,' -','2/3 Gin Dry,
1/3 Vino Porto Rosso (vino Rosso Porto),
4 Gocce Orange Bitter,
2 Spruzzi Scorza Di Limone','E'' ritenuto un cocktail di fine pasto. Si prepara nel mixing glass, aggiungendo gli ingredienti nell''ordine e quindi rimestando accuratamente.',344);
INSERT INTO "ricette" VALUES (19845,'Princeton (2)','Bevande','Gin Dry',2,' -','120 G Gin Dry,
60 G Vino Porto Rosso (vino Rosso Porto),
8 Gocce Orange Bitter,
4 Spruzzi Scorza Di Limone','E'' ritenuto un cocktail di fine pasto. Si prepara nel mixing glass, aggiungendo gli ingredienti nell''ordine e quindi rimestando accuratamente.',380);
INSERT INTO "ricette" VALUES (19846,'Princeton (3)','Bevande','Gin',1,' -','1/3 Vino Porto,
2/3 Gin,
1 Spruzzo Bitter All''arancia,
Per Servire:,
1 Scorza Di Limone','Agitare nel mixer con abbondante ghiaccio in cubetti. Servire nel gotto basso con scorza di limone.',325);
INSERT INTO "ricette" VALUES (19847,'Princeton (4)','Bevande','Gin Dry',1,' -','4 Cubetti Ghiaccio,
6 Cl Gin Dry,
3 Cl Vino Porto,
1 Spruzzo Orange Bitter,
1 Scorzetta Di Limone','Mettete il ghiaccio nel mixing-glass, unite il gin, il porto, lo spruzzo di orange bitter e mescolate a lungo. Filtrate in una coppetta da cocktail. Aromatizzate strizzando sul drink la scorzetta di limone.',199);
INSERT INTO "ricette" VALUES (19848,'Princeton (5)','Bevande','Gin',1,' -','5/10 Gin,
3/10 Vermouth Dry,
2/10 Succo Di Cedro','Scuotete il tutto con aggiunta di ghiaccio e versate in un bicchiere da cocktail già freddo.',269);
INSERT INTO "ricette" VALUES (19849,'Principato','Bevande','Succo D''ananas',1,' -','2/10 Artic Vodka E Pesca,
2/10 Artic Vodka Neutra,
1/10 Aperol,
5/10 Succo D''ananas','Versare gli ingredienti nell''ordine nello shaker con ghiaccio. Agitare vigorosamente e servire nel bicchiere tumbler con ghiaccio. Guarnizioni fantasia e cannucce.',251);
INSERT INTO "ricette" VALUES (19850,'Principe Di Galles','Bevande','Frangelico',1,' -','1/3 Frangelico,
1/3 Drambuie,
1/3 Bailey''s Irish Cream,
Per Guarnire:,
Polvere Di Cacao','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con polvere di cacao sul bordo del bicchiere.',623);
INSERT INTO "ricette" VALUES (19851,'Principessa','Bevande','Gin',1,' -','2/10 Succo D''ananas Del Monte,
2/10 Succo D''arancia Del Monte,
Alcune Gocce Granatina Sacco,
4/10 Gordon''s Gin,
2/10 Aperol,
Per Guarnire:,
1/2 Fettina Ananas','Agitare vigorosamente e servire nella coppetta da cocktail doppia ben fredda. Guarnire con mezza fettina d''ananas.',273);
INSERT INTO "ricette" VALUES (19852,'Principessa (2)','Bevande','Aperol',1,' -','4/10 Aperol,
1/10 Artic Vodka E Pesca,
2 G Rose''s Lime Juice Cordial,
3/10 Succo D''arancia,
2/10 Tanqueray Gin,
Per Guarnire:,
Frutta Fresca Di Stagione','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnizioni fantasia con frutta di stagione.',400);
INSERT INTO "ricette" VALUES (19853,'Printemps','Bevande','Vino Bianco Secco',4,' -','1 Bottiglia Vino Bianco Secco,
5 Pesche A Dadini,
2 Limoni A Fette Sottili,
2 Arance A Fette Sottili','Mettete la frutta in una zuppiera di vetro, coprite col vino ghiacciato e lasciate riposare in frigorifero.',1114);
INSERT INTO "ricette" VALUES (19854,'Printemps Cup','Bevande','Vino Spumante Secco',4,' -','1 Bottiglia Vino Spumante Secco,
150 G Zucchero,
1 Manciata Mandorle Spellate,
Frutta Di Stagione (pesche, Fragole, Albicocche, Banane) A Dadini','Mettete sul fondo di una grande coppa di vetro la frutta di stagione (pesche, fragole, banane, albicocche) tagliata a dadini e le mandorle. Cospargete di zucchero e annaffiate con lo spumante ghiacciato. Lasciate riposare in frigorifero per un''ora e poi servite.',1688);
INSERT INTO "ricette" VALUES (19855,'Profiteroles','Dessert','Cioccolato',6,' -','2 Cucchiai Zucchero A Velo,
3 Cucchiai Latte,
50 Cl Panna,
250 G Cioccolato Fondente,
Per La Pasta Di Bignè:,
150 G Farina,
100 G Burro,
1 Cucchiaio Zucchero Semolato,
4 Uova,
1 Pizzico Sale','Ponete in una casseruola un bicchiere d''acqua, un pizzico di sale, un cucchiaio di zucchero e 80 g di burro, portate ad ebollizione, quindi togliete il recipiente dal fuoco e aggiungete la farina tutta in una volta, mescolando. Rimettete la casseruola sul fuoco e fate cuocere il composto, rimestando energicamente con un cucchiaio di legno, fino a quando si staccherà dalle pareti. A questo punto spegnete il fuoco e incorporate al composto le uova, uno alla volta. Distribuite l''impasto sulla piastra del forno unta col resto del burro, formando tanti mucchietti ben distanziati fra loro con l''aiuto di un cucchiaino. Fate cuocere i bignè così preparati in forno (200 gradi) per 20 minuti, dopodichè spegnete il forno e lasciateli raffreddare senza aprire lo sportello. Quando sono freddi, staccateli delicatamente dalla piastra, praticate un taglio sulla base di ciascuno e riempiteli con la panna, montata e dolcificata con lo zucchero a velo, aiutandovi con una siringa per dolci. Spezzettate il cioccolato fondente e mettetelo in un pentolino, unite tre cucchiai di latte e fatelo sciogliere a calore dolcissimo, in modo da ottenere una crema semifluida. Immergetevi i bignè, uno alla volta, e metteteli man mano in un piatto di portata, disponendoli a cupola. Al termine versate sui bignè la crema avanzata, decorate il dolce con qualche fiocchetto di panna e fatelo raffreddare in frigo per almeno due ore prima di servire.',5055);
INSERT INTO "ricette" VALUES (19856,'Profiteroles Al Cioccolato','Dessert','Cioccolato',6,' -','300 G Bignè Dolci Già Pronti,
1 Tazza Crema Pasticciera,
25 Cl Panna Montata,
200 G Cioccolato Di Copertura,
10 Cl Acqua','Far sciogliere il cioccolato sbriciolato con l''acqua, a fuoco dolce, girando continuamente. Quindi passarlo nel frullatore per ottenere una crema densa e farlo raffreddare. Riempire di crema pasticciera con una siringa da pasticciere i bignè. Disporli a piramide, versarvi il cioccolato, decorare con la panna, formando, con la siringa, un cordone alla base. Servire freddo.',3287);
INSERT INTO "ricette" VALUES (19857,'Profiteroles Al Cioccolato (2)','Dessert','Cioccolato',4,' -','Per La Pasta:,
100 G Farina,
10 Cl Latte,
60 G Burro,
2 Uova,
Per Il Ripieno:,
20 Cl Panna Montata,
Per La Copertura:,
100 G Cioccolato Fondente,
50 G Zucchero,
30 G Burro','Versate in una casseruolina il latte e mezzo bicchiere d''acqua, 50 g di burro ammorbidito. Ponete sul fuoco e portate lentamente a bollore. Ritirate, incorporatevi 75 g di farina setacciata, mescolando velocemente in modo che non si formino grumi. Mettete di nuovo il recipiente sul fuoco e tenetevelo, sempre mescolando, fino a quando la pasta si stacca dal fondo e dalle pareti. Lasciatela raffreddare, incorporatevi un uovo alla volta, non aggiungendo il secondo se il primo non è stato assorbito. Mettete il composto in una tasca di tela da pasticciere e formate sedici mucchietti sulla placca del forno leggermente imburrata e infarinata. Cuocete in forno preriscaldato a 190 gradi per 15 minuti fino a quando i bignè sono gonfi e dorati. Ritirate e fate raffreddare su una gratella. Nel frattempo preparate la copertura: in un tegamino a fuoco basso sciogliete in poca acqua il cioccolato spezzettato, mescolate e unite il burro e lo zucchero. Dovete ottenere una crema piuttosto densa. Ritirate e lasciate raffreddare. Farcite i bignè con la panna. Disponeteli a piramide sul piatto di portata e, sopra, partendo dall''alto, versatevi a filo la salsa di cioccolata che deve distribuirsi in modo irregolare.',2579);
INSERT INTO "ricette" VALUES (19858,'Profiteroles Alla Nutella','Dessert','Nutella',8,' -','30 Bignè Vuoti Già Pronti,
2 Cucchiai Cioccolato Grattugiato,
2 Cucchiai Panna Fresca,
Nutella','Incidete i bignè vuoti e farciteli di Nutella con l''apposita tasca. Sistemateli su un piatto da portata, uno sull''altro, fino a formare una piramide. Sciogliete il cioccolato grattugiato in un pentolino e diluitelo con due cucchiai di panna. Versate la salsa così ottenuta sui bignè. Quando la cioccolata si sarà rappresa potrete guarnire il dolce con ciuffetti di panna montata.',4067);
INSERT INTO "ricette" VALUES (19859,'Profiteroles D''autunno','Dessert','Cioccolato Fondente',4,' -','12 Bignè Pronti,
150 G Cioccolato Fondente,
10 Cl Latte,
20 Cl Panna Fresca,
150 G Burro,
5 Cl Brandy','Montate la panna; lavorate la crema di marroni con il brandy e incorporate la panna con delicatezza mescolando dal basso verso l''alto per non smontarla. Farcite con il composto preparato i bignè servendovi di una siringa da pasticceria e disponeteli in un piatto per dolci, formando una piramide. Fate sciogliere il cioccolato in un pentolino con il latte e il burro, lasciatelo intiepidire e versate la crema sopra i bignè. Mettete i profiteroles in frigo per almeno 30 minuti prima di servire.',4248);
INSERT INTO "ricette" VALUES (19860,'Profiteroles Mandorle E Ciliegie','Dessert','Mandorle',8,'Preparazione: 35 minuti. Cottura: 35 minuti.','1 Cucchiaio Kirsch,
1 Cucchiaio Maizena,
1 Confezione Ciliegie Sciroppate,
20 Cl Panna Montata,
2 Cucchiai Zucchero A Velo,
30 G Mandorle,
2 Uova,
60 G Farina,
50 G Burro','Preriscaldate il forno a 200 gradi. In una casseruola, fate sciogliere il burro con 150 ml di acqua. Portate a ebollizione, aggiungete la farina e sbattete energicamente finché la miscela comincerà a staccarsi dalle pareti della casseruola. Lasciate raffreddare. Poco per volta, unite le uova sbattute alla miscela, mescolando bene dopo ogni aggiunta. Versate la pasta in una tasca da pasticciere con bocchetta liscia di 12 mm e distribuitela a palline sulla piastra da forno inumidita. Cospargete le palline con le mandorle, tritate grossolanamente, e mettetele in forno per venti o venticinque minuti, finché saranno cresciute e ben dorate. Toglietele dal forno. Incidete ciascuna pallina su un lato, per far uscire il vapore. Lasciatele raffreddare su una griglia di metallo. Nel frattempo preparate la farcia. Setacciate lo zucchero a velo e unitelo alla panna montata. Versatela in una tasca da pasticciere e usatela per riempire i bignè raffreddati. Distribuite i profiteroles in sei piattini individuali. Preparate la salsa: versate lo sciroppo delle ciliegie in una caraffa graduata e misuratene 200 ml. Trasferitelo in una casseruola e stemperatevi la maizena. Fate bollire, mescolando costantemente, finché la miscela sarà ispessita. Poi unitevi le ciliegie e, se vi piace, il kirsch. Al momento di servire spolverizzate i profiteroles con zucchero a velo. Serviteli accompagnandoli con la salsa di ciliegie calda.',1799);
INSERT INTO "ricette" VALUES (19861,'Profiteroles Veloci','Dessert','Cioccolato',4,' -','20 Bignè,
500 G Crema Alla Vaniglia,
200 G Cioccolato Fondente','Fare un taglietto in ciascun bignè e, con un cucchiaino, riempirli di crema; metterli in un piatto formando un monticello. Fondere il cioccolato spezzettato in una casseruola con un pò d''acqua, togliere dal fuoco, fare intiepidire, versare sui bignè, lasciare solidificare leggermente e servire.',4888);
INSERT INTO "ricette" VALUES (19862,'Prosciutto Affumicato Al Forno','Carne','Maiale',4,'Luogo: Regno Unito.','1000 G Prosciutto Affumicato Di Maiale,
Pangrattato','Lasciare ammollare in acqua fredda per 18 ore 1000 g di prosciutto affumicato. Avvolgerlo in 3 fogli di carta d''alluminio e disporre il pacchetto al centro del forno già riscaldato a 80 gradi. Cuocere per un''ora. Un po'' d''acqua, versata sulla teglia del forno durante la cottura, manterrà il prosciutto più morbido. Toglierlo dal forno e farlo riposare per 45 minuti prima di scartarlo, tagliare via la cotenna e sostituirla con pangrattato. Si serve il giorno seguente, affettato sottilmente.',5064);
INSERT INTO "ricette" VALUES (19863,'Prosciutto Al Forno','Carne','Maiale',10,' -','1 Prosciutto Crudo Di 3000 G,
1 Cavolo Rosso,
25 Cl Vino Bianco Secco,
2 Mele,
4 Cucchiai Gelatina Di Ribes,
2 Cucchiai Aceto Di Vino,
30 G Zucchero,
60 G Burro,
Sale Grosso,
Sale Fino,
Pepe','Chiedete al salumiere di praticare sulla cotenna del prosciutto delle incisioni regolari in lunghezza e in larghezza in modo da formare un reticolo. Mescolate una certa quantità di sale grosso e di pepe macinato e con questo composto soffregate vigorosamente il prosciutto insistendo sulle incisioni in modo che pepe e sale penetrino bene. Scaldate il forno a 240 gradi. Mettete il prosciutto direttamente sulla griglia e nel piatto sottostante versate il vino e due bicchieri d''acqua. Dopo un quarto d''ora portate il calore a 150 gradi e lasciate cuocere calcolando 30 minuti ogni mezzo chilo. A metà cottura girate il prosciutto, ma non bagnatelo perché la cotenna deve essere croccante. Nel frattempo dividete il cavolo in quattro, eliminate il torsolo. Tagliate le foglie a striscioline. In un tegame mettete il burro, un bicchiere d''acqua, lo zucchero, l''aceto, il sale e il pepe. Quando il tutto bolle unite il cavolo, coprite e abbassate il fuoco. Dopo un quarto d''ora aggiungete la gelatina di ribes e le mele sbucciate e tagliate a pezzi. Coprite e cuocete per 40 minuti. Se necessario finite la cottura senza coperchio per fare evaporare il liquido eccedente. Quando il prosciutto è cotto lasciatelo per 20 minuti nel forno spento con lo sportello aperto. Tagliate il prosciutto a fette, contornate con il cavolo. Diluite il sugo del prosciutto con un mestolo d''acqua calda e servitelo in salsiera. Vini di accompagnamento: Colli Orientali Del Friuli Schioppettino DOC, Chianti Classico DOCG, Aglianico Del Vulture Vecchio DOC.',14227);
INSERT INTO "ricette" VALUES (19864,'Prosciutto Al Latte','Carne','Maiale',1,'Ricetta adatta a: bambini piccoli.','1 Vasetto Omogeneizzato Di Prosciutto,
1 Cucchiaio Latte Intero,
1 Patata Media,
1 Cucchiaio Formaggio Parmigiano,
1 Pizzico Sale','Cuocere in abbondante acqua leggermente salata la patata ben pulita e lavata. Ridurre la patata ben cotta ad una purea piuttosto fluida, aggiungendo eventualmente un po'' di brodo di cottura. Aggiungere il cucchiaio di latte alla purea, quindi amalgamare bene il prosciutto e completare con il parmigiano.',547);
INSERT INTO "ricette" VALUES (19865,'Prosciutto Al Madera','Antipasto','Prosciutto',4,' -','4 Fette Prosciutto Di Praga Affumicato,
1 Tazzina Sugo Di Arrosto,
4 Cucchiai Vino Madera,
1 Cucchiaino Estratto Di Carne,
1 Cucchiaino Farina,
20 G Burro,
Sale','Mettete le fette di prosciutto su un piatto resistente al calore, posatele sopra una casseruola di acqua in ebollizione e scaldatele al vapore. Preparate intanto la salsa al Madera: mettete in una casseruolina il sugo di arrosto e deglassatelo con il Madera. Dopodichè unite un bicchiere di acqua calda nella quale avrete sciolto l''estratto di carne. Fate sobbollire per qualche minuto, poi aggiungete alla salsa il burro maneggiato con la farina. Lavorate la salsa con la frusta finché sarà spumosa, poi versatela sul prosciutto caldo e servite subito.',1248);
INSERT INTO "ricette" VALUES (19866,'Prosciutto Al Madera (2)','Antipasto','Prosciutto Crudo',6,' -','500 G Prosciutto Crudo (pezzi Da 500 G),
50 G Burro,
25 Cl Brodo,
25 Cl Vino Madera,
1 Pomodoro Pelato,
1 Cucchiaio Farina,
1 Cipolla,
1 Chiodo Di Garofano,
Alloro','Levare la cotenna al prosciutto e porlo in una pirofila con la cipolla tritata, il chiodo di garofano, l''alloro, il vino, il pomodoro a pezzi e il brodo. Infornare a 200 gradi. Cuocere finché il fondo di cottura sarà ristretto e il prosciutto colorito. Levare dal forno e tagliarlo a fette spesse. Diluire il burro intriso di farina con 2 cucchiai di brodo e versare questa salsa sul prosciutto.',3033);
INSERT INTO "ricette" VALUES (19867,'Prosciutto Al Marsala','Antipasto','Vino Marsala',4,' -','4 Fette Prosciutto Cotto (fette Alte 1/2 Cm),
Burro,
Vino Marsala,
Fecola Di Patate','Incidete le fette di prosciutto in giro con un coltellino. Mettete le fette a rosolare nel burro dalle due parti e aggiungete un sorso di marsala. Se volete potrete legare la salsettina unendovi un po'' di fecola prima stemperata in acqua fredda.',1890);
INSERT INTO "ricette" VALUES (19868,'Prosciutto Al Marsala (2)','Carne','Maiale',10,' -','1 Prosciutto Tipo Praga Di 3000 G,
6 Cucchiai Olio D''oliva,
80 G Burro,
1 Cipolla,
2 Carote,
2 Coste Sedano,
50 Cl Vino Marsala Secco,
Prezzemolo,
Sale,
Pepe,
Per La Salsa:,
10 Cl Vino Marsala Secco,
1 Cucchiaino Maizena,
20 Cl Brodo (o Acqua Calda),
Burro','Eliminate la cotenna e parte del grasso del prosciutto. Mettetelo in un recipiente che lo contenga di misura e irroratelo con il Marsala. Lasciatelo marinare per 6 ore, poi sgocciolatelo e legatelo con lo spago bianco da cucina. Tagliate a dadini la cipolla, le carote e il sedano. Tritate il prezzemolo. In una grande teglia scaldate l''olio e il burro e rosolatevi il prosciutto girandolo con precauzione da tutte le parti. Unite le verdure, salate e pepate. Passate il recipiente in forno preriscaldato a 180 gradi e cuocete per 3 ore bagnando di frequente il prosciutto sia con la marinata sia con il fondo di cottura. Toglietelo dalla teglia e tenetelo in caldo. Preparate la salsa: passate il fondo di cottura al passaverdure, versatelo in un tegame, aggiungete il restante liquido della marinata e il brodo caldo, fate bollire e ridurre un poco. Sciogliete la maizena in alcuni cucchiai d''acqua fredda, unitela alla salsa e appena questa tende ad addensarsi toglietela dal fuoco. Diluitela con il Marsala e insaporitela con una noce di burro mescolando con una piccola frusta. Slegate il prosciutto, tagliatelo a fette non troppo sottili, passatele su un piatto da portata e servitele ricoperte di salsa. Vini di accompagnamento: servire a tavola lo stesso vino impiegato nella cottura delle pietanze è una regola con molte eccezioni, come questa: Bramaterra DOC, Vino Nobile Di Montepulciano DOCG, Etna Rosso DOC.',17438);
INSERT INTO "ricette" VALUES (19869,'Prosciutto Al Tonno Gelatinato','Antipasto','Tonno',4,' -','8 Fette Prosciutto Crudo Dolce E Magro,
200 G Tonno,
1 Tazza Maionese,
1 Dado Per Gelatina','Fate la gelatina e lasciatela raffreddare, ma non addensare del tutto. Nel frattempo mettete in una larga ciotola il tonno sgocciolato dal suo olio e ben sbriciolato. Amalgamatelo bene con la maionese e poi ammorbidite il composto quanto basta unendo un po'' di gelatina. Tenete in frigo per mezz''ora. Quindi stendete bene le fettine di prosciutto crudo, spalmatele con il tonno gelatinato, arrotolate. Schiacciate un pochino gli involtini , disponeteli su un piatto da portata, versate sopra la gelatina avanzata e ponete in frigo il tempo necessario perché questa solidifichi. Servite',2682);
INSERT INTO "ricette" VALUES (19870,'Prosciutto Al Vino Bianco','Carne','Maiale',4,' -','8 Fette Spesse Prosciutto Cotto,
2 Bicchieri Vino Bianco Secco,
30 G Burro,
300 G Funghi,
1 Scalogno Piccolo,
1 Bicchiere Panna,
1 Cucchiaio Vino Porto Bianco (vino Bianco Porto),
Sale','Imburrate una pirofila piuttosto grande, disponetevi le fette di prosciutto e versatevi sopra la metà del vino. Coprite con un foglio d''alluminio e cuocete per 3 ore abbondanti in forno preriscaldato a 150 gradi facendo attenzione che il liquido non raggiunga assolutamente il bollore. In un tegame mettete i funghi a fettine, lo scalogno tritato e il restante vino. Portate a ebollizione, unite la panna e fate sobbollire. Aggiungete anche il sugo formatosi nel recipiente del prosciutto e lasciate ridurre fino a raggiungere la consistenza voluta. Profumate con il Porto. Regolate il sale. Disponete le fette di prosciutto sul piatto da portata, ricopritele con la salsa. Vini di accompagnamento: Franciacorta Brut DOCG, Collio Tocai DOC, Regaleali Nozze D''Oro VdT Di Sicilia.',3250);
INSERT INTO "ricette" VALUES (19871,'Prosciutto Alla Brace Glassato','Antipasto','Prosciutto Cotto',4,' -','Prosciutto Cotto Alla Brace,
Senape Dolce,
Miele,
Arancia,
Paprica,
Zenzero,
Curry In Polvere,
Chiodi Di Garofano,
Fecola,
1/2 Bicchiere Cognac,
Vino Bianco,
Sale,
Pepe,
Olio D''oliva','Fare delle incisioni sulla cotenna inserendo qualche chiodo di garofano. Mettere a cuocere il prosciutto in forno con olio, sale, pepe e vino bianco. A cottura completa, preparare una salsa con il fondo di cottura, lo zenzero, il curry il miele, la buccia d''arancia grattugiata, il brandy ed irrorarci il prosciutto tagliato a fette.',1925);
INSERT INTO "ricette" VALUES (19872,'Prosciutto Alla Crema','Antipasto','Prosciutto',4,' -','300 G Prosciutto Cotto A Fette Spesse,
150 G Fegatini Di Pollo,
1 Cucchiaino Amido Di Mais,
2 Cucchiai Pernod,
2 Bicchierini Brandy,
1 Dado,
30 G Burro,
Sale','Tagliate il prosciutto a listarelle e mettetele in una terrina; versatevi sopra un bicchierino di Brandy, mescolate e lasciate macerare per un''ora. Intanto mondate i fegatini e metteteli in una casseruolina: unite un bicchierino di Brandy, un mestolino di acqua, il Pernod e il dado sbriciolato e fate cuocere per una decina di minuti. Poi passate tutto al frullatore. Rosolate il prosciutto nel burro, unitevi la salsa al fegato, l''amido e cuocete per 5 minuti.',1983);
INSERT INTO "ricette" VALUES (19873,'Prosciutto Alla Griglia','Antipasto','Prosciutto Cotto',4,' -','4 Fette Prosciutto Cotto (fette Di 1 Cm Di Spessore),
1 Limone (succo),
1 Arancia (succo),
1/2 Bicchiere Vino Bianco,
1 Cucchiaio Senape,
Tabasco,
Burro','In una pirofila dai bordi alti, versate il succo del limone, il succo dell''arancia, il vino bianco, la senape e il tabasco. Subito dopo, immergete le fette di prosciutto lasciandole macerare per almeno 30 minuti e preparate una griglia che successivamente ungerete di burro e farete arroventare. Disponete le fette sulla griglia e cuocetele per pochi minuti fino a quando si formeranno sulla superficie di ambo le parti le consuete righe annerite. Toglietele dal fuoco e servitele subito calde.',1805);
INSERT INTO "ricette" VALUES (19874,'Prosciutto Alla Mostarda','Antipasto','Mostarda',4,' -','4 Fette Prosciutto Cotto (fette Alte 1/2 Cm),
Burro,
Besciamella,
Formaggio,
1 Cucchiaio Mostarda','Preparate le fette di prosciutto incidendole in giro con un coltellino, fatele rosolare nel burro e presentatele poi coperte di una besciamella piuttosto liquida cui, oltre al formaggio, avrete unito della mostarda, regolandone la dose secondo il vostro gusto.',2026);
INSERT INTO "ricette" VALUES (19875,'Prosciutto Alla Salsa Di Caffè','Antipasto','Prosciutto',4,' -','40 G Farina,
40 G Burro,
50 Cl Latte,
1 Presa Sale,
1 Presa Zucchero,
25 G Mostarda,
2 Cucchiai Caffè Forte,
750 G Prosciutto Crudo,
6 Uova Sode','Mescolare 40 g di farina, 40 g di burro e 50 cl di latte, aggiungere una abbondante presa di sale ed una di zucchero, 25 g di mostarda, due cucchiaiate di caffè forte. Ora versare la salsa approntata in una pirofila, dove saranno disposti 750 g di prosciutto tagliato in piccoli quadratini e sei uova sode tagliate a fette. Collocare la pirofila a bagnomaria fino al momento di servire.',4563);
INSERT INTO "ricette" VALUES (19876,'Prosciutto Con Peperoni E Pompelmo','Antipasto','Peperoni',4,' -','80 G Prosciutto Cotto Magro (fette Da 80 G),
100 G Melone,
1/2 Peperone (70 G),
1/2 Cipolla,
1 Pomodoro (100 G),
1/2 Bicchiere Latte Magro (5 Cl),
10 G Farina,
10 G Burro,
1 Pizzico Paprica,
Sale','Lavare e tritare le verdure. Sbucciare e tagliare a cubetti il melone. Preparare una besciamella con il burro, la farina e il latte. Unire alla salsa le verdure tritate. Salare, aggiungere la paprica e versare il tutto sul prosciutto aggiungendo il melone.',530);
INSERT INTO "ricette" VALUES (19877,'Prosciutto Con Salsa Di Funghi','Antipasto','Prosciutto Cotto',4,' -','100 G Funghi Secchi,
200 G Prosciutto Cotto,
80 G Burro,
40 G Farina,
2 Bicchieri Latte,
Sale,
Pepe,
Noce Moscata,
1/2 Bicchiere Panna,
50 G Formaggio Emmenthal,
3 Uova,
1 Cipollina,
1 Spicchio Aglio,
1/2 Bicchiere Vino Bianco,
1/2 Bicchiere Brodo Di Pollo,
1 Cucchiaio Salsina Di Pomodoro','Mettete i funghi a rinvenire in acqua tiepida. Passate il prosciutto al tritacarne, raccogliendolo in una ciotola. Preparate una besciamella: fate fondere 40 g di burro in una casseruola e stemperatevi la farina, mescolando con un cucchiaio di legno per eliminare eventuali grumi; diluite lentamente con il latte caldo, insaporite con una presa di sale e un pizzico di pepe, aromatizzate con un pochino di noce moscata grattugiata, quindi lasciate cuocere per 10 minuti, senza mai smettere di rimestare. Togliete dal fuoco la besciamella e incorporatevi il passato di prosciutto, la panna, l''Emmenthal grattugiato e le uova. Rimestate accuratamente il composto e rovesciatelo in uno stampo da budino con il foro centrale e le pareti lisce, che avrete già imburrato. Sbattete un po'' lo stampo sul tavolo per eliminare eventuali vuoti d''aria interni. Cuocete in forno, a bagnomaria, per 30 minuti, a una temperatura costante di 200 gradi. Nel frattempo preparate la salsa di funghi: tritate finemente la cipolla e l''aglio e poneteli ad appassire in un tegame con il burro rimasto; unite i funghi, precedentemente lavati, strizzati, e triturati, e fateli rosolare per qualche minuto; poi irrorate con il vino bianco e, quando questo sarà evaporato del tutto, regolate di sale e pepe; bagnate quindi con il brodo caldo, nel quale avrete sciolto la salsina di pomodoro. Lasciate cuocere per 20 minuti, a fiamma dolce. Trascorso il tempo convenuto, estraete lo stampo dal forno, asciugatelo e capovolgetelo sul piatto da portata. Rovesciate all''interno dello sformato i funghi con il loro intingolo e servite.',2619);
INSERT INTO "ricette" VALUES (19878,'Prosciutto Crudo Alla Melagrana','Antipasto','Melagrana',4,' -','300 G Prosciutto Crudo (fette Da 300 G),
2 Melagrane,
2 Porri,
4 Cucchiai Gelatina Di Ribes,
1 Limone (scorza Grattugiata),
1 Arancia (scorza Grattugiata),
3 Cucchiai Vino Porto,
Pepe Di Caienna','Lasciate il prosciutto a temperatura ambiente per circa 2 ore e tagliatelo a dadi. Spremete 1 melagrana con lo spremiagrumi e sgranate i chicchi della seconda. Scaldate la gelatina di ribes con il succo della melagrana, unite il Porto e un pizzico di pepe di Caienna. Aggiungete i porri affettati e fate rosolare a fuoco dolce. Togliete dal fuoco e unite i chicchi di melagrana e le scorze di limone e arancia. Mettete i dadi di prosciutto su un piatto da portata, coprite con la salsa e servite tiepido.',1889);
INSERT INTO "ricette" VALUES (19879,'Prosciutto Di Maiale','Carne','Maiale',4,' -','1 Coscia Di Maiale Appena Macellata,
Sale Grosso,
Pepe,
Alcune Foglie Alloro,
Sugna','Prendete una coscia appena macellata, premetela fate ne uscire tutto il sangue e strofinatela con sale grosso e pepe. Adagiatela su un tavolo di legno cosparso di sale e versate altro sale sulla carne. Ripetete questa operazione dello strofinamento ogni 2-3 giorni per circa un mese. Dopo questo tempo asciugate il prosciutto con un telo pulito, strofinatelo questa volta con pepe e foglie di alloro macinate e rimettetelo sul piano di legno, pressatelo con un altro piano di legno con dei pesi sopra. Lasciate così ancora per una settimana, dopodichè toglietelo, riempite eventuali crepe con sugna e pepe e appendetelo in un luogo fresco e ben aerato. Occorre aspettare qualche mese prima di gustarlo.',3906);
INSERT INTO "ricette" VALUES (19880,'Prosciutto Di Maiale Al Latte','Carne','Maiale',4,' -','1000 G Prosciutto Di Maiale (pezzi Da 1000 G),
150 Cl Latte,
10 Cl Olio D''oliva,
50 G Burro,
1 Cipolla,
Sale,
1/2 Bicchiere Vino Bianco,
1 Foglia Alloro','Legare il prosciutto e disporlo in un tegame con olio, burro, latte e cipolla affettata. Salare e cuocere per 2 ore circa. Quando il liquido sarà consumato quasi del tutto, bagnare con il vino e lasciare rosolare. Servire il prosciutto affettato con il suo sugo di cottura.',6809);
INSERT INTO "ricette" VALUES (19881,'Prosciutto Di Maiale Con Tacchino E Ananas','Antipasto','Prosciutto Di Maiale',4,' -','300 G Prosciutto Di Maiale,
300 G Macinato Di Tacchino,
1/2 Scalogno,
1 Uovo,
1 Ananas,
Formaggio Parmigiano,
Aglio,
Rosmarino,
Timo,
Sale,
Pepe,
Zucchero,
Birra','Salare, pepare e cuocere poco il prosciutto a fette. Insaporire il macinato con le spezie, parmigiano e uova e saltare in padella. Mettere 1 fetta di prosciutto in una pirofila, porvi il tacchino, quindi ricoprire con un''altra fetta di prosciutto e infornare per 15 minuti a 200 gradi. Saltare in padella con zucchero e birra l''ananas a cubetti e guarnire.',2816);
INSERT INTO "ricette" VALUES (19882,'Prosciutto Di Maialino Glassato','Carne','Maialino',4,' -','1750 G Prosciutto Di Maialino Già Cotto,
1 Cucchiaio Miele,
2 Cucchiai Vino Da Dessert (traiminer O Rotgipfler)','Tagliate via la cotica dal prosciutto, eliminate il grasso ed eventualmente disossate. Lasciate cuocere nel forno con poco liquido per circa 45 minuti, ungete con il ''vino al miele'' e regolate il forno al massimo, facendo prendere colore al prosciutto per 15 minuti circa, dopodichè diminuite la temperatura e continuate la cottura per altri 15 minuti.',7695);
INSERT INTO "ricette" VALUES (19883,'Prosciutto Farcito Alla Brace','Carne','Maiale',4,' -','Prosciutto Di Maiale Disossato,
200 G Speck Di Cinghiale In Fette,
200 G Salame In Fette,
200 G Mortadella In Fette,
1 Guanciale Di Maiale,
200 G Formaggio Groviera,
200 G Pomodori Secchi,
200 G Fichi Secchi,
200 G Paté Di Olive Nere,
Sale,
Pepe,
Rosmarino,
Salvia','Ricavare una tasca dal prosciutto e dopo averla salata e pepata, farcirla con tutti gli ingredienti citati. Cucinare e legare il prosciutto e cospargerlo con sale, pepe e spezie, passandolo in forno a 200 gradi considerando che per ogni 1000 g occorrerà 1 ora circa di cottura.',5120);
INSERT INTO "ricette" VALUES (19884,'Prosciutto Gustoso','Carne','Maiale',4,' -','4 Fette Prosciutto Cotto Di Maiale,
1 Cipolla,
20 G Farina,
1/2 Bicchiere Vino Marsala,
1 Dado,
40 G Burro,
3 Cucchiai Olio D''oliva,
Sale,
Pepe,
Noce Moscata','Fate rosolare il prosciutto in olio e burro, scolatelo e tenetelo in caldo. Nello stesso condimento fate appassire la cipolla tritata, unite del brodo, la farina e fate cuocere: la salsa dev''essere densa; passatela al setaccio. Aggiustate di sale, pepate, profumate con la noce moscata e aggiungete, poco alla volta, il marsala. Mettete nella salsa il prosciutto e lasciate insaporire.',2434);
INSERT INTO "ricette" VALUES (19885,'Prosciutto In Crosta','Antipasto','Prosciutto',4,' -','8 Fette Prosciutto Cotto Magro,
300 G Pasta Sfoglia,
30 Cl Besciamella,
2 Tuorli D''uovo,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Noce Moscata,
Sale,
Pepe','Preparate circa 30 cl di besciamella morbida (oppure utilizzate quella già pronta), unitevi un tuorlo, il parmigiano grattugiato, sale, pepe e noce moscata. Spalmate con la salsa fredda le fette di prosciutto e arrotolatele. Stendete la pasta sfoglia e ritagliate 8 rettangoli di dimensioni sufficienti ad avvolgere i cannelloni di prosciutto. Avvolgete ogni cannellone in uno dei rettangoli di pasta sfoglia, saldate bene le aperture con il secondo tuorlo d''uovo battuto, poi pennellate le superfici con il tuorlo d''uovo e cuocete in forno a 180 gradi per circa 20 minuti. Accompagnate gli involtini con verdura cotta o con una bella insalata verde.',3512);
INSERT INTO "ricette" VALUES (19886,'Prosciutto Melone E Fichi','Antipasto','Fichi',4,' -','Prosciutto,
Melone,
Fichi','Servite su un vassoio del prosciutto crudo insieme a fichi freschi e al melone ghiacciato e affettato.',564);
INSERT INTO "ricette" VALUES (19887,'Prosciutto Ricco Al Melone','Antipasto','Melone',4,'Preparazione: 15 minuti.','100 G Insalata Rucola,
1/2 Melone Maturo,
80 G Pane Casereccio,
100 G Prosciutto Crudo Di Montagna,
6 Gherigli Di Noci,
1 Cucchiaio Aceto Di Vino,
2 Cucchiai Olio D''oliva,
1/2 Cucchiaino Senape Forte,
Pepe Nero Al Macinino,
Sale','Prelevate tutta la polpa del melone e tagliatela a dadini, stando attenti a non perdere il succo che cola durante l''operazione. Per conservarlo basterà sistemare il tagliere sopra un grande piatto. Pulite e centrifugate delicatamente l''insalata. Eliminate dalle foglie grosse della rucola la parte più chiara dei gambi e riducetele tutte a striscioline. Scaldate 1 cucchiaio d''olio in una padella tenendo il fuoco alto e, quando la padella è ben calda, gettatevi il pane tagliato a dadini. Per fare in modo che il pane dori su tutti i lati, scuotete la padella ogni tanto. Tritate a pezzettoni i gherigli delle noci e tagliate il prosciutto a striscioline dopo aver eventualmente tolto il grasso. Mescolate in un piccolo recipiente l''olio rimasto, 2 cucchiai di succo di melone e gli ingredienti previsti dal condimento. Sistemate l''insalata in un piatto di portata oppure in 2 piatti fondi e distribuitevi sopra tutti gli altri ingredienti. Versate il condimento a filo e servite.',1556);
INSERT INTO "ricette" VALUES (19888,'Provola Ai Ferri','Contorno','Formaggio Provola Dolce',4,'Luogo: Ciociaria. Luogo: Lazio.','Formaggio Provola Dolce,
1 Cucchiaio Olio D''oliva Extra-vergine,
Pepe Nero Appena Macinato','Tagliate la provola a fette alte 1 cm, pennellatela con l''olio, pepate abbondantemente e cuocete le fette sulla griglia o in una padella appena unta, girandole non appena cominciano a fondere.',621);
INSERT INTO "ricette" VALUES (19889,'Provola Ai Ferri (2)','Contorno','Formaggio Provola Affumicata',4,'Luogo: Ciociaria. Luogo: Lazio.','Formaggio Provola Affumicata,
1 Cucchiaio Olio D''oliva Extra-vergine,
Pepe Nero Appena Macinato','Tagliate la provola a fette alte 1 cm, pennellatela con l''olio, pepate abbondantemente e cuocete le fette sulla griglia o in una padella appena unta, girandole non appena cominciano a fondere.',621);
INSERT INTO "ricette" VALUES (19890,'Provola Con Patate','Contorno','Formaggio Provola Affumicata',4,' -','600 G Patate,
250 G Formaggio Provola Affumicata,
2 Cucchiai Erba Cipollina Tritata,
4 Cucchiai Aceto Di Vino,
1/2 Bicchiere Olio D''oliva,
1 Presa Sale','Lavare le patate, togliendo bene la terra poi lessarle con la buccia in acqua salata per circa 40 minuti. Scolarle, lasciarle raffreddare, sbucciarle e affettarle. Togliere la pelle alla provola, tagliarla a fettine e unirla alle patate. In una terrina mescolare l''aceto con 1 presa di sale, l''olio e l''erba cipollina. Emulsionare bene e versare il condimento sull''insalata di patate, mescolando.',1991);
INSERT INTO "ricette" VALUES (19891,'Provolino','Bevande','Brandy',1,' -','2/6 Succo Di Pompelmo,
1/6 Cordial,
3/6 Brandy,
2 Gocce Granatina,
Per Servire:,
1 Fetta Pompelmo,
1 Scorza Di Limone','Agitare nello shaker con poco ghiaccio in cubetti. Servire nel calice panciuto, con una fetta di pompelmo e una scorza di limone.',274);
INSERT INTO "ricette" VALUES (19892,'Provolo','Bevande','Brandy',1,' -','2/6 Succo Di Pompelmo,
1/6 Cordial,
3/6 Brandy,
2 Gocce Granatina,
Per Servire:,
1 Fetta Pompelmo,
1 Scorza Di Limone','Agitare nello shaker con poco ghiaccio in cubetti. Servire nel calice panciuto, con una fetta di pompelmo e una scorza di limone.',274);
INSERT INTO "ricette" VALUES (19893,'Provolone Alla Piastra','Antipasto','Formaggio Provolone',4,' -','8 Fette Formaggio Provolone (fette Da 80 G),
1 Rametto Rosmarino,
1 Rametto Salvia,
2 Spicchi Aglio,
1 Rametto Prezzemolo,
3 Cucchiai Olio D''oliva,
1/2 Limone (succo),
Sale,
Pepe','Il modo per preparare questo piatto, sarebbe la cottura alla brace, ma in mancanza di questa andrà benissimo anche la bistecchiera di ghisa. Innanzitutto, ponete la bistecchiera sul fuoco ad arroventarsi. Nel frattempo tritate le erbe, il prezzemolo e poneteli in una ciotola. Salate leggermente, pepate abbondantemente, quindi unite il succo di limone e l''olio. Sbattete vigorosamente con la forchetta fino ad ottenere un composto ben emulsionato. Prendete una fetta di provolone per volta e ponetela sulla bistecchiera, aspettate pochi secondi, quindi, con una spatola girate la fetta di formaggio dall''altro lato. Disponete, a mano a mano, le fette di provolone sul piatto di portata e quando saranno tutte cotte irroratele con la salsina alle erbe. Servite come se fosse un normale companatico, con insalata di stagione.',3570);
INSERT INTO "ricette" VALUES (19894,'Provolone Impanato','Antipasto','Formaggio Provolone',4,' -','8 Fette Formaggio Provolone Dolce,
2 Uova,
Farina,
Pangrattato,
Paprica Dolce,
Sale,
Pepe,
Olio D''oliva','Togliete la buccia alle fette di provolone, passatele nella farina, poi nelle uova sbattute e salate, quindi nel pangrattato mescolato a due o tre pizzichi di paprica dolce. Friggete le fette in abbondante olio bollente, asciugatele su carta assorbente, insaporitele ancora con un pizzichino di paprica e servitele calde',4050);
INSERT INTO "ricette" VALUES (19895,'Prugne Al Limone','Dessert','Prugne Secche Giganti',4,' -','400 G Prugne Secche Giganti,
1 Bicchiere Vino Bianco Secco,
1 Limone (scorza Grattugiata),
4 Cucchiai Zucchero','Mettere le prugne in una terrina, coprirle di acqua e lasciarle ammollare fino a quando si saranno gonfiate. Scolarle, metterle in una casseruola, unirvi il vino bianco, lo zucchero, la scorza grattugiata del limone e cuocere a fiamma bassa e a recipiente coperto per circa 20 minuti. Disporre le prugne in una coppa e servirle.',986);
INSERT INTO "ricette" VALUES (19896,'Prugne Al Naturale','Dessert','Prugne',4,' -','Prugne Non Mature,
Acqua,
5 G Sale Per Ogni 1000 G Di Frutta,
1 Cucchiaio Zucchero Per Ogni Barattolo Di Frutta','Fate, con un ago, una decina di fori sulle prugne e mettetele in una pentola con acqua e fatele scaldare finché la frutta non salga in superficie; aggiungete 5 g di sale per ogni 1000 g di frutta e lasciate riposare 1 ora. Togliete le prugne e mettetele nei barattoli aggiungendo 1 cucchiaio di zucchero. Chiudete ermeticamente.',166);
INSERT INTO "ricette" VALUES (19897,'Prugne Al Prosciutto','Antipasto','Prugne Secche',4,'Preparazione: 15 minuti. Cottura: 5 minuti. Calorie: 226.','8 Prugne Secche Snocciolate,
80 G Prosciutto Cotto,
50 G Burro','Tagliate il prosciutto a striscioline e avvolgetele alle prugne, fermandole con stecchini di legno. In una padella antiaderente fate rosolare gli involtini finché non sono dorati. Disponeteli su un piatto da portata insieme con dell''insalatina. Questo piatto deve essere servito ben caldo. Può essere anche preparato con pochi minuti di cottura nel forno a microonde.',989);
INSERT INTO "ricette" VALUES (19898,'Prugne Al Vino','Dessert','Prugne',6,' -','1000 G Prugne,
75 Cl Vino Rosato Dolce,
125 G Zucchero,
Cannella,
1/2 Limone (scorza Sottile)','Lavate e sgocciolate le prugne. Snocciolatele. In una casseruola mescolate il vino, la cannella, lo zucchero, aggiungete la buccia sottile di mezzo limone e portate piano a ebollizione. Immergete le prugne nel vino aromatizzato e fate cuocere per 10 minuti dopo la ripresa del bollore. Versate il tutto in una coppa di cristallo, lasciate raffreddare, poi tenete in frigorifero sino al momento di servire a tavola.',1286);
INSERT INTO "ricette" VALUES (19899,'Prugne Alla Grappa','Dessert','Prugne',6,' -','1 Scatola Prugne Secche,
1 Bottiglia Grappa,
1 Stecca Vaniglia','Lavate le prugne in acqua tiepida, sgocciolatele, asciugatele con cura, sistematele a strati in un vaso di vetro a chiusura ermetica. Fra uno strato e l''altro spezzettate la vaniglia. Versate tanta grappa quanta ne occorre per coprire la frutta, chiudete bene il coperchio. Applicate una etichetta adesiva con la data del giorno e riponete il barattolo in luogo asciutto. Le prugne saranno pronte dopo due mesi. Servitele con gelato alla crema o con lo zabaglione caldo.',2700);
INSERT INTO "ricette" VALUES (19900,'Prugne Con Gelato E Panna','Dessert','Prugne',4,' -','500 G Prugne,
75 G Zucchero,
1 Bustina Zucchero Vanigliato,
Panna Montata,
1 Cucchiaino Zucchero A Velo,
Gelato Di Banana (o Gelato Di Zabaglione),
4 Ciliegine (facoltativo)','Scottate le prugne in acqua a bollore, sbucciatele, dividetele e togliete il nocciolo. Disponetele in una pentola, copritele con lo zucchero e lo zucchero vanigliato; mescolate e lasciate insaporire. Montate la panna, incorporatevi un cucchiaino di zucchero a velo e di volta in volta riempite una siringa per dolci. In quattro coppette di vetro mettete sul fondo alcune palline di gelato del gusto preferito e sopra le prugne; guarnite con ciuffetti di panna. Volendo aggiungete una ciliegina. Servite.',884);
INSERT INTO "ricette" VALUES (19901,'Prugne Cotte','Dessert','Prugne',4,' -','250 G Prugne,
50 G Zucchero,
10 Cl Acqua,
1 Chiodo Di Garofano,
1 Pezzetto Cannella,
1/2 Limone (succo E Scorza)','Cuocete l''acqua e lo zucchero insieme con gli odori, aggiungete le prugne disossate e tagliate a metà, continuate la cottura voltando continuamente finché la frutta è sfatta a metà e le bucce cominciano ad accartocciarsi.',296);
INSERT INTO "ricette" VALUES (19902,'Prugne Fredde Alla Cannella','Dessert','Prugne Secche',4,' -','400 G Prugne Secche,
2 Bicchieri Vino Bianco,
2 Cucchiai Zucchero,
1 Limone,
1 Cucchiaino Cannella In Polvere','Lavare bene le prugne, asciugarle, metterle in una terrina e spolverizzarle con lo zucchero e la cannella; unirvi qualche goccia di succo di limone e il vino e lasciarle macerare per un''intera notte. Il mattino seguente metterle in frigo e servirle poi a pranzo come dessert.',1070);
INSERT INTO "ricette" VALUES (19903,'Prugne Sciroppate','Dessert','Prugne',10,' -','2000 G Prugne Piccole,
450 G Zucchero,
1 Limone','Pulire le prugne strofinandole per bene con un canovaccio, punzecchiarle con un ago in cinque o sei punti, adagiarle in un recipiente e versarvi sopra dell''acqua bollente in modo da coprirle completamente. Lasciare nell''acqua fino a che questa diventi tiepida, sgocciolarle e tenere da parte un litro di questa acqua di infusione. Mettere le prugne ad asciugare al sole e non appena sono asciutte collocarle nei vasi. Nel frattempo preparate lo sciroppo versare l''acqua delle prugne in una casseruola, unirvi lo zucchero e portare ad ebollizione. Versare lo sciroppo ancora caldo nei vasi riempiendoli per 3/4 (le prugne stesse emetteranno molta acqua). Spremere in ogni vaso qualche goccia di succo di limone , chiudere ermeticamente i vasi e farli sterilizzare per 15-20 minuti. Conservare in luogo fresco.',2397);
INSERT INTO "ricette" VALUES (19904,'Prugne Secche Al Prosciutto','Antipasto','Prugne Secche',4,'Preparazione: 15 minuti. Cottura: 5 minuti. Calorie: 226.','8 Prugne Secche Snocciolate,
80 G Prosciutto Cotto,
50 G Burro','Tagliate il prosciutto a striscioline e avvolgetele alle prugne, fermandole con stecchini di legno. In una padella antiaderente fate rosolare gli involtini finché non sono dorati. Disponeteli su un piatto da portata insieme con dell''insalatina. Questo piatto deve essere servito ben caldo. Può essere anche preparato con pochi minuti di cottura nel forno a microonde.',989);
INSERT INTO "ricette" VALUES (19905,'Prugne Sott''aceto','Contorno','Prugne',4,' -','3000 G Prugne Mature,
100 Cl Aceto Di Vino,
1000 G Zucchero,
4 Chiodi Di Garofano,
1/2 Bastoncino Cannella,
1 Pezzetto Scorza Di Limone','Lavare le prugne e forarle con un ago. Portare a lenta ebollizione l''aceto con lo zucchero, chiodi di garofano, scorza di limone e cannella. Unire le prugne e cuocerle piano fino a quando inizieranno a raggrinzirsi. Estrarle e bollire il liquido per altri 20 minuti, unire di nuovo le prugne e, dopo pochi minuti, versare il tutto in vasi di vetro, far raffreddare, quindi chiudere ermeticamente. Si accompagna a carni fredde o di maiale.',4909);
INSERT INTO "ricette" VALUES (19906,'Prugne Sotto Spirito','Dessert','Prugne',4,' -','350 G Zucchero,
100 Cl Alcool (grappa),
2000 G Prugne','Prendo un tipo di prugne blu appena più grosse che grosse olive, bellissime e mature. Mescolo 350 g di zucchero in un litro d''alcool (prendo una grappa) e lascio allo zucchero il tempo di fondere. Lavo e asciugo (o lascio asciugare) le prugne (2000 g). Lavo dei boccali di vetro. Ci metto le prugne dopo aver punto ogni prugna con un ago, in 2 o 3 posti (per evitare che la buccia si fenda). Aggiungo l''alcool, quanto per bagnare le prugne, fino all''orlo del boccale. Chiudo bene e aspetto almeno 3 mesi, senza aprire poiché c''è un periodo di fermentazione.',4470);
INSERT INTO "ricette" VALUES (19907,'Prugne Valligiane','Dessert','Prugne Secche',4,'Luogo: Valle D''aosta.','20 Prugne Secche Denocciolate,
20 Fettine Lardo D''arnad','Mettere a bagno le prugne secche in poca acqua tiepida e lasciarle ammollare per circa 30 minuti fino a quando si saranno ammorbidite e gonfiate. Scolarle e asciugarle bene con un canovaccio pulito. Avvolgere ogni prugna in una fettina di lardo. Fermare il tutto con uno stecchino di legno e passare in forno caldo 10 minuti.',4416);
INSERT INTO "ricette" VALUES (19908,'Pseudo-manhattan','Bevande','Whisky',1,' -','1/2 Vermouth Rosso Non Troppo Dolce,
1/2 Irish Whisky,
2 Gocce Angostura,
1 Spruzzo Limone,
1/2 Cucchiaino Zucchero,
1 Ciliegina Al Maraschino,
1 Cubetto Ghiaccio Cristallino','Miscelare il tutto. Il cocktail differisce dal Manhattan originale per l''Irish al posto del Canadian e per il cucchiaino di zucchero che rendono ''apparentemente'' più leggero il cocktail. Provate però a prenderlo 15 minuti prima di cena e vedrete questi piccoli cambiamenti che fame produrranno.',346);
INSERT INTO "ricette" VALUES (19909,'Puccia','Primo','Farina Di Mais',4,' -','300 G Farina Di Mais,
1/2 Cavolo,
300 G Carne Di Maiale Grassa,
1 Spolverata Formaggio Parmigiano Grattugiato,
Sale,
1 Macinata Pepe In Grani','Pulite, lavate a pezzetti il cavolo; tagliate la carne di maiale a dadini. Disponete il tutto in una pentola con 150 cl d''acqua salata e portate a ebollizione, facendo cuocere per mezzora. Infine versate la farina di mais a pioggia e, rimestando con il cucchiaio di legno, cuocete per altri 45 minuti. Servite la polenta bollente completando con una spolverata di parmigiano grattugiato e una macinata di pepe.',2402);
INSERT INTO "ricette" VALUES (19910,'Puccini New Fashion','Bevande','Vino Spumante Brut',1,' -','2/3 Vino Spumante Brut,
1/3 Succo Di Mandarino,
1 Spruzzo Vodka-mandarino Artic','Versate il succo di mandarino nella flute, aggiungete 2/3 cucchiaini di Vodka-Mandarino (freddissima, possibilmente tenuta precedentemente nel freezer per almeno 30 minuti), infine versate lo Spumante ben raffreddato.',143);
INSERT INTO "ricette" VALUES (19911,'Puccini New Fashion (2)','Bevande','Vino Spumante Brut',1,' -','2/3 Vino Spumante Brut,
1/3 Succo Di Mandarancio,
1 Spruzzo Vodka-sottobosco Artic','Versate il succo di mandarancio nella flute, aggiungete 2/3 cucchiaini di Vodka-Sottobosco (freddissima, possibilmente tenuta precedentemente nel freezer per almeno 30 minuti), infine versate lo Spumante ben raffreddato.',139);
INSERT INTO "ricette" VALUES (19912,'Pudding Di Formaggio','Antipasto','Formaggio Cheddar',4,' -','250 G Formaggio Cheddar Grattugiato,
150 G Pangrattato,
25 Cl Latte Bollente,
2 Uova Sbattute,
1 Cucchiaino Senape Inglese In Polvere,
Sale,
Pepe,
Per La Pirofila:,
Poco Burro','Mettete in una terrina il pangrattato e il formaggio; mescolateli bene, aggiungete quindi il latte, le uova sbattute, il pepe, il sale e la senape. Imburrate una pirofila a bordi alti, versatevi il composto e passate in forno caldo (200  gradi) per 40 minuti circa, o fino a quando la superficie del pudding sarà ben dorata. Servite subito nello stesso recipiente di cottura. Variante: potete rendere il pudding più leggero e simile a un soufflé unendo prima i tuorli sbattuti, poi gli albumi montati a neve.',1979);
INSERT INTO "ricette" VALUES (19913,'Pudding Di Formaggio (2)','Antipasto','Formaggio Gouda',4,' -','250 G Formaggio Gouda Grattugiato,
150 G Pangrattato,
25 Cl Latte Bollente,
2 Uova Sbattute,
1 Cucchiaino Senape Inglese In Polvere,
Sale,
Pepe,
Per La Pirofila:,
Poco Burro','Mettete in una terrina il pangrattato e il formaggio; mescolateli bene, aggiungete quindi il latte, le uova sbattute, il pepe, il sale e la senape. Imburrate una pirofila a bordi alti, versatevi il composto e passate in forno caldo (200  gradi) per 40 minuti circa, o fino a quando la superficie del pudding sarà ben dorata. Servite subito nello stesso recipiente di cottura. Variante: potete rendere il pudding più leggero e simile a un soufflé unendo prima i tuorli sbattuti, poi gli albumi montati a neve.',1847);
INSERT INTO "ricette" VALUES (19914,'Pudding Di Formaggio (3)','Antipasto','Formaggio Emmenthal Stagionato',4,' -','250 G Formaggio Emmenthal Stagionato Grattugiato,
150 G Pangrattato,
25 Cl Latte Bollente,
2 Uova Sbattute,
1 Cucchiaino Senape Inglese In Polvere,
Sale,
Pepe,
Per La Pirofila:,
Poco Burro','Mettete in una terrina il pangrattato e il formaggio; mescolateli bene, aggiungete quindi il latte, le uova sbattute, il pepe, il sale e la senape. Imburrate una pirofila a bordi alti, versatevi il composto e passate in forno caldo (200  gradi) per 40 minuti circa, o fino a quando la superficie del pudding sarà ben dorata. Servite subito nello stesso recipiente di cottura. Variante: potete rendere il pudding più leggero e simile a un soufflé unendo prima i tuorli sbattuti, poi gli albumi montati a neve.',1952);
INSERT INTO "ricette" VALUES (19915,'Pudding Di Limone','Dessert','Limoni',4,' -','150 G Farina,
125 G Frutti Di Bosco,
100 G Zucchero,
50 G Burro,
15 Cl Latte,
2 Cl Sciroppo D''acero,
3 Limoni,
2 Uova,
1 Bustina Lievito Per Dolci','Scongelate i frutti di bosco. In una terrina sbattete i tuorli con lo zucchero, ottenendo un composto bianco e spumoso. Dopodichè incorporate in quest''ordine il burro fuso freddo, il succo di 2 limoni e la scorza grattugiata di mezzo, la farina miscelata con il lievito e infine il latte. Imburrate e infarinate una tortiera dai bordi alti, disponete sul fondo circa la metà dei frutti di bosco con tre fettine di limone. Irrorate il tutto con 2 cucchiai di sciroppo d''acero (oppure con 2 cucchiai di sciroppo, ottenuto con 2 cucchiai di zucchero e uno di acqua, scaldati sul fuoco per pochi istanti). Incorporate al composto precedentemente preparato gli albumi montati a neve ben ferma, mescolando con una forchetta dall''alto verso il basso e viceversa, affinché non si smontino. Versate il tutto nello stampo sopra i frutti di bosco e cuocete in forno già caldo a 180 gradi per circa 40 minuti. Lasciate intiepidire il dolce prima di sformarlo. Servitelo tiepido o freddo, decorato con i rimanenti frutti di bosco e con fettine molto sottili di limone.',1699);
INSERT INTO "ricette" VALUES (19916,'Pudding Di Natale','Dessert','Mandorle',4,' -','150 G Mandorle,
150 G Uvetta Sultanina,
1 Limone,
1 Arancia,
4 Uova,
50 Cl Latte,
100 G Pangrattato,
1 Bicchierino Brandy,
Alcune Zollette Zucchero,
Frutta Candita,
30 G Farina','Spellate le mandorle e mettetele in acqua bollente, tritatele e tagliate a dadini la frutta candita. Nel frattempo mettete l''uvetta in acqua tiepida in modo che possa rinvenire. Fate un impasto con farina, zucchero, frutta candita, il succo e la buccia di un limone, il succo e la buccia dell''arancia. Dovete incorporare bene il tutto in modo che quello che otterrete sia un composto ben liscio; quindi fate riposare per una buona mezz''ora. A questo punto all''impasto così ottenuto aggiungerete 4 uova, il latte, un bicchierino di brandy e il pangrattato. Mescolate accuratamente in modo d''incorporare bene tutti questi ultimi ingredienti. Lasciate riposare il tutto per una notte intera. La mattina successiva prendete uno stampo da dolce, spolverizzate con il pangrattato e versatevi il composto preparato. Chiudete il tutto con della carta metallizzata e cuocete a bagnomaria per circa 4 ore e mezza. A cottura ultimata fate raffreddare un poco e mettete in frigo. Al momento di servire tiratelo fuori dal frigo, e mettetelo su di un piatto e guarnite con zollette di zucchero.',2874);
INSERT INTO "ricette" VALUES (19917,'Pudding Di Savoiardi','Dessert','Biscotti Savoiardi',4,' -','150 G Biscotti Savoiardi,
50 Cl Latte,
50 G Uvetta Sultanina,
50 G Canditi,
80 G Zucchero,
3 Uova','Preparare la crema lavorando le uova intere con lo zucchero, e quando saranno ben sbattute versarvi il latte caldo. Prendere uno stampo liscio e alto e foderarlo con la carta forno; sul fondo disporre uno strato di savoiardi, poi su questo cospargere un po'' di uvetta e canditi, poi continuare così facendo altri strati fino ad esaurimento degli ingredienti. Versare nello stampo la crema preparata, in modo che i biscotti si imbevano bene, e quando sarà tutta assorbita e i biscotti si saranno gonfiati, passare lo stampo a bagnomaria e poi in forno, dove la cottura dovrà essere portata avanti sino a quando la crema non si sarà addensata.',1710);
INSERT INTO "ricette" VALUES (19918,'Pudin De Coco','Dessert','Polpa Di Cocco Grattugiata',4,'Luogo: Colombia.','4 Tazze Latte,
1 1/4 Tazza Zucchero,
1/2 Tazza Polpa Di Cocco Grattugiata,
3/4 Tazza Maizena,
1/2 Stecca Cannella','In un tegame mescolate metà del latte con lo zucchero, la polpa di cocco e la cannella e portate ad ebollizione mescolando accuratamente. In un tegame a parte sciogliete il latte rimanente con la maizena quindi versate il latte e la polpa di cocco della preparazione precedente. Trasferite il composto sul fuoco e continuate a mescolare finché inizierà a rapprendersi (10 minuti circa). Prelevate il ''palito'' di cannella, trasferite il budino in coppe individuali che lascerete raffreddare e refrigerare prima di servirle.',936);
INSERT INTO "ricette" VALUES (19919,'Puff','Bevande','Cognac',1,' -','1/3 Latte,
1/3 Soda,
1/3 Cognac','Preparare direttamente nel tumbler ampio, con alcuni cubetti di ghiaccio, mescolando dolcemente.',158);
INSERT INTO "ricette" VALUES (19920,'Pulcinella','Bevande','Gin',1,' -','1/4 Gin Dry,
1/4 Cherry Brandy,
1/4 Vermouth Dry,
1/4 Triple Sec','Si prepara nello shaker con ghiaccio in cubetti.',290);
INSERT INTO "ricette" VALUES (19921,'Pulcinella (2)','Bevande','Kirsch',1,' -','1/3 Crema De Cassis,
2/3 Kirsch','Mescolare, con alcuni cubetti di ghiaccio, nel mixer. Servire nel calice basso.',240);
INSERT INTO "ricette" VALUES (19922,'Pulcinella (3)','Bevande','Whisky',1,' -','1/3 Whisky,
1/3 Vermouth Dry,
1/3 Vermouth Rosso,
4 Cubetti Ghiaccio,
2 Gocce Angostura,
Per Guarnire:,
3 Olive Verdi','Mescolate gli ingredienti, direttamente nel tumbler, con un lungo cucchiaino non prima di aver aggiunto le due gocce di angostura. Guarnite il tumbler con uno stecchino con 3 olive verdi infilzate.',306);
INSERT INTO "ricette" VALUES (19923,'Pulpo Al Vino Blanco','Pesce','Polipo',4,'Luogo: Messico.','200 G Pomodori Pelati Privati Dei Semi E Tritati,
100 G Cipolla Tritata Fine,
50 Cl Vino Bianco,
500 G Polipo,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Far bollire il polipo pulito in acqua bollente per circa 10 minuti; scolarlo e tagliarlo in pezzi grandi come un boccone. Scaldare l''olio in una padella, unire la cipolla e i pomodori e soffriggere senza far colorire. Aggiungere quindi il polipo, spruzzare con il vino, alzare la fiamma e cuocere su fuoco vivo finché tutto il vino sarà evaporato. Ridurre quindi il fuoco e terminare la cottura.',2128);
INSERT INTO "ricette" VALUES (19924,'Puls','Primo','Farina Di Farro',4,' -','500 G Farina Di Farro Per Puls,
Pomodoro In Conserva,
Sale,
1 Filo Olio D''oliva Extra-vergine','Mettere sul fuoco circa 150 cl d''acqua leggermente salata, quando l''acqua è calda ma non bollente, cospargere a pioggia la farina di farro e contemporaneamente mescolare con una paletta di legno. Far cuocere la polenta per circa 20 minuti. Continuando a girare in modo da non creare grumi. Mettere il pomodoro in conserva nella polenta, che non dovrà essere densa, e mescolare. Servire aggiungendo un filo di olio d''oliva extra-vergine.',2033);
INSERT INTO "ricette" VALUES (19925,'Pumpernickel','Antipasto','Segale',4,'Luogo: Danimarca.','200 Cl Acqua,
25 G Lievito,
700 G Farina Di Frumento,
650 G Farina Di Segale,
600 G Grano Di Segale,
2 Cucchiai Sale,
Burro','La preparazione del pane richiede due giorni. Primo giorno: Mescolate mezzo litro di acqua tiepida, 25 g di lievito, 700 g di farina di frumento, 150 g di di farina di segale e 600 g di grano di segale. Lasciate riposare l''impasto ottenuto per circa 24 ore. Secondo giorno: Aggiungete mezzo litro di acqua tiepida, due cucchiai di sale, 500 g di farina di segale e mescolate il tutto. Mettete l''impasto in una teglia imburrata. Lasciate riposare per 6 ore. Fate cuocere in forno per un''ora e mezza a 200 gradi.',6955);
INSERT INTO "ricette" VALUES (19926,'Punch Al Rum','Bevande','Rum',4,' -','250 G Zucchero,
50 Cl Rum,
1 Scorza Di Limone,
1 Arancia','Fare sciogliere sul fuoco in una casseruola 250 g di zucchero in un litro di acqua Fare bollire e, quando la superficie dello sciroppo comincerà a incresparsi, levare dal fuoco. Versare 50 cl di rum di buona marca, ed unirvi la buccia di un limone o di una arancia tagliata a fette. Fare riprendere il bollore per qualche istante. Servire molto caldo dentro bicchieri larghi.',2189);
INSERT INTO "ricette" VALUES (19927,'Punch Alla Romana','Bevande','Arancia',4,'Luogo: Lazio. Luogo: Roma.','1 Arancia,
1 Limone,
2 Bicchieri Vino Spumante Frascati Tipo Brut,
2 Albumi D''uovo,
1/2 Bicchiere Acqua,
1/2 Bustina Zucchero Vanigliato,
2 Bicchierini Rum,
Per Guarnire:,
8 Ciliegine Sotto Spirito','Dopo aver lavato ed asciugato le arance ed i limoni, tagliarne la scorza a strisce molto sottili e spremerne tutto il succo, facendolo passare al colino. Mescolare il vino e metà dello zucchero in una casseruola da mettere sul fuoco facendo bollire il composto, a fuoco moderato, per 6-7 minuti. Togliere la casseruola dal fuoco, aggiungere le scorze degli agrumi e lasciare riposare per circa un ora, quindi aggiungere il succo di arance e limoni e versare il composto in una gelatiera. Conservare nel freezer facendo gelare. Nel frattempo montare gli albumi a neve in una terrina. Versare in un tegamino lo zucchero rimasto e aggiungere l''acqua, mettere sul fuoco e fare sciogliere dando la consistenza di uno sciroppo. Versare poi questo sciroppo in una terrina con gli albumi montati, mescolare energicamente con una frusta ottenendo un composto morbido e filante. Lasciare raffreddare ed aggiungere la bustina di zucchero vanigliato; continuare a mescolare con energia, quindi versare nella terrina anche il gelato ed il rum. Questo nuovo composto va rimesso in frigo per farlo rapprendere, ma senza che diventi solido. Distribuirlo nelle coppe e nei flùtes, decorandolo con ciliegine sotto spirito. ',566);
INSERT INTO "ricette" VALUES (19928,'Punch Caffè Cognac','Bevande','Cognac',1,' -','1 Tazzina Caffè Espresso Zuccherato,
1 Bicchierino Cognac,
Per Servire:,
1 Scorzina Limone','In un tumbler ben riscaldato e munito di reggibicchiere atermico si versa 1 tazzina di caffè espresso zuccherato e bollente. Si aggiunge un bicchierino di cognac, si fiammeggia e si serve con scorzina di limone.',111);
INSERT INTO "ricette" VALUES (19929,'Punch Della Locomotiva','Bevande','Vino Rosso',1,' -','1 Tuorlo D''uovo,
1 Cucchiaino Zucchero,
1 Cucchiaino Miele,
1.5 Cl Curacao,
10 Cl Vino Rosso,
1 Fettina Limone,
1 Pizzico Noce Moscata','Questo punch va servito bollente e fumante. Mescolate in una casseruolina il tuorlo con lo zucchero e il miele, incorporatevi il curacao e il vino rosso e, sempre sbattendo con una frusta, portate tutto quasi all''ebollizione. Adagiate la fettina di limone in un bicchiere resistente al calore e scaldato in precedenza con acqua bollente, versate il punch e servitelo subito.',254);
INSERT INTO "ricette" VALUES (19930,'Punch Della Martinica','Bevande','Vino Porto',1,' -','6 Cubetti Ghiaccio,
2 Cucchiaini Sciroppo Di Zucchero,
1/2 Limone (succo),
5 Cl Vino Porto,
1 Goccia Brandy,
1 Cucchiaio Frutta Di Stagione A Pezzettini','Mettete tre cubetti di ghiaccio nello shaker, unite lo sciroppo di zucchero, il porto, il brandy e il succo di limone ed agitate con forza. Riempite con il restante ghiaccio tritato un bicchiere alto e versatevi sopra il contenuto dello shaker filtrandolo. Mescolate con il cucchiaino lungo, guarnite con la frutta e servite con cannuccia e cucchiaino.',244);
INSERT INTO "ricette" VALUES (19931,'Punch Delle Highlands','Bevande','Whisky',8,' -','350 G Zucchero,
1 Limone (succo Filtrato),
100 Cl Acqua,
1/2 Bottiglia Whisky,
1/2 Bottiglia Rum,
1 Bicchiere Brandy,
1 Bicchiere Vino Porto','Data l''elevata quantità di ingredienti ad alto tenore alcoolico, questo punch è da bere con moderazione. Mettete lo zucchero in una casseruola, unitevi il succo di limone e l''acqua e portate quasi ad ebollizione mescolando ripetutamente per far sciogliere bene lo zucchero. Versate quindi nello sciroppo il whisky, il rum, il brandy e il porto; mescolate, riportate quasi a bollore e servite in coppette da punch resistenti al calore.',4211);
INSERT INTO "ricette" VALUES (19932,'Punch Di Frutta','Bevande','Vino',6,' -','50 Cl Vino,
1 Bicchiere Brandy,
1 Bicchiere Vino Spumante,
1 Tazza Tè,
2 Limoni,
500 G Frutta Assortita (fragole, Pesche, Albicocche, Pere, Meloni, Arance)','Versate in una insalatiera tutti gli ingredienti tagliando la frutta a pezzi o a fette; aggiungete ghiaccio tritato e lasciate al fresco fino a 1 ora prima di servire.',1109);
INSERT INTO "ricette" VALUES (19933,'Punch Di Spremuta D''arancia','Bevande','Arance',4,' -','Spremuta D''arancia,
1 Bicchiere Acqua Bollente,
1 Bicchierino Liquore,
2 Cucchiai Zucchero,
1 Pezzetto Scorza D''arancia','Aggiungete alla spremuta 1 bicchiere d''acqua bollente, 1 bicchierino di liquore, 2 cucchiai di zucchero e 1 pezzetto di scorza d''arancia.',187);
INSERT INTO "ricette" VALUES (19934,'Punch Di Spremuta Di Mandarino','Bevande','Mandarini',4,' -','Spremuta Di Mandarino,
1 Bicchiere Acqua Bollente,
1 Bicchierino Liquore,
2 Cucchiai Zucchero,
1 Pezzetto Scorza Di Mandarino','Aggiungete alla spremuta 1 bicchiere d''acqua bollente, 1 bicchierino di liquore, 2 cucchiai di zucchero e 1 pezzetto di scorza di mandarino.',200);
INSERT INTO "ricette" VALUES (19935,'Punch Eggnog','Bevande','Cognac',1,' -','1 Tuorlo D''uovo,
2/3 Latte Caldo,
1/3 Cognac,
1/2 Cucchiaio Zucchero,
Per Completare:,
1 Albume D''uovo Montato A Neve,
Per Servire:,
1 Pizzico Noce Moscata','Agitare vigorosamente nello shaker aggiungere il bianco d''uovo montato a neve. Servire nel tumbler alto, con un pizzico di noce moscata.',312);
INSERT INTO "ricette" VALUES (19936,'Punch Estivo','Bevande','Succo Di Mela',6,' -','100 Cl Succo Di Mela,
100 Cl Succo D''ananas,
50 Cl Succo D''arancia,
10 Cl Succo Di Limone,
8 Chiodi Di Garofano,
200 G Miele','Riscaldate a fuoco moderato le spezie, il miele e il succo di mela. Fate raffreddare e versate in una caraffa aggiungendo i succhi di frutta. Mettete in frigo e servite con ghiaccio in un bicchiere da bibita. Potete decorare con uno spicchio di arancia, una fetta di mela e una ciliegia.',1703);
INSERT INTO "ricette" VALUES (19937,'Punck','Bevande','Whisky',1,' -','1/4 Rum,
1/4 Gin,
2/4 Whisky,
2 Cucchiai Succo Di Limone,
1 Cucchiaio Zucchero,
Per Decorare:,
1 Limone Tagliato A Fettine,
Alcuni Cubetti Frutta Di Stagione,
Alcune Ciliegine Al Maraschino (facoltativo)','Preparare nel bowl, con molto ghiaccio, decorando con un limone tagliato a fettine e cubetti di frutta di stagione; volendo si possono aggiungere delle ciliegine al maraschino. Servire nei calici panciuti.',468);
INSERT INTO "ricette" VALUES (19938,'Punt E Mes Negroni','Bevande','Punt E Mes',1,' -','1/3 Punt E Mes,
1/3 Gin,
1/3 Vermouth Dolce','Mescolate bene, con ghiaccio, tutti gli ingredienti. Versate in un bicchiere da cocktail già freddo.',273);
INSERT INTO "ricette" VALUES (19939,'Punt E Mes Negroni (2)','Bevande','Punt E Mes',1,' -','1/3 Punt E Mes,
1/3 Gin,
1/3 Vermouth Dolce,
Alcune Gocce Succo Di Limone','Mescolate bene, con ghiaccio, tutti gli ingredienti. Versate in un bicchiere da cocktail già freddo.',274);
INSERT INTO "ricette" VALUES (19940,'Punta Di Petto Al Forno','Carne','Vitello',4,' -','800 G Punta Di Vitello,
50 G Burro,
3 Cucchiai Olio D''oliva,
Rosmarino,
Salvia,
Vino Bianco,
Sale,
Pepe','Disporre in una pirofila la carne con il burro, l''olio d''oliva, il rosmarino, la salvia, sale e pepe. Farlo rosolare, spruzzarlo con il vino e continuare la cottura per circa 2 ore, bagnando ancora con un po'' di vino.',2299);
INSERT INTO "ricette" VALUES (19941,'Punta Di Petto Al Forno (2)','Carne','Vitello',4,' -','Punta Di Petto Di Vitello,
40 G Burro,
3 Cucchiai Olio D''oliva,
1 Rametto Rosmarino,
1 Rametto Salvia,
Vino Bianco,
Sale,
Pepe','Rosolare la carne in burro e olio con rosmarino e salvia. Poi spruzzarla con un po'' di vino, salarla, peparla e continuare la cottura in forno a 200 gradi per circa 2 ore, bagnandola ancora con un po'' di vino.',1868);
INSERT INTO "ricette" VALUES (19942,'Punta Di Petto Di Vitello Al Forno','Carne','Vitello',6,' -','800 G Punta Di Vitello Disossato E Con Tasca,
50 G Burro,
3 Cucchiai Olio D''oliva,
Salvia,
Rosmarino,
Sale,
Per Il Ripieno:,
60 G Pangrattato,
120 G Formaggio Parmigiano Grattugiato,
2 Uova,
30 G Burro,
1 Cucchiaino Doppio Concentrato Di Pomodoro,
1 Tazza Brodo Di Carne,
1 Pizzico Noce Moscata Grattugiata,
Sale','Bollite il brodo con l''aggiunta del concentrato di pomodoro e del burro. Scottatevi il pangrattato, aggiungere le due uova, il parmigiano, la noce moscata e un pizzico di sale. Farcite la punta di petto, cucite l''apertura, e dopo averla condita con un trito di rosmarino e salvia, sale, burro e olio, salatela e passatela in forno a 180-200 gradi circa, curando la cottura, rigirandola e bagnandola con il suo sugo affinché sia ben rosolata da tutte le parti.',3371);
INSERT INTO "ricette" VALUES (19943,'Punta Di Vitello Arrosto','Carne','Vitello',6,' -','1000 G Punta Di Vitello,
1 Cipolla,
1/2 Bicchiere Olio D''oliva,
150 G Pancetta,
50 Cl Brodo,
1 Bicchiere Vino Bianco,
Lardo In Fette,
Pepe (facoltativo),
Aglio','Tritate finemente la pancetta e fatela rosolare in una pentola larga da forno, con una cipolla tritata, mezzo bicchiere d''olio e uno spicchio d''aglio. Quando la pancetta è trasparente, disponete il pezzo di punta di vitello nella pentola, facendolo dorare a fiamma viva. Quando la carne ha preso colore, bagnatela subito con il vino e fate evaporare poi poco alla volta unite il brodo e coprite la carne con fettine di lardo tagliate sottili. Questo è il momento di mettere la punta nel forno precedentemente scaldato a 220 gradi per una bella ora, girando il pezzo di tanto in tanto. La superficie della carne dovrà risultare ben colorita. Se il sugo sarà troppo asciutto al momento di servire, aggiungete un po'' d''acqua e fatela evaporare.',3468);
INSERT INTO "ricette" VALUES (19944,'Puntarelle Alle Acciughe','Antipasto','Puntarelle',4,' -','1 Cespo Puntarelle,
Pasta D''acciughe,
Aceto Di Vino Bianco,
Olio D''oliva,
Poco Sale,
Poco Pepe','Montare le puntarelle eliminando la parte più dura, poi tagliarle a striscioline e tuffarle in acqua fredda per farle arricciare (circa 1 ora). Scolarle e servirle con una salsetta di pasta d''acciughe sciolta in aceto e olio e insaporita con poco sale e pepe.',967);
INSERT INTO "ricette" VALUES (19945,'Puntarelle Con I Croissant','Antipasto','Puntarelle',6,'Preparazione: 35 minuti. Cottura: 25 minuti.','600 G Puntarelle,
1 Rotolo Pasta Sfoglia,
30 G Gherigli Di Noci,
40 G Olive Nere Snocciolate,
4 Filetti D''acciughe Sott''olio,
2 Spicchi Aglio,
7 Cucchiai Olio D''oliva,
1 Pizzico Sale,
1 Pizzico Peperoncino In Polvere','Mondate le puntarelle, tagliatele a filetti sottili, lavatele e tenetele a bagno in acqua fredda per mezz''ora, poi scolatele. Asciugatele bene, chiudetele in un sacchetto di plastica per alimenti e mettetele in frigorifero (vi serviranno il giorno dopo). Passate al mixer le olive con le noci, un cucchiaio di olio e un pizzico di sale. Stendete la sfoglia e tagliatela in otto spicchi uguali. Appoggiate su ognuno un po'' di pesto di noci. Inumidite con l''acqua le punte degli spicchi di sfoglia. Poi, partendo dalla base, arrotolate ogni spicchio fino a formare un involtino. Dategli la forma di mezza luna piegata verso l''interno, in modo da ottenere un piccolo croissant. Procedete così con il resto della sfoglia. Appoggiate i croissant sulla placca da forno foderata di carta speciale, spolverizzateli con un po'' di peperoncino in polvere e cuoceteli in forno a 200 gradi per circa 20 minuti. Sformateli e appoggiateli sopra una gratella. Versate 6 cucchiai di olio in una casseruolina, unite gli spicchi di aglio sbucciati e tagliati a metà e fateli rosolare. Spegnete il fuoco, aggiungete i filetti di acciuga e un pizzico di peperoncino. Mescolate fino a ottenere una salsa omogenea, fatela raffreddare e riponetela in frigorifero in una ciotolina. Scaldate i croissant per pochi minuti nel forno a 220 gradi prima di servirli. Sulla fiamma scaldate anche la salsa di acciughe e ricordate di togliere l''aglio. Distribuite le puntarelle nei piattini, conditele con la salsa tiepida e servitele con i piccoli croissant alle noci.',3521);
INSERT INTO "ricette" VALUES (19946,'Puntarelle Con Le Alici','Contorno','Puntarelle',4,'Luogo: Lazio.','1000 G Puntarelle,
2 Spicchi Aglio,
4 Acciughe,
Poco Aceto Di Vino,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lavate bene le puntarelle (punte della cicoria amara), scartando con un coltellino le foglie verdi e le parti più dure. Mettetele in acqua fredda e lasciatele immerse per almeno mezz''ora. Scolatele, asciugatele e versatele in un''insalatiera, dove avrete preparato una salsina pestando le acciughe, gli spicchi d''aglio, un po'' d''aceto, l''olio d''oliva extra-vergine, il sale e il pepe. Fatele riposare per almeno 15 minuti. Mescolate e servite.',1743);
INSERT INTO "ricette" VALUES (19947,'Punte Di Asparagi Gratinate','Contorno','Asparagi',4,'Preparazione: 30 minuti. Cottura: 10 minuti.','1 Mazzo Asparagi Freschi (mazzi Da 1000 G),
20 Cl Panna Fresca,
1 Cucchiaino Brodo Granulare Di Verdure Knorr,
3 Cucchiai Formaggio Parmigiano Grattugiato,
1 Pezzetto Burro,
1 Uovo,
Alcuni Fili Erba Cipollina,
1 Pizzico Pepe','Pulite gli asparagi e cuoceteli in acqua salata per 15 minuti. Se usate gli asparagi surgelati seguite le indicazioni di cottura sulla confezione. Tagliate gli asparagi in pezzetti di circa 7 cm di lunghezza e disponeteli in una pirofila. Raccogliete la parte restante degli asparagi nella coppa del mixer o del frullatore e riduceteli in purea. Versate la panna in un pentolino, aggiungete la purea di asparagi, il burro, 1 cucchiaino di brodo granulare di verdure Knorr e fate scaldare a fuoco moderato, facendo addensare. Togliete dal fuoco, aggiungete parmigiano, un pizzico di pepe, l''erba cipollina tagliata a pezzettini e il tuorlo d''uovo, mescolate con cura e versate la salsa sugli asparagi. Passate la pirofila in forno già caldo a 200 gradi per 10 minuti. Potrete servire questa gustosissima preparazione con uova strapazzate o con petti di pollo cotti in padella.',1484);
INSERT INTO "ricette" VALUES (19948,'Punte Di Catalogna In Insalata','Contorno','Insalata Catalogna',4,' -','500 G Punte Di Insalata Catalogna,
3 Acciughe Sotto Sale,
1 Limone,
1/2 Spicchio Aglio,
Olio D''oliva,
Poco Sale','Lavate le punte di catalogna, sgocciolatele molto bene e mettetele in un''insalatiera. In una ciotola riunite mezzo spicchio d''aglio tritato, le acciughe dissalate, diliscate e tagliate a pezzettini, il succo di limone filtrato al colino, l''olio e poco sale. Amalgamate con delicatezza. Versate il condimento sulla verdura, lasciate riposare e insaporite un quarto d''ora e servite.',863);
INSERT INTO "ricette" VALUES (19949,'Puntine Di Maiale Al Vino Bianco','Carne','Maiale',4,' -','12 Puntine Di Maiale,
1 Bicchiere Vino Bianco Secco,
4 Foglie Salvia,
Olio D''oliva,
Burro,
Sale,
Pepe','In un tegame piuttosto largo scaldate due cucchiai d''olio e una grossa noce di burro con le quattro foglie di salvia. Quando le foglie sono leggermente dorate adagiate nel recipiente le puntine e fatele rosolare a fuoco vivo per alcuni minuti girandole in continuazione. Poi diminuite il calore e cuocete per 20 minuti. Salate, pepate e proseguite la cottura per 40 minuti spruzzando ogni tanto le costine con il vino, senza versarlo tutto in una volta perché la carne deve riuscire morbida, però asciutta. Passate sul piatto da portata caldo. Vini di accompagnamento: Oltrepò Pavese Bonarda Vivace DOC, Chianti Colli Aretini DOC, Cilento Rosso DOC.',3572);
INSERT INTO "ricette" VALUES (19950,'Puntine Di Maiale Al Vino Rosso','Carne','Maiale',4,' -','1200 G Puntine Di Maiale,
1 Bicchiere Vino Rosso,
30 G Burro,
4 Foglie Salvia,
Sale,
Pepe','In un tegame lasciate sciogliere il burro, insaporitevi le foglioline di salvia, adagiatevi le puntine e fatele rosolare per venti minuti girandole in continuazione. Salate, pepate e proseguite la cottura per mezz''ora abbondante versando ogni tanto un po'' di vino. Servite ben caldo.',2662);
INSERT INTO "ricette" VALUES (19951,'Puntine Di Maiale In Agrodolce','Carne','Maiale',6,' -','12 Puntine Di Maiale,
1/2 Ananas,
1 Peperone Giallo,
1 Peperone Verde,
1 Peperone Rosso,
2 Cucchiai Zucchero,
1 Cipollotto,
Olio D''oliva,
Sale,
Pepe','Salate e pepate le puntine, mettetele in una teglia e cuocetele 10 minuti per parte in forno a 200 gradi, poi fatele dorare al grill per altri 10 minuti. Intanto pulite i peperoni e tagliateli a quadretti molto piccoli. Affettate l''ananas, eliminate la buccia e la parte centrale, riducete la polpa a pezzettini. Tagliate a fettine il cipollotto e rosolatelo in un tegame con tre cucchiai d''olio. Unitevi l''ananas e i peperoni lasciando cuocere a fuoco basso per una decina di minuti. Se necessario aggiungete un po'' d''acqua. Cospargete con lo zucchero, salate, pepate e mescolate bene. Dopo 10 minuti aggiungete le puntine e insaporite per alcuni minuti. Servitele molto calde. Vini di accompagnamento: Freisa Di Chieri Frizzante DOC, Colli Amerini Novello DOC, Salice Salentino Novello DOC.',3120);
INSERT INTO "ricette" VALUES (19952,'Pupuarole Ammullecate','Contorno','Peperoni',4,' -','1500 G Peperoni,
50 G Capperi,
70 G Olive Nere,
Prezzemolo,
Origano,
1 Spicchio Aglio,
150 G Olio D''oliva,
Pangrattato','Dopo aver lavato accuratamente i peperoni metteteli sul fuoco, spellateli, lavateli di nuovo ed asciugateli. Tagliateli a strisce e disponeteli a strati in una teglia con un po'' di sale, olio, aglio, capperi, olive, origano, prezzemolo e pangrattato. Mettete in forno e fate cuocere fino a quando la superficie non apparirà dorata. Questo piatto può essere consumato indifferentemente caldo o freddo ed aggiungendo, secondo i gusti, il limone.',2290);
INSERT INTO "ricette" VALUES (19953,'Purceddhuzzi Col Miele','Dessert','Miele',4,' -','1000 G Farina,
150 G Olio D''oliva,
120 G Liquore (o Vino Bianco),
1 Limone (buccia Grattugiata),
1 Pizzico Sale,
Alcune Scorze Di Limone Grattugiate,
Alcune Scorze D''arancia Grattugiate,
Miele,
Per Guarnire:,
Pinoli,
Mandorle Tostate Nel Forno,
Zucchero,
Cannella In Polvere,
Alcuni Pezzetti Cioccolata Fondente,
Anisini Colorati','Ricetta natalizia. I purceddhuzzi sono dei dadini di pasta dolce fritti e ricoperti di miele. La pasta è quella delle cartellate: si impastano 1000 g farina con 150 g di olio, 120 g di liquore o vino bianco, la buccia grattugiata di un limone, 1 pizzico di sale e, se ci vuole, un po'' d''acqua. Si forma un salamino di pasta della grossezza di un dito, e si taglia a pezzetti della incavarlo, grossezza di un ditale. Ogni pezzetto si passa sui rebbi di una forchetta rovesciata, per poi tutti verranno fritti in una padella in cui si sia fatto fumare dell''olio, con scorze di arancia e di limone. Infine si pongono a gocciolare su carta assorbente per fritti. Si pone ora del miele a sciogliersi in un tegame a bagnomaria, e quando è bollente vi si versano i purceddhuzzi, si rigirano e poi si tolgono, deponendoli tutt''intorno in un piatto da dolci, formando una corona. Si guarniscono con pinoli, mandorle tostate nel forno, zucchero e cannella in polvere, pezzetti di cioccolata fondente, anisini colorati.',6752);
INSERT INTO "ricette" VALUES (19954,'Purdedduzzi Col Miele','Dessert','Miele',4,' -','1000 G Farina,
150 G Olio D''oliva,
120 G Liquore (o Vino Bianco),
1 Limone (buccia Grattugiata),
1 Pizzico Sale,
Alcune Scorze Di Limone Grattugiate,
Alcune Scorze D''arancia Grattugiate,
Miele,
Per Guarnire:,
Pinoli,
Mandorle Tostate Nel Forno,
Zucchero,
Cannella In Polvere,
Alcuni Pezzetti Cioccolata Fondente,
Anisini Colorati','Ricetta natalizia. I purdedduzzi sono dei dadini di pasta dolce fritti e ricoperti di miele. La pasta è quella delle cartellate: si impastano 1000 g farina con 150 g di olio, 120 g di liquore o vino bianco, la buccia grattugiata di un limone, 1 pizzico di sale e, se ci vuole, un po'' d''acqua. Si forma un salamino di pasta della grossezza di un dito, e si taglia a pezzetti della incavarlo, grossezza di un ditale. Ogni pezzetto si passa sui rebbi di una forchetta rovesciata, per poi tutti verranno fritti in una padella in cui si sia fatto fumare dell''olio, con scorze di arancia e di limone. Infine si pongono a gocciolare su carta assorbente per fritti. Si pone ora del miele a sciogliersi in un tegame a bagnomaria, e quando è bollente vi si versano i purdedduzzi, si rigirano e poi si tolgono, deponendoli tutt''intorno in un piatto da dolci, formando una corona. Si guarniscono con pinoli, mandorle tostate nel forno, zucchero e cannella in polvere, pezzetti di cioccolata fondente, anisini colorati.',6752);
INSERT INTO "ricette" VALUES (19955,'Purea Di Broccoletti','Antipasto','Broccoletti',4,'Preparazione: 15 minuti. Cottura: 25 minuti. Calorie: 109.','32 Cozze,
10 Cl Vino Bianco Secco,
1/2 Cipolla,
400 G Broccoletti,
1 Cucchiaio Prezzemolo Tritato,
1 Spicchio Aglio,
1 Bustina Zafferano,
1 Cucchiaio Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulite accuratamente le cozze, lavatele più volte e mettetele in una larga padella con il vino, l''aglio, la cipolla tritata e il prezzemolo; fate aprire le conchiglie a fiamma vivace per 5 minuti circa coperte. Tenete le cozze in caldo e filtrate il liquido di cottura. Lessate i broccoletti in abbondante acqua bollente salata per 15-20 minuti finché saranno teneri. Scolateli e frullateli nel mixer con lo zafferano diluito in 4 cucchiai di liquido delle cozze: se la purea fosse troppo asciutta, diluite con altro liquido di cottura delle cozze. Condite la purea con l''olio, regolate di sale, pepate e servite con le cozze tenute da parte.',729);
INSERT INTO "ricette" VALUES (19956,'Purea Di Carote','Contorno','Carote',4,' -','600 G Carote,
60 G Burro,
1 Foglia Alloro,
Alcuni Semi Cumino,
Sale Marino','Lessare le carote debitamente spazzolate e spezzettate in pochissima acqua salata con la foglia d''alloro e i semi di cumino per 20 minuti. Scolarle e frullarle in un mixer, rimettere poi sul fuoco la purea ottenuta, farla scaldare nuovamente, quindi spegnere il fuoco e mescolarvi il burro. Servire come contorno.',601);
INSERT INTO "ricette" VALUES (19957,'Purea Di Castagne','Dessert','Castagne',4,' -','100 G Zucchero,
100 G Burro,
50 G Cioccolata In Polvere,
200 G Purea Di Castagne,
Zucchero Vanigliato,
Rum,
Panna Montata','Il tutto si lavora bene e si aggiunge una cartina di zucchero vanigliato. Si tappezza una forma liscia di biscotti bagnati nel rum e si mette la purea in esso e si copre di biscotti. Si mette al freddo e si serve con contorno di panna montata dolce.',2234);
INSERT INTO "ricette" VALUES (19958,'Purea Di Cipolle','Contorno','Cipolle',4,' -','500 G Cipolle,
40 Cl Besciamella Pronta,
100 G Burro,
10 Cl Panna Liquida,
Zucchero,
Pepe,
Sale','Pelare e affettare le cipolle. Sbollentarle per qualche minuto in acqua salata e scolarle bene. Mettere le cipolle in un tegame e farle stufare in 50 g di burro, mescolando e facendo attenzione a non farle colorire. Unire poco sale e zucchero e una macinata di pepe poi la besciamella, mescolare, coprire il recipiente e porre in forno a 170 gradi per 30 minuti. Passare al setaccio, aggiungere il resto del burro, la panna e amalgamare bene il tutto prima di servire.',1772);
INSERT INTO "ricette" VALUES (19959,'Purea Di Fave Con Scarola E Pecorino','Contorno','Fave',4,'Luogo: Lazio.','500 G Fave Sbucciate,
1 Pianta Insalata Scarola,
Formaggio Pecorino Romano,
1 Spicchio Aglio,
Sale,
1 Punta Peperoncino,
Per Guarnire:,
1 Foglia Insalata Scarola','Lessare le fave e passarle fino ad ottenere una crema che si farà saltare in padella con uno spicchio di aglio, olio e una punta di peperoncino. A parte lessate la scarola e ripassarla come la purea. Disporre i due composti su un piatto e ricoprire con sottilissime scagliette di pecorino, guarnendo il tutto con una verdissima foglia di scarola.',668);
INSERT INTO "ricette" VALUES (19960,'Purea Di Fave Con Scarola E Pecorino Romano','Contorno','Fave',4,' -','500 G Fave Sgranate,
1 Cespo Insalata Scarola,
Formaggio Pecorino Romano,
2 Spicchi Aglio,
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Mettete le fave a bagno in acqua fredda, portate l''acqua a bollore e lessatele, a recipiente coperto, per circa 1 ora e mezzo. Quando saranno ben tenere scolatele, sciacquatele sotto l''acqua corrente e passatele raccogliendo la purea in una terrina. In una padella fate scaldare 2 cucchiai d''olio con 1 spicchio d''aglio e una punta di peperoncino. Quando l''aglio sarà colorito eliminatelo e fate saltare la purea di fave. A parte lessate per 15 minuti la scarola e ripassatela con 2 cucchiai d''olio, 1 spicchio d''aglio e il peperoncino. Disponete i due composti su un piatto da portata e ricoprite con sottilissime scagliette di pecorino guarnendo il tutto con una verdissima foglia di scarola.',1417);
INSERT INTO "ricette" VALUES (19961,'Purea Di Melanzane','Contorno','Melanzane',4,' -','4 Melanzane,
Sale,
Pepe,
3 Cucchiai Olio D''oliva,
3 Cucchiai Yogurth,
1 Cipolla Cruda,
Alcune Foglie Menta,
Pane Raffermo (per Servire)','Far cuocere a lungo in forno appena caldo 4 melanzane. Quando sono molto tenere avvolgerle in uno straccio bagnato e farle raffreddare. Spellarle e raccogliere la polpa, tritarla finemente e condirla con sale, pepe, 3 cucchiai di olio d''oliva e 3 cucchiai di yogurth. Guarnire questa purea con fette sottilissime di cipolla cruda e foglioline di menta. Servire con crostini di pane raffermo tostato al forno.',1614);
INSERT INTO "ricette" VALUES (19962,'Purea Di Melanzane (2)','Contorno','Melanzane',4,' -','2 Melanzane,
6 Cucchiai Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
1 Pizzico Peperoncino,
1 Limone,
Basilico,
Sale','Lavate bene le melanzane e lasciatele intere per 40 minuti dentro il forno molto caldo appoggiate sulla grata. Levate con attenzione tutta la pelle, schiacciate la polpa con il passaverdura o passatela al mixer e mettetela in una terrina. Amalgamate lentamente con l''aglio tritato, olio, succo di limone e peperoncino. Lavorate con cura per una decina di minuti con un mestolo di legno e se l''impasto risultasse troppo asciutto aggiungete altro olio. Aggiustate di sale a piacimento e servite come antipasto, con crostini di pane fritti, a temperatura ambiente guarnendo con foglie di basilico.',677);
INSERT INTO "ricette" VALUES (19963,'Purea Di Pere Con Pecorino Romano','Contorno','Pere',4,'Luogo: Lazio.','1000 G Pere Mature,
200 G Formaggio Pecorino Romano,
Alcune Foglie Menta','Sbucciare le pere e passarle nel passaverdure, dividere successivamente il succo dalla polpa. Disporre in una padella e far restringere il composto senza l''aggiunta di zucchero. Servire tiepido guarnendo il piatto con delle fettine di pere fresche, delle foglie di menta e dei tocchetti di pecorino.',1148);
INSERT INTO "ricette" VALUES (19964,'Purea Di Piselli','Contorno','Piselli Surgelati',4,' -','250 G Piselli Surgelati,
1 Cipolla,
100 G Pancetta Affumicata,
Vino Bianco,
Brodo,
Panna (o Latte),
Sale,
Pepe','In una padella fate appassire la cipolla con l''olio d''oliva extra-vergine. Aggiungete il vino, fate evaporare e poi unite il brodo. Quando la cipolla sarà diventata cremosa, unite i piselli ancora surgelati. Salate e fate cuocere pochi minuti. Mettete tutto nel mixer, frullate e rimettete il composto nella padella, unite la panna o il latte e aggiustate di sale e pepe. Servite con dei rotolini di pancetta fatti dorare al forno o in padella.',1073);
INSERT INTO "ricette" VALUES (19965,'Purea Di Piselli (2)','Contorno','Piselli',4,' -','250 G Piselli Freschi,
1 Cespo Insalata Lattuga,
1 Carota,
1 Cipolla,
1 Patata Grande,
2 Cucchiai Panna Vegetale,
Sale','In abbondante acqua bollente salata, cuocere i piselli ammollati con la lattuga, la carota e la cipolla, a cottura ultimata passate o frullate il tutto. Lessate a parte la patata e passatela, incorporatela al purè insieme alla panna vegetale, regolate di sale, se necessario allungate leggermente la preparazione e servite.',593);
INSERT INTO "ricette" VALUES (19966,'Purea Di Sedano Rapa','Contorno','Sedano Rapa',4,' -','400 G Sedano Rapa Lessato,
Sale,
Pepe Bianco,
180 G Burro','Rivestite uno schiacciapatate con un telo e mettetevi il sedano lessato e tagliato a cubetti. Schiac