l guscio, alzate la fiamma in modo che cuociano senza rientrare nel guscio. Dopo quest''operazione risciacquate le lumache in abbondante acqua fredda. Fate soffriggere nell''olio, l''aglio e appena tende a scurirsi gettatelo via, versate nel tegame le acciughe spinate e a pezzetti e il peperoncino, appena le acciughe si sono sciolte aggiungete il pomodoro a pezzetti, insaporite di sale e cuocete per qualche minuto. Unite al sugo le lumache e cuocete a fuoco moderato per 30 minuti abbondanti. Questo piatto deve essere servito ben caldo.',2405);
INSERT INTO "ricette" VALUES (13937,'Lumache Alla Ticinese','Antipasto','Lumache',4,' -','100 Lumache Senza Guscio E Pulite,
20 G Burro,
100 G Pancetta,
20 Cl Vino Bianco Secco,
20 Noci,
Prezzemolo,
Maggiorana,
Sale,
Pepe','Rosolare le lumache in pochissimo burro. Aggiungere la pancetta tagliata a pezzetti, bagnare col vino, salare, pepare e aggiungere le noci tritate. Cuocere per 2 ore a coperto e a fuoco molto basso.',5055);
INSERT INTO "ricette" VALUES (13938,'Lumache Cotte (preparazione Base)','Antipasto','Lumache',6,' -','Lumache Vive,
Sale Grosso,
Acqua,
Aceto Di Vino,
Sale,
Farina Gialla,
Carota,
Cipolla,
Timo,
Alloro,
Prezzemolo','Lasciate le lumache vive, coperte di sale grosso, in una scatola piuttosto larga, chiusa ma arieggiata per ventiquattr''ore. Lavatele più volte in acqua, aceto e sale fino a quando l''acqua si presenta priva di qualsiasi traccia di viscosità. Passatele più volte nella farina gialla e risciacquatele ancora sotto l''acqua fresca. Effettuate una precottura immergendole in acqua bollente per 10 minuti. Estraete delicatamente le lumache dal guscio con l''apposito ferretto ed eliminate l''estremità color nero (intestino). Tuffatele in un court-bouillon aromatizzato con carota, cipolla, timo, alloro, prezzemolo e fatele sobbollire per 4 ore, specialmente se le lumache sono grandi. Le lumache sono ora pronte per ulteriori ricette.',559);
INSERT INTO "ricette" VALUES (13939,'Lumache Di Campagna','Antipasto','Lumache',4,'Luogo: Trentino Alto-Adige. Cottura: 150 minuti.','60 Lumache,
Olio D''oliva,
1/2 Bicchiere Aceto Di Vino,
Aglio,
Pangrattato,
Prezzemolo,
1 Pugno Sale Grosso,
Sale,
Pepe','Mettere le lumache in una 
catinella di acqua fredda con un pugno di sale grosso e mezzo bicchiere di aceto, scuotendole di tanto in tanto con le mani in modo che buttino dal guscio molta della loro bava. Risciacquarle due o tre volte. Infine metterle nell''acqua bollente per 10 minuti. Dopo un''altro e definitivo risciacquo, strappare una ad una la lumaca dal guscio, levare il sacchetto verde che si nota all''estremità e gettarlo, perché molto amaro. Preparare una salsa con olio, pangrattato, aglio, prezzemolo, sale e pepe. Ci sono 3 alternative: 1. rimettere le lumache nel guscio, riempirli con la salsa, disporli in un tegame e far cuocere per due ore, aggiungendo un po'' d''acqua di tanto in tanto; 2. mettere nel tegame le lumache senza guscio con la salsa: in questo caso si faranno cuocere per un''ora e mezza, allo stesso modo; 3. si possono anche passare le lumache al tritacarne e poi cuocerle con la salsa.',4100);
INSERT INTO "ricette" VALUES (13940,'Lumache Fritte','Contorno','Lumache',4,' -','Lumache,
Cipolla,
Aglio,
Rosmarino,
Mentuccia,
Maggiorana,
Sedano,
Prezzemolo,
Origano,
Vino Bianco,
Pomodoro','Una volta spurgate e pulite le lumache, fatele soffriggere in un trito di cipolla, aglio, rosmarino, mentuccia, maggiorana, sedano, prezzemolo e origano e poi aggiungete vino bianco e pomodoro. Fatele cuocere a fuoco molto lento. Sono molto buone anche con crostini di pane.',333);
INSERT INTO "ricette" VALUES (13941,'Lumache In Salsa Piccante','Antipasto','Lumache',6,' -','36 Lumache Sgusciate E Lessate,
3 Spicchi Aglio,
1 Peperoncino Rosso,
3 Acciughe,
Sale,
Pepe,
4 Cucchiai Olio D''oliva,
Alcune Foglie Menta Fresca,
400 G Pomodori','Fate scaldare l''olio in una capace casseruola e soffriggetevi gli spicchi d''aglio a calore moderato fino a quando prendono colore, dopodichè eliminateli e mettete nel recipiente le acciughe lavate, private della lisca e sminuzzate. Lasciatele cuocere fino a quando si saranno disfatte, quindi unite i pomodori, pelati, privati dei semi e ridotti a filetti, e il peperoncino spezzettato. Fate addensare un poco la salsa a fuoco dolce, poi conditela con il sale necessario, una macinata di pepe e alcune foglie di menta tritate e aggiungete le lumache. Lasciate insaporire i molluschi nella salsa per circa 30 minuti, a calore moderato, quindi servite con fette di pane casereccio.',3719);
INSERT INTO "ricette" VALUES (13942,'Lumachine Alla Veneta','Antipasto','Lumachine Di Mare',4,'Luogo: Veneto. Preparazione: 20 minuti. Cottura: 20 minuti. Calorie: 174.','1000 G Lumachine Di Mare,
3 Spicchi Aglio,
1 Manciata Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Lasciate spurgare le lumachine in acqua salata per qualche ora e, dopo, lavatele con cura. Pestate nel mortaio l''aglio con il prezzemolo fino ad ottenere un pesto fine. Amalgamatevi un po'' d''olio e aggiungetelo alle lumachine in una pentola, coprite a filo con dell''acqua e fate cuocere per 15 minuti. Salate, pepate, mescolate bene e servite nel guscio. Per togliere il mollusco dalla conchiglia usate dei piccoli stecchini.',1736);
INSERT INTO "ricette" VALUES (13943,'Lumachine Alle Nocciole','Dessert','Nocciole',15,' -','Burro Per La Piastra Del Forno,
Glassa Di Albicocche,
Glassa Fondente Al Limone,
1 Dose Pasta Lievitata,
Per La Farcitura:,
300 G Nocciole Tostate E Tritate,
1 Pizzico Pimento In Polvere,
1 Pizzico Sale,
120 G Zucchero Di Canna,
3 Albumi D''uovo','Preparate la pasta come indicato nella ricetta dei Fiocchetti alle mandorle. Riunite in una terrina gli ingredienti della farcitura e mescolateli fino ad ottenere un composto omogeneo. Stendete la pasta sulla spianatoia infarinata formando un rettangolo di 75 x 35 cm. Spalmatevi sopra la farcia, lasciando un bordo libero lungo i lati maggiori. Arrotolate la pasta partendo da questi lati e andando verso il centro del rettangolo, in modo da ottenere due rotoli paralleli e vicini. Tagliate il doppio rotolo a fette spesse circa 2,5 cm. Allineate i biscotti sulla piastra del forno imburrata, ben distanziati gli uni dagli altri, e lasciateli riposare per un quarto d''ora. Fateli cuocere nel forno preriscaldato (220 gradi) per 15-18 minuti. Trascorso questo tempo sfornateli e, mentre sono ancora caldi, copriteli con la glassa di albicocche, quindi formate su questa uno strato sottile di glassa fondente al limone.',4150);
INSERT INTO "ricette" VALUES (13944,'Lumachine Di Mare Al Finocchietto','Pesce','Lumache Di Mare',4,' -','1000 G Lumachine Di Mare,
400 G Polpa Di Pomodoro Fresco,
1 Porro,
1 Gambo Sedano,
1 Carota,
1 Mazzetto Finocchietto Selvatico,
1 Spicchio Aglio,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale Grosso E Fino,
Pepe Nero','Risciacquate più volte le lumachine di mare, quindi raccoglietele in una capace teglia, copritele di acqua fredda, aggiungete il porro, il sedano e la carota, una manciata di sale grosso, portatele su fuoco moderato e, al bollore, calcolate 2 minuti, quindi scolatele. Soffriggete in una casseruola un grosso spicchio d''aglio in 3 cucchiai d''olio caldo; unite le lumachine, fatele insaporire a fuoco vivo per 3 minuti, poi aggiungete abbondante finocchietto selvatico tritato, la polpa di pomodoro ridotta a dadini, una macinata di pepe, incoperchiate, riducete la fiamma e lasciate stufare per circa 30 minuti; alla fine, correggete di sale (sarà sufficiente un pizzico di quello fino), quindi completate con un trito fresco di finocchietto; trasferite in una ciotola adeguata le lumachine con tutto il loro saporito intingolo e servitele immediatamente, calde.',1689);
INSERT INTO "ricette" VALUES (13945,'Lumachine Di Sant''anna','Antipasto','Lumachine',4,' -','Lumachine,
Olio D''oliva Extra-vergine,
Alcuni Spicchi Aglio,
Alcune Foglie Menta Fresca','Dopo averle spurgate per 2-3 giorni, lavare bene le lumachine in acqua e sale e sbollentarle a fuoco lento. Servire semplicemente con olio d''oliva extra-vergine, alcuni spicchi d''aglio e foglie di menta fresca.',835);
INSERT INTO "ricette" VALUES (13946,'Luna Nera','Bevande','Gin',1,' -','1/5 Vermouth Dry,
2/5 Apricot Brandy,
2/5 Gin','Agitare nel mixer, con poco ghiaccio. Servire nel calice basso con un cubetto di ghiaccio.',321);
INSERT INTO "ricette" VALUES (13947,'Luna Nera (2)','Bevande','Gin',1,' -','1/5 Vermouth Dry,
2/5 Apricot Brandy,
2/5 Gin,
Per Servire:,
Alcuni Pezzetti Albicocche,
1 Scorza Pompelmo','Agitare nel mixer, con poco ghiaccio. Servire nel calice ampio con pezzetti di albicocche e una scorza di pompelmo.',357);
INSERT INTO "ricette" VALUES (13948,'Lunatico','Bevande','Cointreau',1,' -','3/10 Tanqueray Gin,
3/10 Cointreau,
3/10 Vodka Keglevich Fragola,
1/10 Rose''s Lime Juice Cordial','Si prepara nello shaker con abbondante ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda.',335);
INSERT INTO "ricette" VALUES (13949,'Lunga Estate','Bevande','Whisky',1,' -','1/4 Succo Di Limone,
2/4 Crema Di Menta Bianca,
1/4 Whisky,
Per Servire:,
Molta Soda Fredda','Scuotere nello shaker con ghiaccio in cubetti. Servire nel tumbler ampio, con molta soda ben fredda.',283);
INSERT INTO "ricette" VALUES (13950,'Lusia','Bevande','Tequila',1,' -','6/10 Jose Cuervo Tequila,
4/10 Kahlua','Mescolare delicatamente.',388);
INSERT INTO "ricette" VALUES (13951,'Lussuoso','Bevande','Gin',1,' -','1/8 Succo Di Limone,
1/8 Pernod,
6/8 Gin,
2 Spruzzi Granatina,
1 Spruzzo Angostura,
Per Servire:,
1 Fettina Limone','Scuotere a lungo nello shaker con poco ghiaccio in cubetti. Servire nel flute con una fettina di limone.',390);
INSERT INTO "ricette" VALUES (13952,'Lussuria','Bevande','Gin',1,' -','1/6 Succo Di Limone,
1/6 Vermouth,
1/6 Crema Di Banana,
3/6 Gin,
1 Spruzzo Angostura','Scuotere nello shaker con poco ghiaccio in cubetti. Servire nel calice basso.',297);
INSERT INTO "ricette" VALUES (13953,'Luxus','Bevande','Vodka',1,' -','2/6 Vodka Keglevich Classica,
1/6 Succo Di Pompelmo,
1/6 Succo D''arancia,
2/6 Maraschino Luxardo,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino,
1 Spicchio Limone','Si prepara nello shaker con ghiaccio cristallino. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa al maraschino su uno spicchio di limone.',271);
INSERT INTO "ricette" VALUES (13954,'Macaroni','Bevande','Vermouth Rosso',1,' -','1/3 Vermouth Rosso,
2/3 Pernod,
Per Servire:,
1 Fettina Pomodoro','Agitare nello shaker con ghiaccio tritato. Servire nel gotto basso, con una fettina di pomodoro.',242);
INSERT INTO "ricette" VALUES (13955,'Maccaroni Di Casa Alla Pastorella','Primo','Salsiccia',4,'Luogo: Calabria.','500 G Farina Di Grano Integrale,
3 Uova,
10 Cl Olio D''oliva Extra-vergine,
100 G Carne Di Maiale Tritata,
2 Cipolle,
100 G Concentrato Di Pomodoro,
1/2 Bicchiere Vino Rosso Asciutto,
Alcune Foglie Alloro,
Sale,
Pepe,
1/3 Cucchiaino Semi Di Finocchio,
1 Salsiccia Di Maiale,
100 G Ricotta Salata Secca Grattugiata','Sulla spianatoia disponete la farina a fontana e mettetevi nel mezzo le uova e tanta acqua da fare un impasto molto asciutto. Tagliatelo in pezzi, arrotolateli sull''asse con le mani a ridurli allo spessore di una matita e tagliate in pezzetti di 3-4 cm. Appoggiate su ciascuno di essi un ferro da calza sottile, arrotolateli fino a raggiungere la lunghezza di 8-10 cm., sfilate il ferro in modo che resti il buco e mettete ad asciugare i maccheroni su una tovaglia cosparsa di farina. In un tegame di coccio fate scaldare l''olio, rosolatevi la carne tritata, aggiungete le cipolle tritate e, appena imbiondite, il sale, il pepe, i semi di finocchio e l''alloro. Bagnate col vino e quando sarà evaporato unite il concentrato di pomodoro, allungando con un po'' d''acqua. Fate cuocere per un paio d''ore. A parte cuocete la salsiccia e sminuzzatela. Sgocciolatela. Sgocciolate al dente i maccheroni che avrete lessato in acqua leggermente salata, conditeli con il sugo e cospargeteli di ricotta salata secca grattugiata e di salsiccia sminuzzata.',3717);
INSERT INTO "ricette" VALUES (13956,'Maccarruni A Ra Tamarra','Primo','Pomodori',4,'Luogo: Calabria.','400 G Pasta Tipo Maccarruni (pasta Tipo Fusilli),
1/2 Cipolla,
1 Spicchio Aglio,
400 G Pomodori Pelati,
200 G Funghi Porcini Sott''olio,
50 G Olive Nere,
1/2 Peperoncino Rosso Piccante,
1 Ciuffetto Prezzemolo,
1/3 Cucchiaino Semi Di Finocchio,
70 G Capocollo,
10 Cl Olio D''oliva Extra-vergine,
70 G Ricotta Di Pecora Affumicata Stagionata,
Sale','In un ampio tegame di coccio fate soffriggere con l''olio la cipolla finemente affettata e l''aglio che eliminerete appena dorato. Unite i pomodori privati dei semi e dell''acqua di vegetazione, i funghi tagliati a pezzetti (se secchi, li avrete già bene ammollati in acqua tiepida), le olive nere snocciolate e tagliate a metà, il peperoncino rosso tagliuzzato, il prezzemolo tritato, i semi di finocchio e il capocollo a striscioline. Saltate e fate cuocere a fuoco lento con il tegame incoperchiato. Lessate i fusilli al dente, sgocciolateli bene, metteteli in una capace insalatiera, conditeli con la salsa e cospargeteli di ricotta affumicata e stagionata grattugiata, bene amalgamandoli con l''aiuto di un forchettone di legno, versateli in una tortiera nella quale avrete messo qualche cucchiaiata di salsa e mettete in forno caldo per alcuni minuti. Per insaporire meglio i fusilli, o qualsiasi altra pasta che va condita nell''insalatiera, vi consigliamo di cospargere il fondo del recipiente da portata di abbondante formaggio (in questo caso di ricotta grattugiata). Versatevi sopra la pasta ben scolata, mescolate e condite con la salsa. In superficie un''ultima spolverata di formaggio.',3046);
INSERT INTO "ricette" VALUES (13957,'Maccarruni A Ru Ferru','Primo','Uova',4,'Luogo: Calabria.','500 G Farina,
5 Uova,
1 Cucchiaio Olio D''oliva,
Sale,
100 G Formaggio Pecorino Grattugiato,
Ragù D''agnello (o Ragù Di Maiale)','Preparate la pasta mettendo a fontana sulla spianatoia la farina setacciata. In una terrina rompete le uova, unite l''olio e un pizzico di sale, sbattetele e versatele nel mezzo della fontana. Lavorando con le dita, portate, poco alla volta, la farina nel centro, poi, con ambedue le mani, lavorate bene la pasta fino a renderla ben sostenuta. Con il matterello tirate delle sfoglie, tagliatele in piccoli quadrati, avvolgeteli all''apposito ferro sottile, sfilatene i cilindretti di pasta ricavati e allineateli via via su un canovaccio cosparso di farina per farli seccare leggermente. Calate la pasta in abbondante acqua leggermente salata, sgocciolatela al dente, ricopritela di formaggio grattugiato e di un ragù d''agnello o di maiale.',2942);
INSERT INTO "ricette" VALUES (13958,'Maccarruni Con Ragù Di Ghiro E Tordi','Primo','Ghiro',4,'Luogo: Calabria.','500 G Farina,
1 Ghiro Giovane,
Aceto Di Vino Bianco,
8 Tordi,
1 Spicchio Aglio,
1 Cipolla,
1000 G Pomodori Pelati,
1 Cucchiaio Concentrato Doppio Di Pomodoro,
1 Cucchiaio Prezzemolo Tritato,
1/2 Cucchiaio Basilico Spezzettato,
1/2 Bicchiere Vino Rosso Asciutto,
10 Cl Olio D''oliva Extra-vergine,
1 Peperoncino Rosso Piccante,
Sale,
Formaggio Parmigiano Grattugiato','L''uso della carne di ghiro, di cui erano ghiotti gli antichi abitanti di Pompei e di Ercolano, è assai diffuso in Calabria, così come quella del porcellino d''India, che viene anch''esso allevato per scopi gastronomici, come, per esempio, a s. Agata d''esaro. Il ghiro ricorda nell''aspetto lo scoiattolo, vive soprattutto nei boschi, è nottambulo e onnivoro voracissimo. Vive facilmente in prigionia e, se ben nutrito, diventa molto grasso. Figura nell''antica cucina francese (''ghiro farcito'') e nella cucina campana (''ghiri alla pizzaiola'' di san martino valle caudina). Con la farina preparate i ''maccarruni a ru fierru'' secondo l''apposita ricetta e metteteli a seccare un poco. Spellate il ghiro eliminando la parte eccessiva di grasso aderente alla pelle, sventratelo e lasciatelo in acqua corrente per un giorno e una notte. Tagliatelo a pezzi, mettetelo per un''oretta in una miscela d''acqua e aceto (metà e metà) e risciacquatelo bene. Pulite delicatamente i tordi (molti buongustai preferiscono limitarsi a spiumarli, senza vuotarli delle interiora). In un capace tegame di coccio soffriggete con la sugna e l''olio la cipolla tritata e l''aglio a spicchi, mettete i pezzi di ghiro e i tordi, fateli rosolare e bagnate con il vino. Appena evaporato il vino, tirate via i tordi e metteteli da parte, unite i pomodori privi dei semi e la conserva disciolta in un po'' d''acqua tiepida, il sale, il prezzemolo, il basilico e il peperoncino tagliuzzato finemente. Fate cuocere a recipiente coperto e a calore moderato. A metà cottura rimettete nella salsa i tordi e lasciate ancora cuocere per il tempo necessario. Col sugo condite i ''maccarruni'' appena cotti (in acqua abbondante e salata) e scolati. Cospargete di formaggio. Nello stesso piatto potrete poi servire le carni.',6651);
INSERT INTO "ricette" VALUES (13959,'Maccheroncelli Con Le Sarde','Primo','Sarde',4,'Luogo: Calabria.','400 G Pasta Tipo Maccheroncelli,
500 G Sarde Fresche,
1 Cucchiaio Uvetta Sultanina,
2 Spicchi Aglio,
15 Cl Olio D''oliva Extra-vergine,
Sale','Pulite bene le sarde e lessatele a metà cottura. Soffriggete l''aglio con l''olio, unitevi le sarde ben sgocciolate, lasciate che cuociano a calore moderato per qualche minuto, poi aggiungete l''uva passa. Mescolate bene, salate e completate la cottura. Lessate i maccheroncelli, sgocciolateli al dente e conditeli con il soffritto e le sarde.',3248);
INSERT INTO "ricette" VALUES (13960,'Maccheroncelli Con Salsa Di Tonno E Broccoletti','Primo','Tonno',6,' -','500 G Pasta Tipo Maccheroncelli,
150 G Tonno,
300 G Broccoletti,
3 Spicchi Aglio,
60 G Olio D''oliva Extra-vergine,
Prezzemolo,
Sale,
Pepe (o Peperoncino)','Scaldate in tegame l''olio, unite l''aglio finemente affettato, oppure gli spicchi interi, ma schiacciati, che poi si toglieranno. Date qualche rigirata; appena l''aglio accenna a prendere colore, unite l''acciuga, prima ben lavata, per dissalarla, e tritata minutamente; aspettate che arrivi a disfarsi, unite il tonno ben sbriciolato. Date qualche minuto di cottura, in modo che tutto leghi, poi unite i broccoletti, precedentemente lessati al dente e tagliati a pezzettini, oppure passati addirittura al setaccio e ridotti in purea. Ancora qualche minuto sul fuoco perché tutto leghi e si insaporisca assieme, aggiustando di sale e pepe, o peperoncino: e allungando con qualche cucchiaiata di acqua calda se la salsa risultasse troppo densa. Con questa salsa condite la pasta, lessata bene al dente e molto ben scolata.',2714);
INSERT INTO "ricette" VALUES (13961,'Maccheroncini Ai Piselli','Primo','Piselli',4,' -','300 G Piselli Surgelati,
300 G Pasta Tipo Maccheroncini,
2 Cipolle,
30 G Burro,
3 Cucchiai Olio D''oliva,
Prezzemolo,
1 Pizzico Zucchero,
Sale,
Pepe','In un tegame mettere le cipolle finemente affettate, i piselli, l''olio, il burro, un pizzico di zucchero e acqua fredda fino a coprire a filo i piselli. Salare, pepare, coprire con un coperchio e cuocere per 10 minuti a fuoco moderato. Lessare la pasta al dente, condirla con i piselli, cospargere con il prezzemolo tritato e servire.',2581);
INSERT INTO "ricette" VALUES (13962,'Maccheroncini Ai Quattro Formaggi','Primo','Formaggio Fontina',1,' -','400 G Acqua,
3 Cucchiai Pasta Tipo Maccheroncini,
1 Cucchiaino Olio D''oliva,
Mozzarella,
Formaggio Groviera,
Formaggio Fontina,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Sale','In 400 g d''acqua bollente, leggermente salata, versare 3 cucchiai di maccheroncini. Far bollire per 8 minuti. Scolare e condire rapidamente con un cucchiaino d''olio d''oliva, un po'' di mozzarella, groviera e fontina tagliata a dadini ed un cucchiaio di parmigiano grattugiato. Mescolare con cura e servire.',1426);
INSERT INTO "ricette" VALUES (13963,'Maccheroncini Al Finocchietto','Primo','Finocchietti',4,'Ricetta adatta a: bambini piccoli.','600 G Pasta Di Grano Duro Di Tipo Artigianale,
300 G Finocchietti Selvatici,
100 G Acciughe Salate,
1 Cipolla,
2 Spicchi Aglio,
2 Cucchiai Capperi Sotto Sale,
Peperoncino,
4 Cucchiai Olio D''oliva Extra-vergine,
1 Manciata Mollica Di Pane Raffermo Grattugiata','Raschiate le acciughe, lavatele e diliscatele. Lavate i finocchietti, eliminate la parte dura dei gambi e tritateli. Fate appassire la cipolla tritata con 3 cucchiai di olio caldo. Appena prende colore, unite le acciughe, fatele disfare, quindi aggiungete i finocchietti, l''aglio tritato, il peperoncino e i capperi sciacquati. Mescolate e lasciate cuocere a fuoco dolce per 10 minuti. Fate tostare poi la mollica di pane in una padella con i cucchiaio di olio, mescolando finché avrà preso un bel colore biondo. Cuocete la pasta, scolatela al dente, fatela saltare per 2 minuti nella padella con il sugo e spolveratela con la mollica tostata.',3050);
INSERT INTO "ricette" VALUES (13964,'Maccheroncini Al Fumé','Primo','Passata Di Pomodoro',4,' -','500 G Pasta Tipo Maccheroncini,
2 Spicchi Aglio,
1/2 Cipolla,
Olio D''oliva,
2 Peperoncini,
Sale,
Pepe,
8 Cl Panna Da Cucina,
1 Bicchiere Vino Bianco Secco,
700 Cl Passata Di Pomodoro (o Pomodori Pelati),
130 G Pancetta A Dadini Affumicata','Fare un soffritto con l''olio d''oliva e aggiungere la pancetta affumicata, dopodichè, quando la pancetta ha preso colore, aggiungere la cipolla finemente tritata, l''aglio, il peperoncino e fare rosolare per qualche minuto avendo cura di non farli annerire. Aggiungere il vino bianco e quando è evaporato, aggiungere il pomodoro, sale e pepe e fare cuocere il sugo per circa 30 minuti a fuoco lento. Quando la cottura dei maccheroncini è ultimata, farli saltare assieme al sugo aggiungendo la panna da cucina e servire con parmigiano grattugiato.',4435);
INSERT INTO "ricette" VALUES (13965,'Maccheroncini Al Gratin','Primo','Maccheroni',4,' -','500 G Pasta Tipo Maccheroni Cotti Al Dente,
50 Cl Salsa Bechamel,
6 Cucchiai Formaggio Emmenthal Grattugiato,
4 Cucchiai Formaggio Parmigiano,
Sale,
Pepe,
Noce Moscata,
Pangrattato','Accendete il forno a 180 gradi. Cuocete i maccheroni molto al dente (se la confezione indica 14 minuti, voi calcolatene 12) e nel frattempo preparate la bechamel aggiungendo però un bicchiere di latte per renderla più liquida. Scolate, rimetteteli nella pentola di cottura e conditeli bene con la bechamel e i formaggi. Aggiungete una grattatina di noce moscata e, se ce ne fosse bisogno, sale e pepe. Versateli in una pirofila, spolverizzateli con del pangrattato mettendo qua e là qualche fiocchetto di burro. Infornate per 15 minuti fino a quando si sarà formata una bella crostina dorata.',3528);
INSERT INTO "ricette" VALUES (13966,'Maccheroncini Al Pepe Verde','Primo','Pepe Verde',4,' -','2 Tuorli D''uovo,
3 Cucchiai Panna Liquida,
40 G Burro,
2 Cucchiai Pepe Verde In Grani,
350 G Pasta Tipo Maccheroncini,
4 Cucchiai Formaggio Parmigiano Grattugiato','Portare a bollore poca acqua in un pentolino e versarvi i tuorli. Cuocerli per 3 minuti dalla ripresa del bollore, scolarli con una schiumarola e porli in una zuppiera. Unire la panna e 4 cucchiai di parmigiano e lavorare con una forchetta. Aggiungere un mestolo di acqua di cottura della pasta. Aggiungere il burro spezzettato e il pepe. Lessare la pasta, scolarla, versarla nella zuppiera con tutti gli ingredienti, mescolare e servire.',2216);
INSERT INTO "ricette" VALUES (13967,'Maccheroncini Al Prosciutto','Primo','Prosciutto',4,' -','500 G Pasta Tipo Maccheroncini,
100 G Prosciutto Cotto (fette Da 100 G),
100 G Burro,
100 G Formaggio Parmigiano Grattugiato,
Salvia,
Sale,
Pepe','Tagliare a quadretti il prosciutto, metterlo in un tegame con il burro fuso e alcune foglie di salvia, pepare e far rosolare per 5 minuti. Cuocere i maccheroncini al dente in abbondante acqua salata, condirli con la salsa preparata ed il parmigiano e servire.',3240);
INSERT INTO "ricette" VALUES (13968,'Maccheroncini Al Prosciutto (2)','Primo','Prosciutto',1,'Ricetta adatta a: bambini piccoli.','2 Cucchiai Pasta Tipo Maccheroncini,
30 G Prosciutto Cotto Senza Conservanti,
1 Zucchina,
1 Cucchiaino Formaggio Parmigiano Grattugiato,
1 Cucchiaino Olio D''oliva Extra-vergine','Lessate a vapore la zucchina, dopo averla ben pulita e tagliata a tocchetti. Passatela al setaccio insieme al prosciutto e tritate per alcuni secondi. Lessate in acqua i maccheroncini per 7-8 minuti, quindi scolateli lasciando un po'' d''acqua di cottura. Conditeli col composto di prosciutto e zucchina, unite l''olio quindi spolverateli di parmigiano e servite.',469);
INSERT INTO "ricette" VALUES (13969,'Maccheroncini Al Ragù','Primo','Carne Tritata',4,' -','400 G Pasta Tipo Maccheroncini,
300 G Carne Tritata,
2 Cucchiai Conserva Di Pomodoro,
1 Cipolla,
30 G Burro,
3 Cucchiai Olio D''oliva,
Vino Rosso,
Latte,
Sale','Far rosolare in una casseruola la cipolla tritata con l''olio e il burro, unire la carne, spruzzarla di vino, aggiungere la conserva di pomodoro diluita con poco latte, salare e far cuocere per circa 1 ora. Condire con questa salsa la pasta cotta al dente e servire.',3090);
INSERT INTO "ricette" VALUES (13970,'Maccheroncini Al Vesuvio','Primo','Maiale',4,' -','400 G Carne Di Maiale,
2 Cipolle,
4 Cucchiai Olio D''oliva,
30 G Strutto,
30 G Salame Napoletano,
30 G Prosciutto Crudo,
1 Carota,
Sedano,
Salsa Di Pomodoro,
Sale,
Pepe,
1 Scatola Mais,
400 G Pasta Tipo Maccheroncini,
Abbondante Formaggio Parmigiano (o Formaggio Pecorino Dolce)','In un recipiente di terracotta mettete con l''olio e lo strutto la cipolla tagliata sottile, con il sedano a piccoli pezzi e la carota pure affettata sottilmente. Aggiungete la carne, il salame ed il prosciutto a piccoli pezzi, coprite di acqua e cuocete a fuoco basso. Quando l''acqua sarà totalmente evaporata, mescolate il sugo, aggiungete sale e pepe, ancora un bicchiere ai acqua e continuate la cottura per altri 30 minuti a fuoco sempre basso. Per ultimo unite il mais scolato dal suo liquido, la salsa di pomodoro e cuocete ancora per 15 minuti prima di versarla sui maccheroncini lessati al dente in abbondante acqua salata. Servite con abbondante parmigiano o pecorino dolce.',5169);
INSERT INTO "ricette" VALUES (13971,'Maccheroncini Alla Mediterranea','Primo','Passata Di Pomodoro',4,' -','400 G Pasta Tipo Maccheroncini,
450 G Passata Di Pomodoro,
Origano,
Formaggio Grana,
4 Spicchi Aglio,
4 Cucchiai Olio D''oliva,
1 Cucchiaino Aceto Di Vino,
Sale,
Pepe','Cuocere la pasta al dente. Intanto preparare il condimento che non deve cuocere. Versare in 1 terrina l''olio, l''aceto, unire gli spicchi d''aglio schiacciati, l''origano e frullare il tutto con 1 frusta, unendo man mano il passato di pomodoro. Salare, pepare e rovesciare sul sugo la pasta cotta bollente, unendo abbondante grana grattugiato e mescolare velocemente per ben condire e in modo che la pasta non si raffreddi.',3261);
INSERT INTO "ricette" VALUES (13972,'Maccheroncini Alla Pugliese','Primo','Cavolfiore',4,'Luogo: Puglia.','400 G Pasta Tipo Maccheroncini,
1000 G Cimette Di Cavolfiore Verde,
120 G Lardo,
Formaggio Pecorino Grattugiato,
Pepe,
Sale','Mondare le cimette di cavolfiore e farle lessare in abbondante acqua salata, quasi a fine cottura unire i maccheroncini e farli cuocere insieme. Soffriggere il lardo tagliato a dadini senza farlo rosolare. Scolare la pasta e le cimette e condirle con il lardo, pepe e il pecorino.',3043);
INSERT INTO "ricette" VALUES (13973,'Maccheroncini Allo Zafferano','Primo','Zafferano',4,' -','2 Bustine Zafferano,
300 G Pasta Tipo Maccheroncini,
Sale,
50 G Burro,
Formaggio Parmigiano (facoltativo)','In un grande tegame stemperare lo zafferano con poca acqua fredda, poi unire altra acqua fredda fino al livello di un dito. Portare a bollore su fuoco vivace. Versarvi i maccheroncini e portare a cottura aggiungendo poco alla volta altra acqua calda. Regolarsi in modo che alla fine rimangano in fondo alla pentola 300-400 g di sugo. Condire la pasta con il burro a pezzetti, mescolare e servire. Il parmigiano è facoltativo.',1799);
INSERT INTO "ricette" VALUES (13974,'Maccheroncini Con Carciofi ''a Fungetiello''','Primo','Carciofi',4,' -','400 G Pasta Tipo Maccheroncini,
3 Cucchiai Olio D''oliva,
6 Carciofi,
1 Limone,
2 Spicchi Aglio,
60 G Olive Nere,
1 Manciatina Capperi Sotto Sale,
4 Filetti D''acciughe Salate,
Prezzemolo,
Sale,
Pepe','Pulite i carciofi, togliendo le parti dure e le punte, tagliateli a piccoli spicchi e metteteli in acqua acidulata con il succo di limone. Scaldate l''olio con l''aglio tritato e i filetti di acciughe puliti, dissalati e tagliati a pezzetti; fateli sciogliere e poi unite i carciofi. Lasciateli cuocere 5 minuti, quindi unite i capperi lavati e le olive snocciolate e tagliate a pezzi. Coprite il tegame e fate cuocere circa mezz''ora; alla fine regolate di sale, mettete il prezzemolo tritato e una spruzzata di pepe. Intanto lessate la pasta molto al dente. Quando è cotta, scolatela e passatela nel tegame con il sugo di carciofi. Cuocete tutto insieme per un paio di minuti e, se vi sembra troppo asciutta, allungate con un po'' dell''acqua di cottura della stessa pasta. Servite subito.',2792);
INSERT INTO "ricette" VALUES (13975,'Maccheroncini Con Crema Di Tonno E Pomodori','Primo','Pomodori Perini',4,' -','400 G Pasta Tipo Maccheroncini Rigati,
300 G Pomodori Perini,
1 Cipolla,
4 Filetti D''acciughe Sott''olio,
Olio D''oliva,
200 G Tonno Sott''olio,
1/2 Bicchiere Vino Bianco,
1 Manciata Erba Cipollina,
Sale,
Pepe','Lavate con cura i pomodori, tagliate le estremità, spellateli, eliminate i semi, tagliateli a dadini e lasciateli scolare per qualche minuto. In una padella antiaderente, fate riscaldare l''olio e dorare la cipolla, dopodichè, aggiungete le acciughe sgocciolate e tagliate a pezzetti e lasciatele sciogliere schiacciandole con una forchetta. Successivamente, unite il tonno e il vino e cuocete per circa 7-8 minuti facendo insaporire il tutto. A cottura ultimata, frullate gli ingredienti fino ad ottenere una crema omogenea e rimettetela nel tegame. Versate i pomodori tagliati a dadini e fate cuocere per altri 15 minuti a fuoco medio. Infine, aggiungete l''erba cipollina, il sale e il pepe. Nel frattempo, cuocete i maccheroncini in acqua salata, scolateli al dente e conditeli in padella mescolandoli al sugo. Amalgamate bene e serviteli subito caldi.',2738);
INSERT INTO "ricette" VALUES (13976,'Maccheroncini Con Ricotta E Carciofi','Primo','Ricotta',4,' -','400 G Pasta Tipo Maccheroncini,
200 G Ricotta,
6 Carciofi,
Formaggio Parmigiano Grattugiato,
Olio D''oliva Extra-vergine,
2 Cucchiai Capperi,
4 Filetti D''acciughe Sott''olio,
Sale','Pulite bene i carciofi, eliminando metà delle foglie e le punte. Subito dopo, tagliateli e disponeteli in una ciotola colma di acqua e succo di limone per circa 10 minuti, dopodichè, scolateli e versateli in una padella capiente con olio ben caldo e aglio. Cuoceteli a fiamma alta per i primi 5 minuti, in seguito, abbassate la fiamma e continuate la cottura per altri 15 minuti coprendoli con un coperchio. A cottura ultimata, frullateli e versateli in una ciotola capiente; aggiungete il parmigiano grattugiato, i capperi sminuzzati, le acciughe a pezzetti, il sale e mescolate bene il tutto fino ad ottenere una morbida crema. Nel frattempo, scottate in acqua salata i maccheroncini, scolateli al dente e conditeli con la crema aggiungendo contemporaneamente 2 cucchiai di acqua di cottura. Serviteli subito caldi. Suggerimento: potreste amalgamare i maccheroncini con una parte della crema, metterli in una pirofila unta di burro, coprirli con altra crema, cospargerli di caciocavallo a fette e gratinarli in forno caldo per circa 15 minuti.',2839);
INSERT INTO "ricette" VALUES (13977,'Maccheroncini Con Scampi E Funghi','Primo','Scampi',6,' -','500 G Pasta Tipo Maccheroncini,
200 G Polpa Di Scampi,
80 G Funghi Freschi,
100 G Burro,
Prezzemolo,
Sale','Lessate, sgusciate gli scampi, ricavatene la polpa. Nettate, affettate, fate rosolare i funghi con metà del burro; unite un pizzico di sale e uno più generoso di pepe, magari appena macinato; unite anche la polpa di scampi tagliata a dadini, date qualche rimescolata perché i sapori leghino. Condite con questo sugo e con il resto del burro la pasta cotta al dente, spargete sopra una manciata di prezzemolo tritato: servite.',2673);
INSERT INTO "ricette" VALUES (13978,'Maccheroncini Di Braccio Di Ferro','Primo','Spinaci',4,' -','400 G Pasta Tipo Maccheroncini Rigati,
150 G Pancetta Affumicata,
500 G Spinaci Cotti,
2 Tuorli D''uovo,
4 Cucchiai Panna Da Cucina Liquida,
Formaggio Parmigiano Grattugiato,
Olio D''oliva,
Sale,
Pepe','Servendovi di un mixer, inserite nel boccale gli spinaci cotti e frullateli per pochi secondi con l''olio d''oliva e una manciata di parmigiano grattugiato. A parte, in una padella, meglio se antiaderente, scaldate la panna e incorporate i tuorli, il sale, il pepe e mescolando, continuate la cottura a fiamma bassissima per circa 10 minuti. In un''altra padella, rosolate la pancetta fino a renderla croccante e dorata e cuocete in acqua salata i maccheroncini. Scolateli al dente e versateli nella padella con la panna, aggiungete gli spinaci tritati, la pancetta affumicata, il parmigiano grattugiato e mescolate energicamente il tutto. Serviteli subito caldi.',3774);
INSERT INTO "ricette" VALUES (13979,'Maccheroncini Estivi','Primo','Pisellini',4,' -','400 G Pasta Tipo Maccheroncini Ritorti,
100 G Prosciutto Cotto,
150 G Pisellini Primavera,
2 Pomodori,
2 Limoni,
Prezzemolo,
Olio D''oliva,
Sale','Lavare i pomodori, privarli dei semi e tagliarli a dadini; lessare i piselli; tagliare a cubetti il prosciutto; tritare il prezzemolo e mettere tutto in una terrina. Cuocere la pasta in abbondante acqua salata, scolarla al dente, versarla nella terrina, condire con olio e succo di limone e mettere in frigorifero per circa un''ora prima di servire.',2648);
INSERT INTO "ricette" VALUES (13980,'Maccheroncini Filanti','Primo','Formaggio Brie',1,'Ricetta adatta a: bambini piccoli.','80 G Formaggio Brie,
200 G Pasta Tipo Maccheroncini,
100 G Fagiolini Fini,
200 G Spinaci,
30 G Burro,
Sale','Lavare gli spinaci e tagliare il brie a dadini piccolissimi. Mettere i fagiolini in una pentola d''acqua salata e, dal momento del bollore, far cuocere cinque minuti. Aggiungere la pasta e gli spinaci. A cottura ultimata, scolare e versare in una zuppiera, unire il burro già fuso e i dadini di formaggio. Mescolare bene e servire subito.',1221);
INSERT INTO "ricette" VALUES (13981,'Maccheroncini Gialli','Primo','Zafferano',4,' -','300 G Pasta Tipo Maccheroncini,
2 Bustine Zafferano,
50 G Burro,
Sale,
Formaggio Parmigiano Grattugiato','In un tegame largo a pareti alte diluire lo zafferano in poca acqua fredda, aggiungere altra acqua e portare ad ebollizione; versare i maccheroncini, salare e cuocere e fuoco moderato. Man mano che occorre aggiungere ai maccheroncini acqua bollente. A fine cottura deve rimanere un sugo allo zafferano abbastanza ristretto. Condire con il burro e il parmigiano e servire.',1799);
INSERT INTO "ricette" VALUES (13982,'Maccheroncini Gialli Con Sugo All''amatriciana','Primo','Pomodoro',4,' -','300 G Pasta Tipo Maccheroncini Gialli Di Zucca,
150 G Pancetta,
300 G Pomodori,
2 Cucchiai Olio D''oliva,
1 Peperoncino Rosso,
1 Cipolla,
Sale,
4 Cucchiai Formaggio Pecorino Grattugiato,
2 Cucchiai Basilico Tritato','Fate scaldare l''olio d''oliva in una casseruola e rosolatevi dolcemente la pancetta tagliata a dadini, fino a quando comincia a prendere colore. A questo punto toglietela dal recipiente e mettetevi la cipolla, mondata e tritata, e il peperoncino rosso, sminuzzato. Fateli soffriggere a calore moderato per 4-5 minuti, dopodichè unite i pomodori, pelati, privati dei semi e ridotti a filetti, e il sale necessario. Lasciate cuocere la salsa per 15 minuti circa, in modo che si addensi, infine unite la pancetta, togliete dal fuoco e cospargete col basilico tritato finemente. Portate ad ebollizione una pentola piena d''acqua salata, tuffatevi i maccheroncini e lessateli al dente. Scolateli, poneteli in una zuppiera e conditeli con il sugo ben caldo. Suddividete la pasta in quattro piatti fondi individuali e portate in tavola, servendo a parte il Pecorino grattugiato. --- CONSIGLI. Se desiderate preparare personalmente i maccheroncini dove- te aggiungere all''impasto base di farina e uova della purea di zucca. La zucca va prima cotta nel forno, quindi passata al setaccio e fatta asciugare in un pentolino a calore dolcissimo, infine lasciata intiepidire e impastata con uova e farina. Le proporzioni sono di 250 g di polpa di zucca cruda per 400 g di farina e 2 uova.',2389);
INSERT INTO "ricette" VALUES (13983,'Maccheroncini In Bianco','Primo','Carne Tritata',4,' -','280 G Pasta Tipo Maccheroncini,
20 G Funghi Secchi,
1/2 Cipolla,
200 G Carne Tritata,
Prezzemolo,
1 Carota,
Sale,
Pepe,
Olio D''oliva,
1/2 Bicchiere Vino Bianco,
1/2 Bicchiere Latte,
Formaggio Grattugiato','Insaporite nell''olio carne, funghi fatti rinvenire e spezzettati, prezzemolo, carota e cipolla tritati; aggiungete 1/2 bicchiere di vino bianco e fate evaporare; versate 1/2 bicchiere di latte tiepido e spegnete quando la carne è cotta. Lessate i maccheroncini, condite con il sugo bianco e il formaggio.',2401);
INSERT INTO "ricette" VALUES (13984,'Maccheroncini Indiavolati','Primo','Peperoncino Piccante',4,' -','300 G Pasta Tipo Maccheroncini,
2 Cucchiai Cipolla Tritata,
5 Cucchiai Olio D''oliva,
1 Peperoncino Piccante,
85 G Tonno Sott''olio,
1 Cucchiaino Prezzemolo Tritato,
1 Mestolo Brodo,
50 G Formaggio Provolone Affumicato,
Sale','Cuocete la pasta in acqua salata. Soffriggete la cipolla nell''olio, aggiungete il peperoncino tritato, il prezzemolo e il brodo e lasciate insaporire un paio di minuti. Aggiungete anche il tonno e cuocete per altri 5 minuti. Scolate la pasta e conditela subito con la salsa piccante e il provolone tritato. Mescolate finché il formaggio non comincia a filare. Servite ben caldo.',1940);
INSERT INTO "ricette" VALUES (13985,'Maccheroncini Multicolori Con Sugo Di Noci','Primo','Noci',4,' -','75 G Pasta Tipo Maccheroncini Gialli,
75 G Pasta Tipo Maccheroncini Verdi,
75 G Pasta Tipo Maccheroncini Rosa,
75 G Pasta Tipo Maccheroncini Marroni,
150 G Gherigli Di Noci,
50 G Pinoli,
Sale,
Pepe,
1 Panino (mollica),
1 Spicchio Aglio,
1/2 Bicchiere Olio D''oliva','Scottate i gherigli di noci in un pentolino con acqua bollente, scolateli, privateli della pellicina e metteteli in un mortaio. In una ciotola bagnate la mollica di un panino con poca acqua, strizzatela, sminuzzatela e mettete anch''essa nel mortaio. Unite 50 g di pinoli, uno spicchio d''aglio pelato, il sale necessario e una macinata di pepe e pestate gli ingredienti fino a ridurli in poltiglia. Aggiungete lentamente mezzo bicchiere d''olio d''oliva, mescolando con un cucchiaio di legno in modo da amalgamarlo perfettamente al composto. Ponete sul fuoco una pentola piena d''acqua salata, portate ad ebollizione e unite la pasta colorata. Lessatela al dente, scolatela e trasferitela in una zuppiera. Condite velocemente i maccheroncini con la salsa preparata, per evitare che si raffreddino, distribuiteli in quattro piatti fondi individuali e servite.',3227);
INSERT INTO "ricette" VALUES (13986,'Maccheroncini Primaverili','Primo','Pisellini',4,' -','400 G Pasta Tipo Maccheroncini Ritorti,
100 G Prosciutto Cotto,
150 G Pisellini Surgelati,
2 Pomodori,
2 Limoni,
Prezzemolo,
Olio D''oliva,
Sale','Lavare i pomodori, privarli dei semi e tagliarli a dadini. Lessare i piselli, tagliare a cubetti il prosciutto, tritare il prezzemolo e mettere tutto in una terrina. Cuocere la pasta in abbondante acqua salata, scolarla al dente, versarla nella terrina, condire con olio e succo di limone e mettere in frigorifero per circa un''ora prima di servire.',2648);
INSERT INTO "ricette" VALUES (13987,'Maccheroncini Pugliesi','Primo','Cavolfiori',4,'Luogo: Puglia.','400 G Pasta Tipo Maccheroncini,
1000 G Cimette Di Cavolfiore Verde Pugliese,
120 G Lardo,
4 Cucchiai Formaggio Pecorino Grattugiato,
Pepe In Grani,
Sale','Mondare il cavolfiore e lessarlo in acqua bollente salata; quasi a fine cottura unire i maccheroncini e farli cuocere insieme. A parte far soffriggere il lardo a dadini senza farlo rosolare finché diventa quasi trasparente. Condire con il soffritto la pasta e il cavolfiore ben scolati. Cospargere con pecorino e una macinata di pepe.',2967);
INSERT INTO "ricette" VALUES (13988,'Maccheroncini Rosa Ai Carciofi','Primo','Carciofi',4,' -','300 G Pasta Tipo Maccheroncini Rosa Mirtilli,
2 Cucchiai Olio D''oliva,
4 Carciofi,
1 Spicchio Aglio,
Sale,
Pepe,
20 Cl Panna,
2 Cucchiai Prezzemolo Tritato,
1 Limone','Mondate i carciofi eliminando le spine e le foglie esterne, più dure, tagliateli a metà e togliete il fieno, quindi riduceteli a fettine sottili e metteteli a bagno in una terrina colma d''acqua acidulata col succo di un limone, per evitare che anneriscano. Fate rosolare lo spicchio d''aglio in una casseruola con due cucchiai d''olio d''oliva, a calore dolcissimo fino a quando sarà ben dorato, dopodichè toglietelo e mettete nel recipiente i carciofi. Salate, pepate e lasciate cuocere a calore moderato per 10-15 minuti, in modo che i carciofi risultino teneri ma ancora sodi, aggiungendo eventualmente qualche cucchiaio d''acqua. Al termine unite la panna, mescolate e lasciate sul fuoco ancora il tempo necessario perché la salsa si scaldi senza arrivare a bollire, dopodichè spegnete e cospargete con il prezzemolo tritato finissimo. Portate ad ebollizione una pentola piena d''acqua salata, unite i maccheroncini e lessateli al dente, quindi scolateli e poneteli in una zuppiera. Conditeli velocemente con il sugo ai carciofi, ben caldo, distribuiteli in quattro piatti fondi individuali, guarnite con un rametto di prezzemolo e servite.',2224);
INSERT INTO "ricette" VALUES (13989,'Maccheroncini Ubriachi Alla Salsiccia','Primo','Salsiccia',2,' -','220 G Pasta Tipo Maccheroncini,
100 G Salsiccia Fresca Spellata E Sbriciolata,
20 G Olio D''oliva,
1 Bicchiere Panna Fresca,
40 G Formaggio Parmigiano,
1/2 Bicchiere Cognac,
1/2 Dado Da Brodo,
Sale,
Pepe','Fate rosolare nell''olio la salsiccia e quando è ancora morbida aggiungete la panna. Rinforzate il sapore con il dado. Regolate di sale e pepate abbondantemente. Dopo qualche minuto di cottura completate con il cognac; fatelo evaporare prima di condire i maccheroncini lessati in abbondante acqua salata e scolati al dente. Unire parmigiano grattugiato.',1872);
INSERT INTO "ricette" VALUES (13990,'Maccheroncini Verdi Con Ragù Di Carne','Primo','Pomodoro',4,' -','300 G Pasta Tipo Maccheroncini Verdi Spinaci,
400 G Pomodori Pelati,
1 Cipolla,
200 G Carne Tritata Mista (maiale E Manzo),
2 Cucchiai Olio D''oliva,
1 Carota,
1 Gambo Sedano,
4 Cucchiai Formaggio Parmigiano Grattugiato,
50 G Burro,
1 Bicchiere Brodo,
50 G Prosciutto Crudo,
1 Bicchiere Vino Rosso,
Sale,
Pepe,
1 Grattatina Noce Moscata','Mondate la cipolla, il sedano e la carota e riduceteli a dadini minuti insieme al prosciutto crudo, quindi fate soffriggere tutto in una casseruola col burro e l''olio, a calore moderato per 6-7 minuti, mescolando di tanto in tanto con un cucchiaio di legno. Unite la carne tritata, lasciatela rosolare a fuoco vivo per un paio di minuti, poi bagnate il soffritto con un bicchiere di vino rosso e fate cuocere a calore moderatamente vivace per un quarto d''ora, dando ogni tanto una mescolata. Trascorso il tempo indicato aggiungete la polpa dei pomodori, un bicchiere di brodo, una grattatina di noce moscata, il sale necessario e una macinata di pepe e lasciate cuocere a calore dolcissimo per un''ora e mezzo. Ponete sul fuoco una pentola piena d''acqua salata, portate ad ebollizione e tuffatevi i maccheroncini verdi. Lessateli al dente, scolateli, metteteli in una zuppiera e conditeli col ragù preparato. Distribuite la pasta in quattro piatti fondi individuali e portate in tavola, servendo a parte il Parmigiano grattugiato.',2884);
INSERT INTO "ricette" VALUES (13991,'Maccheroni A ''ru Fierro','Primo','Salsiccia',4,'Luogo: Calabria.','500 G Farina Di Grano Integrale,
3 Uova,
10 Cl Olio D''oliva Extra-vergine,
100 G Carne Di Maiale Tritata,
2 Cipolle,
100 G Concentrato Di Pomodoro,
1/2 Bicchiere Vino Rosso Asciutto,
Alcune Foglie Alloro,
Sale,
Pepe,
1/3 Cucchiaino Semi Di Finocchio,
1 Salsiccia Di Maiale,
100 G Ricotta Salata Secca Grattugiata','Sulla spianatoia disponete la farina a fontana e mettetevi nel mezzo le uova e tanta acqua da fare un impasto molto asciutto. Tagliatelo in pezzi, arrotolateli sull''asse con le mani a ridurli allo spessore di una matita e tagliate in pezzetti di 3-4 cm. Appoggiate su ciascuno di essi un ferro da calza sottile, arrotolateli fino a raggiungere la lunghezza di 8-10 cm., sfilate il ferro in modo che resti il buco e mettete ad asciugare i maccheroni su una tovaglia cosparsa di farina. In un tegame di coccio fate scaldare l''olio, rosolatevi la carne tritata, aggiungete le cipolle tritate e, appena imbiondite, il sale, il pepe, i semi di finocchio e l''alloro. Bagnate col vino e quando sarà evaporato unite il concentrato di pomodoro, allungando con un po'' d''acqua. Fate cuocere per un paio d''ore. A parte cuocete la salsiccia e sminuzzatela. Sgocciolatela. Sgocciolate al dente i maccheroni che avrete lessato in acqua leggermente salata, conditeli con il sugo e cospargeteli di ricotta salata secca grattugiata e di salsiccia sminuzzata',3717);
INSERT INTO "ricette" VALUES (13992,'Maccheroni Agli Asparagi','Primo','Asparagi',4,' -','400 G Pasta Tipo Maccheroni,
600 G Punte D''asparagi,
1 Spicchio Aglio,
30 G Burro,
Olio D''oliva,
Vino Bianco,
Brodo,
Panna,
Formaggio Grana Grattugiato,
Sale','Far dorare l''aglio in burro e olio, unire gli asparagi lessati per circa 30 minuti in acqua salata e passati al frullatore, bagnare con il vino e il brodo, cuocere per circa 10 minuti, aggiungere la panna e salare. Cuocere la pasta al dente in abbondante acqua salata, condirla con la salsa preparata, cospargere di grana e servire.',3083);
INSERT INTO "ricette" VALUES (13993,'Maccheroni Agli Spinaci','Primo','Spinaci',4,' -','500 G Pasta Tipo Maccheroni,
450 G Spinaci In Foglia Surgelati,
50 G Burro,
1 Bicchiere Panna Liquida,
Noce Moscata,
Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Lessare gli spinaci in acqua salata, scolarli, strizzarli, passarli al passaverdure, farli insaporire in una casseruola con il burro, unire la panna, poca noce moscata, il sale e il pepe. Cuocere la pasta al dente in abbondante acqua salata, condirla con la salsa preparata, cospargere di parmigiano e servire caldissima.',2815);
INSERT INTO "ricette" VALUES (13994,'Maccheroni Ai Broccoli','Primo','Broccoli Neri',4,' -','400 G Broccoli Neri,
500 G Pasta Tipo Maccheroni,
1 Bicchiere Olio D''oliva,
2 Spicchi Aglio,
1 Peperone Rosso Piccante (fresco O Secco)','Mondate e lavate i broccoli, quindi cuoceteli in abbondante acqua salata. Scolateli e nell''acqua di cottura cuocete i maccheroni spezzettati a metà. Nella stessa pentola, una volta tolta la maggior parte dell''acqua, versate un bicchiere d''olio di oliva nel quale avrete soffritto gli spicchi d''aglio e un peperoncino rosso a pezzetti. Mescolate, unite i broccoli, mescolate ancora e servite.',3161);
INSERT INTO "ricette" VALUES (13995,'Maccheroni Ai Carciofi','Primo','Carciofi',4,' -','400 G Pasta Tipo Maccheroni,
170 G Tonno Sott''olio,
Prezzemolo,
2 Spicchi Aglio,
1 Cucchiaio Conserva Di Pomodoro,
1/2 Bicchiere Vino Bianco,
8 Cuori Carciofi,
Olio D''oliva,
Sale,
1 Macinata Pepe','Soffriggere in 3 cucchiai di olio un trito di aglio e prezzemolo, unire i carciofi a fettine e cuocere per 5 minuti, salare, unire il vino e la conserva. Dopo qualche minuto unire il tonno e 4 cucchiai di acqua, coprire e cuocere ancora per 15 minuti. Lessare i maccheroni, scolarli e condirli con la salsa, profumarli con una macinata di pepe e servire.',2680);
INSERT INTO "ricette" VALUES (13996,'Maccheroni Ai Fagioli','Primo','Fagioli',4,' -','250 G Pasta Tipo Maccheroni,
300 G Fagioli,
80 G Pancetta,
1 Cipolla,
2 Cucchiai Farina,
1 Pizzico Bicarbonato,
Aglio,
Alloro,
Sale,
Pepe','Tenete a bagno i fagioli per una notte intera, il giorno dopo cuoceteli nella stessa acqua e arrivati ad ebollizione aggiungete un pizzico di bicarbonato. Intanto rosolate la cipolla tritata con la pancetta a pezzi, l''aglio, l''alloro e una spolverata di farina. Unite i fagioli, sale e pepe. Cuocete la pasta e poi conditela con la salsa ottenuta.',1669);
INSERT INTO "ricette" VALUES (13997,'Maccheroni Ai Fegatini','Primo','Fegatini Di Pollo',4,' -','350 G Pasta Tipo Maccheroni,
200 G Fegatini Di Pollo,
20 G Mortadella,
1 Scalogno,
1 Carota,
Sedano,
Alloro,
Santoreggia,
Olio D''oliva,
Sale,
Pepe','Cuocere i maccheroni al dente. Intanto, tritare lo scalogno, la carota, il sedano e farli stufare per 5 minuti con l''olio. Unire i fegatini, la mortadella tritata, l''alloro, sale e pepe. Alzare la fiamma e cuocere fino a quando i fegatini saranno rosolati. Poi toglierli, tagliarli a tocchetti e rimetterli nella pentola, tenendo il tutto in caldo. Scolare la la pasta, condirla con il sugo, togliere l''alloro, unire poco olio e distribuirvi sopra la santoreggia tagliuzzata.',2289);
INSERT INTO "ricette" VALUES (13998,'Maccheroni Ai Ferri','Primo','Salsa Di Pomodoro',4,'Luogo: Ciociaria. Luogo: Lazio.','Farina,
Salsa Di Pomodoro,
Carne Di Maiale','Preparare un sfoglia di pasta, acqua e farina, alta almeno 2 mm e dalla consistenza molto elastica. Tagliare in striscie di almeno 3 cm e della lunghezza di 10 cm. Attorcigliare la pasta intorno a un ferro da calza di medie dimensioni e farla rotolare velocemente e con una leggera pressione sulla tavola per tirare la pasta. Posizionare il ferro con la pasta arrotolata in posizione verticale e, con un colpo secco, dall''alto verso il basso, liberare il maccherone dal ferro. Occorre un po'' di manualità per ottenere dei buoni risultati. Cuocere in acqua e condire con salsa di pomodoro e maiale.',890);
INSERT INTO "ricette" VALUES (13999,'Maccheroni Ai Funghi Porcini','Primo','Funghi Porcini',4,' -','350 G Pasta Tipo Maccheroni,
250 G Funghi Porcini,
150 G Pomodori Pelati,
Aglio,
3 Cucchiai Olio D''oliva,
Burro,
Prezzemolo,
Sale,
Pepe','In un tegame scaldate una noce di burro con tre cucchiai d''olio e insaporitevi per alcuni minuti l''aglio intero e i funghi tagliati a fettine. Aggiungete la polpa di pomodoro tritata, regolate sale e pepe, coprite e cuocete piano per circa 20 minuti. A fine cottura aggiungete un po'' di prezzemolo tritato ed eliminate l''aglio. Lessate i maccheroni in abbondante acqua salata a bollore. Scolateli al dente e conditeli con la salsa di funghi. Servite. Questa salsa può essere realizzata anche senza pomodori, in tal caso occorrono 40 g di burro. Vini di accompagnamento: Trentino Müller Thurgau DOC, Collecimoli IGT Dei Colli Della Toscana Centrale, Castel Del Monte Chardonnay DOC.',3136);
INSERT INTO "ricette" VALUES (14000,'Maccheroni Ai Peperoni','Primo','Peperoni',4,' -','350 G Pasta Tipo Maccheroni,
2 Peperoni Gialli,
1 Spicchio Aglio,
4 Acciughe,
Olio D''oliva,
Sale,
Pepe','Pulite i peperoni, lavateli, asciugateli, eliminate semi e filamenti, tagliateli a striscioline. In una padella fate scaldare un po'' d''olio, rosolatevi uno spicchio d''aglio, unite le acciughe e mescolate con un cucchiaio di legno, facendo ben sciogliere. Unite i filetti di peperone, salate, pepate e portateli a cottura. Cuocete la pasta in abbondante acqua salata, scolatela al dente, passatela nella padella dei peperoni e lasciatela sul fuoco alcuni minuti perché insaporisca. Servite subito ben caldo. Se vi piace spolverizzate con un po'' di origano.',1954);
INSERT INTO "ricette" VALUES (14001,'Maccheroni Ai Peperoni (2)','Primo','Peperoni',4,' -','200 G Pasta Tipo Maccheroni,
500 G Peperoni,
Pomodori Pelati,
Olio D''oliva,
Basilico,
Sale','Tagliate i peperoni a strisce sottili e fateli cuocere in una padella con l''olio. Quando saranno cotti aggiungete i pomodori e salate. Nel frattempo lessate la pasta e una volta scolata, fatela insaporire con i peperoni. Aggiungete il basilico e servite.',1523);
INSERT INTO "ricette" VALUES (14002,'Maccheroni Ai Peperoni (3)','Primo','Peperoni Verdi',4,' -','400 G Pasta Tipo Maccheroni,
Acqua,
Sale,
2 Peperoni Verdi,
2 Peperoni Gialli,
5 Foglie Basilico,
2 Spicchi Aglio,
Olio D''oliva','Lavare i peperoni, privateli dei semi e del torsolo, tagliateli a fettine e scottateli poi in un tegame con poco olio per pochi minuti. Abbassate quindi la fiamma e ammorbiditeli stufandoli a tegame coperto per venti minuti circa, mescolando di tanto in tanto e aggiustando infine di sale. Passate poi alla cottura della pasta che, dopo essere stata scolata, sarà versata direttamente nel tegame nel quale avrete stufato i peperoni. Aggiungete le foglie di basilico, l''aglio affettato finemente, un po'' d''olio, mescolate e servite dopo aver lasciato sul fuoco solamente un paio di minuti. ',2151);
INSERT INTO "ricette" VALUES (14003,'Maccheroni Ai Peperoni (4)','Primo','Peperone Rosso',4,' -','350 G Pasta Tipo Maccheroni Alla Chitarra,
1 Peperone Rosso,
1 Peperone Giallo,
1/2 Cipolla,
1 Spicchio Aglio,
Formaggio Pecorino Grattugiato,
300 G Pomodori Pelati San Marzano,
Olio D''oliva Extra-vergine,
Sale,
Peperoncino','Appassire nel forno i peperoni e pelarli. Imbiondire nell''olio aglio e cipolla col peperoncino; unire i peperoni tagliati a listarelle e poi unire i pelati frullati e salare. Far restringere per 20 minuti. Lessare i maccheroni, condirli con la salsa e col pecorino.',2387);
INSERT INTO "ricette" VALUES (14004,'Maccheroni Ai Quattro Formaggi','Primo','Mozzarella',4,' -','500 G Pasta Tipo Maccheroni Rigati,
100 G Mozzarella,
100 G Formaggio Olandese,
100 G Formaggio Groviera,
100 G Formaggio Parmigiano,
150 G Burro','Fondere il burro a bagnomaria, unirvi i primi 3 formaggi tagliati a dadini e il parmigiano grattugiato. Condire la pasta scolata con il composto di formaggi.',4116);
INSERT INTO "ricette" VALUES (14005,'Maccheroni Ai Tre Formaggi','Primo','Formaggio Scamorza',2,' -','Pasta Tipo Maccheroni,
Sale,
1 Bicchiere Latte,
50 G Formaggio Scamorza,
50 G Formaggio Emmenthal,
50 G Formaggio Parmigiano','Far bollire in una casseruola, per 2 minuti e a fiamma bassa, il latte e i tre formaggi triturati. Si deve ottenere una salsa omogenea da versare sui maccheroni cotti in acqua salata e appena scolati dalla pentola. Servire il piatto ben caldo.',1564);
INSERT INTO "ricette" VALUES (14006,'Maccheroni Al Forno','Primo','Pomodori',8,' -','600 G Pasta Tipo Rigatoni,
2000 G Pomodori,
200 G Concentrato Di Pomodoro,
300 G Mozzarella Fiordilatte,
200 G Carne Tritata,
300 G Ricotta,
1 Uovo,
1 Cipolla,
150 G Olio D''oliva (o Sugna),
1 Bicchiere Vino Rosso,
100 G Formaggio Parmigiano','Per questa preparazione sarebbe indicato il classico ragù napoletano, ma potrete farla ugualmente con un buon sugo di pomodoro piuttosto ristretto. Tagliate il fiordilatte a pezzetti e preparate le polpettine, che farete friggere in olio di semi o sugna. Stemperate la ricotta in una zuppiera con qualche cucchiaio di salsa e di acqua dei maccheroni. Scolate la pasta a mezza cottura e conditela con una parte del sugo e parmigiano. Prendete una teglia alta 5-6 cm, cospargetela di sugo, fate quindi un primo strato di maccheroni sul quale spargerete un po'' di ricotta, fiordilatte e polpettine, parmigiano e ancora sugo. Coprite con un secondo strato di maccheroni ed un secondo strato di ripieno. Sul terzo strato di pasta ponete soltanto qualche fettina di fiordilatte, sugo e formaggio grattugiato. Passate in un forno ben caldo per circa 20 minuti e quando comincerà a colorirsi spegnete e lasciate in forno per qualche minuto ancora.',5776);
INSERT INTO "ricette" VALUES (14007,'Maccheroni Al Forno (2)','Primo','Pomodori',4,'Luogo: Calabria.','400 G Pasta Tipo Maccheroni,
750 G Pomodori,
1 Cipolla,
1 Cucchiaio Prezzemolo Tritato,
125 G Prosciutto,
125 G Capocollo,
1 Spicchio Aglio,
1 Peperoncino Rosso,
50 G Sugna,
Sale,
100 G Formaggio Caciocavallo Vecchio Grattugiato','In un tegame di coccio con la sugna mettete a rosolare cipolla e prezzemolo tritati, prosciutto e capocollo ritagliati in dadini, uno spicchio d''aglio intero e il peperoncino rosso tagliuzzato. Aggiungete poi i pomodori pelati, privi dei semi e del liquido di vegetazione, salate e fate cuocere e restringere la salsa. Lessate i maccheroni in acqua leggermente salata, sgocciolateli quasi a metà cottura, ponetene uno strato in una teglia intinta di sugo, condite col caciocavallo grattugiato e con la salsa di pomodoro, fatene un secondo strato, condite ancora e così via, terminando con uno strato di salsa. Mettete in forno per 15-20 minuti.',3439);
INSERT INTO "ricette" VALUES (14008,'Maccheroni Al Forno (3)','Primo','Peperone Verde',2,' -','1 Tazza Pasta Tipo Maccheroni Crudi,
1 Peperone Verde Sminuzzato,
1 1/2 Tazza Formaggio Grana Grattugiato,
1/2 Tazza Latte,
1/4 Cucchiaino Sale,
Pepe','Cuocete i maccheroni in abbondante acqua salata e scolateli bene, metteteli in una terrina, aggiungete gli altri ingredienti e mescolate bene. Ora mettete il tutto in una pirofila leggermente imburrata, e distribuite uniformemente, cospargendo di grana a piacere. Cuocete in forno per 35-40 minuti a 170 gradi fino a fusione del formaggio. Servite caldo.',1132);
INSERT INTO "ricette" VALUES (14009,'Maccheroni Al Forno (4)','Primo','Latte',4,' -','320 G Pasta Tipo Maccheroncini,
1 Noce Burro,
100 G Latte,
80 G Formaggio Grana,
Sale','Far lessare la pasta in 1 pentola con abbondante acqua salata e scolarla molto al dente (poco più di metà cottura); imburrare 1 pirofila, farvi 1 strato di pasta, spargervi sopra delle lamelle di grana, poi ripetere l''operazione, facendone un secondo strato. Versare sul tutto il latte, distribuendolo bene e mettere in forno caldo a circa 180 gradi, per 20 minuti, finché tutto il liquido sarà stato assorbito.',1885);
INSERT INTO "ricette" VALUES (14010,'Maccheroni Al Gratin','Primo','Latte',4,' -','400 G Pasta Tipo Maccheroni,
80 G Burro,
40 G Farina,
40 G Formaggio Parmigiano Grattugiato,
100 Cl Latte,
Sale,
Burro','Lessare i maccheroni in 1/2 l di latte e 1/2 l di acqua salata e scolarli quando avranno assorbito quasi tutto il liquido. Condirli con 40 g di burro e parte del parmigiano e tenerli in caldo. Preparare una besciamella con 40 g di burro fuso, la farina, 1/2 l di latte caldo e mescolare per non formare grumi. Imburrare una pirofila, versarvi i maccheroni e la besciamella, cospargere con abbondante parmigiano grattugiato e infornare a 180 gradi per circa 30 minuti finché la superficie sarà ben dorata.',3467);
INSERT INTO "ricette" VALUES (14011,'Maccheroni Al Gratin (2)','Primo','Besciamella',6,' -','500 G Pasta Tipo Maccheroni Cotti Molto Al Dente,
50 Cl Besciamella,
150 G Formaggio Emmenthal Grattugiato,
100 G Formaggio Parmigiano,
Sale,
Pepe,
1 Grattatina Noce Moscata,
Pangrattato','Accendete il forno a 180 gradi. Cuocete i maccheroni molto al dente (se la confezione indica 14 minuti, voi calcolatene 12) e intanto preparate la besciamella aggiungendo però un bicchiere di latte per renderla più liquida. Scolate, rimetteteli nella pentola di cottura e conditeli bene con la besciamella e i formaggi. Aggiungete una grattatina di noce moscata e, se ce ne fosse bisogno, sale e pepe. Versateli in una pirofila, spolverizzateli con del pangrattato mettendo qua e là qualche fiocchetto di burro. Infornate per 15 minuti fino a quando si sarà formata una bella crostina dorata.',3624);
INSERT INTO "ricette" VALUES (14012,'Maccheroni Al Prosciutto','Primo','Prosciutto',4,' -','400 G Pasta Tipo Maccheroni,
150 G Prosciutto Crudo,
Rosmarino,
Salvia,
60 G Burro,
Formaggio Grana Grattugiato,
Sale,
1 Macinata Pepe','Mettere sul fuoco 60 g di burro con il rosmarino e la salvia legati insieme. Appena il condimento soffrigge aggiungere il prosciutto crudo tagliato a pezzetti molto piccoli e una macinata di pepe. Alzare la fiamma e, mescolando, far rosolare per 2''. Cuocere i maccheroni in abbondante acqua salata; scolarli al dente e condirli subito con il sugo, eliminando rosmarino e salvia, e con grana grattugiato.',2841);
INSERT INTO "ricette" VALUES (14013,'Maccheroni Al Ragù Di Pollo','Primo','Petto Di Pollo',4,' -','400 G Pasta Tipo Maccheroni,
300 G Petto Di Pollo,
400 G Polpa Di Pomodoro,
1 Cucchiaio Concentrato Di Pomodoro,
300 G Piselli,
2 Bustine Zafferano,
1 Cipolla,
Burro,
Sale,
Pepe','Private il petto di pollo dell''ossicino centrale e delle cartilagini, tagliarlo a dadini e farlo rosolare in 1 tegame con il burro e la cipolla tritata; unirvi i piselli, la polpa di pomodoro, il concentrato e bagnare con 1 mestolo di acqua calda mescolata allo zafferano. Salare, pepare e cuocere il sugo per 20 minuti. Lessare la pasta al dente e condirla con il ragù di pollo.',2786);
INSERT INTO "ricette" VALUES (14014,'Maccheroni Al Sugo Svelto','Primo','Pomodoro',4,' -','Pasta Tipo Maccheroni,
Aglio,
Pomodoro Fresco,
3 Filetti D''acciughe Dissalati,
Prezzemolo Tritato,
Olio D''oliva','Cuocere i maccheroni e aggiungere un sugo preparato con tre minuti di cottura di aglio, pomodoro fresco, acciughe, prezzemolo tritato. Completare con olio a crudo.',1798);
INSERT INTO "ricette" VALUES (14015,'Maccheroni Al Taleggio','Primo','Formaggio Taleggio',4,' -','300 G Pasta Tipo Maccheroni,
200 G Patate,
300 G Formaggio Taleggio,
100 G Burro,
250 G Lardo','Far lessare in acqua bollente salata la pasta e le patate, sbucciare le patate, tagliarle a dadi e metterle in una pirofila imburrata con i maccheroni. Unire il lardo fatto dorare nel burro, il taleggio tagliato a pezzetti e infornare fino a che il taleggio sarà sciolto. Servire ben caldo.',5085);
INSERT INTO "ricette" VALUES (14016,'Maccheroni Al Taleggio (2)','Primo','Formaggio Taleggio',4,' -','350 G Pasta Tipo Maccheroni,
150 G Formaggio Taleggio,
2 Patate,
2 Cipolle Rosse,
50 Cl Latte,
2 Foglie Insalata Lattuga,
Sale,
Pepe Nero','Sbucciare le patate e tagliarle a spicchi e le cipolle a pezzi, metterle in 1 casseruola, versarvi il latte, salare e far cuocere per circa 20 minuti a fiamma media. Intanto, cuocere i maccheroni al dente. Lavare e tagliare la lattuga a listarelle larghe 1/2 cm. Ridurre il formaggio a tocchetti e scolare la pasta: riunire entrambi in 1 terrina, aggiungere il sugo di patate e la lattuga. Mescolare bene, distribuire nei singoli piatti e cospargere di pepe.',2294);
INSERT INTO "ricette" VALUES (14017,'Maccheroni Al Telefono','Primo','Mozzarella',4,' -','400 G Pasta Tipo Maccheroni,
1 Mozzarella,
100 G Prosciutto Cotto Tagliato Spesso,
50 G Burro,
50 G Farina Bianca,
50 Cl Latte,
1 Pizzico Noce Moscata,
Sale','Sciogliere sul fuoco il burro, stemperarvi la farina e unire lentamente il latte bollente. Salare e bollire per 10 minuti Togliere dal fuoco e insaporire con noce moscata. Scolare la pasta e condire con la besciamella, la mozzarella a dadini e il prosciutto a listarelle. Servire subito.',2994);
INSERT INTO "ricette" VALUES (14018,'Maccheroni All''arancia','Primo','Arancia',4,' -','400 G Pasta Tipo Maccheroni,
1 Arancia,
200 G Mascarpone Freschissimo,
30 G Burro,
Abbondante Formaggio Parmigiano Grattugiato,
Sale','Mescolare il mascarpone con il burro molto morbido e la scorza grattugiata dell''arancia. Scolare i maccheroni al dente, condirli con il mascarpone e con il parmigiano, mescolare e servire.',2912);
INSERT INTO "ricette" VALUES (14019,'Maccheroni All''olio','Primo','Olio D''oliva',4,' -','6 Tazze Acqua,
1 Cucchiaio Olio D''oliva,
500 G Pasta Tipo Maccheroni,
1 Cucchiaino Sale','Mettete 6 tazze d''acqua nella pentola e portate a ebollizione su un fuoco medio. Quando l''acqua bolle, versatevi 1 cucchiaio d''olio, per non lasciare che la pasta s''incolli. Aggiungete 500 g di maccheroni e 1 cucchiaino di sale. Lasciate cuocere a fuoco lento, finché l''acqua sia assorbita completamente.',2042);
INSERT INTO "ricette" VALUES (14020,'Maccheroni Alla Cavalleggera','Primo','Tuorli D''uovo',4,'Luogo: Lazio.','400 G Pasta Tipo Maccheroni,
2 Tuorli D''uovo,
20 G Burro,
Formaggio Parmigiano,
Alcuni Gherigli Di Noci Tritati Fini','Scolate i maccheroni in una zuppiera dove avete lavorato i tuorli con il burro, il parmigiano e il trito abbondante di gherigli di noci. Servire ben caldi.',2340);
INSERT INTO "ricette" VALUES (14021,'Maccheroni Alla Chitarra','Primo','Cipolla',4,' -','500 G Pasta Tipo Maccheroni,
Salsa Di Pomodoro,
1 Cipolla,
2 Spicchi Aglio,
1 Peperoncino,
Prezzemolo,
Formaggio Pecorino Grattugiato,
Olio D''oliva,
Sale,
Pepe','Rosolare nell''olio la cipolla e l''aglio tritati, unire la salsa di pomodoro, il peperoncino, il prezzemolo tritato, il sale e il pepe e far addensare. Cuocere la pasta al dente in abbondante acqua salata, condirla con la salsa preparata e il pecorino e servire.',2889);
INSERT INTO "ricette" VALUES (14022,'Maccheroni Alla Chitarra (2)','Primo','Uova',6,' -','400 G Farina,
4 Uova,
500 G Pomodori Perini,
6 Cucchiai Olio D''oliva,
Sale,
1 Pizzico Peperoncino','Disponete la farina a fontana, sgusciatevi le uova, insaporite con un pizzico di sale e impastate fino a ottenere un composto sodo ed elastico. Lasciate riposare la pasta un quarto d''ora, poi tiratela a sfoglia (lo spessore deve essere di alcuni millimetri), appoggiatela sui fili di acciaio della chitarra e passatevi sopra il matterello esercitando una certa pressione in modo che i fili taglino la pasta in lunghi spaghetti a sezione quadrata. Tagliate a dadini i pomodori, fateli saltare 10 minuti in padella con sei cucchiai d''olio, salate appena, insaporite con un pizzico di peperoncino. Lessate la pasta, conditela con la salsa, mescolatela e servitela subito ben calda. Vini di accompagnamento: Collio Bianco DOC, Trebbiano D''Abruzzo DOC, Cirò Bianco DOC.',3894);
INSERT INTO "ricette" VALUES (14023,'Maccheroni Alla Chitarra Al Sugo','Primo','Vitellone',4,' -','320 G Pasta Tipo Maccheroni Alla Chitarra,
Formaggio Grattugiato,
800 G Vitellone,
70 G Burro,
1 Bicchiere Vino Bianco,
Rosmarino,
Olio D''oliva,
Sale','Insaporite il pezzo di carne nel burro, sale, rosmarino, girandolo di continuo per dieci minuti. Versate un bicchiere di vino bianco secco e fate evaporare. Terminate la cottura della carne in forno per un''ora abbondante. Togliete la carne e con il suo sugo condite i maccheroni appena scolati; completate con il formaggio grattugiato.',4078);
INSERT INTO "ricette" VALUES (14024,'Maccheroni Alla Chitarra Con Fegatini','Primo','Fegatini',6,' -','Pasta Tipo Maccheroni Alla Chitarra,
350 G Fegatini,
40 G Burro,
1 Cipolla,
Brodo,
Formaggio Grattugiato,
3 Cucchiai Olio D''oliva,
Sale','Fate la pasta secondo la ricetta precedente. In una padella scaldate il burro con tre cucchiai d''olio e insaporitevi la cipolla tritata. Aggiungete i fegatini tritati e fate colorire. Spruzzate con il brodo, fate evaporare. Salate. Lessate i maccheroni, conditeli con la salsa calda. Spolverizzate con formaggio. Vini di accompagnamento: Soave superiore DOC, Vernaccia Di San Gimignano DOCG, Castel Del Monte Chardonnay DOC.',3249);
INSERT INTO "ricette" VALUES (14025,'Maccheroni Alla Chitarra Con Tartufo E Zafferano','Primo','Tartufo',6,'Luogo: Abruzzo. Luogo: Molise.','700 G Farina Di Grano Duro,
6 Uova,
2 Bustine Zafferano,
100 G Tartufo,
Formaggio Parmigiano Grattugiato,
Sale,
Olio D''oliva','Preparate la sfoglia mettendo la farina a fontana e le uova miscelate alle bustine di zafferano. Preparate quindi i maccheroni servendovi dell''apposito attrezzo. Mentre cuocete la pasta in acqua bollente e salata, a parte fate scaldare metà del tartufo grattugiato in un po'' di olio e acqua di cottura della pasta. Quando la pasta sarà giunta a cottura scolatela e saltatela nella padella in cui avete preparato il tartufo scaldato. Dopo aver mescolato velocemente dividete la pasta nei piatti da portata e completate con parmigiano grattugiato e scagliette di tartufo. Servire subito.',4110);
INSERT INTO "ricette" VALUES (14026,'Maccheroni Alla Lattuga','Primo','Insalata Lattuga',4,' -','350 G Pasta Tipo Maccheroni,
1 Insalata Lattuga Grande,
1 Scalogno Tritato,
80 G Midollo Di Bue,
50 Cl Brodo Di Carne Ristretto,
1 Noce Burro,
Olio D''oliva,
Sale,
Pepe','Lessare nel brodo il midollo, scolarlo, asciugarlo e dividerlo in sottili fettine. Insaporire lo scalogno in 4 cucchiai di olio e farvi brasare la lattuga a striscioline. Unire un po'' di brodo pepare e far restringere. Legare con una noce di burro l''intingolo di lattuga e versarlo sulla pasta lessata. Mescolare e rifinire il piatto con il midollo.',3261);
INSERT INTO "ricette" VALUES (14027,'Maccheroni Alla Pastora','Primo','Ricotta',4,'Luogo: Calabria.','400 G Pasta Tipo Maccheroni,
400 G Ricotta Di Pecora Fresca,
Sale,
Pepe','Mettete a cuocere i maccheroni in abbondante acqua salata. Teneteli al dente e versateli senza sgocciolarli del tutto. Avrete intanto diviso la ricotta in pezzetti, schiacciateli con il mestolo di legno e stemperateli con un po'' dell''acqua di cottura dei maccheroni. Condite i maccheroni con questa specie di crema e con pepe macinato grosso.',2430);
INSERT INTO "ricette" VALUES (14028,'Maccheroni Alla Pastora (2)','Primo','Ricotta',4,'Luogo: Calabria.','350 G Pasta Tipo Maccheroni Rigati,
400 G Ricotta Freschissima,
150 G Salsiccia,
Formaggio Pecorino Grattugiato,
Sale,
Pepe','Spellate la salsiccia, sbriciolatela e mettetela in un tegame con un po'' d''acqua in modo che perda tutto il suo grasso senza rosolare; cuocetela a fuoco bassissimo. Nel frattempo lessate i maccheroni in abbondante acqua bollente salata e passate al setaccio la ricotta, facendola cadere nella zuppiera, aggiungete solo il sugo della salsiccia, pepate in abbondanza e amalgamate con un cucchiaio di legno, fino a ottenere una crema. Scolate i maccheroni al dente, lasciando loro aderente un pochino d''acqua di cottura, versateli nella zuppiera, aggiungete il pecorino, rimescolate con cura e servite in piatti caldi.',2641);
INSERT INTO "ricette" VALUES (14029,'Maccheroni Alla Ricotta','Primo','Ricotta',4,' -','350 G Pasta Tipo Maccheroni,
150 G Ricotta,
Formaggio Parmigiano Grattugiato,
Noce Moscata,
Sale,
Pepe','In una terrina mettere la ricotta, il sale, un pizzico di noce moscata e stemperare tutto con qualche cucchiaiata di acqua calda. Cuocere i maccheroni in abbondante acqua salata, scolarli al dente e condirli con il composto preparato. Cospargere con abbondante parmigiano e servire ben caldi.',1786);
INSERT INTO "ricette" VALUES (14030,'Maccheroni Alla Toranese','Primo','Pancetta Magra',4,'Luogo: Calabria.','400 G Pasta Tipo Mezzani (o Maltagliati),
100 G Pancetta Magra,
10 Cl Olio D''oliva Extra-vergine,
2 Cipolle Grandi,
Sale,
Peperoncino Rosso In Polvere,
Formaggio Pecorino Grattugiato','Tagliate a dadini la pancetta, fatela rosolare con l''olio in un tegame, poi toglietela e mettetela da parte. Nel tegame mettete la cipolla tritata finemente, salatela e fatela cuocere fin quando diventa sfatta. A questo punto unite la pancetta abbrustolita. Lessate i maccheroni in acqua leggermente salata, sgocciolateli al dente e conditeli con il pecorino grattugiato e con il soffritto di pancetta e cipolla. Servite a parte il peperoncino.',3108);
INSERT INTO "ricette" VALUES (14031,'Maccheroni Alla Vodka','Primo','Vodka',4,'Preparazione: 20 minuti.','400 G Pasta Tipo Maccheroni,
20 G Salsiccia,
1 Cipolla Grande,
Burro,
50 Cl Panna Per Cucinare,
4 Bicchierini Vodka,
Pepe,
Sale','Fate soffriggere una cipolla con burro, pepe, sale e pezzettini di salsiccia (senza buccia); versatevi un bicchierino di vodka e lasciatelo evaporare, poi versatene un altro e un altro ancora. Infine aggiungete la panna e lasciatela cuocere per circa cinque minuti. Quindi fate bollire i maccheroni in acqua salata, scolateli, versateli nel sugo precedentemente preparato e, al momento di servire, versatevi sopra un altro po'' di panna e vodka.',3706);
INSERT INTO "ricette" VALUES (14032,'Maccheroni Alla Zucca','Primo','Zucca',4,' -','400 G Pasta Tipo Maccheroni,
150 G Zucca,
2 Zucchine,
20 G Farina,
40 G Formaggio Grana,
50 G Formaggio Groviera,
Prezzemolo,
Aglio,
Olio D''oliva,
Burro,
Latte,
Sale','Lessare la zucca e passarla al passaverdure. Preparare una besciamella con 20 g di burro 25 cl di latte e la farina, incorporarvi la zucca e il grana. Saltare in padella, con 2 cucchiai di olio d''oliva, una noce di burro, il prezzemolo e l''aglio, le zucchine tagliate a dadini. Cuocere la pasta e condirla con la salsa, le zucchine e la groviera. Gratinare in forno a 220 gradi per 10 minuti.',3382);
INSERT INTO "ricette" VALUES (14033,'Maccheroni Alle Cipolle','Primo','Cipolle',4,' -','350 G Pasta Tipo Maccheroni,
200 G Cipolle Bianche,
100 G Pancetta (fette Da 100 G),
Formaggio Pecorino Grattugiato,
Olio D''oliva,
Sale','Tagliare la pancetta a dadini e rosolarla in padella con 2 cucchiai d''olio. Quando sarà dorata e croccante levarla dalla padella e tenerla in caldo. Affettare finemente le cipolle e farle sudare nello stesso olio della pancetta. Aggiungere una presa di peperoncino in polvere. Lessare i maccheroni in abbondante acqua salata, scolarli e versarli nella padella con le cipolle, unire la pancetta e far insaporire qualche minuto. Condire con pecorino grattugiato.',2728);
INSERT INTO "ricette" VALUES (14034,'Maccheroni Alle Olive','Primo','Olive Verdi',4,' -','400 G Pasta Tipo Maccheroni,
400 G Pomodori Da Sugo,
2 Cucchiai Pasta Di Olive Verdi,
Olio D''oliva,
Aglio,
Prezzemolo,
Basilico,
Formaggio Grana,
Sale,
Pepe','Lavare i pomodori, spellarli e frullarli con olio, aglio, prezzemolo e basilico. Salare, pepare, far cuocere per circa 20 minuti e unire la pasta di olive. Cuocere i maccheroni al dente in abbondante acqua salata, padellarli con il sugo preparato, cospargere di grana grattugiato e servire.',2570);
INSERT INTO "ricette" VALUES (14035,'Maccheroni Allo Yogurth','Primo','Yogurth Bianco',4,' -','400 G Pasta Tipo Maccheroni,
125 G Yogurth Bianco,
40 G Erbe Aromatiche (basilico, Prezzemolo, Rosmarino),
1 Spicchio Aglio,
2 Cucchiai Brandy,
1 Cucchiaio Formaggio Grana Grattugiato,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Tritare finemente l''aglio e le erbe e metterli in una ciotola. Unire 2 cucchiai di brandy, lo yogurth, 1 cucchiaio di grana e 4 di olio, sale e pepe, mescolare molto bene. Lessare i maccheroni in abbondante acqua salata, scolarli e condirli con la salsa allo yogurth.',3130);
INSERT INTO "ricette" VALUES (14036,'Maccheroni Aromatici','Primo','Polpa Di Pomodoro',4,' -','400 G Pasta Tipo Maccheroni Rigati,
400 G Polpa Di Pomodoro,
4 Cucchiai Olio D''oliva,
Insalata Rucola,
Basilico,
Salvia,
Rosmarino,
Maggiorana,
Timo,
Origano,
1/2 Cucchiaino Zucchero,
1 Presa Sale','Far scaldare l''olio in 1 casseruola; aggiungere la polpa di pomodoro, lo zucchero e 1 presa di sale. Far addensare il sugo a fuoco vivo per 6 minuti. Unire quindi le erbe aromatiche e la rucola mondate, lavate e tritate e proseguire la cottura, a fiamma bassa, fino a quando la salsa si sarà ristretta. Lessare la pasta al dente e condirla con il sugo alle erbe.',2965);
INSERT INTO "ricette" VALUES (14037,'Maccheroni Col Ferretto','Primo','Uova',4,'Luogo: Calabria.','500 G Farina,
5 Uova,
1 Cucchiaio Olio D''oliva,
Sale,
100 G Formaggio Pecorino Grattugiato,
Ragù D''agnello (o Ragù Di Maiale)','Preparate la pasta mettendo a fontana sulla spianatoia la farina setacciata. In una terrina rompete le uova, unite l''olio e un pizzico di sale, sbattetele e versatele nel mezzo della fontana. Lavorando con le dita, portate, poco alla volta, la farina nel centro, poi, con ambedue le mani, lavorate bene la pasta fino a renderla ben sostenuta. Con il matterello tirate delle sfoglie, tagliatele in piccoli quadrati, avvolgeteli all''apposito ferro sottile, sfilatene i cilindretti di pasta ricavati e allineateli via via su un canovaccio cosparso di farina per farli seccare leggermente. Calate la pasta in abbondante acqua leggermente salata, sgocciolatela al dente, ricopritela di formaggio grattugiato e di un ragù d''agnello o di maiale.',2942);
INSERT INTO "ricette" VALUES (14038,'Maccheroni Col Ferro','Primo','Uova',4,'Luogo: Calabria.','500 G Farina,
5 Uova,
1 Cucchiaio Olio D''oliva,
Sale,
100 G Formaggio Pecorino Grattugiato,
Ragù D''agnello (o Ragù Di Maiale)','Preparate la pasta mettendo a fontana sulla spianatoia la farina setacciata. In una terrina rompete le uova, unite l''olio e un pizzico di sale, sbattetele e versatele nel mezzo della fontana. Lavorando con le dita, portate, poco alla volta, la farina nel centro, poi, con ambedue le mani, lavorate bene la pasta fino a renderla ben sostenuta. Con il matterello tirate delle sfoglie, tagliatele in piccoli quadrati, avvolgeteli all''apposito ferro sottile, sfilatene i cilindretti di pasta ricavati e allineateli via via su un canovaccio cosparso di farina per farli seccare leggermente. Calate la pasta in abbondante acqua leggermente salata, sgocciolatela al dente, ricopritela di formaggio grattugiato e di un ragù d''agnello o di maiale.',2942);
INSERT INTO "ricette" VALUES (14039,'Maccheroni Col Ferro (2)','Primo','Uovo',4,' -','350 G Farina,
1 Uovo','Disporre la farina a fontanella sulla spianatoia e nel mezzo le uova. Impastare unendo acqua tiepida nella misura che l''impasto richiede. Lavorare l''impasto finché sia levigato e consistente. Stendere una o più sfoglie e tagliarla a quadratini minuti (1 cm). Allineare un certo numero di questi quadratini sulla spianatoia e premervi rotolandolo sopra un ferro da calza. Si ottengono così dei maccheroncini.',1213);
INSERT INTO "ricette" VALUES (14040,'Maccheroni Col Ferro Al Ragù','Primo','Pomodori',4,' -','500 G Pasta Tipo Maccheroni Col Ferro Freschi,
200 G Polpa Di Maiale Macinata,
70 G Formaggio Pecorino Maiorchino Grattugiato,
30 G Strutto,
6 Pomodori Maturi,
Basilico Fresco A Foglia Riccia,
Sale,
Pepe','Rosolare dolcemente la carne nello strutto. Lavare, spellare e privare dei semi i pomodori, quindi tagliarli a dadini e aggiungerli alla carne, unire il basilico e aggiustare di sale e pepe. Mettere il coperchio e cuocere a fuoco lento per 30 minuti. Condirvi la pasta unendo il pecorino.',2869);
INSERT INTO "ricette" VALUES (14041,'Maccheroni Con Alici','Primo','Acciughe Fresche',4,' -','400 G Acciughe Fresche,
300 G Pasta Tipo Maccheroni,
1/2 Cipolla,
50 G Tonno Sott''olio,
200 G Pomodori Pelati,
1 Cucchiaio Salsa Di Pomodoro,
1/2 Bicchiere Olio D''oliva,
2 Cucchiai Prezzemolo Tritato,
1 Cucchiaio Basilico Tritato,
Sale,
Pepe','Pulite e lavate le acciughe, quindi apritele in due e fatele rosolare in padella con poco olio, per 10 minuti. Dopo aver posto le acciughe su un piatto, versate nello stesso recipiente ancora un po'' d''olio, unite la cipolla tagliata finemente e lasciatela rosolare dolcemente. Quando si sarà imbiondita, aggiungete un cucchiaio di salsa di pomodoro, un po'' d''acqua, il sale necessario e una macinata di pepe; quindi lasciate cuocere a fuoco basso per 15 minuti. Dopodichè unite una cucchiaiata di basilico tritato, due di prezzemolo e il tonno sott''olio sminuzzato, facendo insaporire il tutto per alcuni minuti. In una padella a parte, fate insaporire per 10 minuti a calore moderato i Pomodori pelati, avendo cura di sminuzzarli durante la cottura con una forchetta. Dopo aver lessato i maccheroni scolateli al dente e conditeli con circa 2/3 della salsa a base di tonno. Disponete in una pirofila metà della quantità di pasta e distribuite su questa le acciughe e i filetti di pomodoro. Ricoprite con la pasta rimanente e il resto del sugo, quindi ponete in forno caldo (200 gradi) per circa 5 minuti. Servite il tutto appena tolto dal forno.',2271);
INSERT INTO "ricette" VALUES (14042,'Maccheroni Con Asparagi','Primo','Asparagi',4,' -','350 G Pasta Tipo Maccheroni,
600 G Asparagi,
30 G Burro,
10 Cl Panna,
Sale,
1 Cucchiaio Pepe Verde','Tagliare a tocchetti gli asparagi, eliminando la parte dura del gambo, poi lessarli per 5 minuti. Tenerne da parte la metà e rosolare quelli rimasti con il burro; bagnare con la panna, salare, aggiungere il pepe verde e cuocere per 10 minuti. Frullare il tutto, rimettere sul fuoco e unire i tocchetti di asparagi tenuti da parte. Con questo sugo, condire la pasta cotta al dente.',1914);
INSERT INTO "ricette" VALUES (14043,'Maccheroni Con Funghi E Salsiccia','Primo','Funghi Porcini Secchi',4,' -','350 G Pasta Tipo Maccheroni,
350 G Salsiccia,
1 Cipolla,
20 G Funghi Porcini Secchi,
Santoreggia,
Formaggio Parmigiano Grattugiato,
Olio D''oliva,
Pepe,
Sale','Ammorbidire i funghi in acqua calda, strizzarli, tritarli e conservare l''acqua. Far appassire la cipolla affettata in olio per 10 minuti, poi unire la salsiccia spellata e farla rosolare. Aggiungere i funghi, bagnare con la loro acqua, salare e pepare. Far addensare il sugo. Lessare i maccheroni in abbondante acqua salata, scolarli e condirli con il sugo e il parmigiano.',3564);
INSERT INTO "ricette" VALUES (14044,'Maccheroni Con I Carciofi','Primo','Carciofi',4,' -','400 G Pasta Tipo Maccheroni,
6 Carciofi,
4 Uova,
80 G Formaggio Pecorino Grattugiato,
15 Cl Olio D''oliva Extra-vergine,
Sale,
Pepe Nero','Pulite i carciofi lasciando le foglie tenere e il cuore, tagliateli in spicchi assai sottili e fateli cuocere in abbondante olio. Salateli, pepateli, incorporatevi le uova che avrete sbattuto unitamente al pecorino grattugiato e fate completare la cottura. Sgocciolate bene al dente i maccheroni che avrete lessato in acqua leggermente salata e conditeli con la salsa ben calda.',3472);
INSERT INTO "ricette" VALUES (14045,'Maccheroni Con I Peperoni','Primo','Peperoni',6,' -','600 G Pasta Tipo Vermicelli,
1000 G Peperoni Rossi E Gialli,
200 G Olio D''oliva,
4 Spicchi Aglio,
Prezzemolo,
Pepe,
Sale','In una padella da frittura si fa soffriggere l''aglio nell''olio ed appena sarà biondo si verseranno i peperoni che saranno stati tagliati a filetti dopo essere stati ben lavati e mondati dal torsolo ed ai semi. Coprite la padella e lasciate andare i peperoni a fuoco medio per una decina di minuti rigirandoli di tanto in tanto. Quando vedrete che si saranno ''ammosciati'', ovvero cominceranno ad ammorbidirsi, scopriteli ed aumentate un pò la fiamma sorvegliandoli perché non brucino; prima di spegnere, salate. Cuocete la pasta come al solito, scolatela col il forchettone e conditela con i peperoni, pepe e prezzemolo, se piace.',4083);
INSERT INTO "ricette" VALUES (14046,'Maccheroni Con La Mollica','Primo','Mollica Di Pane Raffermo',4,'Luogo: Basilicata.','500 G Pasta Tipo Maccheroni Fatti In Casa,
Mollica Di Pane Raffermo,
Olio D''oliva,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
Sale','Sbriciolate il pane e lasciatelo dorare, rimestando spesso, in un pentolino con olio dove avrete in precedenza fatto soffriggere 1 spicchio di aglio. Lessate la pasta in abbondante acqua salata, scolatela e conditela con la mollica, aggiungendo in ultimo il prezzemolo tritato.',2546);
INSERT INTO "ricette" VALUES (14047,'Maccheroni Con La Ricotta','Primo','Pomodori Freschi',4,' -','400 G Pasta Tipo Maccheroni,
1000 G Pomodori Freschi,
1/2 Cipolla,
200 G Ricotta,
Olio D''oliva,
Sale,
Basilico,
Formaggio Parmigiano Grattugiato','Far imbiondire la cipolla affettata in 1 tegame con l''olio, quindi versare i pomodori pelati e senza semi, salare e far cuocere per circa 1 ora a fuoco lento. Poco prima di spegnere aggiungere il basilico. Intanto cuocere la pasta al dente e, a parte, in 1 zuppiera, stemperare la ricotta con 1 mestolo di acqua di cottura della pasta. Aggiungere alla ricotta 1 mestolo di salsa e spolverare di parmigiano. Versare la pasta, mescolare, condire con il resto del sugo.',2873);
INSERT INTO "ricette" VALUES (14048,'Maccheroni Con La Ricotta (2)','Primo','Ricotta',4,'Luogo: Lazio.','400 G Pasta Tipo Maccheroni,
1/2 Bicchiere Latte,
200 G Ricotta Freschissima,
1 Cucchiaio Zucchero,
1 Punta Cannella In Polvere,
Sale,
Pepe','Stemperare la ricotta con una punta di cannella, il latte tiepido e lo zucchero. Cuocere la pasta al dente in acqua bollente salata, versarla in una terrina e condirla con la ricotta. Mescolare e mantecare velocemente, poi servire subito.',1723);
INSERT INTO "ricette" VALUES (14049,'Maccheroni Con La Ricotta Alla Romana','Primo','Ricotta Romana',4,'Luogo: Lazio. Luogo: Roma.','400 G Pasta Tipo Maccheroni Spezzati,
250 G Ricotta Romana,
1 Pizzico Zucchero A Velo,
15 G Cannella,
Sale','Cuocere i maccheroni in abbondante acqua salata. Frattanto versare la ricotta con lo zucchero e la cannella in una terrina già calda, aggiustarle di sale e unirvi qualche cucchiaiata di acqua di cottura della pasta. Scolarla bene al dente, condirla con la ricotta e servire.',1727);
INSERT INTO "ricette" VALUES (14050,'Maccheroni Con La Verdura','Primo','Pomodori',4,' -','1 Peperone,
1 Carota,
2 Coste Sedano,
2 Cucchiaini Capperi,
10 Olive Nere,
4 Acciughe,
3 Pomodori,
1 Bicchiere Birra,
400 G Pasta Tipo Maccheroni,
30 G Burro,
Sale,
Formaggio Parmigiano Grattugiato','Arrostire il peperone, privandolo della pelle e dei semi. Pulire la carota e tritarla con sedano, peperone, capperi, olive, acciughe e pomodori. Lasciar soffriggere il trito nel burro, salare e pepare. Poi aggiungere la birra e lasciar cuocere per 30 minuti a fuoco medio. Cuocere la pasta al dente, condirla con il sugo e poi metterla in una pirofila imburrata, cospargere di parmigiano e infornare a 180 gradi per 12 minuti.',2377);
INSERT INTO "ricette" VALUES (14051,'Maccheroni Con Le Alici','Primo','Acciughe Fresche',4,' -','400 G Pasta Tipo Maccheroni,
400 G Acciughe Fresche,
50 G Tonno Sott''olio,
200 G Pomodori Pelati,
1/2 Cipolla,
1/2 Bicchiere Olio D''oliva,
Prezzemolo,
Basilico,
Sale,
Pepe','Togliete la testa alle acciughe, pulitele, apritele in due togliendo la lisca centrale, quindi sciacquatele in acqua corrente e doratele in poco olio per 10 minuti. Scolatele dal liquido di cottura e nello stesso tegame versate ancora un po'' d''olio e lasciate imbiondire la cipolla affettata sottilmente. Aggiungete i pomodori, sale e pepe. Lasciar cuocere per circa 15 minuti quindi unite il prezzemolo e il basilico tritati, il tonno sminuzzato e proseguite la cottura per altri 10 minuti. Lessate i maccheroni in acqua salata, scolateli al dente e conditeli con il sugo al tonno. In una pirofila mettete metà della pasta condita, distribuitevi sopra le acciughe, ricoprite con la pasta rimasta ed infornate a 200 gradi per 5 minuti.',2616);
INSERT INTO "ricette" VALUES (14052,'Maccheroni Con Le Seppie','Primo','Seppie',4,' -','400 G Pasta Tipo Maccheroncelli,
500 G Seppie,
400 G Passata Di Pomodoro,
2 Spicchi Aglio,
1/2 Bicchiere Vino Bianco Secco,
Olio D''oliva,
Sale,
Pepe,
1 Manciata Prezzemolo','Far imbiondire l''aglio schiacciato con l''olio, eliminarlo e versare nella padella le seppie pulite e tagliate a striscioline. Dopo qualche minuto, versare il vino e far evaporare a fuoco vivo, quindi aggiungere la salsa, salare, pepare, coprire e far cuocere per 20 minuti. Lessare la pasta e condirla con la salsa ed una manciata di prezzemolo.',2497);
INSERT INTO "ricette" VALUES (14053,'Maccheroni Con Le Seppioline','Primo','Seppioline',4,' -','350 G Pasta Tipo Maccheroni,
600 G Seppioline Pulite,
1 Patata Grande,
200 G Pisellini Sgranati,
250 G Pomodori Pelati,
1 Cipolla,
2 Spicchi Aglio,
Prezzemolo,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','In una capace casseruola mettete le seppioline lavate e pulite, i pelati spezzettati, la cipolla tritata finemente, due spicchi d''aglio interi, la patata sbucciata e tagliata a fettine, i pisellini, il prezzemolo tritato e quattro cucchiai d''olio. Iniziate la cottura a fiamma media, mescolate spesso. Coprite e cuocete per circa 40 minuti, soltanto alla fine regolate sale e pepe. Lessate i maccheroni in abbondante acqua salata, scolateli al dente, passateli nella pentola delle seppioline, mescolate perché insaporiscano bene. Versate nel piatto da portata. Servite. Vini di accompagnamento: Soave Classico DOC, Vernaccia Di San Gimignano DOCG, Greco Di Tufo DOC.',3394);
INSERT INTO "ricette" VALUES (14054,'Maccheroni Con Patate E Tonno','Primo','Patate A Pasta Gialla',4,' -','400 G Pasta Tipo Maccheroni Rigati,
4 Patate A Pasta Gialla,
240 G Tonno Fresco (o Tonno In Scatola),
1 Cipolla Rossa,
Prezzemolo,
Olio D''oliva,
Sale,
1 Macinata Pepe','Lessate le patate, sbucciatele e tagliatele a tocchetti, fate dorare la cipolla nell''olio, aggiungete le patate e il tonno, aggiungete un po'' dell''acqua salata che state usando per cuocere la pasta, lasciate cuocere per 5-10 minuti. Cuocete la pasta e saltatela con il condimento aggiungendo una macinata di pepe e un po'' di prezzemolo.',3429);
INSERT INTO "ricette" VALUES (14055,'Maccheroni Con Porri E Pancetta','Primo','Porri',4,' -','350 G Pasta Tipo Maccheroni,
4 Porri,
100 G Pancetta Affumicata Affettata,
3 Cucchiai Olio D''oliva Extra-vergine,
2 Rametti Rosmarino,
Sale,
Pepe','Mettete sul fuoco una capace pentola con abbondante acqua salata. Pulite i porri privandoli della parte verde e dei primi 2 strati esterni, poi affettateli sottili. Tritate gli aghi di rosmarino, sminuzzate la pancetta e rosolate i 2 ingredienti in una casseruola con l''olio. Unite i porri, regolate di sale e cuocete sul fuoco basso e con il coperchio per 15 minuti circa aggiungendo, durante la cottura un po'' di acqua. Mentre il sugo cuoce, lessate i maccheroni. Scolate la pasta, conditela con il sugo preparato, mescolate, insaporite con una macinata di pepe e servite.',2330);
INSERT INTO "ricette" VALUES (14056,'Maccheroni Con Ricotta','Primo','Ricotta',4,' -','350 G Pasta Tipo Maccheroni,
300 G Ricotta Freschissima,
1 Pizzico Zucchero,
Sale,
1 Cucchiaino Cannella In Polvere','Mettere la ricotta in una terrina e aggiungervi lo zucchero e la cannella. Cuocere i maccheroni in acqua poco salata, diluire la ricotta con qualche cucchiaio dell''acqua di cottura della pasta, scolare i maccheroni, versarli nella terrina e mescolare bene.',1627);
INSERT INTO "ricette" VALUES (14057,'Maccheroni Con Ricotta (2)','Primo','Ricotta',4,' -','320 G Pasta Tipo Maccheroni,
1/2 Bicchiere Latte,
200 G Ricotta Fresca,
1 Cucchiaio Zucchero,
1 Pizzico Cannella In Polvere,
1 Pizzico Sale,
1 Pizzico Pepe','Lavorate la ricotta con un pizzico di cannella, il latte tiepido e lo zucchero. Fate cuocere la pasta al dente in abbondante acqua salata. Versatela poi in una terrina e conditela con la ricotta, un pizzico di pepe e sale. Mescolate e aggiungete un po'' di burro, poi servire subito. Per non servire la pasta fredda, potete riscaldare i piatti prima di servirla.',1452);
INSERT INTO "ricette" VALUES (14058,'Maccheroni Con Ricotta E Salsiccia','Primo','Ricotta',4,' -','400 G Pasta Tipo Maccheroni,
400 G Ricotta Fresca,
200 G Salsiccia,
Abbondante Formaggio Pecorino Grattugiato,
Sale,
Pepe In Grani','Spellate la salsiccia, sgranatela bene e fatela cuocere su fiamma bassa in un tegame poca acqua in modo che non rosoli. In una zuppiera lavorate con cura la ricotta con una forchetta di legno, quindi unite la salsiccia, sale e abbondante pepe macinato fresco. Lessate la pasta scolatela al dente lasciandole un po'' dell''acqua di cottura, quindi amalgamatela alla ricotta e completate con abbondante pecorino.',2982);
INSERT INTO "ricette" VALUES (14059,'Maccheroni Con Ricotta E Salsiccia (2)','Primo','Ricotta',4,' -','400 G Pasta Tipo Maccheroni,
400 G Ricotta,
150 G Salciccia,
Olio D''oliva Extra-vergine,
Formaggio Pecorino Grattugiato,
Sale,
1 Macinata Pepe','Lavorate a lungo la ricotta in una zuppiera condendola con sale, un''abbondante macinata di pepe e la salciccia che avrete prima privato del budello e fatto rosolare su fiamma bassissima senza altro condimento che quello da lei emesso. Mescolate con cura allungando con un paio di cucchiai dell''acqua della pasta che nel frattempo avrete messo a cottura. Scolate i maccheroni e passateli nella zuppiera con la ricotta, mescolateli con cura condendo con pecorino grattugiato e un giro di olio crudo.',3307);
INSERT INTO "ricette" VALUES (14060,'Maccheroni Con Tonno E Piselli','Primo','Tonno',4,' -','400 G Pasta Tipo Maccheroni,
200 G Tonno Sott''olio,
300 G Pisellini,
1 Cipolla,
Olio D''oliva,
Sale','Tagliare a rondelle la cipolla e farla appassire nell''olio, unire i pisellini e un po'' di sale. Lasciare insaporire e aggiungere il tonno sbriciolato. Cuocere i maccheroni, scolarli al dente e condirli con il sugo di piselli e tonno.',2795);
INSERT INTO "ricette" VALUES (14061,'Maccheroni Con Zucchine','Primo','Zucchine',4,' -','350 G Pasta Tipo Maccheroni,
400 G Zucchine,
5 Cucchiai Latte,
1 Scalogno,
150 G Ricotta,
1 Cucchiaino Maggiorana Tritata,
Sale,
Pepe,
Olio D''oliva,
1 Manciata Prezzemolo Tritato','Rosolare lo scalogno tritato in 4 cucchiai di olio, unire le zucchine affettate, una manciata di prezzemolo tritato, sale, pepe e cuocere per 15 minuti. In un tegame scaldare il latte con la ricotta poi unirli alle zucchine e mescolare. Lessare i maccheroni in acqua salata, scolarli e condirli con la salsa di ricotta e zucchine, un cucchiaino di maggiorana e pepe.',2539);
INSERT INTO "ricette" VALUES (14062,'Maccheroni Con Zucchine (2)','Primo','Zucchine',4,' -','400 G Zucchine,
Olio D''oliva,
1 Scalogno,
100 G Borraggine Tritata,
Sale,
Pepe,
150 G Ricotta,
4 Cucchiai Latte,
350 G Pasta Tipo Maccheroni,
Maggiorana Tritata,
Pepe','Mondare, lavare e affettare le zucchine, farle rosolare con l''olio e lo scalogno mondato e tritato, unirvi la borraggine, salare, pepare e cuocere per 15 minuti. In una casseruola far scaldare la ricotta diluita con il latte. Cuocere i maccheroni al dente, condirli con la crema di ricotta, le zucchine, la maggiorana e abbondante pepe.',2222);
INSERT INTO "ricette" VALUES (14063,'Maccheroni Con Zucchine Fritte','Primo','Zucchine',4,' -','350 G Pasta Tipo Maccheroni,
4 Zucchine,
150 G Fiocchi Di Latte,
3 Cucchiai Latte,
4 Cucchiai Farina,
Basilico,
Olio D''oliva,
Sale,
Abbondante Pepe','Mondare, lavare e affettare le zucchine, passarle nella farina, scuoterle in 1 setaccio per eliminare quella in eccesso e friggerle in olio bollente. Scolarle su carta assorbente da cucina e tenerle in caldo. Mescolare in 1 grossa ciotola i fiocchi di latte con il latte e spolverizzare con abbondante pepe. Intanto, cuocere la pasta al dente, scolarla e aggiungerla ai fiocchi di latte; mescolare, unire le zucchine, il basilico sminuzzato e servire subito.',2391);
INSERT INTO "ricette" VALUES (14064,'Maccheroni Del Buongustaio','Primo','Salsicce Fresche',4,' -','320 G Pasta Tipo Maccheroni,
2 Salsicce Fresche,
1 Cipolla,
350 G Pomodori Pelati,
1 Peperoncino,
4 Cucchiai Formaggio Pecorino Stagionato Grattugiato,
Olio D''oliva,
1/2 Bicchiere Vino Bianco','Fate soffriggere la cipolla in poco olio, aggiungete le salsicce spellate e tagliuzzate. Bagnate col vino, lasciate evaporare poi aggiungete il pomodoro, il peperoncino e aggiustate di sale. Fate cuocere per 15 minuti. Cuocete la pasta in abbondante acqua salata, conditela con il sugo ben caldo, spolverate col pecorino e servite.',2938);
INSERT INTO "ricette" VALUES (14065,'Maccheroni Del Ferretto','Primo','Uova',6,' -','300 G Semola Fine,
2 Uova,
2 Cucchiai Olio D''oliva,
Sugo Di Pomodoro,
Formaggio Pecorino,
Poca Farina,
1 Pizzico Zafferano,
Sale','Impastare i 300 g di semola fina con le uova sbattute, con 1 cucchiaio d''olio d''oliva, un pizzico di sale e uno di zafferano. Lavorare con cura fino ad ottenere un impasto piuttosto sostenuto, raccoglierlo a palla e lasciarlo riposare coperto con un tovagliolo. Trascorsa almeno 1 ora, staccare dalla massa dei pezzi grossi quanto una noce, tirarli in sfoglia sottilissima e farne dei quadratini di circa 8 cm di lato e cospargersi di farina. Prendere un comune ferretto da calza, di quelli che una volta si usavano per lavorare a mano i pedalini, posarlo su un vertice del quadrato di sfoglia e con movimento rotatorio delle mani, aperte e affiancate, rivestirlo di pasta. Ottenuto un cilindro a punta smussata sfilare il ferretto, posare il maccheroncino su un telo infarinato e continuare con lo stesso procedimento. La pasta confezionata va sistemata in un solo strato su una tovaglietta infarinata e ricoperta da un altro telo fino al momento di cuocerla. Va cotta nella solita acqua abbondante, bollente e salata, con aggiunta di un cucchiaio di olio, che ha la funzione di impedire ai maccheroni di attaccarsi gli uni agli altri. Scolati, si condiscono con sugo abbondante e pecorino dolce grattugiato.',2174);
INSERT INTO "ricette" VALUES (14066,'Maccheroni Dell''orto','Primo','Zucchine',4,' -','400 G Pasta Tipo Maccheroni,
200 G Filetti Di Pomodoro,
2 Zucchine,
1 Melanzana,
1 Peperone Sott''aceto,
1 Pizzico Origano,
Abbondante Olio D''oliva,
2 Cucchiai Aceto Di Vino,
1 Pizzico Sale','Mondate le verdure e tagliate a dadini le zucchine e la melanzana, fatele friggere in una padella con abbondante olio poi sgocciolate su un foglio di carta assorbente da cucina e salatele. Tagliate a dadini il peperone e trasferitelo in una terrina con zucchine e melanzana. Unitevi i pomodori, un pizzico d''origano e di sale e 2 cucchiai di aceto. Mescolate e lasciate riposare. Lessate la pasta, scolatela al dente versandola nella terrina del condimento. Mescolate delicatamente e servite ben caldo.',2422);
INSERT INTO "ricette" VALUES (14067,'Maccheroni Dello Chef','Primo','Formaggio Emmenthal',4,' -','Burro,
Formaggio Grattugiato,
Formaggio Emmenthal Tagliato A Dadini,
Prosciutto Cotto,
Besciamella,
Pasta Tipo Maccheroni','Lessate la pasta per 5 minuti. Conditela con burro e formaggio grattugiato. Unitevi i dadini di emmenthal e di prosciutto cotto. Sistematela in una teglia imburrata e copritela con abbondante besciamella. Fare gratinare in forno.',3049);
INSERT INTO "ricette" VALUES (14068,'Maccheroni E Broccoli','Primo','Broccoli',4,'Luogo: Lazio. Luogo: Ciociaria. Luogo: Roccasecca.','500 G Pasta Tipo Maccheroni,
500 G Broccoletti,
Olio D''oliva Extra-vergine,
Aglio,
Peperoncino,
Abbondante Formaggio Parmigiano Grattugiato','Si suole lasciar soffriggere alcuni spicchi d''aglio (in quantità variabile a seconda del gusto e della resistenza di ciascuno nel dopopasto) nell''olio d''oliva in una larga padella; indi si aggiunge un grosso peperoncino fin quando imbiondisca; soltanto allora si uniscano freschissimi broccoletti, si condisca con sale a piacere, si versi mezzo bicchiere d''acqua e alfin si copra con un coperchio in alluminio e si tenga a fuoco moderato. I broccoletti andranno momentaneamente tolti prima che siano completamente cotti e si aggiungerà un bicchiere d''acqua calda della pasta nella padella. Quando i maccheroni saranno cotti al dente, saranno calati nella padella insieme ai broccoletti e si mescolerà frequentemente per pochi minuti. Il piatto va servito caldo, spruzzato con parmigiano in abbondanza. Esiste in realtà una variante che prevede una aggiunta di vino bianco, oltre all''acqua, nella cottura dei broccoletti. Il tipo di pasta, come in tutti i piatti poveri può variare a seconda dei gusti e della disponibilità (spaghetti, bucatini, linguine, etc.).',2865);
INSERT INTO "ricette" VALUES (14069,'Maccheroni Gratinati','Primo','Uova',4,' -','350 G Pasta Tipo Maccheroni,
2 Uova,
Besciamella,
60 G Formaggio Grattugiato,
1 Noce Burro,
Sale','Preparate la besciamella e appena pronta insaporitela incorporandovi il formaggio grattugiato, una noce di burro e i due tuorli. In una capace pentola portate a bollore abbondante acqua salata, lessatevi i maccheroni, scolateli piuttosto al dente. Condite la pasta con metà besciamella mescolando con una certa delicatezza. Disponetela in una pirofila leggermente imburrata e ricopritela con la restante besciamella. Ponete in forno preriscaldato a 240 gradi e ritirate quando la superficie appare ben dorata. Vini di accompagnamento: Trebbiano Di Romagna DOC, Genzano Bianco DOC, Bianco Di Alcamo DOC.',2200);
INSERT INTO "ricette"