,'Cioccolato',8,' -','250 G Cioccolato Fondente,
125 G Burro,
1 Bustina Vaniglina,
3 Uova,
2 Tuorli D''uovo,
100 G Zucchero A Velo','Spezzettate il cioccolato in una casseruola e fatelo fondere a fuoco dolce con 3 cucchiai d''acqua. Lavorate il burro a spatola per rammollirlo. Separate le chiare dai tuorli e unite i 5 tuorli, uno alla volta, al burro, mescolando molto bene dopo ogni aggiunta successiva. Aggiungete lo zucchero a velo e continuate a mescolare. Unite infine il cioccolato fuso e profumate con la vaniglina (o con caffè se preferite). Lasciate raffreddare. Sbattete quindi a neve densa i 3 albumi e uniteli al composto. Versate in uno stampo imburrato e lasciate riposare per 10 ore in frigo. Servite su un letto di crema inglese.',3243);
INSERT INTO "ricette" VALUES (14530,'Marquise Al Cioccolato (2)','Dessert','Cioccolato',6,' -','250 G Cioccolato Fondente,
200 G Burro,
5 Uova,
80 G Zucchero A Velo,
50 G Scorza D''arancia Candita,
2 Cucchiai Rum (facoltativo)','Spezzettate il cioccolato, raccoglietelo in una pentola, aggiungete il rum se piace, fate sciogliere a fuoco basso. Ammorbidite il burro lavorandolo a lungo, unitelo al cioccolato fuso. Mescolate energicamente per rendere il composto leggero. Incorporatevi i tuorli uno alla volta. Unite la buccia d''arancia candita a pezzetti e lo zucchero a velo. Montate gli albumi a neve soda e incorporateli alla crema. Versate in uno stampo bagnato con acqua ghiacciata e mettete in frigorifero 24 ore. Sformate, servite con una salsa all''arancia.',4030);
INSERT INTO "ricette" VALUES (14531,'Marro Di Agnello','Carne','Agnello',4,' -','500 G Budellino D''agnello,
700 G Fegato E Milza D''agnello,
800 G Fettine Di Vitello,
120 G Formaggio Pecorino Grattugiato,
Prezzemolo Tritato,
Sale,
Pepe','Lavare in acqua tiepida le budella poi lasciarle a bagno per 30 minuti. Tagliare a pezzi il fegato e la milza, poi amalgamare il tutto con il pecorino grattugiato, sale e pepe, ed una manciata di prezzemolo tritato. Aprire le fettine di vitello in modo da formare un grande rettangolo. Ricoprire il rettangolo di carne con il composto d''agnello, ed avvolgere in modo da formare una specie di polpettone. Ricoprirlo interamente con il budellino d''agnello, in modo che il polpettone non si rovini durante la cottura. Poi cuocerlo in una teglia, sul fuoco, per circa 40 minuti con dell''acqua salata. Prima di servirlo, finire la cottura in forno a 180 gradi per 10-15 minuti.',3191);
INSERT INTO "ricette" VALUES (14532,'Marronata','Dessert','Castagne',4,' -','600 G Castagne Lesse Già Spellate,
500 G Zucchero,
1 Bicchierino Rum Ambrato,
1 Stecca Vaniglia','Passare le castagne al passino ed aggiungere alla purea ottenuta uno sciroppo fatto con lo zucchero e 300 g d''acqua. Cuocere per circa 30 minuti ed unire la vaniglia ed il rum. Cuocere altri 10 minuti e mettere in vasetti.',3156);
INSERT INTO "ricette" VALUES (14533,'Marroni Allo Sherry','Dessert','Sherry',4,' -','300 G Marroni,
200 G Prugne Secche,
Zucchero,
Cannella In Polvere,
1 Cucchiaio Succo Di Limone,
1 Bicchierino Sherry','Pelare i marroni e cuocerli piano in acqua e zucchero finché saranno morbidi. Snocciolare le prugne e cuocerle senza farle disfare. Mescolare la frutta e condirla con altro zucchero, 1 cucchiaio di succo di limone e 1 bicchierino di sherry, spolverizzare con la cannella e servire caldo.',2209);
INSERT INTO "ricette" VALUES (14534,'Marroni Brasati','Contorno','Marroni',4,' -','600 G Marroni,
20 G Burro,
150 Cl Brodo Di Carne,
1 Foglia Alloro,
Poco Timo,
1 Costa Sedano Bianco,
Sale,
Pepe','Sbucciate i marroni. In una casseruola lasciate sciogliere il burro, insaporitevi i marroni per un minuto e copriteli con un litro e mezzo di brodo. Aggiungete una foglia d''alloro lasciandola intera, poco timo e un costa di sedano bianco. Coprite e cuocete in forno preriscaldato a 220 gradi per 45 minuti, muovendo ogni tanto il recipiente, ma senza mescolare perché non si rompano. Salate e pepate solo alla fine. Servite come contorno di faraone, anatre, oche e carni arrosto.',3729);
INSERT INTO "ricette" VALUES (14535,'Marroni In Zuppetta','Antipasto','Marroni',4,' -','50 Marroni,
2 Fette Prosciutto Crudo,
2 Chiodi Di Garofano,
Alloro,
Pane Tostato,
Brodo','Sbucciate i marroni e cuoceteli in poca acqua con l''alloro, il prosciutto e i chiodi di garofano. Quando saranno teneri aggiungete il brodo e lasciate bollire per 15 minuti. Servite in ciotoline con pane tostato.',12869);
INSERT INTO "ricette" VALUES (14536,'Marrons Glacés','Dessert','Castagne',8,' -','2000 G Castagne,
150 Cl Acqua,
1000 G Zucchero,
1 Stecca Vaniglia','Si mettono a bagno per qualche ora 2000 g di castagne in acqua fredda. Poi si fanno bollire per 2 ore con la buccia e molto adagio. Si sbucciano ancora calde e si mettono nello sciroppo. Lo sciroppo si prepara con un litro e mezzo di acqua ed 1000 g di zucchero: si fa bollire l''acqua con lo zucchero finché è un po'' denso. Versare in una padella, mettervi le castagne e si fare bollire per un''ora molto lentamente con una stecca di vaniglia. Poi si lasciano assorbire lo zucchero per 3 ore sempre tenendole al caldo. Infine, si mettono a scolare sopra un canovaccio.',7561);
INSERT INTO "ricette" VALUES (14537,'Marrons Glacés (2)','Dessert','Marroni',4,' -','Marroni,
Acqua,
Zucchero','Pelare i marroni senza sciuparne la superficie. Adagiateli in un colapasta metallico, possibilmente di rame, e immergeteli in un recipiente pieno di acqua fredda nella quale sia già stata sciolta poca farina. Cuoceteli a fuoco dolce, senza che giungano mai ad ebollizione, per una ventina di minuti. Eliminate la prima acqua di cottura e sostituitela con uno stesso quantitativo di acqua, già bollente e addizionata anch''essa di poca farina. Continuate la cottura per un''ora, togliete i marroni dal fuoco ed eliminate la pellicina esterna. Adagiateli in una casseruola contenente uno sciroppo di zucchero aromatizzato alla vaniglia. Controllate che il liquido copra perfettamente i frutti, mettete la casseruola sul fuoco e fate cuocere, senza coperchio, a temperatura moderata e per tempi lunghissimi. Quando sulla superficie dei marroni si formerà una sottile crosta, scolate e lasciate asciugare molto lentamente in luogo caldo.',441);
INSERT INTO "ricette" VALUES (14538,'Marsal','Bevande','Succo D''arancia',1,' -','1/6 Vodka Keglevich Classica,
1/6 Vecchia Romagna Buton,
2/6 Succo D''arancia,
2/6 Succo D''ananas,
Per Guarnire:,
1 Fetta Arancia,
1 Foglia D''ananas,
1 Ciliegina Rossa Al Maraschino','Si prepara direttamente nel bicchiere tumbler alto con ghiaccio. Mescolare delicatamente. Guarnire con una fetta d''arancia, una foglia d''ananas, una ciliegina rossa al maraschino e cannucce.',259);
INSERT INTO "ricette" VALUES (14539,'Marsala Flip','Bevande','Vino Marsala',1,' -','1 Uovo Intero,
60 G Vino Marsala,
1 Cucchiaino Zucchero,
Per Servire:,
Noce Moscata Grattugiata','Agitare velocemente nello shaker. Servire nel gotto basso, con una velatura di noce moscata grattugiata.',212);
INSERT INTO "ricette" VALUES (14540,'Marsala Martini','Bevande','Gin',1,' -','1/3 Gin,
1/3 Vermouth Dry,
1/3 Vino Marsala Secco,
1 Scorza Di Limone','Scuotete bene, con ghiaccio, i primi 3 ingredienti, quindi versate in un bicchiere da cocktail già freddo. Spremete la scorza di limone e lasciatela cadere dentro il bicchiere.',257);
INSERT INTO "ricette" VALUES (14541,'Marsaletto','Bevande','Noci',4,' -','18 Noci,
100 Cl Vino,
1 Stecca Cannella,
1 Pizzico Chiodi Di Garofano,
250 G Zucchero,
350 G Alcool','Mettere in un vaso noci, vino, cannella e chiodi di garofano ed esporre al sole per 40 giorni, poi filtrare ed aggiungere, per ogni litro ottenuto, 250 g di zucchero e 350 g di alcool.',3489);
INSERT INTO "ricette" VALUES (14542,'Martina','Bevande','Whisky',1,' -','1/5 Curacao Blu De Kuyper,
2/5 Jameson Irish Whisky,
1/5 Mandarinetto,
1/5 Vermouth Martini Dry,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Si prepara nello shaker con cubetti di ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa al maraschino.',299);
INSERT INTO "ricette" VALUES (14543,'Martina (2)','Bevande','Gin',1,' -','1/2 Vermouth Dry,
1/2 Gin,
1 Cucchiaio Curacao,
1 Spruzzo Succo D''arancia,
1 Spruzzo Angostura,
Per Servire:,
1 Oliva','Mescolare a lungo nel mixer con ghiaccio. Servire nel calice basso, con un''oliva.',426);
INSERT INTO "ricette" VALUES (14544,'Martinelli','Bevande','Vermouth',1,' -','1/4 Vermouth Bianco Martini,
1/4 Vermouth Rosso Martini,
1/4 Rum Bacardi Bianco,
1/4 Cointreau,
Per Guarnire:,
1 Fettina Arancia','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con fettina d''arancia.',269);
INSERT INTO "ricette" VALUES (14545,'Martinez','Bevande','Gin',1,' -','4/5 Gin,
1/5 Vermouth Dry,
1/2 Cucchiaino Maraschino,
2 Cucchiaini Aranciata Amara','Mescolate bene, con ghiaccio. Versate in un bicchiere da cocktail già freddo.',380);
INSERT INTO "ricette" VALUES (14546,'Martini Blu','Bevande','Gin',1,' -','9/10 Gin,
1/10 Vermouth Dry,
1 Cucchiaino Scotch Whisky','Agitate bene tutto, aggiungete ghiaccio e versate in un bicchiere da cocktail già freddo.',381);
INSERT INTO "ricette" VALUES (14547,'Martini Cocktail','Bevande','Gin',1,' -','2/3 Gin,
1/3 Vermouth Dry,
Per Servire:,
1 Oliva Verde','Si prepara nel miscelatore con ghiaccio tritato. Si versa nel bicchiere da cocktail e si serve con una oliva verde.',320);
INSERT INTO "ricette" VALUES (14548,'Martini Cocktail (2)','Bevande','Gin',1,' -','5/5 Gin,
1 1/2 Cucchiaio Vermouth Dry,
Per Guarnire:,
1 Spicchio Limone','Nel mixer pieno per metà con cubetti di ghiaccio, mescolare gin e vermouth. Agitare bene. Mettere in un bicchiere da cocktail e guarnire con lo spicchio di limone.',401);
INSERT INTO "ricette" VALUES (14549,'Martini Cocktail (3)','Bevande','Gin',1,' -','5/6 Gin,
1/6 Vermouth Dry,
Per Guarnire:,
1 Spicchio Limone','Nel mixer pieno per metà con cubetti di ghiaccio, mescolare gin e vermouth. Agitare bene. Mettere in un bicchiere da cocktail. Guarnire con lo spicchio di limone.',334);
INSERT INTO "ricette" VALUES (14550,'Martini Cocktail (4)','Bevande','Vermouth',1,' -','1 Cucchiaio Vermouth Dry,
3/11 Gin,
8/11 Lemonsoda,
Per Guarnire:,
1 Spicchio Limone','Nel mixer pieno per metà con cubetti di ghiaccio, mescolare gin e vermouth. Agitare bene. Mettere in un bicchiere da cocktail. Guarnire con lo spicchio di limone.',179);
INSERT INTO "ricette" VALUES (14551,'Martini Cocktail (5)','Bevande','Gin',1,' -','5/6 Gin,
1/6 Vermouth Dry,
Per Guarnire:,
1 Spicchio Limone','Riempire uno shaker per metà con cubetti di ghiaccio. Mettere tutti gli ingredienti nello shaker e agitare bene. Mettere in un bicchiere da cocktail il composto ottenuto nello shaker. Guarnire con lo spicchio di limone.',334);
INSERT INTO "ricette" VALUES (14552,'Martini Cocktail (6)','Bevande','Gin',1,' -','2/7 Vermouth Dry,
5/7 Gin,
Per Servire:,
1 Oliva,
1 Scorza Di Limone','Agitare nel mixer a lungo, con cubetti di ghiaccio. Servire nel calice basso, con un''oliva e una scorza di limone precedentemente spremuta nel bicchiere.',330);
INSERT INTO "ricette" VALUES (14553,'Martini Cocktail (7)','Bevande','Vermouth Dry',1,' -','1/4 Vermouth Dry,
3/4 Gin,
1 Spruzzo Succo Di Limone','Versate gli ingredienti nel mixer, mescolate e servite ghiacciato.',314);
INSERT INTO "ricette" VALUES (14554,'Martini Cocktail (8)','Bevande','Gin',1,' -','6/7 Gin,
1/7 Vermouth Dry,
Per Servire:,
Olive,
Tartine Salate','Agitate gin e vermouth con ghiaccio e versate in un bicchiere da cocktail già freddo. Servite con olive e tartine salate.',600);
INSERT INTO "ricette" VALUES (14555,'Martini Cocktail Dry','Bevande','Gin',1,' -','5/6 Gin,
1/6 Vermouth Dry,
Per Decorare:,
1 Oliva','Si prepara nel mixing glass con dei cubetti di ghiaccio. Si serve nella coppetta per cocktail. Decorare con 1 oliva.',339);
INSERT INTO "ricette" VALUES (14556,'Martini Dolce','Bevande','Gin Dry',1,' -','2/3 Gin Dry,
1/3 Vermouth Rosso','Si prepara nel mixing-glass con poco ghiaccio e si serve in coppette da cocktail. Simile al Martini Dry, ne rappresenta la versione ''più morbida''.',309);
INSERT INTO "ricette" VALUES (14557,'Martini Dolce (2)','Bevande','Gin',1,' -','4/5 Gin,
1/5 Vermouth Dolce,
1 Scorza D''arancia','Mescolate gin e vermouth, aggiungete del ghiaccio e versate in un bicchiere da cocktail già freddo. Spremete la scorza d''arancia nel bicchiere e lasciatela cadere dentro. E'' molto forte.',354);
INSERT INTO "ricette" VALUES (14558,'Martini Dry','Bevande','Gin',1,' -','3/4 Gin,
1/4 Vermouth Dry,
1 Oliva','Agitare gin e vermouth con ghiaccio nel mixer. Mettere in un bicchiere da cocktail. Aggiungere l''oliva e servire.',322);
INSERT INTO "ricette" VALUES (14559,'Martini Dry (2)','Bevande','Gin Dry',1,' -','3/4 Gin Dry,
1/4 Vermouth Dry,
1 Spruzzo Scorza Di Limone,
1 Oliva','Si prepara nel mixer, versando gli ingredienti nell''ordine sopra dei cubetti di ghiaccio e mescolando. Si serve nei bicchieri da cocktail aromatizzati con 1 spruzzo di buccia di limone e con 1 oliva.',323);
INSERT INTO "ricette" VALUES (14560,'Martini Dry (3)','Bevande','Gin Dry',1,' -','120 G Gin Dry,
40 G Vermouth Dry,
1 Spruzzo Scorza Di Limone,
1 Oliva','Si prepara nel mixer, versando gli ingredienti nell''ordine sopra dei cubetti di ghiaccio e mescolando. Si serve nei bicchieri da cocktail aromatizzati con 1 spruzzo di buccia di limone e con 1 oliva.',351);
INSERT INTO "ricette" VALUES (14561,'Martini Dry (4)','Bevande','Gin Dry',1,' -','3/4 Gin Dry,
1/4 Vermouth Dry','Mescolare gli ingredienti con poco ghiaccio nel mixing-glass, utilizzando il cucchiaio lungo. Servire in coppette da cocktail. Aperitivo classico.',312);
INSERT INTO "ricette" VALUES (14562,'Martini Dry (5)','Bevande','Gin',1,' -','1/4 Vermouth Dry,
3/4 Gin,
Per Servire:,
1 Oliva,
1 Scorza Di Limone','Mescolare a lungo nel mixer con cubetti di ghiaccio. Servire nel calice basso, con un''oliva e una scorza di limone.',327);
INSERT INTO "ricette" VALUES (14563,'Martini Dry (6)','Bevande','Gin',1,' -','30 Cl Gin,
10 Cl Vermouth Dry,
4 Pezzetti Scorza Di Limone,
4 Cubetti Ghiaccio','Servendovi di un frullatore, versate nel boccale il gin e il vermouth e lasciate mescolare il tutto per pochi secondi. Servite il drink, versando nei bicchieri la scorzetta di limone e il ghiaccio. Suggerimento: per presentare al meglio il martini dry, potreste bagnare il bordo del bicchiere immergendolo nel succo di limone e passarlo successivamente nel sale fino da cucina. Così oltre a creare un simpatico e poco impegnativo effetto scenografico otterrete un ottimo contrasto di sapori.',861);
INSERT INTO "ricette" VALUES (14564,'Martini Dry Cocktail','Bevande','Martini Dry',1,' -','3/4 Dry Gin,
1/4 Martini Dry,
1 Oliva Verde,
1 Limone (scorza)','Si prepara agitando fortemente nel mixing glass (bicchierone da cocktail) con ghiaccio molto freddo ed aggiungendo appena prima di versare uno sprizzo di buccia di limone. Oliva verde per completare il tutto.',337);
INSERT INTO "ricette" VALUES (14565,'Martini Extra Dry','Bevande','Gin',1,' -','7/8 Gin,
1/8 Vermouth Dry,
Per Servire:,
1 Oliva Verde','Si prepara nel miscelatore con ghiaccio tritato. Si versa nel bicchiere da cocktail e si serve con una oliva verde.',344);
INSERT INTO "ricette" VALUES (14566,'Martini Extra Dry (2)','Bevande','Vermouth',1,' -','1 Spicchio Limone Sbucciato,
1/5 Vermouth Dry,
4/5 Gin','Agitare gin e vermouth con ghiaccio nel mixer. Mettere in un bicchiere da cocktail. Servire con lo spicchio di limone.',329);
INSERT INTO "ricette" VALUES (14567,'Martini Extra Dry (3)','Bevande','Gin',1,' -','1/7 Vermouth Dry,
6/7 Gin,
Per Servire:,
1 Oliva,
1 Scorza Di Limone','Mescolare a lungo nel mixer con cubetti di ghiaccio. Servire nel calice basso, con un oliva e una scorza di limone precedentemente spremuta nel bicchiere.',346);
INSERT INTO "ricette" VALUES (14568,'Martini For All','Bevande','Vodka',1,' -','1/5 Vermouth Rosso Martini,
2/5 Vodka Eristow,
1/5 Bitter Rossi,
1/5 China Martini','Si prepara nello shaker con cubetti di ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda.',293);
INSERT INTO "ricette" VALUES (14569,'Martini Medium','Bevande','Vermouth',1,' -','1 Oliva,
1/5 Vermouth Dolce,
3/5 Gin,
1/5 Vermouth Dry','Agitare gin e vermouth con ghiaccio nel mixer. Mettere in un bicchiere da cocktail. Aggiungere l''oliva e servire.',311);
INSERT INTO "ricette" VALUES (14570,'Martini On The Rocks','Bevande','Gin',1,' -','1/8 Vermouth Dry,
7/8 Gin,
Per Servire:,
1 Oliva,
1 Scorza Di Limone','Preparare direttamente nel tumbler stretto in cui già si trovino cubetti di ghiaccio. Servire con un''oliva e una scorza di limone precedentemente spremuta nel bicchiere.',348);
INSERT INTO "ricette" VALUES (14571,'Martini Perfect','Bevande','Gin',1,' -','8/10 Gin,
1/10 Vermouth Dry,
1/10 Vermouth Rosso Dolce,
Per Decorare:,
1 Ciliegina Al Maraschino','Versate il Gin e i due Vermouth nel mixing glass con dentro i cubetti di ghiaccio, mescolate per 6-8 secondi. Servite nella coppetta per cocktail con la ciliegia.',345);
INSERT INTO "ricette" VALUES (14572,'Martini Red','Bevande','Gin',1,' -','1/3 Vermouth Rosso,
2/3 Gin,
1 Spruzzo Bitter All''arancia,
Per Servire:,
1 Ciliegia','Mescolare con ghiaccio tritato nel mixer. Servire nel calice basso con una ciliegia.',325);
INSERT INTO "ricette" VALUES (14573,'Martini Sweet','Bevande','Gin',1,' -','1/2 Gin,
1/2 Vermouth Bianco Dolce,
Per Servire:,
1 Oliva Verde','Si prepara nel miscelatore con ghiaccio tritato. Si versa nel bicchiere da cocktail e si serve con una oliva verde.',320);
INSERT INTO "ricette" VALUES (14574,'Martini Sweet (2)','Bevande','Gin',1,' -','1 Oliva,
2/4 Gin,
2/4 Vermouth Dolce','Agitare gin e vermouth con ghiaccio nel mixer. Mettere in un bicchiere da cocktail. Aggiungere l''oliva e servire.',319);
INSERT INTO "ricette" VALUES (14575,'Martini Sweet (3)','Bevande','Vermouth Rosso',1,' -','2/3 Gin Dry,
1/3 Vermouth Rosso','Unire gli ingredienti nel mixer con ghiaccio e mescolare.',309);
INSERT INTO "ricette" VALUES (14576,'Martini Sweet (4)','Bevande','Vermouth Rosso',1,' -','120 G Gin Dry,
60 G Vermouth Rosso','Unire gli ingredienti nel mixer con ghiaccio e mescolare.',370);
INSERT INTO "ricette" VALUES (14577,'Martini Sweet (5)','Bevande','Gin Dry',1,' -','4 Cubetti Ghiaccio,
7 Cl Gin Dry,
3 Cl Vermouth Rosso','Questo cocktail si prepara nel mixing-glass, procedendo in questo modo: mettete il ghiaccio nel bicchiere miscelatore e unitevi il gin e il vermouth rosso. Mescolate con cura gli ingredienti ed infine filtrate il drink nella coppetta.',209);
INSERT INTO "ricette" VALUES (14578,'Martini Sweet (6)','Bevande','Vermouth Rosso',1,' -','1/3 Vermouth Rosso,
2/3 Gin','Unite gli ingredienti nel mixer con 2 cubetti di ghiaccio, quindi servite nella coppa da Martini.',309);
INSERT INTO "ricette" VALUES (14579,'Martini Traditional','Bevande','Gin',1,' -','1 Oliva,
3/5 Gin,
2/5 Vermouth Dry','Agitare gin e vermouth con ghiaccio nel mixer. Mettere in un bicchiere da cocktail. Aggiungere l''oliva e servire.',311);
INSERT INTO "ricette" VALUES (14580,'Martini Very Dry','Bevande','Vermouth Martini Dry',1,' -','4/5 Gin Dry,
1/5 Vermouth Martini Dry','Si prepara nel mixing glass.',324);
INSERT INTO "ricette" VALUES (14581,'Martini Vodka','Bevande','Vodka',1,' -','5/6 Vodka,
1/6 Vermouth Dry,
Per Servire:,
1 Oliva','Si prepara nel mixing glass con ghiaccio, si serve nella coppetta per cocktail con l''oliva.',331);
INSERT INTO "ricette" VALUES (14582,'Martinique','Bevande','Vermouth Rosso',1,' -','1/3 Vermouth Rosso,
2/3 Rum,
2 Spruzzi Bitter All''arancia,
Per Servire:,
1 Fettina Arancia,
1 Fettina Limone','Agitare nel mixer con molto ghiaccio in cubetti. Servire nel gotto basso con una fetta d''arancia e una di limone.',332);
INSERT INTO "ricette" VALUES (14583,'Mary','Bevande','Gin',1,' -','4/10 Tanqueray Gin,
4/10 Vermouth Martini Bianco,
1/10 Pernod,
1/10 Succo Di Limone,
Per Guarnire:,
1 Fettina Limone','Si prepara nello shaker con cubetti di ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una fettina di limone.',259);
INSERT INTO "ricette" VALUES (14584,'Mary (2)','Bevande','Gin',1,' -','1/4 Vermouth Dry,
1/4 Benedictine,
2/4 Gin,
2 Spruzzi Pernod,
1 Spruzzo Angostura,
Per Servire:,
1 Scorza Di Limone','Agitare vigorosamente e a lungo nello shaker con ghiaccio in cubetti. Servire nel calice basso con scorza di limone.',405);
INSERT INTO "ricette" VALUES (14585,'Mary Fizz','Bevande','Gin',1,' -','1/5 Succo Di Limone,
4/5 Gin,
1/2 Cucchiaio Zucchero,
Per Completare:,
Soda,
Gazzosa,
1 Cucchiaino Sciroppo Di More','Agitare, con molto ghiaccio, nel mixer. Versare, riempiendo per due terzi, nel gotto alto o nel tumbler ampio in cui già si trovi del ghiaccio tritato. Aggiungere soda e gazzosa e mescolare dolcemente con l''apposito cucchiaino. Infine versare delicatamente in superficie un cucchiaino di sciroppo di more.',459);
INSERT INTO "ricette" VALUES (14586,'Mary Pickford','Bevande','Rum Bianco',1,' -','4 Cubetti Ghiaccio,
5 Cl Rum Bianco,
3 Cucchiai Succo D''ananas,
1 Cucchiaino Granatina,
1 Spruzzo Maraschino','Mettete i cubetti di ghiaccio nello shaker, unite il rum, il succo di ananas, la granatina e il maraschino. Agitate energicamente per qualche istante, poi filtrate il cocktail in un bicchiere a calice.',232);
INSERT INTO "ricette" VALUES (14587,'Mary Pikford','Bevande','Succo D''ananas',1,' -','1/2 Rum Bacardi,
1/2 Succo D''ananas,
1/2 Cucchiaino Granatina,
1/2 Cucchiaino Maraschino','Si prepara nello shaker con ghiaccio tritato.',247);
INSERT INTO "ricette" VALUES (14588,'Mary Pikford (2)','Bevande','Rum Bianco',1,' -','1/2 Rum Bianco,
1/2 Spremuta D''ananas,
4 Cucchiaini Granatina,
24 Gocce Maraschino Luxardo','Si tratta di un cocktail dedicato alla famosa attrice degli anni d''oro di Hollywood. Si prende soprattutto come dissetante, preparato nello shaker con ghiaccio.',443);
INSERT INTO "ricette" VALUES (14589,'Mary Pikford (3)','Bevande','Rum Bianco',1,' -','40 G Rum Bianco,
40 G Spremuta D''ananas,
4 Cucchiaini Granatina,
24 Gocce Maraschino Luxardo','Si tratta di un cocktail dedicato alla famosa attrice degli anni d''oro di Hollywood. Si prende soprattutto come dissetante, preparato nello shaker con ghiaccio.',336);
INSERT INTO "ricette" VALUES (14590,'Mary Poppins','Bevande','Gin',1,' -','1/3 Crema Cacao,
2/3 Gin,
Per Servire:,
1 Pizzico Polvere Di Cacao','Agitare a lungo nel mixer con poco ghiaccio in cubetti. Servire nel flute con un pizzico di polvere di cacao in superficie.',323);
INSERT INTO "ricette" VALUES (14591,'Maryland Crab Cakes','Antipasto','Polpa Di Granchio',6,'Luogo: Stati Uniti.','60 G Burro,
1 1/2 Cipolla Tritata,
200 G Mollica Di Pane,
650 G Polpa Di Granchio,
4 Uova Sbattute,
Sale,
1 Cucchiaino Mostarda In Polvere,
1 Cucchiaino Salsa Worcester,
3 Cucchiai Panna,
100 G Farina,
Olio Per Friggere,
1 Limone','Sciogliete il burro in una larga padella e aggiungete le cipolle. Fatele saltare per circa 3 minuti, fin quando non diventano scure. Togliete la padella dal fuoco e mettetevi dentro la mollica di pane e la polpa di granchio. Nel frattempo in una terrina versate le uova sbattute, il sale, la mostarda e la salsa worcester, e mescolate bene. Aggiungetevi il composto ottenuto alla polpa di granchio, lavorate bene e formate le crocchette (circa 20). Passatele nella farina. In una padella fate scaldare l''olio, e quando è ben caldo friggete le crocchette di granchio per circa 3 minuti, fino a renderle dorate. Servite con fette di limone.',3232);
INSERT INTO "ricette" VALUES (14592,'Marzapane','Antipasto','Mandorle',4,' -','250 G Acqua,
1000 G Zucchero,
1/2 Bustina Vaniglina,
1000 G Mandorle Pelate Ridotte In Polvere','Mettere in un tegame 250 g di acqua con 1000 g di zucchero, mescolare e far bollire finché lo zucchero fila. La prova si fa immergendovi un cucchiaio di legno e sollevandolo: se la goccia colando si allungherà a filo: è il momento di togliere il tegame dal fuoco. Incorporarvi allora mezza bustina di vaniglina e, a cucchiaiate, 1000 g di mandorle pelate e ridotte in polvere. Mescolare bene per amalgamare tutto e versare la pasta su di un tavolo di marmo bagnato. Appena sarà fredda lavoratela a lungo, finché non diventa liscia e compatta. A questo punto si potrà utilizzare come si desidera.',9676);
INSERT INTO "ricette" VALUES (14593,'Marzapane (2)','Dessert','Mandorle Dolci',6,' -','300 G Mandorle Dolci (possibilmente Di Avola),
300 G Zucchero Semolato,
2 Mandorle Amare,
Poco Miele,
Poca Acqua Di Fiori D''arancio,
Olio Di Girasole (o Olio Di Mandorle)','E'' una ricetta piuttosto difficoltosa e lunga: pelate tutte le mandorle e stendetele su una placca. Ponetele nel forno caldo, lasciandole asciugare: non dovranno colorirsi. Lasciatele, infine, raffreddare, per tritarle nel modo più fine possibile. Ponetele in un mortaio e pestatele, riducendole in pasta. Unite, goccia a goccia, una cucchiaiata di acqua di fior d''arancio. Versate lo zucchero in un polsonetto di rame non stagnato (potete usare una casseruolina in materiale antiaderente), unite 150 g di acqua e lasciate cuocere lo zucchero fino a che arrivi a 115 gradi. Unite le mandorle già preparate. Aggiungete una cucchiaiata di miele (manterrà la pasta più morbida) e proseguite la cottura a fuoco molto basso, sempre mescolando con un cucchiaio di legno, sino a che la massa sarà omogenea e consistente. Versatela sul marmo del tavolo da cucina, che avrete leggermente unto con poco olio di semi di girasole o di mandorle. Appena sarà possibile toccare la pasta senza scottarsi, dividetela a pezzi e lavoratela con le mani. Passate i pezzi attraverso i rulli della macchina per fare la pasta, continuando così fino a che questa sarà diventata morbida e pastosa, o utilizzate un matterello (è più faticoso). A questo punto è pronta da usare per le varie preparazioni. Si conserva al fresco, avvolta nella pellicola, posta in un vaso o altro contenitore.',3772);
INSERT INTO "ricette" VALUES (14594,'Marzapane Alle Violette','Dessert','Mandorle',4,' -','200 G Mandorle,
500 G Zucchero,
1 Cucchiaio Essenza Di Violette','Macinate le mandorle. Aggiungete 400 g di zucchero, l''essenza di violette, e acqua sufficiente ad ammorbidire l''impasto. Ricavatene dei rotolini, tagliateli a pezzetti, passateli nello zucchero avanzato. Mettete nei pirottini di carta colorata e servite.',3128);
INSERT INTO "ricette" VALUES (14595,'Marzia','Bevande','Whisky',1,' -','1/10 Sciroppo Di Lampone Sacco,
5/10 Jameson Irish Whisky,
2/10 Cordial Campari,
2/10 Crema Latte,
Per Guarnire:,
Alcuni Lamponi','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con lamponi.',335);
INSERT INTO "ricette" VALUES (14596,'Masanete In Insalata','Pesce','Masanete',4,' -','1000 G Masanete (femmine Dei Granchi),
2 Spicchi Aglio,
1 Ciuffo Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Lavate più volte le masanete (le femmine dei granchi), poi lessatele in abbondante acqua bollente leggermente salata; si dovrebbero mettere in pentola ancora vive per essere certi che siano freschissime. Fatele cuocere per sette-otto minuti, non di più, poi spegnete il fuoco e lasciatele intiepidire nella loro acqua. Scolatele, staccate le zampe e, con una forbicina, tagliate il carapace. Mettete le masanete in un''insalatiera, conditele ancora tiepide con un trito di aglio e prezzemolo, olio, sale e pepe. Lasciatele riposare almeno un''ora perché assorbano il condimento, quindi servitele, magari accompagnate da fette di polenta bianca.',1534);
INSERT INTO "ricette" VALUES (14597,'Mascarpone','Dessert','Panna',4,' -','100 Cl Panna,
1 G Acido Tartarico','Il mascarpone presenta una lavorazione abbastanza lunga e richiede un ambiente tiepido, asciutto e pulito nel quale gocciolare. Prendete 100 cl di panna e fatela cuocere a bagnomaria sino a raggiungere una temperatura di 80 gradi. Togliete dal fuoco e aggiungetevi 1 g di acido tartarico (che potete procurarvi in farmacia) e mescolate qualche minuto col cucchiaio di legno. Versate il composto su un traliccio di giunco o paglia coperto da una pezza di tela pulita. Fate gocciolare in questa maniera per dodici ore. Trascorso questo tempo, con un cucchiaio, prelevate dall''impasto delle quantità di circa 100-150 g e avvolgeteli nella garza pulita. Mettete questi fagottini in frigo per altre dodici ore e poi potrete gustarlo.',3781);
INSERT INTO "ricette" VALUES (14598,'Mascarpone Al Cacao','Dessert','Cacao',4,' -','400 G Mascarpone,
100 G Zucchero A Velo,
50 G Cacao,
3 Cucchiai Rum,
Per Decorare:,
Cioccolato Grattugiato','Lavorare il mascarpone con lo zucchero e il cacao passato al setaccio. Profumare la crema con il rum, suddividerla nelle singole coppe e mettere in frigorifero per un''ora prima di servire. Decorare con il cioccolato grattugiato.',3050);
INSERT INTO "ricette" VALUES (14599,'Mascarpone Al Caffè','Dessert','Caffè',4,' -','400 G Mascarpone Freddissimo,
1 Tazzina Caffè Forte,
50 G Zucchero A Velo,
2 Cucchiai Liquore Al Caffè,
4 Cialde A Bastoncino,
8 Chicchi Caffè','Amalgamare al mascarpone lo zucchero a velo. Versare nella crema il caffè ben freddo e il liquore. Mescolare e suddividere in 4 coppe tenute in frigo per 15 minuti. Decorare ogni coppa con la cialda e con i chicchi di caffè.',2542);
INSERT INTO "ricette" VALUES (14600,'Mascarpone Al Caffè (2)','Dessert','Caffè',4,' -','400 G Mascarpone,
2 Cucchiaini Caffè Macinato,
1 Bicchierino Brandy,
50 G Zucchero,
Biscotti Secchi','Mettere il mascarpone in una terrina, incorporarvi il caffè e mescolare fino a che il mascarpone sarà diventato ben cremoso. Irrorare con il brandy e spolverizzare con lo zucchero. Amalgamare bene tutti gli ingredienti e servire in tavola il composto sistemato in coppette e guarnito con i biscotti, dopo averlo tenuto in frigo per 30 minuti circa.',2202);
INSERT INTO "ricette" VALUES (14601,'Mascolini Marinati','Pesce','Mascolini',4,'Luogo: Sicilia. Luogo: Catania.','500 G Mascolini,
2 Spicchi Aglio,
6 Limoni,
1 Pezzetto Prezzemolo,
1 Filo Olio D''oliva,
1 Pizzico Sale,
Molto Pepe','I mascolini appartengono alla famiglia delle acciughe e sono il pesce bianco più diffuso a Catania e sulla costa etnea. Si cucinano in vari modi e si mangiano anche crudi secondo questa ricetta. Pulite bene i mascolini, lavateli sotto l''acqua corrente e togliete loro la lisca e la testa. Disponeteli in una zuppierina coperti con succo di limone, e aggiungete un pizzico di sale. Lasciate riposare per qualche ora, poi cambiate il succo con quello di altri limoni freschi e condite ancora con un pizzico di sale. Mettete i mascolini in frigorifero e dopo 24 ore toglieteli dalla marinata e serviteli come antipasto, con un filino d''olio, molto pepe, aglio a pezzetti, prezzemolo tritato e qualche fetta di limone. Se non vorrete consumarli subito i pesciolini potranno stare nella marinata, in frigo, per quattro o cinque giorni.',1018);
INSERT INTO "ricette" VALUES (14602,'Massei','Bevande','Whisky',1,' -','4/10 Wild Turkey Bourbon Whisky,
3/10 Drambuie,
2/10 Amaretto Di Saronno,
1/10 Rose''s Lime Juice Cordial','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda.',300);
INSERT INTO "ricette" VALUES (14603,'Masy','Bevande','Vino Champagne Brut',4,' -','1 Bottiglia Vino Champagne Brut,
Alcuni Cucchiai Grappa Di Pere,
Poche Gocce Angostura','Versate in ciascun bicchiere 1 cucchiaio di grappa di pere e 3 gocce di angostura. Colmate sino all''orlo con champagne ghiacciato e servite.',1073);
INSERT INTO "ricette" VALUES (14604,'Matador','Bevande','Tequila',1,' -','1/3 Succo D''ananas,
2/3 Tequila,
1 Cucchiaio Succo Di Limone,
1 Goccia Sciroppo Di Lampone,
Per Servire:,
1 Ciliegina','Agitare nel mixer con molto ghiaccio in cubetti. Servire nel gotto basso, con una ciliegina.',366);
INSERT INTO "ricette" VALUES (14605,'Matador (2)','Bevande','Vermouth Dry',1,' -','1/5 Vermouth Dry,
1/5 Vermouth Chinato,
3/5 Gin','Versate gli ingredienti nel mixer, mescolate e servite con ghiaccio.',301);
INSERT INTO "ricette" VALUES (14606,'Matador Pick Me Up','Bevande','Gin',1,' -','5 Cubetti Ghiaccio,
4 Cucchiai Gin,
1 Cucchiaino Tio Pepe,
1 Cucchiaino Bitter Campari,
1 Oliva Di Spagna','Per la preparazione di questo cocktail bisogna usare il mixing-glass, ben gelato in precedenza nel frigorifero o nel freezer. Per prima cosa mettete nel bicchiere miscelatore i cubetti di ghiaccio, poi versatevi sopra, nell''ordine, gli ingredienti liquidi elencati. Mescolate per alcuni secondi con il cucchiaino a manico lungo, poi trasferite il miscuglio in una coppetta, filtrandolo attraverso l''apposito colino (in modo da trattenere il ghiaccio). Immergete nel cocktail l''oliva di Spagna, infilata sull''apposito spiedino da bar oppure anche semplicemente su uno stecchino.',437);
INSERT INTO "ricette" VALUES (14607,'Mate All''argentina','Bevande','Mate',1,'Luogo: Argentina.','2 Cucchiaini Mate,
Acqua Tiepida','Si mette un cucchiaino o due di Mate in un piccolo recipiente di metallo, poi si versa su dell''acqua appena calda e si tira da una cannuccia, anche questa di metallo.',65);
INSERT INTO "ricette" VALUES (14608,'Mate Cocido','Bevande','Mate',1,' -','1 Cucchiaio Erba Di Mate,
Acqua Calda','Mettere l''erba del mate in infusione per qualche minuto nell''acqua calda, e quindi filtrarlo in tazza.',5);
INSERT INTO "ricette" VALUES (14609,'Mate Con Il Latte','Bevande','Mate',1,' -','Acqua Calda,
Erba Di Mate,
Latte','Mettere l''erba del mate in infusione per qualche minuto nell''acqua calda, e quindi filtrarlo in tazza. Aggiungere un goccio di latte.',60);
INSERT INTO "ricette" VALUES (14610,'Matisse','Bevande','Vodka',1,' -','1/10 Aperol,
2/10 Bitter Campari,
1/10 Cointreau,
2/10 Vermouth Bianco Cinzano,
4/10 Vodka Absolut,
1 Sprizzo Di Scorza D''arancia,
Per Guarnire:,
1 Fettina Mela Rossa','Versare gli ingredienti nello shaker con abbondante ghiaccio cristallino. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda con sprizzo di scorza d''arancia. Guarnire con una fettina di mela.',364);
INSERT INTO "ricette" VALUES (14611,'Matoke','Pollame','Pollo',4,'Luogo: Africa.','6 Banane Verdi,
1500 G Pollo Senza Pelle Tagliato A Pezzi,
2 1/2 Cucchiai Ghee (o Margarina),
1 Tazza Farina (125 G),
1 Cipolla Tagliata A Fette,
1 Cucchiaino Curry In Polvere,
2 Pomodori Tagliati A Fette,
1 Tazza Brodo (24 Cl),
Latte,
Margarina,
Sale,
Pepe','Fate sciogliere 2 cucchiai di ghee o di margarina in un tegame. Infarinate i pezzi di pollo e poi fateli cuocere finché non si coloriscono. Togliete dalla padella e mettete a parte. Fate soffriggere la cipolla per 5 minuti e poi aggiungete il curry in polvere, e dopo circa 1 minuto i pomodori. Lasciate cuocere per qualche minuto e poi rimettete dentro i pezzi di pollo. Versate il brodo, aggiungete sale e pepe e fate cuocere per circa 30 minuti finché la carne non sarà tenera. Intanto bollite dell''acqua in una pentola e fate cuocere le banane con la buccia per circa 20-30 minuti. Lasciate raffreddare e, appena possibile, sbucciatele e schiacciatele in una ciotola aggiungendo un po'' di latte e margarina e insaporendo con sale e pepe. Versate il tutto in un piatto di portata, adagiate sopra i pezzi di pollo e versate la salsa. Servite subito con spinaci e zucchine.',4248);
INSERT INTO "ricette" VALUES (14612,'Matrona','Bevande','Vodka',1,' -','8 Cucchiai Succo Di Pomodoro,
Sale,
Pepe,
Succo Di Limone,
5 Cubetti Ghiaccio,
6 Cucchiai Vodka Ghiacciata','Mettete il succo di pomodoro nel mixing-glass e conditelo con sale, pepe e succo di limone a piacere; poi unite i cubetti di ghiaccio e mescolate a lungo (se preferite, potete usare direttamente succo di pomodoro gelato). Versate il succo condito nel flute o nel tumbler alto (se avete usato i cubetti di ghiaccio, li tratterrete nello strainer) e aggiungetevi la Vodka, senza mescolare.',804);
INSERT INTO "ricette" VALUES (14613,'Mattino Rosa','Bevande','Rum',1,' -','1/3 Succo Di Limone,
1/3 Cointreau,
1/3 Rum,
2 Gocce Granatina,
Per Servire:,
1 Fetta Limone','Agitare nello shaker con ghiaccio in cubetti. Servire nel calice panciuto, con una fetta di limone.',217);
INSERT INTO "ricette" VALUES (14614,'Mattonella A Due Colori','Dessert','Pan Di Spagna',4,'Preparazione: 30 minuti.','350 G Gelato Al Pistacchio (v. Ricetta),
350 G Gelato Al Cioccolato (v. Ricetta),
200 G Pan Di Spagna,
Alchermes,
Ciliegine Al Maraschino','Preparate i due gelati secondo le istruzioni delle ricette relative, ma dimezzando le dosi. Mentre i gelati sono in consolidamento, mettete nel freezer per circa 30 minuti uno stampo da plumcake, foderato con carta di alluminio. Nel frattempo tagliate il pan di Spagna a fettine sottili, allineate queste ultime in un piatto e bagnatele con dell''alchermes per colorarle di rosso. Riprendete quindi lo stampo dal freezer, mettetevi dentro il gelato al cioccolato e, con l''aiuto di un cucchiaio, formate con esso uno strato che ricopra completamente il fondo del recipiente e che risalga tutt''intorno alle pareti dello stampo per un''altezza di circa due centimetri. Nell''incavo che si formerà nel centro sistemate una parte delle fettine di pan di Spagna e disponete su queste il gelato al pistacchio. Livellate accuratamente la superficie del gelato e adagiatevi sopra le fettine di pan di Spagna rimanenti. Coprite lo stampo con altra carta di alluminio e introducetelo nel freezer per circa 2-3 ore. Al momento di servire, capovolgete lo stampo su un piatto ovale, eliminate la carta di alluminio e decorate la superficie della ''mattonella'' con ciliegine al maraschino. Servite subito.',2588);
INSERT INTO "ricette" VALUES (14615,'Mattonella All''arancia','Dessert','Arance',8,' -','150 G Marmellata Di Arance,
180 G Zucchero,
5 Uova,
1 Arancia,
1 Bicchierino Curacao,
50 Cl Latte,
70 G Farina,
30 G Amido Di Mais,
1 Pizzico Sale,
Per Lo Stampo:,
Farina,
Burro','Imburrate ed infarinate uno stampo quadrato di 22 centimetri a parete alta. Preparate la pasta: montate 2 uova intere con 100 g di zucchero sino ad ottenere un composto bianco e gonfio. Unite, facendole cadere a pioggia da un setaccino, la farina, la maizena ed un pizzico di sale, mescolando molto bene: versate il composto nello stampo e infornate a 180 gradi per circa 25 minuti. Fate bollire il latte. Sbattete in una ciotola 2 uova intere ed 1 tuorlo con 80 g di zucchero: unite poi il latte a filo mescolando con una piccola frusta, indi aggiungete la scorza grattugiata dell''arancia. Quando la pasta sarà cotta sformatela su una gratella e lasciatela raffreddare; tagliatela a metà; ponetene una metà sul fondo dello stampo, pulito e foderato con carta forno, irroratela con 1 bicchierino di liquore e spalmatela con metà marmellata di arance. Coprite con il secondo quadrato di pasta, irrorate anch''essa con il Curaçao e distribuitevi sopra la restante marmellata; versate lentamente sulla pasta così farcita il composto al latte, lasciando che venga assorbito. Mettete quindi lo stampo in un bagnomaria caldo e passatelo in forno a 180 gradi per circa 50 minuti. Sformate il dolce sul piatto di portata, togliendo la carta forno. Quando sarà freddo mettetelo in frigorifero per almeno un paio d''ore.',3358);
INSERT INTO "ricette" VALUES (14616,'Mattonella Alla Nutella','Dessert','Nutella',6,' -','300 G Nutella,
250 G Burro,
1/2 Tazzina Caffè,
80 G Zucchero A Velo,
50 G Farina,
6 Uova','Mettete in un pentolino il caffè, la Nutella, il burro e lo zucchero e riscaldate fino a che il burro non si sarà sciolto del tutto. Mescolate le uova e la farina con la frusta, quindi aggiungete lentamente la salsa di Nutella. Rimettete sul fuoco e cuocete per 15 minuti a fiamma bassa evitando che si formino grumi. Imburrate uno stampo rettangolare e riempitelo con la crema di Nutella. Disponete lo stampo in una pirofila dai bordi piuttosto alti e riempita fino a 3/4 di acqua calda. Cuocete il dolce a bagnomaria nel forno preriscaldato a 180 gradi per circa 90 minuti. Fate raffreddare completamente il dolce prima di sformarlo.',4605);
INSERT INTO "ricette" VALUES (14617,'Mattonella Di Caffè','Dessert','Caffè',4,' -','24 Biscotti Secchi,
125 G Burro,
100 G Zucchero A Velo,
1 Cucchiaio Caffè Solubile,
1 Cucchiaino Cacao,
3 Tazze Caffè Freddo,
1 Tuorlo D''uovo','Lavorare a spuma, in una terrina, il burro e lo zucchero. Intanto aggiungere il tuorlo e il caffè solubile. Immergere rapidamente 8 biscotti nel caffè freddo disporli sul piatto di portata e coprirli con 1/3 della crema; posare sopra altri 8 biscotti bagnati di caffè e coprire con crema. Finire con l''ultimo strato di biscotti e crema e spolverizzare di cacao. Tenere in frigo per 3 ore.',2197);
INSERT INTO "ricette" VALUES (14618,'Mattonella Di Carne E Verdura','Contorno','Fagiolini',8,' -','1100 G Carne Tritata Mista (maiale, Pollo, Vitello),
120 G Formaggio Parmigiano,
100 G Fagiolini,
3 Zucchine,
3 Carote,
3 Uova,
Burro,
Latte,
Pancarré,
Pangrattato,
1 Cucchiaio Prezzemolo Tritato,
1 Pizzico Foglie Di Timo,
Noce Moscata,
Sale','Mettete in una ciotola i tre tipi di carne macinata. Lavorateli insieme con il pancarré bagnato nel latte e ben strizzato, il parmigiano grattugiato, le uova, una cucchiaiata di prezzemolo tritato con un pizzico di foglie di timo, noce moscata e sale. Mondate i fagiolini, le carote e le zucchine; tagliate le ultime due a listerelle e scottate le 3 verdure per 2 minuti in acqua bollente, quindi sgocciolatele e stendetele ad asciugare su un canovaccio. Imburrate e rivestite di pangrattato uno stampo da plumcake. Disponetevi a strati gli ingredienti, alternando uno strato di carne, rispettivamente con uno di fagiolini, uno di carote e uno di zucchine; finite con la carne. Cuocete in forno a 200 gradi per circa 40 minuti e servite tiepido o freddo, con sugo di arrosto.',3399);
INSERT INTO "ricette" VALUES (14619,'Mattonella Di Fichi Secchi','Dessert','Ficchi Secchi',4,' -','600 G Fichi Secchi,
30 G Mandorle Sgusciate E Tostate E Noci,
60 G Cioccolata Fondente,
1 Limone Verde Grande (scorza),
Aleatico','Triturare fichi, mandorle, noci; unirli a scorza grattugiata di limone, cioccolato a pezzetti, una spruzzata d''aleatico. Foderare di carta oleata 1 stampo rettangolare con viti a farfalla; adagiarvi il composto e tenerlo pressato per 3 ore. Una volta sformata la mattonella, tenere in frigo 2 ore. Servire a fettine sottili con aleatico.',2225);
INSERT INTO "ricette" VALUES (14620,'Mattonella Di Frutta E Ricotta','Dessert','Fragole',8,'Preparazione: 20 minuti.','1 Rettangolo Pan Di Spagna (400 G),
400 G Ricotta,
200 G Panna Da Montare,
200 G Fragole,
3 Kiwi,
1 Limone,
60 G Zucchero A Velo,
Maraschino,
Per Guarnire:,
Alcune Fragole','Mondate e sciacquate le fragole e sbucciate i kiwi. Montate ben ferma la panna. Frullate le fragole con metà dello zucchero, quindi unitevi metà della ricotta; a parte, frullate anche 2 dei kiwi, con lo zucchero e la ricotta che restano. Aromatizzate i 2 composti con scorzetta grattugiata di limone e amalgamate delicatamente a ognuno metà della panna. Tagliate in tre parti, orizzontalmente, il pan di Spagna e pennellate la parte che farà da base con il Maraschino. Spalmatevi 2/3 del composto rosa, coprite con pan di Spagna, pennellate anche questo pezzo con il liquore e spalmatelo con 2/3 del composto verdino; coprite con il terzo pezzo di pan di Spagna. Decorate la superficie del dolce con i composti tenuti da parte e con fettine di fragole e kiwi.',3743);
INSERT INTO "ricette" VALUES (14621,'Mattonella Di Lenticchie','Antipasto','Lenticchie',4,' -','250 G Lenticchie,
1 Carotina,
Scalogno,
Alloro,
3 Fogli Colla Di Pesce,
Sale,
Pepe,
Per Guarnire:,
Alcune Rondelle Carota,
Alcune Strisce Peperone','Cuocete le lenticchie con carote, sedano, scalogno e alloro. Salate pepate e aggiungete un po'' d''olio. Scolate bene le lenticchie, ricoprite con la gelatina (sciogliere tre fogli di colla di pesce) e guarnite con rondelle di carote a vapore e striscioline di peperone rosso. Lasciate in frigo per qualche ora. Servite come antipasto.',892);
INSERT INTO "ricette" VALUES (14622,'Mattonella Di Straccetti, Fagottino Di Camembert E Peperone','Contorno','Formaggio Camembert',4,' -','200 G Straccetti Di Manzo,
1 Cucchiaio Panna,
1 Albume D''uovo,
Erbe Miste,
2 Cucchiai Zucchero,
100 G Formaggio Camembert,
1 Foglio Brick,
100 G Peperone,
Olio D''oliva,
Sale,
Pepe','Frullare un cucchiaio di panna con le erbe, un albume, 50 g di straccetti, sale e pepe. Mescolare alla restante carne e cuocere in una padella antiaderente all''interno di un coppapasta quadrato, girando la mattonella sull''altro lato dopo 5 minuti. Tagliare a listarelle il peperone e cuocerlo in padella con zucchero. Farcire la brick con il peperone così cucinato e pezzetti di camembert. Chiudere a mo'' di fagottino e cuocere al forno per 10 minuti a 180 gradi. Servire la mattonella con il fagottino.',2196);
INSERT INTO "ricette" VALUES (14623,'Mattonella Di Tonno','Antipasto','Tonno Sott''olio',4,'Preparazione: 30 minuti.','400 G Tonno Sott''olio,
150 Cl Latte,
20 G Farina,
20 G Burro,
4 Fogli Colla Di Pesce (fogli Da 5 G),
1/2 Limone,
4 Filetti D''acciughe Sott''olio,
1 Cucchiaio Senape,
1 Cucchiaio Capperi,
20 Olive Verdi,
Noce Moscata,
Sale','Ammorbidite la colla di pesce in acqua fredda, strizzatela e scioglietela su fuoco basso con un cucchiaino di acqua. Fate la besciamella facendo fondere 20 g di burro, stemperatevi la farina, versate il latte tiepido e fate cuocere su fuoco basso per 10 minuti, mescolando. Salate e profumate con la noce moscata. Sgocciolate il tonno e frullatelo con la besciamella, le acciughe, due cucchiai di succo di limone, un cucchiaio di senape e la colla di pesce liquida. Versate la crema in una terrina, unitevi i capperi e le olive snocciolate. Imburrate uno stampo da plumcake e rovesciatevi il composto. Coprite con la pellicola trasparente e mettete in frigo per almeno 4 ore.',2272);
INSERT INTO "ricette" VALUES (14624,'Mattonella Farcita Con Panna E Banane','Dessert','Banane',8,'Preparazione: 75 minuti.','Per La Mattonella:,
190 G Burro,
170 G Zucchero Semolato,
170 G Cioccolato Fondente,
120 G Farina,
7 Uova,
Sale,
Per Lo Stampo:,
Burro,
Farina,
Per Farcire:,
200 G Panna Fresca,
2 Banane,
Rum,
Zucchero Semolato,
Zucchero A Velo','Tagliate le banane a rondelle, raccoglietele in una ciotola, irroratele con un bicchierino di rum, spolverizzatele con una cucchiaiata di zucchero semolato e lasciatele marinare per un''ora. Intanto, con lo sbattitore, montate a spuma il burro con lo zucchero; unite quindi i tuorli delle uova, il cioccolato fuso, la farina setacciata e, per ultimi, gli albumi montati in neve ben soda con un pizzichino di sale. Tutto l''impasto si può fare con lo sbattitore ad eccezione degli albumi montati che devono essere incorporati con un cucchiaio di legno, con movimenti dal basso verso l''alto e viceversa. Versate l''impasto in uno stampo rettangolare a bordi alti di cm 24 x 15, imburrato e infarinato, quindi passate in forno a 180 gradi per 45 minuti circa. Sfornate il dolce, lasciatelo raffreddare su una gratella da pasticciere poi tagliatelo a metà in senso orizzontale. Pennellate le due metà con il liquore usato per marinare le banane poi, sulla metà inferiore, mettete le fettine di banane e tutta la panna montata fermissima. Ricomponete il dolce, spolverizzatelo con lo zucchero a velo e guarnitelo con alcune rondelle di banane tenute da parte.',6515);
INSERT INTO "ricette" VALUES (14625,'Mattonella Primavera','Antipasto','Prosciutto',4,'Preparazione: 20 minuti. Cottura: 40 minuti. Calorie: 418.','250 G Prosciutto Cotto Tagliato Alto,
1 Patata Lessata,
1 Peperone Rosso,
1 Peperone Giallo,
150 G Maionese,
1 Carota Lessata,
4 Cetriolini Sott''aceto,
100 G Piselli In Scatola,
6 Uova Sode,
2 Tavolette Gelatina Istantanea Da 50 Cl Ciascuna,
Sale','Mescolate alla maionese la patata, la carota, i piselli, i peperoni e i cetriolini, tutto a dadini. Preparate la gelatina e spalmatevi uno stampo, fate rapprendere. Foderate con le fette di prosciutto. Al centro dello stampo sistemate le uova sode in fila e riempite con l''insalata russa. Versate su tutto la gelatina rimasta, chiudete la mattonella con il prosciutto che sborda e passate in frigorifero. Servite tagliato a fette.',3520);
INSERT INTO "ricette" VALUES (14626,'Mattonella Salata','Antipasto','Filetti D''acciughe',8,'Preparazione: 60 minuti. Calorie: 360.','150 G Prosciutto Cotto,
150 G Formaggio Robiola,
30 G Aceto Di Vino,
3 Filetti D''acciughe Sott''olio,
3 Carciofini Sott''olio,
2 Cetriolini Sott''aceto,
1 Falda Peperone Rosso Sott''aceto,
4 Uova Sode,
1 Filone Pane A Cassetta,
Maionese,
Salsa Worcester,
1 Trito D''erbe Aromatiche,
Ravanello,
Sale','Spuntate il filone di pane alle estremità e privatelo di una delle croste di base. Partendo dal lato senza crosta, affettate il filone per il lungo, in modo da ottenere 3 fette di "mollica", lunghe e larghe quanto il filone stesso e spesse cm 1,5 l''una. In una ciotolina mescolate l''aceto con uno spruzzo di Worcester e 40 g d''acqua fredda. Inumidite le fette, pennellandole da un lato con la bagna preparata. Passate il prosciutto al tritatutto elettrico, raccogliendo il ricavato in una ciotola. Mescolatelo ed amalgamatelo con la robiola e insaporite il composto con un pizzico di sale e uno spruzzo di Worcester. Passate ora le uova sode al tritatutto elettrico e raccogliete il ricavato in una seconda ciotola. Salatelo e mescolatelo con 2 cucchiaiate di maionese. Spalmate la prima fetta di pane, sul lato inumidito, con circa metà del composto al prosciutto. Guarnitela quindi con la falda di peperone, tagliata a listerelle. Spalmate con mezza cucchiaiata di maionese il lato non inumidito della seconda fetta, quindi appoggiatelo sulla prima, a contatto con il composto al prosciutto. Spalmate invece il lato inumidito con circa metà del composto d''uovo. Su questo disponete i filetti d''acciuga al centro, in fila per il lungo e, ai lati, i carciofini e i cetriolini tagliati a fettine. Completate la mattonella con la terza fetta di pane, disposta sulle altre due con il lato inumidito a contatto della farcia sottostante. Preparate ora con la carta speciale da cucina due cornetti per decorare e riempitene uno con il composto al prosciutto rimasto, l''altro con quello all''uovo sodo. Decorate la superficie della mattonella con strisce alternate dei due composti e terminate guarnendola con una fila di rondelle di ravanello al centro e cospargendola con una presina di trito aromatico. Sistemate la mattonella su un piatto rettangolare adeguato e servitela subito, oppure conservatela in frigorifero fino al momento di portarla in tavola. Si può preparare anche con un giorno d''anticipo.',4839);
INSERT INTO "ricette" VALUES (14627,'Mattonelle Di Riso','Antipasto','Riso',4,' -','400 G Riso Già Cotto,
100 G Formaggio A Fette,
1 Uovo Intero,
1 Tazza Sugo D''arrosto,
1 Tartufo,
100 G Pangrattato,
Olio Per Friggere,
Sale','Ponete in una terrina il risotto freddo, un uovo intero e il sugo dell''arrosto e mescolate con cura per amalgamare gli ingredienti. Stendete metà del composto ottenuto sul fondo di una teglia rettangolare, livellatelo bene, poi ricopritelo con le fette di formaggio e con il tartufo tagliato a lamelle sottili. Formate sulla farcitura uno strato regolare con il resto del risotto e comprimetelo servendovi di un cucchiaio. Tagliate la preparazione in tanti quadrati di uguale dimensione, usando un coltello inumidito. Sollevate delicatamente ciascun quadrato e passatelo nel pangrattato, facendo in modo che ne resti completamente coperto. Fate scaldare abbondante olio d''oliva in una padella e friggetevi i quadretti di riso 4-5 minuti per parte, a calore moderato. Scolateli quando sono ben dorati e passateli su un foglio di carta assorbente da cucina, per eliminare l''unto in eccesso. Serviteli caldi e cosparsi con un po'' di sale.',3024);
INSERT INTO "ricette" VALUES (14628,'Mattonnelle Di Piselli Tricolore','Contorno','Carote',6,' -','400 G Piselli Freschi Sgranati,
400 G Carote,
200 G Spinaci,
12 Cl Panna,
3 Uova,
30 G Ricotta,
Burro,
Cerfoglio,
Sale,
Pepe','Lessate separatamente piselli, carote e spinaci. Frullate, sempre separatamente, tutte le verdure e mettete il ricavato in tre ciotole diverse. In ognuna aggiungete un tuorlo, 1/3 della panna, un po'' di sale e pepe. In quella degli spinaci mettete anche la ricotta. Mescolate con cura gli ingredienti di ogni ciotola e in ultimo incorporatevi in ciascuna gli albumi montati a neve soda. Imburrate una pirofila e distribuite a strati metà composto di piselli, metà composto di carote, tutto il composto di spinaci, ancora quello di carote e infine quello di piselli. Pressate, livellate con la lama bagnata di un coltello, quindi coprite con un foglio d''alluminio. Cuocete in forno preriscaldato a 190 gradi per 40 minuti. Ritirate, fate intiepidire, quindi sformate sul piatto da portata. Decorate la mattonella tricolore con rondelle di carote e ciuffi di cerfoglio.',1952);
INSERT INTO "ricette" VALUES (14629,'Matuljska','Bevande','Brandy',1,' -','1/3 Brandy,
1/3 Vermouth Martini Bianco,
1/3 Amaretto Di Saronno,
Ginger Ale,
1 Ciliegina Al Maraschino','Agitare bene i primi tre ingredienti nel bicchiere tumbler con cubetti di ghiaccio. Allungare con Ginger Ale. Servire con 1 ciliegina al maraschino.',373);
INSERT INTO "ricette" VALUES (14630,'Maurilio','Bevande','Lemonsoda',1,' -','1/4 Aperol,
2/4 Lemonsoda,
1/4 Vermouth Martini Bianco,
Per Guarnire:,
1 Fragola A Spicchi,
1 Fetta Kiwi','Si prepara direttamente nel bicchiere tumbler alto con cubetti di ghiaccio. Mescolare delicatamente. Guarnire con una fragola a spicchi e una fetta di kiwi divisa in due e cannucce.',183);
INSERT INTO "ricette" VALUES (14631,'Maurizio','Bevande','Gin',1,' -','1/6 Succo Di Limone,
1/6 Apricot Brandy,
2/6 Curacao,
2/6 Gin,
Per Servire:,
1 Fetta Limone,
1 Pezzo Albicocca','Agitare a lungo nel mixer con ghiaccio in cubetti. Servire nel gotto basso, con una fetta di limone e un pezzo di albicocca.',262);
INSERT INTO "ricette" VALUES (14632,'Maurizio (2)','Bevande','Vermouth Dry',1,' -','1/4 Vermouth Dry,
1/4 Cointreau,
1/4 Whisky','Agitate gli ingredienti nello shaker con del ghiaccio, quindi servite.',203);
INSERT INTO "ricette" VALUES (14633,'Maxi ''o','Bevande','Aperol',1,' -','4/10 Aperol,
2/10 Pesca Light,
1/10 Succo Di Limone Boero,
3/10 Tanqueray Gin,
Per Guarnire:,
1 Ciliegina Bianca','Si prepara nello shaker con cubetti di ghiaccio. Agitare velocemente e servire nella coppetta da cocktail ben fredda. Guarnire con ciliegina bianca.',310);
INSERT INTO "ricette" VALUES (14634,'Maxi-coppa Del Bosco','Dessert','Lamponi',4,' -','400 G Sorbetto Di Lamponi,
200 G Lamponi,
4 Cucchiai Acquavite Di Lamponi,
4 Cucchiai Succo D''arancia,
Panna Montata,
Ghiaccio Tritato,
Soda','Mettere sul fondo di 4 grosse coppe freddissime l''acquavite di lamponi e il succo di arancia, mescolando piano. Poi disporre qualche lampone lavato, riempire per 2/3 la coppa con ghiaccio tritato, spruzzare con un po'' di soda, porre sopra 2 palline di sorbetto di lamponi, decorare con i restanti lamponi e con ciuffi di panna montata.',770);
INSERT INTO "ricette" VALUES (14635,'Maya','Bevande','Rum Bianco',1,' -','6/17 Rum Bianco,
2/17 Rum Ambrato,
1/17 Cointreau,
8/17 Succo D''ananas,
1 Cucchiaino Zucchero,
Per Decorare:,
1 Fetta Ananas,
1 Rametto Menta,
1 Ciliegia Candita','Versare i primi 5 ingredienti in un frullatore con del ghiaccio tritato. Azionare il frullatore per alcuni secondi e passare in un bicchiere senza stelo. Decorare con 1 fetta d''ananas, 1 rametto di menta e 1 ciliegia candita.',282);
INSERT INTO "ricette" VALUES (14636,'Mayfair','Bevande','Gin',1,' -','1/4 Succo D''arancia,
1/4 Apricot Brandy,
2/4 Gin,
Per Servire:,
1 Scorza D''arancia','Scuotere vigorosamente nello shaker con ghiaccio tritato. Servire nel tumbler stretto con una scorza d''arancia.',320);
INSERT INTO "ricette" VALUES (14637,'Mayfair (2)','Bevande','Gin',1,' -','1/4 Succo D''arancia,
1/4 Apricot Brandy,
2/4 Gin,
Per Servire:,
1 Fetta Arancia,
1 Scorza Di Limone,
1 Pezzetto Albicocca','Scuotere vigorosamente nello shaker con ghiaccio tritato. Servire nel calice ampio con una fetta d''arancia, una scorza di limone e un pezzetto d''albicocca.',308);
INSERT INTO "ricette" VALUES (14638,'Mazagan','Bevande','Cognac',1,' -','4 Cubetti Ghiaccio,
2 Cl Cognac,
2 Cl Maraschino,
1 Goccia Angostura,
2 Cucchiaini Sciroppo Di Zucchero,
Caffè Freddo,
3 Chiodi Di Garofano Pestati','Mettete i cubetti di ghiaccio in un bicchiere tumbler alto, unite il cognac, il maraschino, poi l''angostura, lo sciroppo di zucchero e finite di riempire con caffè freddo. Mescolate.',218);
INSERT INTO "ricette" VALUES (14639,'Mazzaccrocchi','Primo','Fagioli',6,'Luogo: Alatri. Luogo: Vico Nel Lazio. Luogo: Guarcino. Luogo: Ciociaria. Luogo: Lazio.','1000 G Farina Bianca,
5 Cucchiai Conserva Di Pomodoro,
250 G Fagioli,
300 G Cotechino,
100 G Strutto,
2 Spicchi Aglio,
Sale','Mettere a cuocere i fagioli con cotechino. Nel frattempo impastare la farina solo con l''acqua, stenderla e tagliarla a quadrucci. Preparare un sughetto finto con aglio, strutto e conserva di pomodoro sciolta in acqua calda. Quando i fagioli sono cotti, aggiungere il sughetto finto e la pasta, portando a termine la cottura.',5311);
INSERT INTO "ricette" VALUES (14640,'Mazzafegati Dolci','Carne','Maiale',4,'Luogo: Umbria.','1000 G Fegato Di Maiale,
150 G Grasso Ricavato Dalla Collarina,
100 G Pinoli,
100 G Uvetta Sultanina,
80 G Zucchero,
1 Arancia (scorza Tagliata A Dadini),
Pepe,
Sale','Lavare il fegato e asciugarlo. Porlo sopra il tagliere e con un coltello sminuzzarlo più che si possa. Tagliare il grasso a piccolissimi dadini e porre il tutto in una terrina. Condire il fegato con tutti gli ingredienti, insaccare il composto con l''imbuto e legare i mazzafegati come fossero delle normali salsicce. Cuocerli girati alla fiamma o in forno caldo (180 gradi) oppure al fuoco in un tegame con un po'' di olio.',2569);
INSERT INTO "ricette" VALUES (14641,'Mazzancolle Alla Rucola','Antipasto','Mazzancolle',4,' -','800 G Mazzancolle,
200 G Insalata Rucola,
10 Cl Olio D''oliva,
1 Limone,
Sale','Lavate e asciugate bene la rucola, disponetela sul fondo del piatto da portata. Sgusciate le mazzancolle, eliminate la parte scura, togliete la polpa e tenete da parte il corallo. Mettete la polpa nel cestino della pentola a vapore, ponete sul fuoco a calore moderato e fate cuocere per 4 minuti. Nel frattempo spremete il limone, filtrate il succo al colino e poi emulsionatelo con l''olio e un pizzico di sale battendo il composto con una piccola frusta. Poi adagiate i crostacei sul letto di rucola, guarniteli con il corallo e sopra versatevi a filo la salsa al limone. Servite le mazzancolle ancora tiepide. Vini di accompagnamento: Gavi DOC, Grave Del Friuli Pinot Bianco ''Superiore'' DOC, Vermentino Di Sardegna DOC.',1416);
INSERT INTO "ricette" VALUES (14642,'Mazzancolle In Crema Di Carciofi','Antipasto','Mazzancolle',4,' -','20 Mazzancolle,
8 Carciofi,
1 Limone,
Mentuccia Di Campo Tritata,
5 Cucchiai Olio D''oliva Extra-vergine,
Sale','Mondate i carciofi dalle foglie esterne più dure, tuffateli in acqua acidulata con il succo di mezzo limone e lessateli in acqua salata per 7-8 minuti; scolateli e tagliatene la metà a julienne e l''altra metà a pezzi. Frullate i carciofi a pezzi con un po'' di sale, un po'' di succo di mezzo limone, 2 cucchiai di olio e tanta acqua di cottura quanta ne serve per ottenere una crema leggermente liquida. Versate la crema in un piatto da servizio e, ruotando il piatto, rivestitene il fondo. Prendete l''altra metà dei carciofi e conditela con sale, succo di limone, mentuccia e 2 cucchiaiate di olio. Deponete la julienne al centro del piatto di servizio. Scottate le mazzancolle per 1 minuto in acqua bollente. Conditele con sale, succo di limone e il rimanente olio e sistematele decorativamente sulla crema di carciofi e intorno alla julienne.',1614);
INSERT INTO "ricette" VALUES (14643,'Mazzaro','Bevande','Whisky',1,' -','6/10 Canadian Club Whisky,
2/10 Galliano,
2/10 China Martini,
Per Guarnire:,
Scorza Di Limone','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con scorza di limone.',310);
INSERT INTO "ricette" VALUES (14644,'Mazzetti Di Carciofi E Asparagi Al Prosciutto Crudo','Contorno','Carciofi',4,'Luogo: Umbria.','12 Fette Prosciutto Crudo,
6 Carciofi Piccoli,
1 Mazzo Asparagi Coltivati,
Aglio,
Prezzemolo,
Menta,
Erba Cipollina,
Olio D''oliva Extra-vergine,
Aceto Balsamico,
Sale,
Pepe','Pulire gli asparagi ed i carciofi, privandoli delle parti meno tenere e lessarli separatamente in acqua leggermente salata e profumata con un po'' di aceto, tenendoli bene al dente. Riunire gli asparagi in sei mazzetti legandoli con fili di erba cipollina e quindi avvolgerli con le fette di prosciutto. Usare lo stesso procedimento con ogni carciofo e servire in tavola disponendo i mazzetti in bella vista, irrorandoli con una salsa composta da olio, aceto balsamico, sale, pepe ed un trito di prezzemolo aglio e menta.',6282);
INSERT INTO "ricette" VALUES (14645,'Maître D''hôtel','Salsa','Prezzemolo',4,' -','100 G Burro,
1 Ciuffo Grande Prezzemolo,
1/2 Limone (succo)','Lavorate con un cucchiaio di legno il burro fino a ridurlo un spuma; aggiungete alcune gocce di limone e una manciata di prezzemolo tritato; lavorate fino ad amalgamare il tutto.',767);
INSERT INTO "ricette" VALUES (14646,'Mbrecciata','Primo','Fagioli',4,' -','Fagioli,
Ceci,
Cecere,
Granturco,
Grano,
Lardo Di Maiale,
Pomodori Pelati,
Aglio,
Sale,
Pepe,
Olio D''oliva,
Acqua','Questa ricetta era tipica durante il periodo della ''scortecciatura''. La scortecciatura è la fase che segue il raccolto del granturco, cioè la fase che prevede la divisione delle spighe di granturco dalle proprie foglie e dalla cosiddetta ''barba''. E'' un piatto molto nutriente e soprattutto gustoso. Lasciare a bagno per una notte tutti i legumi ed i cereali in modo da farli rinvenire e quindi lessarli. Durante la cottura dei cereali e dei legumi, preparare il ''battuto''. Il battuto è una pasta ottenuta con il lardo, sale, pepe ed aglio. Si ponga un pezzo di lardo nel tagliere e con un coltello a lama larga o con la mezzaluna, iniziare a tagliuzzarlo fino ad ottenere una pasta omogenea. Aggiungere quindi il sale, il pepe e l''aglio schiacciato e continuare ad amalgamare tutti gli ingredienti. Il battuto è una pasta molto utilizzata nella cucina Umbra ed in particolare a Perugia per insaporire o per soffriggere. Preparare a parte una salsa di pomodoro nel seguente modo: far soffriggere nell''olio di oliva e nel battuto uno spicchio d''aglio quindi unire i pomodori pelati, l''acqua, sale e pepe quanto basta. Aggiungere acqua in modo da ottenere una salsa molto liquida e quindi unire tutti i cereali e tutti i legumi lessati e far bollire per mezz''ora.',2535);
INSERT INTO "ricette" VALUES (14647,'Mdj Light','Bevande','Panna Montata',1,' -','1/3 Panna Montata,
1/3 Crema Menta Verde,
1/3 Crema Cacao Bianca,
3 Cubetti Ghiaccio','Si prepara nel tumbler grande. Versate la crema di menta verde e la crema cacao bianca sopra i cubetti di ghiaccio, infine aggiungete la panna e mescolate il tutto.',258);
INSERT INTO "ricette" VALUES (14648,'Me & You','Bevande','Vermouth',1,' -','2/10 Mandarino Drink Boero,
5/10 Vermouth Martini Bianco,
3/10 Ron Pampero White','Si prepara nello shaker con ghiaccio. Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnizioni fantasia.',235);
INSERT INTO "ricette" VALUES (14649,'Med','Bevande','Succo D''ananas',1,' -','4/10 Artic Vodka E Pesca,
2/10 Vermouth Cinzano Dry,
1/10 Succo Tropicale,
2/10 Succo D''ananas,
1/10 Crema Banana De Kuyper,
Granatina Toschi,
Per Guarnire:,
Frutta Di Stagione','Si prepara nello shaker con ghiaccio. Agitare velocemente e servire nel tumbler con ghiaccio. Guarnire con spiedino di frutta di stagione e cannucce.',543);
INSERT INTO "ricette" VALUES (14650,'Medaglioni','Carne','Manzo',4,' -','500 G Polpa Di Manzo Macinata,
80 G Formaggio Grattugiato,
2 Uova,
30 G Burro,
1 Confezione Besciamella Pronta,
1 Mozzarella,
Olio D''oliva,
Sale','Amalgamate la carne con il formaggio e le uova intere sbattute; salate. Fate delle polpettine piuttosto schiacciate. Cuocetele rapidamente in un padellino con il burro e due cucchiai di olio, disponetele su una pirofila imburrata, sopra a ogni polpetta adagiate una fettina di mozzarella, coprite con la besciamella e mettete in forno a calore medio. Togliete quando la superficie è dorata.',2681);
INSERT INTO "ricette" VALUES (14651,'Medaglioni Ai Caprini','Carne','Manzo',4,' -','250 G Polpa Di Manzo Tritata,
2 Formaggi Caprini,
2 Fette Pancarré Bagnato Nel Latte,
Formaggio Grana Grattugiato,
Sale,
Pepe,
1 Uovo,
Burro Fuso','Impastare la polpa di manzo tritata con i caprini, le fette di pancarré, il grana grattugiato, un pizzico di sale, il pepe e l''uovo. Formare dei piccoli medaglioni, passarli nel pangrattato e metterli in 1 teglia imburrata, irrorarli di burro fuso e cuocerli in forno caldo a 200 gradi per 15 minuti.',2400);
INSERT INTO "ricette" VALUES (14652,'Medaglioni Al Prosciutto','Antipasto','Prosciutto',6,' -','400 G Prosciutto Cotto Tagliato A Fette Spesse,
250 G Lonza (o Pollo O Tacchino),
180 G Burro,
1 Cipolla Piccola,
1 Spicchio Aglio,
2 Cucchiai Cognac,
1/2 Bicchiere Vino Marsala Secco (o Vino Madera),
Sale,
Pepe','Tenete il burro a temperatura ambiente. Tritate la cipolla e fatela rosolare con l''aglio, a cui avrete eliminato l''interno verde, in circa 40 g di burro. Tagliate a pezzettini o, addirittura, tritate la carne: infarinatela e fatela rosolare nel vostro fondo di cottura. Appena si è indorata, aggiungete il Cognac e fatelo evaporare alzando la fiamma. In seguito, eseguite la stessa operazione con il Marsala (o il Madera). Coprite con un coperchio e lasciate cuocere a fuoco basso con una piccola porzione di dado per circa un''ora. Nel frattempo, regolate le fette di prosciutto e mettete i ritagli a cuocere con il resto del preparato. Quando la cottura sarà in fase di ultimazione, frullate il tutto e completatela aggiungendo il restante burro, amalgamando con sale e pepe. Allineate tre fette di prosciutto, sovrapponendole leggermente, in modo da ottenere un lungo rettangolo sul quale spalmate il paté ottenuto. Ricoprite con ulteriori tre fette di prosciutto e ripetete la stessa operazione fino ad esaurimento della crema di carne. Arrotolate il tutto, stringete bene e avvolgete in una carta oleata. Lasciate il rotolo in frigorifero fino a quando si sarà completamente raffreddato e solidificato. Quando ciò sarà avvenuto, lo taglierete a fette dello spessore di non più di 1 cm. che metterete in una gelatina preparata precedentemente. Tenete presente, nel programmare i vostri pranzi, che questo è un antipasto che si può comodamente preparare un giorno prima.',3606);
INSERT INTO "ricette" VALUES (14653,'Medaglioni Alla Cezanne','Contorno','Prosciutto',4,'Preparazione: 45 minuti. Cottura: 40 minuti. Calorie: 624.','120 G Pasta Sfoglia Surgelata,
400 G Prosciutto Di Praga,
200 G Spinaci Surgelati,
100 G Funghi Champignon,
20 Cl Salsa Mornay,
1/2 Cipolla,
2 Cucchiai Formaggio Parmigiano Grattugiato,
60 G Burro,
Prezzemolo,
Sale,
Pepe','Dalla pasta sfoglia tirata ad uno spessore di pochi millimetri ricavate 8 dischi di 8 cm di diametro ciascuno, usando l''apposito stampino. Bucherellateli in superficie e cuoceteli per 10 minuti circa in forno a 200 gradi. Tagliate il prosciutto a dischi leggermente più piccoli della sfoglia. Tritate la cipolla e il prezzemolo, tagliate a dadini i funghi puliti e i ritagli di prosciutto. Rosolate tutto in 20 g di burro, salate e pepate e unite metà della salsa mornay. Intanto lessate gli spinaci in acqua bollente salata, tritateli, insaporiteli in 20 g di burro e con essi formate delle palline. Procedete ora al montaggio del piatto, che è la parte più lunga e laboriosa di tutta la preparazione. Adagiate le tartine di pasta sfoglia su un tagliere, spalmatele con il trito di funghi, prosciutto, cipolla e prezzemolo. Passate la lama di un coltello lungo il bordo, in modo che il trito non fuoriesca dalla pasta. Adagiate su ogni tartina un medaglione di prosciutto. Al centro di ogni medaglione adagiate una pallina di spinaci. Lucidate la superficie con la salsa mornay rimasta, spolverate con il formaggio grattugiato e il burro fuso rimasto. Passate in forno per pochi minuti a gratinare. Servite i medaglioni caldi, decorando il piatto di portata con rondelle di sedano e julienne di carote.',3186);
INSERT INTO "ricette" VALUES (14654,'Medaglioni Di Aragosta','Pesce','Aragosta',4,'Preparazione: 30 minuti. Cottura: 60 minuti. Calorie: 624.','1 Aragosta Di 1200 G,
1/2 Tavoletta Da .5 L Di Gelatina Istantanea,
60 G Burro,
1 Carota,
1 Cipolla,
1 Costa Sedano,
Pepe In Grani,
1 Foglia Alloro,
3 Cucchiai Aceto Di Vino,
Sale,
Per Il Contorno:,
150 G Carote,
150 G Fagiolini,
1 Mazzetto Erba Cipollina','Preparate il brodo con 5 litri d''acqua, la carota, il sedano, la cipolla, l''alloro, l''aceto e il pepe. Cuocetevi l''aragosta per 30 minuti e intanto preparate la gelatina. Estraete la polpa all''aragosta e tagliatela a medaglioni. Pennellateli di gelatina e metteteli in frigo. Cuocete al vapore le carote e i fagiolini, legateli a mazzetti con l''erba cipollina e irrorateli con il burro fuso. Servite i medaglioni di aragosta con la verdura.',1665);
INSERT INTO "ricette" VALUES (14655,'Medaglioni Di Aragosta In Bellavista','Pesce','Aragosta',4,' -','1 Aragosta Da 1000 G,
Pancarré,
Maionese,
Insalata Rucola,
Gelatina,
Burro,
Sale','Lessate l''aragosta in un court-bouillon per 15 minuti e lasciatela raffreddare nel brodo di cottura. Sgocciolatela, estraete la polpa e tagliatela a medaglioni. Preparate la gelatina seguendo le istruzioni sulla confezione. Spennellatela sui medaglioni diverse volte, metteteli in frigorifero. Fate dorare, in poco burro, il pancarré senza crosta, disponetelo sul piatto da portata, adagiatevi i medaglioni, contornate con la rucola e servite con a parte la maionese. Vini di accompagnamento: Collio Sauvignon DOC, Bolgheri Bianco DOC, Arenarie Alghero DOC.',2530);
INSERT INTO "ricette" VALUES (14656,'Medaglioni Di Carne Trita','Carne','Bue',4,' -','300 G Carne Di Bue Macinata,
100 G Prosciutto,
50 G Salsiccia,
3 Cucchiai Formaggio Parmigiano Grattugiato,
1 Cucchiaio Prezzemolo Tritato,
1/2 Spicchio Aglio,
1 Rametto Rosmarino,
1 Uovo,
1 Noce Burro,
Noce Moscata,
1/2 Bicchiere Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Mettete la carne in una terrina, mescolatevi il prosciutto tritato, la salsiccia, il prezzemolo, l''aglio pure tritato, il parmigiano, un pizzico di noce moscata, sale, pepe e l''uovo (tenete a parte un po'' di albume che unirete solo se il composto riuscirà troppo sodo). Impastate con le mani per poter amalgamare perfettamente gli ingredienti. Assaggiate ed eventualmente salate ancora un poco. Dividete il composto in quattro o otto porzioni a seconda se preferite avere dei grossi o piccoli medaglioni e schiacciateli con il palmo delle mani dando loro una forma rotonda il più regolare possibile. Mettete al fuoco una padella con il burro e qualche cucchiaiata di olio, unitevi il rosmarino, lasciate un po'' scaldare, quindi adagiatevi i medaglioni, uno accanto all''altro. Lasciate che formino da una parte la crosticina, quindi staccateli dal fondo con una forchetta e rigirateli delicatamente. Schiacciateli leggermente, sempre con la forchetta, per far uscire il sugo della carne e possano così cuocersi bene anche all''interno. Quando saranno coloriti, eliminate la salvia o il rosmarino e spruzzateli con il vino. Fate evaporare il vino lentamente. Servite i medaglioni contornati con delle carote lessate in acqua, scolate a metà cottura e terminate di cuocere nel burro.',2579);
INSERT INTO "ricette" VALUES (14657,'Medaglioni Di Coda Di Rospo Al Vapore Con Verdure','Pesce','Coda Di Rospo (rana Pescatrice)',4,' -','1 Coda Di Rospo (rana Pescatrice) Di 600 G,
1 Carota,
1 Costa Sedano,
1 Fettina Zenzero,
10 Foglie Basilico,
1 Cucchiaio Vino Bianco,
40 G Olio D''oliva Extra-vergine,
Prezzemolo','Pulire il pesce e tagliarlo a medaglioni. Adagiare su di un piatto e marinare col vino, lo zenzero ed il prezzemolo. Pulire carota e sedano, tagliarli a julienne e sbollentarli. Mettere il pesce nella vaporiera, salare, pepare e cuocere per 4 minuti circa. Mettere le verdure nell''olio della marinatura col basilico tagliato a julienne.',1072);
INSERT INTO "ricette" VALUES (14658,'Medaglioni Di Filetto Al Cognac','Carne','Vitello',1,' -','1 Filetto Di Vitello Di 200 G,
Sale,
Pepe,
1 Cucchiaino Mostarda,
Olio D''oliva,
Succo Di Limone,
1 Noce Burro,
Per Guarnire:,
Punte Di Asparagi,
Prezzemolo Tagliuzzato,
Limone Tagliuzzato','Condire il filetto con sale, pepe e spennellarlo di mostarda. Padella calda, olio di oliva, appoggiare il filetto e dorarlo da una parte e dall''altra. Bagnare con succo di limone e flambare con il cognac. Demi-glace e una noce di burro. Decorare con salsa, filetto, punte di asparagi intorno al medaglione e decorare il bordo con prezzemolo e limone tagliuzzato.',1478);
INSERT INTO "ricette" VALUES (14659,'Medaglioni Di Manzo Con Prugne E Funghi','Carne','Manzo',4,'Preparazione: 20 minuti. Calorie: 416.','650 G Filetto Di Manzo,
300 G Funghi Misti Surgelati,
150 G Prugne Secche Snocciolate,
1/3 Bicchiere Vino Bianco Secco,
5 Cucchiai Olio D''oliva,
1 Mazzetto Prezzemolo,
Sale,
Pepe','Mondate le foglie di un mazzetto di prezzemolo e tritatele finemente. Scaldate in una padella 3 cucchiaiate d''olio d''oliva, aggiungetevi il prezzemolo e i funghi misti, ancora surgelati. Fateli cuocere a fiamma vivace. Bagnateli con un terzo di bicchiere di vino bianco, lasciatelo evaporare e salate. Unite anche le prugne snocciolate. Tagliate il filetto a medaglioni. Rosolatelo in un''altra padella con due cucchiaiate d''olio. Salatelo, pepatelo e unitelo ai funghi. Scaldate il tutto per mezzo minuto, quindi servite la carne accompagnata dal suo saporito intingolo. Vino consigliato: Valtellina Sfurzat.',1593);
INSERT INTO "ricette" VALUES (14660,'Medaglioni Di Mare','Pesce','Filetti Di Sogliola',4,' -','300 G Filetto Di Salmone,
300 G Filetti Di Sogliola,
1 Patata Bollita,
50 G Olive Nere,
1 Uovo,
1 Tuorlo D''uovo,
1 Cucchiaio Prezzemolo Tritato,
20 G Farina,
2 Cucchiai Olio D''oliva,
20 G Burro,
2 Dita Brodo Vegetale,
1 Cucchiaio Concentrato Di Pomodoro,
1 Bicchiere Panna (o Yogurth),
Sale,
Pepe','Salate e pepate il salmone e i filetti di sogliola, disponeteli su una larga pirofila unta con 2 cucchiai di olio, metteteli su una pentola colma di acqua in ebollizione e copritela. Cuocete a vapore per circa 15 minuti, poi frullate i pesci insieme con la patata sbucciate e passata allo schiacciapatate. Unite le olive tritate il tuorlo e l''uovo, mescolate e fate delle polpette molto piatte, perfettamente rotonde. Infarinatele e disponete sul fondo di una pirofila imburrata. Sciogliete 20 g di burro, amalgamatevi 20 g di farina e diluite lentamente mescolando, con 2 dita di brodo caldo in cui avrete stemperato il concentrato di pomodoro. Fate addensare per 7/8 minuti su fuoco basso, mescolando. Spegnete, unite un bicchiere di panna (o yogurth), un cucchiaio di prezzemolo tritato, sale e pepe. Mescolate la salsa, versatela sul pesce e mettete in forno caldo a 180 gradi per 15 minuti.',2086);
INSERT INTO "ricette" VALUES (14661,'Medaglioni Di Patate','Contorno','Patate',4,'Luogo: Lazio.','4 Patate Grandi,
Alcune Fettine Prosciutto Crudo,
Alcune Fettine Formaggio Fontina,
Olio D''oliva,
Burro,
Alcune Foglie Salvia','Prendete le patate sbucciatele e tagliatele a fette piuttosto spesse. Su ogni fetta disponete una fettina di prosciutto e una fettina sottile di formaggio. Sovrapponete un''altra fetta di patata e legate in croce ogni medaglione con del filo sottile in modo che il ripieno non esca cuocendo. Mettete le patate cosi preparate con olio e burro e qualche foglietta di salvia in una teglia, lasciando cuocere piano e rivoltandole fino a che siano ben colorite dalle due parti.',4050);
INSERT INTO "ricette" VALUES (14662,'Medaglioni Di Pollo Con Verdure E Cavolo','Pollame','Pollo',4,' -','300 G Petti Di Pollo,
1 Carota,
1 Costa Sedano,
1/2 Cipolla,
1/2 Limone,
2 Cucchiai Olio D''oliva Extra-vergine','Infarinare il pollo e lasciarlo dorare nel burro. Aggiungere il limone spremuto e lasciar cuocere. A parte, preparare una julienne di verdure e cuocerle nell''olio e cipolla, aggiungendo un po'' d''acqua. Unire e servire.',736);
INSERT INTO "ricette" VALUES (14663,'Medaglioni Di Prosciutto Cézanne','Antipasto','Prosciutto Cotto',4,' -','4 Fette Prosciutto Cotto (meglio Se Di Praga) (fette Spesse 1 Cm, 50 G Ognuna),
1 Confezione Pasta Sfoglia Surgelata,
1 Cipolla Tritata Piuttosto Finemente,
1 Cucchiaio Prezzemolo Tritato,
50 G Burro,
25 Cl Besciamella,
1 Tuorlo D''uovo,
400 G Spinaci Lessati Tritati,
20 G Formaggio Parmigiano Grattugiato,
Sale,
1 Pizzico Pepe Nero Appena Macinato,
Per La Pirofila:,
Poco Burro','Stendete con il matterello la pasta in modo da ottenere una sfoglia di circa 2-3 mm di spessore. Con uno stampino tagliapasta ricavate dei dischi di circa 10 cm di diametro. Disponeteli sulla placca da forno asciutta, punzecchiateli con una forchetta e fateli cuocere in forno già caldo (200 gradi), fino a quando saranno leggermente dorati. Estraete la placca dal forno e lasciate raffreddare i dischi prima di toglierli dalla placca. Con lo stesso stampino tagliapasta ricavate dal prosciutto 8 dischi uguali e tritate finemente i ritagli di prosciutto. Fate rosolare in una casseruola la cipolla con metà burro e, appena sarà dorata, unite il prosciutto tritato e il prezzemolo; continuate la cottura per qualche minuto a fuoco moderato, quindi aggiungete metà della besciamella e un pizzico di pepe; controllate il sale, mescolate con cura e lasciate addensare un poco. Con questa salsa spalmate i dischi di pasta sfoglia ormai freddi in modo da formare uno strato piuttosto alto, sul quale poserete i dischi di prosciutto. Fate saltare in una casseruola, con pochissimo burro, per 45 minuti circa, gli spinaci tritati. Lasciateli intiepidire e formate delle palline di circa 3 cm di diametro che disporrete al centro di ogni medaglione di prosciutto. Aggiungete alla besciamella rimasta il tuorlo d''uovo, il parmigiano, il burro rimasto e lavorate bene con un cucchiaio di legno, quindi distribuite il composto sui medaglioni. Sistemate i medaglioni così preparati in una pirofila leggermente imburrata e fateli gratinare in forno caldo (200 gradi) fino a quando saranno leggermente dorati.',3229);
INSERT INTO "ricette" VALUES (14664,'Medaglioni Di Tacchino All''aceto Balsamico','Pollame','Tacchino',4,' -','300 G Petto Di Tacchino Macinato,
50 G Lardo,
1/2 Cipolla,
100 G Piselli,
Aceto Balsamico,
Finocchina,
Farina,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Condire la carne con sale, pepe e finocchina. Fare dei medaglioni. Rosolare la cipolla e lardo a dadini, unirvi i medaglioni infarinati e bagnare con aceto balsamico. Servire con contorno di piselli saltati con cipolla e lardo.',1969);
INSERT INTO "ricette" VALUES (14665,'Medaglioni Di Vitella Al Marsala','Carne','Vitella',4,' -','250 G Vitella,
50 G Burro,
1 Bicchiere Vino Marsala,
20 G Pepe Verde E Pepe Rosa In Grani,
Rete Di Maiale,
Sale,
Olio D''oliva Extra-vergine,
Rosmarino','Tagliare la carne a medaglioni spessi 2 cm circa. Arrotolarli nella rete di maiale e insaporire con del rosmarino, sciogliere il burro con un po'' di cipolla dorare la carne da ambo i lati e bagnare col marsala facendo un flambé. Terminare la cottura per 15 minuti circa. Aggiungendo acqua di tanto in tanto. Togliere la carne dal fuoco e tirare la salsa aggiungendo altro burro e il pepe. Servire vellutando con la salsa.',1459);
INSERT INTO "ricette" VALUES (14666,'Medaglioni Di Zia Lisa','Antipasto','Speck',4,' -','150 G Speck Tagliato A Listarelle,
8 Fette Formaggio Galbani Di 1.5 Cm Di Spessore,
Erba Cipollina','Servendovi di una padella antiaderente, lasciate rosolare lo speck tagliato a listarelle. Fate lo stesso con le fette di formaggio lasciandole rosolare da entrambi i lati e subito dopo, disponetele su un piatto piano da portata e aggiungete lo speck (che avrete tenuto in caldo). Per finire, spolverizzate il tutto con un trito di erba cipollina e servite subito. Accorgimento: prima di rosolare le fette di formaggio nella padella rovente, ungete il fondo con un filino d''olio o con della margarina, distribuendolo velocemente con un foglio di carta assorbente da cucina. Questa operazione, eviterà che le fette si colorino troppo.',684);
INSERT INTO "ricette" VALUES (14667,'Medaglioni Marinati','Carne','Vitello',4,'Luogo: Campania.','4 Medaglioni Di Vitello Da 150 G Ognuno,
2 Bicchieri Vino Bianco Secco,
2 Cucchiai Aceto Di Vino Bianco,
2 Carote,
1 Gambo Sedano,
1 Cipolla,
1 Foglia Alloro,
1 Rametto Rosmarino,
2 Chiodi Di Garofano,
30 G Burro,
Sale,
Pepe','Mondate e lavate le verdure e tagliatele a pezzetti. Raccoglietele in una terrina che possa contenere la carne di misura, unite l''alloro, il rosmarino, i chiodi di garofano e la carne, dopo averla salata e pepata. Bagnate con il vino e l''aceto e fate marinare la carne per almeno un''ora, coperta con un foglio di pellicola, rigirandola di tanto in tanto. Fate scaldare il burro in una casseruola. Rosolatevi la carne da entrambe le parti, poi versatevi il liquido e le verdure della marinata e fate cuocere a fuoco moderato per 15 minuti circa. Servite subito, con tutto o parte del fondo di cottura.',1099);
INSERT INTO "ricette" VALUES (14668,'Medaglioni Piccanti','Carne','Vitello',4,' -','4 Fettine Di Vitello,
50 G Burro,
2 Cucchiai Olio D''oliva,
4 Fettine Formaggio Fontina,
1/2 Cipolla,
1 Limone,
4 Fette Prosciutto Cotto,
Prezzemolo Tritato,
Sale,
Pepe,
50 G Farina','Rosolare la cipolla e il prezzemolo in olio e burro. Adagiarvi le fettine di vitello già infarinate e farle dorare. Salare e pepare. Disporre su ogni fetta di carne una fetta di prosciutto, una di formaggio e un po'' di prezzemolo. Aggiungere il succo di limone e mettere in forno per 10 minuti.',3271);
INSERT INTO "ricette" VALUES (14669,'Medaglioni Raffinati','Carne','Bue',4,' -','4 Fette Spesse Filetto Di Bue,
50 G Burro,
20 Cl Panna,
Cognac,
Olio D''oliva,
Sale,
Pepe In Grani','Pestate alcuni grani di pepe. Salate le fette di carne e passatele da ambedue le parti nel pepe. Mettete al fuoco una padella con il burro e poco olio; quando il burro si sarà sciolto adagiatevi i filetti e fateli rosolare da ambedue le parti mantenendo il fuoco piuttosto vivace. Non appena saranno cotti (è preferibile mantenerli leggermente al sangue), scolateli e disponeteli su un piatto che manterrete al caldo nello scaldavivande. Ponete di nuovo il recipiente con il sugo sul fuoco e scaldatelo, quindi aggiungete un bicchierino di cognac e rimescolate. Incorporate infine alla salsetta la panna liquida, portate ad ebollizione e fate ridurre un poco la salsetta. Stendete poi la salsa sui filetti e servite in tavola accompagnando con dei carciofi cucinati in questo modo: togliete a 4 carciofi le foglie dure e le punte e tagliateli a spicchi. Ponete al fuoco 50 g di burro con 50 g di prosciutto tritato insieme a una cipollina e olio; lasciate soffriggere, unite i carciofi, salateli, pepateli, bagnateli con brodo e fateli cuocere per 1 ora. A cottura ultimata unitevi una scatola di piselli da 250 g dopo averli sgocciolati dall''acqua di conservazione.',2440);
INSERT INTO "ricette" VALUES (14670,'Mediterraneo','Bevande','Whisky',1,' -','2/4 Four Roses Bourbon Whisky,
1/4 Mandarinetto Isolabella,
1/4 Succo Di Limone,
Per Guarnire:,
1 Ciliegina Rossa Al Maraschino','Agitare vigorosamente e servire nella coppetta da cocktail ben fredda. Guarnire con una ciliegina rossa al maraschino.',264);
INSERT INTO "ricette" VALUES (14671,'Mediterraneo (2)','Bevande','Gin',1,' -','1/3 Succo Di Limone,
2/3 Gin,
1 Cucchiaio Curacao Blu','Agitare delicatamente nel mixer con ghiaccio in cubetti. Servire nel calice panciuto senza decorazioni.',299);
INSERT INTO "ricette" VALUES (14672,'Mela E Banana Passata Con Il Bimby','Dessert','Mela',1,'Ricetta adatta a bambini piccoli','80 G Mela Sbucciata,
40 G Banana,
75 G Acqua,
Alcune Gocce Succo Di Limone','Inserire nel boccale la mela e la banana per 10 secondi a velocità 4. Aggiungere acqua e limone e cuocere per 5 minuti a 90 gradi a velocità 4. A fine cottura amalgamare per 20 secondi a velocità 6. Versare in tazza coprire e lasciare raffreddare.',70);
INSERT INTO "ricette" VALUES (14673,'Mela Grattugiata Con Il Bimby','Dessert','Mela',1,'Ricetta adatta a: bambini piccoli.','120 G Mela Sbucciata,
50 G Acqua,
2 Cucchiaini Succo Di Limone','Inserire nel boccale dal foro con lame in movimento a velocità 7 la mela a pezzetti. Con la spatola riunire il composto e aggiungere l''acqua e il succo di limone per 40 secondi a velocità 8. Servire subito.',57);
INSERT INTO "ricette" VALUES (14674,'Melagrana Royale','Bevande','Melagrana',1,' -','1 Melagrana (semi E Succo),
Vino Spumante Prosecco','Passate al passaverdura con il disco a fori fini i semi di una melagrana e raccogliete il succo in una ciotola. Versatene un cucchiaio in un calice unite qualche chicco di melagrana e riempite di Prosecco.',141);
INSERT INTO "ricette" VALUES (14675,'Melanzane A Funghetti','Contorno','Melanzane',4,' -','1000 G Melanzane,
Menta,
Olio D''oliva Extra-vergine,
1 Spicchio Aglio','Pulire le melanzane, tagliarle a tocchetti e soffriggerle in padella con un po'' di olio d''oliva extra-vergine e lo spicchio di aglio a fuoco lento, quindi aggiungere la menta e il sale e portare a cottura.',875);
INSERT INTO "ricette" VALUES (14676,'Melanzane A Funghetto','Contorno','Melanzane',6,' -','1500 G Melanzane,
350 G Pomodori Freschi,
4 Spicchi Aglio,
Basilico,
Sale,
Olio D''oliva','Lavate le melanzane, asciugatele con un panno e, senza sbucciarle, tagliatele in tocchetti che potrete mettere in uno scolapasta spolverizzandole con un po'' di sale. Dopo circa una mezz''ora vedrete che le melanzane avranno perduto parte della loro acqua; spremetele leggermente e friggetele poche per volta in olio abbondante a fuoco medio. Quando incominciano ad imbiondire sollevatele con la schiumarola e poggiatele su un piatto che avrete cura di poggiare in discesa, in modo che l''eccesso di olio possa colare verso il basso. Quando avrete finito, togliete l''olio dalla padella (potrete adoperarlo una seconda volta con l''aggiunta di altro olio fresco) lasciandone un cucchiaio o due, quanto basta per soffriggere l''aglio. Quando questo comincerà ad imbiondire versate in padella i pomodori spezzettati e dopo due o tre minuti le melanzane. Salate, spegnete ed aggiungete una manciata di basilico tritato.',1032);
INSERT INTO "ricette" VALUES (14677,'Melanzane Agrodolci','Contorno','Melanzane',4,'Luogo: Sicilia.','2 Melanzane,
2 Spicchi Aglio,
Alcune Foglie Menta,
1/2 Bicchiere Aceto Di Mele,
1 Cucchiaio Zucchero,
Olio D''oliva Extra-vergine,
Sale Di Trapani','Nettare e lavare le melanzane, tagliarle a cubetti, salarle e farle spurgare 1 ora. Sciacquarle, strizzarle, asciugarle e friggerle nell''olio. A parte in un padella antiaderente unta d''olio mettere 2 spicchi d''aglio, le melanzane, l''aceto e lo zucchero, facendo scaldare e glassare. Servire con foglie di menta.',862);
INSERT INTO "ricette" VALUES (14678,'Melanzane Al Cartoccio','Contorno','Melanzane',4,' -','4 Melanzane,
Sale,
Olio D''oliva,
Formaggio Grattugiato','Tagliate a fette un po'' spesse le melanzane senza sbucciarle. Ungete d''olio otto fogli di alluminio. Su ognuno disponete alcune fette di melanzana, conditele con un po'' d''olio e sale, cospargete con formaggio grattugiato. Chiudete i cartocci e cuocete in forno caldo per 20 minuti.',1235);
INSERT INTO "ricette" VALUES (14679,'Melanzane Al Formaggio','Contorno','Melanzane',4,' -','4 Melanzane,
50 G Olive Nere,
1 Ciuffo Prezzemolo,
2 Uova,
2 Panini Raffermi,
50 G Formaggio Pecorino Grattugiato,
6 Cucchiai Olio D''oliva,
Sale,
Pepe','Mettete a bagno i panini raffermi. Togliete l''estremità alle melanzane, lavatele, tagliatele a metà e cuocetele in acqua bollente salata per 10 minuti: toglietele e lasciatele asciugare. Togliete la polpa alle melanzane aiutandovi con un cucchiaio e facendo attenzione a non bucare la buccia. Tritatela assieme alle olive snocciolate e fate rosolare il trito ottenuto in un tegame con 3 cucchiai di olio. Salate, pepate ed unite i panini strizzati e sminuzzati. Togliete dal fuoco, aggiungete le uova sbattute, il pecorino, il prezzemolo tritato e mescolate accuratamente. Riempite le melanzane con il composto ottenuto, quindi sistematele in una teglia unta d''olio e cuocetele in forno preriscaldato a 200 gradi per 20 minuti. Servitele calde o tiepide.',3419);
INSERT INTO "ricette" VALUES (14680,'Melanzane Al Formaggio (2)','Contorno','Melanzane',4,' -','700 G Melanzane,
400 G Passata Di Pomodoro,
60 G Formaggio Parmigiano Reggiano Grattugiato,
250 G Mozzarella,
50 G Farina,
Olio D''oliva Extra-vergine,
Sale','Tagliare le melanzane pelate a fette di 1 cm. Metterle sotto sale mezz''ora per far uscire il liquido amaro poi asciugarle bene, infarinarle e friggere in olio bollente. Ungere una pirofila cospargerla di passata di pomodoro distendervi le melanzane scolate, uno strato di mozzarella a fettine e parmigiano. Ripetere per 2 o 3 strati fino ad esaurimento degli ingredienti. Mettere in forno a 180 gradi per 20 minuti.',1825);
INSERT INTO "ricette" VALUES (14681,'Melanzane Al Forno','Contorno','Melanzane',4,' -','4 Melanzane,
Formaggio Grana,
Farina,
Pangrattato,
1 Uovo,
Olio D''oliva,
Sale','Tagliare le melanzane a fettine e metterle a perdere l''acqua sotto sale. Passarle nella farina, nell''uovo sbattuto e nel pangrattato e friggerle in olio caldo. Adagiarle in una teglia, cospargerle con scaglie di grana, passarle in forno caldo a 200 gradi per qualche minuto per far fondere il formaggio e servire.',1991);
INSERT INTO "ricette" VALUES (14682,'Melanzane Al Forno (2)','Contorno','Melanzane',4,' -','3 Melanzane,
Sale,
Olio D''oliva,
Formaggio Grana,
2 Uova,
Pangrattato','Passare prima nella farina, poi nell''uovo e nel pangrattato, delle fettine di melanzana prima messe sotto sale a perdere l''acqua. Friggerle in olio caldo, adagiarle in una teglia, cospargerle con scaglie di grana e passarle in forno caldo a 200 gradi per qualche minuto per far fondere il formaggio.',1748);
INSERT INTO "ricette" VALUES (14683,'Melanzane Al Forno (3)','Contorno','Melanzane',4,' -','4 Melanzane Rotonde,
4 Pomodori,
2 Mozzarelle,
Aglio,
Prezzemolo,
Origano,
Olio D''oliva,
Burro,
Sale','Lavare le melanzane e tagliarle a metà, scavarle un po'' eliminando in parte la polpa interna, salare e metterle a riposare capovolte per almeno 4 ore. Tagliare la mozzarella a cubetti, condirla con l''aglio, il prezzemolo e l''origano tritati insieme a un filo d''olio; distribuire la mozzarella nell''incavo delle melanzane e coprire con i pomodori tagliati a pezzetti. Imburrare 1 teglia, disporre le melanzane e irrorare con un po'' d''olio. Coprire la teglia con un foglio di carta stagnola e mettere in forno a 180 gradi per 45 minuti.',2623);
INSERT INTO "ricette" VALUES (14684,'Melanzane Al Forno (4)','Contorno','Melanzane',4,' -','4 Melanzane Lunghe Piccole,
Aglio,
Prezzemolo,
Basilico,
Olio D''oliva Extra-vergine,
1 Pizzico Sale,
1 Pizzico Pepe Bianco','Lavare e asciugare le melanzane; accomodarle una accanto all''altra in una teglia antiaderente oliata e farle appassire in forno a 180 gradi per 45 minuti. Preparare un trito fine d''aglio e prezzemolo; unirvi 4 cucchiai d''olio e un pizzico di sale e pepe. Togliere le melanzane dal forno, tagliarle a metà e inciderne la polpa formando un reticolo. Irrorare con la salsetta preparata e rifinire col basilico sminuzzato.',912);
INSERT INTO "ricette" VALUES (14685,'Melanzane Al Forno (5)','Contorno','Melanzane',4,' -','4 Melanzane Tonde Piccole,
Aglio,
Prezzemolo,
Basilico,
Olio D''oliva Extra-vergine,
1 Pizzico Sale,
1 Pizzico Pepe Bianco','Lavare e asciugare le melanzane; accomodarle una accanto all''altra in una teglia antiaderente oliata e farle appassire in forno a 180 gradi per 45 minuti. Preparare un trito fine d''aglio e prezzemolo; unirvi 4 cucchiai d''olio e un pizzico di sale e pepe. Togliere le melanzane dal forno, tagliarle a metà e inciderne la polpa formando un reticolo. Irrorare con la salsetta preparata e rifinire col basilico sminuzzato.',912);
INSERT INTO "ricette" VALUES (14686,'Melanzane Al Forno Con Pomodoro E Pecorino','Contorno','Melanzane Lunghe',4,'Luogo: Lazio.','1000 G Melanzane Lunghe,
300 G Pomodori,
200 G Formaggio Pecorino Romano,
Olio D''oliva,
Sale,
Aglio,
Peperoncino','Tagliare le melanzane a fette di 1 cm circa e lessarle. Disporle su una teglia e aggiungere olio, sale, aglio a fettine, peperoncino e pomodoro fresco. Infornarle e quasi a fine cottura, ricoprirle di pecorino romano gatttugiato che formerà una leggera crosticina. Togliere dal forno, tagliare a dadini regolari e guarnire con scagliette dottili di pecorino.',1692);
INSERT INTO "ricette" VALUES (14687,'Melanzane Al Funghetto','Contorno','Melanzane',6,' -','1000 G Melanzane,
300 G Pomodori,
2 Spicchi Aglio,
1/2 Bicchiere Olio D''oliva,
1 Cucchiaio Prezzemolo Tritato (facoltativo),
Sale,
Pepe','Lavate con cura le melanzane, asciugatele, privatele del picciolo e riducetele prima a fette spesse 2-3 di centimetri e successivamente a cubetti. Disponete questi cubetti in un colapasta, cospargeteli con una manciatina di sale, copriteli con un piatto, su questo ponete un peso e lasciate riposare le melanzane per mezz''ora sotto pressione, in modo che perdano la loro acqua amara. Dopodichè, tamponate le melanzane con carta da cucina e ponetele in una casseruola di adeguate dimensioni nella quale avrete già fatto rosolare gli spicchi d''aglio tritati assieme all''olio. Lasciate insaporire nel soffritto per 4-5 minuti a calore moderato, mescolando senza interruzione, quindi unite i pomodori privati di pelle e semi e spezzettati e proseguite la cottura per 20 minuti circa a calore molto moderato e recipiente coperto, avendo cura di scuotere quest''ultimo di tanto in tanto per accertarvi che la preparazione non attacchi sul fondo. Evitate però si mescolare ulteriormente le melanzane perché rischierebbero di spappolarsi. Al termine, regolate di sale e cospargete le melanzane con una macinata abbondante di pepe e, a piacere, con il prezzemolo tritato. Servitele calde o tiepide.',901);
INSERT INTO "ricette" VALUES (14688,'Melanzane Al Funghetto (2)','Contorno','Melanzane',4,' -','1000 G Melanzane,
2 Spicchi Aglio,
Prezzemolo,
Sale,
Pepe,
Olio D''oliva','Tagliate le melanzane a dadini, disponetele in uno scolapasta, salate e lasciate riposare almeno due ore. Mettete un po'' d''olio d''oliva in un tegame con l''aglio, unite le melanzane e fate cuocere lentamente girando di tanto in tanto. Salate e pepate. Verso fine cottura unite un battuto di prezzemolo.',894);
INSERT INTO "ricette" VALUES (14689,'Melanzane Al Funghetto (3)','Contorno','Melanzane',6,' -','1500 G Melanzane,
350 G Pomodori Freschi,
4 Spicchi Aglio,
1 Manciata Basilico Tritato,
Sale','Tagliare le melanzane in tocchetti senza sbucciarle e metterle in un colapasta spolverizzandole con un po'' di sale. Dopo circa una mezza ora, quando le melanzane avranno perduto parte del loro liquido, premerle leggermente e friggerle poche per volta in olio abbondante a fuoco medio. Togliere le melanzane dalla padella quando cominciano ad imbiondire sollevandole con la schiumarola e poggiarle su un piatto posto un poco inclinato per far colare l''eccesso di olio verso il basso; terminata la frittura delle melanzane, lasciare nella padella solo un cucchiaio di olio e soffriggervi l''aglio, quando esso comincerà ad imbiondire aggiungere i pomodori spezzettati e, dopo due o tre minuti, le melanzane. Condire con sale, spegnere ed aggiungere una manciata di basilico tritato.',327);
INSERT INTO "ricette" VALUES (14690,'Melanzane Al Riso','Contorno','Melanzane',4,' -','200 G Riso,
4 Melanzane,
50 G Burro,
100 G Formaggio Parmigiano Grattugiato,
Prezzemolo,
Basilico,
Olio D''oliva,
Sale,
Pepe','Lessare al dente le melanzane e con un cucchiaino svuotarle di parte della polpa. Lessare il riso, condirlo con il burro, il parmigiano, il prezzemolo e il basilico tritati, il sale e il pepe. Riempire le melanzane con il riso, disporle in una teglia unta di olio, infornare per circa 10 minuti e servire.',2322);
INSERT INTO "ricette" VALUES (14691,'Melanzane Al Tegame','Contorno','Melanzane',4,' -','600 G Melanzane,
300 G Pomodori Pelati,
Olio D''oliva,
Aglio,
Sale','Lavare, spuntare e tagliare a dadini le melanzane. Porle in uno scolapasta cosparse di sale e lasciarle a perdere acqua. Sciacquarle e asciugarle. Dorare l''aglio intero nell''olio poi aggiungere le melanzane e friggerle. Unire i pomodori e cuocere a fuoco medio per 20 minuti.',865);
INSERT INTO "ricette" VALUES (14692,'Melanzane Al Verde','Contorno','Melanzane',4,' -','1000 G Melanzane,
1 Spicchio Aglio,
1 Manciata Prezzemolo,
Olio D''oliva,
Sale','Sbucciare le melanzane tagliando nel senso della lunghezza delle listarelle di buccia spesse circa 1, 5 cm e larghe 2 cm (quindi parte della polpa va scartata). Salarle e tenerle 2 ore ad asciugare. Scaldare 1/2 bicchiere di olio con l''aglio ed eliminare quest''ultimo appena prende colore. Unire il prezzemolo tritato e le melanzane asciutte, cuocere a fuoco medio per 30 minuti. Servire calde.',881);
INSERT INTO "ricette" VALUES (14693,'Melanzane Al Vino','Contorno','Melanzane',4,' -','5 Melanzane,
1 Bicchiere Vino Bianco,
1 Bicchiere Passata Di Pomodoro,
Prezzemolo,
Basilico,
Olio D''oliva,
Sale','Sbucciare le melanzane, tagliarle a dadini, salarle e lasciarle in uno scolapasta a perdere acqua. Asciugarle e cuocerle in un tegame con olio caldo, senza friggerle. Bagnarle con il vino e farlo evaporare. Aggiungere la passata di pomodoro, prezzemolo e basilico tritati, salare e cuocere a fuoco medio per 30 minuti.',1068);
INSERT INTO "ricette" VALUES (14694,'Melanzane Al Vino Bianco','Contorno','Melanzane',4,' -','4 Melanzane,
Sale,
Olio Aromatizzato Al Cerfoglio,
Vino Bianco,
1 Bicchiere Passata Di Pomodoro,
Prezzemolo,
Basilico','Sbucciare e tagliare a dadini le melanzane; salarle e lasciarle a perdere acqua. Cuocerle in 1 padella con l''olio aromatizzato al cerfoglio, spruzzarle col vino, unire la passata di pomodoro, il prezzemolo e il basilico tritati e far cuocere per 30 minuti circa.',991);
INSERT INTO "ricette" VALUES (14695,'Melanzane All''aceto','Contorno','Melanzane',4,' -','750 G Melanzane,
100 G Olio D''oliva,
2 Spicchi Aglio,
Origano,
2 Bicchieri Aceto Di Vino,
2 Bicchieri Acqua','Sbucciate e tagliate le melanzane per il lungo. Buttatele poi nell''acqua e aceto a bollore. Alzatele con la schiumarola e mettetele a scolare in uno scolapasta. Quando si saranno raffreddate, strizzatele leggermente e conditele con l''olio d''oliva, il sale e l''aglio tagliato a pezzetti e origano. Queste melanzane, se messe ben pressate in un vasetto di vetro a chiusura ermetica e ben coperte di olio si possono conservare per alcuni mesi. In questo caso sarà necessario però strizzarle bene fra le due mani.',1055);
INSERT INTO "ricette" VALUES (14696,'Melanzane All''aceto (2)','Contorno','Melanzane',6,' -','1000 G Melanzane,
40 G Burro,
8 Cucchiai Olio D''oliva,
Prezzemolo Tritato,
4 Cucchiai Aceto Di Vino','Lavare e tagliare a rondelle le melanzane. Lasciarle cuocere in una padella con il burro e l''olio per 30 minuti. Poi bagnare con l''aceto e spolverizzare di prezzemolo tritato. Servirle calde.',1927);
INSERT INTO "ricette" VALUES (14697,'Melanzane All''aceto (3)','Contorno','Melanzane',4,' -','4 Melanzane,
3 Spicchi Agli