attire leggermente le fette di tacchino e infarinarle. Fondere una noce di burro e farvi appassire la cipolla tritata. Aggiungere la carne e farla rosolare da entrambi i lati. Bagnare con il latte, abbassare il fuoco, salare e lasciar rapprendere il fondo di cottura.',2346);
INSERT INTO "ricette" VALUES (25040,'Tacchino Di Natale','Pollame','Tacchino',8,' -','1 Tacchino Di 3000 G,
1 Noce Burro,
Pancetta,
Sale,
Per Il Ripieno:,
Rigaglie Del Tacchino,
40 G Pancetta,
100 G Salsiccia,
Mollica Di Pane,
2 Mele,
250 G Castagne Lessate,
100 G Prugne Secche Snocciolate,
Burro,
Sale,
Pepe','Ricetta natalizia. Tritate insieme rigaglie, pancetta, salsiccia; unite la mollica di pane bagnata e strizzata le mele a fette sbucciate, le prugne ammorbidite in acqua tiepida, le castagne e riempitevi il tacchino; aggiungete una noce di burro intrisa di sale e pepe. Cucite l''apertura, avvolgetelo con le fette di pancetta e cuocete in forno con un po'' di burro a 220 gradi per un''ora, poi a 180 gradi ancora per un''ora e mezza circa. Bagnate ogni tanto il tacchino con il suo sugo. L''ultimo quarto d''ora togliete la pancetta e fate dorare la pelle. Vini di accompagnamento: Barbaresco DOCG, Cabreo Il Borgo VdT Di Toscana, Taurasi DOCG.',8051);
INSERT INTO "ricette" VALUES (25041,'Tacchino Di Natale (2)','Pollame','Tacchinella',8,' -','1 Tacchinella Giovane Da 2500 G,
400 G Castagne,
2 Mele,
2 Pere,
150 G Prugne Secche,
150 G Salsiccia Fresca,
120 G Lardo,
Sale,
Pepe,
Noce Moscata,
1 Bicchiere Brandy,
Burro,
Vino Bianco Secco,
Brodo','Ricetta natalizia. Aprire, pulire e fiammeggiare la tacchinella sulla fiamma del gas per bruciare gli ultimi residui di pelucchi. per il ripieno: lessare le castagne, togliere la pellicina e tritarle grossolanamente; sbucciare le pere e le mele e tagliarle a dadini; far rinvenire le prugne secche in acqua calda, snocciolarle e tagliarle a pezzetti; sbriciolare la salsiccia e affettare il lardo a fettine sottili, tagliandolo poi a dadini.',7800);
INSERT INTO "ricette" VALUES (25042,'Tacchino Farcito Al Riso','Pollame','Tacchino',6,'Preparazione: 120 minuti.','750 G Fesa Di Tacchino In Una Larga Fetta,
80 G Riso Basmati,
70 G Fagiolini,
50 G Pisellini Sgusciati,
1 Porro,
1 Bicchiere Vino Bianco Secco,
Brodo Vegetale,
1 Rametto Origano Fresco,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lessate il riso in abbondante acqua salata per 10 minuti circa, poi scolatelo. A parte, lessate anche i fagiolini, preferibilmente a vapore. Private il porro della radice, della parte verde e delle foglie esterne più dure, tritatelo finemente e rosolatelo in una padella con 4 cucchiai d''olio. Unite i pisellini e cuoceteli per un paio di minuti. Aggiungete poi il riso, regolate di sale, pepate a piacere e lasciate insaporire per qualche istante. Stendete la fetta di fesa su un tagliere, salatela, pepatela e distribuitevi sopra il riso e i fagiolini, quindi arrotolatela, fermandola con del filo da cucina.Rosolare il rotolo in 4 cucchiai d''olio, poi bagnatelo con il vino, che lascerete evaporare. Cuocete quindi per un''ora e 30 minuti, bagnando spesso con del brodo caldo. A fine cottura, lasciate raffreddare, affettatela, profumatela con l''origano tritata e servite.',2291);
INSERT INTO "ricette" VALUES (25043,'Tacchino Farcito Alle Pere','Pollame','Tacchino',4,' -','4 Fette Fesa Di Tacchino,
30 G Burro,
2 Pere,
2 Cl Brandy,
15 Cl Vino Bianco Secco,
Farina,
Formaggio Parmigiano Reggiano,
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Noce Moscata','Sbucciate le pere, eliminate i torsoli e tagliatele ciascuna in 4 spicchi. Spolverizzatele di parmigiano e profumatele con noce moscata; salate e lasciate riposare per circa 10 minuti. Allargate le fette di tacchino col batticarne e tagliatele in due ottenendo 8 fettine. Al centro di ognuna disponete 1 spicchio di pera, avvolgete e chiudete con spago da cucina. Salate gli involtini, infarinateli e rosolateli in una casseruola in cui avrete scaldato il burro con 4 cucchiai di olio. Fate dorare bene da tutte le parti, quindi bagnate con il vino e lasciate evaporare; sfumate con il brandy e lasciate evaporare anch''esso. Ritirate la casseruola dal fuoco, incoperchiatela e lasciate riposare la preparazione per 5 minuti prima di servire.',2564);
INSERT INTO "ricette" VALUES (25044,'Tacchino Impanato Verde','Pollame','Tacchino',4,' -','600 G Petto Di Tacchino,
Abbondante Prezzemolo,
Pochissimo Aglio,
2 Uova,
2 Uova Sode,
Pangrattato,
Acciughe Sott''olio,
Abbondante Olio Per Friggere,
Sale','Sbattete 2 uova con un po'' di sale. Immergete una alla volta le fette di tacchino. A parte preparate un trito molto fine e abbondante di prezzemolo e pochissimo aglio che unirete al pangrattato. Impanate la carne. Friggetela in abbondante olio, sistematela su di una carta assorbente per assorbire l''unto in eccesso e servitela tiepida decorate da fettine di uova sode con 1 acciuga arrotolata.',2662);
INSERT INTO "ricette" VALUES (25045,'Tacchino In Bianco','Pollame','Tacchino',4,' -','500 G Fesa Di Tacchino,
1 Cipolla,
Farina,
80 G Burro,
1 Bicchiere Vino Bianco,
1 Bicchiere Latte,
Sale,
Pepe','Tagliare la fesa di tacchino a striscioline sottili, passarle nella farina. Far fondere il burro in una padella con la cipolla tritata e, quando sarà appassita, versare nel recipiente le striscioline di tacchino, facendole rosolare un po''. Spruzzarle col vino e farlo evaporare. Bagnare la carne con 1 bicchiere di latte, salare, pepare e far cuocere fino a quando il latte si sarà assorbito, formando una salsetta densa e cremosa.',1864);
INSERT INTO "ricette" VALUES (25046,'Tacchino In Salsa','Pollame','Tacchino',4,' -','8 Fettine Fesa Di Tacchino,
1 Cipollina,
200 G Passato Di Pomodoro,
Olio D''oliva,
Sale,
Farina','Affettare al velo la cipolla e farla appassire in poco olio in una padella antiaderente. Versare la passata nella padella e farla leggermente ritirare. Unire le fette di tacchino precedentemente infarinate, aggiustare di sale e cuocere per circa 10 minuti.',1664);
INSERT INTO "ricette" VALUES (25047,'Tacchino In Salsa Rosa','Pollame','Tacchino',4,' -','2 Cucchiai Olio D''oliva,
500 G Fettine Di Petto Di Pollo,
1/2 Cucchiaio Farina,
1 Cucchiaio Ketchup,
1 Cucchiaino Salsa Worcester,
Sale,
20 G Burro','Dorare nell''olio le fette di tacchino. Mescolare alla farina 1/2 bicchiere di acqua fredda e versarla sul tacchino assieme alle salse tomato ketchup e salsa Worcester. Salare, alzare la fiamma poi abbassarla e cuocere per qualche minuto. Togliere la carne, unire il burro al fondo di cottura e poi versare il sugo sulla carne nel piatto di portata.',1094);
INSERT INTO "ricette" VALUES (25048,'Tacchino Primavera','Pollame','Tacchino',4,' -','600 G Petto Di Tacchino,
1 Cuore Sedano Bianco,
2 Zucchine,
2 Carote,
1 Cipolla,
Olio D''oliva,
Farina,
Sale','Tagliate il petto di tacchino a dadi. Pulite il sedano, le carote e le zucchine e tagliatele a rondelle. Preparate un soffritto con la cipolla affettata sottile. Aggiungete le verdure, fatele rosolare un attimo, aggiungete anche il tacchino leggermente infarinato. Salate, pepate, bagnate col vino bianco e fate cuocere a fuoco moderato per circa 20 minuti.',1958);
INSERT INTO "ricette" VALUES (25049,'Tacchino Ripieno','Pollame','Tacchino',8,' -','1 Tacchino Piccolo (da 4000 G),
350 G Salsiccia,
120 G Pane Integrale,
1/2 Cipolla,
1 Bicchierino Vino Marsala Secco,
3 Cucchiai Farina,
Sale,
Pepe,
3 Cucchiai Prezzemolo Tritato,
1 Bicchiere Panna,
1/2 Bicchiere Brodo,
200 G Burro','Fate rosolare la salsiccia, spellata e sminuzzata, in un tegame con una noce di burro, a fuoco dolce fino a quando sarà ben dorata, dopodichè trasferitela in una terrina e unitevi 100 g di burro fuso. Aggiungete anche il pane integrale, privato della crosta e sbriciolato, il sale necessario, una macinata di pepe e il prezzemolo tritato. Bagnate il tutto con un bicchierino di Marsala secco e mescolate con cura fino ad ottenere un composto omogeneo, infine incorporatevi un poco di panna. Pulite il tacchino, lavatelo sotto l''acqua corrente e asciugatelo con della carta assorbente da cucina, quindi strofinatelo dentro e fuori con sale e pepe. Inserite nella cavità addominale del volatile il ripieno preparato, poi chiudete l''apertura cucendola con ago e filo da cucina. Trasferite il tacchino in una teglia unta di burro, salatelo ancora un poco e fatelo cuocere nel forno preriscaldato (200 gradi) per due ore, bagnandolo spesso con il suo fondo di cottura. A metà cottura, ponete nella teglia mezza cipolla pulita e tagliata a fettine sottili. Mezz''ora prima del termine, mettete in una casseruolina tre cucchiai del fondo di cottura, tre di farina e mezzo bicchiere di brodo. Portate ad ebollizione a calore moderato, mescolando sempre con una frusta, unite il resto della panna, regolate di sale e pepe e lasciate addensare, dopodichè togliete dal fuoco. Servite la salsa così preparata insieme al tacchino.',8942);
INSERT INTO "ricette" VALUES (25050,'Tacchino Ripieno (2)','Pollame','Tacchino',4,'Luogo: Abruzzo.','1 Tacchino Disossato,
450 G Salsiccia,
400 G Castagne,
200 G Carne Macinata,
1 Uovo,
Sedano,
Cipolla,
Carote,
Aglio,
Rosmarino,
Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Lavare e asciugare il tacchino. Lessare le castagne,sbucciarle e tritarle. Preparare il ripieno mescolando alle castagne il macinato, la salsiccia sbriciolata, l''uovo,sale e pepe. Amalgamare bene e farcire il tacchino. Richiuderlo bene con filo da cucina. Tritare le verdure e farle soffriggere in una teglia con abbondante olio quindi unire il tacchino e infornare a 180 gradi finché non sarà ben dorato. A fine cottura bagnare col vino, rimettere in forno pochi minuti per completare la cottura. Servire caldo.',3522);
INSERT INTO "ricette" VALUES (25051,'Tacchino Ripieno Alla Frutta','Pollame','Tacchino',8,' -','1 Tacchino Di 3000 G,
300 G Castagne,
300 G Prugne Secche,
300 G Mele,
100 G Gherigli Di Noci,
100 G Pancetta Magra,
50 G Burro,
Latte,
2 Bicchierini Brandy,
Salvia,
Rosmarino,
Sale,
Pepe','Mettete le prugne in acqua tiepida per farle rinvenire. Togliete la buccia alle castagne, mettetele a bollire per 10 minuti in acqua salata, scolatele, spellatele e trasferitele in una casseruola dove termineranno di cuocere coperte di latte. Quando le castagne avranno assorbito tutto il liquido, unite le prugne sgocciolate, le mele tagliate a fettine, i gherigli di noci ben mondati e tritati; mescolate il composto e aggiungete la pancetta tagliata grossolanamente. Mescolate ancora e bagnate l''impasto ottenuto con il brandy. Introducete il ripieno nel tacchino (che avrete prima ben pulito e preparato per la cottura), cucite l''apertura e accomodate il tacchino in una casseruola larga, versatevi sopra il burro fuso, aggiungete gli aromi, salate e pepate. Ponete in forno caldo a 180 gradi per 3 ore circa, bagnandolo spesso durante la cottura con il suo sugo.',7301);
INSERT INTO "ricette" VALUES (25052,'Tacchino Ripieno Con Patatine','Pollame','Tacchino',8,' -','1 Tacchino Pronto Per La Cottura Da 5000 G,
2 Cipolle,
120 G Burro,
1 Foglia Alloro,
1 Spicchio Aglio,
100 G Polpa Di Maiale Tritata,
75 G Pangrattato,
1/2 Limone,
1 Uovo,
1 Cucchiaio Salvia Tritata,
1 Mazzetto Crescione,
2000 G Patatine Novelle,
Sale,
Pepe','Private il tacchino delle regaglie, ponetele in una casseruola con una cipolla, sbucciata e divisa in quattro, l''alloro e tant''acqua quanta ne occorre per coprire il tutto e portate ad ebollizione a calore moderato. A questo punto chiudete il recipiente e lasciate sobbollire per 1 ora. Fate fondere dolcemente in una padella 40 g di burro e soffriggetevi la seconda cipolla tritata finemente, a calore moderato, fino a quando sarà leggermente dorata, dopodichè trasferitela in una capace terrina. Quando le regaglie sono pronte scolatele, conservando il brodo, e unitele al soffritto di cipolla. Aggiungete anche l''aglio tritato, la carne, il pangrattato, la salvia, la scorza grattugiata e il succo di mezzo limone e mescolate il tutto fino ad ottenere un composto omogeneo. Infine incorporatevi l''uovo sbattuto e insaporite con sale e pepe. Farcite il tacchino con il composto preparato, fermate con uno stecchino di legno il lembo di pelle del collo e della cavità addominale per evitare che il ripieno fuoriesca durante la cottura, quindi ponete il volatile in una teglia che lo contenga agevolmente. Bagnatelo col resto del burro, fuso, cospargetelo con sale e pepe e fatelo cuocere nel forno preriscaldato (180 gradi) per 3 ore e 15 minuti. Quando il tacchino sarà ben dorato, copritelo con un foglio di carta stagnola affinché non scurisca troppo; di tanto in tanto bagnatelo con il suo fondo di cottura. Quando mancano 1 ora e 30 minuti al termine della cottura, mettete nella teglia anche le patatine sbucciate. Alla fine togliete il tacchino dal forno, lasciatelo riposare per 10-15 minuti, quindi trasferitelo su un piatto di portata e contornatelo con le patatine. Guarnite con il mazzetto di crescione e servite ben caldo, insieme a gelatina di mirtilli, carotine novelle, cavolini alle mandorle e una salsina preparata mescolando il fondo di cottura della carne con un mestolo di brodo delle regaglie.',10393);
INSERT INTO "ricette" VALUES (25053,'Tacchino Ripieno Di Castagne','Pollame','Tacchino',8,' -','1 Tacchino Di 3000 G,
250 G Castagne Sbucciate,
150 G Olive Verdi Snocciolate,
300 G Salsiccia,
100 G Pancetta,
Olio D''oliva,
Sale,
Pepe,
Per Servire:,
Alcune Foglie Insalata Lattuga Cappuccio','Lessate le castagne sbucciate. Quando sono cotte, togliete la pellicina e schiacciatele. Unite il composto alla salsiccia sminuzzata e alle olive verdi tritate. Salate e pepate. Amalgamate bene il tutto e farcite con questo impasto il tacchino. Cucite l''apertura. Ricoprite il petto con le fette di pancetta e fermatele con diversi giri di spago bianco da cucina. Salate e pepate. Spennellate d''olio un tegame, ad agiatevi il tacchino e ponete in forno preriscaldato a 180 gradi per un''ora e mezzo. Controllate la cottura e bagnatelo di tanto in tanto con il suo sugo. Dopo questo tempo togliete le fette di pancetta e tenete il tacchino in forno ancora mezz''ora in modo che la carne colorisca bene. Sistemate il tacchino sul piatto da portata e contornatelo con larghe foglie di lattuga cappuccio. Vini di accompagnamento: Nebbiolo D''Alba DOC, Grave Del Friuli Cabernet DOC, Rosso Conero Riserva DOC.',7230);
INSERT INTO "ricette" VALUES (25054,'Tacchino Ripieno Di Castagne (2)','Pollame','Tacchino',8,' -','1 Tacchino,
400 G Castagne Lesse,
2 Cucchiai Burro,
3 Cucchiai Panna Da Cucina,
Pangrattato,
Sale,
Pepe','Ridurre la metà delle castagne in purè, aggiungerci 2 cucchiai di burro, la panna, il sale e il pepe. Intanto in un tegame sciogliete un cucchiaino di burro e rosolateci il cuore e il fegato del tacchino tritati, aggiungendo 1 cucchiaio di pangrattato. Unite questo composto al purè di castagne precedentemente preparato e farciteci il tacchino; cucitelo e arrostitelo aggiungendo intorno dell''altro burro. Servite guarnendo con l''altra metà di castagne che avrete lasciato intere.',6186);
INSERT INTO "ricette" VALUES (25055,'Tacchino Ripieno Di Cavolini Di Bruxelles','Pollame','Tacchino',8,' -','1 Tacchino Di 3000 G,
300 G Cavolini Di Bruxelles,
250 G Prosciutto Cotto,
100 G Lardo A Fettine,
Olio D''oliva,
Sale,
Pepe','Mondate i cavolini di Bruxelles, pareggiateli alla base e incideteli con un taglietto. Tuffateli in abbondante acqua salata a bollore e lessateli per circa 15 minuti a pentola scoperta. Quando sono cotti, sgocciolateli e divideteli a metà. Raccoglieteli in una terrina, unitevi il prosciutto cotto tritato, salate e pepate. Amalgamate e farcite con il composto il tacchino. Cucite l''apertura. Ricoprite il petto con il lardo che deve essere tagliato a fettine molto sottili, fermatele con diversi giri di spago bianco da cucina. Salate e pepate. Spennellate un tegame con abbondante olio, adagiatevi il tacchino e cuocete in forno preriscaldato a 180 gradi per un''ora e mezzo. Controllate la cottura e bagnatelo di tanto in tanto con il suo sugo. Quando manca mezz''ora alla fine togliete le fette di lardo e cuocete ancora in forno per 30 minuti in modo che la carne assuma un colore uniformemente dorato. Ritirate e lasciate riposare 10 minuti. Sistemate il tacchino sul piatto da portata caldo e servitelo con un contorno di patate. Vini di accompagnamento: Trento Cabernet DOC, Chianti Classico DOCG, Solopaca Rosso Superiore DOC.',7096);
INSERT INTO "ricette" VALUES (25056,'Tacchino Saporito','Pollame','Tacchino',4,' -','500 G Fesa Di Tacchino,
1 Cipolla,
1 Carota,
1 Costa Sedano,
Prezzemolo,
Basilico,
Pancetta,
1 Bicchiere Vino Rosso,
1 Cucchiaio Concentrato Di Pomodoro,
4 Cucchiai Olio D''oliva,
2 Mestoli Brodo,
Sale,
Pepe','Far rosolare un trito di pancetta, sedano, carota, cipolla, prezzemolo e basilico nell''olio, unire la fesa di tacchino tagliata a listarelle, bagnare con il vino, aggiungere il concentrato di pomodoro diluito con il brodo, salare, pepare, far cuocere per circa 20 minuti e servire.',2916);
INSERT INTO "ricette" VALUES (25057,'Tacchino Saporito (2)','Pollame','Tacchino',4,' -','4 Fette Fesa Di Tacchino,
4 Cucchiai Formaggio Emmenthal Grattugiato,
20 G Burro,
Vino Bianco,
1/2 Bicchiere Brodo,
Sale','Rosolare nel burro le fette di tacchino. Bagnarle col vino e lasciarlo evaporare poi aggiungere 1/2 bicchiere di brodo, sale, pepe e cuocere coperto, a fuoco basso, per circa 6-7 minuti. Distribuire il formaggio sulla carne, coprire il tegame, spegnere il fuoco e far riposare per 5 minuti prima di servire.',1163);
INSERT INTO "ricette" VALUES (25058,'Tacchino Saporito (3)','Pollame','Tacchino',4,' -','500 G Fesa Di Tacchino,
Sedano,
Carota,
Cipolla,
Prezzemolo,
Basilico,
Pancetta,
4 Cucchiai Olio D''oliva,
Vino Rosso,
1 Cucchiaio Concentrato Di Pomodoro,
2 Mestoli Brodo,
Sale,
Pepe','Tritare sedano, carota, cipolla, prezzemolo, basilico e pancetta e far insaporire tutto con 4 cucchiai di olio. Unire il tacchino a listarelle, far dorare, spruzzare di vino rosso, unire il concentrato di pomodoro diluito con il brodo, salare, pepare e cuocere per circa 20 minuti.',2891);
INSERT INTO "ricette" VALUES (25059,'Taccole Al Bettelmatt','Contorno','Taccole',4,' -','500 G Taccole,
100 G Formaggio Bettelmatt,
1 Scalogno,
1/2 Limone,
Olio D''oliva Extra-vergine,
Cerfoglio Fresco,
Sale,
1 Macinata Pepe','Mondare le taccole e lessarle a vapore. Tagliare a scaglie il formaggio e preparare una emulsione di olio, succo di limone, sale. Disporre le taccole in una insalatiera; cospargerle di scalogno finemente affettato e scaglie di formaggio. Irrorare con l''emulsione preparata, mescolare e rifinire con una macinata di pepe e cerfoglio.',1166);
INSERT INTO "ricette" VALUES (25060,'Taccole Alla Casalinga','Contorno','Taccole',6,' -','1000 G Taccole,
200 G Pomodori,
50 G Cipolla,
2 Spicchi Aglio,
Alcune Foglie Basilico,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Mondate le taccole e lessatele in acqua salata. Scolatele al dente. In un tegame lasciate appassire la cipolla tagliata a fettine sottili in quattro cucchiai d''olio. Aggiungete l''aglio sbucciato intero, le taccole e fate insaporire a fuoco alto per 5 minuti. Eliminate l''aglio, unite i pomodori spellati, privati dei semi e tagliati a cubetti, salate e pepate. Lasciate cuocere per 10-15 minuti. Regolate il sale. Passate sul piatto da portata. Prima di servire cospargete le taccole con foglie di basilico.',2033);
INSERT INTO "ricette" VALUES (25061,'Taccole Alla Greca','Contorno','Taccole',4,'Luogo: Grecia. Preparazione: 15 minuti. Cottura: 40 minuti.','500 G Taccole,
1 Cipolla,
4 Cucchiai Olio D''oliva,
4 Cucchiai Vino Bianco Secco,
1 Gambo Sedano,
6 Rametti Prezzemolo,
1 Foglia Alloro,
1/4 Cucchiaino Timo Secco,
6 Grani Pepe Nero,
6 Grani Di Coriandolo,
1/4 Cucchiaino Sale','Mondate e pelate la cipolla. Lavate il sedano. Pestate il pepe e il coriandolo. Mettete in una pentola cipolla, sedano, pepe, coriandolo, sale, prezzemolo, alloro e timo. Versate sopra l''olio, il vino bianco e quattro decilitri di acqua. Portate a ebollizione, coprite e fate cuocere a fuoco lento per quindici minuti. Mondate le taccole. Lavatele e tagliatele a pezzetti di 2,5 cm. Dopo quindici minuti di cottura, mettete le taccole nella pentola, mescolate. Fate riprendere l''ebollizione, coprite e lasciate ancora sobbollire per dieci minuti fino a quando le taccole non sono diventate tenere. Con una schiumarola togliete dalla pentola le taccole e la cipolla. Mettetele su un piatto e copritelo. Fate bollire a fuoco vivo il liquido di cottura fino a ottenere 15 cl. Versatelo sulle taccole e fate raffreddare. Mettete il piatto in frigorifero e fate marinare per almeno due ore. Potete preparare questo piatto 48 ore prima e tenerlo in frigorifero.',1722);
INSERT INTO "ricette" VALUES (25062,'Taccole In Padella','Contorno','Taccole',4,' -','700 G Taccole (legumi),
Alcune Foglie Basilico,
1 Spicchio Aglio,
30 G Burro,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Lessare le taccole in acqua bollente salata per circa 7 minuti. Tritare il basilico e l''aglio e farli appassire in olio e burro a fuoco dolce. Aggiungere le taccole, mescolare e togliere dal fuoco. Servire subito. Le taccole non sono solo uccelli... invece sono anche delle specie di piselli che si mangiano con il baccello.',710);
INSERT INTO "ricette" VALUES (25063,'Taccole In Padella (2)','Contorno','Taccole',4,' -','700 G Taccole,
Alcune Foglie Basilico,
1 Spicchio Aglio,
30 G Burro,
2 Cucchiai Olio D''oliva,
Sale','Pulire le taccole e lessarle in acqua salata per 7 minuti. Scolarle e metterle in una terrina. Tritare l''aglio e il basilico e farli appassire nell''olio e nel burro a fuoco dolce. Aggiungere le taccole, mescolarle e toglierle dal fuoco. Servire calde.',1059);
INSERT INTO "ricette" VALUES (25064,'Taccole In Padella (3)','Contorno','Taccole',4,' -','700 G Taccole,
Alcune Foglie Basilico,
1 Spicchio Aglio,
30 G Burro,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Lessare le taccole in acqua bollente salata per circa 7 minuti. Tritare il basilico e l''aglio e farli appassire in olio e burro a fuoco dolce. Aggiungere le taccole, mescolare e togliere dal fuoco. Servire subito.',1060);
INSERT INTO "ricette" VALUES (25065,'Taccole In Padella (4)','Contorno','Taccole',4,' -','400 G Taccole,
1 Cipollotto Novello,
Brodo Vegetale,
100 G Lardo Di Maiale,
Pochissimo Olio D''oliva Extra-vergine,
Maggiorana,
Mentuccia,
Sale,
Pepe','Spuntare le taccole, eliminare i filamenti e lavarle. Scottarle appena in brodo bollente e passarle immediatamente sotto l''acqua fredda. Brasare la cipolla finemente affettata con pochissimo olio; unire le taccole, la maggiorana e far insaporire a fuoco vivo per 2 minuti. Salare e pepare. Accomodarle nei piatti e ricoprirle con fettine di lardo croccanti saltate in padella e mentuccia fresca.',1353);
INSERT INTO "ricette" VALUES (25066,'Taco Salad Dip','Antipasto','Avocado',4,' -','3 Avocado Maturi,
2 Cucchiai Succo Di Limone,
1/2 Cucchiaino Sale,
1/4 Cucchiaino Pepe,
1 Tazza Panna,
1/2 Tazza Maionese,
500 G Fagioli Precotti,
1 Peperone,
Cipolle Verdi,
3 Pomodori,
2 Olive Snocciolate Mature,
200 G Formaggio Cheddar,
Alcune Fette Focaccia Di Granturco (o Di Grano)','In un piatto mischiare gli avocado con il succo di limone, il sale e il pepe. In altro piatto unire maionese e panna. Infine in un terzo piatto più largo unire i fagioli e il peperone tagliato in pezzetti. Metterci sopra la mistura di avocado. Più sopra mettere uno strato con la mistura di panna. Spruzzare con cipolle tagliate, pomodori e olive. Coprire con il formaggio spezzettato; servire far raffreddare con patatine.',2908);
INSERT INTO "ricette" VALUES (25067,'Tacos Con Carne','Antipasto','Carne Di Manzo',4,'Luogo: Messico.','450 G Manzo Macinato,
1 Cipolla Tritata,
1 Spicchio Aglio,
1 Cucchiaio Peperoncino In Polvere,
3/4 Cucchiaio Sale,
2 Pomodori Tagliati E Strizzati,
Alcune Foglie Insalata Lattuga,
1 Tazza Formaggio Caciotta A Pezzi,
Salsa Di Chili,
12 Tortillas','Cuocere la carne con olio, aglio e cipolla fino a che non diventa scura. Eliminare il grasso e insaporire con sale e peperoncino. Riempire ogni tortillas con la carne, il pomodoro, il formaggio e la lattuga. Ripiegare e condire con salsa chili. Se le tortillas sono fredde, si possono rendere soffici scaldandole per 10 secondi in 2 cucchiai di olio bollente.',3343);
INSERT INTO "ricette" VALUES (25068,'Tacos De Queso','Antipasto','Formaggio Caciotta',4,'Luogo: Messico.','1 Cipolla Tritata,
Olio D''oliva Extra-vergine,
450 G Pomodori Pelati,
120 G Peperoncino Verde Privato Dei Semi E Tritato,
1 Cucchiaino Origano Secco Pestato,
12 Tortillas,
250 G Formaggio Caciotta,
1 Tazza Panna Acida','Soffriggere la cipolla in 2 cucchiai d''olio fino a farla intenerire. Unire i pomodori pelati, i peperoncini e l''origano. Cuocere lentamente per 20 minuti fino a che il sugo si addensa. In un padellino profondo immergere ogni tortilla in 2 cucchiai d''olio bollente per 10 secondi. Asciugare in carta assorbente. Tagliare il formaggio in 12 strisce. Mettere una striscia di formaggio e 2 cucchiai di salsa al centro di ogni tortilla, chiudere bene i bordi. Sistemare su un piano di cottura, coprire con carta d''alluminio. Cuocere in forno a 180 gradi per 7-10 minuti. Scoprire e cuocere ancora 3-4 minuti. Riaprite le tortillas, aggiungere la panna acida e arrotolare.',3840);
INSERT INTO "ricette" VALUES (25069,'Tadà','Bevande','Grappa Alla Menta',1,' -','3 Cucchiai Grappa Alla Menta,
1 Cucchiaio Curacao Blu','Versate i due ingredienti direttamente nel tumbler medio (in questo caso potete usare anche un bicchiere a calice o una coppetta) e mescolate. Servite a temperatura ambiente, senza aggiunta di ghiaccio.',362);
INSERT INTO "ricette" VALUES (25070,'Tagliarini E Fagioli','Primo','Fagioli',6,'Luogo: Colfelice. Luogo: Arce. Luogo: Ciociaria. Luogo: Lazio.','1000 G Farina Bianca,
5 Cucchiai Conserva Di Pomodoro,
250 G Fagioli,
300 G Cotechino,
100 G Strutto,
2 Spicchi Aglio,
Sale','Mettere a cuocere i fagioli con cotechino. Nel frattempo impastare la farina solo con l''acqua, stenderla e tagliarla a quadrucci. Preparare un sughetto finto con aglio, strutto e conserva di pomodoro sciolta in acqua calda. Quando i fagioli sono cotti, aggiungere il sughetto finto e la pasta, portando a termine la cottura.',5311);
INSERT INTO "ricette" VALUES (25071,'Tagliata Dell''orto','Carne','Vitello',2,'Preparazione: 15 minuti. Cottura: 30 minuti. Calorie: 319.','200 G Fettine Di Magatello,
1 Zucchina,
1 Peperone Giallo,
1 Cipollotto,
20 G Burro,
Salsa Worcester,
Erba Cipollina,
Sale,
Pepe','Mondate il peperone dei semi e delle coste bianche interne, tagliatelo a listerelle. Spuntate la zucchina, lavatela e tagliatela a rondelle. Tritate finemente il cipollotto e soffriggetelo nel burro: quando sarà trasparente, unite la zucchina e il peperone. Salate, pepate e cuocete a fuoco medio per circa 15 minuti, finché le verdure saranno tenere. Disponete in una pirofila le fettine di carne, leggermente accavallate; spolveratele di sale e pepe e spruzzatele di salsa worcester. Ricopritele con le verdure e spolverate di erba cipollina tritata. Cuocete la preparazione in forno caldo a 200 gradi per 10 minuti.',517);
INSERT INTO "ricette" VALUES (25072,'Tagliata Di Filetto Di Maiale All''erbe Con Dadolata Di Rape Rosse','Carne','Maiale',4,' -','500 G Filetto Di Maiale,
1/2 Rapa Rossa,
1 Mazzetto Erbe Aromatiche,
1 Spicchio Aglio,
1 Filo Olio D''oliva Extra-vergine,
Sale,
Pepe','Passare il filetto in un trito di erbe aromatiche e poi cuocerlo in una padella antiaderente con un filo di olio e 1 spicchio di aglio. Tagliare il filetto e poi metterlo per 5 minuti nel forno a 200 gradi. Tagliare a dadini la rapa, condirla con olio, sale e pepe ed adagiarla accanto al filetto.',1817);
INSERT INTO "ricette" VALUES (25073,'Tagliata Di Manzo','Carne','Manzo',4,' -','2 Filetti Di Manzo Da 300 G Ognuno,
Olio D''oliva,
1 Rametto Rosmarino,
Sale,
Pepe','Cospargere la carne con pepe macinato fresco e spennellarla di olio. Lasciarla riposare per 30 minuti. Scaldare bene la griglia e adagiarvi i filetti tenendo inizialmente alta la fiamma. Rigirarli e abbassare il fuoco. Spennellarli con il rametto di rosmarino intriso d''olio. Salare i filetti a fine cottura e portarli in tavola su un tagliere. Affettarli al momento di servire.',1403);
INSERT INTO "ricette" VALUES (25074,'Tagliata Di Manzo Al Ginepro E Salsa Di Vino Rosso','Carne','Manzo',4,' -','200 G Controfiletto Di Manzo,
10 Bacche Di Ginepro,
1 Bicchiere Vino Rosso,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Schiacciare le bacche di ginepro ed insaporire la carne. Rosolare a fuoco vivo, salare e pepare. Adagiare in una pirofila ed infornare per 10 minuti. Intanto nella padella della carne versare il vino e ridurre. Levare la carne dal forno e farla riposare per 5 minuti. Tagliarla a fette sottili e disporla sul piatto con sopra la salsa al vino.',1072);
INSERT INTO "ricette" VALUES (25075,'Tagliata Di Manzo Con Mele Essiccate E Sformatino Di Barba Di Frate','Carne','Manzo',4,' -','1 Bistecca Di Entrecote Di Manzo,
3 Fettine Mele Essiccate,
3 Falde Sedano,
100 G Barba Di Frate,
1 Spicchio Aglio,
1 Tuorlo D''uovo,
50 G Formaggio Grana,
Pangrattato,
Burro,
Olio D''oliva,
Sale Grosso,
Sale,
Pepe','Grigliare la carne e tagliarla, quindi alternare alle fette di carne la costa del sedano sbianchita e le fettine di mele essiccate. Servire con sale grosso e pepe macinati freschi. Nel frattempo sbollentare gli agretti e ripassarli in padella con olio, aglio e sale; lavorarvi un tuorlo, il grana grattugiato ed il pangrattato e trasferire il composto all''interno di uno stampino imburrato e cosparso di pangrattato; cuocerlo al forno per 10 minuti a 180 gradi.',2276);
INSERT INTO "ricette" VALUES (25076,'Tagliata Di Manzo Con Verdure Alla Griglia','Carne','Manzo',6,'Preparazione: 30 minuti.','1 Fetta Costata Di Manzo Spessa Di 4 Cm (500 G),
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe,
1 Melanzana,
1 Zucchina,
1 Peperone Di Voghera,
Alcuni Pomodorini,
Per La Salsa Vinaigrette Alle Erbe:,
5 Cucchiai Olio D''oliva Extra-vergine,
2 Cucchiai Aceto Di Vino,
1 Spicchio Aglio,
1 Rametto Rosmarino,
1 Mazzetto Prezzemolo,
Sale,
Pepe','Preparare la salsa vinaigrette alle erbe: mescolare in una ciotola l''aceto, il sale e il pepe finché il sale sarà completamente sciolto; aggiungere l''olio e battere leggermente con una forchetta; aggiungere infine lo spicchio d''aglio sbucciato e leggermente schiacciato, il prezzemolo e il rosmarino tritati. Spennellare d''olio la carne, adagiarla nella padella grigliante (oppure in una padella antiaderente) ben calda e farla cuocere per 5-6 minuti; rigirarla e farla cuocere anche dall''altra parte per lo stesso tempo, abbassando il fuoco dopo 2 minuti; salarla e peparla. Togliere la carne, adagiarla in una terrina, irrorarla con un poco di vinaigrette alle erbe e farla riposare, per qualche minuto, coperta. Tagliare la carne in sbieco, a fette sottili, adagiarla sul piano di portata, irrorarla con la salsa rimasta nella terrina, servirla accompagnata con verdure alla griglia. Nel frattempo preparare le verdure alla griglia: spuntare la melanzana e la zucchina, lavarle e tagliarle a fette, privare il peperone dei semi e dei fili bianchi interni, lavarlo e dividerlo a falde e lavare i pomodorini. Far scaldare la padella grigliante, adagiarvi le verdure e farle grigliare per qualche minuto da una parte e dall''altra; distribuire le verdure sul piatto di portata e irrorarle con la salsa alle erbe rimasta.',1197);
INSERT INTO "ricette" VALUES (25077,'Tagliata Di Salmone','Antipasto','Filetto Di Salmone',4,'Preparazione: 15 minuti. Cottura: 30 minuti.','600 G Filetto Di Salmone,
2 Limoni,
Alcuni Rametti Finocchietto Selvatico,
100 G Panna Acida,
Olio D''oliva,
Sale,
Pepe','Sistemate il filetto di salmone in una pirofila, salatelo, pepatelo e irroratelo con il succo di un limone e mezzo. Cospargetelo con la metà del finocchietto tritato e con la scorza di mezzo limone tagliata a filettini sottili. Coprite la preparazione con della pellicola da cucina e mettete la pirofila in frigorifero fino al giorno seguente. Togliete la pirofila dal frigorifero un''ora prima di servire. Scolate bene il salmone dalla marinata, appoggiatelo sulla placca del forno foderata con della carta apposita unta di olio e cuocetelo a 250 gradi per 5 minuti. Sfornate il salmone, tagliatelo a fette sottili e sistematelo su un piatto di portata. Cospargetelo con il finocchietto tritato che avete tenuto da parte e servite con la panna acida.',1863);
INSERT INTO "ricette" VALUES (25078,'Tagliata Di Vitello Ai Semi Di Papavero, Sesamo, Scalogno E Spinaci','Carne','Vitella',4,' -','250 G Filetto Di Vitella,
2 Cucchiaini Senape,
1 Scalogno,
1 Bicchiere Panna,
1 Bicchiere Aceto Di Vino,
300 G Spinaci,
1 Cucchiaino Pinoli,
1 Cucchiaino Uvetta Sultanina,
Sale,
Semi Di Papavero,
Semi Di Sesamo,
Olio D''oliva','Rosolare la carne e spalmarla con la senape. Infornare per 10 minuti e scaloppare. Ridurre l''aceto con lo scalogno, aggiungere panna, sale e addensare. Saltare gli spinaci, già sbollentati con olio e unire i pinoli e l''uvetta. Cuocere lentamente per 5 minuti. Servire la carne con salsa di spinaci.',1418);
INSERT INTO "ricette" VALUES (25079,'Tagliatelle','Primo','Piselli',4,' -','500 G Pasta Tipo Tagliatelle,
Ragù Già Pronto (per La Pasta Al Forno),
1 Scatola Piselli,
100 G Pancetta,
1 Confezione Panna,
Formaggio Parmigiano,
Vino Bianco','Sciacquare i piselli, appena usciti dalla scatola, e porli a cuocere, senza niente, per circa 10 minuti. A parte rosolare la pancetta (o del prosciutto), aggiungere una tazzina di vino bianco, lasciare evaporare, unire ai piselli (ai quali è stato aggiunto un pizzico di sale). Il tutto, insieme alla panna, serve a condire la pasta; se si volesse fare la pasta al forno, basta unire, al condimento preparato sopra, il ragù, mettere in una pirofila con dei fiocchetti di burro e lasciare 10 minuti in forno caldo.',3933);
INSERT INTO "ricette" VALUES (25080,'Tagliatelle Agli Amaretti','Primo','Biscotti Amaretti',4,' -','500 G Pasta Tipo Tagliatelle,
100 G Mascarpone,
100 G Biscotti Amaretti,
Burro,
Sale','Sbriciolare gli amaretti, aggiungere il mascarpone, girare delicatamente e far amalgamare. Cuocere le tagliatelle in abbondante acqua salata, scolarle al dente, condirle con il burro fuso, unire la crema ottenuta, mescolare e servire calde.',3566);
INSERT INTO "ricette" VALUES (25081,'Tagliatelle Agli Asparagi','Primo','Asparagi',4,' -','500 G Pasta Tipo Tagliatelle All''uovo Fresche,
200 G Asparagi Surgelati,
200 G Polpa Di Pomodoro,
Olio D''oliva,
Aglio,
Cipolla,
Basilico,
30 G Burro,
Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Cuocere gli asparagi a vapore per 5 minuti. Rosolare nell''olio aglio e cipolla tritati, aggiungere gli asparagi a pezzetti e lasciar insaporire per 5 minuti. Unire pomodoro, basilico sminuzzato, salare, pepare e far restringere la salsa. Lessare ben al dente la pasta in acqua salata, scolarla e trasferirla nella padella con il sugo. Far insaporire e mantecare con burro e parmigiano.',3310);
INSERT INTO "ricette" VALUES (25082,'Tagliatelle Agli Asparagi (2)','Primo','Asparagi',6,'Preparazione: 40 minuti.','250 G Pasta Tipo Tagliatelle All''uovo Fresche,
200 G Asparagi,
2 Cipollotti,
1 Arancia Non Trattata,
4 Cucchiai Olio D''oliva Extra-vergine,
3 Foglie Santoreggia (o Basilico),
4 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
1 Macinata Pepe Bianco In Grani','Mondate i cipollotti e affettateli. Separate i gambi degli asparagi dalle punte e tagliateli a fettine. Fate quindi scaldare 3 cucchiai d''olio in una larga padella, unite i cipollotti e i gambi affettati e lasciate cuocere, coperto e a fuoco dolce, per circa 10 minuti. Unite poi le punte, la buccia grattugiata dell''arancia e il suo succo e fate cuocere a fuoco vivace per qualche istante. Profumate quindi con la santoreggia spezzettata. Lessate la pasta in abbondante acqua salata, a cui avrete aggiunto l''olio rimasto, scolatela al dente e conditela subito con le verdure preparate. Completate infine la pasta con il formaggio e una macinata di pepe e servitela ben calda.',2127);
INSERT INTO "ricette" VALUES (25083,'Tagliatelle Agli Asparagi (3)','Primo','Asparagi',4,'Preparazione: 20 minuti. Cottura: 15 minuti. Calorie: 250.','200 G Pasta Tipo Tagliatelle,
1 Mazzetto Asparagi,
1 Patata,
2 Bustine Zafferano In Polvere,
Formaggio Parmigiano Reggiano,
40 G Burro,
Sale,
Pepe Macinato Al Momento','Sbucciate la patata, lavatela, asciugatela, tagliatela a cubetti e lessatela in acqua bollente finché è tenera. Mettete sul fuoco una pentola con abbondante acqua salata e aromatizzatela con lo zafferano. Nel frattempo, fate fondere il burro in un tegame e rosolate a fiamma dolce gli asparagi. Buttate le tagliatelle nell''acqua allo zafferano, scolatele al dente e conservate un po'' dell''acqua di cottura. Mescolatele subito agli asparagi nel tegame e aggiungete qualche cucchiaio dell''acqua tenuta da parte affinché non si asciughino troppo. Versate nel tegame le patate ben scolate e unite una macinata di pepe. Mescolate e servite subito, accompagnando con il formaggio grattugiato.',1675);
INSERT INTO "ricette" VALUES (25084,'Tagliatelle Agli Asparagi (4)','Primo','Asparagi',4,' -','350 G Pasta Tipo Nidi Di Tagliatelle,
400 G Asparagi,
1 Cipollina,
2 Pomodori,
Formaggio Parmigiano Grattugiato,
Olio D''oliva Extra-vergine,
Sale','Pulire e tagliare a rondelle gli asparagi, lasciando le punte intere; metterli in una padella e aggiungere la cipollina fresca, i pomodori maturi, olio, sale e iniziare a cuocere. Nel frattempo, mettere a bollire l''acqua per la pasta. Dopo circa 20 minuti il sughetto è pronto. Trasferirvi le tagliatelle al dente, saltarle e versarle nei piatti. Servire con parmigiano grattugiato. Suggerimento: eventualmente scottare gli asparagi prima di tagliarli a rondelle, e finirne la cottura in padella; altrimenti rimane un sapore acuto che sciupa un po'' la preparazione.',2513);
INSERT INTO "ricette" VALUES (25085,'Tagliatelle Ai Carciofi','Primo','Carciofi',4,' -','500 G Pasta Tipo Tagliatelle,
1 Cipolla,
2 Cucchiai Olio D''oliva,
4 Carciofi,
2 Uova,
4 Cucchiai Formaggio Parmigiano Grattugiato','Tritate la cipolla e doratela nell''olio; unite i carciofi tagliati a spicchi e fateli insaporire per qualche minuto, poi unite il sale e qualche cucchiaio di acqua calda. Cuocete fino a che i carciofi non diventino teneri e abbiano assorbito il liquido. Cuocete la pasta e intanto in una ciotola sbattete le uova con il parmigiano. Quando la pasta sarà cotta, scolatela e unitela alle uova. Infine unite il ragù di carciofi.',2807);
INSERT INTO "ricette" VALUES (25086,'Tagliatelle Ai Carciofi E Fonduta Di Provolone','Primo','Carciofi',4,' -','200 G Farina,
2 Uova,
1 Tuorlo D''uovo,
2 Carciofi,
100 G Formaggio Provolone,
1 Peperoncino,
1 Spicchio Aglio,
1 Limone,
Olio D''oliva,
Sale','Stendere e tagliare a mo'' di fettuccine la pasta fresca di uova e farina; cuocerla in acqua bollente salata. Nel frattempo pulire e tagliare a spicchi i cuori di carciofi e cuocerli in padella con olio, aglio, peperoncino e scorza di limone grattugiata. Fondere il formaggio in un pentolino a parte con panna e latte bollenti, unendo alla fine olio ed un tuorlo d''uovo lontano dal fuoco per addensare la fonduta. Servire le tagliatelle sulla crema di formaggio a specchio.',2076);
INSERT INTO "ricette" VALUES (25087,'Tagliatelle Ai Fagioli','Primo','Fagioli Cotti',4,' -','450 G Fagioli Cotti,
1/2 Cipolla,
Lardo,
Pomodori Pelati,
250 G Pasta Tipo Tagliatelle All''uovo,
Formaggio Parmigiano,
Olio D''oliva,
Burro,
Sale,
Pepe','Soffriggere il burro e l''olio, la cipolla e il lardo tritati unire i fagioli e far insaporire; aggiungere i pelati, salare, pepare e cuocere per 20 minuti; cuocere le tagliatelle e condirle con il sugo ai fagioli e il parmigiano.',4117);
INSERT INTO "ricette" VALUES (25088,'Tagliatelle Ai Fagiolini','Primo','Fagiolini',4,' -','400 G Pasta Tipo Tagliatelle,
Burro,
2 Spicchi Aglio,
1 Cipolla,
200 G Fagiolini,
1 Dado,
Rosmarino,
Formaggio Grana Grattugiato','Rosolare in burro, aglio e cipolla tritati i fagiolini mondati e lavati. Cospargerli con il dado, coprirli a filo di acqua e cuocerli per circa 25 minuti, poi profumarli con un trito di rosmarino. Lessare le tagliatelle al dente, scolarle, condirle con un po'' di burro, il grana grattugiato e i fagiolini al rosmarino.',2711);
INSERT INTO "ricette" VALUES (25089,'Tagliatelle Ai Funghi','Primo','Funghi Porcini',4,' -','400 G Pasta Tipo Tagliatelle Fresche All''uovo,
300 G Funghi Porcini,
80 G Prosciutto Crudo,
10 Foglie Basilico,
80 G Mascarpone,
2 Spicchi Aglio,
1 Spolverata Formaggio Grana,
2 Cucchiai Olio D''oliva,
20 G Burro,
Sale,
1 Manciata Pepe','Tagliate i funghi a lamelle. Fate rosolare 2 spicchi d''aglio in 2 cucchiai di olio, sale e 20 g di burro, unite i funghi e fateli insaporire per 3/4 minuti sul fuoco basso. Aggiungete il prosciutto tagliato a listarelle e il basilico tritato. Mescolate per un minuto su fuoco basso, poi spegnete la fiamma. Scolate la pasta al dente e conditela con il mascarpone. Trasferitela nella padella con il sugo e fate saltare per mezzo minuto su fuoco vivo. Insaporitele con un manciata di pepe e servite con una spolverata di grana.',2894);
INSERT INTO "ricette" VALUES (25090,'Tagliatelle Ai Funghi (2)','Primo','Funghi Secchi',4,' -','280 G Pasta Tipo Tagliatelle Fresche,
30 G Funghi Secchi,
1/2 Bicchiere Vino Bianco Secco,
40 G Formaggio Grattugiato,
3 Cucchiai Salsa Di Pomodoro,
1 Cipollina,
2 Cucchiai Olio D''oliva,
Sale','Lasciate ammorbidire per un''ora i funghi in acqua tiepida. Scolateli, strizzateli, tritateli finemente insieme alla cipollina e fate insaporire in un tegame con due cucchiai d''olio. Quindi aggiungete un mestolino d''acqua. Mescolate. Salate con parsimonia. Unite mezzo bicchiere di vino bianco, fate evaporare e poi aggiungete tre cucchiai di salsa di pomodoro. Lasciate cuocere a fuoco moderato mezz''ora. Lessate le tagliatelle. Conditele con formaggio grattugiato e sugo di funghi caldo. Vini di accompagnamento: Casteller Superiore DOC, Sangiovese Di Romagna DOC, Melissa Rosso DOC.',1686);
INSERT INTO "ricette" VALUES (25091,'Tagliatelle Ai Funghi (3)','Primo','Funghi Champignon',4,' -','500 G Pasta Tipo Tagliatelle,
300 G Funghi Champignon,
600 G Pomodori Pelati,
50 G Burro,
2 Spicchi Aglio,
3 Cucchiai Olio D''oliva,
1 Bicchiere Vino Rosso,
1 Cucchiaio Prezzemolo,
Sale,
Pepe','Pulire, lavare i funghi e metterli in un grande tegame, nel quale precedentemente rosolava 1 aglio con burro e olio. Lasciar dorare bene il tutto, poi bagnare con il vino, facendolo evaporare a fuoco vivo. Unire quindi i pelati, privati di semi e passati al setaccio. Salare, pepare e lasciar cuocere per 20 minuti, facendo restringere la salsa e aggiungere il prezzemolo tritato. Cuocere le tagliatelle e condirle con il sugo preparato.',3627);
INSERT INTO "ricette" VALUES (25092,'Tagliatelle Ai Funghi Con Salsiccia','Primo','Funghi Porcini',4,' -','320 G Pasta Tipo Tagliatelle Fresche Ai Funghi,
300 G Funghi Porcini,
100 G Salsiccia Fresca,
2 Scalogni,
1 Foglia Alloro,
1 Ciuffo Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Per ottenere le tagliatelle fresche ai funghi aggiungere all''impasto della pasta una manciata di funghi passati nel mixer. Private i funghi della parte terrosa e puliteli con un panno umido, poi tagliateli a pezzi. Spellate la salsiccia, sbriciolatela e fatela rosolare in una padella antiaderente senza aggiungere grassi. Mettetela poi da parte e asciugate il grasso sul fondo della padella. Sbucciate gli scalogni affettateli sottili e rosolateli nella stessa padella con qualche cucchiaio di olio. Unite i funghi e l''alloro e cuocete a fiamma vivace per 5 minuti, lasciando evaporare l''acqua di vegetazione. Aggiungete la salsiccia e lasciate insaporire per qualche istante. Salate e pepate. Cuocete la pasta al dente e conditela subito con il sugo di funghi. Profumate infine con il prezzemolo tritato, e servite in piatti caldi.',2367);
INSERT INTO "ricette" VALUES (25093,'Tagliatelle Ai Funghi E Noci','Primo','Funghi',4,' -','400 G Pasta Tipo Tagliatelle,
1 Cipollina,
40 G Funghi Secchi,
1 Bicchierino Vino Marsala Secco,
1 Mazzetto Prezzemolo,
50 G Burro,
4 Cucchiai Panna,
1/2 Dado Per Brodo,
10 Gherigli Di Noci,
Sale,
Pepe','Tritate i gherigli di noci. Lavate i funghi secchi sotto acqua corrente, metteteli in ammollo in acqua tiepida; quando sono morbidi scolateli senza buttare l''acqua e tagliateli a pezzettini. Mettete in una casseruolina metà burro, unite il trito di cipolla e prezzemolo, lasciate appassire la cipolla, poi unite i funghi. Fateli soffriggere per un paio di minuti o poco più, poi bagnateli con il marsala. Unite il dado sbriciolato, lasciate cuocere su fuoco moderato bagnando con qualche cucchiaiata dell''acqua di ammollo dei funghi (che avrete prelevato senza smuovere il fondo e che avrete filtrato). Mescolate, mettete il coperchio e lasciate cuocere su fuoco molto basso per almeno 20 minuti. Verso il termine di cottura assaggiate e aggiustate di sale, quando i funghi sono pronti unite la panna e il resto del burro. Amalgamate e lasciate cuocere il tutto sul fuoco solo un attimo, poi, a fornello spento, aggiungete le noci. Completate con una grattugiatina di pepe, poi con questo sugo ben caldo condite la pasta cotta a parte in abbondante acqua salata.',2958);
INSERT INTO "ricette" VALUES (25094,'Tagliatelle Ai Piselli','Primo','Piselli',4,' -','450 G Pasta Tipo Tagliatelle,
450 G Piselli,
1/2 Bustina Zafferano,
1/2 Bicchiere Vino Bianco,
Farina,
Brodo,
1 Uovo,
50 G Formaggio Grana,
1 Cipolla,
Burro,
Sale,
Pepe','Mettere i piselli scongelati in un tegame con il burro e la cipolla tritata, spolverizzare con la farina, mescolare, bagnare con il vino, salare, pepare, unire lo zafferano diluito con il brodo, cuocere per 5 minuti e versare il tuorlo. Cuocere la pasta al dente e condirla con la salsa e il grana grattugiato.',3409);
INSERT INTO "ricette" VALUES (25095,'Tagliatelle Ai Piselli (2)','Primo','Piselli',4,' -','320 G Pasta Tipo Tagliatelle All''uovo,
800 G Piselli Da Sgranare,
2 Cipolle Grandi,
1 Spicchio Aglio,
50 G Pancetta,
10 G Prezzemolo,
4 Cucchiai Formaggio Grana,
1 Mestolo Brodo Di Carne,
40 G Burro,
Sale,
Pepe','Sgranare i piselli. Sbucciare l''aglio e la cipolla e tritaleli insieme alla pancetta e al prezzemolo mondato e lavato; fate friggere il trito in una casseruola com metà del burro, dopodichè unitevi i piselli, salate, pepate, mescolate e lasciate cuocere per 10 minuti, aggiungendo il brodo poco alla volta. Fate cuocere le tagliatelle in una pentola con abbondante acqua bollente salata, quindi scolatele al dente, versatele su un piatto da portata, conditeli con i piselli, il burro rimasto e il grana grattugiato e servitele subito in tavola.',2692);
INSERT INTO "ricette" VALUES (25096,'Tagliatelle Ai Quattro Formaggi','Primo','Mozzarella',4,' -','400 G Pasta Tipo Tagliatelle Verdi,
1 Mozzarella,
50 G Formaggio Groviera,
50 G Formaggio Provolone,
50 G Formaggio Olandese,
80 G Burro,
Sale,
Pepe','Cuocere le tagliatelle in abbondante acqua salata, scolarle al dente, metterle in una pirofila imburrata, unire il burro a pezzetti, i formaggi tagliati a bastoncini e la mozzarella tagliata a fettine, infornare per pochi minuti e servire ben calde.',3095);
INSERT INTO "ricette" VALUES (25097,'Tagliatelle Ai Topinambur','Primo','Topinambur',4,' -','380 G Pasta Tipo Tagliatelle Fresche,
150 G Topinambur,
1 Pomodoro,
Aglio,
Prezzemolo Tritato,
Olio D''oliva Extra-vergine','Cuocere i topinambur in abbondante acqua acidula, una volta cotti tagliateli a pezzetti e fateli saltare in padella con olio, aglio e dei quadrettini di pomodoro. Fate saltare le tagliatelle precedentemente cotte in abbondante acqua salata e irrorate, se necessario con un poco di acqua di cottura e olio d''oliva extra-vergine. Guarnire la preparazione con prezzemolo tritato.',2063);
INSERT INTO "ricette" VALUES (25098,'Tagliatelle Al Baccalà','Primo','Baccalà',6,'Luogo: Lazio.','Per La Pasta:,
450 G Farina,
Sale,
Per Il Condimento:,
400 G Baccalà Ammollato,
500 G Passata Di Pomodoro,
30 G Funghi Secchi,
1 Cipolla Tritata,
2 Spicchi Aglio Tritato,
1 Foglia Alloro,
1 Peperoncino,
1 Cucchiaio Prezzemolo Tritato,
1 Pizzico Cannella,
Olio D''oliva,
Sale','Mettere a bagno i funghi in acqua tiepida, dopo un''ora scolarli e strizzarli. Sulla tavola, versare la farina a fontana e impastarla con un po'' di sale e di acqua tiepida; stenderla col matterello e poi ritagliarla in tante tagliatelle larghe circa 2 cm. Allargarle e farle asciugare sulla tavola infarinata. Pulire il baccalà togliendo la pelle e le spine, poi ritagliarlo a riquadri. In un tegame soffriggere olio, aglio e cipolla e farvi rosolare il baccalà; unire il pomodoro, i funghi, il peperoncino, l''alloro sminuzzato e la cannella. Regolare di sale, coprire il tegame e cuocere lentamente. Lessare le tagliatelle, scolarle e condirle con il sugo di baccalà, eliminando i pezzetti di alloro. Decorare con il prezzemolo e servire.',2714);
INSERT INTO "ricette" VALUES (25099,'Tagliatelle Al Burro E Semolino','Primo','Burro',4,' -','80 G Semolino,
230 G Pasta Tipo Tagliatelle,
Sale,
30 G Strutto Di Burro','Friggete il semolino nello strutto di burro finché diventa dorato, aggiungendo in continuazione un po'' di acqua finché diventa morbido. Cuocete le tagliatelle in abbondante acqua salata, passatele nell''acqua fresca, scolatele, aggiungetele al semolino e saltatele.',1348);
INSERT INTO "ricette" VALUES (25100,'Tagliatelle Al Cacao Con Panna E Prosciutto','Primo','Cacao Amaro',4,' -','Per La Pasta:,
200 G Farina,
2 Uova,
25 G Cacao Amaro In Polvere,
Per Condire:,
1 Noce Burro,
120 G Prosciutto Cotto (fette Da 120 G),
20 Cl Panna,
Sale,
Pepe,
4 Rametti Aneto','Impastate la farina con le uova e il cacao, aggiungendo un po'' d''acqua se necessario, quindi stendete la pasta in una sfoglia non troppo sottile e tagliatela formando le tagliatelle. Portate ad ebollizione in una pentola abbondante acqua salata, unite le tagliatelle al cacao e lessatele al dente. Mentre la pasta cuoce preparate la salsa per condire: fate fondere dolcemente il burro in una casseruolina, unite il prosciutto cotto tagliato a dadini e lasciatelo rosolare a calore moderato per 5 minuti, mescolando continuamente con un cucchiaio di legno. A questo punto aggiungete la panna, insaporite con il sale necessario e una macinata di pepe e rimestate con cura per amalgamare bene gli ingredienti. Lasciate cuocere la salsa per pochi istanti, in modo che la panna possa scaldarsi senza arrivare a bollire, quindi togliete dal fuoco. Scolate le tagliatelle, ponetele in una zuppiera e conditele velocemente con la salsa preparata. Distribuite la pasta in quattro piatti fondi individuali, guarnite con un rametto di aneto e portate in tavola. --- CONSIGLI. La pasta colorata può essere facilmente preparata in casa aggiungendo all''impasto base della pasta all''uovo tradizionale un ''''colorante'''' costituito, a seconda dei casi, da un aroma particolare (come il cacao usato in questa ricetta), oppure una purea di verdura o di frutta. L''importante è ricordare che, quale che sia il colorante prescelto, su 1000 g totale di pasta i componenti umidi, quali uova, colorante (frutta o verdura) e acqua non devono mai superare i 400 g; i restanti 600 g sono quindi sempre rappresentati dalla farina. L''impasto che si ottiene non è molto elastico, per cui dovete stenderlo in una sfoglia non troppo sottile, se desiderate preparare le tagliatelle. Potete anche realizzare altri formati di pasta se possedete la macchina apposita. Infine, ricordate che, se l''impasto non dovesse tenere, prima di tirarlo aggiungete altra farina.',2683);
INSERT INTO "ricette" VALUES (25101,'Tagliatelle Al Curry','Primo','Curry',4,' -','400 G Pasta Tipo Tagliatelle All''uovo,
2 Cipolle,
Burro,
1/2 Bicchiere Vino Marsala,
1/2 Dado,
1 Cucchiaino Curry,
Sale','Appassire in 50 g di burro le cipolle affettate a velo. Spruzzare con il marsala, insaporire con il dado e cuocere ancora per 10 minuti. Prima di togliere dal fuoco unire il curry e 20 g di burro. Scolare la pasta al dente, condire con la salsa e servire subito.',2399);
INSERT INTO "ricette" VALUES (25102,'Tagliatelle Al Curry (2)','Primo','Curry',4,' -','400 G Pasta Tipo Tagliatelle All''uovo,
2 Cipolle,
70 G Burro,
1/2 Bicchiere Vino Marsala,
1/2 Dado,
1 Cucchiaino Curry,
Sale','Cuocere le tagliatelle in abbondante acqua salata al dente. Intanto affettare al velo le cipolle; far fondere 50 g di burro, unirvi le cipolle e farle stufare per 10 minuti. Spruzzarle con il marsala, insaporirle con il dado e cuocere ancora per 10 minuti. Unire, infine, il curry e 20 g di burro, che si scioglierà nel sugo caldo. Condirvi la pasta e servire.',2173);
INSERT INTO "ricette" VALUES (25103,'Tagliatelle Al Curry E Vino Rosso','Primo','Pancetta',4,' -','400 G Pasta Tipo Tagliatelle Fresche All''uovo,
150 G Pancetta,
1 Bicchiere Vino Rosso Robusto,
1 Spicchio Aglio Tritato,
1/2 Cucchiaio Cipolla Tritata,
1 Cucchiaino Curry,
100 G Panna,
1 Cucchiaio Olio D''oliva,
1/2 Noce Burro,
Sale','Tagliate la pancetta a dadini e rosolatela nell''olio e nel burro. Versateci il vino e fatelo evaporare a fuoco vivo. Quando il vino si è ridotto di circa la metà aggiungete il curry; fate addensare la salsina aggiungendo la panna. Amalgamate per pochi minuti e tenete la salsa in caldo. Cuocete le tagliatelle al dente, scolatele e fatele saltare con la salsa aggiungendo ancora una spruzzatina di vino. Non aggiungere formaggio.',3294);
INSERT INTO "ricette" VALUES (25104,'Tagliatelle Al Forno','Primo','Carciofi',4,' -','10 G Farina Bianca,
40 G Burro,
2 Bicchieri Brodo,
1 Cipolla,
Sedano,
1 Carota,
Alloro,
Timo,
350 G Carciofi,
1 Uovo,
2 Formaggini,
2 Cucchiai Latte,
350 G Pasta Tipo Tagliatelle All''uovo,
50 G Formaggio Parmigiano Grattugiato,
50 G Panna,
Sale','Amalgamare la farina con poco burro, il brodo, la cipolla, poco sedano, la carota, alloro e timo. Bollire per 30 minuti. Unire la panna, il tuorlo e i formaggi sciolti nel latte tiepido. Cuocere i carciofi a spicchi nel burro. Lessare le tagliatelle e condirle la salsa e il burro. Disporre strati di carciofi e tagliatelle in una teglia imburrata e gratinare.',2505);
INSERT INTO "ricette" VALUES (25105,'Tagliatelle Al Granchio','Primo','Granchio',4,' -','400 G Pasta Tipo Tagliatelle All''uovo,
2 Scalogni,
1 Carota,
1 Costa Sedano,
1 Porro,
170 G Polpa Di Granchio,
1 Cucchiaio Passato Di Pomodoro,
Vino Bianco,
Brandy,
Brodo Vegetale,
Olio D''oliva,
Burro,
Sale,
Pepe','Far appassire con 20 g di burro e 1 cucchiaio di olio tutte le verdure tritate, unire la polpa di granchio e farla insaporire per 3 minuti. Spruzzare con 1/2 bicchiere di vino e 1 cucchiaio di brandy e far evaporare. Unire il passato di pomodoro e 1/2 bicchiere di brodo, salare, pepare e cuocere per 5 minuti. Lessare le tagliatelle e condirle con il sugo.',3487);
INSERT INTO "ricette" VALUES (25106,'Tagliatelle Al Latte','Primo','Latte',4,' -','500 G Pasta Tipo Tagliatelle,
80 G Burro,
80 G Formaggio Parmigiano Grattugiato,
1/2 Bicchiere Latte,
Noce Moscata,
Sale,
Pepe','Fondere il burro, aggiungere il formaggio, mescolare e subito stemperare con il latte. Far restringere la salsa, salare e pepare. Versare la salsa sulle tagliatelle caldissime, completare con una macinatina di noce moscata, mescolare e servire.',2864);
INSERT INTO "ricette" VALUES (25107,'Tagliatelle Al Limone','Primo','Limoni',4,' -','350 G Pasta Tipo Tagliatelle,
3 Limoni,
50 G Burro,
50 G Panna Liquida,
Abbondante Formaggio Grattugiato,
Sale','Lavate bene i limoni, asciugateli e grattugiate la scorza di due. In una padella fate scaldare il burro, quando è spumeggiante, unite le scorze, lasciate insaporire, bagnate con la panna e salate. Cuocete in abbondante acqua salata le tagliatelle, scolatele, passatele nella padella del sugo, mescolate delicatamente. Versate le tagliatelle su un piatto da portata, cospargetele con abbondante formaggio grattugiato e decorate con la scorza dell''altro limone tagliata a julienne.',2276);
INSERT INTO "ricette" VALUES (25108,'Tagliatelle Al Mais','Primo','Mais',4,' -','350 G Mais In Scatola,
400 G Pasta Tipo Tagliatelle,
50 G Pancetta,
1 Tazza Besciamella,
1/2 Cipolla Affettata,
Formaggio Grana Grattugiato,
Burro,
Sale,
Pepe','In un tegame fare soffriggere la cipolla con il burro, aggiungere la pancetta tagliata a dadini e lasciare insaporire. Aggiungere il mais, salare e pepare. Cuocere la pasta in abbondante acqua salata, scolare al dente; aggiungere il soffritto di pancetta e mais, la besciamella ben calda ed il formaggio grana. Mescolare delicatamente e servire.',3332);
INSERT INTO "ricette" VALUES (25109,'Tagliatelle Al Mascarpone','Primo','Mascarpone',4,' -','350 G Pasta Tipo Tagliatelle,
150 G Mascarpone,
1 Uovo,
Formaggio Parmigiano Grattugiato,
Sale','Frullare l''uovo in una terrina e amalgamare il mascarpone lavorando bene l''impasto. Cuocere le tagliatelle al dente in abbondante acqua salata, condirle con il composto, cospargerle con abbondante parmigiano grattugiato e servirle caldissime.',2456);
INSERT INTO "ricette" VALUES (25110,'Tagliatelle Al Mascarpone (2)','Primo','Mascarpone',4,' -','300 G Mascarpone,
1 Fetta Prosciutto Cotto (da 150 G),
400 G Pasta Tipo Tagliatelle All''uovo,
50 G Formaggio Parmigiano Grattugiato','Mentre bolle l''acqua per le tagliatelle, fate sciogliere a bagnomaria il mascarpone. Tagliate a dadini il prosciutto cotto e unitelo al mascarpone. Quando le tagliatelle saranno cotte buttatele per qualche istante nel tegame con il mascarpone e il prosciutto, in modo che si sposino bene col sugo. Condite col parmigiano.',3660);
INSERT INTO "ricette" VALUES (25111,'Tagliatelle Al Nero Di Seppia','Primo','Inchiostro Di Seppia',4,' -','200 G Farina,
2 Uova,
2 Sacchetti Inchiostro Di Seppia,
Sale,
Per Condire:,
150 G Tonno,
Capperi Salati,
3 Cucchiai Olio D''oliva','Disponete la farina a fontana, al centro sgusciatevi le uova e versatevi l''inchiostro delle seppie e il sale. Impastate fino a ottenere una pasta morbida e liscia. Tiratela a sfoglia, ripiegatela più volte e tagliate le tagliatelle larghe 1/2 centimetro. In una ciotola mescolate il tonno sminuzzato con i capperi lavati e strizzati, ammorbidite con tre cucchiai d''olio. In una pentola portate a bollore abbondante acqua salata e lessatevi le tagliatelle. Scolatele al dente e conditele con la salsa fredda. Mescolatele bene e servite senza aggiunta di formaggio. Vini di accompagnamento: Colli Orientali Del Friuli Malvasia Istriana DOC, Orvieto DOC, Regaleali Bianco IGT Di Sicilia.',2515);
INSERT INTO "ricette" VALUES (25112,'Tagliatelle Al Radicchio Rosso','Primo','Radicchio Di Treviso',4,' -','4 Cespi Radicchio Di Treviso,
250 G Panna Da Cucina,
320 G Pasta Tipo Tagliatelle,
100 G Formaggio Parmigiano Grattugiato,
1 Macinata Pepe Nero','Cuocete la pasta in abbondante acqua salata. Pulite il radicchio, tagliate i cespi in due nel senso della lunghezza, metteteli in una pirofila da forno, bagnateli con un po'' di panna e cuoceteli per 5 minuti a 180 gradi. Scolate la pasta, disponetela nella pirofila, versate la panna rimanente, cospargete di parmigiano, una macinata di pepe nero e passate al forno per una lieve gratinatura.',2132);
INSERT INTO "ricette" VALUES (25113,'Tagliatelle Al Salmone','Primo','Salmone',4,' -','250 G Pasta Tipo Tagliatelle,
80 G Salmone Affumicato,
1 Scalogno,
Margarina,
Prezzemolo,
1 Bicchierino Vodka,
Sale,
Pepe,
200 G Panna Da Cucina','Fare rosolare fino ad imbiondire lo scalogno tritato, unire il salmone tagliato a striscioline aggiungere subito la vodka, e sempre a fuoco basso, dopo pochi minuti mettere la panna, un pizzico di sale ed una spolverata di pepe. Una volta condita la pasta spolverare con prezzemolo tritato.',2380);
INSERT INTO "ricette" VALUES (25114,'Tagliatelle Al Salmone (2)','Primo','Salmone',4,' -','280 G Pasta Tipo Tagliatelle Fresche,
100 G Salmone Affumicato,
1/2 Bicchiere Panna,
50 G Burro,
1/2 Bicchierino Whisky,
1/2 Limone (succo),
1 Pizzico Sale,
1 Pizzico Pepe','Fate la pasta e ricavate le tagliatelle. In un tegame fate sciogliere il burro, unitevi il salmone tagliato a pezzetti. Mescolate e spruzzate con il succo di mezzo limone. Dopo pochi minuti aggiungete la panna, mezzo bicchierino di whisky, un pizzico di sale, uno di pepe e cuocete per 5 minuti. Lessate le tagliatelle in abbondante acqua salata, scolatele al dente, versatele nel tegame della salsa e ponete per un attimo sul fuoco perché insaporiscano bene. Mescolate con delicatezza, passate sul piatto da portata caldo. Servite. Vini di accompagnamento: Oltrepò Pavese Rosato DOC, Bolgheri Rosato DOC, Alezio Rosato DOC.',1784);
INSERT INTO "ricette" VALUES (25115,'Tagliatelle Al Salmone Affumicato','Primo','Salmone',4,' -','200 G Pasta Tipo Tagliatelle Gialle,
200 G Pasta Tipo Tagliatelle Verdi,
150 G Salmone Affumicato,
10 Cl Panna Da Cucina,
Pepe,
Sale','Tagliate a listarelle 2 o 3 fettine di salmone affumicato e tenetele a parte. Passate il salmone rimanente al setaccio. Lessate in abbondante acqua salata in ebollizione le tagliatelle. Mettete in una zuppiera, precedentemente scaldata con acqua bollente e asciugata, il passato di salmone e diluitelo con la panna liquida scaldata a parte. Salate e pepate. Scolate la pasta molto al dente, versatela nella zuppiera e mescolate delicatamente. Completatela con le listarelle di salmone tenute da parte e con pepe macinato.',1930);
INSERT INTO "ricette" VALUES (25116,'Tagliatelle Al Sedano E Prosciutto','Primo','Sedano',4,' -','350 G Pasta Tipo Tagliatelle,
1 Cuore Sedano,
50 G Burro,
100 G Prosciutto Cotto,
Sale,
Pepe,
1/2 Bicchiere Vino Marsala Secco','Lavare e tritare grossolanamente il sedano con le sue foglie. Lessare le tagliatelle. Intanto, in un tegame con il burro, far rosolare il sedano e il prosciutto cotto a dadini; salare e pepare. Dopo qualche istante bagnare con il marsala e farlo evaporare a fuoco vivo. Scolare la pasta al dente e condirla subito con il sugo preparato. Mescolare bene e servire.',2195);
INSERT INTO "ricette" VALUES (25117,'Tagliatelle Al Sugo Di Fegatini','Primo','Fegatini',4,' -','400 G Pasta Tipo Tagliatelle Fresche All''uovo,
150 G Fegatini Di Pollo,
2 Bicchieri Vino Bianco Secco,
1 Cipolla,
3 Foglie Salvia,
1 Pizzico Maggiorana,
50 G Formaggio Parmigiano,
40 G Olio D''oliva Extra-vergine,
30 G Burro,
Sale,
Pepe','Tritate la cipolla e mettetela in una casseruola con l''olio di oliva, fate rosolare lentamente; quando prende colore aggiungete il vino (tipo Trebbiano) e lasciate asciugare un poco, cuocendo a fuoco lento. Mondate i fegatini e tagliateli a tocchetti, fateli passare nel burro con la salvia, uniteli alla cipolla, salate e pepate a piacere (il pepe deve essere macinato di fresco) e fate cuocere per circa 10 minuti. Lessate le tagliatelle in abbondante acqua salata, scolatele e conditele con il parmigiano e la salsa ai fegatini.',2708);
INSERT INTO "ricette" VALUES (25118,'Tagliatelle Al Sugo Di Funghi Porcini','Primo','Funghi Porcini',4,' -','400 G Farina,
4 Uova,
Per Il Sugo:,
300 G Funghi Porcini,
1/2 Cipolla,
Olio D''oliva,
1 Noce Burro,
Sale,
Pepe,
Formaggio Parmigiano,
1 Cucchiaio Salsa Di Pomodoro','Impastare uova e farina. Tirare una sfoglia sottile e tagliarla a strisce di 2 cm. Tritare la cipolla e rosolarla nell''olio. Unire i porcini ed 1 cucchiaio di salsa di pomodoro. Cuocere per 10 minuti ed aggiungere sale, pepe, la noce di burro e finir di cuocere. Cuocere al dente le tagliatelle, aggiungere il parmigiano e servire.',3324);
INSERT INTO "ricette" VALUES (25119,'Tagliatelle Al Sugo Di Noci','Primo','Noci',4,' -','Pasta Tipo Tagliatelle,
4 Noci,
1 Spicchietto Aglio,
1 Peperoncino Piccante,
Formaggio Romano (o Formaggio Parmigiano Grattugiato),
Sale,
Olio D''oliva','Tritate le noci insieme all''aglio e al peperoncino, emulsionate con un po'' di olio, quindi unite il formaggio e aggiungete altro olio (ne assorbirà parecchio), aggiustate di salse e usate questo condimento per le tagliatelle.',2466);
INSERT INTO "ricette" VALUES (25120,'Tagliatelle Al Tartufo','Primo','Tartufo',4,' -','Pasta Tipo Tagliatelle Fresche,
Olio D''oliva,
Tartufo,
Poco Pepe,
Formaggio Parmigiano A Scaglie','Tagliatelle fatte a mano condite con olio nel quale avrai scaldato un po'' di tartufo con poco pepe e parmigiano a scaglie.',2234);
INSERT INTO "ricette" VALUES (25121,'Tagliatelle Al Tartufo Bianco','Primo','Tartufo Bianco',4,' -','400 G Pasta Tipo Tagliatelle,
1 Tartufo Bianco,
50 G Burro,
1 Spicchio Aglio,
1 Rametto Rosmarino,
Besciamella,
1 Tuorlo D''uovo,
Formaggio Parmigiano Grattugiato,
Sale,
Pepe','In una padella rosolate nel burro l''aglio e un rametto di rosmarino poi toglieteli. Lessate e scolate le tagliatelle, quindi insaporitele nella padella. Legate la besciamella con il tuorlo sbattuto con sale e pepe. Unitela alle tagliatelle, aggiungete il tartufo a lamelle, spolverizzate con formaggio grattugiato. Mescolate delicatamente. Passate tutto in una teglia imburrata, cospargete con fiocchetti di burro e passate in forno caldo per una decina di minuti.',2514);
INSERT INTO "ricette" VALUES (25122,'Tagliatelle Al Tartufo Nero','Primo','Tartufo Nero',4,' -','350 G Pasta Tipo Tagliatelle,
200 G Tartufo Nero,
80 G Filetti D''acciughe,
1/2 Spicchio Aglio,
1 Ciuffo Prezzemolo,
Olio D''oliva Extra-vergine,
Sale','Grattugiate il tartufo e tritate prezzemolo, aglio e acciughe lavorate poi gli ingredienti in un mortaio fino a ottenere una pasta omogenea che lascerete riposare coprendola con l''olio. Lessate le tagliatelle in abbondante acqua bollente, scolate al dente e spadellatele in un tegame in cui avrete fatto scaldare la salsa di tartufo, servite poi immediatamente.',2175);
INSERT INTO "ricette" VALUES (25123,'Tagliatelle Al Tartufo Nero (2)','Primo','Tartufo Nero',4,' -','350 G Pasta Tipo Fettuccine All''uovo Integrali,
1 Tartufo Nero Piccolo,
4 Acciughe,
1 Spicchio Aglio,
1 Tazza Yogurth Cremoso,
Olio D''oliva Extra-vergine,
1 Pizzico Sale Marino,
Prezzemolo Tritato','Pestare bene in un mortaio 1 spicchio d''aglio, le acciughe diliscate, il tartufo grattugiato; versarvi un po'' d''olio a filo. Mentre cuoce la pasta con 1 pizzico di sale, versare il composto in un padellino e scaldarlo a fiamma bassa, quindi a fuoco spento mescolarvi lo yogurth. Scolare la pasta e amalgamarvi la salsa decorando con prezzemolo tritato.',2039);
INSERT INTO "ricette" VALUES (25124,'Tagliatelle Al Tonno','Primo','Tonno',4,' -','500 G Pasta Tipo Tagliatelle All''uovo,
4 Spicchi Aglio,
200 G Tonno,
1 Cucchiaio Capperi,
Prezzemolo,
Basilico,
Olio D''oliva,
Sale','Far dorare l''aglio nell''olio, unire il tonno sminuzzato, i capperi e far rosolare per pochi minuti. Cuocere le tagliatelle al dente in abbondante acqua salata, scolarle al dente, metterle nella padella con il tonno, far insaporire, cospargere con il prezzemolo e il basilico tritati e servire.',3146);
INSERT INTO "ricette" VALUES (25125,'Tagliatelle All''incanto','Primo','Pomodori Pelati',2,' -','200 G Pasta Tipo Tagliatelle,
5 Pomodori Pelati Maturi,
1 Cipolla,
1 Spicchio Aglio,
3 Acciughe,
Capperi,
Sale,
Olio D''oliva,
10 Cl Latte,
Formaggio Parmigiano','Cuocere in abbondante acqua salata le tagliatelle, preparare a parte i pomodori, la cipolla e l''aglio mondati. In una casseruola con l''olio, i capperi e le acciughe far soffriggere i pomodori, l''aglio e la cipolla. Scolare la pasta e versarla nella casseruola del sugo padellare aggiungendo il latte e cospargere con del parmigiano.',2022);
INSERT INTO "ricette" VALUES (25126,'Tagliatelle All''uovo Con Gamberoni','Primo','Gamberoni',4,' -','6 Gamberoni,
1 Cipollotto Fresco,
3 Pomodori A Grappolo,
Alcune Foglie Basilico,
60 G Burro,
Peperoncino Tritato,
Pasta Tipo Tagliatelle','Nel tempo che l''acqua per la pasta arrivi all''ebollizione, mettere in una teglia il burro con il cipollotto tritato e 1/2 bicchiere di acqua; cuocere 5 minuti fino a che l''acqua si sia ritirata, si aggiungano i gamberoni sgusciati e tagliati in piccoli pezzi; quando questi saranno imbiancati si aggiunga ancora il pomodoro tagliato a piccoli cubetti, assieme al peperoncino. aggiustare di sale. Lasciare cuocere 5 minuti ed aggiungere le foglie di basilico intere. Controllate che non asciughi troppo. In questa salsa salterete le tagliatelle dopo averle scolate. Servite ben caldo.',2177);
INSERT INTO "ricette" VALUES (25127,'Tagliatelle Alla Bolognese','Primo','Carne Di Manzo Tritata',4,'Luogo: Emilia-Romagna. Luogo: Bologna.','400 G Pasta Tipo Tagliatelle,
100 G Lardo,
300 G Carne Di Manzo Tritata,
50 G Burro,
1 Cipolla,
1 Carota,
1 Sedano,
3 Chiodi Di Garofano,
3 Cucchiai Panna,
1 Cucchiaio Salsa Di Pomodoro,
Formaggio Parmigiano,
Sale,
Pepe','Cuocere la pasta con acqua salata. Tritare il lardo, la cipolla, la carota e il sedano, metterli in una padella con il burro e la carne di manzo tritata e fate dorare il tutto. Aggiungete poi i chiodi di garofano e lasciate cuocere per 20 minuti. Quando la carne avrà preso un po'' di colore, versate un bicchiere d''acqua e aggiungete il pomodoro, sale e pepe. Lasciate cuocere ancora per 1 ora. Scolate la pasta e dopo averla condita con il sugo e i 3 cucchiai di panna, spolveratela con il parmigiano.',3779);
INSERT INTO "ricette" VALUES (25128,'Tagliatelle Alla Cannella Con Ragù Di Manzo E Patate','Primo','Cannella',6,' -','Per La Pasta:,
500 G Farina,
1 Cucchiaio Cannella In Polvere,
5 Uova,
Per La Salsa:,
200 G Manzo Tritato,
100 G Cipolla,
100 G Carota,
100 G Sedano,
1 Patata Grattugiata,
2 Pomodori,
1 Bicchiere Vino Rosso,
Olio D''oliva,
Sale,
Pepe,
Cannella','Preparare la pasta. In una padella, rosolare le verdure con l''olio, aggiungere la carne e far rosolare, bagnare con il vino e dopo l''evaporazione aggiungere la patata e i pomodori, salare, pepare e aromatizzare con la cannella. Cuocere per 5 minuti. Versare la pasta al dente, saltare e far legare bene.',3493);
INSERT INTO "ricette" VALUES (25129,'Tagliatelle Alla Carrettiera','Primo','Pomodoro',4,' -','400 G Pasta Tipo Tagliatelle,
40 G Funghi Secchi,
Olio D''oliva,
Aglio,
100 G Ventresca Di Tonno,
Peperoncino,
500 G Pomodoro','Mettere i funghi secchi a bagno in acqua tiepida per farli rinvenire e poi scolarli con un passino. Portare ad ebollizione la pentola per la cottura della pasta. In un tegame mettere l''olio a scaldare, aggiungere l''aglio tagliato a fette non troppo piccole e far imbiondire, i funghi, poi il tonno e il peperoncino, il pomodoro e regolare di sale. Lasciare restringere bene. Scolare la pasta e aggiungerla al condimento, servendo il tutto ben caldo.',2510);
INSERT INTO "ricette" VALUES (25130,'Tagliatelle Alla Cipolla','Primo','Cipolle Bianche',4,' -','350 G Pasta Tipo Nidi Di Tagliatelle,
2 Cipolle Bianche Grandi (350 G),
1 Cucchiaio Farina,
1 Spolverata Formaggio Parmigiano Grattugiato,
Latte,
1 Filo Olio D''oliva Extra-vergine,
Sale,
Pepe In Grani','Affettare a rondelle sottilissime le cipolle bianche, farle stufare lentamente in padella con un filo di Olio D''oliva Extra-vergine e un mestolino di acqua per 40 minuti buoni, fino a quando le cipolle, cioè, saranno sfatte. Spolverizzarle con un cucchiaio di farina e stemperare con un po'' di latte, fino a ottenere una specie di besciamella piuttosto liquida, perché altrimenti fa asciugare la pasta. Correggere di sale e macinare il pepe, poi cuocere le tagliatelle al dente e saltarle nel condimento. Servire immediatamente con una spolverata di parmigiano grattugiato.',1966);
INSERT INTO "ricette" VALUES (25131,'Tagliatelle Alla Crema Di Asparagi','Primo','Asparagi',4,' -','300 G Asparagi,
200 G Panna Liquida,
2 Rametti Maggiorana,
80 G Burro,
2 Scalogni,
Sale,
Pepe','Tagliare a pezzettini gli asparagi (mondati e lavati). Tritare gli scalogni finemente e farli appassire a fuoco basso con il burro spumeggiante. Unire gli asparagi e la panna, salare, pepare e cuocere a fuoco basso fino a quando gli asparagi saranno completamente disfatti. Aggiungere la maggiorana tritata e passare il tutto al mixer. Serve per condire pasta all''uovo fresca in genere e ravioli/tortelloni di magro (cioè con ricotta e spinaci).',1439);
INSERT INTO "ricette" VALUES (25132,'Tagliatelle Alla Crema Di Tartufo','Primo','Crema Di Tartufo',4,' -','400 G Pasta Tipo Tagliatelle Fresche All''uovo,
Crema Di Tartufo,
Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
2 Acciughe Sott''olio,
1 Macinata Pepe','Scaldare l''olio in una padella, unire gli spicchi d''aglio, togliere dal fuoco, aggiungere la crema di tartufo e mescolare bene. Rimettere sul fuoco, amalgamarvi le acciughe precedentemente pulite e diliscate. Farle disfare con una forchetta a fuoco dolce poi togliere dal fuoco. Lessare le tagliatelle al dente in acqua salata, scolarle e condirle in una terrina con la salsa al tartufo e 1 macinata di pepe.',2266);
INSERT INTO "ricette" VALUES (25133,'Tagliatelle Alla Fontina','Primo','Formaggio Fontina',4,' -','400 G Pasta Tipo Tagliatelle All''uovo Secche,
50 G Burro,
4 Filetti D''acciughe,
100 G Formaggio Fontina,
40 G Formaggio Grana Grattugiato,
Pepe,
Sale','Fondere il burro, sciogliervi i filetti d''acciughe ridotti in poltiglia, unire la pasta cotta al dente, la fontina tagliata a dadini e, sempre mescolando, far filare il formaggio. Aggiungere il grana e una macinata di pepe.',2420);
INSERT INTO "ricette" VALUES (25134,'Tagliatelle Alla Giovannella','Primo','Pomodori',4,' -','800 G Pomodori,
200 G Carne Tritata,
400 G Pasta Tipo Tagliatelle,
1/2 Panino,
1 Uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
1/2 Cipolla,
1 Spicchio Aglio,
1/2 Bicchiere Olio D''oliva','Preparare il sugo rosolando 1/2 cipolla e 1 spicchio d''aglio in 1/2 bicchiere d''olio d''oliva. Quando la cipolla sarà imbiondita aggiungere i pomodori pelati e foglie di basilico. Cuocere a fuoco lento per 30 minuti. Preparare delle polpettine con la carne tritata impastata con 1/2 panino bagnato, 1 uovo, 1 cucchiaio di parmigiano grattugiato e sale poi friggerle a aggiungerle al sugo. Condire con le tagliatelle al dente e servire.',2807);
INSERT INTO "ricette" VALUES (25135,'Tagliatelle Alla Gricia','Primo','Guanciale Di Maiale',4,'Luogo: Lazio.','400 G Pasta Tipo Tagliatelle,
200 G Guanciale Di Maiale,
1 Manciata Formaggio Pecorino Grattugiato,
1 Pezzetto Peperoncino,
Abbondante Sale','Tagliare il guanciale a fettine non troppo sottili e ricavare delle listarelle di 2 cm di larghezza. Metterle in una padella di ferro e soffriggerle a fuoco lento finché prendono colore, unendo un pezzetto di peperoncino. In una pentola con abbondante acqua salata gettarvi le tagliatelle e cuocerle al dente; scolarle, versarle in una terrina e condirli con il guanciale e una bella manciata di pecorino.',2801);
INSERT INTO "ricette" VALUES (25136,'Tagliatelle Alla Lattuga','Primo','Insalata Lattuga',4,' -','350 G Pasta Tipo Tagliatelle,
1 Insalata Lattuga,
200 G Piselli,
1 Fetta Prosciutto,
1 Cipolla,
60 G Burro,
60 G Formaggio Grana Grattugiato,
Sale,
Pepe','Lavare la lattuga, asciugarla e tagliarla a listarelle poi cuocerla con 40 g di burro per circa 20 minuti. Tagliare il prosciutto a dadini ed affettare la cipolla, mettere il tutto in una padella con il burro e quando la cipolla sarà rosolata unire i piselli e far cuocere per 15 minuti. Unire la lattuga ai piselli, salare e pepare, se necessario aggiungere poca acqua e terminare la cottura. Cuocere la pasta e condirla con il preparato.',2607);
INSERT INTO "ricette" VALUES (25137,'Tagliatelle Alla Mozzarella','Primo','Mozzarella',4,' -','350 G Pasta Tipo Tagliatelle,
150 G Mozzarella,
100 G Prosciutto Cotto,
30 G Burro,
40 G Formaggio Grattugiato,
Burro,
Poco Pepe','Lessate le tagliatelle e conditele con la mozzarella tagliata a cubetti e il prosciutto a quadratini. Sopra distribuite fiocchetti di burro, spolverizzate con poco pepe e formaggio grattugiato.',3181);
INSERT INTO "ricette" VALUES (25138,'Tagliatelle Alla Mozzarella (2)','Primo','Mozzarella',4,' -','500 G Pasta Tipo Tagliatelle Fresche,
150 G Mozzarella,
100 G Prosciutto Cotto,
50 G Burro,
Sale,
Formaggio Grattugiato','Mettere a cuocere le tagliatelle in acqua salata a bollore per 5-10 minuti. Mescolare la mozzarella a dadini al prosciutto cotto tagliato a strisce. Condire le tagliatelle, appena sgocciolate e caldissime, con il burro fresco. Aggiungere la mozzarella, il prosciutto e un po'' di formaggio grattugiato. Mescolare e servire con altro formaggio grattugiato.',3179);
INSERT INTO "ricette" VALUES (25139,'Tagliatelle Alla Panna E Rosmarino','Primo','Rosmarino',4,' -','400 G Pasta Tipo Tagliatelle,
6 Cucchiai Olio D''oliva Extra-vergine,
1 Manciata Aghi Di Rosmarino Tritati Finemente,
Formaggio Grana Grattugiato,
4 Cucchiai Panna Da Cucina,
Sale','Mentre cuoce la pasta, scaldare a fuoco medio in una grande padella l''olio, quindi versarvi il rosmarino. Lasciar insaporire per una decina di secondi e poi spegnere il fuoco. Aggiungere la panna, salare e mescolare. Scolare le tagliatelle lasciandole un po'' umide e versarle nella padella. Unire il grana e far saltare il tutto velocemente e a fuoco molto alto. Servire subito.',2575);
INSERT INTO "ricette" VALUES (25140,'Tagliatelle Alla Russa','Primo','Granchio',4,' -','250 G Pasta Tipo Tagliatelle,
1 Scatola Granchio Rosso,
25 Cl Panna,
Sale,
Pepe,
Burro,
1 Cucchiaino Vodka','E'' un piatto molto raffinato e un po'' costoso, di gusto molto delicato, che potrà essere scelto per una occasione un po'' speciale. Fate bollire l''acqua in una casseruola, salatela e mentre cuociono le tagliatelle preparate il sugo. In una larga pirofila o in un tegame sufficientemente bello da essere portato in tavola fate sciogliere un pezzetto di burro, aggiungete la panna mescolando sempre, salate e pepate e unite il granchio spezzettato con un forchetta, con un cucchiaino di vodka. Prima di aggiungere il granchio controllate che non ci siano le sottili cartilagini in mezzo alla polpa. Lasciate sobbollire delicatamente per qualche minuto, scolate le tagliatelle e aggiungetele al sugo mescolando e facendo assorbire bene. Tempo: 15 minuti',2954);
INSERT INTO "ricette" VALUES (25141,'Tagliatelle Alla Sogliola','Primo','Filetti Di Sogliola',4,' -','120 G Filetti Di Sogliola,
2 Cucchiai Prezzemolo Tritato,
1/2 Limone,
1/2 Limone (succo),
Sale,
Pepe Bianco','Pulite i filetti da pelle e lische, cuoceteli in acqua bollente salata per 5 minuti con il mezzo limone, toglieteli dall''acqua e sbriciolateli nel frullatore. Condite con olio d''oliva, un po'' di prezzemolo tritato, il succo di limone e una macinata di pepe bianco. Cuocete le tagliatelle in abbondante acqua salata, scolate al dente e conditele col sugo di sogliola. Guarnite col prezzemolo tritato rimasto e servite ben caldo.',121);
INSERT INTO "ricette" VALUES (25142,'Tagliatelle Alle Erbe','Primo','Pomodori',4,' -','350 G Pasta Tipo Nidi Di Tagliatelle,
1 Trito Aromatico Fresco (prezzemolo, Timo, Origano, Rosmarino, Basilico),
4 Pomodori Maturi,
Formaggio Parmigiano Grattugiato,
40 G Burro,
80 G Olio D''oliva Extra-vergine,
Sale,
Pepe In Grani','Mettere a bollire l''acqua in una grande pentola. Nel frattempo riscaldare circa 80 g d''olio in una padella larga e porre su fiamma abbastanza vivace. Aggiungere le erbe tritate (circa un cucchiaino per ogni tipo di erba), i pomodori pelati, privati dei semi, ridotti a dadini, sale, pepe e lasciare cuocere per un minuto circa. Salare l''acqua, buttarvi le tagliatelle e scolarle al dente. Versare nella padella la pasta, 40 g di burro ammorbidito e 2 cucchiaiate di formaggio grattugiato. Mescolare bene assieme alle erbe. Trasferire la preparazione in un piatto di portata caldo e guarnire con un pizzico di prezzemolo. Servire subito, portando in tavola una ciotolina di parmigiano grattugiato.',2800);
INSERT INTO "ricette" VALUES (25143,'Tagliatelle Alle Melanzane','Primo','Melanzane',4,' -','280 G Pasta Tipo Tagliatelle,
2 Melanzane,
250 G Pomodori Pelati,
100 G Ricotta Dura,
10 Foglie Basilico,
1 Spicchio Aglio,
Olio D''oliva,
1 Pizzico Sale,
1 Pizzico Pepe','Lavate e asciugate le melanzane. Tagliatele a fettine senza sbucciarle e friggetele in olio abbondante. In un tegame scaldate due cucchiai d''olio, insaporitevi uno spicchio d''aglio intero e i pomodori spezzettati. Dopo 10 minuti eliminate l''aglio. Lessate le tagliatelle in abbondante acqua salata, scolatele al dente e disponetele in una pirofila. Conditele con la ricotta grattugiata e la salsa di pomodoro cui avete aggiunto un pizzico di sale, uno di pepe e metà basilico tritato. Sulla superficie delle tagliatelle adagiate le fette di melanzane fritte tenute ben in caldo e cospargete foglioline intere di basilico. Vini di accompagnamento: Soave DOC, Colli Martani Grechetto DOC, Taburno Bianco DOC.',2036);
INSERT INTO "ricette" VALUES (25144,'Tagliatelle Alle Melanzane (2)','Primo','Melanzane',4,' -','400 G Pasta Tipo Tagliatelle Fresche,
2 Melanzane,
80 G Prosciutto Cotto,
1 Spicchio Aglio,
Prezzemolo,
1 Cucchiaino Concentrato Di Pomodoro,
Panna,
Formaggio Grattugiato,
Burro,
Sale,
Pepe','Tagliate le melanzane a cubetti, sbollentateli, scolateli. In una padella sciogliete circa 50 g di burro, rosolatevi lo spicchio d''aglio e il prezzemolo tritati; unite il prosciutto a dadini, fate insaporire e aggiungete i cubetti di melanzana; salate, pepate, colorate con un cucchiaino di concentrato diluito in un po'' d''acqua. Cuocete un quarto d''ora, poi amalgamate con la panna. Lessate le tagliatelle, conditele con il sugo, servite con il formaggio.',3280);
INSERT INTO "ricette" VALUES (25145,'Tagliatelle Alle Noci','Primo','Noci',4,' -','400 G Pasta Tipo Tagliatelle,
150 G Gherigli Di Noci,
Olio D''oliva,
2 Spicchi Aglio,
1 Mazzetto Prezzemolo,
Formaggio Parmigiano Grattugiato,
Sale','Tritare di gherigli di noci e gli spicchi d''aglio, quindi farli insaporire per qualche minuto a fuoco basso in un tegame con qualche cucchiaio di olio. Cuocere le tagliatelle, scolarle e versarle in una ciotola. Condirle con la salsa e abbondante parmigiano, cospargere con prezzemolo tritato, mescolare e servire subito.',3566);
INSERT INTO "ricette" VALUES (25146,'Tagliatelle Alle Noci (2)','Primo','Noci',4,' -','2 Pugni Noci Sgusciate,
1 Pugno Pinoli,
2 Cucchiai Olio D''oliva,
Prezzemolo,
400 G Pasta Tipo Tagliatelle','Frullare le noci e i pinoli o passarli al setaccio dopo averli pestati nel mortaio. Farli soffriggere nell''olio per pochi minuti con il prezzemolo tritato. Salare. Cuocere le tagliatelle e condirle con la salsa.',2825);
INSERT INTO "ricette" VALUES (25147,'Tagliatelle Alle Noci (3)','Primo','Noci',4,' -','500 G Pasta Tipo Tagliatelle,
1/2 Cipolla,
10 Noci,
400 G Funghi Freschi,
1 Cucchiaio Prezzemolo Tritato,
150 G Panna,
40 G Burro,
Sale,
Pepe','In una casseruola soffriggere per qualche minuto la cipolla sbucciata e tritata con 40 g di burro. Unire i funghi, mondati, lavati rapidamente, asciugati e affettati e il prezzemolo. Salare, pepare e cuocere con coperchio per 20 minuti. Sgusciare le noci e privarle della pellicina; tritarle e aggiungerle ai funghi. Dopo qualche minuto di cottura unire la panna e togliere dal fuoco. Condire le tagliatelle cotte al dente con la salsa di funghi e noci e servire.',3505);
INSERT INTO "ricette" VALUES (25148,'Tagliatelle Alle Noci Con Arrosto Di Maiale','Primo','Noci',6,'Luogo: Trentino Alto-Adige. Cottura: 180 minuti.','Pasta Tipo Tagliatelle,
1000 G Fesa Di Maiale,
100 G Gherigli Di Noci,
100 G Panna Da Cucina,
Burro,
Aromi (salvia, Rosmarino, 1 Foglia Di Alloro)','Le tagliatelle devono essere fresche: per condirle si userà la salsa dell''arrosto. Preparare l''arrosto. Quando è ben cotto, toglierlo dal tegame e metterlo su un tagliere. Quando è freddo, tagliarlo a fettine sottili. Nel tegame con il sugo ben caldo aggiungere un bel pugno di noci tritate in modo sottile e 100 g di panna, senza mescolare. Mettere il tegame in forno i far dorare fino a quando si forma una leggera crosta (circa 5 minuti). Con un po'' di questa salsa condire le tagliatelle, aggiungendo qualche fiocchetto di burro. Se nel tegame è rimasta poca salsa, aggiungere noci, un po'' di burro e panna e rimettere in forno. Aggiungere una per volta le fettine di arrosto in modo che la salsa bagni i due lati della fetta. Rimettere in forno per alcuni minuti il tegame coperto con una carta stagnola.',5499);
INSERT INTO "ricette" VALUES (25149,'Tagliatelle Alle Rose Rosa','Primo','Rose Rosa',4,' -','350 G Pasta Tipo Tagliatelle (nidi),
200 G Panna Da Cucina,
150 G Prosciutto Cotto (fette Da 150 G),
70 G Burro,
Petali Di Rose Rosa Non Trattate,
Sale','Sciogliere il burro in una padella, aggiungere il prosciutto tritato grossolanamente e farlo insaporire. Unire la panna, i petali di rosa tagliati a julienne (tranne alcuni, i più belli che serviranno per decorare) e le tagliatelle cotte al dente; bagnarle con un mestolino della loro acqua di cottura, facendole mantecare in questo prezioso sugo. Decorare il piatto con i petali di rosa tenuti da parte.',2886);
INSERT INTO "ricette" VALUES (25150,'Tagliatelle Allo Speck','Primo','Speck',4,' -','400 G Pasta Tipo Tagliatelle,
400 G Pomodori Pelati,
100 G Speck (fette Da 50 G),
4 Cucchiai Olio D''oliva,
1 Noce Burro,
Sale,
Pepe','Scolare i pelati, in modo da eliminare il liquido di conservazione. Tagliare lo speck a pezzettini e farli soffriggere in una padella con il burro per qualche minuto. Intanto cuocere le tagliatelle al dente in acqua salata. Versare l''olio in una padella, farlo scaldare e unire i pomodori e cuocerli a fuoco vivo per pochi minuti. Scolare le tagliatelle, metterle in una terrina, versarvi sopra lo speck, mescolare bene, unendo i pomodori e il pepe.',3618);
INSERT INTO "ricette" VALUES (25151,'Tagliatelle Allo Speck E Trevigiana','Primo','Speck',4,' -','250 G Pasta Tipo Tagliatelle (nidi),
100 G Speck,
3 Cespi Radicchio Rosso Di Treviso,
1 Cipolla,
1 Dado,
Formaggio Parmigiano Grattugiato,
1 Goccio Olio D''oliva,
1 Pizzico Sale','Affettare sottilmente la cipolla e farla soffriggere con appena un goccio d''olio d''oliva e un pizzico di sale. Lavare e tagliare a strisce il radicchio; ridurre a listerelle lo speck. Aggiungere il radicchio alla cipolla del soffritto e cuocerlo con un goccio d''acqua e un po'' di dado. Soffriggere lo speck, invece, a parte. Lessare le tagliatelle al dente, unirle al radicchio, completare con lo speck, il formaggio grattugiato e saltarle in padella, eventualmente bagnando il tutto con un mestolino dell''acqua di cottura della pasta.',1542);
INSERT INTO "ricette" VALUES (25152,'Tagliatelle Allo Storione','Primo','Storione',4,' -','250 G Pasta Tipo Tagliatelle All''uovo,
150 G Storione,
4 Cucchiai Olio D''oliva,
2 Porri Piccoli,
2 Pomodori Perini,
Sale','In un tegame scaldate l''olio, insaporitevi i porri tagliati a fettine molto sottili e quando queste sono diventate traslucide unite lo storione a dadini. Mescolate e dopo due minuti e aggiungete i pomodori spellati e spezzettati. In una pentola portate a bollore l''acqua salata, cuocetevi le tagliatele al dente, scolatele, rovesciatele sull''intingolo di storione. Mescolate velocemente e servite.',2602);
INSERT INTO "ricette" VALUES (25153,'Tagliatelle Allo Zafferano','Primo','Zafferano',4,' -','400 G Pasta Tipo Tagliatelle,
400 G Pisellini,
30 G Burro,
1 Bustina Zafferano,
1 Cipolla Media,
Sale','Passare i piselli nel burro insieme alla cipolla tritata sottilmente, cuocere a fuoco dolce per 10 minuti. Sciogliere lo zafferano in abbondante acqua salata e cuocervi la pasta. Scolarla al dente, condirla con una noce di burro, aggiungere i piselli, mescolare con cura e servire subito.',2047);
INSERT INTO "ricette" VALUES (25154,'Tagliatelle Benito Mussolini','Primo','Cappone',4,' -','2 Uova,
300 G Farina,
Brodo,
1/2 Cappone,
200 G Verdure Da Brodo (sedano, Carote),
1 Tartufo Nero,
10000 Cl Acqua','Mettere le uova con il tartufo, almeno 2 giorni prima, in modo che le uova prendano l''odore del tartufo. Sistemare la farina a fontana, inserire le uova e fare l''impasto, poi tirare la sfoglia e farla seccare. Infine tagliare le tagliatelle. Pulire bene il cappone ed immergerlo in acqua fredda insieme agli aromi. Fare bollire a fuoco vivo per 5 minuti; schiumarlo e abbassare la temperatura del brodo fino a 88 gradi; per almeno 3 ore fare sobbollire schiumando. Infine passare tutto all''etamine, aggiustare di sale e dividere: 1\2 litro per saltare le tagliatelle e il restante per la cottura.',3564);
INSERT INTO "ricette" VALUES (25155,'Tagliatelle Burro, Salvia E Noci','Primo','Salvia',6,' -','600 G Pasta Tipo Tagliatelle,
50 G Burro,
2 Rametti Salvia,
6 Cucchiai Formaggio Parmigiano,
6 Cucchiai Noci Tritate (200 G Di Gherigli Di Noci)','Mettere sul fuoco una pentola con 200 cl di acqua ed 1 pugnetto di sale. Quando l''acqua bolle, unire le tagliatelle, mescolare e far cuocere. Intanto, sgusciare le noci e tritarle. Mettere in un tegamino il burro e la salvia, far sciogliere il burro e rosolare la salvia. Scolare la pasta al dente e condirla con il burro e salvia, il parmigiano e le noci, mescolando il tutto.',4378);
INSERT INTO "ricette" VALUES (25156,'Tagliatelle Carciofi E Prosciutto','Primo','Carciofi',4,' -','400 G Pasta Tipo Tagliatelle,
100 G Prosciutto Cotto,
3 Carciofi,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
4 Cucchiai Olio D''oliva,
50 G Burro,
30 G Formaggio Parmigiano Grattugiato,
1 Limone,
Sale,
Pepe','Cuocere i carciofi a spicchi nell''olio a fuoco lento con un trito di aglio e prezzemolo, sale e pepe. Saltare in padella il prosciutto a dadini con 30 g di burro. Lessare le tagliatelle, scolarle al dente e condirle con il burro, i carciofi, il prosciutto e il parmigiano. Mescolare e servire subito.',3921);
INSERT INTO "ricette" VALUES (25157,'Tagliatelle Co'' Du Scampi','Primo','Scampi',4,' -','300 G Pasta Tipo Tagliatelle,
2 Scatola Pomodori Pelati,
2 Cucchiai Panna Da Cucina,
Olio D''oliva,
Aglio,
Peperoncino,
Prezzemolo,
3 Scampi','Fate appena soffriggere in 5 cucchiai d''olio un paio di spicchi d''aglio, togliete gli spicchi appena sono coloriti. Spegnete il fuoco e lasciate raffreddare un attimo l''olio. Dopo poco aggiungete i pelati ben sgocciolati, aggiungete una buona spruzzata di peperoncino il sale e gli scampi schiacciati, di modo che la salsa si insaporisca rapidamente. Riaccendete il fornello in modo vivace, la salsa non deve cuocere più di tanto. 5-10 minuti possono bastare. Togliete gli scampi ed aggiungete un paio di cucchiai di panna, meglio poca che troppa, amalgamate bene. Nel frattempo le tagliatelle saranno cotte, scolatele e conditele con la salsa, aggiungendo una buona manciata di prezzemolo trito. Bon''appetito e mi raccomando mettete il vino a tavola, specie se avete esagerato col peperoncino!',2163);
INSERT INTO "ricette" VALUES (25158,'Tagliatelle Col Prosciutto Cotto','Primo','Prosciutto Cotto',4,' -','400 G Pasta Tipo Tagliatelle,
100 G Prosciutto Cotto,
50 G Burro,
30 G Formaggio Parmigiano,
Panna Liquida,
Sale','Fondere il burro in una grossa padella, aggiungere il prosciutto a dadini. Lessare le tagliatelle, scolarle e versarle nella padella con il burro ed il prosciutto. Aggiungere il formaggio grattugiato e la panna. Mescolare tutto e tenere sul fuoco per qualche minuto.',2597);
INSERT INTO "ricette" VALUES (25159,'Tagliatelle Con Asparagi E Pomodori Secchi','Primo','Asparagi',4,' -','350 G Pasta Tipo Nidi Di Tagliatelle,
300 G Asparagi Lessi,
1 Scalogno,
1 Mazzetto Insalata Rucola,
1 Peperoncino,
12 Pomodorini Secchi,
Formaggio Parmigiano A Scaglie,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Soffriggere lo scalogno nell''olio con il peperoncino. Unire i pomodorini secchi, gli asparagi a tocchetti, sale, pepe e far insaporire qualche minuto. Unire la rucola tritata e la pasta cotta al dente; aggiungere un mestolino della sua acqua di cottura, saltarla a fuoco vivo e finire con le scaglie di parmigiano. Servire subito.',2666);
INSERT INTO "ricette" VALUES (25160,'Tagliatelle Con Broccoli, Manzo Marinato E Ricotta Al Forno','Primo','Rosa Di Manzo',4,' -','200 G Farina,
1 G Zafferano,
2 Uova,
200 G Cime Di Broccoli,
50 G Ricotta Infornata,
1 Spicchio Aglio,
100 G Rosa Di Manzo,
Olio D''oliva,
Sale,
Pepe','Stendere una sfoglia di farina, uova e zafferano. Tagliarla a mo'' di tagliatelle e cuocerla in acqua bollente salata assieme alle cime di broccoli. Scolare e saltare il tutto in padella con poco olio ed uno spicchio d''aglio. Nel frattempo stracuocere la rosa di manzo, marinarla con olio, sale e pepe. Stracciarla e servirla sopra la pasta assieme alla ricotta grattugiata.',1813);
INSERT INTO "ricette" VALUES (25161,'Tagliatelle Con Carciofi','Primo','Carciofi',4,' -','280 G Pasta Tipo Tagliatelle Fresche,
5 Pomodori Pelati,
4 Carciofi,
1 Limone,
1 Spicchio Aglio,
Basilico,
1 Ciuffetto Prezzemolo,
Formaggio Grattugiato,
Olio D''oliva,
1 Pizzico Sale','Pulite i carciofi scartando le foglie più dure. Strofinateli con il succo di limone perché non anneriscano. Lessateli in acqua bollente leggermente salata per 7 minuti. Scolate e tagliateli a spicchi piuttosto sottili. In una padella scaldate l''olio, fatevi dorare lo spicchio d''aglio, poi eliminatelo e insaporitevi i carciofi. Aggiungete alcune foglie di basilico intere, un ciuffetto intero di prezzemolo, un pizzico di sale, i pelati ben sgocciolati e tagliati a dadini e tenete sul fuoco a fiamma bassa. Lessate le tagliatelle, scolatele al dente e trasferitele nella padella dei carciofi. Aggiungete, se occorre, alcuni cucchiai dell''acqua di cottura della pasta. Condite con un giro d''olio versato a filo e il formaggio. Eliminate il ciuffetto di prezzemolo, passate sul piatto da portata tenuto in caldo e servite. Vini di accompagnamento: Friuli Aquileia Traminer Aromatico DOC, Genzano Bianco (anche Novello) DOC, Vermentino Di Sardegna DOC.',2312);
INSERT INTO "ricette" VALUES (25162,'Tagliatelle Con Carote E Speck','Primo','Carote',4,'Preparazione: 20 minuti.','Pasta Tipo Tagliatelle,
Speck Tagliato Spesso,
Carote,
Prezzemolo,
Olio D''oliva,
1 Pizzico Sale','Pelate le carote, tagliatele a dadini e mettetele a bollire con un pizzico di sale. Fate bollire l''acqua per la pasta e contemporaneamente mettete l''olio in un tegame largo e basso, aggiungete lo speck tagliato a dadini e fatelo soffriggere a fuoco basso. Aggiungete poi le carote a dadini e fatele passare sempre a fuoco basso mescolando. Quando l''acqua bolle, buttate le tagliatelle, tenendo presente che di solito hanno un tempo di cottura piuttosto breve. Quando sono cotte scolatele e conditele con il sugo di carote e il prezzemolo.',2003);
INSERT INTO "ricette" VALUES (25163,'Tagliatelle Con Fasolari E Carciofi','Primo','Fasolari',4,' -','200 G Farina Di Semola,
2 Uova,
1 Carciofo,
10 Fasolari,
50 G Olive,
1 Spicchio Aglio,
1/2 Cipolla Di Tropea,
Olio D''oliva Extra-vergine,
Sale','Far aprire i fasolari e sgusciarli conservando l''acqua. Rosolare l''aglio, unire i carciofi e le olive, saltare brevemente, aggiungere i fasolari e alla fine la loro acqua. Lessare la pasta e saltarla nel sugo. Servire guarnendo con anelli di cipolla e olio.',2120);
INSERT INTO "ricette" VALUES (25164,'Tagliatelle Con Gamberi','Primo','Gamberi',4,' -','250 G Pasta Tipo Tagliatelle,
1000 G Gamberi,
500 G Brodo Di Pesce,
70 G Olio D''oliva,
300 G Pomodori Maturi,
Prezzemolo,
2 Spicchi Aglio,
50 G Scalogno,
Scorza D''arancia Grattugiata','Pulite i gamberoni e tagliate i pomodori a pezzetti. Soffriggete aglio e scalogno nell''olio, togliendoli appena saranno rosolati, quindi versate i gamberi i pomodori e il brodo di pesce. Salate, pepate e aggiungete la scorza di arancia. Cuocete la salsa 5 minuti, toglietela dal fuoco e unite il prezzemolo tritato Condite la pasta e servite ben caldo.',2580);
INSERT INTO "ricette" VALUES (25165,'Tagliatelle Con Granchio Di Mare','Primo','Granchio Di Mare',4,' -','200 G Farina,
1 Uovo,
1 Granchio Di Mare,
100 G Pomodori Pelati,
1/2 Bicchiere Vino Bianco,
1 Spicchio Aglio,
Peperoncino,
Olio D''oliva Extra-vergine,
Sale','Levare la parte superiore del granchio, spolparlo e tagliarlo a pezzi. Rosolarlo e bagnarlo con il vino e aggiungere i pelati cuocendo per 10 minuti circa. Preparare la pasta, lessarla e scolarla nel sugo. Servire adagiando la pasta nel guscio del granchio sbollentato e cospargere con il prezzemolo.',1616);
INSERT INTO "ricette" VALUES (25166,'Tagliatelle Con Il Sugo Di Sogliola','Primo','Sogliola',4,' -','1 Sogliola Grande,
100 G Salsa Di Pomodoro Già Pronta,
Sedano,
Carota,
Cipolla,
1 Spicchio Scalogno Intero,
100 G Burro,
2 Cucchiai Vino Bianco,
Alcune Foglie Basilico,
350 G Pasta Tipo Tagliatelle All''uovo Secche','In una padella capiente sciogliere una noce di burro e adagiarvi la sogliola infarinata e pulita dalle interiora. Bagnarla con il vino e coprirla con un coperchio. A metà cottura spegnere il fuoco e aiutandosi con forchetta e cucchiaio privare la sogliola della carne mettendola in un tegame a parte, aggiungere un bicchiere d''acqua e fare cuocere per circa quindici minuti i resti della sogliola, sempre a tegame coperto. Ad operazione terminata, filtrare il brodo ottenuto con un colabrodo molto fine nel tegame precedentemente preparato con la polpa, aggiungere la salsa di pomodoro e il basilico tagliato a striscioline e salare. Lasciare cuocere a fuoco lento per circa quindici minuti, spegnere il fuoco e aggiungere il rimanente burro.',3224);
INSERT INTO "ricette" VALUES (25167,'Tagliatelle Con Olive','Primo','Olive Verdi',4,' -','300 G Pasta Tipo Tagliatelle All''uovo Fresche,
24 Olive Verdi,
Alcune Foglie Basilico,
50 G Burro,
Sale','Snocciolate le olive. Sciogliete il burro a bagnomaria. Cuocete in abbondante acqua salata le tagliatelle, scolatele su un piatto da portata, conditele col burro fuso e le olive, profumate con qualche fogliolina di basilico e servite.',1672);
INSERT INTO "ricette" VALUES (25168,'Tagliatelle Con Pesce','Primo','Pesce Misto',4,' -','360 G Pasta Tipo Tagliatelle,
600 G Pesce Misto (pesce San Pietro, Scorfano),
300 G Pomodori,
2 Cipolle,
Prezzemolo,
1 Gambo Sedano,
1/2 Bicchiere Olio D''oliva,
Sale','Tagliate a fettine una cipolla e rosolatela insieme all''olio. Lavate i pomodori e setacciateli, poi uniteli alla cipolla; salate e lasciate cuocere. Portate ad ebollizione in 3 litri di acqua salata un''altra cipolla tagliata in 4, il sedano e il prezzemolo. Intanto polite il pesce e quando l''acqua bollirà buttatelo nella pentola e lasciatelo cuocere. A fine cottura togliete il pesce dall''acqua, che conserverete, e togliete anche la cipolla il sedano e il prezzemolo. Sfilettate il pesce e unitelo alla cipolla e ai pomodori che stanno rosolando e lasciate cuocere per 15 minuti. Cuocete la pasta nel brodo di cottura del pesce, scolatela e unitela al pesce.',2438);
INSERT INTO "ricette" VALUES (25169,'Tagliatelle Con Ragù E Ricotta','Primo','Ricotta',4,'Luogo: Sicilia.','500 G Pasta Tipo Tagliatelle,
150 G Carne Di Manzo Tritata,
150 G Carne Di Maiale Tritata,
300 G Ricotta Fresca,
100 G Formaggio Caciocavallo Grattugiato,
1 Bicchiere Vino Rosso,
2 Cipolle,
800 G Pomodori Maturi,
Olio D''oliva,
Sale,
Pepe','Tritare e soffriggere la cipolla, unire le carni tritate e sfumare con il vino rosso. A parte, in un tegame, mettere i pomodori a pezzi, la cipolla e il sale. Cuocere per 20 minuti circa. Poi unire la salsa alla carne rosolata e lasciar addensare, regolando di sale e pepe. Nel frattempo cuocere le tagliatelle, scolarle e passarle nel condimento. Aggiungere la ricotta sciolta in poca acqua calda e il caciocavallo grattugiato.',4240);
INSERT INTO "ricette" VALUES (25170,'Tagliatelle Con Ricotta','Primo','Ricotta',4,' -','400 G Pasta Tipo Tagliatelle All''uovo,
2 Zucchine,
200 G Ricotta,
Olio D''oliva,
1 Presa Sale,
1 Manciata Pepe','Lavare le zucchine, poi raschiarle leggermente, spuntarle, asciugarle e tagliarle a rondelle. Friggerle in una padella con 1 bicchiere d''olio, scolarle con una paletta forata appena saranno leggermente dorate e ten