l pesce e l''insalata, completando con il secondo cucchiaino di olio.',282);
INSERT INTO "ricette" VALUES (7066,'Crema Di Broccoletti','Antipasto','Broccoletti',4,' -','250 G Cimette Di Broccoletti,
2 Spicchi Aglio,
4 Uova,
60 Cl Brodo Vegetale,
1 Spruzzata Vino Bianco,
Sale,
Poco Olio D''oliva,
Alcuni Crostini Di Pane','Rosolare le cimette tagliate a pezzetti in poco olio con l''aglio e una spruzzata di vino. Aggiungere metà brodo e portare a cottura. Far raffreddare e frullare il tutto. Rimettere sul fuoco e aggiungere le uova battute con il restante brodo, aggiustare di sale e cuocere per pochi minuti. Servire la crema ben calda sui crostini di pane.',1419);
INSERT INTO "ricette" VALUES (7067,'Crema Di Cacao E Vaniglia','Bevande','Vaniglia',4,' -','100 G Cacao In Polvere,
500 G Zucchero In Polvere,
500 G Acqua,
1/2 G Vaniglina,
250 G Alcool A 95 Gradi','Si scalda, senza far bollire, 1/2 bicchiere d''acqua, alla quale lentamente si aggiunge il cacao in polvere, mescolando in continuazione con un cucchiaio di legno, così da ottenere una crema senza grumi. Aggiungere allora lo zucchero poco per volta; si formerà una crema omogenea che lascerete raffreddare. Nel frattempo in una terrina di coccio diluite la vaniglia nell''alcool e unitela alla crema che avrete preparato. Consumate il liquore così com''è in piccoli bicchierini,
oppure diluitelo nel latte: sarà per voi un''eccellente energetico.',2711);
INSERT INTO "ricette" VALUES (7068,'Crema Di Cacao E Vaniglia (2)','Bevande','Cacao',4,' -','200 G Alcool A 95 Gradi,
100 G Cacao In Polvere,
500 G Zucchero In Polvere,
500 G Acqua,
1/2 G Vaniglia','Si scalda senza far bollire mezzo bicchiere di acqua, alla quale lentamente si aggiunge il cacao in polvere, mescolando in continuazione con un cucchiaio di legno, così da ottenere una crema senza grumi. Aggiungete allora lo zucchero a dosi minime: si formerà una crema omogenea che lascerete raffreddare. Nel frattempo in una terrina di coccio diluite la vaniglia nell''alcool e uniteli alla crema che avete preparato. Consumate il liquore in piccoli bicchierini oppure diluitelo
nel latte.',2631);
INSERT INTO "ricette" VALUES (7069,'Crema Di Cannellini','Primo','Fagioli Cannellini',4,'Preparazione: 120 minuti più il tempo di macerazione dei fagioli.','200 G Fagioli Cannellini Secchi,
250 G Cimette Di Broccoletti,
2 Spicchi Aglio,
1 Foglia Alloro,
10 Cl Olio D''oliva Extra-vergine,
1/2 Carota,
1 Cipolla Piccola,
1/2 Gambo Sedano,
2 Filetti D''acciughe Sott''olio,
1 Peperoncino,
Sale,
Poco Pepe','Far macerare i fagioli in acqua fredda per 12 ore. Spuntare la carota e pelarla; sbucciare la cipolla e gli spicchi d''aglio; privare il sedano dei filamenti e lavare tutti gli altri ortaggi. Scolare i fagioli, metterli in una pentola, aggiungere la carota e il sedano divisi a pezzi, uno spicchio d''aglio e l''alloro; coprirli con abbondante acqua fredda e farli cuocere, a fuoco moderato, per 70 minuti circa; salarli quasi al termine della cottura e aggiungere un poco d''acqua calda se necessario. Al termine della cottura, l''acqua dovrà risultare quasi completamente assorbita. Passare quindi al passaverdura i fagioli con il liquido di cottura rimasto. Lavare le cimette di broccoletti e farle scottare in abbondante acqua salata in ebollizione per 2-3 minuti. In una casseruola con due cucchiai di olio far appassire la cipolla tritata finemente senza lasciarla colorire; aggiungere il passato di fagioli, mescolare e versarvi un poco di acqua calda (mezzo litro circa), portare a ebollizione la crema e farla bollire per qualche minuto, mescolando spesso; insaporirla infine con un pizzico di sale se necessario. In una padella con due cucchiai di olio d''oliva extra-vergine, far imbiondire leggermente l''aglio rimasto con il peperoncino, unirvi i filetti d''acciuga spezzettati e farli sciogliere mescolandoli spesso; aggiungere le cimette di broccoletti e farle insaporire per qualche minuto. Versare la crema di cannellini molto calda nei singoli piatti e distribuirvi le cimette di broccoletti; irrorare con l''olio rimasto e cospargere con un poco di pepe macinato al momento.',1250);
INSERT INTO "ricette" VALUES (7070,'Crema Di Carciofi','Salsa','Carciofi',4,' -','500 G Carciofi,
1 Limone (succo),
40 G Formaggio Grana,
40 G Farina,
50 Cl Latte Scremato,
500 G Acqua,
2 Dadi Di Carne,
1 Pizzico Noce Moscata,
1 Pizzico Sale,
1 Pizzico Pepe','Mondare i carciofi, tagliarli a spicchi e metterli nell''acqua e succo di limone. Stemperare a freddo la farina nel latte, in modo che non si formino grumi e aggiungere l''acqua. Portare a ebollizione a fuoco moderato il composto, quindi aggiungere i dadi, il grana e 1 pizzico di sale, pepe e noce moscata.',581);
INSERT INTO "ricette" VALUES (7071,'Crema Di Carciofi (2)','Primo','Carciofi',4,' -','6 Carciofi,
200 G Patate,
150 Cl Brodo Di Pollo,
1 Tuorlo D''uovo,
65 G Burro,
1 Cipolla,
1 Costa Sedano,
Abbondante Formaggio Grattugiato,
Sale,
Pepe','In una pentola sciogliete 45 g di burro e fatevi appassire una costa di sedano tritato e la cipolla tagliata a fettine sottili. Aggiungete la parte più tenera dei carciofi e le patate divise a spicchi, lasciate stufare per 5 minuti. Bagnate con il brodo, regolate sale e pepe, cuocete lentamente per 40 minuti circa a pentola coperta. Frullate a lungo il tutto. Regolate sale e pepe. Scaldate. Lontano dal fuoco legate la minestra con un tuorlo prima amalgamato con il restante burro. Servite la crema in singole fondine con abbondante formaggio grattugiato. Vini di accompagnamento: Aquileia Traminer Aromatico DOC, Marino DOC, Vermentino Di Sardegna DOC.',1818);
INSERT INTO "ricette" VALUES (7072,'Crema Di Carciofi (3)','Contorno','Carciofi',4,' -','10 Carciofi,
400 G Besciamella Fresca,
50 Cl Brodo Vegetale,
50 G Burro,
Sale,
Pepe','Pulite i carciofi, tagliateli a metà eliminando le barbe interne e le punte. Tenerli in acqua e limone per 5-6 minuti, lessateli in acqua bollente e salata per 10 minuti circa. Passateli al setaccio tenendone 3 da parte, cuocete la purea ottenuta per 5 minuti con la besciamella diluita e il brodo. Tagliate a dadini i 3 carciofi rimasti ed uniteli alla crema.',1178);
INSERT INTO "ricette" VALUES (7073,'Crema Di Carciofi Alla Pentola A Pressione','Primo','Carciofi',4,' -','4 Carciofi,
40 G Burro,
40 G Farina Bianca,
50 Cl Latte,
50 Cl Acqua,
2 Dadi Per Brodo,
Pepe,
Sale,
Per Servire:,
Crostini Di Pane','Pulisci i carciofi liberandoli dalle foglie esterne più dure e dalle spine; tagliali a spicchi e tuffali in acqua acidulata, assieme alla parte interna dei gambi. Nella pentola a pressione fai sciogliere il burro e con la farina ed il latte prepara una besciamella. Quando questa comincia ad addensarsi, aggiungi i carciofi sgocciolati ed i dadi. Chiudi la pentola e cuoci 15 minuti dal sibilo. Al termine passa il tutto al passaverdura (meglio dei vari frullatori, perché elimini i filini delle foglie), aggiusta eventualmente di sale e pepe. Servi fumante con i crostini.',1063);
INSERT INTO "ricette" VALUES (7074,'Crema Di Carota Alle Spezie','Antipasto','Carote',4,' -','500 G Carote,
2 Spicchi Aglio,
Olio D''oliva Extra-vergine,
Aceto Di Mele,
2 Cucchiaini Cumino Pestato,
1 Cucchiaino Harissa,
1 Cucchiaino Cannella,
1/2 Cucchiaino Zenzero,
Sale Marino Integrale','Spazzolare le carote sotto acqua corrente e tuffarle in acqua bollente fino a cottura. Schiacciarle in una ciotola con i rebbi di una forchetta, incorporando a poco a poco l''aglio triturato, le spezie, l''olio, l''aceto, schiacciando e mescolando il composto fino ad ottenere una crema omogenea. Servire su crostini di pane.',885);
INSERT INTO "ricette" VALUES (7075,'Crema Di Carote','Primo','Carote',4,' -','800 G Carote,
40 G Formaggio Fontina,
50 Cl Latte,
2 Bicchieri Brodo,
1 Spicchio Aglio,
1 Pizzico Noce Moscata,
Sale,
Pepe','Mettete in una pentola le carote tagliate a pezzetti e lo spicchio d''aglio, coprite con acqua salata. Cuocete a fuoco medio e fate assorbire il liquido quasi del tutto. Frullate. Versate il composto nella pentola. Unite il brodo e il latte tiepidi, mescolate bene. Cuocete per 10 minuti o fino a ottenere una crema piuttosto densa. Regolate se occorre il sale e il pepe. Distribuite la crema in fondine individuali possibilmente calde. Cospargete sulla superficie la fontina grattugiata, un pizzico di noce moscata e uno di pepe. Passate i piatti sotto il grill. Vini di accompagnamento: Lugana DOC, Parrina Bianco DOC, Bianco D''Alcamo DOC.',697);
INSERT INTO "ricette" VALUES (7076,'Crema Di Carote Al Ginepro','Contorno','Carote',4,' -','6 Carote,
1 Mestolo Fiocchi D''avena,
1 Cipolla,
5 Bacche Di Ginepro,
2 Cucchiai Olio D''oliva Extra-vergine,
Sale Marino Integrale','Rosolare nell''olio la cipolla finemente affettata. Spazzolare e lavare le carote e tagliarle a rondelle. Unirle al soffritto e salare, quindi far brasare. A metà cottura unire 100 cl d''acqua già calda. Portare ad ebollizione e unire i fiocchi d''avena. Far cuocere 15 minuti e passare tutto nel mixer. Aromatizzare con bacche di ginepro pestate nel mortaio.',1430);
INSERT INTO "ricette" VALUES (7077,'Crema Di Carote Con Formaggio','Primo','Carote',1,'Ricetta adatta a: bambini piccoli.','2 Carote,
3 Mestoli Acqua,
1 Pizzico Sale,
1 Cucchiaio Pastina,
1 Formaggino,
1 Cucchiaino Olio D''oliva','Lessare 2 carote, tagliarle a pezzetti, metterle in 3 mestoli d''acqua con un pizzico di sale. Cuocerle per 30 minuti e passarle poi al setaccio. Rimettere quindi al fuoco e aggiungere un pò d''acqua nel caso il composto fosse troppo denso. Quando bolle gettare 1 cucchiaio di pastina. A fuoco spento aggiungere 1 formaggino ed un cucchiaino d''olio d''oliva.',268);
INSERT INTO "ricette" VALUES (7078,'Crema Di Carote E Cozze','Primo','Carote',4,' -','32 Cozze,
100 Cl Brodo Di Pollo,
700 G Carote,
70 G Burro,
1 Bicchiere Vino Bianco,
1/2 Spicchio Aglio,
1 Cucchiaio Prezzemolo Tritato,
2 Pizzichi Zucchero,
Sale','Preparate il brodo di pollo. Tagliate le due carote a dadini e fatele insaporire in una noce di burro con un pizzico di sale e uno di zucchero. Tenetele da parte. Tagliate a rondelle le altre carote, rosolatele con il rimanente burro, sale e un pizzico di zucchero. Versate il brodo sulle carote, cuocete per circa 20 minuti, poi frullatele fino a ridurle a una crema. Fate aprire le cozze ponendole in una padella con il vino e l''aglio. Appena le valve si schiudono staccate il mollusco. Fate scaldare la crema di carote, versatela in una zuppiera, aggiungete la dadolata di carote e le cozze. Cospargete con un cucchiaio di prezzemolo tritato e servite subito. Vini di accompagnamento: Soave Superiore DOC, Montecarlo Bianco DOC, Gravina DOC.',1348);
INSERT INTO "ricette" VALUES (7079,'Crema Di Castagne','Dessert','Castagne',4,' -','10 Cl Latte,
50 G Zucchero,
Sale,
1 Cucchiaino Zucchero Vanigliato,
1 Tuorlo D''uovo,
3 Fogli Gelatina,
1 Cucchiaio Rum,
25 Cl Panna Montata,
130 G Purè Di Marroni','Lasciate la gelatina a mollo in acqua fredda finché si ammorbidisce. Cuocete il latte con lo zucchero vanigliato e una presa di sale. Battete a neve i tuorli insieme con lo zucchero. Versate il latte nell''impasto con i tuorli senza mai smettere di girare e facendo in modo che assuma la consistenza di una crema. Spremete la gelatina, scioglietela nella crema calda e mettetela da parte (fredda) finché si rapprende. Montate la panna. Sbattete il purè di marroni con il rum, aggiungete 1 terzo della panna montata e la crema e mescolate bene. Unite con prudenza la panna rimasta, versate il tutto nei bicchieri e mettete al fresco.',2027);
INSERT INTO "ricette" VALUES (7080,'Crema Di Castagne (2)','Antipasto','Castagne',4,' -','1000 G Castagne,
1 Cipolla,
1 Spicchio Aglio,
1 Gambo Sedano,
Burro (o Panna),
Sale,
Pepe','Sbucciare le castagne, immergerle in acqua bollente e togliere la pellicina. Dopo aver fatto un trito con una cipolla, un gambo di sedano e uno spicchio di aglio, rosolarlo in circa 50 g di burro, quando imbiondisce aggiungere le castagne, due litri di acqua, sale e pepe a piacere. Far cuocere per circa un''ora e mezza a fuoco lento, con la pentola coperta. Passare le castagne fino ad ottenere un purè, da rimettere nel brodo di cottura. Aggiungere prima di servire un noce di burro o un cucchiaio di panna.',2603);
INSERT INTO "ricette" VALUES (7081,'Crema Di Cavolfiore','Primo','Cavolfiore',4,' -','1 Cavolfiore,
Acqua,
1 Tazza Farina Di Riso (o Farina),
Latte,
1 Tuorlo D''uovo,
Poca Panna Fresca','Fate cuocere un cavolfiore in una pentola con un po'' d''acqua; tagliatelo in seguito a mazzetti. Preparate la quantità voluta di brodo di carne; versateci l''acqua di cottura del cavolfiore e portate a ebollizione. A parte diluite una tazza di farina di riso (oppure farina ordinaria) nel latte e versate nel liquido bollente. Fate cuocere circa 30 minuti. Passate la minestra al passatutto e legate con un tuorlo d''uovo e un poco di panna fresca. Aggiungete i mazzetti di cavolfiori all''ultimo momento.',906);
INSERT INTO "ricette" VALUES (7082,'Crema Di Cavolfiore (2)','Primo','Cavolfiore',4,' -','500 G Cavolfiore Pulito,
100 G Porro,
50 G Burro,
25 G Farina Di Riso,
1 Tuorlo D''uovo,
1 Trito Di Timo E Maggiorana,
Alcuni Crostini Di Pane,
1 Dito Latte,
Brodo Vegetale,
10 Cl Panna Liquida,
Sale,
Pepe','Stufate in 30 g di burro il porro e il cavolfiore diviso a cimette; bagnate con un litro di brodo, coprite, lasciate cuocere per 30 minuti poi passate al passaverdura raccogliendo la crema in una casseruola; fatele riprendere il bollore, legatela con la farina di riso sciolta in un dito di latte freddo e proseguite l''ebollizione per 15 minuti, quindi spegnete e incorporatevi un tuorlo stemperato con 10 cl di panna. Salate, pepate, guarnite con i crostini rosolati in 20 g di burro aromatizzato con trito aromatico.',1566);
INSERT INTO "ricette" VALUES (7083,'Crema Di Cavolfiore Con Le Cozze','Primo','Cavolfiore',4,' -','1 Cavolfiore Piccolo,
1000 G Cozze,
1 Scalogno,
30 G Burro,
1/2 Bicchiere Panna,
1 Limone,
Prezzemolo,
Sale,
Pepe','Pulite il cavolfiore, separate le cimette, lavatele, sgocciolatele. Pulite bene le cozze. Mondate lo scalogno, tagliatelo a fettine sottili, fatelo appassire nel burro per 5 minuti. Aggiungete il succo del limone, il prezzemolo tritato e poi le cozze. Lasciatele aprire a fuoco basso, mescolando di tanto in tanto. Quando le valve sono ben dischiuse staccate i molluschi e teneteli al caldo. Passate il sugo di cottura al setaccio. Versatelo in un litro d''acqua calda, portate a bollore, immergetevi le cimette di cavolfiore e cuocete 15 minuti. Spegnete e frullate fino a ottenere un soffice purè. Aggiungete al composto la panna, le cozze sgusciate, salate e pepate. Scaldate per 5 minuti e servite con crostini di pane fritti. Vini di accompagnamento: Riviera Ligure Di Ponente Pigato DOC, Marino DOC, Locorotondo DOC.',1070);
INSERT INTO "ricette" VALUES (7084,'Crema Di Cavolini','Primo','Cavolini',4,' -','600 G Cavolini Di Bruxelles,
60 G Pancetta,
100 Cl Brodo Di Dado,
Formaggio Grattugiato,
Sale,
Pepe,
Alcuni Cucchiai Panna','In una padella soffriggete la pancetta tritata. Unite i cavolini lavati e tagliati a metà; mescolate e bagnate con un bicchiere d''acqua; fate cuocere per venti minuti. Togliete i cavolini e frullateli. Versate il composto ottenuto nel tegame dove c''è ancora il liquido di cottura dei cavolini, aggiungete il brodo, salate, pepate e scaldate bene. Versate in una zuppiera, aggiungete alcuni cucchiai di panna e servite con formaggio grattugiato a parte. Il sapore di questa crema è deciso, quindi meglio accertarsi in anticipo se i cavolini sono graditi agli ospiti.',1489);
INSERT INTO "ricette" VALUES (7085,'Crema Di Ceci','Antipasto','Ceci',4,' -','400 G Ceci,
3 Spicchi Aglio,
Rosmarino,
Sale,
Pepe,
Crostini Di Pane Abbrustoliti,
Brodo','Lessare i ceci, precedentemente ammollati, per 3 ore. Passarli al setaccio fino ad ottenere una crema omogenea unendo il brodo. Soffriggere in poco olio il rosmarino e l''aglio tritati, versarvi la crema di ceci e farla insaporire. Disporre i crostini nei piatti, coprire con la crema ben calda e servire.',1541);
INSERT INTO "ricette" VALUES (7086,'Crema Di Ceci (2)','Primo','Ceci',4,' -','250 G Ceci Messi A Bagno Per Una Notte,
2 Cl Tahin (pasta Di Grani Di Sesamo),
3 Spicchi Aglio,
3 Limoni (succo),
Sale,
Pepe,
Per Decorare:,
1 Cucchiaio Olio D''oliva Extra-vergine Mescolato A Prezzemolo Tritato','Scolate i ceci, metteteli in casseruola e copriteli con acqua. Fate bollire per 10 minuti a fuoco vivo e per altre 2 ore a fuoco basso. Una volta cotti scolateli e conservate 30 cl di acqua di cottura. Passare i ceci e il resto degli ingredienti, aggiungere acqua di cottura ottenendo così una consistenza cremosa. Servite con olio e prezzemolo tritato.',1141);
INSERT INTO "ricette" VALUES (7087,'Crema Di Ceci Al Gratin','Primo','Ceci',4,' -','200 G Ceci,
50 G Formaggio Fontina,
4 Fette Pancarré,
2 Cucchiai Olio D''oliva,
1 Cipolla,
1 Spicchio Aglio,
1 Rametto Rosmarino,
Sale,
Pepe','Per un giorno lasciate i ceci a bagno in acqua tiepida. Al momento di preparare la crema metteteli in una pentola con un litro e mezzo di acqua fredda e la cipolla. Ponete sul fuoco, portate a bollore, salate. Coprite e lasciate cuocere, a fuoco medio, per 2 ore. Frullate il composto a lungo. In un tegame scaldate l''olio, rosolatevi l''aglio e il rosmarino, salate, pepate. Togliete aglio e rosmarino, versate questo olio aromatizzato sulla crema di ceci. Dividetela in singole fondine e sopra adagiatevi una fetta di pane tostata. Grattugiate sul pane la fontina e tenete sotto il grill il tempo necessario perché il formaggio si sciolga e formi una crosticina dorata. Vini di accompagnamento: Dolcetto Di Ovada DOC, Elba Rosso DOC, Alezio Rosato DOC.',2179);
INSERT INTO "ricette" VALUES (7088,'Crema Di Ceci Alla Pentola A Pressione','Primo','Ceci',4,' -','600 G Ceci Già Ammollati,
3 Spicchi Aglio,
Alcune Foglie Salvia Fresca,
Pane Raffermo,
Sale,
2 Cucchiai Olio D''oliva Extra-vergine','Cuocere i ceci in pentola a pressione (10 minuti dal fischio) con 1 spicchio di aglio e qualche foglia di salvia fresca. Tenere da parte qualche cucchiaiata di ceci interi e passare al passaverdure i restanti. In una capace casseruola, soffriggere 2 spicchi di aglio e qualche foglia di salvia in 2 cucchiai di olio, unire la purea di ceci, far insaporire bene per 2/3 minuti unire i ceci interi, parte dell''acqua di cottura (regolatela secondo la densità desiderata) e cuocere a fuoco lento, coprendo con un coperchio per circa 10 minuti. Tostare il pane, strofinarlo con l''aglio e disporlo in terrine individuali, cospargere con la crema di ceci e servire.',2476);
INSERT INTO "ricette" VALUES (7089,'Crema Di Cedro Con Frutta','Dessert','Cedro',6,' -','120 G Zucchero,
8 Cl Succo Di Cedro,
3 Fogli Gelatina,
175 G Yogurth,
15 Cl Panna Montata,
350 G Frutta Fresca Tagliata A Tocchetti,
2 Cl Distillato Di Lamponi','Fate caramellare lo zucchero in una piccola casseruola con 1/5 del succo di cedro, dopodichè allungatelo con il restante succo. Sciogliete la gelatina, ammorbidita in abbondante acqua e strizzata, nel composto caldo e aggiungete lo yogurth. Lasciate raffreddare e, qualche istante prima che il composto si rapprenda, incorporatevi la panna montata. Disponete la frutta nei bicchieri, bagnatela con il distillato di lamponi, copritela con la crema e fate rassodare in frigorifero per due ore. Se volete, potete decorare la preparazione con panna e fettine di cedro.',1324);
INSERT INTO "ricette" VALUES (7090,'Crema Di Cereali Con Finocchio','Primo','Finocchio Tondo',1,'Ricetta adatta a: bambini piccoli.','250 G Brodo Vegetale,
1 Finocchio Tondo,
5 Cucchiai Crema Di Cereali Precotta,
2 Cucchiaini Formaggio Parmigiano Grattugiato,
1 Cucchiaino Olio D''oliva Extra-vergine','Mondate il finocchio delle foglie più esterne, tagliatelo a spicchi e lavatelo. Cuocetelo a vapore finché sarà tenero ma non del tutto spappolato. Passatelo al passaverdure in una casseruolina. Unite il brodo, portate ad ebollizione e versate a pioggia la crema di cereali mescolando finché si e ben stemperata. Spegnete, condite con il parmigiano e l''olio.',617);
INSERT INTO "ricette" VALUES (7091,'Crema Di Cetrioli','Primo','Cetrioli',4,' -','4 Patate,
2 Cetrioli,
1 Prugna Umeboshi,
2 Cucchiai Crema Di Mandorle,
1 Cucchiaino Tamari,
Gomasio','Mettete le patate e i cetrioli, tagliati a dadini, in acqua bollente per 10 minuti. Passatele poi nel frullatore assieme alla prugna senza nocciolo. Legate con la crema di mandorle, il sale e il tamari. Versate la crema nella zuppiera e servite calda con un poco di gomasio. Attenzione le prugne umeboshi sono speciali prugne fermentate. Sono salate! Comunque con quella quantità di patate e cetrioli una umeboshi non si sente molto, così se l''avete è meglio metterne almeno due, altrimenti eliminandola dalla ricetta non perdete molto.',992);
INSERT INTO "ricette" VALUES (7092,'Crema Di Champignon Al Lime Con Quadrucci Di Pollo','Contorno','Funghi Champignon',4,' -','200 G Funghi Champignon,
1 Lime,
1/2 Cipolla Bianca,
200 G Polpa Di Pollo Ruspante,
10 Cl Vino Bianco,
Brodo Vegetale,
Pangrattato,
50 G Formaggio Grana,
50 G Ricotta Infornata,
Poco Olio D''oliva,
Sale','Sbollentare i funghi e ripassarli in padella con olio, sale e cipolla tritata preimbiondita; unire il succo del lime, sfumare il tutto con vino bianco e portare a cottura con brodo vegetale; frullare ed emulsionare con olio d''oliva. Tagliare il pollo a quadrucci e rosolarli in padella antiaderente con poco olio per alcuni minuti; unire il pangrattato ed il formaggio grattugiato. Servire lo spezzatino fine di pollo sulla crema di funghi al lime. Grattugiarvi sopra un po'' di ricotta infornata.',1343);
INSERT INTO "ricette" VALUES (7093,'Crema Di Ciliegie','Dessert','Ciliegie',4,' -','500 G Ciliegie,
2 Albumi D''uovo,
100 G Zucchero,
2 Cucchiai Succo Di Limone,
Per Guarnire:,
10 Cl Panna Liquida,
8 Biscotti Lingue Di Gatto','Mettere la panna nella parte più fredda del frigorifero e gli albumi a temperatura ambiente. Lavate la frutta e togliete i noccioli tagliando le ciliegie a metà, raccoglietele in una ciotola e copritele con lo zucchero. Aggiungete il succo di limone e fate riposare 30 minuti fuori dal frigo. Mettete le ciliegie in una casseruola sul fuoco e cuocete 10 minuti mescolando (devono assorbire tutto il loro succo). Fatele raffreddare e passatele al passaverdura. Montate la panna col frullatore 5 minuti e tenetene da parte 2 cucchiai. Montate gli albumi 5 minuti col frullatore. Unite la panna alla purea di ciliegie mescolando delicatamente. Aggiungete gli albumi un cucchiaio per volta, mescolandoli con una forchetta. Dividete la spuma in 4 coppe e lasciatele in frigo per 2 ore. Guarnite con la panna e 2 biscottini.',1275);
INSERT INTO "ricette" VALUES (7094,'Crema Di Cocco E Mango','Dessert','Cocco',4,' -','150 G Polpa Di Noce Di Cocco Grattugiata,
15 Cl Latte,
160 G Zucchero Di Canna,
350 G Yogurth Intero Doppia Panna,
250 G Polpa Di Mango,
1 Lime (succo),
Per Guarnire:,
3 Albumi D''uovo,
100 G Zucchero Semolato,
50 G Noce Di Cocco Grattugiata','Con la noce di cocco grattugiata e il latte preparate il latte di cocco, seguendo il procedimento illustrato nella ricetta ''Crema al cocco''. Ponetelo in una casseruola insieme allo zucchero di canna e portatelo a ebollizione. Togliete il latte dal fuoco, lasciatelo intiepidire, quindi incorporatevi il succo di un lime, la polpa di mango e lo yogurth, mescolando energicamente con un cucchiaio di legno. In una terrina montate a neve ben soda gli albumi, aggiungendo lentamente lo zucchero semolato. Formate con il composto tanti mucchietti tondeggianti e girateli nella noce di cocco grattugiata in modo che ne siano completamente ricoperti. Fate cuocere i dolcetti in una casseruola con acqua in leggero bollore per 2-3 minuti. Distribuite la crema preparata in quattro coppette individuali, guarnite ogni porzione con qualche pallina al cocco e servite.',2293);
INSERT INTO "ricette" VALUES (7095,'Crema Di Cogne','Dessert','Cioccolato',4,' -','100 Cl Latte,
50 Cl Panna Liquida,
1 Cucchiaino Cacao Amaro In Polvere,
50 G Cioccolato Fondente,
6 Tuorli D''uovo,
300 G Zucchero','Montare i tuorli con metà dello zucchero, aggiungere il cacao in polvere e diluire con il latte e la panna. Mettere il preparato in una casseruola a cuocere a fuoco basso ed aggiungere il cioccolato fondente grattugiato. Prima che la crema raggiunga l''ebollizione, unire lo zucchero caramellato,preparato a parte con il rimanente zucchero. Togliere dal fuoco e raffreddare. Viene servita con biscotti secchi chiamati tegole.',4511);
INSERT INTO "ricette" VALUES (7096,'Crema Di Cogne Con Tegole','Dessert','Cioccolato Fondente',4,'Luogo: Val D''Aosta.','100 Cl Latte,
50 Cl Panna Per Dolci,
1 Cucchiaino Cacao Amaro In Polvere,
50 G Cioccolato Fondente,
6 Tuorli D''uovo,
300 G Zucchero','Montare i tuorli con metà dello zucchero, aggiungere il cacao in polvere e diluire con il latte e la panna. Mettere il preparato in una casseruola a cuocere su fuoco basso e aggiungere il cioccolato fondente grattugiato. Prima che la crema raggiunga l''ebollizione, unire lo zucchero caramellato, preparato a parte con il rimanente zucchero. Togliere dal fuoco e raffreddare. Servire la crema accompagnata dalle tegole.',4081);
INSERT INTO "ricette" VALUES (7097,'Crema Di Coniglio','Carne','Coniglio',1,'Ricetta adatta a: bambini piccoli.','200 G Brodo Di Carne,
1 Vasetto Omogeneizzato Di Coniglio,
1 Patata,
1 Cucchiaino Olio D''oliva Extra-vergine','Lessate la patata con la buccia quindi spellatela e schiacciatela con una forchetta. Portate il brodo ad ebollizione, unite la patata e l''omogeneizzato, mescolare per amalgamare con cura e togliete dal fuoco dopo un paio di minuti. Condite con l''olio e servite.',460);
INSERT INTO "ricette" VALUES (7098,'Crema Di Crescione','Primo','Crescione',4,' -','300 G Crescione,
1 Cipolla,
250 G Yogurth,
1 Limone (scorza Grattugiata),
Sale,
Pepe','Sbucciate la cipolla e tritatela finemente con la mezzaluna, quindi ponetela in una casseruola con due bicchieri d''acqua bollente. Fatela sobbollire a calore moderato per 2-3 minuti, poi unitevi il crescione mondato e lavato più volte sotto l''acqua corrente; proseguite la cottura per altri 10 minuti. Trascorso il tempo indicato, lasciate intiepidire gli ortaggi, poi metteteli nel bicchiere del frullatore e azionate l''apparecchio alla massima velocità per qualche minuto. Travasate il composto ottenuto in una terrina e passatelo in frigorifero per circa un''ora, o fino a quando si sarà addensato bene. Dopodichè, incorporate al frullato di verdura lo yogurth, mescolando con un cucchiaio di legno per amalgamarlo bene. Cospargete la crema con il sale necessario e una macinata abbondante di pepe, infine aggiungete la scorza di un limone grattugiata finemente. Date una mescolata, trasferite la crema in una zuppiera e servite. --- NOTA. Il crescione è un''erba molto comune lungo i corsi d''acqua o presso i ruscelli di montagna. E'' ricco di vitamine e minerali, perciò è consigliato ad anemici e convalescenti. In cucina trova impiego soprattutto nella preparazione di insalate, creme e salse, cui conferisce un gusto particolare, leggermente piccante.',242);
INSERT INTO "ricette" VALUES (7099,'Crema Di Crescione (2)','Primo','Crescione',4,' -','2 Cipolle Tritate,
2 Patate Sbucciate E Tagliate A Spicchi,
2 Manciate Crescione Senza I Gambi Più Duri,
100 Cl Acqua,
6 Cucchiai Panna Liquida,
Alcune Foglie Crescione Fresco','Riunire in pentola 2 cipolle tritate, 2 patate sbucciate e tagliate a spicchi e due grosse manciate di crescione mondato dei gambi più duri e ben lavato. Coprire con 1 litro d''acqua e portare a ebollizione, salare e far sobbollire per 20 minuti. Passare il tutto al setaccio e rimettere al fuoco. Quando sta per bollire condire con 6 cucchiai di panna liquida e guarnire con foglioline di crescione fresco. Servire caldo.',889);
INSERT INTO "ricette" VALUES (7100,'Crema Di Fagioli','Antipasto','Fagioli Bianchi',4,' -','300 G Fagioli Bianchi Sgranati,
1 Patata,
1 Carota,
1 Cipolla,
1 Costa Sedano,
50 G Burro,
30 Cl Latte,
Panna Liquida,
120 G Crostini Fritti,
Sale','Mettere in pentola i fagioli con acqua fredda, carota, sedano, cipolla, patata e sale. Portarli a cottura poi scolarli, tenendo da parte 1/2 l di brodo, e passarli al passaverdura con tutte le verdure. Diluire la purea con il latte ed il brodo e rimettere sul fuoco per 20 minuti. Incorporare il burro a pezzetti e qualche cucchiaio di panna liquida. Servire la crema con i crostini di pane.',1630);
INSERT INTO "ricette" VALUES (7101,'Crema Di Fagioli Con Concassé Di Pomodoro E Cipolla Di Tropea','Contorno','Fagioli',4,' -','1 Barattolo Fagioli,
1 Cipolla Di Tropea,
150 G Gamberetti,
2 Pomodori Ramati,
1 Cucchiaio Odori (cipolla, Sedano E Carota),
1/2 Bicchiere Vino Bianco,
1/2 Bottiglia Acqua,
Basilico,
Olio D''oliva Extra-vergine','Soffriggere metà della cipolla in olio, aggiungere i fagioli, bagnare col vino e far cuocere per 5 minuti. In un''altra padella soffriggere gli odori ed i gusci tritati dei gamberetti. Sfumare col vino, unire l''acqua e lasciar ridurre; filtrare e versare nei fagioli. Frullare il tutto e tenere al caldo. In una padella far cuocere i gamberetti con olio e la restante cipolla per 4 minuti. Decorare con i pomodori in concassé.',1232);
INSERT INTO "ricette" VALUES (7102,'Crema Di Fagioli E Gamberetti','Primo','Fagioli Cannellini',4,' -','2 Scatole Fagioli Cannellini,
300 G Gamberi Sgusciati,
2 Pomodori,
Basilico,
Cipolla,
Aglio,
Peperoncino,
Pasta Reale,
Brodo,
Olio D''oliva Extra-vergine,
Sale','Rosolate i fagioli con la cipolla, aggiungete i pomodori spellati e tagliati a pezzi. Fate rosolare a parte i gamberi in una padella con olio d''oliva extra-vergine, aglio e peperoncino e teneteli da parte. Passate i fagioli al setaccio, se necessario aggiungete un po'' di brodo, e unite i gamberi. Decorate con foglie di basilico e qualche pallina di pasta reale.',2221);
INSERT INTO "ricette" VALUES (7103,'Crema Di Fagiolini','Primo','Fagiolini',4,' -','450 G Fagiolini,
40 G Farina,
70 G Burro,
2 Bicchieri Latte,
75 Cl Brodo,
Prezzemolo,
Sale,
Noce Moscata,
Crostini Di Pane','Lessare i fagiolini, insaporirli in metà burro e passarli al setaccio. In una casseruola sciogliere l''altro burro, unire il latte, la farina, il sale, la noce moscata e cuocere, mescolando, per circa 5 minuti. Unire i fagiolini, cuocere per 10 minuti, versare il brodo e portare ad ebollizione. Cospargere di prezzemolo tritato e servire con crostini di pane.',1492);
INSERT INTO "ricette" VALUES (7104,'Crema Di Fagiolini (2)','Antipasto','Fagiolini',4,' -','350 G Fagiolini,
1 Cipolla,
1 Spicchio Aglio,
Burro,
Olio D''oliva,
100 Cl Brodo Vegetale,
Sale,
Crostini Di Pane','Mondare e lavare i fagiolini. Tritare aglio e cipolla e soffriggerli in olio e burro, aggiungere i fagiolini e farli rosolare per alcuni minuti. Versare un litro abbondante di brodo e cuocere per circa 1 ora. Far intiepidire la minestra poi frullarla e rimetterla sul fuoco. Unire una noce di burro e far sobbollire a fuoco basso pochi minuti. Servire la crema con i crostini.',2193);
INSERT INTO "ricette" VALUES (7105,'Crema Di Fave','Primo','Fave',4,' -','500 G Fave Sgusciate,
3 Patate,
1 Cipolla,
1 Carota,
Formaggio Grattugiato,
30 G Burro,
1 Bicchierino Latte,
Basilico,
Sale,
Pepe','In un litro e mezzo d''acqua cuocete le patate tagliate a spicchi, le fave, la carota e la cipolla a fettine. Dopo 20 minuti spegnete e frullate. Salate, pepate versate nella pentola, aggiungete il latte, il burro, cospargete di basilico spezzettato e formaggio, riportate a bollore per un minuto. Servite con crostini di pane molto piccoli insaporiti in una noce di burro. Vini di accompagnamento: Colli Di Conegliano Bianco DOC, Colli Lanuvi DOC, Castel Del Monte Bianco DOC.',1478);
INSERT INTO "ricette" VALUES (7106,'Crema Di Fave Con Scaglie Di Pecorino','Contorno','Fave',4,'Preparazione: 20 minuti.','450 G Fave Sgusciate Surgelate,
400 G Latte,
80 G Formaggio Pecorino Fresco,
40 G Farina Bianca,
40 G Burro,
1 Filo Olio D''oliva Extra-vergine,
Sale','Lessate le fave nella pentola a pressione, in acqua bollente non salata (circa 8 minuti). Scolatele e passatele con il passaverdura, usando il disco medio, per eliminare la buccia (tenetene da parte 2 cucchiaiate). Fate sciogliere il burro in una pentola, mescolatevi la farina, quindi il latte versato a filo. Lasciate prendere il bollore e fate addensare, mescolando, per circa 8 minuti. Unite allora il passato di fave, salate, mescolate e date altri 2 minuti di cottura. Versate la minestra nei piatti fondi individuali. Condite ogni porzione con il pecorino tagliato a scagliette e con un filo di olio di oliva crudo. Guarnite con le fave intere tenute da parte e servite.',1562);
INSERT INTO "ricette" VALUES (7107,'Crema Di Finocchi','Primo','Finocchi',4,'Preparazione: 20 minuti. Cottura: 30 minuti.','5 Finocchi,
1 Scalogno (o Cipolla),
1 Cucchiaio Olio D''oliva,
1 Pezzetto Burro,
100 Cl Acqua,
2 Cucchiai Brodo Granulare Magro Knorr,
Pepe,
Abbondante Formaggio Parmigiano Grattugiato,
1 Cucchiaio Maizena (facoltativo)','Pulite i finocchi, eliminando le foglie esterne più dure, tagliateli a spicchi. In un tegame fate soffriggere lo scalogno con burro e olio, aggiungete i finocchi e qualche barbina verde (molto profumata) dei finocchi. Fate insaporire molto bene, pepate, aggiungete l''acqua calda e il brodo granulare magro Knorr e fate cuocere per 30 minuti circa. Frullate il tutto fino ad ottenere una crema liscia. Se è necessario addensate con 1 cucchiaio di maizena sciolto in 1/2 tazzina d''acqua. Servite accompagnando con abbondante parmigiano grattugiato. Potrete servire questa crema con pane tostato.',1126);
INSERT INTO "ricette" VALUES (7108,'Crema Di Finocchi Al Salmone Affumicato','Primo','Finocchi',4,' -','3 Finocchi,
80 G Salmone Affumicato,
30 G Burro,
1 Cucchiaio Panna,
1 Pizzico Aneto,
Sale,
Pepe','Mondate e lavate i finocchi. Tagliateli a fettine e fateli stufare a fuoco basso per circa 20 minuti in un tegame con il burro e mezzo bicchiere d''acqua. Quando sono cotti, aggiungete un altro mezzo bicchiere d''acqua e frullateli fino a ottenere una crema omogenea. Amalgamatevi un cucchiaio di panna, regolate sale e pepe. Versate la crema in una zuppiera, aggiungete il salmone sminuzzato e un pizzico di aneto. Servite. Vini di accompagnamento: Trentino Müller-Thurgau DOC, Montecarlo Bianco DOC, Castel Del Monte Sauvignon DOC.',436);
INSERT INTO "ricette" VALUES (7109,'Crema Di Finocchi E Porri','Contorno','Finocchi',4,' -','2 Cipollotti Freschi,
2 Finocchi,
1 Porro,
3 Patate,
Aglio,
Prezzemolo,
1 Cucchiaio Crema Di Latte,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulire bene le verdure, lavarle e tagliarle a pezzetti regolari. Farle brasare con l''olio e bagnarle con 100 cl d''acqua; salare e pepare e cuocere per circa 30 minuti. Con un frullatore ad immersione frullare il tutto e riportare a bollore. Servire la crema nei piatti singoli, versando al centro 1 cucchiaio di crema di latte e cospargendo di prezzemolo finemente triturato.',1478);
INSERT INTO "ricette" VALUES (7110,'Crema Di Formaggi Con Noci','Antipasto','Noci',4,' -','100 G Formaggio Gorgonzola,
200 G Formaggio Robiola Fresca,
100 G Formaggio Caprino,
150 G Mascarpone,
100 G Gherigli Di Noci','Mescolate i quattro formaggi con una forchetta fino a ottenere un composto cremoso. Aggiungete al composto i gherigli di noci sbriciolati lasciandone da parte qualcuno intero per decorare. Mettete su di un piatto questa crema dandole la forma di una cupola su cui appoggerete i gherigli di noci interi. Fate raffreddare in frigorifero per qualche ora. Servite accompagnato con cracker, o anche con del sedano.',2592);
INSERT INTO "ricette" VALUES (7111,'Crema Di Formaggio','Contorno','Groviera',6,' -','Per La Crema:,
100 Cl Latte,
8 Uova,
150 G Formaggio Groviera Grattugiato,
Sale,
Pepe,
Noce Moscata Grattugiata,
Per La Salsa:,
200 G Salsa Di Pomodoro Concentrata,
20 G Farina,
30 G Burro,
2 Bicchieri Acqua Calda,
Sale,
Pepe','Preparate la crema: mentre fate bollire il latte, battete le uova intere come per fare una frittata incorporando il formaggio grattugiato, una presa di sale, una di pepe e una di noce moscata. Versate lentamente il latte bollente sulle uova, continuando a batterle finchè il formaggio si sarà liquefatto. Trasferite il miscuglio in uno stampo da charlotte unto di burro, copritelo e sistematelo in una casseruola larga piena a metà di acqua bollente. Mettete i due recipienti a metà altezza nel forno preriscaldato a 150 gradi e cuocete la crema per un''ora. State attenti che l''acqua del bagno non alzi mai il bollore! La crema sarà pronta quando, bucando lo stampo nel centro con uno stecchino, questo ne uscirà asciutto. Preparate la salsa: scaldate il burro in una casseruola, aggiungete la farina e mescolate per un minuto a fuoco moderato. Unite la salsa di pomodoro e, in seguito, diluitela con l''acqua calda. Salate, pepate e, dopo averla coperta a 3/4, cuocetela per 15 minuti. Sfornate la crema su di un piatto di portata riscaldato e irroratela con la salsa. Se, invece, preferite non sformarla potete cuocerla in una pirofila fonda e servirla con la salsa a parte.',2276);
INSERT INTO "ricette" VALUES (7112,'Crema Di Fragole','Dessert','Fragole',4,' -','400 G Fragole,
2 Fogli Colla Di Pesce,
2 Cucchiai Succo Di Limone,
33 Cl Panna,
120 G Zucchero','Tagliate le fragole e lasciatele da parte. Ammorbidite la gelatina in poca acqua tiepida per 10 minuti circa, quindi versatela sulle fragole che avrete passato al setaccio, aggiungete il succo di limone e lo zucchero. Montate la panna che dovrà essere molto consistente e unitela al passato di fragole. Servitela molto fredda, in coppette singole guarnite con una grossa fragola sistemata al centro.',1847);
INSERT INTO "ricette" VALUES (7113,'Crema Di Fragole (2)','Dessert','Fragole',6,' -','1500 G Fragole,
500 G Zucchero,
750 G Latte,
8 Uova,
120 G Amido Di Riso','Montate i tuorli con lo zucchero fino a renderli spumosi. Aggiungete l''amido e quindi versate a filo il latte freddo. Cuocete a fiamma dolce continuando a mescolare fino a quando la crema si addensa. Frullate le fragole, mescolatele alla crema lasciando il recipiente sul fuoco sempre a fiamma bassa e quando la crema ha una consistenza omogenea ritirate e versate in una larga coppa. Servite freddo.',3961);
INSERT INTO "ricette" VALUES (7114,'Crema Di Frutta All''inglese','Dessert','Frutta Mista',4,'Luogo: Regno Unito. Luogo: Inghilterra.','500 G Frutta Mista (pere, Mele, Ribes, Uva, Ciliegie),
200 G Zucchero,
250 G Panna,
3 Tuorli D''uovo,
60 G Burro Fuso,
1 Bicchiere Acqua','Lavare e tagliare pere e mele a pezzi senza togliere nè buccia, nè torsolo; pulire, lavare e sgranare l''uva e il ribes, snocciolare le ciliegie, mettere tutto in una casseruola con l''acqua e lasciar cuocere a fuoco lento fino a che la polpa delle mele e delle pere sarà tenera. Passare tutto al setaccio e porre il passato in 1 casseruola, zuccherare, unire il burro fuso, i tuorli e la panna, mescolando. Rimettere sul fuoco e far addensare la crema. Servirla fredda.',2724);
INSERT INTO "ricette" VALUES (7115,'Crema Di Funghi','Contorno','Funghi',4,' -','1 Brodo Di Carne,
1 Tazza Farina Di Riso (o Farina),
Latte,
Funghi Tagliati Fini,
Burro,
Crostini Di Pane (facoltativo),
Prezzemolo (facoltativo),
Erba Cipollina (facoltativo)','Preparate un brodo di carne e aggiungetevi l''acqua di cottura dei funghi. Diluite 1 tazza dì farina di riso (potete anche prendere della farina ordinaria) nel latte e versate questo miscuglio nel brodo bollente rimestando continuamente. Aggiungete i funghi tagliati fini, stufati nel burro (funghetti di Parigi, boleti, gallinelle). Potete migliorare questaminestra aggiungendovi dei crostini di pane tostati nel burro, del prezzemolo o dell''erba cipollina.',1574);
INSERT INTO "ricette" VALUES (7116,'Crema Di Funghi (2)','Primo','Funghi',4,' -','250 G Funghi Porcini Tritati,
30 G Cipolla Tritata,
100 Cl Brodo Di Verdure,
60 G Burro,
30 G Farina,
25 Cl Panna Semigrassa,
6 Cucchiai Sauternes,
Sale,
Pepe','Mettere i funghi e la cipolla nel brodo e lasciare sobollire per 20 minuti, poi passarli al setaccio. Mettere il passato sul fuoco. A parte lavorare burro e farina ed incorporarli nel brodo con una frusta. Lasciar asciugare un po'', aggiustare di sale e pepe, aggiungere la panna, lasciar sobollire sino a quando abbia assunto la consistenza della crema. Togliere dal fuoco, aggiungere appena prima di portare in tavola il vino, mescolare delicatamente.',2274);
INSERT INTO "ricette" VALUES (7117,'Crema Di Funghi (3)','Primo','Funghi',4,' -','300 G Funghi Freschi,
2 Cucchiai Farina,
70 G Burro,
25 Cl Latte,
75 Cl Brodo,
Prezzemolo Tritato,
Sale,
Noce Moscata','Pulire i funghi, tagliarli a fettine e farli cuocere con circa 20 g di burro. Aggiungere il sale. Preparare la besciamella: in una casseruola sciogliere il rimanente burro, versarvi la farina e mescolare con un cucchiaio di legno, unire il latte e portare all''ebollizione mescolando sempre; unire sale e noce moscata. Passare i funghi al setaccio (o nel Bravo Simac), unirli alla besciamella e far cuocere a fuoco lento per circa 10 minuti. Diluire con il brodo, far bollire di nuovo ed aggiungere il prezzemolo tritato. Servire la crema con crostini di pane fritti o tostati.',1153);
INSERT INTO "ricette" VALUES (7118,'Crema Di Funghi (4)','Primo','Funghi',4,' -','450 G Funghi Champignon,
3 Cucchiai Olio D''oliva,
1 Spicchio Aglio,
30 G Burro,
30 G Farina,
25 Cl Latte,
50 Cl Brodo Vegetale Concentrato,
1 Cucchiaio Prezzemolo Tritato,
Sale,
Pepe','Preparare un brodo con tante verdure facendolo ridurre a lungo. Cuocere i funghi a pezzetti per 10 minuti con olio e aglio. Preparare una besciamella con farina, burro, latte e sale, unirla ai funghi e cuocere per 15 minuti aggiungendo il brodo. 5 minuti prima del termine di cottura frullare il tutto. Salare, pepare e servire.',1797);
INSERT INTO "ricette" VALUES (7119,'Crema Di Funghi Porcini','Primo','Funghi Porcini',4,' -','400 G Funghi Porcini Freschi,
1 Spicchio Aglio,
30 G Farina,
25 Cl Latte,
50 Cl Brodo Vegetale Concentrato,
1 Cucchiaio Prezzemolo Tritato,
3 Cucchiai Olio D''oliva Extra-vergine,
30 G Burro,
Sale,
Pepe','Preparate un brodo con tante verdure facendolo ridurre a lungo, fino ad ottenere un liquido molto concentrato. Pulite con attenzione i funghi, tenete da parte le tre cappelle più belle, tagliate a pezzetti tutti gli altri e cuoceteli per 10 minuti con l''olio e l''aglio. Preparate una besciamella con burro, farina, latte e sale, quindi unitela ai funghi dai quali avrete tolto l''aglio e cuocete per 15 minuti aggiungendo il brodo e lasciando ridurre a fuoco medio; 5 minuti prima della fine immergete il mixer e frullate il tutto. Affettate le cappelle lasciate da parte e passatele in padella con poco olio e prezzemolo, quindi aggiungetele alla crema con sale e pepe e servite calda. Chi preferisce un gusto più morbido può aggiungere un tuorlo d''uovo alla fine, a fuoco spento.',1245);
INSERT INTO "ricette" VALUES (7120,'Crema Di Gamberetti','Primo','Gamberetti',4,' -','300 G Gamberetti Sgusciati,
150 G Misto Per Soffritto,
1 Porro Sottile,
2 Cucchiai Olio D''oliva,
30 G Burro,
1 Cucchiaio Concentrato Di Pomodoro,
100 Cl Brodo Vegetale,
500 G Patate,
1/2 Bicchiere Vino,
Sale,
Pepe','Unire il soffritto e il porro a rondelle ad olio e burro caldi, cuocere a fuoco dolce per 10 minuti, versare il brodo, unire le patate a pezzi e cuocere per 30 minuti. Unire i gamberetti e il vino e dopo un po'' frullare il tutto, rimetterlo in pentola, salare, riportare a bollore e servire con pepe macinato di fresco.',2009);
INSERT INTO "ricette" VALUES (7121,'Crema Di Gamberetti (2)','Primo','Gamberetti Freschi',4,' -','300 G Gamberetti Freschi,
60 G Burro,
1 Carota,
1 Cipolla,
1 Peperoncino,
1 Foglia Alloro,
Poco Timo,
1 Bicchierino Rum,
1/2 Bicchiere Vino Bianco,
40 G Farina Di Riso,
100 G Panna,
50 Cl Brodo,
Sale,
Pepe','Tritare peperoncino, cipolla e carota e metterli in un tegame con il burro, 1 foglia di alloro e poco timo e rosolare. Unire i gamberetti sgusciati, sale, pepe. Dopo 5 minuti bagnare con 1 bicchierino di rum e farlo evaporare. Versare 1/2 bicchiere di vino e cuocere. Diluire la farina nel brodo, unirla ai gamberetti con la panna rigirando per non formare grumi e portare a cottura mescolando spesso.',1666);
INSERT INTO "ricette" VALUES (7122,'Crema Di Gamberetti E Fagioli','Primo','Gamberetti',4,' -','200 G Fagioli Cannellini Freschi,
200 G Gamberetti,
80 G Burro,
50 G Farina,
100 Cl Brodo Vegetale,
1 Scalogno,
1 Rametto Timo,
1/2 Bicchiere Vino Bianco Secco,
1/2 Bicchiere Panna,
Sale,
Pepe','Lessate i fagioli e passateli al passaverdure. Mettete in un tegame 30 g di burro e insaporitevi lo scalogno tritato. Unite i gamberetti sgusciati, fateli saltare per 2 minuti, spruzzateli con il vino bianco, lasciate evaporare, salate, pepate, frullate. In un altro tegame sciogliete il resto del burro, unite la farina a pioggia, mescolate. Versatevi il passato di fagioli, poi diluite il composto a poco a poco con il brodo bollente e cuocete, a fuoco basso, per circa un quarto d''ora. Unite al frullato di gamberetti mezzo bicchiere di panna e alcune foglioline di timo. Versatelo sulla crema di fagioli. Servite. Vini di accompagnamento: Alto Adige Pinot Bianco DOC, Colli Martani Grechetto DOC, Greco Di Tufo DOC.',1795);
INSERT INTO "ricette" VALUES (7123,'Crema Di Gamberi','Primo','Gamberi',4,' -','1 Pugno Farina,
1 Bicchiere Panna Liquida,
150 Cl Brodo Di Carne,
Crostini Di Pane,
Paprica,
Sale','Lavare i gamberi, lessarli nell''acqua bollente per 10 minuti, farli raffreddare, levarli dal guscio e passarne metà al setaccio. Far rosolare nel burro la farina, versare la panna, cuocere per 5-10 minuti, aggiungere la purea di gamberi, un pizzico di paprica, il sale, il brodo e portare ad ebollizione. Unire i gamberi a pezzetti, far bollire e servire con i crostini di pane.',1277);
INSERT INTO "ricette" VALUES (7124,'Crema Di Gamberi E Pomodori','Primo','Gamberi',4,' -','1000 G Gamberi,
100 Cl Brodo Vegetale,
500 G Pomodori Maturi,
45 G Burro,
40 G Formaggio Farina,
2 Cucchiaini Curry In Polvere,
Sale','Lessate per 3 minuti i gamberi non sgusciati nel brodo bollente. Scolateli, sgusciateli e mettetene da parte dieci interi e gli altri tritateli finemente. Filtrate con cura il brodo. In una pentola fate sciogliere il burro, incorporatevi la farina e quando ha preso colore diluitela con il brodo caldo. Portate a bollore, riducete la fiamma e cuocete per 10 minuti mescolando. Unitevi i gamberi tritati. Spellate i pomodori, eliminate i semi, frullateli, insaporiteli con il curry e aggiungeteli alla crema. Portate a bollore per alcuni minuti. Regolate il sale. Versate nella zuppiera, guarnite con i gamberi interi e servite. Vini di accompagnamento: Collio Sauvignon DOC, Torgiano Riesling Italico DOC, Vermentino Di Gallura DOC.',1623);
INSERT INTO "ricette" VALUES (7125,'Crema Di Gamberi Ungherese','Primo','Gamberi',4,'Luogo: Ungheria.','100 G Brodo,
3 Carote Tritate,
1000 G Gamberi,
1 Bicchiere Vino Bianco,
1 Cucchiaio Brandy,
Sale,
Pepe,
1 Bicchiere Brodo,
150 Cl Brodo,
2 Cipolle,
1 Ciuffo Prezzemolo,
1 Mazzetto Odori,
100 G Burro,
1 Tazzina Panna','Soffriggere in 100 g di burro 3 carote tritate e 1000 g di gamberi. Quando i gamberi saranno ben rossi bagnarli con un bicchiere di vino bianco e un cucchiaio di brandy, salarli, peparli e bagnarli con un bicchiere di brodo. Sgusciare i gamberi e rimettere i gusci a bollire con 150 cl di brodo, 2 cipolle, un ciuffo di prezzemolo e un mazzetto di odori: far sobbollire per 45 minuti. Filtrare e unire a questo brodo la polpa dei gamberi tritata, 100 g di burro, una tazzina di panna, sale, pepe e servire.',2577);
INSERT INTO "ricette" VALUES (7126,'Crema Di Indivia Belga','Primo','Insalata Belga (indivia)',4,' -','500 G Insalata Belga (indivia),
100 G Piselli,
50 Cl Brodo Di Carne,
50 Cl Latte,
50 G Farina,
80 G Burro,
Formaggio Grattugiato,
1 Cucchiaio Prezzemolo Tritato,
Sale,
Pepe','Lavate, sgocciolate, tagliate a pezzetti l''indivia, insaporitela in un tegame con 30 g di burro e poi aggiungetevi i piselli. Coprite e lasciate stufare per 5 minuti. Salate. Versate nel recipiente il brodo bollente e continuate la cottura, sempre a fuoco basso, per circa 20 minuti. Intanto, in una piccola casseruola, sciogliete il restante burro, unitevi la farina, mescolate, aggiungete il latte freddo poco per volta e continuate a mescolare fino a quando il composto si è addensato. Salate, pepate. Versate questa besciamella nel tegame dell''indivia, coprite e cuocete ancora, a fuoco basso, per un quarto d''ora. Frullate, versate in una zuppiera, cospargete un cucchiaio di prezzemolo fresco tritato. Servite con formaggio grattugiato. Vini di accompagnamento: Valdadige Bianco DOC, Bianco Dei Colli Maceratesi DOC, Gravina DOC.',1692);
INSERT INTO "ricette" VALUES (7127,'Crema Di Lamponi Al Vino Bianco','Dessert','Lamponi',4,' -','450 G Lamponi,
20 Cl Vino Bianco Dolce,
100 G Zucchero,
1/2 Bustina Vaniglina,
1 Cucchiaio Succo Di Limone','Pulire i lamponi con 1 panno umido, tenerne da parte 150 g e mettere quelli rimasti nel bicchiere del frullatore. Unire il vino, il succo di limone, lo zucchero e la vaniglina; frullare il tutto, ottenendo una crema fluida. Suddividerla in 4 coppette e distribuirvi sopra i lamponi interi tenuti da parte. Servire subito o conservare in frigo fino al momento di servire.',695);
INSERT INTO "ricette" VALUES (7128,'Crema Di Lattuga','Primo','Insalata Lattuga',4,' -','300 G Insalata Lattuga,
1 Cipolla,
Sedano,
4 Carote,
25 G Burro,
2 Cucchiai Olio D''oliva,
Formaggio Parmigiano,
Sale,
1 Dado','Pulire la lattuga. Cuocere in 150 cl di acqua leggermente salata la cipolla, il sedano, le carote tagliati a dadini. Dopo 20 minuti aggiungere l''olio, la lattuga e cuocere per altri 10 minuti. Passare il tutto, salare, aggiungere il burro e abbondante parmigiano. Servire con crostini di pane fritti.',1120);
INSERT INTO "ricette" VALUES (7129,'Crema Di Lattuga (2)','Primo','Insalata Lattuga',4,' -','3 Cespi Insalata Lattuga,
30 G Burro,
2 Cucchiai Farina,
50 Cl Latte,
50 Cl Brodo Di Carne,
1 Tuorlo D''uovo,
Formaggio Grattugiato,
Sale,
Pepe','Versate in una pentola il latte e il brodo, portate a bollore, salate e lessatevi la lattuga per 5 minuti. Frullatela. In un tegame fate sciogliere il burro, unite la farina, continuate a mescolare e quando ha preso colore diluitela con il frullato. Regolate sale e pepe. Cuocete per un quarto d''ora. In una zuppiera amalgamate il tuorlo con il formaggio e poi, mescolando, versatevi a poco a poco la crema di lattuga calda. Vini di accompagnamento: Colli Tortonesi Cortese DOC, Bianco Della Valdinievole DOC, Locorotondo DOC.',1300);
INSERT INTO "ricette" VALUES (7130,'Crema Di Legumi','Primo','Legumi Misti',4,' -','300 G Legumi Secchi Misti,
2 Patate,
1 Carota,
1 Costa Sedano,
1 Cipolla,
2 Cucchiai Panna,
Formaggio Grattugiato,
Sale,
Pepe','Tenete a bagno i legumi secchi come fagioli, lenticchie, fave, piselli per una notte in acqua tiepida. Eliminate quelli che vengono a galla, mettete a cuocere gli altri in acqua fredda salata con la carota, il sale, il sedano, la cipolla e le patate. Portate a bollore e continuate la cottura, sempre coperto. I legumi devono sobbollire lentamente fino a diventare teneri. Frullate il tutto. Aggiungete la panna, mescolate per amalgamare, regolate sale e pepe. Servite con formaggio grattugiato. Vini di accompagnamento: Colli Di Luni Rosso DOC, Montepulciano D''Abruzzo Cerasuolo DOC, Donnici DOC.',1705);
INSERT INTO "ricette" VALUES (7131,'Crema Di Lenticchie','Primo','Lenticchie Di Castelluccio',6,' -','300 G Lenticchie Di Castelluccio,
1 Cipolla,
40 Cl Latte,
1 Bustina Zafferano,
2 Cucchiai Farina,
2 Foglie Alloro,
Olio D''oliva,
Noce Moscata','Ammollare per un''ora le lenticchie. Scolarle e sciacquarle. Rosolare la cipolla in olio con 2 foglie d''alloro, unire le lenticchie e cuocere a fuoco bassissimo per 10 minuti. Versare 100 Cl d''acqua, portare a ebollizione, salare e cuocere per 40 minuti. A parte scaldare un po'' d''olio, versarvi la farina, mescolare poi aggiungere il latte e far addensare. Aggiungere sale, zafferano e noce moscata. Togliere l''alloro dalle lenticchie, frullarle e condire con la salsa allo zafferano.',1962);
INSERT INTO "ricette" VALUES (7132,'Crema Di Lenticchie (2)','Primo','Lenticchie',4,' -','300 G Lenticchie Già Ammollate,
1 Carota,
1 Costa Sedano,
1 Patata,
Pane Raffermo,
Panna Vegetale,
Sale,
Olio D''oliva Extra-vergine','Mettere a cuocere le lenticchie in abbondante acqua bollente salata con il sedano, la carota e la patata tagliate a tocchetti. Dopo circa 40 minuti di cottura a fuoco lento, passare tutto al passaverdure, rimettere sul fuoco per circa 10 minuti aggiungendo se necessario, dell''acqua calda. Tostare dei crostini di pane, strusciarli con aglio e porli sul fondo di fondine individuali, cospargere con la crema di lenticchie. Versare un cucchiaio di panna vegetale al centro di ogni fondina di zuppa ed aiutandosi con uno stecchino, tirarla verso l''esterno come a disegnare i raggi di un sole.',2301);
INSERT INTO "ricette" VALUES (7133,'Crema Di Limoncello','Dessert','Limoni',4,' -','50 Cl Alcool Neutro A 96 Gradi,
1000 G Zucchero,
100 Cl Latte Intero,
3 Buste Vaniglina In Polvere,
6 Limoni (scorza)','Mettere le bucce sotto spirito per quattro giorni e mezzo. Bollire il latte la vaniglina. Quando è quasi freddo, aggiungere lo zucchero e mescolare. Filtrare le bucce dall''alcool, unire tutto e filtrare bene, anche due volte. Mettere in frezeer per un paio di giorni.',5440);
INSERT INTO "ricette" VALUES (7134,'Crema Di Limoni','Bevande','Limoni',3,' -','150 Cl Limoncello,
50 G Latte Condensato Nestlé,
5 Cubetti Ghiaccio','Mettere in uno sheker 150 cl di limoncello, 50 g di latte condensato Nestlé, 5 cubetti di ghiaccio. Shekerare il tutto Servire.',5216);
INSERT INTO "ricette" VALUES (7135,'Crema Di Limoni (2)','Bevande','Limoni',4,' -','8 Limoni,
100 Cl Alcool,
100 Cl Acqua,
750 G Zucchero,
75 Cl Panna Per Dolci,
1 Vasetto Latte Condensato','Mettere le bucce dei limoni in infusione nell''alcool per 15 giorni. Preparare lo sciroppo con l''acqua e zucchero ed unirlo freddo all''alcool, precedentemente filtrato dalle bucce, unire la panna senza montarla (al limite batterla un po'' con la forchetta) e il vasetto di latte condensato. Riporre in frigo lasciare riposare qualche giorno, e agitatela prima di servirla.',7188);
INSERT INTO "ricette" VALUES (7136,'Crema Di Mandorle','Primo','Mandorle',4,' -','150 G Mandorle Pelate,
75 Cl Brodo Di Pollo,
200 G Panna Liquida,
3 Tuorli D''uovo,
1 Pizzico Pepe,
Sale','Tritare finissime 150 g di mandorle pelate e porle in una pentola aggiungendovi lentamente, rimescolando in continuazione, 75 cl di brodo di pollo. Mettere sul fuoco e portare a ebollizione sempre rimescolando. Unire 150 g. di panna liquida e abbassare la fiamma al minimo. Far scaldare ed emulsionare bene anche la panna e quindi versare questa crema in una zuppiera dove già sono 3 tuorli d''uovo, 50 g di panna liquida e un pizzico di pepe. Rimescolare bene, aggiustare di sale e servire.',2214);
INSERT INTO "ricette" VALUES (7137,'Crema Di Mandorle (2)','Dessert','Latte Di Soia',4,'Ricetta adatta a: vegetariani.','50 Cl Latte Di Soia,
2 Cucchiai Maizena,
2 Cucchiai Burro Di Mandorle,
5 Cucchiai Malto Di Mais,
Vaniglia Naturale,
Sale Marino','Bollite il latte di soia, il burro di mandorle, il sale, la vaniglia e il malto di mais. Sciogliete la maizena in un po'' d''acqua fredda e cuocetela assieme agli altri ingredienti per 10 minuti. Servite freddo.',1113);
INSERT INTO "ricette" VALUES (7138,'Crema Di Mangostano','Dessert','Mangostani',4,' -','6 Mangostani,
150 G Crema Pasticciera (v. Ricetta),
4 Fogli Colla Di Pesce,
1 Cucchiaino Succo Di Lime,
12 Cl Panna,
50 G Zucchero,
2 Cucchiai Salsa Di Cioccolato,
4 Cialde Tagliate A Foglia','Sbucciate i mangostani, privateli del nocciolo e passate la polpa attraverso un setaccio fine, raccogliendo il ricavato in una terrina: dovete ottenere circa 150 g di purea. Passate al setaccio anche la crema pasticciera, raccoglietela in una casseruola, unitevi la purea di frutta e fate scaldare il tutto a calore moderato, mescolando in continuazione con un cucchiaio di legno. Prima che il composto arrivi a bollire, toglietelo dal fuoco e incorporatevi la colla di pesce, precedentemente ammorbidita in acqua fredda e strizzata, e il succo di lime. Lasciate raffreddare il composto e, prima che si rassodi completamente, mescolatevi la panna montata insieme allo zucchero, quindi mettetelo in una tasca di tela con bocchetta a stella e distribuitelo in quattro coppette individuali. Versate sulla crema un poco di salsa di cioccolato fredda, guarnite con le foglioline di cialda e servite.',1867);
INSERT INTO "ricette" VALUES (7139,'Crema Di Marroni','Dessert','Marroni',4,' -','500 G Marroni,
4 Marroni,
200 G Zucchero,
2 Cucchiai Cognac,
1/2 Bicchiere Panna Liquida,
50 G Cioccolato Grattugiato','Incidete i marroni, versateli in una pentola d''acqua bollente e dopo una ventina di minuti sgocciolateli. Privateli della buccia e della pellicina quindi metteteli in una casseruola, copriteli di latte freddo e cuoceteli, coperti a fuoco lento, per 45 minuti. Sgocciolateli, passateli al setaccio e incorporatevi in un recipiente, a fuoco basso, lo zucchero, il Cognac e il cioccolato. Lasciate intiepidire, mescolatevi la panna liquida e disponete la crema nelle coppe; decorate con un fiocco di panna montata e un marrone.',5907);
INSERT INTO "ricette" VALUES (7140,'Crema Di Mascarpone','Dessert','Mascarpone',6,' -','200 G Mascarpone,
3 Tuorli D''uovo,
50 G Zucchero,
1 Bicchierino Rum,
20 Cl Panna Montata','Mescolate al mascarpone i tuorli e lo zucchero, lavorate l''impasto: deve diventare soffice, unite il rum. Versate la crema in una coppa, tenete in frigorifero qualche ora. Servite con panna montata.',2094);
INSERT INTO "ricette" VALUES (7141,'Crema Di Mascarpone Al Panforte','Dessert','Mascarpone',4,' -','3 Tuorli D''uovo,
3 Cucchiai Zucchero Semolato Fine,
300 G Mascarpone,
3 Cucchiai Vino Porto,
100 G Panforte','Mettere i tuorli in una terrina, unire lo zucchero e montarli con una frusta fino ad ottenere un composto chiaro e spumoso; aggiungere il mascarpone, il Porto, i 2 terzi del panforte tritato finemente con 1 coltello e mescolare bene il tutto. Versare la crema ottenuta in 4 coppette, metterle in freezer per 10 minuti. Poi cospargere la superficie con il panforte rimasto. Servire subito ben freddo.',2393);
INSERT INTO "ricette" VALUES (7142,'Crema Di Mascarpone E Pasta D''acciughe','Antipasto','Mascarpone',4,' -','200 G Mascarpone,
60 G Pasta D''acciughe','Mettete il mascarpone e la pasta d''acciughe in una ciotola e mescolateli a lungo fino a ottenere un composto liscio e omogeneo. Mettete la crema in ciotoline individuali e servitele con crostini di pane leggermente tostati, ma molto caldi. Vini di accompagnamento: tutti i VSQPRD (Vino Spumante di Qualità Prodotto in Regione Determinata) di tipologia Brut.',969);
INSERT INTO "ricette" VALUES (7143,'Crema Di Mascarpone, Noci E Gorgonzola','Antipasto','Noci',4,' -','5 Noci,
300 G Mascarpone,
200 G Formaggio Gorgonzola,
Sale,
Pepe','Sgusciare le noci e tritarle leggermente. Schiacciare il mascarpone ed il gorgonzola ed unirli. Aggiustare di sale e di pepe ed infine aggiungere le noci.',2377);
INSERT INTO "ricette" VALUES (7144,'Crema Di Melanzane','Antipasto','Melanzane',4,' -','2 Melanzane Grandi,
1 Spicchio Aglio Schiacciato,
2 Cucchiai Olio D''oliva,
2 Cucchiaini Succo Di Limone,
Sale,
Pepe,
Prezzemolo Tritato,
Alcune Fette Limone','Lavate le melanzane, punzecchiatele con una forchetta e tagliatele a metà in verticale. Disponetele in una teglia antiaderente e mettetele in forno a 190 gradi per 40-45 minuti. Pelatele e passate la polpa nel tritatutto con aglio e succo di limone aggiungendo l''olio a filo, oppure passatela al passaverdura con aglio e succo di limone, aggiungendo poi l''olio e battendo con cura. Incorporate 1 cucchiaio e 1/2 di prezzemolo e disponete la crema in una ciotola o in vaschette individuali. Guarnite con altro prezzemolo e fettine di limone.',501);
INSERT INTO "ricette" VALUES (7145,'Crema Di Melanzane (2)','Antipasto','Melanzane Lunghe',4,' -','4 Melanzane Lunghe,
400 G Yogurth Bianco,
2 Spicchi Aglio,
1 Limone,
4 Cucchiai Olio D''oliva,
Prezzemolo Tritato,
Sale,
Pepe,
Crostini Di Pane','Cuocere le melanzane intere in forno a 220 gradi fino a quando saranno tenere, poi sbucciarle. Frullare la polpa di melanzane con l''aglio, il succo di limone e l''olio fino ad ottenere una crema omogenea. Versare la crema in una zuppiera e unirvi lo yogurth, sale e pepe. Mescolare bene e cospargere con il prezzemolo. Servire la crema fredda con i crostini a parte.',2144);
INSERT INTO "ricette" VALUES (7146,'Crema Di Menta','Dessert','Menta',4,' -','75 Cl Latte,
4 Tuorli D''uovo,
150 G Zucchero,
80 G Farina,
1 Bustina Vaniglina,
5 Cucchiai Sciroppo Di Menta,
Menta Fresca','Portare a ebollizione il latte, levare dal fuoco e aggiungere la vaniglina e lo sciroppo di menta. A parte sbattere i tuorli con lo zucchero, unire la farina e il latte, mescolando per non formare grumi. Rimettere il composto sul fuoco e cuocere, sempre mescolando, per circa 10 minuti finché la crema non si sarà addensata. Versarla in 4 coppette, lasciarla intiepidire e porre in frigo per 1 ora prima di servire. Decorare con la menta fresca.',2249);
INSERT INTO "ricette" VALUES (7147,'Crema Di Mirtilli','Dessert','Mirtilli',4,' -','600 G Mirtilli,
200 G Zucchero,
2 Cucchiai Maizena,
25 Cl Panna,
1/2 Bicchiere Acqua,
1 Bicchiere Vino Bianco','Lavare delicatamente i mirtilli nel vino bianco e passarli al setaccio. Mettere la maizena in una casseruola, unire lo zucchero e, poco per volta, il passato di mirtilli. Aggiungere 1 bicchiere di vino bianco, l''acqua e portare a ebollizione mescolando continuamente con un cucchiaio di legno. Far bollire la crema per pochi minuti, levarla dal fuoco e distribuirla in 4 coppette individuali. Lasciar raffreddare e servire guarnita con la panna montata.',2240);
INSERT INTO "ricette" VALUES (7148,'Crema Di Nutella E Fiocchi D''avena','Dessert','Nutella',6,' -','6 Tazze Latte,
10 Cucchiai Fiocchi D''avena,
3 Manciate Nocciole Tritate,
6 Cucchiai Nutella,
3 Cucchiai Zucchero,
1 Presa Sale','Mettete per almeno 2 ore i fiocchi d''avena a bagno nel latte. Trasferite questo composto in una casseruola. Unite il sale, la Nutella, lo zucchero e portate ad ebollizione. Fate cuocere per 10 minuti avendo cura di mescolare spesso. Togliete dal fuoco ed incorporatevi la Nutella. Mescolate bene e versate la crema in 6 coppette.',2118);
INSERT INTO "ricette" VALUES (7149,'Crema Di Panna E Mango','Dessert','Mango',4,' -','350 G Polpa Di Mango,
2 Cucchiai Sciroppo (v. Ricetta),
35 Cl Panna Da Montare,
30 G Zucchero,
4 Cucchiai Salsa Al Cioccolato','Staccate la polpa di mango dalla buccia servendovi di un cucchiaio e tagliatela a dadini con un coltello. Eliminate la polpa rimasta attaccata al nocciolo con l''aiuto di un coltello, tenendo ovviamente il nocciolo fermo con una mano. Raccogliete la polpa di mango in una terrina e riducetela in purea frullandola con un frullatore ad immersione. La purea di polpa di mango non deve essere obbligatoriamente addolcita. Solamente se necessario, aggiungetevi un poco di sciroppo di zucchero o di zucchero semolato. Montate la panna con lo zucchero e incorporatene 2/3 alla purea di mango, con l''aiuto di una frusta. Distribuite la crema in 4 coppette a calice e guarnite ciascuna con una rosetta di panna, aiutandovi con una tasca di tela munita di una bocchetta a stella. Completate versando sopra ciascuna preparazione un cucchiaio di salsa al cioccolato. --- CONSIGLI. Solo se il frutto è veramente maturo otterrete una purea dal sapore dolce che di per sè già costituisce un dessert molto semplice eppure fine. Si può gustare al naturale oppure addolcita, o, ancora, acidulata, secondo le preferenze. L''aggiunta di yogurth, invece che panna montata, può rappresentare una variante ugualmente valida e ancora più leggera.',2062);
INSERT INTO "ricette" VALUES (7150,'Crema Di Patate','Primo','Patate',4,' -','50 Cl Brodo,
500 G Patate,
1 Cipolla,
25 Cl Latte,
30 G Burro,
1 Uovo,
1/2 Bicchiere Crema Di Latte,
Crostini Di Pane','Rosolare nel burro la cipolla affettata, unire le patate tagliate a pezzi, bagnare con il latte e il brodo e quando il tutto sarà cotto passare al setaccio. Aggiungere il tuorlo d''uovo e la crema di latte, mescolare con cura e servire caldo con i crostini di pane.',1501);
INSERT INTO "ricette" VALUES (7151,'Crema Di Patate (2)','Primo','Patate',4,' -','300 G Patate,
40 G Burro,
Formaggio Grana Grattugiato,
2 Porri,
4 Fette Pancarré,
100 G Panna,
Noce Moscata,
Sale,
Pepe','Lessare in 150 cl d''acqua le patate e frullarle con poco burro. Unire al composto ottenuto la parte bianca dei porri tagliata a fettine, salare, pepare e cuocere per 1/2 ora. Spalmare il pane con il burro, cospargere con il grana e e cuocere in forno finché non è dorato. 5 minuti prime di togliere la crema dal fuoco unire panna e noce moscata. Servire con il grana e i crostoni di pane.',2384);
INSERT INTO "ricette" VALUES (7152,'Crema Di Patate (3)','Primo','Patate',1,'Ricetta adatta a: bambini piccoli.','1 Patata,
250 G Brodo Di Carne Sgrassato,
1 Cucchiaio Crema Di Riso,
1 Omogeneizzato Di Carne,
1 Cucchiaino Olio D''oliva Extra-vergine','Lessare una patata, schiacciarla e aggiungerla a 250 g di brodo di carne sgrassata, portare a bollore e aggiungere un cucchiaio di crema di riso e cuocere per 5-8 minuti mescolando spesso. Togliere dal fuoco e aggiungere un omogeneizzato di carne e un cucchiaino di olio d''oliva extra-vergine.',548);
INSERT INTO "ricette" VALUES (7153,'Crema Di Patate (4)','Primo','Patate',4,' -','600 G Patate,
2 Porri,
50 G Burro,
4 Fette Pancarré,
100 Cl Brodo Vegetale,
1/2 Bicchiere Panna,
Sale','In una casseruola sciogliete 30 g di burro e insaporitevi i porri tritati. Aggiungete le patate pelate e tagliate a pezzetti e lasciate rosolare alcuni minuti. Versate nel recipiente il brodo bollente. Regolate il sale e continuate la cottura per una ventina di minuti a fuoco moderato. Intanto tagliate le fette di pane a cubetti e soffriggeteli nel restante burro. Frullate il composto di patate, ponete di nuovo sul fuoco, fate riprendere il bollore, incorporate la panna, mescolate. Servite la crema ben calda con i crostini. Vini di accompagnamento: Colli Morenici Mantovani Del Garda Bianco DOC, Bianchello Del Metauro DOC, Taburno Bianco DOC.',2487);
INSERT INTO "ricette" VALUES (7154,'Crema Di Patate (5)','Primo','Patate',4,' -','6 Patate,
2 Sedani,
180 Cl Brodo Vegetale,
Formaggio Parmigiano Grattugiato,
1 Pezzetto Burro,
Sale,
Pepe','Pelare le patate, tagliarle a pezzi e versarle nel brodo freddo. Portare ad ebollizione e unire i sedani tagliati a pezzetti. Cuocere per circa 20 minuti quindi passare al passaverdura patate e sedano tenendo da parte il brodo, raccogliere la purea in una zuppiera e diluirla con il brodo fino ad ottenere una crema. Aggiungere un pezzetto di burro e parmigiano a piacere e mescolare. Aggiustare di sale, pepare e servire subito.',2116);
INSERT INTO "ricette" VALUES (7155,'Crema Di Patate Con Mazzancolle','Pesce','Mazzancolle',4,' -','6 Mazzancolle,
3 Patate,
1 Scalogno,
4 Cucchiai Olio D''oliva Extra-vergine,
4 Gocce Tabasco,
3 Foglioline Dragoncello,
Aceto Balsamico,
Sale,
Pepe,
Prezzemolo','Lessare le patate in acqua per circa 15 minuti. Sgusciare le mazzancolle e cuocerle per 3-4 minuti nell''olio. Salare, pepare e togliere dal fuoco, quindi aggiungere 2-3 gocce di tabasco. Intanto schiacciare le patate e condirle con olio, sale, tabasco, dragoncello e prezzemolo. Formare con questo impasto delle quenelles e disporvi sopra le mazzancolle. Condire con olio e aceto balsamico.',1604);
INSERT INTO "ricette" VALUES (7156,'Crema Di Patate E Broccoli','Contorno','Patate',4,' -','1 Cipolla,
4 Patate,
300 G Broccoli,
Sale,
Olio D''oliva Extra-vergine','In una capace pentola, soffriggere la cipolla affettata sottilmente in 2 cucchiai di olio, unire le patate tagliate a dadini ed i broccoli tagliati a pezzetti, far insaporire bene mescolando per qualche minuto. Coprire le verdure con acqua bollente salata e cuocere a fuoco basso e con coperchio per circa 30 minuti. Frullare il tutto servire con un filo d''olio crudo.',1511);
INSERT INTO "ricette" VALUES (7157,'Crema Di Patate E Porri','Contorno','Patate',4,' -','3 Patate,
1 Porro,
1 Spicchio Aglio,
1 Rametto Rosmarino,
Sale,
Olio D''oliva Extra-vergine','Porre tutte le verdure tagliate a dadini in una pentola, coprirle di acqua bollente salata e far cuocere a fuoco basso per circa 20 minuti. Frullare il tutto, aggiustare di sale e rimettere sul fuoco unendo un rametto di rosmarino, far insaporire per circa 5 minuti.',1271);
INSERT INTO "ricette" VALUES (7158,'Crema Di Peperoni','Contorno','Peperoni',4,' -','1 Peperone Rosso,
1 Peperone Giallo,
2 Patate,
1 Cipolla,
100 Cl Brodo,
20 Cl Panna,
Prezzemolo,
40 G Burro,
Sale','Pelare e tagliare a dadini le patate, tagliare a pezzetti i peperoni puliti e affettare la cipolla. Soffriggere la cipolla nel burro, unire patate e peperoni e farli ammorbidire. Aggiungere il brodo e cuocere a fuoco basso per 35 minuti circa. Frullare le verdure e rimetterle nella pentola, unire la panna e il prezzemolo tritato e mescolare bene. Suddividere la crema in 4 fondine e lasciar raffreddare prima di servire.',1894);
INSERT INTO "ricette" VALUES (7159,'Crema Di Peperoni Con Brodo Di Pollame','Primo','Peperoni',4,' -','4 Peperoni Dello Stesso Colore,
3 Cucchiai Olio D''oliva,
1 Cucchiaino Zucchero,
50 G Scalogno Tritato,
2 Cucchiai Succo Di Limone,
50 Cl Brodo Di Pollame,
12 Cl Panna,
1 Spicchio D''aglio Schiacciato,
1 Rametto Timo,
1 Rametto Prezzemolo,
1 Rametto Rosmarino,
Sale,
Pepe Bianco,
1 Pizzico Zenzero Grattugiato','Dividete a metà i peperoni, privateli della pelle, dei semi e delle membrane bianche interne, poi riducete la polpa a listarelle sottili. Fate scaldare l''olio in una casseruola, unite lo zucchero e lo scalogno e lasciate rosolare a fuoco dolce per pochi minuti. Aggiungete il succo di limone e i peperoni e fate cuocere per 5 minuti. Versate il brodo, portate a ebollizione e proseguite la cottura a calore moderato per 10 minuti. Unite la panna e fate cuocere per altri 10 minuti. Trascorsi i primi 5 minuti di cottura aggiungete lo spicchio d''aglio, le erbe aromatiche, il sale, il pepe e lo zenzero. Al termine, eliminate le erbe e l''aglio e passate la preparazione al setaccio. Se lo gradite, potete arricchire la crema con pezzetti di carne di pollo lessata. --- CONSIGLI. Questa è una ricetta base che potrete modificare a piacere variando il colore dei peperoni e il gusto del brodo utilizzato. Indipendentemente dal tipo, i peperoni vanno sempre pelati, per ottenere una crema particolarmente delicata.',1864);
INSERT INTO "ricette" VALUES (7160,'Crema Di Peperoni Con Brodo Di Verdura','Primo','Peperoni',4,' -','Per Il Brodo Di Verdura:,
3 Cipolle,
3 Cucchiai Olio D''oliva,
250 G Porri,
300 G Carote,
150 G Sedano,
150 G Zucchine,
300 G Peperoni Verdi,
25 Cl Vino Bianco Secco,
300 Cl Acqua,
1 Rametto Timo,
2 Foglie Alloro,
1/2 Spicchio Aglio,
Per La Crema Di Peperoni:,
4 Peperoni Dello Stesso Colore,
60 G Brunoise Di Cipolla,
2 Cucchiai Olio D''oliva,
1 Cucchiaio Succo Di Limone,
75 Cl Brodo Di Verdura,
12 Cl Panna,
1 Spicchio D''aglio Schiacciato,
1 Rametto Timo,
1 Rametto Rosmarino,
Sale,
Pepe Bianco','Fate rosolare le cipolle tritate in una casseruola con l''olio, a calore moderato per 4 minuti. Pulite le altre verdure e tritatele, quindi unitele al soffritto e fate insaporire tutt''assieme per alcuni minuti. Versate il vino e l''acqua, unite le erbe aromatiche e l''aglio e fate cuocere per 60-70 minuti, abbassando la fiamma in modo che il brodo sobbolla appena. Schiumate ripetutamente. Al termine filtrate il brodo attraverso un telo, raccogliete il ricavato in una casseruola pulita e fatelo ridurre a calore medio fino ad ottenere 1 litro e mezzo circa di liquido. Lavate i peperoni per la crema e privateli dei semi e delle membrane bianche interne. Fate rosolare la brunoise di cipolla in una casseruola con l''olio, a calore moderato per 4-5 minuti, unite il succo di limone e i peperoni tagliati a dadini e fate cuocere per 5 minuti. Versate il brodo, portate a ebollizione e proseguite la cottura a calore moderato per 10 minuti. Unite la panna e fate cuocere per altri 10 minuti. Trascorsi i primi 5 minuti di cottura aggiungete lo spicchio d''aglio, il timo e il rosmarino, il sale e il pepe. Al termine, eliminate le erbe e l''aglio e passate la preparazione al setaccio. Al momento di servire, potete arricchire la crema con tocchetti di sedano bollito. --- CONSIGLI. Il brodo di verdura è meno nutriente di quello preparato con la carne, tuttavia ha il vantaggio di essere molto leggero, aromatico e privo di grassi. Con il brodo vegetale la crema risulta ancora più delicata e adatta anche a chi ha problemi di natura dietetica. La presenza dei peperoni, fra gli ingredienti del brodo, rende ancora più intenso il sapore finale della crema. Il brodo vegetale di cui vi forniamo la ricetta, se avanza, può essere conservato nel congelatore, diviso in vaschette da una o più porzioni.',2737);
INSERT INTO "ricette" VALUES (7161,'Crema Di Pere','Dessert','Pere',6,' -','1000 G Pere,
3 Cucchiai Acqua,
4 Cucchiai Zucchero A Velo,
1 Vasetto Panna Fresca,
1 Bicchierino Maraschino,
2 Cucchiai Zucchero,
Biscotti Amaretti','Sbucciate le pere, tagliatele in 4 e cuocetele con lo zucchero a velo e l''acqua. Quando saranno cotte frullatele e aggiungete il maraschino. Frullate la panna con i 2 cucchiai di zucchero e aggiungete il tutto al purè di pere. Mettete nella gelatiera. Quando sarà pronto versatelo nelle coppette da gelato che avrete precedentemente tenuto nel congelatore e guarnite con amaretti sbriciolati.',1663);
INSERT INTO "ricette" VALUES (7162,'Crema Di Pesce','Primo','Pesce',4,' -','Alcuni Filetti Pesce Affumicato,
Alcuni Cetriolini Sott''aceto,
Aceto All''aneto,
Yogurth,
Erbe Aromatiche (cipolla, Erba Cipollina)','Frullare alcuni filetti di pesce affumicato con cetriolini sott''aceto, aceto all''aneto, yogurth e varie erbe aromatiche,
dalla cipolla all''erba cipollina.',499);
INSERT INTO "ricette" VALUES (7163,'Crema Di Pesce (2)','Primo','Gamberetti',4,' -','Alcuni Gamberetti Lessati E Sgusciati,
Poco Yogurth,
Alcuni Pomodori,
1 Cucchiaio Panna Liquida','O semplici gamberetti lessati e sgusciati, da frullare con poco yogurth e polpa di pomodori crudi e resi più gentili da una cucchiaiata di panna liquida.',314);
INSERT INTO "ricette" VALUES (7164,'Crema Di Pesce (3)','Primo','Pesce',4,'Luogo: Haiti.','1000 G Filetto Di Pesce (meglio Se Bianco),
Burro,
2 Tuorli D''uovo Sbattuti,
Farina,
25 Cl Vino Bianco,
Sale,
Pepe Bianco','In una padella sciogliete il burro. Aggiungete la farina e mescolate bene. Aggiungete i filetti di pesce lentamente, mescolando costantemente fino a formare una crema morbida. Versate parte della salsa sui tuorli d''uovo, che avrete sbattuto in un piatto a parte. Mescolate bene e rimettete il composto ottenuto nella padella. Fate cuocere per circa 10 minuti a fuoco moderato, girando continuamente. Verso la fine della cottura aggiungete vino, sale e pepe.',2973);
INSERT INTO "ricette" VALUES (7165,'Crema Di Pesche','Dessert','Pesche',4,' -','3 Tuorli D''uovo Freschissimi,
3 Pesche Mature A Pasta Gialla,
5 Cucchiai Zucchero,
Per Servire:,
Alcune Cialde','Sbattere i tuorli con lo zucchero finché non si ottiene una crema spumosa. Pelare, sbucciare e passare al setaccio due pesche. Unire la polpa delle pesche alle uova battute. Sbucciare e tagliare a dadini la terza pesca e aggiungerla al composto. Amalgamare bene il tutto, suddividere in 4 coppette individuali e tenere in frigo almeno 2 ore. Servire con le cialde.',777);
INSERT INTO "ricette" VALUES (7166,'Crema Di Piselli','Primo','Piselli',4,' -','600 G Piselli,
2 Patate,
1 Cipolla Bianca,
4 Fette Pancarré,
Olio D''oliva Extra-vergine,
Sale','Cuocete in acqua salata i piselli sgranati, le patate a dadini e la cipolla affettata. Quando le verdure sono cotte togliete un mestolo di piselli e passate il resto al frullatore. Rimettete la minestra sul fuoco, riportate a bollore, unite i piselli interi, aggiustate di sale. Nel frattempo abbrustolite le fette di pancarré divise in due in poco olio, sistematele nelle fondine, sopra mettete la crema di piselli, condite con un filo d''olio extra vergine e servite.',2505);
INSERT INTO "ricette" VALUES (7167,'Crema Di Piselli (2)','Primo','Piselli',6,'Preparazione: 25 minuti.','450 G Piselli Dolci Surgelati,
40 G Burro,
30 G Farina Bianca,
1 Scalogno,
1 Dado Da Brodo,
3 Fette Pancarré,
Sale','Tritate finemente lo scalogno. Fatelo appassire in una pentola in cui avrete messo g 10 di burro. Unite circa 750 G di brodo, bollente, preparato con un dado. Fate prendere il bollore, poi versatevi i piselli, ancora surgelati, portandoli a cottura (circa 15 minuti). Tagliate a dadini o a rombi il pancarré e tostatelo nel forno. Impastate la farina con il restante burro e stemperatela con un po'' del liquido di cottura dei piselli. Unite quanto preparato alla minestra in ebollizione, mescolando finché questa si addenserà un po''. Passatela al frullatore, quindi servitela accompagnata con i crostini.',1641);
INSERT INTO "ricette" VALUES (7168,'Crema Di Piselli E Lattuga','Primo','Piselli',4,' -','1 Cespo Insalata Lattuga,
300 G Piselli Secchi,
3 Cipolline Fresche,
Alcune Foglie Santoreggia Fresca,
3 Cucchiai Olio D''oliva,
1 Cucchiaio Prezzemolo Tritato','Lasciate in ammollo i piselli per 12 ore e lessateli bene. Nel frattempo stufate le cipolline tritate in un tegame con poco olio. Passate poi entrambi al passaverdure. Aggiungete al composto la lattuga tagliata a striscioline e portate ad ebollizione in un tegame basso. Togliete dal fuoco e unite la santoreggia, l''olio e il prezzemolo tritato. Servite con crostini di pane abbrustolito.',1982);
INSERT INTO "ricette" VALUES (7169,'Crema Di Piselli E Patate','Primo','Piselli',4,' -','600 G Piselli,
3 Patate,
2 Porri,
2 Cucchiai Yogurth,
2 Cucchiai Olio D''oliva,
4 Fettine Pane (fette Sottili),
1/2 Limone,
6 Foglie Menta Fresca,
Sale','In una pentola scaldate l''olio, unite i piselli sgranati, le patate a cubetti, i porri tritati e fate insaporire per un minuto. Coprite con un litro d''acqua e cuocete fino a quando le verdure sono tenere. Lasciate da parte un cucchiaio di piselli, frullate il resto e versatelo nella pentola, unite anche i piselli interi e regolate il sale. Amalgamate lo yogurth alla crema, mescolate bene. Aggiungete le foglie di menta e versate nella zuppiera. Servitela con fettine di pane tostato e spruzzate di limone. Vini di accompagnamento: Grave Del Friuli Traminer DOC, Genzano Bianco DOC, Nuragus Di Cagliari DOC.',1799);
INSERT INTO "ricette" VALUES (7170,'Crema Di Pollo','Primo','Pollo',4,' -','1 Coscia Di Pollo,
1 Osso Di Vitello,
Verdure Da Brodo,
50 G Riso,
Brodo,
2 Tuorli D''uovo,
3 Cucchiai Panna,
1 Noce Burro,
Formaggio Grana Grattugiato','Lessare la coscia di pollo con l''osso di vitello e le verdure. A parte lessare il riso, frullarlo con 2/3 della polpa della coscia, unire un litro di brodo e cuocere per 10 minuti. Unire la rimanente polpa a filetti, i tuorli stemperati con la panna, il burro e molto grana.',2229);
INSERT INTO "ricette" VALUES (7171,'Crema Di Pollo (2)','Primo','Pollo',4,' -','50 G Burro,
50 G Farina,
150 Cl Brodo Di Gallina,
50 G Polpa Di Pollo Lessata E Tritata,
1 Pizzico Noce Moscata,
1 Bicchiere Panna Liquida,
Sale,
Per Servire:,
Crostini,
Burro','Fondere in pentola 50 g di burro e dorarvi 50 g di farina. Diluire il tutto con 150 cl di brodo di gallina, rimescolando. Portare a ebollizione e far sobbollire per 5 minuti. Unire 50 g di polpa di pollo lessata e tritata, un pizzico di noce moscata e un bicchiere di panna liquida. Riportare a ebollizione, togliere dal fuoco, aggiustare di sale e servire con crostini fritti nel burro.',2440);
INSERT INTO "ricette" VALUES (7172,'Crema Di Pollo (3)','Primo','Pollo',1,'Ricetta adatta a: bambini piccoli.','1/2 Fettina Petto Di Pollo,
1/2 Patata,
1/2 Tazza Brodo Di Pollo Sgrassato,
1 Cucchiaio Panna,
1 Pizzico Prezzemolo Tritato,
1 Pizzico Sale','Lessiamo il petto di pollo e la patata e frulliamoli nel brodo di pollo sgrassato. Mettiamo il composto sul fuoco, aggiungiamo il cucchiaio di panna, il prezzemolo tritato, il sale e serviamo la crema.',246);
INSERT INTO "ricette" VALUES (7173,'Crema Di Pollo Alla Panna','Primo','Pollo',4,' -','125 Cl Brodo Di Pollo,
500 G Ossi Di Pollo,
12 Cl Panna,
Sale,
Pepe Bianco,
1 Grattatina Noce Moscata','Fate fondere 20 g di burro in una casseruola e rosolatevi dolcemente le verdure, ridotte a pezzettini minuti, per 5 minuti, quindi cospargetele con la farina e fate soffriggere per un paio di minuti. Infine versate nel recipiente il brodo di pollo. Sminuzzate gli ossi di pollo e fateli bollire in una pentola piena d''acqua, poi scolateli e aggiungeteli al brodo. Lasciate cuocere a calore moderato per circa mezz''ora, dopodichè unite la panna e proseguite la cottura per altri 5-10 minuti. Insaporite la zuppa con sale, pepe e noce moscata, passatela al setaccio e raccoglietela nella casseruola. Incorporatevi il resto del burro, infine frullatela con un frullatore a immersione. Fatela scaldare prima di servire. --- CONSIGLI. La ricetta di questa delicata crema può essere utilizzata per prepararne altre di sapore diverso, sostituendo il brodo di pollo con un uguale quantitativo di brodo di altro tipo (vitello, tacchino, ecc.). Inoltre la stessa crema può essere variata con l''aggiunta di aromi e spezie e arricchita con verdure dal sapore delicato o con quenelle di pollo.',1353);
INSERT INTO "ricette" VALUES (7174,'Crema Di Pomodoro','Primo','Pomodoro',1,'Ricetta adatta a: bambini piccoli.','500 G Acqua,
1 Pomodoro Maturo,
1 Patata,
Poco Sedano,
1 Formaggino Ipolipidico,
1 Cucchiaino Olio D''oliva Extra-vergine','In 500 g di acqua aggiungere 1 pomodoro maturo privato di buccia e semi e tagliato a pezzettini, 1 patata e un po'' di sedano. Portare a ebollizione e cuocere per 20 minuti. Togliere dal fuoco e passare le verdure al setaccio. Aggiungere un Formaggino Ipolipidico o un Omogeneizzato di Carne e un cucchiaino di olio d''oliva extra-vergine.',337);
INSERT INTO "ricette" VALUES (7175,'Crema Di Pomodoro (2)','Primo','Pomodori Perini',4,' -','1000 G Pomodori Perini,
1 Cipolla,
2 Patate,
30 G Burro,
1/2 Bicchiere Panna,
Formaggio Grattugiato,
Sale,
Pepe','In una pentola lasciate appassite nel burro la cipolla tagliata a fettine sottili. Aggiungete i pomodori spellati, privati dei semi, tagliati a spicchi e fate insaporire per un quarto d''ora. Regolate sale e pepe. Versate 3/4 d''acqua. Unite le patate tagliate a cubetti, portate a bollore, diminuite il calore e cuocete per un''ora. Frullate a lungo poco composto alla volta, poi versate il tutto in una pentola, mescolate e tenete sul fuoco fino a quando la crema ha raggiunto una giusta consistenza. In ultimo amalgamatevi la panna e fate scaldare lentamente. Servite con crostini di pane fritti nel burro e con formaggio. Vini di accompagnamento: Riviera Ligure Di Ponente Vermentino DOC, Verdicchio Dei Castelli Di Jesi DOC, Cilento Bianco DOC.',1306);
INSERT INTO "ricette" VALUES (7176,'Crema Di Pomodoro (3)','Primo','Pomodori',4,' -','1000 G Pomodori,
3 Carote,
1 Cipolla,
50 G Burro,
1 Bicchiere Panna Liquida,
Formaggio Parmigiano Grattugiato,
Pepe,
Sale','Scottare e pelare i pomodori, togliere loro i semi e farli insaporire in un soffritto di burro e cipolla tagliata a fettine. Passarli al passaverdura con le carote già lessate. Rimettere al fuoco con 100 cl d''acqua. Lasciar restringere la crema, unire la panna e servire con il parmigiano e crostini di pane fritti al burro, a piacere.',1252);
INSERT INTO "ricette" VALUES (7177,'Crema Di Pomodoro (4)','Primo','Pomodori',4,' -','500 G Pomodori Maturi,
40 G Burro,
200 G Panna Fresca,
500 G Latte,
2 Cucchiai Farina,
20 Foglie Basilico,
1 Pizzico Zucchero,
1 Presa Sale','Lavare i pomodori, tagliarli a pezzi e metterli in pentola con 20 g di burro e 20 foglie di basilico. Cuocere a fuoco basso mescolando. In un tegame dal fondo pesante fondere il burro rimasto, aggiungere 2 cucchiai di farina e il latte, poco per volta, mescolando sempre. Cuocere per 10 minuti. Unire alla besciamella i pomodori passati, un pizzico di zucchero, una presa di sale e la panna. Amalgamare gli ingredienti e servire a temperatura ambiente.',1500);
INSERT INTO "ricette" VALUES (7178,'Crema Di Pomodoro Con Bocconcini Di Mozzarella','Antipasto','Pomodori',4,' -','3 Pomodori,
1 Mozzarella Di Bufala,
1/2 Cipolla,
2 Spicchi Aglio,
10 Cl Olio D''oliva Extra-vergine,
1 Mazzetto Insalata Rucola,
Basilico,
Sale,
Pepe','Tagliare in 4 i pomodori. Soffriggere olio, cipolla e aglio. unire i pomodori, poca acqua, salare, pepare e cuocere per pochi minuti. Passare il tutto al cutter e versare in una zuppiera. Disporre sopra la mozzarella a dadini, la rucola, il basilico e un filo di olio.',1442);
INSERT INTO "ricette" VALUES (7179,'Crema Di Pomodoro E Peperone','Contorno','Pomodori',4,' -','4 Pomodori Ben Maturi,
1 Peperone Rosso,
1 Cipolla Bianca,
1 Peperoncino,
Sale,
Pepe,
2 Cucchiai Olio D''oliva','Preparate un soffritto con la cipolla e il peperoncino in olio d''oliva, tagliate i pomodori e il peperone a cubetti e aggiungeteli al soffritto. Aggiustate di sale e pepe, fate cuocere per una decina di minuti e poi passate al passaverdure. Rimettete la crema sul fuoco e fatela ritirare finché non sarà abbastanza consistente. Potete servirla fredda guarnita con qualche foglia di basilico, o calda aggiungendo piccoli crostini di pane arrostito.',484);
INSERT INTO "ricette" VALUES (7180,'Crema Di Porri','Primo','Porri',4,' -','6 Porri,
30 G Burro,
40 G Farina,
Latte,
100 Cl Brodo Vegetale,
1 Cucchiaio Passato Di Pomodoro,
1 Tuorlo D''uovo,
2 Cucchiai Panna,
20 G Formaggio Grattugiato,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','In un tegame mettete tre cucchiai d''olio e insaporitevi la parte bianca dei porri tagliata a fettine sottili. Versate nel recipiente un bicchiere di latte in cui avete sciolto un cucchiaio di passato di pomodoro, scaldate e frullate. In una pentola fate sciogliere il burro, incorporatevi la farina e, sempre mescolando, aggiungete a poco a poco il brodo freddo come per fare una besciamella. Dopo 20 minuti unite al composto il frullato di porri e cuocete ancora per un quarto d''ora a fiamma molto bassa, salate con moderazione. In una ciotola amalgamate il tuorlo con panna e formaggio. Incorporatelo alla crema lavorando con una piccola frusta. Vini di accompagnamento: Soave DOC, Colli Dell''Etruria Centrale DOC, Gravina DOC.',2252);
INSERT INTO "ricette" VALUES (7181,'Crema Di Prosciutto','Antipasto','Prosciutto Cotto',6,' -','150 G Prosciutto Cotto,
60 G Burro A Temperatura Ambiente,
Formaggio Parmigiano Grattugiato,
150 Cl Brodo Di Dado,
50 G Crema Di Riso,
20 Cl Panna,
Crostini Di Pane','Tritare finemente il prosciutto cotto, passarlo al passaverdura con il burro, mescolarlo con il parmigiano e mettere il composto in 1 zuppiera. In 1 casseruola portare ad ebollizione il brodo, mescolarvi la crema di riso diluita con 1 mestolo d''acqua fredda e lasciar cuocere per 5 minuti. Aggiungere la panna e farla scaldare senza bollire; versare il tutto lentamente, sempre rimestando, nella zuppiera; servire dopo 5 minuti con a parte i crostini di pane.',3206);
INSERT INTO "ricette" VALUES (7182,'Crema Di Prosciutto Con Il Bimby','Primo','Prosciutto Magro',1,'Ricetta adatta a: bambini piccoli.','120 G Patate Sbucciate,
20 G Prosciutto Magro,
2 Foglie Insalata Lattuga,
20 G Semolino Di Grano Istantaneo,
250 G Acqua,
1 Cucchiaino Olio D''oliva Extra-vergine','Inserire nel boccale l''insalata e le patate a pezzetti per 20 secondi portando lentamente da velocità 1 a velocità 8. Aggiungere l''acqua e cuocere per 12 minuti a 90-100 gradi a velocità 2. Terminata la cottura inserire del foro il prosciutto a pezzetti e il semolino per 20 secondi a velocità 4 e per 15 secondi a velocità 8. Versare la pappa e aggiungere un cucchiaino d''olio.',360);
INSERT INTO "ricette" VALUES (7183,'Crema Di Ricotta','Dessert','Ricotta',8,' -','500 G Ricotta Romana,
180 G Panna Montata,
140 G Zucchero Semolato,
80 G Zucchero A Velo,
100 G Albicocche Secche,
4 Fogli Colla Di Pesce,
4 Uova,
50 Cl Latte,
20 G Maizena,
Apricot Brandy','Tagliate le albicocche a pezzetti e lasciatele macerare nell''apricot. In una pentolina montate i tuorli con lo zucchero semolato; unite la maizena sciolta con un po'' di latte tiepido e poi versate il resto del latte freddo. Appena il composto alza il bollore unite la colla di pesce ben strizzata, mescolate, ritirate dal fuoco, fate raffreddare. Frullate la ricotta e lo zucchero a velo. Amalgamate crema, ricotta, panna montata, albicocche con il loro liquore. Versate in coppa e ponete in frigo.',3275);
INSERT INTO "ricette" VALUES (7184,'Crema Di Ricotta Alla Banana','Dessert','Ricotta',1,' -','60 G Ricotta Freschissima,
1/2 Banana Schiacciata,
1 Cucchiaino Zucchero','Per la merenda mescolare accuratamente 60 g di ricotta freschissima, mezza banana schiacciata, un cucchiaino di zucchero. Servire quando il composto avrà assunto i caratteri di una crema morbida.',174);
INSERT INTO "ricette" VALUES (7185,'Crema Di Ricotta Con Cipolle','Antipasto','Ricotta',4,' -','Ricotta,
Cipolle A Fettine Sottili,
Aceto Di Vino (o Aceto Balsamico)','Amalgamare bene la ricotta con cipolle a fettine sottili e un po'' d''aceto.',162);
INSERT INTO "ricette" VALUES (7186,'Crema Di Ricotta Con Mirtilli','Dessert','Ricotta',4,' -','2 Tuorli D''uovo,
10 Cl Latte,
80 G Zucchero,
2 Fogli Gelatina,
Zucchero Vanigliato,
1/2 Limone,
180 G Ricotta Passata Al Colino,
10 Cl Panna,
1 Cl Rum,
150 G Mirtilli,
1 Cucchiaio Miele','Sbattete i tuorli, il latte, lo zucchero e lo zucchero vanigliato sopra una pentola piena d''acqua calda finché questa non diventa bollente, dopodichè mettete da parte il miscuglio, aggiungetevi la gelatina ammorbidita e spremuta. Quando l''impasto si è raffreddato, unite la ricotta, il rum, il succo di limone e la buccia di limone. Prima che l''impasto si indurisca, aggiungetevi la panna montata, versatelo subito nei bicchieri e fate raffreddare. A questo punto mescolate i mirtilli con il miele. Quando è l''ora di servire, versate il miscuglio sulla crema di ricotta e guarnite con una rosetta di panna montata.',1393);
INSERT INTO "ricette" VALUES (7187,'Crema Di Ricotta Della Nonna','Primo','Ricotta',4,' -','800 G Ricotta,
120 G Zucchero,
3 Tuorli D''uovo,
1 Bicchiere Latte,
1/2 Bicchiere Alchermes,
1 Cucchiaio Zucchero Vanigliato,
1 Pizzico Cannella,
1 Scatola Biscotti Savoiardi','Sciogliere la ricotta con il latte, poi unire tutti gli altri ingredienti, esclusi i biscotti, sbattendo per circa 1 ora con 1 cucchiaio di legno. Comporre il dolce in 1 vassoio alternando gli strati con i savoiardi bagnati nel liquore. Livellare l''ultimo strato di ricotta con la lama di 1 coltello bagnata nell''acqua bollente. Guarnire a piacere e mettere in frigo per qualche ora.',2904);
INSERT INTO "ricette" VALUES (7188,'Crema Di Ricotta E Verdure','Antipasto','Ricotta',4,' -','200 G Ricotta,
100 G Acetosella,
2 Cespi Insalata Lattuga,
2 Patate Piccole,
2 Porri,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Pelate le patate, lavatele e tagliatele a cubetti. Mondate e tagliate finemente la lattuga, l''acetosella e i porri. Mettete tutto in un tegame con le patate. Versatevi un litro d''acqua e quando giunge a ebollizione salate e pepate. Coprite il recipiente e cuocete per circa mezz''ora a fuoco moderato. Togliete il composto dal fuoco e frullatelo. Versatelo di nuovo nel tegame e amalgamatevi la ricotta passata al setaccio. Mescolate e fate scaldare a fiamma non troppo alta. Versate il composto nella zuppiera, aggiungete due cucchiai d''olio, cospargete con un po'' di prezzemolo tritato e servite. Vini di accompagnamento: Erbaluce Di Caluso DOC, Orvieto DOC, Gioia Del Colle Bianco DOC.',1390);
INSERT INTO "ricette" VALUES (7189,'Crema Di Riesling','Salsa','Vino',4,' -','50 Cl Vino Riesling,
2 Patate,
50 Cl Brodo Ristretto,
1 Noce Burro,
3 Cucchiai Panna,
1/2 Cucchiaio Farina','Fate restringere il vino con le patate. Quando saranno cotte passatele con lo schiacciaverdura ed unite il brodo. A parte amalgamate il burro con la farina e la panna ed unite tutto al brodo. Frullate e controllate la densità se troppo denso fate bollire ancora un poco.',1667);
INSERT INTO "ricette" VALUES (7190,'Crema Di Riso Al Cardamomo','Primo','Cardamomo',4,'Luogo: Afghanistan.','100 Cl Latte,
150 G Riso (o Farina Di Riso),
5 Capsule Cardamomo,
3 Cucchiai Zucchero,
1 Manciata Pistacchi (o Mandorle)','Macinare il riso con il macinino del caffè, o usare la farina di riso già pronta. In una pentola versare il latte, aspettare che prenda il bollore, poi aggiungere il riso mescolando bene con l''apposita frusta. Cuocere per 25 minuti a fuoco lento e a fine cottura unire lo zucchero e il cardamomo, utilizzando i piccoli semi dell''interno, che anch''essi devono essere macinati. Amalgamare tutto con cura. Versare la crema di riso in coppette individuali e lasciare raffreddare a temperatura ambiente. Prima di portare il dessert in tavola, guarnire le coppette con pistacchi o mandorle finemente tritati.',1250);
INSERT INTO "ricette" VALUES (7191,'Crema Di Riso All''anice','Dessert','Riso',4,' -','100 G Riso,
100 Cl Latte,
2 Bacche Anice Stellato,
1 Baccello Vaniglia,
100 G Zucchero,
2 Mele Delizia,
30 G Burro,
1 Bicchierino Cognac,
1 Pizzico Sale','Riunite in una casseruola il latte con 80 g di zucchero, il sale, le bacche di anice stellato, il baccello di vaniglia inciso nel senso della lunghezza, e portate ad ebollizione. Unite il riso e cuocete a fiamma bassa per circa 30 minuti, mescolando di tanto in tanto con un cucchiaio di legno, spegnete, eliminate anice e vaniglia e lasciate raffreddare completamente. Lavate le mele, asciugatele, tagliatele a metà, eliminate il torsolo e riducetele a spicchi sottili; fate sciogliere il burro in una padella, unite le mele e cuocetele a fiamma viva per 5 minuti. Spolverizzate le mele con lo zucchero rimasto e fatelo caramellare; bagnate con il cognac, infiammatelo con un fiammifero e, quando la fiamma si sarà spenta togliete la padella dal fuoco. Suddividete le mele sul fondo di quattro bicchieri, tenendo da parte, qualche fettina per il decoro; mescolate alla crema di riso il fondo di cottura delle mele e distribuitela nei bicchieri, sopra la frutta. Decorate con le fettine di mela tenute da parte e servite.',1742);
INSERT INTO "ricette" VALUES (7192,'Crema Di Riso All''uovo','Primo','Uovo',1,'Ricetta adatta a: bambini piccoli.','250 G Acqua Bollita Leggermente Salata,
5 Cucchiai Crema Di Riso Precotta,
1 Cucchiaino Olio D''oliva,
1 Tuorlo D''uovo Crudo','In 250 g d''acqua bollita e leggermente salata, stemperare 5 cucchiai di crema di riso precotta. Aggiungere un cucchiaino d''olio d''oliva e un tuorlo d''uovo crudo. Mescolare accuratamente e servire.',546);
INSERT INTO "ricette" VALUES (7193,'Crema Di Riso All''uovo (2)','Primo','Uovo',1,'Ricetta adatta a: bambini piccoli.','250 G Brodo Vegetale Leggermente Salato,
5 Cucchiai Crema Di Riso Precotta,
1 Cucchiaino Olio D''oliva,
1 Tuorlo D''uovo Crudo','In 250 g di brodo vegetale leggermente salata, stemperare 5 cucchiai di crema di riso precotta. Aggiungere un cucchiaino d''olio d''oliva e un tuorlo d''uovo crudo. Mescolare accuratamente e servire.',628);
INSERT INTO "ricette" VALUES (7194,'Crema Di Riso All''uovo (3)','Primo','Uovo',1,'Ricetta adatta a: bambini piccoli.','250 G Brodo Di Carne Leggermente Salato,
5 Cucchiai Crema Di Riso Precotta,
1 Cucchiaino Olio D''oliva,
1 Tuorlo D''uovo Crudo','In 250 g di brodo di carne leggermente salato, stemperare 5 cucchiai di crema di riso precotta. Aggiungere un cucchiaino d''olio d''oliva e un tuorlo d''uovo crudo. Mescolare accuratamente e servire.',628);
INSERT INTO "ricette" VALUES (7195,'Crema Di Riso Con Zucca','Primo','Zucca',1,'Ricetta adatta a: bambini piccoli.','300 G Acqua,
1 Fetta Zucca,
2 Cucchiai Crema Di Riso,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Cucchiaio Formaggio Parmigiano Grattugiato','Preparare un brodo mettendo a bollire per un''ora, in 300 g d''acqua, una fetta di zucca tagliata pezzetti. Stemperare in 180 g di brodo 2 cucchiai di crema di riso precotta. Aggiungere la zucca passata al setaccio, un cucchiaino d''olio d''oliva ed un cucchiaio di parmigiano grattugiato.',272);
INSERT INTO "ricette" VALUES (7196,'Crema Di Riso Con Zucca (2)','Primo','Zucca',1,'Ricetta adatta a: bambini piccoli.','300 G Acqua,
1 Fetta Zucca,
2 Cucchiai Crema Di Riso,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Formaggino','Preparare un brodo mettendo a bollire per un''ora, in 300 g d''acqua, una fetta di zucca tagliata pezzetti. Stemperare in 180 g di brodo 2 cucchiai di crema di riso precotta. Aggiungere la zucca passata al setaccio, un cucchiaino d''olio d''oliva ed 1 formaggino.',250);
INSERT INTO "ricette" VALUES (7197,'Crema Di Riso Con Zucca (3)','Primo','Crema Di Riso',1,'Ricetta adatta a: bambini piccoli.','1 Fetta Zucca,
300 G Acqua,
4 Cucchiai Crema Di Riso Precotta,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Cucchiaino Formaggio Parmigiano','Tagliare la zucca a pezzettini e farla bollire nell''acqua per circa 60 minuti e tenete in serbo 200 g di brodo. Passate la zucca al passaverdure. Aggiungete al brodo caldo 4 cucchiai di crema di riso, stemperatela e aggiungete la zucca. Condite con l''olio e il parmigiano.',405);
INSERT INTO "ricette" VALUES (7198,'Crema Di Riso In Brodo Vegetale','Primo','Brodo Vegetale',4,'Ricetta adatta a: bambini piccoli.','200 G Brodo Vegetale,
2 Cucchiai Crema Di Riso,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Cucchiaio Formaggio Parmigiano Grattugiato','In una casseruola stemperiamo la crema di riso nel brodo vegetale. Portiamo lentamente a bollore e cuociamo, mescolando con un cucchiaio di legno, per una ventina di minuti. Togliamo quindi dal fuoco e aggiungiamo un cucchiaino di olio d''oliva extra-vergine e il parmigiano reggiano grattugiato.',316);
INSERT INTO "ricette" VALUES (7199,'Crema Di Riso Per Neonati','Primo','Crema Di Riso',1,'Ricetta adatta a: bambini piccoli.','2 Cucchiai Crema Di Riso,
Brodo Per Neonati (v. Ricetta),
1 Cucchiaino Olio D''oliva Extra-vergine (facoltativo),
1 Cucchiaino Formaggio Parmigiano (facoltativo),
1 Cucchiaino Verdure Passate (facoltativo),
Carne Omogeneizzata (facoltativo)','Stemperare la crema di riso nel brodo. Si possono aggiungere l''olio e/o il parmigiano grattugiato e/o le verdure passate e/o la carne omogeneizzata.',368);
INSERT INTO "ricette" VALUES (7200,'Crema Di Sambuco','Dessert','Bacche Di Sambuco',4,' -','200 G Bacche Di Sambuco,
60 G Zucchero,
1 Pizzico Cannella In Polvere,
50 Cl Latte,
60 G Farina,
30 G Burro','In una casseruola posta sul fuoco, versare le bacche di sambuco, lo zucchero, un pizzico di cannella, poi aggiungere tanta acqua fino a coprire. Man mano che procede il bollore, schiumare con un mestolo forato. Quando le bacche sono cotte, passarle al setaccio e versare la crema ottenuta in un altro tegame. Unire il latte, il burro e, per ultima, la farina. Far bollire piano, mescolando continuamente, fino alla consistenza desiderata.',940);
INSERT INTO "ricette" VALUES (7201,'Crema Di Sciroppo D''acero','Dessert','Sciroppo Acero',4,' -','4 Tuorli D''uovo,
50 G Zucchero Di Canna,
250 G Sciroppo D''acero,
6 Fogli Colla Di Pesce,
4