to a parte assieme alla panna, scaldate la salsa per pochi secondi facendola leggermente addensare e versatela nella salsiera. Servite il pollo caldo accompagnato con la salsa.',2580);
INSERT INTO "ricette" VALUES (19169,'Pollo Al Dragoncello (2)','Pollame','Pollo',4,' -','1 Pollo Ruspante,
1 Mazzetto Dragoncello,
Salvia,
1/2 Limone,
2 Noci Strutto,
Olio D''oliva Extra-vergine,
Sale,
Pepe Bianco','Pulire e fiammeggiare il pollo, lavarlo, asciugarlo e strofinarlo dentro e fuori col limone. Sciogliere a fuoco basso metà strutto e unirvi il dragoncello finemente triturato, inserire all''interno del pollo e cucire. Salare e pepare all''esterno e accomodare in una pirofila con fiocchetti di strutto, irrorare d''olio e cuocere in forno. Servire con una salsa al dragoncello.',2683);
INSERT INTO "ricette" VALUES (19170,'Pollo Al Formaggio','Pollame','Pollo',4,' -','2 Petti Di Pollo,
80 G Formaggio Emmenthal,
2 Fette Prosciutto Cotto,
Vino Bianco,
1/2 Limone (succo),
Olio D''oliva,
Burro,
Farina,
Sale','Sfilettare i petti di pollo e infarinarli. In un tegame scaldare olio e un po'' di burro, adagiarvi i filetti di pollo e rosolarli circa 5 minuti per parte. Spruzzarli con 1/2 bicchiere di vino bianco e il limone, far evaporare. Aggiungere 2 cucchiai di acqua calda. Su ogni filetto di pollo mettere una fetta di emmenthal e 1/2 fetta di prosciutto, coprire il tegame, far cuocere ancora qualche minuto e servire.',3307);
INSERT INTO "ricette" VALUES (19171,'Pollo Al Formaggio (2)','Pollame','Pollo',4,' -','2 Petti Di Pollo,
80 G Formaggio Emmenthal,
2 Fette Prosciutto Cotto,
1/2 Bicchiere Vino Bianco Secco,
1/2 Limone (succo),
1 Cucchiaio Olio D''oliva,
1 Noce Burro,
Farina,
Sale','Mondare i petti di pollo e dividerli in 4 filetti uguali poi salare ogni filetto e infarinarlo. Farli rosolare, in 1 tegame largo, con 1 cucchiaio d''olio e 1 noce di burro, per 5 minuti per parte. Spruzzarli con 1/2 bicchiere di vino e con il succo di limone, alzare la fiamma e farlo evaporare, poi unire 2 cucchiai di acqua calda. Coprire ogni filetto con 1/2 fetta di prosciutto e 1 fetta di emmenthal, coprire il recipiente e tenere sul fuoco ancora per qualche minuto.',2696);
INSERT INTO "ricette" VALUES (19172,'Pollo Al Forno','Pollame','Pollo',4,' -','1 Pollo Novello Di 1000 G,
30 G Burro,
1 Rametto Rosmarino,
2 Spicchi Aglio,
Olio D''oliva,
Sale,
Pepe','Tagliate le zampe al pollo, avvicinate le cosce al corpo e legatele; ripiegate la testa sotto l''ala sinistra e infilate nella pancia gli spicchi di aglio e il rametto di rosmarino. Se ne gradite il profumo, unite anche due o tre foglioline intere di alloro. Legate bene le ali fra di loro con uno spago sottile. Disponete il pollo in una casseruola salatelo, pepatelo e irroratelo con un po'' di olio, cospargendolo con il burro a fiocchetti. Mettete il recipiente in forno già caldo, irrorate il pollo di tanto in tanto con il sughetto di cottura e cuocetelo per 45 minuti circa, rigirandolo di sovente. Prima di sfornarlo punzecchiatelo vicino alla coscia con i rebbi della forchetta e, se dovesse uscire un liquido rossastro, lasciatelo in forno ancora un po''. Servitelo subito in tavola accompagnandolo con patate tagliate a bastoncini e fritte nell''olio.',2065);
INSERT INTO "ricette" VALUES (19173,'Pollo Al Forno Al Limone','Pollame','Pollo',4,' -','1 Pollo Di 1200 G,
1 Dado Di Pollo,
1 Limone,
3 Cucchiai Olio D''oliva,
1 Noce Burro,
Sale,
Pepe','Fiammeggiate e lavate il pollo; sbriciolate il dado e strofinateci l''interno. Inserite nella pancia del pollo un limone intero dopo averlo forato con una forchetta. Cucite le aperture del po lo con filo bianco, salatelo e pepatelo all''esterno e mettetelo in una teglia con l''olio. Aggiungete qualche fiocchetto di burro ed infornate a 200 gradi per circa 1 ora e un quarto, fino a quando non è ben dorato e con la pelle croccante.',2961);
INSERT INTO "ricette" VALUES (19174,'Pollo Al Ginepro','Pollame','Pollo',4,' -','1 Pollo Di 1200 G,
1 Limone,
30 Bacche Ginepro,
1 Spicchio Aglio,
Sale,
Pepe','Pulire il pollo, fiammeggiarlo, lavarlo e asciugarlo. Aprirlo e appiattirlo leggermente, poi farcirlo con il limone sbucciato, l''aglio tagliato a lamelle e le bacche lavate; salare e pepare. Ricomporre il pollo, legarlo, salarlo esternamente e metterlo in forno caldo a 180 gradi. Cuocere per 40 minuti. toglierlo dal forno, rigirarlo e cuocere per altri 20 minuti. Slegarlo, eliminare limone e aglio e servire caldo tagliato a pezzi.',1418);
INSERT INTO "ricette" VALUES (19175,'Pollo Al Latte','Pollame','Pollo',4,' -','8 Fette Petto Di Pollo,
1 Bicchiere Latte,
Sale,
Pepe,
Farina,
30 G Burro','Infarinate i filetti di pollo, fate sciogliere il burro in una teglia e dorate la carne a fuoco vivace da entrambi i lati salando e pepando. Aggiungete il latte, coprite e fate cuocere a fiamma bassa per 15 minuti.',2350);
INSERT INTO "ricette" VALUES (19176,'Pollo Al Limone','Pollame','Pollo',4,' -','100 G Uvetta Sultanina,
2 Cucchiai Olio D''oliva,
2 Cipolle,
1 Pollo,
Sale,
Pepe,
2 Spicchi Aglio,
1 Mazzetto Verdura,
4 Limoni,
1 Bicchiere Vino Bianco Secco,
1 Bicchiere Brodo,
100 G Pinoli,
1 Yogurth Naturale','Mettere l''uva secca in una ciotola di acqua tiepida. Lasciare gonfiare. Versare l''olio in una cocotte. Mettete le cipolle tagliate rotonde e fate dorare il pollo da tutte le parti. Mettete sale e pepe. Aggiungete i gusci d''aglio, il mazzetto di verdura, due limoni tagliati a rotella e il succo di due altri. Bagnate con il vino bianco e il brodo. Coprite. Lasciate bollire lentamente 30 minuti a fuoco lento. Aggiungete poi l''uva sultanina scolata e i pinoli. Mescolate. Coprite. Proseguire la cottura ancora 20 minuti. Metteteci lo yogurth. Sciogliere il tutto. Coprite. Finire la cottura per altri 10 minuti.',3290);
INSERT INTO "ricette" VALUES (19177,'Pollo Al Limone (2)','Pollame','Pollo',4,' -','1 Pollo,
75 G Burro,
1 Rametto Rosmarino,
Poca Farina,
Brodo Di Dado,
Sale,
Pepe,
Limone,
Cipolla','Dividere il pollo a pezzi e infarinarli. Cuocere i pezzi di pollo nell''olio e nel burro con la cipolla tritata per 15 minuti, salare e pepare. Bagnarlo con il brodo e cuocere a fiamma bassa per altri 10 minuti, quindi spruzzarlo con il limone e servire.',2489);
INSERT INTO "ricette" VALUES (19178,'Pollo Al Limone (3)','Pollame','Pollo',4,' -','1 Pollo,
2 Limoni,
30 G Burro,
1 Spicchio Aglio,
1 Ciuffo Prezzemolo,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Soffregate esternamente il pollo con mezzo limone e poi farcitelo con alcune fettine di limone, una noce di burro e lo spicchio d''aglio. Mettete in una teglia l''olio, il restante burro, sistematevi il volatile, salate, pepate e cuocete in forno preriscaldato a 180 gradi per un''ora e un quarto abbondante. A metà cottura bagnate con il succo di un limone spremuto al momento. Tagliate il dorso e il petto del pollo in quattro pezzi, staccate le ali e le cosce, disponete il tutto sul piatto da portata caldo, cospargete di prezzemolo tritato e servite. Vini di accompagnamento: Valle D''Aosta Nus Rosso DOC, Sangiovese Di Romagna Novello DOC, Brindisi Rosato DOC.',2317);
INSERT INTO "ricette" VALUES (19179,'Pollo Al Limone (4)','Pollame','Pollo',4,' -','1 Pollo Da 1500 G,
1000 G Limoni,
200 G Olive Verdi E Nere,
3 Cucchiai Olio D''oliva,
Pepe','Pulire e lavare il pollo, poi tagliarlo in piccoli pezzi. Lavare molto bene i limoni e snocciolare le olive. Tagliare a pezzi i limoni con la buccia e porli in un tegame di coccio con le olive e i pezzi di pollo. Unire l''olio e pepare. Non è necessario salare perché le olive insaporiranno il pollo durante la cottura. Coprire e cuocere a fuoco bassissimo per 90 minuti. Mescolare di tanto in tanto. Al momento di servire eliminare i pezzi di limone.',3137);
INSERT INTO "ricette" VALUES (19180,'Pollo Al Limone (5)','Pollame','Pollo',4,' -','1 Pollo Ruspante,
4 Limoni,
Sale Marino,
Pepe','Inserire un limone intero nella cavità addominale del pollo ovviamente pulito ed eviscerato. Adagiare il pollo in un recipiente da forno di coccio e irrorarlo col succo degli altri limoni. Salare e pepare la superficie, unire 3 cucchiai d''acqua e coprire col suo coperchio. Infornare per 1 ora a 200 gradi, quindi scoprire e far prendere colore ancora per 30 minuti. Servire con riso pilaf.',1414);
INSERT INTO "ricette" VALUES (19181,'Pollo Al Limone Tedesco','Pollame','Pollo',4,'Luogo: Germania.','1 Pollo Di 1500 G,
Sale,
Pepe,
1 Rametto Salvia,
1 Spicchio Limone,
Burro Fuso,
Succo Di Limone,
1 Bicchierino Sherry Secco','Lavare e asciugare 1 pollo di circa 1500 g, condirlo con sale e pepe dentro e fuori, mettere all''interno 1 rametto di salvia e 1 spicchio di limone. Ungere il pollo con 30 g di burro fuso e porlo in forno in una teglia con i bordi alti. Cuocerlo a 200 gradi girandolo ogni tanto e bagnandolo con burro fuso e succo di limone. Dopo 90 minuti togliere il pollo dal forno, tagliarlo e bagnarlo con il fondo di cottura deglassato con 1 bicchierino di sherry secco.',2551);
INSERT INTO "ricette" VALUES (19182,'Pollo Al Marsala Con Mele E Mandorle','Pollame','Pollo',4,' -','4 Petti Di Pollo,
2 Mele Annurche,
50 G Mandorle,
1 Noce Burro,
Vino Marsala,
Sale,
Farina','Infarinare il pollo e dorarlo con il burro. Bagnare con il marsala e lasciare evaporare. Unire un po'' d''acqua, le mandorle e le mele a pezzi. Coprire e portare a cottura.',2442);
INSERT INTO "ricette" VALUES (19183,'Pollo Al Miele','Pollame','Pollo',4,' -','1 Pollo Di 1200 G,
40 G Miele,
25 G Burro,
25 G Olio D''oliva,
2 Spicchi Aglio,
Timo,
Rosmarino,
Chiodi Di Garofano,
Salvia,
Sale,
Pepe','Fiammeggiate, pulite bene il pollo, lavatelo e strofinatelo col burro. Mettete nell''addome l''aglio tagliato in pezzi, gli aromi sminuzzati, salate e pepate. Mettetelo in un tegame, unite l''olio e infornatelo a 180 gradi. A metà cottura toglietelo dal forno e pennellatelo col miele, quindi rimettetelo in forno e, di tanto in tanto, bagnatelo col suo sugo.',1949);
INSERT INTO "ricette" VALUES (19184,'Pollo Al Miele (2)','Pollame','Pollo',4,' -','1 Pollo Da 1500 G,
40 G Miele,
25 G Burro,
2 Spicchi Aglio,
Timo,
Rosmarino,
Salvia,
Chiodi Di Garofano,
Olio D''oliva,
Sale,
Pepe','Pulire e fiammeggiare il pollo, eviscerarlo, lavarlo ed asciugarlo. Strofinarlo esternamente ed internamente con il burro poi riempire l''interno con le spezie sminuzzate, l''aglio affettato, sale e pepe. Metterlo in una teglia unta e bagnarlo con 25 g di olio. Infornare a 180 gradi. A metà cottura levare il pollo dal forno, spennellarlo con il miele e proseguire la cottura.',2760);
INSERT INTO "ricette" VALUES (19185,'Pollo Al Peperone','Pollame','Pollo',4,' -','1 Pollo,
3 Pomodori,
4 Peperoni Gialli,
400 G Fagiolini,
Burro,
Olio D''oliva,
1 Cipolla,
Sale,
Prezzemolo,
Limone','Pulite il pollo e tagliatelo a pezzi, mettetelo in una padella con il sale, l''olio e una cipolla tritata e lasciate rosolare per 15 minuti. Aggiungete i pomodori tagliati a pezzi e il prezzemolo tritato, cuocete per 1 ora e mezzo mescolando continuamente. In una padella a parte, cuocete con dell''olio e dell''aglio, i peperoni gialli tagliati a fette. Condite, a parte, con olio e succo di limone, 400 g di fagiolini che avrete precedentemente lessato. Servite mettendo intorno al vassoio i peperoni, poi il pollo e al centro i fagiolini.',3402);
INSERT INTO "ricette" VALUES (19186,'Pollo Al Prosciutto','Pollame','Pollo',4,' -','2 Petti Di Pollo Interi,
4 Cucchiai Olio D''oliva,
100 G Di Prosciutto Crudo,
1 Limone,
8 Cucchiai Latte','Aprire e battere i petti di pollo. Scaldare l''olio in una padella e adagiarvi i petti di pollo. Cuocerli un paio di minuti per parte facendoli colorire. Tagliare a striscioline il prosciutto e unirlo ai petti di pollo, spruzzare con il succo di limone, coprire, abbassare la fiamma e cuocere per 5-10 minuti. Levare i petti di pollo dalla padella e tenerli in caldo. Versare 8 cucchiai di latte nella padella e far restringere il sugo a fuoco vivace, versarlo sui petti di pollo e servire.',2617);
INSERT INTO "ricette" VALUES (19187,'Pollo Al Rosmarino','Pollame','Pollo',4,' -','1 Pollo Ruspante Di 1000 G,
Poca Farina,
2 Cucchiai Olio D''oliva Extra-vergine,
1 Tazza Brodo,
1 Cipolla,
1 Spicchio Aglio,
1 Rametto Rosmarino,
Poco Vino Bianco,
Sale,
Pepe','Fiammeggiate il pollo, togliete le eventuali pennette rimaste quindi spuntate le ali e dividetelo in otto parti incidendolo alle giunture. Lavatelo sotto l''acqua corrente, asciugatelo e infarinate leggermente ogni pezzo. Scaldate l''olio in un tegame, mettetevi il pollo e fatelo rosolare girandolo spesso. Mondate la cipolla e tritatela finissima insieme allo spicchio d''aglio e alle foglioline di un rametto di rosmarino. Quando il pollo avrà preso un bel colore uniforme, tiratelo su dal tegame e tenetelo in caldo fra 2 piatti. Versate nel tegame il trito preparato e fatelo appassire a fuoco moderato. Quando la cipolla comincia a prendere colore, rimettete il pollo nel tegame, salate, pepate e fatelo insaporire per qualche minuto nel soffritto aggiungendo qualche cucchiaio di vino quando tende ad attaccarsi. Infine aggiungete il brodo, incoperchiate e proseguite la cottura per circa 45 minuti (più o meno secondo la qualità del pollo). Servite ben caldo.',1792);
INSERT INTO "ricette" VALUES (19188,'Pollo Al Sale','Pollame','Pollo',4,' -','1 Pollo Di 1300 G,
1000 G Sale Grosso,
Salvia,
Rosmarino','Sventrare il pollo, fiammeggiarlo, lavarlo e asciugarlo accuratamente. Mettere all''interno del pollo la salvia e il rosmarino. In una pirofila ovale e con i bordi alti disporre uno strato di sale sul fondo, adagiarvi il pollo e ricoprirlo completamente con il sale. Cuocere in forno caldo a 190 gradi per circa 1 ora. Levare dal forno, rompere la crosta di sale e servire subito il pollo.',1487);
INSERT INTO "ricette" VALUES (19189,'Pollo Al Sale (2)','Pollame','Pollo',4,' -','1 Pollo Di 1500 G,
1 Foglia Alloro,
1 Pizzico Timo,
1 Foglia Salvia,
1 Rametto Rosmarino,
1 Spicchio Aglio,
2000 G Sale Grosso','Eviscerare il pollo, fiammeggiarlo, lavarlo e asciugarlo con carta assorbente da cucina. Metterlo in una teglia e aromatizzarlo con le erbe e con l''aglio, mondati e tritati. Ricoprirlo con il sale e metterlo nel forno caldo a 200 gradi per 90 minuti. Dopo la cottura spaccare la crosta di sale, eliminarla e servire.',1701);
INSERT INTO "ricette" VALUES (19190,'Pollo Al Sale Aromatizzato Al Curry','Pollame','Pollo',4,' -','1 Pollo Pulito,
1000 G Sale Fino,
1000 G Sale Grosso,
1 Vasetto Curry,
1 Rametto Rosmarino,
3 Spicchi Aglio,
Poca Acqua','Mescolare i 2 sali con il curry, aggiungere acqua per inumidire. In una pirofila da forno fate una base di almeno 2 cm adagiatevi il pollo in cui avrete messo all''interno l''aglio e il rosmarino, aggiungere l''altro sale, sia intorno e sopra pressando e ricoprendo bene. Cuocere per circa 180 minuti in forno a 180-200 gradi. Il pollo risulterà asciutto, morbido e profumato al curry ma non piccante.',1197);
INSERT INTO "ricette" VALUES (19191,'Pollo Al Timo','Pollame','Pollo',4,' -','1 Pollo Di 1250 G,
3 Bicchieri Vino Bianco,
Timo Fresco,
Alloro,
Aglio,
Prezzemolo,
50 G Burro,
Olio D''oliva,
1/2 Cipolla,
Sale,
Pepe','Eviscerare e fiammeggiare il pollo, lavarlo e tagliarlo a pezzetti. Lasciarlo marinare con il vino bianco, il timo e il prezzemolo lavati (non tritati), l''alloro, sale e pepe per 2 ore, rigirandolo ogni tanto. In una padella larga far scaldare il burro e l''olio con la cipolla e l''aglio sbucciati e tritati; adagiarvi i pezzi di pollo e lasciarli dorare. Poi a fiamma bassa far cuocere per 1 ora, unendo poco per volta parte del vino della marinata filtrato.',2896);
INSERT INTO "ricette" VALUES (19192,'Pollo Al Tonno','Pollame','Pollo',4,' -','1 Pollo,
250 G Tonno Sott''olio,
Maionese,
2 Acciughe Sotto Sale,
1 Cucchiaio Capperi,
1 Bicchiere Vino Bianco Secco,
1 Foglia Alloro,
1 Spicchio Aglio,
Carota,
1 Costa Sedano,
Cipolla,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','In una casseruola scaldate tre cucchiai d''olio e rosolatevi delicatamente il pollo. Spruzzatelo con un bicchiere di vino bianco e lasciatelo evaporare. Dopo alcuni minuti salate, pepate, aggiungete una foglia d''alloro e uno spicchio d''aglio interi, cipolla, carota e sedano ben tritati. Coprite il recipiente e cuocete in forno preriscaldato a 180 gradi per circa un''ora. Nel frattempo preparate la maionese. Frullate il tonno e le acciughe lavate e diliscate. Incorporate il frullato alla maionese, aggiungete un cucchiaio di capperi, mescolate con cura. Ritirate il recipiente dal forno, togliete il pollo, filtrate al passino il fondo di cottura e unitelo alla maionese. Tagliate il pollo freddo a pezzi, disponeteli sul piatto da portata, copriteli di maionese. Tenete in frigo 2 ore. Vini di accompagnamento: Il piatto richiede i vini bianchi come Collio Tocai DOC, Marino DOC.',4005);
INSERT INTO "ricette" VALUES (19193,'Pollo Al Vapore','Pollame','Pollo',4,' -','2 Petti Di Pollo Interi,
6 Zucchine Piccole,
Abbondante Prezzemolo,
5 Cucchiai Olio D''oliva,
Sale','Dividere a metà i petti di pollo e disossarli. Metterli nel cestello per la cottura a vapore e cuocere per 20 minuti a pentola coperta. Dopo 10 minuti unire le zucchine lavate e tagliate a pezzetti. Lavare abbondante prezzemolo, asciugarlo e tritarlo. Metterlo in una ciotola con 5 cucchiai di olio e farlo riposare. Quando pollo e zucchine saranno cotti metterli in un piatto da portata, cospargerli con l''olio e prezzemolo, salarli e servirli.',1285);
INSERT INTO "ricette" VALUES (19194,'Pollo Al Verde','Pollame','Pollo',4,' -','1 Petto Di Pollo Intero,
500 G Spinaci Lessati,
Aglio,
Burro,
50 G Formaggio Parmigiano Grattugiato,
1 Uovo,
Pangrattato','Dividere in 4 il petto di pollo e tagliarlo lateralmente. Passare gli spinaci nel burro, con l''aglio schiacciato. Farli insaporire bene, cospargerli di parmigiano e usarli per farcire i petti di pollo. Cucire i bordi con filo da cucina. Passare i petti farciti nell''uovo battuto e nel pangrattato e friggerli in abbondante burro spumeggiante.',1899);
INSERT INTO "ricette" VALUES (19195,'Pollo Al Vino','Pollame','Pollo',4,' -','1 Pollo Da 1200 G,
200 G Pancetta,
200 G Cipolline,
100 G Funghi Champignon,
1 Spicchio Aglio,
1 Cucchiaio Fecola,
75 Cl Vino Rosso,
Olio D''oliva,
25 G Burro,
Sale,
Pepe','Tagliare a pezzi il pollo e farlo rosolare in poco olio. In una altro tegame rosolare nel burro le cipolline, la pancetta a dadini, i funghi a pezzi. Unire il pollo, l''aglio e il vino. Salare e pepare. Coprire il tegame, abbassare il fuoco al minimo e cuocere per 45 minuti. A cottura ultimata unire al sugo del pollo 25 g di burro mescolato alla fecola, far cuocere altri 10 minuti poi servire.',3816);
INSERT INTO "ricette" VALUES (19196,'Pollo Al Vino Bianco','Pollame','Pollo',4,' -','1 Pollo,
1 Bottiglia Vino Bianco Secco,
1 Spicchio Aglio,
Rosmarino,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','In una teglia scaldate due cucchiai d''olio con l''aglio e il rosmarino, rosolatevi il pollo, a pezzi non troppo grandi. Salate e pepate. Versate il vino bianco fin quasi a coprire il pollo. Chiudete il recipiente con un foglio di carta d''alluminio doppio. Passate in forno preriscaldato a 180 gradi. Dopo mezz''ora scoprite e continuate a cuocere fino a quando il vino è consumato. Vini di accompagnamento: Terre Di Franciacorta Bianco DOC, Verdicchio Di Matelica DOC, Bianco D''Alcamo DOC.',2807);
INSERT INTO "ricette" VALUES (19197,'Pollo Al Vino Rosso','Pollame','Pollo',4,' -','1 Pollo,
100 G Funghi Coltivati,
100 G Cipolline,
100 G Pancetta (fette Da 100 G),
50 G Burro,
1 Cucchiaio Farina,
50 Cl Vino Rosso,
1 Spicchio Aglio,
1 Rametto Timo,
Sale','In un tegame fate dorare leggermente il burro, quindi aggiungete la pancetta tagliata a cubetti, le cipolline, uno spicchio d''aglio intero, i funghi e un rametto di timo. Rosolate per alcuni minuti, poi spolverizzate con un cucchiaio di farina. Eliminate l''aglio. Aggiungete il pollo tagliato a pezzi. Coprite e cuocete 10 minuti. Versate il vino. Salate. Coprite di nuovo e portate a cottura a fuoco basso per circa 30 minuti. Vini di accompagnamento: Servite a tavola lo stesso vino usato per la cottura: Trentino Cabernet DOC, Rosso Di Montalcino DOC, Montepulciano D''Abruzzo DOC.',2978);
INSERT INTO "ricette" VALUES (19198,'Pollo All''aglio','Pollame','Pollo',4,' -','1 Pollo,
30 G Burro,
1 Testa Aglio,
1/2 Bicchiere Vino Bianco Secco,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate il pollo a pezzi e rosolateli in un tegame con il burro e due cucchiai d''olio per circa un quarto d''ora girandoli in continuazione. Poi aggiungete gli spicchi d''aglio interi e quando la loro buccia è diventata dorata salate e pepate abbondantemente. Versate il vino, lasciatelo evaporare poi coprite il tegame e cuocete a fuoco basso per mezz''ora. Scoprite il recipiente, alzate la fiamma, fate addensare un po'' il sugo, eliminate gli spicchi d''aglio. Sistematelo sul piatto da portata. Vini di accompagnamento: Oltrepò Pavese Rosso DOC, Colli Di Luni Rosso DOC, Biferno Rosso DOC.',2349);
INSERT INTO "ricette" VALUES (19199,'Pollo All''aglio (2)','Pollame','Pollo',4,' -','1 Pollo Da 1000 G,
30 Spicchi Aglio,
1 Rametto Rosmarino,
1 Bicchiere Olio D''oliva,
Sale,
Pepe','Eviscerare il pollo, lavarlo, asciugarlo e fiammeggiarlo. Legarlo con del filo da cucina. Pulire gli spicchi d''aglio ma non pelarli e distribuirne una parte sul fondo di una casseruola. Deporre il pollo sullo strato d''aglio, bagnarlo con 1 bicchiere di olio, salarlo e peparlo. Mettere il resto dell''aglio attorno e sopra il pollo. Chiudere ermeticamente la casseruola e cuocere in forno caldo a 200 gradi per circa 90 minuti. Il pollo può essere servito sia con l''aglio cotto sia senza, a piacere.',2667);
INSERT INTO "ricette" VALUES (19200,'Pollo All''agro','Pollame','Pollo',4,' -','8 Cosce Di Pollo,
1 Spicchio Aglio,
1 Cipolla,
Rosmarino,
3 Cucchiai Olio D''oliva,
2 Cucchiai Aceto Di Vino,
Burro,
Sale,
Pepe','Incidere le cosce di pollo, infilare in ognuna una fettina di aglio sbucciato e qualche ago di rosmarino tritato, salare e pepare. Far soffriggere la cipolla tritata con l''olio e il burro, unire le cosce di pollo, spruzzare con l''aceto, farlo evaporare, coprire, far cuocere per 30 minuti circa e servire.',3956);
INSERT INTO "ricette" VALUES (19201,'Pollo All''aragonese','Pollame','Pollo',6,' -','1 Pollo Di Circa 1500 G,
250 G Prosciutto Cotto (fette Di 250 G),
Sale,
2 Cucchiai Farina,
1 Cucchiaio Paprica Dolce,
5 Cucchiai Olio D''oliva,
2 Spicchi Aglio Tritato,
4 Cucchiai Vino Bianco Dolce,
2 Cipolle Piccole,
400 G Peperoni Rossi Tagliati A Dadini,
200 G Pomodori Tagliati A Dadini,
50 G Brunoise Di Sedano','Pulite il pollo, dividetelo in otto o dodici pezzi di dimensioni il più possibile uniformi e cospargeteli con il sale e con la paprica mescolata alla farina. Tagliate la fetta di prosciutto a cubetti di 1 cm di lato. Ponete i pezzi di pollo infarinati e aromatizzati in un tegame che li contenga agevolmente, insieme all''olio d''oliva, e fateli rosolare bene da ogni lato. Unite i dadini di prosciutto, date una mescolata e fate rosolare anch''essi a calore medio. Aggiungete l''aglio tritato e il vino, girate i pezzi di pollo e fateli cuocere per 20 minuti, dopodichè toglieteli dal tegame. Mettete nel fondo di cottura del pollo le cipolle tagliate a spicchi, il sedano, i peperoni e i pomodori e fate rosolare mescolando senza interruzione, infine salate. Trasferite le verdure in una pirofila, adagiatevi sopra i pezzi di pollo e il prosciutto e fate gratinare in forno a 200 gradi per 10 minuti. --- CONSIGLI. Come suggerisce il titolo, si tratta di un piatto originario dell''Aragona, che però è assai diffuso in tutta la Spagna, dove viene preparato in numerose varianti. Quale che sia la ricetta, gli ingredienti di base sono sempre gli stessi, ossia il pollo, i peperoni, il prosciutto e i pomodori.',3617);
INSERT INTO "ricette" VALUES (19202,'Pollo All''arancia','Pollame','Pollo',4,' -','4 Cosce Di Pollo Intere,
100 G Pancetta Affumicata,
1 Cipolla,
2 Carote,
1 Arancia,
2 Cucchiai Brandy,
25 Cl Vino Bianco Secco,
Timo,
Alloro,
Maggiorana,
2 Chiodi Di Garofano,
Olio D''oliva,
Sale,
Pepe','Rosolare la pancetta a dadini in poco olio. Porre le cosce in pentola di coccio, unire la pancetta, il brandy, il vino, la cipolla tritata, le carote affettate, il mazzetto di odori, i chiodi di garofano pestati, il succo e la scorza di arancia grattugiata, sale e pepe e far marinare per 2 ore. Unire il brodo, chiudere e cuocere in forno a 170 gradi per 1 ora e mezzo.',3029);
INSERT INTO "ricette" VALUES (19203,'Pollo All''arancia (2)','Pollame','Pollo',4,' -','500 G Petti Di Pollo Interi,
100 G Pancetta,
3 Arance,
1 Bicchierino Gin,
1 Mestolo Brodo,
1/2 Cucchiaio Maggiorana Secca,
50 G Burro,
30 G Farina,
Sale','Mondare il pollo, tagliarlo a striscioline ed infarinarlo. Tagliare a dadini la pancetta. Scaldare il burro in 1 larga padella e farvi dorare il pollo e la pancetta, rigirandoli spesso, poi bagnare col gin e col succo di un''arancia, unire 1/2 mestolo di brodo e cuocere per 10 minuti, mescolando spesso. Intanto sbucciare le arance rimaste, tagliarle a fette spesse e unirle al pollo, aggiungere la maggiorana e cuocere altri 2 minuti.',1813);
INSERT INTO "ricette" VALUES (19204,'Pollo All''indiana','Pollame','Pollo',4,'Luogo: India.','1 Pollo Da 1500 G Tagliato A Pezzi,
5 Cucchiai Farina Bianca,
3 Cucchiai Olio Di Semi,
2 Spicchi Aglio Sbucciato,
2 Cipolle Sbucciate Affettate Finemente,
1 Peperone Verde Senza Semi Tritato,
50 G Sedano Lavato E Tritato,
1 Cucchiaino Curry In Polvere,
2 Cucchiai Sale,
800 G Pomodori Pelati,
Per Servire:,
1 Noce Burro,
50 G Mandorle Sbianchite,
225 G Riso A Grani Lunghi Bollito,
75 G Uvetta Sultanina Senza Semi,
Prezzemolo Tritato','Passate il pollo nella farina. Scaldate l''olio in un largo tegame e indorate i pezzi di pollo da ogni lato, pochi per volta. Toglieteli dalla padella e metteteli da parte. Mettete in tegame aglio, cipolla, peperone, sedano, curry e sale; cuocete per 5 minuti mescolando. Unite quindi i pomodori col loro sugo. Aggiungete i pezzi di pollo e portare a bollore. Abbassate la fiamma, coprite e sobbollite per 30 minuti finché la carne sia tenera. Intanto sciogliete il burro in una padella e saltate le mandorle dorandole appena. Mescolatevi insieme riso ed uvetta. Sistemare la mistura di riso ed i pezzi di pollo su un piatto da portata largo, riscaldato. Eliminate gli spicchi d''aglio e versate la salsa sopra il pollo. Spargete uniformemente su pollo e riso le mandorle saltate e il prezzemolo tritato.',4463);
INSERT INTO "ricette" VALUES (19205,'Pollo Alla Babi','Pollame','Pollo',4,'Luogo: Piemonte.','1 Pollo,
1/2 Bicchiere Olio D''oliva,
1 Spicchio Aglio,
1 Rametto Rosmarino,
Sale,
Pepe','Babi, in piemontese, vuol dire rospo. Per dare al pollo questo aspetto apritelo dalla parte del petto e schiacciatelo più volte con il batticarne. Quindi soffregate esternamente il volatile con sale e pepe. In una padella, preferibilmente di ferro, scaldate l''olio e fatevi dorare il pollo da ambo le parti a fuoco vivace. Dopo un quarto d''ora aggiungete lo spicchio d''aglio schiacciato e il rametto di rosmarino avendo cura di ridurre la fiamma, altrimenti perdono entrambi l''aroma e acquistano un sapore amaro. Dopo circa mezz''ora sgocciolate bene il pollo dal grasso di cottura e servitelo asciutto e caldo. Vini di accompagnamento: Barbera Del Monferrato DOC, Chianti Classico DOCG, Cirò Rosso Classico DOC.',2367);
INSERT INTO "ricette" VALUES (19206,'Pollo Alla Barbabietola','Pollame','Pollo',4,' -','500 G Petto Di Pollo,
4 Barbabietole,
2 Bacche Anice,
1 Bastoncino Cannella,
2 Bacche Cardamomo,
Alcune Gocce Aceto Balsamico,
Olio D''oliva Extra-vergine,
Sale','Mondate e tagliate a spicchi le barbabietole, posatele in una teglia con le bacche di anice, la cannella, le bacche di cardamomo schiacciate, 5 cucchiai di olio d''oliva extra-vergine e un po'' di sale. Dopo aver mescolato il tutto infornate a 200 gradi per circa 1/2 ora. Tagliate a fette il petto di pollo e fatele dorare per pochi minuti in una padella con olio e sale; quindi adagiate le fette nella teglia con le barbabietole e lasciatelo cuocere ancora per 10/15 minuti. Servite il piatto caldo, con qualche goccia di aceto balsamico.',1445);
INSERT INTO "ricette" VALUES (19207,'Pollo Alla Birra','Pollame','Pollo',4,' -','1 Pollo,
75 Cl Birra Chiara,
1 Cipolla,
Olio D''oliva,
1 Pugnetto Uvetta Sultanina,
2 Foglie Alloro,
Sale','Soffriggere lentamente nell''olio la cipolla affettata. Unire il pollo tagliato a pezzi e, quando questi saranno dorati, versare la birra; cuocere a fuoco basso, finché non sarà quasi del tutto evaporata. Salare, aggiungere le foglie di alloro e l''uva passa ammorbidita in acqua calda. Coprire e continuare la cottura per una mezz''ora.',2852);
INSERT INTO "ricette" VALUES (19208,'Pollo Alla Birra (2)','Pollame','Pollo',4,' -','1 Pollo,
100 Cl Birra,
1 Cipolla,
1 Porro,
1 Costa Sedano,
1 Carota,
Sale,
Pepe','Salate e pepate il pollo internamente, mettetelo in un tegame dove stia di misura. Aggiungete carota, cipolla, porro e sedano finemente tritati. Versate la birra che deve coprirlo quasi completamente. Portate a ebollizione e lasciate cuocere circa un''ora, ma dopo mezz''ora girate con delicatezza il volatile. A fine cottura la birra deve essere quasi consumata, il pollo dorato e vellutato. Servitelo con patatine lessate al prezzemolo. Vini di accompagnamento: Birre doppio malto, chiare o scure.',2228);
INSERT INTO "ricette" VALUES (19209,'Pollo Alla Birra (3)','Pollame','Pollo',6,'Luogo: Olanda. Luogo: Belgio. Luogo: Fiandre.','2000 G Pollo In Pezzi,
Sale,
Pepe,
1 Pizzico Zucchero,
1 Cucchiaio Olio Di Semi Vari (o Olio D''oliva),
15 G Burro,
8 Bulbi Di Scalogno,
15 Funghi Champignon,
4 Carote,
3 Spicchi Aglio Finemente Tritato,
2 Cucchiai Farina 00,
1 Bottiglia Birra (33 Cl),
25 Cl Brodo Di Carne,
1 Cucchiaio Timo Disidratato,
2 Foglie Alloro,
Prezzemolo Fresco Tritato','Consiglierei l''impiego di una birra chiara ma piuttosto corposa; preferibilmente sceglierei una birra olandese o belga a gradazione alcolica ''normale'' (5%) e non aromatizzata. Condire i pezzi di pollo con sale e pepe. Far sciogliere il burro ed insieme scaldare l''olio un una padella sufficientemente grande e dotata di coperchio. Far rosolare il pollo a fuoco medio da tutti i lati. Una volta leggermente imbrunita la carne, spostarla tutta su un lato della padella e, nella stessa, mettere lo scalogno (o cipolle) finemente tritato ed i funghi tagliati a fettine o in quarti; far saltare per circa 5 minuti finché leggermente imbrunite (attenzione a non far bruciare la cipolla: renderebbe amara la carne) ed aggiungere l''aglio finemente tritato ed un pizzico di zucchero. Cuocere per circa 1 minuto rimestando continuamente. Attenzione: controllare che, durante questa fase di cottura delle verdure, la carne non bruci: a tal fine continuare a girarla quando possibile. Aggiungere le carote e cospargere la farina sulle verdure. Rimestare fino a far amalgamare bene la farina cercando di non far formare grumi. Aggiungere quindi il brodo in modo da sciogliere gli eventuali grumi (eventualmente raschiare leggermente il fondo della padella). Rimestare i pezzi di pollo nel composto di verdure saltate ed aggiungervi il timo e le foglie di alloro. Versare a questo punto la birra e far cuocere il tutto coperto a fuoco medio per 30-40 minuti, finché il pollo è quasi cotto ed ancora tenero; ogni tanto rimestare. Rimuovere quindi il coperchio e far cuocere per altri 10 minuti scoperto, in modo da ridurre la salsa di circa un terzo. Servire cosparso di prezzemolo tritato.',3290);
INSERT INTO "ricette" VALUES (19210,'Pollo Alla Birra (4)','Pollame','Pollo',4,' -','1 Pollo Da 1000 G,
Birra Chiara,
Sale','Preparare il pollo svuotato, passato alla fiamma, lavato e asciugato. Salarlo all''interno e metterlo in una casseruola. Coprirlo di birra. Oprire la casseruola e cuocere a fuoco medio. Quando la birra sarà evaporata e il pollo tenero, far intiepidire e servire.',1168);
INSERT INTO "ricette" VALUES (19211,'Pollo Alla Birra (5)','Pollame','Pollo',4,' -','1 Pollo Da 1500 G,
33 Cl Birra Chiara,
1 Cipolla,
1 Carota,
1 Gambo Sedano,
2 Cucchiaini Paprica Dolce,
Cannella In Polvere,
Burro,
Farina,
Sale','Dopo aver pulito, lavato e fiammeggiato il pollo, tagliarlo in 8 pezzi ed infarinarlo leggermente. Tagliare a fettine le verdure e farle rosolare nel burro già caldo; unire i pezzi di pollo e lasciar rosolare a lungo, prima di aggiungere la birra. Salare, coprire il tegame e far cuocere per 10 minuti. Unire la paprica e la cannella disciolte in poca acqua tiepida e proseguire la cottura a tegame scoperto.',3014);
INSERT INTO "ricette" VALUES (19212,'Pollo Alla Birra Con Cipollotto Fondente E Frittelle Di Mele','Pollame','Pollo',4,' -','2 Cosce Di Pollo,
1 Mela,
2 Cipollotti,
100 G Formaggio Groviera,
1 Uovo,
3 Cucchiai Farina,
3 Cucchiai Latte,
Olio D''oliva Extra-vergine,
Birra,
Sale,
Pepe','Rosolare le cosce disossate con i 2 cipollotti, sale, pepe, sfumare con la birra e infornare per 20 minuti. Pulire le mele, togliere il torsolo con il cavatorsolo, tagliare a rondelle, e passare le mele nella pastella fatta con uovo, latte, farina. Friggere in olio ben caldo. Terminare la cottura del pollo gratinandolo con una julienne di groviera.',2572);
INSERT INTO "ricette" VALUES (19213,'Pollo Alla Brace','Pollame','Pollo',4,' -','1 Pollo Ruspante,
Olio D''oliva Extra-vergine,
1 Limone (succo),
2 Rametti Rosmarino,
Sale Marino Integrale,
Pepe','Pulire il pollo; aprirlo a libro. Farlo marinare in una marinata con succo di limone, olio, sale, pepe, aghi di rosmarino per 1 ora circa, quindi metterlo sulla griglia a 30 cm dalla brace. Cuocerlo per 30 minuti e poi per altri 15 minuti a distanza più ravvicinata rigirandolo spesso e ungendolo con un rametto di rosmarino intinto nella marinata.',2063);
INSERT INTO "ricette" VALUES (19214,'Pollo Alla Cacciatora','Pollame','Pollo',4,' -','1 Pollo In 8 Parti,
100 G Margarina,
Pomodori Perini A Fette,
Sale,
Pepe,
Cipolline Tagliate A Fette,
Carote A Cubetti,
Peperoni,
2 Spicchi Aglio,
Alcuni Grani Ginepro','Tagliate il pollo in otto parti e fatelo rosolare con 100 g di margarina. Aggiungete dei pomodori perini tagliati a fette. Salate, pepate e mescolate. Lasciate insaporire un poco a tegame coperto. Aggiungete quindi cipolline tagliate a fette, carote a cubetti e falde di peperoni. Mescolate ancora e coprite aggiungendo, per ultimo, due spicchi di aglio e qualche grano di ginepro. Il pollo deve essere quasi del tutto cotto quando leverete il coperchio e alzerete la fiamma per asciugare la salsa e renderla abbastanza densa.',2623);
INSERT INTO "ricette" VALUES (19215,'Pollo Alla Cacciatora (10)','Pollame','Pollo',4,'Luogo: Friuli.','1 Pollo Di 2000 G,
30 G Burro,
1/2 Cipolla Tritata,
6 Pomodori Pelati,
Olio D''oliva,
1 Goccio Grappa,
3 Peperoni Dolci,
Sale,
Pepe,
Maggiorana','Pulire e tagliare a pezzi il pollo; metterlo in un tegame a rosolare con burro, olio e cipolla. Unire i pomodori, salare, pepare, aggiungere la grappa e continuare la cottura. Unire anche la maggiorana e poca acqua se occorre; coprire e cuocere per 20 minuti circa. Ora unire i peperoni tagliati a pezzetti e terminare la cottura.',3297);
INSERT INTO "ricette" VALUES (19216,'Pollo Alla Cacciatora (2)','Pollame','Pollo',4,' -','1 Pollo,
30 G Burro,
6 Pomodori Maturi,
1 Cipolla,
1 Costa Sedano,
1 Carota,
1 Ciuffo Prezzemolo,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Tagliate il pollo a pezzi piuttosto piccoli e regolari, lavateli, asciugateli, metteteli in una casseruola con il burro, tre cucchiai d''olio e la cipolla affettata. Fateli rosolare bene per circa 15 minuti. Aggiungete i pomodori spellati, senza semi e spezzettati, la carota e il sedano tritati. Bagnate con un mestolino d''acqua, coprite e cuocete ancora per 45 minuti. All''ultimo momento unite le foglioline di prezzemolo, salate e pepate. Questo è il modo più semplice di preparare il pollo alla cacciatora: in alcune regioni vi mettono più sedano e più carote, in altre si bagna con vino bianco invece che con acqua o brodo, in altre si aggiungono funghi freschi tagliati a fettine. Vini di accompagnamento: Grave Del Friuli Refosco DOC, Chianti DOCG, Gioia Del Colle Rosso DOC.',3150);
INSERT INTO "ricette" VALUES (19217,'Pollo Alla Cacciatora (3)','Pollame','Pollo',4,'Preparazione: 60 minuti. Cottura: 20 minuti.','Pepe,
Sale,
40 G Burro,
3 Cucchiai Olio D''oliva,
1 Cucchiaio Farina,
20 Cl Vino Rosso,
4 Cucchiai Prezzemolo,
1 Spicchio Aglio,
1 Scalogno,
1 Cipolla,
300 G Funghi Champignon,
6 Pomodori,
1 Pollo Da 1400 G','Il pollo deve essere già tagliato in 4 pezzi e il prezzemolo tritato. Salate e pepate abbondantemente i pezzi di pollo. Immergete brevemente i pomodori in acqua bollente, raffreddateli sotto l''acqua fredda corrente e pelateli. Tagliateli in quattro ed eliminate i semi e l''acqua di vegetazione. Mondate la cipolla, lo scalogno e l''aglio e tritateli finemente. Scaldate l''olio in una grande casseruola, aggiungetevi il burro e fatevi rosolare i pezzi di pollo per tre minuti a fuoco vivace. Toglieteli con una schiumarola. Rosolate per dieci minuti la cipolla, lo scalogno e l''aglio nella casseruola, a fuoco moderato e mescolando regolarmente con un cucchiaio di legno. Dopo dieci minuti, aggiungete la farina e mescolate per un minuto a fuoco molto moderato. Bagnate con il vino mescolando rapidamente. Lasciate bollire per due minuti, aggiungete i pomodori, il prezzemolo, sale e pepe. Rimettete i pezzi di pollo nella casseruola, coprite e lasciate sobbollire per trenta minuti, mescolando di tanto in tanto. Nel frattempo, mondate gli champignon, lavateli, asciugateli e affettateli. Dopo trenta minuti di cottura, aggiungete al pollo i funghi, mescolate e lasciate cuocere per altri quindici minuti, a fuoco moderato e a coperto. Quando il pollo è cotto, disponete i pezzi su un piatto di servizio caldo; assaggiate la salsa e, se necessario, salatela e pepatela. Versatela sul pollo e servite immediatamente. Vino consigliato: Sizzano.',3378);
INSERT INTO "ricette" VALUES (19218,'Pollo Alla Cacciatora (4)','Pollame','Pollo',6,' -','1 Pollo,
15 G Funghi Secchi,
1 Cucchiaio Conserva Di Pomodoro,
Aglio,
Cipolla,
1 Bicchiere Vino Bianco,
Brodo,
Olio D''oliva Extra-vergine,
Sale','Tagliate il pollo in piccoli pezzi e fatelo rosolare in una casseruola con l''aglio, l''olio d''oliva extra-vergine e la cipolla. Bagnate con il vino e lasciate evaporare. Continuate la cottura unendo i funghi, che avrete messo in ammollo e il concentrato di pomodoro sciolto nel brodo. Fate cuocere per mezz''ora a fuoco lento.',2603);
INSERT INTO "ricette" VALUES (19219,'Pollo Alla Cacciatora (5)','Pollame','Pollo',4,' -','1 Pollo A Pezzi,
500 G Pomodori Pelati,
25 Cl Vino Bianco,
3 Spicchi Aglio,
1 Misurino Olio D''oliva,
Sale,
Pepe','Tritare l''aglio e farlo dorare in una teglia con l''olio. Adagiare i pezzi di pollo e farli rosolare aggiungendo il vino bianco. Quando il vino sarà evaporato unire i pomodori, il sale, il pepe e far cuocere a fuoco lento per circa 30 minuti.',2368);
INSERT INTO "ricette" VALUES (19220,'Pollo Alla Cacciatora (6)','Pollame','Pollo',4,' -','1 Pollo Di 1000 G,
60 G Burro,
1 Trito Di Cipolla, Prezzemolo, Aglio E Alloro,
300 G Polpa Di Pomodoro Tritata,
Sale,
Pepe','Condire il pollo a pezzi con sale e pepe. Soffriggere il burro e unire i pezzi di pollo, appena rosolati sgocciolarli e metterli da parte. Unire al fondo di cottura il trito di odori e mescolare. Unire la polpa di pomodoro, salare e pepare. Aggiungere il pollo, cuocere ancora 35 minuti a fuoco moderato e servire.',1663);
INSERT INTO "ricette" VALUES (19221,'Pollo Alla Cacciatora (7)','Pollame','Pollo',4,'Luogo: Lazio.','1 Pollo,
Olio D''oliva,
Burro,
Alcuni Pomodori Freschi,
60 G Funghi Secchi,
Sale,
Pepe,
1 Foglia Alloro (facoltativo)','Tagliate a pezzi un bel pollo tenero e fatelo rosolare in metà olio e metà burro, poi aggiungetevi i pomodori freschi e i funghi secchi già rinvenuti in acqua tiepida, scolati strizzati e tagliati a pezzi. Mescolate e lasciate cuocere tutto piano e a casseruola scoperta, dopo aver condito con sale, pepe e avere aggiunto anche, se vi piace, una foglietta di alloro.',3293);
INSERT INTO "ricette" VALUES (19222,'Pollo Alla Cacciatora (8)','Pollame','Pollo',4,'Luogo: Lazio.','1 Pollo,
Olio D''oliva,
Burro,
1 Scatola Pomodori Pelati,
60 G Funghi Secchi,
Sale,
Pepe,
1 Foglia Alloro (facoltativo)','Tagliate a pezzi un bel pollo tenero e fatelo rosolare in metà olio e metà burro, poi aggiungetevi i pomodori pelati e i funghi secchi già rinvenuti in acqua tiepida, scolati strizzati e tagliati a pezzi. Mescolate e lasciate cuocere tutto piano e a casseruola scoperta, dopo aver condito con sale, pepe e avere aggiunto anche, se vi piace, una foglietta di alloro.',3269);
INSERT INTO "ricette" VALUES (19223,'Pollo Alla Cacciatora (9)','Pollame','Pollo',1,' -','155 G Pollo,
45 G Pomodori Pelati,
Olio D''oliva Extra-vergine,
Cipolle,
Alcuni Cucchiai Brodo Vegetale,
Poco Vino Bianco','Lasciare cuocere la cipolla in poco brodo vegetale. Unire il pollo e farlo colorire leggermente, quindi spruzzare il tutto con poco vino bianco e lasciare che evapori. Aggiungere i pomodori pelati e cuocere per circa 30 minuti. Servire la pietanza ben calda.',1018);
INSERT INTO "ricette" VALUES (19224,'Pollo Alla Ciociara','Pollame','Pollo',4,'Luogo: Lazio. Luogo: Ciociaria.','1 Pollo Di 1000 G,
300 G Pomodoro,
3 Peperoni Dolci A Polpa Grossa,
1 Peperoncino,
2 Spicchi Aglio,
1/2 Bicchiere Vino Bianco,
Olio D''oliva,
Sale','Pulire il pollo, fiammeggiarlo e tagliarlo a tocchetti. In un tegame imbiondire nell''olio gli spicchi d''aglio. Aggiungere i tocchetti di pollo e far rosolare spruzzando con vino bianco. Appena il vino sarà evaporato aggiungere il peperoncino, i pomodori e i peperoni mandati e tagliati a falde. Salare, coprire il tegame e cuocere per circa 45 minuti.',2006);
INSERT INTO "ricette" VALUES (19225,'Pollo Alla Contadina','Pollame','Pollo',4,'Luogo: Lazio. Luogo: Ciociaria. Luogo: Roccasecca.','1 Pollo Ruspante,
4 Patate,
1 Cipolla,
50 G Burro,
1 Fetta Lardo,
1 Ciuffo Prezzemolo,
1 Bicchiere Vino Bianco,
Sale','Tagliate il pollo a pezzi e mettetelo a rosolare in un tegame con il burro ed il lardo, cospargendo il tutto con il prezzemolo tritato. Coprite successivamente con le patate tagliate a fette non troppo erte, la cipolla a fettine, il sale ed il vino. Coprite il tegame e tenetelo in forno fino a cottura ultimata (da un''ora a un''ora e mezza). Servire ben caldo. In versioni simili di questo piatto, vengono aggiunti peperoni, zucchine ed altre verdure.',2765);
INSERT INTO "ricette" VALUES (19226,'Pollo Alla Crema','Pollame','Pollo',4,' -','1 Pollo,
1 Cipolla,
1 Costa Sedano,
1/2 Dado,
50 Cl Latte,
2 Cucchiai Farina,
30 G Margarina,
Olio D''oliva,
Prezzemolo Tritato','Soffriggere nell''olio cipolla e sedano tritati, aggiungere il pollo a pezzetti e dopo qualche minuto un po'' d''acqua e il dado sbriciolato. Cuocere lentamente e quando il sugo comincia ad addensarsi cospargere con la farina e versare poco alla volta il latte caldo. A fine cottura unire margarina e prezzemolo.',3018);
INSERT INTO "ricette" VALUES (19227,'Pollo Alla Crema (2)','Pollame','Pollo',4,' -','1 Pollo,
1 Bicchiere Cognac,
1 Bicchiere Panna,
Crostoni Al Burro,
Brodo','Preparate il pollo tagliato a pezzi e fatelo colorire nel burro, poi versate nella casseruola il cognac e poi brodo quanto occorre per portarlo a cottura. Alla fine, vi unirete anche la panna e lascerete cuocere ancora qualche minuto. Servite con crostoni fritti al burro.',2706);
INSERT INTO "ricette" VALUES (19228,'Pollo Alla Crema (3)','Pollame','Pollo',4,' -','4 Fusi Di Pollo,
2 Cipollotti,
1 Limone,
125 G Yogurth Bianco,
300 G Patatine Novelle,
2 Cucchiai Olio D''oliva,
Abbondante Prezzemolo Tritato,
Sale','Tritare finemente i cipollotti e porli in una padella antiaderente assieme ai fusi di pollo e 2 cucchiai di olio. Lasciar cuocere a fuoco medio per circa 20 minuti mescolando ogni tanto. Lessare le patatine in acqua salata e scolarle. Quando il pollo è quasi cotto unire il succo di limone, salare e cuocere altri 10 minuti. Aggiungere le patatine e abbondante prezzemolo tritato, abbassare la fiamma, unire lo yogurth e lasciar amalgamare gli ingredienti.',2739);
INSERT INTO "ricette" VALUES (19229,'Pollo Alla Crema Di Limone','Pollame','Pollo',4,' -','500 G Petto Di Pollo,
125 G Formaggio Philadelphia,
2 Limoni,
3/4 Cucchiai Latte,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe','Tagliate il petto di pollo a tocchetti e fatelo leggermente rosolare in un tegame con 3 cucchiai di olio. Bagnatelo con il succo dei limoni, salate, pepate e cuocete a fuoco moderato per circa 15 minuti, unendo se necessario un po'' di acqua calda. Trascorso questo tempo estraete i tocchetti di pollo dal tegame e versatevi il Philadelphia, che avrete prima stemperato con il latte. Regolate di sale e pepe, unite il prezzemolo e lasciate cuocere la crema per qualche minuto. Rimettete il pollo nel tegame, mescolate bene e servite.',1678);
INSERT INTO "ricette" VALUES (19230,'Pollo Alla Creola','Pollame','Pollo',4,' -','1 Pollo Da 1000 G Tagliato A Pezzi,
1 Limone (succo),
1 Chiodo Di Garofano In Polvere,
Origano,
Pepe,
2 Cucchiai Paprica Dolce,
Farina,
2 Foglie Alloro,
1 Spicchio Aglio,
1 Bicchierino Rum,
Olio D''oliva,
Sale','In una terrina mettere il pollo e cospargerlo con olio, succo di limone, origano, chiodo di garofano, paprica, aglio, pepe, alloro, rum, sale e marinarlo per almeno 5 ore. Scolarlo, passarlo nella farina e friggerlo in olio caldo, rigirandolo. Quando sarà ben dorato versarvi la marinata passata col colino e portare a cottura. Servire i pezzi di pollo cosparsi con il fondo di cottura.',2317);
INSERT INTO "ricette" VALUES (19231,'Pollo Alla Dany Con Birra','Pollame','Pollo',4,' -','1 Pollo Di 1000 G,
1 Rametto Rosmarino,
100 Cl Birra,
Sale','Pulire accuratamente il pollo e salario. Prendere una casseruola di cui il pollo non occupi più di 2/3 della sua capacità; porvi a freddo il pollo, ricoprire completamente con la birra, aggiungervi il rametto di rosmarino; sistemare il tutto su una fiamma molto viva. Dopo circa mezz''ora la birra, che sarà quasi completamente evaporata, formerà un condensato sul fondo della casseruola, nel quale rigirare più volte il pollo per dargli la dovuta colorazione. Servire molto caldo.',1596);
INSERT INTO "ricette" VALUES (19232,'Pollo Alla Diavola','Pollame','Pollo',2,' -','1 Pollo (galletto),
Senape,
Pepe,
Sale,
Pangrattato,
2 Cucchiai Olio D''oliva','Dividete il pollo (galletto) in due e schiacciatelo, spalmatelo con senape, pepe e sale e impanatelo nel pangrattato. Posate la grande padella su un fuoco medio con 2 cucchiai di olio. Mettete il pollo nella padella e fatelo rosolare per 5 minuti, quindi coprite e lasciatelo arrostire lentamente, per 20 minuti. Servite con delle patate, insalata, salsa alla diavola.',2496);
INSERT INTO "ricette" VALUES (19233,'Pollo Alla Diavola (2)','Pollame','Pollo',4,' -','1 Pollo Di 1000 G Circa,
30 G Olio D''oliva,
20 G Burro,
Sale,
1 Limone','Battere il pollo con il batticarne per appiattirlo. Farlo rosolare in una pentola con burro e olio su fuoco vivo. Salare, abbassare la fiamma e coprire con un foglio di carta di alluminio e con un coperchio su cui si appoggerà un peso. Di tanto in tanto sorvegliare che non bruci. Prima di spegnere il fuoco spruzzare con il succo di limone. Servire caldissimo.',1558);
INSERT INTO "ricette" VALUES (19234,'Pollo Alla Diavola (3)','Pollame','Pollo',4,' -','1 Pollo Da 1000 G,
Olio D''oliva,
Pepe,
Sale','Pulire il pollo, fiammeggiarlo, lavarlo e aprirlo sul dorso. Appiattirlo con il batticarne per farlo rimanere ben aperto. Ungerlo, salarlo e peparlo e metterlo sulla griglia rovente. Farlo dorare da ambo le parti e abbassare la fiamma. Proseguire la cottura rigirandolo spesso affinché sia cotto in modo uniforme.',1822);
INSERT INTO "ricette" VALUES (19235,'Pollo Alla Diavola (4)','Pollame','Pollo',4,' -','1 Pollo,
2 Pizzichi Peperoncino In Polvere,
3 Cucchiai Olio D''oliva,
Sale','La vera cottura alla diavola è alla griglia. Questa è una versione casalinga da fare sul fornello. Aprite longitudinalmente il pollo dalla parte del dorso e aiutandovi con un batticarne schiacciatelo bene. In una padella scaldate tre cucchiai d''olio e rosolatevi il pollo per un quarto d''ora. Giratelo diverse volte. Salate e insaporite con due pizzichi di peperoncino in polvere. Proseguite la cottura per circa tre quarti d''ora e servitelo. Anche i galletti possono essere cotti con lo stesso sistema. Vini di accompagnamento: Vini Del Piave Raboso DOC, Velletri Rosso Doc, Lamezia DOC.',2762);
INSERT INTO "ricette" VALUES (19236,'Pollo Alla Diavola (5)','Pollame','Pollo',4,' -','1 Pollo Grande,
Alcune Fette Prosciutto Crudo,
1 Fetta Grande Pancetta,
1 Bicchiere Vino Bianco,
Poco Brodo,
1 Rametto Rosmarino,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulite il pollo dalle interiora, levate testa e zampe e lavatelo molto bene sotto l''acqua corrente, quindi asciugatelo. Tagliate a pezzetti la pancetta e sistematela all''interno del pollo con sale e pepe. Salate il pollo anche all''esterno e poi mettetelo a rosolare in un grande tegame con dell''olio e un rametto di rosmarino. Coprite il tegame, rigirate di tanto in tanto il pollo e aggiungete poco brodo se si attaccasse al fondo. Quando il pollo sarà quasi cotto ricopritelo con le fette di prosciutto crudo e spruzzate con il vino lasciandolo poi evaporare. Spolverate ancora con il pepe e servite.',4432);
INSERT INTO "ricette" VALUES (19237,'Pollo Alla Diavola (6)','Pollame','Pollo',6,' -','1 Pollo Giovane,
Limone,
Burro,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Aprite il pollo a libro e rompete le ossa con il batticarne lasciando intero il petto. Ungetelo bene da tutte le parti, salate e pepate. Prendete una padella (poco più grande del pollo), mettete 4 fette di limone, il pollo e sopra altre 4 fette di limone, coprite con un coperchio. A metà cottura girate e mettete 2 noci di burro. Il pollo dovrà risultare croccante e il petto morbido.',2591);
INSERT INTO "ricette" VALUES (19238,'Pollo Alla Diavola (7)','Pollame','Pollo',4,'Luogo: Lazio.','1 Pollo,
Olio D''oliva,
Sale,
Pepe','Aprite il pollo, dopo averlo fiammeggiato, lungo la schiena, togliete le interiora, lavatelo bene, asciugatelo e posatelo sul tagliere, premetelo sul petto con la mano in modo da appiattirlo bene. Ungete il pollo da ogni parte con olio e conditelo con sale, pepe e mettetelo sulla graticola a fuoco ardente. Rivoltatelo più volte e, se è teneto e piccolino, il pollo dovrebbe essere cotto in 30 minuti, se non ci vorrà di più. Per vedere se è cotto trapassate una coscia con uno spillone e, se non esce sangue vorrà dire che è cotto.',2382);
INSERT INTO "ricette" VALUES (19239,'Pollo Alla Diavola All''agro','Pollame','Pollo',4,' -','1 Pollo Di 1000 G,
1 Ramo Rosmarino,
3 Cucchiai Olio D''oliva Extra-vergine,
1 Limone,
1 Pizzico Sale,
1 Pizzico Pepe','Spremete il limone, raccogliete il succo in una ciotola e tenetelo da parte. Pulite il pollo, fiammeggiatelo, lavatelo e asciugatelo. Tagliatelo lungo la parte anteriore, apritelo, adagiatelo sopra un tagliere e appiattitelo con il batticarne. Irroratelo da ogni parte con l''olio. Mettete in una ciotolina un pizzico di sale e pepe e il rosmarino tritato, mescolateli e cospargeteli sul pollo. Adagiatelo in una padella larga già sul fuoco, con la parte aperta verso l''alto. Coprite la padella con un coperchio, ponendovi un peso sopra affinché il pollo rimanga piatto. Fate cuocere per 20 minuti a fuoco moderato, quindi girate il pollo dall''altra parte e cuocete ancora per 15 - 20 minuti. Il pollo dovrà essere ben dorato da ogni parte. Poco prima della fine cottura irroratelo con il succo di limone che farete evaporare a fuoco vivace. Fate riposare 5 minuti prima di servire in tavola.',1686);
INSERT INTO "ricette" VALUES (19240,'Pollo Alla Fiorentina','Pollame','Pollo',4,'Luogo: Toscana. Luogo: Firenze.','1 Pollo,
2 Uova,
Farina,
1 Spicchio Aglio,
Prezzemolo,
Rosmarino,
Alloro,
Limone,
Olio D''oliva,
Sale,
Pepe','Pulire il pollo, fiammeggiarlo, lavarlo, tagliarlo a pezzi. Tritare una manciata di prezzemolo con l''aglio e unirvi un rametto rosmarino e una foglia di alloro sminuzzati. Mettere i pezzi di pollo in una terrina, cospargerli con gli aromi preparati, versarvi sopra mezzo bicchiere di olio e il succo del limone, salarli, peparli e lasciarli marinare per circa due ore rimuovendoli ogni tanto preparare una pastella sbattendo le uova con un po'' di sale e pepe e aggiungendovi, mescolando, due cucchiaiate di farina e mezzo bicchiere di latte. Mettere al fuoco una padella con abbondante olio. Scolare i pezzi di pollo dalla marinata, immergerli nella pastella ricoprendoli bene, quindi farli rosolare nell''olio caldo. Scolarli quando avranno assunto un bel colore dorato, metterli su una carta assorbente perché perdano l''eccesso di unto e lasciarli raffreddare completamente prima di metterli nel contenitore da picnic.',2950);
INSERT INTO "ricette" VALUES (19241,'Pollo Alla Greca','Pollame','Pollo',4,'Luogo: Grecia.','1200 G Pollo Disossato Senza Grasso A Pezzi,
1/2 Limone,
1/2 Cucchiaino Paprica,
1 Pizzico Pepe,
1/4 Tazza Brodo Di Pollo,
1 Limone Tagliato A Fettine','Strofinare bene il pollo con il limone e cospargerlo di paprica e pepe. Metterlo in forno a 160 gradi per 15 minuti. Aggiungere il brodo e cuocere il pollo per altri 45 minuti, rigirandolo spesso. Guarnire con fette di limone e servire ben caldo.',1514);
INSERT INTO "ricette" VALUES (19242,'Pollo Alla Griglia','Pollame','Pollo',4,' -','1 Pollo Novello Del Peso Di 900 G,
1 Limone,
Olio D''oliva,
Sale,
Pepe','Pulite il pollo eliminando testa, collo e zampe; fiammeggiatelo, lavatelo e asciugatelo bene con un canovaccio. Apritelo praticando un taglio sulla schiena, appiattitelo con il batticarne premendo in particolare modo sullo sterno. Mettetelo a marinare in un po'' di olio, succo di limone, abbondante pepe e sale. Lasciatevelo per il tempo che avete a disposizione (almeno una mezz''oretta). Di tanto in tanto rigiratelo nella marinata perché la carne si insaporisca. Mettete al fuoco la griglia quando sarà ben calda appoggiatevi il pollo scolato dalla marinata e cuocetelo mantenendo il fuoco basso; di tanto in tanto rigiratelo.',1727);
INSERT INTO "ricette" VALUES (19243,'Pollo Alla Griglia Con Aromi','Pollame','Pollo',4,' -','1 Pollo Di 1500 G In Pezzi Da 375 G,
1 Cipolla,
1/2 Bicchiere Olio D''oliva,
5 Foglie Alloro,
1/2 Limone,
1 Rametto Salvia,
1 Rametto Rosmarino,
3 Peperoncini,
1 Spicchio Aglio,
1 Manciata Olive Nere,
Sale,
Pepe','Pulite con cura i pezzi di pollo, cospargeteli con sale e abbondante pepe e poneteli in una terrina; unite la cipolla tagliata ad anelli, l''aglio schiacciato, le olive, la salvia, il rosmarino, l''alloro, i peperoncini dimezzati e privati di semi e nervature, il succo di mezzo limone e l''olio. Rigirate più volte i pezzi di pollo nella terrina, in modo che si insaporiscano nel condimento, coprite il recipiente con un foglio di pellicola trasparente e lasciate marinare per mezza giornata in luogo fresco. Trascorso il tempo indicato, sgocciolate i quarti di pollo dalla marinata e poneteli sulla griglia calda dalla parte con la pelle, lasciateli cuocere 20 minuti per parte e abbiate cura di spennellarli di tanto in tanto con la marinata. Servite il pollo caldissimo.',2574);
INSERT INTO "ricette" VALUES (19244,'Pollo Alla Malva','Pollame','Pollo',4,' -','2 Petti Di Pollo,
10 G Fiori Di Malva,
1 Mela Verde,
Erba Cipollina,
Olio D''oliva,
Alcuni Cucchiai Maionese,
Sale,
Pepe','In un padellino insaporite i petti con olio, sale e pepe fino a quando sono ben dorati .Poi tagliateli a striscioline, metteteli in una insalatiera, aggiungete l''erba cipollina tagliuzzata e la mela verde a fettine. Condite con alcuni cucchiai di maionese, mescolate. Cospargete i fiori di malva. Servite.',2053);
INSERT INTO "ricette" VALUES (19245,'Pollo Alla Marengo','Pollame','Pollo',4,'Luogo: Piemonte. Luogo: Alba. Preparazione: 30 minuti. Cottura: 40 minuti.','1 Pollo Medio Pulito E Fiammeggiato,
5 Cucchiai Farina Di Grano 00,
1 Bicchiere Vino Bianco Secco,
1 Bicchiere Brodo Di Carne,
Burro,
Olio D''oliva,
1/2 Limone (succo),
1 Spicchio Aglio,
Sale,
Pepe,
Noce Moscata','Fate il pollo in otto pezzi, infarinateli e metteteli a rosolare in una casseruola con olio d''oliva e burro e uno spicchio d''aglio; salateli, pepateli e spolverizzateli di noce moscata. Quando avranno assunto un bel colore dorato, bagnateli col vino bianco secco e lasciatelo evaporare. Aggiungete adesso un bicchiere di brodo, incoperchiate e cuocete a fiamma sostenuta, ma non violenta, fino a completa cottura. Disponete i pezzi di pollo in un piatto di portata ed irrorateli con un intingolo ottenuto miscelando il fondo di cottura col succo di mezzo limone. Servite caldo, guarnito con patatine novelle al forno. Si dice che questo piatto fosse stato servito la sera della battaglia di Marengo al generale Bonaparte, poi uscito vittorioso. Si dice che i viveri delle truppe francesi fossero allo stremo: ma un pollo si può anche rubare, in guerra. Si dice ancora che fosse stato fritto nell''olio ed irrorato di Madera. Ho consultato i sacri testi della cucina piemontese postnapoleonici che sono quelli del Chapusot (1846) e del Vialardi (1854), ma del Madera non ho trovato traccia. Il Chapusot, poi, in questo sauté ci mette anche le tomatiche, ovvero pomodori, avvicinandosi al pollo alla cacciatora. Vino consigliato: Barbera d''Alba.',3594);
INSERT INTO "ricette" VALUES (19246,'Pollo Alla Marengo Con Cortese Di Gavi','Pollame','Pollo',4,' -','1 Pollo Giovane,
50 G Burro,
1 Cucchiaio Olio D''oliva Extra-vergine,
Noce Moscata,
1 Cucchiaio Farina,
1 Bicchiere Vino Cortese Di Gavi,
1 Mestolo Brodo,
Prezzemolo Tritato,
1/2 Limone','Prendete il pollo ed escludete la pelle e le zampe, tagliatelo a pezzi grossi nelle giunture. Mettetelo a rosolare con il burro, l''olio, un pizzico di sale, pepe e una presa di noce moscata. Quando i pezzi saranno ben rosolati da una parte e dall''altra,scolate via l''unto e aggiungete la farina e il bicchiere di Cortese di Gavi. Unite il brodo e portate il pollo a cottura coperto e a fuoco lento. Prima di toglierlo dal fuoco spruzzate un pizzico di prezzemolo tritato e quando il pollo sarà nel vassoio di portata versategli il succo di limone.',2110);
INSERT INTO "ricette" VALUES (19247,'Pollo Alla Normanna','Pollame','Pollo',4,'Luogo: Francia. Luogo: Normandia.','1 Pollo,
20 G Burro,
Sale,
Pepe,
1 Bicchiere Calvados,
20 Cl Panna,
1 Tuorlo,
400 G Funghi Coltivati','Rosolare senza colorare il pollo in pochissimo burro, salare e pepare. Coprire e cuocere, rivoltando ogni tanto il pollo, per 30 minuti. Sbattere il tuorlo con la panna. Far saltare al burro i funghi. Aggiungere i funghi nella pentola. Cuocere a coperto 5 minuti. Mettere il pollo sul piatto di portata. Aggiungere la panna alla salsa, scaldare senza bollire e versare sulla carne.',3034);
INSERT INTO "ricette" VALUES (19248,'Pollo Alla Normanna (2)','Pollame','Pollo',4,'Luogo: Francia. Luogo: Normandia.','1 Pollo,
70 G Burro,
1/2 Tazza Panna Fresca,
1/2 Bicchiere Sidro,
1 Bicchierino Calvados,
2 Mele Renette,
2 Cucchiai Prezzemolo Tritato,
Sale,
Pepe','Salate e pepate l''interno e l''esterno del pollo e mettetelo in un piatto da forno con qualche noce di burro. Cuocetelo a forno caldo (200 gradi) per 35 minuti, bagnandolo frequentemente durante la cottura. Togliete il pollo dal piatto, tagliatelo in sei pezzi e tenetelo in caldo. Lavate e pelate le mele, privatele del torsolo, tagliatele a rondelle e rosolatele a fuoco lento in poco burro. Versate il sugo di cottura del pollo in una casseruola, aggiungete il sidro, il calvados e la panna. Mettete a fuoco vivo e fate ribollire per 4 o 5 minuti per ridurre. Disponete il pollo nel piatto da portata, guarnitelo con le mele, ricopritelo con la salsa di calvados e panna, spolverate con il prezzemolo tritato e servite.',2735);
INSERT INTO "ricette" VALUES (19249,'Pollo Alla Panna','Pollame','Pollo',4,' -','1 Pollo,
2 Cucchiai Olio D''oliva,
30 G Burro,
10 G Farina,
250 G Panna Liquida,
Sale','Pulire e tagliare a pezzi il pollo. Insaporirlo in padella con l''olio. Sciogliere nel burro la farina, diluire con la panna e cuocere per 5 minuti. Versare la salsa sul pollo, salare e cuocere per circa 1 ora.',3144);
INSERT INTO "ricette" VALUES (19250,'Pollo Alla Panna (2)','Pollame','Pollo',4,' -','1 Pollo,
40 G Burro,
60 G Prosciutto Cotto,
1/2 Limone,
1 1/2 Bicchiere Panna,
Farina,
Sale,
Pepe','Tagliate a pezzi il pollo, salateli, pepateli e infarinateli. In un tegame fate sciogliere il burro, disponetevi la carne e cuocete a fuoco basso evitando che i pezzi coloriscano troppo in fretta. Quando sono rosolati, versate la panna e lasciate sobbollire piano per mezz''ora o poco più. Regolate sale e pepe. Aggiungete il succo di limone filtrato al colino, mescolate bene e cospargete sul pollo il prosciutto tritato. Tenete ancora 2 minuti sul fuoco, disponete sul piatto da portata e servite. Vini di accompagnamento: Colli Morenici Mantovani Del Garda Rosso DOC, Colli Amerini rosso Novello DOC, Taburno Novello DOC.',3125);
INSERT INTO "ricette" VALUES (19251,'Pollo Alla Panna (3)','Pollame','Pollo',4,' -','1 Pollo,
2 Cucchiai Olio D''oliva,
50 G Burro,
10 G Farina,
250 G Panna Liquida,
Sale','Pulire e tagliare a pezzi il pollo. Insaporirlo in padella con l''olio. Sciogliere nel burro la farina, diluire con la panna e cuocere per 5 minuti. Versare la salsa sul pollo, salare e cuocere per circa 1 ora.',3294);
INSERT INTO "ricette" VALUES (19252,'Pollo Alla Paprica','Pollame','Pollo',4,'Luogo: Austria.','1 Pollo Di Circa 1000 G,
30 G Pancetta Affumicata,
200 G Cipolle,
100 G Peperoni Verdi,
50 G Olio D''oliva,
20 G Paprica Dolce,
Sale,
50 G Concentrato Di Pomodoro','Lavate il pollo, asciugatelo e tagliatelo a pezzi di dimensioni il più possibile uniformi. Tritate la pancetta affumicata e le cipolle, separatamente, servendovi della mezzaluna. Tagliate a metà i peperoni, privateli dei semi e delle membrane bianche interne, poi lavateli e riducete la polpa a listerelle sottili. Fate soffriggere dolcemente la pancetta in una pirofila con l''olio d''oliva, quindi unite le cipolle e fate rosolare anch''esse. Aggiungete la paprica, quindi mettete nel recipiente anche i pezzetti di pollo e fateli rosolare da tutti i lati, infine salate. Unite il concentrato di pomodoro e i peperoni, coprite la pirofila e lasciate cuocere la carne a calore moderato per 30-40 minuti. Se il fondo di cottura tende ad asciugarsi troppo, aggiungete di tanto in tanto un po'' d''acqua.',1893);
INSERT INTO "ricette" VALUES (19253,'Pollo Alla Paprica (2)','Pollame','Pollo',4,'Luogo: Austria.','1 Pollo Tagliato A Pezzi,
2 Cipolle Non Troppo Grandi,
Paprica Dolce,
Sale,
Farina,
Panna Acida,
Olio Di Semi','Si cuoce la cipolla, tagliata finemente, nell''olio, senza farla colorire, si toglie dal fuoco e si aggiunge la paprica ed il pollo. Si mette nuovamente sul fuoco, si fa rosolare, si aggiunge acqua e si fa cuocere, salando opportunamente. Si toglie poi la carne e si aggiunge al sughetto la panna acida con dentro due cucchiai di farina per far addensare. Si mette poi di nuovo dentro la carne, facendo insaporire per qualche minuto.',2966);
INSERT INTO "ricette" VALUES (19254,'Pollo Alla Provenzale','Pollame','Pollo',4,'Luogo: Francia. Luogo: Provenza.','1 Pollo Tagliato In 8 Parti,
500 G Melanzane,
500 G Pomodori Maturi,
2 Peperoni Verdi,
1 Cipolla,
2 Spicchi Aglio,
Sale,
Pepe,
Timo,
Rosmarino,
Origano','Rosolare il pollo. Aggiungere la cipolla tagliuzzata e l''aglio. Aggiungere i peperoni, le melanzane e i pomodori (tutti tagliati a pezzi piuttosto grossi). Salare e pepare. Aggiungere le erbe e coprire. Cuocere per 30 minuti.',1963);
INSERT INTO "ricette" VALUES (19255,'Pollo Alla Roccia','Pollame','Pollo',4,' -','1 Pollo Aperto E Appiattito,
Olio D''oliva,
1/2 Limone (succo),
Sale,
Pepe','Si metta il pollo in un pò d''olio, cui si e aggiunto il succo di mezzo limone, sale e pepe. Si volti il pollo ogni tanto lasciandolo nell''infuso per circa un''ora. Lo si passi poi alla piòta moderatamente calda e lo si faccia cuocere per circa mezzora voltandolo di tanto in tanto. E'' giunto a cottura giusta quando sarà ben rosolato esternamente e ben morbido dentro. Disponendo di una seconda piota già riscaldata, il pollo si può far cuocere schiacciato tra le due lastre. Tranciare e servire.',2385);
INSERT INTO "ricette" VALUES (19256,'Pollo Alla Romana','Pollame','Pollo',2,'Luogo: Lazio. Luogo: Roma.','1 Pollo Di 1000 G Pronto Per La Cottura,
1 Spicchio Aglio,
Sale,
Pepe Bianco,
3 Cucchiai Erbe Tritate (salvia, Rosmarino),
1/2 Limone (scorza),
3 Cucchiai Olio D''oliva,
4 Fette Pancetta,
12 Cl Vino Bianco Secco,
300 G Pomodori Pelati,
100 G Cipollotti,
Olio D''oliva Per La Teglia','Lavate con cura il pollo sotto l''acqua corrente, asciugatelo tamponandolo con un canovaccio, infine tagliatelo a metà. In una ciotolina mescolate l''aglio tritato finemente, una presa di sale, una macinata di pepe, le erbe miste e la scorza grattugiata di mezzo limone, quindi cospargete il pollo col miscuglio ottenuto. Bagnate il volatile con l''olio d''oliva, avvolgete ogni metà nelle fette di pancetta e disponetele in una teglia ben unta d''olio. Fate cuocere il pollo nel forno a 200 gradi per 15 minuti, poi versate il vino, riducete la temperatura a 180 gradi, unite i pomodori e i cipollotti tagliati a dadini e portate a cottura (occorrono altri 30 minuti).',4293);
INSERT INTO "ricette" VALUES (19257,'Pollo Alla Romana (2)','Pollame','Pollo',4,'Luogo: Lazio. Luogo: Roma.','1 Pollo,
3 Spicchi Aglio,
3 Cipolle,
5 Peperoni,
50 G Estratto Di Pomodoro,
Rosmarino,
Pepe,
Sale,
Paprica,
Senape,
4 Pomodori','Tagliare il pollo a pezzi e spalmarli con senape, sale e paprica. Affettare i peperoni, le cipolle, l''aglio e i pomodori. Rosolare i pezzi di pollo da tutte le parti e aggiungere le verdure, l''estratto di pomodoro, il sale e il rosmarino. Cuocere a fuoco medio per 15 mm. coprire e contenere la cottura al minimo per altri 15 minuti. Spegnere e lasciare in pentola coperta per ulteriori 15 minuti.',2107);
INSERT INTO "ricette" VALUES (19258,'Pollo Alla Romana Coi Peperoni','Pollame','Pollo',4,'Luogo: Lazio. Luogo: Roma.','1 Pollo Tagliato In 8 Pezzi,
50 G Guanciale Di Maiale,
1 Spicchio Aglio,
1 Cucchiaio Maggiorana Fresca,
1/2 Bicchiere Vino Bianco,
300 G Pomodori San Marzano,
2 Peperoni Gialli E Rossi,
10 Cl Olio D''oliva Extra-vergine,
Sale,
Pepe','Soffriggere in padella il guanciale con 2 cucchiai d''olio, aggiungere il pollo e farlo rosolare aggiustando quindi di sale e pepe. Unire 1 spicchio di aglio schiacciato, la maggiorana sminuzzata e i pomodori spellati e ridotti in pezzettini. Cuocere a fuoco vivace, irrorando con vino. Da parte tagliare i peperoni a listarelle di 2 cm, arrostirli in padella con 1 spicchio di aglio e olio, quindi, una volta cotti, unirli al pollo, mescolare bene e servire.',2989);
INSERT INTO "ricette" VALUES (19259,'Pollo Alla Salsa Di Capperi','Pollame','Pollo',4,' -','6 Bistecche Petto Di Pollo,
2 Cucchiai Olio D''oliva,
4 Cucchiai Burro,
Sale,
Pepe,
2 Cucchiai Succo Di Limone,
2 Cucchiai Capperi,
Prezzemolo,
1 Limone A Fette','Scaldate due cucchiai di burro in una padella antiaderente a fuoco basso. Aggiungete il pollo e fatelo dorare da entrambi i lati per 4 o 5 minuti. Togliere il pollo dal fuoco, metterlo su un piatto caldo e condire con sale pepe e olio. Versare il succo di limone e i capperi nella padella, scaldare e aggiungere il rimanente burro. Mescolare fino a far sciogliere del tutto. Aggiungere il prezzemolo e versare la salsina sul pollo. Decorare con fettine di limone e servire con riso bollito o insalata di patate.',2910);
INSERT INTO "ricette" VALUES (19260,'Pollo Alla Salsa Di Noci','Pollame','Pollo',4,' -','1 Pollo Ruspante,
Olio D''oliva Extra-vergine,
Per La Salsa:,
3 Cipollotti,
3 Scalogni,
1 Limone,
1 Ciuffo Prezzemolo,
Alcune Foglie Basilico,
6 Gherigli Di Noci,
4 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Paprica','Grattugiare il limone. Tagliare il pollo in 8 pezzi e disporlo in una pirofila unta d''olio. Sbucciare gli scalogni e frullarli con prezzemolo, basilico, noci, buccia di limone, versando l''olio a filo. Unire sale e paprica. Irrorare di salsa i pezzi di pollo e mettere in forno a 180 gradi per 30 minuti rigirando il pollo di tanto in tanto.',3313);
INSERT INTO "ricette" VALUES (19261,'Pollo Alla Salsa Di Tonno','Pollame','Pollo',4,' -','1 Pollo,
1 Bicchiere Vino,
1 Scatola Tonno,
1 Carota,
1 Cipolla,
3 Acciughe,
3 Uova Sode,
1 Limone,
Olio D''oliva','Cuocere il pollo nell''acqua con il vino, la cipolla, la carota e il sale per circa 1 ora e 30 minuti. Far raffreddare il pollo nel brodo. Pulire le acciughe, sgocciolare il tonno e passarli al mixer con i tuorli sodi. Allungare la salsa ottenuta con olio e succo di limone. Disporre il pollo a pezzi su un piatto e servirlo con la salsa al tonno.',4145);
INSERT INTO "ricette" VALUES (19262,'Pollo Alla Ticinese','Pollame','Pollo',4,' -','1 Pollo Di 1200 G Già Pulito,
Olio D''oliva,
2 Cucchiai Farina Bianca,
80 G Prosciutto Crudo,
1/2 Bicchiere Vino Bianco,
Salvia,
1 Pizzico Spezie Miste In Polvere,
Sale,
Pepe','Fiammeggiare e lavare il pollo, tagliarlo a pezzi, infarinarli appena e farli dorare da tutte le parti in 1 capace pirofila nell''olio ben caldo, per 10 minuti. Tagliare il prosciutto a striscette e unirlo al pollo, versando poi nel recipiente il vino bianco, le spezie, sale, pepe e le foglie di salvia. Passare la pirofila in forno caldo a 200 gradi per 40 minuti circa o più, fino a quando la carne del pollo sarà tenera.',2577);
INSERT INTO "ricette" VALUES (19263,'Pollo Alla Toscana','Pollame','Pollo',4,'Luogo: Toscana.','1 Pollo A Pezzi,
Farina,
2 Uova,
Olio D''oliva,
Burro,
Sale','Lavate i pezzi di pollo, devono essere piccoli, asciugateli, poi passateli nelle uova sbattute e leggermente salate e nella farina. In una padella scaldate olio e burro, quando sono fumanti cuocete i pezzi di pollo per circa quindici minuti: devono diventare dorati all''esterno e morbidi dentro. Sgocciolateli, passateli su carta assorbente, quindi su un piatto da portata caldo. Allo stesso modo potrete cuocere il coniglio, sempre tagliato a piccoli pezzi.',3639);
INSERT INTO "ricette" VALUES (19264,'Pollo Alla Waterzooi','Pollame','Pollo',4,' -','1 Pollo Tagliato In 8 Pezzi,
2 Gambi Sedano,
2 Porri,
1 Cipolla,
30 Cl Brodo,
Sale,
Pepe,
Noce Moscata,
20 Cl Panna,
2 Tuorli D''uovo','Far fondere a coperto la cipolla tagliuzzata. Aggiungere i pezzi di pollo e le verdure sminuzzate. Salare e pepare. Bagnare col brodo e coprire. Cuocere per 1 ora. Sbattere i tuorli con la panna un po'' di noce moscata. Aggiungere alla salsa del pollo e servire senza più mettere sul fuoco.',2875);
INSERT INTO "ricette" VALUES (19265,'Pollo Alle Arachidi','Pollame','Pollo',4,' -','1 Pollo,
200 G Arachidi Sgusciate E Tostate,
20 G Burro,
6 Cucchiai Olio D''oliva,
1 Cucchiaio Farina,
Spezie Miste In Polvere','Tagliare il pollo a pezzi, infarinarli e cuocerli lentamente nell''olio. Pestare le arachidi nel mortaio, metterle in una pentola con poca acqua e lasciarle cuocere con sale, pepe e spezie fino ad ottenere una crema alla quale unire il burro. Versare questa salsa sul pollo, cuocere ancora 10 minuti mescolando e unire, se occorre, un po'' d''acqua calda.',5321);
INSERT INTO "ricette" VALUES (19266,'Pollo Alle Cipolle','Pollame','Pollo',4,' -','1 Pollo,
500 G Cipolline,
30 G Burro,
1 Spicchio Aglio,
1 Cipolla Grande,
1 Rametto Timo,
1 Foglia Alloro,
2 Cucchiai Olio D''oliva,
Sale,
Pepe','In un tegame scaldate il burro e due cucchiai d''olio, rosolatevi il pollo tagliato a pezzi, aggiungete la cipolla affettata molto sottilmente e le cipolline intere. Fate prendere colore lentamente. Mescolate un paio di volte, salate e pepate. Aggiungete un rametto di timo, una foglia d''alloro intera e uno spicchio d''aglio. Coprite e cuocete a fuoco basso per 40 minuti. Eliminate l''alloro e l''aglio. Disponete sul piatto da portata. Vini di accompagnamento: Gabiano DOC, Sangiovese Dei Colli Pesaresi DOC, Ischia Rosso DOC.',2486);
INSERT INTO "ricette" VALUES (19267,'Pollo Alle Erbe','Pollame','Pollo',4,' -','4 Petti Di Pollo Divisi A Metà,
2 Zucchine Tagliate A Rondelle,
1 Peperone A Pezzetti,
12 Cl Aceto Di Vino,
150 G Pomodori Pelati,
1 Cucchiaio Olio D''oliva,
1 Cipolla A Fettine,
1 Cucchiaio Zucchero,
2 Spicchi Aglio,
1 Cucchiaino Origano,
1 Cucchiaino Pepe','Battere delicatamente i petti di pollo e tagliarli in quattro grosse strisce. Metterle in una casseruola con le zucchine e il peperoncino. Unire l''aceto e gli altri ingredienti e far riposare in bicchiere. Coprire e agitare bene. Mettere la salsina sul pollo e sulle verdure. Coprire, marinare e far riposare per un''ora. Versare di nuovo la salsina in una padella antiaderente. Far bollire per un minuto. Infilzare negli spiedini di legno, un pezzetto di verdura e un pezzetto di pollo e bagnare nella salsina. Far cuocere ancora per dieci minuti, unendo la marinata.',1599);
INSERT INTO "ricette" VALUES (19268,'Pollo Alle Erbe Aromatiche','Pollame','Pollo',4,' -','1 Pollo Da 1200 G,
4 Cucchiai Prezzemolo, Basilico, Maggiorana, Salvia,
Pepe,
4 Cucchiai Olio D''oliva Extra-vergine,
4 Pomodori Pelati,
1 Cipolla,
1 Scalogno,
2 Mestoli Brodo,
Sale','Tagliate il pollo a pezzi non troppo grossi; sbucciate e tritate cipolla e scalogno, fateli appassire con l''olio, poi adagiatevi i pezzi di pollo e lasciateli colorire da tutte le parti. Cospargeteli con le erbe aromatiche tritate, con i pomodori triturati, salate, pepate e bagnate con il brodo. Fate cuocere per circa 50 minuti, piano e a recipiente coperto. Negli ultimi 10 minuti scoprite per far addensare il sugo. Levate il pollo dal tegame, frullate il fondo di cottura, riscaldatelo leggermente, senza farlo bollire, poi versatelo sul pollo che avrete tenuto in caldo e servite subito.',2287);
INSERT INTO "ricette" VALUES (19269,'Pollo Alle Erbe Con Patatine','Pollame','Pollo',4,' -','1 Pollo Di 1000 G,
1 Ramo Rosmarino,
Salvia,
Timo,
2 Foglie Alloro,
400 G Patate Novelle,
4 Scalogni,
3 Cucchiai Aceto Aromatico,
20 G Burro,
4 Cucchiai Olio D''oliva Extra-vergine,
1 Mazzetto Prezzemolo,
Sale,
Pepe','Sbucciate e lavate le patatine novelle e gli scalogni. Pulite il pollo, privatelo delle interiora, passatelo sulla fiamma per eliminare la peluria, lavatelo e asciugatelo. Strofinatelo internamente ed esternamente con il sale. lavate la salvia, il timo e gli aghi dei rosmarino, asciugateli e tritateli finemente. In una ciotola mescolate il trito di erbe con abbondante pepe; mettetene una parte nell''interno del pollo aggiungendo anche una foglia di alloro. legate il pollo con lo spago da cucina, spennellatelo con un cucchiaio d''olio e cospargetelo con metà dei trito di erbe rimasto. Mettete il pollo in un tegame da forno, ponetelo in forno preriscaldato a 180 gradi e fatelo cuocere per 15 minuti circa rigirandolo di tanto in tanto. Trascorso questo tempo, aggiungete nello stesso tegame le patatine e gli scalogni; irrorate con l''olio rimasto, cospargete con il rimanente trito di erbe, aggiungete l''altra foglia d''alloro e un pizzico di sole e pepe. Continuate la cottura per circa 40 minuti irrorando di tanto in tanto col fondo di cottura Scolate il pollo, dividetelo a pezzetti e adagiateli sul piatto di portata caldo. Aggiungetevi le patatine, gli scalogni e coprite il piatto con un foglio di carta metallizzata. Eliminate il grasso di cottura dal tegame che porrete sul fuoco; versatevi l''aceto e mescolate per staccare il fondo di cottura. Dopo qualche minuto, aggiungete mezzo bicchiere di acqua e fatela ridurre alla metà. Aggiungete infine il burro diviso a pezzetti, battendolo con una forchetta per addensare la salsa; unitevi il prezzemolo lavato e tritato. Eliminate la carta metallizzata, versate la salsa sul pollo e servitelo subito.',2344);
INSERT INTO "ricette" VALUES (19270,'Pollo Alle Erbe Di Monte','Pollame','Pollo',4,' -','1 Pollo Di Circa 1300 G,
Burro,
Olio D''oliva,
Fegatini Di Pollo,
1 Cipolla,
1 Sedano,
Alcune Carote,
Alcune Bacche Ginepro,
Timo,
Maggiorana Di Monte,
Sale,
Pepe,
Alloro,
1/2 Bicchierino Cognac,
1/2 Bicchiere Vino Rosso Valtellina Invecchiato,
1 Cucchiaio Farina,
1 Cucchiaio Crema Di Latte,
Per Servire:,
Crostoni Di Pane','Pulito un pollo del peso di circa 1300-1400 g, lo si faccia rosolare in burro e olio. Vi si uniscano i suoi fegatini, una cipolla, sedano, carote, alcune bacche di ginepro, timo e maggiorana di monte, sale e pepe e alloro. Lo si bagni - poi - con mezzo bicchierino di cognac e mezzo bicchiere di vino rosso valtellina invecchiato. Al termine della cottura, si passino al setaccio gli ingredienti e il sugo, che va legato con un cucchiaino di farina ed un cucchiaino di crema di latte. Si tagli il pollo in ottavi. Infine, lo si serva su crostoni di pane ben caldi, passati nel burro e bagnati con il sugo che deve essere cremoso ed abbondante.',3821);
INSERT INTO "ricette" VALUES (19271,'Pollo Alle Mandorle','Pollame','Pollo',4,' -','4 Cosce Di Pollo,
1 Cipolla,
150 G Olive Verdi,
125 G Mandorle Pelate,
1 Cucchiaio Farina Di Mais,
2 Spicchi Aglio,
1 Cucchiaino Semi Di Coriandolo,
1 Cucchiaino Semi Di Cumino,
1 Pizzico Paprica Piccante,
1 Bicchiere Vino Rosso,
Abbondante Olio D''oliva,
Noce Moscata,
Sale','Passate le cosce del pollo nella farina di mais, poi rosolate in abbondante olio. Unite la cipolla tritata con due spicchi d''aglio, salate, insaporite con noce moscata, un cucchiaino di semi di cumino e uno di coriandolo pestati. Bagnate con un bicchiere di vino e un po'' d''acqua, coprite e portate a cottura. Prima di togliere dal fuoco aggiungete un pizzico di paprica. Passate il pollo su un piatto. Nel suo sugo mettete le olive, le mandorle a filetti, un cucchiaio di farina di mais, mescolate e versate sul pollo.',3155);
INSERT INTO "ricette" VALUES (19272,'Pollo Alle Mandorle (2)','Pollame','Pollo',4,' -','1 Pollo Ruspante Disossato Ridotto In Pezzi Regolari,
150 G Mandorle Tostate Pelate,
250 G Cipolle,
3 Cucchiai Olio D''oliva Extra-vergine,
Prezzemolo Tritato,
Radice Di Zenzero Grattugiata,
Alcuni Stimmi Zafferano,
Pepe Bianco,
Sale Marino Integrale','Disporre i pezzi di pollo in un coccio; irrorarli con olio; cospargervi sale, pepe, zenzero, zafferano. Unire la cipolla triturata e coprire con acqua. Portare ad ebollizione e cuocere 1 ora. Triturare le mandorle e cospargerne il pollo servito col suo fondo di cottura.',2862);
INSERT INTO "ricette" VALUES (19273,'Pollo Alle Mandorle Con Il Bimby','Pollame','Pollo',6,' -','600 G Petti Di Pollo,
150 G Mandorle Pelate,
30 G Farina,
50 G Cipolla,
40 G Olio D''oliva,
20 Cl Brodo,
Sale,
Pepe','Taglia il pollo a bocconcini e infarinali. Trita metà delle mandorle a velocità 3 e unisci le restanti intere con 2 cucchiai di olio: 3 minuti a temperatura 90 velocità 1. Toglile e posale su carta assorbente. Soffriggi il rimanente olio con la cipolla: 3 minuti a temperatura 100 velocità 4. Disponi la farfalla sulle lame, unisci i bocconcini di pollo e cuoci 3 minuti a temperatura 100 velocità 1. Aggiungi il brodo e termina la cottura per 12 minuti velocità 1. Aggiusta di sale, pepe, unisci le mandorle e cuoci ancora per 2 minuti. Disponilo in un piatto da portata e servilo ben caldo.',2053);
INSERT INTO "ricette" VALUES (19274,'Pollo Alle Mele','Pollame','Pollo',4,' -','1 Pollo,
2 Mele Renette,
4 Fettine Lardo,
Sale,
Pepe','Fiammeggiate, lavate e asciugate con cura il pollo. Salatelo, pepatelo internamente e riempitelo con la polpa grattugiata delle mele. Cucite l''apertura e avvolgetelo nel lardo fermandolo con alcuni giri di spago bianco da cucina. Adagiatelo in una teglia e cuocete in forno a 240 gradi lasciando che il lardo si sciolga, ammorbidisca la carne e coli sul fondo del recipiente. Riducete la temperatura a 190 gradi. Dopo mezz''ora cominciate a bagnare il volatile con il suo sugo a intervalli regolari. Calcolate che il tempo complessivo di cottura è di circa un''ora, dipende dal peso del pollo. Se vi sembra che la pelle colorisca troppo rapidamente, riducete il calore e coprite la teglia con un foglio d''alluminio. Ritirate, eliminate lo spago, staccate cosce e ali, tagliate a fette la parte centrale ripiena. Vini di accompagnamento: Valle D''Aosta Gamay DOC, Lago Di Caldaro Scelto DOC, Sangiovese Di Romagna Novello DOC.',2574);
INSERT INTO "ricette" VALUES (19275,'Pollo Alle Olive','Pollame','Pollo',4,' -','800 G Pollo A Pezzi,
80 G Olive Verdi Snocciolate,
3 Cucchiai Olio D''oliva,
1/2 Arancia (scorza),
1 Cipolla,
2 Carote,
Sedano,
3 Spicchi Aglio,
Origano,
1 Bicchierino Vino Bianco,
5 Grani Pepe,
2 Chiodi Di Garofano,
Sale,
1 Bicchierino Cognac','Tagliare a pezzi sedano carote e cipolla e metterli in una ciotola con l''origano, l''aglio, la scorza d''arancia, il pepe, i chiodi di garofano, il pollo, il vino e il cognac e marinare per 4 ore. In una casseruola scaldare l''olio e rosolarvi il pollo, aggiungere le olive e, dopo 5 minuti, la marinata e cuocere a fuoco lento per circa 30 minuti.',2334);
INSERT INTO "ricette" VALUES (19276,'Pollo Alle Olive (2)','Pollame','Pollo',4,' -','1 Pollo Di 1200 G,
200 G Olive Verdi Snocciolate,
1 Bicchiere Aceto Di Vino,
4 Cucchiai Olio D''oliva Extra-vergine,
2 Spicchi Aglio,
Peperoncino','Fiammeggiate, lavate il pollo e tagliatelo a pezzi piccoli; fatelo rosolare molto bene in olio dove avrete fatto imbiondire l''aglio e soffriggere il peperoncino. Aggiungete l''aceto e fatelo evaporare a fuoco vivo. Aggiungete le olive, rimescolate e fate cuocere a fuoco lento per circa mezz''ora; se si asciuga troppo aggiungete un goccio di acqua calda o di brodo.',2323);
INSERT INTO "ricette" VALUES (19277,'Pollo Alle Olive (3)','Pollame','Pollo',4,' -','1 Pollo,
1 Bicchiere Vino Bianco,
6 Pomodori,
1/2 Limone (succo),
60 G Olive Nere,
Maggiorana,
2 Spicchi Aglio,
Timo,
Basilico,
Salvia,
Olio D''oliva,
Sale,
Pepe','In un tegame scaldate l''olio e rosolatevi il pollo tagliato a pezzi per almeno un quarto d''ora mescolando spesso. Salate, pepate, poi togliete i pezzi e teneteli da parte al caldo. Diluite con il vino il fondo di cottura, fate evaporare, aggiungete i pomodori, l''aglio tritato, il timo, la salvia e la maggiorana tritati. Ponete di nuovo il pollo nel tegame e cuocete per mezz''ora mescolando ogni tanto. Aggiungete le olive snocciolate, il succo di limone e il basilico. Fate insaporire e servite. Vini di accompagnamento: Riviera Ligure Di Ponente Rossese DOC, Sangiovese Di Romagna DOC, Gioia Del Colle rosso DOC.',2846);
INSERT INTO "ricette" VALUES (19278,'Pollo Alle Olive (4)','Pollame','Pollo',4,' -','1 Pollo,
3 Pomodori,
3 Peperoni,
3 Zucchine,
100 G Olive Nere,
Alcune Foglie Basilico,
1/2 Bicchiere Olio D''oliva,
Sale,
Pepe','Tagliate il pollo in 8 pezzi e doratelo in una padella con olio, sale e pepe. Aggiungete i peperoni e le zucchine tagliati a fettine, e i pomodori tagliati in 4 parti. Mescolate il tutto aggiungendo il basilico e lasciate cuocere per 45 minuti. Prima della fine della cottura aggiungete le olive senza osso. Lasciate ancora cuocere per 5 minuti.',2867);
INSERT INTO "ricette" VALUES (19279,'Pollo Alle Olive (5)','Pollame','Pollo',4,' -','800 G Pollo A Pezzi,
200 G Olive Nere,
1 Bicchiere Vino Marsala Secco,
Olio D''oliva,
Sale','In un tegame mettere insieme pollo e olio e far rosolare il pollo a fuoco vivo. Salare il pollo, bagnarlo con il marsala e unire le olive snocciolate. Coprire e cuocere a fuoco lento per circa 40 minuti.',2370);
INSERT INTO "ricette" VALUES (19280,'Pollo Alle Olive Di Donna Patrizia','Pollame','Pollo',4,' -','1/2 Cipolla Rossa,
1 Gambo Sedano,
1 Manciata Prezzemolo,
1 Carota,
25 G Burro,
1 Cucchiaio Olio D''oliva,
1 Pollo,
50 Cl Brodo,
14 Olive Di Gaeta,
1 Cucchiaino Conserva Di Pomodoro','Tritate la cipolla il sedano, il prezzemolo e la carota e metteteli in una casseruola col burro e l''olio; quando sarà soffritto ponetevi il pollo a rosolare da ogni parte, rivoltando spesso. Salatelo, poi bagnatelo col brodo bollente. Allora aggiungete quattro olive trinciate, altre quattro pestate bene nel mortaio e sei intere e la conserva di pomodoro, lasciate concentrare l''intingolo e servite quando il pollo sarà cotto.(cucina genovese). Trucchi e segreti: fate andare a fuoco lento il soffritto altrimenti potrebbe bruciarsi e rendere amara la preparazione; rosolate bene il pollo (la rosolatura iniziale mantiene la carne del pollo tenera); non abbiate paura di cuocere bene la cipolla (il gusto della cipolla mezza cruda non è gradevole); se il sugo tende ad asciugarsi aggiungete una cucchiaio d''acqua calda.',2769);
INSERT INTO "ricette" VALUES (19281,'Pollo Alle Olive E Capperi Al Microonde','Pollame','Pollo',4,'Preparazione: 15 minuti. Cottura: 25 minuti.','1 Pollo Giovane Di 1000 G Già Pulito,
150 G Olive Nere,
80 G Capperi Sotto Sale,
10 Cl Vino Bianco Secco,
2 Cucchiai Olio D''oliva Extra-vergine,
3 Spicchi Aglio,
1 Dado,
30 G Burro,
Origano Essiccato,
Sale,
Pepe','Dissalate i capperi sotto l''acqua corrente. Asciugateli e metteteli da parte. Sbucciate gli spicchi d''aglio, scolate le olive, snocciolatele con l''apposito attrezzo e tritatene grossolanamente la metà insieme con l''aglio. Pulite bene il pollo, togliete la pelle e tagliatelo a pezzi. Sistematelo in una pirofila, aggiungete 2 cucchiai d''olio, il trito di olive e aglio, le olive intere e i capperi dissalati. Mescolate bene e cuocete nel forno a microonde per 10'' a potenza massima. Togliete la pirofila dal forno, profumate il pollo con l''origano, bagnate con il vino bianco e aggiungete 1 dado sbriciolato. Salate, pepate, girate i pezzi di pollo e cuocete altri 10'' a potenza massima. Grigliate 3-5 minuti e lasciate riposare 5 minuti prima di servire.',2297);
INSERT INTO "ricette" VALUES (19282,'Pollo Alle Olive Nere','Pollame','Pollo',4,' -','1 Pollo Di 1000 G,
100 G Olive Nere,
50 G Burro,
2 Cucchiai Olio D''oliva,
1 Bicchiere Vino Bianco,
Brodo,
Pepe,
Sale','Tagliare a pezzi il pollo e cuocerlo a fuoco vivo con olio, burro, pepe e sale. Se necessario unire un po'' di brodo di dado. Quando sarà ben cotto (1 ora circa), toglierlo dal fondo di cottura, unire le olive e il vino. Cuocere fino all''evaporazione del vino, coprire con questo intingolo il pollo e servire.',2308);
INSERT INTO "ricette" VALUES (19283,'Pollo Alle Prugne E Albicocche','Pollame','Pollo',4,' -','1 Pollo Tagliato In 8 Pezzi,
Sale,
Pepe,
1 G Zafferano,
12 Cucchiaini Curcuma,
1 Cucchiaino Cannella,
2 Cipolle Grandi,
9 Cucchiai Olio D''oliva Extra-vergine,
200 G Prugne Secche Snocciolate,
200 G Albicocche Secche,
1 Cucchiaio Miele,
80 G Mandorle','Mettete il pollo in una casseruola ampia e alta con sale, pepe, 
lo zafferano sbriciolato, la curcuma, metà della cannella e le cipolle tritate grossolanamente. Versate 4 cucchiai di olio e 3 mestoli di acqua calda e fate cuocere a fiamma bassa per 45 minuti. Unite quindi la frutta secca, il resto della cannella in polvere, il miele, un altro mestolo dacqua, se necessario, e lasciate cuocere per altri 15-20 minuti. A fine cottura, unite le mandorle prima rosolate in 3 cucchiai di olio, regolate di sale e servite il pollo con riso.',4771);
INSERT INTO "ricette" VALUES (19284,'Pollo Alle Spezie','Pollame','Pollo',6,'Luogo: India.','1500 G Pollo,
100 G Burro,
500 G Riso,
1 Cipolla,
1 Manciata Mandorle Sbucciate,
1 Cucchiaino Cumino,
3 Chiodi Di Garofano,
Cannella,
Zenzero,
Zafferano,
Noce Moscata,
Pepe Nero,
Yogurth Magro Naturale','Fate bollire il riso e scolatelo. Pulite il pollo e tagliatelo in almeno 10 pezzi. Spezzettate le mandorle nel mixer con un cucchiaino d''acqua. Passate al mixer anche zenzero, cipolla e sale, ottenendo una pasta dove passare il pollo. Cuocete il pollo in una casseruola, bagnandolo con un bicchiere d''acqua, per 10 minuti. Toglietelo, tenendolo in caldo e aggiungendo al fondo di cottura lo yogurth e la pasta di mandorle. In un''altra casseruola fate sciogliere il burro e aggiungete i pezzi di pollo aromatizzati nella pasta insieme a chiodi di garofano, grani di pepe nero e cannella tritati fini. Fate insaporire mescolando per dieci minuti. Unite riso, salsa di yogurth e zafferano, cuocete piano coperto per 5 minuti. Mettete in forno a 200 gradi per circa 30 minuti.',4605);
INSERT INTO "ricette" VALUES (19285,'Pollo Alle Spezie (2)','Pollame','Pollo',4,'Luogo: Libano.','6 Cipolle Grandi,
1 Pagnotta Pane,
25 Cl Olio Per Friggere,
1 Pollo,
Sale,
Pepe,
Spezie','Pulite il pollo e tagliatelo in 4-6 pezzi. Tagliate una cipolla in piccoli pezzi. Fate soffriggere la cipolla in una pentola in cui avrete versato un filo d''olio. Aggiungetevi il pollo, il sale, il pepe e tutte le spezie. Coprite con acqua e fate cuocere finché la carne diventa tenera. Tagliate quattro cipolle in pezzi medi. Fatele friggere fino a farle diventare dorate. Quando il pollo è cotto, scolatelo dall''acqua di cottura e mettetelo in una teglia aggiungendo una cipolla tagliata. Fatelo scaldare in forno. Nel frattempo preparate il pane su cui adagerete il pollo pronto per essere servito. Tagliate il pane in fette e sfregatele con le cipolle fritte. Quindi, posatevi il pollo e servite.',5588);
INSERT INTO "ricette" VALUES (19286,'Pollo Alle Spezie Delicato','Pollame','Pollo',6,' -','1 Pollo Di 1600 G,
1 Cipolla,
2 Spicchi D''aglio,
Sale,
1/2 Cucchiaino Curcuma In Polvere,
1 Rametto Erba Cedrata,
4 Cucchiai Olio Di Semi Di Soia,
50 Cl Brodo Di Pollo,
2 Pomodori,
150 G Zucca Sott''olio,
2 Cucchiai Foglioline Di Coriandolo Tritate','Pulite il pollo, lavatelo sotto l''acqua corrente e asciugatelo, quindi dividetelo a pezzetti e riducete questi in piccoli bocconcini. Tritate la cipolla e l''aglio, poi frullateli insieme al sale, alla curcuma, all''erba cedrata e a due cucchiai d''olio. Fate scaldare il resto del condimento nel wok, unite il composto aromatico e fatelo soffriggere per 2-3 minuti, mescolando continuamente. A questo punto versate nel recipiente il brodo di pollo, unite la carne e fate cuocere, a calore moderato, per 20 minuti, senza mai smettere di mescolare. Tagliate a dadini i pomodori e la zucca, uniteli al pollo e fate cuocere per altri 30 minuti. Al termine, cospargete la preparazione con le foglioline di coriandolo e servite. --- CONSIGLI. Si tratta di una ricetta di pollo alle spezie originaria del Burma. Contrariamente a quanto si potrebbe pensare, si tratta di un piatto molto delicato, in quanto il sapore piccante delle spezie, usate con molta parsimonia, viene attenuato dalla polpa dolciastra dei pomodori e della zucca.',2815);
INSERT INTO "ricette" VALUES (19287,'Pollo Alle Verdure','Pollame','Pollo',4,' -','4 Petti Di Pollo Divisi A Metà,
2 Zucchine Tagliate A Rondelle,
1 Peperone A Pezzetti,
12 Cl Aceto Di Vino,
150 G Pomodori Pelati,
1 Cucchiaio Olio D''oliva,
1 Cipolla A Fettine,
1 Cucchiaio Zucchero,
2 Spicchi Aglio,
1 Cucchiaino Origano,
1 Cucchiaino Pepe','Battere delicatamente i petti di pollo e tagliarli in quattro grosse strisce. Metterle in una casseruola con le zucchine e il peperoncino. Unire l''aceto e gli altri ingredienti e far riposare in bicchiere. Coprire e agitare bene. Mettere la salsina sul pollo e sulle verdure. Coprire, marinare e far riposare per un''ora. Versare di nuovo la salsina in una padella antiaderente. Far bollire per un minuto. Infilzare negli spiedini di legno, un pezzetto di verdura e un pezzetto di pollo e bagnare nella salsina. Far cuocere ancora per dieci minuti, unendo la marinata.',1599);
INSERT INTO "ricette" VALUES (19288,'Pollo Alle Verdure (2)','Pollame','Pollo',4,' -','1 Pollo,
200 G Carote,
200 G Cipolle,
150 G Zucchine,
150 G Pomodori,
20 G Uvetta Sultanina,
1 Peperoncino Rosso,
Olio D''oliva,
Sale,
Pepe','Tagliate il pollo a pezzi e mettetelo in una padella con olio, sale, pepe e peperoncino. Tagliate a pezzi le carote, le cipolle, le zucchine e i pomodori e aggiungeteli al pollo. Fate cuocere per 1 ora. A 15 minuti dalla fine della cottura aggiungete l''uvetta, che avrete lasciato macerare per 1 ora in acqua calda.',2574);
INSERT INTO "ricette" VALUES (19289,'Pollo Allo Speck','Pollame','Pollo',4,' -','4 Petti Di Pollo,
100 G Speck,
1 Cipolla,
1 Bicchierino Brandy,
Olio D''oliva,
Burro,
Sale,
Brodo','Soffriggere in poco olio la cipolla affettata al velo e lo speck tagliato a dadini. Bagnare con il brandy e farlo evaporare. Aggiungere un mestolo abbondante di brodo e cuocere per 15 minuti a fuoco basso. A parte rosolare i petti di pollo in olio e burro, salarli e servirli irrorati con la salsa allo speck.',2760);
INSERT INTO "ricette" VALUES (19290,'Pollo Allo Spiedo','Pollame','Pollo',4,' -','1 Pollo,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Ripiegate le ali sul dorso, salate e pepate il pollo dentro e fuori, spennellatelo bene d''olio e infilzatelo nello spiedo del forno che farete girare lentamente. Durante la cottura, occorrono dai 35 ai 50 minuti a seconda del peso, bagnate ogni tanto il pollo con il sugo colato nella leccarda sottostante. Se invece del forno a gas o elettrico usate quello a raggi infrarossi, ricordate che non occorre ungere il pollo, perché il volatile cuoce usufruendo soltanto del proprio grasso. Appena tolto il pollo dallo spiedo spolverizzatelo con il sale e un po'' di pepe e servitelo ben caldo con un contorno d''insalatina verde o di patate novelle al rosmarino cotte in teglia. Vini di accompagnamento: Barbera D''Asti Superiore DOC, Chianti Classico DOCG, Castel Del Monte Rosso DOC.',2762);
INSERT INTO "ricette" VALUES (19291,'Pollo Allo Yogurth','Pollame','Pollo',4,' -','1 Pollo Da 1200 G,
25 G Burro,
1 Cipolla,
2 Cucchiai Farina,
2 Cucchiai Olio D''oliva,
2 Cucchiaini Paprica Dolce,
1 Vasetto Yogurth,
Sale','Pulire il pollo, lavarlo, tagliarlo a pezzi e asciugarlo. Mescolare 1 cucchiaino di paprica e una presa di sale alla farina. Infarinare il pollo. Soffriggere la cipolla tritata in olio e burro, unire i pezzi di pollo e far rosolare per 10 minuti girando spesso. Unire 1 bicchiere d''acqua e infornare a 180 gradi coperto per 45 minuti. Togliere il pollo dalla teglia e aggiungere yogurth e paprica al fondo di cottura, rimettere sul fuoco, far restringere e versare sul pollo.',2129);
INSERT INTO "ricette" VALUES (19292,'Pollo Allo Yogurth (2)','Pollame','Pollo',4,' -','2 Petti Di Pollo,
2 Scalogni,
125 G Yogurth Bianco Non Compatto,
Poco Olio D''oliva,
Erba Cipollina,
Sale','Tritare finemente lo scalogno, fatelo imbiondire in poco olio poi aggiungete i petti di pollo tagliati a fettine. Aggiustate di sale, bagnate con un po'' di vino bianco e lasciate cuocere per una quindicina di minuti. Tritate l''erba cipollina e mescolatela allo yogurth prima di versarlo sul pollo. Lasciate insaporire pochi minuti e servite ben caldo.',1141);
INSERT INTO "ricette" VALUES (19293,'Pollo Allo Yogurth (3)','Pollame','Pollo',4,' -','1 Pollo Novello,
1 Vasetto Yogurth,
1 Spicchio Aglio,
60 G Burro,
Poco Latte,
Peperoncino,
1/2 Limone (succo),
1 Presa Sale,
Prezzemolo Tritato','Preparare una marinata con lo yogurth, poco latte, l''aglio tritato, il peperoncino in polvere, il succo del 1/2 limone e una presa di sale. Tagliare a pezzi il pollo e coprirlo con la marinata. Lasciarlo riposare circa 2 ore. Fondere 40 g di burro in un tegame e unirvi il pollo con tutta la marinata. Cuocere a fuoco basso, coperto per circa 40 minuti. Prima di levare dal fuoco unire il resto del burro, il prezzemolo e mescolare bene.',1700);
INSERT INTO "ricette" VALUES (19294,'Pollo Allo Zafferano','Pollame','Pollo',4,'Luogo: Abruzzo.','1 Pollo,
60 G Burro,
2 Cucchiai Olio D''oliva,
1 Tazza Brodo Di Dado,
1 Bicchierino Cognac,
1/2 Cucchiaino Zafferano,
1 Manciata Prezzemolo Fresco,
Vino Bianco,
Panna,
1 Spolverata Farina,
Sale','Rosolate il pollo a pezzi in un tegame insieme all''olio ed il burro. Aggiungete il vino e il cognac, continuate la cottura ed aggiungete poco alla volta il brodo, lasciandone un po'' da parte. A cottura ultimata, togliete i pezzi di pollo e teneteli al caldo su un piatto da portata. Intanto aggiungete al fondo di cottura il brodo rimasto, una spolverata di farina, la panna e lo zafferano. Miscelare bene fino ad ottenere una crema che andrete a mettere sul pollo già cotto. Spolverizzate una manciata di prezzemolo fresco e servire.',2969);
INSERT INTO "ricette" VALUES (19295,'Pollo Allo Zenzero','Pollame','Pollo',4,' -','1 Petto Di Pollo Di 450 G Già Pulito,
8 Cucchiaini Shoyu (salsa Di Soia),
2 Cucchiaini Zenzero Grattugiato Fresco,
1 Cucchiaino Cannella,
Aglio,
Olio D''oliva Extra-vergine,
Sale','Tagliare il petto di pollo a cubetti e metterli in una terrina; unirvi 1 spicchio d''aglio schiacciato. Cospargerli di cannella, zenzero, sale e irrorare con lo shoyu. Far marinare per 2 ore. Spennellare con olio una pirofila, disporvi il pollo e versarvi la marinata. Cuocere in forno a 180 gradi per circa 35 minuti finché il sugo sia quasi tutto asciugato.',1921);
INSERT INTO "ricette" VALUES (19296,'Pollo Arrosto','Pollame','Pollo',4,' -','1 Pollo,
1 Rametto Rosmarino,
1 Cipolla,
1 Carota,
1 Costa Sedano,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Pepate e salate un po'' il pollo all''interno, legatelo con uno spago bianco da cucina sottile. In un tegame scaldate l''olio, unite cipolla, carota, sedano e rosmarino tritati, e quando il composto ha preso colore adagiatevi il pollo e fatelo rosolare a fuoco vivace per un quarto d''ora. Salate, coprite e cuocete a fuoco basso per 40-50 minuti. Se necessario, bagnatelo con poca acqua calda. A cottura ultimata (bucando con una forchetta non deve uscire sangue o liquido rosato) eliminate lo spago, tagliate il pollo e servitelo caldo con carote al burro. Vini di accompagnamento: Valpolicella Superiore DOC, Chianti Dei Colli Fiorentini DOCG, Cirò Classico DOC.',3183);
INSERT INTO "ricette" VALUES (19297,'Pollo Arrosto Alla Francese','Pollame','Pollo',4,'Luogo: Francia.','1 Pollo,
500 G Patate','Mettete in una pirofila il pollo con un po'' di acqua. Fatelo arrostire girandolo e innaffiandolo spesso con acqua. La cottura sarà ultimata quando mettendo una forchetta nella carne non ne uscirà più sangue. Nel frattempo friggete le patate. Servitelo circondato di patate fritte.',2130);
INSERT INTO "ricette" VALUES (19298,'Pollo Arrosto Con Datteri E Riso','Pollame','Pollo',4,' -','1 Pollo Di 1400 G Pronto Per La Cottura,
Sale,
1 Pizzico Pepe Di Caienna,
1 Pizzico Pimento,
2 Cucchiaini Paprica Piccante,
120 G Cipolle,
1 Spicchio Aglio,
50 Cl Brodo Di Pollo,
100 G Sedano,
4 Cucchiai Olio D''oliva,
250 G Pomodori,
1 Cucchiaio Prezzemolo Tritato,
3 Tazze Riso Bollito,
6 Datteri Freschi','Tagliate il pollo in otto pezzi e cospargeteli uniformemente con il sale, la paprica, il pimento e il pepe di Caienna, precedentemente mescolati in una ciotolina. Tritate finemente le cipolle sbucciate, lo spicchio d''aglio e il sedano, e fate soffriggere il tutto in una padella con l''olio, a calore moderato per 5 minuti. Unite i pezzi di pollo e fateli rosolare a fuoco vivo da ogni lato, fino a quando saranno ben dorati. Scottate per pochi istanti i pomodori in acqua bollente, pelateli, eliminate i semi e tagliate la polpa a filetti, quindi metteteli nella padella con la carne. Private i datteri dei noccioli, riducetene la polpa a striscioline e unite anch''essa alla carne. Fate cuocere a calore moderato per 15 minuti, mescolando continuamente con un cucchiaio di legno. Trascorso il tempo indicato versate il brodo e proseguite la cottura nel forno (200 gradi) per 20 minuti, dopodichè unite il riso e il prezzemolo tritato e portate a cottura (occorreranno altri 20-30 minuti). Al termine regolate di sale e pepe, se necessario, e servite ben caldo.',5285);
INSERT INTO "ricette" VALUES (19299,'Pollo Arrosto Con Olive','Pollame','Pollo',6,' -','1 Pollo,
1 Manciata Olive Verdi In Salamoia,
3