Primo','Spinaci Lessati',4,' -','200 G Farina,
2 Uova,
100 G Spinaci Lessati,
1 Pizzico Sale','Disponete la farina a fontana, sgusciatevi nel mezzo le uova, aggiungete un pizzico di sale e gli spinaci tritati. Lavorate il composto per alcuni minuti. Se l''umido degli spinaci richiede altra farina, aggiungetene poca alla volta. Lasciate riposare la pasta un quarto d''ora e poi tiratela a sfoglia non tanto sottile. Questa pasta può essere utilizzata per lasagne, tagliatelle, tortellini, ravioli. Le tagliatelle verdi mescolate con un po'' di quelle all''uovo si chiamano ''paglia e fieno''. I condimenti più adatti sono quelli classici, ragù, burro e formaggio, sugo d''arrosto.',850);
INSERT INTO "ricette" VALUES (17601,'Pasta Viennese','Dessert','Burro',4,'Luogo: Austria. Luogo: Vienna.','100 G Zucchero Semolato,
50 G Burro Freschissimo,
50 G Farina Bianca 00,
50 G Fecola Di Patate,
2 Uova Intere,
2 Tuorli D''uovo,
1/2 Limone','Prendete due ciotole di differente misura: io quella più grande versate dell''acqua ben calda, ponete in essa la seconda ciotola e in questa mettete le uova intere ed i tuorli, lo zucchero, la scorza grattugiata di mezzo limone. Sbattete il composto con una frusta sollevando di tanto in tanto la ciotola dall''acqua, sostituendo questa, una sola volta, con altra acqua caldissima. Quando il composto sarà divenuto ben gonfio levate la piccola ciotola dall''acqua e proseguite la lavorazione sino ad avere la massa quasi fredda. Incorporatevi allora, con un cucchiaio di legno. la farina e la fecola fatte cadere insieme da un setaccio e per ultimo unite il burro fuso e tiepido, mescolando sempre dopo ogni aggiunta, procedendo dall''alto verso il basso e viceversa e non in senso rotatorio. Imburrate ed infarinate una tortiera del diametro di cm 24 e versatevi l''impasto, scuotendo lo stampo sul tavolo affinché il composto si sistemi bene. Passatelo in forno già caldo (180 gradi) lasciandovelo per circa 30 minuti; infilate quindi nella pasta uno stecchino di legno e se uscirà asciutto sformate la ''viennese'' sopra una gratella da pasticceria coperta da un canovaccio rivoltandola subito. Lasciatela raffreddare, poi tagliatela in 3 dischi di eguale spessore, pennellate ognuno con un buon liquore e farciteli con ''crema pasticciera''. Decorate la parte superiore con dei cerchi di panna montata intervallata da altri cerchi di crema: alla fine segnate otto porzioni mettendo su ognuna una ciliegina al Maraschino e una fogliolina di menta. Conservate la torta in frigorifero (massimo 4-5 ore) sino al momento di servire.',1512);
INSERT INTO "ricette" VALUES (17602,'Pasta Zucchine E Prosciutto Cotto','Primo','Prosciutto Cotto',4,' -','Olio D''oliva Extra-vergine,
Zucchine,
Prosciutto Cotto,
Aglio,
Pasta Tipo Qualsiasi,
1 Uovo,
1 Pizzico Sale','Prendere un tegame, versare un po'' d''olio ed 1 spicchio d''aglio e far soffrigere leggermente. Togliere l''aglio ed aggiungere le zucchine tagliate a rondelle cuocere per 20 minuti, Verso fine cottura aggiungere il prosciutto cotto sminuzzato e 1 uovo. Rigirare il tutto durante la cottura facendo rompere l''uovo in tanti pezzettini, aggiungere un pizzico di sale e la pasta appena scolata e mantecare il tutto nella stessa padella usata per il sugo.',2261);
INSERT INTO "ricette" VALUES (17603,'Pasta, Patate E Sedano','Primo','Patate',4,' -','200 G Pasta Tipo Ditalini,
1000 G Patate,
2 Cuori Sedano,
50 G Pancetta,
1 Carota,
1 Cucchiaio Concentrato Di Pomodoro,
Formaggio Grattugiato,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Tritate una carota e due cuori di sedano, insaporiteli in una casseruola con tre cucchiai d''olio. Aggiungete la pancetta a dadini, mescolate. Unite le patate a cubetti e versate nel recipiente un litro d''acqua calda. Coprite e cuocete mezz''ora. Insaporite con un cucchiaio di concentrato di pomodoro, sale e pepe. Aggiungete acqua se occorre, mettete la pasta e portate a cottura. Servite con formaggio grattugiato a parte.',3302);
INSERT INTO "ricette" VALUES (17604,'Pastasciutta Alla Crema','Primo','Mascarpone',4,' -','350 G Pasta Tipo Penne Rigate,
50 G Burro,
100 G Ricotta,
100 G Mascarpone,
100 G Prosciutto Cotto,
Sale,
Pepe','Mettete il burro ammorbidito in una terrina, unite la ricotta, il mascarpone, sale e pepe. Sbattete con una frusta fino a ottenere una crema morbida. Unite il prosciutto tritato. Fate cuocere la pasta in acqua salata, scolatela e conditela con la crema.',2555);
INSERT INTO "ricette" VALUES (17605,'Pastasciutta Alla Passata Di Pomodoro','Primo','Pomodoro',4,' -','400 G Pasta Tipo Penne,
Passato Di Pomodoro,
Origano,
Formaggio Parmigiano Grattugiato,
Olio D''oliva','Ponete in una terrina il passato di pomodoro (quanto basta), salate e pepate. Aggiungete l''origano e l''olio d''oliva crudo. Amalgamate con la forchetta. Cuocete la pasta in acqua salata, poi versatela nel sugo cospargendo abbondantemente di formaggio.',2445);
INSERT INTO "ricette" VALUES (17606,'Pastasciutta Coi Porri','Primo','Porri',4,' -','Pasta Tipo Pasta Corta,
Porri,
Olio D''oliva,
Sale,
Pepe Bianco','Tagliare i porri a fettine di circa mezzo cm. di spessore e metterli a cuocere nell''acqua della pasta portata a ebollizione. Dopo circa 5 minuti buttare la pasta e farla cuocere. Scolare il tutto e condire con olio e pepe bianco a piacere. Nota: abbondare coi porri!',1771);
INSERT INTO "ricette" VALUES (17607,'Pastasciutta Con La Pentola A Pressione','Primo','Pomodori Pelati',4,'Preparazione: 10 minuti.','Pasta Tipo Pasta Corta,
Pomodori Pelati,
2 Dadi,
Origano,
Burro,
Olio D''oliva,
Sale,
Peperoncino','Mettete nella pentola a pressione tutti gli ingredienti alla rinfusa, acqua, pasta, pelati, meglio ancora pomodori a pezzi, olio, burro, mezzo dado a testa, sale, origano, peperoncino. L''unica cosa da rispettare rigorosamente è il rapporto fra pasta e acqua che deve essere circa 160 g di acqua per ogni 100 g di pasta. Tenete presente che se ne fate una sola porzione occorre aggiungere altri 40 g di acqua per fare vapore, e che i pelati buttano fuori anche loro un po'' d''acqua. Mescolate bene, facendo attenzione che la pasta sia coperta dall''acqua, tappate e portate al fischio. A questo punto abbassate un po'' la fiamma, cronometrate la metà del tempo di cottura indicato sulla confezione, poi spegnete e sfiatate. Stappate la pentola e nel caso fosse rimasta un po'' d''acqua nel fondo fatela asciugare a fuoco vivo mescolando bene. Aggiungete ancora un po'' di origano e servite.',2539);
INSERT INTO "ricette" VALUES (17608,'Pastasciutta Con Le Erbe','Primo','Erbe Miste',4,' -','Pasta Tipo Penne,
Erbe Miste (insalata Rucola, Basilico, Menta),
2 Spicchi Aglio,
Poco Pomodoro In Scatola A Pezzetti','Come pasta vanno bene penne o qualcosa del genere. Fai un trito abbondante di tutte le erbe che riesci a trovare, prezzemolo, rucola, basilico come base, poi menta, erba cipollina se le trovi, due foglie di salvia, un pochino di rosmarino ecc. Tutto quello che è verde va bene. Aggiungi un paio di spicchi d''aglio spremuti. Con l''aglio abbonda pure, si deve sentire il piccante, ma guarda che deve essere crudo e spremuto con l''apposito attrezzino. Una volta scolata la pasta, la fai scaldare un attimo in pentola con quel trito lì e poco pomodoro in scatola a pezzetti (non passata). Il condimento non deve cuocere, solo scaldarsi.',1029);
INSERT INTO "ricette" VALUES (17609,'Pastasciutta Con Tonno E Olive','Primo','Tonno',4,' -','Pasta Tipo Spaghetti,
Olive Nere,
Prezzemolo,
Tonno,
1 Goccio Olio D''oliva,
Poco Pangrattato','Ci vedo meglio gli spaghetti. Trita olive nere e un po'' di prezzemolo, aggiungi tonno, un goccio d''olio d''oliva e un po'' di pangrattato. Anche qui il sugo non si cuoce, ci fai saltare un momento la pasta prima di servire.',1525);
INSERT INTO "ricette" VALUES (17610,'Pastasciutta Notturna','Primo','Tonno Sott''olio',4,' -','350 G Pasta Tipo Pasta Corta,
200 G Besciamella,
200 G Panna,
150 G Tonno Sott''olio,
2 Cucchiai Pasta Di Olive,
2 Cucchiai Olio D''oliva,
1 Pizzico Peperoncino Rosso (facoltativo),
1 Pizzico Noce Moscata (facoltativo)','Mentre cuoce la pasta, far soffriggere in una padella larga il tonno con l''olio e la pasta d''olive. Quando il tutto sarà ben rosolato e sminuzzato aggiungere la besciamella e la panna; far cuocere ancora alcuni minuti aggiungendo a piacere un pizzico di peperoncino rosso o di noce moscata. Scolare la pasta al dente nella padella e condire facendo saltare sul fuoco.',2975);
INSERT INTO "ricette" VALUES (17611,'Pastasciutta Panarea','Primo','Aglio',4,' -','Pomodori,
Pasta Tipo Pasta Corta,
3 Spicchi Aglio,
Abbondante Basilico Fresco,
Olio D''oliva Extra-vergine','Tagliate i pomodori a pezzi, sbucciate e tagliate a metà l''aglio, metteteli in una zuppiera insieme al basilico spezzato a mano e condite il tutto con l''olio. Lasciate insaporire per 15 minuti. Cuocete intanto la pasta in abbondante acqua salata e scolatela. Mettetela nella zuppiera con i pomodori, mescolate e servite.',1766);
INSERT INTO "ricette" VALUES (17612,'Pastatelle','Dessert','Marmellata Di Ciliegie',4,'Luogo: Puglia.','1000 G Pasta Frolla,
500 G Marmellata Di Ciliegie,
100 G Gherigli Di Noci,
Scorza D''arancia,
1 Cucchiaio Zucchero,
Cannella','Amalgamate la marmellata, le noci tritate, la scorza d''arancia e un po'' di cannella. Dividete la pasta frolla e create delle palle. Stendetele col mattarello. Ricavate dei dischetti nel centro dei quali ponete un cucchiaio del composto di marmellata. Chiudete ogni dischetto ottenendo una mezza luna. Ponete le pastatelle in una teglia e cospargetele di zucchero. Cuocete in forno a 200 gradi per 30 minuti.',6129);
INSERT INTO "ricette" VALUES (17613,'Pastatelle (2)','Dessert','Marmellata D''uva',4,'Luogo: Puglia.','1000 G Pasta Frolla,
500 G Marmellata D''uva,
100 G Gherigli Di Noci,
Scorza D''arancia,
1 Cucchiaio Zucchero,
Cannella','Amalgamate la marmellata, le noci tritate, la scorza d''arancia e un po'' di cannella. Dividete la pasta frolla e create delle palle. Stendetele col mattarello. Ricavate dei dischetti nel centro dei quali ponete un cucchiaio del composto di marmellata. Chiudete ogni dischetto ottenendo una mezza luna. Ponete le pastatelle in una teglia e cospargetele di zucchero. Cuocete in forno a 200 gradi per 30 minuti.',6129);
INSERT INTO "ricette" VALUES (17614,'Paste Di Mandorle','Dessert','Farina Di Mandorle',4,'Luogo: Basilicata.','800 G Zucchero,
3 Bicchieri Acqua,
800 G Farina Di Mandorle,
100 G Farina Di Maiorca,
1/2 Bustina Vaniglia','Sciogliere a fuoco basso lo zucchero con i 3 bicchieri d''acqua. Quando comincerà a filare, togliere il tegame dal fuoco. Aggiungere la farina di mandorle, la farina di maiorca, la vaniglia e mescolare fino a quando la pasta si staccherà tutta insieme dal tegame. Versare l''impasto su un tavolo di marmo bagnato. Appena si sarà freddato, lavorarlo a lungo con le mani. Quandò sarà liscio e compatto, sistemarlo negli stampi e decorare a piacere.',6075);
INSERT INTO "ricette" VALUES (17615,'Paste Di Meliga','Dessert','Burro',6,'Luogo: Piemonte. Luogo: Alba. Preparazione: 30 minuti. Cottura: 30 minuti.','600 G Farina Di Meliga (farina Di Mais),
150 G Burro,
150 G Zucchero,
6 Tuorli D''uovo,
1 Limone (scorza Grattugiata),
Sale,
Olio D''oliva','Fate fondere a fiamma bassissima il burro; unite la farina gialla, lo zucchero, i tuorli d''uovo, il limone grattugiato, un pizzico di sale ed eventualmente qualche cucchiaio di olio d''oliva onde ottenere un composto fluido, che esca senza difficoltà dalla tasca da pasticciere. Depositate il composto in barrette di 6-7 centimetri, a forma di esse, sul fondo di una teglia da forno imburrata ed infarinata. Ponete in forno già caldo a 180 gradi per 20-30 minuti. Servite le paste di meliga fredde. Vino consigliato: Barolo d''annata.',5207);
INSERT INTO "ricette" VALUES (17616,'Pasteis De Bacalau','Pesce','Baccalà',4,'Luogo: Portogallo.','350 G Baccalà,
3 Uova,
Noce Moscata,
Olio Per Friggere,
500 G Patate,
1 Cucchiaio Prezzemolo Tritato,
Sale,
Pepe Macinato Fresco','Bagnare il pesce per togliere il sale di conservazione. Cuocerlo in acqua salata insieme con le patate sbucciate. Togliere la pelle dal pesce e con delicatezza rimuovere le lische. Mettere polpa di pesce e patate in un macinacarne e unire alla poltiglia ottenuta i tuorli d''uovo, il prezzemolo, la noce moscata, il pepe e il sale. Intanto impastate. Quando l''impasto è omogeneo, aggiungere gli albumi montati a neve. Formare delle polpette non tanto grandi e tuffatele in olio bollente per 1 o 2 minuti. Abbassare il fuoco e friggere per altri 5 minuti. Alzare ancora il fuoco, togliere le crocchette e mettere sul fuoco le polpettine ancora da friggere. Servite con riso al pomodoro, insalata o come anti- pasto o come snack.',1892);
INSERT INTO "ricette" VALUES (17617,'Pastella Per Crepes (ricetta Base)','Antipasto','Uova',12,' -','100 G Farina,
2 Uova Intere,
25 Cl Latte,
30 G Burro,
Olio D''oliva,
Sale','In una terrina mettete la farina a fontana, al centro sgusciatevi le uova, unite tre o quattro cucchiai di latte e mescolate per amalgamare il tutto. Diluite il composto versando lentamente a filo il restante latte fino a ottenere un impasto alquanto fluido. Aggiungete il burro lasciato sciogliere a bagnomaria e poi fatto quasi raffreddare. Salate, lavorate ancora per alcuni minuti con una piccola frusta e fate riposare la pastella per almeno un''ora. Al momento di cuocere le crepes, ungete appena il fondo di un padellino con olio o burro, lasciate scaldare, versatevi due cucchiai di pastella, muovete il padellino perché il composto si spanda su tutto il fondo e cuocete da entrambi i lati. Così di seguito. In caso di crepes dolci si sostituisce il sale con lo zucchero',1555);
INSERT INTO "ricette" VALUES (17618,'Pastella Per Friggere','Dessert','Vino Bianco',4,' -','150 G Farina,
1 Uovo,
1/2 Bicchiere Vino Bianco,
2 Cucchiai Grappa,
1 Pizzico Sale','In una grande ciotola mettete la farina, il vino e la grappa, aggiungete un pizzico di sale, mescolate. Incorporatevi il tuorlo. La pastella deve riuscire abbastanza densa, ma fluida. Lasciatela riposare per mezz''ora, incorporatevi delicatamente l''albume montato a neve. Passate velocemente nella pastella gli ingredienti da friggere e fateli dorare nell''olio bollente. Toglieteli con la paletta forata e passateli su carta assorbente.',828);
INSERT INTO "ricette" VALUES (17619,'Pastella Per Friggere Al Vino Bianco','Salsa','Vino Bianco',4,' -','150 G Farina,
2 Tuorli D''uovo,
12 Cl Vino Bianco,
1 Cucchiaio Olio D''oliva,
Sale,
2 Albumi D''uovo','Ponete in una terrina la farina, i tuorli, il vino bianco, l''olio e una presa di sale e lavorate il tutto con una frusta fino ad ottenere un impasto liscio e omogeneo, che lascerete riposare per 20 minuti. In una ciotola montate a neve ben ferma gli albumi con un pizzico di sale, quindi uniteli alla pastella. Potete preparare una versione dolce di questa pastella incorporando agli albumi montati 30 g di zucchero.',1171);
INSERT INTO "ricette" VALUES (17620,'Pastella Per Friggere All''acqua Minerale','Salsa','Acqua Minerale',4,' -','250 G Farina,
2 Uova Intere,
2 Albumi D''uovo,
Sale,
20 Cl Acqua Minerale Gassata','Setacciate la farina in una terrina, aggiungetevi l''acqua minerale, le uova e una presa di sale e mescolate fino ad ottenere un impasto omogeneo. Coprite la terrina con uno strofinaccio da cucina e fate riposare l''impasto per 15-20 minuti. Trascorso questo tempo mescolate ancora una volta energicamente, poi passate il composto attraverso un setaccio sottile per eliminare eventuali grumi di farina. Un attimo prima di friggere, incorporate all''impasto gli albumi montati a neve non troppo soda. Aggiungete gli albumi poco alla volta, in modo da poter controllare la consistenza della pastella: se diventa troppo liquida, si disfa cuocendo.',1115);
INSERT INTO "ricette" VALUES (17621,'Pastella Per Friggere Alla Birra','Salsa','Birra Chiara',4,' -','250 G Farina,
2 Uova,
20 Cl Birra Chiara,
Sale,
2 Albumi D''uovo','Setacciate la farina in una terrina, aggiungetevi la birra, le uova e una presa di sale e mescolate fino ad ottenere un impasto omogeneo. Coprite la terrina con uno strofinaccio da cucina e fate lievitare l''impasto per 15-20 minuti. Trascorso questo tempo mescolate ancora una volta energicamente, poi passate il composto attraverso un setaccio sottile per eliminare eventuali grumi di farina. Un attimo prima di friggere, incorporate all''impasto gli albumi montati a neve non troppo soda. Aggiungete gli albumi poco alla volta, in modo da poter controllare la consistenza della pastella: se diventa troppo liquida, si disfa cuocendo.',1103);
INSERT INTO "ricette" VALUES (17622,'Pastella Per Frutta Affettata','Dessert','Birra Chiara',4,' -','250 G Farina Bianca,
250 G Acqua,
2 Cucchiai Burro Fuso,
2 Albumi D''uovo,
15 Cl Birra Chiara,
Sale','Mettete in una capace ciotola, per poter lavorare bene l''impasto, la farina setacciata, 5 g di sale fino e il burro tiepido: mescolate bene e diluite con la birra e con l''acqua tiepida, senza lavorare troppo il composto e badando di non fare grumi. Lasciatelo riposare per un''ora e poi unite i due albumi montati in neve ben soda, incorporandoli delicatamente. Questo tipo di pastella è molto leggero; serve per circa 1500 g di frutta.',1498);
INSERT INTO "ricette" VALUES (17623,'Pastella Per Frutta Da Caramellare','Dessert','Birra Chiara',4,' -','250 G Farina Bianca,
25 Cl Acqua,
2 Cucchiai Burro Fuso,
1 Uovo,
15 Cl Birra Chiara,
Zucchero Semolato,
Sale,
Brandy,
Frutta (mele O Pere O Banane O Ananas)','Versate in una ciotola la farina setacciata, unite 5 g di sale, il burro tiepido e una cucchiaiata di Brandy, aggiungete poi un pizzicone di zucchero, l''uovo intero sbattuto con una forchetta la birra chiara e l''acqua tiepida. Lasciate fermentare per qualche ora la pastella in luogo caldo e al momento di usarla mescolatela bene. Le frutta adatte per essere fritte sono: fettine di mela, di pera, di banana, di ananas e frutta sciroppata bene asciugata. Dopo aver fritto le frutta mettetele su una placca, cospargetele di zucchero semolato e passatele in forno caldo (220 gradi) lasciandole caramellare leggermente per e non oltre 10 minuti. Questo tipo di pastella è buono e leggero, serve per 1500 g circa di frutta.',1929);
INSERT INTO "ricette" VALUES (17624,'Pastella Per Tempura','Salsa','Uova',4,'Preparazione: 5 minuti.','2 Uova Grandi,
75 G Farina','Rompete le uova in un recipiente di medie dimensioni con 20 cl di acqua fredda e sbattete finché la miscela è ben amalgamata. Aggiungete la farina, senza setacciarla, e sbattete (se possibile con i bastoncini) finché la preparazione è appena mescolata. Fate attenzione a non sbattere troppo.',446);
INSERT INTO "ricette" VALUES (17625,'Pasticcini Al Cocco Con Nutella','Dessert','Nutella',6,' -','150 G Cioccolato Fondente,
90 G Burro,
2 Uova,
200 G Zucchero,
200 G Noce Di Cocco Secca,
Nutella','Le dosi sono per 60 pasticcini. Fate fondere il cioccolato in un pentolino e spalmatelo su una placca rivestita di alluminio. Fate raffreddare per circa mezz''ora in frigo perché indurisca. Mescolate il burro fuso e raffreddato con le uova, poi incorporate il cocco grattugiato e lo zucchero: continuate a mescolare energicamente per 15 secondi. Spalmate il composto sul cioccolato indurito sulla placca e cuocete in forno preriscaldato a 180 gradi per circa 20 minuti, poi sfornate e fate raffreddare per 4 ore. Capovolgete il dolce su un piano da lavoro, togliete l''alluminio e dopo aver tagliato circa 60 quadratini rivestiteli di Nutella fusa.',3535);
INSERT INTO "ricette" VALUES (17626,'Pasticcini Al Tartufo','Dessert','Tartufo',4,'Luogo: Piemonte.','Per La Pasta:,
100 G Farina,
1 Tuorlo D''uovo,
35 G Burro Ammorbidito,
1 Cucchiaio Latte,
Per Il Ripieno:,
60 G Tartufo Nero,
15 G Burro,
15 G Olio D''oliva,
1 Spicchio Aglio,
1/2 Cucchiaio Prezzemolo Tritato,
5 G Formaggio Parmigiano Grattugiato,
1 Limone (succo)','Versare la farina in una ciotola, aggiungere il tuorlo d''uovo, il burro, il latte, e un pizzico di sale. Mescolare fino ad ottenere una pasta liscia. Lasciare l''impasto riposare in un posto fresco per almeno un''ora. Portare la temperatura del forno a 220 gradi. Tagliare il tartufo in finissime striscioline. Riscaldare il burro e l''olio in una padella, se è possibile su carbonella ardente, e imbiondire l''aglio. Rimuovere l''aglio e gettarlo. Cuocere le striscioline di tartufo nell''olio e il burro. Aggiungere il prezzemolo tritato, il Parmigiano grattugiato, e il succo di limone. Cuocere per 10 minuti, poi lasciar freddare il tartufo. Imburrare 4 terrine. Stendere la pasta e dividerla in 8 pezzi. Mettere uno strato di impasto in ogni terrina e riempirle con il pasticcio di tartufo. Coprire ogni terrina con un disco di impasto e cuocere in forno per 20 minuti. I pasticcini devono poi essere coperti con un po'' di fonduta piemontese e leggermente gratinati. Servirli caldi con alcune striscioline di tartufo bianco, se disponibile, coperti dalla fonduta. Vino: Arneis dei Roeri (Piedmont),1-2 anni o Gavi dei Gavi (Piedmont), 2-4 anni.',1005);
INSERT INTO "ricette" VALUES (17627,'Pasticcini Alla Noce Di Cocco','Dessert','Noce Di Cocco',4,' -','Zucchero,
Albumi D''uovo,
Sale,
Noci Di Cocco,
Olio D''oliva','Unire lo zucchero con gli albumi non battuti e il sale. Porre a bagnomaria e girare spesso finché lo zucchero sarà sciolto. Aggiungere quindi la polpa di noce di cocco e amalgamare bene. Ungere la placca da forno di olio e disporvi, allineandole e distanziandole, piccole quantità del composto. Cuocere a 180 gradi fino a doratura.',1154);
INSERT INTO "ricette" VALUES (17628,'Pasticcini Alla Noce Di Cocco (2)','Dessert','Polpa Di Noce Di Cocco Fresca',4,' -','300 G Polpa Di Noce Di Cocco Fresca Grattugiata,
300 G Zucchero In Polvere,
6 Albumi D''uovo,
1 Pizzico Sale,
Olio D''oliva Per La Placca Da Forno','Unire lo zucchero con gli albumi non battuti e il sale. Porre a bagnomaria e girare spesso finché lo zucchero sarà sciolto. Aggiungere quindi la polpa di noce di cocco e amalgamare bene. Ungere la placca da forno di olio e disporvi, allineandole e distanziandole, piccole quantità del composto. Cuocere a 180 gradi fino a doratura.',3078);
INSERT INTO "ricette" VALUES (17629,'Pasticcini Alla Siciliana Con Nutella','Dessert','Nutella',4,'Luogo: Sicilia.','3 Tuorli D''uovo,
3 Cucchiai Zucchero,
2 Cucchiai Cacao In Polvere,
Alcune Gocce Essenza Di Vaniglia,
3 Albumi D''uovo,
Nutella','Accendete il forno a 180 gradi, imburrate ed infarinate il fondo e le pareti di una placca di cm 30 x 20. Battete i tuorli con lo zucchero fino ad ottenere un composto spumoso e incorporatevi il cacao setacciato, la vaniglia e gli albumi mondati a neve. Versate il composto nella placca, lisciate la superficie e cuocetelo in forno per 10-15 minuti finché non si sarà rassodato, quindi fatelo raffreddare per 10 minuti e capovolgete il dolce su carta da forno. Lasciate raffreddare ancora completamente. Tagliate il dolce a metà, spalmate con la Nutella parte di esso e copritelo con l''altra, spolverizzate con il cacao e tagliate 20 fette. Mettete in frigorifero per due ore prima di servire.',936);
INSERT INTO "ricette" VALUES (17630,'Pasticcini Alle Mandorle','Dessert','Mandorle Sgusciate',4,' -','200 G Farina,
100 G Zucchero,
2 Tuorli D''uovo,
100 G Burro,
Per La Crema:,
3 Uova Intere,
1 Tuorlo D''uovo,
100 G Zucchero,
1/2 Bicchiere Latte,
50 G Mandorle Sgusciate,
1 Cucchiaino Brandy','Fate la pasta mescolando la farina, lo zucchero, il burro sciolto e i tuorli. Lasciate riposare per 15 minuti e poi riempiteci dei piccoli stampi imburrati. Fate la crema frullando bene le uova, il tuorlo, lo zucchero, il latte e il brandy; aggiungete poi mezzo cucchiaio di questa crema in ogni tortina. Tagliate a fettine le mandorle, mettetele in forno per 3 minuti e disponetele sopra le tortine. Mettete tutto in forno per 20 minuti. e quando saranno cotte lasciate riposare per mezza giornata.',3167);
INSERT INTO "ricette" VALUES (17631,'Pasticcini Di Castagne','Dessert','Castagne',6,'Preparazione: 90 minuti.','500 G Castagne Lessate E Pelate,
80 G Burro Freschissimo Morbido,
80 G Polvere Di Biscotti,
50 G Cioccolato Fondente Amaro,
50 G Zucchero A Velo,
24 Pinoli,
6 Cucchiai Liquore Amaretto Di Saronno','Le dosi sono per 24 pasticcini. Passate le castagne dal passaverdure con il disco medio. Tagliuzzate il cioccolato e fatelo sciogliere a bagnomaria poi incorporatelo alle castagne; aggiungete anche il burro ammorbidito ed a pezzetti. Unite lo zucchero a velo fatto cadere a pioggia da un setaccino e, una per volta, sei cucchiaiate di liquore, mescolando sempre con energia. Alla fine dovrete ottenere un composto morbido ma non troppo; mettetelo in una tasca di tela munita di grossa bocchetta rotonda spizzata e deponetene un ciuffo in 24 pirottini dove prima avrete distribuito la polvere di biscotto. Decorateli con un pinolo copriteli con pellicola trasparente e passateli in frigorifero per almeno un''ora; sono ottimi e si conservano benissimo per due o tre giorni. Potete servire questi ''pasticcini'' all''ora del tè.',3064);
INSERT INTO "ricette" VALUES (17632,'Pasticcini Gallesi','Antipasto','Formaggio Fontina',4,'Luogo: Regno Unito. Luogo: Galles.','1 Confezione Pasta Sfoglia,
150 G Formaggio Fontina (20 Pezzetti),
Farina Per La Spianatoia,
Burro Per La Placca','Imburrare la placca del forno. Scongelare la pasta e stenderla con il mattarello in una sfoglia di circa 3 mm di spessore. Ricavare 20 dischi, su ognuno formare un bordo lungo il suo perimetro, disporli sulla placca e passarli in forno già caldo a 180 gradi. Appena iniziano a colorire mettere su ogni disco un pezzetto di formaggio e portare a termine la cottura. Servirli caldi.',2256);
INSERT INTO "ricette" VALUES (17633,'Pasticcini Gallesi (2)','Antipasto','Formaggio Cheddar',4,'Luogo: Regno Unito. Luogo: Galles.','Pasta Sfoglia,
150 G Formaggio Cheddar In Pezzetti,
Per La Placca:,
Farina,
Burro','Imburrare la placca del forno. Scongelare la pasta e stenderla con il mattarello in una sfoglia di circa 3 mm di spessore. Ricavare 20 dischi, su ognuno formare un bordo lungo il suo perimetro, disporli sulla placca e passarli in forno già caldo a 180 gradi. Appena iniziano a colorire mettere su ogni disco un pezzetto di formaggio e portare a termine la cottura. Servirli caldi.',1968);
INSERT INTO "ricette" VALUES (17634,'Pasticcini Gallesi (3)','Dessert','Formaggio Cheddar',4,'Luogo: Regno Unito. Luogo: Galles.','500 G Pasta Sfoglia,
150 G Formaggio Cheddar Tagliato In Pezzetti,
Farina,
Burro','Imburrare la placca del forno. Scongelare la pasta e stenderla con il matterello in una sfoglia di circa 3 mm di spessore. Ricavare 20 dischi, su ognuno formare un bordo lungo il suo perimetro, disporli sulla placca e passarli in forno già caldo a 180 gradi. Appena iniziano a colorire mettere su ogni disco un pezzetto di formaggio e portare a termine la cottura. Servirli caldi.',3372);
INSERT INTO "ricette" VALUES (17635,'Pasticcini Gallesi (4)','Dessert','Formaggio Fontina',4,'Luogo: Regno Unito. Luogo: Galles.','500 G Pasta Sfoglia,
150 G Formaggio Fontina Tagliato In Pezzetti,
Farina,
Burro','Imburrare la placca del forno. Scongelare la pasta e stenderla con il matterello in una sfoglia di circa 3 mm di spessore. Ricavare 20 dischi, su ognuno formare un bordo lungo il suo perimetro, disporli sulla placca e passarli in forno già caldo a 180 gradi. Appena iniziano a colorire mettere su ogni disco un pezzetto di formaggio e portare a termine la cottura. Servirli caldi.',3372);
INSERT INTO "ricette" VALUES (17636,'Pasticcini Glassati','Dessert','Glassa',4,' -','125 G Farina,
4 Uova,
125 G Zucchero,
80 G Burro,
Alcuni Confettini Colorati,
Alcuni Fiorellini Di Zucchero,
300 G Marmellata Di Albicocche,
1 Cucchiaio Succo Di Limone,
2 Cucchiai Acqua,
400 G Glassa','Sgusciate le uova in una terrina, unite lo zucchero e sbattete i due ingredienti servendovi di una frusta o di uno sbattitore elettrico. Appena il composto assume un aspetto omogeneo, trasferite la terrina in un bagnomaria di acqua in leggera ebollizione e continuate a sbattere fino a quando diventerà denso e chiaro: occorreranno circa 20 minuti se usate la frusta, 10 minuti se impiegate uno sbattitore elettrico. Al termine, togliete la terrina dal bagnomaria e continuate a sbattere il composto fino a quando si sarà raffreddato, quindi unite la farina setacciata, poca alla volta, alternandola a 60 g di burro fuso e tiepido. Quando avrete incorporato tutti gli ingredienti, trasferite l''impasto in una teglia rettangolare (36x20 cm), già foderata con un foglio di carta oleata unto col resto del burro e passatelo nel forno già caldo (180 gradi) per 20-25 minuti. Trascorso questo tempo, togliete la teglia dal forno, lasciate intiepidire leggermente il pan di Spagna, quindi sformatelo su una griglia, eliminate la carta oleata e fatelo raffreddare completamente. A questo punto, tagliate a metà il pan di Spagna in senso orizzontale, stendete sullo strato di base la marmellata di albicocche, già mescolata con l''acqua e il succo di limone, e copritela con il secondo strato di pasta. Ricavate dal dolce tanti pasticcini di forme diverse, tagliandolo con delle fustelle sagomate. Per la fase finale di glassatura scegliete una glassa a piacere e usatela per ricoprire i pasticcini, prendendo spunto dalle immagini qui riprodotte. A tale proposito vi saranno utili tasche di tela con bocchette piccole e medie variamente sagomate, confettini colorati, scaglie di cioccolato, pralina di nocciole, canditi, ecc. Per comodità, ricordiamo qui quali sono le glasse che potete utilizzare: glassa di albicocche, glassa al cioccolato, glassa fondente, meringa, glassa all''albume o reale, glassa al cioccolato per piccole decorazioni e crema al burro (vedi ricette omonime).',4841);
INSERT INTO "ricette" VALUES (17637,'Pasticcini Glassati Rosa','Dessert','Pan Di Spagna',4,' -','1 Pan Di Spagna,
350 G Zucchero A Velo,
40 G Zucchero,
80 G Burro,
1 Tuorlo D''uovo,
Sciroppo Di Amarene','Tagliate il pan di Spagna orizzontalmente a metà, ricavate dai due dischi tanti tondini. In un pentolino tenuto a bagnomaria lavorate il burro con 60 g di zucchero a velo e il tuorlo; insaporite la crema con tre cucchiai di sciroppo. Spalmate con la crema metà dischetti e ricopriteli con le altre metà. Mescolate lo zucchero semolato con un decilitro d''acqua, ponete sul fuoco e fate restringere lo sciroppo; lasciatelo intiepidire e incorporate lo zucchero a velo in modo da ottenere una glassa densa, coloratela con lo sciroppo di amarene e spalmatela sui pasticcini. Fate asciugare.',4532);
INSERT INTO "ricette" VALUES (17638,'Pasticcini Mandorlati','Dessert','Mandorle',6,' -','300 G Mandorle Macinate,
300 G Zucchero A Velo,
4 Albumi D''uovo,
1 Bustina Vaniglina,
Alcune Ciliegine Candite,
Alcune Mandorle Spellate,
Alcuni Pistacchi Interi Spellati','Mescolare le mandorle con lo zucchero e la vaniglina e amalgamarvi un po'' alla volta gli albumi non montati e tenuti a temperatura ambiente. Mettere il composto ottenuto nella tasca per dolci con la bocchetta a stella e allineare sulla placca, rivestita di carta forno, i pasticcini a forma di anello, di rosetta o di s. Scaldare il forno a 200 gradi. Decorare ogni pasticcino con 1/2 ciliegina, 1 mandorla o 1 pistacchio e cuocerli in forno per 15 minuti.',3388);
INSERT INTO "ricette" VALUES (17639,'Pasticcini Salati Alla Frutta','Antipasto','Formaggio Robiola',10,'Preparazione: 60 minuti. Calorie: 281.','Per La Pasta Brisée:,
200 G Farina Bianca,
100 G Burro,
1 Tuorlo D''uovo,
1 Pizzico Sale,
Per Farcire:,
350 G Formaggio Robiola,
60 G Latte,
1 Pizzico Salsa Worcester,
1 Pizzico Sale,
Per Decorare:,
Frutta Fresca Mista (kiwi, Fragole, Uva)','Preparate la pasta brisèe: intridete il burro con la farina poi versate il tutto sulla spianatoia e fate la fontana. Al centro mettete il tuorlo, 70 g d''acqua fredda e un pizzichino di sale. Impastate velocemente per non riscaldare troppo il burro, poi fate con la pasta una palla, avvolgetela nella pellicola trasparente e lasciatela riposare al fresco per circa 30 minuti. Trascorso questo tempo mettete la pasta sulla spianatoia e tiratela, con il matterello, in una sfoglia dello spessore di mm 2. Usando un tagliapasta rotondo a bordo scanalato di 7 cm di diametro, ritagliate 30 dischi con i quali rivestirete altrettanti stampini per tartellette. Sistemateli su una o più placche e passateli nel forno già a 180 gradi per circa 10 minuti, poi sfornate, sformate le tartellette e lasciatele raffreddare. Se non avete stampini a sufficienza, fate l''operazione in 2 o 3 volte. Intanto preparate la farcia. In una ciotola lavorate la robiola stemperandola con il latte. Insaporitela con un pizzico di Worcester e con un pizzico di sale. Mondate quindi la frutta: sbucciate un kiwi e tagliatene metà in dadolata. Sgranate un grappoletto d''uva bianca, risciacquate i chicchi e poneteli ad asciugare su un canovaccio o su un doppio foglio di carta da cucina: private una decina di fragole del picciolo e passatele rapidamente sotto l''acqua corrente ponendole quindi a sgocciolare accanto all''uva. Mettete il composto al formaggio in una tasca di tela da pasticcere munita di bocchetta liscia, quindi distribuitela tra i "pasticcini" freddi. Guarniteli con pezzetti della frutta preparata e con i chicchi d''uva. Serviteli subito, ben disposti su un piatto da portata adeguato, oppure teneteli in frigorifero, fino al momento di portarli in tavola. In ogni caso, non preparateli con un anticipo superiore all''ora, perché la pasta si inumidirebbe, diventando molliccia. Potrete invece fare i pasticcini il giorno prima e farcirli solamente al momento di servirli, con il ripieno preparato di fresco.',2773);
INSERT INTO "ricette" VALUES (17640,'Pasticcio Con Verdure','Antipasto','Peperoni Rossi',4,'Luogo: Brasile. Preparazione: 20 minuti. Cottura: 25 minuti.','800 G Filetti Di Pesce (o Tranci Di Pesce),
2 Peperoni Rossi,
2 Cipolle,
2 Limoni,
2 Pomodori Maturi,
2 Spicchi Aglio,
Alcuni Rametti Coriandolo (o Menta),
1 Tazza Olio Di Palma,
10 Cl Latte Di Cocco Denso,
Sale','Mondate i peperoni. Frullate un peperone e un pomodoro con una cipolla tagliata a pezzi, l''aglio sbucciato e il coriandolo tritato. Tagliate un peperone, un pomodoro e una cipolla a rondelle. Versate metà del frullato in una padella antiaderente a bordi alti. Sistematevi sopra i filetti di pesce e coprite con il resto. Lasciate riposare per mezz''ora. Distribuite nella padella le verdure a rondelle e metà dell''olio. Salate leggermente. Cuocete il tutto a fuoco moderato per 20 minuti con un coperchio. Trascorso questo tempo, versate nella padella l''olio rimasto, il latte di cocco e il succo dei limoni. Proseguite la cottura per altri 5 minuti, scuotendo una o due volte la padella per amalgamare bene il pesce e le verdure. Servite con riso basmati lessato o polenta di mais.',2475);
INSERT INTO "ricette" VALUES (17641,'Pasticcio Del Norcino','Primo','Cotiche Di Maiale',4,'Luogo: Umbria. Luogo: Norcia.','Pasta Tipo Tagliatelle,
Pasta Di Salsicce,
Prosciutto Cotto A Fette,
Cotiche Di Maiale,
3 Uova Sode,
Piselli,
Funghi,
Formaggio Parmigiano Grattugiato,
Noce Moscata,
Carota,
Cipolla,
1 Costa Sedano,
Pomodori Maturi,
Olio D''oliva,
Pangrattato,
Sale,
Pepe','Preparare una salsa di pomodoro con le verdure; scottare i piselli, le cotiche, ammollare i funghi. Cuocere le tagliatelle al dente e disporle su una pirofila con il fondo ricoperto da fette di prosciutto. Condirle con la salsa e ricoprire con dei rotolini di pasta di salsiccia, le uova sode ed i funghi; condire con il parmigiano e ricoprire con fette di prosciutto passando al forno.',5717);
INSERT INTO "ricette" VALUES (17642,'Pasticcio Di Asparagi','Contorno','Asparagi',4,' -','1000 G Asparagi,
5 G Burro,
1 Tazza Besciamella,
Sale,
Pepe,
50 G Formaggio Parmigiano Grattugiato,
100 G Mozzarella,
100 Cl Latte','Pulite gli asparagi eliminando la parte bianca troppo legnosa, legateli a mazzetti e lessateli al dente. Quando saranno cotti tamponateli con uno strofinaccio per togliere l''eccesso d''acqua e metteteli in una pirofila precedentemente imburrata. Copriteli con la mozzarella affettata, il parmigiano e dei pezzettini di burro. Versatevi sopra il latte. In ultimo ricoprite il tutto con la besciamella. Infornate a 200 gradi fino a quando la superficie sarà gratinata.',1341);
INSERT INTO "ricette" VALUES (17643,'Pasticcio Di Carne','Carne','Vitello',4,' -','400 G Fesa Di Vitello,
100 G Prosciutto Cotto,
1 Confezione Carciofi Findus,
70 G Burro,
Sale','Tagliare a fette la carne, appiattirla con il batticarne. Bollire per qualche minuto i carciofi a fette. Imburrare una pirofila e riempirla alternando strati di carciofi, carne e prosciutto. Cospargere ogni strato con fiocchi di burro e sale. Coprire la pirofila e cuocere in forno per 30-45 minuti. Scoprire nelle ultime fasi della cottura per far gratinare per bene il pasticcio.',1341);
INSERT INTO "ricette" VALUES (17644,'Pasticcio Di Carne (2)','Carne','Manzo',6,' -','500 G Carne Di Manzo In Fettine Sottili,
5 Patate,
2 Uova Sode,
Brodo,
200 G Farina,
100 G Burro,
Sale,
Pepe,
1 Confezione Pasta Sfoglia Surgelata','Imburrate una pirofila e disponete sul fondo le patate a rondelle, poi la carne salata e pepata e, infine, le uova sode a rondelle. Bagnate con un po'' di brodo, distribuite fiocchetti di burro. Inumidite il bordo della pirofila, coprite il pasticcio con la sfoglia tirata a 1 cm di spessore e premete i bordi. Bucherellate la superficie. Cuocete a 180 gradi un''ora.',4392);
INSERT INTO "ricette" VALUES (17645,'Pasticcio Di Carne (3)','Carne','Vitello',8,' -','4 Fette Larghe Carne Di Vitello Magro,
4 Fette Spesse Mortadella,
4 Fette Prosciutto Cotto,
4 Uova,
2 Cucchiai Formaggio Grattugiato,
Sale','Battete le fette di vitello allargandole bene. Stendete la prima fetta sul fondo di una casseruola un po'' fonda, deve starci di misura; cospargetela con un po'' di formaggio grattugiato e un pizzico di sale; sopra adagiatevi una fetta di mortadella e poi una di prosciutto cotto; coprite questo primo strato con un uovo sbattuto. Ripetete gli strati e terminate con una frittatina di un uovo. Cuocete a bagnomaria per 2 ore. Rovesciate il pasticcio che si staccherà facilmente. Appoggiatevi sopra un peso e lasciatelo così per circa un''ora. Scolate il liquido di consistenza gelatinosa che si è formato, servirà come guarnizione. Fate raffreddare il pasticcio in frigorifero. Potete servirlo anche il giorno dopo tagliato a fette trasversali. Vini di accompagnamento: Alto Adige Lagrein Rosato, Colli Piacentini Sauvignon DOC, Lizzano Rosato DOC.',2358);
INSERT INTO "ricette" VALUES (17646,'Pasticcio Di Carne (4)','Carne','Vitello',6,' -','500 G Fesa Di Vitello,
6 Carciofi,
150 G Prosciutto Cotto,
80 G Burro,
Succo Di Limone,
Pepe,
Sale','Affettare la carne e appiattirla col batticarne. Mondare i carciofi, tagliarli a fette larghe e farli bollire per pochi minuti in acqua acidulata con limone. Imburrare una pirofila e riempirla a strati con uno strato di carciofi, uno di carne e uno di prosciutto. Coprire ogni strato con fiocchetti di burro, sale e pepe. Cuocere coperto in forno caldo a 200 gradi per circa 40 minuti.',1801);
INSERT INTO "ricette" VALUES (17647,'Pasticcio Di Carne E Verdure','Carne','Vitello',4,' -','1/2 Bicchiere Olio D''oliva,
600 G Carne Macinata Di Vitello (o Di Maiale),
Sale,
Pepe,
Peperoni,
Melanzane,
Pomodori,
2 Spicchi Aglio,
1 Ciuffo Prezzemolo Tritato','Friggere in 1/2 bicchiere d''olio bollente 600 g di carne macinata (di vitello o maiale). Salare, pepare e disporla in una teglia da forno sopra uno strato di peperoni affettati. Coprire con uno strato di melanzane affettate e pomodori spezzettati. Soffriggere nell''olio di cottura della carne 2 spicchi d''aglio e 1 ciuffo di prezzemolo tritato e versare l''olio sul pasticcio. Passare la teglia in forno già caldo a 180 gradi per 40 minuti. Si serve tiepido.',1361);
INSERT INTO "ricette" VALUES (17648,'Pasticcio Di Chiodini E Uova','Contorno','Funghi Chiodini',4,' -','400 G Funghi Chiodini,
6 Uova,
1 Spicchio Aglio,
Prezzemolo Tritato,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Pulire molto bene i chiodini. Versare l''olio in 1 casseruola e farvi rosolare l''aglio, quindi unire i funghi; a fine cottura salare, pepare e unire il prezzemolo. Sbattere le uova in 1 terrina, unirvi i funghi cotti e versare il tutto in una padella ben unta. Lasciar cuocere il pasticcio a fuoco lento e girarlo appena rappreso; poi dopo averlo ben cotto da ambedue le parti, rovesciarlo su 1 piatto di portate e servire.',2125);
INSERT INTO "ricette" VALUES (17649,'Pasticcio Di Coniglio','Carne','Coniglio',4,' -','1 Coniglio A Pezzi,
6 Patate,
3 Spicchi Aglio,
Prezzemolo,
Sale,
Pepe,
Olio D''oliva','Sbucciare le patate e tagliarle a fette sottili. Lavare il coniglio, asciugarlo e strofinarlo con sale e pepe. In una teglia unta disporre uno strato di patate e uno di coniglio. Cospargere con un trito di aglio e prezzemolo. Ricoprire con altre fette di patate. Emulsionare 6 cucchiai di olio con 6 di acqua e versare sul pasticcio. Salare e pepare. Cuocere in forno caldo a 180 gradi per circa 90 minuti.',3561);
INSERT INTO "ricette" VALUES (17650,'Pasticcio Di Coste','Carne','Maiale',4,' -','1500 G Coste Di Maiale,
Sale,
Burro,
Formaggio Grana Grattugiato,
Prosciutto Cotto,
Formaggio Fondente','Pulire il bianco delle coste e farlo lessare per 20 minuti, in acqua salata. In una teglia imburrata fare uno strato di coste, uno di grana grattugiato, uno di prosciutto cotto e uno di fette di formaggio fondente. Continuare ad alternare gli strati, finendo con le coste cosparse con molto grana e fiocchetti di burro. Infornare a 200 gradi per 20 minuti.',4797);
INSERT INTO "ricette" VALUES (17651,'Pasticcio Di Erbette','Contorno','Zucchine',4,'Preparazione: 105 minuti.','700 G Zucchine,
200 G Erbette,
10 Fiori Di Zucca,
2 Uova,
40 G Pancetta Tesa (fette Di 40 G),
50 G Riso,
40 G Formaggio Parrnigiano Grattugiato,
Olio D''oliva Extra-vergine,
1 Cipolla,
1 Spicchio Aglio,
1 Cucchiaio Basilico Tagliuzzato,
Sale,
Pepe','Lessate le zucchine intere in acqua salata per 30 minuti. Lessate a parte anche il riso in acqua salata per 10 minuti, poi scolatelo e passatelo sotto l''acqua corrente in modo da raffreddarlo. Tagliate la pancetta a cubetti, private i fiori di zucca dei pistilli e spezzettateli, poi rosolate l''aglio e la cipolla, tritati finemente, in un tegame con 2 cucchiai d''olio. Scolate quindi le zucchine e lasciatele raffreddare, poi spuntatele, spremetele per eliminare l''acqua, quindi passatele al passaverdura. Aggiungete alla purea ottenuta le erbette, finemente tritate, il soffritto, il basilico, la pancetta, i fiori, il parmigiano, il riso e le uova, sbattute prima con sale e pepe, quindi regolate di sale e pepate a piacere. Versate il composto ottenuto in una pirofila oliata, livellandone la superficie con una spatola, poi cuocetelo in forno caldo a 180 gradi per 45 minuti. Portate quindi la temperatura del forno a 200 gradi e cuocete ancora per 10 minuti. Servite il pasticcio caldo o freddo. Per un tocco in più, provate a sostituire le erbette con 400 g di zucca affettata, cotta al vapore o lessata e poi tagliata a pezzetti.',1629);
INSERT INTO "ricette" VALUES (17652,'Pasticcio Di Fagiano','Primo','Fagiano',6,' -','350 G Pasta Sfoglia Congelata,
1/2 Fagiano,
200 G Fegatini Di Pollo,
150 G Polpa Di Maiale,
10 Cl Panna,
50 G Burro,
1 Tuorlo D''uovo,
1 Bicchierino Vino Marsala,
1/2 Bicchierino Brandy,
2 Spicchi Aglio,
2 Foglie Alloro,
Olio D''oliva,
Sale,
Pepe','Rosolate in metà burro i fegatini con gli spicchi d''aglio e le foglie d''alloro interi. Unitevi la carne sfilettata del fagiano e quella di maiale tagliata a piccoli pezzi. Salate, pepate e cuocete a fuoco moderato per un quarto d''ora. Irrorate con un bicchierino di Marsala e mezzo di brandy, lasciate evaporare. A fine cottura eliminate l''aglio e le foglie d''alloro. Frullate la carne aggiungendo poco alla volta la panna e una noce di burro sciolto prima a bagnomaria. Tirate la pasta scongelata in una sfoglia sottile, rivestite gli stampini individuali imburrati. Riempiteli con il pasticcio di fagiano e ricoprite con un altro dischetto di sfoglia, sigillando bene i bordi. Praticate un foro al centro di ogni tortina e con i rebbi di una forchetta disegnate dei raggi tutt''intorno. Spennellate la superficie con il tuorlo leggermente sbattuto. Cuocete in forno preriscaldato a 180 gradi per circa un quarto d''ora. Ritirate, lasciate riposare 5 minuti, sformate e servite. Vini di accompagnamento: Vintage Tunina IGT Del Friuli, Cabreo La Pietra IGT Di Toscana, Marchese Di Villa Marina Bianco IGT Di Sardegna.',4737);
INSERT INTO "ricette" VALUES (17653,'Pasticcio Di Finocchi','Contorno','Finocchi',4,'Preparazione: 60 minuti.','4 Finocchi Grandi,
50 G Cubetti Di Prosciutto Cotto,
200 G Formaggio Roquefort (o Formaggio Gorgonzola Stagionato),
30 G Gherigli Di Noci,
50 G Farina,
50 Cl Latte,
50 G Burro,
Noce Moscata,
Sale,
Per La Teglia:,
Burro','Mondate i finocchi, tagliateli in 8 spicchi e cuoceteli a vapore per circa 20 minuti. Fate sciogliere in una casseruola, il burro a fiamma dolce, poi unite la farina, setacciata, e lasciatela tostare per un minuto. Aggiungete quindi il latte a filo e, sempre mescolando in modo da evitare la formazione di grumi, cuocete fino a ottenere una besciamella densa. Salate e profumate con noce moscata a piacere. Unite poi il formaggio tagliato a pezzetti e continuate a mescolare finché si sarà sciolto. Imburrate una larga pirofila e disponetevi i finocchi in un solo strato. Distribuitevi sopra i gherigli di noci spezzettati, metà cubetti di prosciutto, la besciamella preparata e infine il prosciutto rimasto. Cuocete la preparazione in forno già caldo a 180 gradi per 20 minuti circa. Servite subito.',2822);
INSERT INTO "ricette" VALUES (17654,'Pasticcio Di Lenticchie','Primo','Lenticchie',4,' -','500 G Lenticchie,
300 G Patate,
1 Cipolla,
50 G Burro,
Salvia,
Alloro,
Sale,
Pepe','Tenere le lenticchie a bagno per 12 ore. Scolare e lessarle con alloro e salvia finché saranno tenere. Passarle al passaverdure. Lessare le patate e passarle. Mescolare lenticchie e patate. Soffriggere la cipolla tritata nel burro, versarvi il composto e farlo insaporire, mescolando, per 15 minuti. Aggiustare di sale e pepare. Mettere il tutto in una pirofila imburrata e infornare a 200 gradi per 30 minuti.',2182);
INSERT INTO "ricette" VALUES (17655,'Pasticcio Di Maccheroni','Primo','Ragù Di Carne',4,' -','400 G Pasta Tipo Maccheroni Di Semola Di Grano Duro,
1 Pasta Sfoglia Surgelata Da 350 G,
1 Tazza Ragù Di Carne,
100 G Burro,
6 Cucchiai Farina,
8 Cucchiai Latte,
1 Manciata Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
1 Noce Moscata','Preparare una tazza di besciamella con 100 g di burro, 6 cucchiai di farina e 8 di latte, unitevi 1 manciata di parmigiano grattugiato, sale, pepe, e una noce moscata. Preparate ora il ragù di carne a piacere o usate un vasetto di ragù già pronto. Lessate al dente i maccheroni. Stendete la sfoglia e foderate una teglia imburrata, anche a forma quadrata. Disponete uno strato di pasta, uno di besciamella, uno di pasta e uno di ragù e proseguite in questo modo fino a finire la besciamella. Chiudete la sfoglia in modo da coprire bene tutta la preparazione. Quando manca mezz''ora ad andare a tavola accendere il forno a 200 gradi, e passatevi il recipiente, cuocete e servite subito: se volete potrete capovolgere il pasticcio sul piatto di portata. Si taglia a fette in tavola.',4324);
INSERT INTO "ricette" VALUES (17656,'Pasticcio Di Maccheroni Ai Funghi','Primo','Funghi',4,' -','400 G Pasta Tipo Maccheroni,
100 G Formaggio Emmenthal,
100 G Formaggio Parmigiano Grattugiato,
200 G Funghi,
1 Spicchio Aglio,
Prezzemolo,
Besciamella,
Olio D''oliva Extra-vergine,
Burro,
Sale,
Pepe','Mondate i funghi, affettateli e stufateli in un po'' di olio fatto precedentemente insaporire con lo spicchio di aglio schiacciato; una volta cotti togliete l''aglio e condite con sale, pepe e prezzemolo finemente tritato. Amalgamate la besciamella all''emmenthal tagliato a dadini e a due cucchiai dei funghi precedentemente preparati. Lessate la pasta in acqua salata, scolatela bene al dente e conditela con i funghi, quindi disponetela a strati in una teglia da forno alternandola con la besciamella e parmigiano grattugiato. Terminate con besciamella, parmigiano e qualche fiocchetto di burro; passate a cuocere in forno caldo per 15 minuti.',3753);
INSERT INTO "ricette" VALUES (17657,'Pasticcio Di Maiale Con Bacon E Patate','Carne','Maiale',4,' -','8 Fette Bacon,
300 G Patate,
40 G Burro,
1/2 Cipolla,
1 Cucchiaio Farina,
2 Uova,
1/2 Bicchiere Latte,
Sale,
Pepe','Riunite in una grande ciotola il bacon e la cipolla grossolanamente tritati. Aggiungete le patate tagliate a fiammifero, cospargete di farina e mescolate. Sbattete le uova, salatele, pepatele, diluitele con il latte e versate il tutto nella ciotola del bacon amalgamando in modo da ottenere un morbido impasto. In una teglia fate fondere il burro e quando è dorato versatevi il composto. Pareggiate la superficie e rigatela con i rebbi di una forchetta. Cuocete in forno a 200 gradi per circa 45 minuti. Tagliate il pasticcio a fettine e servite caldo. Vini di accompagnamento: Alto Adige Santa Maddalena DOC, Bolgheri Rosato DOC, Alezio Rosato DOC.',5483);
INSERT INTO "ricette" VALUES (17658,'Pasticcio Di Manzo Con Pancetta E Patate','Carne','Manzo',4,' -','700 G Bollito Di Manzo Tagliato A Fette,
100 G Pancetta Affumicata A Fettine,
4 Patate Lesse,
Olio D''oliva,
6 Pomodorini,
Origano,
Brodo,
Sale,
Pepe','Ungere con olio 1 pirofila, poi fare un primo strato con il manzo, disporvi sopra le fette di pancetta e ricoprire il tutto con qualche fetta di patata e qualche filetto di pomodoro. Irrorare con 1 filo d''olio e spolverizzare con sale, pepe e origano. Continuare così fino ad esaurimento degli ingredienti, terminando con le fette di patate. Unire un po'' di brodo caldo e passare in forno già caldo a 180 gradi per 15 minuti.',2784);
INSERT INTO "ricette" VALUES (17659,'Pasticcio Di Melanzane','Contorno','Melanzane',4,' -','1000 G Melanzane,
Farina,
2 Uova,
Olio D''oliva,
200 G Mozzarella,
Origano,
Sale','Lavate le melanzane, asciugatele con della carta assorbente e tagliatele a fette rotonde con uno spessore di circa 1 cm. A parte, in un recipiente, sbattete le uova aggiungendo un pizzico di sale e dopo aver infarinato le fette immergetele nell''uovo. In una padella antiaderente lasciate riscaldare l''olio e quando sarà ben caldo, friggete le melanzane da entrambi i lati fino a quando non si saranno dorate. Subito dopo, affettate la mozzarella e ungete il fondo di una teglia d''olio. Preparate un primo strato di melanzane e un secondo strato di mozzarella che spolverizzerete con l''origano e sale. Continuate così fino a quando gli ingredienti a disposizione saranno terminati e chiudete l''ultimo strato con le melanzane e l''origano rimasto. Salate e condite con un altro goccino d''olio e lasciate cuocere in forno preriscaldato per 15 minuti a 250 gradi. Servite caldo.',1825);
INSERT INTO "ricette" VALUES (17660,'Pasticcio Di Pasta Di Zucca','Primo','Zucca Cotta',4,' -','300 G Farina,
200 G Zucca Cotta,
50 G Funghi Secchi,
25 Cl Besciamella,
1 Uovo,
50 G Burro,
1/2 Scalogno,
1/2 Carota,
Sale,
Pepe','Mettete a bagno i funghi in acqua fredda. Nel frattempo, in un tegame, fate appassire lo scalogno e mezza carota tritati con metà burro, aggiungete i funghi strizzati e tritati. Coprite, portate a cottura, amalgamateli alla besciamella. Intanto frullate la zucca con un pizzico di sale, mescolatela con la farina, legate con l''uovo, lavorate la pasta velocemente e tiratela a sfoglia piuttosto sottile. Ricavatene 10-12 rettangoli, lessateli in acqua a bollore salata, sgocciolateli. Imburrate una pirofila e disponetevi i rettangoli di pasta alternandoli con la besciamella ai funghi e passate in forno caldo alcuni minuti. Vini di accompagnamento: Colli Berici Sauvignon DOC, Frascati Superiore DOC, Castel Del Monte Sauvignon DOC.',1855);
INSERT INTO "ricette" VALUES (17661,'Pasticcio Di Pasta E Pesce','Primo','Pesce Affumicato',4,' -','200 G Pasta Tipo Maccheroni,
400 G Pesce Affumicato,
2 Cucchiai Burro,
1 Cucchiaio Farina,
1 Limone,
1 Cucchiaio Pangrattato,
Sale','Cuocete la pasta e tritate il pesce. Prendete una pirofila e imburratela; riempitela a strati alternati di pesce e pasta. Preparate una salsa con la farina, il burro, un po'' di acqua, il succo di limone e il sale. Versatela sul pasticcio e poi cospargete il tutto di pangrattato e noci di burro. Cuocete in forno per 15 minuti.',1885);
INSERT INTO "ricette" VALUES (17662,'Pasticcio Di Patate','Contorno','Patate',4,' -','800 G Patate,
2 Uova,
1 Bicchiere Latte,
3 Cucchiai Formaggio Parmigiano Grattugiato,
Olio D''oliva,
150 G Mozzarella,
Prezzemolo Tritato,
Sale,
Pepe,
Burro,
Pangrattato','Sciacquate con molta cura le patate, lessatele con la buccia, lasciatele intiepidire, sbucciatele e passatele nello schiacciapatate. Versate in una pentola capiente il latte, e quando sarà caldo, aggiungete la purea ottenuta amalgamando a fuoco dolce per evitare che si formino eventuali grumi. Successivamente, unite i tuorli, il parmigiano grattugiato, l''olio d''oliva, la mozzarella tagliata a cubetti, il prezzemolo tritato (precedentemente sciacquato e asciugato con carta assorbente), il sale, il pepe, e in ultimo gli albumi montati a neve e mescolate fino ad ottenere un composto omogeneo e cremoso. Per finire, imburrate una pirofila, spolverizzatela con del pangrattato e versate il pasticcio livellandolo con una spatola. Dopodichè, spolverizzate con altro pangrattato e cospargete qualche ricciolo di burro. Cuocete in forno già caldo per circa 30 minuti a 250 gradi controllando di tanto in tanto la cottura.',3368);
INSERT INTO "ricette" VALUES (17663,'Pasticcio Di Patate E Cipolle','Contorno','Patate',6,' -','900 G Patate,
500 G Cipolle,
Rosmarino,
Burro,
1 Filo Olio D''oliva,
Sale,
Pepe','Sbucciate le patate e tagliatele a dischetti, pelate le cipolle e affettatele a rondelle. Imburrate una pirofila, fate un primo strato di patate, salate, pepate, aggiungete un po'' di rosmarino tritato e un filo d''olio. Fate un secondo strato di cipolle, salate, pepate, unite il rosmarino e un po'' d''olio. Continuate così a strati fino a esaurimento degli ingredienti, terminando con le patate. Coprite la pirofila con un foglio d''alluminio e cuocete in forno per un''ora. Togliete la carta d''alluminio e continuate la cottura per altri 20 minuti in modo da far dorare le patate.',2094);
INSERT INTO "ricette" VALUES (17664,'Pasticcio Di Penne','Primo','Panna',4,' -','400 G Pasta Tipo Penne,
4 Carciofi,
250 G Panna,
150 G Formaggio Grana Grattugiato,
150 G Pancetta,
150 G Prosciutto Cotto,
1 Cipolla,
2 Dadi,
1 Bicchiere Vino Bianco Secco,
50 G Burro,
Sale,
Pepe','Soffriggere nel burro la cipolla affettata e la pancetta a dadini, unire i carciofi a fettine sottili. Dopo qualche minuto bagnare con il vino, lasciare evaporare, unire 2 bicchieri d''acqua calda e i dadi sbriciolati. Cuocere fino a quando i carciofi sono teneri. Lessare le penne, condirle con i carciofi, unire panna, grana, prosciutto e mescolare.',4706);
INSERT INTO "ricette" VALUES (17665,'Pasticcio Di Penne Ai Funghi','Primo','Funghi Porcini',6,' -','Pasta Frolla,
300 G Pasta Tipo Pennette Lisce,
800 G Funghi Porcini,
1 Uovo,
50 G Burro,
1/2 Bicchiere Panna,
Formaggio Grattugiato,
Brodo,
Aglio,
Prezzemolo Tritato,
Olio D''oliva,
Sale,
Pepe','Fate la pasta frolla dimezzando la quantità dello zucchero e lasciatela riposare al fresco. Nel frattempo, in un tegame scaldate 30 g di burro con un cucchiaio d''olio, insaporitevi uno spicchio d''aglio e toglietelo quando è dorato. Aggiungete i funghi puliti, lavati e tagliati a fettine sottili, spruzzateli con un mestolo di brodo, coprite e cuocete a calore moderato fino a quando sono diventati morbidi, spruzzandoli con poco brodo tiepido se occorre. Alla fine regolate sale e pepe, versate la panna, mescolate con cura e fate addensare. Ritirate dal fuoco, aggiungete ai funghi un cucchiaio di prezzemolo tritato e, mescolando, un tuorlo diluito con un cucchiaino di brodo. I funghi devono essere velati dal condimento. Lessate in acqua salata a bollore le pennette, scolatele un po'' al dente, dividetele in due parti. Imburrate una pirofila da timballo, disponete sul fondo uno strato di penne, cospargetele con poco formaggio grattugiato e tre fiocchetti di burro, sopra distribuite uno strato di funghi, poi un altro di pasta condita sempre con poco formaggio e burro, poi uno di funghi e ricoprite con la pasta frolla tirata a disco dello spessore di circa mezzo centimetro. Cuocete in forno preriscaldato a 170 gradi per 15 minuti o fino a quando la superficie del timballo risulta leggermente dorata. Vini di accompagnamento: Garda Bresciano Rosso DOC, Trentino Marzemino DOC, Torgiano Pinot Nero DOC.',3290);
INSERT INTO "ricette" VALUES (17666,'Pasticcio Di Pesce','Pesce','Cernia',4,' -','Olio D''oliva,
Sale,
Pepe,
3 Spicchi Aglio,
Prezzemolo,
Limone,
2 Cipolle,
Alloro,
1 Cucchiaio Capperi,
2 Gambi Sedano,
120 G Olive Verdi Snocciolate,
1 Cernia Di 1200 G,
300 G Gamberi,
1 1/2 Bottiglia Vino Bianco','Questa è la versione un po'' semplificata di un pasticcio di pesce molto in onore, un tempo, nella Sicilia del ''Gattopardo''. Allora: fate un brodo con due litri d''acqua, qualche foglia di alloro, le cipolle affettate, il sedano tagliato a pezzetti e fettine di limone. Date dieci minuti di ebollizione, unite una bottiglia di vino, aspettate che torni il bollore; mettete dentro i gamberi, abbassate la fiamma, lasciate cuocere per una decina di minuti; tirate fuori i gamberi, scolateli bene, tenete da parte il brodo, fatelo raffreddare, passatelo in una pesciera o altro recipiente adatto, mettete dentro la cernia, ben pulita, aperta; fatela cuocere per quaranta minuti circa, sempre a fuoco basso: il brodo deve sobbollire, cioè mandate bolle lente, larghe. Alla fine, tirate fuori il pesce, sgocciolatelo, pulitelo da lische, ossicini e pelle e sistematelo nel frullatore assieme alle olive, ai capperi lavati e strizzati e a tre spicchi d''aglio. Fate ridurre in purea aggiungendo olio d''oliva poco alla volta e spegnendo a intermittenza il frullatore: dovete ottenere un composto omogeneo. Unite il prezzemolo, sale, pepe e l''olio rimasto, montando a mano con una spatola di legno fino a ottenere un insieme leggero e spumoso. Durante questa operazione, assieme all''olio rimasto aggiungete, poco alla volta, la mezza bottiglia di vino. Versate il composto su un piatto di portata, modellatelo possibilmente in forma di pesce e guarnitelo con i gamberoni che disporrete sgusciati sul pasticcio, ancora col guscio tutto intorno. Fate raffreddare in frigorifero prima di portare in tavola.',3280);
INSERT INTO "ricette" VALUES (17667,'Pasticcio Di Pesce (2)','Pesce','Cernia',4,' -','Olio D''oliva,
Sale,
Pepe,
3 Spicchi Aglio,
Prezzemolo,
Limone,
2 Cipolle,
Alloro,
1 Cucchiaio Capperi,
2 Gambi Sedano,
120 G Olive Verdi Snocciolate,
1 Cernia Di 1200 G,
300 G Scampi,
1 1/2 Bottiglia Vino Bianco','Questa è la versione un po'' semplificata di un pasticcio di pesce molto in onore, un tempo, nella Sicilia del ''Gattopardo''. Allora: fate un brodo con due litri d''acqua, qualche foglia di alloro, le cipolle affettate, il sedano tagliato a pezzetti e fettine di limone. Date dieci minuti di ebollizione, unite una bottiglia di vino, aspettate che torni il bollore; mettete dentro gli scampi, abbassate la fiamma, lasciate cuocere per una decina di minuti; tirate fuori i gamberi, scolateli bene, tenete da parte il brodo, fatelo raffreddare, passatelo in una pesciera o altro recipiente adatto, mettete dentro la cernia, ben pulita, aperta; fatela cuocere per quaranta minuti circa, sempre a fuoco basso: il brodo deve sobbollire, cioè mandate bolle lente, larghe. Alla fine, tirate fuori il pesce, sgocciolatelo, pulitelo da lische, ossicini e pelle e sistematelo nel frullatore assieme alle olive, ai capperi lavati e strizzati e a tre spicchi d''aglio. Fate ridurre in purea aggiungendo olio d''oliva poco alla volta e spegnendo a intermittenza il frullatore: dovete ottenere un composto omogeneo. Unite il prezzemolo, sale, pepe e l''olio rimasto, montando a mano con una spatola di legno fino a ottenere un insieme leggero e spumoso. Durante questa operazione, assieme all''olio rimasto aggiungete, poco alla volta, la mezza bottiglia di vino. Versate il composto su un piatto di portata, modellatelo possibilmente in forma di pesce e guarnitelo con i gamberoni che disporrete sgusciati sul pasticcio, ancora col guscio tutto intorno. Fate raffreddare in frigorifero prima di portare in tavola.',3367);
INSERT INTO "ricette" VALUES (17668,'Pasticcio Di Polenta','Primo','Farina Di Mais Giallo',4,' -','Per La Besciamella:,
Olio D''oliva Extra-vergine,
Farina Di Frumento Integrale (o Farina Setacciata Tipo 2),
Brodo Vegetale (o Brodo Di Cottura),
Timo,
Sale,
Per Il Condimento:,
1000 G Funghi Porcini,
1 Cipolla,
Olio D''oliva Extra-vergine,
Sale,
25 Cl Panna Liquida (facoltativa),
1 Spicchio Aglio,
Alcuni Rametti Prezzemolo,
100 G Formaggio Parmigiano,
100 G Formaggio Caciotta Fresca,
Per La Polenta:,
500 G Farina Di Mais Giallo,
Sale','Preparate anzitutto la besciamella con gli ingredienti sopra elencati. Passate quindi alla cottura dei funghi: puliteli scrupolosamente e passateli sotto acqua corrente, asciugateli bene, tagliateli a fettine e fateli saltare in un tegame con alcuni cucchiai d''olio e la cipolla sbucciata e tritata. Al termine, aggiustate di sale, unite la panna (se lo ritenete opportuno), il prezzemolo e l''aglio tritato, mescolate e spegnete. Preparate una polenta piuttosto morbida. Poi ungete d''olio una teglia, disponetevi uno strato di polenta, uno di besciamella, spolverizzate di parmigiano grattugiato, fate uno strato di funghi e infine ricoprite con la polenta e concludete con la caciotta tagliata a dadini. Mettete in forno già caldo e fate cuocere a fuoco piuttosto vivace per circa un quarto d''ora.',5508);
INSERT INTO "ricette" VALUES (17669,'Pasticcio Di Polenta E Gorgonzola','Primo','Formaggio Gorgonzola',4,' -','300 G Sbramato Di Mais,
65 Cl Acqua,
32 Cl Latte,
200 G Formaggio Gorgonzola,
80 G Burro,
Sale','Preparare una polenta piuttosto soda. In un tegame scaldare il burro e mescolarlo al gorgonzola. Rovesciare su una spianatoia metà della polenta, ricoprirla con il gorgonzola fuso col burro e quindi con la restante polenta. Servire molto calda a fette.',2527);
INSERT INTO "ricette" VALUES (17670,'Pasticcio Di Pollo E Zucchine','Pollame','Pollo',4,'preparazione: 10 minuti. Cottura: 50 minuti. Calorie: 410.','300 G Pollo Arrosto (senza Pelle),
3 Zucchine,
20 Cl Vino Bianco Secco,
80 G Burro,
60 G Formaggio Emmenthal Grattugiato,
Prezzemolo,
1 Spicchio Aglio,
4 Cucchiai Farina Bianca,
Noce Moscata,
Sale,
Pepe','Tagliate a rondelle sottilissime le zucchine. Fatele soffriggere in un tegame con il burro nel quale avrete soffritto un trito di aglio e prezzemolo. Dopo 5 minuti salate, pepate, profumate di noce moscata e spolverizzate con la farina. Bagnate con il vino bianco e fatelo evaporare. Fuori dal fuoco incorporate il formaggio. Versate la preparazione in una pirofila e cuocete in forno a 200 gradi per circa 15 minuti.',1671);
INSERT INTO "ricette" VALUES (17671,'Pasticcio Di Pomodori, Zucchine E Melanzane','Contorno','Pomodori',6,' -','500 G Pomodori,
250 G Zucchine,
250 G Melanzane,
2 Cipolle,
1 Spicchio Aglio,
1 Peperoncino Rosso,
Olio D''oliva,
1 Cucchiaio Formaggio Parmigiano,
Sale','Sbucciate e tagliate le cipolle, l''aglio e il peperone rosso e metteteli a rosolare con un cucchiaio d''olio in un tegame. Quando sono appassiti passateli sul fondo di una pirofila. Tagliate i pomodori a fette rotonde, le zucchine e le melanzane a rondelle. Disponetele allineate nella pirofila, 1 fila di pomodori, 1 fila di zucchine, 1 fila di melanzane. Irrorate con olio, spolverate di sale e fate cuocere in forno a 180 gradi per una mezz''ora abbondante. Quando lo togliete dal forno cospargetele con il parmigiano grattugiato.',988);
INSERT INTO "ricette" VALUES (17672,'Pasticcio Di Rognoni','Carne','Vitello',4,'Luogo: Regno Unito.','2 Rognoni Di Vitello,
Olio D''oliva,
1/2 Cipolla Affettata,
1 Cucchiaio Prezzemolo Tritato,
Sale,
2 Petti Di Pollo Sfilettati,
Pasta Sfoglia,
Burro,
1 Cucchiaio Sherry Secco','Affettare sottilmente 2 rognoni di vitello e saltarli in padella con poco olio. Eliminare il liquido di cottura e saltare di nuovo i rognoni con poco olio, 1/2 cipolla affettata e 1 cucchiaio di prezzemolo tritato. Salare e aggiungere 2 petti di pollo sfilettati. Completare la cottura e far raffreddare. Foderare con pasta sfoglia (fresca o surgelata) una tortiera unta con burro e versarvi all''interno il misto di rognoni e pollo trifolati, bagnare con un cucchiaio di sherry secco e chiudere con altra pasta sfoglia. Cuocere a forno caldo a 150 gradi. Servire tiepido.',3059);
INSERT INTO "ricette" VALUES (17673,'Pasticcio Di Salmone','Pesce','Salmone',4,' -','1 Scatoletta Salmone,
3 Cucchiai Pangrattato,
1 Uovo,
1 Albume D''uovo,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Maionese,
Alcuni Capperi,
Per Servire:,
Burro','Aprite una piccola scatola di salmone, toglietelo e mettetelo in una terrina dove versate tre cucchiai di pangrattato fine, due cucchiai di parmigiano grattugiato, un uovo intero e un albume, mescolate bene il tutto con un cucchiaio di legno e non aggiungete sale perché, in genere il salmone è già salato a sufficienza. Impastate quindi con le mani e date al composto una forma allungata e stretta dome di un salame, avvolgete questa specie di salame in un lino pulito, inumidito e spremuto e legatelo bene tutto intorno. Fatelo cuocere in una casseruola piena d''acqua e fate bollire per circa un''ora. Quando è cotto, toglietelo dalla casseruola, levate il panno e lasciate raffreddare, poi tagliate a fettine che servite coperte di maionese insaporita con alcuni capperi tritati. Potete anche servirlo con burro fritto.',1926);
INSERT INTO "ricette" VALUES (17674,'Pasticcio Di Selvaggina In Crosta','Carne','Pernici',8,' -','Per La Pasta:,
250 G Grasso Di Rognone,
500 G Farina,
Sale,
30 Cl Acqua,
1 Tuorlo D''uovo,
Per Il Ripieno:,
1200 G Pernici,
4 Cucchiai Olio D''oliva,
12 Cl Vino Bianco Secco,
100 Cl Acqua,
50 G Pancetta Affumicata,
200 G Brunoise Di Cipolla,
100 G Brunoise Di Carota,
100 G Julienne Di Sedano,
50 G Burro,
Sale,
Pepe Bianco,
2 Bacche Ginepro,
1 Cucchiaino Paprica','Private il grasso di rognone della pellicina, cospargetelo con un po'' di farina e tritatelo grossolanamente. Ponetelo quindi in una terrina con l''acqua e il resto della farina, e lavorate il tutto fino ad ottenere un impasto sodo e omogeneo. Salatelo e lavoratelo ancora un poco sulla spianatoia; lasciatelo riposare per un paio d''ore e poi stendetelo sottilmente con il matterello in una sfoglia. Da questa ricavate una striscia, larga 2 cm e lunga quanto il perimetro della pirofila, e un coperchio in misura. Spennellate il bordo della pirofila con un po'' di tuorlo sbattuto, poi rivestitelo con la striscia di pasta preparata. Disossate le pernici, ponete gli ossi in una casseruola con l''olio caldo e fateli rosolare a fuoco vivo insieme a metà della cipolla e della carota, per 4-5 minuti. Unite il vino, fatelo consumare leggermente, quindi versate nella casseruola anche l''acqua e lasciate cuocere gli ossi fino a quando il liquido si sarà ridotto della metà. A questo punto passate al setaccio il fondo di cottura degli ossi, raccoglietelo in un pentolino pulito e lasciatelo sobbollire a fuoco medio fino a quando sarà diventato un quarto della quantità iniziale. In un tegame fate soffriggere la pancetta tagliata a dadini a calore moderato per 5 minuti, poi unite il resto delle verdure e lasciatele rosolare per 4-5 minuti. In un altro tegame fate fondere dolcemente il burro e rosolatevi la carne di pernice per 6-7 minuti a fuoco vivo, quindi ponete nel recipiente anche il soffritto di verdure e pancetta, la paprica, le bacche di ginepro schiacciate, il sale necessario e una macinata di pepe. Mescolate bene e trasferite il composto nella pirofila, quindi appoggiatevi sopra il coperchio di pasta aiutandovi con il matterello, e premetelo bene lungo il bordo. Usate i ritagli di pasta per decorare il coperchio preparato con tante strisce disposte a griglia, quindi praticate un foro nel centro dello stesso per permettere la fuoriuscita del vapore durante la cottura. Fate cuocere il pasticcio nel forno a 200 gradi per circa 50 minuti. A metà cottura versate nella pirofila, attraverso il buco del coperchio, il brodo preparato con gli ossi. --- CONSIGLI. Si tratta di un piatto tradizionale inglese, molto gustoso e anche di gradevole effetto estetico. Il coperchio di pasta, dorato e croccante, racchiude un saporito ripieno preparato con carne di pernice o di fagiano. Questo tipo di preparazione consente tra l''altro di utilizzare con ottimi risultati esemplari danneggiati dai pallini e quindi non presentabili interi.',7570);
INSERT INTO "ricette" VALUES (17675,'Pasticcio Di Spinaci','Contorno','Spinaci',4,' -','450 G Spinaci Surgelati,
1 Pugno Mollica Di Pane Raffermo,
100 G Formaggio Emmenthal Grattugiato,
2 Uova,
Panna,
Burro,
Olio D''oliva,
Sale','Scongelate gli spinaci in acqua bollente, strizzateli e insaporiteli in una casseruola per 5 minuti con 20 g. di burro e un cucchiaio d''olio. Poneteli in una terrina, unite il formaggio, il pane sbriciolato e 2 cucchiai di panna. Mescolate, unite 1 uovo e 1 tuorlo. Salate e amalgamate. Versate il composto in uno stampo imburrato, coprite e cuocete per 45 minuti a bagnomaria.',2440);
INSERT INTO "ricette" VALUES (17676,'Pasticcio Di Tagliatelle','Primo','Zucchine',4,' -','225 G Pasta Tipo Tagliatelle,
150 G Formaggio Parmigiano,
1 Uovo,
50 Cl Latte,
50 G Farina,
500 G Zucchine,
Olio D''oliva,
Burro,
Pepe,
Sale','Cuoci le tagliatelle in abbondante acqua salata per 10 minuti dopodichè scolale al dente e tienile da parte; in una casseruola prepara la besciamella (fai sciogliere il burro a cui va aggiunto farina e latte, sali e continui a mescolare fino a cottura ultimata). A parte fai saltare le zucchine tagliate a fettine col burro, salale e mescolale alle tagliatelle. Imburra una pirofila, sistema sul fondo uno strato di tagliatelle con le zucchine, copri con uno strato di besciamella a cui avrai aggiunto parmigiano grattugiato poi copri con un secondo strato di tagliatelle e copri di nuovo con la besciamella. Sull''ultimo strato sistema alcune fette di zucchina appena saltate nel burro, un po'' di besciamella e parmigiano. A questo punto cuoci in forno per circa 30 minuti e buon appetito.',3429);
INSERT INTO "ricette" VALUES (17677,'Pasticcio Di Tagliatelle (2)','Primo','Uova',4,' -','Per La Pasta:,
400 G Farina,
2 Uova,
Per Il Ripieno:,
1 Bustina Funghi Secchi,
3 Panini,
3 Uova,
Latte,
Sale,
Pepe,
Per Condire:,
Burro,
Formaggio Parmigiano','Lasciate rinvenire i funghi nell''acqua. In una ciotola ammorbidite la mollica dei tre panini nel latte e poi con un cucchiaio di legno mescolate fino a ridurla una pappa omogenea. Aggiungete i funghi ben strizzati e tritati. Legate il composto con i tuorli e poi incorporatevi gli albumi montati a neve. Salate e pepate. Con la farina e le uova fate la pasta. Tiratela a sfoglia sottile, tagliatela a nastrini e lessateli nell''acqua bollente. In una pirofila imburrata distribuite sul fondo le tagliatelle, versatevi sopra il composto, pareggiate, condite con parmigiano e burro a fiocchetti. Cuocete in forno a 160 gradi per mezz''ora. Vini di accompagnamento: Friuli Grave Pinot Bianco DOC, Orvieto DOC, Gravina DOC.',3812);
INSERT INTO "ricette" VALUES (17678,'Pasticcio Di Tagliatelle (3)','Primo','Uova',6,' -','200 G Farina,
50 G Burro,
3 Uova,
250 G Pasta Tipo Tagliatelle All''uovo,
60 G Formaggio Grana Grattugiato,
50 Cl Besciamella,
1 Pizzico Sale,
Pepe','Con farina, burro, uova e un pizzico di sale impastare la pasta brisée e metterla in frigo per 60 minuti. Lessare le tagliatelle in acqua salata, scolarle, condirle con burro, formaggio, pepe, besciamella. Stendere in due dischi la pasta brisée; col primo foderare una teglia imburrata; versarvi le tagliatelle e ricoprire col secondo richiudendo i bordi. Spennellare con tuorlo e infornare a 180 gradi per una ventina di minuti.',3049);
INSERT INTO "ricette" VALUES (17679,'Pasticcio Di Zucchine','Antipasto','Zucchine',4,' -','6 Zucchine,
150 G Mozzarella,
50 G Formaggio Emmenthal Grattugiato,
1 Cipolla,
2 Spicchi Aglio,
Prezzemolo,
3 Uova,
150 G Panna Fresca,
6 Fette Pancarré,
3 Cucchiai Olio D''oliva,
10 G Burro,
Sale','Soffriggere un trito di aglio, cipolla e prezzemolo con 3 cucchiai di olio e 10 g di burro, unire le zucchine a rondelle e il sale. Coprire, abbassare la fiamma e far stufare per 20 minuti. Battere le uova con panna e sale, quindi unire mozzarella a dadini, emmenthal e zucchine. Coprire il fondo di una pirofila imburrata con le fette di pane, distribuirvi il composto e cuocere in forno a 190 gradi.',3867);
INSERT INTO "ricette" VALUES (17680,'Pasticcio Di Zucchine Al Forno','Contorno','Zucchine',6,' -','1500 G Zucchine Tenere,
60 G Formaggio Philadelphia,
4 Uova,
1 Cipolla,
2 Cucchiai Formaggio Parmigiano Grattugiato,
4 Cucchiai Pangrattato,
1 Spicchio Aglio,
1 Mazzetto Prezzemolo,
1 Pizzico Maggiorana,
6 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Mondate le zucchine, tagliatele a dadini, mettetele in un colapasta, salatele e lasciatele fare l''acqua. Affettate a velo la cipolla e fatela appassire in 6 cucchiai d''olio con l''aglio. Unite le zucchine e lasciate insaporire fino a che risulteranno tenere. Alla fine pepate e unite un bel trito di prezzemolo. Intanto amalgamate il formaggio con le uova, il parmigiano, un pizzico di maggiorana e poco sale. Aggiungete le zucchine e mescolate bene poi versate il composto in una teglia unta e cosparsa di pangrattato. Irrorate con 3 cucchiai d''olio, cospargete di pangrattato e cuocete in forno a 180 gradi per 1 ora. Si serve sia caldo sia freddo.',1792);
INSERT INTO "ricette" VALUES (17681,'Pasticcio Vegetariano','Contorno','Sedano',4,' -','200 G Sedano Tenero,
2 Carote,
300 G Ricotta Fresca,
15 Olive Nere,
Sale,
Pepe,
1 Pizzico Noce Moscata','Mondare il sedano e tritarlo finemente. Mondare le carote, grattugiarle e unirle al sedano. Unire la ricotta passata al setaccio e le olive snocciolate e divise a metà. Condire con sale, pepe e un pizzico di noce moscata. Amalgamare delicatamente e versare il composto in uno stampo da budino scannellato. Conservare in frigorifero.',822);
INSERT INTO "ricette" VALUES (17682,'Pastiera','Dessert','Ricotta',4,' -','Per La Pasta:,
300 G Farina,
150 G Zucchero,
80 G Strutto,
4 Uova,
Zucchero Vanigliato,
1 Limone (scorza),
Sale,
Per Il Ripieno:,
500 G Ricotta,
300 G Zucchero,
500 G Grano In Scatola,
100 G Cedro Candito,
50 G Burro,
6 Uova,
1 Limone (scorza Grattugiata),
50 Cl Latte,
1 Bottiglina Acqua Di Fiori D''arancio,
Cannella In Polvere,
Sale','Far bollire in abbondante acqua il grano per circa un ora, poi scolarlo e rimetterlo sul fuoco con il latte, la scorza del limone (intera), un pizzico di cannella, un pizzico di sale, mezz''etto di zucchero e far cuocere a fuoco moderato fino a completa riduzione del liquido. Poi far raffreddare eliminando la scorza di limone. Per la pasta: impastare la farina con lo zucchero, lo strutto, 4 tuorli ed un pizzico di sale (se è troppo secca, aggiungere un uovo intero). Lavorare quanto basta e metterla a riposare in un luogo fresco. Per il ripieno: unire al grano la ricotta passata al setaccio, lo zucchero, la scorza di limone grattugiata, il cedro tagliato a dadini, un pizzico di cannella e l''acqua di fiori d''arancio, legare con i tuorli e con quattro albumi montati a neve. Stendere la pasta dello spessore di pochi millimetri, ricavarne un disco di circa 30 cm. di diametro e foderare con esso una teglia unta di burro; versare il ripieno nella teglia e completare stendendo in superfice delle strisce a forma di grata. Far cuocere la pastiera in forno ben caldo per circa 90 minuti e quindi, dopo raffreddata, cospargerla di zucchero a velo.',7547);
INSERT INTO "ricette" VALUES (17683,'Pastiera (2)','Dessert','Ricotta',6,' -','Per La Pasta:,
600 G Farina,
300 G Zucchero,
300 G Burro,
6 Tuorli D''uovo,
Per Il Ripieno:,
50 G Grano,
500 G Ricotta,
3 Cucchiai Farina,
50 Cl Latte,
9 Uova Intere,
Acqua Di Fiori D''arancio,
500 G Zucchero,
1 Noce Burro (o Sugna),
150 G Canditi (cedro, Scorzette D''arancia)','L''involucro è una comune pasta sfoglia. Per il ripieno fate cuocere il grano coperto d''acqua con la noce di sugna o di burro per un paio di ore e preparate la crema pasticciera con i rossi d''uova, 1/2 l di latte, 3 cucchiai colmi di zucchero e tre cucchiai di farina. Passate o frullate la ricotta e mescolatevi lo zucchero rimasto, i tuorli delle uova avanzate, l''acqua di fiori, i canditi, la crema e, in ultimo, gli albumi montati a neve. Per la pastiera esistono due scuole e due gusti: c''è chi la vuole bassa 3-4 cm. e c''è chi la preferisce sui 5-6 cm. perché così resta più umida e profumata. Con la dose che vi ho dato potrete fare una pastiera piuttosto alta in una teglia di 27-28 cm. di diametro o una più bassa ed ancora più larga. Ho ritenuto di darvi delle dosi piuttosto generose perché si tratta di un dolce che si consuma in giorni di festa quando ci sono numerosi commensali: non va a male facilmente e potrete consumarlo nell''arco di 4-5 giorni. D''altronde, mi sembra assurdo fare un lavoro così elaborato solo per poche persone. Stendete i 2/3 della pasta e foderate come al solito la teglia che riempirete con il ripieno. La parte superiore di questo dolce, anziché completamente chiusa, deve essere schermata da strisce di pasta larga circa 2 cm. incrociate a griglia. Dopo aver allargata la pasta, tagliate quindi queste strisce e mettetele prima per un verso, lasciando fra l''una e l''altra circa 3 cm. di distanza, poi per l''altro verso, in modo che restino in vista delle losanghe di ripieno. Mettete in forno già caldo a calore moderato e lasciate cuocere per 40-45 minuti se avrete fatto una pastiera bassa e per un''ora quasi se la pastiera sarà alta. Spento il forno mettete il dolce a raffreddare fuori se toccandolo al centro con i polpastrelli vi sembrerà asciutto; lasciatelo raffreddare nel forno se sarà ancora un po'' molle. La pastiera comunque non deve essere troppo asciutta. Quando sarà fredda cospargetela di zucchero a velo: è preferibile mangiarla il giorno seguente, e dura anche diversi giorni. Non farà che migliorare nell''attesa.',10868);
INSERT INTO "ricette" VALUES (17684,'Pastiera (3)','Dessert','Ricotta',8,' -','700 G Ricotta,
450 G Zucchero,
7 Tuorli D''uovo,
5 Albumi D''uovo,
2 Bustine Vaniglina,
1/3 Bustina Cannella,
1 Limone (scorza Grattugiata),
1 Presa Sale,
4 Cl Acqua Fiore D''arancio,
Cedro Tagliato A Quadretti,
Per Cuocere Il Grano:,
450 G Grano,
100 G Latte,
30 G Strutto,
Per La Pasta Frolla:,
6 Tuorli D''uovo,
3 Albumi D''uovo,
Acqua,
150 G Zucchero,
250 G Margarina,
900 G Farina,
1 Pizzico Sale','Cottura del grano. Cuocere il grano per 10 minuti insieme al latte e allo strutto. Passarne poi la metà. Preparazione della Pasta frolla. Mescolare tutti insieme gli ingredienti; lasciare riposare in frigo per 1 ora, poi stendere a sfoglia sottile. Battere i tuorli d''uovo insieme allo zucchero, aggiungere la ricotta e frullare bene. Aggiungere quindi, continuando a frullare, il grano passato, l''acqua ''fior d''arancio'', la cannella, la vaniglina e la buccia di limone. A parte montare a neve gli albumi aggiungendo il sale. A questo punto unire il tutto al resto del grano e frullare. Foderare poi una teglia bassa con la pasta frolla, versarvi il composto precedentemente ottenuto fino a 3/4 dal bordo. Cospargere di cedro e guarnire con striscioline di pasta frolla incrociate. Infornare in forno già caldo per 1 ora a fuoco medio. Una volta raffreddata, spargere uniformemente su tutta la pastiera, lo zucchero a velo.',11082);
INSERT INTO "ricette" VALUES (17685,'Pastiera (4)','Dessert','Ricotta',6,'Luogo: Campania. Luogo: Napoli.','500 G Farina Per Dolci,
Strutto,
Zucchero,
2 Uova Intere,
Latte Freddo (facoltativo),
Per Il Ripieno:,
250 G Ricotta Freschissima,
250 G Zucchero,
5 Uova,
250 G Grano Lessato,
100 G Cedro Candito A Dadini,
1 Pizzico Cannella,
4 Cucchiai Fiori D''arancia,
1 Cucchiaio Rum,
1 Bustina Vaniglia,
Per La Teglia:,
Burro','Ricetta natalizia. Anche se di origine napoletana, la pastiera è uno dei dolci più diffusi nelle solennità religiose. Si prepara una pasta frolla con mezzo chilo di farina per dolci, un quarto di strutto, un quarto di zucchero, 2 uova intere; se necessario si aggiunge un po'' di latte freddo. La pasta si prepara ponendo la farina a fontana sulla spianatoia, mescolando bene lo zucchero, aggiungendo il burro o lo strutto e cercando di amalgamarlo con le mani, in ultimo unendo le uova e formando la palla che si lascerà riposare per un''oretta, coperta da un tovagliolo. Nel frattempo si prepara il ripieno: si uniscono a 250 g di ricotta freschissima 250 g di zucchero e uno alla volta 5 tuorli d''uovo, le chiare montate a neve (per accelerare si può dividere la quantità di zucchero stabilita in due parti, una unendola ai rossi, l''altra alle chiare). Si unisce a quest''impasto 250 g di grano lessato, 100 g di cedro candito tagliato a dadini; un pizzico di cannella; 4 cucchiai di fiori d''arancia e uno di rum ed infine una bustina di vaniglia. Foderare con la pasta ridotta a lamina col matterello, una teglia unta di burro, sistemarvi dentro il ripieno, con la pasta rimasta tagliare delle striscioline con l''apposita rotella e formare una grata sopra la preparazione. Infornare a calore moderato per circa 30 minuti.',6367);
INSERT INTO "ricette" VALUES (17686,'Pastiera (5)','Dessert','Ricotta',6,'Luogo: Campania. Luogo: Napoli.','500 G Farina Per Dolci,
Burro,
Zucchero,
1 Uovo Intero,
2 Tuorli D''uovo,
Latte Freddo (facoltativo),
Per Il Ripieno:,
250 G Ricotta Freschissima,
250 G Zucchero,
5 Uova,
250 G Grano Lessato,
100 G Cedro Candito A Dadini,
1 Pizzico Cannella,
4 Cucchiai Vino Marsala,
1 Cucchiaio Triple Sec (o Gin),
1 Bustina Vaniglia,
Per La Teglia:,
Burro','Ricetta natalizia. Anche se di origine napoletana, la pastiera è uno dei dolci più diffusi nelle solennità religiose. Si prepara una pasta frolla con mezzo chilo di farina per dolci, un quarto di burro, un quarto di zucchero, 1 uova intero e 2 tuorli; se necessario si aggiunge un po'' di latte freddo. La pasta si prepara ponendo la farina a fontana sulla spianatoia, mescolando bene lo zucchero, aggiungendo il burro o lo strutto e cercando di amalgamarlo con le mani, in ultimo unendo le uova e formando la palla che si lascerà riposare per un''oretta, coperta da un tovagliolo. Nel frattempo si prepara il ripieno: si uniscono a 250 g di ricotta freschissima 250 g di zucchero e uno alla volta 5 tuorli d''uovo, le chiare montate a neve (per accelerare si può dividere la quantità di zucchero stabilita in due parti, una unendola ai rossi, l''altra alle chiare). Si unisce a quest''impasto 250 g di grano lessato, 100 g di cedro candito tagliato a dadini; un pizzico di cannella; 4 cucchiai di marsala e uno di triple sec (o gin) ed infine una bustina di vaniglia. Foderare con la pasta ridotta a lamina col matterello, una teglia unta di burro, sistemarvi dentro il ripieno, con la pasta rimasta tagliare delle striscioline con l''apposita rotella e formare una grata sopra la preparazione. Infornare a calore moderato per circa 30 minuti.',6480);
INSERT INTO "ricette" VALUES (17687,'Pastiera Salata Di Pasqua','Carne','Agnello',6,' -','1 Confezione Pasta Brisée Surgelata,
600 G Fegatini D''agnello,
3 Spicchi Aglio,
1 Mazzetto Prezzemolo,
2 Limoni,
150 G Formaggio Toma,
2 Uova,
1 Cucchiaio Olio D''oliva,
Sale,
Pepe','Mettete la pasta a scongelare (a temperatura ambiente) e, frattanto, a parte, mondate e spezzettate i fegatini. Rosolateli in padella con un cucchiaio d''olio e un trito d''aglio, sale e pepe. Rivoltate il soffritto finché sarà tutto ben cotto; quindi mescolatevi il prezzemolo tritato e il succo del limome. Spegnete il fuoco e fate intiepidire. Quando sarà freddo, mescolate al composto il formaggio grattugiato a grosse scaglie. Dividete la pasta in due pezzi e spianateli a forma di disco. Stendete uno dei dischi sulla piastra unta del forno e sistematevi al centro il ripieno. Poggiate su questo il secondo disco di pasta e arrotolate insieme i bordi delle due sfoglie. Mettete la piastra in forno preriscaldato a 200 gradi e fate cuocere la focaccia per circa mezz''ora.',3325);
INSERT INTO "ricette" VALUES (17688,'Pastiglie Al Formaggio','Antipasto','Formaggio Emmenthal',6,' -','200 G Farina,
100 G Formaggio Parmigiano Grattugiato,
100 G Burro,
1 Uovo,
100 G Formaggio Emmenthal Bavarese,
50 G Panna,
Sale,
Pepe','In una fondina, mescolate alla farina il parmigiano, il burro fuso (non caldo), l''uovo battuto con sale e pepe e la panna. Ottenuta una pasta omogenea, di media consistenza, spianatela sul piano di lavoro infarinato e ritagliatevi, con una fustella tonda a bordi lisci o con l''orlo d''un piccolo bicchiere, delle tartine circolari di circa 4 cm di diametro. Appena pronte, poggiate le pastiglie sull''emmenthal grattugiato in modo che ne risultino ricoperte solo da un lato. Fatto ciò, adagiatele sulla piastra unta del forno, posandole sul lato opposto a quello ricoperto di emmenthal. Spingete la piastra in forno preriscaldato a 200 gradi e lasciate che le pastiglie diventino dorate (20 minuti circa).',2436);
INSERT INTO "ricette" VALUES (17689,'Pastina Al Pomodoro','Primo','Pomodoro',1,'Ricetta adatta a: bambini piccoli.','400 G Acqua,
Sale,
1 Nido Pasta Tipo Pastina,
1 Cucchiaino Olio D''oliva,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Sugo Di Pomodoro Passato Al Colino','In 400 g circa d''acqua bollente, leggermente salata, immergere la pastina. Far bollire, mescolando con una forchetta, per 5-6 minuti. Scolare e condire con 1 cucchiaino d''olio d''oliva, 1 cucchiaio di parmigiano grattugiato ed il sugo di pomodoro fresco maturo passato al colino.',540);
INSERT INTO "ricette" VALUES (17690,'Pastina Al Sugo','Primo','Pomodori',1,'Ricetta adatta a: bambini piccoli.','2 Pomodori Freschi Passati Al Setaccio,
1 Cucchiaio Brodo,
Pasta Tipo Pastina Junior,
1 Cucchiaino Olio D''oliva Extra-vergine,
2 Cucchiaini Formaggio Parmigiano,
1 Omogeneizzato Di Carne','Preparare un sughetto ponendo in un tegame a fuoco basso 2 pomodori freschi o pelati passati al setaccio. Scaldare mescolando e, se necessario, aggiungere un cucchiaio di brodo o di acqua. Con questo sugo condire la pastina junior cotta per 4-7 minuti a seconda del formato e ben scolata. Aggiungere un cucchiaino di olio d''oliva extra-vergine, 2 cucchiaini di parmigiano e a cottura ultimata un omogeneizzato di carne.',1333);
INSERT INTO "ricette" VALUES (17691,'Pastina Alla Ligure','Primo','Maggiorana',4,'Luogo: Liguria.','100 G Pasta Tipo Pastina,
1 Tuorlo D''uovo,
1 Cucchiaio Maggiorana Tritata,
Formaggio Grattugiato,
Sale','Cuocete la pastina e intanto lavorate a parte un cucchiaio di maggiorana tritata con il formaggio e il tuorlo. Unite il composto alla pastina a cottura ultimata.',821);
INSERT INTO "ricette" VALUES (17692,'Pastina Fresca Per Brodo Con Il Bimby','Primo','Uovo',4,'Ricetta adatta a: bambini piccoli.','1 Uovo,
100 G Farina,
20 G Farina Per Tritare','Inserire nel boccale la farina, l''uovo e impastare: 10 secondi a velocità 5. Inserire dal foro del coperchio con lame in movimento a velocità 5, i 20 g di farina e fermare subito l''apparecchio. Versare la pastina e utilizzarla subito o lasciarla seccare su un canovaccio.',477);
INSERT INTO "ricette" VALUES (17693,'Pastina In Brodo','Primo','Brodo Vegetale',1,'Ricetta adatta a: bambini piccoli.','250 G Brodo Vegetale,
2 Cucchiai Pastina Per L''infanzia,
1 Cucchiaino Olio D''oliva Extra-vergine,
1 Cucchiaino Formaggio Parmigiano','Portate a bollore il brodo e aggiungete la pastina a pioggia. Fate cuocere per 5 minuti circa. Poi aggiungete l''olio e il parmigiano.',375);
INSERT INTO "ricette" VALUES (17694,'Pastina In Brodo Allo Zafferano','Primo','Zafferano',4,' -','80 G Pasta Tipo Stelline,
100 G Salsiccia Magra,
150 Cl Brodo,
1 Pizzico Zafferano,
Formaggio Grattugiato','In un pentola da minestra soffriggete brevemente la salsiccia spellata e sbriciolata senza altro condimento. Versatevi sopra il brodo e poi aggiungete la pastina e lasciate cuocere dieci minuti o poco più. Unite il pizzico di zafferano, mescolate e servite con formaggio grattugiato.',1560);
INSERT INTO "ricette" VALUES (17695,'Pastina In Brodo Coi Fagioli','Primo','Fagioli',1,'Ricetta adatta a: bambini piccoli.','200 G Fagioli Freschi,
250 G Brodo,
2 Cucchiai Passato Di Pomodoro,
2 Cucchiai Pasta Tipo Pastina,
1 Cucchiaino Olio D''oliva,
1 Omogeneizzato Di Carne','Preparare un brodo di fagioli facendo bollire per due ore circa 200 g di fagioli freschi. In 250 g di brodo, portato ad ebollizione, aggiungere 2 cucchiai di passata e far cuocere per 3-4 minuti circa 2 cucchiai di pastina. Aggiungere infine un cucchiaino d''olio d''oliva ed un omogeneizzato di carne.',700);
INSERT INTO "ricette" VALUES (17696,'Pastina In Brodo Coi Fagioli (2)','Primo','Fagioli',1,'Ricetta adatta a: bambini piccoli.','200 G Fagioli Secchi Ammollati Per 12 Ore,
250 G Brodo,
2 Cucchiai Passato Di Pomodoro,
2 Cucchiai Pasta Tipo Pastina,
1 Cucchiaino Olio D''oliva,
50 G Carne Tritata','Preparare un brodo di fagioli facendo bollire per due ore circa 200 g di fagioli freschi. In 250 g di brodo, portato ad ebollizione, aggiungere 2 cucchiai di passata e far cuocere per 3-4 minuti circa 2 cucchiai di pastina. Aggiungere infine un cucchiaino d''olio d''oliva e 50 g di carne tritata.',918);
INSERT INTO "ricette" VALUES (17697,'Pastina Marinara','Primo','Omogeneizzato Di Salmone',1,'Ricetta adatta a: bambini piccoli.','4 Cucchiai Pasta Tipo Stelline,
2 Pomodori Ben Maturi,
1 Vasetto Omogeneizzato Di Salmone,
1 Cucchiaino Olio D''oliva Extra-vergine','Fate sbollentare per qualche secondo i pomodori, in modo da togliere facilmente la pelle, eliminate il picciolo ed i semi e passateli al passaverdure, in modo da ottenere una salsa. Nel frattempo portate a ebollizione un pentolino d''acqua, versatevi la pastina e fatela cuocere per il tempo indicato sulla confezione. Scolatela, ponetela nel piatto ed aggiungete 1 cucchiaio di salsa di pomodoro; completate con l''omogeneizzato di salmone, mescolate bene e prima di servire condite con l''olio.',558);
INSERT INTO "ricette" VALUES (17698,'Pastina Marinara (2)','Primo','Omogeneizzato Di Salmone',1,'Ricetta adatta a: bambini piccoli.','4 Cucchiai Pasta Tipo Gemmine,
1 Pomodoro Ben Maturo,
1 Vasetto Omogeneizzato Di Salmone,
1 Cucchiaino Olio D''oliva Extra-vergine','Fate sbollentare per qualche secondo il pomodoro, in modo da togliere facilmente la pelle, eliminate il picciolo ed i semi e passateli al passaverdure, in modo da ottenere una salsa. Nel frattempo portate a ebollizione un pentolino d''acqua, versatevi la pastina e fatela cuocere per il tempo indicato sulla confezione. Scolatela, ponetela nel piatto ed aggiungete 1 cucchiaio di salsa di pomodoro; completate con l''omogeneizzato di salmone, mescolate bene e prima di servire condite con l''olio.',542);
INSERT INTO "ricette" VALUES (17699,'Pastina Per Brodo Con Il Bimby','Primo','Uovo',4,' -','1 Uovo,
130 G Farina','Inserisci nel boccale 100 G di farina e l''uovo: 10 secondi a velocità 3. Con lame in movimento a velocità 5 aggiungi i restanti 30 G di farina e ferma l''apparecchio dopo 2 secondi. Versa la pastina su un canovaccio e lasciala asciugare. Se una parte dell''impasto rimane attaccato alle pareti, staccalo con la spatola e ripeti l''operazione con un poco di farina.',509);
INSERT INTO "ricette" VALUES (17700,'Pastine All''arancia','Dessert','Panna',4,'Preparazione: 90 minuti.','150 G Marmellata Di Arance,
50 G Panna Da Montare,
45 G Zucchero Semolato,
40 G Farina Bianca 00,
30 G Fecola Di Patate,
30 G Zucchero A Velo,
2 Uova Grandi,
Poca Scorza D''arancia Candita,
1 Pizzico Cremortartaro,
1 Pizzico Sale','Le dosi sono per 24 pastine. Rivestite con un foglio di carta oleata una larga placca da forno. Montate in neve ben soda gli albumi, unendo un pizzico di sale; quando saranno ben montati aggiungete lo zucchero e un pizzico di cremortartaro, continuando a sbattere sino ad avere ottenuto un composto sodo, sul tipo di quello delle meringhe. In un''altra ciotola sbattete i tuorli, aggiungendo poi, a poco per volta, la massa degli albumi mescolando tutto con delicatezza; incorporatevi quindi la farina e la fecola mescolate e fatte cadere a pioggia da un setaccino. Versate il composto in una tasca di tela munita di bocchetta rotonda liscia e deponete sulla placca preparata 48 ciuffetti della grossezza di una bella noce; passateli in forno già caldo a 190 gradi e dopo circa 10 minuti di cottura, quando le sfere di pasta saranno cotte internamente e dorate in superficie, staccatele dalla placca e mettetele a raffreddare sopra una gratella. Spalmate allora 24 dolcetti con la marmellata di arance, posandovi poi sopra gli altri privi di marmellata: otterrete 24 pastine formate da due mezze sfere. Così preparate collocate in altrettanti pirottini di carta. Montate la panna, mettetela in una piccola tasca di tela impermeabile munita di bocchetta spizzata e coprite con essa il punto d''unione delle due pastine; sopra la panna posate una corta listerella di scorza di arancia candita. Spolverizzatele infine con lo zucchero a velo fatto scendere da un setaccino a maglia fine e servitele. Vanno consumate in giornata.',1336);
INSERT INTO "ricette" VALUES (17701,'Pastine Alle Mandorle','Dessert','Mandorle Dolci',4,' -','200 G Farina, Zucchero E Mandorle Dolci,
1 Uovo,
2 Cucchiaini Lievito In Polvere,
Zucchero A Velo Vanigliato,
Per La Placca:,
Burro','Scottare le mandorle in acqua bollente, indi pelarle e tritarle. Impastarle con la farina, lo zucchero, l''uovo e il lievito, poi farne 1 bastone piuttosto sottile e tagliarlo a fettine. Allinearle in 1 placca per dolci imburrata e farle cuocere in forno, a calore moderato, per circa 20 minuti. Sfornare e spolverizzare di zucchero a velo vanigliato.',1545);
INSERT INTO "ricette" VALUES (17702,'Pastine Bicolori','Dessert','Uova',8,' -','120 G Farina,
150 G Zucchero,
50 G Amido Di Mais,
40 G Burro Fuso,
15 G Cacao Amaro,
3 Uova,
1 Bustina Vaniglina,
1 Pizzico Sale,
Zucchero A Velo','Montate le uova intere con lo zucchero semolato, la vaniglina e un pizzico di sale, sino ad ottenere un composto soffice e gonfio. Incorporatevi allora 100 g di farina e la maizena, miscelate e fate cadere a pioggia da un setaccino, e il burro fuso e fatto raffreddare, mescolando delicatamente con un cucchiaio di legno. Imburrate e infarinate una teglia di 26 x 18 centimetri poi in essa versate metà del composto fatto; al restante unite il cacao setacciato, mescolando con cura, poi versatelo sul composto giallo; battete un momento il recipiente sul piano del tavolo, sopra un canovaccio piegato, indi mettetelo in forno già caldo a 180 gradi. Dopo circa 30 minuti infilate nella pasta uno stecchino di legno e se uscirà asciutto sformatela su una gratella e lasciatela raffreddare. Poco prima di servire tagliatela a grossi cubi, spolverizzateli con zucchero a velo e disponeteli in un piatto.',1842);
INSERT INTO "ricette" VALUES (17703,'Pastine Bicolori (2)','Dessert','Cacao Amaro',4,'Preparazione: 60 minuti.','150 G Zucchero Semolato,
120 G Farina Bianca,
50 G Fecola Di Patate,
40 G Burro,
15 G Cacao Amaro,
3 Uova,
1 Bustina Vaniglina,
Zucchero A Velo,
1 Pizzico Sale','Le dosi sono per 24 pastine circa. Fate fondere 25 g di burro, poi lasciatelo raffreddare. Montate le uova intere con lo zucchero semolato, la vaniglina e un pizzico di sale, sino ad ottenere un composto soffice e gonfio. Incorporatevi allora 100 g di farina e la fecola, mescolate e fatte cadere a pioggia da un setaccino, ed il burro fuso, mescolando delicatamente con un cucchiaio di legno. Imburrate e infarinate una teglia di cm 26 x 18 poi in essa versate metà del composto fatto; al restante unite 15 g di cacao setacciato, mescolando con cura, poi versatelo sul composto giallo; battete un momento il recipiente sul piano del tavolo, sopra un asciughino piegato, indi mettetelo in forno già caldo a 180 gradi. Dopo circa 30 minuti infilate nella pasta uno stecchino di legno e se uscirà asciutto sformatela su una gratella e lasciatela raffreddare. Poco prima di servire tagliatela a grossi cubi, spolverizzateli con zucchero a velo e disponeteli in un piatto.',1820);
INSERT INTO "ricette" VALUES (17704,'Pastine Da Tè','Dessert','Margarina',4,' -','200 G Farina Bianca,
80 G Zucchero,
140 G Margarina,
2 Tuorli D''uovo,
10 G Lievito In Polvere,
Scorza Di Limone Grattugiata,
Mandorle Pelate (o Ciliegie Candite)','Setacciare a fontana la farina sul tavolo assieme al lievito, fare un incavo nel centro, mettere lo zucchero, la margarina, i tuorli d''uovo e la buccia di limone. Lavorare velocemente la pasta, quindi formare delle palline grosse come una noce. Immergerle nel bianco d''uovo leggermente sbattuto e disporle distanziate su una teglia unta. Su ogni pallina mettere 1/2 mandorla o ciliegia premendola nel centro. Cuocere in forno già caldo a 180 gradi per circa 20 minuti, mettendo la teglia a mezza altezza nel forno.',2819);
INSERT INTO "ricette" VALUES (17705,'Pastine Di Castagne All''amaretto','Dessert','Castagne',6,'Preparazione: 90 minuti.','500 G Castagne,
120 G Latte,
75 G Panna Da Montare,
50 G Zucchero Semolato,
6 Biscotti Amaretti,
Poco Cacao Amaro,
1 Cucchiaio Zucchero Vanigliato','Le dosi sono per 12 pastine. Incidete la buccia della castagne con un coltellino appuntito e mano a mano che sono pronte mettetele in una casseruola; alla fine copritele di acqua fredda e fatele cuocere per circa 30 minuti a partire dall''ebollizione. Levate il recipiente dal fornello ed estraendo poche castagne per volta pelatele; a lavoro finito passatele dal passaverdure con il disco più fine raccogliendole in una ciotola. Incorporatevi poi il latte freddo e lo zucchero, mescolando bene. Sbriciolate gli amaretti e distribuitene la metà sul fondo di 12 larghi pirottini di carta; in una tasca di tela impermeabile munita di bocchetta rotonda liscia mettete i tre quarti del composto di castagne, premendolo poi nei pirottini. Montate la panna ben soda e coprite il composto, spolverizzatela con lo zucchero vanigliato e cospargetela con tutte le briciole di amaretti. Mettete a poco per volta il restante composto di castagne in uno spremiaglio e fate cadere questi sottili fili a monticello sui dolcetti, per ultimo spolverizzateli con pochissimo cacao amaro fatto cadere da un setaccino. Disponete le pastine in un adeguato piatto di portata e in attesa di servire conservatele in frigo. E consigliabile però gustarle entro 2 ore dalla loro preparazione.',1823);
INSERT INTO "ricette" VALUES (17706,'Pastine Frolle','Dessert','Uova',4,' -','500 G Farina,
1/2 Cucchiaino Lievito In Polvere,
125 G Burro,
100 G Strutto,
4 Tuorli D''uovo,
Poca Scorza Di Limone Grattugiata,
1 Albume D''uovo','Lavorare la pasta il meno possibile, dare la forma alle pastine e spennellarle con l''albume. Quando sono cotte, spolverarle di zucchero.',3879);
INSERT INTO "ricette" VALUES (17707,'Pastissà De Caval','Carne','Cavallo',4,' -','1500 G Carne Di Cavallo (coscia),
1000 G Cipolle,
Carote,
Sedano,
Lardo,
Aglio,
Rosmarino,
Salvia,
Chiodi Di Garofano,
Alloro,
Cannella,
Pepe,
Sale,
Burro,
Olio D''oliv