are il tutto in uno stampo di terraglia e cuocere a bagno maria per 6 ore. Sformare e servire caldo con panna liquida zuccherata e ben fredda.',9541);
INSERT INTO "ricette" VALUES (5595,'Christmas Punch','Bevande','Rum',1,' -','1/2 Rum,
1/2 Cognac,
4 Arance,
Molto Zucchero,
4 Chiodi Di Garofano,
1 Spolverata Noce Moscata E Cannella','Infornare le arance dopo averle tagliate a metà e aver messo quattro chiodi di garofano su ognuna, finché la buccia diventerà dorata. Metterle nella bowl e versarvi sopra i liquori e lo zucchero. Dare fuoco; spegnere dopo una decina di secondi e aggiungere sidro. Servire nel cup con una spolverata di noce moscata e cannella.',844);
INSERT INTO "ricette" VALUES (5596,'Christstollen','Dessert','Uvetta Sultanina',12,' -','1200 G Farina,
100 G Lievito Di Birra,
40 Cl Latte,
100 G Zucchero,
2 Uova,
1 Stecca Vaniglia,
1 Limone (scorza Grattugiata),
1 Cucchiaino Sale,
400 G Burro,
350 G Uvetta Sultanina,
100 G Mandorle Pelate E Tritate,
100 G Cedro Candito,
50 G Arancia Candita,
2 Cl Rum,
Per Guarnire:,
150 G Burro Fuso,
200 G Zucchero A Velo,
1 Stecca Di Vaniglia','Setacciate 1000 g di farina in una terrina, disponendola a fontana, e fate un incavo al centro. Mettetevi il lievito sbriciolato, bagnate questo col latte tiepido e fatelo sciogliere. Impastate il tutto e lasciate riposare, coperto, per 20 minuti. Trascorso questo tempo unite le uova, lo zucchero, l''interno della stecca di vaniglia raschiato con un coltello, la scorza di limone grattugiata e il sale e lavorate gli ingredienti fino ad ottenere una pasta liscia e soda. Lasciatela riposare per 10-12 minuti. Impastate il resto della farina con il burro, incorporate il composto alla pasta lievitata e fate riposare per altri 15 minuti. Nel frattempo riunite l''uvetta, ammorbidita in acqua tiepida e strizzata, la frutta candita e le mandorle in una scodella e bagnateli col rum. Fate macerare per alcuni minuti, poi sgocciolate il miscuglio, incorporatelo alla pasta e lasciate lievitare ancora per 10-15 minuti. Dividete la pasta in due pezzi uguali e modellate entrambi in modo da ottenere due cilindri lunghi 30 cm. Con il matterello schiacciate leggermente ogni dolce nel senso della lunghezza, appoggiando l''attrezzo vicino a uno dei due lati lunghi, in modo che il dolce, lievitando, acquisti la tipica forma asimmetrica. Coprite due piastre da forno con un foglio di carta pergamena imburrata, adagiatevi sopra i Christstollen e lasciateli lievitare per 20-30 minuti, quindi cuoceteli nel forno preriscaldato (200 gradi) per 60 minuti. Trascorso questo tempo togliete i dolci dal forno e, mentre sono ancora caldi, spennellatene la superficie con il burro fuso, poi cospargeteli con lo zucchero a velo profumato con l''interno della stecca di vaniglia.',11405);
INSERT INTO "ricette" VALUES (5597,'Chun Juan Con Salsa Hoi-sin','Pollame','Pollo',4,' -','Per La Pasta:,
200 G Farina Di Frumento,
2 Tazze Latte Di Soia,
3 Uova,
1 Presa Sale,
Olio D''arachidi Per Friggere,
Per Il Ripieno:,
2 Petti Di Pollo,
2 Cipolline Novelle,
2 Cucchiai Olio D''arachidi,
200 G Germogli Di Soia,
50 G Funghi Cinesi (o Champignon) Macerati,
3 Cucchiai Salsa Hoisin,
1 Cucchiaino Fecola,
1 Tazza Brodo Di Pollo,
1 Presa Peperoncino,
1 Tuorlo D''uovo,
Glutammato Monosodico O Punta Di Dado,
Olio Per Friggere','Ovvero Involtini (Primavera) con Carne di Pollo e Germogli di Soia. Pasta: Lavorare tutti gli ingredienti e formare la pastella. Fare le frittatine scaldando la padella e ricoprendola con un velo di olio. Una volta pronte le frittatine tenerle al caldo. Ripieno: Tagliare a strisce sottili i petti di pollo, metterli a rosolare per un minuto mescolando continuamente in una padella contenete un po'' d''olio bollente (sempre quello d''arachidi), aggiungere le cipolle tagliate a strisce, i funghi ed i germogli di soia sgocciolati e tagliuzzati. Continuare la cottura
per un minuto ancora. Unire la salsa Hoisin e legare il tutto con la fecola mescolata al brodo. Insaporite con sale, peperoncino, e glutammato. Distribuire il composto sulle frittatine, chiudere le frittatine e spalmarne i bordi con il tuorlo. Friggere in padella o ad Immersione nell''olio. Alcuni consigli: Come avrete notato i Cinesi usano fare grossi lavori di preparazione e poi la cottura si risolve in 3 minuti di pentola. Si deve avere l''accortezza di tagliare molto finemente tutto (germogli di soia esclusi) pena un eccessiva cottura delle verdure rispetto alla carne. Per ripiegare la pasta sul ripieno bisogna fare attenzione: 1 Si solleva un lembo inferiore fino a ricoprire il ripieno. 2 Si piegano verso l''interno i lati della pastella così da formare un rettangolo. 3 Si spalmano con il tuorlo tutti i lati visibili di pasta. 4 Si arrotola la pasta e si da l''ultima passata con il tuorlo per saldare. Per la Salsa Hoi-sin si chiede ai ristoranti oppure si cerca in negozi specializzati, è nota anche come salsa Barbecue, oppure infine si fa in casa, ecco la ricetta: SALSA HOI-SIN 3 cucchiai di salsa di semi gialli di Soia 2 cucchiai di Zucchero 1 cucchiaio di aceto 1 spicchio d''Aglio pestato 1 cucchiaio di olio di semi di Sesamo 1 cucchiaino di salsa al peperoncino di Caienna Mischiare il tutto... Ovviamente il ripieno può essere di qualsiasi tipo, nei ristoranti Cinesi è facile incontrare il Maiale al posto del pollo per il minor costo di tale carne, oppure un miscuglio di pollo e maiale, poi ancora mettono carota, cavolo cinese (ovviamente), bambù ed altre piacevolezze. Ma gli Involtini vengono anche fatti con Zucca o con base di pesce... a voi la scelta.',5068);
INSERT INTO "ricette" VALUES (5598,'Chupa Pousse','Bevande','Granatina',1,' -','1/6 Granatina,
1/6 Liquore Menta Verde,
1/6 Curacao Blu,
1/6 Liquore Strega,
1/6 Brandy Stock 84,
1/6 Vodka Keglevich','Versare piano piano con l''aiuto del cucchiaino, iniziando dalla granatina, nell''apposito bicchierino cilindrico.',291);
INSERT INTO "ricette" VALUES (5599,'Chupa-chup','Bevande','Liquore Galliano',1,' -','2 Cucchiai Liquore Galliano,
2 Cucchiai Liquore Strega,
2 Cucchiai Crema Di Latte,
Per Servire:,
Alcune Gocce Succo Di Lampone,
Alcune Gocce Curacao Blu,
Alcune Gocce Liquore Galliano','Preparare nello shaker con ghiaccio. Servire nella coppa da champagne spruzzando in superficie alcune gocce di succo di lampone, curacao blu e liquore galliano.',427);
INSERT INTO "ricette" VALUES (5600,'Churchill','Bevande','Whisky',1,' -','3/6 Whisky,
1/6 Vermouth Bianco,
1/6 Cointreau,
1/6 Succo Di Limone','Si prepara nel miscelatore con ghiaccio tritato.',260);
INSERT INTO "ricette" VALUES (5601,'Churchill (2)','Bevande','Whisky',1,' -','1/6 Succo Di Limone,
1/6 Vermouth,
3/6 Whisky,
1/6 Cointreau,
Per Servire:,
1 Chicco D''uva','Agitare vigorosamente nello shaker. Servire nel tumbler, con ghiaccio e un chicco d''uva.',264);
INSERT INTO "ricette" VALUES (5602,'Chutney D''ananas','Dessert','Ananas',4,'Luogo: Melanesia. Luogo: Vanuatu.','1 Ananas Maturo,
1 Tazza Aceto Di Vino Bianco,
500 G Zucchero,
1 Pollice Zenzero Fresco,
3 Spicchi Aglio,
2 Cipolle Grandi,
1/2 Stecca Cannella,
3 Peperoncini Piccanti,
Sale','Sbucciate l''ananas e tagliatelo a cubetti. Tritate lo zenzero, le cipolle, l''aglio e i peperoncini. Mescolatelo insieme allo zucchero, l''aceto e la scorza grattugiata del lime. Aggiustate di sale. Sistemate tutti gli ingredienti in una pentola di coccio e cuocete finché la salsa inizierà ad ispessire.',2547);
INSERT INTO "ricette" VALUES (5603,'Chutney Di Albicocche','Salsa','Albicocche',4,' -','1000 G Albicocche Mature Snocciolate,
1 Cipolla,
3 Spicchi Aglio,
300 G Zucchero,
150 G Uvetta Sultanina,
1 Cucchiaio Radice Di Zenzero Grattugiato,
1 Cucchiaio Sale,
1 Cucchiaio Semi Di Coriandolo Pestati,
1 Bicchiere Aceto Di Vino,
Chutney','Mettere in una pentola capace 1000 g di albicocche mature snocciolate, 1 cipolla affettata e 3 spicchi d''aglio tritati, 300 g. di zucchero, 150 g. di uvetta sultanina, 1 cucchiaio di radice di zenzero grattugiato, 1 cucchiaio di sale, 1 cucchiaio di semi di coriandolo pestati e 1 bicchiere di aceto di vino. Cuocere a fiamma vivace finché le albicocche sono morbide. Scolare il tutto, far restringere il liquido rimasto e versarlo sul chutney. Ottimo con la lingua o il prosciutto al forno.',1933);
INSERT INTO "ricette" VALUES (5604,'Chutney Di Gamberi','Antipasto','Gamberi',6,' -','500 G Gamberi,
1 Foglia Alloro (o 1 Rametto Di Timo),
2 Peperoni Dolci,
1 Limone (succo),
1 Bicchiere Olio D''oliva,
Sale,
Pepe','Cuocere i gamberi a vapore con l''alloro o il timo, sgusciarli. Pestarli nel mortaio insieme ai peperoni abbrustoliti 10 minuti in forno caldo a 200 gradi e pelati, al sugo di limone, sale e pepe. Quando l''impasto è ben lavorato aggiungervi poco per volta l''olio di oliva rimestando velocemente col pestello così da ottenere una specie di crema. Accomodarla in un recipiente da antipasto, farla raffreddare. Servirla con crostini.',1764);
INSERT INTO "ricette" VALUES (5605,'Chutney Di Pomodori Verdi','Contorno','Pomodori Verdi',12,'Preparazione: 30 minuti. Cottura: 90 minuti.','1200 G Pomodori Verdi,
300 G Cipolle,
3 Spicchi Aglio,
175 G Uvetta Sultanina,
350 G Zucchero Nero,
15 G Zenzero In Polvere,
1/2 Cucchiaino Peperoncino Della Giamaica In Polvere,
60 Cl Aceto Di Vino Bianco,
1 Cucchiaino Sale','Lavate i pomodori e tritateli. Pelate le cipolle e tritatele. Mondate l''aglio e schiacciatelo. Risciacquate l''uva passa e sgocciolatela. Mettete pomodori, cipolla, aglio, uva passa e zucchero in una grande casseruola. Mettete lo zenzero, il peperoncino della Giamaica e il sale in una ciotola, aggiungete un po'' di aceto e mescolate. Versate la miscela nella casseruola. Versate l''aceto rimanente nella casseruola, scaldate mescolando a fuoco dolce finché lo zucchero è perfettamente sciolto. Portate a ebollizione, abbassate il fuoco e lasciate sobbollire per un''ora e quindici minuti circa, mescolando ogni tanto. Nel frattempo sbollentate i barattoli, capovolgeteli su un canovaccio. Riempite i barattoli di chutney, copriteli con dischetti di carta paraffinata e chiudeteli ermeticamente. Etichettateli.',2130);
INSERT INTO "ricette" VALUES (5606,'Chutney Di Pomodori Verdi (2)','Salsa','Pomodori Verdi',4,'Luogo: Regno Unito. Luogo: India.','1000 G Pomodori Verdi,
300 G Zucchero Scuro Di Canna,
250 G Aceto Di Vino Bianco,
200 G Uvetta Sultanina,
2 Spicchi Aglio,
40 G Radice Di Zenzero Fresca,
1 Peperoncino Piccante,
1 Cucchiaio Senape In Polvere,
1 Cucchiaino Sale','Lavate i pomodori, divideteli in due, privateli dei semi e tagliuzzateli lasciandoli cadere in una casseruola di acciaio a fondo pesante. Unitevi lo zucchero, l''aceto, l''uvetta lavata e asciugata, l''aglio tritato, la radice di zenzero, pelata e grattugiata, il peperoncino, la senape e il sale. Mettete la casseruola sul fuoco, fate alzare l''ebollizione, quindi abbassate un po'' la fiamma e proseguite la cottura, senza coperchio, per un paio d''ore, fino a quando il composto sarà diventato denso e consistente come una marmellata. Versate il chutney, ancora bollente, in vasetti di vetro [sterilizzati in acqua in ebollizione e ben scaldati in forno] chiudeteli subito e conservateli in ambiente fresco. Questa salsa, di origine indiana, appartiene ormai alla cucina tradizionale anglosassone dove viene usata come classico accompagnamento ad arrosti di carni grasse: oca, anatra e maiale. Può essere servita anche con carni fredde come il pollo lesso, il prosciutto cotto, ecc.',1916);
INSERT INTO "ricette" VALUES (5607,'Ciabattine','Antipasto','Farina Di Grano Duro',10,' -','700 G Farina Bianca,
300 G Farina Di Grano Duro,
35 G Lievito Di Birra,
Olio D''oliva,
Sale','Gli ingredienti sono per 10 ciabattine. Con 150 g di farina bianca, il lievito e un po'' d''acqua tiepida, fare un impasto abbastanza sodo. Ricoprirlo con la restante farina e lasciarlo riposare per circa 3 ore in luogo tiepido. A questo punto, aggiungere 3 cucchiaini di sale e impastare con tanta acqua tiepida (circa 400 g), per ottenere un impasto liscio, ma sodo; lasciarlo lievitare per due ore (oppure fin quando non abbia raddoppiato il proprio volume), quindi sgonfiarlo e formare 10 palline uguali. Con l''aiuto di un matterello, stendere ciascuna pallina a uno spessore di circa 2/3 cm dando una forma leggermente ovale. Far lievitare le ciabattine per circa due ore, poi spennellarle d''olio d''oliva e infornarle a 200/210 gradi fino a quando non avranno assunto un bel colore dorato; volendo congelarle, sfornarle prima che diventino dorate e passarle subito nel congelatore. Si tratta di un pane con pochissima mollica, facilmente digeribile e conservabile nel congelatore. Al momento di consumarlo, estrarlo dal congelatore e metterlo subito nel forno a 200/210 gradi finché non avrà raggiunto la colorazione dorata.',4094);
INSERT INTO "ricette" VALUES (5608,'Ciak','Bevande','Whisky',1,' -','4/10 Whisky,
2/10 Cinzano,
2/10 Cherry Dry,
1/10 Bitter Campari,
1/10 Liquore Galliano,
Per Decorare:,
1 Ciliegina Al Maraschino','Questo cocktail si prepara nel mixing glass con alcuni cubetti di ghiaccio. Si serve nella coppetta da cocktail possibilmente raffreddata e si decora con la ciliegina.',304);
INSERT INTO "ricette" VALUES (5609,'Cialde','Dessert','Uova',6,' -','4 Uova,
500 G Farina,
1 Pizzico Sale,
Olio D''oliva,
1 Bustina Lievito,
125 G Zucchero,
200 G Burro,
1 Pizzico Cannella','Prendete 125 g di farina, acqua, un po'' di lievito e fate una pasta molle. Mescolate il resto della farina con il burro sciolto, la cannella e le uova. Unendo i 2 composti formate una palla, tagliatela a pezzi grossi, arrotolateli e metteteli su una tavola infarinata, lasciandoli riposare per 30 minuti. Ungete, con l''olio, uno stampo per cialde e metteteci dentro un pezzo di pasta. Fate cuocere su ogni lato. Servite le cialde spolverandole con zucchero raffinato e cannella in polvere.',4689);
INSERT INTO "ricette" VALUES (5610,'Cialde All''arancia','Dessert','Albumi',8,' -','200 G Farina,
300 G Zucchero,
180 G Burro,
7 Albumi D''uovo,
1 Cucchiaino Scorza D''arancia Grattugiata,
1 Bicchierino Curacao,
1 Pizzico Vaniglina','Lavorate a lungo con un cucchiaio di legno lo zucchero insieme al burro ammorbidito a temperatura ambiente, in un recipiente di rame non stagnato o di acciaio inossidabile. Quando il composto apparirà cremoso, omogeneo e ben montato, incorporate uno alla volta 5 albumi poi, lentamente, la vaniglina e il curacao. Dopo aver lavorato a lungo provate la densità del composto: fatene cadere un mucchietto sopra un piatto. Se la pasta si espanderà lentamente, la consistenza sarà giusta, se la pasta risulterà troppo densa, dovrete unire ancora uno o due albumi, se al contrario sarà troppo fluida raddensatela con un cucchiaio di farina. Versate l''impasto in una tasca da pasticceria e fatelo uscire a mucchietti ben distanziati sulla piastra del forno imburrata. Cuocete le crespelle in forno alla massima temperatura e levatele appena cominceranno a prendere colore. Mentre sono ancora calde arrotolatele su un cannolo di latta, dando la classica forma della cialda. Dovrete eseguire questa operazione molto velocemente, per non far raffreddare le crespelle (se dovesse accadere rimettete brevemente la placca in forno). Man mano che le cialde sono pronte srotolatele dal cannolo e mettetele a raffreddare sul piatto da portata. Potete servire le cialde così semplicemente, oppure riempite con panna montata o con una crema al cioccolato. Si conservano per parecchi mesi in scatole di latta ben chiuse.',3353);
INSERT INTO "ricette" VALUES (5611,'Cialde Arrotolate','Dessert','Burro',6,' -','75 G Farina,
75 G Zucchero,
100 G Burro,
2 Albumi D''uovo','Togliete il burro dal frigorifero e lasciatelo ammorbidire a temperatura ambiente. Mettetelo in una terrina e lavoratelo sino a renderlo soffice e spumoso, aggiungete lo zucchero e la farina. Montate a neve soda gli albumi e incorporateli delicatamente all''impasto che deve risultare abbastanza morbido. Se non lo fosse aggiungete un altro albume montato. Tirate a sfoglia sottile la pasta, ricavatene dei dischetti e distribuitene la metà sulla piastra del forno imburrata, avendo cura che siano distanziati fra loro. Cuocete per 7-8 minuti in forno preriscaldato a 200 gradi fino a quando hanno assunto un bel colore dorato. Ritirate dal forno. Staccate i biscotti con la spatola e arrotolateli a sigaretta. Quindi fateli raffreddare su una griglia.',1314);
INSERT INTO "ricette" VALUES (5612,'Cialde Di Grano Duro','Contorno','Grano Duro',4,'Preparazione: 5 minuti. Cottura: 25 minuti.','100 G Farina Di Semola Di Grano Duro,
Sale,
Olio D''oliva Extra-vergine','Setacciate la farina con un pizzico di sale e fate la fontana in una ciotola. Cominciate a versare a poco a poco 25 cl di acqua tiepida, amalgamandola via via alla farina, fino a ottenere una pastella cremosa e omogenea. Coprite la ciotola e lasciate riposare per 20-30 minuti. Fate scaldare bene su fiamma media un padellino di circa 15 cm di diametro. Quando sarà ben caldo, ungetelo leggermente passandovi un pezzetto di carta assorbente imbevuta d''olio. Versatevi quindi un piccolo mestolo di pastella e, inclinando e ruotando la padella, distribuite il composto su tutto il fondo in modo uniforme. Lasciate cuocere finché la cialda sarà dorata sui bordi, quindi voltatela (con l''aiuto di un coperchio) e lasciatela cuocere anche dall''altra parte. Quando è pronta, trasferitela su un piatto e piegatela in quattro. Procedete in questo modo fino a esaurire la pastella, ricordandovi ogni volta di ungere la padella con la carta assorbente imbevuta d''olio. Prima di servire le cialde, passatele per pochi minuti nel forno ben caldo o in un tostapane.',1021);
INSERT INTO "ricette" VALUES (5613,'Cialdine Di Grana Con Bresaola','Antipasto','Formaggio Grana',4,'Preparazione: 10 minuti. Cottura: 5 minuti.','80 G Formaggio Grana Grattugiato,
8 Fette Bresaola,
1 Mazzetto Insalata Rucola,
1 Filo Olio D''oliva,
Sale,
Pepe','Dividete il formaggio grana in 8 parti uguali. Formate dei piccoli mucchi, distanziati tra loro, direttamente sulla placca del forno foderata con la carta speciale. Cuocete il formaggio a 220 gradi per circa 5 minuti. Quando vedete che i mucchietti, allargandosi, prendono l''aspetto di cialdine dorate e morbide, spegnete. Fate attenzione a non farle dorare troppo perché diventerebbero amare. Togliete le cialdine dal forno e appoggiatele delicatamente sul mattarello, in modo che prendano una forma ricurva. Pulite la rucola, tagliuzzatela e conditela con un filo d''olio, sale e pepe. Tenete da parte qualche foglia intera per decorare. Sistemate dentro ogni cialda una fettina di bresaola e un po'' di rucola. Portate in tavola.',1686);
INSERT INTO "ricette" VALUES (5614,'Cialdoni Alla Veneziana','Dessert','Caffè',4,'Luogo: Veneto. Luogo: Venezia.','500 G Farina,
500 G Zucchero,
40 G Burro,
10 Cl Panna,
1 Caffè Ristretto,
1 Pizzico Sale','In una ciotola, impastare la farina con lo zucchero e il burro sciolto, la panna e il caffè. Aggiungere 1 pizzico di sale e lavorare l''impasto con un cucchiaio di legno fino ad ottenere una pastella morbida. Versare negli appositi stampi di ferro con un cucchiaio e cuocere i cialdoni. Si servono caldi, ripiegati in quattro.',4244);
INSERT INTO "ricette" VALUES (5615,'Cialdoni Alla Veneziana (2)','Dessert','Caffè',4,'Luogo: Veneto. Luogo: Venezia.','500 G Farina,
500 G Zucchero,
40 G Burro,
10 Cl Latte,
1 Caffè Ristretto,
1 Pizzico Sale','In una ciotola, impastare la farina con lo zucchero e il burro sciolto, il latte e il caffè. Aggiungere 1 pizzico di sale e lavorare l''impasto con un cucchiaio di legno fino ad ottenere una pastella morbida. Versare negli appositi stampi di ferro con un cucchiaio e cuocere i cialdoni. Si servono caldi, ripiegati in quattro.',3915);
INSERT INTO "ricette" VALUES (5616,'Ciambella','Dessert','Burro',6,' -','100 G Farina Bianca,
100 G Farina Gialla,
100 G Burro,
100 G Zucchero,
3 Tuorli D''uovo,
1 Albume D''uovo,
3 Cucchiai Latte,
1 Bustina Lievito','Unire le due farine, lo zucchero e i tuorli. Mescolare e poco alla volta unire il burro fuso e il latte. Incorporare l''albume montato a neve e il lievito. Mescolare rapidamente, versare l''impasto in uno stampo da ciambella imburrato e infarinato e cuocere in forno preriscaldato a 200 gradi per 30 minuti.',2203);
INSERT INTO "ricette" VALUES (5617,'Ciambella (2)','Dessert','Burro',8,' -','400 G Farina Bianca,
300 G Zucchero,
240 G Burro,
100 G Latte,
4 Uova,
1 Bustina Lievito Per Dolci,
1 Tazzina Caffè,
Zucchero A Velo','Montate burro e zucchero fino a ottenere un composto spumoso, incorporatevi le uova intere, ila tazzina di caffè, la farina, il lievito, il latte. Imburrate e infarinate uno stampo col buco, versatevi l''impasto e cuocete a 180 gradi per un''ora. Sformate. Servite la ciambella cosparsa di zucchero a velo.',4718);
INSERT INTO "ricette" VALUES (5618,'Ciambella Al Cacao','Dessert','Cacao Dolce',4,' -','80 G Burro,
80 G Farina,
100 G Cacao Dolce,
75 Cl Latte,
75 G Zucchero','Sciogliere il burro, unire la farina, stemperandola bene, poi aggiungere il cacao, lo zucchero e diluire con il latte già bollito. Mescolare su fuoco dolce finché il composto sarà denso. Versarlo in uno stampo a ciambella e, appena freddo, far rassodare in frigorifero per 3 ore.',1868);
INSERT INTO "ricette" VALUES (5619,'Ciambella Al Cioccolato','Dessert','Cioccolato',4,' -','1 1/2 Tazza Farina,
1 Bustina Lievito Per Dolci,
3 Cucchiai Cacao In Polvere,
1 Tazza Zucchero,
1 Tazza Acqua,
1 Fialetta Vaniglia,
1 Cucchiaio Aceto Di Vino Bianco,
1/2 Tazza Olio D''oliva Extra-vergine,
Per La Glassa:,
1 Tazza Zucchero A Velo,
1 1/2 Cucchiaino Cacao,
1 Cucchiaio Burro,
Acqua Calda','Accendere il forno a 180 gradi. Imburrare una tortiera per ciambelle (col buco) e cospargerla di farina bianca. In una terrina mescolare la farina, il cacao, il lievito, lo zucchero e l''acqua, aggiungere la vaniglia, l''aceto e l''olio e mescolare molto bene gli ingredienti (possibilmente usando una frusta)per non formare dei grumi. Versare il composto nella tortiera e infornare per 40 minuti. Poi farlo intiepidire, rovesciare lo stampo su un piatto da portata e coprire la ciambella con la glassa. Per preparare la glassa: Mescolare lo zucchero a velo, il cacao, il burro sciolto e un po'' d''acqua calda fino ad ottenere una crema liscia (più acqua si usa più la glassa risulta liquida: fare quindi attenzione!',2161);
INSERT INTO "ricette" VALUES (5620,'Ciambella Al Paté Di Lenticchie','Antipasto','Lenticchie',4,'Luogo: Lombardia.','200 G Lenticchie,
100 G Burro,
40 G Gherigli Di Noci,
1 Foglia Alloro,
1 Patata,
Sale,
Pepe,
Maggiorana','Lessare le lenticchie con la patata affettata sottilmente e la foglia di alloro. A fine cottura salare, pepare e spolverare con maggiorana. Eliminare la foglia di alloro e passare al setaccio. Unire il burro fuso e i gherigli di noci e versare il composto in uno stampo a ciambella. Far raffreddare e mettere in frigo per almeno 5 ore. Sformare sul piatto di portata e servire a fette.',1803);
INSERT INTO "ricette" VALUES (5621,'Ciambella All''uvetta','Dessert','Uvetta Sultanina',6,' -','250 G Farina,
150 G Fecola,
200 G Burro,
200 G Zucchero,
100 G Uvetta Sultanina,
3 Tuorli D''uovo,
1 Bustina Lievito,
Sale,
Farina,
Burro','Far ammorbidire l''uvetta in acqua tiepida. Lavorare il burro, lo zucchero, la fecola, la farina, il lievito e aggiungere i tuorli uno alla volta. Se l''impasto dovesse essere troppo duro unire 1 albume. Strizzare l''uvetta e mescolarla all''impasto. Imburrare e infarinare una tortiera con foro centrale e versarvi l''impasto. Cuocere in forno caldo a 190 gradi per circa 1 ora. Sformare la ciambella calda e lasciarla raffreddare.',5257);
INSERT INTO "ricette" VALUES (5622,'Ciambella Alla Ricotta','Dessert','Ricotta',4,' -','400 G Ricotta,
1 Limone,
300 G Zucchero,
300 G Farina,
3 Uova,
1 Bustina Lievito,
1 Pizzico Sale','Stemperare in 1 ciotola la ricotta con il succo e la scorza di limone; lavorare i tuorli con lo zucchero e amalgamarvi la ricotta. Setacciare insieme farina e lievito e unirli a cucchiaiate al composto di uova e ricotta. Infine, montare a neve gli albumi con 1 pizzico di sale e amalgamare anch''essi al composto. Accendere il forno a 180 gradi. Versare il composto nello stampo imburrato e infarinato e infornare per 1 ora. Lasciar riposare la ciambella per 5 minuti, sformarla e farla raffreddare.',3001);
INSERT INTO "ricette" VALUES (5623,'Ciambella Alla Ricotta Glassata','Dessert','Ricotta',4,' -','300 G Zucchero,
1 Limone,
3 Uova,
400 G Ricotta,
320 G Farina,
1 Bustina Lievito Per Dolci,
1 Cucchiaino Gelatina Di Lamponi,
200 G Zucchero A Velo,
1 Pizzico Sale,
1 Cucchiaio Confettini Di Zucchero (bianchi E Rosa),
Codetta Di Zucchero,
Per Lo Stampo:,
Burro','Lavorate i tuorli con lo zucchero e la scorza grattugiata del limone, poi unite la ricotta stemperata con la forchetta e quindi 300 g di farina setacciata con il lievito. Amalgamate infine gli albumi montati a neve con un pizzico di sale. Imburrate e infarinate leggermente uno stampo da ciambella, versatevi il composto e cuocete un''ora nel forno già caldo a 180 gradi. Fate raffreddare il dolce su una gratella. Lavorate lo zucchero a velo con 2 cucchiai di succo di limone filtrato e quando il composto ricade come un nastro amalgamatevi la gelatina. Spalmate il dolce con la glassa, quindi fatevi aderire i confettini e la codetta coprendo il più possibile la superficie della ciambella.',4752);
INSERT INTO "ricette" VALUES (5624,'Ciambella Alle Carote','Dessert','Carote',6,' -','140 G Farina,
150 G Zucchero Grezzo,
2 Carote,
2 Uova,
1/2 Bustina Lievito,
1/2 Bicchiere Olio D''oliva,
30 G Burro,
50 G Uvetta Sultanina,
20 G Noci,
2 Cucchiai Latte,
1 Pizzico Zenzero,
1 Pizzico Noce Moscata,
Abbondante Zucchero A Velo,
1 Puntina Sale','In una terrina mescolate la farina, lo zucchero, il lievito, una puntina di sale, un pizzico di zenzero e uno di noce moscata. Aggiungete due cucchiai di latte, mezzo bicchiere d''olio, il burro fuso e le uova. Mescolate fino a ottenere un impasto omogeneo. Incorporatevi l''uvetta, le noci tritate e amalgamate. Infine aggiungete le carote mondate, lavate e tritate finemente. Imburrate uno stampo a ciambella, versatevi il composto e cuocete in forno preriscaldato a 170 gradi per circa un''ora. Ritirate, lasciate raffreddare bene. Sformate, cospargete la ciambella con abbondante zucchero a velo e servitela.',2610);
INSERT INTO "ricette" VALUES (5625,'Ciambella Alle Carote (2)','Dessert','Carote',4,' -','500 G Farina 0,
250 G Carote Novelle,
25 G Lievito Di Birra,
2 Fettine Zenzero Fresco (facoltativo),
1 Tuorlo D''uovo,
Panna Da Cucina,
Olio D''oliva,
Sale,
Pepe','Nella farina a fontana mettere carote grattugiate, sale, lievito sciolto in poca panna tiepida, zenzero grattugiato e pepe. Impastare unendo poca alla volta acqua tiepida per ottenere un impasto morbido. Far lievitare fino al doppio del volume. Lavorare ancora, formare una ciambella e metterla sulla piastra unta. Far lievitare per 1 ora, pennellare con il tuorlo sbattuto con olio e cuocere in forno già caldo a 220 gradi per 1 ora.',2656);
INSERT INTO "ricette" VALUES (5626,'Ciambella Allo Yogurth','Dessert','Yogurth',8,' -','250 G Yogurth Magro,
375 G Farina,
375 G Zucchero,
60 G Olio D''oliva,
3 Uova Intere,
1 Busta Lievito Bartolini','Amalgamare tutto, mettere in una teglia precedentemente imburrata il composto e cuocere a 150 gradi a forno caldo per 20 minuti.',3671);
INSERT INTO "ricette" VALUES (5627,'Ciambella Allo Yogurth (2)','Dessert','Yogurth',4,' -','125 G Yogurth Intero,
80 G Zucchero,
50 G Farina Integrale,
50 G Maizena,
2 Uova,
Lievito In Polvere,
Zucchero A Velo,
Sale,
Burro','In una ciotola montate le uova con lo zucchero e un pizzico di sale, fino a ottenere un composto cremoso. Unite poco alla volta la farina, la fecola setacciata con un po'' di lievito, incorporate lo yogurth mescolando delicatamente. Imburrate e infarinate uno stampo, versatevi l''impasto e cuocete in forno a 180 gradi per 40 minuti. Sformate sulla gratella, lasciate raffreddare. Passate la ciambella su un piatto da portata, spolverizzatela di zucchero a velo e servite.',1730);
INSERT INTO "ricette" VALUES (5628,'Ciambella Della Nonna','Dessert','Farina',10,' -','400 G Farina,
150 G Burro,
250 G Zucchero,
1 Bicchiere Latte,
1 Limone (scorza Grattugiata),
3 Tuorli D''uovo,
1 Pizzico Sale,
1 Bustina Lievito In Polvere,
1 Bustina Vaniglia In Polvere,
1 Bicchierino Liquore All''anice,
2 Cucchiai Zucchero In Granella,
1 Manciata Mandorle Pelate','Mettete il burro nello stampo che userete per cuocere la ciambella e fatelo fondere nel forno a calore moderato. Quando è completamente liquefatto, e prima che arrivi a friggere, toglietelo dal forno e lasciatelo raffreddare. Ponete i tuorli in una terrina. Unite lo zucchero e sbattete con una frusta fino ad ottenere un composto chiaro e spumoso. Aggiungete poco alla volta la farina setacciata, alternandola al latte e al burro fuso tiepido. Mescolate con un cucchiaio di legno fino a quando gli ingredienti si saranno ben amalgamati e avranno formato un composto liscio e cremoso. Aromatizzatelo con la scorza grattugiata di un limone, una bustina di vaniglia in polvere e un bicchierino di liquore all''anice, infine incorporatevi il lievito in polvere, fatto scendere da un setaccio. Trasferite il composto nello stampo usato prima, che sarà rimasto leggermente unto di burro, cospargetelo con lo zucchero in granella, disponete qua e là le mandorle pelate e passate nel forno già caldo (180 gradi) per circa 40 minuti. Al termine verificate il grado di cottura del dolce infilzandolo con uno stecchino: se questo fuoriesce asciutto, spegnete il forno, lasciate riposare la ciambella per 5 minuti, quindi sfornatela e fatela raffreddare completamente. Sformate il dolce freddo su un piatto di portata e servite.',4201);
INSERT INTO "ricette" VALUES (5629,'Ciambella Di Banane','Dessert','Banane',6,' -','300 G Farina,
100 G Burro,
1 Uovo,
100 G Zucchero,
3 Banane,
1 Bustina Lievito Vanigliato,
100 G Gherigli Di Noci,
1 Cucchiaio Pinoli,
1 Manciata Uvetta Sultanina,
Brandy,
Per La Glassa:,
4 Cucchiai Marmellata Di Albicocche,
20 G Burro,
3 Cucchiai Panna','In una ciotola lavorate molto bene l''uovo con lo zucchero ed il burro ammorbidito, poi unite le banane precedentemente schiacciate con una forchetta fino a ridurle in purea. Incorporate al composto di uovo e zucchero la farina setacciata con il lievito, i gherigli di noci e i pinoli tritati, l''uvetta ammollata in acqua e brandy. Versate il composto in uno stampo da ciambella precedentemente imburrato e infarinato, poi passate in forno già caldo a 180 gradi per circa 30 minuti. Per la glassa, fate fondere il burro, unite la panna e la marmellata di albicocche e lavorate fino a ottenere una crema. Sformate la ciambella, versatevi la glassa e decorate con gherigli di noci e pinoli.',4311);
INSERT INTO "ricette" VALUES (5630,'Ciambella Di Carote Con Riso','Contorno','Carote',8,' -','6 Carote,
500 G Riso,
2 Uova,
1 Cucchiaio Prezzemolo Tritato,
Sale','Fate cuocere per circa 30 minuti le carote, raschiate e lavate, in acqua salata, e tagliatele poi in dischetti. Bollite anche il riso, scolatelo ancora al dente e raffreddatelo sotto acqua corrente. In una terrina unite al riso le carote, le uova, il prezzemolo tritato; salate, mescolate bene e versate il composto in uno stampo a forma di ciambella, precedentemente imburrato. Ponete in forno caldo per 20 minuti. Rovesciate la forma su un piatto da portata e servite.',2023);
INSERT INTO "ricette" VALUES (5631,'Ciambella Di Natale','Dessert','Ciliegine Candite',4,' -','240 G Farina,
150 G Burro Morbido Più Un Poco Per Lo Stampo,
150 G Zucchero,
4 Uova A Temperatura Ambiente,
1 Bustina Lievito Per Dolci,
1 Limone,
1 Pizzico Sale,
Per Il Decoro:,
800 G Ciliegine Candite Rosse E Verdi (o Piccoli Frutti)','Setacciate la farina (meno un cucchiaio) con il lievito. Mettete il burro a pezzetti in una ciotola, unitevi lo zucchero e un pizzico di sale e lavoratelo a lungo con il cucchiaio di legno fino ad avere un composto gonfio e spumoso. Sempre mescolando, aggiungete le uova intere, uno alla volta non aggiungendo il successivo fino a quando il precedente non sarà perfettamente amalgamato e, infine, poco alla volta, la farina con il lievito. Lavorate energicamente l''impasto per qualche minuto: dovrà risultare piuttosto compatto e consistente. Imburrate uno stampo ad anello (diametro di 24 cm), infarinatelo e scuotetelo per fa cadere l''eccesso di farina. Versateci l''impasto, che dovrà arrivare circa a 3/4 d''altezza e livellate la superficie. Mettete la ciambella nel forno già caldo a 180 gradi e lasciate cuocere per circa 70 minuti. Prima di toglierla dal forno, bucatela con uno stuzzicadenti: se rimane perfettamente asciutto, la cottura è completa. Lasciate raffreddare la ciambella nello stampo prima di sformarla. Per decorarla, infilzate ogni piccolo frutto con uno stuzzicadenti e coprite completamente la superficie della ciambella riempiendo i vuoti con le foglioline verdi. Potete preparare la ciambella anche con molto anticipo: ben avvolta in carta oleata o chiusa in una scatola di latta, la ciambella si conserva bene anche per una settimana.',5343);
INSERT INTO "ricette" VALUES (5632,'Ciambella Di Noci Al Rum','Dessert','Noci',12,' -','350 G Farina,
350 G Burro,
350 G Zucchero,
150 G Banana Mondata,
130 G Noci Sgusciate,
80 G Rum,
4 Uova,
1 Bustina Lievito Per Dolci,
1 Pizzico Sale,
1 Limone,
Per Lo Stampo:,
Burro,
Zucchero','Mettete il burro in una ciotola e montatelo con lo sbattitore elettrico. Unitevi lo zucchero e un pizzichino di sale. Amalgamate una alla volta 3 delle uova, intere. Setacciate la farina con il lievito e unitene metà, poi amalgamate il quarto uovo e la farina restante. Aromatizzate con il rum, quindi unite le noci tritate e le banane, frullate con il succo spremuto e filtrato del limone. Imburrate bene uno stampo alto, da kugelhupf, rivestitelo di zucchero e versatevi il composto. Cuocete nel forno a 180 gradi per circa un''ora e 15 minuti (provate il grado di cottura con uno stecchino, che dovrà uscire asciutto). Lasciate raffreddare, sformate e servite con una crema pasticciera preparata con mezzo litro di latte, 4 tuorli d''uovo, 50 g di farina e 50 g di zucchero, raffreddata e mescolata con 200 g di panna montata.',7469);
INSERT INTO "ricette" VALUES (5633,'Ciambella Di Patate','Dessert','Patate',4,' -','500 G Pasta Sfoglia Surgelata,
250 G Patate,
90 G Burro,
80 G Zucchero,
2 Uova,
100 G Canditi Misti,
4 Cucchiai Panna,
Zucchero A Velo','Fate scongelare la pasta sfoglia. Lavate le patate e cuocetele per 4 minuti, poi sbucciatele e passatele allo schiacciapatate. Montate a crema il burro (meno 1 pezzettino che servirà per ungere) con lo zucchero semolato; unite i tuorli, il passato di patate e i canditi;mescolate ed incorporate al composto la panna e gli albumi montati. Scaldate il forno a 220 gradi. Stendete la pasta sfoglia in un rettangolo sottile e distribuirvi sopra il composto preparato, livellandolo e lasciando un bordo di pasta scoperto di 3-4 cm. Arrotolate la sfoglia, saldate i lembi di pasta, togliete l''eccedenza alle estremità e chiudete il rotolo a ciambella. Trasferitela, delicatamente, sulla placca del forno unta con il burro tenuto da parte e cuocetela in forno per 50 minuti circa.Servitela tiepida o fredda, cosparsa con zucchero a velo.',3894);
INSERT INTO "ricette" VALUES (5634,'Ciambella Di Ricotta','Dessert','Ricotta Romana',4,' -','500 G Ricotta Romana,
5 Cl Latte,
50 G Fecola Di Patate,
150 G Zucchero,
3 Uova,
1 Bicchierino Vino Marsala,
1 Arancia (scorza Grattugiata),
1 Bustina Lievito Vanigliato,
20 G Burro,
1 Bustina Zucchero A Velo','In una terrina mettete la ricotta, il latte, i tre tuorli d''uovo e lo zucchero e lavorate bene il composto. Aggiungete quindi la farina, la fecola di patate, la scorza dell''arancia, il marsala e, sempre mescolando con un cucchiaio di legno, la metà del burro e il lievito vanigliato. A parte, montate a neve ben ferma gli albumi e incorporateli delicatamente al composto. Ungete con il resto del burro uno stampo per ciambelle e versatevi l''impasto. Infornate a 200 gradi per 40 minuti circa. Quando la ciambella è dorata, toglietela dal forno e lasciatela raffreddare per mezz''ora poi sfornatela e spolverate di zucchero a velo.',2019);
INSERT INTO "ricette" VALUES (5635,'Ciambella Di Ricotta (2)','Dessert','Ricotta',8,' -','500 G Ricotta,
500 G Zucchero,
5 Tuorli D''uovo,
1 Limone (scorza),
500 G Farina,
2 Buste Vaniglina,
40 G Burro,
1 Bustina Lievito Per Dolci','Montare le chiare a neve aggiungervi gradatamente lo zucchero, i tuorli d''uovo, la ricotta, la vaniglina, il burro e la scorza di limone. Unite all''impasto ottenuto la farina e il lievito. Amalgamare delicatamente ma poi lavorare bene. Ungere lo stampo e mettere l''impasto e cuocere a temperatura moderata per circa 50 minuti.',5137);
INSERT INTO "ricette" VALUES (5636,'Ciambella Di Ricotta (3)','Dessert','Ricotta',4,' -','300 G Farina,
300 G Ricotta,
250 G Zucchero,
3 Uova,
1 Limone,
1 Bustina Lievito,
1 Pizzico Sale','Fate sciogliere lo zucchero lavorandolo a lungo con le uova fino ad ottenere una crema soffice e spumosa. Poca alla volta unite alla crema la farina mischiata con il lievito e un pizzico di sale; incorporate poi anche il succo e la buccia grattugiata del limone e la ricotta. Mescolate con cura fino ad amalgamare bene gli ingredienti poi versate l''impasto in una forma per ciambelle imburrata e leggermente cosparsa di farina. Fate quindi cuocere in forno caldo per 30 minuti, lasciate raffreddare e servite.',2665);
INSERT INTO "ricette" VALUES (5637,'Ciambella Facile','Dessert','Uova',4,' -','250 G Fecola Di Patate,
100 G Burro,
200 G Zucchero,
3 Uova,
1/2 Bustina Lievito,
Zucchero Vanigliato,
Latte,
Sale,
Farina','Togliete il burro dal frigorifero un''ora prima di preparare il dolce. Quindi lavoratelo a lungo con lo zucchero fino a renderlo una crema soffice e spumosa. Insaporitelo con un pizzico di sale. Incorporatevi i tre tuorli. Mescolate la fecola con il lievito e una bustina di zucchero vanigliato e setacciandola unitela al composto di burro. Ammorbidite il tutto con alcuni cucchiai di latte e poi incorporatevi gli albumi montati a neve soda. Imburrate e infarinate uno stampo a ciambella e versatevi l''impasto che deve arrivare solo a metà. Ponete il recipiente in forno preriscaldato a 170 gradi per circa 40 minuti.',3082);
INSERT INTO "ricette" VALUES (5638,'Ciambella Marmorizzata','Dessert','Latte',8,' -','400 G Farina,
80 G Burro,
80 G Zucchero,
1 Bicchiere Latte,
30 G Cacao,
2 Uova,
1/2 Bustina Lievito,
Zucchero A Velo,
Sale','In una terrina mescolate la farina con il lievito, lo zucchero e un pizzico di sale. Sgusciatevi le uova, aggiungete il burro fuso e il latte. Amalgamate fino a ottenere un impasto liscio e omogeneo. A un terzo della pasta incorporate il cacao. Imburrate e infarinate uno stampo a ciambella, mettetevi la pasta bianca e sopra lasciate cadere quella al cacao. Cuocete in forno preriscaldato a 180 gradi per 35-40 minuti. Ritirate, lasciate riposare la ciambella per un quarto d''ora, poi sformatela. Spolverizzatela con lo zucchero a velo e servite.',2622);
INSERT INTO "ricette" VALUES (5639,'Ciambella Pugliese','Dessert','Patate Lesse',4,'Luogo: Puglia.','125 G Pasta Da Pane,
125 G Zucchero Semolato,
125 G Patate Lesse,
50 G Strutto,
5 Uova,
Farina Bianca,
Poco Burro','Alle patate ancora calde, unire lo zucchero, le uova, la pasta da pane e lo strutto. Impastare gli ingredienti unendo la quantità di farina per ottenere una pasta morbida. Formare una palla, infarinarla e avvolgerla in un tovagliolo. Lasciarla riposare per 24 ore. Lavorare la pasta. Formare con essa una ciambella e collocarla in uno stampo con buco centrale imburrato e spolverizzato di farina. Far rilievitare la ciambella per un''ora. Cuocere nel forno già caldo. Spolverizzare con zucchero.',2236);
INSERT INTO "ricette" VALUES (5640,'Ciambella Salata','Antipasto','Uova',4,'Preparazione: 20 minuti. Cottura: 60 minuti. Calorie: 612.','500 G Pasta Da Pane,
6 Uova,
2 Cipolle,
2 Cucchiai Olio D''oliva,
Sale','Sbucciate le cipolle, lasciatele immerse in acqua fredda per 10 minuti in modo che perdano l''amaro, poi tritatele finemente ed incorporatele alla pasta da pane, lavorando rapidamente sulla spianatoia infarinata ed incorporando contemporaneamente l''olio d''oliva. Arrotolate la pasta a forma di ciambella ed inseritevi in superficie, a distanza regolare l''una dall''altra, le uova lavate e asciugate accuratamente. Cuocete la ciambella in forno molto caldo per 1 ora circa. Servitela fredda al mattino, come prima colazione pasquale. Potete variare l''aggiunta di cipolle con quella di una manciata di semi di finocchio, sia incorporati nella pasta, sia cosparsi in superficie.',2057);
INSERT INTO "ricette" VALUES (5641,'Ciambella Semplice','Dessert','Uova',4,'Luogo: Emilia-Romagna. Preparazione: 75 minuti.','1/2 Bicchiere Latte,
2 Uova,
200 G Zucchero,
200 G Farina,
50 G Burro,
Scorza Di Limone Grattugiata,
Lievito Per Mezzo Chilo Di Farina','Impastare dapprima zucchero, tuorli e farina, aggiungere il latte, la scorza di limone, il burro fuso, le chiare montate e infine il lievito. Cuocere 45 minuti a 180 gradi.',2083);
INSERT INTO "ricette" VALUES (5642,'Ciambella Vellutata','Dessert','Burro',4,' -','200 G Farina,
100 G Burro,
1/2 Bicchiere Latte,
2 Uova,
40 G Zucchero,
10 G Lievito,
2 Cucchiai Rum,
1 Pizzico Sale','Togliete il burro dal frigorifero per farlo ammorbidire. In una terrina disponete la farina a fontana. Scaldate leggermente il latte, scioglietevi lo zucchero, un pizzico di sale, il lievito e versate il tutto al centro della farina. Mescolate con un cucchiaio di legno, aggiungete il burro a pezzetti lavorando la pasta con le mani, poi incorporatevi un uovo alla volta e due cucchiai di rum. Coprite con un tovagliolo e lasciate lievitare 8 ore. Disponete la pasta in uno stampo a ciambella imburrato e cuocete in forno preriscaldato a 170 gradi per 40 minuti. Ritirate, lasciate riposare un quarto d''ora e sformate.',1987);
INSERT INTO "ricette" VALUES (5643,'Ciambelle Ai 5 Cereali','Antipasto','Farina Integrale',4,' -','Per 8 Ciambelline:,
270 G Farina Integrale,
50 G Farina Di Farro,
50 G Fiocchi D''avena,
50 G Fiocchi Di Soia,
20 G Lievito Di Birra,
1 Cucchiaio Fruttosio,
2 Cucchiaini Sale,
Per La Teglia:,
Farina Integrale,
Olio D''oliva,
Per Cospargere:,
Semi Di Girasole, Zucca, Papavero, Sesamo E Lino','Per la pasta: versare i vari tipi di farina integrale, i fiocchi di soia e di avena in un''impastatrice e mescolare. Versare il fruttosio, il sale, il lievito di birra sciolto in 35 cl d''acqua e impastare per 10 minuti, fino a ottenere un impasto elastico (aggiungere eventualmente un cucchiaio d''acqua). Spolverare la pasta con un po'' di farina, coprire il recipiente con un canovaccio e lasciare lievitare per circa 40 minuti. Dividere l''impasto in 8 parti e formare delle palle, avvolgerle nella carta trasparente e farle riposare per 5 minuti. Per le ciambelle: infarinare il piano di lavoro e lavorare la pasta per formare delle ciambelline: potete fare dei rotoli e poi congiungere le estremità oppure formare un buco al centro della palla e allargarlo con le dita. Porre le ciambelle in una teglia distanziandole. Coprirle con un canovaccio e lasciarle lievitare per circa 30 minuti. Riscaldare il forno a 225 gradi. Ricoprire un''altra teglia con la carta da forno. Portare a ebollizione una pentola d''acqua: cuocervi 2-3 ciambelle alla volta per un minuto, rivoltandole delicatamente. Poi, scolarle e farle sgocciolare su un canovaccio. Per servire: disporre le ciambelle sulla teglia foderata in precedenza con la carta da forno e cospargerle con i vari semi. Infornare per 20-25 minuti, finché la superficie non sia ben dorata.',2640);
INSERT INTO "ricette" VALUES (5644,'Ciambelle Al Formaggio','Antipasto','Formaggio Pecorino Dolce',4,'Luogo: Umbria.','800 G Pasta Di Pane Già Lievitata,
120 G Formaggio Pecorino Dolce,
3 Cucchiai Olio D''oliva Extra-vergine,
Per La Placca Da Forno:,
Olio D''oliva','Le dosi sono per 10 ciambelle. Grattugiare metà del pecorino e fare a pezzetti l''altra metà. Lavorare la pasta di pane con il formaggio e l''olio, ricavarne un panetto e fare di nuovo lievitare. Ricavare dall''impasto tante ciambelle, disporle piuttosto distanti tra loro su una placca da forno unta e cuocerle a forno caldo (200 gradi) per una ventina di minuti. Lasciare raffreddare prima di servire.',3443);
INSERT INTO "ricette" VALUES (5645,'Ciambelle Al Latte','Dessert','Latte',4,'Luogo: Ciociaria. Luogo: Lazio.','50 Cl Latte,
50 Cl Olio D''oliva,
500 G Zucchero,
2 Bustine Lievito Pane Degli Angeli,
1 Bustina Vaniglina,
Farina,
Alchermes','In un grosso recipiente si versano tutti gli ingredienti e si lavorano. Quando il composto diventa abbastanza consistente, si modellano le ciambelline che vengono cosparse di Alchermes e zucchero. Successivamente esse vengono messe in una teglia imburrata e infornate quando già il forno è caldo (180 gradi).',7235);
INSERT INTO "ricette" VALUES (5646,'Ciambelle Al Vino','Dessert','Vino',4,'Luogo: Ciociaria. Luogo: Lazio.','50 Cl Vino,
50 Cl Olio D''oliva,
500 G Zucchero,
2 Bustine Lievito Pane Degli Angeli,
1 Bustina Vaniglina,
Farina','In un grosso recipiente si versano tutti gli ingredienti e si lavorano. Quando il composto diventa abbastanza consistente, si modellano le ciambelline che vengono cosparse di zucchero. Successivamente esse vengono messe in una teglia imburrata e infornate quando già il forno è caldo (180 gradi).',7205);
INSERT INTO "ricette" VALUES (5647,'Ciambelle All''anice','Antipasto','Anice',4,' -','1 Bicchiere Vino Bianco Secco,
1 Bicchiere Olio D''oliva,
1 Bicchiere Zucchero,
Farina,
1 Pugno Anice,
Burro Per La Placca Del Forno','Versare in un recipiente il vino, l''olio, lo zucchero e l''anice. Unire la farina fino ad ottenere un impasto elastico ed omogeneo. Ricavare dall''impasto dei cordoni di pasta del diametro di un dito e da questi tante ciambelline. Sistemarle su una placca da forno imburrata e cuocerle in forno caldo a 180 gradi per circa 30 minuti.',2142);
INSERT INTO "ricette" VALUES (5648,'Ciambelle Con Il Vino','Dessert','Vino',4,' -','50 Cl Vino,
50 Cl Olio D''oliva,
500 G Zucchero,
1 Cartina Lievito Per Dolci (bertolini),
1 Uovo,
1 Cucchiaio Semi Di Anice,
1000 G Farina','Metti da parte un po'' di zucchero. Impasta fino ad amalgamare bene tutti gli ingredienti e fanne delle ciambelle da intingere nella parte superiore nello zucchero messo da parte. Riscalda il forno a 180 gradi. Metti in una teglia, ricoperta con carta da forno o imburrata e infarinata, le ciambelle che dovranno cuocere per 30 minuti circa.',10152);
INSERT INTO "ricette" VALUES (5649,'Ciambelle Di Casa','Dessert','Mandorle',4,' -','400 G Farina Setacciata,
100 G Mandorle Tostate Pestate Nel Mortaio,
200 G Zucchero Fine,
1 Uovo Intero,
50 G Burro Ridotto In Crema,
10 G Bicarbonato,
1 Pizzico Sale,
Poca Farina,
Burro','Disporre la farina a fontana sul tavolo Riunire nel mezzo il burro, il pesto di mandorle, lo zucchero, l''uovo, il bicarbonato e il sale. Impastare, ricavarne delle piccole ciambelle e allinearle sulla placca imburrata e infarinata. Passarle al forno a calore vivace e ritirarle ben cotte e colorate.',4114);
INSERT INTO "ricette" VALUES (5650,'Ciambelle Di Yemma','Dessert','Patate',8,' -','1000 G Patate,
2000 G Farina,
8 Uova Intere,
Poco Sale,
1 Limone (scorza Grattugiata),
100 G Burro,
1 Bicchiere Olio D''oliva,
3 Cubetti Lievito Di Birra','Lessare le patate, passarle e farle raffreddare. Aggiungere gli altri ingredienti ed impastare il tutto. Formare le ciambelle e farle ricrescere per un po''. Infine friggerle in abbondante olio di semi, scolarle e passarle nello zucchero.',10223);
INSERT INTO "ricette" VALUES (5651,'Ciambelle Rustiche','Antipasto','Sugna',4,'Luogo: Calabria.','500 G Pasta Da Pane,
1 Cucchiaio Sugna,
Sale,
1 Pizzico Peperoncino Rosso In Polvere,
8 Uova','Aggiungete alla pasta da pane la sugna, il sale e il peperoncino in polvere e lavoratela fino a quando sarà diventata elastica, riunitela a palla e mettetela a lievitare in un luogo tiepido per un paio d''ore. Dividetela, formate quattro ciambelle e guarnitele con le uova crude con il loro guscio. Fate cuocere in forno a calore moderato.',2136);
INSERT INTO "ricette" VALUES (5652,'Ciambelle Ruzze','Dessert','Vino Bianco',4,'Luogo: Lazio.','500 G Farina,
250 G Zucchero,
1 Manciata Semi Di Anice,
1 1/2 Bicchiere Vino Bianco,
1/2 Bicchiere Olio D''oliva','Sulla spianatoia setacciare a fontana la farina, fare un incavo nel centro, versarvi lo zucchero, il vino, l''olio e i semi di anice. Impastare. La pasta deve risultare non troppo morbida. Dividerla in tanti tocchetti, formare dei cilindretti e unirli alle due estremità per formare delle ciambelline del diametro di circa 5 cm. Disporle quindi in una placca da forno già infarinata, spennellare con vino e zucchero e infornare a 180 gradi per mezz''ora.',3433);
INSERT INTO "ricette" VALUES (5653,'Ciambelline','Dessert','Uova',4,' -','400 G Zucchero,
400 G Farina,
80 G Burro,
4 Uova,
Olio D''oliva','Far sciogliere il burro in un pentolino senza farlo bollire. In una terrina rompere le uova, in una zuppiera mettere la farina e aggiungere le uova mescolando bene. Versare il burro e lo zucchero, continuare a mescolare fino a formare un impasto consistente. Con le mani formare delle ciambelline. Friggerle nell''olio bollente, poi passarle nello zucchero e lasciarle raffreddare prima di servire.',4522);
INSERT INTO "ricette" VALUES (5654,'Ciambelline (2)','Dessert','Uova',8,' -','600 G Farina,
175 G Zucchero (6 Cucchiai Colmi),
100 G Burro (o Margarina),
3 Uova,
1 Limone (buccia Grattugiata),
1 Pizzico Cannella In Polvere,
5 Cucchiai Latte,
1 Pizzico Sale,
Pinoli,
Per La Placca:,
Burro (o Margarina)','Sbattete a lungo in una terrina 2 uova e 1 albume con lo zucchero, la buccia di limone e la cannella. Setacciate a fontana, sulla spianatoia la farina col lievito, fate un incavo nei centro, versatevi le uova sbattute e ben gonfie, il burro appena sciolto e il latte tiepido: impastate. La pasta deve risultare gonfia, morbida e liscia. Dividetela in tanti pezzetti, formate altrettante ciambelline e immergetele in acqua bollente, poche per volta, in modo che non si sovrappongano. Appena risalgono alla superficie, scolatele con un mestolo bucato e disponetele sulla placca del forno imburrata. Decoratele coi pinoli, premendoli perché aderiscano bene e pennellate la superficie di ognuna col tuorlo rimasto. Mettetele in forno, già caldo, a 200 gradi per circa 30 minuti.',5336);
INSERT INTO "ricette" VALUES (5655,'Ciambelline (3)','Dessert','Uovo Sodo',4,' -','250 G Farina,
200 G Burro,
150 G Zucchero A Velo,
2 Tuorli D''uovo,
1 Albume D''uovo,
1 Uovo Sodo,
1 Limone (scorza Grattugiata),
Zucchero In Granella,
1 Pizzico Sale','Dolce tipico del Natale. Sgusciare l''uovo sodo, eliminare l''albume e passare il tuorlo al setaccio. Montare il burro con lo zucchero a velo, aggiungere la scorza del limone, i tuorli crudi e quello sodo passato al setaccio ed impastare con la farina e un pizzico di sale. Formare una palla con questo composto, avvolgerla nella pellicola e fare riposare in frigo per circa mezz''ora. Passata la mezz''ora riprendere la pasta, formare dei cordoncini di 1/2 cm di diametro, 13 cm di lunghezza e chiuderli ad anello. Spennellare le ciambelline con l''albume, cospargerle con lo zucchero in granella e disporle sulla placca del forno foderata di carta forno. Cuocere in forno caldo a 180 gradi per 15 minuti. Se si vogliono regalare, avvolgere le ciambelline in una carta trasparente, legarle con della rafia grezza e decorarle con agrifoglio o bastoncini di cannella.',3258);
INSERT INTO "ricette" VALUES (5656,'Ciambelline Al Limone E Pistacchi','Dessert','Pistacchi',4,' -','150 G Burro,
50 G Zucchero A Velo,
150 G Farina,
50 G Pistacchi,
1 Limone (scorza Grattugiata),
Per Decorare:,
Zucchero A Velo','Accendete il forno a 190 gradi. Ungete leggermente due placche da forno. In una ciotola lavorate il burro a crema con un cucchiaio di legno. Incorporatevi lo zucchero a velo e lavorate ancora fino a ottenere un composto chiaro e soffice. Setacciatevi la farina e unite la scorza di limone. Riempite con l''impasto una tasca da pasticciere con bocchetta a stella media. Distribuitelo sulla placca formando una quindicina di anelli di 5 centimetri di diametro. Distanziateli a sufficienza per permetterne la crescita in cottura. Cospargetene la superficie con i pistacchi tritati. Mettete in frigo per almeno 15 minuti poi passate in forno per 10-12 minuti. Lasciate intiepidire qualche minuto sulle placche prima di appoggiarle a raffreddare su una griglia. Cospargete con zucchero a velo fatto cadere da un setaccino. Conservate le ciambelline in una scatola metallica ben chiusa separando gli strati con carta oleata.',2151);
INSERT INTO "ricette" VALUES (5657,'Ciambelline All''anice','Dessert','Semi Di Anice',4,' -','1 Bicchiere Zucchero,
1 Bicchiere Olio D''oliva,
1 Bicchiere Vino Bianco Secco,
Farina,
Semi Di Anice','Unire in una grande ciotola lo zucchero, l''olio, il vino e farina quanto basta per ottenere un impasto omogeneo ed elastico. Aggiungere un po'' di semi di anice. Lavorare l''impasto per ricavarne tante ciambelline. Allinearle sulla placca del forno imburrata e infarinata e metterle in forno già caldo finché saranno ben dorate.',1941);
INSERT INTO "ricette" VALUES (5658,'Ciambelline Alla Frutta','Dessert','Fichi',8,'Preparazione: 90 minuti.','200 G Zucchero Semolato,
100 G Gelatina Di Albicocche,
80 G Farina Bianca 00,
80 G Rum Bianco,
40 G Fecola Di Patate,
16 Acini Uva Moscato,
8 Fichi,
2 Uova,
Sale,
Per Gli Stampini:,
Poco Burro','Imburrate e infarinate otto stampini del diametro di cm 10, con foro centrale. Montate le due uova intere con 100 g di zucchero e un pizzico di sale; quando avrete ottenuto un composto soffice e gonfio unite 60 g di farina e la fecola dì patate, fatte cadere insieme a pioggia da un setaccino. Mescolate con un cucchiaio di legno. con un movimento dall''alto verso il basso e viceversa; mettete l''impasto in una tasca di tela impermeabile munita di bocchetta rotonda liscia e distribuitelo uniformemente negli stampini. Passateli quindi in forno già caldo a 180 gradi per 15 minuti. Nel frattempo versate in una casseruolina 30 g d''acqua e il restante zucchero; fatelo sciogliere su fuoco basso sino ad ottenere uno sciroppo limpido. Levatelo dal fornello ed unite il rum, mescolando bene. Sformate le pastine in un largo piatto o su un vassoio coperto con un foglio di alluminio; mentre sono ancora bollenti pennellate con tutto lo sciroppo al rum, anch''esso caldo, poi lasciatele raffreddare. Pelate i fichi ed incideteli con due tagli a croce, senza però arrivare al fondo; mettete al centro di ognuno due acini di uva. Appena le ciambelline saranno fredde pennellatele con la gelatina sciolta su fuoco basso e diluita con un cucchiaino di rum. Disponetele in un piatto piano e al centro di ognuna collocate un fico.',2239);
INSERT INTO "ricette" VALUES (5659,'Ciambelline Allo Zafferano','Dessert','Zafferano',4,' -','1/2 Bustina Zafferano,
13 Cl Latte Tiepido,
400 G Farina Bianca,
1 Bustina Lievito Di Birra,
75 G Zucchero,
1 Bustina Vaniglina,
1 Limone (scorza Grattugiata),
1 Cucchiaino Sale,
3 Uova,
50 G Burro Fuso,
75 G Zucchero Granella Guarnì Cameo,
30 G Pistacchi Tritati','Sciogliere lo zafferano nel latte tiepido. Setacciare la farina in una terrina larga e mescolarvi il lievito. Al centro del mucchio praticare una buca e versarvi zucchero, vaniglina, scorza di limone, sale, 2 uova e il burro fuso tiepido. Amalgamare il tutto con l''aiuto di una forchetta, aggiungendo poco per volta il latte con lo zafferano. Lavorare l''impasto sul piano del tavolo leggermente infarinato per almeno 10 minuti, allargandolo con i pugni chiusi, riavvolgendolo e sbattendolo sul tavolo, fino al completo assorbimento del liquido. Rimettere l''impasto nella terrina infarinata, coprirlo con un canovaccio umido e porlo a lievitare in luogo tiepido, fino a quando il suo volume sarà raddoppiato (90 minuti circa). Con un matterello stendere l''impasto ben lievitato in una sfoglia spessa 1 cm circa. Con uno stampino o un bicchiere infarinato ritagliare dei dischetti del diametro di 10 cm circa e con uno stampino più piccolo praticare un foro centrale in ogni dischetto. Disporre le ciambelline sulla lastra del forno foderata con carta da forno e porre a lievitare nuovamente in luogo tiepido per 15 minuti circa. Spennellare le ciambelline con 1 uovo sbattuto, cospargere di zucchero granella e pistacchi. Cuocere nella parte media del forno preriscaldato a 200 gradi per 8-10 minuti.',2829);
INSERT INTO "ricette" VALUES (5660,'Ciambelline Campagnole','Dessert','Vino Rosso',4,' -','250 G Farina,
100 G Zucchero,
100 G Vino Rosso,
80 G Olio D''oliva,
Strutto','Lavorare in 1 ciotola lo zucchero con il vino, l''olio e tanta farina quanta ne occorre per ottenere 1 impasto consistente ed omogeneo; con esso formare 1 panetto, avvolgerlo in 1 telo e farlo riposare 30 minuti. Riprendere la pasta, prelevarne 1 pallina e formare 1 cilindretto di circa 10 cm; richiuderlo ad anello in modo da formare 1 ciambellina e metterla sulla placca del forno, unta con lo strutto, proseguire così fino ad esaurimento dell''impasto. Cuocere in forno già caldo a 160 gradi per 20 minuti.',2963);
INSERT INTO "ricette" VALUES (5661,'Ciambelline D''aosta','Dessert','Uova',4,'Luogo: Val D''Aosta. Luogo: Aosta.','400 G Farina Gialla Finissima,
75 G Farina Bianca,
200 G Burro,
250 G Zucchero Semolato,
3 Uova,
1/2 Limone','Mescolare le 2 qualità di farina e impastare con il burro ammorbidito. Aggiungere lo zucchero, le uova, la scorza di limone grattugiata e lavorare bene il composto, ottenendo un impasto omogeneo. Versarlo in una siringa da pasticciere e dare all''impasto la forma di piccole ciambelline. Sistemarle sulla placca da forno non unta e cuocerle a 180 gradi per 20 minuti circa. Servirle con un buon vino bianco secco.',4443);
INSERT INTO "ricette" VALUES (5662,'Ciambelline Di Formaggio','Antipasto','Formaggio',4,' -','100 G Formaggio Grattugiato,
100 G Burro,
100 G Farina,
1 Uovo,
Latte,
1 Pizzico Sale','Lasciate ammorbidire il burro a temperatura ambiente poi, lavorandolo energicamente, impastatelo con il formaggio grattugiato, la farina e un pizzico di sale. Quando il composto è diventato di consistenza omogenea prendetene un pezzetto alla volta, ricavate tanti rotolini e chiudeteli a ciambellina. Così di seguito fino a esaurimento dell''impasto. In una tazzina diluite il tuorlo con un po'' di latte e spennellate leggermente la superficie delle ciambelline. Allineatele in una teglia foderata con carta da forno e cuocetele in forno preriscaldato a 150 gradi per circa 12 minuti, non di più. Dovete ritirare le ciambelline quando sono ancora pallide, altrimenti il formaggio cuocendo troppo assume uno sgradevole sapore forte e le ciambelline induriscono oltre il dovuto. Queste ciambelline sono molto buone servite con gli aperitivi. Vini di accompagnamento: Tutti i VSQPRD (Vino Spumante di Qualità Prodotto in Regione Determinata) di tipologia Brut.',1578);
INSERT INTO "ricette" VALUES (5663,'Ciambelline Di Pasqua','Dessert','Uova',8,'Preparazione: 60 minuti.','720 G Farina Bianca 00,
300 G Zucchero Semolato,
200 G Burro,
50 G Pinoli,
5 Uova,
1 Bicchiere Latte,
2 Bustine Lievito,
1 Pizzico Cannella','Le dosi sono per 24-25 ciambelline. Fate sciogliere 180 g di burro. In una ciotola sbattete quattro uova e un albume unendo lo zucchero e un pizzico di cannella; quando saranno ben gonfie e soffici aggiungete la scorza grattugiata del limone e il burro sciolto, amalgamando bene gli ingredienti. Setacciate per tre volte la farina (meno 20 g) insieme al lievito in polvere, fate la fontana e versatevi al centro il composto di uova: impastate unendo tanto latte tiepido quanto basta per ottenere una pasta ben gonfia e liscia. Imburrate e spolverizzate di farina una placca da forno. Ponete sul fuoco una capace casseruola con abbondante acqua. Dividete la pasta in tanti pezzetti (dovranno essere 24-25) e con essi formate dei cilindretti del diametro di circa 2 cm ai quali darete la forma di ciambelline di circa 6 cm di diametro; quando saranno tutte pronte, usando un mestolo forato immergetele, una alla volta, per un istante, nell''acqua bollente, indi sistematele sulla placca. Dorate la superficie di ogni ciambellina con il tuorlo sbattuto con una cucchiaiata di latte e decoratele con i pinoli; mettetele subito in forno già caldo (180 gradi) lasciandolo cuocere per circa mezz''ora.',6018);
INSERT INTO "ricette" VALUES (5664,'Ciambelline Di Patate','Dessert','Patate',4,' -','500 G Patate,
1/2 Bicchiere Latte,
1 Tuorlo D''uovo,
3 Albumi D''uovo,
30 G Burro,
Sale,
Olio D''oliva,
Zucchero A Velo','Lessate le patate e passatele; in un tegame sciogliete il burro, unite le patate, diluite con il latte e cuocete mescolando. Togliete dal fuoco, legate col tuorlo, fate raffreddare; incorporate gli albumi a neve. Formate delle ciambelline e friggetele nell''olio bollente. Scolate e spolverate di zucchero a velo.',1626);
INSERT INTO "ricette" VALUES (5665,'Ciambelline Di Verdura','Dessert','Uova',4,' -','4 Uova,
1 Albume D''uovo,
200 G Farina,
Sale,
Alcuni Cucchiai Latte,
Zucchine,
Carote,
Finocchi (o Patate),
Per Friggere:,
Olio D''oliva','Mettere in una fondina 4 uova e 200 g di farina, salare e aggiungere qualche cucchiaio di latte. Mescolare bene per circa 10 minuti fino a ottenere un impasto denso. Qualora il composto fosse troppo liquido o troppo denso aggiungere rispettivamente ancora un po'' di farina o di latte. A parte montare una chiara a neve e incorporarla lentamente nella pastella. Dentro la pastella si potranno grattugiare a piacere: zucchine, carote, finocchi e patate. Oppure aggiungere spinaci ed erbetta già bolliti e tritati. Preparare una padella bassa e larga con un dito di olio d''oliva bollente. Gettare la pastella a piccole cucchiaiate nell''olio bollente, in modo da formare delle piccole ciambelline che farete dorare da entrambi i lati. Adagiarle una ad una sulla carta assorbente per asciugare l''olio in eccesso e servirle subito ben calde.',1857);
INSERT INTO "ricette" VALUES (5666,'Ciambelline Dorate','Antipasto','Patate',4,'Preparazione: 60 minuti. Calorie: 398.','400 G Patate,
60 G Farina Bianca,
35 G Burro,
1 Tuorlo D''uovo,
2 Uova,
3 Cucchiai Formaggio Parmigiano Grattugiato,
1 Pizzicone Trito Aromatico (salvia, Rosmarino, Prezzemolo),
1 Grattatina Noce Moscata,
Abbondante Olio D''oliva,
Sale,
Pepe','Lavate le patate e lessatele con la buccia. Appena pronte, pelatele e passatele al passaverdura (disco medio), raccogliendo il ricavato in una ciotola. Amalgamatelo con il tuorlo, un pizzico di sale, una grattatina di noce moscata e una cucchiaiata di parmigiano. Mettete quindi a bollire 125 g d''acqua, il burro e una presina di sale. Quando alzerà il bollore, versatevi la farina tutta in una sola volta e, sempre mescolando, tenete l''impasto sul fuoco fino a quando si staccherà dal fondo della casseruola con un leggero sfrigolio come se friggesse. Allora allargatelo su un piatto e lasciatelo raffreddare. Appena sarà freddo, trasferitelo in una ciotola e incorporatevi, uno alla volta, le uova, non aggiungendo il successivo se il precedente non sarà stato bene amalgamato. Unite questo impasto a quello di patate. Mescolateli insieme poi insaporite il tutto ancora con 2 cucchiaiate di parmigiano e con un pizzicone di trito aromatico. Aggiustate di sale e di pepe. Mettete a riscaldare la padella dei fritti con abbondante olio. Raccogliete il composto preparato in una tasca di tela da pasticcere munita di bocchetta spizzata e fatelo uscire a nastro formando delle piccole ciambelle sopra un foglio di carta speciale da cucina già unto. Disponetene 5-6 per volta distanziandole giustamente quindi sollevate il foglio e capovolgetelo sopra la padella, scuotetelo delicatamente e, al caso, immergete anche la carta nel recipiente, per permettere alle ciambelle di staccarsi e finire senza sformarsi nell''olio; friggetele fino a quando saranno ben dorate e gonfie, quindi estraetele con il mestolo forato e passatele a sgocciolare su un doppio foglio di carta da cucina, tenendole al caldo. Terminato di friggere, sistemate le ciambelline su un piatto e servitele subito.',2288);
INSERT INTO "ricette" VALUES (5667,'Ciambelline Fritte Di San Giuseppe','Dessert','Uova',4,' -','180 G Acqua,
1 Noce Burro,
2 Cucchiaini Zucchero,
1 Pizzico Sale,
120 G Farina,
3 Uova','Far bollire l''acqua con burro, zucchero e sale; gettarvi tutta insieme la farina, mescolando vigorosamente perché non si formino nodi, togliere dal fuoco, far raffreddare un po'' e poi unire un uovo alla volta, sempre mescolando. Versare poi sul tagliere e lavorare aggiungendo un po'' di farina, in modo da avere una pasta morbida. Dividere quindi in 16-18 pezzi grandi come noci, farne prima pallottoline e poi, premendole al centro, delle ciambelline, che si devono far bollire in acqua bollente finché non vengono a galla. Incidere intorno intorno con un coltello e friggere in olio abbondante. Si possono insaporire con zucchero a velo o con fiocchetti di crema e ciliegine.',1205);
INSERT INTO "ricette" VALUES (5668,'Ciambelline Ruzze','Dessert','Vino Bianco',4,'Luogo: Ciociaria. Luogo: Lazio.','1200 G Farina,
250 G Zucchero,
1 Manciata Semi Di Anice,
1 1/2 Bicchiere Vino Bianco,
1/2 Bicchiere Olio D''oliva','Sulla spianatoia setacciare a fontana la farina, fare un incavo nel centro, versarvi lo zucchero, il vino, l''olio e i semi di anice. Impastare. La pasta deve risultare non troppo morbida. Dividerla in tanti tocchetti, formare dei cilindretti e unirli alle due estremità per formare delle ciambelline del diametro di circa 5 cm, disporle quindi in una placca da forno già infarinata, spennellare con vino e zucchero e infornare a 180 gradi per mezz''ora.',5673);
INSERT INTO "ricette" VALUES (5669,'Ciambelline Salate','Antipasto','Farina',4,' -','1 Bicchiere Olio D''oliva,
1 Bicchiere Vino,
Sale,
Pepe (facoltativo),
Origano,
Farina','Impastare sul tagliere tutti gli ingredienti, formare le ciambelline, gettarle un po'' alla volta nell''acqua bollente leggermente salata ed estrarle tirarle fuori non appena vengono a galla. Disporle in una teglia unta ed infarinata e cuocerle al forno a temperatura media. Se necessario, se si nota che si cuociono più sotto che sopra, dopo un po'' rigirarle.',1794);
INSERT INTO "ricette" VALUES (5670,'Ciambelline Siciliane','Dessert','Mandorle',4,'Luogo: Sicilia.','400 G Farina Setacciata,
100 G Mandorle Tostate E Pestate A Poltiglia Nel Mortaio,
200 G Zucchero Fine,
1 Uovo,
60 G Burro Ridotto In Crema,
10 G Bicarbonato,
1 Pizzico Sale','Disporre la farina a fontana sul tavolo. Riunire nel mezzo il burro, il pesto di mandorle, lo zucchero, l''uovo, il bicarbonato e il sale. Impastare come se si facesse una pasta frolla, formare delle piccole ciambelle e allinearle in una placca imburrata ed infarinata leggermente, passarle in forno a calore vivace; ritirarle ben cotte e colorite.',3277);
INSERT INTO "ricette" VALUES (5671,'Ciambellone','Dessert','Uvetta Sultanina',4,' -','400 G Farina,
150 G Zucchero,
100 G Burro,
3 Uova,
1 Bustina Lievito,
200 G Uvetta Sultanina,
2 Limoni (scorza Grattugiata),
Pinoli,
Latte (o Liquore)','Sbattete bene uova e zucchero, aggiungete il burro fuso, l''uvetta, la buccia grattugiata dei limoni, i pinoli, latte o liquore e per ultimo il lievito. Cuocere in forno già caldo per 45 minuti.',4173);
INSERT INTO "ricette" VALUES (5672,'Ciambellone (2)','Dessert','Burro',6,' -','600 G Farina,
250 G Zucchero,
150 G Burro,
1 1/2 Bicchiere Latte,
3 Uova,
1 1/2 Bustina Lievito Vanigliato,
1 Limone (scorza Grattugiata)','Mescolare farina, zucchero, burro fuso, buccia grattugiata del limone, le uova e il latte. Incorporare infine il lievito. Versare il composto in una teglia unta di burro e cuocere per 50 minuti in forno già caldo a 180 gradi.',4511);
INSERT INTO "ricette" VALUES (5673,'Ciambellone (3)','Dessert','Mandorle',6,' -','50 G Farina,
160 G Zucchero,
80 G Burro,
50 G Cacao In Polvere,
80 G Mandorle Tritate,
4 Uova','Fate sciogliere il burro a bagnomaria e lasciate raffreddare. Montate le uova con lo zucchero fino ad ottenere un composto denso e spumoso. Mescolate farina e cacao, incorporateli alle uova sbattute e, per evitare che si formino grumi, usate un setaccino. Ammorbidite con il burro fuso e, alla fine, aggiungete le mandorle tritate. Amalgamate bene il tutto e versatelo in uno stampo a ciambella imburrato e infarinato. Cuocete in forno preriscaldato a 180 gradi per circa tre quarti d''ora. Togliete dal forno, fate raffreddare e sformate sul piatto da portata. Servite con crema zabaglione a parte.',2394);
INSERT INTO "ricette" VALUES (5674,'Ciambellone (4)','Dessert','Uova',4,'Luogo: Ciociaria. Luogo: Lazio.','500 G Farina,
4 Uova,
200 G Zucchero,
1 Limone (scorza Grattugiata),
1 Bicchiere Latte,
1 Bustina Lievito,
1 Bicchiere Olio D''oliva,
Per Lo Stampo:,
Burro','In una bacinella lavorare le uova con lo zucchero, aggiungere il latte, l''olio, la raschiatura di limone, la farina e il lievito. Amalgamare bene e versare il composto in uno stampo imburrato. Infornare a 180 gradi per 40 minuti.',4959);
INSERT INTO "ricette" VALUES (5675,'Ciambellone Con Frutta Secca','Dessert','Noci',6,' -','200 G Gherigli Di Noci,
4 Uova,
100 G Albicocche Secche,
100 G Datteri,
100 G Uvetta Sultanina,
100 G Scorza D''arancia Candita,
100 G Ciliegine Sciroppate,
250 G Farina,
1 Noce Burro,
140 G Zucchero Semolato,
200 G Zucchero A Velo,
1 Cucchiaio Succo Di Limone,
2 Cucchiai Rum,
2 Cucchiaini Lievito In Polvere,
1 Pizzico Sale','Mettete a bagno l''uvetta in una ciotola con acqua tiepida per un quarto d''ora. Riducete a pezzetti le albicocche secche, i gherigli di noci e i datteri, privati dei noccioli, e poneteli in una terrina insieme all''uvetta scolata e strizzata. Unite la scorza d''arancia candita, tagliata a dadini, e le ciliegine, ben sgocciolate dallo sciroppo di conserva e snocciolate. In una scodella sbattete le uova con lo zucchero, servendovi di una frusta, fino ad ottenere un composto gonfio e omogeneo. Aggiungetevi un cucchiaio di rum e la frutta secca e mescolate per amalgamare bene gli ingredienti. Unite anche la farina, poca per volta, il lievito e un pizzico di sale continuando a mescolare energicamente per alcuni minuti. Ungete di burro uno stampo per ciambelle, versatevi il composto, livellatene la superficie e fatelo cuocere nel forno già caldo (220 gradi) per 40 minuti. In una terrina mescolate lo zucchero a velo col resto del rum, un cucchiaio d''acqua e uno di succo di limone. Lavorate il composto fino a quando sarà liscio e, alzandolo con un cucchiaio, ricadrà formando un nastro piuttosto denso. Togliete la ciambella dal forno, sformatela su un piatto di portata e lasciatela raffreddare. Coprite la torta con la glassa preparata e fatela solidificare all''aria per mezz''ora, prima di servire.',5668);
INSERT INTO "ricette" VALUES (5676,'Ciambellone Della Mamma','Dessert','Uova',8,' -','300 G Farina 0,
200 G Zucchero,
150 G Burro,
3 Uova,
20 Cl Latte,
1 Bustina Lievito Chimico,
Sale','Montare il burro con lo zucchero passato al velo, incorporare le uova una per volta, aggiungere il sale, la farina, il latte, e, per ultimo, il lievito. Infornare subito nel forno, preriscaldato a 175 gradi per circa 40 minuti (se avete dubbi, è ottima e sempre valida la prova dello stecchino).',3270);
INSERT INTO "ricette" VALUES (5677,'Ciambellone Della Nonna','Dessert','Burro',8,' -','200 G Zucchero A Velo,
180 G Burro,
160 G Farina Bianca 00,
70 G Fecola Di Patate,
2 Uova Intere,
6 Tuorli D''uovo,
1 Bustina Lievito Per Dolci,
1 Bustina Zucchero In Granella,
Sale,
1 Limone,
Per Lo Stampo:,
Burro,
Farina','Accendere il forno e portarlo a 180 gradi; imburrare e infarinare uno stampo a ciambella (diametro 25 cm); se manca, si può ricorrere a uno stampo a bordi alti, in mezzo al quale mettere una scodella rovesciata. Montare lungamente con lo sbattitore elettrico il burro e lo zucchero a velo, la scorza grattugiata di mezzo limone e un pizzico di sale; quando il composto sarà ben gonfio, incorporare uova intere e tuorli, uno alla volta. Aggiungere, quindi, la farina mescolata con la fecola a cucchiaiate e mezza bustina di lievito. Versare l''impasto nello stampo, spianare la superficie e cospargerla di zucchero in granella. Infornare a 180 gradi per circa 45 minuti. Provare la cottura, perforando con uno stecchino. Sformare e far raffreddare su una gratella. Si può servire con crema inglese o panna montata.',4935);
INSERT INTO "ricette" VALUES (5678,'Ciambellone Nero Con Panna Montata','Dessert','Cacao In Polvere',4,' -','200 G Farina,
200 G Zucchero,
2 Uova,
40 G Cacao In Polvere,
70 G Burro,
1 Bicchiere Latte,
1 Bustina Lievito,
1 Limone (scorza Grattugiata),
250 G Panna Montata','Mescolare insieme farina, zucchero, 2 tuorli, il cacao, 50 g di burro, il latte, la scorza del limone, e, Infine, aggiungere il lievito e le chiare montate a neve. Versare l''impasto in uno stampo a ciambella precedentemente imburrato e porre in forno a calore moderato per circa 1 ora. Lasciarlo raffreddare, quindi sformarlo e servirlo insieme alla panna montata.',3106);
INSERT INTO "ricette" VALUES (5679,'Ciambellone Rustico','Dessert','Latte',4,'Luogo: Marche.','1000 G Farina,
150 G Strutto,
250 G Zucchero,
1 Bicchiere Latte,
1 Scorza Di Limone Grattugiata,
4 Uova,
150 G Lievito Di Birra','Formare una fontanella con la farina e impastare con lo strutto, lo zucchero, il latte, le uova, il lievito e la scorza di limone. Lavorare l''impasto sino ad ottenere una pasta fina e liscia. Formare dei filoncini e metterli su una teglia unta di strutto e infarinata. Dopo averli spennellati con tuorlo d''uovo e cuocere in forno a 200 gradi per 30-40 minuti a secondo della grandezza.',6110);
INSERT INTO "ricette" VALUES (5680,'Cianfotta','Contorno','Pomodori',6,'Luogo: Campania.','800 G Patate,
800 G Peperoni Gialli,
500 G Cipolle,
500 G Pomodori Maturi,
1/2 Bicchiere Olio D''oliva,
Alcune Foglie Basilico,
1 Gambo Sedano,
4 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
Melanzane (facoltativo),
Zucchine (facoltativo)','Passare i pomodori a crudo al setaccio. Tagliare le cipolle a fette sottili e metterle in casseruola con abbondante olio d''oliva (circa mezzo bicchiere). Porre sul fuoco e farle cuocere senza che prendano colore (appassire). Aggiungervi il pomodori e quando comincia a bollire aggiungervi le patate e lasciar cuocere a fuoco lentissimo, aggiungendo eventualmente acqua se l''intingolo asciugasse troppo. Intanto taglierete i peperoni a striscioline che aggiungerete al preparato che starà cuocendo. A cottura ultimata aggiungervi il basilico ed il formaggio grattugiato. Si possono anche aggiungere melanzane e zucchine a piacere.',2132);
INSERT INTO "ricette" VALUES (5681,'Cianfotta (2)','Contorno','Peperoni',4,' -','3 Peperoni,
3 Zucchine,
2 Patate,
2 Melanzane,
1 Cipolla,
1 Costa Sedano,
1 Spicchio Aglio,
1 Costa Sedano,
200 G Polpa Di Pomodoro,
150 Cl Brodo Vegetale,
Olio D''oliva Extra-vergine,
Sale,
Peperoncino,
Pepe','Mondare tutte le verdure e tagliarle a dadini. Scaldare l''olio e farvi saltare a fuoco vivo tutte le verdure; salare e pepare. Brasare aglio e cipolla triturati nell''olio; unirvi la polpa di pomodoro, sale, pepe e far insaporire, quindi unire alle verdure. Mettere il peperoncino sminuzzato e il brodo e cuocere 30 minuti.',1963);
INSERT INTO "ricette" VALUES (5682,'Cianfotta (3)','Contorno','Zucchine',4,' -','4 Zucchine,
4 Melanzane Lunghe Piccole,
1 Peperone Giallo,
1 Peperone Rosso,
4 Pomodori,
2 Cipolle,
Aglio,
Capperi,
Basilico,
Brodo Vegetale,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Mondare le verdure. Far appassire nell''olio la cipolla affettata sottilmente con l''aglio. A parte, in poco olio, far saltare melanzane e zucchine a cubetti, poi unirli alle cipolle, togliendo l''aglio. Aggiungere i peperoni a quadrotti e soffriggerli per alcuni minuti. Unire i pomodori a pezzi, capperi, basilico, un po'' di brodo. Salare, pepare e stufare,coperto, per un''ora a fuoco dolce.',1243);
INSERT INTO "ricette" VALUES (5683,'Cianfotta Sorrentina','Contorno','Pomodori',6,'Luogo: Campania. Luogo: Sorrento.','Olio D''oliva,
Peperoncino Piccante,
1 Cipolla,
1 Spicchio Aglio,
400 G Pomodori San Marzano,
300 G Patate,
200 G Carote,
400 G Zucchine,
200 G Zucca Lunga,
1 Melanzana,
300 G Zucchette,
6 Prugne Secche,
6 Pere Mast''antuono (o Pere Spadone),
Balisico,
Sale','Rosolare nell''olio la cipolla tagliata a fette sottili con il peperoncino e lo spicchio d''aglio, che eliminerete quando sarà dorato. Unite poi i pomodori pelati e tagliati a pezzi e lasciateli cuocere per circa dieci minuti prima di aggiungere le patate, le carote tagliate a dadini e un bicchiere d''acqua. Intanto sbucciate la zucca lunga e tagliatela a pezzetti; tagliate nella stessa forma anche le zucchine, le zucchette e la melanzana e unite ogni cosa nella casseruola. Mettete il sale quasi al termine della cottura in modo che le verdure non perdano la lucentezza dei loro colori. Lasciate cuocere a calore moderato per circa un''ora, senza mescolare troppo, aggiungete le prugne secche snocciolate e le pere (rigorosamente quasi acerbe) tagliate a pezzi. Dopo circa quindici minuti la cianfotta sarà ben cotta, controllate che il sale sia giusto e completate, aggiungendo profumo, con del buon basilico fresco.',2141);
INSERT INTO "ricette" VALUES (5684,'Cianfotta Sorrentina (2)','Contorno','Melanzane',4,'Luogo: Campania. Luogo: Sorrento.','2 Melanzane,
2 Zucchine,
2 Peperoni,
Patate,
4 Pomodori San Marzano,
1 Spicchio Aglio,
1 Cipolla,
Capperi,
Olive Di Gaeta,
Sale,
1 Limone Spremuto,
Basilico,
1/2 Bicchiere Vino Bianco','Affetto tutte le verdure le lavo, le metto in un grosso recipiente e le condisco con olio e sale aggiungendo le olive e i capperi e premendo il limone. Metto al forno ogni tanto le do una giratina e a metà cottura aggiungo un mezzo bicchiere di vino bianco. Più o meno un''oretta per cuocere il tutto.',834);
INSERT INTO "ricette" VALUES (5685,'Cianfotta Sorrentina Al Microonde','Contorno','Patate',4,'Luogo: Campania. Luogo: Sorrento.','Olio D''oliva,
Olive Nere,
Capperi,
1 Cipolla,
2 Spicchi Aglio,
Pomodori San Marzano,
3 Patate Medie,
3 Zucchine,
3 Melanzane,
2 Peperoni,
Basilico,
Sale,
1/2 Bicchiere Vino Bianco','Pulire e tagliare a listarelle i peperoni, porli in un recipiente di ceramica, condirli con olio e aglio, sigillare con carta tipo pellicola domopak e farli cuocere nel microonde. Friggere le patate tagliate a cubetti. In Padelle differenti, friggere le zucchine e le melanzane a tocchetti. Tirarle su lasciandole a metà cottura. Prendere una grande teglia da forno ed unire tutti questi ingredienti, aggiungendo i pomodori san marzano la cipolla l''aglio, le olive e i capperi ed il basilico, mescolare aiutandovi con un grosso cucchiaio il tutto e regolare di sale. Mettere al forno e far cuocere per un 3/4 d''ora quando la cianfotta comincerà a ''tirarsi'' innaffiare con il mezzo bicchiere di vino bianco fino a farlo evaporare.',1823);
INSERT INTO "ricette" VALUES (5686,'Ciao','Bevande','Brandy Stock 84',1,' -','6/10 Brandy Stock 84,
4/10 Vermouth Cinzano Bianco,
Alcune Gocce Angostura,
Alcune Gocce Liquore Galliano','Preparare nel mixing glass con dei cubetti di ghiaccio. Servire nella coppetta da cocktail.',328);
INSERT INTO "ricette" VALUES (5687,'Ciao Ciao','Bevande','Calvados',1,' -','1/3 Vermouth Dubonnet,
2/3 Calvados,
1 Cucchiaio Cointreau,
1 Spruzzo Angostura','Agitare a lungo nel mixer con ghiaccio. Servire nel calice basso.',333);
INSERT INTO "ricette" VALUES (5688,'Ciaramicola','Dessert','Tuorli D''uovo',4,' -','550 G Farina,
3 Tuorli D''uovo,
120 G Burro,
300 G Zucchero,
1/2 Limone,
1 Bicchierino Alchermes,
2 Albumi D''uovo,
1 Bustina Lievito Per Dolci,
Confettini Colorati','Mettere in 1 terrina la farina, i tuorli, la scorza grattugiata del limone, lo zucchero e 100 g di burro morbido a pezzetti. Impastare il tutto, poi unire 1 bicchierino di alchermes e il lievito formando una pasta omogenea e formare una ciambella. Metterla in 1 stampo imburrato e infarinato. Infornare a 180 gradi per 40 minuti. A cottura quasi ultimata, ricoprirla con gli albumi montati a neve e rimetterla in forno per 2 minuti. Servire fredda, cosparsa di confettini.',4330);
INSERT INTO "ricette" VALUES (5689,'Ciau Turin','Bevande','Cognac',1,' -','1/3 Caffè Lavazza,
1/3 Cognac,
1/3 Rum,
1 Limone (scorza),
1 Chiodo Di Garofano','Mescolare tutti gli ingredienti.',236);
INSERT INTO "ricette" VALUES (5690,'Ciavarro','Contorno','Lenticchie',4,' -','50 G Lenticchie,
50 G Ceci,
50 G Cicerchie,
50 G Granturco,
50 G Orzo Perlato,
50 G Fave,
50 G Favino,
50 G Fagioli Bianchi,
50 G Fagioli Borlotti,
500 G Pomodoro,
1 Cipolla,
Olio D''oliva,
Aglio,
Sale,
Peperoncino','Mettere a bagno per 24 ore legumi e cereali. Scolarli, metterli in acqua fredda e cuocerli in una pentola di terracotta cominciando con le cicerchie ed unire, a intervalli di 30 minuti: ceci, orzo, granturco, fagioli dei 2 tipi, fave, favino, lenticchie, unendo man mano acqua bollente salata. Soffriggere la cipolla finemente affettata con olio, aglio e peperoncino, aggiungere polpa di pomodoro, far insaporire e unirlo alla zuppa Cuocere per 15 minuti. Far riposare e servire.',1820);
INSERT INTO "ricette" VALUES (5691,'Cibreo','Pollame','Pollo',4,' -','Fegatini Di Pollo,
1 Tuorlo D''uovo,
Succo Di Limone,
Pepe,
Sale,
Burro,
Brodo','Pulite i fegatini, badando di togliere con cura il sacchetto della bile e tagliateli a pezzetti. Fateli rosolare rapidamente nel burro aggiungendo, se occorre, un goccio di brodo per terminare la cottura. In una tazza sciogliete il tuorlo col succo di limone e aggiungetelo fuori dal fuoco ai fegatini già cotti, salando leggermente. Mescolate e portate ancora un attimo il tegame sul fuoco bassissimo per scaldare la salsa.',1036);
INSERT INTO "ricette" VALUES (5692,'Cibreo (2)','Pollame','Fegatini Di Pollo',4,' -','Fegatini Di Pollo,
1 Tuorlo D''uovo,
Brodo,
1 Limone (succo),
1 Cucchiaino Farina,
Sale,
Pepe Nero,
Burro','Rosolare i fegatini nel burro, abbassare la fiamma e cuocere lentamente bagnando col brodo, regolare di sale. Intanto a parte in una ciotolina mettere il rosso d''uovo con la farina, poco alla volta per non fare grumi mescolando bene con un cucchiaio di legno, aggiungere il succo di limone e un po'' di brodo (deve restare semiliquida). Versare la salsa sui fegatini, cuocere pochi minuti, servire e macinarvi sopra pepe a piacere quando sono già nei piatti.',1050);
INSERT INTO "ricette" VALUES (5693,'Cibreo Di Rigaglie','Pollame','Pollo',4,' -','400 G Fegatini, Ovette E Creste Di Pollo,
30 G Burro,
Brodo Di Pollo,
3 Uova,
1/2 Limone,
1 Cucchiaio Farina,
Sale,
Pepe','Dopo averli puliti, scottare i fegatini in acqua bollente con le creste e toglierli subito. Spellare le creste e tagliuzzarle; tagliuzzare i fegatini. Scaldare il burro, unirvi le creste e cuocere per 30 minuti con poco brodo. Aggiungere ovette e fegatini, salare e pepare. Sbattere i tuorli con 1 cucchiaio di farina, succo di limone e, sbattendo continuamente, 1/2 mestolino di brodo bollente. Versare sulle rigaglie e mescolare per 1-2 minuti. Servire.',1091);
INSERT INTO "ricette" VALUES (5694,'Cicale Farcite','Pesce','Cicale Di Mare',4,' -','800 G Cicale Di Mare (canocchie),
100 G Mollica Di Pane Raffermo,
1 Ciuffo Prezzemolo,
60 G Filetti D''acciughe,
Olio D''oliva,
Sale,
Pepe','La stagione ideale per consumare le cicale è la primavera, quando i crostacei sono ricchi di corallo. Lavate le cicale sotto l''acqua corrente e lasciatele sgocciolare su un canovaccio pulito; quindi incidetele lungo il dorso e allargate un po'' l''apertura. Fate rinvenire la mollica di pane in poca acqua tiepida; strizzatela e mettetela in una terrinetta. Tritate molto finemente il prezzemolo e i filetti d''acciughe e mescolate entrambi con la mollica di pane, unendo tanto olio quando ne basta per ottenere un composto piuttosto consistente. Distribuite il ripieno nelle cicale, inserendolo nelle aperture praticate, poi richiudete i gusci con la pressione delle mani. Fate scaldare bene un paio di griglie. Adagiate le cicale farcite sulle griglie roventi e cuocetele per 15 minuti a calore moderato, rivoltandole di tanto in tanto e regolandole di sale e di pepe. A cottura ultimata, disponete le cicale sul piatto da portata e servite caldissime.',1852);
INSERT INTO "ricette" VALUES (5695,'Cicerchia','Dessert','Uova',8,' -','300 G Farina,
3 Uova,
4 Cucchiaini Anisetta,
1 Cucchiaio Olio D''oliva Extra-vergine,
100 G Mandorle Tritate Grossolanamente,
1 Limone,
150 G Canditi,
500 G Miele Millefiori,
200 G Strutto,
350 G Olio D''oliva,
Sale,
Burro','Impastare farina e uova incorporando olio d''oliva extra-vergine, buccia di limone grattugiata, liquore e sale. Ricavarne serpentelli sottili; tagliarli a 1 cm e friggerli in olio e strutto adagiandoli poi su carta assorbente. In una ciotola mescolare canditi e mandorle e versare il miele fuso. Mescolare e mettere in forma in una ciambella unta; far rapprendere.',6748);
INSERT INTO "ricette" VALUES (5696,'Cicerchiata','Dessert','Miele',4,' -','Per Le Cicerchie:,
240 G Farina,
20 G Burro,
20 G Zucchero,
2 Uova,
1 Cucchiaio Vino Bianco Secco,
Per Friggere:,
Olio D''oliva,
Per L''amalgama:,
100 G Zucchero,
100 G Miele,
Frutta Candita A Pezzettini','Dolce tipico del Carnevale. Impastare bene farina, burro, zucchero e uova, aggiungere il vino e fare tanti bastoncini da tagliare a gnocchetti di 1 cm circa, in modo da ottenere quasi delle palline, della grandezza di un cece. Friggerli e scolarli bene. Far caramellare zucchero e miele. Quando sono ben dorati, versarvi le palline e mescolare velocemente in modo da amalgamare bene il tutto. Versare sul piatto da portata, dando la forma di ciambella, e decorare con i canditi ed i confettini. Il nome deriva da Cicerchia = Cece, anche se con i ceci non ha nulla a che vedere, se non l''aspetto.',2903);
INSERT INTO "ricette" VALUES (5697,'Cicerchie E Finocchietti','Primo','Finocchietto Selvatico',4,'Luogo: Puglia.','350 G Pasta Tipo Cicerchie,
3 Pomodori,
1 Cipolla,
2 Spicchi Aglio,
Prezzemolo,
Finocchietto Selvatico,
Olio D''oliva Extra-vergine Del Gargano,
Sale','Tenere a bagno le cicerchie per 24 ore. Cambiare l''acqua e portare ad ebollizione unendo il
finocchietto, aglio, prezzemolo, cipolla, pomodoro a filetti. A cottura quasi ultimata salare. Terminata la
cottura (2-3 h) servire la zuppa su fette di pane abbrustolito irrorando con olio a crudo.',1997);
INSERT INTO "ricette" VALUES (5698,'Cicerelli Alla Menta','Pesce','Cicerelli',6,' -','800 G Cicerelli,
1 Mazzetto Foglie Di Menta,
Aceto Di Mele,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lavare i cicerelli, asciugarli tamponandoli e friggerli interi in olio ben caldo, facendoli dorare appena, appena. Trasferirli su carta assorbente e salarli. Preparare un''emulsione con olio, aceto, sale, pepe e abbondanti foglie di menta, irrorarne i pesci e far riposare. Si servono freddi.',793);
INSERT INTO "ricette" VALUES (5699,'Ciceri E Trie','Primo','Ceci',4,'Luogo: Puglia.','300 G Ceci,
1 Cipolla,
1 Foglia Alloro,
Peperoncino,
5 Cucchiai Olio D''oliva,
Sale,
Per La Pasta:,
250 G Farina Di Grano Duro,
Acqua','Mettere a bagno i ceci il giorno prima quindi lessarli in 200 cl di acqua con l''alloro e unendo il sale a fine cottura. Con acqua e farina preparare una sfoglia né sottile né spessa. Arrotolarla su se stessa prima che asciughi, quindi ritagliarne laganelle (trie) di circa 3-4 mm di larghezza. Farle asciugare. Lessare al dente le trie in abbondante acqua salata, scolarle e unirle ai ceci. Condire con un soffritto di olio, peperoncino e cipolla affettata sottilmente preparato contemporaneamente alla cottura delle trie.',2183);
INSERT INTO "ricette" VALUES (5700,'Ciclamino','Bevande','Gin',1,' -','1/4 Vermouth Dry,
1/4 Peychaud,
2/4 Gin','Agitare con ghiaccio in cubetti nel mixer. Servire nel calice basso.',304);
INSERT INTO "ricette" VALUES (5701,'Cico','Bevande','Succo D''ananas',1,' -','1 Limone (succo),
1/2 Arancia (succo),
6 Cucchiai Succo D''ananas,
1 Cucchiaio Sciroppo Di Lampone,
1/2 Bottiglietta Gassosa Schweppes','Preparare nel tumbler grande con dei cubetti di ghiaccio.',386);
INSERT INTO "ricette" VALUES (5702,'Cicoria Al Formaggio','Contorno','Insalata Cicoria',4,' -','1000 G Insalata Cicoria,
1 Cipolla,
2 Uova,
4 Cucchiai Olio D''oliva,
3 Cucchiai Formaggio Parmigiano,
2 Cucchiai Formaggio Pecorino,
Sale','Lavare e pulire la cicoria e lessarla in acqua salata. Scolarla e strizzarla bene. In un tegame scaldare l''olio, unire la cipolla e, appena sarà imbiondita, aggiungere la cicoria. Mescolare, salare e aggiungere le uova, mescolando continuamente con il cucchiaio di legno. Incorporare i formaggi e servire subito.',2146);
INSERT INTO "ricette" VALUES (5703,'Cicoria Al Formaggio (2)','Contorno','Insalata Cicoria',4,' -','1 Cipolla Piccola Tritata,
2 Uova,
4 Cucchiai Olio D''oliva,
3 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
1200 G Insalata Cicoria,
2 Cucchiai Formaggio Pecorino Non Piccante Grattugiato','Mondare la cicoria e lessarla in acqua salata. Scolarla e strizzarla. Scaldare l''olio d''oliva, unire la cipolla e, appena questa sarà imbiondita, la cicoria. Mescolare, salare, pepare e rompervi dentro le uova sempre mescolando. Cospargere con i formaggi, mescolare nuovamente e servire immediatamente.',2167);
INSERT INTO "ricette" VALUES (5704,'Cicoria Al Formaggio (3)','Contorno','Insalata Cicoria',4,' -','1200 G Insalata Cicoria,
1 Cipolla Piccola Tritata,
2 Uova,
4 Cucchiai Olio D''oliva,
3 Cucchiai Formaggio Parmigiano Grattugiato,
2 Cucchiai Formaggio Pecorino Non Piccante Grattugiato,
Sale,
Pepe','Mondare la cicoria e lessarla in acqua salata. Scolarla e strizzarla. Scaldare l''olio, unire la cipolla e, appena questa sarà imbiondita, la cicoria. Mescolare, salare, pepare e rompervi dentro le uova sempre mescolando. Cospargere con i formaggi, mescolare nuovamente e servire immediatamente.',2167);
INSERT INTO "ricette" VALUES (5705,'Cicoria Al Pane','Contorno','Insalata Cicoria',4,' -','1 Cespo Insalata Cicoria,
2 Manciate Pane Secco Tritato Grossolanamente,
1 Spicchio Aglio,
Vinaigrette','Sfregare l''insalatiera con lo spicchio d''aglio. Lavare, asciugare e tagliare a striscioline sottili la cicoria. Metterla nell''insalatiera e mescolarla al pane secco. Preparare la vinaigrette sciogliendo il sale nell''aceto, unendo l''olio e un pizzico di pepe e sbattendo molto bene con una forchetta. Versare la vinaigrette sull''insalata e mescolare.',360);
INSERT INTO "ricette" VALUES (5706,'Cicoria Al Peperoncino','Contorno','Insalata Cicoria',4,' -','1000 G Insalata Cicoria,
Peperoncino Rosso,
3 Spicchi Aglio,
3 Cucchiai Olio D''oliva,
Sale,
Pepe','Lessate la cicoria per un quarto d''ora in acqua salata, sgocciolatela e strizzatela. In una padella fate scaldare tre cucchiai d''olio con gli spicchi d''aglio e il peperoncino rosso sminuzzato. Quando l''aglio ha preso colore eliminatelo e aggiungete la cicoria tagliuzzata. Salate, pepate e fate insaporire per 10 minuti.',1226);
INSERT INTO "ricette" VALUES (5707,'Cicoria Alla Besciamella','Contorno','Insalata Cicoria',4,' -','1000 G Insalata Cicoria,
1 Tazza Besciamella,
100 G Prosciutto Cotto,
Burro,
Sale','Mondate e lavate la cicoria. Sgocciolatela e lessatela in acqua bollente salata. Scolatela, strizzatela, tritatela grossolanamente e fatela insaporire in un tegame con 30 g di burro per circa 10 minuti. Distribuite la cicoria in una pirofila imburrata, mettete sulla superficie il prosciutto tritato grossolanamente e ricoprite con la besciamella che deve essere di consistenza piuttosto fluida. Gratinate in forno preriscaldato a 180 gradi per 10 minuti. Servite.',1465);
INSERT INTO "ricette" VALUES (5708,'Cicoria Belga Al Gratin','Contorno','Insalata Cicoria Belga',4,'Preparazione: 15 minuti. Cottura: 60 minuti.','750 G Insalata Cicoria Belga,
2 Cucchiai Succo Di Limone,
25 G Burro,
Sale,
Pepe,
Per La Salsa:,
40 Cl Latte,
25 G Farina,
1 Tuorlo D''uovo,
2 Cucchiai Formaggio Groviera Grattugiato,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Noce Moscata Grattugiata,
25 G Burro,
Sale,
Pepe,
Per La Decorazione:,
1 Ciuffetto Prezzemolo','Scaldate il forno a 170 gradi (termostato 5). Tagliate la base delle cicorie ed eliminatene la parte amara e le foglie esterne. Asciugatele. Sciogliete il burro, versatelo in una pirofila. Disponete le cicorie nella pirofila una accanto all''altra, salatele, pepatele e irroratele di succo di limone. Copritele con un foglio di alluminio e fatele cuocere per quarantacinque minuti in forno, finché sembrano trasparenti. Nel frattempo, preparate la salsa: fondete il burro in una pentola dal fondo spesso e gettatevi la farina. Lasciate cuocere per due o tre minuti a fuoco moderato mescolando con un cucchiaio di legno. Bagnate a poco a poco con il latte, sbattendo con una frusta e portate a ebollizione. Lasciate sobbollire da sette a dieci minuti, mescolando regolarmente, finché la salsa si addensa. Ritraetela dal fuoco e incorporatevi il tuorlo e la metà del groviera e del parmigiano. Aggiungete poco sale, pepe abbondante e noce moscata. Tenete in caldo. Quando le cicorie sono cotte, sgocciolatele e rimettetele nella pirofila. Copritele con salsa e cospargetele di groviera e parmigiano. Infornate sotto il grill e lasciate gratinare cinque minuti circa. Decorate con il prezzemolo. Servite immediatamente nella pirofila di cottura. Potete anche cuocere la cicoria belga in una casseruola, da venticinque a trenta minuti, a fuoco molto moderato e a pentola coperta. Trasferitela poi in una pirofila per gratinarla sotto il grill.',1212);
INSERT INTO "ricette" VALUES (5709,'Cicoria Belga Brasata','Contorno','Insalata Cicoria Belga',4,'Preparazione: 10 minuti. Cottura: 30 minuti.','8 Insalate Cicorie Belghe Piccole,
50 G Burro,
1/2 Limone (succo),
Sale,
Pepe','Mondate le cicorie, eliminate le foglie appassite, togliete, con un coltellino affilato, la parte amara alla base. Asciugatele. Sciogliete il burro a fuoco dolce in una pirofila abbastanza larga da contenere tutte le cicorie in un solo strato. Disponetevi le cicorie, salatele e pepatele. Coprite le cicorie con un foglio di carta pergamena imburrato con il lato unto a contatto con la verdura. Coprite ermeticamente la pirofila. Lasciate cuocere a fuoco dolce venti minuti, scuotendo il piatto ogni tanto. Togliete il foglio di carta pergamena, irrorate la verdura con il succo di limone, rimettete la pergamena e il coperchio e lasciate cuocere ancora per dieci o quindici minuti: le cicorie devono essere tenere. Potete anche infornare la pirofila a 170 gradi (termostato 5). In questo caso dovrete calcolare da quaranta a cinquanta minuti di cottura.',581);
INSERT INTO "ricette" VALUES (5710,'Cicoria Impazzita','Contorno','Insalata Cicoria',4,'Luogo: Ciociaria. Luogo: Lazio.','1000 G Insalata Cicoria,
1 Peperoncino Piccante Senza Semi,
2 Spicchi Aglio,
4 Cucchiai Olio D''oliva,
Sale','Pulire la cicoria lavandola con cura quindi lessarla in acqua abbondante poco salata per 45 minuti circa. Scolarla appena cotta e strizzarla. In una casseruola versare l''olio e farvi soffriggere gli spicchi d''aglio, il peperoncino e la cicoria, aggiungendo un pizzico di sale. Mescolare e continuare la cottura per circa 15 minuti.',1576);
INSERT INTO "ricette" VALUES (5711,'Cicoria In Padella','Contorno','Insalata Cicoria',4,' -','1000 G Insalata Cicoria,
2 Spicchi Aglio,
Olio D''oliva,
Sale,
Abbondante Pepe Nero','Mondare la verdura e lessarla per 15 minuti in acqua salata. Scolarla e strizzarla bene. Scaldare l''olio in un tegame e farvi rosolare l''aglio schiacciato, unire la cicoria, sale e abbondante pepe. Cuocere a fuoco vivo per alcuni minuti poi abbassare la fiamma, coprire il tegame e far insaporire per 5-10 minuti.',834);
INSERT INTO "ricette" VALUES (5712,'Cicoria Pazza','Contorno','Insalata Cicoria',4,'Luogo: Ciociaria. Luogo: Lazio.','1000 G Insalata Cicoria,
1 Peperoncino Piccante Senza Semi,
2 Spicchi Aglio,
4 Cucchiai Olio D''oliva,
Sale','Mondare e lavare accuratamente la cicoria. Lessarla in abbondante acqua leggermente salata per circa 45 minuti. Scolarla appena cotta e strizzarla. In una casseruola versare l''olio e farvi soffriggere gli spicchi d''aglio, il peperoncino e la cicoria, aggiungendo un pizzico di sale. Mescolare e continuare la cottura per circa 15 minuti.',1576);
INSERT INTO "ricette" VALUES (5713,'Cicoria Saporita','Contorno','Insalata Cicoria',4,' -','1000 G Insalata Cicoria,
1 Spicchio Aglio,
1 Rametto Timo,
100 G Burro,
50 G Formaggio Parmigiano,
Sale','Mondate, lavate e fate sgocciolare la cicoria. Fatela cuocere in abbondante acqua bollente e salata. Poi, appena cotta, scolatela e strizzatela bene. In una padella, dove in precedenza avrete fatto sciogliere il burro, fatevi rosolare lo spicchio d''aglio, sbucciato e leggermente schiacciato ed unitevi il rametto di timo. Aggregatevi la cicoria e fatela saltare, mescolandola di continuo con un cucchiaio di legno in modo che si insaporisca uniformemente. Condite con sale e due cucchiai di parmigiano.',1070);
INSERT INTO "ricette" VALUES (5714,'Cicorietta Con Purè Di Fave','Contorno','Insalata Cicorietta',4,' -','1000 G Insalata Cicorietta Di Campo,
350 G Fave Secche Decorticate,
Olio D''oliva Extra-vergine Molto Fruttato,
Poco Sale','Tenere a bagno le fave per 2h, quindi lessarle in acqua salata finché diventino una purea. Nel frattempo pulire, lavare la cicorietta e lessarla in poca acqua salata. Servire in un piatto piano la cicoria ben sgocciolata con accanto una porzione di purea. Condire con un filo d''olio crudo.',2105);
INSERT INTO "ricette" VALUES (5715,'Cider Cup','Bevande','Cognac',1,' -','1/3 Curacao,
1/3 Calvados,
1/3 Cognac,
Per Servire:,
Cedro,
Frutta Di Stagione','Preparare con ghiaccio in cubetti nella bowl. Servire nel cup riempiendo il bicchiere a metà, aggiungendo cedro e decorando con frutta di stagione.',524);
INSERT INTO "ricette" VALUES (5716,'Cielo Alto','Bevande','Vodka',4,' -','1000 G Carote,
50 G Burro,
25 Cl Panna Fresca,
Abbondante Basilico,
Sale,
Pepe','Pulire le carote e tagliarle a rondelle. Sciogliere il burro, unirvi le carote e farle cuocere a fuoco vivace. Salare, pepare e versarvi la panna, abbassando il fuoco. Unire alle carote il basilico tritato finemente e servire caldissimo.',1553);
INSERT INTO "ricette" VALUES (5717,'Cigarette','Bevande','Cognac Hennessy',1,' -','3 Cucchiai Cognac Hennessy,
1 Cucchiaio Liquore Strega,
1 Cucchiaio Cherry Stock,
1 Limone (succo),
Alcune Gocce Vodka,
1/2 Bottiglietta Tonica Water Schweppes,
Per Decorare:,
1 Fetta Mela,
1 Fetta Arancia,
1 Ciliegina','Preparare nel bicchiere tumbler grande con dei cubetti di ghiaccio. Decorare con 1 fetta di mela, 1 fetta d''arancia e 1 ciliegina.',532);
INSERT INTO "ricette" VALUES (5718,'Ciliegie Affogate Con Crema Inglese Di Canestrato','Dessert','Ciliegie',4,' -','10 Ciliegie,
1 Limone,
Sedano,
Carota,
100 G Zucchero,
Zucchero,
500 G Panna,
100 G Latte,
5 Tuorli D''uovo','Bollire il latte e la panna, unire i tuorli montati con lo zucchero e portare a cottura al crema sciogliendovi un po'' di canestrato. Servire con ciliegie affogate in succo di limone, sedano, carota e zucchero mischiati assieme.',2982);
INSERT INTO "ricette" VALUES (5719,'Ciliegie Al Barolo','Dessert','Ciliegie',4,' -','400 G Ciliegie Mature E Snocciolate,
150 G Zucchero,
10 Cl Gelatina Di Ribes,
Vino Barolo,
1/2 Stecca Cannella,
1 Arancia (scorza)','Mettere le ciliegie in una casseruola di rame, aggiungere lo zucchero, la cannella la scorza d''arancia tagliata 