 Freschi O Surgelati,
30 G Burro,
1 Cucchiaio Olio D''oliva,
3 Cucchiai Farina,
30 G Pancetta,
1 Bicchierino Cognac,
1/2 Bicchiere Latte,
1/2 Cipolla,
Noce Moscata,
Sale,
Pepe','Preparare le polpette, infarinarle e metterle in una casseruola con olio, burro, pancetta e cipolla tritata. Irrorare con il latte, salare, pepare e cospargere di noce moscata. Unire i piselli lessati, bagnare con il cognac, portare a cottura e servire.',1744);
INSERT INTO "ricette" VALUES (19418,'Polpette Con Piselli (2)','Contorno','Soia',4,' -','200 G Spezzatino Di Soia,
200 G Piselli,
2 Foglie Insalata Lattuga,
1 Cipolla,
Alcune Foglie Basilico,
Sale,
Pepe,
Burro','Preparate un soffritto con il burro, la cipolla tritata, il basilico e le foglie di lattuga. Aggiungete i piselli e lasciate insaporire per 5 minuti. Aggiungere lo spezzatino e lasciare cuocere a fuoco basso per circa 20 minuti.',1597);
INSERT INTO "ricette" VALUES (19419,'Polpette Con Spinaci','Carne','Manzo',4,' -','350 G Spinaci,
1 Cipolla,
250 G Carne Di Manzo Tritata,
40 G Pangrattato,
1 Uovo,
Latte,
1 Cucchiaio Prezzemolo Tritato,
Timo,
Formaggio Parmigiano,
Olio D''oliva,
Burro,
Sale','Riunire in una terrina pangrattato,timo,prezzemolo,uovo,carne e cipolla tritata e cotta in poco olio. Salare e unire il latte per ottenere un composto omogeneo. Ricavare 4 polpette, disporle in una pirofila imburrata, cospargerle con fiocchi di burro e cuocerle in forno caldo a 200 gradi per 15 minuti. Lessare per 15 minuti gli spinaci in acqua salata, scolarli e insaporirli in padella con burro e parmigiano. Servirli con le polpette.',2529);
INSERT INTO "ricette" VALUES (19420,'Polpette D''agnello Alle Melanzane','Carne','Agnello',4,' -','500 G Polpa D''agnello Tritata,
2 Melanzane,
2 Tuorli D''uovo,
Origano,
Prezzemolo,
4 Cucchiai Olio D''oliva,
Sale,
Pepe','Avvolgete le melanzane in un foglio d''alluminio e cuocetele in forno preriscaldato a 180 gradi per circa 30 minuti. Ritiratele, aprite l''involucro, lasciate intiepidire. Dividete le melanzane a metà e con un cucchiaio togliete parte della polpa. In una ciotola mescolate la carne d''agnello tritata, la polpa delle melanzane, l''origano, i tuorli, il prezzemolo tritato. Amalgamate bene. Salate e pepate. Con l''impasto formate tante piccole polpette e rosolatele in un tegame con quattro cucchiai d''olio. Passatele sul piatto da portata e servite. Vini di accompagnamento: Valpolicella Superiore DOC, Chianti Montalbano DOCG, Savuto DOC.',2835);
INSERT INTO "ricette" VALUES (19421,'Polpette Della Turingia','Contorno','Patate',4,'Luogo: Germania. Luogo: Turingia.','2000 G Patate,
Sale,
3 Panini,
Burro Fuso','Pelare 1000 g di patate e grattugiarle direttamente in un recipiente con acqua fredda affinché le patate non si anneriscano. Successivamente asciugare bene le patate con un panno. Pelare il resto delle patate e tagliarle a dadi. Cuocere le patate a fuoco lento insieme alle patate grattugiate precedentemente e mescolare continuamente fino ad ottenere un pure. Far bollire le patate, aggiungere il tutto alla pasta di patata cruda e salare. Tagliare a pezzettini il pane e friggerlo nel burro fuso fino ad ottenere un tono dorato. Formare delle polpette con la pasta di patata e riempirle con i pezzettini di pane. In una pentola larga far bollire dell''acqua con sale e aggiungere la quantità di polpette desiderata. Far cuocere per circa 20 minuti. Togliere le polpette con una schiumarola e metterle in un recipiente sul quale sarà stato collocato un piattino all''ingiù per scolare bene le polpette e perché queste non si attacchino. Possono essere un contorno ideale dello stufato di manzo con verdure.',3396);
INSERT INTO "ricette" VALUES (19422,'Polpette Di Acciughe','Pesce','Acciughe',4,' -','500 G Acciughe,
1 Uovo,
1/2 Bicchiere Latte,
60 G Formaggio Pecorino Grattugiato,
Pangrattato,
1 Spicchio Aglio,
Prezzemolo,
Olio D''oliva Extra-vergine,
Sale,
Pepe Bianco','Pulire, lavare le alici e triturarne i filetti. Amalgamarvi uovo, formaggio, latte, pangrattato, un trito d''aglio e prezzemolo e formare delle polpettine. Rigirarle nel pangrattato e friggerle nell''olio, servendole belle calde.',1954);
INSERT INTO "ricette" VALUES (19423,'Polpette Di Alici','Pesce','Acciughe',4,' -','500 G Acciughe,
1 Uovo,
1/2 Bicchiere Latte,
60 G Formaggio Pecorino Grattugiato,
Pangrattato,
1 Spicchio Aglio,
Prezzemolo,
Olio D''oliva Extra-vergine,
Sale,
Pepe Bianco','Pulire, lavare le alici e triturarne i filetti. Amalgamarvi uovo, formaggio, latte, pangrattato, un trito d''aglio e prezzemolo e formare delle polpettine. Rigirarle nel pangrattato e friggerle nell''olio, servendole belle calde.',1954);
INSERT INTO "ricette" VALUES (19424,'Polpette Di Baccalà','Pesce','Baccalà',4,' -','400 G Baccalà Ammollato,
500 G Patate,
2 Uova,
Prezzemolo,
1 Spicchio Aglio,
Sale,
Pepe,
Pangrattato,
Olio D''oliva','Lessare il baccalà, spellarlo, spinarlo e schiacciarlo in una terrina con una forchetta. A parte schiacciare le patate lessate, amalgamarvi le uova, uno spicchio di aglio tritato e il prezzemolo anch''esso tritato. Unire il composto al baccalà, salare, pepare e formare delle polpette. Passarle nel pangrattato e friggerle in abbondante olio bollente.',2107);
INSERT INTO "ricette" VALUES (19425,'Polpette Di Baccalà (2)','Pesce','Baccalà',6,'Luogo: Abruzzo.','1200 G Baccalà Già Ammollato,
100 G Mollica Di Pane Grattugiata,
2 Spicchi Aglio,
Prezzemolo,
2 Uova,
500 G Salsa Di Pomodoro,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lessate il baccalà quindi, dopo averlo spinato, sbriciolatelo ed unitevi il prezzemolo e l''aglio tritati, la mollica di pane e le uova sbattute. Aggiustate di sale e pepe quindi fate tante piccole polpettine. Friggetele nell''olio e fatele scolare su carta assorbente. A parte scaldate la salsa di pomodoro e versatela sulle polpette sistemate su un piatto da portata.',2765);
INSERT INTO "ricette" VALUES (19426,'Polpette Di Baccalà (3)','Pesce','Baccalà',4,'Luogo: Sicilia.','1000 G Filetti Di Baccalà,
1 Uovo,
Prezzemolo,
3 Cucchiai Formaggio Pecorino Grattugiato,
100 G Mollica Di Pane,
1 Spicchio Aglio,
Latte,
Farina,
Olio D''oliva,
Sale,
Pepe','Mettete a bagno il baccalà per 2 giorni. Lessate poi i filetti in acqua abbondante, sgocciolateli, eliminate spine e pelle. Amalgamate la polpa sminuzzata con la  mollica di pane inzuppata nel latte, strizzata e sbriciolata, uovo, trito d''aglio, prezzemolo e pecorino. Condite il composto con sale e, secondo gusto, con pepe. Formate delle polpette della grandezza di una noce. Infarinatele e friggetele in olio ben caldo.',2697);
INSERT INTO "ricette" VALUES (19427,'Polpette Di Borraggine','Contorno','Borraggine',4,' -','600 G Borraggine,
3 Uova,
40 G Mollica Di Pane Raffermo Sbriciolata,
50 G Formaggio Pecorino Grattugiato,
Prezzemolo,
Aglio,
Noce Moscata,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Mondare e lavare la borragine. Scottarla in poca acqua con un pizzico di sale. Scolarla e sminuzzarla. Una volta tiepida, unirvi le uova sbattute, il pecorino, la mollica di pane, il prezzemolo e l''aglio tritati finemente, sale, pepe, noce moscata. L''impasto deve avere giusta consistenza (eventualmente aggiungere altro pane). Ricavarne delle polpette e friggerle nell''olio.',1472);
INSERT INTO "ricette" VALUES (19428,'Polpette Di Broccoli','Contorno','Broccoli',4,' -','450 G Broccoli,
3 Uova Sode,
10 Filetti D''acciughe Sott''olio,
9 Cucchiai Pangrattato,
2 Spicchi Aglio,
1 Peperoncino,
Olio D''oliva,
Sale,
Pepe','Lessare i broccoli, scolarli bene e frullarli. Unire ai broccoli i tuorli, il pangrattato, gli albumi a dadini, sale e pepe. Formare delle polpettine e cuocerle al vapore per 10 minuti. Scaldare 6 cucchiai d''olio e unirvi l''aglio, il peperoncino e le acciughe e cuocere finché queste si saranno sciolte bene. Mettere le polpettine in un piatto da portata e irrorarle con l''olio caldo filtrato. Servire subito.',1835);
INSERT INTO "ricette" VALUES (19429,'Polpette Di Carote','Contorno','Carote',4,' -','300 G Carote,
500 G Patate,
1 Uovo,
100 G Formaggio Bitto,
1 Foglia Alloro,
Semi Di Cumino,
Rosmarino,
1 Spicchio Aglio,
Olio D''oliva Extra-vergine,
Sale Marino','Lessare in poca acqua con aglio e alloro patate sbucciate e carote spazzolate; scolarle e passarle. Alla purea ottenuta unire 1 uovo, sale e, se l''impasto lo richiede, un po'' di farina. Farne polpettine e mettere in ciascuna un dadino di formaggio. Infarinare e friggere dolcemente nell''olio aromatizzati con cumino e rosmarino.',1652);
INSERT INTO "ricette" VALUES (19430,'Polpette Di Carote (2)','Contorno','Carote',4,'Luogo: Russia.','1000 G Carote,
500 G Latte,
50 G Semolino,
3 Uova,
Pangrattato,
150 G Burro,
Salsa Smetana,
Sale','Grattugiate le carote che avrete già pulite e lavate; ponetele in una pentola e versate il latte caldo in modo che le carote siano coperte. Aggiungete 50 g di burro ammorbidito, salate e coprite la pentola, cuocete per 20 minuti a fuoco lento rimescolando ogni tanto perché non attacchi. Versate quindi nella pentola il semolino e mescolando continuate la cottura per altri 8-10 minuti. Togliete la pentola dal fuoco, lasciate riposare per 5 minuti poi mettete i tuorli delle uova mettendo da parte gli albumi. Amalgamate bene il tutto e lasciatelo raffreddare completamente. Con questo impasto fate poi le polpette di forma ovale o tonda. Sbattete con il sale gli albumi delle uova messi da parte, bagnatevi le polpette e passatele nel pangrattato. In padella sciolto il burro, fate rosolare da ogni parte a fuoco vivo le polpette di carote; a cottura disponetele sul piatto da portata e servitele con a parte nella salsiera la smetana.',2452);
INSERT INTO "ricette" VALUES (19431,'Polpette Di Carote (3)','Contorno','Carote',4,' -','600 G Carote,
4 Cucchiai Farina,
2 Uova,
4 Cucchiai Formaggio Parmigiano Grattugiato,
Prezzemolo Tritato,
Olio D''oliva,
Sale,
Pepe','Lavare e pelare le carote. Asciugarle e grattugiarle. Incorporarvi le uova, 4 cucchiai di farina, il parmigiano, il prezzemolo tritato, sale e pepe. Amalgamare bene gli ingredienti e formare delle polpettine. Friggerle in olio bollente e passarle nella carta assorbente prima di portarle in tavola.',1543);
INSERT INTO "ricette" VALUES (19432,'Polpette Di Castagne','Dessert','Castagne',6,' -','1000 G Castagne,
5 Cucchiai Cioccolato In Polvere,
1 Bicchierino Rum,
1 Tuorlo D''uovo,
4 Cucchiai Zucchero','Fate bollire le castagne, poi sbucciatele, passatele nel passaverdura fine ed aggiungete l''uovo, il rum, lo zucchero e la polvere di cioccolato, amalgamando tutto molto bene. Lasciate riposare 5 minuti e poi fate delle palline come delle polpette, passatele quindi nello zucchero per farle rimanere come caramellate.',2730);
INSERT INTO "ricette" VALUES (19433,'Polpette Di Castagne (2)','Dessert','Castagne',4,' -','1000 G Castagne,
5 Cucchiai Cacao In Polvere,
1 Tuorlo D''uovo,
1 Bicchierino Rum,
4 Cucchiai Zucchero,
Zucchero A Velo','Bollire le castagne, pelarle e passarle al passaverdura. Unire alla purea di castagne il tuorlo, il rum, il cacao e lo zucchero. Amalgamare bene e a lungo gli ingredienti. Lasciar riposare l''impasto per 30 minuti. Formare delle palline e rotolarle nello zucchero a velo prima di servirle.',2556);
INSERT INTO "ricette" VALUES (19434,'Polpette Di Ceci','Contorno','Ceci',4,' -','250 G Ceci In Scatola,
1 Uovo,
1 Spicchio Aglio,
Rosmarino Tritato,
6 Cucchiai Pangrattato,
Sale,
Pepe,
Olio D''oliva,
Brodo','Scolare i ceci e passarli al passaverdura. Unire alla purea l''uovo, rosmarino, sale, pepe, l''aglio tritato e 6 cucchiai di pangrattato. Amalgamare bene e formare delle polpettine ovali e un po'' schiacciate. Farle dorare in padella con l''olio, poi bagnare con un po'' di brodo, coprire e cuocere per circa 10 minuti.',2024);
INSERT INTO "ricette" VALUES (19435,'Polpette Di Ceci (2)','Contorno','Ceci',4,' -','300 G Ceci In Scatola,
2 Spicchi Aglio,
1 Cucchiaino Cumino In Polvere,
1 Cucchiaino Coriandolo In Polvere,
1 Cipollotto,
1 Presa Pepe Di Caienna,
Sale,
Pepe,
Abbondante Olio D''oliva,
Prezzemolo','Scolare i ceci e passarli al passaverdura. Mettere il purè di ceci nel frullatore e aggiungere 1 cucchiaino di cumino e 1 di coriandolo, l''aglio, una presa di pepe di caienna, prezzemolo, cipollotto, sale e pepe e frullare il tutto. Far riposare il composto per almeno 30 minuti, poi formare delle polpettine e friggerle in abbondante olio ben caldo.',1857);
INSERT INTO "ricette" VALUES (19436,'Polpette Di Cozze','Pesce','Cozze',4,' -','1500 G Cozze,
1 Uovo,
70 G Mortadella,
2 Spicchi Aglio,
500 G Pomodori Perini,
3 Cucchiai Pangrattato,
3 Cucchiai Formaggio Grana Grattugiato,
1 Ciuffo Prezzemolo,
10 Cl Vino Bianco,
Sale,
Olio D''oliva,
Sale,
Pepe','Far aprire le cozze nel vino bianco e sgusciarle. Tritarle, unire l''uovo, la mortadella tritata con 1 spicchio d''aglio, 3 cucchiai di pangrattato e 3 di grana, sale, pepe e formare delle polpettine. Tritare un ciuffo di prezzemolo e farlo dorare in olio con l''aglio intero, unire i pomodori a tocchetti e le polpette, aggiustare di sale e cuocere per 10 minuti circa.',2459);
INSERT INTO "ricette" VALUES (19437,'Polpette Di Fagioli','Contorno','Fagioli',4,' -','300 G Fagioli Rossi Secchi,
1 Gambo Sedano,
1 Cipolla,
1 Carota,
2 Foglie Alloro,
2 Uova,
50 G Formaggio Parmigiano,
50 G Pangrattato,
2 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Pepe','Mettete a bagno i fagioli in acqua per qualche ora, in modo che si ammorbidiscano bene, quindi lessateli per un''ora e mezza con le verdure. Scolate i fagioli e passateli, unite i 2 tuorli d''uovo, il parmigiano e metà del pangrattato, sale e pepe. Amalgamate con cura e, se l''impasto risulterà troppo molle, aggiungete altro parmigiano e pangrattato. Lavorate con le mani delle polpettine, schiacciatele, passatele quindi negli albumi, lasciandovele per qualche minuto, e poi nel pangrattato facendolo aderire bene; a questo punto friggetele nell''olio ben caldo.',1732);
INSERT INTO "ricette" VALUES (19438,'Polpette Di Fiocchi Di Riso','Contorno','Fiocchi Di Riso',4,' -','150 G Fiocchi Di Riso,
1 Tuorlo D''uovo,
2 Cipolle,
Farina,
Timo Tritato,
Maggiorana Tritata,
Basilico Tritato,
Sale,
Olio D''oliva Extra-vergine','In una padella soffriggete dolcemente le cipolle finemente tritate con l''olio; una volta diventate morbide, lasciatele raffreddare. In una terrina, mettete i fiocchi di riso e bagnateli con un bicchiere d''acqua tiepida e lasciateli gonfiare per almeno 15 minuti. Aggiungete ai fiocchi di riso, il soffritto di cipolle, le erbe aromatiche tritate, il tuorlo d''uovo sbattuto, un pizzico di sale. Lavorate bene per amalgamare tutti gli ingredienti (se necessario aggiungete un po'' di farina). Con l''impasto formate delle polpettine che, dopo una leggera infarinatura, metterete in una teglia da forno leggermente unta. Cuocere in forno a 180 gradi girandole spesso, e dopo circa 40 minuti o in ogni modo quando avranno assunto un bel colore dorato e servite le polpette su un letto d''insalata.',1725);
INSERT INTO "ricette" VALUES (19439,'Polpette Di Funghi Siciliane','Contorno','Funghi',4,'Luogo: Sicilia.','500 G Funghi Porcini Già Puliti,
2 Uova,
3 Spicchi Aglio,
2 Cucchiai Pangrattato,
1 Manciata Prezzemolo Tritato,
2 Cucchiai Formaggio Pecorino Grattugiato,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Pulire i funghi e cuocerli a vapore in pochissima acqua con poco sale. Scolarli, tritarli finemente e metterli in una terrina. Unire le uova, l''aglio tritato con una manciata di prezzemolo, 2 cucchiai di pecorino e 2 di pangrattato, sale e pepe. Amalgamare il tutto, aggiungendo eventualmente altro pangrattato se l''impasto risulta molle. Ricavare 20-25 polpettine rotonde. Friggerle in olio molto caldo facendole dorare e posarle su carta assorbente. Metterle in un piatto caldo e servire subito.',1339);
INSERT INTO "ricette" VALUES (19440,'Polpette Di Maiale','Carne','Maiale',4,'Luogo: Russia.','800 G Carne Di Maiale Tritata,
1 Panino,
Latte,
1 Uovo,
Sale,
Pepe,
2 Cucchiai Olio D''oliva,
1 Carota,
1 Cipolla,
1 Costa Sedano,
1 Ciuffo Prezzemolo,
1 Pizzico Origano,
300 G Polpa Di Pomodoro,
1 Cucchiaio Farina','Impastare 800 g di carne di maiale tritata con un panino ammorbidito nel latte e strizzato, un uovo, sale e pepe. Fare delle polpette grandi come una noce e friggerle nel burro. Scolarle e tenerle al caldo. Soffriggere in 2 cucchiai d''olio il trito di una carota, una cipolla, una costa di sedano, un ciuffo di prezzemolo e un pizzico di origano. Unire 300 g di polpa di pomodoro e sobbollire per 15 minuti. Salare, pepare e aggiungere un cucchiaio di farina diluita in 1/2 bicchiere di latte. Portare a bollore e versare la salsa sulle polpette calde.',3155);
INSERT INTO "ricette" VALUES (19441,'Polpette Di Manzo Al Brandy','Carne','Manzo',4,' -','400 G Carne Di Manzo Tritata,
50 G Prosciutto Cotto,
2 Tuorli D''uovo,
50 G Formaggio Grattugiato,
50 G Burro,
1/2 Bicchiere Brandy,
1 Cipolla Piccola,
Prezzemolo,
Farina,
Alcuni Cucchiai Besciamella,
Pepe,
1 Cucchiaio Olio D''oliva,
Sale','In una ciotola amalgamate la carne con il prosciutto cotto tritato, i due tuorli, il formaggio grattugiato, il prezzemolo tritato, qualche cucchiaio di besciamella, sale e pepe. Fate tante polpettine. Infarinatele. In un tegame scaldate il burro con un cucchiaio d''olio; insaporitevi la cipolla tritata, cuocetevi le polpette a fuoco vivace un minuto da ogni lato; riducete il calore. Dopo 15 minuti circa passate le polpette su un piatto da portata e tenetele al caldo. Versate sul fondo di cottura due o tre cucchiai d''acqua tiepida e uno di ottimo brandy, mescolate bene e fate ridurre sino a ottenere un sughetto denso. Ritirate dal fuoco, mescolate, versatelo sulle polpette e servite. Vini di accompagnamento: Botticino DOC, Colli Di Luni Rosso DOC, Romagnano Rosso VdT Del Lazio.',2369);
INSERT INTO "ricette" VALUES (19442,'Polpette Di Manzo Al Limone','Carne','Manzo',4,' -','400 G Carne Di Manzo Tritata,
50 G Formaggio Grattugiato,
4 Cucchiai Besciamella,
40 G Burro,
1 Spruzzo Salsa Worcester,
4 Cucchiai Panna,
1/2 Limone,
1 Cucchiaino Pangrattato,
Sale','In una ciotola mettete la carne, il formaggio grattugiato, la besciamella, uno spruzzo di Worcester e il sale. Amalgamate bene l''impasto e ricavatene otto polpette dalla forma rotonda e schiacciata. In un tegame lasciate sciogliere il burro e quando comincia a diventare color oro adagiatevi le polpette cuocendo a fuoco moderato per circa un quarto d''ora. Passatele sul piatto da portata e tenetele al caldo. Versate nel tegame quattro cucchiai di panna, il succo di mezzo limone filtrato al colino, un cucchiaino di pangrattato, mescolate e fate leggermente addensare e insaporire. Versate la salsa calda sulle polpette, servite subito a tavola.',1329);
INSERT INTO "ricette" VALUES (19443,'Polpette Di Manzo Alle Acciughe','Carne','Manzo',4,' -','400 G Polpa Di Manzo Tritata,
Latte,
2 Panini,
Prezzemolo,
1 Spicchio Aglio,
1 Tuorlo D''uovo,
2 Cucchiai Formaggio Grattugiato,
2 Filetti D''acciughe,
Pangrattato,
Olio D''oliva,
Sale,
Pepe','Tritate finemente un ciuffo di prezzemolo, l''aglio, i filetti d''acciughe e uniteli alla carne. Ammorbidite l''impasto con il tuorlo e la mollica dei panini bagnata nel latte e ben strizzata, il formaggio grattugiato, sale e pepe. Amalgamate bene il tutto e ricavatene otto-dieci polpette. Schiacciatele un po''. Passatele nel pangrattato finissimo. Velate il fondo di un tegame con un pochino d''olio e rosolatevi a fuoco vivace le polpette un minuto da entrambe le parti. Coprite e continuate la cottura per una decina di minuti a fuoco basso. Servitele ben calde con spinaci al burro. Vini di accompagnamento: Barbera D''Asti DOC, Friuli Aquileia Merlot DOC, Cori Rosso DOC.',2377);
INSERT INTO "ricette" VALUES (19444,'Polpette Di Manzo Alle Patate','Carne','Manzo',4,' -','300 G Carne Di Manzo,
2 Fette Mortadella,
2 Patate Lessate,
1 Uovo,
1 Cucchiaio Formaggio Grattugiato,
Prezzemolo,
Pangrattato,
Olio D''oliva,
Sale,
Pepe','Tritate finemente la carne e la mortadella; schiacciate le patate lessate mentre sono ancora calde. Mescolate il tutto, legate l''impasto con un uovo; insaporitelo con un cucchiaio di formaggio e un po'' di prezzemolo tritato, sale e pepe. Preparate otto polpette, passatele nel pangrattato e friggetele in olio ben caldo. Asciugatele su carta assorbente, passatele su un piatto da portata caldo, servitele con un''insalata di lattughino. Vini di accompagnamento: Riviera Del Garda Bresciano Rosso DOC, Colli Dell''Etruria Centrale Rosso DOC, Sant''Agata Dé Goti Rosso DOC.',2155);
INSERT INTO "ricette" VALUES (19445,'Polpette Di Manzo Con Spinaci','Carne','Manzo',4,' -','250 G Carne Di Manzo,
250 G Spinaci,
1/2 Tazza Besciamella,
30 G Formaggio,
1 Uovo,
30 G Burro,
Farina,
Olio D''oliva,
Sale','Lessate gli spinaci, sgocciolateli, tritateli. Tritate finemente anche la carne. Fate la besciamella. Amalgamate tutto e insaporite l''impasto con il formaggio grattugiato, l''uovo e il sale. Preparate otto polpette, infarinatele e friggetele in un tegame con due cucchiai d''olio e il burro ben caldi. Asciugatele su carta assorbente, servitele subito a tavola. Vini di accompagnamento: Sorni Rosso DOC, Biferno Rosato DOC, Sangiovese D''Arborea DOC.',1867);
INSERT INTO "ricette" VALUES (19446,'Polpette Di Manzo Saporite','Carne','Manzo',4,' -','400 G Polpa Di Manzo Tritata,
1 Cipolla Grande,
70 G Burro,
2 Tuorli D''uovo,
Sale,
Pepe','In un tegame lasciate sciogliere metà burro, cuocetevi la cipolla affettata per 10 minuti a fuoco basso. Salate. Unite alla carne metà salsa, legate con i tuorli, salate e pepate. Ricavate otto polpette. Cuocetele in una padella a fuoco vivace con il restante burro. Passatele sul piatto, nappatele con il fondo di cottura e guarnitele con la salsa di cipolla avanzata. Vini di accompagnamento: Dolcetto D''Asti DOC, Montescudaio Rosso DOC, Castel Del Monte Rosso DOC.',1190);
INSERT INTO "ricette" VALUES (19447,'Polpette Di Melanzane','Contorno','Melanzane',4,' -','300 G Carne Tritata,
450 G Melanzane,
1 Cucchiaio Cipolla Affettata E Imbiondita,
3 Tuorli D''uovo,
Farina,
2 Uova Sbattute,
Pangrattato,
Olio D''oliva,
2 Limoni,
Sale,
Pepe','Unire alla carne le melanzane tritate, la cipolla, i tuorli d''uovo, salare, pepare e farne un impasto omogeneo. Con le mani infarinate formare delle palline, passarle nell''uovo battuto e, poi, nel pangrattato. Friggerle in olio fumante, sgocciolarle e servire con mezzi limoni.',2268);
INSERT INTO "ricette" VALUES (19448,'Polpette Di Melanzane (2)','Antipasto','Melanzana',4,'Luogo: Sicilia.','1 Melanzana,
1 Spicchio Aglio,
Basilico,
1 Uovo,
Pangrattato,
2 Cucchiai Formaggio Parmigiano Grattugiato (o Ricotta Salata),
Formaggio Provoletta','Cuocere le melanzane dopo averle sbucciate; si possono stufare in padella, o lessare al microonde, o in forno. Schiacciarle con una forchetta, ripassare la purea in una padella antiaderente con uno spicchio di aglio schiacciato ed il basilico. In una ciotola aggiungere alla purea un uovo, due cucchiai di formaggio grattugiato, sale, pepe e pangrattato il minimo indispensabile a dare un poco di consistenza all''impasto, quindi tagliare dei cubetti di provoletta. Nella mano sinistra mettere un poco di impasto, al centro un cubetto di formaggio, poi chiudere a polpetta e schiacciare. Passare nel pangrattato e friggere fino a doratura.',922);
INSERT INTO "ricette" VALUES (19449,'Polpette Di Melanzane (3)','Antipasto','Melanzana',4,'Luogo: Sicilia.','1 Melanzana,
1 Spicchio Aglio,
Basilico,
1 Uovo,
Pangrattato,
2 Cucchiai Ricotta Salata,
Formaggio Provoletta','Cuocere le melanzane dopo averle sbucciate; si possono stufare in padella, o lessare al microonde, o in forno. Schiacciarle con una forchetta, ripassare la purea in una padella antiaderente con uno spicchio di aglio schiacciato ed il basilico. In una ciotola aggiungere alla purea un uovo, due cucchiai di ricotta salata, sale, pepe e pangrattato il minimo indispensabile a dare un poco di consistenza all''impasto, quindi tagliare dei cubetti di provoletta. Nella mano sinistra mettere un poco di impasto, al centro un cubetto di formaggio, poi chiudere a polpetta e schiacciare. Passare nel pangrattato e friggere fino a doratura.',826);
INSERT INTO "ricette" VALUES (19450,'Polpette Di Melanzane Alla Rumena','Contorno','Melanzane',6,'Luogo: Romania.','6 Melanzane,
2 Uova,
3 Cucchiai Prezzemolo Tritato,
1 Presa Origano,
1 Fetta Pane Bagnato Nel Latte,
2 Cucchiai Farina,
3 Cucchiai Olio D''oliva,
1 Manciata Pinoli Tritati,
1 Pugno Uvetta Sultanina,
Per La Salsa:,
500 G Pomodori Freschi,
1 Cipolla,
1 Cucchiaio Prezzemolo,
Alcune Foglie Basilico,
Poco Olio D''oliva,
Sale,
Pepe','Lavate le melanzane, arrostitele sul fuoco e toglietene la pelle. Mettete la polpa ben cotta in un piatto e schiacciatele con la forchetta. Ponete la poltiglia in una terrina e aggiungetevi il pane strizzato, l''uovo sbattuto, i pinoli, l''uvetta, una parte della farina, il prezzemolo, l''origano in polvere e poco olio. Ricavate delle polpette, passatele nella farina rimanente e friggetele nell''olio. In precedenza avrete già preparato la salsa di pomodoro con gli aromi. Disponete quindi le polpette di melanzane in un tegame, versatevi sopra la salsa e lasciatele andare per alcuni minuti, a fuoco moderato.',2813);
INSERT INTO "ricette" VALUES (19451,'Polpette Di Melanzane Alle Olive','Contorno','Melanzane',4,' -','3 Melanzane,
2 Cucchiai Formaggio Pecorino Grattugiato,
1 Mazzetto Insalata Rucola,
1 Ciuffo Basilico,
Olive Nere,
4 Pomodori Perini,
1 Uovo,
1 Pugno Mollica Di Pane Bagnata E Strizzata,
Farina,
Peperoncino Fresco,
Alcuni Cucchiai Olio D''oliva Extra-vergine,
Sale','In acqua bollente salata scottate le melanzane, scolatele e strizzatele per eliminare l''acqua. Sbucciatele, riducete la polpa in pezzetti e passateli al tritatutto. Mettete in una terrina il passato di melanzane, il pecorino, il basilico (tranne qualche fogliolina) e metà mazzetto di rucola tritati, l''uovo, il pane e il peperoncino tritato. Mescolate con cura e salate. Con il composto formate delle palline grandi come una noce, infarinatele e cuocetele a vapore per 7/8 minuti. Trascorso questo tempo, foderate con carta da forno una placca, disponetevi le polpette, spennellatele di olio e lasciatele dorare in forno preriscaldato a 220 gradi per 10 minuti. Tagliate i pomodori, eliminate i semi e riduceteli a dadini. Unite qualche cucchiaio di olio, alcune foglie di basilico spezzettato, la rucola rimasta e le olive; salate solo al momento di servire e accompagnate con questa insalata le polpette di melanzane.',2500);
INSERT INTO "ricette" VALUES (19452,'Polpette Di Melanzane Pugliesi','Primo','Melanzane',4,'Luogo: Puglia.','1 Melanzana,
1 Uovo,
50 G Pane Raffermo,
Ricotta Grattugiata,
1 Tazza Brodo Vegetale,
Foglie Di Menta,
Prezzemolo,
Noce Moscata,
Sale,
Pepe','Mondare la melanzana, tagliarla a metà per lungo, appassirla in forno sulla placca con la parte tondeggiante rivolta verso l''alto (180 gradi per 30 minuti). Togliere la pelle e impastare la polpa con la mollica di pane già bagnata nel brodo vegetale e strizzata, uovo, ricotta grattugiata, erbe e spezie, sale, pepe. Formare delle polpettine e farle cuocere nella zuppa di cardi.',536);
INSERT INTO "ricette" VALUES (19453,'Polpette Di Merluzzo','Pesce','Merluzzo',4,' -','400 G Merluzzo,
3 Uova,
100 G Patate,
Abbondante Noce Moscata,
3 Cucchiai Farina,
Vino Bianco,
Olio D''oliva,
Sale,
Pepe','Preparare una pastella con 200 g di farina, 2 tuorli, 3 cucchiai di olio, sale e pepe. Unire vino bianco sufficiente ad ottenere una crema densa e 2 albumi montati a neve. Tritare il merluzzo e amalgamarlo con le patate lessate, abbondante noce moscata, 1 uovo, 3 cucchiai di farina, sale e pepe. Formare delle polpette con questo composto, passarle nella pastella e friggerle in olio ben caldo.',1623);
INSERT INTO "ricette" VALUES (19454,'Polpette Di Montone','Carne','Montone',4,'Luogo: Grecia.','250 G Carne Di Montone Già Cotto,
1 Scorzetta Di Limone,
2 Spicchi Aglio,
1 Ciuffo Prezzemolo,
1 Fetta Pane Bianco,
Latte,
Sale,
Pepe,
Noce Moscata,
2 Uova,
Olio D''oliva,
Succo Di Limone','Tritare 250 g di carne di montone già cotto con 1 scorzetta di limone, 2 spicchi d''aglio e 1 ciuffo di prezzemolo. Unire alla carne una fetta di pane bianco imbevuto nel latte e strizzato, sale, pepe, noce moscata e 2 uova. Amalgamare bene il tutto e formare polpette grandi come una noce, infarinarle leggermente e friggerle in olio bollente. Scolarle su carta assorbente e servirle calde o fredde spruzzate con succo di limone.',1597);
INSERT INTO "ricette" VALUES (19455,'Polpette Di Palamita','Pesce','Palamita',4,' -','1 Palamita Da 600 G,
2 Uova,
300 G Mollica Di Pane Raffermo,
Brodo Vegetale,
1 Arancia,
1 Cipolla,
Prezzemolo,
Pangrattato,
Olio D''oliva Extra-vergine,
Sale,
Pepe Bianco','Far bollire la palamita con la cipolla per 30 minuti in acqua salata. Spellarla e ricavarne la polpa eliminando le parti scure. Frullarla con cipolla lessa, mollica, prezzemolo, succo d''arancia, uova, brodo, sale, pepe. Ricavare dal composto delle palline; passarle nel pangrattato e friggerle in olio ben caldo.',2840);
INSERT INTO "ricette" VALUES (19456,'Polpette Di Pane','Primo','Pane Raffermo',4,' -','450 G Pane Raffermo,
3 Pomodori,
1 Uovo,
2 Cucchiai Farina,
4 Cipollotti,
Sale,
Pepe,
Latte,
Olio D''oliva,
Basilico','Ammollare il pane nel latte. Scottare i pomodori, spellarli e tagliarli a tocchetti. Strizzare il pane e sbriciolarlo con le mani in una terrina. Incorporarvi l''uovo, i pomodori, la farina, i cipollotti tritati, sale, pepe e il basilico tritato. Amalgamare bene e formare delle polpettine ovali. Friggerle in abbondante olio caldo.',2364);
INSERT INTO "ricette" VALUES (19457,'Polpette Di Pesce','Pesce','Nasello',4,' -','200 G Filetti Di Nasello,
200 G Filetti Di Platessa,
1 Cipolla,
1 Costa Sedano,
1 Ciuffo Prezzemolo,
1 Limone,
2 Fette Pancarré,
1 Cucchiaio Prezzemolo Tritato,
Noce Moscata,
1 Uovo,
Farina,
Olio Per Friggere,
Sale','Lessate in acqua bollente salata i filetti di pesce ben puliti con cipolla, sedano, prezzemolo, il succo del limone e un pizzico di sale. Cuocete una decina di minuti, scolate i filetti, sbriciolateli in una terrina con la mollica del bane bagnata e ben strizzata, il prezzemolo tritato, un po'' di noce moscata e l''uovo sbattuto. Amalgamate, aggiustate di sale e, se necessario, assodate con un po'' di farina. Preparate tante polpettine grandi come noci, passatele nel pangrattato e friggetele in abbondante olio bollente.',2093);
INSERT INTO "ricette" VALUES (19458,'Polpette Di Pesce (2)','Pesce','Pesce',4,' -','200 G Pesce Già Cotto,
50 G Besciamella Già Pronta,
1 Fetta Pancarré,
1 Uovo,
Poca Farina,
Burro,
Sale,
Per Servire:,
Alcuni Spicchi Limone','Sbriciolare il pesce ben pulito e mescolarlo in 1 ciotola con la besciamella, il pancarré leggermente bagnato e sbriciolato e l''uovo. Salare, formare delle piccole polpette, passarle nella farina, scuotendo quella in eccesso e rosolarle nel burro. Servirle con spicchi di limone a piacere.',1477);
INSERT INTO "ricette" VALUES (19459,'Polpette Di Polipo All''opatia','Pesce','Polipo',4,'Luogo: Jugoslavia.','1 Polipo Di 1000 G,
150 G Mollica Di Pane,
1/2 Cipolla,
1 Spicchio Aglio,
120 G Latte,
100 G Olio D''oliva,
2 Uova,
1 Tazzina Farina,
Prezzemolo,
Noce Moscata,
Sale,
Pepe','Lavate e pulite il polipo. Cuocetelo in acqua salata bollente finché non si ammorbidisce. Tiratelo fuori dall''acqua e privatelo della pelle finché è tiepido dopodichè tritatelo finemente. Mettete a mollo la mollica del pane nel latte freddo. In 40 g di olio bollente fate rosolare la cipolla, aggiungete l''aglio e il prezzemolo e continuare la cottura. Strizzate il pane e aggiungetelo al polipo tritato. Aggiungete del pepe, sale, noce moscata, il soffritto, le uova e il sale. Impastate bene e ricavate otto polpette, infarinatele quindi passatele nell''uovo sbattuto e friggerle in olio bollente fino a doratura.',2245);
INSERT INTO "ricette" VALUES (19460,'Polpette Di Pollo','Pollame','Pollo',4,' -','250 G Petto Di Pollo Già Lessato,
150 G Prosciutto Cotto,
2 Uova,
3 Cucchiai Formaggio Parmigiano Grattugiato,
3 Cucchiai Pangrattato,
Olio Per Friggere,
1 Pizzico Noce Moscata,
Pepe,
Sale','Amalgamare pollo e prosciutto macinati, 1 uovo, il parmigiano, la noce moscata, sale e pepe. Formare con le mani inumidite delle polpette grandi come un uovo da appiattire leggermente. Passarle prima nell''uovo sbattuto con un po'' di sale e poi nel pangrattato. Friggerle nell''olio bollente e servirle calde.',2220);
INSERT INTO "ricette" VALUES (19461,'Polpette Di Pollo (2)','Pollame','Pollo',4,' -','400 G Petto Di Pollo,
2 Uova,
10 G Funghi Secchi,
Mollica Di Pane,
Latte,
Prezzemolo,
Farina,
Pangrattato,
Abbondante Olio D''oliva,
Burro,
Sale','Ammollare i funghi in acqua tiepida per 30 minuti. Bagnare la mollica con il latte, strizzarla e porla in una terrina. Unire un pezzetto di burro morbido, il pollo tritato, i funghi scolati e tritati, il prezzemolo tritato, 1 uovo, sale e pepe. Mescolare molto bene il composto. Formare delle polpette e passarle prima nella farina, poi nell''uovo sbattuto e infine nel pangrattato. Friggerle in abbondante olio bollente.',3179);
INSERT INTO "ricette" VALUES (19462,'Polpette Di Pomodoro','Contorno','Pomodori',4,' -','3 Pomodori Maturi,
450 G Pane Raffermo,
1 Uovo,
4 Cipollotti,
Latte,
2 Cucchiai Farina,
Basilico,
Sale,
Pepe,
Olio D''oliva','Ammollare il pane nel latte. Scottare i pomodori, pelarli, privarli dei semi e tagliarli a dadini. Strizzare il pane, sbriciolarlo e porlo in una terrina. Incorporare l''uovo, 2 cucchiai di farina, i pomodori, i cipollotti e il basilico tritati, sale e pepe. Amalgamare il composto e formare delle polpettine ovali. Friggerle in abbondante olio bollente e passarle nella carta da cucina prima di servirle.',2364);
INSERT INTO "ricette" VALUES (19463,'Polpette Di Ricotta','Antipasto','Ricotta Romana',4,' -','200 G Ricotta Romana,
1 Spicchio Aglio,
Prezzemolo,
1 Uovo,
2 Cucchiai Pangrattato,
1 Noce Burro,
3 Cucchiai Olio D''oliva,
1 Presa Sale','Sgusciare l''uovo in 1 terrina, salarlo e sbatterlo leggermente. Continuando a mescolare, incorporarvi la ricotta, l''aglio e il prezzemolo mondati e tritati, 2 cucchiai di pangrattato e 1 presa di sale. Suddividere quindi il composto in palline, poi passarle nel pangrattato, formando delle polpettine. Mettere sul fuoco 1 padella con 1 noce di burro e 3 cucchiai d''olio. Appena il condimento soffrigge, adagiarvi le polpettine e farle dorare qualche minuto per parte.',2113);
INSERT INTO "ricette" VALUES (19464,'Polpette Di Ricotta Con Pomodoro','Antipasto','Ricotta Romana',4,' -','500 G Ricotta Romana,
40 G Formaggio Grana Padano Grattugiato,
5 Foglie Menta,
40 G Pinoli,
2 Rametti Maggiorana,
2 Pomodori Ramati,
2 Fette Pane Per Tramezzini,
1 Filo Olio D''oliva,
Sale,
1 Pizzico Noce Moscata Grattugiata','Mescolate in una terrina la ricotta con il grana, una presa di sale, un pizzico di noce moscata grattugiata.Tritate finemente le foglie di menta e maggiorana, aggiungete la ricotta e mescolate bene. Formate con le mani inumidite, 4 grosse polpette piatte che disporrete in quattro piatti piani; scottate in acqua in ebollizione, per pochi secondi, i pomodori, scolateli, spellateli, privateli dei semi e riducete la polpa a dadini. Tostate i pinoli in un padellino antiaderente, poi distribuiteli sulle polpette di ricotta; ungete con un filo di olio le fette di pane tostate sotto il grill del forno e tagliatele a triangolini. Distribuite al centro delle polpette la dadolata di pomodoro, condite con un filo di olio e un pizzico di sale. Disponete i triangolini di pane tostato intorno alle polpette e servite subito.',1789);
INSERT INTO "ricette" VALUES (19465,'Polpette Di Ricotta In Brodo','Primo','Ricotta',4,'Luogo: Calabria.','100 G Ricotta Di Pecora,
2 Uova,
50 G Mollica Di Pane,
1 Cucchiaio Formaggio Pecorino Grattugiato,
1 Macinata Pepe Nero,
1 Pizzico Sale,
Brodo Di Carni Miste (pollo, Vitello),
1 Cucchiaio Farina','Impastate la ricotta con le uova, la mollica di pane ammollata e ben strizzata, il pecorino, un pizzico di sale e una macinatina di pepe nero. Fate con l''impasto delle minuscole polpette che sistemerete via via in un vassoio. Spolverate di farina e mettetele in frigorifero. Appena pronto il brodo sgrassatelo e versatelo in una pentola sul fuoco. Al momento di passare in tavola, immergete le polpettine di ricotta nel brodo ben caldo e spegnete il fuoco. Servite in ciotoline individuali di terracotta, calcolando cinque-sei polpettine a persona',763);
INSERT INTO "ricette" VALUES (19466,'Polpette Di Rognone','Carne','Vitello',4,' -','4 Fette Vitello,
1 Rognone Di Vitello,
4 Pezzetti Prosciutto Affumicato,
1/2 Bicchiere Cognac,
2 Petti Di Pollo Lessati,
4 Carote,
2 Porri,
3 Cipolle,
4 Gambi Sedano,
60 G Burro,
1000 G Fagiolini,
2 Cucchiai Panna,
Pepe','Tagliate le verdure a pezzi e mettetele in una padella con il burro e lasciate cuocere per 45 minuti. Tagliate il rognone in 4 parti. Insaporite le fette di vitello con il pepe e su ogni pezzo di rognone mettete del prosciutto. Sistemate ogni pezzo di rognone dentro una fettina, arrotolatele e legatele. In una padella mettete 40 g di burro per rosolarci la carne e le verdure; lasciate cuocere 1 ora. Dopodichè aggiungete il cognac e date fuoco. Coprite la pentola e lasciate cuocere per 30 minuti aggiungendo un cucchiaio di panna. A parte cuocete i fagiolini. Quando il tutto è cotto passate le verdure nel frullatore mettendoci un cucchiaio di panna e di farina. Salate e pepate le verdure e servitele con le polpette.',3166);
INSERT INTO "ricette" VALUES (19467,'Polpette Di Sarde','Pesce','Sarde',4,'Luogo: Sicilia.','500 G Sarde,
100 G Uvetta Sultanina,
100 G Formaggio Pecorino,
200 G Farina,
Prezzemolo,
Olio D''oliva,
Sale,
Pepe,
50 G Pangrattato','Pulire le sarde, eliminando testa, coda e lisca. Tagliarle a pezzi e impastare con il pecorino grattugiato, l''uvetta, il prezzemolo tritato, il pangrattato, il sale e il pepe. Fare delle polpette, passarle nella farina e friggerle in olio bollente.',2663);
INSERT INTO "ricette" VALUES (19468,'Polpette Di Sgombro','Pesce','Sgombro',4,' -','400 G Polpa Di Sgombro,
30 G Burro,
1/2 Panino,
Noce Moscata,
Prezzemolo,
Farina,
Olio D''oliva,
Sale,
Pepe','Ammorbidite il burro e amalgamatelo con la polpa di sgombro frullata. Unite la mollica del panino bagnata e strizzata, il prezzemolo tritato, la noce moscata, sale e pepe. fate tante polpettine, passatele nella farina e friggetele in olio bollente.',2110);
INSERT INTO "ricette" VALUES (19469,'Polpette Di Spinaci','Contorno','Spinaci',4,' -','750 G Spinaci Freschi,
2 Uova,
Formaggio Parmigiano Grattugiato,
Noce Moscata,
Farina,
Pangrattato,
Olio D''oliva,
Burro,
Sale','Mondate e lavate gli spinaci, fateli stufare per 5/10 minuti, fino a che saranno teneri poi strizzateli e tritateli molto finemente. Metteteli sul fuoco con una noce di burro, salateli, mescolate e fateli asciugare bene. Trasferiteli in una terrina e lasciateli raffreddare un pò, quindi unite un uovo, 4 cucchiaiate di parmigiano, una grattata di noce moscata. Amalgamate il tutto e lasciate riposare in frigorifero per almeno mezz''ora. Passato il tempo indicato, ricavate dal composto tante polpettine tonde, man mano che le preparate passatele nella farina poi nell''uovo sbattuto e nel pangrattato. Friggetele in abbondante olio caldissimo e scolatele su della carta assorbente da cucina prima di servirle.',2889);
INSERT INTO "ricette" VALUES (19470,'Polpette Di Spinaci (2)','Contorno','Spinaci',4,' -','600 G Spinaci,
150 G Ricotta,
1 Cucchiaio Farina,
2 Uova,
Olio D''oliva,
1 Pizzico Sale,
Pepe','Mondare gli spinaci e lessarli. Strizzarli, tritarli e mescolarli con la ricotta sbriciolata, 1 cucchiaio di farina, un pizzico di sale e le uova. Con l''impasto fare delle polpettine rotonde, passarle nella farina e friggerle in abbondante olio ben caldo. Sgocciolarle e servirle subito.',1281);
INSERT INTO "ricette" VALUES (19471,'Polpette Di Spinaci (3)','Contorno','Spinaci',4,' -','300 G Pane Casereccio Raffermo,
Latte,
400 G Spinaci,
1 Cipolla,
Olio D''oliva Extra-vergine,
2 Uova,
70 G Formaggio Caciocavallo,
Sale Marino,
Pepe','Ammorbidire il pane nel latte. Cuocere a vapore gli spinaci e una volta tiepidi strizzarli e triturarli. Imbiondire la cipolla tritata nell''olio; unire gli spinaci, sale e stufare 5 minuti. In una zuppiera con mollica strizzata, spinaci, uova, sale, pepe, e formaggio a fiammifero fare un impasto consistente e farlo rassodare in frigo per 30 minuti. Ricavarne delle polpette e friggerle nell''olio d''oliva extra-vergine.',2167);
INSERT INTO "ricette" VALUES (19472,'Polpette Di Tacchino Alla Noce Moscata','Pollame','Tacchino',6,' -','600 G Fesa Di Tacchino,
Mollica Di Pane,
20 Cl Panna,
Farina,
Abbondante Noce Moscata Grattugiata,
Sale,
Olio D''oliva,
Burro','Tritate la carne, unite un po'' di mollica di pane precedentemente ammorbidita nella panna, salate, aggiungete abbondante noce moscata grattugiata, amalgamate. Formate con il composto delle polpettine e infarinatele leggermente. Scaldate due cucchiai d''olio e un po'' di burro, friggetevi le polpettine, prima a fuoco vivo e poi dolce per quindici minuti: devono riuscire morbide, ma con una leggera crosticina dorata. Sgocciolatele con la schiumarola, asciugatele su carta da cucina e servitele.',3595);
INSERT INTO "ricette" VALUES (19473,'Polpette Di Tonno','Antipasto','Tonno Sott''olio',4,' -','250 G Tonno Sott''olio Sgocciolato,
200 G Ricotta,
1 Uovo,
30 G Formaggio Parmigiano Grattugiato,
50 G Pangrattato,
1 Rametto Timo,
Olio D''oliva,
Sale','Tritate le foglie di timo e mettetele in una ciotola, unite la ricotta, l''uovo e il parmigiano. Amalgamate il tutto con un cucchiaio di legno. Passate al mixer il tonno, unitelo al miscuglio e regolate di sale. Formate delle polpette della dimensione di una noce, passatele man mano nel pangrattato premendole leggermente al centro. Scaldate 2 cucchiai d''olio in una padella antiaderente , unite le polpette e cuocetele per circa 10 minuti finché saranno dorate.',2005);
INSERT INTO "ricette" VALUES (19474,'Polpette Di Tonno Fresco','Contorno','Tonno Fresco',4,' -','500 G Tonno Fresco,
70 G Formaggio Pecorino Siciliano Grattugiato,
2 Uova,
30 G Pinoli,
30 G Uvetta Sultanina,
Prezzemolo,
Salvia,
Pangrattato,
Farina,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Tagliare al coltello il tonno e incorporarvi formaggio, uova, pinoli, uvetta ammollata e strizzata, prezzemolo tritato, sale, pepe. Ricavarne delle polpettine e passarle prima nella farina, poi nel pangrattato, quindi friggerle nell''olio dopo avervi fritto e tolto alcune foglie di salvia. Servire le polpettine sopra un letto di misticanza di primavera.',3244);
INSERT INTO "ricette" VALUES (19475,'Polpette Di Verza','Contorno','Verza',4,' -','1 Verza,
250 G Arrosto Di Maiale (o Arrosto Di Manzo),
40 G Salame,
20 G Formaggio Grana,
Pangrattato,
1 Trito Di Aglio E Prezzemolo,
1 Uovo,
Olio D''oliva Extra-vergine,
40 G Pancetta,
Cipolla,
Carota,
Vino Bianco Secco,
Brodo,
Sale,
Pepe','Scottare in acqua bollente 8 foglie di verza private della costa; asciugarle su un canovaccio. Impastare salame e carne trita, aglio, prezzemolo, formaggio grattugiato, uovo, pangrattato. Fare grosse palline, avvolgerle nella verza e legarle. Rosolarle in un soffritto di olio e aromi; sfumare col vino e cuocere.',2655);
INSERT INTO "ricette" VALUES (19476,'Polpette Divine','Antipasto','Tonno Sott''olio',4,' -','150 G Tonno Sott''olio,
100 G Ricotta,
3 Uova Sode,
1 Cucchiaio Succo Di Limone,
1 Cucchiaio Capperi,
Maionese,
30 G Burro,
Sale,
Pepe','Servendovi di un mixer, frullate insieme un uovo sodo sgusciato, il tonno (precedentemente fatto sgocciolare), i capperi, la ricotta, il burro ammorbidito e il succo di limone. Successivamente, insaporite e pepate il composto ottenuto e disponetelo in una ciotola capiente che conserverete in frigorifero per circa 15 minuti. Nel frattempo, sgusciate le altre uova, tagliatele a fette e sistematele su un piatto piano da portata, dopodichè, tirate fuori dal frigorifero il composto e con il palmo delle mani create delle palline e appoggiatele sulle fettine di uova sode. Per finire, decoratele con riccioli di maionese e servite. Suggerimento: per rendere più carino il vostro piatto, potreste foderarlo con foglie grandi di lattuga e aggiungere sui riccioli di maionese, capperi o fettine di olive nere snocciolate.',1437);
INSERT INTO "ricette" VALUES (19477,'Polpette Fiammeggianti','Dessert','Panna Pasticciera',6,' -','15 Bignè Vuoti,
700 G Panna Pasticciera,
300 G Cioccolato Di Copertura,
6 Uova,
Vino Marsala,
Cognac,
Zucchero,
1 1/2 Fogli Colla Di Pesce','Per prima cosa mettiamo in ammollo la colla di pesce in acqua fredda. Prepariamo allora lo zabaglione: bisogna sbattere i tuorli delle uova in una casseruola insieme a sei cucchiaiate di zucchero lavorando bene il tutto fino ad ottenere un composto omogeneo e cremoso. In seguito, aggiungiamo 10 cucchiaiate di Marsala continuando a mescolare. Mettiamo la casseruola a bagnomaria sul fuoco a fiamma bassissima non smettendo mai di mescolare. Dovremo mescolare fino a quando il composto sarà divenuto ben gonfio, stando attenti a non farlo bollire! A questo punto è necessario strizzare la colla di pesce dall''acqua per incorporarla allo zabaglione caldo. Consigliamo di utilizzare una frusta affinché la colla di pesce possa sciogliersi perfettamente. Versiamo quindi lo zabaglione in una terrina, lasciandolo raffreddare, mescolando di tanto in tanto. Versiamo lo zabaglione in una tasca di tela munita di una bocchetta a foro liscio, foriamo leggermente sul lato ogni bignè, e, finalmente, li riempiamo con lo zabaglione. Tagliamo il cioccolato a piccole scaglie e mettiamolo a bagnomaria in un tegamino per farlo fondere. Prendiamo un bignè alla volta e immergiamo la parte superiore nel cioccolato. Montiamo la panna e distribuiamola su di un piatto di portata con una tasca di tela facendo attenzione a lasciare sei zone vuote tutt''attorno al piatto un po'' distanti l''una dall''altra. Distribuiamo i bignè sulla panna a due a due e mettiamone tre al centro. Riempiamo gli spazi vuoti con dello zucchero semolato. Al momento di servire il dolce in tavola, colpo da maestro, versiamo su ogni porzione di zucchero qualche goccia di Cognac e... diamo fuoco al tutto!',7071);
INSERT INTO "ricette" VALUES (19478,'Polpette Fritte Di Fave, Ceci E Lenticchie','Contorno','Fave',4,'Luogo: Medio Oriente.','Fave E Ceci,
Lenticchie,
Cipolla,
Aglio,
Cumino,
Coriandolo Secco Macinato,
Sale,
Pepe,
Olio Per Friggere','Scolare i legumi, passarli o frullarli (molto fini). Aggiungere cipolla, aglio, prezzemolo e le spezie. Amalgamare, impastare e lasciar riposare per qualche ora. Fare delle palline appiattite e friggerle nell''olio bollente. Scolare e far asciugare su carta assorbente. Servire con tahina',1280);
INSERT INTO "ricette" VALUES (19479,'Polpette Impanate','Carne','Manzo',4,' -','600 G Manzo Tritato,
1 Panino Raffermo,
1 Uovo,
50 G Pangrattato,
Latte,
Prezzemolo,
Sale,
Pepe,
Olio D''oliva,
1 Spicchio Aglio','Mettere il panino a bagno nel latte. Mettere in una ciotola la carne e unire l''uovo, il pane strizzato e sbriciolato, l''aglio e il prezzemolo tritati, sale e pepe. Amalgamare bene tutti gli ingredienti. Formare delle polpettine e passarle nel pangrattato. Friggerle in abbondante olio bollente.',2023);
INSERT INTO "ricette" VALUES (19480,'Polpette In Foglia Di Limone','Carne','Carne',4,' -','400 G Carne Macinata,
1 Limone,
50 G Formaggio Parmigiano,
1/2 Spicchio Aglio,
5 Foglie Limone,
1 Cucchiaio Olio D''oliva Extra-vergine,
Sale,
Pepe','Preparare le polpette amalgamando la carne con aglio, sale, pepe, parmigiano, olio e grattugiandovi 1/2 buccia di limone chiudendole a portafoglio. Metterle in una teglia, cospargere con olio e infornare a 200 gradi per 15 minuti.',937);
INSERT INTO "ricette" VALUES (19481,'Polpette Norvegesi','Carne','Manzo',6,'Luogo: Norvegia. Calorie: 477.','4 Fette Pane Bianco,
20 Cl Latte Caldo,
500 G Polpa Di Manzo Macinata,
250 G Polpa Di Maiale Macinata,
2 Uova Sbattute,
1 Cucchiaino Noce Moscata,
1 Cucchiaino Pepe,
1 Cucchiaino Mix Di Spezie Per Arrosti,
250 G Cipolla A Fettine,
Sale,
Olio D''oliva,
Per La Salsa:,
4 Cucchiai Burro,
4 Cucchiaini Farina,
2 Cucchiai Brodo Di Manzo,
60 Cl Acqua Bollente','In una terrina, fate ammorbidire il pane nel latte. Aggiungere tutti gli altri ingredienti e mescolate bene. Dividere in piccole polpette. Fate dorare le polpette in una padella antiaderente, aggiungete un po'' di olio per non farle attaccare. Preriscaldate il forno a circa 250 gradi. Preparate la salsina di fondo: unire il burro, la farina e il brodo che avrete mescolato con l''acqua bollente. Mettete le polpette in una pirofila da forno, versate la salsina e cuocete per circa 30 minuti.',4192);
INSERT INTO "ricette" VALUES (19482,'Polpette Piccanti','Carne','Maiale',4,' -','200 G Lonza Di Maiale,
200 G Fesa Di Tacchino,
200 G Manzo,
1 Uovo,
4 Peperoni,
1 Peperoncino,
1/2 Cucchiaino Paprica,
Aglio,
Brodo,
4 Cucchiai Pangrattato,
5 Cucchiai Olio D''oliva,
Sale,
Pepe,
Prezzemolo Tritato','Tritare tutte le carni, metterle in una terrina e unire 4 cucchiai di pangrattato, l''uovo, il prezzemolo tritato, la paprica, sale e pepe. Formare delle polpette e friggerle in 5 cucchiai di olio con l''aglio schiacciato e il peperoncino. Aggiungere i peperoni lavati e tagliati a listarelle, bagnare poco alla volta con il brodo caldo e cuocere per 15-20 minuti. Prima di servire eliminare il peperoncino e l''aglio.',2078);
INSERT INTO "ricette" VALUES (19483,'Polpette Pinolate','Carne','Vitello',4,' -','400 G Carne Di Vitello,
3 Uova,
100 G Pinoli,
1/2 Bicchiere Vino Bianco,
Farina,
Olio D''oliva,
Sale,
Pepe,
Pangrattato','Rosolate la carne con poco olio e sfumate col vino bianco. Passate al tritatutto, unite 1 uovo intero, sale, pepe e pinoli. Fate tante polpette, infarinatele, passatele nelle 2 uova sbattute e nel pangrattato. Friggetele in olio ben caldo e servite.',2646);
INSERT INTO "ricette" VALUES (19484,'Polpette Vegetali Al Formaggio','Contorno','Patate Gialle',4,' -','500 G Patate Gialle,
1 Uovo,
120 G Formaggio Salato Morbido Friulano,
4 Cipollotti,
1 Ciuffo Finocchietto,
3 Cucchiai Olio D''oliva Extra-vergine,
Sale,
Peperoncino In Polvere,
1 Spruzzatina Succo Di Limone','Lessare le patate e ancora calde pelarle e passarle al passapatate. Alla purea ottenuta incorporare dadini di formaggio, cipollotti affettati, finocchietto tritato, uovo sbattuto, una spruzzatina di succo di limone. Salare leggermente e amalgamare. Formare delle polpettine e infarinarle. Friggerle nell''olio.',1661);
INSERT INTO "ricette" VALUES (19485,'Polpette Verdi','Carne','Manzo',4,' -','350 G Carne Di Manzo Magra Tritata,
120 G Tonno In Olio D''oliva,
2 Uova,
4 Cucchiai Pangrattato,
2 Cucchiai Formaggio Parmigiano Grattugiato,
1 Pugno Spinaci Lessi Strizzati E Tritati,
Prezzemolo,
Sale,
Pepe','Riunite in una ciotola la carne, il tonno sminuzzato, le uova, gli spinaci, 2 cucchiai di pangrattato e il formaggio; da ultimo unite un cucchiaio di prezzemolo tritato. Amalgamate bene gli ingredienti, aggiustate di sale e pepe. Formate delle palline e passatele nel pangrattato rimasto, pressandole un poco in modo da farle diventare ovali. Cuocete le polpettine in olio e una noce di burro facendole dorare da entrambe le parti, poi spruzzatele con vino bianco e... buon appetito.',1331);
INSERT INTO "ricette" VALUES (19486,'Polpettine Ai Piselli E Prosciutto Cotto','Carne','Maiale',4,' -','300 G Macinato Di Maiale,
100 G Prosciutto Crudo,
750 G Passato Di Pomodoro,
1 Lattina Piselli Fini,
1 Uovo,
Pangrattato,
Farina,
Prezzemolo,
1 Spruzzata Paprica Dolce,
Vino Bianco,
1 Cipolla,
Margarina','Preparate il soffritto con la cipolla e la margarina, aggiungete una spruzzata di paprica dolce e, quando la cipolla è brunita, aggiungete mezzo bicchiere di vino. Fate evaporare. Versate nella padella il pomodoro e i pisellini sgocciolati, salate a gusto. Mentre il pomodoro e i piselli si cuociono preparate le polpettine. Mettete il prosciutto (io ne ho tagliata una fettona di circa 1 hg da un trancetto e poi tagliata a dadoni) nel robot e sminuzzatelo con le lame, aggiungete il macinato e continuate a sminuzzare. Poi ancora nell''ordine il prezzemolo, l''uovo e il pangrattato. Una volta che gli ingredienti si sono ben amalgamati preparate le polpettine e passatele sulla farina, a me le polpettine piacciono piccole, circa 2 o 3 cm di diametro, ad altri piacciono più grosse, dipende dai gusti. Mettete le polpette in padella ed attendete la fine della cottura. Occhio a non cuocerle troppo se no diventano eccessivamente dure.',3165);
INSERT INTO "ricette" VALUES (19487,'Polpettine Al Forno','Carne','Vitello',4,' -','400 G Carne Di Vitello Magra,
2 Cucchiai Besciamella,
70 G Burro,
1 Uovo,
2 Cucchiai Formaggio Parmigiano Grattugiato,
Pinoli,
Basilico,
Pepe,
Sale,
1 Rametto Salvia','Tritare la carne, aggiungere la besciamella, il parmigiano, l''uovo e il basilico tritato. Salare e pepare, mescolare bene, formare tante polpettine rotonde e su ciascuna infilare 4 pinoli. Scaldare il burro con la salvia e unire le polpettine. Mettere in forno, bagnare ogni tanto con il burro di cottura e ritirarle dorate.',1769);
INSERT INTO "ricette" VALUES (19488,'Polpettine Al Gorgonzola','Carne','Carne',4,' -','400 G Carne Tritata,
2 Cipolle,
Burro,
1 Panino (mollica),
Latte,
2 Uova,
Formaggio Grana,
Sale,
Pepe,
Farina,
Olio D''oliva,
Formaggio Gorgonzola','Mescolare la carne con le cipolle tritate e soffritte nel burro, la mollica di pane bagnata nel latte e ben strizzata, le uova, una manciata di grana, sale e pepe. Formare delle polpettine, infarinarle, farle dorare in olio e burro, poi adagiare su ogni polpetta un pezzetto di gorgonzola, coprire e cuocere ancora per 5 minuti.',3415);
INSERT INTO "ricette" VALUES (19489,'Polpettine Al Limone','Carne','Vitello',8,' -','600 G Polpa Di Vitello,
5 Uova,
150 G Formaggio Parmigiano Grattugiato,
Succo Di Limone,
Olio D''oliva,
Sale','Macinare molto fine la carne cruda; mescolarla con le uova, il formaggio, sale e abbondante succo di limone. Mettere sul fuoco un pentolone pieno d''acqua e, quando l''acqua bolle, mettere sopra una padella con l''olio. Quando l''olio e` ben caldo far scivolare dentro a cucchiaiate l''impasto in modo che si formino delle polpettine. Farle dorare e servirle.',2296);
INSERT INTO "ricette" VALUES (19490,'Polpettine Al Sugo','Carne','Manzo',4,' -','300 G Polpa Di Manzo Tritata,
100 G Salsiccia,
4 Rametti Prezzemolo,
2 Spicchi Aglio,
2 Cucchiai Formaggio Parmigiano Grattugiato,
1/2 Panino Raffermo,
1 Uovo,
1 Cipolla,
500 G Pomodori,
Olio D''oliva,
1 Rametto Basilico,
Sale,
Pepe','Ponete la carne trita in una terrina, unite la salsiccia sminuzzata, il prezzemolo e l''aglio tritati finemente, il Parmigiano grattugiato e il pane raffermo fatto ammorbidire nell''acqua, strizzato e spezzettato, quindi mescolate gli ingredienti con un cucchiaio di legno. Quando saranno ben amalgamati, legate tutto con un uovo sbattuto a parte con una presa di sale e una macinata di pepe. Ricavate dal composto ottenuto tante piccole polpette rotonde, modellandole con le mani leggermente inumidite. A questo punto versate in una padella abbondante olio d''oliva, fatelo scaldare e friggetevi le polpettine a fuoco moderato per 4-5 minuti, o fino a quando saranno dorate in modo uniforme. Al termine, toglietele dal recipiente con una schiumarola e passatele su un foglio di carta assorbente, per eliminare l''unto in eccesso. Mondate la cipolla, tritatela con la mezzaluna e fatela soffriggere in una casseruola con un paio di cucchiai d''olio, a calore moderato per circa 5 minuti. Unite i pomodori pelati e passati al setaccio, insaporite con sale, pepe e basilico e lasciate cuocere a fuoco dolce per una decina di minuti. Trascorso il tempo indicato, mettete le polpettine nella casseruola con la salsa e proseguite la cottura per altri 15 minuti. Servite le polpettine e il loro sugo insieme a una polenta fumante, oppure utilizzatele come condimento per la pastasciutta.',1914);
INSERT INTO "ricette" VALUES (19491,'Polpettine Al Vino','Carne','Carne',4,' -','400 G Carne Macinata,
50 Cl Vino Rosso,
1 Cipolla,
Poco Olio D''oliva,
Farina,
Sale','Con la carne formare delle palline grandi come nocciole. Passarle nella farina. Soffriggere la cipolla tritata in poco olio, versare le polpettine nel tegame e farle dorare. Coprirle con il vino e far cuocere a fuoco basso. Aggiustare di sale a fine cottura.',1488);
INSERT INTO "ricette" VALUES (19492,'Polpettine Alla Belga','Carne','Manzo',4,'Luogo: Belgio.','600 G Manzo Tritato,
2 Cipolle,
75 G Burro,
Vino Bianco,
Prezzemolo,
Farina,
Brodo,
Sale,
Pepe','Tritare una cipolla, unirla alla carne, salare, pepare e mescolare. Formare delle polpettine e infarinarle. Fondere il burro in un tegame, adagiarvi le polpette e cuocerle. Quando saranno pronte levarle dal fuoco e tenerle in caldo. Nello stesso burro far appassire la cipolla tritata, bagnarla con vino e brodo, unire il prezzemolo finemente tritato e far addensare. Versare questa salsina bollente sulle polpettine e servire subito.',1762);
INSERT INTO "ricette" VALUES (19493,'Polpettine Alle Olive','Carne','Carne',4,' -','500 G Carne Macinata,
3 Salsicce,
2 Uova,
200 G Formaggio Parmigiano Grattugiato,
1 Bicchiere Latte Freddo,
Sale,
Noce Moscata,
200 G Olive Nere Tritate,
Pangrattato,
Abbondante Olio Per Friggere,
Per Guarnire:,
Alcune Fettine Carota,
Alcuni Bastoncini Di Sedano,
Alcuni Tocchetti Di Pomodoro,
Alcune Olive','Mescolare insieme tutti gli ingredienti (tranne l''olio), ottenendo così un impasto morbido. Formare quindi delle polpettine e rosolarle in padella con abbondante olio. Disporle su 1 piatto da portata e guarnirle con fettine di carota, bastoncini di sedano, tocchetti di pomodoro e qualche oliva.',4541);
INSERT INTO "ricette" VALUES (19494,'Polpettine Aromatizzate All''anice','Carne','Vitella',4,' -','300 G Macinato Di Vitella,
1 Uovo,
30 G Formaggio Parmigiano,
2 Fette Pane In Cassetta,
4 Pomodori,
Prezzemolo,
Basilico,
Semi Di Anice,
Insalata Rucola,
Sale,
Pepe,
Olio D''oliva Extra-vergine','Preparare le polpette impastando tutti gli ingredienti e cuocere per 3-4 minuti. Frullare la rucola con olio e sale. Frullare a parte i pomodori con olio fino a montarli. Sistemare nel piatto le salse a mezzaluna e al centro una piramide di polpettine calde.',1656);
INSERT INTO "ricette" VALUES (19495,'Polpettine Aromatizzate All''arancia','Carne','Carne',4,' -','200 G Carne Macinata,
1 Tuorlo D''uovo,
1 Pugno Pangrattato,
10 Cl Latte,
Prezzemolo,
Farina,
Per La Salsa:,
Vino Bianco,
Succo D''arancia,
Per La Pasta Fresca Per Uccelletti:,
Farina,
Burro,
Pangrattato,
Acqua Calda,
Sale','Formare con gli ingredienti delle palline, infarinarle e cuocerle in padella con burro e olio. Aggiungere vino e succo d''arancia. Cuocere 15 minuti con del peperoncino. Servirle con gli uccelletti preparati con farina, burro, pangrattato, acqua calda; fare dei pezzetti con la pasta ottenuta e condirli con burro, prezzemolo e parmigiano.',2363);
INSERT INTO "ricette" VALUES (19496,'Polpettine Con Mandorle E Pinoli','Carne','Manzo',4,' -','400 G Carne Di Manzo Tritata,
1 Cipollina,
30 G Pinoli,
30 G Mandorle,
2 Uova,
1 Panino,
Latte,
Formaggio Grattugiato,
Farina,
Burro,
Sale,
Pepe','In una ciotola mettete la carne, i pinoli e le mandorle tritati, il panino ammorbidito nel latte e strizzato, il formaggio grattugiato, la cipolla tritata, sale, pepe e le uova. Impastate e col composto fate delle polpettine. Passatele nella farina e cuocetele nel burro caldo per 4/5 minuti.',2779);
INSERT INTO "ricette" VALUES (19497,'Polpettine Con Verdure E Pappardelle','Carne','Manzo',2,' -','150 G Pappardelle,
Sale,
1 Cucchiaio Olio D''oliva,
Per Le Polpettine:,
200 G Carne Di Manzo,
1 Cipolla,
Sale,
Pepe Bianco,
1/2 Cucchiaio Senape Di Digione,
1 Cucchiaio Erbe Tritate (salvia, Prezzemolo),
Olio D''oliva,
Per Il Sugo Al Pomodoro:,
1 Scatola Pelati,
2 Cucchiai Olio D''oliva,
1 Spicchio Aglio,
1 Cucchiaio Concentrato Di Pomodoro,
1 Cucchiaio Ketchup,
Sale,
1 Rametto Basilico,
Verdure:,
1 Zucchina,
1 Melanzana Lunga,
1 Testa Aglio,
2 Cucchiaio Olio D''oliva','Passate la polpa di manzo al tritacarne (disco medio) e raccogliete il ricavato in una terrina. Tritate finemente la cipolla e fatela rosolare in un tegamino con un cucchiaio d''olio, per 5 minuti a fuoco dolce. Unite il soffritto alla carne trita, quindi aggiungete le erbe tritate, la senape, il sale necessario e una macinata di pepe e mescolate con cura in modo da amalgamare bene gli ingredienti. Ricavate dal composto ottenuto tante polpettine rotonde delle dimensioni di una noce e friggetele in una padella con olio bollente, a fuoco medio, fino a quando saranno ben dorate da ogni lato. Preparate la salsa di pomodoro: in una padella fate scaldare un cucchiaio d''olio, mescolatevi il concentrato di pomodoro, unite l''aglio e lasciate insaporire il tutto per qualche minuto a calore moderato. Aggiungete la ketchup e una presa di sale, date una mescolata, infine mettete nella padella anche i pelati passati al setaccio, il basilico e un altro cucchiaio d''olio. Fate cuocere la salsa a fuoco basso e a recipiente coperto fino a quando si sarà addensata, dopodichè passatela al setaccio. Mondate la zucchina e la melanzana, private quest''ultima della buccia, quindi tagliate entrambi gli ortaggi a fettine sottili nel senso della lunghezza. Pelate la testa d''aglio e affettatene sottilmente alcuni spicchi, lasciando interi gli altri. Fate rosolare in un tegame con l''olio d''oliva la zucchina e la melanzana, a calore moderato per pochi istanti, in modo che non prendano colore, quindi levatele dal recipiente e mettetevi l''aglio. Lasciatelo soffriggere dolcemente fino a quando sarà ben dorato. Fate lessare le pappardelle in una pentola con abbondante acqua salata, a cui avrete aggiunto un cucchiaio d''olio, scolatele al dente e ponetele nella padella col sugo di pomodoro. Unite anche le polpettine e fate scaldare tutt''assieme per pochi minuti. Distribuite la preparazione in due piatti individuali insieme alle verdure e servite.',3135);
INSERT INTO "ricette" VALUES (19498,'Polpettine Della Nonna','Carne','Manzo',6,' -','300 G Polpa Di Manzo,
100 G Prosciutto Cotto,
3 Cucchiai Formaggio Parmigiano Grattugiato,
Sale,
Pepe,
1 Grattatina Noce Moscata,
2 Cucchiai Pinoli,
2 Cucchiai Uvetta Sultanina,
1 Panino (mollica),
3 Cucchiai Aceto Di Vino,
10 Cl Brodo,
100 G Pangrattato,
3 Cucchiaini Farina,
3 Cucchiaini Senape,
1 Limone,
1 Uovo Intero,
3 Tuorli D''uovo,
Olio Per Friggere','Passate al tritacarne la polpa di manzo e il prosciutto cotto e raccogliete il ricavato in una terrina. Unitevi il Parmigiano grattugiato, una grattatina di noce moscata, l''uvetta, fatta rinvenire in acqua tiepida e strizzata, i pinoli, la mollica del panino, bagnata con il brodo, il sale necessario e una macinata di pepe. Mescolate con cura gli ingredienti, quindi legate il tutto con un tuorlo. Ricavate dal composto ottenuto tante piccole polpette rotonde e di dimensioni uniformi, passatele nell''uovo sbattuto con sale e pepe e nel pangrattato e friggetele in una padella con olio bollente. Quando sono ben dorate toglietele dal recipiente usando una schiumarola e passatele su un foglio di carta assorbente per eliminare l''unto in eccesso, dopodichè adagiatele in un piatto di portata. Ponete la senape in una casseruolina, scioglietela con l''aceto, quindi unitevi la farina mescolata con tre cucchiai d''acqua, regolate di sale e sbattete il composto con un cucchiaio di legno. Incorporatevi i tuorli rimasti e il succo di 1/2 limone e fate scaldare la salsa a fuoco dolce, senza farle prendere il bollore. Versate la salsa calda sulle polpettine, guarnite con il restante limone e servite.',3246);
INSERT INTO "ricette" VALUES (19499,'Polpettine Di Carne','Carne','Carne',1,'Ricetta adatta a: bambini piccoli.','1 Vasetto Carne Omogeneizzata (vasetti Da 80 G),
1/2 Tuorlo D''uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Poco Grissino Grattugiato','Versare in una scodellina il contenuto di un vasetto da 80 g di carne omogeneizzata, aggiungere 1/2 tuorlo d''uovo, un cucchiaio di parmigiano grattugiato ed un po'' di grissino grattugiato per ottenere un composto piuttosto sodo. Lavorare con la forchetta e formare quattro polpettine. Disporle su un piatto ricoperto da un altro e farle cuocere a vapore per 15 minuti circa sopra una casseruola piena di acqua in ebollizione.',281);
INSERT INTO "ricette" VALUES (19500,'Polpettine Di Carne (2)','Carne','Carne',1,'Ricetta adatta a: bambini piccoli.','1 Omogeneizzato Di Carne,
1/2 Tuorlo D''uovo,
1/2 Albume D''uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Poco Grissino Grattugiato','Versare in una scodellina il contenuto di un omogeneizzato di carne: aggiungere mezzo tuorlo e mezzo albume, un cucchiaio di parmigiano grattugiato ed un pò di grissino sbriciolato per ottenere un composto piuttosto sodo. Lavorare bene con la forchetta e formare 4 polpettine. Disporle su un piatto ricoperto da un altro e far cuocere a vapore per 15 minuti circa sopra una casseruola piena a metà di acqua in ebollizione.',330);
INSERT INTO "ricette" VALUES (19501,'Polpettine Di Ceci E Verdure','Antipasto','Ceci',4,'Preparazione: 20 minuti. Cottura: 25 minuti.','1 Scatola Ceci Lessati,
1 Falda Peperone Rosso,
1/2 Zucchina,
1 Carota Piccola,
1 Pezzetto Porro (la Parte Bianca),
1 Spicchio Aglio,
2 Cucchiai Olio D''oliva,
2 Uova,
Pangrattato,
Sale,
Olio Per Friggere','Riducete tutte le verdure mondate a dadini minuscoli (altrimenti, se non siete abbastanza brave e pazienti con il coltello, potete grattugiarle con il disco a fori piccoli). Soffriggete lo spicchio di aglio tagliato in due in una padella dove avrete scaldato l''olio. Quando l''aglio inizia a dorare, toglietelo e mettete le verdure. Lasciatele cuocere a fuoco moderato per circa 10 minuti, mescolando ogni tanto per assicurarvi una cottura uniforme, quindi spegnete. Schiacciate i ceci al passaverdure e raccogliete la purea in una ciotola. A parte, sbattete le uova. Unite circa 2 cucchiai di uovo sbattuto nella ciotola con i ceci. Salate leggermente e aggiungete le verdure. Mescolate e unite alcune cucchiaiate di pangrattato. Alla fine, avrete un impasto abbastanza consistente. Passate le polpettine prima nell''uovo sbattuto poi nel pangrattato e friggetele in abbondante olio ben caldo. Scolatele, mettetele su carta assorbente e servitele tiepide.',2556);
INSERT INTO "ricette" VALUES (19502,'Polpettine Di Fave','Contorno','Fave',6,' -','350 G Fave Secche Decorticate,
6 Cipollotti Freschi,
1 Spicchio Aglio,
Olio D''oliva,
Sale,
Pepe,
Prezzemolo,
1 Cucchiaino Cumino In Polvere,
1 Cucchiaino Coriandolo In Polvere,
1 Cucchiaino Lievito Per Pizza In Polvere','Tenere a bagno le fave per 24 ore. Scolarle e frullarle ottenendo un composto granuloso. Tritare finemente i cipollotti, schiacciare l''aglio e unirli al composto di fave con il cumino, il coriandolo, il lievito e il prezzemolo tritato. Aggiustare di sale e pepe, mescolare, coprire e far riposare per 1 ora. Formare delle polpettine grandi come ciliegie e lasciarle riposare per circa 15 minuti. Friggerle in olio molto caldo. Servire come antipasto.',1948);
INSERT INTO "ricette" VALUES (19503,'Polpettine Di Manzo','Carne','Manzo',1,'Ricetta adatta a: bambini piccoli.','1 Omogeneizzato Di Manzo,
1/2 Tuorlo D''uovo,
1/2 Albume D''uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Poco Grissino Grattugiato','Versare in una scodellina il contenuto di un omogeneizzato di manzo: aggiungere mezzo tuorlo e mezzo albume, un cucchiaio di parmigiano grattugiato ed un pò di grissino sbriciolato per ottenere un composto piuttosto sodo. Lavorare bene con la forchetta e formare 4 polpettine. Disporle su un piatto ricoperto da un altro e far cuocere a vapore per 15 minuti circa sopra una casseruola piena a metà di acqua in ebollizione.',330);
INSERT INTO "ricette" VALUES (19504,'Polpettine Di Melanzane','Contorno','Melanzane',4,' -','3 Melanzane,
200 G Mollica Di Pane Di Farro,
60 G Formaggio Pecorino Sardo Grattugiato,
3 Spicchi Aglio,
1 Cipolla,
Basilico,
Semi Di Sesamo Tostati,
1 Uovo,
Latte,
Menta,
Sale Marino','Bagnare nel latte la mollica. Affettare le melanzane sbucciate; tenerle 1 ora sotto sale. Ridurle a dadini; rosolare con aglio e cipolla affettata sottile. Far stiepidire; unire mollica strizzata, uovo, sesamo, formaggio, basilico. Fare le polpette; disporle in una pirofila unta d''olio e cuocere in forno. Condire con salsa di yogurth o di pomodoro.',1161);
INSERT INTO "ricette" VALUES (19505,'Polpettine Di Miglio','Antipasto','Miglio Decorticato',4,' -','200 G Miglio Decorticato,
1 Cipolla,
1 Carota,
1 Zucchina,
1 Patata,
1 Pomodoro,
1 Melanzana,
Sesamo,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Lessate il miglio in mezzo litro di acqua bollente appena salata finché il cereale non avrà assorbito tutta l''acqua. In una casseruola preparate un soffritto di cipolla, aggiungetevi le verdure pulite e tagliate a pezzettini, salate, pepate e fate cuocere per 10 minuti. Impastate le verdure e il miglio, preparate 12 polpettine, passatele nel sesamo e cuocetele al vapore per 10 minuti.',1664);
INSERT INTO "ricette" VALUES (19506,'Polpettine Di Pesce','Pesce','Sogliola',4,' -','500 G Sogliola,
50 G Formaggio Grana Grattugiato,
50 G Pangrattato,
20 G Uvetta Sultanina,
20 G Pinoli,
1 Uovo,
Sale,
Pepe,
Olio D''oliva,
Prezzemolo,
Farina','Tritare il pesce, ben spinato, i pinoli e l''uvetta. Unire il grana, l''uovo, una manciata di prezzemolo tritato, il pangrattato, sale e pepe. Amalgamare bene gli ingredienti e aggiungere pangrattato se l''impasto dovesse essere troppo morbido. Formare delle palline e passarle nella farina. Friggerle in abbondante olio bollente e levarle con una schiumarola quando saranno dorate.',2003);
INSERT INTO "ricette" VALUES (19507,'Polpettine Di Pesce (2)','Pesce','Acciughe',4,'Luogo: Campania.','400 G Acciughe,
3 Tuorli D''uovo Sodo,
1 Cucchiaio Aceto Di Vino,
1 Cipollina,
Maionese,
Alcune Fettine Limone,
1 Pizzico Sale','Diliscate e pulite le acciughe, schiacciatele in modo da ottenere un impasto liscio, diluitelo con un cucchiaio di aceto. Unite i tuorli, la cipollina tritata, un pizzico di sale, amalgamate con la maionese e formate delle polpettine. Disponetele su un piatto e servitele con fettine di limone.',1134);
INSERT INTO "ricette" VALUES (19508,'Polpettine Di Pesce (3)','Pesce','Merluzzo',4,' -','400 G Merluzzo Bollito,
100 G Patate Bollite,
3 Uova,
200 G Farina,
Vino Bianco Frizzante,
Sale,
Pepe,
Noce Moscata,
Olio D''oliva','Preparare una pastella con 2 tuorli, la farina, 3 cucchiai di olio, sale e pepe. Aggiungere vino sufficiente per ottenere una pastella fluida poi amalgamare 2 albumi montati. Impastare il pesce con le patate, un uovo, sale, pepe e noce moscata tritata. Formare delle polpettine, passarle nella pastella e friggerle in abbondante olio ben caldo.',2100);
INSERT INTO "ricette" VALUES (19509,'Polpettine Di Pesce Alla Trevigiana','Pesce','Tonno',4,'Luogo: Veneto. Luogo: Treviso.','200 G Tonno Sott''olio,
4 Fette Pancarré,
1 Scalogno,
3 Uova,
3 Cespi Insalata Trevigiana,
3 Filetti D''acciughe,
1 Spicchio Aglio,
1 Pizzico Peperoncino,
Olio D''oliva,
Pangrattato,
Sale','Sbriciolate il tonno, unite la mollica del pancarré, lo scalogno tritato, due uova e il sale. Con il composto formate delle polpettine piatte; passatele nell''uovo sbattuto e salato, poi nel pangrattato. Disponetele in una teglia appena unta d''olio e cuocete a 220 gradi per un quarto d''ora. Lavate la trevigiana, tagliatela in quattro parti e grigliatela. Scaldate un po'' d''olio, rosolate l''aglio, toglietelo, mettete le acciughe tritate e un pizzico di peperoncino; mescolate e condite l''insalata. Servitela con le polpette.',2947);
INSERT INTO "ricette" VALUES (19510,'Polpettine Di Pesce Alla Tunisina','Pesce','Pesce',4,'Luogo: Tunisia.','500 G Polpa Di Pesce Lessato (palombo, Merluzzo, Dentice) Anche Surgelato,
4 Cucchiai Prezzemolo,
2 Cipolle,
4 Cucchiai Farina,
1 Uovo,
1/2 Cucchiaio Paprica Dolce,
1/2 Cucchiaio Semi Di Cumino,
1/2 Cucchiaino Pepe Nero,
Olio Di Semi Di Girasole,
Sale','Private la polpa dei pesce da eventuali lische, cartilagini e pelle; tritatela finemente e mettetela in una terrina con il prezzemolo e le cipolle entrambe tritate finemente, l''uovo, il pepe, la paprica, il cumino tritato e il sale. Amalgamate bene il tutto e formate delle piccole polpette; appiattitele leggermente e infarinatele con cura. Mettete abbondante olio nella padella e, quando sarà bollente, fatevi dorare uniformemente le polpette. Toglietele con la paletta, passatele sulla carta per fritti perché perdano l''eccesso di unto e servitele ben calde.',1580);
INSERT INTO "ricette" VALUES (19511,'Polpettine Di Polenta, Burro E Salvia','Contorno','Polenta Gialla',4,' -','500 G Polenta Gialla (o Polenta Bianca),
100 G Formaggio Gorgonzola Dolce,
100 G Formaggio Parmigiano Reggiano,
200 Cl Latte,
70 G Burro,
Abbondante Salvia','Far bollire la polenta nel latte leggermente salato. A cottura ultimata, mentre la polenta è calda, incorporare i 2 formaggi e mescolare accuratamente finché non si otterrà un composto omogeneo col quale si creeranno delle polpettine. Disporre tali polpette su una teglia antiaderente, o leggermente unta, irrorarle col burro, fuso a fuoco lento, insaporito con abbondante salvia tagliata a pezzettini e porre a gratinare finché non saranno ben dorate. Servire calde con un contorno di verdure stufate.',3746);
INSERT INTO "ricette" VALUES (19512,'Polpettine Di Polenta, Burro E Salvia (2)','Contorno','Polenta Bianca',4,' -','500 G Polenta Bianca,
100 G Formaggio Gorgonzola Dolce,
100 G Formaggio Parmigiano Reggiano,
200 Cl Latte,
70 G Burro,
Abbondante Salvia','Far bollire la polenta nel latte leggermente salato. A cottura ultimata, mentre la polenta è calda, incorporare i 2 formaggi e mescolare accuratamente finché non si otterrà un composto omogeneo col quale si creeranno delle polpettine. Disporre tali polpette su una teglia antiaderente, o leggermente unta, irrorarle col burro, fuso a fuoco lento, insaporito con abbondante salvia tagliata a pezzettini e porre a gratinare finché non saranno ben dorate. Servire calde con un contorno di verdure stufate.',3746);
INSERT INTO "ricette" VALUES (19513,'Polpettine Di Pollo','Pollame','Pollo',1,'Ricetta adatta a: bambini piccoli.','1 Omogeneizzato Di Pollo,
1/2 Tuorlo D''uovo,
1/2 Albume D''uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Poco Grissino Grattugiato','Versare in una scodellina il contenuto di un omogeneizzato di pollo: aggiungere mezzo tuorlo e mezzo albume, un cucchiaio di parmigiano grattugiato ed un pò di grissino sbriciolato per ottenere un composto piuttosto sodo. Lavorare bene con la forchetta e formare 4 polpettine. Disporle su un piatto ricoperto da un altro e far cuocere a vapore per 15 minuti circa sopra una casseruola piena a metà di acqua in ebollizione.',314);
INSERT INTO "ricette" VALUES (19514,'Polpettine Di Pollo (2)','Pollame','Pollo',1,'Ricetta adatta a: bambini piccoli.','50 G Petto Di Pollo,
1 Patata Piccola,
1 Cucchiaino Tuorlo D''uovo,
2 Cucchiaini Formaggio Parmigiano Grattugiato,
1/2 Cucchiaio Olio D''oliva Extra-vergine,
2 Foglie Salvia,
Sale','Ricetta adatta a un bambino dai 10 mesi in poi. Lessate la patata senza sbucciarla. Frullate il petto di pollo e unitevi la patata, pelata e schiacciata, il tuorlo d''uovo, il parmigiano e un pizzichino di sale. Mescolate bene il tutto quindi ungetevi leggermente le mani e formate delle palline delle dimensioni di una ciliegia. Versate l''olio in un piatto, deponetevi le palline, leggermente schiacciate, e distribuitevi le foglie di salvia spezzettate. Coprite il piatto con un coperchio, appoggiatelo sopra una pentola contenente acqua in ebollizione e lasciate cuocere le polpettine per circa un quarto d''ora, girandole una volta. Fatele leggermente intiepidire per consentire al piccolo ospite di afferrarle tranquillamente con le mani.',437);
INSERT INTO "ricette" VALUES (19515,'Polpettine Di Ricotta','Contorno','Ricotta',4,' -','150 G Ricotta Freschissima,
2 Tuorli D''uovo,
1 Albume D''uovo,
Pangrattato,
Sale,
Pepe,
80 G Tartufo Nero Di Norcia Grattugiato,
Olio D''oliva','In un recipiente, unite insieme: la ricotta, la chiara d''uovo montata a neve, il tartufo grattugiato e il pangrattato. Mescolate con cura fino ad ottenere un composto omogeneo e maneggevole e con il palmo delle mani, create delle polpettine che immergerete nell''uovo e che lascerete rotolare nel pangrattato (anch''esso insaporito con poco pepe e altro tartufo). Immergetele infine in olio ben caldo e friggetele fino a dorarle. In ultimo, adagiatele su un piatto piano da portata, ricoperto con fogli di carta assorbente per eliminare l''eccesso d''olio. Servitele subito calde e croccanti. Suggerimento: potreste spolverizzarle con scagliette sottili di tartufo nero prima di servirle.',1526);
INSERT INTO "ricette" VALUES (19516,'Polpettine Di Riso E Carciofi','Primo','Carciofi',4,' -','200 G Riso,
350 G Cuori Di Carciofi,
Prezzemolo,
1/2 Cipolla,
1 Bicchierino Vino,
50 Cl Brodo,
30 G Formaggio Parmigiano Grattugiato,
Burro,
Sale,
Pepe,
Pangrattato','Soffriggere la cipolla e il prezzemolo tritati nel burro, unire i carciofi a fettine, farli appassire, poi bagnarli col vino bianco. Sfumato il vino, unire il riso, sale e pepe. Portarlo a cottura aggiungendo poco alla volta il brodo. A fine cottura incorporare il parmigiano, far raffreddare il riso e farne delle polpettine. Passarle nel pangrattato e friggerle nel burro o margarina.',2206);
INSERT INTO "ricette" VALUES (19517,'Polpettine Di Rucola','Antipasto','Insalata Rucola',4,' -','40 G Insalata Rucola E Farina,
1 Formaggio Caprino,
100 G Ricotta,
2 Uova,
100 G Prosciutto Crudo,
Olio D''oliva,
Sale,
Pepe','Mescolare la ricotta con i tuorli, la farina, la rucola mondata, lavata e spezzettata con le mani, sale, pepe e gli albumi montati a neve densissima. Con l''aiuto di 2 cucchiai formare 20 polpette irregolari e friggerle in olio ben caldo. Scolarle su carta assorbente da cucina e salarle. Affettare il caprino in 10 parti e dividerle in 2. Tagliare a metà le fette di prosciutto, mettervi al centro 1 pezzetto di formaggio, arricciarle e fissarle alle polpette con 1 stecchino.',1682);
INSERT INTO "ricette" VALUES (19518,'Polpettine Di Tacchino','Pollame','Tacchino',1,'Ricetta adatta a: bambini piccoli.','1 Omogenaizzato Di Tacchino,
1/2 Tuorlo D''uovo,
1/2 Albume D''uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Poco Grissino Grattugiato','Versare in una scodellina il contenuto di un omogeneizzato di tacchino: aggiungere mezzo tuorlo e mezzo albume, un cucchiaio di parmigiano grattugiato ed un pò di grissino sbriciolato per ottenere un composto piuttosto sodo. Lavorare bene con la forchetta e formare 4 polpettine. Disporle su un piatto ricoperto da un altro e far cuocere a vapore per 15 minuti circa sopra una casseruola piena a metà di acqua in ebollizione.',360);
INSERT INTO "ricette" VALUES (19519,'Polpettine Di Tacchino (2)','Pollame','Tacchino',4,' -','500 G Petto Di Tacchino,
50 G Formaggio Parmigiano Grattugiato,
100 G Mortadella,
50 G Salamino Tipo Cacciatore,
1 Cipollina,
1 Manciata Prezzemolo,
1 Manciatina Mollica Di Pane,
30 G Burro,
1 Uovo,
Vino Bianco Secco,
Poca Farina,
Poco Latte,
Olio D''oliva,
Sale,
Pepe','Ammollate la mollica di pane nel latte. Tritate la carne di tacchino con la mortadella e il salamino. Mettete il trito in una terrina aggiungetevi il parmigiano, il prezzemolo tritato con la cipollina, il pane ammollato e ben strizzato dal latte, sale e pepe e impastate il tutto con l''uovo. Se vedete che il composto risulta troppo asciutto aggiungete ancora un tuorlo. Formate con il composto delle polpettine rotonde e schiacciatele leggermente con il palmo della mano. Mettete al fuoco una padella con il burro e qualche cucchiaiata di olio, adagiatevi, una accanto all''altra, le polpettine leggermente infarinate. Cuocetele a fuoco dolce, rigirandole spesso. Quando appariranno ben colorite, bagnatele con un po'' di vino bianco e portatele a completa cottura (impiegheranno a cuocere complessivamente 30 minuti), unendo eventualmente qualche cucchiaiata di brodo bollente. Servitele in tavola accompagnandole con dei finocchi scottati in acqua, insaporiti nel burro e spolverizzati di parmigiano.',2865);
INSERT INTO "ricette" VALUES (19520,'Polpettine Di Tacchino E Melanzane','Pollame','Tacchino',6,' -','20 Polpette Polpa Di Tacchino,
20 Fette Melanzane,
50 G Formaggio Parmigiano,
Salsa Di Pomodoro,
Basilico,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Friggete le fette di melanzane e mettetele su una carta assorbente. Friggete le polpettine di tacchino e mettetene una su ogni fetta di melanzana. Decorate con una foglia di basilico e fermate con uno stuzzicadenti. Disponetele in una pirofila unta, coprite con salsa di pomodoro spolverate con il parmigiano grattugiato e fate cuocere in forno caldo a 180 gradi per mezz''ora. Servite subito.',1945);
INSERT INTO "ricette" VALUES (19521,'Polpettine Di Tonno','Contorno','Tonno Sott''olio',4,' -','250 G Tonno Sott''olio,
2 Patate,
1 Uovo,
Farina,
Pangrattato,
Abbondante Olio D''oliva,
Sale','Lessare le patate sbucciate e tagliate a dadini, in acqua salata, per 15 minuti. Poi scolarle e passarle allo schiacciapatate, raccogliendole in una terrina. Frullare il tonno con il suo olio di conservazione e unirlo alle patate, poi aggiungere l''uovo e un po'' di farina per legare meglio l''impasto. Formare delle polpettine piatte, passarle nel pangrattato e friggerle in abbondante olio bollente.',2673);
INSERT INTO "ricette" VALUES (19522,'Polpettine Di Vitello','Carne','Vitello',1,'Ricetta adatta a: bambini piccoli.','1 Omogeneizzato Di Vitello,
1/2 Tuorlo D''uovo,
1/2 Albume D''uovo,
1 Cucchiaio Formaggio Parmigiano Grattugiato,
Poco Grissino Grattugiato','Versare in una scodellina il contenuto di un omogeneizzato di carne: aggiungere mezzo tuorlo e mezzo albume, un cucchiaio di parmigiano grattugiato ed un pò di grissino sbriciolato per ottenere un composto piuttosto sodo. Lavorare bene con la forchetta e formare 4 polpettine. Disporle su un piatto ricoperto da un altro e far cuocere a vapore per 15 minuti circa sopra una casseruola piena a metà di acqua in ebollizione.',314);
INSERT INTO "ricette" VALUES (19523,'Polpettine Di Vitello Con Riso','Carne','Vitello',4,' -','250 G Carne Macinata Di Vitello,
2 Pugni Riso,
1 Cucchiaino Paprica Dolce,
2 Cucchiai Pangrattato,
1 Tuorlo D''uovo,
1/2 Cipolla,
2 Spicchi Aglio,
5 Cl Passata Di Pomodoro,
1 Bicchiere Acqua,
Farina,
Olio D''oliva Extra-vergine,
Sale,
Pepe','Tritare la cipolla, 1 spicchio di aglio e impastarli con la carne assieme agli altri ingredienti e lavorare per 5 minuti. Mettere in padella olio, 1 spicchio di aglio, la passata di pomodoro e sale. Preparare le polpettine, porle in padella, salare, pepare e cuocere per 20 minuti.',1684);
INSERT INTO "ricette" VALUES (19524,'Polpettine Di Zucchine','Contorno','Zucchine',4,' -','4 Zucchine Grandi,
4 Uova,
Formaggio Parmigiano Grattugiato,
Formaggio Pecorino Grattugiato,
Prezzemolo Tritato,
Farina,
Olio D''oliva,
Sale,
Pepe','Spuntate le zucchine, lavatele con cura e asciugatele con della carta assorbente. Grattugiatele grossolanamente servendovi di un mixer da cucina e disponetele in una ciotola capiente. Sciacquate con cura anche il prezzemolo, asciugatelo con della carta assorbente e tritatelo nel mixer. Unitelo alle zucchine e aggiungete i formaggi, le uova sbattute, il sale e il pepe. Mescolate bene il tutto fino ad ottenere un composto cremoso ed omogeneo e gradualmente aggiungete anche la farina. Aiutandovi con il palmo delle mani, formate delle polpettine che friggerete in olio bollente per pochi minuti fino a dorarle. Giratele di tanto in tanto, servendovi di due forchette e a cottura ultimata disponetele su fogli di carta assorbente per eliminare l''olio in eccesso. Servitele subito calde e croccanti. Accorgimento: se il composto dovesse risultare troppo denso, diminuite la quantità di farina.',2301);
INSERT INTO "ricette" VALUES (19525,'Polpettine Dolci','Dessert','Ricotta',4,' -','150 G Ricotta,
2 Uova,
2 Cucchiai Zucchero,
2 Cucchiai Farina,
1 Cucchiaio Liquore All''arancia,
Pangrattato,
Zucchero A Velo,
1 Limone (scorza Grattugiata Finissima),
Olio D''oliva','Mescolare la ricotta con un uovo, il liquore, la farina e lo zucchero. Amalgamare molto bene e formare delle polpettine. Passarle nell''uovo battuto e nel pangrattato e friggerle in olio bollente finché non saranno dorate. Cospargerle con lo zucchero a velo e la scorza di limone grattugiata prima di servirle.',1736);
INSERT INTO "ricette" VALUES (19526,'Polpettine Dolci (2)','Dessert','Biscotti Amaretti',4,' -','150 G Biscotti Amaretti,
180 G Carote,
2 Tuorli D''uovo,
6 Biscotti Savoiardi,
1 Banana,
30 G Burro,
3 Cucchiai Liquore All''amaretto,
Zucchero A Velo','Lessare le carote e frullarle insieme ai savoiardi, gli amaretti, i tuorli, la banana e il liquore. Amalgamare bene il composto. Con le mani leggermente unte formate delle polpettine e farle dorare nel burro spumeggiante. Passarle su carta da cucina e servirle spolverizzate di zucchero a velo.',1836);
INSERT INTO "ricette" VALUES (19527,'Polpettine Dolci Di Pere Con Meringhette E Crema Al Rum','Dessert','Pera',4,' -','1 Pera,
10 Cl Latte,
30 G Burro,
30 G Farina,
1 Uovo,
3 Meringhette,
Per La Crema:,
1 Tuorlo D''uovo,
1 Cucchiaio Farina,
1 Cucchiaio Zucchero,
1 Bicchiere Latte,
Rum','Sciogliere in padella latte e burro, unire la farina e le uova intere. Cuocere il composto per pochi minuti a fuoco dolce, unirvi le pere tagliate a cubetti e ricavare delle polpettine dalla massa. Sbattere i tuorli con lo zucchero in una bowl a parte, unirvi la farina e il latte bollente versato a filo, quindi rapprendere sul fuoco dolce la crema per alcuni minuti. Unire il rum e lasciarla freddare. Servire la crema con le polpettine in una coppa, guarnire con le meringhette in purezza.',1300);
INSERT INTO "ricette" VALUES (19528,'Polpettine Golose','Carne','Manzo',1,'Ricetta adatta a: bambini piccoli.','3 Cucchiai Crema Di Cereali Misti,
1 Vasetto Omogeneizzato Di Manzo,
2 Cucchiaini Tuorlo D''uovo,
1 Cucchiaino Formaggio Parmigiano Grattugiato,
1 Cucchiaino Olio D''oliva Extra-vergine','Lavorate la crema di cereali con qualche cucchiaio di acqua calda, ottenendo un impasto piuttosto consistente; aggiungete poi, mescolando bene, l''omogeneizzato di manzo, l''uovo, l''olio e il parmigiano. Formate delle polpettine della grandezza di una noce e ponetele su un piatto coperto che appoggerete sopra un pentolino di acqua bollente. Cuocete a vapore per circa 15 minuti.',527);
INSERT INTO "ricette" VALUES (19529,'Polpettine In Agrodolce Con Curry','Carne','Manzo',2,' -','150 G Carne Macinata Di Manzo,
150 G Carne Macinata Di Maiale,
Farina Di Grano Duro,
1000 G Mele Rosse,
1 Mazzo Cipollina Fresca,
1 Goccio Brandy,
Curry,
Mollica Di Pane','Preparare le polpettine con la mollica di pane bagnata, la carne macinata, sale e la farina. Grattugiare le mele e metterle a cuocere in una padella con olio e cipollina. Una volta imbiondite, unirvi le polpettine, aggiungendo un po'' di curry e acqua per non farle attaccare. Prima di toglierle dal fuoco, versarvi un goccio di brandy.',1590);
INSERT INTO "ricette" VALUES (19530,'Polpettine In Brodo','Primo','Panino',4,' -','100 G Spinaci,
1 Uovo,
1 Panino (mollica),
2 Foglie Salvia,
1 Manciata Prezzemolo,
Poca Scorza Di Limone,
Brodo,
Formaggio Grana Grattugiato,
Burro,
Pangrattato,
Sale','Tritare finemente prezzemolo, spinaci, salvia, buccia di limone e mollica. Lavorare a crema una noce di burro con una presa di sale, unire l''uovo, amalgamare e poi unire il trito di erbe e pane. Se il composto non fosse consistente aggiungere un po'' di pangrattato. Ricavare tante piccole polpettine e cuocer- le nel brodo per 5 minuti. Servire con grana.',1923);
INSERT INTO "ricette" VALUES (19531,'Polpettine In Salsa Verde','Carne','Carne',4,' -','600 G Carne Tritata,
60 G Ricotta,
300 G Patate Farinose,
Formaggio Parmigiano Grattugiato,
4 Uova,
Aromi Per Il Brodo,
Prezzemolo,
Maggiorana,
Olio D''oliva,
Burro,
Sale,
Pepe','Rosolate la cipolla in olio e burro, unite la carne e fatele prendere colore, poi spegnete, aggiungete le uova il pangrattato, il sale e il pepe, il prezzemolo tritato, la ricotta, le foglioline di maggiorana sminuzzata e una abbondante dose di parmigiano. Fate lessare nel frattempo le patate. Una volta cotte, passatele al mulinetto e aggiungetele al composto preparato in precedenza. Amalgamate bene, poi stendete l''impasto su di un telo, dategli la forma di un salame, chiudetelo in maniera molto energica ai due poli, e fatelo bollire per circa due ore immergendolo in acqua fredda con aromi per brodo. Una volta cotto, sgocciolatelo e fatelo raffreddare prima di aprire il telo. Affettatelo e disponetelo su di piatto di portata accompagnandolo con salsa verde fredda.',3164);
INSERT INTO "ricette" VALUES (19532,'Polpettine In Teglia','Carne','Manzo',4,'Luogo: Lazio.','250 G Polpa Di Manzo Tritata,
250 G Ricotta,
2 Uova,
2 Manciate Formaggio Grana Grattugiato,
Pangrattato,
Brodo Vegetale,
1 Cucchiaio Prezzemolo Tritato,
Noce Moscata,
Sale,
Pepe','Impastate la carne con un uovo, una manciata di grana, sale pepe e noce moscata a piacere, unendo anche il pangrattato necessario a ottenere un composto consistente. Ricavatene tante polpettine, lessatele nel brodo bollente per 5 minuti, quindi scolatele con un mestolo forato. Mescolate la ricotta con l''uovo e il grana rimasti, sale e pepe a piacere. In una teglia versate un dito di brodo, sistematevi le polpettine, distribuitevi sopra l''impasto di ricotta, poi ancora uno strato di polpettine. Spolverizzate la superficie con pangrattato, quindi passate la teglia in forno e cuocete per una decina di minuti sotto il grill. Infine profumate con il prezzemolo e servite.',1493);
INSERT INTO "ricette" VALUES (19533,'Polpettine Miste','Carne','Manzo',4,'Luogo: Svezia.','200 G Carne Di Manzo Macinata,
100 G Maiale Magro Macinato,
100 G Carne Di Vitello Macinata,
30 G Pangrattato,
3 Bicchieri Latte Caldo,
1 Cipolla Tritata Finemente,
Burro,
1 Cucchiaio Aneto,
1 Uovo,
Sale,
Pepe','Mischiare insieme 200 g di carne macinata di manzo, 100 g di maiale magro macinato, 100 g di carne di vitello macinata, 30 g di pangrattato ammorbidito in 3 bicchieri di latte caldo per 2 ore, 1 cipolla tritata finemente e dorata in 30 g di burro, 1 cucchiaio di aneto, 1 uovo, sale, pepe. Amalgamare bene l''impasto e ricavarne polpette da friggere nel burro caldo finché sono ben dorate su entrambi i lati.',1679);
INSERT INTO "ricette" VALUES (19534,'Polpettine Piccanti','Carne','Manzo',4,' -','300 G Carne Di Manzo Tritata,
200 G Carne Di Maiale Tritata,
1 Cipolla,
1 Uovo,
1 Spicchio Aglio,
1/2 Peperone,
1 Fetta Pane,
Peperoncino In Polvere,
Prezzemolo,
Sale,
Pangrattato,
Olio D''arachidi','Tritare tutte le verdure molto finemente e farle rosolare in olio. Spolverizzarle con il peperoncino e farle raffreddare. Mescolare i 2 tipi di carne, unire la mollica di pane ben sbriciolata, l''uovo, le verdure ed amalgamare a lungo gli ingredienti. Preparare delle polpettine grandi come noci, passarle nel pangrattato e friggerle nell''olio caldo ma non bollente finché saranno dorate. Servirle subito.',2253);
INSERT INTO "ricette" VALUES (19535,'Polpettine Semplici','Carne','Carne Tritata',4,' -','300 G Carne Tritata,
1 Panino,
50 G Formaggio Grana Grattugiato,
1/2 Bicchierino Latte,
1 Uovo,
Prezzemolo Tritato,
6 Pomodori Da Sugo,
1/2 Cipolla,
Olio D''oliva,
Sale','Bagnare il pane nel latte, ridurlo in poltiglia e unirlo alla carne tritata, al grana, all''uovo e al prezzemolo. Salare e amalgamare bene. Formare con il composto di carne delle polpettine da porre in una teglia da forno con 1/2 cipolla tritata, i pomodori a pezzi e poco olio. Salare e cuocere in forno a 180 gradi per 40 minuti circa.',1596);
INSERT INTO "ricette" VALUES (19536,'Polpettine Semplici (2)','Carne','Carne Tritata',4,' -','300 G Carne Tritata,
1 Panino,
50 G Formaggio Grana Grattugiato,
1/2 Bicchiere Latte,
1 Uovo,
Prezzemolo Tritato,
6 Pomodori Da Sugo,
1/2 Cipolla,
Olio D''oliva,
Sale','Bagnare il pane nel latte, ridurlo in poltiglia e unirlo alla carne tritata, al grana, all''uovo e al prezzemolo sminuzzato. Salare e amalgamare bene. Formare con il composto di carne delle polpettine da porre in una teglia da forno con 1/2 cipolla tritata, i pomodori a pezzi, poco olio. Salare e cuocere in forno a 180 gradi per 40 minuti circa.',1652);
INSERT INTO "ricette" VALUES (19537,'Polpettine Tonno E Ricotta','Antipasto','Tonno',4,' -','400 G Tonno,
300 G Ricotta,
2 Uova,
Farina,
2 Cucchiai Formaggio Parmigiano Grattugiato,
2 Cucchiai Prezzemolo Tritato,
Sale,
Pepe','Impastare tutti gli ingredienti tranne la farina ,in cui, passeremo le polpette. Friggere in olio caldo e servire.',2106);
INSERT INTO "ricette" VALUES (19538,'Polpettine Ubriache','Carne','Vitello',4,' -','400 G Carne Tritata Di Vitello,
50 Cl Vino Rosso,
1 Cipolla,
Olio D''oliva,
Farina,
Sale','Formare delle palline con la carne e infarinarle. Tritare la cipolla e farla dorare in olio caldo, unire le polpettine, salarle e farle rosolare. Coprirle con il vino e portare a cottura, unendo altro vino se si dovessero asciugare troppo.',1788);
INSERT INTO "ricette" VALUES (19539,'Polpettine Vegetali','Contorno','Farro',4,' -','300 G Farro In Chicchi,
1 Trito Di Prezzemolo E Aglio,
2 Uova,
60 G Formaggio Parmigiano Grattugiato,
Sale,
Pepe','Lavare sotto l''acqua corrente 300 g di farro in chicchi, scolarlo, coprirlo in una terrina con acqua fredda e lasciarlo a bagno per 12 ore. Cuocerlo poi per 30 minuti nella sua acqua, scolarlo e frullarlo. Unire al passato un trito di prezzemolo e aglio, 2 uova, 60 g di parmigiano grattugiato, sale e pepe. Ricavare dall''impasto delle palline, passarle nel pangrattato e friggerle in olio caldo. Metterle a perdere l''unto su carta assorbente da cucina e servirle su un letto di insalata verde.',490);
INSERT INTO "ricette" VALUES (19540,'Polpettine Vietnamite','Carne','Maiale',4,'Luogo: Vietnam. Preparazione: 20 minuti. Cottura: 20 minuti.','400 G Carne Di Maiale Magra Tritata,
1 Cipollotto,
2 Spicchi Aglio,
2 Albumi D''uovo,
3 Cm Radice Di Zenzero Fresca,
Sale,
Pepe','Pelate l''aglio e il pezzetto di zenzero. Spremete l''aglio con l''apposito attrezzo e tritate molto finemente lo zenzero. Mondate il cipollotto e sminuzzatelo. Trasferite tutto in una ciotola e unitevi la carne tritata; impastate i vari ingredienti con una forchetta. Aggiungete a poco a poco gli albumi leggermente sbattuti e continuate a mescolare con cura. Alla fine, è preferibile lavorare l''impasto con le mani. Unite quindi fino a 10 cl d''acqua gelata, un cucchiaio per volta, mescolando, sempre con le mani. Alla fine, salate e pepate. Formate delle polpettine e deponetele su un piatto ben oleato. Lessate le polpette in acqua bollente salata e cuocetele per 3 minuti dopo che sono venute a galla. Sgocciolatele e infilatele, a tre a tre, su spiedini di legno. 10 minuti prima di servire, fatele dorare da tutti i lati sotto il grill del forno oppure sulla griglia del barbecue.',1165);
INSERT INTO "ricette" VALUES (19541,'Polpettone','Carne','Manzo',6,' -','400 G Wurstel,
240 G Manzo Tritato,
200 G Patate,
1 Uovo,
100 G Formaggio Groviera,
30 G Burro,
1 Cipolla,
1 Cucchiaio Senape,
20 Cl Panna,
Sale,
Pepe','Lessare le patate, sbucciarle e schiacciarle. Tagliare a dadini i wurstel. Mescolare carne, patate, wurstel, uovo e il groviera tagliato a julienne. Salare, pepare e mettere il composto in uno stampo imburrato. Coprire con un foglio di alluminio imburrato e infornare a 200 gradi per 1 ora. Far appassire la cipolla tritata nel burro, unire la panna e la senape e amalgamare. Versare questa salsina sulle fette di polpettone.',3167);
INSERT INTO "ricette" VALUES (19542,'Polpettone Ai Funghi','Carne','Manzo',6,' -','700 G Polpa Di Manzo Maremmano Macinata,
500 G Funghi Porcini,
2 Uova,
Noce Moscata,
Salvia,
Rosmarino,
Olio D''oliva Extra-vergine,
Sale,
Pepe,
Aglio,
Prezzemolo,
Brodo,
Mollica Di Pane','Imbiondire aglio ed erbe nell''olio; brasarvi i funghi con poco brodo. Mescolare carne, uova, prezzemolo, mollica, sale, spezie. Spianare il composto su una pellicola. Aiutandosi con questa arrotolarlo; a metà sistemare i funghi nel senso della lunghezza e arrotolare mettendo in forma. Rosolare, poi cuocere bagnando col brodo.',2042);
INSERT INTO "ricette" VALUES (19543,'Polpettone Al Cognac','Carne','Maiale',4,'Preparazione: 30 minuti.','30 G Polpa Di Maiale Tritata Con La Ricotta,
1 Uovo,
2 Cucchiai Formaggio Parmigiano Grattugiato,
5 Cucchiai Cognac,
Burro,
Noce Moscata,
Sale,
Pepe','Impastare la polpa di maiale tritata con la ricotta, un uovo, due
cucchiai di formaggio parmigiano grattugiato un po'' di sale, pepe e noce moscata (abbastanza perché se ne senta il sapore). Legate molto bene questi ingredienti, quindi date al composto la forma di un polpettone. Spruzzatelo di cognac e mettetelo in un tegame in cui avrete precedentemente fatto rosolare il burro. Rigirate ogni tanto facendo ben attenzione che non si attacchi al fondo del tegame e spruzzate, durante la cottura, dell''altro cognac, un liquore che si amalgama molto bene con la ricotta e con la carne di maiale. Questo polpettone può anche essere utilizzato come piatto forte per un .... sostanzioso pic-nic di montagna.',1559);
INSERT INTO "ricette" VALUES (19544,'Polpettone Al Forno','Carne','Manzo',6,' -','500 G Polpa Di Manzo Macinata,
100 G Prosciutto Cotto (fette Da 100 G),
100 G Lingua Salmistrata,
4 Cucchiai Formaggio Grana Grattugiato,
1 Tazza Latte,
50 G Burro,
4 Cucchiai Olio D''oliva,
2 Uova,
1 Rametto Prezzemolo,
1 Cipolla,
1 Panino Raffermo,
50 G Pangrattato,
1 Grattatina Noce Moscata,
Sale,
Pepe,
Piselli Al Burro,
1 Cipollotto Novello','Sminuzzate il panino raffermo e fatelo ammorbidire in una terrina con il latte, quindi scolatelo e strizzatelo bene, conservando il latte che rimane. In un''altra terrina ponete la polpa di manzo, il grana, la lingua e il prosciutto tritati, unite le uova intere, il latte utilizzato prima, il prezzemolo tritato, il pane ammorbidito, il sale necessario, una macinata di pepe e la noce moscata. Mescolate bene gli ingredienti fino a quando avrete ottenuto un composto il più possibile omogeneo; rovesciatelo sul piano di lavoro inumidito e modellatelo, dandogli la tipica forma allungata del polpettone, quindi passatelo più volte nel pangrattato in modo che ne resti ricoperto. Fatto ciò, ponete l''olio e il burro in una pirofila e fate scaldare sul fuoco, unite la cipolla tritata finemente e lasciatela appassire a calore molto moderato. Prima che il soffritto prenda colore, mettete nel recipiente anche il polpettone e fatelo rosolare per 6-7 minuti a calore moderatamente vivace, rigirandolo delicatamente da tutte le parti. Passate la pirofila nel forno già caldo (180 gradi) e lasciate cuocere per 30 minuti. Al termine, estraete la pirofila dal forno e lasciate riposare per qualche minuto il polpettone a temperatura ambiente, quindi trasferitelo sul piatto di portata, circondatelo con i piselli al burro, guarnite con il cipollotto tagliato ad anelli sottili e servite.',4132);
INSERT INTO "ricette" VALUES (19545,'Polpettone Al Forno (2)','Carne','Manzo',4,' -','400 G Carne Di Manzo Macinata,
4 Fette Pancarré,
1 Bicchiere Succo Di Pomodoro,
1 Cipolla Tritata,
1 Cucchiaio Prezzemolo Tritato,
2 Uova,
Sale,
Pepe,
Per Lo Stampo:,
Burro','Togliere la crosta al pane e tagliarlo a dadolini. Riunire in una terrina la carne, il pane, il succo di pomodoro, le uova sbattute, la cipolla, il prezzemolo, il sale e il pepe. Mescolare e sistemare in uno stampo unto. Mettere in forno già caldo a 180 grad